googleapis/google-cloud-cpp

google/cloud/bigtable/table_admin.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10179)
=> cleanup(bigtable): use implicit default ctor

google/cloud/pubsub/doc/pubsub-main.dox, google/cloud/storage/doc/storage-main.dox
The samples to override the authentication defaults were chosen for simplicity, not to represent the best practices for authentication. This changes the Doxygen landing pages for `storage` and `pubsub` to provide better guidance and links to best practices.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10184)
=> doc: better guidance for authentication samples

generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc
As RestClient::Get does not accept a payload, any simple fields in the request proto that are not part of the path need to be added as query parameters. This is especially important for List methods that support pagination.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10190)
=> impl(generator): determine url query parameters for GET rpcs

google/cloud/doc/guac.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10193)
=> doc(common): add overview section

google/cloud/storage/doc/storage-options.dox, google/cloud/storage/options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10200)
=> doc(storage): create page for configuration options

google/cloud/bigtable/doc/bigtable-options.dox, google/cloud/bigtable/options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10197)
=> doc(bigtable): create page for configuration options

google/cloud/pubsub/doc/pubsub-options.dox, google/cloud/pubsub/options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10198)
=> doc(pubsub): create page for configuration options

google/cloud/grpc_error_delegate.cc, google/cloud/grpc_error_delegate_test.cc, google/cloud/internal/log_wrapper_helpers.cc, google/cloud/internal/status_payload_keys.cc, google/cloud/internal/status_payload_keys.h, google/cloud/internal/status_payload_keys_test.cc, google/cloud/spanner/internal/status_utils.cc, google/cloud/spanner/internal/status_utils_test.cc
CMake can automatically create Windows DLLs if we don't use *data* symbols in the library.  This may unblock some folks trying to support DLLs.
Fixes #10205
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10212)
=> fix(common): avoid globals for easier DLLs

cmake/CompileProtos.cmake, cmake/EnableWerror.cmake, cmake/FindgRPC.cmake
We require CMake >= 3.10, any workarounds for CMake < 3.10 are no longer needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10216)
=> cleanup: remove workarounds for older CMake versions

generator/generator_config.textproto, google/cloud/logging/internal/logging_service_v2_auth_decorator.cc, google/cloud/logging/internal/logging_service_v2_auth_decorator.h, google/cloud/logging/internal/logging_service_v2_connection_impl.cc, google/cloud/logging/internal/logging_service_v2_connection_impl.h, google/cloud/logging/internal/logging_service_v2_logging_decorator.cc, google/cloud/logging/internal/logging_service_v2_logging_decorator.h, google/cloud/logging/internal/logging_service_v2_metadata_decorator.cc, google/cloud/logging/internal/logging_service_v2_metadata_decorator.h, google/cloud/logging/internal/logging_service_v2_stub.cc, google/cloud/logging/internal/logging_service_v2_stub.h, google/cloud/logging/logging_service_v2_client.cc, google/cloud/logging/logging_service_v2_client.h, google/cloud/logging/logging_service_v2_connection.cc, google/cloud/logging/logging_service_v2_connection.h, google/cloud/logging/mocks/mock_logging_service_v2_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10194)
=> feat(logging): generate `AsyncWriteLogEntries()`

ci/cloudbuild/builds/lib/quickstart.sh, ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile, ci/cloudbuild/triggers/demo-rockylinux-9-ci.yaml, ci/cloudbuild/triggers/demo-rockylinux-9-pr.yaml, ci/generate-markdown/generate-packaging.sh, doc/packaging.md
Fixes #10124
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10215)
=> ci: add demo build for Rocky Linux 9

google/cloud/spanner/client.h, google/cloud/spanner/integration_tests/data_types_integration_test.cc, google/cloud/spanner/samples/postgresql_samples.cc, google/cloud/spanner/samples/samples.cc
Add tests and samples for GOOGLE_STANDARD_SQL "THEN RETURN" and POSTGRESQL "RETURNING".
Note that `Client::ExecuteQuery()` can now execute a DML statement with a returning clause.
Previously we added support for `RowStream::RowsModified()` (#10102), which is now used here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10233)
=> feat(spanner): tests and samples for DML RETURNING

google/cloud/google_cloud_cpp_rest_internal.bzl, google/cloud/google_cloud_cpp_rest_internal.cmake, google/cloud/internal/curl_rest_client.cc, google/cloud/internal/curl_rest_client.h, google/cloud/internal/oauth2_minimal_iam_credentials_rest.cc, google/cloud/internal/rest_client.h, google/cloud/internal/rest_options.h, google/cloud/rest_options.h
This adds a user visible set of RestOptions for use with REST transport. These are based on the system parameters found at https://cloud.google.com/apis/docs/system-parameters. If we need to add additional options from these parameters, we can do so later as they are needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10240)
=> impl(rest): add user facing RestOptions

ci/generate-markdown/update-library-landing-dox.sh
Note that no documentation changes. That is because the only services that would be affected are Bigtable and Spanner Admin. The dox for those libraries are handwritten; not maintained by `checkers`.
Applied to `speech`, we see the endpoints (which, admittedly, look pretty dumb)
And the samples:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10242)
=> ci: inject nested samples, endpoints

ci/cloudbuild/builds/clang-tidy.sh
To be honest, I am not sure what this does.
<hr />
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10244)
=> cleanup: use C++14 for clang-tidy

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/admin/samples/CMakeLists.txt
These samples were never built with cmake. We run them with bazel in the `integration-production` build.
We still do not run them, but at least they are built in `clang-tidy`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10247)
=> samples(spanner): build admin samples with cmake

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/admin/samples/CMakeLists.txt
These samples were never built with cmake. We run them with bazel in the `integration-production` build.
We still do not run them, but at least they are built in `clang-tidy`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10246)
=> samples(bigtable): build admin samples with cmake

google/cloud/rest_options.h
`Options{}.set<ServerTimeoutOption>(3.14)` creates a double not a float, which in turn results in a narrowing conversion warning. Change the option type to double as a quality of life improvement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10253)
=> impl(rest): change ServerTimeout type to match type of literals

google/cloud/google_cloud_cpp_common.bzl, google/cloud/google_cloud_cpp_common.cmake, google/cloud/google_cloud_cpp_common_unit_tests.bzl, google/cloud/internal/access_token.cc, google/cloud/internal/access_token.h, google/cloud/internal/access_token_test.cc, google/cloud/internal/credentials_impl.h
I think this will be handy in the implementation of external account credentials.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10258)
=> refactor(common): split `internal::AccessToken` struct

google/cloud/spanner/samples/samples.cc
The sample specification document was ambiguous about whether one of the FGAC tag names should be plural or not.  The one we chose lost the toss.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10266)
=> fix(spanner): tweak the tag name of a FGAC sample

ci/cloudbuild/builds/check-api.sh, ci/generate-markdown/generate-readme.sh
Run `abi-dumper; abi-compliance-checker` in parallel for each library. This reduces the run time of "check-api" (in a totally unscientific, one-off, "ninja: no work to do" test) from around 20m30s to about 7m30s.
Also take this opportunity to improve the output by discarding the noise ("cmake --install" messages, "missed type id" errors, etc.) and by including the elapsed time for each library.
On the latter front, the outliers are ...
```
bigtable completed in 4m2s
dialogflow_cx completed in 6m7s
dialogflow_es completed in 6m56s
```
where we can see that the "6m56" dominates the overall run time.
Fixes #10234
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1 …
=> ci: parallelize API report generation

google/cloud/internal/make_status.cc, google/cloud/internal/make_status.h, google/cloud/internal/make_status_test.cc, google/cloud/storage/internal/curl_request_builder.h, google/cloud/storage/internal/rest_request_builder.h
Motivated by #5915
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10271)
=> impl(common): helpers to create ErrorInfo

google/cloud/internal/error_metadata.h, google/cloud/internal/error_metadata_test.cc
TIL: the return type for `push_back()` changed between C++14 and C++17, I had to fix that, then add some tests, then I noticed the thing was not easy to test because it did not behave like a C++ collection, so I fixed that too.
Motivated by #5915 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10275)
=> impl(common): make `ErrorContext` a collection

google/cloud/internal/populate_grpc_options.cc
For backwards compatibility with the pre-Unified Credentials world we were calling `grpc::GoogleDefaultCredentials()` if `g::c::GrpcCredentialsOption` was not set. In many cases the option is not set, but `g::c::UnifiedCredentialsOption` is. If that is the case, the unified options are preferred. Calling
`grpc::GoogleDefaultCredentials()` produces spurious errors, and these credentials won't be used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10280)
=> fix(common): create default gRPC credentials only if needed

google/cloud/spanner/client.h, google/cloud/spanner/internal/defaults.cc, google/cloud/spanner/internal/defaults_test.cc, google/cloud/spanner/internal/metadata_spanner_stub_test.cc, google/cloud/spanner/internal/session_pool.h, google/cloud/spanner/internal/spanner_stub.h, google/cloud/spanner/samples/samples.cc
Raise the disfavor for `ConnectionOptions` and `SessionPoolOptions` arguments to `spanner::MakeConnection()` from @note to @deprecated.
Also removed some stale inclusions of `connection_options.h` and `session_pool_options.h`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10284)
=> doc(spanner): deprecate old MakeConnection() overloads

.github/workflows/external-account-integration.yml
We need integration tests for external account support. The existing CI systems run on Google infrastructure and therefore not suitable for these tests. GitHub Actions are a bit underpowered, but if we keep the number of tests in this builds small, and the caches are warm, the builds are fast enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10287)
=> ci: create build for external accounts integration

google/cloud/pubsub/internal/pull_ack_handler.cc, google/cloud/pubsub/internal/pull_ack_handler.h, google/cloud/pubsub/internal/pull_ack_handler_test.cc
For historical reasons, `ack()` and `nack()` errors are reported via the `ErrorInfo`. We need to use custom retry and backoff policies for them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10298)
=> impl(pubsub): use `ExactlyOnce` policies in `PullAckHandler`

google/cloud/doc/guac.dox
I made a pass trying to assume less about what the reader may know about authentication. Motivated by the incorrect magic for numbered items in Doxygen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10300)
=> doc: another pass on authentication components

BUILD.bazel, google/cloud/BUILD.bazel
Part of the work for #10283 
We will keep the flag internal until it does anything.
We verify the configuration, by breaking the build in the [Analysis Phase](https://bazel.build/run/build#analysis) if OpenTelemetry is not built with Abseil.
Now is the time to bikeshed the error message, and the target the error is attached to. (We could pick `//:common` instead.). Here is what an error looks like:
```
$ bazel build --//:experimental-open_telemetry //:common
ERROR: google-cloud-cpp/google/cloud/BUILD.bazel:45:11: configurable attribute "target_compatible_with" in //google/cloud:google_cloud_cpp_common_private doesn't match this configuration: OpenTelemetry must be built with Abseil. To fix this error, supply the `--@io_opentelemetry_cpp//api:with_abseil` flag to your build command.
This …
```
=> impl(otel): add experimental flag

google/cloud/pubsub/internal/subscriber_connection_impl.cc, google/cloud/pubsub/internal/subscriber_connection_impl.h, google/cloud/pubsub/internal/subscriber_connection_impl_test.cc
Note that this function is not yet in the base class. We can implement it and write a unit test first, keeping future PRs smaller.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10315)
=> impl(pubsub): add `SubscriberConnectionImpl::Pull()`

google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsub/google_cloud_cpp_pubsub.bzl, google/cloud/pubsub/integration_tests/subscriber_integration_test.cc, google/cloud/pubsub/internal/subscriber_connection_impl.cc, google/cloud/pubsub/internal/subscriber_connection_impl.h, google/cloud/pubsub/internal/subscription_session_test.cc, google/cloud/pubsub/pull_response.h, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscriber.cc, google/cloud/pubsub/subscriber.h, google/cloud/pubsub/subscriber_connection.cc, google/cloud/pubsub/subscriber_connection.h, google/cloud/pubsub/subscriber_connection_test.cc
This adds blocking pulls to the Pub/Sub public APIs. It also includes a minimal example, and an integration test.
Fixes #7187
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10317)
=> feat(pubsub): blocking pulls

.bazelrc
Part of the work for #10283
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10314)
=> ci(otel): enable otel by default in our project

ci/cloudbuild/builds/otel-disabled-bazel.sh, ci/cloudbuild/triggers/otel-disabled-bazel-ci.yaml, ci/cloudbuild/triggers/otel-disabled-bazel-pr.yaml
Part of the work for #10283 
I will add the trigger on Cloud Build after this PR goes through.
I decided not to run the integration tests, in this build. I think the unit tests will be sufficient.
Note that `//:experimental-open_telemetry` is set to false by default in all of our bazel builds. The plan of record is to change that, but in a separate PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10313)
=> ci(otel): add bazel build with otel disabled

google/cloud/internal/oauth2_authorized_user_credentials.cc, google/cloud/internal/oauth2_authorized_user_credentials.h, google/cloud/internal/oauth2_authorized_user_credentials_test.cc, google/cloud/internal/oauth2_compute_engine_credentials.cc, google/cloud/internal/oauth2_compute_engine_credentials.h, google/cloud/internal/oauth2_compute_engine_credentials_test.cc, google/cloud/internal/oauth2_refreshing_credentials_wrapper.cc, google/cloud/internal/oauth2_refreshing_credentials_wrapper.h, google/cloud/internal/oauth2_refreshing_credentials_wrapper_test.cc, google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/internal/oauth2_service_account_credentials.h, google/cloud/internal/oauth2_service_account_credentials_test.cc, google/cloud/storage/oauth2/refreshing_credentials_wrapper.cc, google/cloud/storage/oauth2/refreshing_credentials_wrapper.h
Prefer `internal::AccessToken` over the (now removed) `RefreshingCredentialsWrapper::TemporaryToken`. This will make it easier to replace `AuthorizationHeader()` with `GetToken()` in the `oauth2_internal::*Credentials` classes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10326)
=> refactor(common): prefer `internal::AccessToken`

google/cloud/pubsub/internal/subscriber_connection_impl.cc, google/cloud/pubsub/internal/subscriber_connection_impl.h, google/cloud/pubsub/internal/subscriber_connection_impl_test.cc, google/cloud/pubsub/internal/subscription_session.cc, google/cloud/pubsub/internal/subscription_session.h, google/cloud/pubsub/internal/subscription_session_test.cc, google/cloud/pubsub/options.h, google/cloud/pubsub/subscriber_connection.cc, google/cloud/pubsub/subscription.cc, google/cloud/pubsub/subscription.h
For historical reasons, a `pubsub::SubscriberConnection` has a subscription assigned to it.  With this change that subscription becomes the default, and one can provide an override via the `Options` argument.
Motivated by #10320 and #9171
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10327)
=> feat(pubsub): add option to override subscription

google/cloud/google_cloud_cpp_rest_internal.cmake, google/cloud/google_cloud_cpp_rest_internal_unit_tests.bzl, google/cloud/internal/curl_rest_client.cc, google/cloud/internal/oauth2_credentials.cc, google/cloud/internal/oauth2_credentials.h, google/cloud/internal/oauth2_credentials_test.cc, google/cloud/storage/internal/unified_rest_credentials.cc, google/cloud/storage/oauth2/authorized_user_credentials.h, google/cloud/storage/oauth2/compute_engine_credentials.h, google/cloud/storage/oauth2/service_account_credentials.h
The Storage library has multiple places where we call `oauth2_internal::Credentials::AuthorizationHeader()`.  I am planning to remove this function, but first I am introducing an adapter to change the code in a single place.
Part of the work for #10316
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10332)
=> refactor(common): use `AuthorizationHeader()` adapter

generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator.h, generator/internal/scaffold_generator_test.cc
These will help us generate scaffolding in the form we want. For context, the full change is [here](https://github.com/googleapis/google-cloud-cpp/compare/main...dbolduc:scaffold-update?expand=1), but I thought there was value in breaking down the changes a bit.
Hopefully I will never touch these helpers again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10336)
=> impl(scaffold): more intense parsing of product path

generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator_test.cc, google/cloud/vmwareengine/BUILD.bazel
Drop the `samples/{BUILD.bazel,CMakeLists.txt}`. Instead build the samples from the library's top level build files.
Support a `service.product_path()` like `google/cloud/foo/bar/baz/quux/v1alpha7` by using `LibraryPath(...)` to strip it to `google/cloud/foo/`.
The changes were based off of @devbww's #10278. These scaffolding changes were used to generate: https://github.com/dbolduc/google-cloud-cpp/tree/feat-paymentgateway-generate-library
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10338)
=> impl(scaffold): support new directory structure

doc/contributor/howto-guide-adding-generated-libraries.md, generator/standalone_main.cc
A pass on the howto add a new library docs, in light of https://github.com/googleapis/google-cloud-cpp/blob/main/doc/adr/2022-11-11-multiple-versions-of-GCP-service-in-one-library.md
The main change in the code is to compare `LibraryPath(product_path)` instead of the `product_path` directly. `LibraryPath()` has a trailinng `/`, so update the howto guide to match the expectation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10342)
=> doc: update howto generate library guide

google/cloud/storage/quickstart/WORKSPACE.bazel
Part of the work for #10208
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10350)
=> cleanup(storage): remove Bazel workspace name workaround

google/cloud/internal/external_account_integration_test.cc, google/cloud/internal/external_account_token_source_file.cc, google/cloud/internal/external_account_token_source_file_test.cc, google/cloud/internal/external_account_token_source_url.cc, google/cloud/internal/external_account_token_source_url.h, google/cloud/internal/external_account_token_source_url_test.cc, google/cloud/internal/oauth2_external_account_credentials.cc, google/cloud/internal/oauth2_external_account_credentials.h, google/cloud/internal/oauth2_external_account_credentials_test.cc, google/cloud/internal/oauth2_external_account_token_source.h
For external accounts we will need HTTP clients to exchange subject tokens into access tokens.  Some (most?) subject token sources also need HTTP clients. I think it will be simpler if the subject token sources receive a `RestClient` factory when asked to fetch a subject token, as opposed to binding a factory to the time when the source is created.
The downside is an extra (unused) parameter in the subject token sources that do not use HTTP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10349)
=> impl(common): more consistent HTTP clients

google/cloud/storage/oauth2/anonymous_credentials.h, google/cloud/storage/oauth2/authorized_user_credentials.h, google/cloud/storage/oauth2/compute_engine_credentials.h, google/cloud/storage/oauth2/credential_constants.h, google/cloud/storage/oauth2/credentials.h, google/cloud/storage/oauth2/google_application_default_credentials_file.h, google/cloud/storage/oauth2/google_credentials.h, google/cloud/storage/oauth2/refreshing_credentials_wrapper.h, google/cloud/storage/oauth2/service_account_credentials.h, google/cloud/storage/options.h
Update the Doxygen comments to mark every type, function, and even the complete namespace as deprecated.  In the next major release we will actually add the `[[deprecated]]` attribute, and (maybe) remove them in the major release following it.
Motivated by #10353 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10352)
=> doc(storage): document all `oauth2` names as deprecated

google/cloud/internal/external_account_integration_test.cc, google/cloud/internal/oauth2_external_account_credentials.cc, google/cloud/internal/oauth2_external_account_credentials.h
We need to parse and validate the external account configuration. Like other credential types, this configuration is a JSON object, received as a string.  The string itself is usually the contents of a file, but could be received from some other place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10354)
=> impl(common): parse external account configuration

google/cloud/internal/oauth2_external_account_credentials.cc, google/cloud/internal/oauth2_external_account_credentials_test.cc
Also add a bunch of missing tests.
Tested in https://github.com/coryan/google-cloud-cpp/actions/runs/3605392288
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10357)
=> fix(common): correctly parse external account configuration

google/cloud/internal/external_account_parsing.cc, google/cloud/internal/external_account_parsing.h, google/cloud/internal/external_account_parsing_test.cc, google/cloud/internal/oauth2_external_account_credentials.cc, google/cloud/internal/oauth2_external_account_credentials_test.cc
Soon we will need to parse another numeric field, time to create functions to do so.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10360)
=> refactor(common): functions for external account parsing

google/cloud/internal/oauth2_compute_engine_credentials.cc, google/cloud/internal/oauth2_compute_engine_credentials.h, google/cloud/internal/oauth2_compute_engine_credentials_test.cc
The implementation of `ComputeEngineCredentials` queries the metadata service to support self-signed URLs in `google/cloud/storage`. This query only needs to be done once, once the data is successfully retrieved it is not going to change as it is immutable in the GCE instance.
It also makes no sense to fail the token creation if the metadata query fails.
Part of the work for #10316
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10356)
=> impl: simplify `oauth2_internal::ComputeEngineCredentials`

google/cloud/internal/external_account_token_source_url.cc, google/cloud/internal/oauth2_authorized_user_credentials.cc, google/cloud/internal/oauth2_compute_engine_credentials.cc, google/cloud/internal/oauth2_external_account_credentials.cc, google/cloud/internal/oauth2_minimal_iam_credentials_rest.cc, google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/internal/rest_response.cc, google/cloud/internal/rest_response.h, google/cloud/internal/rest_response_test.cc, google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/internal/rest_client.cc
We often need to determine if a `RestResponse` contains a successful HTTP response or an error.  These helpers make the code easier to read and provide more consistent treatment of `RestResponse`. Callers that deviate from the standard success/failure codes can write their own functions (e.g., GCS treats 308 as "success" in some RPCs).
Part of the work for #5915 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10370)
=> refactor: success predicates for `rest_internal::RestResponse`

cmake/FindgRPC.cmake
We require gRPC >= 1.35, they are no longer needed and create problems elsewhere.
Fixes #10374
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10375)
=> fix: remove workarounds for gRPC < 1.30

google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/internal/oauth2_service_account_credentials.h, google/cloud/storage/internal/unified_rest_credentials.cc, google/cloud/storage/oauth2/service_account_credentials.cc, google/cloud/storage/oauth2/service_account_credentials.h, google/cloud/storage/oauth2/service_account_credentials_test.cc
The storage service does not support self-signed JWTs with scopes. With this change, self-signed JWTs will be automatically disabled when using the legacy `storage::oauth2::Credentials`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10369)
=> fix(storage): scopes should disable self-signed JWTs

google/cloud/internal/oauth2_minimal_iam_credentials_rest.cc, google/cloud/internal/oauth2_minimal_iam_credentials_rest.h, google/cloud/internal/oauth2_minimal_iam_credentials_rest_test.cc
We will need to parse the `GenerateAccessToken()` response in the external account implementation. This splits the parsing to a standalone function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10378)
=> refactor: split IAMCredentials `GenerateAccessToken()`

CMakeLists.txt, ci/cloudbuild/builds/lib/features.sh, google/cloud/google_cloud_cpp_common.cmake
Part of the work for #10283 
Third time's the charm...
Process `-DGOOGLE_CLOUD_CPP_ENABLE=experimental-opentelemetry`. Default some of our cmake builds (e.g. `clang-tidy`, `cmake-install`) to supply this option. The demo builds, for example, do not supply the option.
Note that we are not taking a dependency on `opentelemetry-cpp` in this PR. Nor are we advertising the feature yet.
Leave a placeholder for where the work will pick up. The builds will emit a little warning, but it's temporary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10381)
=> impl(otel): handle cmake build option

google/cloud/internal/oauth2_external_account_credentials.cc, google/cloud/internal/oauth2_external_account_credentials.h, google/cloud/internal/oauth2_external_account_credentials_test.cc
External accounts may require the service account impersonation flow to convert access tokens to access tokens associated with an specific service account.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10383)
=> impl: support impersonation for external accounts

google/cloud/BUILD.bazel, google/cloud/config.cmake.in, google/cloud/google_cloud_cpp_common.cmake, google/cloud/google_cloud_cpp_common_unit_tests.bzl, google/cloud/internal/opentelemetry_test.cc
Part of the work for #10283 
Take a dependency on `opentelemetry-cpp`, if requested, and the library is present. Maybe the build should just fail if OpenTelemetry is requested, but not found... cmake will warn.
Add a way to optionally `find_dependency` for `cmake --install` build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10387)
=> impl(otel): take dependency on library

ci/etc/oldest-deps/vcpkg.json
Testing with gRPC==1.33 is untenable, as we need features only available in gRPC==1.35. Unfortunately `vcpkg` skipped gRPC 1.34 and gRPC 1.35, so we need to skip forward. That opens a gap in our test coverage, but that is better than getting stuck without any ability to make progress.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10394)
=> ci: use gRPC 1.36.4 in `oldest-deps` build

.bazelrc, BUILD.bazel, ci/cloudbuild/builds/otel-disabled-bazel.sh, google/cloud/BUILD.bazel
I have settled on the convention that `opentelemetry` should be stylized as one word. (The OT repo does us no favors. It is `open-telemetry/opentelemetry-cpp`).
yes, the `bool_flag` is public, but it is experimental, and it doesn't do anything yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10396)
=> cleanup(otel): rename bazel flag

google/cloud/internal/credentials_impl.cc, google/cloud/internal/credentials_impl.h, google/cloud/internal/credentials_impl_test.cc, google/cloud/internal/external_account_integration_test.cc, google/cloud/internal/unified_grpc_credentials.cc, google/cloud/internal/unified_rest_credentials.cc, google/cloud/storage/internal/unified_rest_credentials.cc
Create the class derived from `google::cloud::Credentials` that will represent external accounts. These classes are mapped to the implementation using `google::cloud::internal::CredentialsVisitor`, which now supports external accounts. I change the integration test for external accounts to use the credentials to make a GCS request.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10391)
=> impl: support external accounts mapping

google/cloud/internal/oauth2_impersonate_service_account_credentials.cc, google/cloud/internal/oauth2_impersonate_service_account_credentials.h, google/cloud/internal/oauth2_minimal_iam_credentials_rest.cc, google/cloud/internal/oauth2_minimal_iam_credentials_rest.h, google/cloud/internal/oauth2_minimal_iam_credentials_rest_test.cc, google/cloud/internal/unified_rest_credentials.cc, google/cloud/internal/unified_rest_credentials_integration_test.cc
This will make things easier to test, I am thinking of `oauth2_internal::MapCredentials()` or `oauth2_internal::GoogleDefaultCredentials()`, which are not easy to mock at this time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10416)
=> impl(oauth2): use client factory for impersonation credentials

google/cloud/internal/curl_handle.h, google/cloud/internal/oauth2_credentials.h, google/cloud/internal/rest_response.h, google/cloud/pubsub/ack_handler.h, google/cloud/storage/bucket_cors_entry.h, google/cloud/storage/iam_policy.h, google/cloud/storage/internal/hash_function_impl.h, google/cloud/storage/internal/object_read_source.h
Without the change build fails on this week's `gcc-13` as:
In file included from google/cloud/internal/curl_handle.cc:15:
google/cloud/internal/curl_handle.h:107:8:
error: 'int32_t' in namespace 'std' does not name a type
107 |   std::int32_t GetResponseCode();
|        ^~~~~~~
`gcc-13` cleaned up `<string>` not to include `<cstdint>` for newer c++ standards. Hence the build failures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10421)
=> fix: add missing `<cstdint>` includes

google/cloud/internal/unified_rest_credentials.cc, google/cloud/internal/unified_rest_credentials.h, google/cloud/internal/unified_rest_credentials_test.cc
Add a variant of `rest_internal::MapCredentials()` that can be unit tested.  Use this to test all interesting code paths in the function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10426)
=> impl(oauth2): make `MapCredentials()` unit testable

.github/workflows/external-account-integration.yml, generator/CMakeLists.txt, generator/integration_tests/CMakeLists.txt, google/cloud/bigtable/benchmarks/CMakeLists.txt, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/google_cloud_cpp_rest_internal.cmake, google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake, google/cloud/testing_util/CMakeLists.txt, google/cloud/testing_util/google_cloud_cpp_testing_grpc.cmake
The CMake targets need to be unique across the whole project. That is trivial for libraries, but tests often have conflicting names. A `foo_test.cc` will typically result in a target name of `foo` regardless of what directory it is in. Note that only the target name needs to be globally unique, the output file (`foo_test`) is already in the same directory as `foo_test.cc` and not likely to conflict.
In some places we used something inspired by the path (relative to the project root or to `google/cloud`) to prefix the target name. In other places we used something inspired by the associated library. I think it is simpler to always use the path. And it also yields shorter target.
- - - …
=> cleanup: shorter names for CMake targets

ci/kokoro/windows/build.ps1, ci/kokoro/windows/builds/bazel-debug-2017.ps1
The build is getting too large for our CI VMs. We probably have enough coverage between the other builds (Bazel+MSVC+Debug+20{19,22} and Bazel+MSVC+Release+2017).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10435)
=> ci: reduce scope for the Bazel+MSVC+Debug+2017 build

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc, google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscription_admin_client.h
Just throw from the samples and have a little wrapper capture and ignore the right exceptions when running with the emulator.
Fixes #4792 - or at least we will not be worrying about unimplemented features in the emulator after this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10441)
=> cleanup(pubsub): simplify emulator workarounds

google/cloud/internal/ci/run_integration_tests_emulator_cmake.sh
I neglected to update the driver script while renaming the test targets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10443)
=> ci: restore `rest` integration tests

google/cloud/internal/external_account_token_source_aws.cc, google/cloud/internal/external_account_token_source_aws.h, google/cloud/internal/external_account_token_source_aws_test.cc
As with the other external accounts, we need to build a subject token for AWS external accounts. Building this subject token requires obtaining a number of pieces of information. These can be found on environment variables or via the VM's metadata service. The functions to get them are complex enough that they deserve their own tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10439)
=> impl(oauth2): building blocks for AWS external accounts

doc/contributor/howto-guide-adding-generated-libraries.md, doc/contributor/howto-guide-declare-a-library-ga.md, doc/contributor/howto-guide-running-ci-builds-locally.md
While taking notes about the changes for generating libraries with version subdirectories (eventually handled in #10342), I made some other small cleanups to the opening paragraph, and those cascaded over into a couple of other guides.  We might as well preserve them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10445)
=> doc: clean up some howto-doc opening paragraphs

.github/workflows/external-account-integration.yml, google/cloud/internal/external_account_integration_test.cc
Another test that I renamed and neglected to run with the new name. It needed fixing in any case, as it can now use normal credential initialization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10447)
=> test(oauth2): simplify and restore WIF integration test

google/cloud/internal/external_account_token_source_aws.cc, google/cloud/internal/external_account_token_source_aws_test.cc
The spec (aip.dev/auth/4117) requires validation for some URL fields in the AWS external account configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10448)
=> impl(oauth2): validate some URLs in AWS external account

google/cloud/internal/oauth2_external_account_credentials.cc, google/cloud/internal/oauth2_external_account_credentials_test.cc
Use the right content-type header during the token exchange. At this time, Google's Security Token Service seems to work fine without it. It seems better to use the right header though.
I took the opportunity to clean up the tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10453)
=> impl(oauth2): content-type header in token exchange

generator/integration_tests/tests/golden_kitchen_sink_stub_test.cc, generator/integration_tests/tests/golden_thing_admin_stub_test.cc, google/cloud/bigtable/internal/bigtable_channel_refresh_test.cc, google/cloud/completion_queue.h, google/cloud/internal/async_connection_ready.cc, google/cloud/internal/async_read_stream_impl.h, google/cloud/internal/async_read_write_stream_impl.h, google/cloud/internal/async_read_write_stream_impl_test.cc, google/cloud/internal/async_streaming_read_rpc_impl.h, google/cloud/internal/async_streaming_read_rpc_impl_test.cc, google/cloud/internal/async_streaming_write_rpc_impl.h, google/cloud/internal/async_streaming_write_rpc_impl_test.cc, google/cloud/internal/completion_queue_impl.h, google/cloud/internal/default_completion_queue_impl.cc, google/cloud/internal/default_completion_queue_impl.h, google/cloud/testing_util/fake_completion_queue_impl.h, google/cloud/testing_util/mock_completion_queue_impl.h
This change is in preparation for adding derivations of `CompletionQueueImpl` that do not contain a `grpc::CompletionQueue`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10451)
=> refactor: change CompletionQueueImpl::cq return type

google/cloud/internal/external_account_token_source_aws.cc, google/cloud/internal/external_account_token_source_aws.h, google/cloud/internal/external_account_token_source_aws_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10457)
=> impl(oauth2): subject token source for AWS credentials

google/cloud/internal/external_account_token_source_aws.cc, google/cloud/internal/external_account_token_source_aws_test.cc, google/cloud/internal/oauth2_external_account_credentials_test.cc
This fixes a number of mistakes in the AWS subject token generation. I was able to test these changes manually using a VM in AWS.
The largest changes are:
- If present, the `x-amz-security-token` header must be signed, this required a new test
- It is also a recommended that the `x-goog-cloud-target-resource` header is signed too
- The subject token must be URL-encoded. Effectively this URL-encodes the subject token twice, as it is included in form payload.
- The signature should be based on the `YYYYMMDD` date, not the `YYYYMMDDTHHMMSSZ` timestamp
- I was missing a separator line for the canonical request
- s/AWS/AWS4/
- - - …
=> impl(oauth2): fix AWS subject token generation

google/cloud/credentials.cc, google/cloud/credentials.h, google/cloud/internal/credentials_impl_test.cc
Fixes #5915
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10465)
=> feat(common): factory function for external accounts

generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/golden_kitchen_sink_connection.h, generator/integration_tests/golden/golden_kitchen_sink_connection_idempotency_policy.h, generator/integration_tests/golden/golden_kitchen_sink_options.h, generator/integration_tests/golden/golden_thing_admin_client.h, generator/integration_tests/golden/golden_thing_admin_connection.h, generator/integration_tests/golden/golden_thing_admin_connection_idempotency_policy.h, generator/integration_tests/golden/golden_thing_admin_options.h, generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_connection.h, generator/integration_tests/golden/mocks/mock_golden_thing_admin_connection.h, generator/internal/forwarding_client_generator.cc, generator/internal/forwarding_connection_generator.cc, generator/internal/forwarding_idempotency_policy_generator.cc, generator/internal/forwarding_mock_connection_generator.cc, generator/internal/forwarding_options_generator.cc
In response to: https://github.com/googleapis/google-cloud-cpp/pull/10463#discussion_r1052997265
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10466)
=> impl(generator): backwards compat using declarations are deprecated

google/cloud/grafeas/CMakeLists.txt
We should use ${PROJECT_SOURCE_DIR}, as we do in all the other libraries, because that works even if `google-cloud-cpp` is used via `add_subdirectory()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10469)
=> cleanup(grafeas): fix path to find proto{deps,list}

generator/integration_tests/BUILD.bazel, generator/integration_tests/CMakeLists.txt, generator/integration_tests/benchmarks/client_benchmark.cc
Motivated by #10407 and other observability efforts.
Add a benchmark to measure the round trip time of a client call (where the server responds instantaneously).
If the cost incurred by logging is < X, we can justify always logging. Especially when compared with the time it takes to serialize/deserialize a message and send it over the wire.
What is X? Probably greater than 1 microsecond.
Also, for the record, the results look different on my laptop. The ratios are very similar though.
```
Run on (8 X 4900 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x4)
L1 Instruction 32 KiB (x4)
L2 Unified 256 KiB (x4)
L3 Unified 8192 KiB (x1)
Load Average: 0.61, 3.36, 5.01
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead. …
```
=> impl: benchmark client call round trip

generator/CMakeLists.txt, generator/google_cloud_cpp_generator.bzl, generator/integration_tests/golden/v1/internal/golden_kitchen_sink_logging_decorator.h, generator/integration_tests/golden/v1/internal/golden_kitchen_sink_metadata_decorator.h, generator/integration_tests/golden/v1/internal/golden_kitchen_sink_round_robin_decorator.h, generator/integration_tests/golden/v1/internal/golden_thing_admin_auth_decorator.h, generator/integration_tests/golden/v1/internal/golden_thing_admin_logging_decorator.h, generator/integration_tests/golden/v1/internal/golden_thing_admin_metadata_decorator.h, generator/integration_tests/golden/v1/internal/golden_thing_admin_round_robin_decorator.h, generator/internal/auth_decorator_generator.cc, generator/internal/auth_decorator_generator.h, generator/internal/logging_decorator_generator.cc, generator/internal/logging_decorator_generator.h, generator/internal/metadata_decorator_generator.cc, generator/internal/metadata_decorator_generator.h, generator/internal/round_robin_decorator_generator.cc, generator/internal/stub_generator_base.cc, generator/internal/stub_generator_base.h, google/cloud/bigtable/internal/bigtable_round_robin_decorator.h, google/cloud/pubsub/internal/subscriber_round_robin_decorator.h
All gRPC stubs have the same public methods. I think there are enough stubs to justify this consolidation.
It would be nice if we could do something similar for the method signatures in the `.cc` files... but I have not thought that far ahead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10473)
=> refactor(generator): consolidate some stub member functions

google/cloud/spanner/integration_tests/data_types_integration_test.cc, google/cloud/spanner/testing/database_integration_test.cc
The backend now supports PG JSONB arrays.  Fixes #10095.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10475)
=> test(spanner): enable testing of PG JSONB[] support

ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile, doc/packaging.md
Installing `curl` conflicts with a pre-installed `curl-minimal` package. It seems that `curl-minimal` is all we need.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10481)
=> ci: fix `demo-rockylinux-9` builds

google/cloud/bigtable/testing/table_integration_test.cc, google/cloud/bigtable/testing/table_integration_test.h
use a `::testing::Matcher` instead of defining `operator==` and such for `bigtable::Cell`. Motivated by cl/499097840.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10482)
=> test(bigtable): refactor CheckEqualUnordered

doc/contributor/howto-guide-adding-generated-libraries.md, generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator.h, generator/internal/scaffold_generator_test.cc, generator/standalone_main.cc, generator/templates/WORKSPACE.bazel
The generated `${library}/quickstart/WORKSPACE.bazel` are often out of date as soon as they are generated. To solve this, I moved the template for this generated file to a separate file, where renovate bot will keep it up to date.
Fixes #9825
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10493)
=> cleanup: automate scaffold WORKSPACE file

ci/cloudbuild/builds/checkers.sh
Make `checkers` only run on files that have diverged from `upstream/main`, if `GOOGLE_CLOUD_CPP_FAST_CHECKERS` is set.
This is a convenience for developers (especially those who run `checkers` on a laptop). We should not change our CI... but I am sure there are some how-to instructions that could benefit from a faster `checkers` build. If no one else sees the utility in this, I will painstakingly maintain it locally.
From a repo that only has changes to `checkers.sh`, on my gLaptop.
```sh
$ ci/cloudbuild/build.sh -t checkers-pr
Running typos:                                    ... 1.436 seconds
Running check-include-guards:                     ... 0.220 seconds
Running Abseil header fixes:                      ... 3.125 seconds
Running include fixes:                            ... 4.648 …
```
=> ci: faster checkers build

bazel/google_cloud_cpp_deps.bzl
Manually update `opentelemetry-cpp` to a commit that includes https://github.com/open-telemetry/opentelemetry-cpp/pull/1873
Otherwise the SDK will not build with bazel 6.0, which we need to use in our tests.
I do not want to wait on OpenTelemetry's release schedule. Also, I do not know how the bots will react. :shrug:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10498)
=> chore(otel): patch bazel

google/cloud/bigtable/tests/instance_admin_integration_test.cc
This test has flaked a few times recently. We do not need to be setting a strict deadline here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10503)
=> cleanup(bigtable): deflake integration test

google/cloud/internal/async_retry_unary_rpc.h, google/cloud/internal/retry_policy.h, google/cloud/internal/sha256_hmac.h, google/cloud/internal/throw_delegate.h, google/cloud/internal/type_traits.h, google/cloud/kms_key_name.h, google/cloud/log.h, google/cloud/polling_policy.h, google/cloud/project.h, google/cloud/status_or.h, google/cloud/stream_range.h, google/cloud/terminate_handler.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10504)
=> doc(common): use real Doxygen groups

generator/internal/descriptor_utils.cc
One of the comments in the `gkemultcloud` protos is incorrectly formatted. I have sent a fix upstream, but while that works its way through the pipelines, this workaround will keep the code generation happy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10515)
=> feat(generator): another comment workaround

doc/contributor/howto-guide-adding-generated-libraries.md
The `check-api` build immediately starts testing new GA libraries, we need to create the API baseline as we create the new library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10516)
=> doc: update howto guide for generated libraries

doc/contributor/howto-guide-setup-cmake-environment.md
docs: Also fixed the directory name for clang example
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10532)
=> docs: Added `-GNinja` to cmake configuration commands

.github/renovate.json
`opentelemetry-cpp` is pinned to a commit for bazel builds, while we wait for a fix to be included in their next release.
This PR tells `renovate-bot` not to send PRs for each new commit (or whatever the bot's PR cadence is). It is a temporary measure. See #10543 
We should still get notified of a new `opentelemetry-cpp` release, because of our cmake builds. I signed up for release email alerts, anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10542)
=> chore: (temporarily) pause otel bazel updates

google/cloud/BUILD.bazel, google/cloud/google_cloud_cpp_rest_protobuf_internal.bzl, google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake, google/cloud/google_cloud_cpp_rest_protobuf_internal_unit_tests.bzl, google/cloud/internal/rest_completion_queue_impl.cc, google/cloud/internal/rest_completion_queue_impl.h, google/cloud/internal/rest_completion_queue_impl_test.cc
This PR provides an implementation for use with `CompletionQueue` that does not rely on `grpc::CompletionQueue`. This implementation of `CompletionQueue` will be used to make LRO and Async calls for services that use REST transport.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10539)
=> impl(rest): add RestCompletionQueueImpl

google/cloud/testing_util/opentelemetry_matchers.cc, google/cloud/testing_util/opentelemetry_matchers.h
In response to @devbww's comments: https://github.com/googleapis/google-cloud-cpp/pull/10501#pullrequestreview-1244622069
Fix up the error output for span matchers. For example, this test:
```
TEST(OpenTelemetry, Fail) {
auto span_catcher = InstallSpanCatcher();
auto provider = opentelemetry::trace::Provider::GetTracerProvider();
auto tracer = provider->GetTracer("bad-scope-name", "bad-scope-version");
auto s = tracer->StartSpan("bad-span-name");
s->End();
auto spans = span_catcher->GetSpans();
auto& span = spans[0];
EXPECT_THAT(span, SpanHasInstrumentationScope());
EXPECT_THAT(span, SpanKindIsClient());
EXPECT_THAT(span, SpanNamed("expected-span-name"));
}
```
... produces the following error output:
```
[ RUN      ] OpenTelemetry.Fail …
```
=> cleanup(otel): neater span matchers

README.md
Also use a `<detail>` to avoid a giant wall of text with all the libraries.
Maybe we should highlight the most commonly used libraries outside the zippy (is that the name?), and just hide the other 90+ libraries.  Thoughts?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10561)
=> doc: reorder top-level README

google/cloud/internal/timer_queue_test.cc
Fixes #10535.  Or rather, I think that was fixed by the earlier changes to test for equality in the expiration times, but that made the test kind of trivial.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10560)
=> test(common): deflake `TimerQueue` test

google/cloud/internal/opentelemetry.cc, google/cloud/internal/opentelemetry.h, google/cloud/internal/opentelemetry_test.cc, google/cloud/testing_util/opentelemetry_matchers.cc, google/cloud/testing_util/opentelemetry_matchers.h
Part of the work for #10487 
Add helper function to extract status information (code, message, error info) and set span's status and attributes, accordingly.
Comments about the exact information we decide to capture are welcome. But I am inclined to jam this PR through, then iterate. (because much of the remaining work for the linked issue is blocked on this PR).
Also add some internal documentation for the existing functions, because one day I will forget what the code does.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10557)
=> impl(otel): extract attributes from status types

google/cloud/internal/rest_completion_queue_impl.cc
Fixes #10553
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10571)
=> fix(common): use atomic scheduling in RestCompletionQueue

google/cloud/internal/rest_completion_queue_impl.cc, google/cloud/internal/timer_queue.h, google/cloud/internal/timer_queue_test.cc
This adds an overload for `TimerQueue::Schedule()` that offers a cleaner implementation for `RestCompletionQueueImpl::RunAsync()`.  Certainly faster too, but that might be a very small difference.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10579)
=> impl(common): cleaner RestCQ's `RunAsync()`

CMakeLists.txt, cmake/GoogleCloudCppFeatures.cmake
Move the functions and code to control what features are enabled to its own file. It was getting messy in the top-level CMake file, and I need to add more functionality to this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10586)
=> refactor: separate file to enable/disable features

google/cloud/pubsub/samples/iam_samples.cc
Similar to #10587
We throw `Status`es now, so we should catch `Status`es as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10591)
=> cleanup(pubsub): catch status in samples

google/cloud/iam/samples/iam_samples.cc
fixes #7330 
Per issue comments, increasing allowance for propagation delay up to 7 minutes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10587)
=> flake(iam): increase propagation delay for GetServiceAccountKey sample

ci/cloudbuild/dockerfiles/centos-7.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cmake.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile
Will unblock adoption of the new abseil major, which dropped C++11.
Fixes #10599
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10601)
=> ci(otel): explicitly set cmake lang version to C++14

.bazelrc
Fixes #10600 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10604)
=> ci: enable C++14 for Bazel 'host' targets

google/cloud/internal/opentelemetry.cc, google/cloud/internal/opentelemetry.h, google/cloud/internal/opentelemetry_test.cc, google/cloud/internal/rest_retry_loop.h, google/cloud/internal/rest_retry_loop_test.cc, google/cloud/internal/retry_loop.h, google/cloud/internal/retry_loop_test.cc
Part of the work for #10489 
Adds ability to trace a synchronous backoff. Implemented in the gRPC / REST retry loops.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10589)
=> impl(otel): traced retry backoff (sync)

google/cloud/storage/tests/object_rewrite_integration_test.cc
Replace it with some `if()` and simpler (I think) assertions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10605)
=> cleanup(storage): avoid `xor` in a test

google/cloud/internal/rest_stub_helpers.cc, google/cloud/internal/rest_stub_helpers_test.cc
Provide more detailed diagnostic when a json response from a REST call fails parsing into its intended protobuf Message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10602)
=> impl(rest): improve error messaging from failed json to proto

google/cloud/internal/opentelemetry_aliases_test.cc
`ScopedSpan` is a `std::nullptr_t`. `clang-tidy` emitted a `google-readability-casting` warning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10609)
=> cleanup(otel): suppress warning if disabled

google/cloud/internal/log_wrapper.h, google/cloud/internal/log_wrapper_test.cc
Add LogWrapper calls that can be used with REST LROs. By using a `typename Context` parameter we avoid having to include anything specifically REST.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10595)
=> impl(rest): add LogWrapper overloads using RestContext

ci/cloudbuild/builds/checkers.sh, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/generate-markdown/generate-packaging.sh, doc/packaging.md
Keep most of the contents in the `.md` file and just inject the generated code. I changed one of the source files to avoid reformatting when `mdformat` goes through the file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10628)
=> cleanup: simplify doc/packaging.md generation

ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cmake.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cxx14.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cxx20.Dockerfile, doc/packaging.md
The next version of gRPC fixes its pkg-config dependencies, and that exposes a latent bug in the RE2 packages for some distros.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10627)
=> doc: install RE2 from source

ci/cloudbuild/builds/checkers.sh
ignore deleted files in "fast checkers".
`git diff --diff-filter=...` documentation: https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10625)
=> cleanup: fast checkers ignores deleted files

ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, doc/packaging.md
I missed a few in the last pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10631)
=> ci: more distros need RE2 compiled from source

ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, doc/packaging.md
We were using a static build for gRPC on this platform.  There is no reason to prefer a static build on only this platform.  Furthermore, to use it correctly we would need to add `--static` to any pkg-config invocations, which seems more complicated than needed too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10632)
=> doc: more consistent builds for Ubuntu Bionic

cmake/CompileProtos.cmake, google/cloud/dialogflow_es/CMakeLists.txt, google/cloud/speech/CMakeLists.txt, google/cloud/texttospeech/CMakeLists.txt, google/cloud/trace/CMakeLists.txt
Older versions of CMake are (too) strict about what properties may be attached to an interface library.  That was not working for some functions we use with proto libraries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10636)
=> fix: interface proto libraries work with older CMake

cmake/GoogleCloudCppDoxygen.cmake
Most of our builds do not need Doxygen, and when they fail to find it they merrily continue. With this change we do not get 100 lines saying the same thing (that Doxygen was not found).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10637)
=> cleanup: less noise when failing to find Doxygen

google/cloud/google_cloud_cpp_common.bzl, google/cloud/google_cloud_cpp_common.cmake, google/cloud/google_cloud_cpp_common_unit_tests.bzl, google/cloud/internal/traced_stream_range.h, google/cloud/internal/traced_stream_range_test.cc, google/cloud/testing_util/opentelemetry_matchers.cc, google/cloud/testing_util/opentelemetry_matchers.h
Fixes #10487 
Adds a function to make a traced `StreamRange<>`.
The new test matcher and helper function could be used to improve readability in existing tests. My plan is to send a `cleanup` PR after this one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10641)
=> impl(otel): add traced StreamRange

ci/cloudbuild/dockerfiles/fedora-36-bazel.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cmake.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cxx14.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-focal.Dockerfile
In general, the system packages (stuff installed with `apt-get` or its analog) tend to change less often than packages we compile from source. It makes sense to install them early in the Dockerfile, so that step is preserved when a new package is installed from source.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10639)
=> ci: make Dockerfiles slightly more cache-friendly

ci/cloudbuild/builds/checkers.sh
The in-place update performed by `mdformat` does not preserve the file mode, so do something simple to (probably) compensate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10635)
=> cleanup(doc): reset group/other permissions after mdformat

google/cloud/storage/internal/xml_escape.cc, google/cloud/storage/internal/xml_escape.h, google/cloud/storage/internal/xml_escape_test.cc, google/cloud/storage/internal/xml_node.cc, google/cloud/storage/internal/xml_node_test.cc
I split it into many member functions mainly for avoiding cognitive complexity warning. I'm not sure if it matters, but I made them all inline function to avoid function call overhead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10608)
=> impl(storage): add XML parser implementation

google/cloud/storage/internal/xml_builders.cc, google/cloud/storage/internal/xml_builders.h, google/cloud/storage/internal/xml_builders_test.cc
Avoid `unsigned int` in the `CompleteMultipartUpload()` API.  Of the simpler alternatives, plain `int` or `std::size_t`, the latter seems more appropriate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10648)
=> cleanup(storage): change part number type to std::size_t

google/cloud/internal/grpc_opentelemetry.cc, google/cloud/internal/grpc_opentelemetry.h, google/cloud/internal/grpc_opentelemetry_test.cc, google/cloud/internal/opentelemetry.cc, google/cloud/internal/opentelemetry.h, google/cloud/internal/opentelemetry_test.cc
Part of the work for #10489 
Add `InjectTraceContext(...)`, which is used for context propagation. For now we only use the global propagator (exactly how we only use the global tracer provider). In the future it may become `Option` dependent.
If you are wondering when I will settle on the customer-facing options for tracing, tomorrow I will pick a date by which I must have made the decision.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10646)
=> impl(otel): inject trace context for gRPC

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_metadata_decorator.cc, generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_metadata_decorator.cc, generator/internal/metadata_decorator_rest_generator.cc
Always include headers for both `absl::StrCat` and `absl::StrJoin`  as they are used in `SetMetadata`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10660)
=> impl(generator): fix metadata includes

google/cloud/internal/grpc_opentelemetry.cc
@devbww pointed out that the use of `string_view` was problematic: https://github.com/googleapis/google-cloud-cpp/pull/10646#discussion_r1086216072
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10664)
=> cleanup(otel): fix string_view usage in gRPC carrier

google/cloud/storage/internal/xml_node.cc, google/cloud/storage/internal/xml_node.h, google/cloud/storage/internal/xml_node_test.cc
Split `UnescapeXmlString()` into `UnescapeTagName()` and `UnescapeTextContent()` in order to have direct inverses of `EscapeTagName()` and `EscapeTextContent()`.  Tweak the `XmlNodeTest.Unescape` test case to check for the difference.
Also minimize `shared_ptr<XmlNode>` ref-count manipulations through appropriate use of `std::move`.
Plus some miscellaneous other cleanups:
- Rename `Rtrim()` to `StripTrailingSpaces()`.
- Strip trailing spaces before unescaping.
- Use `StatusOr<T>::operator bool`.
- Tidy up some comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10665)
=> cleanup(storage): split UnescapeXmlString() by purpose

generator/BUILD.bazel, generator/CMakeLists.txt, generator/google_cloud_cpp_generator_testing.bzl, generator/internal/descriptor_utils_test.cc, generator/testing/fake_source_tree.cc, generator/testing/fake_source_tree.h
I am about to create another test that will need a fake source tree.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10667)
=> refactor(generator): split `FakeSourceTree`

ci/cloudbuild/builds/demo-install.sh, doc/packaging.md, google/cloud/channel/CMakeLists.txt
I want to avoid any embarrassment if the libraries fail to build for whatever reason.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10634)
=> ci: demo builds compile all GA libraries

google/cloud/storage/internal/xml_node.cc
Don't do micro optimizations until we have a micro benchmark to evaluate the effects.
Also stop using in-class definitions, which makes the API clearer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10669)
=> cleanup(storage): remove inline specifiers from XmlParser

google/cloud/storage/internal/xml_node.cc, google/cloud/storage/internal/xml_node.h, google/cloud/storage/internal/xml_node_test.cc
[Reviewers: Yes, this is somewhat of a catchall, but it is convenient to gather all these together to finalize this work for now.]
Reformulate the `XmlParser` as a true state machine, where there are no branches on the next input char that are independent of the current state.  This means the current state can be represented simply by the handler function, without maintaining a parallel `enum`.
Correct a couple of transitions to the "base" state instead of the "end tag" state.  This should not affect a successful parse, but will improve the message given for errors after the transition.
There is no need to store `root_` and `current_parent_` separately when they can just be the bottom and top of `node_stack_`.
Accumulate the start/end tag names and the text content as views into the XML …
=> cleanup(storage): a handful of concluding cleanups for XmlParser

generator/CMakeLists.txt, generator/generator_test.cc, generator/google_cloud_cpp_generator_testing.bzl, generator/internal/descriptor_utils_test.cc, generator/internal/predicate_utils_test.cc, generator/internal/resolve_comment_references_test.cc, generator/internal/service_code_generator_test.cc, generator/testing/error_collectors.cc, generator/testing/error_collectors.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10675)
=> refactor(generator): split *ErrorCollector

generator/BUILD.bazel, generator/CMakeLists.txt, generator/google_cloud_cpp_generator_testing.bzl, generator/internal/resolve_comment_references_test.cc, generator/testing/descriptor_pool_fixture.cc, generator/testing/descriptor_pool_fixture.h, generator/testing/fake_source_tree.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10676)
=> refactor(generator): split DescriptorPoolFixture

google/cloud/spanner/ci/lib/spanner_emulator.sh, google/cloud/spanner/ci/run_integration_tests_emulator_bazel.sh
Part of the work to test gRPC/HTTP transcoding using generated Spanner admin code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10704)
=> impl(spanner): start second emulator to service REST transport

.github/renovate.json, bazel/google_cloud_cpp_deps.bzl
Update `opentelemetry-cpp` to v1.8.2 for bazel and revert #10542
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10706)
=> chore(otel): resume bazel renovate-bot updates

google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
The test had a race condition where the subscription could be cancelled before the message was acked. The `ack()` call would fail in this case, resulting in a (flaky) test error.
Part of the work for #9619
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10715)
=> test(pubsub): deflake `ExactlyOnce` integration test

ci/cloudbuild/triggers/cmake-gcs-rest-ci.yaml, ci/cloudbuild/triggers/cmake-gcs-rest-pr.yaml, ci/cloudbuild/triggers/cmake-install-ci.yaml, ci/cloudbuild/triggers/cmake-install-pr.yaml, ci/cloudbuild/triggers/cmake-single-feature-ci.yaml, ci/cloudbuild/triggers/cmake-single-feature-pr.yaml, ci/cloudbuild/triggers/integration-production-ci.yaml, ci/cloudbuild/triggers/integration-production-pr.yaml, ci/cloudbuild/triggers/noex-ci.yaml, ci/cloudbuild/triggers/noex-pr.yaml, ci/cloudbuild/triggers/quickstart-production-ci.yaml, ci/cloudbuild/triggers/quickstart-production-pr.yaml, ci/cloudbuild/triggers/shared-ci.yaml, ci/cloudbuild/triggers/shared-pr.yaml
These are builds that do not require specialized tools:
- `cmake-gcs-rest`
- `cmake-install`
- `cmake-single-feature`
- `integration-production`
- `noex`
- `quickstart-production`
- `shared`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10722)
=> ci: switch multiple builds to Fedora:37

google/cloud/internal/grpc_opentelemetry_test.cc, google/cloud/testing_util/opentelemetry_matchers.cc, google/cloud/testing_util/opentelemetry_matchers.h
Use a mock propagator instead of a fake. (This will prove useful when testing tracing stubs).
Document some OTel matchers/helpers with proper warnings for how they should be used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10729)
=> cleanup(otel): some test cleanups

google/cloud/internal/async_rest_retry_loop_test.cc, google/cloud/internal/async_retry_loop_test.cc
Verify the behavior of this line of code, with a test that would fail if it were removed: https://github.com/googleapis/google-cloud-cpp/blob/10cfef588c819438b85c5a086fd9f44d8f087288/google/cloud/internal/async_retry_loop.h#L194
Also, rearrange the order of the `ConfigureContext` test, so that the `TEST()`s are not broken up by `TEST_F()`s.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10731)
=> test: AsyncRetryLoop cancel options

google/cloud/internal/grpc_opentelemetry.cc, google/cloud/internal/grpc_opentelemetry.h, google/cloud/internal/grpc_opentelemetry_test.cc, google/cloud/testing_util/opentelemetry_matchers.h
Part of the work for #10489 
Introduce a method to extract relevant tracing info from a `grpc::ClientContext`.
The RPC Semantic Conventions would have us split up the peer URI into a port, IP address, IP version. Take on some technical debt by not initially doing this work.
gRPC has helpers to parse the URI, but they are an internal implementation. So leave a note for ourselves on where we can find a way to parse the URI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10735)
=> impl(otel): process gRPC Client Context

ci/cloudbuild/triggers/bazel-oldest-ci.yaml, ci/cloudbuild/triggers/bazel-oldest-pr.yaml, ci/cloudbuild/triggers/bazel-targets-ci.yaml, ci/cloudbuild/triggers/bazel-targets-pr.yaml, ci/cloudbuild/triggers/gcs-grpc-ci.yaml, ci/cloudbuild/triggers/gcs-grpc-pr.yaml, ci/cloudbuild/triggers/otel-disabled-bazel-ci.yaml, ci/cloudbuild/triggers/otel-disabled-bazel-pr.yaml
These builds verify that several Bazel targets and configurations work correctly.  Seemed like a good idea to ugprade them together.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10738)
=> ci: switch 'target' builds to Fedora:37

ci/cloudbuild/builds/cmake-install.sh, google/cloud/bigquery/BUILD.bazel, google/cloud/bigquery/CMakeLists.txt, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.cc, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.h, google/cloud/bigquery/v2/minimal/internal/job_logging.cc, google/cloud/bigquery/v2/minimal/internal/job_logging.h, google/cloud/bigquery/v2/minimal/internal/job_metadata.cc, google/cloud/bigquery/v2/minimal/internal/job_metadata.h, google/cloud/bigquery/v2/minimal/internal/job_options.cc, google/cloud/bigquery/v2/minimal/internal/job_options.h, google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.h, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.h, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_factory.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_factory.h, google/cloud/bigquery/v2/minimal/internal/job_retry_policy.h
Initial mostly empty files for the Bigquery V2 job API.
For details please see design doc: go/bq-odbc-client-design
I have run checkers-pr, clang-tidy-pr for bigquery. Running it from root was taking a very long time even the second time around.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10733)
=> impl(bigquery): v2 job initial files

google/cloud/grafeas/CMakeLists.txt
The `grafeas` library has nothing but protos, and therefore no input for Doxygen.  Newer versions of Doxygen reject empty input lists, and we do not even upload the output anywhere.  Seems better to save time by not generating a documentation set that is empty and unused.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10746)
=> doc(grafeas): prepare for Fedora:37

ci/cloudbuild/builds/check-api.sh, ci/cloudbuild/dockerfiles/checkers.Dockerfile, ci/generate-markdown/generate-readme.sh, cmake/print-ga-libraries.cmake
These builds used `bazel query` (or `bazelist query`) to discover the list of GA libraries. Starting bazel requires downloading dependencies, which can fail in the CI system. In normal Bazel builds we minimize these failures with some  `bazel fetch` before the build, but now that the list of GA libraries is in CMake there is a simpler and less flaky way to discover them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10754)
=> ci: deflake checks and check-api builds

google/cloud/testing_util/expect_exception.h
Assuming an API like `std::exception::what()`, fix the examples to use `EXPECT_STREQ("...", ex.what())`.
Also clear up some other comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10760)
=> cleanup(common): clarify expectation examples for ex.what()

docfx/CMakeLists.txt, docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc, vcpkg.json
This PR introduces the first function to convert simple paragraphs in Doxygen XML to MarkDown strings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10763)
=> impl(docfx): scaffolding for conversion functions

bazel/google_cloud_cpp_deps.bzl
Take advantage of the `maybe()` utility to load dependencies only if they are defined.  I appeased `buildifier` by adding an (unused) `name` argument to the `google_cloud_cpp_deps()` macro, and documenting why it is there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10765)
=> cleanup: simplify Bazel dependency loads

cmake/GoogleCloudCppFeatures.cmake
Use `internal-docfx` to explicitly label this as a feature intended only for internal use.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10766)
=> cleanup: rename `docfx` feature

google/cloud/internal/async_connection_ready_test.cc, google/cloud/pubsub/internal/subscription_concurrency_control_test.cc, google/cloud/spanner/samples/samples.cc, google/cloud/testing_util/validate_metadata.cc
For empty loop bodies I chose `continue` instead of `{}` as it is more visually distinctive, and a future edit will be more obvious.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10769)
=> cleanup: remove/clarify empty statements

ci/cloudbuild/builds/clang-tidy.sh, ci/cloudbuild/dockerfiles/fedora-37-cmake.Dockerfile, docfx/doxygen2markdown_test.cc
This needs installing a package in the Docker image, and enabling the feature in the build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10771)
=> ci: add `docfx` to clang-tidy build

ARCHITECTURE.md, doc/contributor/howto-guide-adding-generated-libraries.md, generator/integration_tests/golden/v1/golden_kitchen_sink_client.h, generator/integration_tests/test.proto, generator/integration_tests/tests/golden_kitchen_sink_metadata_decorator_test.cc, google/cloud/bigtable/doc/bigtable-main.dox, google/cloud/bigtable/tools/convert_acceptance_tests.py, google/cloud/capture_build_info.bzl, google/cloud/iam/quickstart/README.md, google/cloud/internal/grpc_opentelemetry.cc, google/cloud/internal/time_utils.h, google/cloud/pubsub/doc/pubsub-main.dox, google/cloud/spanner/doc/spanner-main.dox, google/cloud/spanner/partition_options.h, google/cloud/storage/doc/storage-main.dox, google/cloud/testing_util/mock_async_response_reader.h
Use more recent branch names, blobs, and paths.  Also, use "blob" instead of "tree" for file links (to avoid a forwarding step).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10774)
=> cleanup: update some reference links

google/cloud/storage/tests/object_read_large_integration_test.cc
Explicitly cast the result of `std::stoull()` to `std::size_t`. This is safe because the value being cast is a count of memory pages in the 32-bit address space.
Addresses #10772.  Part of #10775.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10779)
=> cleanup: cater to platforms with 32-bit std::size_t

examples/grpc_credential_types.cc, google/cloud/spanner/value_test.cc
Part of #10775.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10778)
=> cleanup: avoid std::time_t as it is platform specific

google/cloud/storage/benchmarks/aggregate_upload_throughput_benchmark.cc
Explicitly cast a 64-bit value to `std::streamsize`.  This is safe because the value being cast is bounded by another value that originated as a `std::streamsize`.
Part of #10775.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10780)
=> cleanup: cater to platforms with 32-bit std::streamsize

google/cloud/pubsub/internal/subscription_message_queue_test.cc
This reduces the number of threads created by the test. AFAICT, each thread consumes 8MiB of virtual address space (not all of that committed), and the test was creating 1,000 threads. That is too large for a 32-bit address space.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10785)
=> test(pubsub): avoid crashes in 32-bit builds

google/cloud/spanner/integration_tests/client_stress_test.cc
Reduce the number of threads-per-core in `client_stress_test` from 4 to 3.  On a machine with a large number of processing units, this apparently reduces the number of threads enough to not exhaust the 32-bit address space.
Part of #10775.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10787)
=> test(spanner): avoid timeouts in 32-bit builds

ci/generate-markdown/update-library-landing-dox.sh, google/cloud/automl/doc/main.dox, google/cloud/bigquery/doc/main.dox, google/cloud/dialogflow_cx/doc/main.dox, google/cloud/dialogflow_es/doc/main.dox, google/cloud/monitoring/doc/main.dox, google/cloud/retail/doc/main.dox, google/cloud/speech/doc/main.dox, google/cloud/tpu/doc/main.dox
De-duplicate entries for endpoint-overriding environment variables, which can arise when we support multiple versions of the same service. This was true for speech and tpu.
An artifact of the de-duplication is that entries are now sorted, which isn't a bad thing, but causes some initial churn.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10788)
=> doc: de-dup endpoint environment-variable documentation

bazel/google_cloud_cpp_deps.bzl
These are manually updated anyway, so creating a backup source is not much of an extra burden.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10791)
=> ci: deflake libcurl downloads

google/cloud/pubsub/internal/defaults.cc
When the code is compiled for 32-bit platforms using 4 * thread-count background threads can quickly exhaust the address space. Reduce the default number of background threads to just 4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10793)
=> fix(pubsub): fewer default threads for 32-bit builds

google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client_acl_test.cc
The `retention_period` field is deprecated and will be retired "soon".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10792)
=> cleanup(GCS+gRPC): use `retention_duration` field

google/cloud/spanner/client.h
Move all the backwards-compatibility overloads in `spanner::Client` to the end of the public-functions section so that the recommended interfaces are more obvious, particularly in the doxygen-generated documentation.
Also remove some grouping around `ExecuteQuery()` and `ProfileQuery()` overloads.
Fixes #10755.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10798)
=> cleanup(spanner): reorder class function declarations for clarity

cmake/AddPkgConfig.cmake, cmake/templates/config.pc.in, google/cloud/google_cloud_cpp_common.cmake
Part of the work for #10795 
Capture the `-D` flags that were present when the library was compiled (the [INTERFACE_COMPILE_DEFINITIONS](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_COMPILE_DEFINITIONS.html)).
Note that we could also extract other Cflags, such as `-I` flags by looking at [INCLUDE_DIRECTORIES](https://cmake.org/cmake/help/latest/prop_tgt/INCLUDE_DIRECTORIES.html). But there is no need to do so now, so I'd rather not touch it. I looked into capturing the target's linked libraries, but could not find them.
Also, add `HAVE_ABSEIL` to the compile definitions to unblock other work. It relies on us transitively picking up opentelemetry's deps (`absl_strings absl_bad_variant_access absl_any absl_base absl_bits absl_city`). And we assume `opentelemetry` is installed in a …
=> impl: pkg-config respects compile defs

google/cloud/storage/tests/bucket_integration_test.cc
Restore or enable the Bucket metadata integration tests against production. These used to fail due to multiple little bugs in the client, tests, and/or production.
Fixes #9801 and fixes #9802
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10802)
=> test(GCS+gRPC): enable Bucket patch integration tests

google/cloud/stream_range.h, google/cloud/stream_range_test.cc
Part of the work for #10618
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10730)
=> impl(otel): `StreamRange<>` uses `CallContext`

google/cloud/spanner/integration_tests/data_types_integration_test.cc, google/cloud/spanner/samples/samples.cc
A `Commit()` mutator might be re-run, so it should ensure its own idempotency.  Fix the `*DataTypeIntegrationTest.DmlReturning` tests accordingly.
Also raise visibility on the issue by adding a note in the samples about non-transactional state changes in mutators.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10805)
=> test(spanner): reset state in the DmlReturning test mutators

google/cloud/internal/opentelemetry.cc, google/cloud/internal/opentelemetry.h, google/cloud/internal/opentelemetry_test.cc
Motivated by #10491 
I cannot avoid a clang diagnostic warning from an unused parameter. `NOLINT`s do not solve the problem. It seems nicer to do the `#ifdefs` in one place, than in N `MakeFooTracingStub(..., Options const& options)`.
If anyone wishes to say "I told you so", now is the time. https://github.com/googleapis/google-cloud-cpp/pull/10496#discussion_r1062730261
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10804)
=> cleanup(otel): `TracingEnabled()` always exists

google/cloud/storage/tests/grpc_object_media_integration_test.cc, google/cloud/storage/tests/object_integration_test.cc
Enable the tests blocked by lacking a functional
`CancelResumableUpload()` in production.
Fixes #9804
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10810)
=> test(GCS+gRPC): more integration tests in production

google/cloud/storage/internal/grpc_bucket_access_control_parser.cc, google/cloud/storage/internal/grpc_bucket_access_control_parser.h, google/cloud/storage/internal/grpc_bucket_access_control_parser_test.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.h, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_access_control_parser.cc, google/cloud/storage/internal/grpc_object_access_control_parser.h, google/cloud/storage/internal/grpc_object_access_control_parser_test.cc, google/cloud/storage/internal/grpc_object_metadata_parser.cc, google/cloud/storage/internal/grpc_object_metadata_parser_test.cc
This populates synthetic self-link fields for the `*AccessControl` resources. I neglected these earlier because other fields (such as ETag) were failing too and my test did not catch them.
Part of the work for #9805
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10809)
=> impl(GCS+gRPC): synthetic self-links for ACLs

google/cloud/storage/tests/grpc_hmac_key_integration_test.cc, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc, google/cloud/storage/tests/object_basic_crud_integration_test.cc
Some tests were disabled waiting for ETag support in production.
Fixes #9805
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10813)
=> test(GCS+gRPC): enable production integration tests

google/cloud/internal/streaming_read_rpc.cc, google/cloud/internal/streaming_read_rpc.h, google/cloud/internal/streaming_read_rpc_test.cc, google/cloud/internal/streaming_write_rpc_impl.cc, google/cloud/internal/streaming_write_rpc_impl.h, google/cloud/internal/streaming_write_rpc_test.cc
When a streaming RPC is cancelled we should expect the final status of the RPC to be either kOk, or kCancelled. Both are normal outcomes in this case and do not deserve a warning in the log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10811)
=> fix(common): fewer spurious warnings in the log

CMakeLists.txt
We no longer need to override CMAKE_CXX_STANDARD on macOS. The compiler defaults to C++98, but our libraries use `target_compile_features()` to request C++14 or higher.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10817)
=> cleanup: remove CMAKE_CXX_STANDARD override

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/force_sanitizer_failures_test.cc
Remove some code and CMake option used to force a static analysis error. We no longer have any builds with this static analysis, and when we did, the flag was used to troubleshoot problems with the build not failing when it should. The latter is better done with a local change rather than polluting the options namespace.
Motivated by #8572 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10818)
=> cleanup(bigtable): remove unused CMake option

CMakeLists.txt, ci/cloudbuild/builds/lib/cmake.sh, ci/cloudbuild/builds/lib/quickstart.sh, ci/kokoro/macos/builds/cmake-vcpkg.sh, ci/kokoro/macos/builds/quickstart-cmake.sh, ci/kokoro/windows/builds/cmake.ps1, ci/kokoro/windows/builds/quickstart-cmake.ps1, cmake/EnableWerror.cmake
Change some CMake defaults to make them more suitable for our customers. For example, turning on `-Werror` can fail for our customers if they use a newer compiler. And enabling `ccache(1)` is not helpful for package maintainers.
Fixes #7387
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10819)
=> cleanup: more user-friendly CMake defaults

ci/cloudbuild/builds/coverage.sh, ci/cloudbuild/builds/lib/integration.sh, google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh, google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh, google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
Specify integration test tags in one place, `integration.sh`, instead of in each script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10812)
=> refactor(ci): consolidate bazel tag filters

ci/cloudbuild/builds/lib/integration.sh, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc, google/cloud/storage/tests/object_basic_crud_integration_test.cc
Production now supports patching some sub-fields, notably the bucket labels and the object custom metadata.
Fixes #9803
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10820)
=> impl(GCS+gRPC): support sub-field patches

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_insert_object_media_test.cc, google/cloud/storage/internal/grpc_client_upload_chunk_test.cc
In some environments the storage protos use `absl::Cord`.  We believe we can minimize data copying in gRPC if the protos are initialized with an `absl::Cord` in these environments.  Even if the performance benefits do not materialize, this change makes the code easier to follow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10828)
=> impl(GCS+gRPC): better support for `absl::Cord`

bazel/google_cloud_cpp_deps.bzl
To pick up the [CVE-2023-0286] fixes.
[CVE-2023-0286]: https://github.com/advisories/GHSA-x4qr-2fvf-3mr5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10835)
=> chore(deps): update BoringSSL pinned SHA

.bazelignore, bazel/google_cloud_cpp_deps.bzl
To pick up the [CVE-2023-0286] fixes.
[CVE-2023-0286]: https://github.com/advisories/GHSA-x4qr-2fvf-3mr5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10838)
=> chore(deps): update BoringSSL pinned SHA (#10835)

ci/cloudbuild/builds/checkers.sh
As part of applying whitespace fixes to text files during the `checkers` build, ensure that there is a newline at end-of-file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10841)
=> ci: add a trailing newline to files that don't already have one

google/cloud/bigtable/examples/bigtable_hello_world.cc
The `bigtable_hw_create_table` region cares about making a `CreateTable` rpc, not creating a `Table` client.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10844)
=> docs(bigtable): clean up `CreateTable` sample

bazel/google_cloud_cpp_deps.bzl
It seems the renovate bot understands `maybe(http_archive, ...`, but does not understand `maybe(repo_rule=http_archive, ...)`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10845)
=> chore: use `maybe()` in a renovate-friendly way

bazel/google_cloud_cpp_deps.bzl
Download the complete https://github.com/nlohmann/json archive, even though we only use the "include" files.  This will allow us to cache a file that has the version number in its name, simplifying cache management.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10843)
=> chore(deps): download the full nlohmann library

bazel/deps-cache.sh, bazel/google_cloud_cpp_deps.bzl
Add GCS alternative URLs to download archives for all the external Bazel dependencies that didn't already have one.  Hopefully this will help reduce download flakiness.
Note that Bazel says, "URLs are tried in order until one succeeds, so you should list local mirrors first."  We can do some re-ordering later, if desired, to list GCS URLs first.
Also add a script to verify and (optionally) populate the GCS cache. For now I only propose that we run it manually when dependencies are updated, but we might consider running it from, say, the `checkers` build in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10840)
=> chore(deps): add GCS alternatives for remaining bazel dependencies

google/cloud/internal/async_streaming_read_rpc_auth_test.cc, google/cloud/internal/async_streaming_write_rpc_auth_test.cc, google/cloud/pubsub/internal/batching_publisher_connection.cc, google/cloud/pubsub/internal/sequential_batch_sink.cc, google/cloud/pubsub/internal/subscription_concurrency_control.cc
There may be more such structs. I only looked for ones named `*MoveCapture*`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10849)
=> cleanup: use lambdas w move capture

bazel/google_cloud_cpp_deps.bzl
"Closer" mirrors should be listed first in `http_archive.urls`. In an unscientific test of sequential downloads of all the archives to my workstation, GCS wins by a 10x factor over GitHub for elapsed time (~1s -v- ~10s).  Nothing huge, but every second counts.
Also canonicalize the ordering of urls/sha256/strip_prefix fields.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10851)
=> chore(deps): prefer the GCS URL for downloading Bazel dependencies

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
This introduces support for itemized lists in Doxygen sections. I think this is the simplest thing that justifies adding the context and indentation.  The basic ideas in this change are:
- New paragraphs need a empty line just before them **unless** the paragraph is the start of a list item, where you just need a line starting with "- " (maybe with some indentation.
- Sub itemized lists and list items with multiple paragraphs need to be indented to preserve the structure in Markdown.
For example: this is new paragraph, as it is precedeed by an empty line. It is also part of the same list item, by virtue of its indentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/googl …
=> impl(docfx): support for itemized lists

bazel/deps-cache.sh
PR #10851 moved a comment into a `urls=[]` list, which the simple parser did not expect.  Hopefully things will be stable for a while now, but the sooner we move to something more general (Python based), the better.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10854)
=> chore(deps): handle comments in urls=[] lists

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
These appear in most pages, they are generated by many Doxygen commands, including `@note`, `@warning`, and `@par`. All of these are used routinely in our documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10860)
=> impl(docfx): handle `simplesect` elements

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h
This will avoid the need for new parameters when TransactionContext is expanded, which will be happening shortly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10868)
=> impl(spanner): push TransactionContext further down in ConnectionImpl

google/cloud/spanner/internal/connection_impl.cc
Call `ConfigureContext()` in the two cases (`StreamingRead()` and `ExecuteStreamingSql()`) where the Spanner connection allocates its own `grpc::ClientContext` objects.
Part of #9454.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10879)
=> impl(spanner): call ConfigureContext() for streaming RPCs

google/cloud/storage/internal/xml_node.cc, google/cloud/storage/internal/xml_node.h
Quash a "multiplication result converted to larger type" alert when we produce the length of the indentation string.  Of course, we know `int` truncation (and `std::size_t` truncation, which is still possible) are not practical concerns, but this should silence the bots.
Fixes #10881.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10884)
=> impl(storage): use std::size_t for indentation width and level

google/cloud/spanner/internal/defaults.cc, google/cloud/spanner/internal/defaults_test.cc, google/cloud/spanner/options.h
This will be used in upcoming code that will add a routing header to RPCs that should be served in the leader region.
The boolean option defaults to true, but the default can be changed with a suitably-negative value in `${GOOGLE_CLOUD_CPP_SPANNER_ROUTE_TO_LEADER}`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10885)
=> feat(spanner): introduce the RouteToLeaderOption

docfx/doxygen2markdown.cc, docfx/doxygen2markdown_test.cc
I should have connected `simplesect` to `para` when I introduced it. At least we got better tests out of my mistake.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10882)
=> impl(docfx): use and test `simplesect` support

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
These appear in some of the additional pages for the common library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10887)
=> impl(docfx): support `ulink` elements

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/job.h, google/cloud/bigquery/v2/minimal/internal/job_request.cc, google/cloud/bigquery/v2/minimal/internal/job_request.h, google/cloud/bigquery/v2/minimal/internal/job_request_test.cc, google/cloud/bigquery/v2/minimal/internal/job_response.cc, google/cloud/bigquery/v2/minimal/internal/job_response.h, google/cloud/bigquery/v2/minimal/internal/job_response_test.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.h, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc
Most of the implementation and tests are stubbed out.
I was trying to be mindful of the PR size as requested and also the request for the implmentation and testing files to be submitted in a single PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10837)
=> impl(bigquery): Interface headers with request/response and stubbed out implementation and tests for GetJob api.

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/transaction_impl.h, google/cloud/spanner/query_partition.h, google/cloud/spanner/read_partition.h, google/cloud/spanner/transaction.cc, google/cloud/spanner/transaction.h
RPCs within the transaction will then be able to inspect the context to determine if their requests should be routed to the region leader.
Mostly this is just YES for read-write transactions and NO for readonly transactions.  Partitioned-DML transactions are a slight complication, which will be dealt with presently.
Query and read partitions currently say NO, pending some updates as to how they are serialized/deserialized.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10894)
=> impl(spanner): add TransactionContext.route_to_leader

google/cloud/spanner/internal/connection_impl.cc
Even though the `spanner::Transaction` created in `ExecutePartitionedDml()` is only a placeholder until it is replaced by a partitioned-dml transaction within `ExecutePartitionedDmlImpl()`, use a read-write transaction so that it is marked as "route to leader".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10908)
=> impl(spanner): use a read-write transaction in ExecutePartitionedDml()

google/cloud/pubsub/internal/ack_handler_wrapper.cc, google/cloud/pubsub/internal/ack_handler_wrapper_test.cc
Fixes #10921 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10920)
=> fix(pubsub): no warnings on `ack()/nack()` success

google/cloud/spanner/database_admin_client.h, google/cloud/spanner/samples/samples.cc
We made a poor choice in naming the (hand-written) `DatabaseAdminClient` interface to `rpc UpdateDatabaseDdl` as just `UpdateDatabase()`.  Soon there actually will be a database-admin `UpdateDatabase` RPC, which fortunately we'll only support in the generated API, but it will want to use the "update-database" tag.
So, use "add-column" for the old snippet tag instead.  It is also a closer match for the corresponding doc tag, "spanner_add_column".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10919)
=> cleaup(spanner): rename the "update-database" snippet tag

google/cloud/spanner/query_partition_test.cc, google/cloud/spanner/read_partition_test.cc
`QueryPartitionTest.Constructor` was equivalent to `.MakeQueryPartition`.
`ReadPartitionTest.Constructor` was equivalent to `.MakeReadPartition`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10937)
=> test(spanner): de-dup query/read-partition tests

google/cloud/spanner/client.cc, google/cloud/spanner/query_partition.h, google/cloud/spanner/query_partition_test.cc
Clarify how `SqlParams` receives its `QueryOptions`.  Previously `MakeSqlParams()` produced an empty `.query_options` member, which `Client::ExecuteQuery()` then promptly over-wrote.  Let's take the `QueryOptions` as a `MakeSqlParams()` parameter instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10938)
=> cleanup(spanner): pass QueryOptions to MakeSqlParams()

external/googleapis/renovate.sh
`renovate.sh` knew that the editable `bazel/google_cloud_cpp_deps.bzl` elements were terminated by the "sha256" field ... until they weren't. (See "canonicalize the ordering of urls/sha256/strip_prefix fields" in #10851.)
The new sed script is just as fragile, but hopefully now a little more stable.
Also update the order of the substitution commands to match the file, for just a little more clarity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10946)
=> impl: fix updating of strip_prefix in renovate.sh

ci/kokoro/windows/build-32.bat, ci/kokoro/windows/build.bat
There is no need to install `bazelisk` during the build, it is already installed in the base image.  The fewer things we install dynamically, the fewer things that can fail to download, the fewer flakes we have.
Fixes #10140
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10948)
=> ci: deflake Kokoro+Windows builds

google/cloud/terminate_handler.h
I noticed this when writing the docfx stuff.  It is also a good test for the new CI images.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10950)
=> doc: improve description for "terminate" group

generator/generator_config.textproto, google/cloud/bigtable/admin/bigtable_table_admin_connection_idempotency_policy.cc
Part of the work for #10413
Default `BigtableTableAdmin::(Async)CheckConsistency` to be idempotent. This will improve the success rate for the `bigtable_admin::AsyncWaitForConsistency(...)` helper.
This probably "fixes" #9870. Getting `UNAVAILABLE` is a fairly common flake when run against production in our CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10955)
=> fix(bigtable): retries for `CheckConsistency` / `AsyncWaitForConsistency`

ci/cloudbuild/builds/clang-tidy.sh
This feature is included: https://github.com/googleapis/google-cloud-cpp/blob/9ee0d20890064e3fe547e5f868eae86424a6180b/ci/cloudbuild/builds/lib/features.sh#L30
I just forgot to clean up the TODO.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10956)
=> cleanup(ci): de-dup enabled feature

CHANGELOG.md
Related to #10170 
This seemed worthy of a CHANGELOG entry
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10958)
=> chore: versioned clients CHANGELOG entry

google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/storage/tests/curl_download_request_integration_test.cc, google/cloud/storage/tests/curl_request_integration_test.cc
We do not gain more information by using httpbin.org, and that fails sometimes.
Part of the work for #10413
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10961)
=> test: only use emulator for low-level HTTP tests

generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc
@coryan says "there is prior code to detect `SetIamPolicy` methods, maybe you should have followed the same structure as those?" https://github.com/googleapis/google-cloud-cpp/pull/10957#discussion_r1118700155
I think this is what he means.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10965)
=> cleanup(generator): stricter IAM checks

docfx/CMakeLists.txt, docfx/config.h, docfx/docfx.bzl
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10970)
=> refactor(docfx): split Config to its own file

docfx/doxygen2markdown.cc, docfx/doxygen2markdown_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10971)
=> impl(docfx): support sect{2,3,4} in description

docfx/CMakeLists.txt, docfx/docfx.bzl, docfx/doxygen2toc.cc, docfx/doxygen2toc.h, docfx/doxygen2toc_test.cc, docfx/unit_tests.bzl
Generate an initial table of contents files, with just the Doxygen `@page` documents for now.  This introduces the first YAML output.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10972)
=> impl(docfx): initial table of contents file

google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client_test.cc
How to create a bucket is changing. This is the "new and improved" way to specify what project owns the bucket.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10986)
=> impl(GCS+gRPC): use new spec for `CreateBucket()`

ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/builds/quickstart-cmake.sh, ci/kokoro/windows/builds/quickstart-cmake.ps1, ci/verify_quickstart/CMakeLists.txt
This will speed up the Windows build, by parallelizing all the quickstart tests.  We may be able to use these changes to test more quickstarts with vcpkg on Linux and macOS too.
Fixes #9925
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10985)
=> ci: use ci/verify_quickstart on Windows

google/cloud/apikeys/quickstart/BUILD.bazel, google/cloud/apikeys/quickstart/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10992)
=> cleanup(apikeys): apikeys is no longer experimental in v2.8.0

ci/cloudbuild/builds/gcs-grpc.sh, ci/cloudbuild/builds/integration-production.sh, google/cloud/storage/tests/bucket_integration_test.cc, google/cloud/storage/tests/grpc_integration_test.cc
The GCS+gRPC implementation is stable enough to enable *most* integration tests.  Nevertheless, I am planning to keep the `gcs-grpc` test as optional for now.  Eventually we should merge this tests into the `integration-production` build and make them required for each PR.
Part of the work for #6268
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10993)
=> ci: enable GCS+gRPC metadata integration tests

ci/cloudbuild/builds/coverage.sh, ci/cloudbuild/builds/gcs-grpc.sh, ci/cloudbuild/builds/integration-production.sh, google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh, google/cloud/storage/tests/BUILD.bazel, google/cloud/storage/tests/service_account_integration_test.cc
The storage library integration tests can run using (1) the normal HTTP transport, (2) the legacy HTTP implementation, (3) use GCS+gRPC for only media operations, or (4) use GCS+gRPC for media and metadata operations. We were testing all these variations by calling `bazel` with different environment variables, that made our test scripts more complicated, it wastes parallelism opportunities, and it pays the bazel startup costs multiple times. It also seems that running the same test with different environment variables disables test result caching.
This PR moves the complexity to the Bazel file: it creates multiple "variants" of each integration test, with different environment variables. The program drivers can exclude some variants using test tags.
Part of the work for #6268
- - -
This …
=> test(storage): simplify testing transport variants

google/cloud/completion_queue.h, google/cloud/completion_queue_test.cc, google/cloud/internal/async_rpc_details.h
Introduce `MakeUnaryRpcImpl(...)` which exists outside of the CQ. Note that it accepts a `std::shared_ptr<grpc::ClientContext>`. Update `AsyncUnaryRpcFuture` to interact with a `std::shared_ptr<grpc::ClientContext>`.
I could use double checking on the templates when split into definition vs. declaration. Also on moving the context into the lambda. I am fairly sure I want the lambda to own the context.
Note that the new test is just a copy of the existing `TEST(CompletionQueueTest, MakeUnaryRpc)`. I considered updating the test to use a MockCQ, but it was more trouble than it's worth. (Just mocking `StartOperation` then calling `op->Notify(true);` will not actually test the stuff in `AsyncUnaryRpcFuture::Start()`.)
We should deprecate `CQ::MakeUnaryRpc` and …
=> refactor: MakeUnaryRpc that is not a CQ member

.clang-format, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/client.cc, google/cloud/storage/client.h, google/cloud/storage/client_object_test.cc, google/cloud/storage/compose_many_test.cc, google/cloud/storage/hashing_options.cc, google/cloud/storage/hashing_options.h, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_request.cc, google/cloud/storage/internal/curl_request.h, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_metadata_parser.cc, google/cloud/storage/internal/grpc_object_metadata_parser.h, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/object_requests_test.cc, google/cloud/storage/internal/openssl_util.cc, google/cloud/storage/internal/openssl_util.h, google/cloud/storage/internal/openssl_util_test.cc, google/cloud/storage/internal/rest_client.cc, google/cloud/storage/parallel_uploads_test.cc, google/cloud/storage/tests/object_media_integration_test.cc
We can avoid a data copy if we use `absl::string_view` to contain the object payload.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11014)
=> feat(storage): reduce copies in `InsertObject()`

generator/standalone_main.cc, google/cloud/log.cc, google/cloud/log.h, google/cloud/log_test.cc
If the generator is to use `GCP_LOG()` to report problems, then we must ensure that logging messages end up on the "stderr" output stream. The easiest way to do that is enable the `std::clog` backend on the `LogSink` (flush/tie aside), which we were already attempting.
Unfortunately the `EnableStdClog()` call was doing nothing because a default backend was already in place.  So, we must remove that backend first, and the easiest was to do that is to call `DisableStdClog()`.
Also lower the default minimum log severity to NOTICE, which is the first level that is an indication of a problem.
And finally add a `--log_level` flag so that the minimum can be lowered all the way down to the compile-time limit.  Parsing this flag required exposing `ParseSeverity()`.
- - - …
=> fix(generator): ensure warnings and errors are sent to std::clog

ci/cloudbuild/builds/generate-libraries.sh, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils.h, generator/standalone_main.cc
A couple of the ad hoc substitutions we apply to the comments for method_signature parameters are no longer needed (the ones from google/pubsub/v1/schema.proto), so remove them.
How do we know they're obsolete?  By making it a fatal error for a substitution to fail to match.  This will make it easy for us to remove dead cruft.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11021)
=> cleanup(generator): remove obsolete parameter comment substitutions

generator/internal/codegen_utils.cc, generator/internal/codegen_utils.h, generator/internal/codegen_utils_test.cc
The Discovery docs have a variety of description fields that we need to turn into comments to document the protos being created.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010)
=> impl(generator): functions for formatting comments

CHANGELOG.md
edits to #11028
@coryan I assume the other Google libraries have stopped testing with MSVC 2017, not MSVC altogether. Please correct me if that is wrong.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11030)
=> cleanup: grammar/punctuation

google/cloud/internal/async_rest_retry_loop.h, google/cloud/internal/async_rest_retry_loop_test.cc, google/cloud/internal/async_retry_loop.h, google/cloud/internal/async_retry_loop_test.cc, google/cloud/internal/async_rpc_details.h, google/cloud/internal/default_completion_queue_impl.cc, google/cloud/internal/rest_background_threads_impl.cc
Propagate trace context across the `AsyncGrpcOperation`s involved in an async unary client call.
Also, include the REST version of things so the async retry loop tests stay in sync.
Note that (to my knowledge) nothing is really testing context propagation in some of the individual async operations, e.g. `AsyncUnaryRpcFuture`. (call options and parent span)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11035)
=> impl(otel): `CallContext` for `Async(Rest)RetryLoop`

google/cloud/internal/async_polling_loop.cc, google/cloud/internal/async_polling_loop_test.cc, google/cloud/internal/async_rest_polling_loop.cc, google/cloud/internal/async_rest_polling_loop_test.cc
Propagate trace context across an `Async(Rest)PollingLoop`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11040)
=> impl(otel): trace context across AsyncPollingLoop

google/cloud/internal/async_connection_ready.cc, google/cloud/internal/async_connection_ready.h, google/cloud/internal/async_connection_ready_test.cc
This is a more obscure API that only affects handwritten libraries. But we might as well make all the `OptionsSpan` -> `ScopedCallContext` conversions at one time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11041)
=> impl(otel): trace context across gRPC channel refresh

generator/integration_tests/golden/v1/internal/golden_thing_admin_tracing_stub.cc, generator/integration_tests/tests/golden_thing_admin_tracing_stub_test.cc, generator/internal/tracing_stub_generator.cc, google/cloud/bigtable/admin/internal/bigtable_table_admin_tracing_stub.cc, google/cloud/bigtable/internal/bigtable_tracing_stub.cc, google/cloud/logging/v2/internal/logging_service_v2_tracing_stub.cc, google/cloud/monitoring/v3/internal/metric_tracing_stub.cc, google/cloud/pubsub/internal/publisher_tracing_stub.cc, google/cloud/pubsub/internal/subscriber_tracing_stub.cc, google/cloud/pubsublite/internal/admin_tracing_stub.cc, google/cloud/storage/internal/storage_tracing_stub.cc
Part of the work for #10620 
As per the design, we do only mark the span for the async call as active in order to inject the trace context. By closing the scope, we ensure that the parent span (to be started by the connection) is propagated. This way subsequent backoffs / retries are siblings of each other.
Get/Cancel for LROs are also async unary stub calls. I will add them in a follow up though, so I can embellish my productivity before the OSPO.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11044)
=> impl(otel): async unary gRPC stub tracing

google/cloud/google_cloud_cpp_common.cmake, google/cloud/google_cloud_cpp_common_unit_tests.bzl, google/cloud/google_cloud_cpp_mocks.bzl, google/cloud/mocks/current_options.h, google/cloud/mocks/current_options_test.cc, google/cloud/mocks/mock_stream_range_test.cc
Fixes #10030 
If we think this should be more publicized, say the words and I will add it to our [mocking exemplar](https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/bigquery/samples/mock_bigquery_read.cc).
Also, while we are here, put the other mock test in an anonymous namespace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11050)
=> feat(mocks): provide access to call options in client tests

google/cloud/internal/grpc_opentelemetry.h, google/cloud/internal/grpc_opentelemetry_test.cc
The analog of #10589, but async.
I will incorporate it in the `AsyncRetryLoop`s and `AsyncPollingLoop`s in separate PRs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11048)
=> impl(otel): traced async backoffs

google/cloud/bigquery/v2/minimal/internal/job_options.cc, google/cloud/bigquery/v2/minimal/internal/job_options.h, google/cloud/bigquery/v2/minimal/internal/job_options_test.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_factory.cc
This replaces default rest client with pooled rest client. I looked at a few other examples in the repo for pooled rest clients especially 
https://github.com/googleapis/google-cloud-cpp/blob/ecf4413da87637e893601ac00f406cfc66b92660/google/cloud/spanner/admin/internal/database_admin_rest_stub.cc 
and
https://github.com/googleapis/google-cloud-cpp/blob/ecf4413da87637e893601ac00f406cfc66b92660/google/cloud/spanner/admin/internal/instance_admin_rest_stub.cc
And it doesn't seem like I need to change rest request path for GetJob  but let me know if that is not the case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11043)
=> impl(bigquery): Fixes googleapis/google-cloud-cpp#11027

google/cloud/internal/async_rest_retry_loop.h, google/cloud/internal/async_rest_retry_loop_test.cc, google/cloud/internal/async_retry_loop.h, google/cloud/internal/async_retry_loop_test.cc
Part of the work for #10618
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11051)
=> impl(otel): traced async backoff in retry loop

google/cloud/storage/internal/hash_function.cc, google/cloud/storage/internal/hash_function.h, google/cloud/storage/internal/hash_function_impl.cc, google/cloud/storage/internal/hash_function_impl.h, google/cloud/storage/internal/hash_function_impl_test.cc, google/cloud/storage/internal/hash_validator_test.cc, google/cloud/storage/internal/object_read_streambuf.cc, google/cloud/storage/internal/object_write_streambuf.cc
This changes the `storage::internal::HashFunction` classes to support calling them from `RawClient::InsertObjectMedia()` and `RawClient::UploadChunk()`. The new functionality is not used yet, but it is testable and thus can be merged as a separate PR.
Part of the work for #11060
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11065)
=> impl(storage): support upload hashing in `RawClient`

google/cloud/spanner/integration_tests/client_integration_test.cc
`ClientIntegrationTest.UnifiedCredentials` was overwriting the test fixture member, causing it to have (the potential of) an effect on subsequent tests.  Instead, let it operate on its own `Client`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11069)
=> test(spanner): remove test ordering problem

generator/internal/codegen_utils.cc, generator/internal/codegen_utils.h, generator/internal/codegen_utils_test.cc, generator/internal/descriptor_utils.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator.h
Motivated by #10782
Simplify `BuildNamespaces(...)` to only return the namespace we care about. I think we can assume the others. Also use the helpers that parse product paths.
This refactor should simplify the namespace logic and make it easier to insert documentation for a namespace.
For context, the full change is (more or less) here: https://github.com/dbolduc/google-cloud-cpp/tree/doc-generator-forwarding-namespaces
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11072)
=> refactor(generator): namespace printing

google/cloud/storage/client.cc, google/cloud/storage/hashing_options.cc, google/cloud/storage/idempotency_policy_test.cc, google/cloud/storage/internal/async_accumulate_read_object.cc, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_client_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_client_upload_chunk_test.cc, google/cloud/storage/internal/grpc_configure_client_context_test.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/object_requests_test.cc, google/cloud/storage/internal/object_write_streambuf.cc, google/cloud/storage/internal/object_write_streambuf.h, google/cloud/storage/internal/rest_client.cc, google/cloud/storage/internal/retry_client_test.cc
Move the CRC32C and MD5 computations to the `GrpcClient` and `RestClient`. In the case of gRPC this allows us to compute the CRC32C checksum for each `Write()` message and then concatenate this checksum with the CRC32C checksum computed for the full object.  That saves one of the most expensive computations in the gRPC uploads.
Fixes #11060
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11070)
=> feat(GCS+gRPC): more efficient CRC32C computations

google/cloud/internal/async_streaming_read_rpc_impl.h, google/cloud/internal/async_streaming_read_rpc_impl_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11076)
=> impl(otel): call context across async streaming reads

google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/streaming_read_rpc_tracing.h, google/cloud/internal/streaming_read_rpc_tracing_test.cc, google/cloud/testing_util/opentelemetry_matchers.h
Part of the work for #10619 
The event names follow this convention: https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/rpc/#events
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11075)
=> impl(otel): `StreamingReadRpcTracing`

google/cloud/status_or.h
There was an obsolete and undefined `TODO()` in the documentation for `StatusOr`. First, TODOs like these do not belong in the public documentation. Second, the TODO was obsolete since `StatusOr` uses `absl::optional<>` and therefore works with whatever `absl::optional<>` supports.
I introduce a `static_assert()` to verify `T` is not a reference type. That was never supported, and this should create a more readable error.
Finally, I made some editorial changes to the comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11083)
=> doc(common): remove undefined TODO from StatusOr

CHANGELOG.md
Make the future breaking changes section of the CHANGELOG slightly more accurate.
Also sorta organize things by library, and use `<code></code>` instead of backticks in summary titles, so it renders more nicely.
(The diff is likely unhelpful. I would just compare the before and after side-to-side)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11086)
=> cleanup: future breaking changes

google/cloud/internal/async_read_write_stream_impl.h, google/cloud/internal/async_read_write_stream_impl_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11090)
=> impl(otel): call context across async streaming read writes

google/cloud/internal/async_streaming_write_rpc_impl.h, google/cloud/internal/async_streaming_write_rpc_impl_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11091)
=> impl(otel): call context across async streaming writes

docfx/BUILD.bazel, docfx/CMakeLists.txt, docfx/docfx.bzl, docfx/doxygen2toc_test.cc, docfx/generate_metadata.cc, docfx/generate_metadata.h, docfx/generate_metadata_test.cc, docfx/parse_arguments.cc, docfx/parse_arguments_test.cc, docfx/unit_tests.bzl
The DocFX generator requires a small "docs.metadata.json" file describing the programming language, library name, and version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11093)
=> impl(docfx): generate metadata file

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11094)
=> impl(docfx): support `briefdescription` elements

docfx/CMakeLists.txt, docfx/docfx.bzl, docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc, docfx/unit_tests.bzl
Generate YAML entries for `enum` and `enumvalue`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11098)
=> impl(docfx): generate YAML for enums

google/cloud/internal/random.cc
The bug was fixed in 2020-05-19, any version released after that date should be safe.
The libstdc++ fix is https://github.com/gcc-mirror/gcc/commit/a2d196e75cef95c2b70734ad02e94f9da0e769fe
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11099)
=> cleanup: disable `std::random_device` workaround

google/cloud/internal/random.h
We initialized our PRNG with a lot of entropy. This was overkill, and the entropy sources are not always an infinite resource.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11102)
=> feat: consume less entropy for PRNG

docfx/CMakeLists.txt, docfx/docfx.bzl, docfx/doxygen2syntax.cc, docfx/doxygen2syntax.h, docfx/doxygen2syntax_test.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc, docfx/unit_tests.bzl, docfx/yaml_context.h, docfx/yaml_emit.cc, docfx/yaml_emit.h
The YAML file the reference documentation includes a `syntax` section where one includes the source code to display (think "a function declaration"), links to the source files, the definition of the function or template parameters, etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11103)
=> impl(docfx): initial generator for `syntax`

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_tracing_connection.cc, generator/integration_tests/tests/golden_kitchen_sink_tracing_connection_test.cc, generator/internal/tracing_connection_generator.cc, google/cloud/bigquery/storage/v1/internal/bigquery_read_tracing_connection.cc, google/cloud/osconfig/agentendpoint/v1/internal/agent_endpoint_tracing_connection.cc
Part of the work for #10620 
It is basically the same code as for Paginated APIs. Only the response type differs.
Note that this change only impacts generated connections. Handwritten connections like `bigtable::DataConnection` will be instrumented later. (This explains why less files are changed in this PR than the tracing stub PR (#11104))
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11106)
=> impl(otel): tracing for streaming reads in generated connections

google/cloud/internal/unified_rest_credentials_integration_test.cc
Produce more output when the `unified_rest_credentials_integration_test` fails.
Motivated by #11109
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11113)
=> test(common): more logging on failures

docfx/doxygen2syntax.cc, docfx/doxygen2syntax.h, docfx/doxygen2syntax_test.cc
The `syntax.content` attribute contains the C++ code we want to show in the reference documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11114)
=> impl(docfx): add content to enums and typedefs

ci/cloudbuild/builds/grpc-at-head.sh
Part of the work for #10323.  I also need to create a trigger to execute this nightly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11118)
=> ci: create `grpc-at-head` build script

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/defaults.cc, google/cloud/spanner/internal/defaults_test.cc, google/cloud/spanner/internal/session_pool.cc
The final glue to add a routing header to Spanner RPCs that should be served in the leader region.
For the time being, the boolean option defaults to off (set as false), but that default can be changed with a suitably-positive value for `${GOOGLE_CLOUD_CPP_SPANNER_ROUTE_TO_LEADER}`.  The conditional code can be removed to restore the defaults-to-on behavior.  See #11111.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11112)
=> feat(spanner): add the final pieces for the RouteToLeaderOption

ci/kokoro/macos/builds/bazel.sh, ci/kokoro/macos/builds/quickstart-bazel.sh, ci/kokoro/windows/lib/bazel.ps1
I am seeing too many failures in the logs, I think my timeout is too aggressive.
I am hoping this will reduce the noise in the logs, and maybe reduce the number of crashes on macOS (#8325) simply because downloading the cache takes less memory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11129)
=> ci: use default GCS timeout for Bazel cache

docfx/CMakeLists.txt
CMake is too fogiving in this case. Currently using `nlohmann::json` requires no additional compiler or linker flags. However (1) that may not be the case forever, and (2) the error messages are earier to understand if one uses `find_package()` when the package is missing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11128)
=> cleanup(docfx): missing deps in CMake script

ci/cloudbuild/cloudbuild.yaml
This will allow us to insert a custom tag in a GCB build, using the trigger configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11130)
=> ci: custom tags in GCB builds

docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc
Some things are not to be documented, e.g., the private section of a class, or the references to the C++ `std::` namespace that are created by Doxygen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11142)
=> impl(docfx): a helper to filter the public API

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11149)
=> impl(docfx): support `<ndash>` elements

google/cloud/bigquery/quickstart/README.md
Should be google rather than google
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11170)
=> doc(bigquery): typo in the quickstart path

google/cloud/bigquery/v2/minimal/internal/job_request.cc, google/cloud/bigquery/v2/minimal/internal/job_request_test.cc
It is a feature if request/response logging uses a common format no matter whether the message types are protoc generated or not.  So, update the `DebugString()` functions for `GetJobRequest` and `ListJobsRequest` to produce that common format, as if they had been defined as messages like ...
```
message GetJobRequest {
string project_id = 1;
string job_id = 2;
string location = 3;
}
message Projection {
string value = 1;
}
message StateFilter {
string value = 1;
}
message ListJobsRequest {
string project_id = 1;
bool all_users = 2;
int32 max_results = 3;
google.protobuf.Timestamp min_creation_time = 4;
google.protobuf.Timestamp max_creation_time = 5;
string page_token = 6;
Projection projection = 7;
StateFilter state_filter = 8;
string parent_job_id = 9;
}
```
In particular, …
=> impl(bigquery): unify bigquery request/response logging format

google/cloud/internal/README.md
I figured that if sometimes we put too many `o`'s in Google, sometimes we would but too few.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11173)
=> doc: fix more google typos

docfx/doxygen2syntax.cc, docfx/doxygen2syntax_test.cc
Constructors have an empty `<type>` element, clean up the output for this case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11174)
=> impl(docfx): improve syntax for constructors

google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake, google/cloud/storage/internal/async_accumulate_read_object.cc, google/cloud/storage/internal/async_accumulate_read_object_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_ctype_cord_workaround.h, google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/grpc_object_read_source_test.cc
With Protobuf < v23.x the effect of adding a `[ctype = CORD]` annotation is to make the accessors and modifiers for the field private. We expect that most, but not *all*, customers will use GCS+gRPC with Protobuf >= v23.x. With that version of Protobuf the field accessors and modifiers are public, and they return/consume `absl::Cord`.  To support customers using older Protobuf versions we implement a workaround to gain access to these private accessors and modifiers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11175)
=> impl(GCS+gRPC): workarounds related to ctype=CORD

google/cloud/storage/internal/grpc_object_read_source_test.cc
One more allowance for `absl::Cord` conversion missed in #11175.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11184)
=> cleanup(GCS+gRPC): workarounds related to ctype=CORD

google/cloud/bigquery/v2/minimal/internal/job_request.cc, google/cloud/internal/debug_string.cc, google/cloud/internal/debug_string.h, google/cloud/internal/debug_string_test.cc
Follow up on a @coryan idea from #11172 for a `DebugFormatter` to produce request/response-logging strings for non-protobuf message types.
Use `DebugFormatter` to reimplement the message formatters from #11172.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11182)
=> impl(common): add formatter for request/response logging

generator/internal/discovery_resource.cc, generator/internal/discovery_resource_test.cc
If an rpc returns `Operation` but does not specify zone or region, we should default to global instead of returning an error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11177)
=> impl(generator): default operation scope to global

docfx/doxygen2docfx.cc, docfx/doxygen2toc.cc, docfx/doxygen2toc_test.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc, docfx/toc_entry.h
This generates the ToC for C++ entities, starting with namespaces.
Part of the work for #10895 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11189)
=> impl(docfx): generate ToC for C++ entities

ci/cloudbuild/builds/checkers.sh
If `ci/cloudbuild/builds/checkers.sh` finds any diffs, exit with a (hopefully) distinctive status (instead of 1) so that callers might distinguish formatting corrections (e.g., `clang-format`) from hard errors (e.g., `shellcheck`).
This will help me stop pushing commits with `typos` errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11193)
=> ci: exit with a distinctive status on checkers differences

generator/internal/discovery_resource.cc, generator/internal/discovery_resource.h, generator/internal/discovery_resource_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11186)
=> impl(generator): support generating proto rpcs with empty requests

ci/cloudbuild/dockerfiles/fedora-m32.Dockerfile
Motivated by #11156 
opentelemetry-cpp does not have a binary package we can just install. So we have to build the code using our m32 toolchain.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11196)
=> ci: build otel with m32

google/cloud/bigquery/v2/minimal/internal/job_request.cc, google/cloud/bigquery/v2/minimal/internal/job_request.h, google/cloud/bigquery/v2/minimal/internal/job_request_test.cc, google/cloud/internal/debug_string.cc, google/cloud/internal/debug_string.h, google/cloud/internal/debug_string_test.cc
- composable support for sub-messages: `SubMessage()` can now use the `DebugString()` of the sub field to build the upper `DebugString()`. This requires `DebugString()` to now take a name, which should either be the top-most class name or an inner field name.
- direct support for `time_point` fields: Match the auto formatting of `Timestamp` proto messages as human-readable strings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11197)
=> impl(common): enhance DebugFormatter support

google/cloud/internal/curl_wrappers.cc, google/cloud/internal/curl_wrappers_test.cc
The HTTP status line is returned as one of the headers. We were not removing the trailing newline from it, resulting in log split across multiple lines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11202)
=> fix(rest): remove newlines from 'status' header

google/cloud/internal/grpc_opentelemetry.cc, google/cloud/internal/grpc_opentelemetry_test.cc
As @coryan noticed, I was assuming the string views were null terminated in `MakeSpanGrpc()`. (@devbww has also warned in the past that `sv.data()` without `sv.size()` is a red flag).
So fix it, and add a regression test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11208)
=> fix(otel): handle non-null terminated string_views

ci/cloudbuild/builds/publish-docs.sh, cmake/GoogleCloudCppDoxygen.cmake, google/cloud/opentelemetry/CMakeLists.txt, google/cloud/opentelemetry/google_cloud_cpp_opentelemetry_sdk.bzl, google/cloud/opentelemetry/trace_exporter.h
Generate documentation for `google/cloud/opentelemetry`. This is what the docs would look like if we had a public class: [otel_sdk_example.pdf](https://github.com/googleapis/google-cloud-cpp/files/11180893/otel_sdk_example.pdf). (Note that the interface will change).
Abstract Doxygen's CLANG_OPTIONS ever so slightly.
Without the `trace_exporter.h` file, Doxygen would not have any input. (It skips `internal/` directories). And if Doxygen does not have input, it throws an error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11207)
=> impl(otel): docs for opentelemetry_sdk

google/cloud/internal/log_impl.cc, google/cloud/internal/log_impl.h, google/cloud/internal/log_impl_test.cc, google/cloud/log.cc
This is a variant of the "lastN" logger. It only dumps the lastN log lines *in the thread* when the library or application creates a log line over a minimum severity threshold. This is an improvement over the "lastN" logger, which dumps the last N logs from all the threads in similar circumstances.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11200)
=> feat(common): a "lastN in thread" logger

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
Part of the work for #10895 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11210)
=> impl(docfx): support xrefsect in markdown

vcpkg.json
This file is only used by `google-cloud-cpp` contributors using CMake as the build system, and vcpkg as the package manager to find dependencies. The existing comments and descriptions gave the impression that it could be used for other purposes.  I also included a new dependency on opentelemetry-cpp.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11213)
=> chore(deps): update vcpkg.json file

docfx/doxygen2markdown.cc, docfx/doxygen2markdown_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11218)
=> impl(docfx): add tile to 'see also' sections

docfx/doxygen2yaml.cc, docfx/doxygen2yaml_test.cc
Sometimes there is a `<description>` node, just make it part of the summary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11216)
=> impl(docfx): include `<description>` in summary

docfx/doxygen2docfx.cc, docfx/doxygen2yaml_test.cc
My plan to use the ToC entries in driving the file generation does not work. We need all compounddef generated so the cross-references work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11219)
=> impl(docfx): generate files for every compounddef

google/cloud/internal/opentelemetry.h
The `EndSpan()` function consumes (and returns) a `StatusOr<T>`. That should be captured by value. There are the usual performance reasons, but also `T` may not satisfy the `std::copyable<>` concept.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11220)
=> impl(otel): pass-by-value in `EndSpan()`

google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable.h, google/cloud/opentelemetry/internal/recordable_test.cc
The `google::devtools::v2::Span` proto has several such `TruncatableString` fields. Add a helper for setting them.
I will remove the `TEST(Recordable, Compiles)` later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11221)
=> impl(otel): add TruncatableString helper

google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable.h, google/cloud/opentelemetry/internal/recordable_test.cc
Part of the work for #11156
Implement `Recordable::SetName()`. Also add a method to extract the underlying `Span` proto from the `Recordable`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11229)
=> impl(otel): Recordable set display name

generator/internal/descriptor_utils.cc
Without this change, generating the libraries triggers this:
https://github.com/googleapis/google-cloud-cpp/blob/30872a70a880349f1c25ae9261794d6a133b6ef6/generator/standalone_main.cc#L416
I am not sure how that went unnoticed through the CI builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11230)
=> cleanup(generator): remove unused substitution

google/cloud/google_cloud_cpp_rest_internal.bzl, google/cloud/google_cloud_cpp_rest_internal.cmake, google/cloud/google_cloud_cpp_rest_internal_unit_tests.bzl, google/cloud/internal/tracing_rest_response.cc, google/cloud/internal/tracing_rest_response.h, google/cloud/internal/tracing_rest_response_test.cc
We need to wrap the `RestResponse` object to create `TracingRestHttpPayload`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11246)
=> impl(otel): wrap `rest_internal::RestResponse`

google/cloud/testing_util/status_matchers.h, google/cloud/testing_util/status_matchers_test.cc
Given, say, `StatusOr<int> i = ...`, this will allow us to write
```
EXPECT_THAT(i, IsOkAndHolds(Ge(0)));
```
instead of
```
ASSERT_THAT(i, IsOk());
EXPECT_THAT(*i, Ge(0));
```
Fixes #5606.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11250)
=> test: add IsOkAndHolds(m) matcher for StatusOr<T>

google/cloud/internal/rest_request.cc, google/cloud/internal/rest_request_test.cc
The constructors consumed headers but did not normalize them to lowercase. These are internal-only APIs and rarely used, so I think it is harmless.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11258)
=> fix(rest): normalize headers in `RestRequest`

google/cloud/internal/rest_opentelemetry.cc, google/cloud/internal/rest_opentelemetry_test.cc, google/cloud/internal/tracing_http_payload.cc, google/cloud/internal/tracing_http_payload_test.cc, google/cloud/internal/tracing_rest_response_test.cc
The UI is not that helpful for events vs. spans.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11257)
=> impl(otel): use spans for HttpPayload::Read

CMakeLists.txt, ci/cloudbuild/builds/publish-docs.sh, ci/cloudbuild/dockerfiles/fedora-37-cmake.Dockerfile, cmake/GoogleCloudCppDoxygen.cmake, cmake/GoogleCloudCppFeatures.cmake, docfx/README.md
This creates CMake targets to create the DocFX YAML files. I cannot enable this in the build (yet), because the docfx tool needs more work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11270)
=> ci: initial support to automate DocFX generation

generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, google/cloud/storage/internal/storage_metadata_decorator.cc
Bandaid for #11253 Or maybe "fixes". It buys us some time, at least.
Check to see if a `*` is followed by a `:` when turning a routing pattern into a regular expression. There is a slight complication in that we might interject a `)` to signify the capture group.
We still default to map `*` -> `[^/]+`. Several routing patterns end on a single asterisk, and that seems to be the right default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11273)
=> fix(generator): routing headers handle colon

google/cloud/storage/internal/grpc_configure_client_context.cc, google/cloud/storage/internal/grpc_configure_client_context_test.cc
This is the analog of #11253 for one RPC that needs hand-crafted metadata decoration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11272)
=> impl(GCS+gRPC): alternative routing format for upload id

google/cloud/storage/oauth2/service_account_credentials.cc, google/cloud/storage/oauth2/service_account_credentials.h, google/cloud/storage/oauth2/service_account_credentials_test.cc
I think we missed the caching feature during the multiple refactorings. The test is (maybe) not ideal, but the API is not easy to test, and we do not want to change it.
Fixes #11194
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11271)
=> fix(storage): cache legacy credentials

google/cloud/internal/rest_opentelemetry.cc, google/cloud/internal/rest_opentelemetry.h, google/cloud/internal/rest_opentelemetry_test.cc, google/cloud/internal/tracing_http_payload.cc, google/cloud/internal/tracing_http_payload_test.cc, google/cloud/internal/tracing_rest_client.cc, google/cloud/internal/tracing_rest_client_test.cc, google/cloud/internal/tracing_rest_response_test.cc
Using a separate span to handle the HTTP response / payload is not a good representation of the flow. A single span that lasts (but it is not necessarily active) until the full payload is received seems like a better model of the actual code flow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11274)
=> impl(otel): single span for each HTTP request

CHANGELOG.md
Should have been a part of #11180.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11281)
=> doc: announce servicecontrol/v2 support in the CHANGELOG

google/cloud/opentelemetry/BUILD.bazel, google/cloud/opentelemetry/CMakeLists.txt, google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable.h, google/cloud/opentelemetry/internal/recordable_test.cc
Implement `Recordable::SetAttribute`. The main work is implementing a helper to set the `google::devtools::cloudtrace::v2::Attributes` field. THe helper will be used by other member functions (`AddEvent`, `AddLink`, etc.).
Is using `std::ostringstream` the best way to convert a double to a string? `to_string(x)` gave me a bunch of decimals.
Of note, the exporter spec will require us to map OpenTelemetry semantic conventions for attribute names to Cloud Trace semantic conventions. For example, "http.host" -> "/http/host". This work will come later. There is enough going on in this PR already.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-c …
=> impl(otel): Recordable can set attributes

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/bytes_test.cc, google/cloud/spanner/client_test.cc, google/cloud/spanner/database_admin_client_test.cc, google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/instance_admin_connection_test.cc, google/cloud/spanner/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/integration_tests/client_integration_test.cc, google/cloud/spanner/integration_tests/data_types_integration_test.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/internal/merge_chunk_test.cc, google/cloud/spanner/numeric_test.cc, google/cloud/spanner/row_test.cc, google/cloud/spanner/value_test.cc
This started out as an exercise to use IsOkAndHolds(m) within the Spanner tests, just to make sure it was working as intended, but soon turned into a cleanup for other assert/expect mismatches.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11262)
=> test(spanner): make use of the IsOkAndHolds() StatusOr<T> matcher

google/cloud/opentelemetry/BUILD.bazel, google/cloud/opentelemetry/CMakeLists.txt, google/cloud/opentelemetry/google_cloud_cpp_opentelemetry_sdk.bzl, google/cloud/opentelemetry/opentelemetry_sdk_unit_tests.bzl, google/cloud/opentelemetry/trace_exporter.cc, google/cloud/opentelemetry/trace_exporter.h, google/cloud/opentelemetry/trace_exporter_test.cc
Implement the Trace Exporter. It is not useful until we write span IDs into the `Recordable` class though. The feature is marked as experimental, so I am ok with having a partial implementation.
The `static_cast` could use another set of eyes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11283)
=> impl(otel): add the Trace Exporter

google/cloud/bigquery/BUILD.bazel, google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_testing.bzl, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/v2/minimal/internal/bigquery_http_response.cc, google/cloud/bigquery/v2/minimal/internal/bigquery_http_response.h, google/cloud/bigquery/v2/minimal/internal/job_logging.cc, google/cloud/bigquery/v2/minimal/internal/job_logging_test.cc, google/cloud/bigquery/v2/minimal/testing/mock_job_log_backend.h
This is the final PR for the logging decorator cleanup and fixes #11122
This PR integrates request and response logging with tracing options in the logging decorator and adds unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11223)
=> impl(bigquery): Logging Decorator Cleanup: Added request and response logging to logging decorator

google/cloud/bigquery/v2/minimal/internal/job_request.cc, google/cloud/bigquery/v2/minimal/internal/job_request.h, google/cloud/bigquery/v2/minimal/internal/job_request_test.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.h, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_factory.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc
Addressing some of the remaining cleanup items for the Job apis
This PR fixes Github issue#11123 and addresses the following changes with regards to Job Requests and stub
1) Removed passing of options to BuildRestRequest and Default job stub, to be consistent with other apis.
2) Made min_creation_time and max_creation_time optional so they can be checked and set easiy in request parameters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11224)
=> impl(bigquery): Addresses remaining cleanup items for job apis

ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
Hi!
The Dockerfile placed at "ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile" contains the best practice violation [DL3007](https://github.com/hadolint/hadolint/wiki/DL3007) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3007 occurs when the tag "latest" is used instead of a specific version tag for the base image.
In this pull request, we propose a fix for that smell generated by our fixing tool. We have verified that the patch is correct before opening the pull request.
To fix this smell, specifically, we use a heuristic approach that selects the most probable version tag for the base image in order to replace the "latest" tag. In detail, it selects the most recent image tag which corresponds to the same image digest that currently …
=> cleanup: Dockerfile smell DL3007

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
Part of the work for #11245
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11300)
=> impl(docfx): support `<parblock>` elements

google/cloud/opentelemetry/BUILD.bazel, google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable_test.cc
Implements `SetStatus`, `SetSpanKind`, `SetInstrumentationScope`.
The remaining member functions are busy enough to warrant their own PRs.
- `AddLink`
- `AddEvent`
- `SetResource`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11299)
=> impl(otel): implement `Recordable` status, kind, scope

google/cloud/internal/curl_http_payload.cc, google/cloud/internal/curl_http_payload.h, google/cloud/internal/curl_rest_client.cc, google/cloud/internal/curl_rest_client.h, google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/internal/http_payload.h, google/cloud/internal/tracing_http_payload.cc, google/cloud/internal/tracing_http_payload.h, google/cloud/testing_util/mock_http_payload.h
I had to add a new member function to `HttpPayload` to implement tests without a `dynamic_cast<>`.  Probably a "Good Thing"[tm].
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11280)
=> impl(otel): create wrapped `RestClient`

google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable.h, google/cloud/opentelemetry/internal/recordable_test.cc
The `opentelemetry::common::KeyValueIterable` interface is... something...
https://github.com/open-telemetry/opentelemetry-cpp/blob/7cb7654552d68936d70986bc2ee67f3cc3e0b469/api/include/opentelemetry/common/key_value_iterable.h#L13-L34
I could not find any helpers that they offer to construct one easily, so I had to extend the class myself in the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11302)
=> impl(otel): Recordable add links

CMakeLists.txt, ci/cloudbuild/builds/clang-tidy.sh, ci/cloudbuild/builds/publish-docs.sh, cmake/GoogleCloudCppDoxygen.cmake, cmake/GoogleCloudCppFeatures.cmake, doc/compile-time-configuration.md, docfx/CMakeLists.txt
Running the `doxygen2docfx` tool in each PR will ensure we do not regress w.r.t. supporting all the libraries in the tool. We also need to run the tool to (eventually) upload the documents to start the publication pipeline, so this is a good place to run them.
I had to change how the tool is integrated into CMake. It cannot be a "feature" (an element in the `GOOGLE_CLOUD_CPP_ENABLE` list) because CMake needs to configure the `docfx/` directory before the `google/cloud/` directory and the features always go afted `google/cloud/`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11315)
=> ci: publish-docs always run DocFX generation

docfx/doxygen2docfx.cc, docfx/doxygen2toc.cc, docfx/doxygen2toc_test.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml_test.cc, docfx/doxygen_groups.cc, docfx/doxygen_groups_test.cc, docfx/doxygen_pages.cc, docfx/doxygen_pages_test.cc, docfx/toc_entry.h
Start the table of contents (TOC) with the `indexpage` and use
`index.md` as the output file for that page. Doxygen uses `indexpage`
for the landing page, the cloud site uses `index.md`.
Move the namespaces up in the TOC, and use the C++ name (instead of the
Doxygen uid) as the name of the TOC entry.
Move the groups down in the TOC, and use the group title as the name of
the TOC entry.
Keep the TOC entries sorted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11319)
=> impl(docfx): iterate on TOC

generator/internal/descriptor_utils.cc, generator/internal/pagination.cc, generator/internal/pagination.h, generator/internal/pagination_test.cc, google/cloud/sql/README.md, google/cloud/sql/quickstart/quickstart.cc, google/cloud/sql/v1/internal/sql_instances_rest_connection_impl.cc, google/cloud/sql/v1/internal/sql_instances_rest_connection_impl.h, google/cloud/sql/v1/internal/sql_instances_tracing_connection.cc, google/cloud/sql/v1/internal/sql_instances_tracing_connection.h, google/cloud/sql/v1/internal/sql_operations_rest_connection_impl.cc, google/cloud/sql/v1/internal/sql_operations_rest_connection_impl.h, google/cloud/sql/v1/internal/sql_operations_tracing_connection.cc, google/cloud/sql/v1/internal/sql_operations_tracing_connection.h, google/cloud/sql/v1/mocks/mock_sql_instances_connection.h, google/cloud/sql/v1/mocks/mock_sql_operations_connection.h, google/cloud/sql/v1/sql_instances_client.cc, google/cloud/sql/v1/sql_instances_client.h, google/cloud/sql/v1/sql_instances_connection.cc, google/cloud/sql/v1/sql_instances_connection.h, google/cloud/sql/v1/sql_instances_connection_idempotency_policy.cc, google/cloud/sql/v1/sql_instances_connection_idempotency_policy.h, google/cloud/sql/v1/sql_operations_client.cc, google/cloud/sql/v1/sql_operations_client.h, google/cloud/sql/v1/sql_operations_connection.cc, google/cloud/sql/v1/sql_operations_connection.h, google/cloud/sql/v1/sql_operations_connection_idempotency_policy.cc, google/cloud/sql/v1/sql_operations_connection_idempotency_policy.h
PR is split into multiple commits for readability.
Modified the generator to check for the alternate pagination mechanism utilized by sql and compute in the case where AIP-4233 pagination is not detected. This cascaded into refactoring the sql quickstart which uses the List method (which is now paginated).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11318)
=> impl(generator): add alternate pagination support

google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable.h, google/cloud/opentelemetry/internal/recordable_test.cc
Part of the work for #11156
The interesting thing here is that we have a choice about whether to call events `Annotation`s vs. `MessageEvent`s. (There are differences in how they render in the UI, and the amount you can set per span).
The other exporters call everything `Annotation`s, so that is what we do here. If we decide to use `MessageEvent`s in the future, this PR is still a good first step.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11321)
=> impl(otel): Recordable add event

google/cloud/iam/doc/iam-credentials-mock.dox, google/cloud/iam/doc/iam-mock.dox, google/cloud/iam/samples/iam_credentials_samples.cc, google/cloud/iam/samples/iam_samples.cc, google/cloud/iam/samples/mock_iam.cc, google/cloud/iam/samples/mock_iam_credentials.cc
Is anyone concerned that we are recommending both
- `namespace iam = ::google::cloud::iam_admin_v1` and
- `namespace iam = ::google::cloud::iam_credentials_v1` ?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11328)
=> cleanup(iam): versioned clients in samples

google/cloud/bigquery/doc/bigquery-read-mock.dox, google/cloud/bigquery/samples/bigquery_read_samples.cc, google/cloud/bigquery/samples/mock_bigquery_read.cc
Fixes #10170
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11329)
=> cleanup(bigquery): use versioned clients in samples

google/cloud/internal/curl_handle.cc, google/cloud/internal/curl_handle.h, google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h, google/cloud/internal/curl_rest_client.cc, google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/internal/rest_context.h
This changes the `RestClient` implementation to capture each request metadata, such as the IP addresses and ports used in the request. The main motivation is to include this information in OTel tracing attributes, but could be used for other troubleshooting too.
Part of the work for #11264
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11331)
=> impl(rest): capture request metadata

google/cloud/spanner/client.h, google/cloud/spanner/options.h, google/cloud/spanner/partition_options.h, google/cloud/spanner/query_partition.h, google/cloud/spanner/read_partition.h
- Move the `@name` for `ClientOptions` compatibility calls to within the doxygen group, just like all the other such groups.
- Clarify that the compute resources used for the "DataBoost" feature are independent of Spanner, rather than some special category of "independent" resources supplied by Spanner.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11345)
=> cleanup(spanner): some accumulated Spanner comment cleanup

google/cloud/internal/tracing_rest_client.cc, google/cloud/internal/tracing_rest_client_test.cc
Part of the work for #11264
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11332)
=> impl(otel): set the tracing scope on HTTP requests

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc, google/cloud/spanner/integration_tests/session_pool_integration_test.cc, google/cloud/spanner/internal/session_pool.cc, google/cloud/spanner/internal/session_pool_test.cc, google/cloud/spanner/options.h
`BatchCreateSessions()` calls made during the `SessionPool` callback chain depend on the prevailing options to determine whether the RPC should be routed to a region leader.  So, we need to ensure that the construction-time options are propagated through those callbacks by instantiating `OptionsSpan` objects when appropriate.
Add similar `OptionsSpan` objects to `session_pool_integration_test.cc`, which uses "FriendForTest" access to reach into `SessionPool`, bypassing the normal span instantiation.
Add unit tests to verify that the "x-goog-spanner-route-to-leader" header is now set appropriately when the `RouteToLeaderOption` is both enabled and disabled.
Add `RouteToLeaderOption` to the `SessionPoolOptionList`, marking it as a valid option to pass to `spanner::MakeConnection()`.
Also …
=> fix(spanner): propagate Options through SessionPool callbacks

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/job_logging.cc, google/cloud/bigquery/v2/minimal/internal/log_wrapper.h
Refactored JobLogWrapper template function to a separate header so it can be used from multiple places e.g. dataset logging decorator
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11350)
=> impl(bigquery): refactored JobLogWrapper template function

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc
GCS+gRPC performs much better if the upload buffers are at least 32MiB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11351)
=> impl(GCS+gRPC): larger `UploadBufferSizeOption`

generator/internal/discovery_file_test.cc, generator/internal/discovery_resource_test.cc, generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto_test.cc, generator/internal/discovery_type_vertex.cc, generator/internal/discovery_type_vertex.h, generator/internal/discovery_type_vertex_test.cc
part of the work for #11353 
This is the first of several PRs to add package name handling so that we correctly qualify types when we emit protos. In order to keep the PRs small, I had to temporarily disable some tests and add overloads that will be shortly removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11349)
=> impl(generator): add package support to DiscoveryVertexType

google/cloud/internal/tracing_rest_client.cc, google/cloud/internal/tracing_rest_client_test.cc
With this change the `TracingRestClient` always includes the `x-cloud-trace-context` header and any other configured tracing propagators.
Fixes #11264
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11352)
=> impl(otel): `TracingRestClient` tracing propagation

ci/cloudbuild/builds/lib/integration.sh, google/cloud/opentelemetry/CMakeLists.txt, google/cloud/opentelemetry/configure_basic_tracing.cc, google/cloud/opentelemetry/configure_basic_tracing.h, google/cloud/opentelemetry/google_cloud_cpp_opentelemetry.bzl, google/cloud/opentelemetry/integration_tests/CMakeLists.txt, google/cloud/opentelemetry/integration_tests/configure_basic_tracing_integration_test.cc, google/cloud/opentelemetry/integration_tests/tests.bzl
For many applications we can provide a one-liner that initializes OpenTelemetry. Some applications will need more elaborate initialization, but making things easy for the common case is valuable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11359)
=> impl(otel): a simplified tracing initializer

ci/cloudbuild/builds/lib/integration.sh
Cease to run the OpenTelemetry integration tests against production for each GCB bazel build that uses `lib/integration.sh`.
Note that the tests still run as part of `integration-production`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11367)
=> ci(otel): reduce Cloud Trace quota usage

google/cloud/internal/tracing_rest_client.cc, google/cloud/internal/tracing_rest_client_test.cc
Sending a HTTP request can take a while and create confusing spans in the overall request. I also think using events to represent the connection setup steps (name lookup, tcp connection, and SSL handshakes) is a cleaner representation than custom attributes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11365)
=> impl(otel): add span while HTTP sends a request

google/cloud/opentelemetry/integration_tests/configure_basic_tracing_integration_test.cc, google/cloud/opentelemetry/integration_tests/trace_exporter_integration_test.cc
Use the `GetTrace()` API in the Cloud Trace integration tests. This has 1/25th the quota cost of the `ListTraces` APi.
Also, use an initial backoff before sending the first RPC. From my minimal testing
- `ListTraces` would take 3-7s to propagate
- `GetTrace` would take 1-3s to propagate
.... so by adding an initial sleep, we are probably saving another 1/3 of quota usage.
---
Also standardize the two tests a bit.
I despise code duplication, and I would typically refactor before sending such a PR.... But given that this PR makes us something like 75x less likely to hit quota and I have to sign off for the day.... I am sending the PR now and refactoring later.
- - - …
=> ci(otel): further reduce Cloud Trace quota usage

generator/internal/discovery_file.cc, generator/internal/discovery_file.h, generator/internal/discovery_resource.h, generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc
In order to make both the type name and package name available, `DetermineAndVerifyResponseType` now returns a pointer to the type object instead of just the type_name.
Also changed DiscoveryFile::WriteFile to accept types by const& as std::async is happy to accept a const& arg without leaning on std::ref.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11384)
=> impl(generator): finish package naming support

generator/CMakeLists.txt, generator/google_cloud_cpp_generator.bzl, generator/internal/discovery_document.h, generator/internal/discovery_file.cc, generator/internal/discovery_file.h, generator/internal/discovery_file_test.cc, generator/internal/discovery_resource.cc, generator/internal/discovery_resource.h, generator/internal/discovery_resource_test.cc, generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc
fixes #11377 
Some classes were holding top level document properties as member variables. As most such properties were strings this led to constructors with lots of repeated strings, reducing readability and introducing potential sources of future errors. In order to remedy this, member variables were removed from classes where it made sense and are now instead passed only to the methods that needed them via the existing `DiscoveryDocumentProperties` struct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11391)
=> refactor(generator): replace multistring constructors with struct parameter

.bazelrc, BUILD.bazel, ci/cloudbuild/builds/otel-disabled-bazel.sh, google/cloud/BUILD.bazel, google/cloud/opentelemetry/BUILD.bazel, google/cloud/opentelemetry/integration_tests/BUILD.bazel
Add an experimental top level bazel target for the opentelemetry exporter library. This requires renaming the flag that builds common with a dep on `opentelemetry-cpp`.
Naming continues to be hard. I don't love that `//:enable-experimental-opentelemetry` is independent of `//:experimental-opentelemetry`, but oh well.
The best alternatives I came up with for the `bool_flag`s were:
- `//:experimental-opentelemetry_instrumentation`
- `//:enable-experimental-opentelemetry_instrumentation`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11389)
=> impl(otel): add top level target; rename bool_flag

docfx/.clang-tidy, docfx/doxygen2markdown.cc, docfx/doxygen_pages.cc
We generate small doxygen "pages" to host the examples showing how to override the default endpoint and/or authentication mechanism. Listing these pages in the TOC just clutters things. I am adopting a convention that all (and only) generated pages will use `::` as part of their uid.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11415)
=> impl(docfx): skip generated pages

docfx/doxygen2syntax.cc, docfx/doxygen2syntax_test.cc, docfx/doxygen2yaml_test.cc, docfx/testing/inputs.cc, docfx/testing/inputs.h
The DocFX templates support both `return` and `returns`, but `returns` seems to work better. It does require putting the return type in a sequence (I think to work with languages where you may return multiple types).
The fields used by the DocFX templates are `id`, `var_type`, and `description`. With these changes the function parameters should have better documentation.
The `var_type` needs to be HTML-escaped to render C++ templates correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11413)
=> impl(docfx): improve function return and parameters

docfx/doxygen2markdown.cc, docfx/doxygen2markdown_test.cc, docfx/doxygen2syntax.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11418)
=> impl(docfx): escape text in `<ulink>` elements

google/cloud/storage/grpc_plugin_test.cc, google/cloud/storage/internal/hybrid_client.cc
This is mostly to use the right default buffer sizes for uploads and downloads.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11419)
=> impl(GCS+gRPC): use gRPC options in hybrid client

google/cloud/opentelemetry/integration_tests/configure_basic_tracing_integration_test.cc, google/cloud/opentelemetry/integration_tests/trace_exporter_integration_test.cc
Also, just remove the `StartSpanOptions` which we weren't using, lol.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11397)
=> test(otel): more integration tests for basic tracing configuration

google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable_test.cc
Mini cleanup. The version is an optional argument to create a tracer. So there's no point in adding an empty attribute for it when it is not set.
Also rename the keys. The names are shorter. The Go exporter uses these names at HEAD. I think the exporter spec is just stale.
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/327f5866b4fc60227d44c666c9ccb160a8ef9bf6/exporter/trace/trace_proto.go#L68-L69
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11424)
=> cleanup(otel): instrumentation scope

google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable_test.cc
Translate between OpenTelemetry semantic conventions for attribute names and Cloud Trace semantics for labels.
This is probably a "big whoop". I suspect it will matter more when we get into monitored resources. As far as I can tell this is the only difference:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11425)
=> impl(otel): map attribute keys

generator/integration_tests/tests/golden_kitchen_sink_connection_test.cc, generator/integration_tests/tests/golden_kitchen_sink_stub_factory_test.cc, generator/integration_tests/tests/golden_kitchen_sink_tracing_connection_test.cc, generator/integration_tests/tests/golden_thing_admin_connection_test.cc, generator/integration_tests/tests/golden_thing_admin_stub_factory_test.cc, generator/integration_tests/tests/golden_thing_admin_tracing_connection_test.cc, google/cloud/internal/async_polling_loop_test.cc, google/cloud/internal/async_rest_polling_loop_test.cc, google/cloud/internal/async_rest_retry_loop_test.cc, google/cloud/internal/async_retry_loop_test.cc, google/cloud/internal/grpc_opentelemetry_test.cc, google/cloud/internal/opentelemetry_test.cc, google/cloud/internal/rest_retry_loop_test.cc, google/cloud/internal/retry_loop_test.cc, google/cloud/storage/internal/retry_client_test.cc, google/cloud/testing_util/opentelemetry_matchers.cc, google/cloud/testing_util/opentelemetry_matchers.h
Use a single source to produce testing options that have tracing enabled/disabled. (Except in the test for `TracingEnabled()`.
This saves some future refactoring, if we change the tracing enabled formula. (e.g. if we move `OpenTelemetryTracingOption` out of internal).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11420)
=> refactor(otel): tests use abstract tracing Options

ci/cloudbuild/builds/publish-docs.sh, cmake/GoogleCloudCppDoxygen.cmake
Change the build to start the publication of DocFX documents for `common`, `kms`, and `secretmanager`. Once these work we will add additional libraries in a series of PRs. . The reference docs are not public yet, but fine tuning the output is easier if they are published internally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11427)
=> ci: initial docfx publication pipeline

docfx/doxygen_pages.cc, docfx/doxygen_pages_test.cc
Skipping pages with `::` in their id does not work because the snippet pages have `::` in their **name**. I realized that all the snippet pages that we generate have a more obvious pattern to search for, so let's use that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11432)
=> impl(docfx): another TOC cleanup attempt

ci/cloudbuild/builds/publish-docs.sh, google/cloud/opentelemetry/trace_exporter.h
In order to upload the docs for `experimental-opentelemetry`, we must drop the `experimental-` prefix.
Previously, `publish-docs` would say:
```
2023-04-28T18:35:47Z (+1000s): Directory not found: cmake-out/google/cloud/experimental-opentelemetry/html, skipping
```
e.g. https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/11433/5c9cb195cef4fd14d845a55f9eb6a6ee6eee0985/fedora-37-cmake-publish-docs/log-61f41343-0f05-4477-8dc4-c491a50276fa.txt
Now it says:
```
--------------------------------------------------
|   Uploading docs: google-cloud-opentelemetry   |
--------------------------------------------------
2023-04-28T17:08:49Z (+978s): docs_dir=cmake-out/google/cloud/opentelemetry/html
docuploader > Wrote metadata to …
```
=> docs(otel): upload docs

google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/streaming_write_rpc_tracing.h, google/cloud/internal/streaming_write_rpc_tracing_test.cc
If I don't get around to it, the corresponding change in the generator is here: https://github.com/dbolduc/google-cloud-cpp/tree/otel-streaming-write-stub
Leads to traces like:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11440)
=> impl(otel): streaming write tracing wrapper

ci/cloudbuild/builds/bazel-oldest.sh
This will simplify adoption by one of our customers and ease the transition to GCS+gRPC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11443)
=> ci: extend Bazel 4.2 testing for one release

README.md, ci/cloudbuild/builds/checkers.sh, google/cloud/opentelemetry/README.md, google/cloud/opentelemetry/quickstart/quickstart.cc, google/cloud/storage/README.md, google/cloud/storage/quickstart/quickstart.cc, google/cloud/storage/quickstart/quickstart_grpc.cc
This simplifies flow control in the opentelemetry quickstart. For consistency, it also fixes the storage quickstart.
I updated the opentelemetry README to inject the quickstart code too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11446)
=> doc: another pass over opentelemetry quickstart

google/cloud/internal/curl_rest_client.cc, google/cloud/internal/curl_rest_client.h, google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/internal/rest_context.h, google/cloud/storage/internal/bucket_acl_requests.h, google/cloud/storage/internal/bucket_requests.cc, google/cloud/storage/internal/bucket_requests.h, google/cloud/storage/internal/default_object_acl_requests.h, google/cloud/storage/internal/hmac_key_requests.h, google/cloud/storage/internal/object_acl_requests.h, google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/rest_client.cc, google/cloud/storage/internal/rest_client_test.cc, google/cloud/storage/internal/sign_blob_requests.h
With the `rest_internal::RestClient` implementation we were not respecting some per-request options. This changes the implementation of `rest_internal::RestClient` to use the options provided in `rest_internal::RestContext`. That seemed cleaner than using the options span.
I gave myself some leeway by adding default constructors to some `storage::internal::*Request` classes. It makes it easier to write unit tests where the contents of the request are uninteresting.
I included an integration test in `rest_internal::RestClient`.
Fixes #11441
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11445)
=> fix(storage): support per-request options

google/cloud/storage/oauth2/authorized_user_credentials.cc, google/cloud/storage/oauth2/authorized_user_credentials.h, google/cloud/storage/oauth2/authorized_user_credentials_test.cc, google/cloud/storage/oauth2/compute_engine_credentials.cc, google/cloud/storage/oauth2/compute_engine_credentials.h, google/cloud/storage/oauth2/compute_engine_credentials_test.cc
Applications may call `AuthorizedHeader()` and that can generate calls to the GCE metadata service or Google's Security Token Service.
Fixes #11442
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11447)
=> fix(storage): cache all credential types

google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc, google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h, google/cloud/bigquery/v2/minimal/internal/common_v2_resources_test.cc, google/cloud/bigquery/v2/minimal/internal/dataset.cc, google/cloud/bigquery/v2/minimal/internal/dataset.h, google/cloud/bigquery/v2/minimal/internal/dataset_response_test.cc, google/cloud/bigquery/v2/minimal/internal/dataset_test.cc, google/cloud/bigquery/v2/minimal/internal/table_schema.cc, google/cloud/bigquery/v2/minimal/internal/table_schema.h
This PR contains following refactor/cleanup specific to Dataset and Table custom classes
1) Deduplicated common resources used by both Dataset and Table classes by moving them to common_v2_resources.h
2) Cleanup of enum values
3) Added unit tests for the resources moved to common_v2_resources
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11465)
=> impl(bigquery): Dataset and Table classes cleanup

google/cloud/internal/rest_stub_helpers.cc, google/cloud/internal/rest_stub_helpers.h
Use the canonical include syntax and namespace qualification for Google Protobuf references so that downstream code-rewriting rules are applied correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11471)
=> cleanup: use canonical references to google protobuf

google/cloud/internal/minimal_iam_credentials_stub.cc, google/cloud/internal/minimal_iam_credentials_stub_test.cc
Fixes #10621 
Adds a tracing decorator to the minimal IAM stub.
Continue throwing decorators in the same source file.
The implementation is this (but async):
https://github.com/googleapis/google-cloud-cpp/blob/8ea75cf4f17ca32f42f21a68cd3c02d2c3e42d12/google/cloud/iam/credentials/v1/internal/iam_credentials_tracing_stub.cc#L37-L42
And this:
https://github.com/googleapis/google-cloud-cpp/blob/8ea75cf4f17ca32f42f21a68cd3c02d2c3e42d12/google/cloud/iam/credentials/v1/internal/iam_credentials_tracing_stub.cc#L61-L65
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11479)
=> impl(otel): gRPC access token credential tracing

google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/storage/tests/curl_request_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11473)
=> fix(rest): missing user-agent separator

docfx/doxygen2children.cc, docfx/doxygen2children_test.cc, docfx/doxygen2references.cc, docfx/doxygen2references_test.cc
Listing the nested namespaces as children is (arguably) technically correct, but it does not render right, and does not aid in navigation.
Fixes #11452
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11483)
=> fix(docfx): skip nested namespaces in children list

ci/cloudbuild/builds/generate-libraries.sh, cmake/CompileProtos.cmake, external/googleapis/CMakeLists.txt, generator/generator_config.proto, generator/standalone_main.cc
Because code generated from protos captures proto file line numbers, we need to:
1. emit protos
2. format protos
3. emit C++
4. format C++
Also add new googleapis proto dep and update automated tools to handle local protos.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11433)
=> impl(generator): support generating, building, and installing local protos

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc, google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h, google/cloud/bigquery/v2/minimal/internal/common_v2_resources_test.cc, google/cloud/bigquery/v2/minimal/internal/table.cc, google/cloud/bigquery/v2/minimal/internal/table.h, google/cloud/bigquery/v2/minimal/internal/table_constraints.cc, google/cloud/bigquery/v2/minimal/internal/table_constraints.h, google/cloud/bigquery/v2/minimal/internal/table_partition.cc, google/cloud/bigquery/v2/minimal/internal/table_partition.h, google/cloud/bigquery/v2/minimal/internal/table_schema.cc, google/cloud/bigquery/v2/minimal/internal/table_schema.h, google/cloud/bigquery/v2/minimal/internal/table_test.cc, google/cloud/bigquery/v2/minimal/internal/table_view.cc, google/cloud/bigquery/v2/minimal/internal/table_view.h
This PR adds DebugString() member functions with unit tests, to all Table custom classes. This is in preparation for request and response logging for the Table logging decorator.
Please note that I have commented out all member values that are of type `std::vector<std::string>` as that is currently not supported in the DebugFormatter. 
bww@ is aware of the above.
Thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11475)
=> impl(bigquery): Table custom classes logging

docfx/doxygen2children.cc, docfx/doxygen2children.h, docfx/doxygen2docfx.cc, docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2references.cc, docfx/doxygen2references.h, docfx/doxygen2syntax.cc, docfx/doxygen2syntax.h, docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen_errors.cc, docfx/doxygen_errors.h, docfx/doxygen_groups.cc, docfx/doxygen_groups.h, docfx/doxygen_pages.cc, docfx/doxygen_pages.h, docfx/function_classifiers.cc, docfx/function_classifiers.h, docfx/public_docs.cc, docfx/public_docs.h, docfx/yaml_context.cc, docfx/yaml_context.h
A `pugi::xml_node` is akin to an iterator or a pointer. They should be passed by value and not by `const&`. It is possible some additional cleanups will be needed, but this should have caught most cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11482)
=> cleanup(docfx): use `pugi::xml_node` as pointers

docfx/doxygen2toc.cc, docfx/doxygen2toc.h, docfx/doxygen2toc_test.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc, docfx/doxygen_groups.cc, docfx/doxygen_groups.h, docfx/doxygen_groups_test.cc, docfx/doxygen_pages.cc, docfx/doxygen_pages.h, docfx/doxygen_pages_test.cc, docfx/toc_entry.cc, docfx/toc_entry.h
Change the table of contents generation to include namespaces, classes, structs, functions, enums, typedefs, etc. Group elements by "type", so structs appear together. The grouping matches the groups in the right-side navigation for a namespace or class. Compound elements (namespaces, classes, structs) have an 'Overview' link to point to the element description. There is no way to have a grouping that is also a link, that is, a group for "all the stuff in class Foo that also links to Foo" is not a thing.
Links to enums and typedefs are not pointing anywhere at the moment, that will be fixed in separate PRs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1149 …
=> impl(docfx): generate full table of contents

.typos.toml, docfx/doxygen2toc.cc, docfx/doxygen2toc_test.cc, docfx/testing/inputs.cc
For functions and enums (and in general for `<memberdef>` elements) we do not want to use the fully-qualified name, it is just too cumbersome. Likewise, items in the table of contents without subitems (like functions, enum values, and typedefs) we don't need to create an `Overview` section, just use the item as its own link.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11495)
=> impl(docfx): iterate on table-of-contents

docfx/doxygen2docfx.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml_test.cc
The tooling at google expects enums to be generated as separate files. This adds a small loop in `main()` to generate the files. We need to remove the enum definitions from the previous yml files, or we get duplicate definitions. And to make the enumvalues visible we need to list them as children of the enum.
Part of the work for #11455
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11497)
=> impl(docfx): generate separate file for enums

generator/internal/http_option_utils.cc, generator/internal/http_option_utils.h, generator/internal/http_option_utils_test.cc
When dealing with protos generated from discovery documents, we can encounter http paths with multiple substitutions, i.e. multiple pairs of `{}`. We need to parse this and then reassemble it with the string literals pieces and appropriate request accessor calls.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11502)
=> impl(generator): handle http path with multiple substitutions

google/cloud/storage/internal/grpc_client.cc
Fixes #11135.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11506)
=> fix(GCS+gRPC): remove erroneous dereference of StatusOr value

generator/internal/discovery_file_test.cc, generator/internal/discovery_resource.cc, generator/internal/discovery_resource_test.cc, generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto_test.cc, generator/internal/discovery_type_vertex.cc, generator/internal/discovery_type_vertex_test.cc
Add variable substitution format in http paths such that the generator can parse them correctly.
Add `json_name="resource"` option for `$ref` types in requests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11503)
=> impl(generator): improved resource and path handling

ci/cloudbuild/builds/check-api.sh, ci/cloudbuild/builds/clang-tidy.sh, ci/cloudbuild/builds/cmake-gcs-rest.sh, ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/builds/cxx14.sh, ci/cloudbuild/builds/cxx20.sh, ci/cloudbuild/builds/lib/cmake.sh, ci/cloudbuild/builds/m32.sh, ci/cloudbuild/builds/noex.sh, ci/cloudbuild/builds/quickstart-production.sh, ci/cloudbuild/builds/scan-build.sh, ci/cloudbuild/builds/shared.sh
The enabled features aren't really a "common argument" as more often than not we override them with an extra `-DGOOGLE_CLOUD_CPP_ENABLE` setting. So, stop adding a setting in `cmake::common_args`, and instead have each build script specify its own (typically starting from a `features::*` call).  This makes what we're building much clearer in the scripts, and when looking at an executed CMake command.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11515)
=> cleanup(ci): disentangle cmake::common_args from GOOGLE_CLOUD_CPP_ENABLE

google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/pick_instance_config.cc
Followup to #11461, but skipping instance configs that have an optional replica in location "europe-west9" ("regional-us-central1") rather than ones whose names include "europe-west9" ("regional-europe-west9").
Part of #11346.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11516)
=> test(spanner): avoid "europe-west9" in CreateInstanceConfig() tests

CMakeLists.txt, cmake/FindgRPC.cmake, external/googleapis/config.cmake.in, generator/CMakeLists.txt, google/cloud/config-rest-protobuf.cmake.in, google/cloud/dataproc/CMakeLists.txt, google/cloud/resourcesettings/CMakeLists.txt
CMake ships with a `FindProtobuf` module, when one types:
```
find_package(Protobuf)
```
CMake uses that module to find protobuf and add the necessary compile and link-time flags. The next release of Protobuf adds dependencies that the module does not know about. Fortunately the next release also install the CMake support files, which can be used if one types:
```
find_package(Protobuf CONFIG)
```
Because we need to support older versions of Protobuf, we first try with the `CONFIG` flag, and then fallback to the module instead.
We install our own CMake configuration files, which need to use `find_dependency()` to find Protobuf. `find_dependency()` is a thin wrapper around `find_package()`, and it needs to use the same strategy that we know worked for building `google-cloud-cpp`.
- - - …
=> impl: prefer Protobuf config vs. module in CMake

google/cloud/bigtable/admin/integration_tests/admin_backup_integration_test.cc, google/cloud/bigtable/tests/admin_backup_integration_test.cc, google/cloud/servicecontrol/README.md, google/cloud/servicecontrol/quickstart/quickstart.cc, google/cloud/trace/README.md, google/cloud/trace/quickstart/quickstart.cc
On Windows, `GetCurrentTime()` is a macro. The current and previous releases of Protobuf undefine this macro in one of its headers.  That was probably a bug in Protobuf.  We use `TimeUtil::GetCurrentTime()`. With the next release of Protobuf that will expand the macro. We either need to prevent the macro expansion, using something like `(TimeUtil::GetCurrentTime)()`, or we need to avoid the function altogether.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11518)
=> impl: prepare for next Protobuf release

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/bigtable_client_unit_tests.bzl, google/cloud/bigtable/data_connection_test.cc, google/cloud/bigtable/internal/data_connection_impl_test.cc
This is testing a function from `data_connection.h` so it should be in `data_connection_test.cc`.
I was probably too lazy to create a new test file at the time it was added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11521)
=> refactor(bigtable): move test

ci/cloudbuild/builds/check-api.sh, ci/cloudbuild/builds/checkers.sh, ci/cloudbuild/builds/clang-60.sh, ci/cloudbuild/builds/clang-tidy.sh, ci/cloudbuild/builds/cmake-gcs-rest.sh, ci/cloudbuild/builds/cmake-single-feature.sh, ci/cloudbuild/builds/cxx14.sh, ci/cloudbuild/builds/cxx20.sh, ci/cloudbuild/builds/gcc-7.3.sh, ci/cloudbuild/builds/lib/cmake.sh, ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/builds/m32.sh, ci/cloudbuild/builds/noex.sh, ci/cloudbuild/builds/publish-docs.sh, ci/cloudbuild/builds/quickstart-production.sh, ci/cloudbuild/builds/scan-build.sh, ci/cloudbuild/builds/shared.sh
In #11515 I removed `io::run` from the cmake command in the "m32" build, in the interests of consistency with the other cmake builds, which don't use logging.
Here, we still maintain consistency but by adding `io::run` to all the other cmake/ctest commands instead (well, at least those in the top-level build scripts).  This makes the build output easier to follow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11523)
=> cleanup(ci): log cmake/ctest command lines

generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, generator/internal/stub_rest_generator.cc
For rest json payloads, if the request contains a field annotated with `json_name="resource"`, only convert the contents of that field, not the entire request, into the json payload.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11501)
=> impl(generator): provide the correct proto for the payload

google/cloud/bigtable/admin/integration_tests/admin_backup_integration_test.cc, google/cloud/bigtable/tests/admin_backup_integration_test.cc
Bigtable stores the backup expiration time in microsecond granularity, don't expect that full nanosecond is preserved (or whatever the `std::chrono::time_point` granularity happens to be).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11524)
=> test(bigtable): relax backup expiration time checks

docfx/doxygen2syntax.cc, docfx/doxygen2syntax_test.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml_test.cc
DocFX recognizes `typealias` as, well, aliases for types. A separate PR tweaks it to support typealiases in namespaces, but these changes make the aliases visible in the generated documentation.
Part of the work for #11456
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11541)
=> impl(docfx): use `typealias` for typedefs

google/cloud/bigtable/data_client.h, google/cloud/bigtable/table.h
This PR marks the `class DataClient` and `Table::Table(std::shared_ptr<DataClient>, ...)` ctors as deprecated. This is in doxygen only. There are no compiler warnings emitted.
Also, move these deprecated constructors to the bottom of the header, so that they show up later in our documentation.
(Yes, my PR is doing two things at once. I split it into two commits for the sake of reviewability)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11550)
=> doc(bigtable): deprecate DataClient in doxygen

google/cloud/bigtable/examples/data_async_snippets.cc
I noticed this call fails silently in Cloud Trace, lol.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11563)
=> cleanup(bigtable): fix CI table leaks

google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/async_streaming_read_rpc_tracing.h, google/cloud/internal/async_streaming_read_rpc_tracing_test.cc
Part of the work for #10619 
Eventually becomes things like this:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11564)
=> impl(otel): `AsyncStreamingReadRpcTracing`

.github/workflows/external-account-integration.yml, ci/cloudbuild/builds/coverage.sh, ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/dockerfiles/centos-7.Dockerfile, ci/cloudbuild/dockerfiles/debian-github.Dockerfile, ci/cloudbuild/dockerfiles/demo-alpine-stable.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cmake.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cxx14.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/fedora-m32.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, ci/kokoro/lib/vcpkg.sh, ci/kokoro/macos/build.sh, doc/contributor/howto-guide-setup-development-workstation.md, doc/packaging.md, external/googleapis/renovate.sh, google/cloud/opentelemetry/quickstart/README.md
With the `-f` flag `curl(1)` treats status codes (other than 2xx and 3xx) as errors. We probably want that behavior, otherwise a 500 is treated "success" and we try to untar the contents.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11565)
=> ci: use `curl -f` to detect HTTP errors

google/cloud/spanner/admin/integration_tests/instance_admin_rest_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11569)
=> fix(rest): use insecure credentials with the Spanner emulator REST endpoint

google/cloud/bigtable/internal/data_tracing_connection.cc, google/cloud/bigtable/internal/data_tracing_connection_test.cc
I missed this in: #11558 
We need to set the connection level span as active before we get to the stub layer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11572)
=> impl(bigtable): correlate AsyncReadRows span with children

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_tracing_stub.cc, generator/integration_tests/tests/golden_kitchen_sink_tracing_stub_test.cc, generator/internal/tracing_stub_generator.cc, google/cloud/bigtable/internal/bigtable_tracing_stub.cc, google/cloud/storage/internal/storage_tracing_stub.cc
Part of the work for #10620 
Note that async streaming reads are handwritten only in the connection layer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11573)
=> impl(otel): async streaming read tracing in stubs

google/cloud/options.h, google/cloud/options_test.cc
```
absl::optional<typename T::Type> internal::ExtractOption<T>(Options&);
```
Extracts and returns the value for `T` from the options, or nullopt if `T` was not set.
This is intended for code paths that want to consume an option, for example in a client call that passes the option's value via conventional mechanisms, rather than through an `OptionsSpan`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11576)
=> impl(common): support extracting a typed option from an Options

google/cloud/bigtable/internal/async_row_sampler.cc, google/cloud/bigtable/internal/async_row_sampler.h, google/cloud/bigtable/internal/async_row_sampler_test.cc
Part of the work for #11585
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11593)
=> impl(bigtable): AsyncSampleRows traced backoffs

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/doc/bigtable-main.dox, google/cloud/bigtable/doc/migrating-from-dataclient.dox
Exclude test proxy symbols from the documentation. Formatting as monospace does not work well in titles. I tried backticks, `@c` commands, and `<tt>`. Use the magic `*-endpoint-snippet` name to skip pages from the DoxFX table of contents.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11610)
=> docs(bigtable): small cleanups

google/cloud/bigtable/tests/table_sample_rows_integration_test.cc
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/eb9fbf8a-9bca-4c32-a422-35df84ecbfb2;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/0669593d4b1a72eed9c16f828ca7c1d4f76aef6e/fedora-m32-m32/log-eb9fbf8a-9bca-4c32-a422-35df84ecbfb2.txt
This build flaked and there was too much noise in the log to see why. We had enabled logging for `"rpc"` , but not `"rpc-streams"`. That will still dump the request, which in this case, is too big:
https://github.com/googleapis/google-cloud-cpp/blob/b89901f7c51ffcc1a2cfba35631ba6a26a428663/google/cloud/internal/log_wrapper.h#L114-L117
So just turn off all logging for the set up. That will at least tell us if it is the set up that is …
=> cleanup(bigtable): reduce test logs

docfx/doxygen2syntax.cc, docfx/doxygen2syntax_test.cc, docfx/doxygen2yaml_test.cc
Finally found a way to convince docfx that we need the return type descriptions to go through markdown.
Fixes #11451
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11612)
=> impl(docfx): return descriptions go through markdown

docfx/doxygen_groups.cc, docfx/doxygen_groups_test.cc
I could not figure out how to represent the children of a group as `children` elements in DocFX. It appears that having them as children of the namespace and the group does not match the expected data model. With this change they are listed, and linked, which is enough for our purposes.
Fixes #11453
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11619)
=> impl(docfx): add group's children to description

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml_test.cc
Namespaces can have multiple `xrefsect` marking them as deprecated. This skips all but the first such section.
Fixes #11614
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11615)
=> impl(docfx): skip duplicate `deprecated` sections

google/cloud/status_or.h, google/cloud/status_or_test.cc
The most interesting change is expressing some SFINAE tricks in a way that is easier to document.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11631)
=> docs(common): improve `StatuOr<>` documentation

google/cloud/storage/internal/object_write_streambuf.cc, google/cloud/storage/internal/object_write_streambuf.h
Allocating large upload buffers upfront can be slow if the application is going to send a small amount of data.  Better grow the buffer as needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11633)
=> feat(storage): lazy allocation for upload buffer

google/cloud/spanner/doc/spanner-main.dox
Fixed some typos in the landing page: `THis` vs. `This` and `C++11` when we only support C++14.  With DocFX we don't have deep linking to sections of pages working, the page is small, so just link the page for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11641)
=> docs(spanner): some documentation tweaks

google/cloud/bigtable/cell.h, google/cloud/bigtable/mutations.h, google/cloud/bigtable/table.h, google/cloud/completion_queue.h, google/cloud/spanner/numeric.h, google/cloud/status_or.h
From time-to-time the template parameters of a function include implementation details to exclude the function from overload resolution, or to apply some template magic to deduce dependent types. These details do not need to be documented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11645)
=> docs: exclude some implementation details

docfx/doxygen2children.cc, docfx/doxygen2references.cc, docfx/yaml_context.cc, docfx/yaml_context.h
The Pub/Sub library has a few mocks that don't mock anything. We kept the `MOCK_METHOD(..., ack_id...)` definitions for backwards compatibility, but the base class has no `ack_id()` to mock. Skip these in the documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11648)
=> impl(docfx): support odd mocks in pubsub library

google/cloud/bigtable/doc/bigtable-main.dox, google/cloud/pubsub/doc/pubsub-main.dox, google/cloud/spanner/doc/spanner-main.dox, google/cloud/storage/doc/storage-main.dox
Remove the installation instructions and just link the common "set up" page.
Avoid deep links to the environment variables page as those do not work (yet) with docfx.
Avoid formatting problems with back-to-back links.
Motivated by #11430. Part of the work for #10157
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11654)
=> docs: cleanup landing pages for docfx

google/cloud/internal/curl_impl.cc
Fixes #11647.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11649)
=> fix: workaround curl_multi_poll returning an error on EINTR

ci/cloudbuild/cache.sh
Motivated by #10031
I think this command takes ~4s normally. So 2m should be generous enough. Anything seems better than this command struggling for 3.5 hours.
The comments say this is not necessary that downloading the cache is not necessary for running the build, so we just continue on timeout.
We could implement a retry loop (with timeouts) instead.... thoughts?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11604)
=> ci: timeout Linux GCS cache download

google/cloud/bigquery/v2/minimal/internal/dataset_logging_test.cc, google/cloud/bigquery/v2/minimal/internal/job_logging_test.cc, google/cloud/bigquery/v2/minimal/internal/project_logging_test.cc, google/cloud/bigquery/v2/minimal/internal/table_logging_test.cc
This PR addresses code review feedback by Bradley [here](https://github.com/googleapis/google-cloud-cpp/pull/11643#pullrequestreview-1433049852) regarding the logging test expectations to make them more meaningful.
Changes in the PR include:
1) Adding `Contains(e).Times(n)` where applicable
2) Adding expectations for some additional required members that should be logged.
Bradley, when you get a chance can you take a look?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11659)
=> impl(bigquery): minor cleanup logging decorators

docfx/.clang-tidy, docfx/doxygen2references.cc, docfx/doxygen2toc.cc, docfx/yaml_context.cc, docfx/yaml_context.h, docfx/yaml_context_test.cc
Use the name of the mocked function, but link to the mocking function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11661)
=> impl(docfx): fix table of contents for mocks

google/cloud/bigquery/v2/minimal/internal/dataset_logging_test.cc, google/cloud/bigquery/v2/minimal/internal/job_logging_test.cc, google/cloud/bigquery/v2/minimal/internal/project_logging_test.cc, google/cloud/bigquery/v2/minimal/internal/table_logging_test.cc
Addressing some more test cleanup for read-only apis before I start on the mutating apis for V2 resources next week.
This PR adds the expectations for context headers and ensures they are getting logged along with request and response logging. These were missed in initial tests.
Thanks in advance for the review!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11667)
=> impl(bigquery): Logging Tests cleanup

docfx/doxygen2yaml.cc, docfx/doxygen2yaml_test.cc, docfx/yaml_context.h
Many of our functions share a brief (and rarely a longer) description in a custom group (the things that start with `///@{`. These become `<sectiondef>` elements in the XML representation. With this change we use their description, or their header, as a fallback to the member descriptions.
Fixes #11496
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11668)
=> impl(docfx): fallback to sectiondef descriptions

CHANGELOG.md, ci/kokoro/windows/builds/quickstart-bazel.ps1, ci/kokoro/windows/builds/quickstart-cmake.ps1, google/cloud/storagetransfer/BUILD.bazel, google/cloud/storagetransfer/CMakeLists.txt
Reverse #8789 now that we have a new protobuf release that avoids the macOS `UID_MAX`/`GID_MAX` issue.
Fixes #8785.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11672)
=> cleanup: re-enable google/cloud/storagetransfer on macOS

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_option_defaults.cc, generator/integration_tests/golden/v1/internal/golden_rest_only_option_defaults.cc, generator/integration_tests/golden/v1/internal/golden_thing_admin_option_defaults.cc, generator/internal/option_defaults_generator.cc
Adjust the generation of the call to `PopulateCommonOptions()` so that it is not affected by the recent "smart" indentation changes to `protobuf::io::Printer`.  This restores the (pre clang-format) shape of the generated code to what we had before the protobuf upgrade.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11673)
=> impl(generator): tweak generation of PopulateCommonOptions() call

.clang-format, google/cloud/storage/client.h, google/cloud/storage/examples/storage_default_object_acl_samples.cc
`clang-format` broke a reference to a snippet because the name was too long.  Fixed the reference and configure `clang-format` to avoid this problem in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11678)
=> docs(storage): fix snippet reference

google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable.h, google/cloud/opentelemetry/trace_exporter.cc
Motivated by #11669 
Factor out the longer, more involved implementations in the exporter classes. They will be wrapped in a `NoExceptAction(...)` in a follow up PR.
I had planned to do the refactor and `noexcept` handling as two commits in the same PR, but this diff is sufficiently ugly. So I am splitting it up into separate PRs.
No, I don't really care that `Foo() noexcept` is calling `FooImpl()` (which could throw). If the compilers yell at me, I will do something about it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11676)
=> refactor(otel): prepare for noexcept handling

generator/BUILD.bazel, generator/CMakeLists.txt, generator/internal/longrunning.cc, generator/internal/longrunning.h, generator/internal/longrunning_test.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator.h, generator/internal/service_code_generator_test.cc
part of the work for #11531 
We're currently hardcoding compute LRO values for many of these variables as that's all we need right now for non `google::longrunning::Operation` types. If in the future, we need support additional LRO mechanisms, we can figure out if we want to abstract the values out and inject them via the config textproto, or some additional branching in this code to handle additional LRO schemes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11653)
=> impl(generator): add longrunning var support for compute operation types

google/cloud/storage/client.cc, google/cloud/storage/client.h, google/cloud/storage/client_write_object_test.cc, google/cloud/storage/parallel_upload.cc, google/cloud/storage/parallel_upload.h, google/cloud/storage/tests/object_resumable_write_integration_test.cc
A number of places still used `client_options()` or did not use `google::cloud::internal::CurrentOptions()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11686)
=> cleanup(storage): use `Options` in implementation

google/cloud/storage/examples/storage_client_mock_samples.cc, google/cloud/storage/google_cloud_cpp_storage.cmake, google/cloud/storage/storage_client_testing.bzl, google/cloud/storage/testing/mock_client.cc, google/cloud/storage/testing/mock_client.h, google/cloud/storage/testing/remove_stale_buckets_test.cc
Motivated by #11613 
This allows customers to mock a single response from a `RawClient` (instead of N responses in the case of transient errors).
Prefer the `UndecoratedClientFromMock` > `ClientFromMock` in the public samples. I did not update our unit tests.
I did not think about whether extra effort is needed to make the install work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11697)
=> feat(storage): offer mock client without decorators

google/cloud/internal/curl_handle.cc, google/cloud/internal/curl_impl.cc
We configure libcurl to get the data for PUT and POST requests using callbacks. Sometimes libcurl may have sent part of the data and needs to resend it. The documentation mentions "multi-pass authentication methods", as well as reusing connections where libcurl detects they were closed after some data is sent. There are cases on the Internet about chasing HTTP redirects (3xx responses) too. In any case, we have seen these as flakes in the tests.
I took the belt and suspenders approach. Try to handle the rewind requests, but if unhandled treat the error as retryable, because they are.
Fixes #11167
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11703)
=> fix(rest): support rewinds in libcurl

generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, generator/internal/discovery_file_test.cc, generator/internal/discovery_type_vertex.cc, generator/internal/discovery_type_vertex_test.cc
"resource" was occurring as an actual field name and causing proto parsing errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11698)
=> impl(generator): switch to a more likely to be unique field name

google/cloud/future_generic.h, google/cloud/future_void.h, google/cloud/internal/future_impl.h, google/cloud/status_or.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11705)
=> docs(common): better exception descriptions

generator/generator_config.proto, generator/internal/discovery_document.h, generator/internal/discovery_file_test.cc, generator/internal/discovery_resource.cc, generator/internal/discovery_resource.h, generator/internal/discovery_resource_test.cc, generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc, generator/standalone_main.cc
part of the work for #11531 
The services that are used to poll longrunning operations for compute need to be emitted as synchronous services, even though their methods have a response type of `Operation`. We define the necessary services as part of the config.
We continue to hard code some of the logic for compute as its not obvious at this time if we need to abstract this behavior to handle other REST-only services.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11710)
=> impl(generator): emit longrunning operation services methods as synchronous

docfx/doxygen2toc.cc
The class groups (Constructors, Functions, etc) should match the navigation on the generated HTML.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11717)
=> impl(docfx): match class ToC groups with devsite

WORKSPACE.bazel, bazel/google_cloud_cpp_deps.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11724)
=> feat: avoid development dependencies with Bazel

google/cloud/channel/BUILD.bazel, google/cloud/channel/CMakeLists.txt
We used to exclude some platforms because Protobuf lacked protection against the `DOMAIN` macro being defined in the system.
Part of the work for #8125
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11721)
=> cleanup(channel): build on all tested platforms

google/cloud/opentelemetry/CMakeLists.txt, google/cloud/opentelemetry/README.md, google/cloud/opentelemetry/doc/main.dox
- Add a main page for `google/cloud/opentelemetry`
- Link to it from the README
- Add a brief description to the README
I want to get this in place before we add samples. (so we can reference those samples from the index page)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11692)
=> doc(otel): add main.dox

ci/cloudbuild/builds/check-api.sh, doc/contributor/howto-guide-adding-generated-libraries.md
There are times when we want to run `check-api-pr` and we only care about one library. (e.g. when we generate a new library).
Add a `GOOGLE_CLOUD_CPP_CHECK_API=common,bigtable,kms` env variable to only check a subset of the libraries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11719)
=> impl: faster check-api runs

google/cloud/bigtable/data_connection.cc, google/cloud/bigtable/data_connection.h, google/cloud/bigtable/examples/howto_mock_data_api.cc, google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/internal/data_tracing_connection.cc, google/cloud/bigtable/internal/data_tracing_connection_test.cc, google/cloud/bigtable/mocks/mock_data_connection.h, google/cloud/bigtable/mocks/mock_row_reader.h, google/cloud/bigtable/table_test.cc
Part of the work for \<mystery bigtable feature\>
Googlers can see: go/cloud-cxx:how-to-grow-bigtable-read-rows
The new Connection API allows us to add additional `ReadRowsRequest` configuration parameters.
I think we should include `app_profile_id` in the params struct. It is easier to check in the params struct than in `google::cloud::mocks::CurrentOptions()`.
Note that we cannot `internal::ExtractOption<AppProfileIdOption>` in the connection layer, because the current options are ` const&`. I think it is safer to just use `.get<>` instead of changing the method to `Options& internal::CurrentOptions()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11725) …
=> refactor(bigtable): future-proof ReadRows mocking

google/cloud/opentelemetry/CMakeLists.txt, google/cloud/opentelemetry/configure_basic_tracing.h, google/cloud/opentelemetry/samples/BUILD.bazel, google/cloud/opentelemetry/samples/CMakeLists.txt, google/cloud/opentelemetry/samples/samples.cc
Part of the work for #11360 
---
Start with one sample. One is better than none.
Arguably I should just do `void MyApplicationCode() {};`. But I like the idea of something potentially happening if the sample is run from the command line. (of course with the hardcoded .001 sample rate, `otel-basic-tracing-rate` will barely ever do anything). I am open to other opinions.
---
Note that the `google/cloud/opentelemetry/...` integration tests do not run for any CMake builds. (I think this is also true of the most generated `google/cloud/${library}/samples/...`). I did run them manually to make sure they worked.
```
2023-05-25T16:25:57Z (+36s)
--------------------------------------------------------------------
|   Running OpenTelemetry integration tests (against production)   | …
```
=> docs(otel): introduce a sample

google/cloud/spanner/samples/samples.cc
Add the `spanner_set_custom_timeout_and_retry` tag to the retry/backoff sample.
Also make the sample itself look more like those in the other Cloud languages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11729)
=> cleanup(spanner): fixes for retry/backoff sample

generator/internal/connection_impl_rest_generator.cc, generator/internal/descriptor_utils.cc, generator/internal/logging_decorator_rest_generator.cc, generator/internal/longrunning.cc, generator/internal/longrunning_test.cc, generator/internal/metadata_decorator_rest_generator.cc, generator/internal/stub_rest_generator.cc
part of the work for #11531 
Adds an additional case in the generator for LRO methods that do not use the `google::longrunning::Operation` type and its associated methods. Existing tests verify that nothing has changed for the `google::longrunning::Operation` paths. Tests for the custom operation type path will be introduced later and will take the form of the generated compute services and integration tests for those services. This is a consequence of needing to hard code some of the substitution variables to compute specific types and services.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11723)
=> impl(generator): emit LRO code for REST rpc with bespoke Operation type

google/cloud/storage/client.cc, google/cloud/storage/client_sign_policy_document_test.cc, google/cloud/storage/client_sign_url_test.cc
The error messages for signed URL functions (`CreateV2SignedUrl()`, `CreateV4SignedUrl()` and `CreatedSignedPolicyDocument()`) were not helpful when the signing account is missing.
Fixes #11740
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11741)
=> feat(storage): better error messages in signed URLs

ci/cloudbuild/builds/bazel-oldest.sh
The next version of gRPC won't compile with Bazel 4.2.1. They are doing the right thing, we had extended the life of 4.2.1 to accomodate one customer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11785)
=> ci: minimum tested Bazel is 5.4.1

google/cloud/internal/minimal_iam_credentials_stub_test.cc
There is no `clang-tidy` build without OTel and I make mistakes ~~sometimes~~ often.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11787)
=> cleanup: clang-tidy

CMakeLists.txt, cmake/CompileProtos.cmake, doc/compile-time-configuration.md, examples/hello_world_grpc/CMakeLists.txt, generator/CMakeLists.txt
Allow overrides for the `protobuf::protoc` and `gRPC::grpc_cpp_plugin` targets. On cross-compilation builds the targets point to the binaries for the *target*, but we need binaries that can run on the *host* build.
Fixes #11779
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11782)
=> fix: better support for cross-compilation

ci/kokoro/windows/builds/quickstart-bazel.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11788)
=> ci: skip `debugger` in Bazel+quickstart builds too

ci/cloudbuild/builds/integration-production.sh, ci/cloudbuild/cloudbuild.yaml
Builds would succeed because `GENERATE_GOLDEN_ONLY` was the string `\"\"`, not the empty string. Which would cause us to hit the branches of this `if` statement intended for development only: https://github.com/googleapis/google-cloud-cpp/blob/02f0266d5cf31ad735467e4d001b7399808a1536/ci/cloudbuild/builds/generate-libraries.sh#L64-L66
e.g. this: https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/d4c7d23d-b8aa-4edb-acd9-f840e76169f8;step=3?project=cloud-cpp-testing-resources
This hasn't been a problem, because we run `generate-libraries-pr` locally (not on GCB) all of the time.
Also remove `HTTP_TRANSCODING_TEST` because it does not do anything.
- - - …
=> ci: run generate-libraries on GCB

ci/cloudbuild/dockerfiles/fedora-37-cxx20.Dockerfile
Now that we are using Fedora:37 and GCC-12.2 the workaround (compiling with C++17) is no longer needed.
Fixes #9508
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11797)
=> ci: remove workaround for google benchmark and C++20

ci/cloudbuild/builds/checkers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11816)
=> ci: also exclude '.pb' files from whitespace checks

google/cloud/internal/streaming_write_rpc_logging_test.cc, google/cloud/internal/streaming_write_rpc_tracing_test.cc
verify that the wrappers pass along the value returned by the child for writes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11826)
=> cleanup: streaming write test nits

google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/samples/testdata/revised_schema.avsc, google/cloud/pubsub/samples/testdata/revised_schema.proto
Issue #11720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11840)
=> fix(pubsub): add commit schema and list schema revision samples

generator/internal/descriptor_utils.cc, google/cloud/automl/v1/prediction_client.h, google/cloud/iam/v2/policies_client.h, google/cloud/notebooks/v1/managed_notebook_client.h, google/cloud/resourcemanager/v3/organizations_client.h, google/cloud/resourcemanager/v3/projects_client.h, google/cloud/translate/v3/translation_client.h
We need to preserve newlines in comments as `@n` commands. We do not need (or want?) to preserve each newline because in markdown one or more act as paragraph separators.
There are no comments with 4 newlines in a row (yet).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11858)
=> feat(generator): handle comments with 3 newlines

google/cloud/pubsub/samples/pubsub_samples_common.cc, google/cloud/pubsub/samples/pubsub_samples_common.h, google/cloud/pubsub/samples/samples.cc
Issue 11720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11848)
=> doc(pubsub): add get/delete/rollback schema samples

ci/cloudbuild/builds/protobuf-at-head.sh
Same idea as 'gRPC at HEAD': it will build nightly, it will not stop our PRs, and will notify a separate space where the Protobuf and gRPC folks can see what broke.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11874)
=> ci: add a 'Protobuf at HEAD' build

google/cloud/spanner/internal/spanner_stub_factory.cc, google/cloud/spanner/internal/spanner_stub_factory.h, google/cloud/spanner/internal/spanner_stub_factory_test.cc
Factor out the stub decoration in spanner, so we can use a mock stub as the base.
This allows us to
- Add a test to confirm the "google-cloud-resource-prefix" header is present.
- Update the other tests to not create any gRPC stubs or channels.
This ought to fix #9664. We lose test coverage over the code in `CreateDecoratedStub`, though. I think the trade off is fine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11876)
=> refactor(spanner): stub decoration

CMakeLists.txt, google/cloud/storage/internal/grpc_ctype_cord_workaround.h
Minor change to fix the urls pointing to the workaround.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11879)
=> chore(storage): fixed ctype=CORD workarounds url

google/cloud/pubsub/samples/pubsub_samples_common.cc, google/cloud/pubsub/samples/pubsub_samples_common.h, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/topic_builder.h
Fixes part of Issue #11720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11872)
=> doc(pubsub): add update topic schema and create topic with schema revisions to samples

google/cloud/pubsub/samples/pubsub_samples_common.cc, google/cloud/pubsub/samples/pubsub_samples_common.h, google/cloud/pubsub/samples/samples.cc
Issue #11720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11862)
=> doc(pubsub): delete schemas > 48 hours old

google/cloud/opentelemetry/internal/recordable.cc
`SetAttribute(...)` already has a noexcept wrapper. So this one was unnecessary.
https://github.com/googleapis/google-cloud-cpp/blob/1145a8ccff7f8ce7fcebc0256efe6b3093e8e21a/google/cloud/opentelemetry/internal/recordable.cc#L204-L207
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11886)
=> cleanup(otel): unnecessary wrapper

google/cloud/spanner/options.h, google/cloud/spanner/partition_options.h, google/cloud/spanner/query_partition.h, google/cloud/spanner/read_partition.h
I finally received word from the writers of how they want to describe this parameter, most importantly by saying "Cloud Spanner Data Boost". See #11345.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11913)
=> doc(spanner): update the description of the "DataBoost" feature

google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc, google/cloud/bigquery/v2/minimal/internal/job.cc, google/cloud/bigquery/v2/minimal/internal/job.h, google/cloud/bigquery/v2/minimal/internal/job_configuration_query_test.cc, google/cloud/bigquery/v2/minimal/internal/job_configuration_test.cc, google/cloud/bigquery/v2/minimal/internal/job_logging_test.cc, google/cloud/bigquery/v2/minimal/internal/job_query_stats.h, google/cloud/bigquery/v2/minimal/internal/job_response_test.cc, google/cloud/bigquery/v2/minimal/internal/job_stats.h, google/cloud/bigquery/v2/minimal/internal/job_test.cc, google/cloud/bigquery/v2/minimal/testing/job_test_utils.cc
This is the last of the PR for adding DebugString to `Job` resources. 
It includes the following changes:
1) Integrates the DebugString change from PR-11898 that supports `std::map<string, T>`. 
This caused changes to `JobConfiguration` and `JobConfigurationQuery` logging.
2) Adds initialization of primitive members (int, double, bool) so they are initialized correctly when the value is
not set explicitly by the caller.
3) Adds DebugString to all the Job and ListFormatJob classes.
4) Updates/Adds unit tests for all the above.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11911)
=> impl(bigquery): Adds DebugString Job and ListFormatJob classes

CMakeLists.txt, examples/CMakeLists.txt
Always `add_subdirectory(examples)` and let that directory decide what it can build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11932)
=> cleanup: simplify examples/ CMake files

google/cloud/essentialcontacts/CMakeLists.txt
This reverts commit 61c66e961d29e2e38c5bd01e37a491a4981de8a2.
Tested that the service is now working
`gcloud essential-contacts list --project=alevenb-test
API [essentialcontacts.googleapis.com] not enabled on project [1029569578106]. Would you
like to enable and retry (this will take a few minutes)? (y/N)?  y
Enabling service [essentialcontacts.googleapis.com] on project [1029569578106]...
Operation "operations/acat.p2-1029569578106-a128f3b7-b0db-4743-8524-10ba93625675" finished successfully.
Listed 0 items.`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11931)
=> fix: re-enable essentialcontacts test (#11922)

google/cloud/internal/pagination_range.h, google/cloud/internal/pagination_range_test.cc
Some services return empty pages with a non-empty pagination token. Our code would stop such iterations immediately. The correct behavior is to retrieve the next page until some non-empty range is returned.
Fixes #11936
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11937)
=> fix(common): pagination must support empty pages

google/cloud/pubsub/samples/samples.cc
Just like #10139 reverted a similar change from #10135, we now relearn the lesson for #11940.  Contrary to the promise, the change in `#include` form does not eliminate a special-case transformation used during the Google import.  I'll leave a breadcrumb elsewhere in the hope of having to not re-relearn in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11947)
=> cleanup(pubsub): revert PR #11940

ci/kokoro/windows/builds/quickstart-bazel.ps1
Fixes  #11926
After spending too much time trying to wrangle a Windows VM, I'm conceding and only disabling the compute library- not all experimental libraries. 
Sigh.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11949)
=> fix: disable compute library 

google/cloud/opentelemetry/CMakeLists.txt, google/cloud/opentelemetry/google_cloud_cpp_opentelemetry.bzl, google/cloud/opentelemetry/internal/monitored_resource.cc, google/cloud/opentelemetry/internal/monitored_resource.h, google/cloud/opentelemetry/internal/monitored_resource_test.cc, google/cloud/opentelemetry/opentelemetry_unit_tests.bzl
Part of the work for #11775 
Add support for mapping OTel attributes to GCP [Monitored Resources](https://cloud.google.com/monitoring/api/resources).
This is a whole lot of if statements, copied from: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/02fd6f23e8557907cda61ef01c94198dec4ccd71/internal/resourcemapping/resourcemapping.go#L165
(If you are wondering how we keep the logic up to date, there is an end-to-end test suite written by google's OpenTelemetry team. It does things like test the resource detector on GCE/GKE/Cloud Run/etc. It verifies mapping logic like in this PR. It seems like a lot of set up work. I will consider whether it should be required for C++)
---
I considered code like:
```cc
bool PlatformIsGce(std::string const& platform) {
return platform …
```
=> impl(otel): monitored resource mapping

google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable.h, google/cloud/opentelemetry/internal/recordable_test.cc
Part of the work for #11775
If we recognize the `opentelemetry::sdk::resource::Resource` as a GCP Monitored Resource, add attributes representing the monitored resource.
Copying attributes is [involved](https://github.com/dbolduc/google-cloud-cpp/commit/220d6178ebd21c8221e3ecbd255c7f19ee12a866) enough for its own PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11963)
=> impl(otel): monitored resources in trace exporter

google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.cc, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.h, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy_test.cc
This PR defines the Idempotency policy for the CancelJob api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11975)
=> impl(bigquery): Idempotency policy for cancel job

google/cloud/bigquery/v2/minimal/internal/job_logging.cc, google/cloud/bigquery/v2/minimal/internal/job_logging.h, google/cloud/bigquery/v2/minimal/internal/job_logging_test.cc, google/cloud/bigquery/v2/minimal/internal/job_metadata.cc, google/cloud/bigquery/v2/minimal/internal/job_metadata.h, google/cloud/bigquery/v2/minimal/internal/job_metadata_test.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.h, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc, google/cloud/bigquery/v2/minimal/testing/mock_job_rest_stub.h
This PR implements the rest stub, decorator and mock changes for CancelJob api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11979)
=> impl(bigquery): CancelJob stub and decorator changes

ci/cloudbuild/builds/lib/quickstart.sh
I missed this build in the cleanup to take advantage of CMake >= 3.13. We were also passing `-DGOOGLE_CLOUD_CPP*` flags to the quickstart builds. These have no effect because we use
`google/cloud/*/quickstart/CMakeList.txt` as the top-level CMake file in these builds, and these flags are only defined in the ./CMakeList.txt file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11990)
=> ci: cleanup CMake flags for quickstart builds

ci/cloudbuild/dockerfiles/checkers.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cmake.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cxx14.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cxx20.Dockerfile, ci/cloudbuild/triggers/integration-production-ci.yaml, ci/cloudbuild/triggers/integration-production-pr.yaml
The Docker images used exclusively in CMake-based builds should have no need to install bazelisk, so don't install it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11991)
=> cleanup: only install bazelisk if needed

ci/cloudbuild/builds/clang-tidy.sh
Make the "ctcache stats" banner look like the "sccache stats" one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11995)
=> cleanup(ci): make the "ctcache stats" banner consistent

ci/cloudbuild/builds/generate-libraries.sh, doc/contributor/howto-guide-update-googleapis-sha.md
`generate-libraries.sh` is used to:
- drive a CI build to verify the generated libraries and support files are up to date
- update the libraries after the googleapis SHA changes
- update the libraries after (and during) changes to the generator
The first two cases need to run `update_libraries.sh`. The last case is probably the most common case, and the slowest part was running the `update_libraries.sh`.
I took the opportunity to make the output more readable when making large updates.
Fixes #11999
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12000)
=> cleanup: speed up library generation

google/cloud/testing_util/validate_metadata.h
Documentation nits for an internal testing helper. I forgot to update the documentation when I refactored the class a year ago.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12012)
=> cleanup: `ValidateMetadataFixture` doc nits

google/cloud/bigtable/internal/bigtable_stub_factory.cc, google/cloud/bigtable/internal/bigtable_stub_factory_test.cc
Part of the work for #12010 
For context: https://github.com/googleapis/googleapis/blob/5b2d46f59088b73d9c8db994e49f33d0e2880782/google/bigtable/v2/feature_flags.proto#L27-L43
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12011)
=> impl(bigtable): add bigtable-features header

bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/centos-7.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cmake.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cxx14.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile, google/cloud/completion_queue_benchmark.cc, google/cloud/options_benchmark.cc, google/cloud/spanner/bytes_benchmark.cc, google/cloud/spanner/internal/merge_chunk_benchmark.cc, google/cloud/spanner/numeric_benchmark.cc, google/cloud/spanner/row_benchmark.cc, google/cloud/storage/internal/crc32c_benchmark.cc
Requires some concurrent edits because `benchmark::DoNotOptimize(T const&)` has been deprecated with "The const-ref version of this method can permit undesired compiler optimizations in benchmarks".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12015)
=> chore(deps): update benchmark to v1.8.1

google/cloud/bigtable/internal/async_row_reader.cc, google/cloud/bigtable/internal/async_row_reader.h, google/cloud/bigtable/internal/async_row_reader_test.cc, google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/internal/default_row_reader.cc, google/cloud/bigtable/internal/default_row_reader.h, google/cloud/bigtable/internal/default_row_reader_test.cc, google/cloud/bigtable/internal/legacy_async_row_reader.cc, google/cloud/bigtable/internal/legacy_row_reader.cc, google/cloud/bigtable/internal/legacy_row_reader_test.cc, google/cloud/bigtable/internal/readrowsparser.cc, google/cloud/bigtable/internal/readrowsparser.h, google/cloud/bigtable/internal/readrowsparser_test.cc
Part of the work for #12010 
- Have sync/async row readers set the `reversed` flag
- Teach sync/async row readers how to resume a reverse scan
- Teach the row parser about reverse row orders
The diff might have been prettier had I defaulted the `bool reverse` used to initialize a `ReadRowsParser`. I know at least one person on the team who does not like to use defaulted arguments for internal-only APIs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12013)
=> impl(bigtable): reverse scan internals

.codecov.yml, ci/cloudbuild/builds/coverage.sh
We only report code coverage for hand-crafted code, as the generated code is not tested directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12019)
=> test(bigquery): include `v2/` in coverage results

bazel/deps-cache.py
Adapt to the new shape of google_cloud_cpp_deps.bzl, where #11724 introduced an additional `maybe()` calling function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12017)
=> chore(deps): adapt deps-cache.py to new google_cloud_cpp_deps.bzl

google/cloud/bigtable/data_connection.cc, google/cloud/bigtable/data_connection.h, google/cloud/bigtable/examples/read_snippets.cc, google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/options.h, google/cloud/bigtable/tests/data_integration_test.cc
Fixes #12010 
- Adds a `ReverseScanOption` and passes its value to the sync/async row readers
- Adds a `bool reverse` field to the `ReadRowsParams`
- Adds a sample
- Adds an integration test
Note that the emulator does not yet support returning rows in reverse.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12022)
=> feat(bigtable): reverse scans

google/cloud/completion_queue_benchmark.cc, google/cloud/spanner/bytes_benchmark.cc, google/cloud/spanner/internal/merge_chunk_benchmark.cc, google/cloud/spanner/numeric_benchmark.cc, google/cloud/spanner/row_benchmark.cc, google/cloud/storage/internal/crc32c_benchmark.cc
A followup to #12015 where we can simplify some calls to `benchmark::DoNotOptimize()` because we already have an r-value handy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12026)
=> cleanup: simplify some benchmark::DoNotOptimize() calls

ci/cloudbuild/builds/quickstart-production.sh
I missed these when enabling re-runs for other integration tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12036)
=> ci: re-run quickstarts to workaround flakes

google/cloud/pubsub/retry_policy.h
Part of the work for #9434
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12030)
=> docs(pubsub): document `RetryPolicy` interface

google/cloud/spanner/retry_policy.h
Part of the work for #9434
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12037)
=> docs(spanner): document `RetryPolicy` interface

google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable_test.cc
Part of the work for #11775 
The cloud trace proto only supports attributes of type: `bool`, `int`, or `string`. So convert composite attributes into a string.
I picked "|" as a separator. :shrug:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12038)
=> impl(otel): trace exporter handles composite attributes

google/cloud/bigtable/retry_policy.h
Changed the comments and class order to match the generated code and the code in other hand-crafted libraries.
Fixes #9434
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12040)
=> docs(bigtable): document `DataRetryPolicy`

README.md, doc/public-api.md
I thought the top-level README was getting cluttered.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12044)
=> docs: split public API doc

google/cloud/bigtable/tests/data_integration_test.cc
Related to #12010 
Bigtable does not make guarantees on how it stores column families, which is why we use `CheckEqualUnordered(...)` for a list of cells.
Bigtable does make guarantees on the order of row keys returned. So we should verify that a reverse scan receives rows in reverse order.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12054)
=> test(bigtable): verify reverse scan row order

google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.cc, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.h, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy_test.cc
Implements the `Idempotency` policy for query api, with tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12051)
=> impl(bigquery): Idempotency policy Query api

ci/cloudbuild/cloudbuild.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12070)
=> ci: increase timeout to accommodate clang-tidy-full

google/cloud/bigtable/internal/bigtable_stub_factory.cc, google/cloud/bigtable/internal/bigtable_stub_factory_test.cc
cc: @igorbernstein2 who pointed out that the feature flags metadata should be web safe escaped.
Aside: there are probably several uses of `internal::Base64Encoder` that could be replaced with the abseil implementation. I do not plan to refactor them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12057)
=> cleanup(bigtable): websafe encoding of feature flags

.github/workflows/external-account-integration.yml
The vcpkg binary cache uses the compiler executable SHA as part of its hash. We need to include these files in the GHA hash or the GHA is treated as "valid" even though it is no longer usable.
Save the vcpkg cache as soon as it builds correctly. This preserves the vcpkg cache when our build fails but building the deps succeeded.
Part of the work for #11211
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12077)
=> ci: more robust vcpkg cache for GHA build

google/cloud/credentials.h, google/cloud/internal/credentials_impl.cc, google/cloud/internal/credentials_impl.h, google/cloud/internal/credentials_impl_test.cc, google/cloud/internal/curl_rest_client.cc, google/cloud/internal/grpc_impersonate_service_account.cc, google/cloud/internal/oauth2_impersonate_service_account_credentials.cc, google/cloud/internal/unified_grpc_credentials.cc, google/cloud/internal/unified_grpc_credentials.h, google/cloud/internal/unified_grpc_credentials_test.cc, google/cloud/internal/unified_rest_credentials.cc, google/cloud/internal/unified_rest_credentials.h, google/cloud/internal/unified_rest_credentials_test.cc, google/cloud/storage/client_options.cc, google/cloud/storage/internal/impersonate_service_account_credentials.cc, google/cloud/storage/internal/unified_rest_credentials.cc, google/cloud/storage/internal/unified_rest_credentials.h, google/cloud/storage/internal/unified_rest_credentials_test.cc
When mapping `google::cloud::Credentials` to the implementation (gRPC or REST) we don't need a `std::shared_ptr<>` or (shudder) `std::shared_ptr<> const&`.  The visitor can work with a `const&`.
Motivated by https://github.com/googleapis/google-cloud-cpp/pull/12064#discussion_r1260032585
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12073)
=> cleanup: const-correctness for unified credentials

google/cloud/opentelemetry/configure_basic_tracing.cc, google/cloud/opentelemetry/internal/recordable_test.cc, google/cloud/opentelemetry/samples/samples.cc
Prepare for `opentelemetry-cpp` v1.10.0. (See the `renovate-bot` PR: #12072)
Tested (using `cxx14`): https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/a813048e-5eca-49d7-b316-182ac714efe9?project=cloud-cpp-testing-resources&jsmode=o&mods=logs_tg_prod
Note that the `cxx20` build fails for a different (external) reason. I sent https://github.com/open-telemetry/opentelemetry-cpp/pull/2230 upstream.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12075)
=> cleanup(otel): fix includes for v1.10.0

google/cloud/internal/base64_transforms.h, google/cloud/internal/make_jwt_assertion.cc, google/cloud/internal/openssl_util.cc, google/cloud/internal/openssl_util.h, google/cloud/storage/oauth2/service_account_credentials_test.cc
@devbww points out that we no longer `#include <algorithm>` while using `std::replace()` after #12508, which has google3 consequences.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12078)
=> cleanup: IWYU after #12058

google/cloud/bigtable/polling_policy_test.cc, google/cloud/bigtable/rpc_retry_policy_test.cc, google/cloud/internal/retry_policy_impl_test.cc, google/cloud/polling_policy_test.cc, google/cloud/testing_util/check_predicate_becomes_false.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12094)
=> test(bigtable): log more to deflake a test

cmake/GoogleCloudCppFeatures.cmake
If only the `compute` feature is enabled we need to manually enable `rest_internal`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12096)
=> fix(compute): enable `rest_internal` if needed

google/cloud/internal/curl_rest_client.cc
We were always including the REST tracing client. Now, only include it if tracing is enabled, as determined by the `Options`.
`Make(Default|Pooled)RestClient(...)` are one of those interfaces (like `Make*Connection()`) that are difficult to cover with unit tests. If someone asks, I can try to cover it in an integration test.
---
**NOTE:** I also changed a
```cc
std::make_shared<DefaultCurlHandleFactory>(options);
```
to a
```cc
GetDefaultCurlHandleFactory(options);
```
The difference is that `GetDefaultCurlHandleFactory(options)` checks if `CARootsFilePathOption` is empty, before using it and `CAPathOption`: https://github.com/googleapis/google-cloud-cpp/blob/08e52b4aaf243363a6be3a3e2e37740ff8754945/google/cloud/internal/curl_handle_factory.cc#L39
I think that is the one we want. @coryan …
=> cleanup(rest): only trace if enabled

.github/workflows/external-account-integration.yml, .github/workflows/test-runner.yml, ci/gha/builds/external-account.sh, ci/gha/builds/lib/cmake.sh, ci/gha/builds/lib/linux.sh
Restructure the external-accounts build to support additional builds in the near future. All the steps to prepare the VM running the build are in the workflow file. The steps to compile the code are in a shell script, which follows the structure of analogous scripts for the GCB-based builds.
This build is still "special" in that it runs one integration test from the workflow file. We may want to refactor that in the future.
This helps with #11944. It also prepares us to move the macOS builds to GHA, which I hope will avoid problems such as #10272 and #9975
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12095)
=> ci(gha): restructure external accounts build

google/cloud/testing_util/opentelemetry_matchers.cc, google/cloud/testing_util/opentelemetry_matchers.h
Use a scoped span catcher object, that restores the `NoopTracerProvider` after a test runs.
If we forget to `InstallSpanCatcher()` in a test that creates spans, we can see a different valid test fail, because it picks up the extra spans. I don't quite understand why that behavior happens, but I think this PR will eliminate it.
Keep the interface the same so I don't have to update N tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12097)
=> cleanup(otel): tests use scoped span catcher

google/cloud/internal/oauth2_service_account_credentials.cc
The best explanation I found is in:
https://github.com/confluentinc/librdkafka/issues/3554#issuecomment-924787199
Basically using the `FILE*` variants of OpenSSL functions requires linking to the same MSVC runtime as the OpenSSL DLL, that can be tricky to figure out. Using the `BIO*` variants does not have the problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12105)
=> fix(common): avoid run-time conflicts on Windows

.github/workflows/macos.yml
The `Core` shard was too slow under Bazel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12121)
=> ci(gha): reshard macOS builds

ci/gha/builds/macos-bazel.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12127)
=> ci(gha): workaround Bazel on macOS crash

google/cloud/spanner/integration_tests/client_integration_test.cc, google/cloud/spanner/samples/samples.cc
As is often the case, the integration tests don't exercise anything that is particularly specific to the client implementation, but we adhere to the cross-language test specification none the less.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12122)
=> feat(spanner): tests and samples for foreign-key delete cascade

.github/workflows/test-runner.yml
Using the wrong step id results in an empty string (not an error), and then you checkout the target branch instead of the PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12134)
=> ci(gha): checkout correct version on PRs

.github/workflows/test-runner.yml, .github/workflows/windows.yml, ci/gha/builds/cmake/windows-sccache.cmake, ci/gha/builds/lib/bazel.sh, ci/gha/builds/lib/cmake.sh, ci/gha/builds/lib/windows.sh, ci/gha/builds/windows-bazel.sh, ci/gha/builds/windows-cmake.sh
As usual, we want to test the builds with Bazel and CMake. We also support MSVC 2019 and MSVC 2022, so we want to test with both compilers. And with MSVC there is a big difference between the C++ library in Debug vs. Release mode, so we need to test both. There is no need to test all these things with Bazel and CMake. So Bazel gets one build and CMake gets 4.  We also need to shard the builds.
This replaces the flakes caused by Kokoro with flakes caused by GHA (hopefully fewer). It also improves the caching strategy for Windows builds using sccache as proposed in #11944
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12128)
=> ci(gha): create configuration for Windows builds

google/cloud/spanner/doc/override-retry-policies.dox, google/cloud/spanner/doc/spanner-main.dox
Documentation for the `TransactionRerunPolicy` and its two, supplied implementations, the `LimitedErrorCountTransactionRerunPolicy` and the `LimitedTimeTransactionRerunPolicy`.  Link to the "commit-with-policies" snippet.  Fixes #11269.
Also separate the "spanner-retry-policies" documentation into its own `.dox` file, expanding the treatment of `spanner::RetryPolicy` and `spanner::BackoffPolicy` in the process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12140)
=> doc(spanner): add documentation/sample for TransactionRerunPolicy

.github/workflows/test-runner.yml
Tested on https://github.com/googleapis/google-cloud-cpp/actions/runs/5591585074
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12144)
=> ci(gha): stop concurrent builds for same PR

generator/integration_tests/tests/golden_kitchen_sink_tracing_connection_test.cc, generator/integration_tests/tests/golden_kitchen_sink_tracing_stub_test.cc, generator/integration_tests/tests/golden_thing_admin_tracing_connection_test.cc, generator/integration_tests/tests/golden_thing_admin_tracing_stub_test.cc, google/cloud/bigtable/internal/data_tracing_connection_test.cc, google/cloud/internal/async_polling_loop_test.cc, google/cloud/internal/async_read_write_stream_tracing_test.cc, google/cloud/internal/async_rest_polling_loop_test.cc, google/cloud/internal/async_streaming_read_rpc_tracing_test.cc, google/cloud/internal/async_streaming_write_rpc_tracing_test.cc, google/cloud/internal/grpc_opentelemetry_test.cc, google/cloud/internal/minimal_iam_credentials_stub_test.cc, google/cloud/internal/opentelemetry_test.cc, google/cloud/internal/rest_opentelemetry_test.cc, google/cloud/internal/streaming_read_rpc_tracing_test.cc, google/cloud/internal/streaming_write_rpc_tracing_test.cc, google/cloud/internal/tracing_http_payload_test.cc, google/cloud/internal/tracing_rest_client_test.cc, google/cloud/internal/tracing_rest_response_test.cc, google/cloud/opentelemetry/internal/resource_detector_impl_test.cc, google/cloud/storage/internal/tracing_client_test.cc, google/cloud/testing_util/opentelemetry_matchers.h
Fixes #11082 
This is purely a rename. It eliminates strange code like: `EventAttributesAre(SpanAttribute<>(...))`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12154)
=> refactor(otel): rename attribute matcher

doc/contributor/howto-guide-adding-generated-libraries.md
Importantly, fix the `check-api` command from the "expanding a library" section.
Also, mention that `libraries.bzl` needs to be updated before we tell the developer to `bazel run //google/cloud/${library}/quickstart:quickstart`, which depends on the top level `//:${library}`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12157)
=> doc: nth pass on generating libraries

google/cloud/bigquery/v2/minimal/internal/project.cc, google/cloud/bigquery/v2/minimal/internal/project.h, google/cloud/bigquery/v2/minimal/internal/project_response.cc, google/cloud/bigquery/v2/minimal/internal/project_response_test.cc, google/cloud/bigquery/v2/minimal/testing/project_test_utils.cc
This PR implements the json field name changes for Project response object. It ensures the field names in the response are in accordance with the[ response body](https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/list#response-body) mentioned in the api docs.
No logic has been changes. Just the field names and corresponding unit tests.
This fixes the github issue https://github.com/googleapis/google-cloud-cpp/issues/12109
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12150)
=> impl(bigquery): Response field changes for Projects api

google/cloud/bigquery/v2/minimal/internal/dataset.cc, google/cloud/bigquery/v2/minimal/internal/dataset.h, google/cloud/bigquery/v2/minimal/internal/dataset_connection_test.cc, google/cloud/bigquery/v2/minimal/internal/dataset_logging_test.cc, google/cloud/bigquery/v2/minimal/internal/dataset_metadata_test.cc, google/cloud/bigquery/v2/minimal/internal/dataset_response.cc, google/cloud/bigquery/v2/minimal/internal/dataset_response_test.cc, google/cloud/bigquery/v2/minimal/internal/dataset_rest_stub_test.cc, google/cloud/bigquery/v2/minimal/internal/dataset_test.cc
This PR fixes the json field names in the response for the Dataset apis. Ensure  that the json field names parsed from the response body for the Get and list Dataset apis are in accordance with the API docs mentioned below:
https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets/get
https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets/list
The request object is already in compliance with the api docs.
No processing logic has been changes. Just the json field names that are being parsed from the response and corresponding unit tests.
This fixes the github issue https://github.com/googleapis/google-cloud-cpp/issues/12110
- - - …
=> impl(bigquery): Dataset api response field name changes

.github/workflows/test-runner.yml
This did not work as I expected when unrelated labels get added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12195)
=> ci(gha): do not trigger on `labeled`

google/cloud/bigquery/v2/minimal/internal/json_utils.cc, google/cloud/bigquery/v2/minimal/internal/json_utils.h, google/cloud/bigquery/v2/minimal/internal/json_utils_test.cc
This PR adds a SafeGetTo() json utility method for parsing fields from the json body, as a potential performance improvement.
Please see https://github.com/googleapis/google-cloud-cpp/issues/12188 for more details.
Application of this function will be in separate PRs based on the resource type. 
Please note that this function will only be applied to manual `to_json` and `from_json` methods.  It cannot be applied to `to_json` and `from_json` methods generated from NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT macros.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12192)
=> impl(bigquery): Adds SafeGetTo method for potential perf improvement

ci/cloudbuild/builds/publish-docs.sh
Use the same ideas as `check-api`. Move the retry loop outside the function so we can see the output when a retry is needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12189)
=> ci: parallelize uploads in `publish-docs`

google/cloud/bigquery/v2/minimal/internal/json_utils.cc, google/cloud/bigquery/v2/minimal/internal/json_utils.h, google/cloud/bigquery/v2/minimal/internal/json_utils_test.cc
This PR modifies the `SafeGetTo` function, that was added in https://github.com/googleapis/google-cloud-cpp/pull/12192  to be a template function. This is done so that the function can be applied to all json field types and not just strings.
My apologies, I should have thought of the above when I sent the initial PR but completely slipped my mind, till I started applying the function to the json fields.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12199)
=> impl(bigquery): Modified SafeGetTo() to be a template function

google/cloud/bigquery/v2/minimal/internal/project.cc
This PR applies the SafeGetTo() from [PR-12199](https://github.com/googleapis/google-cloud-cpp/pull/12199) to `Project` resource's response parsing i.e `from_json` methods.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12214)
=> impl(bigquery): Applies SafeGetTo function to project json parsing

google/cloud/bigquery/BUILD.bazel, google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/v2/minimal/internal/dataset_logging.cc, google/cloud/bigquery/v2/minimal/internal/log_wrapper.h, google/cloud/bigquery/v2/minimal/internal/table_logging.cc
Part of the work for #12210 
cc: @jsrinnn @sachinpro 
Stream the status, instead of calling `DebugString(status, options)`.
Note that no behavior is changed, as:
1. the implementation is to stream the status as is
https://github.com/googleapis/google-cloud-cpp/blob/6dcf55e64db842b781f8f2f0a45b15d005e023bd/google/cloud/internal/debug_string_status.cc#L36-L38
2. the payload is empty for `g::c::Status`es that do not originate from an RPC status.
https://github.com/googleapis/google-cloud-cpp/blob/6dcf55e64db842b781f8f2f0a45b15d005e023bd/google/cloud/internal/debug_string_status.cc#L39-L42
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12215)
=> cleanup(bigquery): drop grpc_utils dep

generator/internal/discovery_file.cc, generator/internal/discovery_file.h, generator/internal/discovery_file_test.cc, generator/internal/discovery_resource.cc, generator/internal/discovery_resource_test.cc, generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc, generator/internal/discovery_type_vertex.cc, generator/internal/discovery_type_vertex.h, generator/internal/discovery_type_vertex_test.cc
part of the work for #11095 
ThisPR creates the descriptor pool for the current generation of compute protos and plumbs the pointer down to DiscoveryTypeVertex where it will be used later (in a follow up PR) to determine field numbers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12230)
=> impl(generator): create descriptor pool and plumb through

google/cloud/spanner/client_options.h, google/cloud/spanner/commit_options.h, google/cloud/spanner/connection_options.h, google/cloud/spanner/partition_options.h, google/cloud/spanner/query_options.h, google/cloud/spanner/read_options.h, google/cloud/spanner/session_pool_options.h, google/cloud/spanner/tracing_options.h
Mark the `spanner::${foo}Options` classes that are only used in the backwards-compatibility `spanner::Client` functions as deprecated. List the "Options" types that should be used in their place.
Note: These are still also used when mocking a `spanner::Connection`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12256)
=> doc(spanner): mark obsolete Spanner options classes as deprecated

.bazelrc
Bazel limits the "size of the stdout / stderr files that will be printed to the console."  The default limit is 1MB, but I've seen our logging can exceed that, so let's try removing the limit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12259)
=> test: remove the bazel limit on the size of test output

google/cloud/bigquery/v2/minimal/internal/job_response.cc, google/cloud/bigquery/v2/minimal/internal/job_response.h, google/cloud/bigquery/v2/minimal/internal/job_response_test.cc, google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.cc, google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.h
This PR Implements the [GetQueryResultsResponse](https://source.corp.google.com/piper///depot/google3/google/cloud/bigquery/v2/job.proto;l=646;rcl=544196886) object for the `GetQueryResults` api, with unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12249)
=> impl(bigquery): Response object for GetQueryResults api

google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.cc, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.h, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy_test.cc
Implements Idempotency policy for GetQueryResults api, with unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12250)
=> impl(bigquery): Idempotency policies for GetQueryResults api

google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc, google/cloud/bigquery/v2/minimal/internal/json_utils.h, google/cloud/bigquery/v2/minimal/internal/json_utils_test.cc
1) This PR applies the SafeGetTo() from [PR-12199](https://github.com/googleapis/google-cloud-cpp/pull/12199) to the resources defined in `common_v2_resources.h` that all apis use.
2) it also adds a clang-tidy warning suppression related to recursive fields that are used in the common resources.
FYI: I will be sending around 4 to 5 PRs after this one, that applies the SafeGetTo() 
to the different V2 apis i.e Job, Table, Dataset and Projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12208)
=> impl(bigquery): Applies SafeGetTo function to common resources

google/cloud/bigquery/v2/minimal/internal/job_logging.cc, google/cloud/bigquery/v2/minimal/internal/job_logging.h, google/cloud/bigquery/v2/minimal/internal/job_logging_test.cc, google/cloud/bigquery/v2/minimal/internal/job_metadata.cc, google/cloud/bigquery/v2/minimal/internal/job_metadata.h, google/cloud/bigquery/v2/minimal/internal/job_metadata_test.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.h, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc, google/cloud/bigquery/v2/minimal/testing/mock_job_rest_stub.h
This implements Rest stub, logging and metadata decorators for GetQueryResults() api with unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12261)
=> impl(bigquery): Stub and Decorator changes for GetQueryResults api

google/cloud/bigtable/internal/bigtable_stub_factory.cc, google/cloud/bigtable/internal/bigtable_stub_factory_test.cc
Tell the bigtable server that our client supports resuming from the last scanned row key.
Note that lowercase characters are part of the base64 alphabet. I just forgot to include them earlier: https://datatracker.ietf.org/doc/html/rfc4648#section-4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12270)
=> chore(bigtable): update feature flags

google/cloud/bigquery/v2/minimal/internal/job_client.cc, google/cloud/bigquery/v2/minimal/internal/job_client.h, google/cloud/bigquery/v2/minimal/internal/job_client_test.cc, google/cloud/bigquery/v2/minimal/internal/job_connection.cc, google/cloud/bigquery/v2/minimal/internal/job_connection.h, google/cloud/bigquery/v2/minimal/internal/job_connection_test.cc, google/cloud/bigquery/v2/minimal/internal/job_response.cc, google/cloud/bigquery/v2/minimal/internal/job_response.h, google/cloud/bigquery/v2/minimal/internal/job_response_test.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.h, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc, google/cloud/bigquery/v2/minimal/mocks/mock_job_connection.h, google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.cc, google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.h
This PR renames `QueryResults` response structure to `PostQueryResults` for the `Query` api which currently looks like this
in the `job_connection.h`
```
virtual StatusOr<QueryResults> Query(PostQueryRequest const& request);
```
After the rename it will look like this
```
virtual StatusOr<PostQueryResults> Query(PostQueryRequest const& request);
```
The above is done to avoid confusion with the `QueryResults` api which will have a similar response . This api is not yet added to the `job_connection.h` and will be added in subsequent PRs. The api below is needed to retrieve the query results from the above `Query` api if the results are more than a single page.
```
virtual StreamRange<GetQueryResults> QueryResults(GetQueryResultsRequest const& request);
```
- - - …
=> impl(bigquery): Rename QueryResults to PostQueryResults for Query api

google/cloud/spanner/samples/postgresql_samples.cc, google/cloud/spanner/samples/samples.cc
Bit-Reversed Sequence provides a way for Cloud Spanner to automatically generate hotspot-proof, unique 64-bit values for primary key columns. Manually bit-reversing monotonic key values is now recommended as a best practice.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12280)
=> feat(spanner): samples for bit-reversed sequence

google/cloud/bigquery/v2/minimal/internal/dataset_response.cc, google/cloud/bigquery/v2/minimal/internal/dataset_response_test.cc, google/cloud/bigquery/v2/minimal/internal/job_response.cc, google/cloud/bigquery/v2/minimal/internal/job_response_test.cc, google/cloud/bigquery/v2/minimal/internal/project_response.cc, google/cloud/bigquery/v2/minimal/internal/project_response_test.cc, google/cloud/bigquery/v2/minimal/internal/table_response.cc, google/cloud/bigquery/v2/minimal/internal/table_response_test.cc, google/cloud/bigquery/v2/minimal/testing/project_test_utils.cc, google/cloud/bigquery/v2/minimal/testing/project_test_utils.h, google/cloud/bigquery/v2/minimal/testing/table_test_utils.cc, google/cloud/bigquery/v2/minimal/testing/table_test_utils.h
This PR fixes GitHub issue https://github.com/googleapis/google-cloud-cpp/issues/12269
The `List*` apis currently assume `nextPageToken` to be a required response field with value empty for single page and non-empty for multiple pages. But from E2E testing it was revealed that `nextPageToken` is completely omitted for single page.
This PR addresses the above and makes `nextPageToken` field optional for all List apis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12276)
=> impl(bigquery): Makes pageToken optional in the List response

google/cloud/bigquery/v2/minimal/internal/json_utils.cc, google/cloud/bigquery/v2/minimal/internal/json_utils.h, google/cloud/bigquery/v2/minimal/internal/json_utils_test.cc
This PR fixes https://github.com/googleapis/google-cloud-cpp/issues/12268
Currently all time fields in the response are expected to be numbers for parsing into chrono fields, but in actual they are being sent as strings (or numbers within quotes).
This PR modifies the `to_json` and `from_json1 methods for chrono fields to accomodate both strings and numbers as it is not guaranteed that all time fields would be sent as strings in the future as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12278)
=> impl(bigquery): Update json parsing for time fields

cmake/CompileProtos.cmake, google/cloud/pubsub/samples/CMakeLists.txt, google/cloud/storage/tests/CMakeLists.txt
The `LOCAL_INCLUDE` option was no longer needed, and actually caused problems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12286)
=> cleanup: simplify CMake functions to compile protos

google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc, google/cloud/storage/client.cc, google/cloud/storage/examples/storage_bucket_requester_pays_samples.cc, google/cloud/storage/examples/storage_grpc_samples.cc, google/cloud/storage/examples/storage_object_csek_samples.cc, google/cloud/storage/examples/storage_object_preconditions_samples.cc, google/cloud/storage/examples/storage_object_samples.cc, google/cloud/storage/examples/storage_public_object_samples.cc, google/cloud/storage/tests/slow_reader_chunk_integration_test.cc
Prefer `is.bad()` over `!is.status().ok()` because the former should be more familiar to C++ programmers, and one of the invariants in the library is that if `!is.status().ok()` then `is.bad()` is true.
Add missing error handling to several examples.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12289)
=> cleanup(storage): consistent error-handling in samples

google/cloud/internal/rest_retry_loop.h, google/cloud/internal/rest_retry_loop_test.cc, google/cloud/internal/retry_loop.h, google/cloud/internal/retry_loop_test.cc
The retry policy may be expired when it enters the retry loop. For example, time-based policies may suffer from poor scheduling luck.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12301)
=> fix(common): handle expired policies in `*RetryLoop`

google/cloud/storage/google_cloud_cpp_storage.cmake, google/cloud/storage/storage_client_testing.bzl, google/cloud/storage/testing/mock_generic_stub.h
Part of the work for #12294, probably should have done this with the introduction of the class.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12305)
=> impl(storage): `storage_internal::GenericStub` mock

google/cloud/storage/client_test.cc, google/cloud/storage/grpc_plugin_test.cc, google/cloud/storage/internal/curl/client.cc, google/cloud/storage/internal/curl/client.h, google/cloud/storage/internal/generic_stub.h, google/cloud/storage/internal/generic_stub_adapter.cc, google/cloud/storage/internal/grpc/client.cc, google/cloud/storage/internal/grpc/client.h, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/internal/hybrid_client.h, google/cloud/storage/internal/logging_client.cc, google/cloud/storage/internal/logging_client.h, google/cloud/storage/internal/raw_client.cc, google/cloud/storage/internal/raw_client.h, google/cloud/storage/internal/rest/client.cc, google/cloud/storage/internal/rest/client.h, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client.h, google/cloud/storage/internal/tracing_client.cc, google/cloud/storage/internal/tracing_client.h, google/cloud/storage/testing/mock_client.h, google/cloud/storage/testing/mock_generic_stub.h
Make the decorator stack easier to test. A new member function returns the elements in the stack, by name, we can then inspect the names in the tests.
Part of the work #12294
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12307)
=> impl(storage): testable decorator stack

generator/integration_tests/tests/golden_thing_admin_connection_test.cc, generator/integration_tests/tests/golden_thing_admin_rest_connection_test.cc, google/cloud/accesscontextmanager/CMakeLists.txt, google/cloud/apigeeconnect/CMakeLists.txt, google/cloud/assuredworkloads/CMakeLists.txt, google/cloud/internal/async_rest_retry_loop.h, google/cloud/internal/async_rest_retry_loop_test.cc, google/cloud/internal/async_retry_loop.h, google/cloud/internal/async_retry_loop_test.cc, google/cloud/internal/rest_retry_loop.h, google/cloud/internal/rest_retry_loop_test.cc, google/cloud/internal/retry_loop.h, google/cloud/internal/retry_loop_helpers.cc, google/cloud/internal/retry_loop_helpers.h, google/cloud/internal/retry_loop_helpers_test.cc, google/cloud/internal/retry_loop_test.cc, google/cloud/oslogin/CMakeLists.txt, google/cloud/pubsub/internal/subscriber_connection_impl.cc, google/cloud/servicecontrol/CMakeLists.txt, google/cloud/shell/CMakeLists.txt, google/cloud/status.cc, google/cloud/status.h, google/cloud/storage/client_object_test.cc, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/testing/retry_tests.h
Use the `Status::error_info()` to signal details about why a retry loop fails. We were using the contents of the message.
Fixes #12303
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12313)
=> feat(common): retry loops signal via error info

generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc
part of the work for #11190 
In order to eventually add the appropriate import statements between proto files, the generator needs to determine all the $ref types present in the discovery document for a given type.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12317)
=> impl(generator): determine all depended on discovery types for given type

google/cloud/storage/client.cc, google/cloud/storage/client_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12314)
=> fix(storage): tracing should decorate retries

google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable_test.cc
When the Cloud Trace UI changed, it started showing parent spans with null ids.
So stop setting the field on our end, in that case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12323)
=> cleanup(otel): omit invalid parent span IDs

generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc, generator/internal/discovery_type_vertex.cc, generator/internal/discovery_type_vertex.h
part of the work for #11190 
Add dependency edges between the type vertices for later use.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12320)
=> impl(generator): set dependencies between discovery types

generator/internal/discovery_resource.cc, generator/internal/discovery_resource.h, generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc, generator/internal/discovery_type_vertex.cc, generator/internal/discovery_type_vertex.h
part of the work for #11190 
For every type a resource depends on, add its name as a label to the depended upon type. The generator uses this information later to group types into common proto files and to determine import paths.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12329)
=> impl(generator): apply resource labels to types

google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client.h, google/cloud/storage/internal/retry_client_bucket_acl_test.cc, google/cloud/storage/internal/retry_client_bucket_test.cc, google/cloud/storage/internal/retry_client_default_object_acl_test.cc, google/cloud/storage/internal/retry_client_notifications_test.cc, google/cloud/storage/internal/retry_client_object_acl_test.cc, google/cloud/storage/internal/retry_client_object_copy_test.cc, google/cloud/storage/internal/retry_client_object_test.cc, google/cloud/storage/internal/retry_client_service_account_test.cc, google/cloud/storage/internal/retry_client_sign_blob_test.cc, google/cloud/storage/testing/retry_tests.cc, google/cloud/storage/testing/retry_tests.h
With this change the `RetryClient` loops populate the idempotency token header. More PRs are required to propagate this value to the stubs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12327)
=> impl(storage): populate idempotency token header

google/cloud/opentelemetry/configure_basic_tracing.h
Fixes #11733 
I don't think this was worthy of a full document, so just write it up in the function's documentation.
Also, while we are here, resolve an old TODO about linking the quickstart.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12345)
=> docs(otel): troubleshoot exporter doc

google/cloud/storage/grpc_plugin.cc, google/cloud/storage/grpc_plugin_test.cc, google/cloud/storage/internal/async/connection_impl.cc, google/cloud/storage/internal/grpc/client.cc, google/cloud/storage/internal/grpc/client.h, google/cloud/storage/internal/grpc/client_acl_test.cc, google/cloud/storage/internal/grpc/client_insert_object_media_test.cc, google/cloud/storage/internal/grpc/client_read_object_test.cc, google/cloud/storage/internal/grpc/client_test.cc, google/cloud/storage/internal/grpc/client_upload_chunk_test.cc, google/cloud/storage/internal/grpc/configure_client_context.cc, google/cloud/storage/internal/grpc/configure_client_context.h, google/cloud/storage/internal/grpc/configure_client_context_test.cc, google/cloud/storage/internal/grpc/object_request_parser_test.cc, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/internal/hybrid_client.h
And as a `GenericStub`, it receives the `rest_internal::RestContext` and can propagate the idempotency token header to the service. In the case of operations emulated via OCC loops (most of the *AccessControl modifiers), we want the latest value after each iteration in the OCC loop. That is, the idempotency token should not be propagated in this case.
Part of the work for #12294.  Sorry for the overly large PR. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12343)
=> impl(GCS+gRPC): `GrpcClient` is a `GenericStub`

google/cloud/spanner/ci/lib/spanner_emulator.sh, google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh
Like the bazel builds, use a non-ephemeral port for the Spanner emulator when building with cmake.  Originally, in the bazel case, we used a fixed port so as to not invalidate the test cache.  But this meant that we also used a fixed, non-ephemeral port when adding the second emulator invocation (with HTTP support). Now we do the same with cmake for the second reason, which (largely) eliminates the chance of "Address already in use" errors.
Fixes #11073.
Also make the two invocations look similar, correct some environment variables names, and add the "--copy_emulator_stdout" option in the HTTP case (in case that is useful in future debugging).
- - - …
=> ci(spanner): stop using ephemeral ports for emulator with cmake

ci/cloudbuild/builds/generate-libraries.sh
Because we remove then add the common protos, if we defer formatting them until after they are added, the results of the formatting shows up as unstaged changes in git, causing the generate-libraries build to fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12352)
=> ci: format common protos earlier

google/cloud/opentelemetry/samples/samples.cc
Part of the work for #11777  (or internally, b/291745267)
I made up these region tag names. I need to use them in the C++ Cloud Trace docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12355)
=> impl(otel): add cloud docs snippet tags

google/cloud/storage/client.h, google/cloud/storage/idempotency_policy.cc, google/cloud/storage/idempotency_policy.h, google/cloud/storage/idempotency_policy_test.cc, google/cloud/storage/internal/retry_client_test.cc
Turns out that more work is needed in the service.
Reverts googleapis/google-cloud-cpp#12347
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12365)
=> Revert "feat(storage): all operations are idempotent"

google/cloud/internal/async_rest_retry_loop_test.cc, google/cloud/internal/async_retry_loop_test.cc, google/cloud/internal/rest_retry_loop_test.cc, google/cloud/internal/retry_loop_helpers.cc, google/cloud/internal/retry_loop_helpers_test.cc, google/cloud/internal/retry_loop_test.cc
Some applications want to have access to the original message, even after a retry failure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12368)
=> feat(common): retry loops preserve original message

google/cloud/internal/async_rest_retry_loop.h, google/cloud/internal/async_retry_loop.h, google/cloud/internal/call_context.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12369)
=> cleanup(common): `internal::CallContext` supports explicit options

google/cloud/bigtable/internal/async_bulk_apply.cc, google/cloud/bigtable/internal/async_row_reader.cc, google/cloud/bigtable/internal/async_row_sampler.cc, google/cloud/internal/async_polling_loop.cc, google/cloud/internal/async_rest_polling_loop.h, google/cloud/internal/async_rest_retry_loop.h, google/cloud/internal/async_retry_loop.h, google/cloud/internal/grpc_opentelemetry.h, google/cloud/internal/grpc_opentelemetry_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12372)
=> cleanup(common): explicit options for `TracedAsyncBackoff`

google/cloud/pubsub/internal/defaults.cc
Fixes #12328
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12306)
=> fix(pubsub): increase backoff from 1.3 to 4.0

google/cloud/bigtable/internal/logging_data_client.cc, google/cloud/internal/log_wrapper.h, google/cloud/internal/log_wrapper_test.cc
Some of the `LogWrapper` overloads are used in a single place. There is little need to expose them to all the rest of the code. And it may be easier to remove them if the future if they are in the same place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12380)
=> refactor: move single-use `LogWrapper` overloads

ci/cloudbuild/builds/clang-tidy-compute.sh
Building everything with clang-tidy wasn't completing even with a 10 hour timeout. Lower our expectations and build compute with clang-tidy which after splitting the protos has a "more reasonable" duration. 
The intent is to run this as a daily ci build as it still takes over an hour.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12382)
=> ci: build compute with clang-tidy separately instead of all

google/cloud/internal/log_wrapper.h, google/cloud/internal/log_wrapper_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12384)
=> cleanup(common): rm unused `LogWrapper` overload

google/cloud/internal/log_wrapper.h
I am sorry I missed this overload, I should have removed it in a previous pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12386)
=> cleanup(common): rm another unused `LogWrapper`

google/cloud/storage/internal/connection_impl_bucket_acl_test.cc, google/cloud/storage/internal/connection_impl_bucket_test.cc, google/cloud/storage/internal/connection_impl_default_object_acl_test.cc, google/cloud/storage/internal/connection_impl_notifications_test.cc, google/cloud/storage/internal/connection_impl_object_acl_test.cc, google/cloud/storage/internal/connection_impl_object_copy_test.cc, google/cloud/storage/internal/connection_impl_object_test.cc, google/cloud/storage/internal/connection_impl_service_account_test.cc, google/cloud/storage/internal/connection_impl_sign_blob_test.cc, google/cloud/storage/testing/retry_tests.cc, google/cloud/storage/testing/retry_tests.h
Part of the work for #12340
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12387)
=> cleanup(storage): rename `RetryClientTestOptions()`

generator/integration_tests/tests/golden_kitchen_sink_logging_decorator_test.cc, google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/internal/log_wrapper.cc, google/cloud/internal/log_wrapper.h, google/cloud/internal/log_wrapper_test.cc
Move repetitive code in `internal::LogWrapper` to an overload set that only knows how to log responses.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12389)
=> refactor(common): repetitive code in LogWrapper

google/cloud/dialogflow_cx/CMakeLists.txt, google/cloud/dialogflow_es/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12396)
=> cleanup: guard cmake quickstart targets with ENABLE_CXX_EXCEPTIONS

google/cloud/internal/default_completion_queue_impl.cc
Turns out `grpc::Alarm` is not thread-safe. The documentation is about to say so, and a future implementation will trigger more faults in our code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12406)
=> fix(common): gRPC alarms require more locking

google/cloud/options.cc, google/cloud/options.h, google/cloud/options_benchmark.cc
Once a `*Client` creates the first `OptionSpan` we can save the options as a `std::shared_ptr<Options const>`. This will let us reuse the options in new spans without copying. This is safe as the options in the current span were (and are) accessed as `Options const&`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12407)
=> impl(common): introduce immutable options

google/cloud/pubsublite/integration_tests/CMakeLists.txt, google/cloud/pubsublite/integration_tests/publisher_integration_test.cc
Pub/Sub Lite topics consume at least 4MiB/s of throughput capacity per partition. The default quota is 64 MiB/s. With 3 partitions a few simultaneous runs of the test can consume all the quota.
This change reduces the number of partitions to 1, so we can run at least 16 tests simultaneously.
The test was also mislabeled, and was running in most builds even though it does not use an emulator.
We could also use Lite Reservations to further reduce the capacity requirements per run, but that seems like a problem for another day.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12417)
=> test(pubsublite): reduce quota requirements

google/cloud/internal/async_retry_loop_test.cc
It is only used in the OTel tests, and is defined lower in the file: https://github.com/dbolduc/google-cloud-cpp/blob/458be5aa4338344f1e8cf90a7339814357237263/google/cloud/internal/async_retry_loop_test.cc#L606
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12418)
=> cleanup: unused using

cmake/GoogleCloudCppFeatures.cmake, google/cloud/apikeys/config.cmake.in, libraries.bzl
I think it is safe to remove the `google-cloud-cpp::experimental-apikeys` alias after 6 months.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12426)
=> chore: apikeys is GA

google/cloud/optimization/CMakeLists.txt
This function only takes one argument and we are not using `${ARGN}` or anything.
https://github.com/googleapis/google-cloud-cpp/blob/eef7b7c2421b0ffa867b254f50fd1bbf7bdd7d07/cmake/CompileProtos.cmake#L465-L474
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12425)
=> cleanup(optimization): remove unused parameter in cmake

google/cloud/options.h, google/cloud/options_benchmark.cc, google/cloud/options_test.cc
In our examples and documentation we use expressions like `Options{}.set<A>(a).set<B>(b)` and then pass the result by value. To get a move constructor out of such expressions the `set<>` functions must have a `&&` overload.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12424)
=> feat(common): add `Options::set<>() &&` overload

cmake/GoogleCloudCppLibrary.cmake
Part of the work for #12428 
- Check whether the sample directory exists instead of skipping `""` outright. (This unblocks one of the dialogflows)
- Uses `NAMELINK_COMPONENT`, as suggested by @coryan in review comments for #12429 
- No need for `google_cloud_cpp_common` in the `.pc` file when `google_cloud_cpp_grpc_utils` depends on `google_cloud_cpp_common`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12431)
=> cleanup(cmake): cleanups around library helper function

cmake/CompileProtos.cmake
Follow up to #10644
`PROTOBUF_IMPORT_DIRS` is a "List of additional directories to be searched for imported .proto files", according to https://cmake.org/cmake/help/v3.5/module/FindProtobuf.html
We were not setting it's value properly.
We were...
1. inserting an empty string
2. not setting the variable in the parent scope anyway
When I test these changes locally, I see `/usr/local/include` is added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12432)
=> fix: more reliable vcpkg+protobuf install

cmake/GoogleCloudCppLibrary.cmake, google/cloud/asset/CMakeLists.txt
Part of the work for #12428
`asset` is a weird one. We always compile that `orgpolicy` proto. Note that it is just messages. So it is not a huge deal, and I don't expect us to treat it any differently in light of #8022
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12433)
=> refactor(cmake): asset uses library helper

google/cloud/storage/client_test.cc
This function is deprecated, but not retired, we need to continue testing it, even if we stop using it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12449)
=> test(storage): verify `ClientFromMock()` works

generator/integration_tests/tests/golden_kitchen_sink_metadata_decorator_test.cc, generator/integration_tests/tests/golden_kitchen_sink_rest_metadata_decorator_test.cc, generator/integration_tests/tests/golden_thing_admin_rest_metadata_decorator_test.cc, google/cloud/bigtable/internal/legacy_row_reader_test.cc, google/cloud/bigtable/metadata_update_policy.cc, google/cloud/bigtable/metadata_update_policy_test.cc, google/cloud/internal/routing_matcher.h, google/cloud/internal/routing_matcher_test.cc, google/cloud/testing_util/validate_metadata.cc
Part of the work for #12232 
Update the explicit routing matchers to url encode the values in the routing pairs.
Update the part of `testing_util::ValidateMetadataFixture` that computes the expected routing headers.
Then legacy bigtable also uses that testing helper, so we must update it in this PR. I separated the bigtable stuff into its own commit (hopefully) for clarity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12447)
=> fix: URL encode explicit routing values

google/cloud/storage/internal/grpc/configure_client_context.cc, google/cloud/storage/internal/grpc/configure_client_context_test.cc, google/cloud/storage/internal/grpc/stub_test.cc
Part of the work for #12232
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12448)
=> fix(GCS+gRPC): URL encode routing params for streaming writes

google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/samples/samples.cc
It appears that we no longer need to avoid "europe-west9", but there is non-determinism in how we pick instance configs so a good course seems to be to restore normal behavior and see where we stand.  If problems reoccur, we can escalate.
Reverts #11516 and fixes #11346.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12455)
=> test(spanner): restore normal behavior of CreateInstanceConfig() tests

google/cloud/binaryauthorization/CMakeLists.txt, google/cloud/contentwarehouse/CMakeLists.txt
Motivated by #12428 
These libraries have dependencies on other libraries' protos.
`binaryauthorization_protos` depends on `grafeas_protos` and `contentwarehouse_protos` depends on `documentai_protos` already. So we do not need this extra stuff.
I looked into the history, and adding the extra `google-cloud-cpp::foo_protos` to `google_cloud_cpp_doxygen_targets()` seems to be a misdiagnosis of the problem that is solved by adding `google/cloud/foo` to `GOOGLE_CLOUD_CPP_DOXYGEN_EXTRA_INCLUDES`.
With this change, the cmake to generate these targets becomes standard, and they can adopt the common helpers. I am splitting the PRs up for atomicity.
- - - …
=> cleanup(cmake): simplify cross library deps

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/subscriber_connection_test.cc
Part of the work for #12232
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12454)
=> fix(pubsub): url encode routing params on publish

ci/verify_current_targets/CMakeLists.txt
Let's get these tests in place first before we start pulling the targets out of `external/googleapis/CMakeLists.txt` and compiling them as part of the client library targets.
Preemptively `find_package(...)` for the libraries that these targets will go to (that aren't already loaded earlier in the CMakeLists.txt). Alternatively, we could just add them to the GA libraries list above, but I'd rather keep it with the backwards compatibility tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12461)
=> ci: verify old proto libraries exist

ci/cloudbuild/builds/cmake-single-feature.sh
The `single-feature` build is only concerned with verifying installed targets. It does not need to build the testing targets.
This matters, because tests in `grpc_utils` depend on some libraries protos (`bigtable_protos`, `iam_protos`, `spanner_protos`) and we are no longer going to compile these protos by default, unless those features are enabled.
For the build failure we are avoiding, see:
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/224eb02b-5763-4638-8cfe-7232943dba5c;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/12462/96c2c14c65e71a542e5bae5c3c4d5ea2725f8ccd/fedora-37-cmake-cmake-single-feature/log-224eb02b-5763-4638-8cfe-7232943dba5c.t …
=> ci: ignore tests in single feature build

cmake/GoogleCloudCppLibrary.cmake, doc/contributor/howto-guide-declare-a-library-ga.md, generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator_test.cc
Part of the work for #12428 
Transition the scaffolding. Add support for experimental libraries.
Yes, we are adding EXPERIMENTAL to the GA library helper... I definitely misnamed the helper function. I will switch it to something like `google_cloud_cpp_gapic(...)` when there are fewer outstanding PRs.
I tested it manually like this: https://github.com/dbolduc/google-cloud-cpp/commit/1bf9012a4835353bfdc9ab9aa1b31d0079bbdae9
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12470)
=> refactor: scaffolding knows about cmake library helper

ci/cloudbuild/builds/cmake-install.sh, cmake/CompileProtos.cmake, external/googleapis/CMakeLists.txt
This proto was used by Cloud Debugger, which has been removed.
We are not offering any targets for backwards compatibility.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12459)
=> cleanup(cmake)!: stop compiling `source_context.proto`

ci/gha/builds/external-account.sh, external/googleapis/CMakeLists.txt, google/cloud/bigtable/CMakeLists.txt
My plan is to do #8022 in this release cycle. I will add one CHANGELOG entry when all the changes are complete.
Aside: That `PROTOBUF_IMPORT_DIRS` was a random thing that only existed in `bigtable`. It seems like something we learned did not matter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12462)
=> fix(cmake)!: only compile protos if asked - bigtable

ci/verify_current_targets/CMakeLists.txt, external/googleapis/CMakeLists.txt, google/cloud/dialogflow_es/CMakeLists.txt
Part of the work for #8022 and #12428 
This one has a legacy proto library with a name we don't like.
I forgot to include this library's legacy protos in the cmake install build, so that is done in this PR.
Also move `dialogflow_es` to the common cmake library helper.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12477)
=> fix(cmake)!: only compile protos if asked - dialogflow

external/googleapis/CMakeLists.txt, google/cloud/opentelemetry/CMakeLists.txt, google/cloud/trace/CMakeLists.txt
Part of the work for #8022 and #12428
This one has 2 legacy proto libraries with names we don't like.
Also move `trace` to the common cmake library helper.
Note that we are checking that the proto libraries still exist:
https://github.com/googleapis/google-cloud-cpp/blob/82d88becf1b6c9c2403a6f03fd86cd5744c908ab/ci/verify_current_targets/CMakeLists.txt#L84-L85
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12478)
=> fix(cmake)!: only compile protos if asked - trace

external/googleapis/CMakeLists.txt, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
This one is a bit weird. I think the protos should only be built with GCS+gRPC. (As opposed to, `storage IN LISTS GOOGLE_CLOUD_CPP_ENABLE AND GOOGLE_CLOUD_CPP_ENABLE_GRPC`)
Conditionally include the raw gRPC client in the throughput benchmark only if GCS+gRPC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12481)
=> fix(cmake)!: only compile protos if asked - storage

external/googleapis/CMakeLists.txt, google/cloud/bigquery/bigquery_rest.cmake, google/cloud/compute/CMakeLists.txt, google/cloud/google_cloud_cpp_common.cmake, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/google_cloud_cpp_rest_internal.cmake, google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake, google/cloud/grafeas/CMakeLists.txt, google/cloud/logging/CMakeLists.txt, google/cloud/opentelemetry/CMakeLists.txt, google/cloud/sql/CMakeLists.txt, google/cloud/storage/google_cloud_cpp_storage.cmake
Clean up the rest of these instead of deleting them randomly as they are encountered.
I left the one in pubsublite, because it is removed in #12484. (Am I making a mess, or cleaning one up? It is hard to say.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12486)
=> cleanup(cmake): use NAMELINK_COMPONENT

google/cloud/completion_queue_test.cc, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/internal/async_long_running_operation_test.cc, google/cloud/internal/async_polling_loop_test.cc, google/cloud/internal/async_rest_long_running_operation_test.cc, google/cloud/internal/async_rest_polling_loop_test.cc, google/cloud/internal/async_retry_unary_rpc_test.cc, google/cloud/internal/extract_long_running_result_test.cc, google/cloud/internal/unified_grpc_credentials_test.cc
Part of the work for #12485 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12488)
=> cleanup(common): avoid bigtable in unit tests

google/cloud/storage/async_object_requests.h, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake, google/cloud/storage/internal/async/write_payload_fwd.h, google/cloud/storage/internal/async/write_payload_impl.cc, google/cloud/storage/internal/async/write_payload_impl.h, google/cloud/storage/internal/async/write_payload_impl_test.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl
We need a public API for object payloads. Applications may need to examine the contents of the upload in their mocks, to ensure their code is sending the right data.
We want the implementation of this type to be an `absl::Cord`, so we can pass the data to gRPC and Protobuf without copying the contents.
Part of the work for #9131
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12458)
=> impl(GCS+gRPC): a class to represent write payloads

generator/internal/http_option_utils.cc, generator/internal/metadata_decorator_generator.cc, generator/internal/metadata_decorator_rest_generator.cc
Part of the work for #12232 
I am not adding any tests. I am almost certain that these keys cannot contain characters that need to be escaped. Note that there are no corresponding changes to any generated code...
But it is simple enough to encode them and the encoding is done at code generation time.... So whatever.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12440)
=> impl: url encode routing keys

google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake
Part of the work for #12485
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12490)
=> cleanup: rest internal no bigtable protos dep

generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator.h, generator/internal/scaffold_generator_test.cc
Part of the work for #12483
I have not thought through what to do for transition libraries. We don't really use these any more. So deferring the problem isn't horrible.
https://github.com/googleapis/google-cloud-cpp/blob/main/doc/contributor/howto-guide-declare-a-library-ga.md#googlecloudlibraryconfigcmakein
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12489)
=> ci: scaffolding stops generating config.cmake.in

ci/cloudbuild/build.sh, ci/cloudbuild/cloudbuild.yaml
Since adding the LIBRARIES var, manually starting cloudbuilds via build.sh was failing due to this new substitution that was not handled as one of the special case vars defined here: https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#using_user-defined_substitutions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12492)
=> ci: plumb through optional LIBRARIES substitution

cmake/GoogleCloudCppLibrary.cmake, google/cloud/bigtable/CMakeLists.txt, google/cloud/grafeas/CMakeLists.txt, google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsublite/CMakeLists.txt, google/cloud/spanner/CMakeLists.txt, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
Motivated by #8022 (and would have been wiser to do before sending many of the PRs). Also related to #12428 
Factor out the code to add proto libraries from protolists/protodeps. Use it in our handwritten libraries.
Our REST based libraries could probably use this too, but for now leave them alone.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12484)
=> refactor(cmake): client proto library creation

google/cloud/google_cloud_cpp_grpc_utils.cmake
An interim solution for #12485 
Thanks to #12488, it is easier to avoid the one test that still uses bigtable.
We will try running a full build, because I think our sharded GHA builds have been silently failing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12491)
=> ci: conditionally disable test that depends on `bigtable_protos`

ci/cloudbuild/builds/cmake-install.sh, cmake/CompileProtos.cmake, external/googleapis/CMakeLists.txt, google/cloud/appengine/CMakeLists.txt, google/cloud/logging/CMakeLists.txt, google/cloud/servicecontrol/CMakeLists.txt
Part of the work for #8022 and #12428
Only `iam` remains for both...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12502)
=> refactor(cmake)!: only compile protos if asked - logging

ci/cloudbuild/build.sh, ci/cloudbuild/cloudbuild.yaml, cmake/GoogleCloudCppDoxygen.cmake
Correctly plumbs the value of LIBRARIES from the trigger data through to publish-docs.sh.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12499)
=> ci: fix LIBRARIES substitution

google/cloud/storage/async_object_requests.h, google/cloud/storage/internal/grpc/configure_client_context.cc, google/cloud/storage/internal/grpc/configure_client_context.h, google/cloud/storage/internal/grpc/configure_client_context_test.cc, google/cloud/storage/internal/grpc/object_request_parser.cc, google/cloud/storage/internal/grpc/object_request_parser.h, google/cloud/storage/internal/grpc/object_request_parser_test.cc, google/cloud/storage/internal/hash_function.cc, google/cloud/storage/internal/hash_function.h, google/cloud/storage/internal/hash_function_impl_test.cc, google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h
We need a class to represent requests that insert objects via the `AsyncClient`. We cannot use the class from the synchronous client because that uses non-owning types for the data payload. And we also want the class in the public API (eventually) as it is needed for mocking.
Part of the work for #9131
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12503)
=> impl(GCS+gRPC): `InsertObjectRequest` for `AsyncClient`

google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake, google/cloud/internal/rest_log_wrapper_test.cc, google/cloud/internal/rest_stub_helpers_test.cc
At some point I had to switch up the request type from a `google::protobuf::Duration`, because that gets printed in JSON as: `{"123.000000456s"}` instead of `{"seconds":123,"nanos":456}`. :unamused:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12513)
=> cleanup: remove dep on IAM admin in unit tests

cmake/GoogleCloudCppLibrary.cmake
Part of the work for #8022, should have been done in #12514. Sorry for the churn.
We also need to add the shared proto deps to the package config file.
CMake readability note: I opted to link the private targets (`google_cloud_cpp_foo`) instead of the public ones (`google-cloud-cpp::foo`) because it saved me a variable and some list transforms. :shrug:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12518)
=> fix(cmake): shared proto deps in pc files

google/cloud/internal/async_retry_unary_rpc_test.cc
Due to clang tool failing to build in google3 import
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12517)
=> fix: remove testing_util::chrono_literals from async test

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12507)
=> doc: CHANGELOG entry for #8022

cmake/FindCurlWithTargets.cmake, cmake/GoogleCloudCppDoxygen.cmake, external/googleapis/CMakeLists.txt
Part of the work for #11781
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12542)
=> cleanup(cmake): remove pre-3.13 workarounds

google/cloud/internal/minimal_iam_credentials_stub.cc
Part of https://github.com/googleapis/google-cloud-cpp/issues/12232
I added no tests since DISABLED_AsyncGenerateAccessTokenMetadata should cover the case with the changes to the ValidateMetadataFixture in https://github.com/googleapis/google-cloud-cpp/pull/12544
I tried undisabling the test and it passed using bazel, so I think the issue is something with the Cmake configuration for the iam protos, but nothing stood out to me.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12558)
=> fix(internal): add url encoding for minimal iam creds

bazel/google_cloud_cpp_deps.bzl, bazel/libpfm.BUILD
It seems that sourceforge.net is down.  Provide an alternative URL to download `libpfm`, and indirect dependency via google/benchmark.  We do not use this dep, but the download failure breaks our build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12568)
=> ci: alternative url for `libpfm`

google/cloud/storage/google_cloud_cpp_storage.cmake, google/cloud/storage/internal/policy_document_request.cc, google/cloud/storage/internal/policy_document_request_test.cc
Use custom code to "escape" UTF-8 strings into the canonical format expected by the V4 signed URLs.  We were using `std::codecvt_utf8<>` which was deprecated in C++17.
Fixes #12550
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12563)
=> cleanup(storage): avoid deprecated C++ symbols

bazel/google_cloud_cpp_deps.bzl
Followup to #12568.
Remove the `str()` wrapper around `Label()`, which confuses the deps cacher script `bazel/deps-cache.py`.
Also remove the `/download` suffix from the URL, that similarly confused the deps cacher, and which appears to be superfluous.  This also removes the need for the `type` specifier.
Finally, reorder the `maybe()` arguments to match the other invocations. Provide an alternative URL to
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12573)
=> chore(deps): tweak definition of libpfm dependency

generator/internal/scaffold_generator.cc, google/cloud/config/v1/.repo-metadata.json
This ignores the `api_short_name` from the service YAML file and always uses the `nameInServiceConfig` aka `api_id` to generate the short name. Evidently the YAML files can have inconsistent names, and the short name and api id are required to match (which seems redundant).
Fixes #12552
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12575)
=> feat(generator): generate shortname from api id

google/cloud/internal/api_client_header.cc, google/cloud/internal/api_client_header.h, google/cloud/internal/api_client_header_test.cc
Create specific functions for generated vs. hand-crafted client libraries, preparing to delete the generic `ApiClientVersion()` function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12576)
=> impl(common): refactor x-goog-api-client functions

google/cloud/storage/client.h, google/cloud/storage/examples/storage_object_samples.cc
Show that both `InsertObject()` and `WriteObject()` can be used to upload data from memory. At least one customer missed the existence of `InsertObject()` because they thought the example showed **all** the ways.
Fixed the links showing the tradeoffs between single-shot and resumable-uploads. Be more explicit about what upload type does `InsertObject()` use.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12577)
=> docs(storage): more on InsertObject vs. WriteObject

google/cloud/bigtable/internal/bigtable_stub_factory.cc, google/cloud/bigtable/internal/bigtable_stub_factory_test.cc, google/cloud/bigtable/internal/legacy_async_row_reader_test.cc, google/cloud/bigtable/internal/legacy_row_reader_test.cc, google/cloud/bigtable/metadata_update_policy.cc, google/cloud/bigtable/table_apply_test.cc, google/cloud/bigtable/table_check_and_mutate_row_test.cc, google/cloud/bigtable/table_readmodifywriterow_test.cc, google/cloud/bigtable/table_readrow_test.cc, google/cloud/bigtable/testing/mock_async_failing_rpc_factory.h, google/cloud/bigtable/testing/mock_response_reader.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12579)
=> impl(bigtable): identify generated libraries

google/cloud/spanner/internal/database_admin_metadata.cc, google/cloud/spanner/internal/database_admin_metadata_test.cc, google/cloud/spanner/internal/instance_admin_metadata.cc, google/cloud/spanner/internal/instance_admin_metadata_test.cc, google/cloud/spanner/internal/spanner_stub_factory.cc
Part of the work #12562
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12581)
=> impl(spanner): identify generated libraries

google/cloud/internal/minimal_iam_credentials_stub.cc, google/cloud/internal/minimal_iam_credentials_stub_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12583)
=> impl(auth): identify generated libraries

google/cloud/pubsub/blocking_publisher_connection_test.cc, google/cloud/pubsub/internal/publisher_stub_factory.cc, google/cloud/pubsub/publisher_connection_test.cc, google/cloud/pubsub/subscriber_connection.cc, google/cloud/pubsub/subscriber_connection_test.cc, google/cloud/pubsub/subscription_admin_connection.cc, google/cloud/pubsub/subscription_admin_connection_test.cc, google/cloud/pubsub/topic_admin_connection_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12580)
=> impl(pubsub): identify generated libraries

google/cloud/storage/internal/storage_stub_factory.cc, google/cloud/storage/internal/storage_stub_factory_test.cc, google/cloud/storage/version.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12582)
=> impl(storage): identify generated libraries

google/cloud/bigquery/v2/minimal/internal/dataset_metadata.cc, google/cloud/bigquery/v2/minimal/internal/dataset_metadata_test.cc, google/cloud/bigquery/v2/minimal/internal/job_metadata.cc, google/cloud/bigquery/v2/minimal/internal/job_metadata_test.cc, google/cloud/bigquery/v2/minimal/internal/project_metadata.cc, google/cloud/bigquery/v2/minimal/internal/project_metadata_test.cc, google/cloud/bigquery/v2/minimal/internal/table_metadata.cc, google/cloud/bigquery/v2/minimal/internal/table_metadata_test.cc, google/cloud/bigquery/v2/minimal/testing/metadata_test_utils.cc, google/cloud/bigquery/v2/minimal/testing/metadata_test_utils.h, google/cloud/internal/curl_rest_client.cc, google/cloud/internal/curl_rest_client.h, google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/storage/internal/rest/request_builder.cc, google/cloud/storage/internal/rest/request_builder_test.cc, google/cloud/storage/internal/rest/stub_test.cc
For automatically generated REST-based clients we were injecting the `x-goog-api-client` header twice: once in the generated `*RestMetadataDecorator` class and once more in the `rest_internal::CurlRestClient` class.
With this change the hand-crafted libraries inject the header explicitly, and use the new `HandCraftedLibClientHeader()` to do so. Meanwhile, the generated libraries inject the header only in the decorator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12578)
=> impl: only decorators inject x-goog-api-client

release/README.md
Patch releases no longer require updating the API baseline.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12603)
=> docs: update patch release instructions

google/cloud/storage/async_client.cc, google/cloud/storage/async_client.h, google/cloud/storage/async_connection.h, google/cloud/storage/examples/storage_async_samples.cc, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake, google/cloud/storage/internal/async/connection_impl.cc, google/cloud/storage/internal/async/connection_impl.h, google/cloud/storage/internal/async/connection_impl_test.cc, google/cloud/storage/tests/async_client_integration_test.cc
This is now part of the `storage_experimental` namespace and it does not use internal symbols in its API. This makes it possible to mock `AsyncClient` without having to peer into the internal components of the library.
Fixes #12521
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12611)
=> cleanup(GCS+gRPC): `AsyncConnection` is not private

.clang-tidy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12614)
=> ci(clang-tidy): disable modernize clang-tidy checks

.typos.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12625)
=> chore: exclude external/googleapis.patch from typos

google/cloud/internal/minimal_iam_credentials_stub_test.cc, google/cloud/testing_util/validate_metadata.cc
`MinimalIamCredentialsStubTest.AsyncGenerateAccessTokenMetadata`: rather than disabling the test altogether, allow for failures of `FindMethodByName()` in `IsContextMDValid()`.  The code for the method may have been dropped by the linker, so it never registers itself.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12624)
=> test(common): allow for FindMethodByName() failure

ci/cloudbuild/builds/generate-libraries.sh
workaround for #12621
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12622)
=> ci: execute clang-format twice in generate-libraries

generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc, generator/internal/discovery_type_vertex.cc, generator/internal/discovery_type_vertex.h, generator/internal/discovery_type_vertex_test.cc
Compute was permitted to add exactly one `google.protobuf.Any` equivalent json to the Discovery Document, in order to support uniform error reporting, as part of a new `Status` schema such that:
```
message Status {
optional int32 code = 1;
repeated google.protobuf.Any details = 2;
optional string message = 3;
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12627)
=> impl(generator): add support for google.protobuf.Any in discovery doc

google/cloud/pubsub/publisher_connection.cc, google/cloud/pubsub/publisher_connection_test.cc
Use the MakePublisherTracingConnection if the Open Telemetry tracing option is set
Closes #[12525](https://github.com/googleapis/google-cloud-cpp/issues/12525)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12634)
=> impl(pubsub): use publisher tracing connection when otel is enabled

generator/integration_tests/tests/golden_kitchen_sink_tracing_stub_test.cc, generator/integration_tests/tests/golden_thing_admin_tracing_stub_test.cc, google/cloud/bigtable/internal/bigtable_stub_factory_test.cc, google/cloud/internal/grpc_opentelemetry.cc, google/cloud/internal/grpc_opentelemetry_test.cc, google/cloud/internal/minimal_iam_credentials_stub_test.cc, google/cloud/spanner/internal/spanner_stub_factory_test.cc, google/cloud/testing_util/google_cloud_cpp_testing_grpc.bzl, google/cloud/testing_util/google_cloud_cpp_testing_grpc.cmake, google/cloud/testing_util/opentelemetry_matchers.cc, google/cloud/testing_util/opentelemetry_matchers.h, google/cloud/testing_util/validate_propagator.cc, google/cloud/testing_util/validate_propagator.h
Part of the work for #12451 
Send both `x-cloud-trace-context` and `traceparent` headers over gRPC when tracing with OTel.
Note that we allocate a few unique_ptrs per request now. In a follow up PR I will cache the propagator in the gRPC stubs, so we only do this once at stub creation time.
Bland test updates are relegated to a second commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12635)
=> impl(otel): use composite propagator over gRPC

google/cloud/internal/tracing_rest_client.cc, google/cloud/internal/tracing_rest_client.h
Motivated by #12451 sorta
This refactor may make things nicer when we add an opentelemetry type as a member of this class.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12638)
=> refactor(rest+otel): move tracing client definition to .cc

google/cloud/internal/rest_opentelemetry.cc, google/cloud/internal/rest_opentelemetry.h, google/cloud/internal/rest_opentelemetry_test.cc, google/cloud/internal/tracing_rest_client.cc, google/cloud/internal/tracing_rest_client_test.cc
Fixes #11355 . Most of the remaining work for #12451 (there is an outstanding cleanup to remove unused functions).
Always use the composite propagator (`x-cloud-trace-context`, `traceparent`) over REST.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12643)
=> impl(otel): use composite propagator for REST

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/metadata_update_policy_test.cc, google/cloud/future_generic.h, google/cloud/future_void.h, google/cloud/internal/async_long_running_operation_test.cc, google/cloud/internal/async_rest_long_running_operation_test.cc, google/cloud/internal/default_completion_queue_impl.cc, google/cloud/internal/log_wrapper.h, google/cloud/internal/log_wrapper_test.cc, google/cloud/internal/rest_stub_helpers_test.cc, google/cloud/options.cc, google/cloud/options.h, google/cloud/storage/client.cc, google/cloud/storage/grpc_plugin.cc, google/cloud/storage/internal/async/connection_impl.cc, google/cloud/storage/internal/connection_impl.cc, google/cloud/storage/internal/connection_impl_test.cc, google/cloud/storage/internal/grpc/stub.h, google/cloud/storage/internal/hash_function.cc, google/cloud/storage/internal/logging_stub.cc, google/cloud/storage/internal/object_write_streambuf.cc, google/cloud/storage/internal/object_write_streambuf.h, google/cloud/storage/internal/retry_object_read_source.cc, google/cloud/storage/internal/retry_object_read_source.h, google/cloud/storage/object_rewriter.cc, google/cloud/storage/object_rewriter.h, google/cloud/storage/parallel_upload.cc, google/cloud/storage/tests/object_write_streambuf_integration_test.cc
Correct a mostly-random set of include-what-you-use problems by directly including the header previously found transitively.
Also tidy up some `future` comments while we're in the file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12646)
=> cleanup: deal with some include-what-you-use issues

doc/contributor/howto-guide-update-googleapis-sha.md, external/googleapis/renovate.sh
Move some of the steps used to update the googleapis/googleapis version from the recipe documented in the how-to guide, to the `renovate.sh` script.
In particular, the script now updates the protodeps/protolists files, runs the generate-libraries build, and creates git commits ready to be pushed.
This is another step towards possibly automating the whole process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12647)
=> impl: make external/googleapis/renovate.sh a little smarter

ci/cloudbuild/builds/lib/features.sh
I missed this in #12506
`iam_policy` was never released as a feature, so we can remove it from this list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12651)
=> cleanup: iam_policy never became a feature

google/cloud/bigtable/internal/bigtable_stub_factory_test.cc, google/cloud/pubsub/internal/publisher_tracing_connection.cc
Every so often I run clang-tidy with OTel disabled and find some nits. If only there was a way to do this automatically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12652)
=> chore: clang tidy fixes when no otel

google/cloud/bigtable/metadata_update_policy_test.cc, google/cloud/completion_queue_test.cc, google/cloud/internal/completion_queue_impl.h, google/cloud/internal/default_completion_queue_impl.cc, google/cloud/internal/default_completion_queue_impl.h
Includes an update to #12646, where the include was moved to a header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12657)
=> cleanup: deal with a few more random include-what-you-use issues

ci/cloudbuild/builds/cmake-split-install.sh, cmake/GoogleCloudCppFeatures.cmake
In some package ecosystems it may be valuable to compile only the common libraries. Previously it was impossible to compile `grpc_utils` or `rest` unless some feature was also enabled that required these common components.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12660)
=> feat: support builds for only common libraries

google/cloud/opentelemetry_options.h
Noticed while looking at #12332
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12670)
=> doc(otel): clarify when `OpenTelemetryTracingOption` applies

google/cloud/pubsub/internal/flow_controlled_publisher_tracing_connection_test.cc
Addressing comments in https://github.com/googleapis/google-cloud-cpp/pull/12637
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12664)
=> cleanup(pubsub): add otel expectation to tests

google/cloud/opentelemetry/internal/recordable.cc, google/cloud/opentelemetry/internal/recordable.h, google/cloud/opentelemetry/internal/recordable_test.cc
Part of the work for #12450 
The effect of this PR is that "otel.scope.*" attributes are only set on root spans. They are superfluous on child spans.
---
The OTel implementation calls `SetInstrumentationScope(...)` before `SetIdentity(...)`, so if we want to set it only on the root span, we have to remember its value.
https://github.com/open-telemetry/opentelemetry-cpp/blob/0563a71ce3ea2c580f535996aeb8ce9246f2d703/sdk/src/trace/span.cc#L68-L71
---
I acknowledge that it would have been wiser to treat most if not all `Recordable::Set*` functions this way. ("this way" means writing the proto in `as_proto()`, not in `SetFoo()`). But in the interest of time, I only plan to move the ones I need for now, and will leave the rest as technical debt for my future self.
- - - …
=> impl(otel): InstrumentationScope on root spans only

google/cloud/storage/client_options.cc, google/cloud/storage/internal/grpc/stub.cc
Fixes #12332
If tracing is enabled in the connection, and no credentials are supplied via Options, assume that the customer wants to trace the auth components.
For example, in our OTel tracing quickstart...
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12672)
=> fix(storage): trace auth when default credentials are assumed

google/cloud/bigtable/instance_admin.cc, google/cloud/bigtable/instance_admin_test.cc
Correct a few places where #12659 confused projects ids ("foo") and project names ("projects/foo").
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12675)
=> fix(bigtable): the Location ctor takes project ids

.github/workflows/test-runner.yml
This will let us trigger full builds manually. This can be used to test changes affecting the full build before the scheduled time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12682)
=> ci(gha): support manual builds

google/cloud/spanner/samples/samples.cc
Update the custom retry sample to use a max retry delay of 16 seconds, as that is smaller than the total timeout of 60 seconds. The current values are slightly confusing for users, as it could give the impression that retry delays are not counted towards the total timeout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12680)
=> docs(spanner): set max_delay to 16s
