googleapis/google-cloud-cpp

google/cloud/edgecontainer/v1/.repo-metadata.json
google/cloud/eventarc/publishing/v1/.repo-metadata.json
google/cloud/eventarc/v1/.repo-metadata.json

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11605)

chore(e*): backfill `.repo-metadata.json` files

---

google/cloud/filestore/v1/.repo-metadata.json
google/cloud/functions/v1/.repo-metadata.json
google/cloud/gameservices/v1/.repo-metadata.json
google/cloud/gkehub/v1/.repo-metadata.json
google/cloud/gkemulticloud/v1/.repo-metadata.json

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11607)

chore([fg]*): backfill `.repo-metadata.json` files

---

google/cloud/shell/v1/.repo-metadata.json

Fixes #11621
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11624)

chore(shell): fix `.repo-metadata.json` lint

---

google/cloud/networkconnectivity/v1/.repo-metadata.json
google/cloud/networkmanagement/v1/.repo-metadata.json
google/cloud/notebooks/v1/.repo-metadata.json

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11626)

chore(n*): backfill `.repo-metadata.json` files

---

google/cloud/kms/v1/.repo-metadata.json
google/cloud/language/v1/.repo-metadata.json
google/cloud/logging/v2/.repo-metadata.json
google/cloud/managedidentities/v1/.repo-metadata.json
google/cloud/memcache/v1/.repo-metadata.json
google/cloud/monitoring/dashboard/v1/.repo-metadata.json
google/cloud/monitoring/metricsscope/v1/.repo-metadata.json
google/cloud/monitoring/v3/.repo-metadata.json

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11625)

chore([klm]*): backfill `.repo-metadata.json` files

---

google/cloud/iam/admin/v1/.repo-metadata.json
google/cloud/iam/credentials/v1/.repo-metadata.json
google/cloud/iam/v1/.repo-metadata.json
google/cloud/iam/v2/.repo-metadata.json
google/cloud/iap/v1/.repo-metadata.json
google/cloud/ids/v1/.repo-metadata.json
google/cloud/iot/v1/.repo-metadata.json

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11622)

chore(i*): backfill `.repo-metadata.json` files

---

google/cloud/optimization/v1/.repo-metadata.json
google/cloud/orgpolicy/v2/.repo-metadata.json
google/cloud/osconfig/agentendpoint/v1/.repo-metadata.json
google/cloud/osconfig/v1/.repo-metadata.json
google/cloud/oslogin/v1/.repo-metadata.json

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11623)

chore(o*): backfill `.repo-metadata.json` files

---

google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc
google/cloud/spanner/samples/samples.cc

Exercise the new `DatabaseAdminClient::UpdateDatabase()` interface to set the `Database.enable_drop_protection` field.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11637)

feat(spanner): tests and samples for drop-database protection

---

docfx/doxygen2markdown.cc
docfx/doxygen2markdown_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11640)

impl(docfx): another title that needs separators

---

ci/cloudbuild/builds/publish-docs.sh

Part of the work for #11430
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11628)

ci: upload spanner docfx docs

---

ci/cloudbuild/builds/publish-docs.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11646)

ci: upload pubsub documentation

---

docfx/yaml_context.cc

See #11648
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11652)

impl(docfx): address post-merge review comments

---

generator/internal/pagination.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11662)

impl(generator): defer paginating map fields for now

---

docfx/doxygen2toc_test.cc
docfx/public_docs.cc
docfx/public_docs_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11663)

impl(docfx): skip destructors

---

ci/cloudbuild/builds/publish-docs.sh

Fixes #11430
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11664)

ci: upload all docfx document sets

---

docfx/doxygen2yaml_test.cc
docfx/node_name.cc

Add a little annotation in the function name when the function is static or virtual.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11665)

impl(docfx): annotate virtual and static functions

---

ci/cloudbuild/cache.sh
ci/kokoro/macos/download-cache.sh

Fixes #11670
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11671)

ci: increase ccache size

---

google/cloud/storage/grpc_plugin.h

Part of the work for #11428 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11679)

docs(GCS+gRPC): fix plugin example

---

ci/cloudbuild/cloudbuild.yaml

Fixes #11235
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11687)

ci: ignore errors trying to cancel other builds

---

docfx/doxygen2syntax.cc
docfx/doxygen2syntax_test.cc
docfx/doxygen2yaml_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11690)

impl(docfx): use code formatting for 'aliasof' elements

---

ci/cloudbuild/cache.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11704)

ci: increase timeout for cache download

---

docfx/doxygen2syntax.cc
docfx/doxygen2syntax_test.cc

Fixes #11681
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11707)

impl(docfx): support exception descriptions

---

google/cloud/storage/grpc_plugin.cc
google/cloud/storage/grpc_plugin_test.cc
google/cloud/storage/tests/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11712)

impl(GCS+gRPC): by default use gRPC for metadata

---

generator/BUILD.bazel
generator/CMakeLists.txt
generator/generator_test.cc
generator/integration_tests/BUILD.bazel
generator/internal/codegen_utils_test.cc
generator/internal/descriptor_utils_test.cc
generator/internal/discovery_file_test.cc
generator/internal/discovery_resource_test.cc
generator/internal/discovery_to_proto_test.cc
generator/internal/discovery_type_vertex_test.cc
generator/internal/format_class_comments_test.cc
generator/internal/format_method_comments_test.cc
generator/internal/http_option_utils_test.cc
generator/internal/longrunning_test.cc
generator/internal/pagination_test.cc
generator/internal/predicate_utils_test.cc
generator/internal/printer_test.cc
generator/internal/resolve_comment_references_test.cc
generator/internal/resolve_method_return_test.cc
generator/internal/routing_test.cc
generator/internal/scaffold_generator_test.cc
generator/internal/service_code_generator_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11713)

chore(generator): add workaround for protoc_lib defined main

---

ci/cloudbuild/builds/grpc-at-head.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11718)

ci: use stock Protobuf version with grpc-at-head

---

google/cloud/internal/unified_rest_credentials_integration_test.cc

It seems that BigQuery may need more than 3 retries.
Part of the work for #10143
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11722)

test(rest): increase retries for integration test

---

google/cloud/storage/grpc_plugin_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11732)

test(GCS+gRPC): avoid timeouts in gRPC plugin test

---

google/cloud/opentelemetry/samples/samples.cc

Part of the work for #11360 
Add some more samples for Cloud Trace integration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11743)

docs(otel): more samples

---

google/cloud/internal/pagination_range.h
google/cloud/internal/pagination_range_test.cc

Part of the work for #11742
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11750)

impl(common): `PaginationRange` for any status

---

google/cloud/storage/doc/storage-grpc.dox

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11760)

docs(storage): add GCS+gRPC release notes

---

google/cloud/storage/examples/storage_grpc_samples.cc

This is going to be used in the service documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11767)

docs(GCS+gRPC): add quickstart with DP enabled

---

ci/cloudbuild/builds/clang-7.0.sh
ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile
ci/cloudbuild/triggers/clang-7.0-ci.yaml
ci/cloudbuild/triggers/clang-7.0-pr.yaml

Part of the work for #11472
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11768)

ci: drop Ubuntu:18.04 builds

---

google/cloud/video/CMakeLists.txt
google/cloud/video/doc/main.dox
google/cloud/video/quickstart/CMakeLists.txt
google/cloud/video/quickstart/WORKSPACE.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11773)

docs(video): consistent library title

---

google/cloud/spanner/integration_tests/client_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11789)

test(spanner): integration tests for fine-grained access control

---

google/cloud/iam/doc/main.dox

Part of the work for #10157
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11801)

docs(iam): another declutter iteration

---

google/cloud/bigquery/doc/main.dox

Part of the work for #10157
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11800)

docs(bigquery): another declutter iteration

---

google/cloud/bigquery/v2/minimal/internal/job.h
google/cloud/bigquery/v2/minimal/internal/job_query_stats_test.cc
google/cloud/bigquery/v2/minimal/internal/job_stats_test.cc
google/cloud/bigquery/v2/minimal/internal/job_test.cc
google/cloud/bigquery/v2/minimal/testing/job_test_utils.cc
google/cloud/bigquery/v2/minimal/testing/job_test_utils.h

This PR adds the all the new statistical classes from previous PRs to the `Job` and `ListFormatJob` resource.
I'll do all the DebugLogging changes in separate PRs as they have tendency to bloat the PR size.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11796)

impl(bigquery): Add JobStatistics to Job and ListFormatJob

---

google/cloud/google_cloud_cpp_grpc_utils.bzl
google/cloud/google_cloud_cpp_grpc_utils.cmake
google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
google/cloud/internal/async_read_write_stream_tracing.h
google/cloud/internal/async_read_write_stream_tracing_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11812)

impl(otel): `AsyncStreamingReadWriteRpcTracing`

---

google/cloud/google_cloud_cpp_grpc_utils.bzl
google/cloud/google_cloud_cpp_grpc_utils.cmake
google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
google/cloud/internal/async_streaming_write_rpc_tracing.h
google/cloud/internal/async_streaming_write_rpc_tracing_test.cc

Fixes #10619
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11827)

impl(otel): `AsyncStreamingWriteRpcTracing`

---

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_tracing_stub.cc
generator/integration_tests/tests/golden_kitchen_sink_tracing_stub_test.cc
generator/internal/tracing_stub_generator.cc
google/cloud/bigquery/storage/v1/internal/bigquery_write_tracing_stub.cc
google/cloud/dialogflow_cx/internal/sessions_tracing_stub.cc
google/cloud/dialogflow_es/internal/participants_tracing_stub.cc
google/cloud/dialogflow_es/internal/sessions_tracing_stub.cc
google/cloud/logging/v2/internal/logging_service_v2_tracing_stub.cc
google/cloud/pubsub/internal/subscriber_tracing_stub.cc
google/cloud/pubsublite/internal/cursor_tracing_stub.cc
google/cloud/pubsublite/internal/partition_assignment_tracing_stub.cc
google/cloud/pubsublite/internal/publisher_tracing_stub.cc
google/cloud/pubsublite/internal/subscriber_tracing_stub.cc
google/cloud/speech/v1/internal/speech_tracing_stub.cc
google/cloud/speech/v2/internal/speech_tracing_stub.cc

Part of the work for #10620
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11838)

impl(otel): async streaming read write tracing in stubs

---

google/cloud/timeseriesinsights/README.md
google/cloud/timeseriesinsights/doc/main.dox
google/cloud/timeseriesinsights/quickstart/README.md
google/cloud/timeseriesinsights/v1/.repo-metadata.json

Part of the work for #11804
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11841)

fix(timeseriesinsights): correct links to docs and issue tracker

---

doc/contributor/howto-guide-adding-generated-libraries.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11846)

doc: update code generation command for new libraries

---

google/cloud/bigquery/v2/minimal/internal/job_query_stats.cc
google/cloud/bigquery/v2/minimal/internal/job_query_stats.h
google/cloud/bigquery/v2/minimal/internal/job_query_stats_test.cc

This and following 5 PRs are related to adding DebugString to the new and existing custom classes related to the `Job` resource.
This PR adds `DebugString` member function to `JobQueryStatistics` custom classes with unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11845)

impl(bigquery): Adds DebugString to JobQueryStatistics

---

doc/contributor/howto-guide-adding-generated-libraries.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11851)

docs: update how-to guide to generate libraries

---

google/cloud/essentialcontacts/v1/internal/essential_contacts_metadata_decorator.h
google/cloud/essentialcontacts/v1/internal/essential_contacts_stub_factory.cc

I merge the code without rebasing and regenerating while a separate PR changed the generator.
Part of the work for #11809
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11856)

impl(essentialcontacts): merge mishap

---

google/cloud/pubsub/samples/samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11844)

doc(pubsub): remove unnecessary documentation tags

---

google/cloud/bigquery/v2/minimal/internal/job_stats.cc
google/cloud/bigquery/v2/minimal/internal/job_stats.h
google/cloud/bigquery/v2/minimal/internal/job_stats_test.cc

This PR adds `DebugString()` member methods to `JobStatistics` classes with unit tests so they can be used in request and response logging for `Job` apis and resources.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11864)

impl(bigquery): Adds DebugString to JobStatistics

---

google/cloud/compute/.repo-metadata.json

Related to #11791.  I think we would want to automate the generation of this file, but a hand-crafted file is useful in the interim.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11865)

chore(compute): create `.repo-metadata.json` file

---

google/cloud/spanner/internal/spanner_stub_factory.cc
google/cloud/spanner/internal/spanner_stub_factory_test.cc

Part of the work for #11854 
The only remaining work is an optional refactor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11863)

impl(spanner): include tracing stub

---

google/cloud/batch/v1/.repo-metadata.json
google/cloud/domains/v1/.repo-metadata.json
google/cloud/orgpolicy/v2/.repo-metadata.json
google/cloud/sql/v1/.repo-metadata.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11870)

cleanup: public ticketing system

---

doc/contributor/howto-guide-adding-generated-libraries.md

Expanding a library is similar, but not exactly the same as adding a new library.
Offer a separate set of instructions, as a certain team member has [struggled](https://github.com/googleapis/google-cloud-cpp/pull/11882/commits) with the difference.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11884)

doc: howto expand library

---

google/cloud/spanner/client.h
google/cloud/spanner/samples/samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11905)

doc(spanner): add an example for CommitAtLeastOnce()

---

google/cloud/essentialcontacts/CMakeLists.txt

Part of Issue #11922
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11923)

fix: temp disable essentialcontacts test

---

google/cloud/bigquery/v2/minimal/internal/job_request.cc
google/cloud/bigquery/v2/minimal/internal/job_request.h
google/cloud/bigquery/v2/minimal/internal/job_request_test.cc

This PR contains the definition and unit tests for `InsertJobRequest` which will be used in `InsertJob` api for the `JobClient` rest stub.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11927)

impl(bigquery): Request object for InsertJob api

---

google/cloud/status.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11928)

docs(common): fix formatting nit

---

google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.cc
google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.h
google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy_test.cc

This PR implements the idempotency policy for InsertJob api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11934)

impl(bigquery): Idempotency policy for InsertJob

---

examples/CMakeLists.txt
examples/batch_logging.cc
google/cloud/batch/v1/samples/samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11935)

docs: an example to extract Cloud Batch logs

---

google/cloud/storagetransfer/README.md
google/cloud/storagetransfer/quickstart/quickstart.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11941)

cleanup(storagetransfer): tidy up quickstart

---

google/cloud/compute/quickstart/quickstart.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11942)

cleanup(compute): tidy up quickstart

---

google/cloud/bigquery/v2/minimal/internal/job_response.cc
google/cloud/bigquery/v2/minimal/internal/job_response.h
google/cloud/bigquery/v2/minimal/internal/job_response_test.cc

This PR implements the response object for InsertJob api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11933)

impl(bigquery): InsertJobResponse implementation with unit tests

---

ci/cloudbuild/builds/checkers.sh

Parallelize the step to update the Doxygen landing pages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11948)

ci: speed up checkers

---

google/cloud/bigquery/v2/minimal/internal/job_logging.cc
google/cloud/bigquery/v2/minimal/internal/job_logging.h
google/cloud/bigquery/v2/minimal/internal/job_metadata.cc
google/cloud/bigquery/v2/minimal/internal/job_metadata.h
google/cloud/bigquery/v2/minimal/internal/job_response_test.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_stub.h
google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc
google/cloud/bigquery/v2/minimal/testing/mock_job_rest_stub.h

This PR includes the following
1) Addition of InsertJob api to the `Job` rest stub and dependent classes e.g. (metadata, logging and mock classes)
2) Unit tests for rest stub changes
3) Unit tests for DebugString changes for the InsertJobResponse. I forgot to add this in the previous PR
Please note that this PR doesn't include the unit tests for logging and metadata changes. I was being mindful of the PR size and will add them in a followup PR.
Thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11951)

impl(bigquery): InsertJob stub changes

---

google/cloud/bigtable/doc/bigtable-main.dox
google/cloud/bigtable/doc/override-retry-policies.dox
google/cloud/bigtable/examples/client_samples.cc

Fixes #11265 Part of the work for #10157 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11955)

docs(bigtable): add page describing retry policies

---

google/cloud/bigquery/v2/minimal/internal/job_logging_test.cc
google/cloud/bigquery/v2/minimal/internal/job_metadata_test.cc

This PR adds Logging and Metadata decorator unit tests for InsertJob api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11959)

impl(bigquery): Logging and Metadata  decorator unit tests

---

google/cloud/bigquery/v2/minimal/internal/job_connection.cc
google/cloud/bigquery/v2/minimal/internal/job_connection.h
google/cloud/bigquery/v2/minimal/internal/job_connection_test.cc
google/cloud/bigquery/v2/minimal/internal/job_logging_test.cc
google/cloud/bigquery/v2/minimal/internal/job_metadata_test.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.h
google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc
google/cloud/bigquery/v2/minimal/mocks/mock_job_connection.h
google/cloud/bigquery/v2/minimal/testing/job_test_utils.cc
google/cloud/bigquery/v2/minimal/testing/job_test_utils.h

This PR includes the following:
1) Connection classes changes for InsertJob api with unit tests
2) Minor refactor of test functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11960)

impl(bigquery): Connection classes for InsertJob

---

google/cloud/pubsub/doc/override-retry-policies.dox
google/cloud/pubsub/doc/pubsub-main.dox

Fixes #11267 Part of the work for #10157 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11957)

docs(pubsub): add page describing retry policies

---

google/cloud/bigquery/v2/minimal/internal/job_client.cc
google/cloud/bigquery/v2/minimal/internal/job_client.h
google/cloud/bigquery/v2/minimal/internal/job_client_test.cc

This PR adds the InsertJob api to JobClient class and corresponding unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11961)

impl(bigquery): Client class for InsertJob

---

google/cloud/bigquery/v2/minimal/internal/job_request.cc
google/cloud/bigquery/v2/minimal/internal/job_request.h
google/cloud/bigquery/v2/minimal/internal/job_request_test.cc

This PR defines the CancelJobRequest object for CancelJob api, with unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11972)

impl(bigquery): Request object for CancelJob api

---

google/cloud/bigquery/v2/minimal/internal/job_response.cc
google/cloud/bigquery/v2/minimal/internal/job_response.h
google/cloud/bigquery/v2/minimal/internal/job_response_test.cc

This PR defines the CancelJobResponse object for CancelJob api, with unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11971)

impl(bigquery): Response object for CancelJob api

---

ci/cloudbuild/cloudbuild.yaml

This fixes #11235 for realsies.  Honest. Proper fixed this time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11973)

ci: ignore errors in GCB cleanup steps

---

google/cloud/videointelligence/CMakeLists.txt

Fixes #11205 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11967)

test(videointelligence): restore quickstart

---

google/cloud/bigquery/v2/minimal/internal/job_connection.cc
google/cloud/bigquery/v2/minimal/internal/job_connection.h
google/cloud/bigquery/v2/minimal/internal/job_connection_test.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.h
google/cloud/bigquery/v2/minimal/mocks/mock_job_connection.h

This PR contains the `Connection` interface and implementation changes for CancelJob api, with unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11984)

impl(bigquery): CancelJob connection classes

---

google/cloud/bigquery/v2/minimal/internal/job_client.cc
google/cloud/bigquery/v2/minimal/internal/job_client.h
google/cloud/bigquery/v2/minimal/internal/job_client_test.cc

This PR includes `Client` interface and implementation changes for CancelJob api with unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11986)

impl(bigquery): CancelJob Client classes

---

ci/cloudbuild/builds/demo-install.sh
ci/cloudbuild/builds/gcc-7.3.sh
ci/cloudbuild/builds/lib/cmake.sh
ci/cloudbuild/builds/lib/quickstart.sh
ci/cloudbuild/builds/lib/vcpkg.sh
ci/cloudbuild/cloudbuild.yaml
ci/cloudbuild/dockerfiles/centos-7.Dockerfile
ci/cloudbuild/dockerfiles/demo-alpine-stable.Dockerfile
ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile
ci/cloudbuild/dockerfiles/fedora-37-cmake.Dockerfile
ci/cloudbuild/dockerfiles/fedora-37-cxx14.Dockerfile
ci/cloudbuild/dockerfiles/fedora-37-cxx20.Dockerfile
ci/cloudbuild/dockerfiles/fedora-m32.Dockerfile
ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile
ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile
ci/cloudbuild/dockerfiles/ubuntu-focal.Dockerfile
doc/packaging.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11978)

ci: use remote cache for CMake

---

google/cloud/batch/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11994)

ci(batch): give samples more time

---

ci/cloudbuild/builds/lib/integration.sh

This is part of the work for #10413
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11992)

ci: retry integration tests on failure

---

ci/cloudbuild/builds/clang-7.0.sh
ci/cloudbuild/builds/gcc-7.3.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12025)

ci(compute): add compute to old compiler ci builds

---

generator/integration_tests/benchmarks/client_benchmark.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12027)

cleanup(generator): fix compiler warnings

---

google/cloud/internal/retry_policy.h
google/cloud/pubsub/internal/subscriber_connection_impl.cc
google/cloud/pubsub/internal/subscriber_connection_impl_test.cc

Fixes issue #11025
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11983)

fix: pubsub blocking pull integration test (#11025)

---

generator/integration_tests/golden/v1/golden_kitchen_sink_connection.h
generator/integration_tests/golden/v1/golden_rest_only_connection.h
generator/integration_tests/golden/v1/golden_thing_admin_connection.h
generator/internal/connection_generator.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12035)

cleanup(generator): nits in output format

---

google/cloud/storage/retry_policy.h

Part of the work for #9434
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12031)

docs(storage): document `RetryPolicy` interface

---

google/cloud/bigtable/internal/default_row_reader_test.cc

Three cleanups at once:
- match the exact contents of the row keys, instead of matching on the count
- convert the range to a `std::vector<StatusOr<Row>>` and match the container (unless we are testing manual iteration)
- fix an incorrect comment
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12028)

cleanup(bigtable): more precise expectations in ReadRows tests

---

google/cloud/bigquery/bigquery_rest.cmake
google/cloud/bigquery/bigquery_rest_testing.bzl
google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc
google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h
google/cloud/bigquery/v2/minimal/internal/job_request.cc
google/cloud/bigquery/v2/minimal/internal/job_request.h
google/cloud/bigquery/v2/minimal/internal/job_request_test.cc
google/cloud/bigquery/v2/minimal/testing/common_v2_test_utils.cc
google/cloud/bigquery/v2/minimal/testing/common_v2_test_utils.h
google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.cc
google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.h
google/cloud/bigquery/v2/minimal/testing/job_test_utils.cc

This PR implements the [Request](http://google3/google/cloud/bigquery/v2/job.proto;l=727;rcl=544196886) object for the `job` [Query api,](http://google3/google/cloud/bigquery/v2/job.proto;l=176;rcl=544196886) with unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12018)

impl(bigquery): Request object for Query api

---

google/cloud/accessapproval/doc/main.dox
google/cloud/assuredworkloads/doc/main.dox
google/cloud/billing/doc/main.dox
google/cloud/kms/doc/main.dox
google/cloud/logging/doc/main.dox
google/cloud/scheduler/doc/main.dox
google/cloud/secretmanager/doc/main.dox
google/cloud/tasks/doc/main.dox
google/cloud/webrisk/doc/main.dox
google/cloud/websecurityscanner/doc/main.dox
google/cloud/workflows/doc/main.dox

This was introduced during a declutter pass
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12046)

cleanup: remove extra blank line

---

google/cloud/opentelemetry/internal/recordable.cc
google/cloud/opentelemetry/internal/recordable_test.cc

Part of the work for #11775 
- Handle `OwnedAttributeValue`s in the `AttributeVisitor`.
- Copy attributes from the resource into the spans
Note that the `AttributeVisitor` used to make a drop decision based on the type of the attribute variant. Now that it doesn't we can make the keep/drop decision outside of the `AttributeVisitor`. I intend to refactor this in a follow up PR.
---
There might have been a way to consolidate the conversion of `span<T const>` and `vector<T>` with something like:
```
template <template <typename> class Container, typename T>
void ToString(Container<T> values);
template <template <typename> class Container>
void ToString(Container<bool> values);
template <template <typename> class Container>
void ToString(Container<opentelemetry::nostd::string_view> values); …
```

impl(otel): trace exporter includes resource attributes

---

google/cloud/opentelemetry/internal/recordable.cc

Cleanup related to #11775 
Make the keep/drop decision outside of the `AttributeVisitor`.
There is some weirdness in that we expose 
```cc
void AddAttribute(
google::devtools::cloudtrace::v2::Span::Attributes& attributes,
opentelemetry::nostd::string_view key,
opentelemetry::common::AttributeValue const& value, std::size_t limit);
```
... in the header (for better test coverage). We probably could expose
```cc
template <typename AttributeVariant>
void AddAttribute(
google::devtools::cloudtrace::v2::Span::Attributes& attributes,
opentelemetry::nostd::string_view key,
AttributeVariant const& value, std::size_t limit);
```
... instead. We would not need the `AddAttributeImpl(...)`. But I do not like how that forces me to move a lot of the implementation out of the source file and into the …

refactor(otel): simplify `AttributeVisitor`

---

ci/cloudbuild/builds/clang-tidy-full.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12055)

ci: add daily clang-tidy full build

---

google/cloud/bigquery/v2/minimal/internal/job_request.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12059)

test(bigquery): deflake job_request_test

---

google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc
google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h
google/cloud/bigquery/v2/minimal/internal/job_response.cc
google/cloud/bigquery/v2/minimal/internal/job_response.h
google/cloud/bigquery/v2/minimal/internal/job_response_test.cc
google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.cc
google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.h

This PR implements the [Response](http://google3/google/cloud/bigquery/v2/job.proto;l=930;rcl=544196886) object for [`Query` api](http://google3/google/cloud/bigquery/v2/job.proto;l=176;rcl=544196886), with unit tests and logging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12050)

impl(bigquery): Response object for Query api

---

google/cloud/bigquery/v2/minimal/internal/job_logging.cc
google/cloud/bigquery/v2/minimal/internal/job_logging.h
google/cloud/bigquery/v2/minimal/internal/job_logging_test.cc
google/cloud/bigquery/v2/minimal/internal/job_metadata.cc
google/cloud/bigquery/v2/minimal/internal/job_metadata.h
google/cloud/bigquery/v2/minimal/internal/job_metadata_test.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_stub.h
google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc
google/cloud/bigquery/v2/minimal/testing/mock_job_rest_stub.h

This PR implements the Rest stub, logging and metadata decorators for Query() api with unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12067)

impl(bigquery): Stub and Decorator for Query API

---

google/cloud/bigquery/v2/minimal/internal/job_connection.cc
google/cloud/bigquery/v2/minimal/internal/job_connection.h
google/cloud/bigquery/v2/minimal/internal/job_connection_test.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.h
google/cloud/bigquery/v2/minimal/mocks/mock_job_connection.h

Implements Connection classes for Query api, with unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12076)

impl(bigquery): Connection classes for Query api

---

generator/internal/discovery_type_vertex.cc
generator/internal/discovery_type_vertex.h
generator/internal/discovery_type_vertex_test.cc

part of the work for #11095
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12071)

impl(generator): interrogate existing protos for field number info

---

generator/BUILD.bazel
generator/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12081)

cleanup(generate): only compile on Linux

---

release/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12080)

docs(release): updating packages post release

---

google/cloud/bigquery/v2/minimal/internal/job_client.cc
google/cloud/bigquery/v2/minimal/internal/job_client.h
google/cloud/bigquery/v2/minimal/internal/job_client_test.cc

This PR implements the `Client` classes for the Query api, with unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12085)

impl(bigquery): Client classes for Query api

---

BUILD.bazel

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12091)

feat: public Bazel target `google_cloud_cpp_bigquery_rest`

---

google/cloud/compute/integration_tests/compute_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12093)

cleanup(compute): add missing #include

---

google/cloud/storage/benchmarks/benchmark_utils.cc
google/cloud/storage/benchmarks/throughput_options.cc
google/cloud/storage/benchmarks/throughput_options_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12101)

test(storage): fix benchmark command-line parsing

---

google/cloud/compute/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12104)

fix(compute): build problems with MSVC

---

google/cloud/google_cloud_cpp_rest_internal.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12103)

fix(common): add missing library on Windows

---

google/cloud/bigquery/v2/minimal/internal/job_request.cc
google/cloud/bigquery/v2/minimal/internal/job_request.h
google/cloud/bigquery/v2/minimal/internal/job_request_test.cc
google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.cc
google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.h

Implements the [Request](https://source.corp.google.com/piper///depot/google3/google/cloud/bigquery/v2/job.proto;l=566;rcl=544196886) object for [GetQueryResults](http://google3/google/cloud/bigquery/v2/job.proto;l=156;rcl=544196886) api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12106)

impl(bigquery): Request object for GetQueryResults api

---

google/cloud/opentelemetry/configure_basic_tracing.cc
google/cloud/opentelemetry/resource_detector.cc

Fixes #11775 
No tests because the interface is opaque.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12052)

impl(otel): gcp resource detection in basic tracing

---

ci/gha/builds/macos-bazel.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12131)

ci(gha): export io::run before using in subshell

---

ci/cloudbuild/builds/publish-docs.sh

We are going to redirect customers to
cloud.google.com/cpp/docs/reference/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12139)

ci: stop staging googleapis.dev documents

---

google/cloud/internal/rest_stub_helpers.cc

part of the work for for #12112
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12145)

fix(rest): preserve proto field snake case naming style in json

---

ci/gha/builds/windows-cmake.sh

Part of the work for #12141
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12146)

ci(gha): deflake Windows+CMake builds

---

.github/trusted-contribution.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12156)

ci: no need for `kokoro:force-run` label

---

.typos.toml
ci/cloudbuild/builds/checkers.sh
ci/cloudbuild/dockerfiles/checkers.Dockerfile
doc/contributor/howto-guide-setup-development-workstation.md
google/cloud/bigquery/v2/minimal/internal/job_stats.h
google/cloud/bigquery/v2/minimal/internal/table_schema.cc
google/cloud/bigquery/v2/minimal/internal/table_view.cc
google/cloud/bigquery/v2/minimal/internal/table_view.h
google/cloud/internal/rest_client.h
google/cloud/storage/parallel_uploads_test.cc
google/cloud/storage/tests/conformance_tests.proto

Fixes #12165
Upgrade `typos-cli`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12166)

ci: upgrade typos

---

google/cloud/retail/v2/internal/control_logging_decorator.cc
google/cloud/retail/v2/internal/control_logging_decorator.h
google/cloud/retail/v2/internal/model_logging_decorator.cc
google/cloud/retail/v2/internal/model_logging_decorator.h
google/cloud/retail/v2/internal/serving_config_logging_decorator.cc
google/cloud/retail/v2/internal/serving_config_logging_decorator.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12175)

cleanup(retail): update #12170 after #12172

---

google/cloud/dataproc/CMakeLists.txt

Part of the work for #12163
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12174)

ci: run `dataproc` quickstart

---

ci/etc/integration-tests-config.ps1
ci/etc/integration-tests-config.sh
google/cloud/policytroubleshooter/CMakeLists.txt

Part of the work for #12163
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12177)

ci: run `policytroubleshooter` quickstart

---

.github/workflows/test-runner.yml
.github/workflows/windows-cmake.yml
ci/gha/builds/windows-cmake.sh

I accidentally dropped this one on the road from Kokoro to GHA.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12182)

ci(gha): add Windows + MSVC + x86 build

---

.github/workflows/windows-bazel.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12186)

ci(gha): fix typo

---

google/cloud/video/livestream/v1/internal/livestream_metadata_decorator.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12206)

chore: resolve generator vs. libraries PR conflict

---

google/cloud/bigquery/v2/minimal/internal/dataset.cc

This PR applies the SafeGetTo() from [PR-12199](https://github.com/googleapis/google-cloud-cpp/pull/12199) to `Dataset` resource's response parsing i.e `from_json` methods.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12211)

impl(bigquery): Applies SafeGetTo function to Dataset json parsing

---

.github/renovate.json
.github/workflows/macos-bazel.yml
.github/workflows/windows-bazel.yml
ci/gha/builds/lib/bazel.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12205)

ci(gha): use renovate-bot for Bazel updates

---

.github/renovate.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12221)

chore: disable pip updates

---

generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_stub.cc
generator/internal/descriptor_utils.cc
generator/internal/descriptor_utils_test.cc
generator/internal/http_option_utils.cc
generator/internal/http_option_utils.h
generator/internal/http_option_utils_test.cc
google/cloud/spanner/admin/internal/database_admin_rest_stub.cc
google/cloud/sql/integration_tests/sql_integration_test.cc
google/cloud/sql/v1/internal/sql_backup_runs_rest_stub.cc
google/cloud/sql/v1/internal/sql_databases_rest_stub.cc
google/cloud/sql/v1/internal/sql_instances_rest_stub.cc
google/cloud/sql/v1/internal/sql_ssl_certs_rest_stub.cc
google/cloud/sql/v1/internal/sql_users_rest_stub.cc

fixes #12112
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12207)

fix(sql): use correct message field as JSON request body

---

generator/internal/format_method_comments.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12224)

cleanup(generator): remove multiline comment

---

cmake/GoogleCloudCppFeatures.cmake

Fixes #12210
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12220)

cleanup: bigquery_rest without grpc_utils for cmake

---

generator/internal/discovery_type_vertex.cc
generator/internal/discovery_type_vertex.h
generator/internal/discovery_type_vertex_test.cc

part of the work for #11095 
Also made test results more readable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12231)

impl(generator): add message detection to DetermineTypeAndSynthesis

---

google/cloud/opentelemetry/BUILD.bazel
google/cloud/opentelemetry/internal/recordable.cc
google/cloud/opentelemetry/internal/recordable_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12229)

fix(otel): remove the codes dependency on `rpc::Code`

---

release/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12239)

cleanup: release doc nits

---

google/cloud/spanner/options.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12238)

doc(spanner): Improve documentation for ActionOnExhaustion

---

external/googleapis/update_libraries.sh
google/cloud/sql/BUILD.bazel
google/cloud/sql/CMakeLists.txt

#11914 for `sql`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12240)

cleanup(sql): no grpc

---

generator/internal/discovery_type_vertex.cc
generator/internal/discovery_type_vertex.h
generator/internal/discovery_type_vertex_test.cc

part of the work for #11095
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12235)

impl(generator): use previous generation protos to determine field numbers

---

.github/renovate.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12242)

chore: automate vcpkg updates

---

.github/renovate.json

I do apologize, this is ridiculous.
Part of the work for #8297
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12245)

chore: automate vcpkg updates, take 3

---

google/cloud/bigquery/v2/minimal/internal/job.cc
google/cloud/bigquery/v2/minimal/internal/job_configuration.cc
google/cloud/bigquery/v2/minimal/internal/job_configuration_query.cc
google/cloud/bigquery/v2/minimal/internal/job_query_stats.cc
google/cloud/bigquery/v2/minimal/internal/job_request.cc
google/cloud/bigquery/v2/minimal/internal/job_response.cc
google/cloud/bigquery/v2/minimal/internal/job_stats.cc
google/cloud/bigquery/v2/minimal/internal/json_utils.h

This PR applies the SafeGetTo() from [PR-12199](https://github.com/googleapis/google-cloud-cpp/pull/12199) to `Job` resource response parsing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12209)

impl(bigquery): Applies SafeGetTo function Job response parsing

---

.github/renovate.json

Arguably more readable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12246)

chore: automate vcpkg updates, take 4

---

generator/internal/discovery_type_vertex.cc
generator/internal/discovery_type_vertex.h

fixes #12234
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12243)

impl(generator): refactor DiscoveryTypeVertex::FormatProperties

---

google/cloud/bigquery/v2/minimal/internal/json_utils.h
google/cloud/bigquery/v2/minimal/internal/table.cc
google/cloud/bigquery/v2/minimal/internal/table_constraints.cc
google/cloud/bigquery/v2/minimal/internal/table_partition.cc
google/cloud/bigquery/v2/minimal/internal/table_schema.cc
google/cloud/bigquery/v2/minimal/internal/table_view.cc

This PR applies the SafeGetTo() from https://github.com/googleapis/google-cloud-cpp/pull/12199 to `Table` api's response parsing methods.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12248)

imp(bigquery): Applies SafeGetTo method to Table api response parsing

---

doc/contributor/howto-guide-adding-generated-libraries.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12257)

cleanup: add links to generate lib docs

---

generator/integration_tests/tests/mock_golden_kitchen_sink_stub.h
google/cloud/bigtable/internal/async_streaming_read_test.cc
google/cloud/bigtable/testing/mock_bigtable_stub.h
google/cloud/internal/async_streaming_read_rpc_auth_test.cc
google/cloud/internal/async_streaming_read_rpc_logging_test.cc
google/cloud/internal/async_streaming_read_rpc_tracing_test.cc
google/cloud/storage/testing/mock_storage_stub.h
google/cloud/testing_util/CMakeLists.txt
google/cloud/testing_util/google_cloud_cpp_testing.bzl
google/cloud/testing_util/mock_async_streaming_read_rpc.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12275)

refactor: de-dup `MockAsyncStreamingReadRpc`

---

google/cloud/bigquery/v2/minimal/internal/job_connection.cc
google/cloud/bigquery/v2/minimal/internal/job_connection.h
google/cloud/bigquery/v2/minimal/internal/job_connection_test.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.h
google/cloud/bigquery/v2/minimal/mocks/mock_job_connection.h

This PR implements the `Connection` classes for GetQueryResults api with unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12279)

impl(bigquery): GetQueryResults Connection classes

---

google/cloud/storage/internal/curl_client.h
google/cloud/storage/internal/grpc/client.h
google/cloud/storage/internal/rest_client.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12290)

cleanup(storage): unused `enable_shared_from_this`

---

google/cloud/google_cloud_cpp_grpc_utils.bzl
google/cloud/google_cloud_cpp_grpc_utils.cmake
google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
google/cloud/internal/async_streaming_read_rpc_timeout.h
google/cloud/internal/async_streaming_read_rpc_timeout_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12281)

impl(common): `AsyncStreamingReadRpc` timeout decorator

---

generator/integration_tests/tests/mock_golden_kitchen_sink_stub.h
google/cloud/internal/async_streaming_write_rpc_logging_test.cc
google/cloud/internal/async_streaming_write_rpc_tracing_test.cc
google/cloud/testing_util/CMakeLists.txt
google/cloud/testing_util/google_cloud_cpp_testing.bzl
google/cloud/testing_util/mock_async_streaming_write_rpc.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12296)

refactor(common): de-dup `MockAsyncStreamingWriteRpc`

---

google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc
google/cloud/bigquery/v2/minimal/internal/job_configuration.cc
google/cloud/bigquery/v2/minimal/internal/job_configuration_query_test.cc
google/cloud/bigquery/v2/minimal/internal/job_configuration_test.cc
google/cloud/bigquery/v2/minimal/internal/job_request_test.cc
google/cloud/bigquery/v2/minimal/internal/job_response_test.cc
google/cloud/bigquery/v2/minimal/internal/job_test.cc

Modified `stament_timeout_ms` and `job_timeout_ms` in DebugString methods to `statement_timeout` and `job_timeout` based on the following feedback:
https://reviewable.io/reviews/googleapis/google-cloud-cpp/12292#gh-1282027080
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12302)

impl(bigquery): Updated statement_timeout_ms and job_timeout_ms field names

---

google/cloud/storage/client.cc
google/cloud/storage/client_test.cc
google/cloud/storage/grpc_plugin_test.cc
google/cloud/storage/internal/object_write_streambuf_test.cc
google/cloud/storage/internal/retry_client.cc
google/cloud/storage/internal/retry_client.h
google/cloud/storage/internal/retry_client_test.cc
google/cloud/storage/internal/retry_object_read_source_test.cc

Part of the changes for #12294
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12308)

impl(storage): use `GenericStub` in `RetryClient`

---

google/cloud/storage/client.cc
google/cloud/storage/client_test.cc
google/cloud/storage/internal/logging_client.cc
google/cloud/storage/internal/logging_client.h
google/cloud/storage/internal/logging_client_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12318)

impl(storage): `LoggingClient` is a `GenericStub`

---

ci/cloudbuild/builds/check-api.sh

In #11719, we added a way to only generate ABI dumps for a subset of the libraries. But we still built all of the GA libraries in `google-cloud-cpp`, first.
This PR makes it so that we only build the libraries we need.
---
Reminder that `GOOGLE_CLOUD_CPP_CHECK_API` is used (for developer convenience) when we add a new library or expand an existing library.
Given that our operator cycles are spaced out by a month, and our releases happen monthly, we often have a cold cache for this local build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12309)

ci: faster ABI dump for new libraries

---

google/cloud/storage/internal/retry_client.cc
google/cloud/storage/internal/retry_client_bucket_acl_test.cc
google/cloud/storage/internal/retry_client_bucket_test.cc
google/cloud/storage/internal/retry_client_default_object_acl_test.cc
google/cloud/storage/internal/retry_client_notifications_test.cc
google/cloud/storage/internal/retry_client_object_acl_test.cc
google/cloud/storage/internal/retry_client_object_copy_test.cc
google/cloud/storage/internal/retry_client_object_test.cc
google/cloud/storage/internal/retry_client_service_account_test.cc
google/cloud/storage/internal/retry_client_sign_blob_test.cc
google/cloud/storage/testing/retry_tests.cc
google/cloud/storage/testing/retry_tests.h

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12331)

impl(storage): `RestContext` needs current options

---

ci/cloudbuild/builds/generate-libraries.sh

part of the work for #11190 
As the generator dynamically creates the internal proto files for compute, there exists the case where we end up with fewer proto files than the previous generation. These unnecessary proto files need to be removed before we generate C++ code from the current generation of proto files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12333)

impl(compute): remove obsolete internal compute protos

---

google/cloud/storage/internal/grpc/client_failures_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12335)

test(storage): simplify gRPC client failures test

---

google/cloud/storage/client.cc
google/cloud/storage/client.h

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12336)

impl(storage): initialize from `GenericStub`

---

google/cloud/storage/grpc_plugin.cc
google/cloud/storage/grpc_plugin_test.cc
google/cloud/storage/internal/hybrid_client.cc
google/cloud/storage/internal/hybrid_client.h

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12337)

impl(storage): `HybridClient` is a `GenericStub`

---

google/cloud/storage/client.cc
google/cloud/storage/client_test.cc
google/cloud/storage/grpc_plugin_test.cc
google/cloud/storage/internal/hybrid_client.cc
google/cloud/storage/internal/hybrid_client.h
google/cloud/storage/internal/rest/client.cc
google/cloud/storage/internal/rest/client.h
google/cloud/storage/internal/rest/client_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12339)

impl(storage): `RestClient` is a `GenericStub`

---

CHANGELOG.md
README.md
ci/cloudbuild/builds/bazel-oldest.sh
google/cloud/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12353)

ci: minimum tested Bazel is 6.0.0

---

google/cloud/internal/opentelemetry.cc
google/cloud/internal/opentelemetry.h
google/cloud/internal/opentelemetry_test.cc
google/cloud/internal/rest_retry_loop.h
google/cloud/internal/rest_retry_loop_test.cc
google/cloud/internal/retry_loop.h
google/cloud/storage/internal/retry_client.cc
google/cloud/testing_util/opentelemetry_matchers.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12360)

cleanup(common): prefer explicit `Options`

---

google/cloud/internal/rest_retry_loop.h
google/cloud/internal/rest_retry_loop_test.cc
google/cloud/storage/internal/retry_client.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12364)

impl(common): explicit options for `RestRetryLoop`

---

google/cloud/internal/retry_loop.h
google/cloud/internal/retry_loop_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12366)

impl(common): explicit options for `RetryLoop`

---

google/cloud/storage/examples/storage_grpc_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12367)

docs(GCS+gRPC): sample showing transport detection

---

google/cloud/internal/debug_string_status_test.cc
google/cloud/internal/log_wrapper_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12390)

refactor(common): move test to the right file

---

google/cloud/internal/log_wrapper_test.cc

Add tests for the `std::unique_ptr<>` case, and refactor the other tests to be parametric on the argument and return types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12392)

test(common): better coverage in LogWrapper tests

---

google/cloud/internal/log_wrapper.h

Part of the work for #12369
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12395)

refactor(common): remove duplicate `LogWrapper` overloads

---

ci/cloudbuild/builds/noex.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12397)

ci: noex all the things

---

google/cloud/internal/grpc_impersonate_service_account_integration_test.cc
google/cloud/internal/log_wrapper.h
google/cloud/internal/log_wrapper_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12398)

impl(common): `LogWrapper` with explicit `Options`

---

google/cloud/internal/rest_carrier.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12404)

cleanup(otel): fix wording in #12399

---

google/cloud/internal/async_rest_retry_loop.h
google/cloud/internal/async_rest_retry_loop_test.cc
google/cloud/internal/async_retry_loop.h
google/cloud/internal/async_retry_loop_test.cc
google/cloud/internal/call_context.h
google/cloud/internal/call_context_test.cc
google/cloud/options.cc
google/cloud/options.h

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12410)

impl(common): use immutable options

---

google/cloud/pubsub/subscription_admin_connection.cc
google/cloud/pubsub/subscription_admin_connection_test.cc
google/cloud/pubsub/topic_admin_connection.cc
google/cloud/pubsub/topic_admin_connection_test.cc

Part of the work for #12359 and #9168
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12419)

cleanup(pubsub): explicit options for policy helpers

---

google/cloud/bigtable/internal/data_connection_impl.cc

Part of the work for #12359 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12420)

cleanup(bigtable): explicit options for policy helpers

---

google/cloud/bigquery/v2/minimal/internal/dataset_connection_test.cc
google/cloud/bigquery/v2/minimal/internal/dataset_rest_connection_impl.cc
google/cloud/bigquery/v2/minimal/internal/dataset_rest_connection_impl.h
google/cloud/bigquery/v2/minimal/internal/job_connection_test.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.h
google/cloud/bigquery/v2/minimal/internal/project_connection_test.cc
google/cloud/bigquery/v2/minimal/internal/project_rest_connection_impl.cc
google/cloud/bigquery/v2/minimal/internal/project_rest_connection_impl.h
google/cloud/bigquery/v2/minimal/internal/table_connection_test.cc
google/cloud/bigquery/v2/minimal/internal/table_rest_connection_impl.cc
google/cloud/bigquery/v2/minimal/internal/table_rest_connection_impl.h

Part of the work for #12359 and #9168
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12423)

cleanup(bigquery): explicit options in policy helpers

---

google/cloud/storage/internal/async/connection_impl.cc

Part of the work for #12359 and #9168
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12421)

cleanup(storage): explicit options in policy helpers

---

google/cloud/internal/grpc_opentelemetry.cc

Fixes #12400
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12427)

cleanup(otel): parity between the gRPC and REST carriers

---

cmake/CompileProtos.cmake
external/googleapis/CMakeLists.txt
google/cloud/monitoring/CMakeLists.txt
google/cloud/speech/CMakeLists.txt
google/cloud/texttospeech/CMakeLists.txt
google/cloud/trace/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12434)

cleanup(cmake): use helper to find protobuf

---

external/googleapis/CMakeLists.txt
google/cloud/spanner/CMakeLists.txt

Part of the work for #8022
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12472)

fix(cmake)!: only compile protos if asked - spanner

---

external/googleapis/CMakeLists.txt
google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsublite/CMakeLists.txt

Part of the work for #8022
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12475)

fix(cmake)!: only compile protos if asked - pubsub

---

google/cloud/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12495)

cleanup: doxygen doesnt need bigtable_protos

---

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_metadata_decorator.cc
generator/integration_tests/tests/golden_kitchen_sink_rest_metadata_decorator_test.cc
generator/internal/metadata_decorator_rest_generator.cc

Part of Issue #12232
[Splitting work into a separate PR from 12493
](https://github.com/googleapis/google-cloud-cpp/pull/12493#issuecomment-1698166373)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12500)

fix: add url encoding to metadata rest decorator

---

external/googleapis/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12504)

cmake: remove duplicate iam_v2_policy proto libs

---

google/cloud/workflows/quickstart/quickstart.cc

Per b/296916003
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12509)

docs: Add region tags

---

google/cloud/storage/internal/async/connection.h
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl.h
google/cloud/storage/internal/async/connection_impl_test.cc

Part of the work for #9131
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12515)

impl(GCS+gRPC): add `AsyncConnection::InsertObject()`

---

google/cloud/storage/async_client.h
google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/examples/storage_async_samples.cc
google/cloud/storage/examples/storage_examples.bzl
google/cloud/storage/tests/async_client_integration_test.cc

Include an integration test and some examples.
Fixes #9131
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12519)

impl(GCS+gRPC): `AsyncClient::InsertObject()`

---

google/cloud/storage/examples/storage_async_samples.cc

Part of the changes for #9131
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12520)

impl(GCS+gRPC): fix usage message in samples

---

google/cloud/storage/examples/storage_async_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12522)

fix(GCS+gRPC): conflict with Win32 global function

---

google/cloud/discoveryengine/v1/internal/conversational_search_metadata_decorator.cc
google/cloud/discoveryengine/v1/internal/conversational_search_metadata_decorator.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12546)

fix(discoveryengine): update generated files

---

google/cloud/discoveryengine/v1/internal/conversational_search_metadata_decorator.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12549)

fix(discoveryengine): regenerate with latest generator

---

google/cloud/storage/async_client.h
google/cloud/storage/async_object_requests.h
google/cloud/storage/examples/storage_async_samples.cc
google/cloud/storage/internal/async/connection.h
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl.h
google/cloud/storage/tests/async_client_integration_test.cc

Part of the work for #12521
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12538)

cleanup(GCS+gRPC): public `ComposeObjectRequest`

---

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc

Part of the work for #12553
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12555)

cleanup(pubsub): prepare for GCC 13

---

google/cloud/internal/oauth2_external_account_credentials.cc
google/cloud/internal/openssl_util.h

Part of the work for #12553
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12554)

cleanup(common): prepare for GCC 13

---

google/cloud/bigtable/internal/legacy_async_row_sampler.cc

Part of the work for #12553 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12556)

cleanup(bigtable): prepare for GCC 13

---

ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
ci/generate-markdown/generate-packaging.sh
doc/packaging.md

Fixes #12553
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12557)

ci: upgrade demo-fedora build to Fedora:38

---

.github/renovate.json
ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
ci/cloudbuild/dockerfiles/fedora-37-cmake.Dockerfile
ci/cloudbuild/dockerfiles/fedora-37-cxx14.Dockerfile
ci/cloudbuild/dockerfiles/fedora-37-cxx20.Dockerfile
ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile
doc/packaging.md

The latest version if 1.19.1, but I held back to test the renovate bot configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12565)

chore(deps): update c-ares to 1.18.1

---

ci/cloudbuild/dockerfiles/centos-7.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
doc/packaging.md

I missed a few places in my first PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12567)

chore(deps): upgrade c-ares to 1.18.1 / take 2

---

.github/renovate.json
ci/cloudbuild/dockerfiles/centos-7.Dockerfile
ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
ci/cloudbuild/dockerfiles/fedora-37-cmake.Dockerfile
ci/cloudbuild/dockerfiles/fedora-37-cxx14.Dockerfile
ci/cloudbuild/dockerfiles/fedora-37-cxx20.Dockerfile
ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile
doc/packaging.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12569)

ci: revert changes to manually install c-ares

---

google/cloud/config/v1/config_client.h
google/cloud/netapp/v1/net_app_client.h

#12516 got merged without the corresponding the the (new) `netapp` and `config` libraries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12589)

chore: update generated files post merge

---

google/cloud/storage/async_client.h
google/cloud/storage/internal/async/connection.h
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl.h
google/cloud/storage/tests/async_client_integration_test.cc

Part of the work for #12521
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12591)

cleanup(GCS+gRPC): remove async StartResumableUpload

---

google/cloud/storage/internal/policy_document_request.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12596)

cleanup(storage): fix typo

---

google/cloud/storage/async_client.h
google/cloud/storage/async_object_requests.h
google/cloud/storage/internal/async/connection.h
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12604)

cleanup(GCS+gRPC): add public ReadObjectRequest

---

google/cloud/storage/async_object_requests.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12610)

cleanup(GCS+gRPC): fix typo

---

.github/workflows/test-runner.yml

Part of the work for #12593
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12607)

ci: run full GHA builds daily

---

release/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12606)

docs: update notes to update conan packages

---

.github/workflows/test-runner.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12613)

ci(gha): full build on schedule

---

google/cloud/storage/internal/async/connection_impl.cc

I prefer if the functions in the `.cc` file are in the same order as they are declared in the `.h` file. Easier to find things this way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12616)

cleanup(GCS+gRPC): reorder functions in `.cc` file

---

google/cloud/pubsub/internal/publisher_tracing_connection.cc
google/cloud/pubsub/internal/publisher_tracing_connection.h
google/cloud/pubsub/internal/publisher_tracing_connection_test.cc

Part of #[12525](https://github.com/googleapis/google-cloud-cpp/issues/12525)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12617)

impl(pubsub): add start and end span for publisher tracing connection

---

google/cloud/bigquery/v2/minimal/benchmarks/BUILD.bazel
google/cloud/bigquery/v2/minimal/benchmarks/CMakeLists.txt
google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc
google/cloud/bigquery/v2/minimal/benchmarks/benchmark.h
google/cloud/bigquery/v2/minimal/benchmarks/benchmark_test.cc
google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config.cc
google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config.h
google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config_test.cc
google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc
google/cloud/bigquery/v2/minimal/benchmarks/experimental_bigquery_rest_client_benchmark_programs.bzl
google/cloud/bigquery/v2/minimal/benchmarks/experimental_bigquery_rest_client_benchmark_unit_tests.bzl
google/cloud/bigquery/v2/minimal/benchmarks/experimental_bigquery_rest_client_benchmarks.bzl
google/cloud/bigquery/v2/minimal/benchmarks/job_benchmark_programs.cc
google/cloud/bigquery/v2/minimal/benchmarks/project_benchmark_programs.cc
google/cloud/bigquery/v2/minimal/benchmarks/table_benchmark_programs.cc

This PR includes the following changes for performance benchmark tests for v1/minimal apis
1) Additional parameter configs for each resource, and corresponding test changes
2) A shared benchmark class/library that all benchmark programs would use. I modeled it after bigtable benchmark tests.
3) Initial shell or empty files for each benchmark program based on the resource being tested. Subsequent PRs would implement these files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600)

impl(bigquery): performance benchmark shared classes

---

google/cloud/pubsub/publisher_connection_test.cc

Fixes #12626
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12628)

test(pubsub): remove race condition in test

---

google/cloud/pubsub/internal/publisher_tracing_connection.cc
google/cloud/pubsub/internal/publisher_tracing_connection_test.cc

Fix for https://github.com/googleapis/google-cloud-cpp/actions/runs/6168147169/job/16740231408
Caused by https://github.com/googleapis/google-cloud-cpp/pull/12617
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12633)

fix(pubsub): change size_t -> int for otel attribute

---

google/cloud/pubsub/internal/publisher_tracing_connection.cc
google/cloud/pubsub/internal/publisher_tracing_connection_test.cc

Closes #[12620](https://github.com/googleapis/google-cloud-cpp/issues/12620)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12636)

cleanup(pubsub): set attribute only when present

---

google/cloud/internal/opentelemetry.cc
google/cloud/internal/opentelemetry.h
google/cloud/internal/opentelemetry_test.cc

Fixes #12451 
I did not even try to build this PR... yolo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12648)

cleanup(otel): remove unused code

---

google/cloud/internal/tracing_rest_client_test.cc

Verify that `MakeTracingRestClient(...)` works when OTel is disabled
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12649)

test(otel+rest): coverage when otel disabled

---

google/cloud/storage/internal/storage_stub_factory_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12650)

test(storage): verify tracing stub included

---

google/cloud/pubsub/message.h
google/cloud/pubsub/message_test.cc

Part of [#12530](https://github.com/googleapis/google-cloud-cpp/issues/12530)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12644)

impl(pubsub): add set attribute accessor for message

---

google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection_test.cc

Closes #12526
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12639)

impl(pubsub): enable flow control tracing when set

---

google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc
google/cloud/bigquery/v2/minimal/benchmarks/benchmark_test.cc
google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config.cc
google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config.h
google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config_test.cc
google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc

This PR contains the following changes:
1) A Dataset benchmark program that runs the benchmark for GetDataset and ListDataset BQ Apis and prints out the latency results
2) Added additional parameters to benchmark_config classes related to running the benchmark and to print help/usage information and description about the Dataset benchmark program
3) Minor cleanup/refactor of the benchmark code.
The Dataset benchmark program has been tested and these are the various outputs from it: https://paste.googleplex.com/5052702143807488
Subsequent PRs will add the benchmark programs for Table, Project and the Job resources
Once I have added the code for all the benchmarks, I'll add a README file that details the prerequisites, how each of the benchmark program can be run similar to the above …

impl(bigquery): Dataset Benchmark program

---

google/cloud/bigtable/tests/instance_admin_integration_test.cc

Part of #12661.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12662)

cleanup(bigtable): replace a couple of expects with asserts

---

google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection_test.cc

Closes #12527
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12665)

impl(pubsub): use batching publisher conn if otel is set

---

google/cloud/pubsub/internal/message_batch.h

Part of #[12528](https://github.com/googleapis/google-cloud-cpp/issues/12528)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12640)

impl(pubsub): add message batch interface

---

ci/gha/builds/macos-bazel.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12684)

ci(gha): fix logging for macOS+Bazel

---

google/cloud/storage/async_connection.h
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl.h
google/cloud/storage/internal/async/connection_impl_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12691)

impl(GCS+gRPC): `ReadObject()` in async connection

---

google/cloud/storage/BUILD.bazel
google/cloud/storage/async_reader.cc
google/cloud/storage/async_reader.h
google/cloud/storage/async_reader_test.cc
google/cloud/storage/google_cloud_cpp_storage_grpc.bzl
google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
google/cloud/storage/storage_client_grpc_unit_tests.bzl

Introduce `AsyncReader`, the public API to asynchronously read object contents.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12688)

impl(GCS+gRPC): asynchronous object reader

---

google/cloud/storage/async_client.h
google/cloud/storage/examples/storage_async_samples.cc
google/cloud/storage/tests/async_client_integration_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12694)

impl(GCS+gRPC): asynchronous `ReadObject()`

---

google/cloud/storage/examples/storage_async_samples.cc

/FYI: @frankyn
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12695)

docs(GCS+gRPC): additional `ReadObject()` example

---

google/cloud/compute/v1/.repo-metadata.json

part of the work for #11791
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12696)

doc(compute): add repo-metadata.json

---

google/cloud/bigtable/examples/data_async_snippets.cc
google/cloud/bigtable/testing/table_integration_test.cc
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsublite/internal/routing_policy.h
google/cloud/spanner/integration_tests/data_types_integration_test.cc
google/cloud/spanner/internal/connection_impl_test.cc
google/cloud/storage/compose_many_test.cc
google/cloud/storage/examples/storage_policy_doc_samples.cc
google/cloud/storage/examples/storage_service_account_samples.cc
google/cloud/storage/examples/storage_signed_url_v2_samples.cc
google/cloud/storage/examples/storage_signed_url_v4_samples.cc
google/cloud/storage/oauth2/compute_engine_credentials.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12699)

cleanup: fixes for GCC 13

---

ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
ci/cloudbuild/triggers/cxx14-ci.yaml
ci/cloudbuild/triggers/cxx14-pr.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12714)

ci: move cxx14 build to Fedora:38

---

ci/cloudbuild/dockerfiles/fedora-m32.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12717)

ci: move m32 build to Fedora:38

---

google/cloud/pubsub/message.cc
google/cloud/pubsub/message.h
google/cloud/pubsub/message_test.cc

Part of https://github.com/googleapis/google-cloud-cpp/issues/12530
Needs to be submitted before #12667
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12722)

impl(pubsub): add friend function to return an attribute value

---

ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile

Reduce inconsistencies between these Dockerfiles and between the different steps in the Dockerfiles themselves.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12725)

ci: cleanup `cxx14` and `cxx20` Dockerfiles

---

google/cloud/storage/internal/grpc/buffer_read_object_data.cc
google/cloud/storage/internal/grpc/buffer_read_object_data.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12729)

impl(GCS+gRPC): more efficient Cord construction

---

ci/cloudbuild/builds/asan.sh
ci/cloudbuild/builds/msan.sh
ci/cloudbuild/builds/tsan.sh
ci/cloudbuild/builds/ubsan.sh
ci/cloudbuild/builds/xsan.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12733)

ci: some more io::run calls to delineate build output

---

google/cloud/pubsub/message.cc
google/cloud/pubsub/message.h
google/cloud/pubsub/message_test.cc

Part of https://github.com/googleapis/google-cloud-cpp/issues/12530
Needs to be submitted before https://github.com/googleapis/google-cloud-cpp/pull/12667
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12736)

impl(pubsub): change GetAttribute from  std::string to absl::string_view

---

ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12740)

ci: simplify Dockerfile for CMake builds

---

google/cloud/internal/rest_stub_helpers.cc
google/cloud/internal/rest_stub_helpers.h
google/cloud/internal/rest_stub_helpers_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12741)

refactor(rest): ProtoRequestToJsonPayload signature

---

.bazelrc
CHANGELOG.md
ci/cloudbuild/build.sh
ci/cloudbuild/builds/integration-daily.sh
ci/cloudbuild/dockerfiles/fedora-latest-bazel.Dockerfile
ci/cloudbuild/triggers/asan-ci.yaml
ci/cloudbuild/triggers/asan-pr.yaml
ci/cloudbuild/triggers/bazel-oldest-ci.yaml
ci/cloudbuild/triggers/bazel-oldest-pr.yaml
ci/cloudbuild/triggers/bazel-targets-ci.yaml
ci/cloudbuild/triggers/bazel-targets-pr.yaml
ci/cloudbuild/triggers/coverage-ci.yaml
ci/cloudbuild/triggers/coverage-pr.yaml
ci/cloudbuild/triggers/integration-production-ci.yaml
ci/cloudbuild/triggers/integration-production-pr.yaml
ci/cloudbuild/triggers/libcxx-ci.yaml
ci/cloudbuild/triggers/libcxx-pr.yaml
ci/cloudbuild/triggers/otel-disabled-bazel-ci.yaml
ci/cloudbuild/triggers/otel-disabled-bazel-pr.yaml
ci/cloudbuild/triggers/tsan-ci.yaml
ci/cloudbuild/triggers/tsan-pr.yaml
ci/cloudbuild/triggers/ubsan-ci.yaml
ci/cloudbuild/triggers/ubsan-pr.yaml
ci/cloudbuild/triggers/xsan-ci.yaml
ci/cloudbuild/triggers/xsan-pr.yaml
doc/compile-time-configuration.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12743)

ci: move Bazel builds to Fedora:38

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/google_cloud_cpp_pubsub.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12744)

cleanup(pubsub): add message_batch.h to build

---

CHANGELOG.md
google/cloud/opentelemetry/README.md

Fixes #12726 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12748)

doc(otel): GA

---

ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12750)

ci: move `msan` build to Fedora:38

---

ci/cloudbuild/README.md
ci/cloudbuild/schedule.sh
ci/cloudbuild/schedules/clang-tidy-compute-schedule.json
ci/cloudbuild/schedules/grpc-at-head-schedule.json
ci/cloudbuild/schedules/integration-daily-schedule.json
ci/cloudbuild/schedules/protobuf-at-head-schedule.json
ci/cloudbuild/schedules/rotate-keys-schedule.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12751)

ci: script schedule-triggered builds

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12757)

cleanup: fix library link

---

ci/cloudbuild/triggers/grpc-at-head.yaml
ci/cloudbuild/triggers/integration-daily.yaml
ci/cloudbuild/triggers/protobuf-at-head.yaml
ci/cloudbuild/triggers/rotate-keys.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12763)

ci: save triggers for scheduled jobs

---

CHANGELOG.md
google/cloud/compute/README.md
google/cloud/compute/doc/main.dox

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12756)

doc(compute): update CHANGELOG and other docs for GA

---

google/cloud/opentelemetry/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12768)

doc(otel): update link

---

google/cloud/compute/samples/disk_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12767)

impl(compute): handle optional sample arg

---

google/cloud/compute/CMakeLists.txt
google/cloud/compute/quickstart/CMakeLists.txt
google/cloud/compute/quickstart/Makefile

fixes #12759
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12777)

impl(compute): add google_cloud_cpp_compute INTERFACE cmake target

---

google/cloud/pubsub/internal/publisher_tracing_connection.cc
google/cloud/pubsub/internal/publisher_tracing_connection_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12774)

cleanup(pubsub): add attribute to publish

---

google/cloud/pubsub/internal/publisher_stub_factory.cc
google/cloud/pubsub/internal/publisher_stub_factory_test.cc
google/cloud/pubsub/publisher_connection_test.cc

Closes https://github.com/googleapis/google-cloud-cpp/issues/12529
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12776)

impl(pubsub): add tracing stub if enabled

---

google/cloud/internal/opentelemetry.cc
google/cloud/internal/opentelemetry.h
google/cloud/internal/opentelemetry_test.cc

Part of https://github.com/googleapis/google-cloud-cpp/issues/12778
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12787)

impl(otel): add a make span with attributes function

---

google/cloud/pubsub/internal/batching_publisher_tracing_connection.cc
google/cloud/pubsub/internal/flow_controlled_publisher_tracing_connection.cc

Closes https://github.com/googleapis/google-cloud-cpp/issues/12778
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12791)

cleanup(pubsub): set attribute on span creation

---

ci/cloudbuild/builds/clang-tidy.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12794)

ci(clang-tidy-pr): remove integration tests

---

generator/internal/scaffold_generator.cc

Part of #12631.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12803)

impl(generator): use google::cloud::Location in prototype quickstarts

---

BUILD.bazel
google/cloud/storage/examples/BUILD.bazel
google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/examples/storage_async_mock_samples.cc
google/cloud/storage/examples/storage_examples.bzl
google/cloud/storage/examples/storage_grpc_examples.bzl
google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
google/cloud/storage/mocks/mock_async_connection.h

Also includes some examples of how to use the mock.  These double up as tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12806)

impl(GCS+gRPC): add mock for `AsyncConnection`

---

google/cloud/storage/internal/rest/stub.cc

Using types from `storage/internal/curl/*` makes it hard to remove the latter.
Part of the work for #9659
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12809)

cleanup(storage): decouple RestClient from curl/

---

generator/internal/scaffold_generator.cc

Fixes an error in #12803.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12815)

impl(generator): account for nested services in scaffold product_namespace

---

google/cloud/bigquery/v2/minimal/benchmarks/CMakeLists.txt
google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config.cc
google/cloud/bigquery/v2/minimal/benchmarks/experimental_bigquery_rest_client_benchmark_programs.bzl
google/cloud/bigquery/v2/minimal/benchmarks/job_query_benchmark_programs.cc

This PR includes the following benchmark changes:
- A new benchmark program that tests the  Query() and GetQueryResults() apis end to end and prints out latency and throughput results. The output is [here](https://paste.googleplex.com/6258557430267904). Additionally, verified the query given in the QueryRequest executed successfully i.e. in this specific case, made sure that DDL statements were successful.
- Benchmark fixes related to Query and GetQueryResults api as listed below:
- Fixed benchmark GetQueryResults api to remove the format_options since its not supported by the server.
- Fixed the json payload for create and drop statements in dry-run and non dry-run mode.
- Fixed benchmark’s Query method  to remove the empty keys from json payload.
- - - …

impl(bigquery): Benchmark program for Query and GetQueryResults api

---

google/cloud/bigquery/v2/minimal/benchmarks/BUILD.bazel
google/cloud/bigquery/v2/minimal/benchmarks/CMakeLists.txt
google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc
google/cloud/bigquery/v2/minimal/benchmarks/job_insert_benchmark_programs.cc
google/cloud/bigquery/v2/minimal/benchmarks/job_query_benchmark_programs.cc
google/cloud/bigquery/v2/minimal/benchmarks/job_readonly_benchmark_programs.cc
google/cloud/bigquery/v2/minimal/benchmarks/project_benchmark_programs.cc
google/cloud/bigquery/v2/minimal/benchmarks/table_benchmark_programs.cc

This PR includes common cleanup changes across benchmark files, based on feedback in previous PRs:
- Renamed Bigquery => BigQuery
- Renamed api => API
- Fixed Copyright text in multiple files.
This PR completes all the benchmark changes for the v2/minimal apis. 
BIG Thank you for all the reviews!!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12829)

impl(bigquery): Benchmark programs cleanup

---

google/cloud/storage/internal/make_jwt_assertion.cc
google/cloud/storage/internal/openssl_util.cc
google/cloud/storage/internal/openssl_util.h
google/cloud/storage/oauth2/service_account_credentials.h

Remove an unused parameter. Or "a parameter that was always used with the same value" if you prefer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12831)

cleanup(storage): internal function with unused param

---

bazel/google_cloud_cpp_deps.bzl
ci/cloudbuild/dockerfiles/centos-7.Dockerfile
ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile
ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile
doc/packaging.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12834)

chore(deps): update Protobuf to v24.4

---

ci/cloudbuild/builds/lib/integration.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12838)

chore(deps): update storage testbench to v0.39.0

---

ci/cloudbuild/triggers/clang-tidy-compute.yaml
ci/cloudbuild/triggers/publish-docs-release.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12846)

ci: missing trigger yaml files

---

google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12850)

impl(pubsub): add event to publish span

---

bazel/crc32c.BUILD

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12851)

fix(storage): automatically configure crc32c for ARM64

---

ci/verify_current_targets/CMakeLists.txt
cmake/GoogleCloudCppFeatures.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12860)

cleanup: consistent CMake sorting directives

---

google/cloud/testing_util/opentelemetry_matchers.cc
google/cloud/testing_util/opentelemetry_matchers.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12858)

test(otel): add linking matchers for unit tests

---

google/cloud/testing_util/opentelemetry_matchers.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12863)

cleanup: remove unneeded namespace qualifier

---

google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch.h
google/cloud/pubsub/internal/tracing_message_batch_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12862)

impl(pubsub): add tracing message flush callback impl

---

ci/cloudbuild/builds/coverage.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12871)

chore: update codecov uploader

---

google/cloud/internal/opentelemetry.cc
google/cloud/internal/opentelemetry.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12857)

impl(otel): add a function to create a span with links

---

google/cloud/pubsub/internal/message_propagator.cc
google/cloud/pubsub/internal/message_propagator.h
google/cloud/pubsub/internal/message_propagator_test.cc
google/cloud/pubsub/internal/publisher_tracing_connection.cc
google/cloud/pubsub/internal/publisher_tracing_connection_test.cc

Closes https://github.com/googleapis/google-cloud-cpp/issues/12530
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12868)

impl(pubsub): inject trace context into message

---

ci/gha/builds/windows-bazel.sh
google/cloud/compute/BUILD.bazel
protos/google/cloud/compute/BUILD.bazel

Tested on https://github.com/googleapis/google-cloud-cpp/actions/runs/6487918176/job/17619290737
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12877)

fix(compute): build with Bazel and MSVC

---

release/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12883)

cleanup: vcpkg update tweaks

---

google/cloud/compute/integration_tests/BUILD.bazel
google/cloud/compute/integration_tests/CMakeLists.txt
google/cloud/compute/integration_tests/compute_integration_test.cc

fixes #12874
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12885)

impl(compute): rework non-hermetic integration test

---

google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/batching_publisher_connection.h
google/cloud/pubsub/internal/batching_publisher_connection_test.cc
google/cloud/pubsub/internal/noop_message_batch.h
google/cloud/pubsub/publisher_connection.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12869)

impl(pubsub): add noop message batch to connection

---

doc/contributor/howto-guide-adding-generated-libraries.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12889)

docs: update 'generate libraries' howto

---

google/cloud/compute/integration_tests/compute_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12888)

impl(compute): improved matcher

---

google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh
google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12891)

ci: skip production-only targets in coverage builds

---

google/cloud/internal/opentelemetry.h
google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch.h
google/cloud/pubsub/internal/tracing_message_batch_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12859)

impl(pubsub): add initial flush impl for less than 128 links

---

doc/contributor/howto-guide-setup-development-workstation.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12896)

docs: update instructions for GCE instances

---

google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch.h
google/cloud/pubsub/internal/tracing_message_batch_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12897)

impl(pubsub): add flush events to message span

---

google/cloud/internal/opentelemetry.cc
google/cloud/internal/opentelemetry.h
google/cloud/internal/opentelemetry_test.cc
google/cloud/testing_util/opentelemetry_matchers.cc
google/cloud/testing_util/opentelemetry_matchers.h

Closes https://github.com/googleapis/google-cloud-cpp/issues/12899
- add some unit tests for make span
- add a matcher for the parent span id
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12900)

impl(otel): pass in options to MakeSpan

---

google/cloud/storage/internal/async/connection_tracing.cc
google/cloud/storage/internal/async/connection_tracing_test.cc
google/cloud/storage/internal/async/reader_connection_tracing.cc
google/cloud/storage/internal/async/reader_connection_tracing_test.cc
google/cloud/testing_util/opentelemetry_matchers.h

Part of the work for #12880 
- Start an `OTelScope` instead of an `opentelemetry::trace::Scope`
- Manually detach that context (unless `EndSpan()` is already doing it for us)
In tests I wanted to verify that there were no active spans, nor an active scope during the execution of the `.then()`. The best way I came up with to test it was to wrap the promises to behave more like an `AsyncGrpcOperation` (such as an `AsyncUnaryRpcFuture`).
I suspect other handwritten libraries will need/want this helper so it is placed in `testing_util`.
---
code style things:
- The order that we call `EndSpan(...)` and `DetachOTelContext(...)` doesn't matter.
- I am considering factoring out something like:
```
template <typename T>
future<T> DetachOTelContext(future<T> f) {
return f.then([oc = …
```

fix(storage): fix when async client spans are ended

---

generator/internal/descriptor_utils.cc
generator/internal/format_class_comments.cc
generator/internal/format_class_comments.h
generator/internal/format_class_comments_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12927)

refactor(generator): take service name as a param

---

google/cloud/spanner/integration_tests/client_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12940)

test(spanner): fix `signed` vs. `unsigned` warning

---

google/cloud/spanner/internal/connection_impl_test.cc

Extend the "Session not found"-returning tests for `Read()` and `BatchWrite()` to make an additional call to verify that the bad session was not returned to the pool.  Streaming reads follow a different model given that the error response is part of the stream, so they deserve some additional coverage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12944)

test(spanner): extend bad-session tests for streaming-read RPCs

---

generator/generator_config.proto
generator/internal/codegen_utils.cc
generator/internal/codegen_utils_test.cc
generator/standalone_main.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12947)

impl(generator): add service_name_to_comment flag

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/internal/subscriber_stub_factory.cc
google/cloud/pubsub/internal/subscriber_stub_factory.h
google/cloud/pubsub/internal/subscriber_stub_factory_test.cc
google/cloud/pubsub/pubsub_client_unit_tests.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12949)

test(pubsub): add unit test for the subscriber factory

---

google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
google/cloud/storage/tests/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12963)

cleanup(storage): remove integration test variant

---

google/cloud/bigtable/data_client.h
google/cloud/bigtable/internal/async_bulk_apply.h
google/cloud/bigtable/internal/bulk_mutator.cc
google/cloud/bigtable/internal/bulk_mutator.h
google/cloud/bigtable/internal/bulk_mutator_test.cc
google/cloud/bigtable/internal/data_connection_impl.cc
google/cloud/bigtable/internal/legacy_async_bulk_apply.h
google/cloud/bigtable/internal/legacy_bulk_mutator_test.cc
google/cloud/bigtable/table.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12967)

cleanup(bigtable): move to bigtable_internal

---

generator/internal/descriptor_utils.cc
generator/internal/descriptor_utils_test.cc

Closes https://github.com/googleapis/google-cloud-cpp/issues/12935
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12945)

cleanup(generator): refactor GetEffectiveServiceName

---

ci/cloudbuild/build.sh
ci/cloudbuild/builds/clang-tidy.sh
ci/cloudbuild/cloudbuild.yaml
ci/cloudbuild/triggers/clang-tidy-bigquery-ci.yaml
ci/cloudbuild/triggers/clang-tidy-bigquery-pr.yaml
ci/cloudbuild/triggers/clang-tidy-compute.yaml
ci/cloudbuild/triggers/clang-tidy-pubsub-ci.yaml
ci/cloudbuild/triggers/clang-tidy-pubsub-pr.yaml
ci/cloudbuild/triggers/clang-tidy-storage-ci.yaml
ci/cloudbuild/triggers/clang-tidy-storage-pr.yaml
ci/cloudbuild/triggers/clang-tidy-tools-ci.yaml
ci/cloudbuild/triggers/clang-tidy-tools-pr.yaml
ci/lib/shard.sh

Reduce the worst-case build time by (imperfectly) sharding the build N ways.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12966)

ci: shard the `clang-tidy` build

---

ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12974)

ci: use `ctcache` from main repo

---

google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12977)

impl(pubsub): use semantic convention for attribute

---

generator/internal/descriptor_utils.cc
generator/internal/descriptor_utils_test.cc
generator/internal/format_class_comments.cc
generator/internal/format_class_comments.h
generator/internal/format_class_comments_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12982)

impl(generator): replace leading service comment with config

---

generator/internal/descriptor_utils.cc
generator/internal/format_class_comments.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12983)

cleanup(generator): address review comments post-merge

---

generator/standalone_main.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12985)

fix(generator): use the correct arg 🤦 

---

google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch_test.cc

Closes https://github.com/googleapis/google-cloud-cpp/issues/12958
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12975)

fix(pubsub): create root async batch sink spans

---

google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection.h
google/cloud/pubsub/publisher_connection_test.cc

Reverts googleapis/google-cloud-cpp#12996
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12998)

Revert "impl(pubsub): use tracing message batch"

---

release/README.md

- Add ordered lists so steps are easier to reference
- Move sections and add headers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13020)

docs(release): update release notes for readability

---

google/cloud/pubsub/internal/subscriber_stub_factory.cc
google/cloud/pubsub/internal/subscriber_stub_factory.h
google/cloud/pubsub/subscriber_connection.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13021)

refactor(pubsub): use subscriber factory

---

generator/integration_tests/tests/golden_kitchen_sink_auth_decorator_test.cc
generator/integration_tests/tests/golden_kitchen_sink_logging_decorator_test.cc
generator/integration_tests/tests/golden_kitchen_sink_metadata_decorator_test.cc
generator/integration_tests/tests/golden_kitchen_sink_stub_test.cc
google/cloud/bigtable/internal/bigtable_stub_factory_test.cc
google/cloud/internal/streaming_read_rpc_test.cc
google/cloud/storage/async_writer_test.cc
google/cloud/storage/internal/async/connection_impl_test.cc
google/cloud/storage/internal/async/connection_tracing_test.cc
google/cloud/storage/internal/async/reader_connection_impl_test.cc
google/cloud/storage/internal/async/writer_connection_impl_test.cc
google/cloud/storage/internal/async/writer_connection_tracing_test.cc
google/cloud/storage/internal/storage_stub_factory_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13028)

cleanup: prefer `VariantWith` matcher

---

google/cloud/credentials.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13033)

doc: fix cliffhanger

---

google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch_test.cc
google/cloud/pubsub/publisher_connection_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13039)

refactor(pubsub): rename spans to match other languages

---

google/cloud/pubsub/internal/defaults.cc
google/cloud/pubsub/internal/defaults_test.cc
google/cloud/pubsub/options.h

Part of https://github.com/googleapis/google-cloud-cpp/issues/12979
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13024)

impl(pubsub): add MaxOtelLinkCountOption

---

google/cloud/internal/async_long_running_operation.h
google/cloud/internal/async_long_running_operation_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13053)

cleanup: explicit options for LROs

---

google/cloud/internal/async_rest_long_running_operation.h
google/cloud/internal/async_rest_long_running_operation_test.cc
google/cloud/internal/async_rest_polling_loop.cc
google/cloud/internal/async_rest_polling_loop.h
google/cloud/internal/async_rest_polling_loop_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13054)

impl(common): explicit options in REST polling loop

---

google/cloud/storage/async_client.h
google/cloud/storage/tests/async_client_integration_test.cc

This is the (anticipated) public API to create objects using a streaming upload.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13051)

impl(GCS+GRPC): `AsyncClient::WriteObject()`

---

doc/contributor/howto-guide-modify-gha.md
doc/contributor/howto-guide-test-gha.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13056)

docs: how to test gha

---

google/cloud/internal/async_rest_long_running_operation.h
google/cloud/internal/async_rest_long_running_operation_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13059)

impl(common): explicit options for REST LRO

---

ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13064)

chore: upgrade demo-fedora build to Fedora:39

---

google/cloud/storage/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13067)

fix: upstream fix for missing copybara deps

---

ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13071)

ci: upgrade cxx20 build to Fedora:39

---

google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch.h
google/cloud/pubsub/internal/tracing_message_batch_test.cc
google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection_test.cc
google/cloud/pubsub/testing/test_retry_policies.cc

Closes https://github.com/googleapis/google-cloud-cpp/issues/12979
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13047)

impl(pubsub): use option to determine link batch size

---

ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13074)

ci: ugprade msan build to Fedora:39

---

ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13077)

ci: upgrade cxx14 build to Fedora:39

---

bazel/google_cloud_cpp_deps.bzl

Fixes #12113
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13080)

chore(deps): update `rules_cc` to 0.0.9

---

.bazelrc
bazel/curl.BUILD
ci/cloudbuild/builds/asan.sh
ci/cloudbuild/dockerfiles/fedora-latest-bazel.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13081)

ci: update Bazel builds to Fedora:39

---

generator/internal/longrunning.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13094)

cleanup(generator): prepare for `clang-tidy` 17

---

google/cloud/pubsub/internal/sequential_batch_sink.cc
google/cloud/pubsub/message.h
google/cloud/pubsub/samples/iam_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13092)

cleanup(pubsub): prepare for `clang-tidy` 17

---

google/cloud/spanner/internal/connection_impl_test.cc
google/cloud/spanner/internal/tuple_utils.h
google/cloud/spanner/numeric.h
google/cloud/spanner/row.h
google/cloud/spanner/value.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13091)

cleanup(spanner): prepare for `clang-tidy` 17

---

generator/generator_config.textproto

Adddress comment https://github.com/googleapis/google-cloud-cpp/pull/13089
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13096)

fix: capitalize network in comment

---

docfx/node_name.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13100)

impl(docfx): prepare for `doxygen` 1.9.7

---

google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13099)

cleanup(bigquery): prepare for `clang-tidy` 17

---

google/cloud/storage/internal/grpc/stub.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13105)

cleanup(GCS+gRPC): simplify-stub-initialization

---

.clang-tidy
ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13095)

ci: upgrade CMake builds to Fedora:39

---

.github/renovate.json
.github/workflows/external-account-integration.yml
ci/cloudbuild/dockerfiles/centos-7.Dockerfile
ci/cloudbuild/dockerfiles/demo-alpine-stable.Dockerfile
ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-bookworm.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-publish-docs.Dockerfile
ci/cloudbuild/dockerfiles/fedora-m32.Dockerfile
ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13112)

chore(deps): update sccache to v0.7.1

---

google/cloud/google_cloud_cpp_common.bzl
google/cloud/google_cloud_cpp_common.cmake
google/cloud/universe_domain_options.h

fixes #13116 
fixes #13117
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13120)

impl: add universe domain options

---

google/cloud/sql/integration_tests/sql_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13132)

test(sql): retry loop in integration test

---

.bazelrc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13137)

ci: silence warnings for external dependencies

---

.bazelrc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13138)

ci: dedup configuration in bazelrc file

---

google/cloud/internal/credentials_impl.cc
google/cloud/internal/credentials_impl.h
google/cloud/internal/credentials_impl_test.cc
google/cloud/internal/unified_grpc_credentials.cc
google/cloud/internal/unified_grpc_credentials_test.cc
google/cloud/internal/unified_rest_credentials.cc
google/cloud/internal/unified_rest_credentials_test.cc
google/cloud/storage/internal/unified_rest_credentials.cc
google/cloud/storage/internal/unified_rest_credentials_test.cc

fixes #13119
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13135)

impl: add ErrorCredentials support

---

google/cloud/internal/compute_engine_util.cc
google/cloud/internal/compute_engine_util_test.cc
google/cloud/internal/unified_rest_credentials_test.cc
google/cloud/storage/internal/compute_engine_util.cc
google/cloud/storage/internal/compute_engine_util_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13139)

fix(common): use FQDN for the metadata service

---

google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch_test.cc

Rename pubsub.batch_sink -> gcp_pubsub.publish
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13143)

refactor(pubsub): rename span event attribute

---

google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch_test.cc

Also rename batch flushed to publish_start
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13152)

impl(pubsub): add event at the end of the async publish

---

google/cloud/bigtable/internal/mutate_rows_limiter.cc
google/cloud/bigtable/internal/mutate_rows_limiter_test.cc

(A less important) part of the work for #12959
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13157)

impl(bigtable): tracing for bulk apply throttling

---

google/cloud/pubsub/blocking_publisher_connection_test.cc
google/cloud/pubsub/internal/blocking_publisher_tracing_connection.cc
google/cloud/pubsub/internal/blocking_publisher_tracing_connection_test.cc
google/cloud/pubsub/internal/publisher_tracing_connection.cc
google/cloud/pubsub/internal/publisher_tracing_connection_test.cc
google/cloud/pubsub/publisher_connection_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13153)

refactor(pubsub): rename s/send/create

---

google/cloud/storage/benchmarks/BUILD.bazel
google/cloud/storage/benchmarks/CMakeLists.txt
google/cloud/storage/benchmarks/async_throughput_benchmark.cc
google/cloud/storage/benchmarks/benchmark_utils.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13146)

test(GCS+gRPC): a benchmark for resumable uploads

---

google/cloud/pubsub/internal/tracing_message_batch.cc

https://github.com/googleapis/google-cloud-cpp/pull/13152/files#r1399485848
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13163)

cleanup(pubsub): save a copy

---

google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13167)

refactor(pubsub): s/pubsub/gcp_pubsub

---

google/cloud/pubsub/internal/blocking_publisher_tracing_connection.cc
google/cloud/pubsub/internal/publisher_tracing_connection.cc
google/cloud/pubsub/internal/publisher_tracing_connection_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13166)

impl(pubsub): add messaging.operation attr

---

google/cloud/pubsub/internal/batch_sink.h
google/cloud/pubsub/internal/default_batch_sink.h
google/cloud/pubsub/internal/sequential_batch_sink.h
google/cloud/pubsub/testing/mock_batch_sink.h

Part of https://github.com/googleapis/google-cloud-cpp/issues/13171
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13174)

refactor(pubsub): add no-op addmessage to batch sink interface

---

google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13175)

refactor(pubsub): change span to a producer kind

---

google/cloud/pubsub/benchmarks/BUILD.bazel
google/cloud/pubsub/benchmarks/endurance.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13172)

cleanup(pubsub): adapt to different forms of PubsubMessageDataType

---

google/cloud/pubsub/internal/publisher_tracing_connection.cc
google/cloud/pubsub/internal/publisher_tracing_connection_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13182)

refactor(pubsub): use sc instead of string

---

google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/message_batch.h
google/cloud/pubsub/internal/noop_message_batch.h
google/cloud/pubsub/internal/tracing_message_batch.cc
google/cloud/pubsub/internal/tracing_message_batch_test.cc
google/cloud/pubsub/publisher_connection_test.cc
google/cloud/pubsub/testing/mock_message_batch.h

This is a no-op
https://github.com/googleapis/google-cloud-cpp/issues/13171
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13179)

refactor(pubsub): s/SaveMessage/AddMessage

---

google/cloud/internal/async_read_write_stream_auth_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13184)

test(common): use public `MockAsyncStreamingReadWriteRpc`

---

ci/cloudbuild/builds/cmake-install.sh
ci/cloudbuild/builds/cmake-split-install.sh
ci/cloudbuild/builds/quickstart-production.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13181)

cleanup: ci nits

---

google/cloud/internal/populate_common_options.cc
google/cloud/internal/populate_common_options_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13190)

impl: check for empty EndpointOption in PopulateCommonOptions

---

google/cloud/options.h
google/cloud/options_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13195)

impl: add FetchOption

---

google/cloud/spanner/client.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13201)

cleanup(spanner): use FetchOption() in spanner::Client

---

google/cloud/internal/service_endpoint.cc
google/cloud/internal/service_endpoint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13207)

impl: check for empty parameters in DetermineServiceEndpoint

---

google/cloud/pubsub/internal/tracing_batch_sink_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13220)

fix(pubsub): pass by reference explictly

---

google/cloud/pubsub/internal/tracing_batch_sink.cc
google/cloud/pubsub/internal/tracing_batch_sink.h
google/cloud/pubsub/internal/tracing_batch_sink_test.cc
google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13222)

refactor(pubsub): add topic to publish span

---

cmake/GoogleCloudCppFeatures.cmake
google/cloud/sql/quickstart/BUILD.bazel
google/cloud/sql/quickstart/CMakeLists.txt
libraries.bzl

fixes #13212
fixes #12120 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13210)

chore(sql): move from transitional to GA

---

google/cloud/internal/populate_common_options.cc
google/cloud/internal/populate_common_options_test.cc
google/cloud/internal/service_endpoint.cc
google/cloud/internal/service_endpoint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13225)

impl: allow empty EndpointOption

---

BUILD.bazel
google/cloud/compute/quickstart/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13226)

impl(compute): add aggregate bazel target

---

generator/generator_config.textproto
google/cloud/pubsub/admin/internal/subscription_admin_option_defaults.cc
google/cloud/pubsub/admin/internal/topic_admin_option_defaults.cc
google/cloud/pubsub/integration_tests/blocking_publisher_integration_test.cc

Part of https://github.com/googleapis/google-cloud-cpp/issues/13250
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13251)

test(pubsub): add tracing enabled tests for blocking publisher

---

release/README.md
release/howto-update-conan-package.md

Also updated the document with more information on troubleshooting problems while preparing a PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13257)

docs: separate document for Conan packages

---

google/cloud/spanner/integration_tests/client_integration_test.cc

Since the `DirectedReadOption` support was released, the backend has grown the ability to detect and reject its use outside of read-only transactions.  The ask on the client libraries was to ensure that we could elicit the error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13261)

test(spanner): add test for directed read within RW transaction

---

google/cloud/testing_util/validate_metadata.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13280)

cleanup: spare heap allocations in test

---

ci/cloudbuild/builds/coverage.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13291)

ci: ignore negative coverage counts

---

ci/verify_current_targets/CMakeLists.txt
google/cloud/sql/config.cmake.in

Part of the work for #12120
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13289)

cleanup(sql): remove backwards compatibility target

---

google/cloud/bigtable/client_options.cc
google/cloud/bigtable/client_options_test.cc
google/cloud/bigtable/internal/defaults.cc
google/cloud/bigtable/internal/defaults_test.cc

Follow up to #13254 for bigtable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13305)

fix(bigtable): use FQDN

---

google/cloud/future_generic.h
google/cloud/future_generic_then_test.cc
google/cloud/internal/future_impl.h
google/cloud/internal/future_then_meta.h

Motivated by #13258
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13299)

cleanup(common): simplify `make_ready_future()`

---

.bazelrc
WORKSPACE.bazel
bazel/google_cloud_cpp_deps.bzl
ci/cloudbuild/builds/lib/bazel.sh
ci/cloudbuild/builds/quickstart-bazel.sh
ci/gha/builds/lib/bazel.sh
ci/gha/builds/macos-bazel.sh
ci/verify_current_targets/.bazelrc
ci/verify_current_targets/WORKSPACE.bazel
ci/verify_deprecated_targets/.bazelrc
ci/verify_deprecated_targets/WORKSPACE.bazel
generator/internal/scaffold_generator.cc
generator/templates/WORKSPACE.bazel

Reverts googleapis/google-cloud-cpp#13274
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13319)

revert: update Bazel to v7

---

WORKSPACE.bazel
bazel/deps-cache.py
bazel/development0.bzl
bazel/development1.bzl
bazel/workspace0.bzl
bazel/workspace1.bzl
bazel/workspace2.bzl
bazel/workspace3.bzl
bazel/workspace4.bzl
bazel/workspace5.bzl
external/googleapis/renovate.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13322)

refactor: Bazel workspace functions

---

google/cloud/pubsub/internal/subscriber_tracing_connection.cc
google/cloud/pubsub/internal/subscriber_tracing_connection_test.cc

Part of https://github.com/googleapis/google-cloud-cpp/issues/13266
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13318)

impl(pubsub): add attributes at the end of the receive span

---

google/cloud/pubsub/subscriber_connection.cc
google/cloud/pubsub/subscriber_connection_test.cc

Part of https://github.com/googleapis/google-cloud-cpp/issues/13266
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13308)

impl(pubsub): use subscriber tracing connection

---

google/cloud/bigtable/internal/bigtable_stub_factory_test.cc

Motivated by #13300
The stub factory conditionally includes several layers. It is clearer to organize the tests by the logic we are testing, as opposed to putting all the expectations in one test, then copying it * N RPCs.
e.g. We want to make sure we do not include the logging layer when it is not enabled. The old tests didn't do that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13329)

test(bigtable): redo stub factory tests

---

google/cloud/bigtable/internal/defaults.cc
google/cloud/bigtable/internal/defaults_test.cc

Fixes #13300 
Bigtable is weird because I (foolishly) introduced individual options for each service endpoint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13335)

impl(bigtable): support `UniverseDomainOption`

---

google/cloud/storage/async/client.h
google/cloud/storage/examples/storage_async_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13333)

impl(GCS+gRPC): examples for async `WriteObject()`

---

google/cloud/internal/future_then_impl_test.cc

In our `noex` build this function works, but that is not always the case when exceptions are disabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13337)

test(common): avoid `std::make_exception_ptr()`

---

google/cloud/pubsub/internal/subscriber_tracing_connection.cc
google/cloud/pubsub/internal/subscriber_tracing_connection_test.cc
google/cloud/pubsub/internal/tracing_batch_sink_test.cc

Closes https://github.com/googleapis/google-cloud-cpp/issues/13264
Also remove use of anything matcher with LinkHasSpanContext in favor of SpanLinksSizeIs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13339)

impl(pubsub): add link from receive to create span

---

google/cloud/spanner/integration_tests/client_integration_test.cc

Reverts #13283.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13342)

test(spanner): reenable DirectedReadWithinReadWriteTransaction test

---

google/cloud/internal/compiler_info.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13348)

impl(common): correctly report C++23

---

google/cloud/storage/internal/rest/stub.cc

style nit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13352)

cleanup: multiline if

---

google/cloud/internal/populate_common_options.cc
google/cloud/internal/populate_common_options.h
google/cloud/internal/populate_common_options_test.cc
google/cloud/internal/populate_grpc_options.cc
google/cloud/internal/populate_grpc_options.h
google/cloud/internal/populate_grpc_options_test.cc

Part of the work for #13361
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13362)

refactor: DefaultTracingOptions into common

---

google/cloud/pubsub/internal/batching_publisher_tracing_connection.cc
google/cloud/pubsub/internal/batching_publisher_tracing_connection_test.cc
google/cloud/pubsub/publisher_connection_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13359)

refactor(pubsub): rename publish scheduler -> publisher batching

---

google/cloud/pubsub/internal/default_pull_lease_manager.cc
google/cloud/pubsub/internal/default_pull_lease_manager.h
google/cloud/pubsub/internal/default_pull_lease_manager_test.cc
google/cloud/pubsub/internal/pull_lease_manager.h

Part of https://github.com/googleapis/google-cloud-cpp/issues/13298
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13366)

impl(pubsub): add extend lease to pull manager interface

---

google/cloud/pubsub/internal/default_pull_lease_manager.cc
google/cloud/pubsub/internal/default_pull_lease_manager.h
google/cloud/pubsub/internal/default_pull_lease_manager_test.cc
google/cloud/pubsub/internal/pull_lease_manager.h

Part of https://github.com/googleapis/google-cloud-cpp/issues/13298
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13367)

impl(pubsub): add ack id and subscription to lease interface

---

BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13372)

feat(bigquery): expose experimental bigquery v2 mocks

---

google/cloud/pubsub/integration_tests/subscriber_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13375)

test(pubsub): add subscriber tracing tests for unary pull

---

google/cloud/pubsub/internal/pull_ack_handler_factory.cc
google/cloud/pubsub/internal/pull_ack_handler_factory.h
google/cloud/pubsub/internal/pull_ack_handler_factory_test.cc
google/cloud/pubsub/internal/subscriber_connection_impl.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13376)

refactor(pubsub): s/CreatePullAckHandler/MakePullAckHandler

---

generator/integration_tests/tests/golden_thing_admin_tracing_stub_test.cc
generator/internal/discovery_document.h
generator/internal/discovery_file.cc
generator/internal/discovery_file_test.cc
generator/internal/discovery_resource_test.cc
generator/internal/discovery_to_proto.cc
generator/internal/discovery_to_proto_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13381)

test(generator): Happy New Year!

---

google/cloud/storage/async/client.h
google/cloud/storage/async/connection.h
google/cloud/storage/benchmarks/async_throughput_benchmark.cc
google/cloud/storage/examples/storage_async_samples.cc
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl.h
google/cloud/storage/internal/async/connection_impl_test.cc
google/cloud/storage/internal/async/connection_tracing.cc
google/cloud/storage/internal/async/connection_tracing_test.cc
google/cloud/storage/mocks/mock_async_connection.h
google/cloud/storage/tests/async_client_integration_test.cc

Part of the work for #13385
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13399)

refactor(GCS+gRPC): rename `WriteObject()`

---

google/cloud/storage/internal/async/writer_connection_buffered.cc

Applications may discard the buffered writer while its reconnect loop is still running. That makes using `this` in a callback unsafe, we need another level of indirection.
Part of the work for #13385
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13407)

impl(GCS+gRPC): buffered writer shutdown

---

google/cloud/pubsub/internal/tracing_helpers.cc
google/cloud/pubsub/internal/tracing_helpers.h
google/cloud/pubsub/internal/tracing_helpers_test.cc
google/cloud/pubsub/internal/tracing_pull_ack_handler.cc
google/cloud/testing_util/opentelemetry_matchers.h

Part of [#13298](https://github.com/googleapis/google-cloud-cpp/issues/13298)
1/4 in a chain
1. https://github.com/googleapis/google-cloud-cpp/pull/13377
2. https://github.com/googleapis/google-cloud-cpp/pull/13378
3. https://github.com/googleapis/google-cloud-cpp/pull/13379
4. https://github.com/googleapis/google-cloud-cpp/pull/13389
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13377)

refactor(pubsub): create shared helper tracing functions

---

google/cloud/storage/async/connection.h
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl.h
google/cloud/storage/internal/async/connection_impl_test.cc
google/cloud/storage/internal/async/connection_tracing.cc
google/cloud/storage/internal/async/connection_tracing_test.cc
google/cloud/storage/mocks/mock_async_connection.h

Part of the work for #13385
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13409)

impl(GCS+gRPC): `Connection*::StartBufferUpload`

---

google/cloud/storage/async/client_test.cc
google/cloud/storage/object_metadata.cc
google/cloud/storage/object_metadata_test.cc

Fixes #13419
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13421)

test(GCS+gRPC): missing unit tests for `AsyncClient`

---

google/cloud/bigquery/v2/minimal/internal/job_request.cc
google/cloud/bigquery/v2/minimal/internal/job_request_test.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13430)

feat(bigquery): remove validation of input parameters

---

google/cloud/internal/async_rest_polling_loop_impl.h

Our favorite build environment requires this include
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13431)

cleanup: includes

---

generator/generator_config.textproto
google/cloud/storage/internal/storage_auth_decorator.cc
google/cloud/storage/internal/storage_auth_decorator.h
google/cloud/storage/internal/storage_logging_decorator.cc
google/cloud/storage/internal/storage_logging_decorator.h
google/cloud/storage/internal/storage_metadata_decorator.cc
google/cloud/storage/internal/storage_metadata_decorator.h
google/cloud/storage/internal/storage_round_robin_decorator.cc
google/cloud/storage/internal/storage_round_robin_decorator.h
google/cloud/storage/internal/storage_stub.cc
google/cloud/storage/internal/storage_stub.h
google/cloud/storage/internal/storage_tracing_stub.cc
google/cloud/storage/internal/storage_tracing_stub.h
google/cloud/storage/testing/mock_storage_stub.h

Part of the work for #9130
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13437)

impl(GCS+gRPC): generate `AsyncRewriteObject` methods

---

google/cloud/internal/oauth2_cached_credentials.cc
google/cloud/internal/oauth2_cached_credentials.h
google/cloud/internal/oauth2_cached_credentials_test.cc
google/cloud/internal/oauth2_logging_credentials.cc
google/cloud/internal/oauth2_logging_credentials.h
google/cloud/internal/oauth2_logging_credentials_test.cc
google/cloud/internal/oauth2_service_account_credentials.cc
google/cloud/internal/oauth2_service_account_credentials.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13454)

impl(oauth2): add additional universe_domain overrides

---

google/cloud/bigtable/internal/data_connection_impl.cc
google/cloud/bigtable/internal/data_connection_impl_test.cc

Note that `ReadModifyWriteRow` is always treated as non-idempotent.
I tried to do this using an adapter. I could get it to work for the unary sync RPCs. I like how the adapter can abstract the logic relevant to the `RetryContext`, and leave it in `retry_context.h`.
But I could not get the async version to work, which is scary. There are only 2 RPCs that need the adapter. The adapter code isn't horrendously long. Composing functions is slightly less performant. Also, this PR is easier to review, and I have other PRs blocked on it.
https://github.com/dbolduc/google-cloud-cpp/blob/81590f37a400eb15846543f227b91e183fd31a04/google/cloud/bigtable/internal/retry_context.h#L68-L95
https://github.com/dbolduc/google-cloud-cpp/blob/81590f37a400eb15846543f227b91e183fd31a04/ …

impl(bigtable): bigtable cookie support in sync unary RPCs

---

google/cloud/storage/client_options.cc
google/cloud/storage/client_options_test.cc

Fixes #13345
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13471)

feat(storage): support `UniverseDomainOption` for REST

---

google/cloud/bigtable/internal/data_connection_impl.cc
google/cloud/bigtable/internal/data_connection_impl_test.cc

Adapters would probably be easier to read, but I failed to figure it out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13470)

impl(bigtable): support bigtable cookie in async unary RPCs

---

google/cloud/bigtable/internal/mutate_rows_limiter.cc
google/cloud/bigtable/internal/mutate_rows_limiter_test.cc

Fixes #13487
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13488)

feat(bigtable): logging for bulk apply throttling

---

google/cloud/internal/minimal_iam_credentials_stub.cc
google/cloud/internal/minimal_iam_credentials_stub_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13498)

cleanup: no FQDN in IAM credentials stub

---

google/cloud/internal/oauth2_compute_engine_credentials.cc
google/cloud/internal/oauth2_compute_engine_credentials_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13497)

impl(universe_domain): use default GDU with older MDS versions

---

google/cloud/pubsub/internal/publisher_tracing_connection.cc
google/cloud/pubsub/internal/publisher_tracing_connection_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13510)

refactor(pubsub): split attributes into topic and project id on create span

---

google/cloud/pubsub/internal/tracing_batch_sink.cc
google/cloud/pubsub/internal/tracing_batch_sink_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13511)

refactor(pubsub): split attributes into topic and project id on publish span

---

generator/generator_config.textproto
google/cloud/storagecontrol/v2/.repo-metadata.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13513)

chore(storagecontrol): update metadata

---

google/cloud/compute/integration_tests/compute_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13523)

chore(compute): disable integration test until it can be fixed

---

google/cloud/grpc_error_delegate.cc
google/cloud/grpc_error_delegate_test.cc

Part of the work for #13514
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13521)

impl: extract `RetryInfo` from gRPC responses

---

google/cloud/pubsub/samples/CMakeLists.txt
google/cloud/pubsub/samples/pubsub_client_integration_samples.bzl
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/samples/topic_admin_samples.cc
google/cloud/pubsub/topic_admin_client.h

- remove old sample tags, but keep functions since they are used else where
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13525)

refactor(pubsub): add generated topic admin sample file

---

google/cloud/pubsub/samples/blocking_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13532)

cleanup(pubsub): use the generated admin api for the blocking sample

---

google/cloud/pubsub/samples/CMakeLists.txt
google/cloud/pubsub/samples/pubsub_client_integration_samples.bzl
google/cloud/pubsub/samples/pubsub_samples_common.h
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/samples/subscription_admin_samples.cc
google/cloud/pubsub/topic_admin_client.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13535)

refactor(pubsub): add generated admin subscription samples

---

google/cloud/internal/compute_engine_util.cc
google/cloud/internal/compute_engine_util_test.cc
google/cloud/internal/oauth2_compute_engine_credentials.cc
google/cloud/internal/oauth2_compute_engine_credentials_test.cc
google/cloud/internal/unified_rest_credentials_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13530)

impl(universe_domain): update implementation to reflect testing results

---

google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/samples/topic_admin_samples.cc
google/cloud/pubsub/topic_admin_client.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13527)

refactor(pubsub): move get topic, update topic, and list topic samples

---

google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/samples/topic_admin_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13553)

cleanup(pubsub): move detach subscription example

---

google/cloud/pubsub/samples/samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13555)

cleanup(pubsub): remove schema admin samples from the list

---

generator/internal/discovery_file_test.cc

more permanent fix than #13382
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13559)

test(generator): avoid fixed copyright year in tests

---

google/cloud/storage/async/connection.h
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl.h
google/cloud/storage/internal/async/connection_impl_test.cc
google/cloud/storage/internal/async/connection_tracing.cc
google/cloud/storage/internal/async/connection_tracing_test.cc
google/cloud/storage/mocks/mock_async_connection.h

Part of the work for #9130
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13564)

impl(GCS+gRPC): `AsyncConnection::RewriteObject`

---

.github/workflows/windows-bazel.yml
.github/workflows/windows-cmake.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13572)

chore: update msvc-dev-cmd action to 1.13.0

---

external/googleapis/renovate.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13573)

cleanup: simplify `renovate.sh` requirements

---

google/cloud/storage/async/client.h
google/cloud/storage/async/client_test.cc
google/cloud/storage/async/object_requests.h
google/cloud/storage/examples/storage_async_samples.cc
google/cloud/storage/tests/async_client_integration_test.cc

Add client-level functions to rewrite objects and to resume rewrites. Includes unit tests, integration tests, and examples.
Fixes #9130
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13567)

impl(GCS+gRPC): `AsyncClient::*Rewrite()`

---

google/cloud/storage/examples/storage_async_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13577)

impl(GCS+gRPC): fix async client sample

---

google/cloud/pubsub/samples/schema_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13578)

cleanup(pubsub): remove unused headers in sample

---

google/cloud/bigtable/internal/retry_context.cc
google/cloud/bigtable/internal/retry_context.h
google/cloud/bigtable/internal/retry_context_test.cc

Fixes #13569 
cc @mutianf
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13570)

impl(bigtable): add attempt header

---

google/cloud/storage/internal/grpc/stub_failures_test.cc

Mitigates #13114
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13584)

test(GCS+gRPC): deflake test with older gRPC

---

generator/internal/discovery_type_vertex.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13588)

impl(generator): do not use deprecated has_optional_keyword

---

google/cloud/pubsub/samples/subscription_admin_samples.cc

Closes https://github.com/googleapis/google-cloud-cpp/issues/13558
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13601)

cleanup(pubsub): add bigquery subscription to the ci

---

google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/samples/subscription_admin_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13589)

cleanup(pubsub): move the rest of the subscription admin apis

---

google/cloud/pubsub/samples/topic_admin_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13590)

cleanup(pubsub): add tags to topic admin samples

---

google/cloud/credentials.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13614)

docs(common): advertise OAuth2 library

---

docfx/doxygen2markdown.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13618)

cleanup(docfx): more consistent handling of `programlisting`

---

ci/cloudbuild/builds/lib/integration.sh

Part of the work for #13575
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13622)

ci: upgrade storage testbench to latest version

---

.github/workflows/test-runner.yml

Fixes #12512
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13629)

ci(gha): notify Google Chat on failures

---

ci/cloudbuild/triggers/clang-cxx20-ci.yaml
ci/cloudbuild/triggers/clang-cxx20-pr.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13630)

chore: save GCB trigger resources

---

.github/workflows/test-runner.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13634)

ci(gha): improve Google Chat message

---

.github/workflows/test-runner.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13638)

ci(gha): no notifications on PRs

---

ci/cloudbuild/cloudbuild.yaml

Mitigates #6438 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13639)

ci(gcb): make 2 kaniko attempts

---

google/cloud/storage/google_cloud_cpp_storage.bzl
google/cloud/storage/google_cloud_cpp_storage.cmake
google/cloud/storage/internal/well_known_parameters_impl.h
google/cloud/storage/well_known_parameters.h

Part of the work for #13575
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13637)

refactor(storage): split `WellKnownParameter`

---

release/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13645)

docs: update broken link

---

google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscription_admin_client.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13636)

cleanup(pubsub): remove bigquery sample

---

google/cloud/pubsub/samples/samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13591)

cleanup(pubsub): remove create topic using handwritten api

---

google/cloud/bigquery/v2/minimal/internal/job_request.cc
google/cloud/bigquery/v2/minimal/internal/job_request_test.cc
google/cloud/bigquery/v2/minimal/internal/project_response.cc
google/cloud/bigquery/v2/minimal/internal/project_response_test.cc
google/cloud/bigquery/v2/minimal/internal/table_response.cc
google/cloud/bigquery/v2/minimal/internal/table_response_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13665)

feat(bigquery): remove validation of input and output parameters

---

generator/integration_tests/tests/request_id_connection_impl_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13685)

test(generator): improve request id tests

---

google/cloud/storage/internal/async/connection_impl.cc

I missed a few manual retry loops still using implicit options.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13686)

cleanup(GCS+gRPC): use explicit options in retry loops

---

google/cloud/spanner/database_admin_connection.cc
google/cloud/spanner/instance_admin_connection.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13692)

cleanup(spanner): explicit options in legacy LROs

---

google/cloud/bigquery/v2/minimal/internal/dataset_rest_connection_impl.cc
google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.cc
google/cloud/bigquery/v2/minimal/internal/project_rest_connection_impl.cc
google/cloud/bigquery/v2/minimal/internal/table_rest_connection_impl.cc

Part of the work #12359
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13700)

cleanup(bigquery): explicit options in `RestRetryLoop`

---

.github/workflows/macos-bazel.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13703)

ci: switch macos bazel to large runner

---

google/cloud/internal/rest_retry_loop.h
google/cloud/internal/rest_retry_loop_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13694)

cleanup: remove unused `RestRetryLoop`

---

google/cloud/internal/async_retry_loop.h
google/cloud/internal/async_retry_loop_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13706)

cleanup: remove unused `AsyncRetryLoop`

---

.github/workflows/macos-bazel.yml

Reverts googleapis/google-cloud-cpp#13703
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13712)

Revert "ci: switch macos bazel to large runner"

---

.github/workflows/macos-bazel.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13727)

ci: switch macos-bazel to large with updated run command

---

google/cloud/pubsub/integration_tests/subscriber_integration_test.cc

Part of #12987
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13701)

cleanup(pubsub): move sub admin to generated in integration test

---

google/cloud/pubsub/samples/samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13732)

cleanup(pubsub): remove the handwritten subscription admin client from samples.cc

---

google/cloud/storage/internal/well_known_parameters_impl.h

Motivated by #12116
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13737)

impl(storage): const-qualify `WellKnownParameters::value_or`

---

ci/cloudbuild/build.sh
ci/cloudbuild/builds/generate-libraries.sh
ci/cloudbuild/cloudbuild.yaml
generator/discovery/update_discovery_doc.sh

part of the work for #11737
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13733)

chore: add script to help automate discovery document updating

---

google/cloud/spanner/samples/samples.cc

Allows customers to automatically scale up/down their instance based on user-specified utilization targets and resource usage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13740)

feat(spanner): add sample for instance-admin managed autoscaler

---

google/cloud/storage/internal/grpc/object_request_parser.cc
google/cloud/storage/internal/grpc/object_request_parser_test.cc
google/cloud/storage/tests/object_integration_test.cc

Part of the work for #13561
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13754)

feat(GCS+gRPC): support listing folders as prefixes

---

google/cloud/spanner/client.cc

If the service returned a `google.rpc.RetryInfo.retry_delay` in the failing operation that caused `Commit()` to re-run the transaction, use its value instead of the delay provided by the backoff policy.
Not tested as we do not (yet) have a mechanism to inject/mock the "sleeper" behavior in the re-run loop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13761)

impl(spanner): heed any google.rpc.RetryInfo in transaction re-run loop

---

generator/internal/codegen_utils.cc
generator/internal/codegen_utils.h
generator/internal/discovery_file.cc
generator/internal/discovery_proto_export_file.cc
generator/internal/scaffold_generator.cc
generator/internal/scaffold_generator.h
generator/internal/scaffold_generator_test.cc

Fixes #12818.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13762)

refactor(generator): unify multiple definitions of MakeDirectory()

---

ci/install-cloud-sdk.sh
google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc
google/cloud/spanner/ci/lib/spanner_emulator.sh
google/cloud/spanner/integration_tests/client_integration_test.cc

Updating to get the pub/sub changes. You can find the SHA here https://cloud.google.com/sdk/docs/install-sdk#linux for future updates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13764)

chore: update gcloud version

---

google/cloud/storage/google_cloud_cpp_storage.cmake
google/cloud/storage/internal/async/writer_connection_impl_test.cc
google/cloud/storage/storage_client_testing.bzl
google/cloud/storage/testing/mock_hash_function.h

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13780)

refactor(storage): split `MockHashFunction`

---

google/cloud/bigtable/internal/defaults.cc
google/cloud/bigtable/internal/defaults_test.cc

Part of the work for #13122
See #13781 for the main changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13782)

impl(bigtable): respect GOOGLE_CLOUD_UNIVERSE_DOMAIN

---

google/cloud/storage/client_options.cc
google/cloud/storage/client_options_test.cc
google/cloud/storage/internal/grpc/stub_test.cc

Part of the work for #13122
See #13781 for the main changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13783)

impl(storage): respect GOOGLE_CLOUD_UNIVERSE_DOMAIN

---

google/cloud/storage/tests/object_compose_many_integration_test.cc
google/cloud/storage/tests/object_integration_test.cc
google/cloud/storage/tests/object_list_objects_versions_integration_test.cc
google/cloud/storage/tests/object_plenty_clients_serially_integration_test.cc
google/cloud/storage/tests/object_plenty_clients_simultaneously_integration_test.cc
google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc

Motivated by #13786
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13787)

cleanup(storage): remove unused system headers

---

google/cloud/storage/google_cloud_cpp_storage.cmake
google/cloud/storage/internal/async/reader_connection_resume_test.cc
google/cloud/storage/storage_client_testing.bzl
google/cloud/storage/testing/mock_resume_policy.h

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13789)

refactor(GCS+gRPC): split `MockResumePolicy`

---

google/cloud/storage/internal/hash_function_impl.cc
google/cloud/storage/internal/hash_function_impl.h
google/cloud/storage/internal/hash_function_impl_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13790)

impl(storage): decorate hash functions for downloads

---

google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl_test.cc
google/cloud/storage/internal/async/reader_connection_impl.cc
google/cloud/storage/internal/async/reader_connection_impl.h
google/cloud/storage/internal/async/reader_connection_impl_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13791)

impl(GCS+gRPC): validate per-message checksums

---

google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl_test.cc

Fixes #13453
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13801)

impl(GCS+gRPC): set timeouts on async downloads

---

google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl_test.cc

Part of the work for #13452
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13804)

impl(GCS+gRPC): use timeouts in async `InsertObject`

---

google/cloud/google_cloud_cpp_grpc_utils.bzl
google/cloud/google_cloud_cpp_grpc_utils.cmake
google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
google/cloud/internal/async_read_write_stream_timeout.h
google/cloud/internal/async_read_write_stream_timeout_test.cc

Part of the work for #13452
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13805)

impl(common): timeout decorator for R/W streaming

---

ci/cloudbuild/builds/generate-libraries.sh
generator/discovery/update_discovery_doc.sh

part of the work for #11737
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13800)

chore(compute): handle new resources when updating compute discovery doc

---

google/cloud/storage/internal/async/connection_impl_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13806)

fix(GCS+gRPC): test compilation with MSVC

---

google/cloud/storage/CMakeLists.txt
google/cloud/storage/quickstart/BUILD.bazel
google/cloud/storage/quickstart/CMakeLists.txt
google/cloud/storage/quickstart/Makefile
google/cloud/storage/quickstart/quickstart_async.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13809)

docs(GCS+gRPC): quickstart for `AsyncClient`

---

google/cloud/pubsub/samples/topic_admin_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13811)

cleanup(pubsub): fix kinesis tags

---

google/cloud/storage/tests/bucket_integration_test.cc
google/cloud/storage/tests/grpc_notification_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13816)

test(GCS+gRPC): enable more integration tests

---

google/cloud/compute/instance_group_manager_resize_requests/v1/samples/instance_group_manager_resize_requests_client_samples.cc
google/cloud/compute/storage_pools/v1/samples/storage_pools_client_samples.cc

Just two changes to the generator at the same time, happens from time to time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13821)

fix(compute): regenerate samples

---

google/cloud/storage/internal/make_jwt_assertion.cc
google/cloud/storage/internal/openssl_util.cc
google/cloud/storage/internal/openssl_util.h
google/cloud/storage/oauth2/service_account_credentials.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13825)

refactor(storage): de-duplicate `SignWithPem()`

---

google/cloud/storage/tests/error_parsing_integration_test.cc
google/cloud/storage/tests/object_insert_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13828)

cleanup(storage): remove stale TODO comment

---

generator/discovery/update_discovery_doc.sh

Process git ls-files output into suggested edits for the service_dirs.cmake file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13822)

chore(compute): emit suggested service dir updates

---

docfx/README.md
docfx/doxygen2yaml.cc
docfx/doxygen2yaml_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13852)

feat(docfx): support Doxygen 1.9.7 output

---

google/cloud/pubsub/internal/batch_callback.h
google/cloud/pubsub/internal/batch_callback_wrapper.h
google/cloud/pubsub/internal/default_batch_callback.h
google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
google/cloud/pubsub/internal/tracing_batch_callback.cc
google/cloud/pubsub/internal/tracing_batch_callback_test.cc
google/cloud/pubsub/testing/mock_batch_callback.h

Part of https://github.com/googleapis/google-cloud-cpp/issues/13720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13854)

impl(pubsub): add events to batch callback api

---

ci/cloudbuild/dockerfiles/centos-7.Dockerfile
google/cloud/pubsub/internal/message_propagator.cc
google/cloud/pubsub/internal/message_propagator.h
google/cloud/pubsub/internal/message_propagator_test.cc
google/cloud/pubsub/internal/subscriber_tracing_connection.cc
google/cloud/pubsub/internal/subscriber_tracing_connection_test.cc
google/cloud/pubsub/internal/tracing_batch_callback.cc
google/cloud/pubsub/internal/tracing_batch_callback_test.cc
google/cloud/pubsub/internal/tracing_batch_sink.cc
google/cloud/pubsub/internal/tracing_helpers.cc
google/cloud/pubsub/internal/tracing_helpers.h
google/cloud/pubsub/internal/tracing_pull_ack_handler.cc
google/cloud/pubsub/internal/tracing_pull_lease_manager.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13867)

cleanup(pubsub): make otel headers system headers

---

google/cloud/spanner/ci/lib/spanner_emulator.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13872)

ci(spanner): highlight successful emulator starts with color

---

google/cloud/storagecontrol/quickstart/quickstart.cc

Fixes #13871
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13874)

docs(storagecontrol): region tags for quickstart

---

google/cloud/pubsub/internal/tracing_batch_callback.cc
google/cloud/pubsub/internal/tracing_batch_callback_test.cc

https://github.com/googleapis/google-cloud-cpp/issues/13720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13866)

impl(pubsub): add span attributes to subscribe span

---

ci/cloudbuild/builds/check-api.sh

Part of the work for #13875
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13876)

ci: prepare for `storage_grpc` as GA

---

google/cloud/spanner/mutations_test.cc
google/cloud/spanner/row_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13880)

test(spanner): add mutations/row unit tests for FLOAT32

---

google/cloud/spanner/BUILD.bazel
google/cloud/spanner/integration_tests/data_types_integration_test.cc
google/cloud/spanner/testing/database_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13882)

test(spanner): add integration tests for FLOAT32

---

google/cloud/storage/google_cloud_cpp_storage_grpc.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13884)

cleanup(GCS+gRPC): trim dependencies

---

google/cloud/pubsub/samples/pubsub_samples_common.cc
google/cloud/pubsub/samples/pubsub_samples_common.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13886)

cleanup(pubsub): add missing includes

---

google/cloud/storage/google_cloud_cpp_storage_grpc.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13887)

fix(GCS+gRPC): I said > 23.x I mean >= 23

---

google/cloud/pubsub/internal/tracing_batch_callback.cc
google/cloud/pubsub/internal/tracing_batch_callback_test.cc

[#13720](https://github.com/googleapis/google-cloud-cpp/issues/13720)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13889)

impl(pubsub): add exactly once delivery enabled attribute to subscribe span

---

ci/install-cloud-sdk.sh
google/cloud/spanner/integration_tests/client_integration_test.cc

Includes core/beta 2024.03.22, with bq 2.1.2, cbt 1.18.0,
and cloud-spanner-emulator 1.5.15.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13901)

chore(deps): update gcloud to 470.0.0

---

ci/cloudbuild/dockerfiles/demo-alpine-stable.Dockerfile
doc/packaging.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13904)

ci: upgrade demo-alpine builds

---

google/cloud/pubsub/integration_tests/subscriber_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13905)

impl(pubsub): add streaming pull integration test for otel

---

generator/internal/discovery_to_proto.h
generator/internal/discovery_to_proto_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13907)

cleanup(generator): remove default parameter and call with false in tests

---

google/cloud/pubsub/internal/batch_callback.h
google/cloud/pubsub/internal/batch_callback_wrapper.h
google/cloud/pubsub/internal/default_batch_callback.h
google/cloud/pubsub/internal/subscription_concurrency_control.cc
google/cloud/pubsub/internal/subscription_concurrency_control_test.cc
google/cloud/pubsub/internal/tracing_batch_callback.cc
google/cloud/pubsub/internal/tracing_batch_callback_test.cc
google/cloud/pubsub/testing/mock_batch_callback.h

[13721](https://github.com/googleapis/google-cloud-cpp/issues/13721)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13890)

impl(pubsub): add concurrency functions to callback

---

google/cloud/pubsub/internal/tracing_batch_callback.cc

https://github.com/googleapis/google-cloud-cpp/issues/13721
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13913)

cleanup(pubsub): make concurrency funcs public and remove scope

---

google/cloud/pubsub/internal/batch_callback.h
google/cloud/pubsub/internal/batch_callback_wrapper.h
google/cloud/pubsub/internal/default_batch_callback.h
google/cloud/pubsub/internal/subscription_message_queue.cc
google/cloud/pubsub/internal/subscription_message_queue_test.cc
google/cloud/pubsub/internal/tracing_batch_callback.cc
google/cloud/pubsub/internal/tracing_batch_callback_test.cc
google/cloud/pubsub/testing/mock_batch_callback.h

Closes [#13722](https://github.com/googleapis/google-cloud-cpp/issues/13722)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13914)

impl(pubsub): add scheduler span

---

generator/internal/codegen_utils.cc

Only add support for linux, since we only run the generator on linux (I think). Or at least logging on linux will be enough for debugging.
I think we will just have to make the directory as a one time thing, but this will give a good indicator if we ever want to add another service. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13918)

cleanup(generator): add logging if it was unable to create directory

---

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc

[#13726](https://github.com/googleapis/google-cloud-cpp/issues/13726)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13920)

impl(pubsub): add end modack event for exactly once

---

ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
doc/packaging.md

Silences #13921 although we may want to revert this change if the packaging is fixed upstream.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13923)

ci: build deps from source on openSUSE

---

google/cloud/opentelemetry/internal/time_series.cc
google/cloud/opentelemetry/internal/time_series.h
google/cloud/opentelemetry/internal/time_series_test.cc

I borrowed some of @coryan's code from because I liked the way it looked more than my code.
After this PR, we will be ready to put these `TimeSeries` into a `CreateTimeSeriesRequest`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13924)

impl(otel): convert `HistogramDataPoint` to protos

---

google/cloud/opentelemetry/internal/time_series_test.cc

See: https://github.com/googleapis/google-cloud-cpp/actions/runs/8565216527
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13930)

cleanup: text fixes on non-linux

---

google/cloud/common_options.h

Thanks to @devbww for noticing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13937)

docs(common): link to system parameters page

---

google/cloud/opentelemetry/internal/time_series_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13938)

test(otel): fix build on non-Linux

---

generator/internal/discovery_type_vertex.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13949)

cleanup(generator): add line for debugging

---

generator/internal/discovery_to_proto.cc
generator/internal/discovery_to_proto_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13948)

impl(generator): add any to recognized types

---

google/cloud/pubsub/internal/subscription_session_test.cc
google/cloud/pubsub/internal/tracing_exactly_once_ack_handler.cc

Close https://github.com/googleapis/google-cloud-cpp/issues/13953
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13954)

fix(pubsub): fix flakey test by checking for at least N acks

---

.github/workflows/external-account-integration.yml
.github/workflows/macos-cmake.yml
.github/workflows/windows-cmake.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13964)

ci(gha): fix CMake builds

---

.github/workflows/macos-cmake.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13966)

ci(gha): cleaner script for macOS

---

google/cloud/storage/async/bucket_name.cc
google/cloud/storage/async/bucket_name.h
google/cloud/storage/async/bucket_name_test.cc
google/cloud/storage/google_cloud_cpp_storage_grpc.bzl
google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
google/cloud/storage/storage_client_grpc_unit_tests.bzl

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13967)

impl(GCS+gRPC): new class for bucket names

---

generator/internal/discovery_type_vertex.cc
generator/internal/discovery_type_vertex_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13963)

impl(generator): map any type to any proto

---

generator/internal/discovery_type_vertex.cc
generator/internal/discovery_type_vertex.h
generator/internal/discovery_type_vertex_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13962)

impl(generator): handle bigquery map type

---

google/cloud/opentelemetry/monitoring_exporter.cc

Part of the work for #13869
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13984)

cleanup(otel): respect noexcept in GCM exporter

---

google/cloud/storage/async/client.cc
google/cloud/storage/async/client.h
google/cloud/storage/async/client_test.cc
google/cloud/storage/async/connection.h
google/cloud/storage/async/object_requests.h
google/cloud/storage/benchmarks/async_throughput_benchmark.cc
google/cloud/storage/examples/storage_async_mock_samples.cc
google/cloud/storage/examples/storage_async_samples.cc
google/cloud/storage/examples/storage_otel_samples.cc
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl_test.cc
google/cloud/storage/tests/async_client_integration_test.cc
google/cloud/storage/tests/smoke_test_async.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13978)

cleanup(GCS+gRPC): protos for AsyncDeleteObject()

---

google/cloud/storage/async/client.cc
google/cloud/storage/async/client.h
google/cloud/storage/async/client_test.cc
google/cloud/storage/examples/storage_async_samples.cc
google/cloud/storage/tests/async_client_integration_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13985)

cleanup(GCS+gRPC): remove redundant overload

---

google/cloud/pubsub/internal/tracing_batch_callback.cc

Remove some unnecessary code. Then reduce nesting, because we can.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13976)

cleanup(pubsub): lock_guard; early returns

---

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_metadata_decorator.cc
generator/integration_tests/tests/golden_kitchen_sink_rest_metadata_decorator_test.cc
generator/integration_tests/tests/golden_thing_admin_rest_metadata_decorator_test.cc
generator/internal/metadata_decorator_rest_generator.cc

fixes #13979
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13980)

impl(generator): support api_version metadata for REST

---

google/cloud/storage/async/client.cc
google/cloud/storage/async/client.h
google/cloud/storage/async/client_test.cc
google/cloud/storage/async/connection.h
google/cloud/storage/async/object_requests.h
google/cloud/storage/examples/storage_async_samples.cc
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl.h
google/cloud/storage/internal/async/connection_impl_test.cc
google/cloud/storage/internal/async/connection_tracing.cc
google/cloud/storage/internal/async/connection_tracing_test.cc
google/cloud/storage/mocks/mock_async_connection.h
google/cloud/storage/tests/async_client_integration_test.cc

Part of the work for #13910 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13986)

cleanup(GCS+gRPC): protos for ComposeObject()

---

google/cloud/storage/async/client.h

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14001)

docs(GCS+gRPC): refactor AsyncClient comments

---

google/cloud/storage/async/options.h
google/cloud/storage/google_cloud_cpp_storage_grpc.bzl
google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
google/cloud/storage/internal/async/default_options.cc
google/cloud/storage/internal/async/default_options_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14002)

feat(GCS+gRPC): checksum options

---

google/cloud/storagecontrol/BUILD.bazel
google/cloud/storagecontrol/quickstart/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14004)

cleanup(storagecontrol): update dependencies

---

google/cloud/storage/internal/async/connection_impl_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14009)

test(GCS+gRPC): fix MSVC build

---

google/cloud/spanner/internal/connection_impl_test.cc

Always(*) create test transactions within the lifetime of the connection that uses them so that those transactions will not hold references to any sessions allocated from the test connection's pool when the pool is destroyed.  This will make a difference after an upcoming change to verify the final state of the test session pool.
(*) Note that there is one test, TransactionOutlivesConnection, where we explicitly do the opposite to check that having an associated session outside the pool after its destruction does not have any ill effects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14007)

test(spanner): scope transactions within connections

---

.github/workflows/windows-cmake.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14010)

ci(gha): retry CMake install via choco

---

cmake/GoogleCloudCppFeatures.cmake
google/cloud/storage/config-grpc.cmake.in
google/cloud/storage/google_cloud_cpp_storage_grpc.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13969)

impl(GCS+gRPC): always require OpenTelemetry

---

google/cloud/pubsub/internal/tracing_exactly_once_ack_handler.cc
google/cloud/pubsub/internal/tracing_exactly_once_ack_handler_test.cc

Closes https://github.com/googleapis/google-cloud-cpp/issues/13726
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13965)

impl(pubsub): add links btwn ack/nack and subscribe span

---

release/changes.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14024)

chore: note the googleapis commit date/time in the draft changelog

---

google/cloud/storage/async/client.cc
google/cloud/storage/async/client.h
google/cloud/storage/async/client_test.cc
google/cloud/storage/examples/storage_async_samples.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14016)

impl(GCS+gRPC): client functions to resume uploads

---

generator/discovery/update_discovery_doc.sh

part of the work for #11737 
Script now updates the service_dirs.cmake file.
Script now prints out copy/paste `rest_services` block for each new service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13941)

impl(generator): improve discovery update script

---

google/cloud/storage/async/client.cc
google/cloud/storage/async/client.h
google/cloud/storage/async/client_test.cc
google/cloud/storage/async/connection.h
google/cloud/storage/benchmarks/async_throughput_benchmark.cc
google/cloud/storage/examples/storage_async_samples.cc
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl_upload_hash_test.cc
google/cloud/storage/internal/async/connection_impl_upload_test.cc
google/cloud/storage/tests/async_client_integration_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14027)

impl(GCS+gRPC): use protos for resumable uploads

---

google/cloud/storage/async/client_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14031)

fix(GCS+gRPC): MSVC build problems

---

generator/discovery/update_discovery_doc.sh

Search for the place to add a new service directory rather than assuming an absolute line number.
Fixes #13972.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14030)

chore(compute): a more robust method to update service_dirs.cmake

---

google/cloud/storage/async/client_test.cc
google/cloud/storage/async/object_responses.h
google/cloud/storage/internal/async/accumulate_read_object.cc
google/cloud/storage/internal/async/accumulate_read_object.h
google/cloud/storage/internal/async/accumulate_read_object_test.cc
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/read_payload_impl_test.cc
google/cloud/storage/internal/async/reader_connection_impl.cc
google/cloud/storage/internal/async/reader_connection_impl_test.cc
google/cloud/storage/internal/async/reader_connection_resume_test.cc
google/cloud/storage/quickstart/quickstart_async.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14033)

cleanup(GCS+gRPC): return protos from `Read*()`

---

google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl_read_hash_test.cc
google/cloud/storage/internal/async/connection_impl_upload_hash_test.cc
google/cloud/storage/storage_client_grpc_unit_tests.bzl

Fixes #13910
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14037)

impl(GCS+gRPC): fix pre-computed hashes support

---

google/cloud/storagecontrol/README.md
google/cloud/storagecontrol/quickstart/quickstart.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14044)

docs(storagecontrol): use `GetStorageLayout()` for quickstart

---

.github/workflows/windows-cmake.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14053)

ci: try avoiding windows-cmake errors

---

generator/standalone_main.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14056)

impl(generator): improve error messaging

---

generator/internal/discovery_resource.cc
generator/internal/discovery_resource_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14057)

impl(generator): handle periods in the parameter name

---

google/cloud/pubsub/internal/tracing_pull_lease_manager.cc
google/cloud/pubsub/internal/tracing_pull_lease_manager_test.cc

Part of https://github.com/googleapis/google-cloud-cpp/issues/14020
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14055)

impl(pubsub): make the modack a root span

---

google/cloud/internal/grpc_request_metadata.cc

https://github.com/googleapis/google-cloud-cpp/issues/13724
Splits GetRequestMetadataFromContext into AddContextMetadata and AddServerRequestMetadata.
AddContextMetadata gets metadata from the ClientContext and AddServerRequestMetadata gets the metadata from the intial/trailing server metadata calls from ClientContext
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14062)

refactor(internal): refactor GetRequestMetadataFromContext into 2 functions

---

ci/cloudbuild/cloudbuild.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14069)

ci(gcb): remove more hard-coded stuff

---

ci/cloudbuild/build.sh

We sometimes need to manually launch builds on GCB. This makes it easier
to pick a different project, or different worker pool.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14072)

ci(gcb): more flexible manual builds on GCB

---

ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
ci/generate-markdown/generate-packaging.sh
doc/packaging.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14079)

ci: upgrade `demo-install` to Fedora:40

---

ci/cloudbuild/triggers/demo-ubuntu-24-04-ci.yaml
ci/cloudbuild/triggers/demo-ubuntu-24-04-pr.yaml

Fixes #14075
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14083)

chore: save demo-ubuntu-24-04* triggers

---

google/cloud/spanner/interval.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14102)

cleanup(spanner): add missing chrono include

---

google/cloud/bigtable/internal/async_row_sampler.cc
google/cloud/bigtable/internal/async_row_sampler_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14106)

impl(bigtable): add origin client metadata to cancelled

---

google/cloud/storage/grpc_plugin.h
google/cloud/storage/internal/async/default_options.cc
google/cloud/storage/internal/grpc/default_options.cc
google/cloud/storage/internal/grpc/default_options_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14094)

impl(GCS+gRPC): new options for gRPC metrics

---

google/cloud/opentelemetry/integration_tests/CMakeLists.txt
google/cloud/opentelemetry/integration_tests/monitoring_exporter_integration_test.cc
google/cloud/opentelemetry/integration_tests/tests.bzl

Part of the work for #14047
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14097)

test(otel): add GCM exporter integration test

---

google/cloud/opentelemetry/internal/time_series.cc
google/cloud/opentelemetry/internal/time_series.h
google/cloud/opentelemetry/internal/time_series_test.cc
google/cloud/opentelemetry/monitoring_exporter.cc
google/cloud/opentelemetry/monitoring_exporter.h
google/cloud/opentelemetry/monitoring_exporter_test.cc

Part of the work for #14074
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14113)

impl(otel): GCM exporter custom metric prefix

---

google/cloud/bigtable/internal/async_row_reader.cc
google/cloud/bigtable/internal/async_row_reader_test.cc
google/cloud/bigtable/internal/default_row_reader.cc
google/cloud/bigtable/internal/default_row_reader_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14131)

impl(bigtable): add client metadata to cancelled status

---

google/cloud/bigtable/internal/row_reader_impl.h
google/cloud/pubsub/internal/default_batch_sink.h
google/cloud/pubsub/internal/noop_message_callback.h
google/cloud/pubsub/internal/sequential_batch_sink.h
google/cloud/pubsublite/internal/publisher_connection_impl.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14140)

cleanup: remove unnecessary trailing semi colon

---

doc/contributor/howto-guide-find-missing-service-protos.md
doc/contributor/howto-guide-update-googleapis-sha.md

Fixes #14109
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14139)

docs: howto find missing service protos

---

ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14141)

ci: upgrade `msan` to Fedora:40

---

ci/cloudbuild/dockerfiles/fedora-latest-bazel.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14147)

ci: upgrade `bazel` to Fedora:40

---

google/cloud/internal/curl_handle_factory.cc

#14076
Handle the void cast extra
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14161)

cleanup: prepare for clang-tidy 18

---

google/cloud/internal/oauth2_compute_engine_credentials.cc
google/cloud/internal/oauth2_compute_engine_credentials.h
google/cloud/internal/oauth2_compute_engine_credentials_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14150)

impl(oauth2): retrieve project id from MDS

---

cmake/GoogleCloudCppDoxygen.cmake
google/cloud/storage/google_cloud_cpp_storage_grpc.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14180)

cleanup(cmake): fewer uninformative messages

---

cmake/GoogleCloudCppDoxygen.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14181)

ci: more informative Doxygen runs

---

google/cloud/spanner/internal/connection_impl.cc
google/cloud/spanner/internal/merge_chunk.cc
google/cloud/spanner/internal/partial_result_set_source.cc
google/cloud/spanner/internal/session_pool.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14190)

cleanup(spanner): use Status factory functions in spanner/internal

---

ci/cloudbuild/builds/clang-cxx20.sh
ci/cloudbuild/builds/cxx20.sh
ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14145)

ci: upgrade `cxx20` to Fedora:40

---

google/cloud/internal/async_connection_ready.cc
google/cloud/internal/async_read_write_stream_auth.h
google/cloud/internal/async_streaming_read_rpc_auth.h
google/cloud/internal/async_streaming_write_rpc_auth.h
google/cloud/internal/oauth2_credentials.cc
google/cloud/internal/openssl/parse_service_account_p12_file.cc

#14107
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14191)

cleanup: use Status factory functions in internal

---

google/cloud/spanner/testing/cleanup_stale_instances.cc
google/cloud/spanner/testing/pick_random_instance.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14197)

cleanup(spanner): use Status factory functions in spanner/testing

---

google/cloud/spanner/client.cc
google/cloud/spanner/query_partition.cc
google/cloud/spanner/read_partition.cc
google/cloud/spanner/row.cc
google/cloud/spanner/row.h
google/cloud/spanner/value.cc
google/cloud/spanner/value.h

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14193)

cleanup(spanner): use Status factory functions in spanner

---

google/cloud/bigtable/wait_for_consistency.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14199)

cleanup(bigtable): use Status factory functions

---

google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14201)

cleanup(bigquery): use Status factory functions

---

google/cloud/internal/openssl/parse_service_account_p12_file.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14200)

cleanup: use Status factory functions

---

google/cloud/pubsub/benchmarks/endurance.cc
google/cloud/pubsub/benchmarks/throughput.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14208)

cleanup(pubsub): use `Status` factory functions

---

generator/internal/make_generators.cc

A simplification I will want for #14108
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14212)

refactor(generator): map lookups

---

google/cloud/pubsublite/endpoint.cc
google/cloud/pubsublite/internal/cloud_region.cc
google/cloud/pubsublite/internal/cloud_zone.cc
google/cloud/pubsublite/internal/default_publish_message_transformer.cc
google/cloud/pubsublite/internal/default_publish_message_transformer_test.cc
google/cloud/pubsublite/internal/location.cc
google/cloud/pubsublite/internal/location_test.cc
google/cloud/pubsublite/internal/multipartition_publisher.cc
google/cloud/pubsublite/internal/multipartition_publisher_test.cc
google/cloud/pubsublite/internal/partition_publisher.cc
google/cloud/pubsublite/internal/partition_publisher_test.cc
google/cloud/pubsublite/internal/service_composite.h
google/cloud/pubsublite/internal/service_composite_test.cc
google/cloud/pubsublite/message_metadata.cc
google/cloud/pubsublite/message_metadata_test.cc
google/cloud/pubsublite/publisher_connection.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14209)

cleanup(pubsublite): use `Status` factory functions

---

google/cloud/kms_key_name.cc
google/cloud/location.cc
google/cloud/project.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14217)

cleanup: use `Status` factory functions

---

google/cloud/storage/BUILD.bazel
google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
google/cloud/storage/internal/grpc/monitoring_project.cc
google/cloud/storage/internal/grpc/monitoring_project.h
google/cloud/storage/internal/grpc/monitoring_project_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14219)

impl(GCS+gRPC): monitoring project from OTel resource

---

google/cloud/bigtable/benchmarks/benchmark_options.cc

#14107
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14231)

cleanup(bigtable): use `Status` factory functions

---

google/cloud/internal/grpc_opentelemetry.cc
google/cloud/internal/grpc_opentelemetry.h
google/cloud/internal/grpc_opentelemetry_test.cc

Closes #13724
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14230)

impl: skip crashing call to grpc for client-originated errors

---

ci/cloudbuild/builds/clang-tidy-compute.sh

#14076
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14237)

ci: support Fedora:40 cmake upgrade

---

ci/cloudbuild/builds/development.sh
ci/cloudbuild/builds/publish-docs.sh

Part of the work for #14076
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14239)

ci: update more clang build scripts

---

ci/cloudbuild/dockerfiles/centos-7.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile
ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile
cmake/FindgRPC.cmake

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14241)

ci: compile gRPC with OTel plugin

---

google/cloud/internal/grpc_opentelemetry_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14243)

cleanup: some test expectations

---

ci/verify_current_targets/.bazelrc
google/cloud/storage/BUILD.bazel
google/cloud/storage/internal/grpc/metrics_exporter_options.cc
google/cloud/storage/internal/grpc/metrics_exporter_options.h
google/cloud/storage/internal/grpc/metrics_exporter_options_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14238)

impl(GCS+gRPC): more options for metrics exporter

---

google/cloud/storage/internal/grpc/default_options.cc
google/cloud/storage/internal/grpc/default_options_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14246)

impl(GCS+gRPC): disable gRPC metrics for testbench

---

google/cloud/storage/BUILD.bazel

Part of the changes for #13998
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14244)

impl(GCS+gRPC): always require gRPC OTel plugin

---

google/cloud/storage/BUILD.bazel
google/cloud/storage/google_cloud_cpp_storage_grpc.cmake

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14251)

impl(GCS+gRPC): build tweaks for gRPC OTel plugin

---

generator/internal/scaffold_generator.cc
google/cloud/publicca/README.md
google/cloud/publicca/doc/main.dox

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14258)

impl: add newline to README to separate link definitions from bulleted list

---

google/cloud/storage/internal/grpc/metrics_meter_provider_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14263)

test(GCS+gRPC): deflake meter provider test

---

google/cloud/storage/internal/grpc/default_options.cc
google/cloud/storage/internal/grpc/default_options.h
google/cloud/storage/internal/grpc/default_options_test.cc

Thanks to @devbww for the review.
Part of the work for #13998 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14267)

fix(GCS+gRPC): correct handling of gRPC versions

---

google/cloud/internal/oauth2_compute_engine_credentials.cc

Fixes #13436
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14268)

refactor: oauth2 gce creds json lookups

---

google/cloud/internal/oauth2_compute_engine_credentials.cc
google/cloud/internal/oauth2_compute_engine_credentials_test.cc

We've been asked to delay this change until some point in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14276)

impl: revert update ud request path

---

ci/cloudbuild/builds/check-api.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14273)

ci: fewer check-api false positives on templates

---

cmake/FindgRPC.cmake
google/cloud/storage/google_cloud_cpp_storage_grpc.cmake

Fixes #14260
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14294)

cleanup(GCS+gRPC): remove gRPC OTel plugin workarounds

---

google/cloud/networkservices/README.md
google/cloud/networkservices/doc/main.dox

fixes #14322
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14326)

docs(networkservices): update documentation links

---

ci/cloudbuild/dockerfiles/ubuntu-24.04.Dockerfile
ci/cloudbuild/triggers/quickstart-bazel-ci.yaml
ci/cloudbuild/triggers/quickstart-bazel-pr.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14327)

ci: upgrade quickstart bazel build

---

cmake/GoogleCloudCppFeatures.cmake
google/cloud/storagecontrol/quickstart/CMakeLists.txt
libraries.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14347)

cleanup(storagecontrol): bake period is over

---

ci/cloudbuild/builds/publish-docs.sh
ci/cloudbuild/dockerfiles/fedora-latest-publish-docs.Dockerfile

Fixes #14207
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14357)

chore: `publish-docs` to Fedora:40

---

google/cloud/storage/internal/grpc/metrics_exporter_impl.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14369)

fix(GCS+gRPC): correct gRPC OTel plugin config

---

google/cloud/opentelemetry/doc/main.dox

:facepalm:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14374)

docs(otel): it's GA

---

google/cloud/storage/internal/grpc/metrics_exporter_options.cc
google/cloud/storage/internal/grpc/metrics_exporter_options_test.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14376)

impl(GCS+gRPC): new monitored resource type

---

ci/cloudbuild/builds/publish-docs.sh

See: #14364
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14391)

cleanup: remove false alarm

---

google/cloud/internal/async_streaming_write_rpc_tracing.h
google/cloud/internal/async_streaming_write_rpc_tracing_test.cc

Part of the work for #14371, same PR as #14379
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14394)

fix(otel): async write stream tracing

---

google/cloud/internal/opentelemetry.cc
google/cloud/internal/opentelemetry_test.cc
google/cloud/testing_util/opentelemetry_matchers.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14414)

cleanup(otel): some renames

---

bazel/workspace0.bzl
ci/cloudbuild/dockerfiles/centos-7.Dockerfile
ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile
ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile
doc/packaging.md

Motivated by https://github.com/googleapis/google-cloud-cpp/issues/14411
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14415)

chore(deps): downgrade to gRPC 1.64.2

---

CMakeLists.txt
README.md
google/cloud/README.md
google/cloud/storage/google_cloud_cpp_storage.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14431)

docs: update minimum GCC version

---

google/cloud/internal/oauth2_universe_domain.h

Fixes #14438
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14439)

fix(common): `json_fwd.h` is not always available

---

CMakeLists.txt
MODULE.bazel

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14445)

ci: automatically update Bazel module version

---

bazel/googleapis.modules.patch

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14460)

cleanup: reduce indirect bzlmod dependencies

---

ci/gha/builds/lib/bazel.sh

See: #14462
Tested: https://github.com/googleapis/google-cloud-cpp/actions/runs/9880869472
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14463)

ci: disable `bzlmod` on Windows

---

CHANGELOG.md

Follow up to #14443
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14464)

doc: mocks link GoogleTest

---

google/cloud/bigquerycontrol/CMakeLists.txt
google/cloud/bigquerycontrol/integration_tests/BUILD.bazel
google/cloud/bigquerycontrol/integration_tests/CMakeLists.txt
google/cloud/bigquerycontrol/integration_tests/job_integration_test.cc

part of the work for #14456
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14457)

test(bigquerycontrol): add job integration tests

---

google/cloud/storage/internal/connection_impl.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14473)

fix(storage): reset backoff after partial write

---

external/googleapis/renovate.sh

Fixes #14454 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14474)

ci: support bzlmod in renovate.sh

---

bazel/workspace3.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14481)

ci: load indirect googletest deps with Bazel

---

google/cloud/spanner/value_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14482)

cleanup(spanner): fix missing IWYU

---

ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
doc/packaging.md

Fixes #13921
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14483)

ci: use system packages for openSUSE/Leap demo build

---

google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc
google/cloud/storage/tests/grpc_hmac_key_integration_test.cc
google/cloud/storage/tests/grpc_integration_test.cc
google/cloud/storage/tests/grpc_object_acl_integration_test.cc
google/cloud/storage/tests/grpc_object_media_integration_test.cc
google/cloud/storage/tests/grpc_object_metadata_integration_test.cc
google/cloud/storage/tests/grpc_service_account_integration_test.cc

Another round of cleanups on test initialization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14490)

cleanup(storage): simplify test initialization

---

google/cloud/common_options.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14504)

docs(common): fix doxygen directive

---

generator/internal/http_option_utils.cc
generator/internal/http_option_utils.h
generator/internal/http_option_utils_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14506)

cleanup(generator): remove unused fields

---

google/cloud/storage/tests/grpc_integration_test.cc
google/cloud/storage/tests/unified_credentials_integration_test.cc

The integration tests already run with gRPC and JSON because either
Bazel invokes them with the right environment variables, or the CMake
driver scripts do.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14521)

test(GCS+gRPC): no parametric gRPC tests

---

.github/workflows/test-runner.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14547)

ci: add debug step

---

.github/workflows/test-runner-untrusted.yml
.github/workflows/test-runner.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14550)

ci: more debugging

---

google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc
google/cloud/storage/benchmarks/aggregate_upload_throughput_benchmark.cc
google/cloud/storage/benchmarks/async_throughput_benchmark.cc
google/cloud/storage/benchmarks/benchmark_utils.cc
google/cloud/storage/benchmarks/create_dataset.cc
google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc
google/cloud/storage/benchmarks/storage_parallel_uploads_benchmark.cc
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
google/cloud/storage/benchmarks/throughput_options.cc
google/cloud/storage/examples/storage_client_mock_samples.cc
google/cloud/storage/internal/crc32c_test.cc
google/cloud/storage/internal/object_read_streambuf.cc
google/cloud/storage/internal/object_requests.cc
google/cloud/storage/internal/object_write_streambuf.cc
google/cloud/storage/internal/policy_document_request.cc
google/cloud/storage/internal/storage_stub_factory.cc
google/cloud/storage/oauth2/service_account_credentials_test.cc
google/cloud/storage/tests/async_client_integration_test.cc
google/cloud/storage/tests/grpc_hmac_key_integration_test.cc
google/cloud/storage/tests/object_basic_crud_integration_test.cc
google/cloud/storage/tests/object_media_integration_test.cc
google/cloud/storage/tests/object_resumable_write_integration_test.cc
google/cloud/storage/tests/service_account_integration_test.cc
google/cloud/storage/tests/signed_url_conformance_test.cc
google/cloud/storage/tests/thread_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14552)

cleanup(storage): fix MOAR IWYU warnings, take 4

---

google/cloud/storage/async/client.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14563)

cleanup(GCS+gRPC): remove unused private function

---

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_logging_decorator.cc
generator/integration_tests/tests/golden_kitchen_sink_logging_decorator_test.cc
generator/internal/logging_decorator_generator.cc
google/cloud/bigtable/internal/bigtable_logging_decorator.cc
google/cloud/internal/curl_wrappers.cc
google/cloud/internal/curl_wrappers_test.cc
google/cloud/storage/internal/storage_logging_decorator.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14565)

feat(generator): include request in async streaming RPC logs

---

generator/generator_config.proto
generator/generator_config.textproto
generator/integration_tests/golden_config.textproto
generator/internal/codegen_utils.cc
generator/internal/codegen_utils_test.cc
generator/internal/descriptor_utils.cc
generator/internal/service_code_generator.cc
generator/standalone_main.cc

Remove emitted_rpcs and emit the deprecated RPC by default.
#14353
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14571)

cleanup(generator): Remove emitted_rpcs

---

google/cloud/storage/tests/async_client_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14577)

test(GCS+gRPC): restore integration test assertion

---

google/cloud/storage/async/read_all.cc
google/cloud/storage/async/read_all.h
google/cloud/storage/async/read_all_test.cc
google/cloud/storage/examples/storage_async_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14584)

feat(GCS+gRPC): easier to use  overloads

---

google/cloud/storage/tests/async_client_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14581)

test(GCS+gRPC): add failure integration tests

---

google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580)

doc(bigquerycontrol): add job query sample

---

google/cloud/aiplatform/v1/mocks/mock_notebook_connection.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14610)

cleanup: regenerate libraries

---

google/cloud/storage/internal/grpc/metrics_exporter_impl.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14624)

feat(GCS+gRPC): add optional lb locality to otel metrics

---

release/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14630)

cleanup: save a manual vcpkg step

---

release/howto-update-conan-package.md

missing links, and remove mention of the late, great coryan.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14638)

cleanup: missing links in conan docs

---

doc/adr/2024-08-13-googleapis-sha-update-policy.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14639)

doc(adr): googleapis SHA update policy

---

bazel/workspace0.bzl
ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile
ci/cloudbuild/dockerfiles/gcc-oldest.Dockerfile
ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile
doc/packaging.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14652)

chore(deps): update gRPC to 1.65.5

---

generator/internal/scaffold_generator.cc

Fixes #14664
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14665)

cleanup: remove manual step from scaffolding

---

.typos.toml
ci/cloudbuild/dockerfiles/checkers.Dockerfile
google/cloud/bigtable/examples/data_filter_snippets.cc
google/cloud/bigtable/testing/random_names.cc
google/cloud/internal/invocation_id_generator_test.cc
google/cloud/internal/rest_request.h
google/cloud/pubsublite/internal/publisher_connection_impl_test.cc
google/cloud/storage/bucket_metadata_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14671)

chore: update typos to `1.24.1`

---

CODE_OF_CONDUCT.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14689)

doc: update code of conduct POC

---

.github/workflows/macos-bazel.yml
.github/workflows/macos-cmake.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14695)

ci: additional macos sharding

---

ci/cloudbuild/builds/integration-production.sh
ci/cloudbuild/builds/lib/integration.sh
google/cloud/generativelanguage/CMakeLists.txt
google/cloud/generativelanguage/samples/BUILD.bazel
google/cloud/generativelanguage/samples/CMakeLists.txt
google/cloud/generativelanguage/samples/samples.cc

Sample execution works manually, but I have been unsuccessful in configuring our CI environment with the necessary permissions to execute the samples in that environment.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14701)

doc(generativelanguage): add samples

---

google/cloud/bigquery/v2/minimal/internal/job_request.cc
google/cloud/bigquery/v2/minimal/internal/job_request.h
google/cloud/bigquery/v2/minimal/internal/job_request_test.cc
google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14699)
Adds the option to set [JobCreationMode](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query#JobCreationMode).

impl(bigquery): Added option to set JobCreationMode in QueryRequest

---

google/cloud/spanner/samples/graph_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14714)

chore(spanner): formatting and clang tidy fixes

---

ci/cloudbuild/builds/lib/universe_domain.sh
ci/cloudbuild/builds/universe-domain-demo.sh
ci/cloudbuild/cloudbuild.yaml
ci/cloudbuild/triggers/universe-domain-demo-ci.yaml
ci/cloudbuild/triggers/universe-domain-demo-pr.yaml
google/cloud/universe_domain/demo/kms.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14715)

ci: add universe-domain-demo build

---

ci/cloudbuild/dockerfiles/demo-alpine-stable.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14730)

chore: update Alpine Linux version

---

generator/internal/descriptor_utils.cc
generator/internal/descriptor_utils.h
generator/internal/descriptor_utils_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14727)

feat(mixin): add mixin support in descriptor utils

---

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc
google/cloud/spanner/integration_tests/backup_extra_integration_test.cc
google/cloud/spanner/samples/graph_samples.cc
google/cloud/spanner/testing/database_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14757)

ci(spanner): graph samples to use enterprise instances

---

google/cloud/internal/oauth2_compute_engine_credentials.cc
google/cloud/internal/oauth2_compute_engine_credentials_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14777)

cleanup(oauth2): change universe domain endpoint

---

google/cloud/storage/client_options.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14786)

docs(storage): better suggestion for deprecated API

---

google/cloud/storage/internal/unified_rest_credentials.cc

Fixes #14759
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14788)

cleanup(storage): add comment on why no API key support

---

ci/cloudbuild/builds/lib/universe_domain.sh
ci/cloudbuild/builds/universe-domain-demo.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14811)

ci: do not fail universe-domain-demo tests

---

generator/internal/stub_rest_generator.cc

Add missing mixin headers to rest stub headers.
This won't affect existing generated code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14808)

impl(mixin): add missing mixin headers to rest stub headers

---

bazel/workspace0.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14864)

build(bazel): update workspace file to work with protobuf v29

---

ci/cloudbuild/builds/lib/universe_domain.sh
ci/cloudbuild/cloudbuild.yaml
google/cloud/universe_domain/integration_tests/impersonation_tests.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14867)

ci: add IdToken integration tests for universe domain

---

bazel/gapic.bzl
google/cloud/bigquerycontrol/BUILD.bazel
google/cloud/sql/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14895)

bazel: update gapic.bzl to work with REST transport

---

google/cloud/gkeconnect/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14898)

impl(gkeconnect): only needs proto target

---

ci/cloudbuild/builds/lib/universe_domain.sh
ci/cloudbuild/cloudbuild.yaml
ci/cloudbuild/dockerfiles/fedora-latest-bazel.Dockerfile
google/cloud/universe_domain/integration_tests/impersonation_tests.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14878)

ci: add 3PI(workforce) to SA impersonation integration tests for universe domain

---

google/cloud/opentelemetry/internal/monitored_resource.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14900)

impl(otel): include algorithm header

---

MODULE.bazel
bazel/workspace0.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14921)

chore: update rules_cc to v0.0.17

---

.github/workflows/macos-cmake.yml
.github/workflows/windows-cmake.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14956)

ci(gha): update sccache version and windows destination dir

---

BUILD.bazel

Make bool_flag public, so user can set the flag from their projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14961)

fix: Make bool_flag public

---

cmake/GoogleCloudCppFeatures.cmake
google/cloud/bigquerycontrol/quickstart/BUILD.bazel
libraries.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14985)

chore(bigquerycontrol): upgrade bigquerycontrol from transitive to GA

---

google/cloud/doc/guac.dox

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14990)

doc: fix typo in doc link

---

release/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15032)

doc: update SHA512 of googleapis for vcpkg release

---

ci/cloudbuild/builds/universe-domain.sh

close #15021
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15034)

cleanup: re-enable kms demo tests in universe domain

---

MODULE.bazel
bazel/workspace0.bzl
ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile
ci/cloudbuild/dockerfiles/gcc-oldest.Dockerfile
ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile
doc/packaging.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15039)

chore: update abseil to 20250127.1

---

google/cloud/opentelemetry/quickstart/quickstart.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15065)

docs(storage): region tags for otel quickstart

---

google/cloud/storagebatchoperations/v1/storage_batch_operations_client.h

https://github.com/googleapis/googleapis/commit/9e4b973f05ca380bdb4514634ce54b9de0d50f84
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15075)

cleanup: StorageBatchOperations comment changes introduced by googleapis

---

google/cloud/credentials.h
google/cloud/internal/curl_handle_factory.cc
google/cloud/internal/curl_handle_factory.h
google/cloud/internal/curl_impl.cc
google/cloud/storage/tests/mtls_object_basic_crud_integration_test.cc
google/cloud/storage/tests/unified_credentials_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15068)

impl: add experimental ca store in memory

---

google/cloud/internal/curl_handle_factory.cc
google/cloud/internal/curl_handle_factory.h
google/cloud/rest_options.h
google/cloud/storage/tests/unified_credentials_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15088)

impl: add experimental support for providing an SSL_CTX_FUNCTION

---

.github/workflows/windows-cmake.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15091)

ci: split gha windows shard2

---

google/cloud/compute/service_dirs.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15098)

ci: format compute service dirs bzl

---

google/cloud/internal/ci/run_integration_tests_emulator_bazel.sh
google/cloud/internal/curl_impl.cc
google/cloud/internal/curl_impl.h
google/cloud/internal/curl_impl_test.cc
google/cloud/internal/curl_rest_client.cc
google/cloud/internal/curl_rest_client.h
google/cloud/internal/curl_rest_client_integration_test.cc
google/cloud/internal/curl_rest_client_test.cc

fixes #15096
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15100)

impl(rest): dedup and merge headers right before writing them to curl

---

google/cloud/BUILD.bazel
google/cloud/google_cloud_cpp_rest_internal.cmake
google/cloud/internal/curl_handle_factory.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15101)

build: leverage cmake and bazel to determine when to use OpenSSL API

---

generator/standalone_main.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15103)

impl(generator): remove unused variable

---

google/cloud/storage/internal/async/connection_impl_open_test.cc
google/cloud/storage/internal/async/object_descriptor_impl_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15128)

impl(storage): qualify grpc status codes for portability

---

ci/cloudbuild/builds/integration-production.sh
google/cloud/storagecontrol/v2/samples/storage_control_anywhere_cache_samples.cc
google/cloud/storagecontrol/v2/samples/storage_control_folder_samples.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15134)

samples(storagecontrol): add samples for anywhere cache

---

google/cloud/storage/examples/storage_bucket_soft_delete_samples.cc

Add tags related to the bucket soft delete samples,
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15154)

samples(storage): add the bucket soft delete related tags

---

google/cloud/aiplatform/samples/samples.cc

The life cycle of old model is expired, update it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15183)

fix: update model version in aiplatform samples

---

google/cloud/storage/internal/async/connection_impl.cc
google/cloud/storage/internal/async/connection_impl.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15160)

fix(storage): make sure to send append_object_spec when retrying

---

generator/generator_config.textproto
google/cloud/pubsub/admin/internal/subscription_admin_option_defaults.cc
google/cloud/pubsub/admin/internal/subscription_admin_option_defaults.h
google/cloud/pubsub/admin/internal/topic_admin_option_defaults.cc
google/cloud/pubsub/admin/internal/topic_admin_option_defaults.h
google/cloud/pubsub/admin/samples/subscription_admin_client_samples.cc
google/cloud/pubsub/admin/samples/topic_admin_client_samples.cc
google/cloud/pubsub/admin/subscription_admin_connection.cc
google/cloud/pubsub/admin/subscription_admin_connection.h
google/cloud/pubsub/admin/topic_admin_connection.cc
google/cloud/pubsub/admin/topic_admin_connection.h
google/cloud/pubsub/blocking_publisher_connection.cc
google/cloud/pubsub/blocking_publisher_connection.h
google/cloud/pubsub/doc/pubsub-main.dox
google/cloud/pubsub/integration_tests/CMakeLists.txt
google/cloud/pubsub/integration_tests/generated_subscription_admin_integration_test.cc
google/cloud/pubsub/integration_tests/pubsub_client_integration_tests.bzl
google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
google/cloud/pubsub/internal/defaults.cc
google/cloud/pubsub/internal/defaults.h
google/cloud/pubsub/internal/schema_option_defaults.cc
google/cloud/pubsub/internal/schema_option_defaults.h
google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection.h
google/cloud/pubsub/samples/client_samples.cc
google/cloud/pubsub/samples/schema_client_samples.cc
google/cloud/pubsub/schema_connection.cc
google/cloud/pubsub/schema_connection.h
google/cloud/pubsub/subscriber_connection.cc
google/cloud/pubsub/subscriber_connection.h

fixes #15161
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15190)

feat(pubsub): add MakeConnection overloads to support regional and locational endpoints

---

.github/workflows/test-runner.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15198)

ci: enable gha ci for v3 branch

---

.github/renovate.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15199)

ci: try baseBranches with regex

---

google/cloud/spanner/internal/connection_impl_test.cc
google/cloud/spanner/internal/session.cc
google/cloud/spanner/internal/session.h
google/cloud/spanner/internal/session_pool.cc
google/cloud/spanner/internal/session_pool.h
google/cloud/spanner/internal/session_pool_test.cc
google/cloud/spanner/options.h

fixes #15219
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15226)

impl(spanner): add support for Multiplexed Session maintenance

---

.bazelrc
MODULE.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15288)

fix: explicitly register macOS toolchain

---

google/cloud/bigtable/CMakeLists.txt
google/cloud/bigtable/bigtable_client_unit_tests.bzl
google/cloud/bigtable/internal/metrics.cc
google/cloud/bigtable/internal/metrics.h
google/cloud/bigtable/internal/metrics_test.cc

Adds a function to extract the ResponseParams proto from the trailing metadata.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15299)

 impl(bigtable): add and test some metric utility functions

---

google/cloud/opentelemetry/internal/monitoring_exporter_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15318)

chore(opentelemetry): add missing includes

---

google/cloud/universe_domain/integration_tests/BUILD.bazel

#15332
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15333)

ci: disable EAToSAImpersonationRest and EAToSAImpersonationGrpc

---

google/cloud/storage/quickstart/.bazelrc
google/cloud/storage/quickstart/MODULE.bazel

b/280608087#comment20
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15327)

feat: enable bzlmod for storage quickstart

---

ci/bzlmod_tests/consumer-test/MODULE.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15354)

feat: update consumer-test to use 3.0.0-rc1 from BCR

---

CHANGELOG.md
google/cloud/spanner/integration_tests/client_integration_test.cc
google/cloud/spanner/internal/connection_impl.cc
google/cloud/spanner/internal/connection_impl_test.cc
google/cloud/spanner/internal/session_pool.cc
google/cloud/spanner/internal/session_pool_test.cc
google/cloud/spanner/options.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15366)

impl(spanner): promote from experimental and document multiplexed session support

---

google/cloud/bigtable/CMakeLists.txt
google/cloud/bigtable/google_cloud_cpp_bigtable.bzl
google/cloud/bigtable/results.h

Porting spanner::ResultSourceInterface into bigtable::ResultSourceInterface
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15575)

feat(bigtable): implement bigtable::ResultSourceInterface

---

google/cloud/storage/examples/storage_async_samples.cc

There are minor fixes for compiling the samples.

fix(storage): Fix the compilation error of samples code
