- google/cloud/opentelemetry/internal/recordable.cc
- google/cloud/opentelemetry/internal/recordable_test.cc
Fixes #12450 
This PR uses some knowledge of the implementation. Namely that `SetResource()` gets called after `SetIdentity()`. In the long run, this may be brittle.
I am refactoring our Recordable class, but would like to get this bandaid in first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12683)
> impl(otel): resources on root span only

- ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile
- ci/cloudbuild/triggers/cxx20-ci.yaml
- ci/cloudbuild/triggers/cxx20-pr.yaml
Fedora 37 is approaching EOL, and we get some goodies with Fedora 38. Using `latest` as the name of the distro will make it easier to upgrade in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12701)
> ci: move cxx20 build to Fedora:38

- google/cloud/internal/rest_stub_helpers.cc
- google/cloud/internal/rest_stub_helpers.h
Patch needs to accept query parameters in order to fix an issue; I figured it wouldn't hurt to enable all the helpers to accept query parameters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12697)
> impl(rest): allow all rest stub helpers to accept query params

- google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc
- google/cloud/bigquery/v2/minimal/benchmarks/benchmark.h
- google/cloud/bigquery/v2/minimal/benchmarks/benchmark_test.cc
- google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc
- google/cloud/bigquery/v2/minimal/benchmarks/project_benchmark_programs.cc
- google/cloud/bigquery/v2/minimal/benchmarks/table_benchmark_programs.cc
- google/cloud/bigquery/v2/minimal/internal/project.cc
- google/cloud/bigquery/v2/minimal/internal/project_response.cc
- google/cloud/bigquery/v2/minimal/internal/project_response_test.cc
- google/cloud/bigquery/v2/minimal/testing/project_test_utils.cc
This benchmark PR includes the following changes
1) A Project benchmark program that runs theListProject apis end to end based on input parameters 
and prints latency and throughput results. See the Project benchmark program output here: https://paste.googleplex.com/5685157741723648
2) Minor refactor of common time conversion method used by all benchmarks.
3) Added more information in `PrintThroughputResults()`.
3) Fixed the following issues related to parsing of json projects response, as exposed by benchmark tests:
- Fixed json parsing of 64-bit numbers being returned as json strings and corresponding unit tests.
- Fixed the validation logic in `valid_projects_list()` (e.g. "projects" field is not always returned. It may not be returned for the last page when "totalItems" field is 0)
- …
> impl(bigquery): Project benchmark program

- ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
- ci/cloudbuild/triggers/clang-tidy-ci.yaml
- ci/cloudbuild/triggers/clang-tidy-pr.yaml
- google/cloud/compute/integration_tests/compute_integration_test.cc
- google/cloud/spanner/internal/defaults_test.cc
- google/cloud/storage/internal/grpc/synthetic_self_link.h
The `google/cloud/storage/*` code changes are really related to libstdc++ 13.  And the `google/clouod/compute/*` code changes are (I think) just because I manually ran the build for compute.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12705)
> ci: move clang-tidy build to Fedora:38

- bazel/google_cloud_cpp_deps.bzl
We have different names for this repo. With this PR we are saying: "When `opentelemetry-cpp` refers to `@curl`, they really mean our `@com_github_curl_curl`."
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12706)
> fix(otel): bazel works with OTel curl client

- ci/cloudbuild/builds/lib/features.sh
- google/cloud/storage/examples/storage_async_samples.cc
- google/cloud/storage/internal/async/read_payload_impl_test.cc
Time to start testing `storage-grpc` in the `cxx20` and similar builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12707)
> ci: compile `storage-grpc` in most builds

- google/cloud/storage/internal/async/insert_object.cc
- google/cloud/storage/internal/async/insert_object.h
- google/cloud/storage/tests/async_client_integration_test.cc
The code assumed the `OnWrite()` callback (and the follow-on `Write()` call) would be invoked after it had a chance to prepare for the `Write()` call.  Clever in that overlapped some I/O with CPU operations, but wrong in that scheduling does not work like this.
I also changed the test to make the errors easier to interpret.
Fixes #12710
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12715)
> fix(GCS+gRPC): race condition in async `Insert()`

- google/cloud/internal/minimal_iam_credentials_stub.cc
- google/cloud/internal/minimal_iam_credentials_stub_test.cc
Look for "auth" or "rpc" to enable logging in the minimal IAM credentials stub.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12702)
> fix: gRPC auth logging enabled by "auth"

- ci/cloudbuild/triggers/check-api-ci.yaml
- ci/cloudbuild/triggers/check-api-pr.yaml
I already updated the triggers because the build passed locally.  If I did something wrong, we would need to revert the trigger changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12727)
> ci: move `check-api` to Fedora:38

- google/cloud/opentelemetry/configure_basic_tracing.cc
- google/cloud/opentelemetry/resource_detector.cc
- google/cloud/opentelemetry/resource_detector.h
Part of the work for #12726. Anti-work for #12114. 
Remove `google::cloud::Options` from the API to create a GCP resource detector. This opens up the possibility to switch out the implementation of this thing to something that does not depend on `google_cloud_cpp_common`, and other libraries.
We do not want to remove the API because it has value on its own. In the future we can add defaulted arguments to it, e.g. a `ResourceDetectorOptions o = {}`.
---
cc: @yashykt - [This change will not affect you](https://github.com/grpc/grpc/blob/3bdd972c4aad5578dde5a383b00fdf542ede8fb7/src/cpp/ext/csm/csm_observability.cc#L81C32-L81C52), but FYI.
- - - …
> cleanup(otel)!: Drop `Options` from resource detector API.

- .bazelrc
- BUILD.bazel
- ci/cloudbuild/builds/otel-disabled-bazel.sh
- doc/compile-time-configuration.md
- google/cloud/BUILD.bazel
- google/cloud/opentelemetry/integration_tests/BUILD.bazel
- google/cloud/opentelemetry/quickstart/.bazelrc
- google/cloud/opentelemetry/quickstart/BUILD.bazel
- google/cloud/opentelemetry/quickstart/README.md
- google/cloud/opentelemetry/samples/BUILD.bazel
- google/cloud/testing_util/BUILD.bazel
Part of the work for #12726 
We have:
- `--//:enable-experimental-opentelemetry`
- `//:experimental-opentelemetry`
Introduce:
- `--//:enable_opentelemetry` (Note that we take this opportunity to use snake_case)
- `//:opentelemetry`
We will leave around the old targets for a release to ease transition for our dependents (if they even exist).
Also correct the documentation about whether OTel is enabled/disabled by default with Bazel.
---
Note that `config_settings` must be mutually exclusive, and they only support AND logic over the `flag_values`.
---
cc: @yashykt - at some point this will affect you.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12732)
> feat(otel): GA bazel

- ci/cloudbuild/builds/check-api.sh
- ci/cloudbuild/builds/publish-docs.sh
- ci/cloudbuild/dockerfiles/checkers.Dockerfile
We need to ignore some "unreachable code" warnings in ShellCheck because the functions are called after being exported.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12738)
> ci: move checkers build to Fedora:38

- ci/cloudbuild/builds/coverage.sh
- ci/cloudbuild/builds/lib/integration.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12752)
> ci: no retry for flakes in coverage builds

- google/cloud/bigquery/v2/minimal/benchmarks/CMakeLists.txt
- google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc
- google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config.cc
- google/cloud/bigquery/v2/minimal/benchmarks/experimental_bigquery_rest_client_benchmark_programs.bzl
- google/cloud/bigquery/v2/minimal/benchmarks/job_insert_benchmark_programs.cc
This PR includes the following benchmark changes:
- A new benchmark program that tests the InsertJob api end to end and prints out latency and throughput results. 
The output is [here]( https://paste.googleplex.com/5338571408932864). Additionally, verified the query
given in the job configuration executed successfully ie in this specific case inserts were successful.
- Benchmark fixes related to InsertJob api as listed below:
> - Fixed the test Json payload for dry-run and real-run mode for InsertJob
> - Fixed benchmark InsertJob to set the job_id values correctly in the test request.
> - Fixed benchmark InsertJob to set the needed enum values in the test request.
> - Fixed benchmark to remove the not needed keys for InsertJob api.
- - - …
> impl(bigquery): Benchmark program for InsertJob api

- google/cloud/spanner/ci/lib/spanner_emulator.sh
- google/cloud/spanner/ci/run_integration_tests_emulator_bazel.sh
Copy the (usually short) Spanner emulator logs into our log after killing the emulator.  This may help diagnose connection failures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12769)
> ci(spanner): always include Spanner emulator logs in our log

- google/cloud/common_options.h
- google/cloud/grpc_options.cc
- google/cloud/grpc_options.h
- google/cloud/grpc_options_test.cc
- google/cloud/internal/curl_impl.cc
- google/cloud/internal/curl_impl.h
- google/cloud/internal/curl_impl_test.cc
Applications can use this option to configure the HTTP proxy settings. Some applications need to set the username and password and this cannot be done through environment variables (for `libcurl`).
Fixes #12764 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12766)
> feat(common): new `*Option` to configure HTTP proxy

- google/cloud/pubsub/internal/publisher_tracing_connection.cc
- google/cloud/pubsub/internal/publisher_tracing_connection_test.cc
Cleanup https://github.com/googleapis/google-cloud-cpp/pull/12774
Change from custom attribute to semantic convention
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12782)
> cleanup(pubsub): custom name to semantic convention for span

- ci/etc/integration-tests-config.sh
Try to resolve https://github.com/googleapis/google-cloud-cpp/issues/12661
Picked us-central1 since @coryan says it is usually the largest zone
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12784)
> ci(bigtable): change bigtable zone

- google/cloud/storage/examples/CMakeLists.txt
First, remove a level of nesting. Then remove some duplicate definitions.  And finally remove obsolete comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12792)
> cleanup: simplify CMake for storage/examples

- google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc
- google/cloud/bigquery/v2/minimal/internal/job_request.cc
- google/cloud/bigquery/v2/minimal/internal/job_request.h
- google/cloud/bigquery/v2/minimal/internal/job_request_test.cc
- google/cloud/bigquery/v2/minimal/internal/job_response.cc
- google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc
- google/cloud/bigquery/v2/minimal/internal/json_utils.cc
- google/cloud/bigquery/v2/minimal/internal/json_utils.h
- google/cloud/bigquery/v2/minimal/internal/json_utils_test.cc
- google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.cc
This PR includes the following fixes for the core Job library found during benchmark and end to end testing
of the Query and GetQueryResults api
- Added methods to PostQueryRequest() to record json keys that need to be filtered.
- Modified Query() rest stub to filter out json keys from the request, in the json payload.
- Modified “timeoutMs” field to be integer in GetQueryResultsRequest.
- Removed “formatOptions” from GetQueryResultsRequest as the server rejects it even though the documentation mentions it.
- Fixed “maximumBytesBilled” to be string in PostQueryRequest
- Fixed parsing of QueryResponse and GetQueryResultsResponse fields. This includes 64-bit parsing of integer fields, handling absent fields etc.
The above has been tested with a benchmark program. I'll send the benchmark …
> fix(bigquery): core job library fixes for Query and GetQueryResults api

- ci/cloudbuild/builds/clang-7.0.sh
- ci/cloudbuild/builds/clang-tidy.sh
- ci/cloudbuild/builds/cmake-gcs-rest.sh
- ci/cloudbuild/builds/cmake-install.sh
- ci/cloudbuild/builds/cmake-oldest-deps.sh
- ci/cloudbuild/builds/cxx14.sh
- ci/cloudbuild/builds/cxx20.sh
- ci/cloudbuild/builds/gcc-7.3.sh
- ci/cloudbuild/builds/lib/cmake.sh
- ci/cloudbuild/builds/lib/ctest.sh
- ci/cloudbuild/builds/lib/integration.sh
- ci/cloudbuild/builds/m32.sh
- ci/cloudbuild/builds/noex.sh
- ci/cloudbuild/builds/quickstart-production.sh
- ci/cloudbuild/builds/shared.sh
- ci/gha/builds/external-account.sh
- ci/gha/builds/lib/cmake.sh
- ci/gha/builds/lib/ctest.sh
- ci/gha/builds/macos-cmake.sh
- ci/gha/builds/windows-cmake.sh
This will make it possible to use ctest::* without the `cmake.sh` side-effects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12807)
> ci: refactor ctest:: function to its own module(s)

- .gitignore
- ci/cloudbuild/build.sh
- ci/cloudbuild/builds/development.sh
- ci/cloudbuild/builds/lib/ctest.sh
- ci/etc/cloudcxxrc
- google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh
- google/cloud/internal/ci/run_integration_tests_emulator_cmake.sh
- google/cloud/pubsub/ci/run_integration_tests_emulator_cmake.sh
- google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh
- google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
This script is expected to support /most/ developer workflows. We will be able to create a configuration file in $HOME or in the workspace to build only a subset of the code, with clang-tidy, and to run (or not run) the unit and integration tests associated with that code.
I expect this script will grow and be more customizable over time, as the team adds features to match their workflow.
Part of the work for #12801
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12804)
> ci: build script for developer workflows

- release/README.md
- release/changes.sh
The instruction update and script updates should probably be split into separate PRs, but eh.
- Only include handwritten libraries in the `sections`
- Only print changes that affect all libraries in "Common Libraries"
- Do not list storage-only changes under "Common Libraries"
- This is the change from `mapfile` to `IFS`
- Credit to @devbww for this fix
---
Pre-change:
```
- fix: export headers with top-level Bazel targets ([#12762](https://github.com/googleapis/google-cloud-cpp/pull/12762))
- perf(otel): cache propagator in gRPC tracing stubs ([#12642](https://github.com/googleapis/google-cloud-cpp/pull/12642))
- feat(generator): configurable x-goog-api-client  ([#12571](https://github.com/googleapis/google-cloud-cpp/pull/12571))
-  fix(internal): change url_encode include from .h to .cc …
```
> cleanup: slightly smarter release notes

- CMakeLists.txt
- ci/cloudbuild/builds/publish-docs.sh
- cmake/GoogleCloudCppDoxygen.cmake
e.g. fix the link in here https://cloud.google.com/cpp/docs/reference/kms/latest/classgoogle_1_1cloud_1_1kms__v1__mocks_1_1MockEkmServiceConnection#see-also
cleanup some dead code while we are here. I do not think cmake options to generate documentation need to be preserved.
I did not look at the docs in the staging site. I am relying on logic and reasoning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12771)
> cleanup(docs): and fix the mock links

- google/cloud/pubsub/testing/mock_message_batch.h
- google/cloud/storage/internal/async/connection_tracing.cc
- google/cloud/storage/mocks/mock_async_connection.h
Some of the clang-tidy warnings from the latest import
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12823)
> cleanup: iwyu based on google3 import

- google/cloud/storage/testing/retry_http_request.cc
- google/cloud/storage/testing/retry_http_request.h
- google/cloud/storage/tests/key_file_integration_test.cc
- google/cloud/storage/tests/service_account_credentials_integration_test.cc
- google/cloud/storage/tests/signed_url_integration_test.cc
Some integration tests need to make raw HTTP request. Use `rest_internal` types to make these, reducing the dependencies on `storage::internal::Curl*`.
Part of the work for #9659
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12821)
> cleanup(storage): use `rest_internal` in tests

- google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc
This PR includes the following fixes for the core Job library found during benchmark and end to end testing
of the CancelJob api
- Removed content-type header from CancelJob api request since the request body
needs to be empty.
This has been tested end to end with the benchmark program which I'll send in a
follow-up PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12825)
> fix(bigquery): Job Library fixes for CancelJob api

- google/cloud/bigquery/v2/minimal/benchmarks/CMakeLists.txt
- google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc
- google/cloud/bigquery/v2/minimal/benchmarks/benchmark.h
- google/cloud/bigquery/v2/minimal/benchmarks/experimental_bigquery_rest_client_benchmark_programs.bzl
- google/cloud/bigquery/v2/minimal/benchmarks/job_cancel_benchmark_programs.cc
This PR includes the following benchmark changes:
- Added new benchmark program that tests CancelJob api end to end and
prints out latency and throughput results. 
Output of the benchmark is here: https://paste.googleplex.com/6724924809936896
- Added CancelJob support in the benchmark library
- Build changes for the new benchmark file.
FYI: I have a minor clean-up PR after this one to address some additional feedback across benchmarks. I wanted to keep this one specific to cancel-job api.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12827)
> impl(bigquery): Benchmark program for CancelJob api

- google/cloud/storage/client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12833)
> doc(storage): describe default project search

- generator/integration_tests/tests/golden_kitchen_sink_tracing_connection_test.cc
- generator/integration_tests/tests/golden_kitchen_sink_tracing_stub_test.cc
- generator/integration_tests/tests/golden_thing_admin_tracing_connection_test.cc
- generator/integration_tests/tests/golden_thing_admin_tracing_stub_test.cc
- google/cloud/bigtable/internal/data_tracing_connection_test.cc
- google/cloud/internal/minimal_iam_credentials_stub_test.cc
- google/cloud/internal/opentelemetry.cc
- google/cloud/internal/opentelemetry_test.cc
- google/cloud/internal/tracing_http_payload_test.cc
- google/cloud/internal/tracing_rest_response_test.cc
- google/cloud/pubsub/internal/batching_publisher_tracing_connection_test.cc
- google/cloud/pubsub/internal/flow_controlled_publisher_tracing_connection_test.cc
- google/cloud/pubsub/internal/publisher_tracing_connection_test.cc
- google/cloud/storage/internal/async/reader_connection_tracing_test.cc
- google/cloud/storage/internal/tracing_connection_test.cc
Follow up to #12835
`google/cloud/internal/opentelemetry.cc` has the real change. The rest are tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12836)
> cleanup(otel): rename status attribute

- google/cloud/bigtable/internal/traced_row_reader.cc
- google/cloud/bigtable/internal/traced_row_reader_test.cc
- google/cloud/internal/async_read_write_stream_tracing.h
- google/cloud/internal/async_read_write_stream_tracing_test.cc
- google/cloud/internal/async_streaming_read_rpc_tracing.h
- google/cloud/internal/async_streaming_read_rpc_tracing_test.cc
- google/cloud/internal/async_streaming_write_rpc_tracing.h
- google/cloud/internal/async_streaming_write_rpc_tracing_test.cc
- google/cloud/internal/streaming_read_rpc_tracing.h
- google/cloud/internal/streaming_read_rpc_tracing_test.cc
- google/cloud/internal/streaming_write_rpc_tracing.h
- google/cloud/internal/streaming_write_rpc_tracing_test.cc
- google/cloud/internal/tracing_rest_client.cc
- google/cloud/internal/tracing_rest_client_test.cc
- google/cloud/storage/internal/async/reader_connection_tracing.cc
- google/cloud/storage/internal/async/reader_connection_tracing_test.cc
We intrument streaming RPC events that do not have names prescribed by the OTel semantic conventions. Some of these events were of the form `gcloud.*` and some not. This change makes them all consistent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12835)
> impl: consistently name our OTel events

- generator/integration_tests/tests/golden_kitchen_sink_tracing_stub_test.cc
- google/cloud/internal/async_read_write_stream_tracing.h
- google/cloud/internal/async_read_write_stream_tracing_test.cc
- google/cloud/internal/async_streaming_read_rpc_tracing.h
- google/cloud/internal/async_streaming_read_rpc_tracing_test.cc
- google/cloud/internal/async_streaming_write_rpc_tracing.h
- google/cloud/internal/async_streaming_write_rpc_tracing_test.cc
For streaming RPCs the `Start()` and `Finish()` calls need to be spans, as they can take significant time and may involve waiting for the server. It is also using to record the first `Read()` and `Write()` as they may initiate the upload or download.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12837)
> impl(otel): record more streaming RPC events

- google/cloud/storage/client.h
- google/cloud/storage/internal/grpc/object_request_parser.cc
- google/cloud/storage/internal/grpc/object_request_parser_test.cc
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/well_known_parameters.h
Support globs to filter object listing operations.
Fixes #1227
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12840)
> feat(storage): `MatchGlob` for `ListObjects()`

- google/cloud/storage/client.h
- google/cloud/storage/internal/grpc/object_request_parser.cc
- google/cloud/storage/internal/grpc/object_request_parser_test.cc
- google/cloud/storage/internal/grpc/stub.cc
- google/cloud/storage/internal/rest/stub.cc
- google/cloud/storage/internal/rest/stub_test.cc
Some options for `ReadObject()` can only be freely combined. The application intent is unclear when somebody says `ReadRange(1, 10)` and `ReadLast(7)`. And it is impossible to represent this as two instructions that the service can disambiguate.
We were checking for the presence of these options in the parameter pack, but that does not work, because the options can be "set" with no value (maybe at runtime choosing to set either `ReadLast()` or `ReadRange()`). Adding insult to injury, I forgot to `std::decay_t` the types in the parameter pack, so the compile-time check did not always work either.
In hindsight we should have represented them by a `absl::variant<>` or some other type that did not allow for illegal combinations, too late to do that.
- - - …
> fix(storage): check ReadObject options at runtime

- google/cloud/storage/client.cc
- google/cloud/storage/internal/object_read_streambuf.cc
- google/cloud/storage/internal/object_read_streambuf.h
- google/cloud/storage/internal/object_read_streambuf_test.cc
- google/cloud/storage/tests/object_media_integration_test.cc
The initial values for `tellg()` were incorrect `ReadRange()` and `ReadLast()` options.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12844)
> fix(storage): fix tellg() values

- google/cloud/internal/url_encode.cc
- google/cloud/internal/url_encode_test.cc
Make the URL encode/decode mappings constexpr and namespace scoped. Leave a note about creating one mapping from the other at compile time once we require C++17.
Extend the "MultipleReplacements" tests to cover all the things. Also add a "PercentNoOverlap" test to check that decoded bytes are not subject to further matching.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12849)
> impl(common): statically initialize URL encoding maps

- google/cloud/storage/bucket_autoclass.cc
- google/cloud/storage/bucket_autoclass.h
- google/cloud/storage/bucket_metadata.cc
- google/cloud/storage/bucket_metadata_test.cc
- google/cloud/storage/examples/storage_bucket_autoclass_samples.cc
- google/cloud/storage/internal/bucket_metadata_parser.cc
- google/cloud/storage/internal/grpc/bucket_metadata_parser.cc
- google/cloud/storage/internal/grpc/bucket_metadata_parser_test.cc
- google/cloud/storage/internal/grpc/bucket_request_parser_test.cc
This time, the `Bucket.auto_class()` gains `terminal_storage_class`, and `OUTPUT_ONLY` `terminate_storage_class_update` fields. Only interesting for completeness sake.
Fixes #12658
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12842)
> feat(storage): another Bucket CRUD field

- google/cloud/compute/quickstart/.bazelrc
This is necessary (but not sufficient) to get the quickstart building.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12856)
> fix(compute): add missing bazelrc file

- google/cloud/testing_util/validate_metadata.cc
Verify that our routing header values are actually URL encoded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12855)
> test: verify routing headers are url encoded

- ci/cloudbuild/builds/generate-libraries.sh
- generator/internal/discovery_to_proto.cc
- generator/internal/discovery_to_proto.h
- generator/internal/discovery_to_proto_test.cc
- generator/standalone_main.cc
Sometimes we need the `*_proto_export.h` files to go to a different directory vs. the `*.proto` files.
Part of the work for #12854
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12866)
> feat(generator): split discovery doc output

- google/cloud/internal/oauth2_authorized_user_credentials.cc
- google/cloud/internal/oauth2_authorized_user_credentials_test.cc
Only a limited number of scopes returns this field. For the rest of scopes this field is not populated, which is ok.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12867)
> fix(oauth2): do not require `id_token` in creds

- google/cloud/storage/google_cloud_cpp_storage.cmake
- google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
We do not directly use `OpenSSL::SSL` or `ZLIB::ZLIB`. Both are used indirectly via `CURL::libcurl`. We should not require the package or link the libraries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12890)
> fix(storage): remove unused dependencies

- google/cloud/internal/opentelemetry_context.h
- google/cloud/internal/opentelemetry_context_test.cc
https://github.com/googleapis/google-cloud-cpp/pull/12887#discussion_r1358695983
> (don't forget the empty collection case)
D'oh.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12893)
> cleanup(otel): handle empty in ScopedOTelContext

- google/cloud/internal/grpc_opentelemetry.cc
- google/cloud/internal/grpc_opentelemetry_test.cc
- google/cloud/internal/rest_opentelemetry.cc
- google/cloud/internal/rest_opentelemetry_test.cc
- google/cloud/internal/tracing_http_payload_test.cc
- google/cloud/internal/tracing_rest_client.cc
- google/cloud/internal/tracing_rest_client_test.cc
- google/cloud/internal/tracing_rest_response_test.cc
https://github.com/open-telemetry/opentelemetry-cpp/pull/2285 deprecated these names. Update to the new names so we can use the latest OTel version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12901)
> chore(otel): update semantic conventions

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl_test.cc
Refactor `internal::ConnectionImpl` and its test to facilitate upcoming additions to the `Connection` interface.
`connection_impl.cc`:
- Extract the "make commit timestamp" code to a named function.
- Use a single anonymous namespace.
`connection_impl_test.cc`:
- Rename `MockStream` to `MockStreamingReadRpc` so as to match the similar concept in other modules.
- Make `MockStreamingReadRpc` a template on the response type to prepare for its future use with `BatchWriteResponse`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12905)
> impl(spanner): refactor connection_impl and test

- google/cloud/internal/opentelemetry_context.cc
- google/cloud/internal/opentelemetry_context.h
- google/cloud/internal/opentelemetry_context_test.cc
Motivated by #12880 
Apologies for the churn in the internal interface....
Having code like:
```cc
{
auto span = MakeSpan("span");
OTelScope scope(span);
return child_->AsyncFoo();
}
```
is cleaner than having code like:
```cc
{
auto span = MakeSpan("span");
auto scope = opentelemetry::trace::Scope(scope);
PushOTelContext();
auto f =  child_->AsyncFoo();
PopOTelContext();
return f;
}
```
It is also closer to the code we currently write, so the diffs will be cleaner.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12904)
> cleanup(otel): manage OTelContext stack with class

- CHANGELOG.md
- cmake/GoogleCloudCppFeatures.cmake
Enabling `oauth2` if `GOOGLE_CLOUD_CPPP_ENABLE_REST` is set is a bug: it introduces a cycle in the dependencies of the library, and makes it impossible to compile `oauth2`, `storage`, and `compute` in different shards.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12911)
> fix(oauth2): only enable via GOOGLE_CLOUD_CPP_ENABLE

- google/cloud/internal/grpc_opentelemetry.h
- google/cloud/internal/grpc_opentelemetry_test.cc
- google/cloud/internal/opentelemetry.h
- google/cloud/internal/opentelemetry_test.cc
Part of the work for #12880 
These `EndSpan(..., future<>)` are mainly a `.then()` which might execute in a different thread than the future is returned in. Detach the context from the original thread in the callback thread.
This change is currently a no-op until we start pushing/popping the context and copying the OTelContext into the callback threads.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12902)
> impl(otel): detach context from `EndSpan(..., future<>)`

- generator/integration_tests/golden/v1/internal/golden_kitchen_sink_connection_impl.cc
- generator/internal/connection_impl_generator.cc
- google/cloud/aiplatform/v1/internal/featurestore_online_serving_connection_impl.cc
- google/cloud/aiplatform/v1/internal/prediction_connection_impl.cc
- google/cloud/aiplatform/v1/internal/tensorboard_connection_impl.cc
- google/cloud/bigquery/storage/v1/internal/bigquery_read_connection_impl.cc
- google/cloud/osconfig/agentendpoint/v1/internal/agent_endpoint_connection_impl.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12920)
> fix(generator): do not override default sleeper in streaming-read RPCs

- generator/generator_config.proto
- generator/internal/codegen_utils.cc
- generator/internal/codegen_utils_test.cc
- generator/standalone_main.cc
Part of [12873](https://github.com/googleapis/google-cloud-cpp/issues/12873)
Adds the service_name_mapping command line flag and parsing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12923)
> impl(generator): add service_name_mapping flag

- generator/internal/descriptor_utils.cc
- generator/internal/descriptor_utils_test.cc
- generator/internal/format_class_comments.cc
- generator/internal/format_class_comments_test.cc
Also fixes the format class comments to replace the service name in the comments with the new service name. This is unused for the pubsub library, but I figured if you use the param you would expect this behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12932)
> impl(generator): use the service name mapping param

- ci/gha/builds/macos-bazel.sh
Now that the build uses Bazel v6.4.0, which includes the fix for https://github.com/bazelbuild/bazel/issues/18965, we can remove the retry from #12127.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12931)
> ci(gha): remove workaround for Bazel crash on macOS

- google/cloud/storage/internal/async/insert_object.cc
- google/cloud/storage/internal/grpc/ctype_cord_workaround.h
I am going to need `SetContent(ChecksummedData&, absl::Cord)` from more than one `.cc` file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12936)
> refactor(GCS+gRPC): reusable `SetContent` for cords

- google/cloud/spanner/BUILD.bazel
- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/commit_result.h
- google/cloud/spanner/connection.cc
- google/cloud/spanner/connection.h
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/mocks/mock_spanner_connection.h
- google/cloud/spanner/samples/samples.cc
`spanner::Client::CommitAtLeastOnce(std::vector<Mutations>)`
Add support for committing mutation groups, batched efficiently into transactions with at-least-once semantics, using a single RPC.
All mutations within a group are committed atomically, but there is no atomicity or ordering between groups, so they must be independent of each other.
Partial failure is possible. That is, some batches can commit while others fail. The results of individual batches are returned via the response stream as their transactions complete.
Mutation groups are not replay protected. That is, it is possible that any mutation group may be applied more than once. They should be idempotent to avoid replay complications.
- - - …
> feat(spanner): single-RPC, batched commit of mutation groups

- google/cloud/internal/grpc_opentelemetry.cc
- google/cloud/internal/rest_opentelemetry.cc
- google/cloud/internal/tracing_rest_client.cc
- google/cloud/pubsub/internal/publisher_tracing_connection.cc
Now that the function is overloaded, we can use it instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12946)
> refactor(otel): use makespan instead of start span

- generator/integration_tests/tests/mock_golden_kitchen_sink_stub.h
- google/cloud/BUILD.bazel
- google/cloud/google_cloud_cpp_common.cmake
- google/cloud/google_cloud_cpp_mocks.bzl
- google/cloud/internal/async_read_write_stream_logging_test.cc
- google/cloud/internal/async_read_write_stream_tracing_test.cc
- google/cloud/mocks/mock_async_streaming_read_write_rpc.h
- google/cloud/pubsublite/BUILD.bazel
- google/cloud/pubsublite/CMakeLists.txt
- google/cloud/pubsublite/internal/partition_publisher_test.cc
- google/cloud/pubsublite/internal/resumable_async_streaming_read_write_rpc_test.cc
- google/cloud/pubsublite/pubsublite_testing.bzl
This class is part of the public API for some `*Connection` and `*Client` classes. Applications may need to mock them, we should provide the mock.
I also refactored existing mocks to a single place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12950)
> feat(common): mock for `AsyncStreamingReadWriteRpc`

- google/cloud/policytroubleshooter/README.md
- google/cloud/policytroubleshooter/quickstart/quickstart.cc
If we are going to write `std::move(r).status()` we cannot make `r` a `const` object.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12953)
> cleanup(policytroubleshooter): cannot move a `const`

- ci/cloudbuild/builds/clang-tidy.sh
Since #12707, when `experimental-storage_grpc` joined the `features::always_build()` list, we have no reason to add it explicitly in the `clang-tidy` build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12965)
> cleanup(ci): remove double feature enable from clang-tidy build

- google/cloud/pubsub/internal/batching_publisher_connection.cc
- google/cloud/pubsub/internal/batching_publisher_connection_test.cc
- google/cloud/pubsub/internal/message_batch.h
- google/cloud/pubsub/internal/noop_message_batch.h
- google/cloud/pubsub/internal/tracing_message_batch.cc
- google/cloud/pubsub/internal/tracing_message_batch.h
- google/cloud/pubsub/internal/tracing_message_batch_test.cc
- google/cloud/pubsub/testing/mock_message_batch.h
- google/cloud/testing_util/opentelemetry_matchers.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12928)
> impl(pubsub): add more than 128 links

- google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc
- google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc
Without it `rest_request->AddHeader(...` and other operations terminate the program without any error message.
@jsrinnn
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12973)
> fix(bigquery): propagate bad status back

- google/cloud/pubsub/internal/tracing_message_batch.cc
Getting
```
google/cloud/pubsub/internal/tracing_message_batch.cc(112): error C3493: 'kMaxOtelLinks' cannot be implicitly captured because no default capture mode has been specified
google/cloud/pubsub/internal/tracing_message_batch.cc(117): error C2064: term does not evaluate to a function taking 1 arguments
google/cloud/pubsub/internal/tracing_message_batch.cc(121): error C2064: term does not evaluate to a function taking 1 arguments
google/cloud/pubsub/internal/tracing_message_batch.cc(121): error C2660: 'google::cloud::pubsub_internal::v2_18::`anonymous-namespace'::MakeLinks': function does not take 1 arguments
google/cloud/pubsub/internal/tracing_message_batch.cc(55): note: see declaration of 'google::cloud::pubsub_internal::v2_18::`anonymous-namespace'::MakeLinks' …
```
> fix(pubsub): add missing default capture

- google/cloud/internal/grpc_opentelemetry.cc
- google/cloud/internal/grpc_opentelemetry_test.cc
- google/cloud/internal/rest_opentelemetry.cc
- google/cloud/internal/rest_opentelemetry_test.cc
- google/cloud/internal/tracing_http_payload_test.cc
- google/cloud/internal/tracing_rest_client.cc
- google/cloud/internal/tracing_rest_client_test.cc
- google/cloud/internal/tracing_rest_response_test.cc
Part of the work for #12991 
Instead of changing the values of these semantic convention variables, OTel deprecates them, and tells you to use the new name. That is weird, but whatever.
Let's not mess with any `#if OPENTELEMETRY_CPP_VERSION`s. Let's just use the values du jour directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12992)
> fix(otel): restore compatibility with otel 1.9.1

- google/cloud/pubsub/internal/tracing_message_batch.cc
- google/cloud/pubsub/internal/tracing_message_batch.h
- google/cloud/pubsub/internal/tracing_message_batch_test.cc
- Move the tracing message batch class declaration into the .cc
- Add MakeTracingMessageBatch interface with one definition when GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY is defined and one when not
- Remove test only constructor and `GetMessageSpans` and refactor corresponding tests.
- Remove SaveMessage and SaveMultipleMessages tests since they are not helpful without the `GetMessageSpans` helper
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12995)
> refactor(pubsub): hide tracing message batch class definition

- google/cloud/internal/trace_propagator.cc
Part of the work for #12991 
`SimpleHexAtoi()` was not added until later.
Updates to `cmake-oldest-deps.sh` revealed this.... but I need to do a few things to update that script. So there is no verification in our CI at this commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12993)
> fix(otel): support abseil <= 20210324

- google/cloud/pubsub/publisher_connection.cc
- google/cloud/pubsub/publisher_connection.h
- google/cloud/pubsub/publisher_connection_test.cc
Closes https://github.com/googleapis/google-cloud-cpp/issues/12528
Second attempt at https://github.com/googleapis/google-cloud-cpp/pull/12969.
- Add an additional param to add a mock'd message batch and then use a condition variable to wait for the spans to complete before checking.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12996)
> impl(pubsub): use tracing message batch

- google/cloud/credentials.h
- google/cloud/internal/grpc_service_account_authentication.cc
- google/cloud/internal/unified_grpc_credentials.cc
- google/cloud/storage/testing/temp_file.h
- google/cloud/storage/tests/unified_credentials_integration_test.cc
A number of credentials failed to use the `CARootsFilePathOption` as they should.
Use the storage integration test because it covers both gRPC and REST.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12997)
> fix(common): missed using `CARootsFilePathOption`

- ci/cloudbuild/builds/conformance.sh
- ci/cloudbuild/triggers/conformance-ci.yaml
- ci/cloudbuild/triggers/conformance-pr.yaml
Fixes #12391
I made the trigger files by:
- copying `asan-*.yaml`
- deleting `createTime`, `id`, `resourceName` fields
- running `ci/cloudbuild/trigger.sh -i triggers/conformance-*.yaml`
- copying that output into the trigger files
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13002)
> ci: dedicated build for conformance tests

- ci/cloudbuild/builds/demo-install.sh
- ci/cloudbuild/dockerfiles/demo-alpine-stable.Dockerfile
- ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
- ci/cloudbuild/dockerfiles/demo-debian-bookworm.Dockerfile
- ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
- ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
- ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
- ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
- ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
- ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
- ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
- ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile
- doc/packaging.md
- google/cloud/opentelemetry/quickstart/README.md
Part of the work for #12991 (well, sorta. this might have deserved its own issue).
By default, tell customers to install and build opentelemetry-cpp.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13005)
> doc(otel): add packaging instructions

- ci/cloudbuild/builds/cmake-oldest-deps.sh
- ci/etc/oldest-deps/vcpkg.json
- doc/packaging.md
- google/cloud/opentelemetry/quickstart/README.md
Fixes #12991 
Pin OTel to v1.9.1 in our cmake-oldest-deps build. Communicate this in the packaging doc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13007)
> ci(otel): test with minimum version

- google/cloud/internal/future_coroutines.h
As I write more C++20 examples and tests it is getting harder to hide the coroutine support code from `clang-tidy`'s prying eyes. Where possible, I followed the Google Style Guide naming convention. Where the C++ standard and the Google Style Guide conflict, I silenced `clang-tidy`.
Motivated by #9134
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13009)
> cleanup(common): tidy coroutine support code

- ci/cloudbuild/builds/cmake-oldest-deps.sh
- google/cloud/storage/internal/grpc/make_cord_test.cc
- google/cloud/storage/internal/grpc/stub.cc
- google/cloud/storage/internal/storage_stub_factory_test.cc
Some missing headers in `storage/internal/grpc/stub.cc`. Older versions of `absl::Cord::chunks()` cannot be used with googletests's `ElementsAre()`.
And older versions of gRPC need us to have a thread associated with the completion queue in one of the tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13019)
> ci: enable `storage_grpc` with oldest deps

- google/cloud/storage/internal/grpc/configure_client_context.cc
- google/cloud/storage/internal/grpc/configure_client_context.h
- google/cloud/storage/internal/grpc/configure_client_context_test.cc
We need to populate the routing headers for resumable uploads, as the generator cannot do so for bi-directional streaming RPCs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13025)
> impl(GCS+gRPC): resumable upload routing header

- google/cloud/storage/internal/async/partial_upload.cc
- google/cloud/storage/internal/async/partial_upload_test.cc
When we send messages with `flush: true` we also want a response with the current status. I also took the opportunity to add additional test cases and other cleanups in the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13036)
> impl(GCS+gRPC): need state lookup on flush

- examples/grpc_credential_types.cc
- google/cloud/bigtable/doc/bigtable-samples-grpc-credentials.dox
- google/cloud/bigtable/examples/bigtable_grpc_credentials.cc
Prefer unified credentials in the examples (over `GrpcCredentialOption`).
Also use the versioned IAM credentials client.
Also remove the GCE credentials example from Bigtable, which is not recommended. Customers should be using the default credentials instead.
---
I am not certain that this gets tested in our CI. I think it is skipped most of the time in `integration-production-pr`. (Maybe they run in `integration-daily`? I don't remember).
I ran the bigtable examples, and the two access token examples manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13032)
> cleanup: GUAC in examples

- google/cloud/storage/async_connection.h
- google/cloud/storage/async_object_requests.h
- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl.h
- google/cloud/storage/internal/async/connection_impl_test.cc
- google/cloud/storage/internal/async/connection_tracing.cc
- google/cloud/storage/internal/async/connection_tracing_test.cc
- google/cloud/storage/mocks/mock_async_connection.h
- google/cloud/storage/testing/mock_storage_stub.h
Introduce a member function in the `AsyncConnection` interface (and its implementations) to use resumable uploads. This is the only reasonable way to stream data too, but it requires additional features to fully support recovering from interrupted uploads.
Part of the work for #9134 
I apologize for sending so many large PRs.  This one I can break a little bit, but the additional pieces will look unmotivated. Unfortunately adding a member function to `AsyncConnection` requires changes in all the implementations and requires tests for all of them too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13030)
> impl(GCS+gRPC): `AsyncWriteObject()`, part 1/2

- google/cloud/pubsub/internal/tracing_message_batch.cc
Closes https://github.com/googleapis/google-cloud-cpp/issues/13014 
Spans are now grouped
Before
https://screenshot.googleplex.com/B3Epm7BVQVNoumk
After
https://screenshot.googleplex.com/6Ns58ZaedPXkSD4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13027)
> impl(pubsub): fix scopes

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/client.cc
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/connection.h
- google/cloud/spanner/directed_read_replicas.h
- google/cloud/spanner/google_cloud_cpp_spanner.bzl
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/options.h
- google/cloud/spanner/query_partition.h
- google/cloud/spanner/query_partition_test.cc
- google/cloud/spanner/read_partition.h
- google/cloud/spanner/read_partition_test.cc
- google/cloud/spanner/samples/samples.cc
Add the `DirectedReadOption` to indicate which replicas or regions should be used for `Client::Read()`, `Client::ExecuteQuery()`, and `Client::ProfileQuery()` calls in read-only or single-use transactions.
- The `IncludeReplicas` variant lists the replicas to try (in order) to process the request, and what to do if the list is exhausted without finding a healthy replica.
- The `ExcludeReplicas` variant lists replicas that should be excluded from serving the request.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13031)
> feat(spanner): control replicas/regions used in non-transactional reads

- ci/cloudbuild/builds/checkers.sh
Fixes #12785 
Release notes use a different markdown renderer than the rest of GitHub. It preserves line breaks. That bothers me, but I may be alone.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13045)
> ci: no mdformat for CHANGELOG.md

- google/cloud/pubsub/internal/tracing_message_batch.cc
- google/cloud/pubsub/internal/tracing_message_batch_test.cc
- google/cloud/testing_util/opentelemetry_matchers.cc
It needs to increase the span catcher buffer size since the default is 100 (https://github.com/open-telemetry/opentelemetry-cpp/blob/ca08c5a34ad4af1b6b392c8bf5fc26a5210a2f2c/exporters/memory/include/opentelemetry/exporters/memory/in_memory_span_exporter.h#L17)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13043)
> impl(pubsub): only add links that are sampled

- google/cloud/pubsub/internal/tracing_message_batch_test.cc
https://github.com/googleapis/google-cloud-cpp/pull/13039 went in before https://github.com/googleapis/google-cloud-cpp/pull/13043 so the names were not updated in the unit test 😮 
Causing all our CI builds to fail 🙃 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13046)
> fix(pubsub): fix merge conflict causing bad unit test

- google/cloud/pubsub/internal/blocking_publisher_tracing_connection.cc
- google/cloud/pubsub/internal/blocking_publisher_tracing_connection_test.cc
- google/cloud/pubsub/internal/publisher_tracing_connection.cc
- google/cloud/pubsub/internal/publisher_tracing_connection_test.cc
Closes https://github.com/googleapis/google-cloud-cpp/issues/12952
Trying to get this into the otel semconvs (https://github.com/open-telemetry/semantic-conventions/pull/490)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13041)
> refactor(pubsub): rename messaging system to gcp_pubsub

- google/cloud/internal/async_polling_loop.cc
- google/cloud/internal/async_polling_loop_test.cc
- google/cloud/internal/async_rest_polling_loop.h
- google/cloud/internal/async_rest_polling_loop_test.cc
- google/cloud/internal/opentelemetry.cc
- google/cloud/internal/opentelemetry.h
- google/cloud/internal/opentelemetry_test.cc
Require explicit options to set attributes in the current span.
Part of the work for #12359 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13048)
> cleanup(common): explicit options for span attr

- google/cloud/storage/async_writer_connection.h
- google/cloud/storage/internal/async/writer_connection_finalized.cc
- google/cloud/storage/internal/async/writer_connection_finalized.h
- google/cloud/storage/internal/async/writer_connection_finalized_test.cc
- google/cloud/storage/internal/async/writer_connection_impl.cc
- google/cloud/storage/internal/async/writer_connection_impl.h
- google/cloud/storage/internal/async/writer_connection_impl_test.cc
- google/cloud/storage/internal/async/writer_connection_tracing.cc
- google/cloud/storage/internal/async/writer_connection_tracing_test.cc
- google/cloud/storage/mocks/mock_async_writer_connection.h
This implements `Flush()` and `Query()` member functions in `AsyncWriterConnection` and its implementations. This is needed to fully support uploads for streaming data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13042)
> impl(GCS+gRPC): flush data in `AsyncWriterConnection`

- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl.h
- google/cloud/storage/internal/async/connection_impl_test.cc
Complete the implementation of `AsyncWriteObject()`. This adds support for resuming uploads.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13044)
> impl(GCS+gRPC): `AsyncWriteObject()`, part 2/2

- google/cloud/internal/async_long_running_operation.h
- google/cloud/internal/async_long_running_operation_test.cc
- google/cloud/internal/async_polling_loop.cc
- google/cloud/internal/async_polling_loop.h
- google/cloud/internal/async_polling_loop_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13049)
> cleanup: explicit options for LRO polling loop

- .github/workflows/windows-cmake.yml
Fix the error in the cmake builds
```
Error: google-github-actions/setup-gcloud failed with: failed to execute command `gcloud.cmd --quiet auth login --force --cred-file C:\a\google-cloud-cpp\google-cloud-cpp\gha-creds-5220443cfe4db9bc.json`: ERROR: gcloud failed to load. You are running gcloud with Python 3.7, which is no longer supported by gcloud
```
[Failed build](https://github.com/googleapis/google-cloud-cpp/actions/runs/6766491508)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13058)
> ci(gha): set CLOUDSDK_PYTHON env variable

- google/cloud/google_cloud_cpp_common.bzl
- google/cloud/google_cloud_cpp_common.cmake
- google/cloud/google_cloud_cpp_common_unit_tests.bzl
- google/cloud/internal/clock.h
- google/cloud/internal/clock_test.cc
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/google_cloud_cpp_spanner.bzl
- google/cloud/spanner/internal/session.h
- google/cloud/spanner/internal/session_pool_test.cc
- google/cloud/spanner/spanner_client_testing.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
- google/cloud/testing_util/CMakeLists.txt
- google/cloud/testing_util/fake_clock.h
- google/cloud/testing_util/google_cloud_cpp_testing.bzl
Move `spanner_internal::Clock` (and its associated classes) into common.
In bigtable, I am going to have a few interfaces (I think 4) that will need to know `Clock::now()`. I could always accept `time_point now` as an argument to all of these interfaces.... but the code would be unnecessarily verbose. I would rather initialize the objects with a generic `Clock` and call `Clock::now()` in the implementation. Hence this refactor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13057)
> refactor: clock interface into common

- google/cloud/bigquery/v2/minimal/internal/json_utils.cc
- google/cloud/bigquery/v2/minimal/internal/json_utils_test.cc
This functionality replaces all arrays with `<discarded>` value, making the json invalid. It happens even if the array is not empty.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13052)
> fix: leave arrays in json

- google/cloud/bigquery/v2/minimal/internal/dataset_response.cc
- google/cloud/bigquery/v2/minimal/internal/dataset_response_test.cc
If a user doesn't have permissions to datasets or there are no datasets in a project, BQ API returns only 'kind' and 'etag' field. The response status is 200. We shouldn't fail such response.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13061)
> impl(bigquery): return empty list if BQ API doesn't populate datasets

- google/cloud/bigtable/client_options_test.cc
- google/cloud/internal/curl_rest_client_integration_test.cc
- google/cloud/internal/user_agent_prefix.cc
- google/cloud/internal/user_agent_prefix_test.cc
- google/cloud/spanner/internal/defaults_test.cc
Using this prefix will let us distinguish between fully generated vs. hand-crafted libraries in Google's telemetry.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13082)
> impl: change User-Agent prefix

- google/cloud/pubsub/internal/tracing_message_batch.cc
- google/cloud/pubsub/internal/tracing_message_batch_test.cc
Closes https://github.com/googleapis/google-cloud-cpp/issues/12976
Follows what Otel does with the include guard (https://github.com/open-telemetry/opentelemetry-cpp/blob/35a9362732216c00a24bdd4c98ebb5f9bbaab2c5/sdk/src/trace/span.cc#L149-L176)
Lmk if I need to add a separate build to test this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13078)
> impl(pubsub): add addlink api if otel version 2

- google/cloud/completion_queue.h
- google/cloud/future_generic_then_test.cc
- google/cloud/internal/async_read_stream_impl.h
- google/cloud/internal/async_rest_retry_loop.h
- google/cloud/internal/async_retry_loop.h
- google/cloud/internal/async_retry_unary_rpc.h
- google/cloud/internal/base64_transforms.cc
- google/cloud/internal/big_endian.h
- google/cloud/internal/error_context.h
- google/cloud/internal/future_then_impl.h
- google/cloud/internal/future_then_meta.h
- google/cloud/internal/invoke_result.h
- google/cloud/internal/pagination_range.h
- google/cloud/internal/random.h
- google/cloud/internal/rest_retry_loop.h
- google/cloud/internal/retry_loop.h
- google/cloud/internal/strerror.cc
- google/cloud/internal/tuple.h
- google/cloud/internal/utility.h
- google/cloud/status_or.h
- google/cloud/testing_util/chrono_output.h
- google/cloud/testing_util/status_matchers.h
A number of places where `std::foo_t<T>` is a more succint way to say `typename std::foo<T>::type`. `clang-tidy` also recommends a `noexcept` on `swap()` functions, where that is not a lie, it seems like a good idea.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13083)
> cleanup(common): prepare for clang-tidy 17

- google/cloud/bigtable/internal/bigtable_stub_factory.cc
Yes, we really need to set both of these, even though `mutate_rows_rate_limit` means "I have implemented the feature with a bug" and `mutate_rows_rate_limit2` means "I have implemented the feature correctly". The server must be doing an `&&`. :facepalm:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13086)
> impl(bigtable): flip throttling flag(s)

- google/cloud/storage/bucket_metadata_test.cc
- google/cloud/storage/examples/storage_object_csek_samples.cc
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/internal/generate_message_boundary.h
- google/cloud/storage/internal/generic_request.h
- google/cloud/storage/internal/grpc/make_cord.h
- google/cloud/storage/internal/grpc/object_request_parser.cc
- google/cloud/storage/internal/policy_document_request.cc
- google/cloud/storage/internal/rest/request_builder.h
- google/cloud/storage/internal/tuple_filter.h
- google/cloud/storage/object_read_stream.cc
- google/cloud/storage/object_read_stream.h
- google/cloud/storage/object_rewriter.h
- google/cloud/storage/object_write_stream.cc
- google/cloud/storage/object_write_stream.h
- google/cloud/storage/parallel_upload.cc
- google/cloud/storage/parallel_upload.h
- google/cloud/storage/tests/bucket_integration_test.cc
- google/cloud/storage/tests/object_compose_many_integration_test.cc
`clang-tidy` really wants us to use `emplace_back()`, but that is not possible for brace-initialized `struct`s with C++14.
Also needed to use `std::foo_t<T>` over `typename std::foo<T>::type`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13088)
> cleanup(storage): prepare for `clang-tidy` 17

- ci/cloudbuild/dockerfiles/checkers.Dockerfile
- google/cloud/spanner/internal/transaction_impl_test.cc
- google/cloud/spanner/results_test.cc
- google/cloud/spanner/row.cc
- google/cloud/terminate_handler_test.cc
- google/cloud/testing_util/mock_http_payload.h
New version of `clang-format` with (better ?) east-const enforcement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13101)
> ci: upgrade `checkers` build to Fedora:39

- google/cloud/storage/internal/storage_stub_factory.cc
- google/cloud/storage/internal/storage_stub_factory.h
- google/cloud/storage/internal/storage_stub_factory_test.cc
Change the factory helpers to avoid race conditions in the test. The `GrpcChannelRefresh` object should be deleted after the stubs and the corresponding channels. The test was destroying them in the opposite order, this results in race conditions with older versions of gRPC.
I solved the problem by *not* creating a `GrpcChannelRefresh` that then goes unused.
I think this was a test-only bug: the library does destroy these things in the right order.
Fixes #13084
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13104)
> test(GCS+gRPC): deflake stub factory test

- google/cloud/bigtable/CMakeLists.txt
- google/cloud/bigtable/bigtable_client_testing.bzl
- google/cloud/bigtable/data_connection.cc
- google/cloud/bigtable/internal/bulk_mutator.cc
- google/cloud/bigtable/internal/bulk_mutator.h
- google/cloud/bigtable/internal/bulk_mutator_test.cc
- google/cloud/bigtable/internal/data_connection_impl.cc
- google/cloud/bigtable/internal/data_connection_impl.h
- google/cloud/bigtable/internal/data_connection_impl_test.cc
- google/cloud/bigtable/internal/mutate_rows_limiter.cc
- google/cloud/bigtable/internal/mutate_rows_limiter.h
- google/cloud/bigtable/internal/mutate_rows_limiter_test.cc
- google/cloud/bigtable/testing/mock_mutate_rows_limiter.h
Create a no-op limiter, and plumb it through the internal layers of the library for `Table::BulkApply()`
Also fix virtual destructor for `MutateRowsLimiter`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13090)
> impl(bigtable): plumb MutateRowsLimiter internally

- ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-publish-docs.Dockerfile
- ci/cloudbuild/triggers/publish-docs-ci.yaml
- ci/cloudbuild/triggers/publish-docs-compute-pr.yaml
- ci/cloudbuild/triggers/publish-docs-pr.yaml
- ci/cloudbuild/triggers/publish-docs-release.yaml
With the latest Doxygen we generate invalid docfx documents. I don't want to hold back the upgrade to Fedora:39 for most builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13107)
> ci: `publish-docs` needs its own image

- google/cloud/internal/opentelemetry.cc
- google/cloud/internal/opentelemetry.h
- google/cloud/internal/opentelemetry_test.cc
- google/cloud/internal/rest_retry_loop.h
- google/cloud/internal/retry_loop.h
- google/cloud/storage/internal/connection_impl.cc
Motivated by #12959 
Generalize traced sleeps
- `std::chrono::duration<R,P>` instead of `std::chrono::milliseconds`
- `name` instead of `"Backoff"`
I plan to trace the sleeps when rate limiting in the Bigtable client (when tracing is enabled).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13106)
> refactor(otel): any duration in traced sleeper

- WORKSPACE.bazel
- ci/cloudbuild/builds/grpc-at-head.sh
Basically, gRPC used to vendor-in `upb`, but that is now part of Protobuf, so both needed changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13109)
> ci: gRPC at HEAD requires Protobuf >= v25

- google/cloud/grpc_options.cc
- google/cloud/grpc_options.h
- google/cloud/pubsub/internal/default_batch_sink_test.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/internal/connection_impl_test.cc
Add a common option to set the gRPC compression algorithm, which can be used at both the client and individual-operation levels. (Previously, users could only affect client-to-server compression at the connection level, using `GrpcChannelArgumentsNativeOption`.)
- It will take precedence over any compression algorithm set by the `internal::GrpcSetupOption` function.
- The `pubsub::CompressionAlgorithmOption` takes precedence over any other settings during `AsyncPublish()` calls when the request-size threshold is met.
Exercise the new option in the Spanner client in two ways:
- A new `ConnectionImpl` test to check that the compression algorithm from the prevailing options is reflected in the `grpc::ClientContext` passed to the stub.
- Setting the compression algorithm used during the …
> feat(common): add GrpcCompressionAlgorithmOption

- google/cloud/internal/log_wrapper.cc
The last argument to `LogRequest()` is (the debug string of) a request message, so don't prefix it with "status=".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13126)
> cleanup(common): remove misleading text from request-message log

- google/cloud/internal/opentelemetry.h
- google/cloud/internal/opentelemetry_test.cc
- google/cloud/internal/rest_retry_loop_test.cc
- google/cloud/internal/retry_loop_test.cc
- google/cloud/storage/internal/connection_impl_test.cc
Motivated by #12959 
I still like invoking the `sleeper` even when the duration is 0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13125)
> impl(otel): no spans if no sleeps

- google/cloud/bigquery/v2/minimal/internal/job_response.cc
- google/cloud/bigquery/v2/minimal/internal/job_response_test.cc
BQ returns this field only if `projection:FULL` was chosen during request. If request doesn't have it or `projection:MINIMAL` is chosen, BQ doesn't return this field. Which makes it not mandatory for ALL responses to have it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13102)
> fix(bigquery): remove requirement to have `configuration` field

- google/cloud/bigquery/v2/minimal/internal/job_request.cc
- google/cloud/bigquery/v2/minimal/internal/job_request_test.cc
Docs states that min/maxCreationTime is a string with `value for job creation time, in milliseconds since the POSIX epoch` 
https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/list#query-parameters
Currently the format is like `2023-11-03T10:33:16.946721928Z` which is not valid for BQ API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13103)
> fix(bigquery): use int for creationTime

- google/cloud/bigquery/v2/minimal/internal/job_request.cc
- google/cloud/bigquery/v2/minimal/internal/job_request_test.cc
Based on comments for already merged PR
https://github.com/googleapis/google-cloud-cpp/pull/13103
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13140)
> internal(bigquery): cast time without 'time_since_epoch()'

- google/cloud/internal/async_polling_loop_test.cc
- google/cloud/internal/async_rest_polling_loop_test.cc
Unblocks #12880 and #13141 
Modify the async polling loop tests to only test the behavior of the class -- that cancels (which happen out of band) are tied to the operation span.
We did a similar thing for the async retry loop in #12915.
Testing that the call span is active throughout requires a lot of setup. (We have to recreate the behavior of async grpc operations in the mock CQ and mock Stubs). A test that the call span is active throughout is more like #13034.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13144)
> test(otel): only test the AsyncPollingLoop interface

- google/cloud/pubsub/internal/blocking_publisher_tracing_connection.cc
- google/cloud/pubsub/internal/blocking_publisher_tracing_connection_test.cc
- google/cloud/pubsub/internal/publisher_tracing_connection.cc
- google/cloud/pubsub/internal/publisher_tracing_connection_test.cc
"messaging.message.total_size_bytes" -> sc::kMessagingMessageEnvelopeSize
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13142)
> refactor(pubsub): use sc instead of custom attribute

- google/cloud/internal/opentelemetry_context.cc
- google/cloud/internal/opentelemetry_context.h
- google/cloud/internal/opentelemetry_context_test.cc
Part of the work (and fix the implementation of) #12880 
We write code like:
```cc
{
auto span = MakeSpan("span");
OTelScope scope(span);
return AsyncFoo().then([oc = opentelemetry::context::RuntimeContext::GetCurrent(), span] {
DetachOTelContext(oc);
EndSpan(span);
// We do not want `span` to be active at this point
}).then([] { AsyncBar(); });
}
```
A problem occurs when the future returns immediately. Then the code looks more like:
```cc
{
auto span = MakeSpan("span");
OTelScope scope(span);
AsyncFoo();
DetachOTelContext(opentelemetry::context::RuntimeContext::GetCurrent()));
EndSpan(span);
// We do not want `span` to be active at this point, but it is.
AsyncBar();
}
```
---
To make sure `DetachOTelContext()` ends the active context, we want to own the token associated with that …
> fix(otel): detach context when single-threaded

- google/cloud/internal/opentelemetry_test.cc
- google/cloud/testing_util/opentelemetry_matchers.h
It is a little bit nicer to match on the span object. Still, the best we can do in the debug string is to just dump the span ID. (We do not have access to the span's name or anything).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13155)
> cleanup: parent span matcher

- google/cloud/bigtable/internal/data_tracing_connection.cc
- google/cloud/bigtable/internal/data_tracing_connection_test.cc
Fixes #12880, a similar PR to #12921, which was for updating `storage`. This one is for `bigtable`.
Generally, we need to replace any `opentelemetry::trace::Scope` with `g::c::i::OTelScope`. And if we are not using `EndSpan(..., future<T>)`, be sure to manually `DetachOTelContext(...)` when the operation is over.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13156)
> fix(bigtable): async context propagation for tracing

- .github/workflows/macos-cmake.yml
- ci/cloudbuild/builds/bazel-oldest.sh
Both gRPC and Protobuf stopped testing with Bazel < 6.3.x, we need to update too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13133)
> chore(deps): use 6.3.2 as the oldest Bazel version

- google/cloud/bigtable/examples/howto_mock_data_api.cc
This unblocks building the example in google3, where `cbt::RowKeyType != std::string`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13164)
> cleanup(bigtable): use generic `RowKeyType`

- ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
- doc/packaging.md
`opentelemetry-cpp` is installed into `/usr/local/lib64`. Manually update the PKG_CONFIG_PATH to include this path.
Noticed when testing #13177. This is worthy of its own PR though.
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/f55fe348-dff2-4cba-b602-6ea5b6e4f415;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/13177/6f83e7f67591a66352c9c83809ea3b9450199074/demo-fedora-demo-install/log-f55fe348-dff2-4cba-b602-6ea5b6e4f415.txt
```
2023-11-21T17:46:27Z (+238s): [ Make ]
make: Entering directory '/workspace/google/cloud/bigquery/quickstart'
Package opentelemetry_api was not found in the pkg-config search path.
Perhaps you should add the directory containing …
```
> doc(otel): fix fedora install instructions

- google/cloud/pubsub/internal/blocking_publisher_tracing_connection.cc
- google/cloud/pubsub/internal/blocking_publisher_tracing_connection_test.cc
- google/cloud/pubsub/internal/publisher_tracing_connection.cc
- google/cloud/pubsub/internal/publisher_tracing_connection_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13183)
> refactor(pubsub): rename to match the semantic convention

- ci/verify_quickstart/CMakeLists.txt
- google/cloud/google_cloud_cpp_common.cmake
- google/cloud/opentelemetry/CMakeLists.txt
- google/cloud/opentelemetry/quickstart/Makefile
- google/cloud/opentelemetry/quickstart/README.md
Fixes #10795
Add a Makefile to the OpenTelemetry exporter library quickstart, to show how to build with `make(1)`.
Also, now that `opentelemetry-cpp` installs its own `opentelemetry_*.pc` modules with proper compiler definitions, we no longer need to define `HAVE_ABSEIL` for them in our code. Yay.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13177)
> feat(otel): add Makefile

- google/cloud/pubsub/blocking_publisher_connection_test.cc
- google/cloud/pubsub/internal/blocking_publisher_tracing_connection.cc
- google/cloud/pubsub/internal/blocking_publisher_tracing_connection_test.cc
- google/cloud/pubsub/internal/publisher_tracing_connection.cc
- google/cloud/pubsub/internal/publisher_tracing_connection_test.cc
- google/cloud/pubsub/publisher_connection_test.cc
- Change topic.FullName() + " create" -> topic.topic_id() + " create"
- sc::kMessagingDestinationName, topic.FullName() ->  sc::kMessagingDestinationName, topic.topic_id() 
- sc::kMessagingDestinationTemplate, "topic" -> sc::kMessagingDestinationName, topic.FullName()
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13178)
> refactor(pubsub): change naming to use topic id not full name

- google/cloud/bigtable/examples/BUILD.bazel
Using the same rule for `howto_mock_data_api` as the other `bigtable_examples_unit_tests` means that the union of the dependencies for all test are used by each.  This is causing a problem for an important google_cloud_cpp consumer.
So, split out the `howto_mock_data_api` rule so that we can minimize its dependency count.  This avoids the downstream issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13189)
> cleanup(bigtable): split out howto_mock_data_api bazel rule

- google/cloud/bigtable/internal/mutate_rows_limiter.cc
- google/cloud/bigtable/internal/mutate_rows_limiter.h
- google/cloud/bigtable/internal/mutate_rows_limiter_test.cc
- google/cloud/bigtable/testing/mock_mutate_rows_limiter.h
I considered having the `ThrottlingMutateRowLimiter` hold a `CompletionQueue` and `Options const&`, but I think it is nicer to just pass the async sleeper (`std::function<future<void>(duration)>`) in.
---
I considered only having an async sleeper, and implementing the following:
```cc
void ThrottlingMutateRowsLimiter::Acquire() {
AsyncAcquire().get();
}
```
I do not want to do this, because in practice the async sleeper will be implemented by a `CompletionQueue`. I do not want to involve a `CompletionQueue` in the synchronous code paths.
A follow up PR will add a `CompletionQueue` as a parameter to the factory function.
---
Take this opportunity to reorder `MakeMutateRowsLimiter()` to return early from the simpler branch.
- - - …
> impl(bigtable): MutateRowsLimiter can do async

- google/cloud/bigtable/internal/async_bulk_apply.cc
- google/cloud/bigtable/internal/async_bulk_apply.h
- google/cloud/bigtable/internal/async_bulk_apply_test.cc
- google/cloud/bigtable/internal/data_connection_impl.cc
- google/cloud/bigtable/internal/data_connection_impl_test.cc
Plumb the `MutateRowsLimiter` through the layers of `AsyncBulkApply`.
Note that the implementation is not yet complete, as `MakeMutateRowsLimiter`'s async sleeper just returns immediately. That will take another 1 or 2 PRs, then we can call the thing done.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13197)
> impl(bigtable): plumb limiter thru AsyncBulkApply

- google/cloud/bigtable/internal/async_bulk_apply.cc
- google/cloud/bigtable/internal/async_row_reader.cc
- google/cloud/bigtable/internal/async_row_sampler.cc
- google/cloud/internal/async_polling_loop.cc
- google/cloud/internal/async_rest_polling_loop.h
- google/cloud/internal/async_rest_retry_loop.h
- google/cloud/internal/async_retry_loop.h
- google/cloud/internal/grpc_opentelemetry.h
- google/cloud/internal/grpc_opentelemetry_test.cc
Motivated by #12959 
I want to use a name other than "Async Backoff", so first generalize the function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13202)
> refactor: generalize name given to TracedAsyncBackoff

- google/cloud/bigtable/data_connection.cc
- google/cloud/bigtable/internal/mutate_rows_limiter.cc
- google/cloud/bigtable/internal/mutate_rows_limiter.h
- google/cloud/bigtable/internal/mutate_rows_limiter_test.cc
- google/cloud/bigtable/options.h
Fixes #12959 
Actually start setting async timers for the `AsyncBulkApply` limiting case.
Correct the record about when the option applies.
Fix the synchronous `TracingEnabled` test, which could succeed if no spans were created at all.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13203)
> feat(bigtable): throttling for AsyncBulkApply

- release/README.md
- Suggest the possibility of starting with the verbatim output of `release/changes.sh`, and doing all the edits with the review process.
- Remove the notion of including "updated ... API baselines" in the release, where it doesn't apply.
- Add a `ports` pathspec to the "git commit" command.
- Move the `./bootstrap-vcpkg.sh` invocation earlier in the vcpkg instructions so that `./vcpkg` is available when needed.
- Correct the `shell` tag on the "git push" command section.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13223)
> docs: slightly smarter release notes

- google/cloud/spanner/client.h
The overloads for `Client::ExecuteQuery()` used `@copydoc` to share documentation, but this meant they had overly general specifications, and included examples that did not apply to the overload at hand.
Let's instead give each overload an independent documentation block, so that the text and examples are closely related to the behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13221)
> docs(spanner): reorganize Client::ExecuteQuery() docs

- google/cloud/async_streaming_read_write_rpc.h
- google/cloud/internal/async_read_write_stream_auth.h
- google/cloud/internal/async_read_write_stream_auth_test.cc
- google/cloud/internal/async_read_write_stream_impl.h
- google/cloud/internal/async_read_write_stream_impl_test.cc
- google/cloud/internal/async_read_write_stream_logging.h
- google/cloud/internal/async_read_write_stream_logging_test.cc
- google/cloud/internal/async_read_write_stream_tracing.h
- google/cloud/internal/async_read_write_stream_tracing_test.cc
- google/cloud/mocks/mock_async_streaming_read_write_rpc.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13228)
> feat(common): read-write streaming RPCs metadata

- generator/integration_tests/tests/universe_domain_test.cc
These tests are being added to verify existing behavior that we want to preserve during the implementation of universe domain support.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13230)
> impl(generator): add tests to verify existing behavior of connection and options

- google/cloud/storage/async_writer.cc
- google/cloud/storage/async_writer.h
- google/cloud/storage/async_writer_connection.h
- google/cloud/storage/async_writer_test.cc
- google/cloud/storage/internal/async/writer_connection_finalized.cc
- google/cloud/storage/internal/async/writer_connection_finalized.h
- google/cloud/storage/internal/async/writer_connection_finalized_test.cc
- google/cloud/storage/internal/async/writer_connection_impl.cc
- google/cloud/storage/internal/async/writer_connection_impl.h
- google/cloud/storage/internal/async/writer_connection_impl_test.cc
- google/cloud/storage/internal/async/writer_connection_tracing.cc
- google/cloud/storage/internal/async/writer_connection_tracing_test.cc
- google/cloud/storage/mocks/mock_async_writer_connection.h
The request metadata is useful when troubleshooting upload problems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13232)
> impl(GCS+gRPC): capture metadata in async writer

- google/cloud/storage/async_reader.cc
- google/cloud/storage/async_reader.h
- google/cloud/storage/async_reader_connection.h
- google/cloud/storage/async_reader_test.cc
- google/cloud/storage/internal/async/reader_connection_impl.cc
- google/cloud/storage/internal/async/reader_connection_impl.h
- google/cloud/storage/internal/async/reader_connection_impl_test.cc
- google/cloud/storage/internal/async/reader_connection_tracing.cc
- google/cloud/storage/internal/async/reader_connection_tracing_test.cc
- google/cloud/storage/mocks/mock_async_reader_connection.h
The request metadata provides troubleshooting information to applications. It is also helpful in benchmarks to verify the right network path was used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13231)
> impl(GCS+gRPC): capture metadata in async reader

- google/cloud/internal/url_encode.cc
- google/cloud/internal/url_encode_test.cc
Fixes #13160 
Note that while `UrlEncode()` and `UrlDecode()` do not look like inverse functions, it is always the case that `UrlDecode(UrlEncode(x)) == x`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13224)
> cleanup: URL encode values outside `std::isprint`

- google/cloud/storage/internal/grpc/configure_client_context.cc
- google/cloud/storage/internal/grpc/configure_client_context_test.cc
GCS has settled on `/` as a separator between the bucket name and the upload id name.
Fixes #13026
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13238)
> cleanup(GCS+gRPC): simplify upload_id parsing

- google/cloud/storage/benchmarks/async_throughput_benchmark.cc
This is a rather large set of changes to the `AsyncClient` benchmark. The most significant change is that now it measures the aggregate throughput when doing multiple concurrent transfers. It still reports the per-stream throughput too. Other changes include:
- The benchmark can use the existing `storage::Client` (concurrently), this is useful to see if the `AsyncClient` provides any improvements.
- The benchmark reports the network peer used in each transfer, this is useful to troubleshoot the network path used (vs. requested) in each transfer.
- The benchmark reports the `x-guploader-uploadid` header, useful when troubleshooting problems and one needs help from the GCS team.
- The benchmark can randomize the background thread count, useful when trying to find good values for this …
> test(GCS+gRPC): redesign `AsyncClient` benchmark

- google/cloud/storage/async/client.h
- google/cloud/storage/async/connection.h
- google/cloud/storage/async/object_responses.h
- google/cloud/storage/examples/storage_async_samples.cc
- google/cloud/storage/internal/async/accumulate_read_object.cc
- google/cloud/storage/internal/async/accumulate_read_object.h
- google/cloud/storage/internal/async/accumulate_read_object_test.cc
- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl.h
- google/cloud/storage/internal/async/connection_tracing.cc
- google/cloud/storage/internal/async/connection_tracing_test.cc
- google/cloud/storage/mocks/mock_async_connection.h
- google/cloud/storage/tests/async_client_integration_test.cc
Use the same class for streaming downloads and range downloads. Fewer classes for us to explain, and fewer classes for customers to learn.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13252)
> cleanup(GCS+gRPC): `ReadPayload` for range downloads

- google/cloud/pubsub/internal/publisher_tracing_connection.cc
- google/cloud/pubsub/internal/publisher_tracing_connection_test.cc
- google/cloud/pubsub/internal/tracing_batch_sink.cc
- google/cloud/pubsub/internal/tracing_batch_sink_test.cc
Changes in https://github.com/open-telemetry/semantic-conventions/pull/545
- Fixes for the publisher
Publish span
- Remove the link # attribute
- Add a full name topic attribute
- Add a gcp_pubsub attribute
- Change publish to client not producer
Create span
- Remove topic attribute
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13263)
> refactor(pubsub): modify attributes according to otel spec

- generator/integration_tests/tests/golden_kitchen_sink_option_defaults_test.cc
- generator/integration_tests/tests/golden_thing_admin_option_defaults_test.cc
- generator/integration_tests/tests/universe_domain_test.cc
- google/cloud/bigquery/v2/minimal/internal/dataset_options_test.cc
- google/cloud/bigquery/v2/minimal/internal/job_options_test.cc
- google/cloud/bigquery/v2/minimal/internal/project_options_test.cc
- google/cloud/bigquery/v2/minimal/internal/table_options_test.cc
- google/cloud/internal/populate_common_options.cc
- google/cloud/internal/populate_common_options_test.cc
- google/cloud/pubsub/internal/defaults_test.cc
- google/cloud/spanner/internal/defaults_test.cc
As part of implementing `DetermineServiceEndpoint`, it was suggested that default hostnames should be fully qualified. In order to ease the transition of moving defaulting `EndpointOption` from `PopulateCommonOptions` to `DetermineServiecEndpoint`, this PR adds full qualification to `PopulateCommonOptions`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13254)
> impl: fully qualify default hostname for EndpointOption

- google/cloud/internal/grpc_request_metadata_test.cc
- google/cloud/testing_util/validate_metadata.cc
- google/cloud/testing_util/validate_metadata.h
Part of the work for #13275
Add a test helper to set server metadata on a `grpc::ClientContext`.
I decided to add a new `SetServerMetadata` method separate from `ValidateMetadataFixture::GetMetadata`, even though only one function can be called on any `grpc::ClientContext`. I do not think we need to both validate the client metadata in a context and return server metadata in the same context.
Add a unit test for `g::c::i::GetRequestMetadataFromContext()` using this helper.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13276)
> test: verify gRPC server metadata

- google/cloud/testing_util/validate_metadata.cc
- google/cloud/testing_util/validate_metadata.h
Part of the work for #13275 
Apologies for the churn. This is what #13276 should have looked like. I hadn't prepared the next PR when I sent that for review.
I have since learned that it is convenient for `GetMetadata()` to leave the `grpc::ClientContext` in a state where calling `GetServerInitialMetadata()` does not crash our tests. Now we complete the call, instead of cutting and running the second we get our hands on the metadata.
This also reduces some duplication, which is good, and damning of #13276
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13277)
> refactor: always exchange metadata in test helper

- google/cloud/bigtable/examples/bigtable_hello_instance_admin.cc
https://github.com/googleapis/google-cloud-cpp/blob/79d9455d2decae4c39beffcad33590e8ee1ef753/google/cloud/bigtable/examples/bigtable_hello_instance_admin.cc#L215
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13281)
> cleanup(bigtable): fix usage string in example

- generator/integration_tests/tests/golden_kitchen_sink_tracing_stub_test.cc
- generator/integration_tests/tests/golden_thing_admin_tracing_stub_test.cc
- google/cloud/internal/async_read_write_stream_tracing_test.cc
- google/cloud/internal/async_streaming_read_rpc_tracing_test.cc
- google/cloud/internal/async_streaming_write_rpc_tracing_test.cc
- google/cloud/internal/grpc_opentelemetry.cc
- google/cloud/internal/grpc_opentelemetry_test.cc
- google/cloud/internal/streaming_read_rpc_tracing_test.cc
- google/cloud/internal/streaming_write_rpc_tracing_test.cc
- google/cloud/pubsub/blocking_publisher_connection_test.cc
- google/cloud/pubsub/publisher_connection_test.cc
Fixes #13275 
Capture response metadata over gRPC in traces.
Give special handling to binary headers. I am open to other suggestions on how they should be displayed.
For the tests - note that `ValidatePropagator()` calls `ValidateMetadataFixture::GetMetadata()` under the hood, so it both adds a layer of testing and prevents crashes when trying to access the server metadata stored in the `grpc::ClientContext`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13278)
> feat(otel): capture gRPC response metadata in traces

- google/cloud/spanner/integration_tests/client_integration_test.cc
The service was rolled back (for unrelated reasons) so the test now fails.  Sigh.  Disable it until a roll forward is complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13283)
> test(spanner): disable DirectedReadWithinReadWriteTransaction test

- google/cloud/internal/future_base.h
- google/cloud/internal/future_coroutines.h
- google/cloud/internal/future_impl.h
- google/cloud/internal/future_impl_test.cc
- google/cloud/internal/future_then_meta.h
The implementation of futures uses a type-erased version of the continuation provided in `.then()`.  With this change:
- I renamed the class to more closely follow the style guide.
- I changed the class to receive the state of its (satisfied) future as an argument.
Part of the work for #13258
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13282)
> impl(common): `future` continuations consume state

- .bazelrc
- WORKSPACE.bazel
- bazel/google_cloud_cpp_deps.bzl
- ci/cloudbuild/builds/lib/bazel.sh
- ci/cloudbuild/builds/quickstart-bazel.sh
- ci/gha/builds/lib/bazel.sh
- ci/gha/builds/macos-bazel.sh
- ci/verify_current_targets/.bazelrc
- ci/verify_current_targets/WORKSPACE.bazel
- ci/verify_deprecated_targets/.bazelrc
- ci/verify_deprecated_targets/WORKSPACE.bazel
- generator/internal/scaffold_generator.cc
- generator/templates/WORKSPACE.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13274)
> chore(deps): update Bazel to v7

- google/cloud/bigtable/internal/defaults.cc
- google/cloud/bigtable/internal/defaults_test.cc
Motivated by #8331 / #12354
Connection refreshing only makes sense when running against production. We do not need it when running integration tests against the emulator.
While I doubt this will prevent any crashes, I know that attempting to refresh the connections after the emulator crashes produces a ton of logs. This PR will at least help with that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13327)
> ci(bigtable): no connection refreshing with emulator

- google/cloud/internal/populate_common_options_test.cc
Use a more realistic endpoint in our test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13330)
> cleanup: use real endpoints in common options test

- google/cloud/bigtable/data_connection.cc
- google/cloud/bigtable/internal/bigtable_channel_refresh_test.cc
- google/cloud/bigtable/internal/bigtable_stub_factory.cc
- google/cloud/bigtable/internal/bigtable_stub_factory.h
- google/cloud/bigtable/internal/bigtable_stub_factory_test.cc
- google/cloud/testing_util/mock_grpc_authentication_strategy.cc
- google/cloud/testing_util/mock_grpc_authentication_strategy.h
Part of the work for #13300 although not strictly necessary
Move creation of the `GrpcAuthenticationStrategy` outside of the stub factory.
The clearer separation between the interfaces makes our tests a little nicer.
Also introduce a helper to declutter stub factory tests that need to create mock authentication strategies. (I plan to reuse this).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13331)
> refactor(bigtable): pull auth strategy out of stub factory

- google/cloud/internal/populate_common_options.cc
- google/cloud/internal/populate_common_options_test.cc
Part of the work for #13115
Fixes #13301 Fixes #13302 Fixes #13293 Fixes #13295
Factor the `UniverseDomainOption` into the default endpoint in `PopulateCommonOptions`.
`storage` and `bigtable` do not call `PopulateCommonOptions`. They will need manual work, but it is not much.
The gRPC stub factories now have dead code. I will clean that up in a follow up.
---
I am marking the `pubsub` issues as fixed, although there is still this function which we probably want to deal with: https://github.com/googleapis/google-cloud-cpp/blob/3aa4aec44c9500142ec6008e0c79b80e9d47e716/google/cloud/pubsub/options.cc#L24-L28
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13334) …
> impl: heed universe domain in defaults

- google/cloud/pubsub/internal/tracing_batch_sink.cc
- google/cloud/pubsub/internal/tracing_batch_sink_test.cc
- google/cloud/testing_util/opentelemetry_matchers.h
Now that https://github.com/open-telemetry/opentelemetry-cpp/pull/2427 is in we can start an async span as a root span
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13285)
> impl(pubsub): start the publish span as a root span

- google/cloud/pubsub/options.cc
- google/cloud/pubsub/options_test.cc
Part of the work for #13115 
Pub/Sub has a standalone function that creates `Options` for an `IAMPolicyConnection`. Applications write code like:
```cc
Options options;
auto options = pubsub::IAMPolicyOptions(std::move(options));
auto conn = iam::MakeIAMPolicyConnection(options);
```
We need to incorporate the `UniverseDomainOption` in this function. (or else the library will set the `EndpointOption` and `MakeIAMPolicyConnection` will ignore the `UniverseDomainOption`).
Also while we are here, use the FQDN.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13341)
> impl(pubsub): support UniverseDomainOption for IAM

- google/cloud/pubsub/options.cc
Cleanup after #13341
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13347)
> cleanup(pubsub): no const for std::move

- google/cloud/storage/internal/grpc/stub.cc
- google/cloud/storage/internal/grpc/stub_test.cc
Fixes #13343 Fixes #13344 
Support `UniverseDomainOption` for GCS+gRPC. While we're here, use the FQDN.
Unroll the unit test for `EndpointOption` because I generally do not like branching in unit tests. Also, while we're here, set expectations on `AuthorityOption`.
---
For GCS+gRPC there is some example code to demonstrate direct path usage. It has hardcoded: `"google-c2p:///storage.googleapis.com"`. I don't think we should take any action w.r.t. `UniverseDomainOption` at this time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13346)
> impl(GCS+gRPC): support `UniverseDomainOption`

- google/cloud/pubsub/CMakeLists.txt
- google/cloud/pubsub/mocks/mock_pull_ack_handler.h
- google/cloud/pubsub/pubsub_client_unit_tests.bzl
- google/cloud/pubsub/pull_ack_handler.h
Part of https://github.com/googleapis/google-cloud-cpp/issues/13265
- Adds the pull ack handler test to the build files, we can't add any tests directly since we aren't modifying the inerface
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13349)
> impl(pubsub): add ack id and subscription to PullAckHandler::Impl

- cmake/AddPkgConfig.cmake
- google/cloud/compute/CMakeLists.txt
- protos/google/cloud/compute/CMakeLists.txt
Shorting the target names from `google_cloud_cpp_compute_*` to `compute_*` reduces the path length for intermediate artifacts, such as `.o` and `.obj` files. This prevents problems with MSVC, which is limited to 255 characters in file names.
Note that the target name is used as the default name for the output artifact (libraries in this case). This change overrides these defaults to preserve backwards compatibility.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13351)
> cleanup(compute): shorten target names

- google/cloud/pubsub/internal/default_pull_ack_handler.cc
- google/cloud/pubsub/internal/default_pull_ack_handler.h
- google/cloud/pubsub/internal/default_pull_ack_handler_test.cc
Part of https://github.com/googleapis/google-cloud-cpp/issues/13265
1/5 in a chain of PRs to add tracing for the settle span for the unary pull
1. https://github.com/googleapis/google-cloud-cpp/pull/13350
2. https://github.com/googleapis/google-cloud-cpp/pull/13353
3. https://github.com/googleapis/google-cloud-cpp/pull/13354
4. https://github.com/googleapis/google-cloud-cpp/pull/13358
5. https://github.com/googleapis/google-cloud-cpp/pull/13360
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13350)
> impl(pubsub): add default pull ack handler impls 

- google/cloud/pubsub/internal/tracing_pull_ack_handler.cc
- google/cloud/pubsub/internal/tracing_pull_ack_handler_test.cc
Part of https://github.com/googleapis/google-cloud-cpp/issues/13265
3/5 in a chain of PRs to add tracing for the settle span for the unary pull
1. https://github.com/googleapis/google-cloud-cpp/pull/13350
2. https://github.com/googleapis/google-cloud-cpp/pull/13353
3. https://github.com/googleapis/google-cloud-cpp/pull/13354
4. https://github.com/googleapis/google-cloud-cpp/pull/13358
5. https://github.com/googleapis/google-cloud-cpp/pull/13360
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13354)
> impl(pubsub): add links to tracing pull ack handler

- google/cloud/internal/populate_rest_options.cc
- google/cloud/internal/populate_rest_options_test.cc
Part of the work for #13361
We are copying the gRPC implementation. Of course I am just noticing that in the implementation, setting the `*TracingOptionsOption` will override the `GOOGLE_CLOUD_CPP_TRACING_OPTIONS`, which is at odds with our ADR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13368)
> fix: respect logging format env var in `compute`, `sql`

- google/cloud/pubsub/internal/subscriber_connection_impl.cc
- google/cloud/pubsub/subscriber_connection_test.cc
Part of https://github.com/googleapis/google-cloud-cpp/issues/13265
5/5 in a chain of PRs to add tracing for the settle span for the unary pull
1. https://github.com/googleapis/google-cloud-cpp/pull/13350
2. https://github.com/googleapis/google-cloud-cpp/pull/13353
3. https://github.com/googleapis/google-cloud-cpp/pull/13354
4. https://github.com/googleapis/google-cloud-cpp/pull/13358
5. https://github.com/googleapis/google-cloud-cpp/pull/13360
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13360)
> impl(pubsub): use ack handler factory

- google/cloud/pubsub/internal/tracing_pull_ack_handler.cc
Closes https://github.com/googleapis/google-cloud-cpp/issues/13265
- Makes `CreateLinks` and `MaybeAddLinkAttributes` more generic so they can be re-used in other places
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13371)
> refactor(pubsub): make helper linking functions so they can be shared

- google/cloud/pubsub/internal/publisher_stub_factory.cc
- google/cloud/pubsub/internal/publisher_stub_factory.h
- google/cloud/pubsub/topic_admin_connection.cc
`MakeDefaultPublisherStub` and `MakeRoundRobinPublisherStub` were two ways to say the same thing. Remove one.
I notice that the handwritten topic admin connection stub includes the round robin decorator. That predates this PR. It is probably not worth doing anything about, given that we want to move to the generated admin clients anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13388)
> refactor(pubsub): dedup internal function

- ci/cloudbuild/builds/check-api.sh
This would have saved me a commit on a different PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13391)
> ci: check-api skips grpc namespace

- google/cloud/spanner/samples/samples.cc
It appears that us-east1 now has DataBoost OA capacity.
Fixes #11201.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13392)
> test(spanner): remove PartitionDataBoostOption sample workaround

- google/cloud/internal/populate_rest_options.cc
- google/cloud/internal/populate_rest_options_test.cc
Fixes #13393 (although we would prefer a solution that both reuses connections and uses fully qualified domain names)
While it is strange to set the `EndpointOption` to be fully qualified, then strip the ending, note that:
- This way we keep using FQDN over gRPC
- We are already manipulating `EndpointOption` in `PopulateRestOptions` after it is set in `PopulateCommonOptions`.
---
If the application supplies us with a custom FQDN via `EndpointOption`, we might leave it as is, and not reuse connections. :shrug:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13396)
> fix(rest): reuse connections in `sql`, `compute`

- google/cloud/storage/async/client.h
- google/cloud/storage/async/connection.h
- google/cloud/storage/examples/storage_async_mock_samples.cc
- google/cloud/storage/examples/storage_async_samples.cc
- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl.h
- google/cloud/storage/internal/async/connection_impl_test.cc
- google/cloud/storage/internal/async/connection_tracing.cc
- google/cloud/storage/internal/async/connection_tracing_test.cc
- google/cloud/storage/mocks/mock_async_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13395)
> cleanup(GCS+gRPC): `AsyncConnection::Async*` is overkill

- google/cloud/internal/populate_rest_options.cc
- google/cloud/internal/populate_rest_options_test.cc
If you want me to do something, you have to ask me twice:
https://github.com/googleapis/google-cloud-cpp/pull/13363#discussion_r1436722777
https://github.com/googleapis/google-cloud-cpp/pull/13396#discussion_r1441103622
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13397)
> cleanup(rest): stricter schema checking in `EndpointOption`

- google/cloud/storage/examples/storage_async_samples.cc
See https://github.com/googleapis/google-cloud-cpp/actions/runs/7405693533/job/20149036049#step:5:2692
I obviously missed my own comments in the last refactor:
https://github.com/googleapis/google-cloud-cpp/blob/800121693bc5608af67b0efdbb47c4aff56f8fa7/google/cloud/storage/examples/storage_async_samples.cc#L341-L343
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13398)
> fix(GCS+gRPC): restore build on Windows

- google/cloud/credentials.h
- google/cloud/internal/grpc_access_token_authentication.cc
- google/cloud/internal/grpc_access_token_authentication.h
- google/cloud/pubsub/integration_tests/blocking_publisher_integration_test.cc
- google/cloud/pubsub/integration_tests/publisher_integration_test.cc
- google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
- google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
- google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
`UseInsecureChannelOption` seems unnecessary and the builds will either vindicate or embarrass me.
Note that we are not losing coverage for the GUAC integration tests in spanner / pubsub. The `UnifiedCredentialsOption` is defaulted by the library according to the value of the emulator env var. So the other tests in those fixtures exercise the GUAC code paths.
For history, the option was added in #7430 and since #8058, we have not needed the special treatment for gRPC Access Token credentials.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13413)
> cleanup: remove internal GUAC option

- external/googleapis/renovate.sh
To help the internal automation team, copy the PiperOrigin-RevId from the latest googleapis commit into our SHA-update PR message.
Fixes #13402.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13410)
> impl: capture the PiperOrigin-RevId from the googleapis commit

- .bazelrc
- bazel/workspace0.bzl
- bazel/workspace1.bzl
- bazel/workspace2.bzl
- bazel/workspace3.bzl
With this PR the project can be compiled with Bazel v7.  We need to override some of the dependencies used by gRPC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13412)
> feat: support Bazel v7

- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl.h
Avoid copying `Options` when possible.
Part of the work for #13385
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13415)
> impl(GCS+gRPC): optimize `Start*Upload()`

- google/cloud/pubsub/internal/default_pull_ack_handler.cc
- google/cloud/pubsub/internal/default_pull_ack_handler.h
Part of https://github.com/googleapis/google-cloud-cpp/issues/13298
3/4 in a chain
1. https://github.com/googleapis/google-cloud-cpp/pull/13377
2. https://github.com/googleapis/google-cloud-cpp/pull/13378
3. https://github.com/googleapis/google-cloud-cpp/pull/13379
4. https://github.com/googleapis/google-cloud-cpp/pull/13389
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13379)
> impl(pubsub): use factory to create pull lease manager

- google/cloud/storage/async/client.h
- google/cloud/storage/async/client_test.cc
- google/cloud/storage/examples/storage_async_samples.cc
- google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
- google/cloud/storage/storage_client_grpc_unit_tests.bzl
- google/cloud/storage/tests/async_client_integration_test.cc
Implements a function to start or resumable uploads with client-side buffering. With this buffer at hand the client library can automatically resume the upload and resend data (if needed).
Fixes #13385
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13417)
> impl(GCS+gRPC): `AsyncClient::StartBufferedUpload()`

- ci/cloudbuild/builds/msan.sh
Part of the work for #13320
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13420)
> ci: revert `msan` build to Bazel 6.4.0

- google/cloud/storage/async/connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13424)
> docs(GCS+gRPC): better comments for `AsyncConnection`

- google/cloud/internal/oauth2_compute_engine_credentials.cc
- google/cloud/internal/oauth2_compute_engine_credentials.h
- google/cloud/internal/oauth2_compute_engine_credentials_test.cc
- google/cloud/internal/oauth2_credentials.cc
- google/cloud/internal/oauth2_credentials.h
- google/cloud/internal/oauth2_external_account_credentials.h
- google/cloud/internal/oauth2_impersonate_service_account_credentials.h
- google/cloud/internal/oauth2_impersonate_service_account_credentials_test.cc
- google/cloud/internal/oauth2_minimal_iam_credentials_rest.h
- google/cloud/internal/oauth2_minimal_iam_credentials_rest_test.cc
- google/cloud/storage/internal/impersonate_service_account_credentials_test.cc
fixes #13434 
fixes #13433
Also had to update the return type of the `Credentials::universe_domain` accessor from `std::string` to `StatusOr<std::string>`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13435)
> impl(oauth2): compute credentials query MDS for universe domain

- google/cloud/internal/oauth2_service_account_credentials.cc
- google/cloud/internal/oauth2_service_account_credentials.h
- google/cloud/internal/oauth2_service_account_credentials_test.cc
- google/cloud/storage/oauth2/service_account_credentials.cc
Support universe domain in OAuth2 `ServiceAccountCredentials`, but only for self-signed JWTs.
fixes #13439 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13440)
> impl(oauth2): support self-signed JWT ServiceAccountCredentials

- doc/contributor/howto-guide-adding-generated-libraries.md
Updating the markdown in `checkers.sh` uses the features list. We should first add the new library as a feature before running checkers.
Automated steps like injecting environment variables in the docs will show up in the "regenerate libraries..." commit, not the "manually update..." commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13443)
> cleanup(docs): bury automated generate library steps

- google/cloud/bigtable/internal/defaults.cc
We were unconditionally creating a `grpc::GoogleDefaultCredentials()` object. In some environments[^1] this object does not exist and the creation of it can crash code.
We cannot use GUAC options, because legacy clients also use this code path to default options, but they do not support GUAC.
[^1]:  hint: it rhymes with doogle-dee
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13463)
> cleanup(bigtable): credential defaults

- google/cloud/completion_queue.h
- google/cloud/internal/async_rest_retry_loop.h
- google/cloud/internal/async_retry_loop.h
- google/cloud/internal/resumable_streaming_read_rpc.h
This was added in C++14
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13457)
> cleanup: use `std::decay_t` over `absl::decay_t`

- google/cloud/completion_queue_test.cc
I don't really know what the test is doing, but it seems the intention was to join the `workers` before the `runners`. Adding these threads to the end of `runners` defeats the purpose.
This PR seems to speed up the test 10x, locally. Hopefully we will see less timeouts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13467)
> cleanup: fix CQ TimerCancel test

- google/cloud/internal/minimal_iam_credentials_stub.cc
- google/cloud/internal/minimal_iam_credentials_stub_test.cc
Part of the work for #13115 
GCS+gRPC uses this stub for `SignBlob`. It is also used by gRPC impersonate service account credentials.
Add tests for this function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13466)
> feat: support `UniverseDomainOption` in gRPC IAM stub

- google/cloud/internal/service_endpoint.cc
- google/cloud/internal/service_endpoint_test.cc
Part of the work for #13345 
In light of #13357, accept non-FQDN in our universe domain helper.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13465)
> impl: accept non-FQDN in `UniverseDomainEndpoint(...)`

- google/cloud/bigtable/internal/default_row_reader.cc
- google/cloud/bigtable/internal/default_row_reader.h
- google/cloud/bigtable/internal/default_row_reader_test.cc
This thing is like our `StreamRange` class, for bigtable rows. Before we create the stream, call `RetryContext::PreCall(...)`. When the stream finishes (by returning a variant holding a `Status`), call `RetryContext::PostCall(...)`.
Given the structure of the code, we need to hold the `grpc::ClientContext` in the class. Delete it at our earliest convenience.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13468)
> impl(bigtable): support bigtable cookie in `ReadRow(s)`

- google/cloud/bigtable/internal/bulk_mutator.cc
- google/cloud/bigtable/internal/bulk_mutator.h
- google/cloud/bigtable/internal/bulk_mutator_test.cc
This thing holds state for `Table::BulkApply` calls. The `SetServerMetadata(...)` test changes are to avoid asserts in gRPC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13469)
> impl(bigtable): support bigtable cookie in `BulkApply`

- google/cloud/bigtable/internal/async_row_sampler.cc
- google/cloud/bigtable/internal/async_row_sampler.h
- google/cloud/bigtable/internal/async_row_sampler_test.cc
Again, we need to hold onto the `grpc::ClientContext`. Reset the ptr when we are done with it.
Note that only tests that retry need the `metadata_fixture_.SetServerMetadata(...)` treatment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13479)
> impl(bigtable): support bigtable cookie in `AsyncSampleRows`

- google/cloud/bigtable/internal/data_connection_impl.cc
- google/cloud/bigtable/internal/data_connection_impl_test.cc
More of the same...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13477)
> impl(bigtable): support bigtable cookie in `SampleRows`

- google/cloud/bigtable/internal/async_row_reader.cc
- google/cloud/bigtable/internal/async_row_reader.h
- google/cloud/bigtable/internal/async_row_reader_test.cc
Very similar to #13479...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13480)
> impl(bigtable): support bigtable cookie in `AsyncReadRow(s)`

- google/cloud/bigtable/internal/async_bulk_apply.cc
- google/cloud/bigtable/internal/async_bulk_apply.h
- google/cloud/bigtable/internal/async_bulk_apply_test.cc
Fixes #13447 
Very similar to #13479...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13481)
> impl(bigtable): support bigtable cookie in `AsyncBulkApply`

- google/cloud/pubsub/options.cc
- google/cloud/pubsub/options_test.cc
Follow up to #13341 
The `AuthorityOption` default also needs to respect the `UniverseDomainOption`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13484)
> impl(pubsub): Authority respects UniverseDomainOption for IAM

- google/cloud/bigtable/internal/defaults.cc
- google/cloud/bigtable/internal/defaults_test.cc
Follow up to #13335 
The `AuthorityOption` default also needs to respect the `UniverseDomainOption`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13485)
> impl(bigtable): authority respects UniverseDomainOption

- google/cloud/storage/internal/grpc/stub.cc
- google/cloud/storage/internal/grpc/stub_test.cc
Follow up to #13346
The `AuthorityOption` default also needs to respect the `UniverseDomainOption`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13486)
> impl(GCS+gRPC): authority respects UniverseDomainOption

- google/cloud/internal/populate_common_options.cc
- google/cloud/internal/populate_common_options_test.cc
This necessary in order for authentication to succeed for gRPC services (at a minimum).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13483)
> impl: apply universe_domain to default_endpoint for AuthorityOption

- google/cloud/opentelemetry/quickstart/README.md
The devsite docs "trace-overview" page is being deleted, updated the links to go directly to the new page.
cc @padelaney
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13499)
> docs: Update OpenTelemetry quickstart links

- CMakeLists.txt
- ci/cloudbuild/builds/quickstart-production.sh
- google/cloud/universe_domain/CMakeLists.txt
- google/cloud/universe_domain/demo/BUILD.bazel
- google/cloud/universe_domain/demo/CMakeLists.txt
- google/cloud/universe_domain/demo/bigquery.cc
- google/cloud/universe_domain/demo/compute.cc
- google/cloud/universe_domain/demo/pubsub.cc
- google/cloud/universe_domain/demo/storage.cc
This adds the remaining service demos specified for the universe_domain feature. Additional auth related demos are next.
Demos now are built with cmake and execute as part of the quickstart-production builds.
part of the work for #13495
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13496)
> impl: add remaining universe_domain service demos

- google/cloud/bigtable/internal/bigtable_stub_factory.cc
I forgot to do this as part of #13447 
This flag tells the server that our client supports the feature. Welcome to Bigtable.
Note that the feature flags are tested. We just check that the serialized value is non-empty and in the format we expect: https://github.com/googleapis/google-cloud-cpp/blob/9d54f32c812f693bcf86543fc3be8adee5e923c3/google/cloud/bigtable/internal/bigtable_stub_factory_test.cc#L247-L248
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13502)
> feat(bigtable): support bigtable routing cookies

- google/cloud/pubsub/internal/default_pull_ack_handler.cc
- google/cloud/pubsub/internal/default_pull_ack_handler.h
- google/cloud/pubsub/internal/default_pull_ack_handler_test.cc
- google/cloud/pubsub/internal/pull_ack_handler_factory_test.cc
Closes https://github.com/googleapis/google-cloud-cpp/issues/13298
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13428)
> feat(pubsub): add lease management for unary pull

- google/cloud/pubsub/internal/subscriber_tracing_connection.cc
- google/cloud/pubsub/internal/subscriber_tracing_connection_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13508)
> refactor(pubsub): split the messaging destination attributes on receive span

- google/cloud/pubsub/internal/pull_lease_manager_factory_test.cc
- google/cloud/pubsub/internal/tracing_pull_lease_manager.cc
- google/cloud/pubsub/internal/tracing_pull_lease_manager_test.cc
Also change the subscription template attribute into a gcp.project_id and destination.name attribute.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13507)
> refactor(pubsub): s/extend/modack

- google/cloud/pubsub/internal/pull_ack_handler_factory_test.cc
- google/cloud/pubsub/internal/tracing_pull_ack_handler.cc
- google/cloud/pubsub/internal/tracing_pull_ack_handler_test.cc
- google/cloud/pubsub/subscriber_connection_test.cc
Also add a few attributes to the ack/nack spans based on updated semantic conventions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13506)
> refactor(pubsub): rename s/settle/ack or s/settle/nack

- google/cloud/pubsub/internal/blocking_publisher_tracing_connection.cc
- google/cloud/pubsub/internal/blocking_publisher_tracing_connection_test.cc
For the blocking pull connection
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13512)
> refactor(pubsub): split attributes for blocking publisher

- google/cloud/google_cloud_cpp_common.bzl
- google/cloud/google_cloud_cpp_common.cmake
- google/cloud/internal/retry_info.h
- google/cloud/status.cc
- google/cloud/status.h
- google/cloud/status_test.cc
Store and provide an accessor for `google.rpc.RetryInfo` in our `google::cloud::Status`es.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13515)
> impl: add `RetryInfo` to `Status`

- generator/integration_tests/tests/golden_kitchen_sink_option_defaults_test.cc
- generator/integration_tests/tests/golden_thing_admin_option_defaults_test.cc
- generator/integration_tests/tests/universe_domain_test.cc
- google/cloud/bigquery/v2/minimal/internal/dataset_options_test.cc
- google/cloud/bigquery/v2/minimal/internal/job_options_test.cc
- google/cloud/bigquery/v2/minimal/internal/project_options_test.cc
- google/cloud/bigquery/v2/minimal/internal/table_options_test.cc
- google/cloud/internal/populate_common_options.cc
- google/cloud/internal/populate_common_options_test.cc
- google/cloud/internal/populate_rest_options.cc
- google/cloud/internal/populate_rest_options_test.cc
- google/cloud/internal/service_endpoint.h
- google/cloud/pubsub/internal/defaults_test.cc
- google/cloud/spanner/internal/defaults_test.cc
Part of the work for #13501 
Totally minor point: We arrange the order in some of `PopulateCommonOptions` because we expect that the `EndpointOption` is more likely to be overridden by an application than the `AuthorityOption`. (and thus we are more likely to get the micro-optimization from std::move)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13516)
> cleanup: stop using FQDN in default endpoints

- google/cloud/pubsub/options.cc
- google/cloud/pubsub/options_test.cc
Part of the work for #13501
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13517)
> cleanup(pubsub): stop using FQDN in default endpoint

- google/cloud/bigtable/client_options.cc
- google/cloud/bigtable/client_options_test.cc
- google/cloud/bigtable/internal/defaults.cc
- google/cloud/bigtable/internal/defaults_test.cc
Part of the work for #13501, reverts #13305
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13518)
> cleanup(bigtable): stop using FQDN in default endpoint

- google/cloud/pubsub/internal/default_pull_ack_handler.cc
- google/cloud/pubsub/internal/pull_ack_handler_factory_test.cc
Import was failing on some clang-tidy include issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13520)
> chore(pubsub): address clang-tidy issues

- ci/cloudbuild/dockerfiles/centos-7.Dockerfile
- ci/cloudbuild/dockerfiles/demo-alpine-stable.Dockerfile
- ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
- ci/cloudbuild/dockerfiles/demo-debian-bookworm.Dockerfile
- ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
- ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
- ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
- ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
- ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
- ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
- ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
- ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-publish-docs.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-m32.Dockerfile
- ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile
- doc/packaging.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13526)
> ci(otel): use abi 2.0 in all cmake builds except oldest deps

- google/cloud/bigtable/internal/default_row_reader.cc
- google/cloud/bigtable/internal/default_row_reader.h
- google/cloud/bigtable/internal/default_row_reader_test.cc
Motivated by #13514 
Abstract the sleeper used by the `DefaultRowReader`, so we can supply a mock in our tests.
Currently, we assume that if the backoff policy is called, we will sleep for that long. Soon the class will need to sleep an amount that is not determined by the backoff policy. Having this injection point lets us test that we are sleeping for the right amount.
Modify one test to ensure that we are actually calling the sleeper.
Note that I prefer to default parameters for internal APIs when we want the default 99% of the time. I think this makes the code cleaner.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13524)
> refactor(bigtable): abstract sleeper in `DefaultRowReader`

- cmake/GoogleCloudCppCommon.cmake
- google/cloud/pubsub/CMakeLists.txt
Part of the work for #5782 
We were copying all of the mock files into both `include/google/cloud/pubsub/mocks` and `include/google/cloud/pubsub/admin/mocks`, without preserving the relative directory structure.
The handwritten and generated admin mock files have the same name, so I think we would first install the generated admin mocks (because they were first in the list), then we would overwrite them with the handwritten admin mocks.
Before:
```
docker:fedora-latest-cmake$ ls /h/google-cloud-cpp-installed/include/google/cloud/pubsub/mocks
mock_ack_handler.h		      mock_publisher_connection.h  mock_subscriber_connection.h
mock_blocking_publisher_connection.h  mock_pull_ack_handler.h	   mock_subscription_admin_connection.h
mock_exactly_once_ack_handler.h       mock_schema_connection.h …
```
> fix(pubsub): install admin mocks

- google/cloud/bigtable/internal/data_connection_impl.cc
- google/cloud/bigtable/internal/default_row_reader.cc
- google/cloud/bigtable/internal/default_row_reader.h
- google/cloud/bigtable/internal/default_row_reader_test.cc
We do not need to test all of the `RetryInfo` logic. That is done in `internal/retry_info_helper_test.cc`. We test enough to ensure that `bigtable_internal::BackoffOrBreak(...)` is called.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13536)
> impl(bigtable): support `RetryInfo` in `ReadRow(s)`

- CHANGELOG.md
As @scotthart points out, I forgot to include the YYYY-MM for the v2.21.0 changes.
https://github.com/googleapis/google-cloud-cpp/pull/13540#pullrequestreview-1857481598
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13543)
> cleanup: add date to latest release

- cmake/GoogleCloudCppCommon.cmake
- cmake/GoogleCloudCppLibrary.cmake
- google/cloud/pubsub/CMakeLists.txt
Motivated by #5782 
This helper will be convenient for when we deal with the remaining handwritten libs. They will look like `pubsub`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13545)
> refactor: helper to install mocks in cmake

- google/cloud/bigtable/internal/defaults.cc
- google/cloud/bigtable/internal/defaults_test.cc
- google/cloud/grpc_options.h
Add `EnableServerRetriesOption`, an option that tells the client to use the server's recommendation if the server returns a `RetryInfo` in the error details.
Add the option now in `grpc_utils` (where I expect it will belong), but in an internal namespace. This unblocks other work that needs to happen regardless of where the option ends up.
Default this option to true in bigtable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13547)
> impl: add `EnableServerRetriesOption`

- ci/etc/expected_install_directories
- ci/verify_current_targets/CMakeLists.txt
- generator/standalone_main.cc
- google/cloud/bigtable/CMakeLists.txt
Part of the work for #5782 
Install `bigtable_mocks`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13551)
> feat(bigtable): install mocks library

- google/cloud/pubsub/samples/topic_admin_samples.cc
Ran once, went from 180 topics -> 40. 
I think we might be able to delete some more (cloud-cpp) too, but I will check with someone before adding that
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13556)
> cleanup(pubsub): delete topics older than 3 days

- google/cloud/bigtable/internal/data_connection_impl.cc
- google/cloud/bigtable/internal/data_connection_impl_test.cc
- google/cloud/bigtable/internal/default_row_reader.cc
- google/cloud/bigtable/internal/default_row_reader.h
Heed the `EnableServerRetriesOption` in `ReadRows`. Also rename the member variable used by `DefaultRowReader` to match the option name.
It may not look like it, but there is thinking involved here! We could have added a `bool enable_server_retries_` to the `ReadRowsParams` struct.
I do not think we should do that because:
- the struct should only contain parameters specific to `ReadRows()`
- `EnableServerRetriesOption` applies to all RPCs
- it is more like an extension of the retry/backoff policy options which we do not include in the struct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13565)
> impl(bigtable): heed `RetryInfo` in `ReadRows()`

- google/cloud/bigtable/internal/bulk_mutator.cc
- google/cloud/bigtable/internal/bulk_mutator.h
- google/cloud/bigtable/internal/bulk_mutator_test.cc
- google/cloud/bigtable/internal/data_connection_impl.cc
Related to #12359
Prefer to pass `Options` explicitly vs. accessing the `CurrentOptions()` in `BulkMutator`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13566)
> refactor(bigtable): no `CurrentOptions` in `BulkMutator`

- google/cloud/bigtable/internal/async_row_reader_test.cc
I forgot to actually set an expectation in this test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13571)
> test(bigtable): verify bigtable cookie expectation

- google/cloud/pubsub/samples/subscription_admin_samples.cc
- google/cloud/pubsub/testing/random_names.cc
Went from 240 subs -> 14.
I think this is good since Pub/Sub is also charging for outstanding message storage. Now if our builds fail, the next one will delete the resource
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13557)
> cleanup(pubsub): delete old subs

- google/cloud/pubsub/subscription_admin_client.h
- google/cloud/pubsub/subscription_admin_connection.h
- google/cloud/pubsub/topic_admin_client.h
- google/cloud/pubsub/topic_admin_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13585)
> docs(pubsub): add doxygen comment to deprecate handwritten apis

- google/cloud/bigtable/internal/async_row_sampler.cc
- google/cloud/bigtable/internal/async_row_sampler.h
- google/cloud/bigtable/internal/async_row_sampler_test.cc
- google/cloud/bigtable/internal/data_connection_impl.cc
I decided I don't feel like testing `enable_server_retries(*current)` in the `DataConnectionImpl`, in the same way we don't bother testing `retry_policy(*current)`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13568)
> impl(bigtable): heed `RetryInfo` in `AsyncSampleRows`

- google/cloud/bigtable/internal/bulk_mutator.cc
- google/cloud/bigtable/internal/bulk_mutator.h
- google/cloud/bigtable/internal/bulk_mutator_test.cc
- google/cloud/bigtable/internal/data_connection_impl.cc
- google/cloud/bigtable/internal/data_connection_impl_test.cc
Support `RetryInfo` in `BulkApply`. In the `DataConnectionImpl` this means retrying errors that might not normally be retried, and using the backoff value if present. In the `BulkMutator` this means marking any mutation as retryable, regardless of idempotency, when `RetryInfo` is present.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13581)
> impl(bigtable): heed `RetryInfo` in `BulkApply()`

- generator/generator_config.textproto
- google/cloud/storagecontrol/v2/storage_control_connection_idempotency_policy.cc
The protos for this service lack the `http` annotations we normally use to determine if an operation is idempotent.  Override the few RPCs that are idempotent by virtual of being read-only operations.
Motivated by #13595 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13606)
> fix(storagecontrol): override idempotency policy

- generator/internal/printer.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13611)
> cleanup(generator): no need for exceptions #ifdef

- generator/generator.cc
- generator/generator_config.proto
- generator/integration_tests/golden_config.textproto
- generator/integration_tests/test_request_id.yaml
- generator/internal/descriptor_utils.cc
- generator/internal/descriptor_utils.h
- generator/internal/descriptor_utils_test.cc
- generator/internal/make_generators.cc
- generator/internal/make_generators.h
- generator/internal/scaffold_generator.cc
- generator/internal/scaffold_generator.h
- generator/internal/service_code_generator.cc
- generator/internal/service_code_generator.h
- generator/standalone_main.cc
This sets the method variables needed to support `request_id`-like fields. As these variables need the service config YAML file, we need to make the location of these file available to the code generator. We also need to parse the file and propagate the results to the `CreateMethodVars()` function.
We use the API index file in the googleapis repository to find the location of this service config YAML file. That does not work for the golden protos used in integration tests, so we need a way to override it.
Part of the work for #13595
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13612)
> impl(generator): method variables for `request_id`

- generator/integration_tests/golden/v1/internal/request_id_connection_impl.cc
- generator/integration_tests/golden/v1/internal/request_id_connection_impl.h
- generator/integration_tests/golden/v1/request_id_client.h
- generator/integration_tests/golden/v1/request_id_connection_idempotency_policy.cc
- generator/integration_tests/test_request_id.proto
- generator/integration_tests/tests/request_id_connection_impl_test.cc
- generator/integration_tests/tests/request_id_idempotency_test.cc
- generator/internal/connection_impl_generator.cc
- generator/internal/connection_impl_generator.h
- generator/internal/idempotency_policy_generator.cc
- google/cloud/storagecontrol/v2/internal/storage_control_connection_impl.cc
- google/cloud/storagecontrol/v2/internal/storage_control_connection_impl.h
- google/cloud/storagecontrol/v2/storage_control_connection_idempotency_policy.cc
With this change the generator populates the `request_id`-like fields
and also uses the field to determine if a request is idempotent.
Fixes #13595
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13615)
> feat(generator): support `request_id`-like fields

- google/cloud/bigtable/internal/bulk_mutator_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13616)
> cleanup(bigtable): use more general RowKeyType

- google/cloud/pubsub/internal/tracing_batch_sink.cc
- google/cloud/pubsub/internal/tracing_batch_sink_test.cc
Note server.address is the "Server domain name if available without reverse DNS lookup."
https://opentelemetry.io/docs/specs/semconv/general/attributes/#server-attributes 
using the network attributes would be what we are setting the grpc peer values with (https://opentelemetry.io/docs/specs/semconv/attributes-registry/network/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13617)
> impl(pubsub): add server.address attribute

- google/cloud/bigtable/internal/async_row_reader.cc
- google/cloud/bigtable/internal/async_row_reader.h
- google/cloud/bigtable/internal/async_row_reader_test.cc
- google/cloud/bigtable/internal/data_connection_impl.cc
Part of the work for #13514
and basically the same as #13568
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13609)
> impl(bigtable): heed `RetryInfo` in `AsyncReadRows`

- google/cloud/bigtable/internal/async_bulk_apply.cc
- google/cloud/bigtable/internal/async_bulk_apply.h
- google/cloud/bigtable/internal/async_bulk_apply_test.cc
- google/cloud/bigtable/internal/data_connection_impl.cc
and basically the same as #13568
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13602)
> impl(bigtable): heed `RetryInfo` in `AsyncBulkApply`

- google/cloud/storage/benchmarks/aggregate_upload_throughput_options.cc
Use a more conventional `true` value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13625)
> cleanup(storage): quash an aggregate_upload_throughput benchmark warning

- ci/cloudbuild/builds/clang-cxx20.sh
- ci/cloudbuild/triggers/clang-cxx20-ci.yaml
- ci/cloudbuild/triggers/clang-cxx20-pr.yaml
Clang and GCC detect different errors, this is particularly true with new features, such as coroutines.
For an example see #13577 
Alternatively, we could switch the cxx20 build to only use Clang, your call.  I launched the build to warm up the cache and make sure there are no pre-existing errors:
https://console.cloud.google.com/cloud-build/builds;region=us-east1/a129adc5-8b40-4a8f-937d-b0a5acad1810?project=936212892354
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13626)
> ci: add clang-cxx20 build

- doc/packaging.md
What libraries need `libcurl` and friends has changed over time.
We do not need Protobuf v21.x for most libraries, and that is the version we should highlight here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13631)
> docs: fix dependency details

- google/cloud/storage/client.h
- google/cloud/storage/google_cloud_cpp_storage.bzl
- google/cloud/storage/google_cloud_cpp_storage.cmake
- google/cloud/storage/internal/grpc/object_request_parser.cc
- google/cloud/storage/internal/grpc/object_request_parser_test.cc
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/internal/object_requests_test.cc
- google/cloud/storage/soft_deleted.h
Part of the changes for #13575
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13644)
> feat(storage): support soft-deleted objects

- cmake/GoogleCloudCppFeatures.cmake
It is possible someone was using `-DGOOGLE_CLOUD_CPP_ENABLE=mocks` to build `googleapis` for example, but I doubt it. I think it is a bug that trying to build `mocks` (which depends on `common`) requires gRPC. So let's make the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13643)
> fix: `mocks` feature does not require gRPC

- google/cloud/pubsub/internal/subscriber_tracing_connection.cc
Unblocks #13627 
The propagator used for messages is a no-op if the incoming span is invalid:
https://github.com/open-telemetry/opentelemetry-cpp/blob/4eb99f9e05f45c0ea1461858417e7e52135874c5/api/include/opentelemetry/trace/propagation/http_trace_context.h#L45-L48
In this case, our message receiver does not add a new context to the stack:
https://github.com/open-telemetry/opentelemetry-cpp/blob/4eb99f9e05f45c0ea1461858417e7e52135874c5/api/include/opentelemetry/trace/propagation/http_trace_context.h#L63
The latest update to opentelemetry-cpp copies trace flags from the current context:
https://github.com/open-telemetry/opentelemetry-cpp/blob/423ecacdf62196731d888621e0dfa2e8cc023b4a/sdk/src/trace/tracer.cc#L64
So we should check that the contexts are not equal.
- - - …
> cleanup(pubsub): don't link invalid messages

- google/cloud/internal/async_read_write_stream_impl.h
- google/cloud/internal/async_read_write_stream_impl_test.cc
- google/cloud/internal/async_streaming_read_rpc_impl.h
- google/cloud/internal/async_streaming_read_rpc_impl_test.cc
- google/cloud/internal/async_streaming_write_rpc_impl.h
- google/cloud/internal/async_streaming_write_rpc_impl_test.cc
The streaming RPC wrappers should save the `Options` in effect when the RPC is created, and then set the `OptionsSpan` to reflect the initial values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13648)
> fix(common): streaming RPCs save initial options

- ci/cloudbuild/cloudbuild.yaml
I did not think about what would happen to the
`download-runner-image-attempt-1` step if `kaniko-attempt-1` fails. Obviously the download step would fail too, but we can safely ignore that failure.
Part of the work for #6438 
Tested on https://console.cloud.google.com/cloud-build/builds;region=us-east1/19677ef2-0432-406a-9487-aca8f72beb1c;tab=detail?project=cloud-cpp-testing-resources
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13652)
> ci(gcb): the first kaniko attempt can fail

- google/cloud/internal/async_retry_loop.h
- google/cloud/internal/async_retry_loop_test.cc
- google/cloud/internal/retry_loop.h
- google/cloud/internal/retry_loop_helpers.cc
- google/cloud/internal/retry_loop_helpers.h
- google/cloud/internal/retry_loop_helpers_test.cc
Why are we doing this? Because it will make it easier to add common handling for `RetryInfo`. For context, here is the full change: https://github.com/googleapis/google-cloud-cpp/commit/3f4c403e6d09bed216ad79d95c2c8eba66d234c0
The tests come from here, with some modifications:
https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/bigtable/internal/retry_info_helper_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13632)
> refactor: prepare to support `RetryInfo` in retry loops

- google/cloud/pubsub/samples/samples.cc
- google/cloud/pubsub/samples/topic_admin_samples.cc
- google/cloud/pubsub/topic_admin_client.h
I moved these to the respective generated admin sample file and moved google3 to point at those new files, so deleting tags is OK.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13653)
> cleanup(pubsub): remove duplicate old samples

- google/cloud/internal/async_retry_loop.h
- google/cloud/internal/async_retry_loop_test.cc
- google/cloud/internal/retry_loop.h
- google/cloud/internal/retry_loop_helpers.cc
- google/cloud/internal/retry_loop_helpers.h
- google/cloud/internal/retry_loop_helpers_test.cc
- google/cloud/internal/retry_loop_test.cc
Retry on `RetryInfo` in the common loops. This overrides idempotency and any supplied backoff policies.
This rounds out the Bigtable client calls.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657)
> impl: heed `RetryInfo` in common loops

- google/cloud/pubsub/samples/samples.cc
- google/cloud/pubsub/subscription_admin_client.h
~None of these samples are referenced in google3, so can be removed here immediately~
Note: ListSubscriptions has a DevReel tag, but I moved it already.
- cleanup(pubsub): remove snapshot and subscription admin samples from samples.cc
- remove samples from docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13668)
> cleanup(pubsub): remove snapshot and subscription admin samples from samples.cc

- google/cloud/securitycenter/BUILD.bazel
- google/cloud/securitycenter/CMakeLists.txt
All indications are that there were actually no macro/enum name conflicts on macOS, so limit the exclusions to Windows (where "SERVICE_STOP" is the current culprit).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13674)
> ci(securitycenter): re-enable on macOS

- google/cloud/pubsub/samples/samples.cc
- google/cloud/pubsub/subscription_admin_client.h
Exists in subscription_admin_samples.cc now
Also, moved the tag in google3 already.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13676)
> cleanup(pubsub): remove handwritten create subscription from samples.cc

- google/cloud/storage/client.h
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/google_cloud_cpp_storage.bzl
- google/cloud/storage/google_cloud_cpp_storage.cmake
- google/cloud/storage/include_folders_as_prefixes.h
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/tests/object_integration_test.cc
Part of the work for #13561
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13683)
> feat(storage): support listing folders as prefixes

- CMakeLists.txt
- cmake/GoogleCloudCppCommon.cmake
- cmake/GoogleCloudCppLibrary.cmake
- google/cloud/bigquery/bigquery_rest.cmake
- google/cloud/bigtable/CMakeLists.txt
- google/cloud/compute/CMakeLists.txt
- google/cloud/google_cloud_cpp_common.cmake
- google/cloud/pubsub/CMakeLists.txt
- google/cloud/pubsublite/CMakeLists.txt
- google/cloud/spanner/CMakeLists.txt
- google/cloud/sql/CMakeLists.txt
- google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
Motivated by #13621 
Consumers of `google-cloud-cpp` who want to test their code can use this flag to install mocks, without needing to build all of our unit tests, internal testing infrastructure.
We create mocking libraries (which are all header only) and install them by default (even when `BUILD_TESTING=OFF`). For many months, we only did this in Pub/Sub and GCS+gRPC, but in the latest release, we started installing mocks for all GAPICs. (And in this release, for all libraries except compute).
These libraries link to GoogleTest, which can be hard to find. This can break some (atypical?) builds. (See the linked issue, which uses `FetchContent()`.
- The option controls whether or not we install the mock libraries. It could control whether or not we define mock targets at all. Or whether …
> feat: cmake option to skip building mock libraries

- google/cloud/storage/doc/storage-grpc.dox
- google/cloud/storage/grpc_plugin.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13688)
> docs(GCS+gRPC): add contact info

- google/cloud/opentelemetry/internal/resource_detector_impl.cc
Part of the work for #12359.  I am trying to remove the retry loops with implicit options, at this point they are mostly unused.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13691)
> impl(otel): use explicit options in retry loop

- external/googleapis/renovate.sh
Move the `external/googleapis/update_libraries.sh` invocation from the script to within the `generate-libraries` build by marking the latter as triggered by a PR instead of manually.  This means we will no longer be depending on the locally-installed version of bazel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13690)
> impl: make googleapis renovate.sh (more) hermetic

- google/cloud/internal/async_rest_retry_loop.h
- google/cloud/internal/async_rest_retry_loop_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13693)
> cleanup: remove unused `AsyncRestRetryLoop`

- generator/generator_config.textproto
- google/cloud/storagecontrol/v2/internal/storage_control_retry_traits.h
- google/cloud/storagecontrol/v2/storage_control_connection.h
The `StorageControl` service uses:
- `kResourceExhausted` for request rate control, this is unusual, but
allowed by the AIPs and should be retryable.
- `kInternal`, `kUnknown` and `kDeadlineExceeded` are not allowed by the
AIPs, but are (unfortunately) raised by the service when it should use
something like `kUnavailable`. Fortunately, the service also supports
idempotency via `request_id()` fields, so it is safe to retry these
codes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13696)
> impl(storagecontrol): retry on more error codes 

- google/cloud/bigtable/internal/bulk_mutator.cc
- google/cloud/bigtable/internal/bulk_mutator_test.cc
- google/cloud/bigtable/internal/data_connection_impl.cc
- google/cloud/bigtable/internal/data_connection_impl_test.cc
- google/cloud/bigtable/internal/defaults.cc
- google/cloud/bigtable/internal/defaults_test.cc
- google/cloud/common_options.h
- google/cloud/grpc_options.h
As discussed in the team meeting, put this thing in `common` because conceptually it is agnostic of transport.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13698)
> feat: promote `EnableServerRetriesOption`

- generator/integration_tests/CMakeLists.txt
- generator/integration_tests/tests/mock_request_id_stub.h
- generator/integration_tests/tests/request_id_connection_impl_test.cc
Part of the work for #13704
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13709)
> refactor: split `MockRequestIdServiceStub`

- google/cloud/bigtable/internal/bigtable_stub_factory.cc
Fixes #13514 
Flip the feature flag that tells Bigtable that our client supports `RetryInfo`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13708)
> feat(bigtable): use server retry hints

- google/cloud/internal/invocation_id_generator.cc
Use `MakeDefaultPRNG()` to initialize the PRNG (pseudo-random number generator) in `InvocationIdGenerator`.  This function consumes the same amount of entropy from the OS as the previous call, but uses `std::seed_seq` to fill the initial state of the PRNG. AFAIK, `std::seed_seq` produces better distributed seeds from the same entropy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13711)
> impl(common): improve `InvocationIdGenerator` seed

- .github/CODEOWNERS
Syntax from: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
```
/build/logs/ @doctocat
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13702)
> chore: share GCS libraries with cloud-storage-dpe team

- google/cloud/storage/internal/grpc/object_metadata_parser.cc
- google/cloud/storage/internal/grpc/object_metadata_parser_test.cc
- google/cloud/storage/internal/object_metadata_parser.cc
- google/cloud/storage/object_metadata.cc
- google/cloud/storage/object_metadata.h
- google/cloud/storage/object_metadata_test.cc
Part of the work for #13575
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13728)
> feat(storage): support soft delete timestamps

- CHANGELOG.md
- doc/deprecated.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13731)
> cleanup: fix version # merge conflict and move to deprecated.md

- google/cloud/pubsub/subscription_admin_client.h
- google/cloud/pubsub/subscription_admin_connection.h
Updated changelog in https://github.com/googleapis/google-cloud-cpp/pull/13731
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13736)
> cleanup(pubsub): deprecate the subscription admin handwritten api

- google/cloud/spanner/BUILD.bazel
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/google_cloud_cpp_spanner.bzl
- google/cloud/spanner/proto_enum.h
- google/cloud/spanner/proto_enum_test.cc
- google/cloud/spanner/proto_message.h
- google/cloud/spanner/proto_message_test.cc
- google/cloud/spanner/spanner_client_unit_tests.bzl
- google/cloud/spanner/testing/singer.proto
`spanner::ProtoMessage<M>` represents a protobuf message, `M`, and `spanner::ProtoEnum<E>` a protobuf enumeration, `E`.
Also add a proto message and enum, `SingerInfo` and `Genre`, for testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13743)
> feat(spanner): add representations for the Spanner PROTO/ENUM types

- google/cloud/bigtable/internal/defaults.cc
- google/cloud/bigtable/internal/defaults_test.cc
Bigtable data plane does not use `PopulateCommonOptions(...)` so we copy the handling of `GOOGLE_CLOUD_CPP_OPENTELEMETRY_TRACING`:
https://github.com/googleapis/google-cloud-cpp/blob/c7c14df54c3d79c9d8f5c33b19f8f11d474fa281/google/cloud/internal/populate_common_options.cc#L67-L70
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13748)
> fix(bigtable): respect `GOOGLE_CLOUD_CPP_OPENTELEMETRY_TRACING`

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13747)
> feat(spanner): add spanner::Value support for ProtoEnum/ProtoMessage

- google/cloud/spanner/integration_tests/data_types_integration_test.cc
- google/cloud/spanner/testing/database_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13756)
> feat(spanner): add integration tests for proto columns

- google/cloud/spanner/proto_message.h
- google/cloud/spanner/value.cc
Use `internal::DebugString()` to implement the output operators for `spanner::ProtoMessage<M>` and a PROTO `spanner::Value`.  This allows us to avoid the inter-release vagaries of `Message::ShortDebugString()` (by using a `google::protobuf::TextFormat::Printer` directly), and that allows us to make more-portable test expectations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13758)
> impl(spanner): constrain spanner::ProtoMessage<M>::operator<<()

- google/cloud/spanner/BUILD.bazel
- google/cloud/spanner/integration_tests/BUILD.bazel
- google/cloud/spanner/samples/BUILD.bazel
- google/cloud/spanner/samples/samples.cc
Also add "singer_cc_proto" dependencies to the tests that use it directly, as would be required if strict checking was enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13759)
> feat(spanner): add samples for proto columns

- generator/generator_config.textproto
- google/cloud/speech/doc/environment-variables.dox
- google/cloud/speech/v2/internal/speech_option_defaults.cc
- google/cloud/speech/v2/internal/speech_option_defaults.h
- google/cloud/speech/v2/speech_connection.cc
- google/cloud/speech/v2/speech_connection.h
part of the work for #13729 
In Speech V2 locations (aka regions) can be specified for recognizers, but the connection must also be configured for that same location. While explicitly setting `Options` can achieve this result, adding a location aware `MakeSpeechConnection` overload streamlines this process. When the location is provided to `MakeSpeechConnection`, the SDK handles setting the appropriate `Options` on behalf of the user.
e.g.
```
namespace speech = ::google::cloud::speech_v2;
auto client = speech::SpeechClient(speech::MakeSpeechConnection("asia-southeast1"));
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13757)
> fix(speech): enable location specific connections

- google/cloud/storage/client_options.cc
- google/cloud/storage/client_options_test.cc
Fixes #13765
Same story as #13748. `storage` and `bigtable` do not call `PopulateCommonOptions()`, so we need to manually handle `GOOGLE_CLOUD_CPP_OPENTELEMETRY_TRACING`. They are the only two such libraries that need this manual works.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13766)
> fix(storage): respect `GOOGLE_CLOUD_CPP_OPENTELEMETRY_TRACING`

- google/cloud/spanner/internal/logging_result_set_reader.cc
- google/cloud/spanner/internal/logging_result_set_reader.h
- google/cloud/spanner/internal/logging_result_set_reader_test.cc
When Spanner picked up generic support for streaming-RPC logging, it also continued to log via `LoggingResultSetReader`. Here we remove the redundant request/response logging, leaving only logging of the `PartialResultSet` resume token and resumption indicator.
Fixes #12185.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13768)
> impl(spanner): de-dup logging of streaming-RPC responses

- google/cloud/spanner/integration_tests/data_types_integration_test.cc
- google/cloud/spanner/testing/database_integration_test.cc
Remove some allowances for previously missing emulator functionality:
- support for PostgreSQL syntax to quote identifiers
- support for JSON types
- support for NUMERIC types
The emulator was updated in #13764.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13770)
> cleanup(spanner): remove workarounds not needed by latest emulator

- google/cloud/bigtable/benchmarks/benchmark_options.cc
- google/cloud/storage/benchmarks/aggregate_download_throughput_options.cc
If we really wanted to obfuscate the code we should have used `"false"`. What a wasted opportunity.
FWIW, I found these as warnings in (`-Wnonnull-compare`) in one of the asan builds.  I am not sure why these warnings are not turned on in our `-Wall -Werror` builds.  Maybe a different compiler?
```
Step #5:                  from google/cloud/bigtable/benchmarks/benchmark_options.cc:15:
Step #5: external/com_google_absl/absl/types/optional.h: In member function 'T absl::lts_20240116::optional<T>::value_or(U&&) && [with U = const char (&)[5]; T = bool]':
Step #5: external/com_google_absl/absl/types/optional.h:524:37: warning: 'nonnull' argument 'v' compared to NULL [-Wnonnull-compare]
```
- - - …
> cleanup: `"true"` is `true` but we can do better

- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl_test.cc
- google/cloud/storage/internal/async/default_options.cc
- google/cloud/storage/internal/async/default_options_test.cc
- google/cloud/storage/internal/async/rewriter_connection_impl_test.cc
Fixed a couple of places that did not use `DefaultOptionsAsync()` to initialize the options for an `AsyncClient` or `*Connection`. Also initialize the `ResumePolicyOption` in these defaults.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13776)
> impl(GCS+gRPC): default options for `AsyncClient`

- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl.h
- google/cloud/storage/internal/async/connection_impl_test.cc
Refactor the code so the downloads are started by a factory function. In a future PR this function will be wrapped by a class that resumes the downloads if they get interrupted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13779)
> refactor(GCS+gRPC): use factory to start downloads

- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl_test.cc
Sometimes an asynchronous download may get interrupted. We need to resume the download from the last received byte.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13784)
> feat(GCS+gRPC): resume asynchronous downloads

- google/cloud/internal/populate_common_options.cc
- google/cloud/internal/populate_common_options_test.cc
- google/cloud/universe_domain_options.h
Part of the work for #13122. I will need separate PRs for `bigtable`, `storage`.
Add `GOOGLE_CLOUD_UNIVERSE_DOMAIN` to control the `UniverseDomainOption`.
Any of `EndpointOption` / `AuthorityOption` / endpoint env var will take precedence over the universe domain env var. It is best to keep them separated.
Document this.
---
We ought to be setting `UniverseDomainOption` with the value we end up using when the environment variable is present.
I considered modifying `internal::UniverseDomainEndpoint` to set the `UniverseDomainOption` if the environment variable is set. It would have led to a smaller PR, but I didn't like the idea of passing it an `Options&`. The function would be doing too much in my opinion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> impl: add GOOGLE_CLOUD_UNIVERSE_DOMAIN

- .clang-format
Fixes #13786
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13788)
> cleanup: always put system headers at the bottom

- google/cloud/storage/async/object_responses.h
- google/cloud/storage/google_cloud_cpp_storage.cmake
- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl.h
- google/cloud/storage/internal/async/connection_impl_test.cc
- google/cloud/storage/internal/async/read_payload_impl.h
- google/cloud/storage/internal/async/reader_connection_impl.cc
- google/cloud/storage/internal/async/reader_connection_impl.h
- google/cloud/storage/internal/async/reader_connection_impl_test.cc
- google/cloud/storage/internal/async/reader_connection_resume.cc
- google/cloud/storage/internal/async/reader_connection_resume.h
- google/cloud/storage/internal/async/reader_connection_resume_test.cc
- google/cloud/storage/storage_client_testing.bzl
- google/cloud/storage/testing/mock_hash_validator.h
Full object downloads include the full object checksums, which can be used to validate the download. Note that per-message checksums cannot detect if some messages are missing, duplicated, or reordered.
Fixes #12116
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13795)
> impl(GCS+gRPC): checksum full object downloads

- google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc
- google/cloud/spanner/admin/integration_tests/backup_integration_test.cc
- google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc
- google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/admin/integration_tests/instance_admin_rest_integration_test.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/database_admin_integration_test.cc
- google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
Rather than sometimes simply skipping tests of features supposedly unsupported by the emulator, add expectations that the emulator actually fails in some way.
Some tests were already written with failure expectations, and that allowed us to actively discover what tests could be enabled after the recent SDK version update.  Extend that tactic here.
Indeed, this very process exposed some new cases where we no longer need to make allowance for emulator shortfalls.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13799)
> test(spanner): add expectations for missing emulator functionality

- google/cloud/spanner/samples/postgresql_samples.cc
- google/cloud/spanner/samples/samples.cc
While it is inconvenient to actively notice new emulator support in the samples (unlike the integration tests in #13799), we can still do manual testing to remove obsolete exclusions after an SDK update.
Here we enable some of the Google SQL samples, and almost all of the PostgreSql samples, that were previously skipped on the emulator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13803)
> test(spanner): enable more samples on the emulator

- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl_test.cc
Fixes #13452
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13807)
> impl(GCS+gRPC): timeouts for async `WriteObject()`

- ci/cloudbuild/builds/clang-tidy.sh
- google/cloud/storage/quickstart/quickstart_async.cc
- google/cloud/storage/quickstart/quickstart_grpc.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13818)
> cleanup: enable examples in `clang-tidy*` builds

- ci/cloudbuild/builds/asan.sh
- ci/cloudbuild/builds/bazel-oldest.sh
- ci/cloudbuild/builds/bazel-otel-abi-2.sh
- ci/cloudbuild/builds/bazel-targets.sh
- ci/cloudbuild/builds/conformance.sh
- ci/cloudbuild/builds/coverage.sh
- ci/cloudbuild/builds/development.sh
- ci/cloudbuild/builds/grpc-at-head.sh
- ci/cloudbuild/builds/integration-production.sh
- ci/cloudbuild/builds/lib/cloudcxxrc.sh
- ci/cloudbuild/builds/lib/integration.sh
- ci/cloudbuild/builds/libcxx.sh
- ci/cloudbuild/builds/msan.sh
- ci/cloudbuild/builds/otel-disabled-bazel.sh
- ci/cloudbuild/builds/protobuf-at-head.sh
- ci/cloudbuild/builds/tsan.sh
- ci/cloudbuild/builds/ubsan.sh
- ci/cloudbuild/builds/xsan.sh
- ci/etc/cloudcxxrc
- google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
- google/cloud/internal/ci/run_integration_tests_emulator_bazel.sh
- google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh
- google/cloud/spanner/ci/run_integration_tests_emulator_bazel.sh
- google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
Sometimes we want to run the build scripts on our workstations, but we are only interested in storage, or pubsub, or spanner. We can do this for CMake-builds using `.cloudcxxrc` and the `development.sh` build. With this change any Bazel-based build can be configured to compile a subset of the targets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13824)
> ci: Bazel builds use .cloudcxxrc

- ci/cloudbuild/build.sh
- google/cloud/spanner/ci/lib/spanner_emulator.sh
Cleanup the messages and comments surrounding the launch of the Spanner gRPC and HTTP emulators.
Also take this opportunity to log the Cloud SDK component versions during startup, when applicable.  This will allow us to clearly see the emulator release, for example.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13831)
> test(spanner): clarify emulator startup messages and comments

- google/cloud/compute/BUILD.bazel
- google/cloud/compute/CMakeLists.txt
- protos/google/cloud/compute/BUILD.bazel
- protos/google/cloud/compute/CMakeLists.txt
MSVC cannot handle paths over 254 characters. Bazel creates protobuf generated files in (relatively) deep directories that include the name of the proto library, and the path to the proto file (twice in our case).
Using a single proto library for all the protos creates shorter paths. We still have a duplicate `google/cloud/compute/${service}`, but at least the target name is short.
Fixes #13835
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13836)
> fix(compute): shorten paths for Bazel+MSVC

- google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
- google/cloud/storage/benchmarks/throughput_options.cc
- google/cloud/storage/benchmarks/throughput_options.h
- google/cloud/storage/benchmarks/throughput_options_test.cc
Creating a bucket each time complicates using the benchmark as a prober.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13859)
> test(storage): use pre-existing bucket in benchmark

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
Represented as a `float` in C++, so no need for a wrapper class.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13862)
> feat(spanner): add spanner::Value support for TypeCode::FLOAT32

- google/cloud/testing_util/is_proto_equal.cc
- google/cloud/testing_util/is_proto_equal.h
Add a proto-message matcher that supports approximate equality checks on floating-point fields.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13873)
> test(common): add an IsProtoApproximatelyEqual matcher

- CMakeLists.txt
- ci/cloudbuild/builds/cmake-oldest-deps.sh
- ci/cloudbuild/builds/m32.sh
- ci/gha/builds/lib/cmake.sh
- google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
With Protobuf < v23.x (aka 4.23.x) we need to enable some ugly workarounds to use `ctype=CORD` fields in the storage library. With this change CMake automatically sets the workaround option if needed. Bazel assumes the version of Protobuf is >= v23 and disables the workarounds by default. That is reasonable because Bazel users update more often (or at least we believe that).
Part of the work for #13875
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13877)
> feat(cmake): automatically set `ctype=CORD` workarounds

- ci/cloudbuild/dockerfiles/centos-7.Dockerfile
- ci/cloudbuild/dockerfiles/demo-alpine-stable.Dockerfile
- ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
- ci/cloudbuild/dockerfiles/demo-debian-bookworm.Dockerfile
- ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
- ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
- ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-m32.Dockerfile
- doc/packaging.md
In some platforms the default `pkg-config` or `pkgconf` version is broken. They either take too long (minutes) to analyze the dependencies of something like `Abseil`, and/or produce dependencies in the wrong order. The 2.2.x series of `pkgconf` seems to solve these problems. It seems better to use a newer version of `pkgconf` rather than using an old version of `pkg-config`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13868)
> ci: use pkgconf-2.2.x

- google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc
- google/cloud/storage/benchmarks/aggregate_upload_throughput_benchmark.cc
- google/cloud/storage/benchmarks/async_throughput_benchmark.cc
- google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
- google/cloud/storage/doc/environment-variables.dox
- google/cloud/storage/grpc_plugin.cc
- google/cloud/storage/grpc_plugin.h
- google/cloud/storage/grpc_plugin_test.cc
- google/cloud/storage/tests/smoke_test_grpc.cc
Mark it as deprecated and stop using it in our tests, benchmarks, examples, etc.  We still respect the previous behavior, but we should move the class no later than the next major version.
Part of the work for #13875
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13879)
> cleanup(GCS+gRPC): deprecate `GrpcPluginOption`

- ci/cloudbuild/builds/lib/ctest.sh
Move to `env -C "${dir}" ctest"` instead of `ctest --test-dir "${dir}"`.
Not only does it hide the `Testing/Temporary/LastTest.log` file away in the build directory, but it also seems to produce the "Total Tests" output we're looking for, which means the cmake-oldest-deps build will now actually run tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13881)
> ci: modify ctest invocation in ctest::has_no_tests()

- ci/cloudbuild/builds/cmake-install.sh
- ci/verify_current_targets/CMakeLists.txt
- google/cloud/storage/config-grpc.cmake.in
- google/cloud/storage/google_cloud_cpp_storage.cmake
- google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
- google/cloud/storage/quickstart/CMakeLists.txt
Create a new `google_cloud_cpp_storage_grpc` for the GCS+gRPC plugin. With this change the contents of the `google_cloud_cpp_storage` are always the same, regardless of whether GCS+gRPC is enabled.
It is easier to reason about the packages if their contents are always consistent.
Part of the work for #13875
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13883)
> cleanup(GCS+gRPC): split package for GCS+gRPC

- google/cloud/storage/BUILD.bazel
- google/cloud/storage/benchmarks/BUILD.bazel
- google/cloud/storage/benchmarks/CMakeLists.txt
- google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
The `GOOGLE_CLOUD_CPP_ENABLE_CTYPE_CORD_WORKAROUND` pre-processor macro does not need to be part of the public flags for the library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13885)
> cleanup(GCS+gRPC): remove one public -D flag

- google/cloud/pubsub/internal/batch_callback.h
- google/cloud/pubsub/internal/batch_callback_wrapper.h
- google/cloud/pubsub/internal/default_batch_callback.h
- google/cloud/pubsub/internal/subscription_lease_management.cc
- google/cloud/pubsub/internal/subscription_lease_management.h
- google/cloud/pubsub/internal/subscription_lease_management_test.cc
- google/cloud/pubsub/internal/tracing_batch_callback.cc
- google/cloud/pubsub/internal/tracing_batch_callback_test.cc
- google/cloud/pubsub/testing/mock_batch_callback.h
[13720](https://github.com/googleapis/google-cloud-cpp/issues/13720)
- Store the batch callback on the lease management layer
- Modify the EndMessage function to add an attribute in the BatchCallback interface messaging.gcp_pubsub.result 
- End the span in the lease management layer if the message expires.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13888)
> impl(pubsub): add expire message functionality

- google/cloud/storage/oauth2/google_credentials_test.cc
- google/cloud/storage/oauth2/service_account_credentials_test.cc
Just like OpenSSL may not work if PKCS#12 is disabled, Windows may lack a provider for the PKCS#12 keyfiles too. I tried to use a fairly narrow way to detect that this is indeed the problem.
Related to #13746
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13893)
> test(storage): tolerate PKCS#12 errors on WIN32

- google/cloud/storage/oauth2/google_credentials.cc
- google/cloud/storage/oauth2/google_credentials_test.cc
We no longer encourage using
`google::cloud::storage::oauth2::GoogleDefaultCredentials()`, but in this case the function was dropping details about an error condition that are probably useful.
Related to #13746
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13897)
> fix(storage): preserve full Status in default creds

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/options.h
- google/cloud/spanner/transaction.cc
Mutations within an ExecutePartitionedDml(), the mutation-groups overload of a CommitAtLeastOnce(), or any read-write transaction, will not be recorded in change streams that track the modified columns if this new option is set and the change stream has the `allow_txn_exclusion` option set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13898)
> feat(spanner): add ExcludeTransactionFromChangeStreamsOption

- google/cloud/opentelemetry/internal/monitored_resource.cc
- google/cloud/opentelemetry/internal/monitored_resource.h
- google/cloud/opentelemetry/internal/monitored_resource_test.cc
Related to #11775 
In our Cloud Trace and Cloud Monitoring exporters, we copy over resource attributes. Our GCP Resource Detector only uses strings for the value of these attributes. But in the off-chance that an application is using a different resource detector, handle these additional attribute types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13902)
> impl(otel): support non-string resource attributes

- generator/internal/discovery_to_proto.cc
- generator/internal/discovery_to_proto.h
- generator/standalone_main.cc
The GenerateProtosFromDiscoveryDoc is called in two places- standalone main() and unit tests. We set the default to false in the `standalone_main()` (so it is written in parallel) and the default param to true so that when it is called in the unit tests it is set and the output is not obscured.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13895)
> impl(generator): add a disable parallel write flag

- docfx/doxygen2markdown.cc
- docfx/doxygen2markdown_test.cc
I missed that a `<para>` element may have nested `<para>` elements. There are about 300 element in a `<para>`, most of them symbols.
An example of the trouble highlighted in #13911
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13912)
> feat(docfx): supported nested paragraphs

- google/cloud/opentelemetry/internal/time_series.cc
- google/cloud/opentelemetry/internal/time_series.h
- google/cloud/opentelemetry/internal/time_series_test.cc
Add ability to translate `SumPointData` metrics to a `google::monitoring::v3::TimeSeries`.
New helpers like `ToValueType(...)` and `ToNonEmptyTimeInterval(...)` will get more use as we add conversions from other metric types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13917)
> impl(otel): process `SumPointData` metrics

- google/cloud/opentelemetry/internal/time_series.cc
- google/cloud/opentelemetry/internal/time_series.h
- google/cloud/opentelemetry/internal/time_series_test.cc
Gauge metrics are treated almost the same as Sum metrics. The differences are:
- The metric kind is `GAUGE`
- They represent a point in time, so we only set the end timestamp.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13919)
> impl(otel): convert `LastValuePointData` to protos

- google/cloud/common_options.h
- google/cloud/grpc_options.cc
- google/cloud/grpc_options_test.cc
- google/cloud/rest_options.h
Fixes #13928
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13933)
> feat(common): `QuotaUserOption` for gRPC-based libs

- google/cloud/common_options.h
- google/cloud/grpc_options.cc
- google/cloud/grpc_options_test.cc
- google/cloud/internal/rest_set_metadata.cc
- google/cloud/internal/rest_set_metadata_test.cc
Fixes #13929
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13936)
> feat(common): introduce `FieldMaskOption`

- generator/internal/discovery_resource.cc
- generator/internal/discovery_resource.h
I found this helpful while working on https://github.com/googleapis/google-cloud-cpp/pull/13955, so adding it. It is only meant for debugging, so I didn't add any tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13956)
> cleanup(generator): add a DebugString() method for a DiscoveryResource

- google/cloud/opentelemetry/internal/time_series.cc
- google/cloud/opentelemetry/internal/time_series.h
- google/cloud/opentelemetry/internal/time_series_test.cc
Helper function to convert from `opentelemetry::sdk::metrics::ResourceMetrics` to `google::monitoring::v3::CreateTimeSeriesRequest`.
For unit testing, we have more involved testing for conversions from `*PointData` -> `google::monitoring::v3::TimeSeries`. In these tests, we only need to verify that the `TimeSeries` helpers are used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13951)
> impl(otel): `CreateTimeSeriesRequest` helper

- google/cloud/storage/async/idempotency_policy.cc
- google/cloud/storage/async/idempotency_policy.h
- google/cloud/storage/async/idempotency_policy_test.cc
- google/cloud/storage/google_cloud_cpp_storage_grpc.bzl
- google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/default_options.cc
- google/cloud/storage/internal/async/default_options_test.cc
- google/cloud/storage/storage_client_grpc_unit_tests.bzl
We need a way to determine of a proto-request is idempotent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13968)
> impl(GCS+gRPC): proto-based  idempotency policy

- google/cloud/opentelemetry/monitoring_exporter.cc
- google/cloud/opentelemetry/monitoring_exporter_test.cc
Implement the exporter, especially the `Export()` function.
Note that there are still more line items to clean up in the linked issue (e.g. respecting `noexcept` qualifiers). We also will need to generalize the exporter to handle things like:
- support for Google-defined metrics
- options to set the metric type prefix (currently `"workload.googleapis.com/"`)
But as is, this should be a working exporter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13970)
> impl(otel): GCM export

- google/cloud/storage/internal/grpc/bucket_request_parser.cc
- google/cloud/storage/internal/grpc/object_request_parser.cc
- google/cloud/storage/internal/grpc/stub.cc
- google/cloud/storage/internal/retry_object_read_source.cc
- google/cloud/storage/internal/tracing_connection_test.cc
We should only log from the logging decorators. These were debugging remnants that are no longer relevant. I took the opportunity to remove unused `"google/cloud/log.h"` includes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13975)
> cleanup(storage): remove logging noise

- google/cloud/opentelemetry/internal/time_series.cc
- google/cloud/opentelemetry/internal/time_series_test.cc
Instead of setting the `unit` in each TimeSeries helper, set it once in `ToRequest()`.
Note that we still verify the unit in the `ToRequest()` unit tests, e.g.: https://github.com/googleapis/google-cloud-cpp/blob/788a072a705816e43f6b7229f4c688c547b8d972/google/cloud/opentelemetry/internal/time_series_test.cc#L514
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13974)
> refactor(otel): set unit once

- google/cloud/opentelemetry/internal/recordable_test.cc
We do string substitutions on `google::protobuf::*`, so we need to qualify the namespace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13983)
> cleanup(otel): full namespace for protobuf

- doc/contributor/howto-guide-declare-a-library-ga.md
At some point I "simplified" the declare GA instructions by removing this critical step. :monkey:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13989)
> cleanup(docs): fix declare GA docs

- google/cloud/bigtable/internal/traced_row_reader_test.cc
This code isn't currently built in oogle3gay, so we didn't catch it earlier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13992)
> cleanup(bigtable): `RowKeyType` again

- google/cloud/internal/trace_propagator.cc
https://en.cppreference.com/w/cpp/container/span/span
The constructor I am trying to use is explicit in C++20 land.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13994)
> cleanup(otel): explicit span ctor

- google/cloud/spanner/samples/samples.cc
With the recent release [1], a query without any Distributed Union is also considered partitionable. Modify the comment a bit to avoid inconsistency with the documentation.
[1] https://cloud.google.com/spanner/docs/release-notes#December_19_2023
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13993)
> cleanup(spanner): update samples.cc for comments on is_partitionable

- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl.h
- google/cloud/storage/internal/async/writer_connection_impl.cc
- google/cloud/storage/internal/async/writer_connection_impl.h
- google/cloud/storage/internal/async/writer_connection_impl_test.cc
Change the `AsyncWriterConnectionImpl` to receive a full `BidiWriterObjectRequest`. Should we ever need more information from that message it is now ready. It also gives us some type safety / decoration on function and constructor parameters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14003)
> impl(GCS+gRPC): full proto request for uploads

- google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl.h
- google/cloud/storage/internal/async/connection_impl_upload_hash_test.cc
- google/cloud/storage/storage_client_grpc_unit_tests.bzl
Start using protos in the implementation of the `Connection*` classes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14008)
> cleanup(GCS+gRPC): protos in `Connection::*Upload()`

- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool_test.cc
Send a fire-and-forget `AsyncDeleteSession()` request for all idle sessions during `~SessionPool()`.  Previously they would have continued to exist in the service until garbage collected due to inactivity after 60 minutes.
Add expectations for these requests in the connection/session_pool unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14012)
> fix(spanner): delete idle sessions upon SessionPool destruction

- google/cloud/storage/async/connection.h
- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl.h
- google/cloud/storage/internal/async/connection_impl_upload_hash_test.cc
- google/cloud/storage/internal/async/connection_impl_upload_test.cc
- google/cloud/storage/internal/async/connection_tracing.cc
- google/cloud/storage/internal/async/connection_tracing_test.cc
- google/cloud/storage/mocks/mock_async_connection.h
To use protos as the input parameters in `AsyncClient::*Upload` we will need to separate the functions to start vs. resume an upload. I think the end result is easier to explain too, so that is nice. This PR introduces the new functions in the `*Connection` layer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14013)
> impl(GCS+gRPC): separate functions to resume uploads

- .typos.toml
We do the same for compute. Omit the discovery document and the generated protos (which contains everything from the discovery document)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14015)
> impl(ci): omit bigquery files from typos

- generator/internal/discovery_file_test.cc
- generator/internal/discovery_resource.cc
- generator/internal/discovery_resource.h
- generator/internal/discovery_resource_test.cc
- generator/internal/discovery_to_proto.cc
- generator/internal/discovery_to_proto.h
- generator/internal/discovery_to_proto_test.cc
While the Discovery Document schema allows for per-method apiVersion specification, Discovery Documents intended for proto generation are expected to have methods that all have the same value (or lack of value) for `apiVersion`. It is considered an error if that is not the case.
The generator checks early on to make sure the resource definition is well-formed, and the later uses the apiVersion (if present) when formatting the proto file. As verifying the apiVersion requires iterating through all the methods, we want to save that value for later to avoid repeating that processing.
fixes #13981
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13982)
> impl(generator): support apiVersion in discovery documents

- google/cloud/storage/async/client.cc
- google/cloud/storage/async/client_test.cc
- google/cloud/storage/async/object_requests.h
- google/cloud/storage/async/writer.cc
- google/cloud/storage/async/writer.h
- google/cloud/storage/async/writer_connection.h
- google/cloud/storage/async/writer_test.cc
- google/cloud/storage/examples/storage_async_samples.cc
- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl_upload_hash_test.cc
- google/cloud/storage/internal/async/connection_impl_upload_test.cc
- google/cloud/storage/internal/async/connection_tracing_test.cc
- google/cloud/storage/internal/async/writer_connection_buffered.cc
- google/cloud/storage/internal/async/writer_connection_buffered_test.cc
- google/cloud/storage/internal/async/writer_connection_finalized.cc
- google/cloud/storage/internal/async/writer_connection_finalized.h
- google/cloud/storage/internal/async/writer_connection_finalized_test.cc
- google/cloud/storage/internal/async/writer_connection_impl.cc
- google/cloud/storage/internal/async/writer_connection_impl.h
- google/cloud/storage/internal/async/writer_connection_impl_test.cc
- google/cloud/storage/internal/async/writer_connection_tracing.cc
- google/cloud/storage/internal/async/writer_connection_tracing_test.cc
- google/cloud/storage/mocks/mock_async_writer_connection.h
- google/cloud/storage/tests/BUILD.bazel
- google/cloud/storage/tests/CMakeLists.txt
- google/cloud/storage/tests/async_client_integration_test.cc
Now that all resumable upload operations consume protos, it is time to start returning protos when these operations complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14029)
> cleanup(GCS+gRPC): return protos on uploads

- google/cloud/storage/async/client.cc
- google/cloud/storage/async/client.h
- google/cloud/storage/async/client_test.cc
- google/cloud/storage/async/connection.h
- google/cloud/storage/async/object_requests.h
- google/cloud/storage/benchmarks/async_throughput_benchmark.cc
- google/cloud/storage/examples/storage_async_mock_samples.cc
- google/cloud/storage/examples/storage_async_samples.cc
- google/cloud/storage/examples/storage_otel_samples.cc
- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl.h
- google/cloud/storage/internal/async/connection_impl_read_test.cc
- google/cloud/storage/quickstart/quickstart_async.cc
- google/cloud/storage/tests/async_client_integration_test.cc
- google/cloud/storage/tests/smoke_test_async.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14032)
> cleanup(GCS+gRPC): use protos for `ReadObject*()`

- google/cloud/storage/internal/async/connection_impl_read_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14036)
> test(GCS+gRPC): coverage for `ReadObjectRange()`

- README.md
- google/cloud/storagecontrol/README.md
- google/cloud/storagecontrol/doc/main.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14042)
> docs(storagecontrol): update service title

- google/cloud/beyondcorp/BUILD.bazel
A minor thing we missed in https://github.com/googleapis/google-cloud-cpp/pull/12498
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14041)
> cleanup(beyondcorp): remove unused bazel deps

- google/cloud/pubsub/internal/default_pull_lease_manager.cc
- google/cloud/pubsub/internal/default_pull_lease_manager.h
- google/cloud/pubsub/internal/default_pull_lease_manager_test.cc
- google/cloud/pubsub/internal/pull_lease_manager.h
- google/cloud/pubsub/internal/pull_lease_manager_factory.cc
- google/cloud/pubsub/internal/tracing_pull_lease_manager.cc
- google/cloud/pubsub/internal/tracing_pull_lease_manager.h
- google/cloud/pubsub/internal/tracing_pull_lease_manager_test.cc
- google/cloud/pubsub/testing/mock_pull_lease_manager.h
- refactor(pubsub): create pull manager impl to wrap the modack rpc
- test(pubsub): use the mock pull lease manager impl in the tracing unittest
- refactor(pubsub): remove tracing lease manager class
- test(pubsub): add a test for the default pull lease manager impl
I split up the commits for easier reading, if reviewers prefer I can merge them lmk. 
Fixes https://github.com/googleapis/google-cloud-cpp/issues/14020
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14049)
> fix(pubsub): correctly trace modacks in the unary pull

- google/cloud/storage/internal/retry_object_read_source.cc
We probably lost a transient include from `google/cloud/log.h` in #13975 
https://c3i.jfrog.io/c3i/misc/logs/pr/23695/4-linux-clang/google-cloud-cpp/2.23.0//e846e5adce243ac53f5c2319b7d1d0638f84c96a-build.txt
```
/home/conan/workspace/prod-v1/bsr/31134/fbecd/.conan/data/google-cloud-cpp/2.23.0/_/_/build/e846e5adce243ac53f5c2319b7d1d0638f84c96a/src/google/cloud/storage/internal/retry_object_read_source.cc:102:21: error: implicit instantiation of undefined template 'std::basic_stringstream<char>'
std::stringstream os;
^
/usr/local/bin/../include/c++/v1/iosfwd:142:32: note: template is declared here
class _LIBCPP_TEMPLATE_VIS basic_stringstream;
^
1 error generated.
make[2]: *** [google/cloud/storage/CMakeFiles/google_cloud_cpp_storage.dir/internal/retry_object_read_source.cc.o] Error 1 …
```
> fix(storage): missing include

- ci/cloudbuild/builds/checkers.sh
Skip all `*.patch` files in the "trailing whitespace" format step.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14063)
> ci: no formatting for all patch files

- ci/cloudbuild/cloudbuild.yaml
Make it easier to configure the project running our builds. Avoid
hard-coding the project id, and identify other variables that may need
to be adjusted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14065)
> ci(gcb): make project configurable

- generator/internal/discovery_type_vertex.cc
- generator/internal/discovery_type_vertex_test.cc
Convert any to struct based on https://groups.google.com/a/google.com/g/cloud-cxx-team/c/5bTWceeo4_o/m/n3NuDkL9AQAJ?utm_medium=email&utm_source=footer
This covers the following cases:
3. QueryInfo
```
"QueryInfo": {
"description": "Query optimization information for a QUERY job.",
"id": "QueryInfo",
"properties": {
"optimizationDetails": {
"additionalProperties": {
"description": "Properties of the object.",
"type": "any"
},
"description": "Output only. Information about query optimizations.",
"readOnly": true,
"type": "object"
}
},
"type": "object"
},
```
4. SystemVariables
```
"SystemVariables": {
"description": "System variables given to a query.",
"id": "SystemVariables",
"properties": {
"types": {
"additionalProperties": {
"$ref": "StandardSqlDataType"
},
"description": "Output only. …
```
> impl(generator): convert additional properties any into a struct

- ci/cloudbuild/cloudbuild.yaml
To handle (what I think are rare) overload conditions we cancel a build
if a newer build for the same PR is pending. We only do this at the
beginning of the build, so it only helps if the queue is pretty deep
already. I think a better way to deal with that problem is to get more
quota.
Motivated by #14075
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14086)
> ci(gcb): reduce overhead of builds

- ci/etc/integration-tests-config.sh
- google/cloud/speech/CMakeLists.txt
- google/cloud/speech/README.md
- google/cloud/speech/quickstart/quickstart.cc
While we need to wait until after the next release to commit these changes, for our own CI purposes, this quickstart shows how to use the API available at HEAD to direct the speech client to use regional endpoints and reocgnizers.
part of the work for #13729
blocked on https://github.com/microsoft/vcpkg/pull/38204
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13760)
> ci(speech): update quickstart to V2 demonstrating regional endpoints

- google/cloud/spanner/interval.cc
- google/cloud/spanner/interval.h
- google/cloud/spanner/interval_test.cc
An update to the `Interval` API introduced in #14059.  Use `std::chrono::nanoseconds` instead of `absl::Duration` to represent the absolute "offset" portion of the interval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14095)
> fix(spanner): avoid absl types in public Interval API

- google/cloud/completion_queue_test.cc
- google/cloud/internal/async_read_stream_impl.h
https://github.com/googleapis/google-cloud-cpp/issues/13724
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14103)
> impl: add client origin metadata for a failed streaming read

- google/cloud/completion_queue_test.cc
- google/cloud/internal/async_rpc_details.h
https://github.com/googleapis/google-cloud-cpp/issues/13724
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14088)
> impl: add client origin metadata for a failed async unary rpc

- google/cloud/storage/grpc_plugin.h
- google/cloud/storage/internal/grpc/default_options.cc
- google/cloud/storage/internal/grpc/default_options_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14116)
> impl(GCS+gRPC): fix `GrpcMetrics*Option` names

- google/cloud/opentelemetry/monitoring_exporter.cc
- google/cloud/opentelemetry/monitoring_exporter.h
- google/cloud/opentelemetry/monitoring_exporter_test.cc
Part of the work for #14074 
Note that this is not usable in practice until we can also override the `MonitoredResource`. That is why we have not added an integration test for it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14118)
> impl(otel): support `CreateServiceTimeSeries` rpc

- google/cloud/spanner/interval.cc
- google/cloud/spanner/interval.h
- google/cloud/spanner/interval_test.cc
```
StatusOr<Timestamp> Add(Timestamp const&, Interval const&,
absl::string_view time_zone);
StatusOr<Interval> Diff(Timestamp const&, Timestamp const&,
absl::string_view time_zone);
```
A timestamp and a time zone represent a civil time, to which an Interval can be added. Similarly, the difference between two such civil times is an Interval (albeit without a years/months component).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14120)
> feat(spanner): add Interval/Timestamp/time-zone operations

- google/cloud/spanner/interval.cc
- google/cloud/spanner/interval_test.cc
When adding an `Interval` to a `Timestamp`+time-zone, the offset should be interpreted as an absolute value rather than a civil one.  (This is a poor choice in my opinion, but so be it.)
Update the test case, which now has to use a "1 day" interval to show the difference between `Add(ts, "1 day", tz)` and `Add(ts, "24 hours", tz)` over a civil-time discontinuity.
Add a new test based upon the postgresql.org examples, one of which would have demonstrated the original problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14121)
> fix(spanner): correct use of Interval offset in Timestamp addition

- google/cloud/spanner/interval.cc
- google/cloud/spanner/interval.h
- google/cloud/spanner/interval_test.cc
Add APIs to flow Interval 24-hour offsets into days, and 30-day periods into months.  Seeing as "justification" is included in the relational operators, to best way to verify the results is by conversion to a string.
And now that we have `JustifyHours(intvl)`, apply it to the result of `Diff(ts1, ts2, tz)` as required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14123)
> feat(spanner): add Interval justification

- ci/cloudbuild/builds/generate-libraries.sh
- generator/internal/descriptor_utils_test.cc
- generator/internal/format_method_comments.cc
- generator/internal/format_method_comments.h
- generator/standalone_main.cc
Remove the unnecessary `s/\$/$$/` method comment substitution.
How do we know it's unnecessary?  By making it a fatal error for a substitution to fail to match.  This will make it easy for us to remove dead cruft.
Fixes #12190.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14127)
> cleanup(generator): remove obsolete method comment substitution

- google/cloud/internal/oauth2_service_account_credentials.cc
- google/cloud/internal/oauth2_service_account_credentials.h
- google/cloud/internal/oauth2_service_account_credentials_test.cc
- google/cloud/internal/openssl/parse_service_account_p12_file.cc
- google/cloud/storage/oauth2/service_account_credentials.cc
A service account key file may include a `project_id` field. So far we
had not needed this field and we did not parse it, but that is about to
change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14124)
> impl(oauth2): service account parses project_id

- google/cloud/opentelemetry/internal/time_series.cc
- google/cloud/opentelemetry/internal/time_series.h
- google/cloud/opentelemetry/internal/time_series_test.cc
- google/cloud/opentelemetry/monitoring_exporter.cc
- google/cloud/opentelemetry/monitoring_exporter_test.cc
Part of the work for #14128 
1. Factor out the code that creates a `google::api::MonitoredResource`
2. Have `Export()` create the `google::api::MonitoredResource` (instead of `ToRequest()`)
3. Factor out creation of the `google::monitoring::v3::TimeSeries`es. I considered calling the method `ToTimeSerieses`, but that would be too goofy.
4. Have `ToRequest()` accept this `MonitoredResource` and list of `TimeSeries` as parameters. While we're at it, have it accept the project as well.
Note that there are no changes to `monitoring_exporter_test.cc` (outside of rewriting an error message).
---
A follow up PR will introduce batching.
```cc
google::monitoring::v3::CreateTimeSeriesRequest ToRequest(...);
```
becomes....
```cc
std::vector<google::monitoring::v3::CreateTimeSeriesRequest> …
```
> refactor(otel): prepare to batch requests

- google/cloud/internal/curl_handle_factory.cc
- google/cloud/internal/curl_handle_factory_test.cc
Fixes #14132
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14134)
> fix(common): out of range access in handle cleanup

- google/cloud/opentelemetry/internal/time_series.cc
- google/cloud/opentelemetry/internal/time_series.h
- google/cloud/opentelemetry/internal/time_series_test.cc
- google/cloud/opentelemetry/monitoring_exporter.cc
- google/cloud/opentelemetry/monitoring_exporter_test.cc
Fixes #14128 
Break up the export into multiple requests, each with no more than 200 TimeSeries in them. If we do not do this, we may drop all of our metrics on the floor if the cardinality is sufficiently high.
Generalize the existing tests to exercise the batching logic.
The error handling logic really is not important. I do not think anyone consumes the error. Arguably the tests are too strict.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14133)
> impl(otel): batch TimeSeries

- generator/internal/scaffold_generator.cc
- generator/internal/scaffold_generator_test.cc
fixes #12630
As a side benefit, the test fixture now supports a service yaml file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14136)
> impl(generator): use documentation link from yaml in README

- ci/cloudbuild/cloudbuild.yaml
Practically the first step in our builds is to create (with a cache) the
Docker image with all the development tools. We have been using Google
Container Registry (GCR) to host these images and their cache. And we
have been using the "global" version of GCR.
GCR is deprecated in favor of Artifact Registry. We have been using
artifact registry as the backend of GCR. With this change we start using
artifact registry directly.
We use a regional artifact registry repository, in the same region as
the build pool. That avoids WAN traffic and hopefully gives us better
performance, lower costs, and more reliable builds.
Artifact registry has its own garbage collection, so we can simplify the
build scripts, and let artifact registry take care of removing old
images.
- - - …
> ci(gcb): move build images to artifact registry

- ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14144)
> ci: upgrade `cxx14` to Fedora:40

- google/cloud/internal/future_impl.cc
Starting with libc++ 18.1 the `std::future_error(future_errc)`
constructor only appears if compiling with C++17.
Part of the work for #14076
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14151)
> fix(common): support libc++ >= 18.1

- generator/integration_tests/golden/v1/internal/golden_kitchen_sink_metadata_decorator.cc
- generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_metadata_decorator.cc
- generator/internal/metadata_decorator_generator.cc
- generator/internal/metadata_decorator_rest_generator.cc
Part of the work for #14108 
These definitions conflict if we squash all of the source files for a given service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14155)
> refactor: prepare for squashed sources

- .clang-tidy
#14076
Omit the enum size performance check
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14165)
> cleanup: prepare for clang-tidy 18

- cmake/GoogleCloudCppCommonOptions.cmake
Part of the work for #14076
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14168)
> ci: support mixed GCC and Clang 18 builds

- generator/internal/scaffold_generator.cc
- generator/internal/scaffold_generator_test.cc
Closes https://github.com/googleapis/google-cloud-cpp/issues/12629
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14167)
> cleanup: change README and main.dox for generated libraries to require no editing of service description

- bazel/gapic.bzl
- generator/internal/scaffold_generator.cc
- generator/internal/scaffold_generator_test.cc
- google/cloud/accessapproval/BUILD.bazel
The interesting part of #14171
Add a helper to handle most of the `BUILD.bazel` definitions.
Demonstrate how to use the helper in one library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14173)
> refactor: bazel gapic helper

- google/cloud/accesscontextmanager/BUILD.bazel
- google/cloud/advisorynotifications/BUILD.bazel
- google/cloud/aiplatform/BUILD.bazel
- google/cloud/alloydb/BUILD.bazel
- google/cloud/apigateway/BUILD.bazel
- google/cloud/apigeeconnect/BUILD.bazel
- google/cloud/apikeys/BUILD.bazel
- google/cloud/appengine/BUILD.bazel
- google/cloud/apphub/BUILD.bazel
- google/cloud/artifactregistry/BUILD.bazel
- google/cloud/asset/BUILD.bazel
- google/cloud/assuredworkloads/BUILD.bazel
- google/cloud/automl/BUILD.bazel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14174)
> refactor: bazel gapics `a*`

- google/cloud/certificatemanager/BUILD.bazel
- google/cloud/channel/BUILD.bazel
- google/cloud/cloudbuild/BUILD.bazel
- google/cloud/cloudcontrolspartner/BUILD.bazel
- google/cloud/cloudquotas/BUILD.bazel
- google/cloud/commerce/BUILD.bazel
- google/cloud/composer/BUILD.bazel
- google/cloud/confidentialcomputing/BUILD.bazel
- google/cloud/config/BUILD.bazel
- google/cloud/connectors/BUILD.bazel
- google/cloud/contactcenterinsights/BUILD.bazel
- google/cloud/container/BUILD.bazel
- google/cloud/containeranalysis/BUILD.bazel
- google/cloud/contentwarehouse/BUILD.bazel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14175)
> refactor: bazel gapics `c*`

- google/cloud/datacatalog/BUILD.bazel
- google/cloud/datafusion/BUILD.bazel
- google/cloud/datamigration/BUILD.bazel
- google/cloud/dataplex/BUILD.bazel
- google/cloud/dataproc/BUILD.bazel
- google/cloud/datastore/BUILD.bazel
- google/cloud/datastream/BUILD.bazel
- google/cloud/deploy/BUILD.bazel
- google/cloud/dialogflow_cx/BUILD.bazel
- google/cloud/dialogflow_es/BUILD.bazel
- google/cloud/discoveryengine/BUILD.bazel
- google/cloud/dlp/BUILD.bazel
- google/cloud/documentai/BUILD.bazel
- google/cloud/domains/BUILD.bazel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14176)
> refactor: bazel gapics `d*`

- google/cloud/internal/oauth2_compute_engine_credentials.h
- google/cloud/internal/oauth2_credentials.cc
- google/cloud/internal/oauth2_credentials.h
- google/cloud/internal/oauth2_credentials_test.cc
- google/cloud/internal/oauth2_service_account_credentials.cc
- google/cloud/internal/oauth2_service_account_credentials.h
This will let us retrieve the project id associated with a credentials
type. Not all credential types have a project id associated with them,
and therefore they do not all implement this API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14170)
> impl(oauth2): add `project_id()` to `Credentials`

- google/cloud/iap/BUILD.bazel
- google/cloud/ids/BUILD.bazel
- google/cloud/kms/BUILD.bazel
- google/cloud/language/BUILD.bazel
- google/cloud/logging/BUILD.bazel
- google/cloud/policysimulator/BUILD.bazel
- google/cloud/policytroubleshooter/BUILD.bazel
- google/cloud/privateca/BUILD.bazel
- google/cloud/profiler/BUILD.bazel
- google/cloud/rapidmigrationassessment/BUILD.bazel
- google/cloud/recaptchaenterprise/BUILD.bazel
- google/cloud/recommender/BUILD.bazel
- google/cloud/redis/BUILD.bazel
- google/cloud/resourcemanager/BUILD.bazel
- google/cloud/resourcesettings/BUILD.bazel
- google/cloud/retail/BUILD.bazel
- google/cloud/run/BUILD.bazel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14178)
> refactor: bazel gapics `i*`,`k*`,`l*`,`p*`,`r*`,

- google/cloud/backupdr/BUILD.bazel
- google/cloud/baremetalsolution/BUILD.bazel
- google/cloud/batch/BUILD.bazel
- google/cloud/beyondcorp/BUILD.bazel
- google/cloud/billing/BUILD.bazel
- google/cloud/binaryauthorization/BUILD.bazel
- google/cloud/edgecontainer/BUILD.bazel
- google/cloud/edgenetwork/BUILD.bazel
- google/cloud/essentialcontacts/BUILD.bazel
- google/cloud/eventarc/BUILD.bazel
- google/cloud/filestore/BUILD.bazel
- google/cloud/functions/BUILD.bazel
- google/cloud/gkebackup/BUILD.bazel
- google/cloud/gkehub/BUILD.bazel
- google/cloud/gkemulticloud/BUILD.bazel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14177)
> refactor: bazel gapics `b*`,`e*`,`f*`,`g*`

- google/cloud/managedidentities/BUILD.bazel
- google/cloud/memcache/BUILD.bazel
- google/cloud/metastore/BUILD.bazel
- google/cloud/migrationcenter/BUILD.bazel
- google/cloud/monitoring/BUILD.bazel
- google/cloud/netapp/BUILD.bazel
- google/cloud/networkconnectivity/BUILD.bazel
- google/cloud/networkmanagement/BUILD.bazel
- google/cloud/networksecurity/BUILD.bazel
- google/cloud/networkservices/BUILD.bazel
- google/cloud/notebooks/BUILD.bazel
- google/cloud/optimization/BUILD.bazel
- google/cloud/orgpolicy/BUILD.bazel
- google/cloud/osconfig/BUILD.bazel
- google/cloud/oslogin/BUILD.bazel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14185)
> refactor: bazel gapics `m*`,`n*`,`o*`

- google/cloud/scheduler/BUILD.bazel
- google/cloud/secretmanager/BUILD.bazel
- google/cloud/securesourcemanager/BUILD.bazel
- google/cloud/securitycentermanagement/BUILD.bazel
- google/cloud/servicecontrol/BUILD.bazel
- google/cloud/servicedirectory/BUILD.bazel
- google/cloud/servicehealth/BUILD.bazel
- google/cloud/servicemanagement/BUILD.bazel
- google/cloud/serviceusage/BUILD.bazel
- google/cloud/shell/BUILD.bazel
- google/cloud/speech/BUILD.bazel
- google/cloud/storagecontrol/BUILD.bazel
- google/cloud/storageinsights/BUILD.bazel
- google/cloud/storagetransfer/BUILD.bazel
- google/cloud/support/BUILD.bazel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14186)
> refactor: bazel gapics `s*`

- cmake/GoogleCloudCppCommonOptions.cmake
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14188)
> cleanup: use the correct option for clang abi compat

- google/cloud/pubsub/internal/batching_publisher_connection.cc
- google/cloud/pubsub/internal/blocking_publisher_connection_impl.cc
- google/cloud/pubsub/internal/default_pull_ack_handler.cc
- google/cloud/pubsub/internal/default_pull_lease_manager.cc
- google/cloud/pubsub/internal/extend_leases_with_retry.cc
- google/cloud/pubsub/internal/flow_controlled_publisher_connection.cc
- google/cloud/pubsub/internal/rejects_with_ordering_key.cc
- google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
- google/cloud/pubsub/internal/subscription_concurrency_control.cc
Part of the work for https://github.com/googleapis/google-cloud-cpp/issues/14107
Found the cases using:
```
git grep -e 'StatusCode::k' --and --not -e 'StatusCode::kUnimplemented' --and --not -e 'StatusCode::kOk' -- '*.cc' ':!*_test.cc' | grep pubsub/internal
```
Then used find and replace with regex & added the header
Search
```
Status\(StatusCode::kUnknown, "(.*)"\)
```
Replace
```
internal::UnknownError("$1", GCP_ERROR_INFO())
```
Header
```
#include "google/cloud/internal/make_status.h"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14169)
> cleanup(pubsub): use `Status` factory functions

- google/cloud/pubsublite/endpoint.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14189)
> cleanup(pubsublite): use Status factory functions

- google/cloud/testing_util/fake_completion_queue_impl.cc
- google/cloud/testing_util/mock_grpc_authentication_strategy.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14192)
> cleanup: use Status factory functions in testing_util/*

- google/cloud/talent/BUILD.bazel
- google/cloud/tasks/BUILD.bazel
- google/cloud/telcoautomation/BUILD.bazel
- google/cloud/texttospeech/BUILD.bazel
- google/cloud/timeseriesinsights/BUILD.bazel
- google/cloud/tpu/BUILD.bazel
- google/cloud/trace/BUILD.bazel
- google/cloud/translate/BUILD.bazel
- google/cloud/video/BUILD.bazel
- google/cloud/videointelligence/BUILD.bazel
- google/cloud/vision/BUILD.bazel
- google/cloud/vmmigration/BUILD.bazel
- google/cloud/vmwareengine/BUILD.bazel
- google/cloud/vpcaccess/BUILD.bazel
- google/cloud/webrisk/BUILD.bazel
- google/cloud/websecurityscanner/BUILD.bazel
- google/cloud/workflows/BUILD.bazel
- google/cloud/workstations/BUILD.bazel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14187)
> refactor: bazel gapics `t*`,`v*`,`w*`

- ci/cloudbuild/cloudbuild.yaml
I removed the second attempt to run Kaniko (because it never worked), but did not remove the attributes to keep going after the first attempt failed.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14202)
> ci(gcb): do not allow Kaniko failures

- generator/internal/printer.h
Comments say this ctor will be deprecated.
https://github.com/protocolbuffers/protobuf/blob/82e83ddc95330bbd988ba874ea5aa37d343d4490/src/google/protobuf/io/printer.h#L505-L509
Note that `$` is the default delimiter: https://github.com/protocolbuffers/protobuf/blob/82e83ddc95330bbd988ba874ea5aa37d343d4490/src/google/protobuf/io/printer.h#L457
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14196)
> cleanup(generator): protobuf::io::Printer ctor

- google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config.h
#14076
Remove redundant inline
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14204)
> cleanup(bigquery): prepare for clang-tidy 18

- google/cloud/storage/internal/retry_object_read_source.cc
- google/cloud/storage/lifecycle_rule.cc
#14076
```
Step #2: /workspace/google/cloud/storage/internal/retry_object_read_source.cc:116:36: error: conversion from 'absl::optional<long>' into 'long' and back into 'absl::optional<long>', remove potentially error-prone optional dereference [bugprone-optional-value-conversion,-warnings-as-errors]
Step #2:   116 |   if (r->generation) generation_ = *r->generation;
Step #2:       |                                    ^
Step #2: /workspace/google/cloud/storage/internal/retry_object_read_source.cc:116:36: note: remove '*' to silence this warning
Step #2:   116 |   if (r->generation) generation_ = *r->generation;
Step #2:       |                                    ^
Step #2: 36659 warnings generated.
```
- - - …
> cleanup(storage): prepare for clang-tidy 18

- google/cloud/spanner/internal/session.h
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
Split `Allocate()` and `GetStub()` into lock-acquiring and lock-consuming parts.  This will facilitate future work where two paths will separately call into the lock-consuming parts.
Also improve the `Session` class comment while we're here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14203)
> refactor(spanner): prepare for upcoming SessionPool work

- bazel/gapic.bzl
- google/cloud/bigquery/BUILD.bazel
- google/cloud/iam/BUILD.bazel
These two libraries have handwritten mock samples, which need to depend on the `*_mocks` libraries. We will glob on something more specific, and handle the mock sample targets individually in the BUILD file.
Note that in CMake, we add dependencies to these targets after they are defined by the common helper. We should consider using the `*_samples.cc` glob too, for the sake of consistency.
Only `securitycenter` remains, which has a special `target_compatible_with` field. That field goes away with Protobuf v27. I am tempted to just wait it out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14213)
> refactor: bazel gapics for IAM, BQ

- google/cloud/internal/populate_common_options_test.cc
Closes #13191 
We do not like writing tests that have advanced logic in it. But we also do not like writing out every test case in a 4x3x3x3 matrix.
As discussed, we will close the issue, leave the test alone, and move on with our lives.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14214)
> cleanup: remove TODO we are not going to fix

- google/cloud/storage/internal/async/writer_connection_buffered.cc
```
Step #2: /workspace/google/cloud/storage/internal/async/writer_connection_buffered.cc:164:5: error: redundant explicit casting to the same type 'void' as the sub-expression, remove this casting [readability-redundant-casting,-warnings-as-errors]
Step #2:   164 |     (void)StartWriting(std::move(lk));
Step #2:       |     ^~~~~~
Step #2: /workspace/google/cloud/storage/internal/async/writer_connection_buffered.cc:168:8: note: source type originates from the invocation of this method
Step #2:   168 |   void StartWriting(std::unique_lock<std::mutex> lk) {
Step #2:       |   ~~~~ ^
Step #2: 53615 warnings generated.
```
- - - …
> cleanup(storage): prepare for clang 18

- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/session.h
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/internal/session_pool_test.cc
The Spanner session pool can now allocate and return a "multiplexed" session, which may be used for multiple, concurrent operations, and has no affinity to a single gRPC channel.  Multiplexed sessions have a maximum lifetime of 28 days, and do not need to "kept alive" when idle.  This will greatly simplify client-side session management.
Actual use of the multiplexed session will be added in phases within future changes.  (The first phase will be for single-use reads/queries and read-only transactions.)
Update the tests to expect the new `CreateSession()` and additional `AsyncDeleteSession()` calls.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14216)
> impl(spanner): implement SessionPool::Multiplexed()

- ci/cloudbuild/cloudbuild.yaml
Instead of retrying inside Kaniko, just retry the Kaniko calls. Related to #6438 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14222)
> ci(gcb): make multiple Kaniko attempts

- google/cloud/compute/BUILD.bazel
- google/cloud/compute/compute_library.bzl
Noticed while working on #14108 
The `service.replace("/v1/", ...)` are distracting. Factor this thing out to a function where we can use a local variable to store the service name.
While we're here, build all of the samples.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14225)
> cleanup(compute): simpler BUILD file

- generator/internal/codegen_utils.cc
- generator/internal/descriptor_utils.cc
- generator/internal/service_code_generator.cc
- generator/standalone_main.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14220)
> cleanup(generator): use `Status` factory functions

- google/cloud/internal/async_polling_loop.cc
- google/cloud/internal/async_rest_polling_loop_impl.h
- google/cloud/internal/base64_transforms.cc
- google/cloud/internal/big_endian.h
- google/cloud/internal/default_completion_queue_impl.cc
- google/cloud/internal/extract_long_running_result.cc
- google/cloud/internal/grpc_impersonate_service_account.cc
- google/cloud/internal/oauth2_authorized_user_credentials.cc
- google/cloud/internal/oauth2_google_credentials.cc
- google/cloud/internal/oauth2_service_account_credentials.cc
- google/cloud/internal/openssl/parse_service_account_p12_file.cc
- google/cloud/internal/openssl/sign_using_sha256.cc
- google/cloud/internal/parse_rfc3339.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14221)
> cleanup: use `Status` factory functions

- .bazelrc
- ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14148)
> ci: upgrade LLVM to 18

- google/cloud/internal/oauth2_cached_credentials.cc
- google/cloud/internal/oauth2_cached_credentials.h
- google/cloud/internal/oauth2_cached_credentials_test.cc
- google/cloud/internal/oauth2_logging_credentials.cc
- google/cloud/internal/oauth2_logging_credentials.h
- google/cloud/internal/oauth2_logging_credentials_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14240)
> impl(oauth2): `project_id()` for credential decorators

- google/cloud/storage/internal/grpc/monitoring_project.cc
- google/cloud/storage/internal/grpc/monitoring_project.h
- google/cloud/storage/internal/grpc/monitoring_project_test.cc
This completes the code to determine what project is used for GCS+gRPC
metrics.
Fixes #14112
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14245)
> impl(GCS+gRPC): project for GCS+gRPC metrics

- google/cloud/storage/internal/grpc/metrics_exporter_options.cc
- google/cloud/storage/internal/grpc/metrics_exporter_options.h
- google/cloud/storage/internal/grpc/metrics_exporter_options_test.cc
I need to separate the options for the metrics exporter vs. the options
for the metrics exporter *connection*.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14252)
> impl(GCS+gRPC): metrics exporter vs. connection options

- google/cloud/bigtable/internal/mutate_rows_limiter_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14264)
> cleanup(bigtable): unused using when no otel

- google/cloud/opentelemetry/CMakeLists.txt
`cleanup` and not a `fix` because the `opentelemetry::sdk::metrics::*` symbols that wouldn't link are not used by any public APIs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14266)
> cleanup(otel): missing metrics module

- google/cloud/pubsub/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14272)
> docs(pubsub): add optimistic subscribe example

- google/cloud/securitycenter/BUILD.bazel
- google/cloud/securitycenter/CMakeLists.txt
I am told that the macros are resolved in protobuf v27, which we now test with.
While we're here, refactor the Bazel file in accordance with #14171
YOLO
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14282)
> feat(securitycenter): re-enable on windows

- google/cloud/storage/client.cc
- google/cloud/storage/client.h
- google/cloud/storage/client_sign_policy_document_test.cc
- google/cloud/storage/client_sign_url_test.cc
- google/cloud/storage/internal/policy_document_request.cc
- google/cloud/storage/internal/policy_document_request.h
- google/cloud/storage/internal/policy_document_request_test.cc
- google/cloud/storage/internal/signed_url_requests.cc
- google/cloud/storage/internal/signed_url_requests.h
- google/cloud/storage/internal/signed_url_requests_test.cc
- google/cloud/storage/tests/signed_url_conformance_test.cc
closes #13068
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14179)
> feat(storage): Respect custom endpoint for SignedUrl

- google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
- google/cloud/pubsub/internal/subscriber_connection_impl.cc
- google/cloud/pubsub/internal/subscriber_connection_impl_test.cc
- google/cloud/pubsub/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14280)
> cleanup(pubsub): use client originated error in samples

- google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc
- google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h
- google/cloud/bigquery/v2/minimal/internal/common_v2_resources_test.cc
- google/cloud/bigquery/v2/minimal/internal/job_response.cc
- google/cloud/bigquery/v2/minimal/internal/job_response.h
- google/cloud/bigquery/v2/minimal/internal/job_response_test.cc
- google/cloud/bigquery/v2/minimal/testing/common_v2_test_utils.cc
- google/cloud/bigquery/v2/minimal/testing/common_v2_test_utils.h
- google/cloud/bigquery/v2/minimal/testing/job_query_test_utils.cc
This PR contains the following changes
1) Modified structures for row data processing for Query APIs. Existing `Struct` and `Value` structures and respective parsing logic, do not work based on the json returned from the server. I have added new structures which keeps the processing simpler in the client library layer. For our specific usecase we have to go through the schema of each column anyways in our layer so complex row and value processing is not needed for the query apis in the client library layer, and is also not feasible at this layer.
2) Unit tests changes for the above.
3) Please note that I am still keeping the `Struct` and `Value` structures for the following reasons:
- Change is specific to Query APIs only. If in the future we determine that these structures are not needed …
> impl(bigquery): Modified row data processing for Query apis

- .github/workflows/macos-bazel.yml
- .github/workflows/macos-cmake.yml
- .github/workflows/windows-bazel.yml
- .github/workflows/windows-cmake.yml
In order to accommodate the reduced disk size on the free runners, the sharding factor has been increased for the windows+cmake builds. With this additional sharding, all the windows+cmake builds are expected to pass and all the macos+cmake builds are expected to pass. bazel builds are likely going to fail until they can be similarly sharded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14290)
> ci: use gha free runners

- ci/cloudbuild/notifiers/logs/function/function.cc
- docfx/doxygen2markdown.cc
- google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc
- google/cloud/bigquery/v2/minimal/benchmarks/job_cancel_benchmark_programs.cc
- google/cloud/bigquery/v2/minimal/benchmarks/job_insert_benchmark_programs.cc
- google/cloud/bigquery/v2/minimal/benchmarks/job_query_benchmark_programs.cc
- google/cloud/bigquery/v2/minimal/benchmarks/job_readonly_benchmark_programs.cc
- google/cloud/bigquery/v2/minimal/benchmarks/project_benchmark_programs.cc
- google/cloud/bigquery/v2/minimal/benchmarks/table_benchmark_programs.cc
- google/cloud/bigtable/iam_policy.cc
- google/cloud/internal/curl_impl.cc
- google/cloud/log.cc
- google/cloud/pubsub/benchmarks/endurance.cc
- google/cloud/pubsub/benchmarks/throughput.cc
- google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
- google/cloud/pubsub/internal/session_shutdown_manager.cc
- google/cloud/pubsub/samples/schema_samples.cc
- google/cloud/spanner/benchmarks/benchmarks_config.cc
- google/cloud/spanner/samples/postgresql_samples.cc
- google/cloud/spanner/samples/samples.cc
- google/cloud/storage/compose_many_test.cc
- google/cloud/storage/iam_policy.cc
- google/cloud/storage/internal/hmac_key_requests.cc
- google/cloud/storage/internal/object_requests.cc
- google/cloud/storage/policy_document.cc
- google/cloud/testing_util/opentelemetry_matchers.cc
Our `gcb-checkers` docker image picked up a new version of `clang-format`. We adapt accordingly.
Locally I had to run `docker system prune -a` to clear the cache and get the latest image.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14298)
> chore: checkers

- ci/cloudbuild/builds/cmake-install.sh
I split out the gcs+grpc feature from the rest. Not sure if there's some race going on when trying to add it in with storage at the same time.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14313)
> ci: cmake-install workaround

- .github/workflows/windows-cmake.yml
See #14314 
Avoid the `14.40.*` compilers (if we can).
I only have a fix for cmake at the moment. It still seems worth sending. I will keep working on bazel.
Tested: https://github.com/googleapis/google-cloud-cpp/actions/runs/9426451152
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14315)
> ci: workaround windows compiler (cmake)

- .github/workflows/windows-cmake.yml
It is not enough to just write to `${{ matrix.arch }}-windows.cmake`. Apparently the `x86` build builds some of the deps using the `x64-windows` triplet and others as the `x86-windows` triplet.
Tested: https://github.com/googleapis/google-cloud-cpp/actions/runs/9452556490
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14318)
> ci: fix windows+cmake+x86 builds

- .github/workflows/windows-bazel.yml
Workaround mentioned in #14314 
See the related `windows-cmake.yml` changes: #14315 
The difference is how we set the toolset used by the build system. For Bazel, we set the `BAZEL_FULL_VC_VERSION` environment variable: https://bazel.build/configure/windows#build_cpp
---
Tested: https://github.com/googleapis/google-cloud-cpp/actions/runs/9454681140/job/26042798580
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14319)
> ci: upb workaround for windows+bazel

- generator/internal/pagination.cc
- generator/internal/pagination_test.cc
Closes https://github.com/googleapis/google-cloud-cpp/issues/14281
BigQuery's proto pagination fields differ in 2 ways that our generator does not currently handle: 
1) the max_size field is not always a uint32, but can also be a "google.protobuf.UInt32Value" or "google.protobuf.Int32Value"
2) the name of the repeated field in the response that should be paginated is not always "items".
We use to recognize if the `max_size` field on the request proto for the method to determine if we should generate pagination info and we use the repeated message field to provide the pagination info.
This PR adds custom parsing to the protos to see if pagination should be added for BQ protos. …
> impl(generator): handle bigquery pagination

- bazel/curl.BUILD
cc @mering 
We should use the upstream versions of `zlib` and `c-ares`. We should not assume gRPC will place these in an `//external/...` directory. (In fact, gRPC has moved them to a `//third_party/...` directory).
Tested with: `ci/cloudbuild/build.sh -t grpc-at-head`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14331)
> fix(bazel): use upstream cares, zlib

- generator/internal/longrunning.cc
- generator/internal/longrunning_test.cc
part of the work for #7658 
Create substitution variables for the Operation type of the LRO. In the case of compute type LROs, format the code that sets the request fields for the polling and cancel rpcs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14330)
> impl(generator): format variables for lro await

- google/cloud/internal/async_long_running_operation.h
- google/cloud/internal/async_long_running_operation_test.cc
- google/cloud/internal/async_rest_long_running_operation.h
- google/cloud/internal/async_rest_long_running_operation_custom.h
- google/cloud/internal/async_rest_long_running_operation_custom_test.cc
- google/cloud/internal/async_rest_long_running_operation_test.cc
part of the work for #7658 
Add variations of existing `AsyncLongRunningOperation` template functions that do not start the LRO, but accept an Operation type from an already started LRO.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14329)
> impl: add Await methods to poll already started LRO

- generator/internal/http_option_utils.cc
With the impending addition of synchronous LRO method overloads in the stub, checking for `IsLongrunningOperation` becomes incorrect. Turns out, it's actually redundant as the generator indicates `async` where it's appropriate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14339)
> imp(generator): remove unnecessary check in processing rest path

- ci/lib/shard.sh
- google/cloud/storagecontrol/v2/samples/storage_control_folder_samples.cc
My opinion on: https://github.com/googleapis/google-cloud-cpp/pull/14332#discussion_r1639714674
Also, I notice that `oauth2` previously escaped `clang-tidy`. Throwing it in the storage shard makes some sense.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14338)
> ci: clang-tidy for oauth2, storagecontrol

- google/cloud/internal/opentelemetry.h
We `std::move(sleeper)` into this function. It should take `sleeper` by value.
Otherwise we get `warning: 'sleeper' may be used uninitialized [-Wmaybe-uninitialized]` errors for every library we build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14343)
> cleanup(otel): suppress maybe unitialized warning

- ci/cloudbuild/builds/publish-docs.sh
In #13853, in unrolling `docuploader`, we dropped the `--destination-prefix`, which was `docfx-`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14345)
> ci: fix publish-docs uploads

- google/cloud/storagecontrol/v2/samples/storage_control_managed_folder_samples.cc
Fixes #14305
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14356)
> samples(storagecontrol): add storagecontrol managed folder samples

- google/cloud/bigtable/doc/bigtable-options.dox
- google/cloud/bigtable/options.h
Also part of the work for #14207  
The admin options are called `google-cloud-{library}-options`. They were not being included in these handwritten option dox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14358)
> docs(bigtable): include admin options

- google/cloud/spanner/doc/spanner-options.dox
- google/cloud/spanner/options.h
Also part of the work for #1207 
The admin options are called `google-cloud-{library}-options`. They were not being included in these handwritten option dox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14360)
> docs(spanner): include admin options

- google/cloud/pubsub/doc/pubsub-options.dox
- google/cloud/pubsub/options.h
Also part of the work for #14207 
The admin options are called `google-cloud-{library}-options`. They were not being included in these handwritten option dox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14359)
> docs(pubsub): include admin options

- google/cloud/doc/error-handling.dox
Part of the work for #14207 
Doxygen sees an open `<S>` and fails because there is no `</S>`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14361)
> cleanup(docs): prepare for doxygen 1.11.0

- generator/integration_tests/golden/v1/golden_thing_admin_client.h
- generator/internal/descriptor_utils.cc
- generator/internal/format_method_comments.cc
- google/cloud/bigtable/admin/bigtable_instance_admin_client.h
- google/cloud/bigtable/admin/bigtable_table_admin_client.h
- google/cloud/contactcenterinsights/v1/contact_center_insights_client.h
- google/cloud/dialogflow_cx/deployments_client.h
- google/cloud/dialogflow_cx/environments_client.h
- google/cloud/dialogflow_cx/experiments_client.h
- google/cloud/dialogflow_cx/session_entity_types_client.h
- google/cloud/dialogflow_cx/test_cases_client.h
- google/cloud/dialogflow_cx/versions_client.h
- google/cloud/dialogflow_es/agents_client.h
- google/cloud/dialogflow_es/contexts_client.h
- google/cloud/dialogflow_es/conversation_models_client.h
- google/cloud/dialogflow_es/conversations_client.h
- google/cloud/dialogflow_es/intents_client.h
- google/cloud/dialogflow_es/participants_client.h
- google/cloud/dialogflow_es/session_entity_types_client.h
- google/cloud/dialogflow_es/sessions_client.h
- google/cloud/servicemanagement/v1/service_manager_client.h
- google/cloud/spanner/admin/database_admin_client.h
Part of the work for #14207 
Doxygen 1.11.0 has some new struggles with our documents.
- double backticks don't work.
- single backticks broken over multiple lines don't work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14362)
> cleanup(generator): comment substitutions

- google/cloud/opentelemetry/samples/samples.cc
- google/cloud/testing_util/opentelemetry_matchers.cc
Preparing for `opentelemetry-cpp` `v1.16.0`. #14355
`opentelemetry-cpp` will make a breaking change to the return type of their provider factory functions. We can work around this by handling the returned value more generally.
GCS+gRPC also has such factories, but I did not see it failing in any of the tests against OTel 1.16.0. I am not 100% sure it is being built, to be honest.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14372)
> chore(otel): more general factory handling

- google/cloud/pubsub/internal/blocking_publisher_tracing_connection.cc
- google/cloud/pubsub/internal/publisher_tracing_connection.cc
- google/cloud/pubsub/internal/publisher_tracing_connection_test.cc
- google/cloud/pubsub/internal/subscriber_tracing_connection.cc
- google/cloud/pubsub/internal/subscriber_tracing_connection_test.cc
- google/cloud/pubsub/internal/tracing_batch_callback.cc
- google/cloud/pubsub/internal/tracing_batch_callback_test.cc
- google/cloud/pubsub/internal/tracing_batch_sink.cc
- google/cloud/pubsub/internal/tracing_batch_sink_test.cc
- google/cloud/pubsub/internal/tracing_exactly_once_ack_handler.cc
- google/cloud/pubsub/internal/tracing_exactly_once_ack_handler_test.cc
- google/cloud/pubsub/internal/tracing_pull_ack_handler.cc
- google/cloud/pubsub/internal/tracing_pull_ack_handler_test.cc
- google/cloud/pubsub/internal/tracing_pull_lease_manager.cc
- google/cloud/pubsub/internal/tracing_pull_lease_manager_test.cc
- google/cloud/storage/internal/async/reader_connection_tracing.cc
- google/cloud/storage/internal/async/reader_connection_tracing_test.cc
- google/cloud/storage/internal/async/writer_connection_tracing.cc
- google/cloud/storage/internal/async/writer_connection_tracing_test.cc
Preparing for `opentelemetry-cpp` `v1.16.0`. #14355
They will deprecate some semantic convention types.
In this PR, we adopt the new semantic conventions, but they are not available in the oldest OTel we support, so we must hardcode the values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14373)
> chore(otel): use newer messaging semantic conventions

- google/cloud/opentelemetry/internal/time_series.cc
- google/cloud/opentelemetry/internal/time_series.h
- google/cloud/opentelemetry/internal/time_series_test.cc
- google/cloud/opentelemetry/monitoring_exporter.cc
- google/cloud/opentelemetry/monitoring_exporter.h
- google/cloud/opentelemetry/monitoring_exporter_test.cc
- google/cloud/storage/internal/grpc/metrics_exporter_impl.cc
- google/cloud/storage/internal/grpc/metrics_exporter_impl_test.cc
- google/cloud/storage/internal/grpc/metrics_exporter_options.cc
Let the application provide a function to format metric names. In some
cases we want to do more than prepend a prefix.
Fixes #14304, motivated by #13998
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14378)
> impl(otel): general-purpose metric name formatter

- google/cloud/internal/async_read_write_stream_tracing.h
- google/cloud/internal/async_read_write_stream_tracing_test.cc
Part of the work for #14371
---
Running the `streaming_pull_subscriber` cpp sample:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14379)
> fix(otel): async read write stream tracing

- google/cloud/storage/internal/grpc/metrics_exporter_options.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14381)
> impl(GCS+gRPC): format gRPC metric names

- google/cloud/compute/integration_tests/compute_integration_test.cc
- google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/admin/integration_tests/instance_admin_rest_integration_test.cc
part of the work for #7658
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14377)
> impl: add integration tests for LRO Start and Await methods

- generator/generator_config.textproto
- google/cloud/dataproc/v1/internal/node_group_controller_stub.h
- google/cloud/dataproc/v1/node_group_controller_connection.h
With the Await function checking the LRO metadata type, we need to ensure the appropriate pb.h file is included.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14386)
> impl(dataproc): add include for lro metadata type

- google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc
- google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h
- google/cloud/bigquery/v2/minimal/internal/common_v2_resources_test.cc
- google/cloud/bigquery/v2/minimal/internal/job_response_test.cc
- google/cloud/bigquery/v2/minimal/internal/json_utils.h
- google/cloud/bigquery/v2/minimal/internal/json_utils_test.cc
This PR includes the following changes for json parsing related to null values, based on what is returned from BQ Server API
1. BQ query response can contain null values for row/column data as shown below
```
"rows": [
{
"f": [
{
"v": null
},
{
"v": "Test String 6"
},
{
"v": null
}
]
},
```
Due to the above json `get_to` method crashes with a type exception . The fix checks for null value before calling `get_to` in json_utils.h
2) From the client perspective, we need to be able to distingush an empty string from a null value so that client api can work properly hence an additional `is_null` member has been added to `ColumnData` struct.
3) Unit test changes for all of the above.
- - - …
> fix(bigquery): Fixes parsing of null type values returned from BQ server

- google/cloud/internal/opentelemetry.cc
- google/cloud/internal/opentelemetry_test.cc
With this PR, applications that enable OpenTelemetry tracing, and use the Cloud Trace exporter, will be able to see error messages in the UI.
This change also makes it easier to filter client library errors only in the Cloud Trace UI with:
```
label:gl-cpp.error.message
``` 
---
Other attributes use the domain: `gcloud.error.*`. I will update them to use `gl-cpp.error.*` in a follow up PR.
I also think we should change `gl-cpp.status_code` from an `int` to a human readable `string`. I will address that in a follow up PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14389)
> feat(otel): capture error message in traces (again)

- google/cloud/storage/tests/bucket_integration_test.cc
- google/cloud/storage/tests/curl_sign_blob_integration_test.cc
- google/cloud/storage/tests/object_checksum_integration_test.cc
- google/cloud/storage/tests/object_file_integration_test.cc
- google/cloud/storage/tests/object_hash_integration_test.cc
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/tests/object_media_integration_test.cc
- google/cloud/storage/tests/object_rewrite_integration_test.cc
The testbench does not support the features used by these tests. We may
consider removing the tests, the unit tests are enough for gRPC, and we
could (now) write unit tests for JSON too.
Motivated by #14385
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14388)
> test(storage): skip some gRPC integration tests

- google/cloud/internal/async_streaming_read_rpc_tracing.h
- google/cloud/internal/async_streaming_read_rpc_tracing_test.cc
Part of the work for #14371, same PR as #14379
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14393)
> fix(otel): async read stream tracing

- google/cloud/internal/async_read_write_stream_tracing.h
This line was unintentionally included in #14379
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14395)
> cleanup(otel): remove unnecessary line

- google/cloud/storage/tests/grpc_notification_integration_test.cc
This one does not work against production, and it may never work against
production. Disable it until I can get an authoritative answer.
Motivated by #14396
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14397)
> test(GCS+gRPC): skip another integration test

- generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_stub.cc
- generator/integration_tests/golden/v1/internal/golden_rest_only_rest_stub.cc
- generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_stub.cc
- generator/internal/stub_rest_generator.cc
- google/cloud/compute/global_operations/v1/internal/global_operations_rest_stub.cc
- google/cloud/compute/global_organization_operations/v1/internal/global_organization_operations_rest_stub.cc
- google/cloud/compute/instances/v1/internal/instances_rest_stub.cc
- google/cloud/compute/region_operations/v1/internal/region_operations_rest_stub.cc
- google/cloud/compute/zone_operations/v1/internal/zone_operations_rest_stub.cc
- google/cloud/internal/rest_stub_helpers.h
- google/cloud/internal/rest_stub_helpers_test.cc
- google/cloud/spanner/admin/internal/database_admin_rest_stub.cc
- google/cloud/spanner/admin/internal/instance_admin_rest_stub.cc
- google/cloud/sql/v1/internal/sql_operations_rest_stub.cc
fixes #14382 
Upcoming BigQuery Post calls introduce cases where `Response` and `Request` types are the same. This PR resolves an ambiguity that introduces in the current template function definitions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14390)
> impl(rest): leverage EmptyResponseType to remove ambiguities in Post and Delete template functions

- google/cloud/internal/tracing_http_payload.cc
- google/cloud/internal/tracing_http_payload_test.cc
- google/cloud/internal/tracing_rest_client_test.cc
- google/cloud/internal/tracing_rest_response_test.cc
Prefer using events, as it is easy to hit the number of spans limit for
long running requests. For example, a download of 1GiB objects can
exceed the 1,000 span limit if the application reads in chunks of 1MiB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14406)
> impl(otel): fewer OTel spans on HTTP requests

- google/cloud/opentelemetry/internal/recordable.cc
- google/cloud/opentelemetry/internal/recordable.h
- google/cloud/opentelemetry/internal/recordable_test.cc
- google/cloud/opentelemetry/trace_exporter.cc
We can only upload 32 events per span to Cloud Trace. Some spans may
have a lot more. Use a reservoir sampler to randomly select which events
are sent.  The first and last event are always preserved because they
usually contain something more important than any middle events.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14407)
> impl: reservoir sample for span events

- ci/cloudbuild/cloudbuild.yaml
Mirror the `logsBucket` path:
https://github.com/dbolduc/google-cloud-cpp/blob/2519bb74bfb849be1df98152d55f750ed195013a/ci/cloudbuild/cloudbuild.yaml#L68
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14418)
> ci: fix public logs link

- google/cloud/opentelemetry/internal/recordable_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14422)
> impl(otel): use gtest flag macro

- ci/cloudbuild/builds/gcc-oldest.sh
- ci/cloudbuild/dockerfiles/gcc-oldest.Dockerfile
- ci/cloudbuild/triggers/gcc-oldest-ci.yaml
- ci/cloudbuild/triggers/gcc-oldest-pr.yaml
The minimum GCC version we are required to test is `7.5`. Create a build
name that is more stable and (arguably) easier to grok.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14421)
> ci: new `gcc-oldest` build to replace `gcc-7.3`

- google/cloud/storage/internal/grpc/scale_stall_timeout_test.cc
- google/cloud/storage/internal/grpc/stub.cc
- google/cloud/storage/internal/grpc/stub_read_object_test.cc
The progress timeouts need to be scaled because the data arrives in
quantums on (roughly) 2MiB blocks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14430)
> fix(GCS+gRPC): scale timeout for downloads

- google/cloud/storage/internal/connection_impl.cc
- google/cloud/storage/internal/connection_impl.h
- google/cloud/storage/internal/connection_impl_object_test.cc
- google/cloud/storage/internal/retry_object_read_source.cc
- google/cloud/storage/internal/retry_object_read_source.h
This just changes `storage::internal::RetryObjectReadSource` to make the
class more testable. The backoff function is provided as an argument, so
it can be mocked. Likewise, the code to start new downloads is provided
by a factory function.
Incidentally, I captured the current options using
`internal::ImmutableOptions`, saving a number of copies in the process.
Part of the work for #14424
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14429)
> refactor(storage): make some code more testable

- .bazelrc
- CHANGELOG.md
- ci/verify_current_targets/.bazelrc
- doc/packaging.md
- google/cloud/BUILD.bazel
- google/cloud/opentelemetry/quickstart/.bazelrc
- google/cloud/opentelemetry/quickstart/README.md
- google/cloud/testing_util/BUILD.bazel
In `v1.16.0`, OpenTelemetry started compiling with Abseil all the time with Bazel. See https://github.com/open-telemetry/opentelemetry-cpp/pull/2679
This means their `--io_opentelemetry_cpp//api:with_abseil` flag is now obsolete. Yay. That is good moving forward.
They plan to remove the flag in the future.
The annoying this is that we cannot know which version of OpenTelemetry a downstream target is using. So we will not know if the flag is required or if the flag has been removed. Yuck.
I think our best path forward is to adapt to the change, and try to alert customers to configuration errors through documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud …
> cleanup(otel): bazel flag is obsolete

- google/cloud/storage/internal/retry_object_read_source.cc
- google/cloud/storage/internal/retry_object_read_source_test.cc
`storage::Client::ReadObject()` resumes a download that gets
interrupted (controlled by policy). Before making a resume attempt, the
library backsoff in case the problem is load related. The library was
*also* backing off before issuing the first `Read()` on the newly
created source of data. That effectively doubles the backoff time.
Fixes #14424
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14427)
> fix(storage): only backoff before resume attempts

- google/cloud/internal/sha256_hash.cc
- google/cloud/internal/sha256_hmac.cc
Fixes #14436
If you need to verify the values, consider:
https://github.com/wine-mirror/wine/blob/94fd0561b740dbb94608a8c4b3e1283e345e8c7a/include/bcrypt.h#L450
https://github.com/wine-mirror/wine/blob/94fd0561b740dbb94608a8c4b3e1283e345e8c7a/include/bcrypt.h#L457
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14437)
> fix: workaround missing SHA256 macros in MinGW-w64

- ci/cloudbuild/builds/asan.sh
The ODR problems are fixed in the Bazel Central Registry modules.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14447)
> ci: use `bzlmod` for `asan` build

- google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
- google/cloud/bigtable/tools/run_emulator_utils.sh
The coverage build may be slow to start because it needs to compile the
bigtable emulator with different flags. We cannot use `bazel run` to run
a binary compiled with coverage support.
I also fixed some mistakes in the emulator log dumps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14446)
> test(bigtable): speed up coverage startup time

- ci/gha/builds/windows-cmake.sh
Fix typo, should be `windows` in windows-cmake.sh rather than `macos`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14455)
> cleanup(build): fix typo in windows-cmake.sh

- google/cloud/storage/internal/tracing_object_read_source.h
- google/cloud/storage/internal/tracing_object_read_source_test.cc
Thanks to @dbolduc for the additional review on #14435
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14459)
> cleanup(storage): address post-merge comments

- ci/cloudbuild/dockerfiles/fedora-latest-bazel.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-publish-docs.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-m32.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile
Set the docker root password to `cloudcxx`, because empty password doesn't work for `su -` in docker container.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14470)
> ci: change docker root password to a non-empty string

- .bazelrc
- MODULE.bazel
- bazel/bzlmod0.bzl
- bazel/deps-cache.py
- bazel/development0.bzl
- bazel/development2.bzl
- bazel/downloader.cfg
- bazel/workspace0.bzl
- external/googleapis/CMakeLists.txt
Use Bazel's downloader config to dynamically rewrite the URLs that need
downloading. That means less hacking of our `MODULE.bazel`, and `*.bzl`
files.
Change the script that maintains the dependency cache to find all the
`bzlmod` dependencies via `bazel mod deps` and some Python scripting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14465)
> ci(bazel): dynamically add dependency cache

- google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc
- google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/admin/integration_tests/instance_admin_rest_integration_test.cc
We have been seeing flakes in our `integration-daily` build.
e.g. https://console.cloud.google.com/cloud-build/builds;region=us-east1/2f83568c-9612-44d5-aafe-5c03e9f7a319?project=936212892354
```
google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc:187: Failure
Value of: instance
Expected: code is equal to OK and message is anything
Actual: 176-byte object <00-46 02-C8 BC-7F 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 ... 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>, whose status is …
```
> ci: reduce spanner CreateInstance rpcs in daily build

- ARCHITECTURE.md
Fix the typo of text and link.
`DataClient` is the client class, instead of `Table`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14471)
> doc: fix typo in ARCHITECTURE.md

- google/cloud/storage/internal/retry_object_read_source.cc
- google/cloud/storage/internal/retry_object_read_source_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14472)
> impl(storage): trace spans for `ReadObject` backoffs

- .bazelrc
- MODULE.bazel
- bazel/bzlmod0.bzl
- ci/cloudbuild/notifiers/alerts/function/function.cc
- examples/grpc_credential_types.cc
- google/cloud/internal/curl_handle.cc
- google/cloud/internal/curl_handle.h
- google/cloud/internal/curl_handle_factory.cc
- google/cloud/internal/curl_impl.cc
- google/cloud/internal/curl_wrappers.cc
- google/cloud/internal/curl_wrappers.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14467)
> ci: use bzlmod module for curl

- google/cloud/bigtable/internal/legacy_async_row_reader_test.cc
- google/cloud/bigtable/tests/table_sample_rows_integration_test.cc
In this case, missing `#include <iomanip>` which was implicitly included
via googletest.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14479)
> cleanup(bigtable): fix some IWYU problems

- doc/contributor/howto-guide-adding-generated-libraries.md
- generator/integration_tests/README.md
The old path will cause an exception,
```
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_3::detail::type_error'
what():  [json.exception.type_error.305] cannot use operator[] with a string argument with null
Aborted
```
Replace with new path which we already have in `generate-libraries.sh`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14487)
> doc: use correct path in codegen command

- google/cloud/storage/internal/async/reader_connection_factory_test.cc
Use protos directly, since we do not use `storage::internal::*Request`
in the API anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14496)
> cleanup(GCS+gRPC): simplify some tests

- google/cloud/storage/internal/grpc/object_request_parser.cc
- google/cloud/storage/internal/grpc/object_request_parser_test.cc
Fixes #14494
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14495)
> fix(GCS+gRPC): correctly resume ranged reads

- google/cloud/storage/doc/storage-grpc.dox
- google/cloud/storage/grpc_plugin.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14503)
> docs(GCS+gRPC): fix broken links

- generator/internal/http_option_utils.cc
Noticed in #14510
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14511)
> cleanup: spurious semicolons

- generator/internal/http_option_utils.cc
This is a pure refactor. I will be getting rid of this visitor. To keep the diffs small, pull out the `FormatQueryParameterCode` function first.
Note that we:
- add `method` as a parameter
- return a `std::string`, instead of setting `method_http_query_parameters` in the function
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14513)
> refactor(generator): relocate `FormatQueryParameterCode`

- google/cloud/storage/testing/storage_integration_test.cc
- google/cloud/storage/testing/storage_integration_test.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14502)
> test(storage): support testing with alternative endpoints

- generator/internal/http_option_utils.cc
- generator/internal/http_option_utils.h
- generator/internal/http_option_utils_test.cc
- generator/internal/longrunning.cc
In practice, this function does not return errors. If it did return an error, we would generate code that doesn't compile, or abort. So just move the abort into the function, and simplify the return type.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14512)
> cleanup(generator): api version error handling

- generator/internal/http_option_utils.cc
- generator/internal/http_option_utils_test.cc
This was being set to a nonsense value, so stop setting it and checking for it.
This is how we use the `method_request_params` variable:
https://github.com/googleapis/google-cloud-cpp/blob/a86e887fe2756935a51d4d93b42e45a0fdde7812/generator/internal/metadata_decorator_generator.cc#L45-L48
Note that `HasHttpRoutingHeader() == false` when something is a `HttpSimpleInfo`.
https://github.com/googleapis/google-cloud-cpp/blob/a86e887fe2756935a51d4d93b42e45a0fdde7812/generator/internal/http_option_utils.cc#L430-L433
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14517)
> cleanup(generator): remove unused var

- google/cloud/storage/testing/storage_integration_test.cc
- google/cloud/storage/testing/storage_integration_test.h
- google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc
- google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc
- google/cloud/storage/tests/grpc_default_object_acl_integration_test.cc
- google/cloud/storage/tests/grpc_hmac_key_integration_test.cc
- google/cloud/storage/tests/grpc_integration_test.cc
- google/cloud/storage/tests/grpc_notification_integration_test.cc
- google/cloud/storage/tests/grpc_object_acl_integration_test.cc
- google/cloud/storage/tests/grpc_object_media_integration_test.cc
- google/cloud/storage/tests/grpc_object_metadata_integration_test.cc
- google/cloud/storage/tests/grpc_service_account_integration_test.cc
Part of the work for #14399
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14514)
> cleanup(GCS+gRPC): simplify integration tests

- google/cloud/storage/tests/decompressive_transcoding_integration_test.cc
- google/cloud/storage/tests/key_file_integration_test.cc
- google/cloud/storage/tests/object_basic_crud_integration_test.cc
- google/cloud/storage/tests/object_file_integration_test.cc
- google/cloud/storage/tests/object_media_integration_test.cc
- google/cloud/storage/tests/object_resumable_write_integration_test.cc
- google/cloud/storage/tests/service_account_integration_test.cc
- google/cloud/storage/tests/signed_url_conformance_test.cc
- google/cloud/storage/tests/thread_integration_test.cc
- google/cloud/storage/tests/tracing_integration_test.cc
Use the common function to initialize the `storage::Client` object.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14515)
> cleanup(storage): prefer `MakeIntegrationTestClient()`

- google/cloud/storage/tests/object_checksum_integration_test.cc
- google/cloud/storage/tests/object_hash_integration_test.cc
We used to have a few parametric tests to validate working with the XML
and JSON transport, but we no longer support XML, and the tests only
used the "JSON" parameter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14523)
> cleanup(storage): no parametric XML tests

- generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_stub.cc
- generator/integration_tests/golden/v1/internal/golden_rest_only_rest_stub.cc
- generator/internal/descriptor_utils_test.cc
- generator/internal/http_option_utils.cc
- generator/internal/http_option_utils.h
- generator/internal/http_option_utils_test.cc
- google/cloud/compute/firewall_policies/v1/internal/firewall_policies_rest_stub.cc
- google/cloud/compute/global_organization_operations/v1/internal/global_organization_operations_rest_stub.cc
- google/cloud/sql/v1/internal/sql_flags_rest_stub.cc
Only ever return an `HttpExtensionInfo`, which we pass on to functions that accept a `variant<HttpExtensionInfo, HttpSimpleInfo, absl::monostate>`. I will clean up those functions in a follow up PR.
The generated code diff speaks for itself. 
---
The removed expectation from `descriptor_utils_test.cc` originates from here:
https://github.com/googleapis/google-cloud-cpp/blob/eb1232de7ee83ae2e34000ce0ec87cc93b423166/generator/internal/http_option_utils.cc#L326-L330
The test rpc does not have a `google.api.http` annotation, so we don't care about the `method_http_query_parameters` variable.
---
While we're here use some container matchers in our tests so we get better error messages.
There are some tests that use
```cc
EXPECT_THAT(map.at("key"), Eq("value))
``` …
> cleanup(generator): simplify http info parsing

- .github/workflows/test-runner-untrusted.yml
- .github/workflows/test-runner.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14531)
> ci: add org member check

- generator/internal/http_option_utils.cc
- generator/internal/http_option_utils.h
There is only one case, so remove the `HttpSimpleInfo`, `absl::monostate` branches in `SetHttpQueryParameters`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14535)
> cleanup(generator): fewer HttpInfo code paths 2

- generator/internal/http_option_utils.cc
- generator/internal/http_option_utils.h
There is only one case, so remove the `HttpSimpleInfo`, `absl::monostate` branches in `SetHttpDerivedMethodVars`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14534)
> cleanup(generator): fewer HttpInfo code paths

- google/cloud/edgenetwork/CMakeLists.txt
- google/cloud/edgenetwork/README.md
- google/cloud/edgenetwork/quickstart/quickstart.cc
Replace the deprecated RPC `ListZones` with `ListNetworks` in the quickstart sample code. The deprecation information is in `google/cloud/edgenetwork/v1/service.proto`.
We don't have a zone in the our test project's test location, so a NOT_FOUND error is expected in the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14545)
> docs(quickstart): Replace deprecated RPC in the sample code

- google/cloud/storage/tests/decompressive_transcoding_integration_test.cc
Use timeouts more appropriate for gRPC, specially after the gRPC timeout
scaling fixes.
Part of the work for #14543
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14549)
> test(storage): deflake decompressive transcoding test

- generator/internal/client_generator.cc
- google/cloud/securitycenter/v1/security_center_client.h
Add `deprecation_macro` that is missed in #14553
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14559)
> cleanup(generator): Add missing deprecation tag

- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl_read_test.cc
- google/cloud/storage/internal/async/connection_impl_upload_test.cc
- google/cloud/testing_util/async_sequencer.h
The gRPC rules require asynchronous RPCs (including asynchronous
streaming RPCs) to remain alive until `Finish()` **completes**. That is,
until the callback for `Finish()` is invoked. The code
could destroy them as soon as `Finish()` was **invoked**.
Fixes #14562 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14561)
> fix(GCS+gRPC): RPC lifetime was too short

- google/cloud/internal/curl_wrappers.cc
- google/cloud/internal/curl_wrappers_test.cc
Our logs censored Bearer tokens over HTTP/1.x.  These tokens appear in the "info" callbacks, not the "header" callbacks for HTTP/2, and we failed to censor the tokens in that case.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14564)
> fix(common): censor Bearer tokens over HTTP/2

- google/cloud/storage/internal/hash_function_impl.cc
- google/cloud/storage/internal/hash_function_impl_test.cc
When reading data from GCS we don't necessarily know the initial offset.
Reading the last N bytes is expressed as a negative offset in the
request, and the returned offset is not known until the first message.
But once the offset is known, receiving out of order data indicates a
bug in the client library, and should be detected.
The code was assuming the initial offset was always 0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14567)
> fix(GCS+gRPC): handle offsets in `Hash*::Update()`

- .github/workflows/macos-bazel.yml
- .github/workflows/macos-cmake.yml
- .github/workflows/test-runner-untrusted.yml
- .github/workflows/test-runner.yml
- .github/workflows/windows-bazel.yml
- .github/workflows/windows-cmake.yml
- ci/gha/builds/lib/bazel.sh
- ci/gha/builds/macos-bazel.sh
- ci/gha/builds/windows-bazel.sh
While sccache is unavailable in a read_only mode, both the bazel-cache and vcpkg-cache can be used without credentials.
Integration tests, since they require credentials, will not be run by workflows started by test-runner-untrusted.yml.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14570)
> ci: support external read-only cache for untrusted PRs

- google/cloud/storage/internal/async/connection_impl_read_test.cc
- google/cloud/storage/internal/async/reader_connection_impl.cc
- google/cloud/storage/internal/async/reader_connection_impl.h
- google/cloud/storage/internal/async/reader_connection_impl_test.cc
Another case where we need to wait for `Finish()` before deleting the
underlying RPC.  This is slightly wasteful, as we could start the resume
while the `Finish()` operation is running.  We can improve that later,
once the code no longer crashes.
Fixes #14568
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14569)
> fix(GCS+gRPC): delay resume until Finish() returns

- .github/workflows/macos-cmake.yml
- .github/workflows/test-runner-untrusted.yml
- .github/workflows/test-runner.yml
- .github/workflows/windows-cmake.yml
- ci/gha/builds/macos-cmake.sh
- ci/gha/builds/windows-cmake.sh
Missed these in the previous PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14573)
> ci: also disable integration tests for untrusted GHA cmake workflows

- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl_read_hash_test.cc
- google/cloud/storage/tests/async_client_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14558)
> fix(GCS+gRPC): no hash validation for ranged reads

- google/cloud/spanner/samples/samples.cc
Add samples for instance partitions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14574)
> feat(spanner): add samples for instance partitions

- google/cloud/storage/testing/storage_integration_test.cc
Integration tests are flaky enough without the GCS+gRPC metrics enabled
by default. And the logs are also hard to grok with the additional
metrics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14575)
> test(storage): disable metrics in integration tests

- google/cloud/storage/async/resume_policy.cc
- google/cloud/storage/async/resume_policy.h
- google/cloud/storage/async/resume_policy_test.cc
- google/cloud/storage/internal/async/connection_impl_read_test.cc
- google/cloud/storage/internal/async/default_options.cc
- google/cloud/storage/internal/async/reader_connection_resume.cc
- google/cloud/storage/internal/async/reader_connection_resume_test.cc
By default we want to resume downloads on any error, as long as at least
some data was received. Even if the final status of the stream is scary
(say `NOT_FOUND`), we know the previous attempt was working. Seems
worthwhile to attempt a resume in this case. We also don't want to
believe a resume was "successful" until at least some data was received.
We don't get errors until the first `Read()` attempt.
Fixes #14578
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14579)
> fix(GCS+gRPC): reads resume only after some data

- generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_stub.cc
- generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_stub.cc
- generator/internal/descriptor_utils_test.cc
- generator/internal/http_option_utils.cc
- generator/internal/http_option_utils_test.cc
- google/cloud/compute/backend_buckets/v1/internal/backend_buckets_rest_stub.cc
- google/cloud/compute/backend_services/v1/internal/backend_services_rest_stub.cc
- google/cloud/compute/disks/v1/internal/disks_rest_stub.cc
- google/cloud/compute/firewall_policies/v1/internal/firewall_policies_rest_stub.cc
- google/cloud/compute/global_network_endpoint_groups/v1/internal/global_network_endpoint_groups_rest_stub.cc
- google/cloud/compute/instance_group_manager_resize_requests/v1/internal/instance_group_manager_resize_requests_rest_stub.cc
- google/cloud/compute/instance_group_managers/v1/internal/instance_group_managers_rest_stub.cc
- google/cloud/compute/instances/v1/internal/instances_rest_stub.cc
- google/cloud/compute/network_firewall_policies/v1/internal/network_firewall_policies_rest_stub.cc
- google/cloud/compute/networks/v1/internal/networks_rest_stub.cc
- google/cloud/compute/node_groups/v1/internal/node_groups_rest_stub.cc
- google/cloud/compute/projects/v1/internal/projects_rest_stub.cc
- google/cloud/compute/public_advertised_prefixes/v1/internal/public_advertised_prefixes_rest_stub.cc
- google/cloud/compute/public_delegated_prefixes/v1/internal/public_delegated_prefixes_rest_stub.cc
- google/cloud/compute/region_disks/v1/internal/region_disks_rest_stub.cc
- google/cloud/compute/region_instance_group_managers/v1/internal/region_instance_group_managers_rest_stub.cc
- google/cloud/compute/region_network_endpoint_groups/v1/internal/region_network_endpoint_groups_rest_stub.cc
- google/cloud/compute/region_network_firewall_policies/v1/internal/region_network_firewall_policies_rest_stub.cc
- google/cloud/compute/region_security_policies/v1/internal/region_security_policies_rest_stub.cc
- google/cloud/compute/security_policies/v1/internal/security_policies_rest_stub.cc
- google/cloud/spanner/admin/internal/database_admin_rest_stub.cc
- google/cloud/spanner/admin/internal/instance_admin_rest_stub.cc
- google/cloud/sql/v1/internal/sql_connect_rest_stub.cc
- google/cloud/sql/v1/internal/sql_instances_rest_stub.cc
Part of the work for #14492 
When `body = "*"`, we include the whole `request` as the payload. This means we do not need to include any individual fields in the request as query parameters.
Spec:
https://github.com/googleapis/googleapis/blob/a91d1a37cb86a0e49fdc21d8b4416eb1c2a083ec/google/api/http.proto#L169-L173
---
I removed a failing unit test which was setting a different expectation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14560)
> cleanup(generator): fewer query params already in body

- .github/workflows/windows-cmake.yml
We have been seeing build failures due to running out of space. Specifically on Windows + CMake + Debug + Shard2 e.g.:
https://github.com/googleapis/google-cloud-cpp/actions/runs/10174328835
So rebalance the shards. Note that we skip `pubsublite` which is large, and already included in the pubsub shard.
Tested: https://github.com/googleapis/google-cloud-cpp/actions/runs/10184345439/job/28171467848
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14593)
> ci: reblance windows shards

- generator/internal/http_option_utils.cc
Following the [comment](https://github.com/googleapis/google-cloud-cpp/pull/14595#pullrequestreview-2211120461).
[Static variable should be trivially destructible](https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables).
`std::is_trivially_destructible<std::regex>()` is `false`.
`std::is_trivially_destructible<std::regex*>()` is `true`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14599)
> cleanup(generator): make static variable trivially destructible

- .github/renovate.json
The naming is slightly different with bzlmod. Teach renovate-bot the new names, so, for example, #14604 and #14533 get consolidated into one PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14606)
> chore: consolidate renovate-bot bzlmod PRs

- doc/contributor/howto-guide-find-missing-service-protos.md
- doc/contributor/howto-guide-update-googleapis-sha.md
`bzlmod` puts these in a different place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14608)
> cleanup: missing services script bzlmod

- ci/cloudbuild/builds/check-api.sh
We often detect changes from `absl` internal types. Skip them like we do with gRPC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14613)
> chore: skip absl types in check-api

- generator/internal/option_defaults_generator.cc
- google/cloud/opentelemetry/integration_tests/trace_exporter_integration_test.cc
- google/cloud/opentelemetry/trace_exporter_test.cc
- google/cloud/trace/v2/internal/trace_option_defaults.cc
Fixes #14611 
Avoid an infinite export loop when `GOOGLE_CLOUD_CPP_OPENTELEMETRY_TRACING` is set by never tracing the Cloud Trace client.
While the solution is not good, it seemed less bad than the alternatives listed in the parent issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14612)
> fix(otel): avoid infinite trace export loop

- google/cloud/internal/curl_impl.cc
For a Patch, Post, or Put request, `curl_multi_perform` should result in all the data from the associated `WriteVector` being consumed before it returns. Except in the case of a timeout, in which case we do not want libcurl to attempt to transmit the rest of the data while we read any remaining response data to populate the `Status` error message.
fixes #14614 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14615)
> fix(rest): prevent libcurl callback from reading bad address

- generator/internal/descriptor_utils.cc
- generator/internal/descriptor_utils.h
- generator/internal/descriptor_utils_test.cc
- generator/internal/pagination.cc
Note that `FormatDoxygenLink(...)` is declared in:
https://github.com/googleapis/google-cloud-cpp/blob/d9adf56750af9c9d0917115b7d9ef36ed19d03ae/generator/internal/doxygen.h#L25-L27
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14616)
> cleanup(generator): remove unused code

- google/cloud/internal/curl_impl.cc
- google/cloud/internal/curl_impl.h
Leverage RAII to ensure the `CURLOPT_READFUNCTION` is set to `ReadFunctionAbort` regardless if `MakeRequestImpl` returns normally or if an exception is thrown.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14617)
> impl(rest): set ReadFunctionAbort via RAII

- google/cloud/universe_domain/demo/WORKSPACE.bazel
fixes #13494 
renovate-bot is updating the SHA, just needed to remove the TODO
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14621)
> chore: update universe_domain demos WORKSPACE.bazel

- ci/cloudbuild/triggers/bazel-otel-abi-2-ci.yaml
This was running on PRs. I also uploaded it to GCB with:
```
ci/cloudbuild/trigger.sh --import ci/cloudbuild/triggers/bazel-otel-abi-2-ci.yaml 
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14632)
> ci: fix trigger to run on CI

- google/cloud/compute/service_dirs.bzl
`clang-tidy-compute` enforces that these things are sorted, but it only runs on CI.
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/448e7048-59d0-4b78-9834-7fab8df9ac3f;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/aa75123f5c40c84901971820f65fa542891c5ee6/fedora-latest-cmake-clang-tidy-compute/log-448e7048-59d0-4b78-9834-7fab8df9ac3f.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14641)
> cleanup(compute): sort service_dirs

- google/cloud/opentelemetry/integration_tests/trace_exporter_integration_test.cc
- google/cloud/opentelemetry/trace_exporter_test.cc
I made a bad decision in this commit, so revert it: https://github.com/googleapis/google-cloud-cpp/pull/14612/commits/8150ba796fe2778dfef46d43aa67c1cd16a3a420
This will make the import to google3 go more smoothly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14642)
> cleanup(otel): move test, and guard it

- google/cloud/policysimulator/CMakeLists.txt
Fixes #14643 
If you are unfamiliar with `SKIP_REGULAR_EXPRESSION`, see: https://cmake.org/cmake/help/latest/prop_test/SKIP_REGULAR_EXPRESSION.html
... but a better explainer is here: https://gist.github.com/pudnax/141f0f114c5530d435eea5cd80ccbd11
Basically:
- the quickstart always runs
- if it passes, the test is marked as passing
- if it fails and "RESOURCE_EXHAUSTED" is in the output, the test is marked as skipped
- if it fails and "RESOURCE_EXHAUSTED" is not in the output, the test is failed
That seems like what we want.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14644)
> ci: ignore quota flakes in policysimulator quickstart

- release/README.md
In order to make sure that our monthly release has an updated googleapis SHA, potentially containing updates that service owners are interested in, update it just prior to release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14618)
> doc: add googleapis update step for release

- google/cloud/internal/win32/parse_service_account_p12_file.cc
As part of investigating #14349, I noticed that the `PFXImportCertStore` function persists the keys on disk by default. This PR fixes that by passing the `PKCS12_NO_PERSIST_KEY` flag, and geting a preallocated `HCRYPTPROV` to get the certificate's key.
Validated locally by running `_build/Default/google/cloud/storage/oauth2_service_account_credentials_test.exe --gtest_filter=ServiceAccountCredentialsTest.ParseSimpleP12 --gtest_repeat=-1` and letting the test run hundreds of times. I'm not sure if this will fix the occasional CI failures, but this looks like an improvement to me.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14645)
> fix: do not persist the keys loaded from PKCS#12 on Windows

- google/cloud/bigtable/row_range.cc
- google/cloud/bigtable/row_range.h
- google/cloud/bigtable/row_range_test.cc
Sanitize input for the ctor from protos. Hopefully the comment in the code explains why we want to do this.
Also correct the documentation for this class.
I considered deprecating the constructor that takes a proto, but it is too complicated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14651)
> fix(bigtable): sanitize RowRange proto input

- ci/cloudbuild/builds/cmake-install.sh
- external/googleapis/protolists/backupdr.list
- external/googleapis/update_libraries.sh
This makes the backupdr logging protos available in `google-cloud-cpp::backupdr-protos`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14662)
> fix(backupdr): include logging protos with cmake

- generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_logging_decorator.cc
- generator/internal/connection_generator.cc
- generator/internal/connection_impl_generator.cc
- generator/internal/connection_impl_generator.h
- generator/internal/connection_impl_rest_generator.cc
- generator/internal/connection_impl_rest_generator.h
- generator/internal/logging_decorator_generator.cc
- generator/internal/logging_decorator_rest_generator.cc
- generator/internal/metadata_decorator_generator.cc
- generator/internal/metadata_decorator_rest_generator.cc
- generator/internal/mock_connection_generator.cc
- generator/internal/round_robin_decorator_generator.cc
- generator/internal/stub_generator.cc
- generator/internal/stub_generator_base.cc
- generator/internal/stub_rest_generator.cc
- generator/internal/tracing_connection_generator.cc
- generator/internal/tracing_connection_generator.h
- generator/internal/tracing_stub_generator.cc
A followup cleanup of #14657.
Generalize return type strings of the non-lro methods in generator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14669)
> cleanup(generator): generalize return type strings followup

- generator/internal/longrunning.cc
- generator/internal/longrunning_test.cc
- generator/internal/service_code_generator_test.cc
If a method is grpc longrunning operation, it should also define `google.longrunning.operation_info` extension.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14675)
> cleanup(generator): check extension existence in IsGRPCLongrunningOperation

- google/cloud/spanner/admin/integration_tests/instance_admin_rest_integration_test.cc
- google/cloud/spanner/create_instance_request_builder.h
- google/cloud/spanner/create_instance_request_builder_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14678)
> feat(spanner): support instance edition

- doc/contributor/howto-guide-update-googleapis-sha.md
- external/googleapis/renovate.sh
- release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14682)
> chore: allow commit SHA override in renovate.sh

- google/cloud/internal/populate_common_options.cc
- google/cloud/internal/populate_common_options_test.cc
https://google.aip.dev/auth/4110 says we should have used the env var `GOOGLE_CLOUD_QUOTA_PROJECT` instead of making up our own `GOOGLE_CLOUD_CPP_USER_PROJECT`.
So we will respect both.
Note that this is separate from our `QuotaUserOption` which sets the `x-goog-quota-user` header. Confusing stuff.
I do not think we need to publicize the new form of the env var.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14684)
> fix: respect `GOOGLE_CLOUD_QUOTA_PROJECT`

- google/cloud/opentelemetry/integration_tests/monitoring_exporter_integration_test.cc
- google/cloud/opentelemetry/monitoring_exporter.cc
- google/cloud/opentelemetry/monitoring_exporter.h
- google/cloud/opentelemetry/monitoring_exporter_test.cc
- google/cloud/storage/internal/grpc/metrics_exporter_impl.cc
- google/cloud/storage/internal/grpc/metrics_exporter_impl_test.cc
- google/cloud/storage/internal/grpc/metrics_exporter_options.cc
- google/cloud/storage/internal/grpc/metrics_exporter_options_test.cc
Fixes #14683
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14693)
> feat(otel): release GCM exporter

- .github/workflows/windows-bazel.yml
- .github/workflows/windows-cmake.yml
Fixes #14314 
The machines now come with VC Toolset `14.41.*` which successfully build `upb`.
Tested: https://github.com/googleapis/google-cloud-cpp/actions/runs/10779264515. Note that the failures are due to running out of disk space, not in building `upb` with `vcpkg`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14694)
> ci: remove vc toolset 14.40 workaround

- MODULE.bazel
rules_proto is used in protos/google/cloud/compute/BUILD.bazel whereas rules_python is used immediately below with the python extension.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14696)
> fix(deps): Remove dev_dependency = True for rules_proto and rules_python.

- google/cloud/spanner/samples/CMakeLists.txt
- google/cloud/spanner/samples/graph_samples.cc
- google/cloud/spanner/samples/spanner_client_integration_samples.bzl
Add a few code snippets to illustrate how to use Spanner Graph functionality in Java. These examples resemble other snippets for how various other Spanner features can be used.
Fixes #14659
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660)
> docs: create a few code snippets as examples for using Spanner Graph using cpp

- google/cloud/aiplatform/CMakeLists.txt
- google/cloud/aiplatform/samples/BUILD.bazel
- google/cloud/aiplatform/samples/CMakeLists.txt
- google/cloud/aiplatform/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14703)
> doc(aiplatform): add Vertex AI samples

- generator/internal/http_option_utils.cc
- generator/internal/http_option_utils.h
- generator/internal/http_option_utils_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14707)
> feat(mixin): add mixin support in http option utils

- google/cloud/aiplatform/CMakeLists.txt
- google/cloud/generativelanguage/CMakeLists.txt
Adding these sample dirs is taken care of by:
https://github.com/googleapis/google-cloud-cpp/blob/00ff87b59b9ef7b3ed62a3a174321f968c86101f/cmake/GoogleCloudCppFeatures.cmake#L447
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14717)
> chore: remove redundant cmake add_subdirs for samples

- .bazelrc
Part of the work for #12760 
Note that changes in the `.bazelrc` only affect our `WORKSPACE`. Downstream applications cannot be affected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14721)
> ci: enable layering check in bazel

- generator/BUILD.bazel
- generator/internal/descriptor_utils.cc
- generator/internal/http_option_utils.cc
- generator/internal/http_option_utils.h
- generator/internal/http_option_utils_test.cc
- generator/internal/mixin_utils.cc
- generator/internal/mixin_utils.h
- generator/internal/mixin_utils_test.cc
Refactor mixin utils to use HttpRule as http overrides.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14723)
> cleanup(mixin): refactor mixin utils to use HttpRule

- google/cloud/internal/curl_impl.cc
- google/cloud/internal/curl_impl.h
- google/cloud/internal/curl_writev.h
As a member variable, writev_ will remain in scope until the request is complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14732)
> fix(rest): promote buffer curl reads from to member variable

- google/cloud/common_options.h
- google/cloud/doc/guac.dox
- google/cloud/grpc_options.cc
- google/cloud/grpc_options_test.cc
- google/cloud/internal/populate_grpc_options.cc
- google/cloud/internal/populate_grpc_options_test.cc
Part of the work for #14733 
Start with gRPC support only, because that is all I have had time to test.
My follow up PR will add the sample, which doubles as an integration test. It is involved enough to warrant its own PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14737)
> feat: add support for API keys

- google/cloud/internal/populate_rest_options.cc
- google/cloud/internal/populate_rest_options_test.cc
- google/cloud/internal/rest_set_metadata.cc
- google/cloud/internal/rest_set_metadata_test.cc
Part of the work for #14733 
Note that none of the services for which we have a REST transport layer (`bigquery`, `compute`, `sql`) support authentication via API keys. So there is no useful integration test for us to write at this time.
This PR is still worth having.  We want to be ready if:
- Any of these services start supporting API keys.
- We generate REST transport layers (using gRPC transcoding) for a service that does support API keys.
---
Just to verify the spec, I ran:
```sh
$ API_KEY=...
$ curl -X POST \
-H "Content-Type: application/json" \
-H "x-goog-api-key: ${API_KEY}" \
-d '{"document":{"content":"I finally figured out how to make a request using curl. This is the best day of my life!","type":"PLAIN_TEXT"}}' \
https://content-language.googleapis.com/v1/documents:analyzeSent …
```
> feat: API key support over REST transport

- examples/BUILD.bazel
- examples/CMakeLists.txt
- examples/api_key.cc
Part of the work for #14733 
Add a sample for `apikeys_create_api_key` ([cloud docs](https://cloud.google.com/docs/authentication/api-keys#create)) and `apikeys_authenticate_api_key` ([cloud docs](https://cloud.google.com/docs/authentication/api-keys-use#using-with-client-libs))
These API keys give access to our project's billing account. So we make sure not to print the `key_string`, and periodically remove old keys that may leak. We also restrict the scope of these keys to just the Natural Language API (which we use to test that our library supports API keys).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14740)
> docs: add samples for API key auth

- google/cloud/internal/rest_set_metadata.cc
- google/cloud/internal/rest_set_metadata_test.cc
Thank you @devbww for noticing.
I added a unit test out of shame.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14748)
> fix: `ApiKeyOption` without `UserProjectOption` over REST

- google/cloud/pubsub/samples/topic_admin_samples.cc
Adds a sample for creating an ingestion from GCS import topic for Pub/Sub.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14749)
> docs(pubsub): Add ingestion from GCS topic creation sample

- examples/api_key.cc
Make it clear that the API key restriction in our sample is optional.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14752)
> docs: explain api key restrictions

- ci/cloudbuild/builds/lib/bazel.sh
- ci/cloudbuild/builds/lib/universe_domain.sh
- ci/cloudbuild/builds/universe-domain-demo.sh
- google/cloud/storage/tests/BUILD.bazel
- google/cloud/storage/tests/universe_domain_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14728)
> tests(storage): add universe domain integration test

- google/cloud/storage/benchmarks/async_throughput_benchmark.cc
- google/cloud/storage/internal/grpc/metrics_histograms_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14751)
> fix(builds): require grpc >= 1.65.4 for async_throughput_benchmark.cc

- google/cloud/pubsub/samples/iam_samples.cc
- google/cloud/pubsub/samples/samples.cc
- google/cloud/pubsub/samples/topic_admin_samples.cc
Use the preferred admin client, and quash some `clang-tidy` errors. No I do not know how the `clang-tidy` errors got through our CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14758)
> cleanup(pubsub): samples

- examples/api_key.cc
Avoid using `ApiKeyOption` which we will remove shortly. We do not want to scrap the sample. Luckily we can achieve the same effect as `ApiKeyOption` using other options in our library.
Also, we should break out of the backoff loop when an attempt to authenticate is successful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14760)
> refactor: avoid `ApiKeyOption` in sample

- google/cloud/internal/tracing_rest_client.cc
- google/cloud/internal/tracing_rest_client_test.cc
Part of the work for #14733
Truncate any API keys in our traces. While we're here, test that we truncate OAuth2 tokens as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14755)
> impl: censor API key header in traces

- google/cloud/common_options.h
- google/cloud/grpc_options.cc
- google/cloud/grpc_options_test.cc
- google/cloud/internal/populate_grpc_options.cc
- google/cloud/internal/populate_grpc_options_test.cc
- google/cloud/internal/populate_rest_options.cc
- google/cloud/internal/populate_rest_options_test.cc
- google/cloud/internal/rest_set_metadata.cc
- google/cloud/internal/rest_set_metadata_test.cc
This is breaking at HEAD, but note that `ApiKeyOption` has not been released yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14761)
> cleanup: revert `ApiKeyOption` changes

- google/cloud/pubsub/samples/topic_admin_samples.cc
Uses the correct `START` and `END` tags to specify the ingestion from GCS samples. This will allow DevRel automation to find this snippet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14773)
> docs(pubsub): Fix region tags for Pub/Sub ingestion from GCS samples

- ci/cloudbuild/dockerfiles/demo-alpine-stable.Dockerfile
- ci/cloudbuild/dockerfiles/demo-debian-bookworm.Dockerfile
- ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
- ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
- ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
- ci/cloudbuild/dockerfiles/demo-rockylinux-9.Dockerfile
- ci/cloudbuild/dockerfiles/demo-ubuntu-24.04.Dockerfile
- ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
- ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cmake.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cxx14.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-cxx20.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-latest-publish-docs.Dockerfile
- ci/cloudbuild/dockerfiles/fedora-m32.Dockerfile
- ci/cloudbuild/dockerfiles/gcc-oldest.Dockerfile
- ci/cloudbuild/dockerfiles/ubuntu-20.04-install.Dockerfile
- doc/packaging.md
This was a transitional cmake variable that was removed in `opentelemetry-cpp` v1.17.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14775)
> cleanup: remove unused otel compile def

- google/cloud/internal/credentials_impl.cc
- google/cloud/internal/credentials_impl.h
- google/cloud/internal/grpc_api_key_authentication_test.cc
- google/cloud/internal/unified_grpc_credentials.cc
- google/cloud/internal/unified_grpc_credentials_test.cc
- google/cloud/internal/unified_rest_credentials.cc
- google/cloud/storage/internal/unified_rest_credentials.cc
- google/cloud/testing_util/credentials.h
We implement the gRPC half only.
We short-circuit the REST half because
- None of the services for which we use REST transport support API keys.
- The REST half requires some refactoring to `oauth2_internal::Credentials`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14778)
> impl: add ApiKeyConfig, implement in gRPC

- examples/api_key.cc
- google/cloud/credentials.cc
- google/cloud/credentials.h
- google/cloud/internal/credentials_impl_test.cc
Introduce a dedicated API for authenticating with API keys.
Update the sample because it doubles as an integration test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14779)
> feat: API key authentication

- google/cloud/internal/curl_rest_client.cc
- google/cloud/internal/oauth2_authorized_user_credentials.h
- google/cloud/internal/oauth2_credentials.cc
- google/cloud/internal/oauth2_credentials.h
- google/cloud/internal/oauth2_credentials_test.cc
- google/cloud/internal/oauth2_google_credentials_test.cc
- google/cloud/internal/oauth2_minimal_iam_credentials_rest.cc
- google/cloud/internal/oauth2_service_account_credentials.h
- google/cloud/internal/unified_rest_credentials_test.cc
- google/cloud/storage/internal/unified_rest_credentials.cc
- google/cloud/storage/internal/unified_rest_credentials_test.cc
- google/cloud/storage/oauth2/authorized_user_credentials.h
- google/cloud/storage/oauth2/compute_engine_credentials.h
- google/cloud/storage/oauth2/service_account_credentials.h
Move `AuthorizationHeader(...)` from a standalone function into the `oauth2_internal::Credentials` class. This will allow us to return the `x-goog-api-key: ...` header in the case of API key credentials.
Also generalize the name to `AuthenticationHeader`, now that we are not exclusively setting the `Authorization: ...` header.
Note that we cannot change any public interfaces in `google::cloud::storage::oauth2`. These are sorta-kinda public.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14780)
> refactor(oauth2): prepare for API key auth

- google/cloud/compute/integration_tests/compute_integration_test.cc
Compute service is returning unusual error messages for an empty updateMask. We only care that it when we do set it, the value is transmitted accordingly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14782)
> impl(compute): reduce specificity on integration test error message

- .github/workflows/macos-cmake.yml
... otherwise `vcpkg` fails to build `gsutil`.
Tested: https://github.com/googleapis/google-cloud-cpp/actions/runs/11371663281/job/31634281100
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14792)
> ci: pin python version for gsutil

- doc/contributor/howto-guide-adding-generated-libraries.md
- external/googleapis/update_libraries.sh
1. Added one more case when we need to update the googleapis SHA.
2. Added a description of the error we expected when running `check-api-pr`
3. Replace `bazel` with `bazelisk` in case the lastest bazel version is not available via `apt get install`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14806)
> docs: add more cases for generating new libraries

- google/cloud/internal/oauth2_external_account_credentials.cc
- google/cloud/internal/oauth2_external_account_credentials.h
- google/cloud/internal/oauth2_external_account_credentials_test.cc
External account has two types of identities:
Workload Identity - 3rd party identities that represent a workload, the configs for this are all handled at a project level
Workforce Identity - 3rd party identities that represent a user, configs for this are handled at the org level
We already support Workload Identity. To support Workforce Identity, I added options `userProject` in the request header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14800)
> feat(oauth2): add support for external account workforce identity

- generator/internal/stub_generator.cc
- generator/internal/stub_rest_generator.cc
Prevent `pb` headers introduced by Mixin from being included twice.
This cleanup won't affect existing generated code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14819)
> cleanup(mixin): deduplicate mixin pb headers

- google/cloud/bigtable/column_family_test.cc
- google/cloud/bigtable/filters_test.cc
- google/cloud/bigtable/idempotent_mutation_policy_test.cc
- google/cloud/bigtable/internal/bulk_mutator_test.cc
- google/cloud/bigtable/internal/legacy_async_bulk_apply_test.cc
- google/cloud/bigtable/internal/legacy_async_row_reader_test.cc
- google/cloud/bigtable/internal/legacy_bulk_mutator_test.cc
- google/cloud/bigtable/mutation_batcher_test.cc
- google/cloud/bigtable/mutations_test.cc
- google/cloud/bigtable/polling_policy_test.cc
- google/cloud/bigtable/rpc_backoff_policy_test.cc
- google/cloud/bigtable/rpc_retry_policy_test.cc
- google/cloud/bigtable/table_apply_test.cc
- google/cloud/bigtable/table_bulk_apply_test.cc
- google/cloud/bigtable/table_check_and_mutate_row_test.cc
- google/cloud/bigtable/table_sample_row_keys_test.cc
- google/cloud/bigtable/tests/data_async_future_integration_test.cc
- google/cloud/bigtable/tests/data_integration_test.cc
- google/cloud/bigtable/tests/filters_integration_test.cc
- google/cloud/bigtable/tests/mutations_integration_test.cc
- google/cloud/future_generic_test.cc
- google/cloud/future_generic_then_test.cc
- google/cloud/future_void_test.cc
- google/cloud/future_void_then_test.cc
- google/cloud/internal/future_impl_test.cc
- google/cloud/storage/parallel_uploads_test.cc
- google/cloud/storage/tests/error_injection_integration_test.cc
- google/cloud/testing_util/chrono_literals.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14826)
> cleanup: chrono literals

- google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14829)
> cleanup(mixin): add integration tests

- google/cloud/speech/CMakeLists.txt
Our ci failed in running quickstart-production-pr, although we can succeed locally. See #14841.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14842)
> cleanup(quickstart): disable speech_quickstart_global

- google/cloud/internal/oauth2_google_credentials.cc
- google/cloud/internal/oauth2_google_credentials_test.cc
Part of the work for #12497 
Support ADC impersonation over REST.
We need to feed the `source_credentials` back into the thing that parses the ADC json, then fit that into our existing impersonation code.
I am not sure how to turn this into an integration test. If I figure it out, I will add one in a future PR.
To test locally I...
- created a SA (1) with permissions to read a GCS bucket
- created a SA (2) with `roles/ServiceAccountTokenCreator` on (1)
- Note that (2) does not have permission to read from GCS
- created ADC with impersonation
- the `source_credentials` are (2)
- `service_account_impersonation_url` points to (1)
- successfully ran the GCS quickstart!
- - - …
> feat(rest): support impersonated ADC

- google/cloud/spanner/internal/status_utils.cc
- google/cloud/spanner/proto_enum.h
- google/cloud/spanner/proto_message.h
- google/cloud/spanner/testing/status_utils.cc
Protobuf 6.30.0 will change the return types of Descriptor::name() and other methods to absl::string_view. This makes the code work both before and after such a change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14828)
> feat: prepare for breaking change in Protobuf C++ API.

- README.md
- google/cloud/managedkafka/CMakeLists.txt
- google/cloud/managedkafka/README.md
- google/cloud/managedkafka/doc/main.dox
- google/cloud/managedkafka/doc/options.dox
- google/cloud/managedkafka/quickstart/CMakeLists.txt
- google/cloud/managedkafka/quickstart/Makefile
- google/cloud/managedkafka/quickstart/README.md
- google/cloud/managedkafka/quickstart/WORKSPACE.bazel
Changes all instances of the "old" product title to the "new" one. Internal bug http://b/379316147
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14846)
> docs(managedkafka): change old title to new title

- cmake/GoogleCloudCppCommonOptions.cmake
We need our CI builds to not error on deprecated services and rpc that we still need to support.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14855)
> impl: warn but do not error on deprecated proto types

- ci/cloudbuild/builds/universe-domain.sh
- ci/cloudbuild/triggers/universe-domain-ci.yaml
- ci/cloudbuild/triggers/universe-domain-pr.yaml
I am renaming the build `universe-domain-demo` to `universe-domain`.
This is the first step - create a new build named `universe-domain`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14866)
> ci: add new build universe-domain

- google/cloud/spanner/samples/samples.cc
We got error `Unable to create a backup of ... with version_time earlier than the creation time of the database`, it is introduced by tests in #14674.
In this test, we are trying to use a `version_time` that is initialized before the current database is created, it was used for a database backup creation which was already dropped.
My changes might impact the original intent of this test case. If so, we could have suggestions from the author @aman-19 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14883)
> ci: fix spanner samples integration tests

- google/cloud/spanner/samples/samples.cc
After the fix #14883 is merged, there is new error in `integration-daily`
```
Running spanner_copy_backup_with_MR_CMEK sample
status=INVALID_ARGUMENT: Invalid CopyBackup request. + google.rpc.BadRequest {
Step #2:   field_violations {
Step #2:     field: "encryption_config.encryption_type"
Step #2:     description: "No value provided for required field."
Step #2:   }
Step #2: } (google/cloud/internal/log_wrapper.cc:29)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14885)
> ci: fix spanner samples

- external/googleapis/renovate.sh
revert accidental changes from #14905
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14911)
> ci: fix renovate script

- MODULE.bazel
`bazel/deps-cache.py` is broken. It calls `bazelisk mod deps --output json google_cloud_cpp`. This fails because of issues in `protoc-gen-validate` v1.0.4. We do not use this mod directly, but one of our dependents does.
We can avoid problems by explicitly pinning to a newer version of this module.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14912)
> ci: fix `bazel/deps-cache.py`

- google/cloud/bigquery/v2/minimal/internal/json_utils.h
- google/cloud/bigquery/v2/minimal/internal/json_utils_test.cc
This PR modifies the `SafeGetToNullable` method based on the calling use case. The Json value field can hold any values and it is best parsed on the calling layer based on column schema and the row data that is provided to the caller.
The function is being modified to consistently return a string value. What that string value means is decided and parsed by by the calling layer as it has the most information to parse the value. It is not feasible to do this parsing at the Client LIbrary layer for our usecase.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14918)
> impl(bigquery): Json parsing changes for custom BigQuery library

- google/cloud/opentelemetry/internal/time_series.cc
- google/cloud/opentelemetry/internal/time_series.h
- google/cloud/opentelemetry/internal/time_series_test.cc
Fixes #14823 
Credit to @icysteam for raising the issue, and offering a fix for it in #14825. I also stole their tests. :smile: 
---
Copy several well-known service labels from the resource into the metric, if they exist.
This avoids duplicate timeseries when multiple instances of a service are running on a single monitored resource, for example running multiple service processes on a single GCE VM.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14930)
> feat(otel): copy service labels into GCM Metric

- google/cloud/bigquery/v2/minimal/internal/job_response.cc
- google/cloud/bigquery/v2/minimal/internal/job_response_test.cc
- google/cloud/bigquery/v2/minimal/internal/table_response.cc
- google/cloud/bigquery/v2/minimal/internal/table_response_test.cc
This PR fixes the jobs and tables response for the usecase when no jobs or tables returned from the server for the calling account.
Before the fix, the API response for `jobs.list` and `tables.list`assumed that the "jobs" and "tables" json keys will always be provided by the server. From our testing this was not the case.
This PR fixes the above and adds unit test cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14938)
> impl(bigquery): Fixed jobs and tables response for empty use case

- google/cloud/opentelemetry/internal/monitored_resource.cc
- google/cloud/opentelemetry/internal/monitored_resource_test.cc
Fixes #14925
When inside a Cloud Run environment, the [`MonitoredResource`](https://cloud.google.com/monitoring/api/ref_v3/rpc/google.monitoring.v3#google.monitoring.v3.TimeSeries) in a [`CreateTimeSeriesRequest`](https://cloud.google.com/monitoring/api/ref_v3/rpc/google.monitoring.v3#google.monitoring.v3.CreateTimeSeriesRequest) to the Cloud Monitoring API does not include the necessary fields for the [`generic_task`](https://cloud.google.com/monitoring/api/resources#tag_generic_task) resource type, and is rejected.
Also updating the GenericNode mapping to match Golang.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14923)
> fix(otel): Exporter creating Monitored Resource with task_id for Cloud Run

- google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14949)
> ci(spanner): use enterprise edition in instance autoscaler sample

- README.md
- google/cloud/credentials.h
- google/cloud/doc/guac.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14942)
> doc: update documentation to point to security best practice

- google/cloud/optimization/CMakeLists.txt
The optimization service is currently returning `UNAVAILABLE`. Until the service comes back online, update the quickstart to pass. If/when the service is back online, we'll likely need to revert this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14955)
> ci(optimization): pass quickstart if service is unavailable

- google/cloud/pubsub/samples/topic_admin_samples.cc
Add samples and tests for Cloud Pub/Sub ingestion from Kafka.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14954)
> docs(pubsub): Add Pub/Sub ingestion from Kafka samples

- doc/packaging.md
I think `msbuild` is very similar to the `make` tool just mentioned a few words before. Thus, adding a similar style.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14962)
> docs: add code formatting to `msbuild`

- google/cloud/resourcesettings/CMakeLists.txt
The service has been turned down, so attempting to run the quickstart always fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14966)
> ci: disable execution of resourcesettings quickstart

- .clang-tidy
Created #14972 to re-enable it with C++17.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14973)
> cleanup: disable modernize-type-traits in .clang-tidy

- .clang-tidy
- generator/internal/mixin_utils.cc
- google/cloud/bigtable/row_reader.h
- google/cloud/storage/async/reader.cc
- google/cloud/storage/async/reader.h
For merging #14957, fix the following:
[modernize-unary-static-assert](modernize-unary-static-assert): Disabled, it is only for c++17, and added it to #14972 
[modernize-use-auto]: changes `std::string` to `auto`
[performance-noexcept-move-constructor]: Disabled because adding `nonexcept` to move constructor will cause error.
[bugprone-exception-escape]: Disabled, because adding `noexcept(false)` to destructor will cause error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14976)
> cleanup: changes following clang-tidy suggestions

- .github/workflows/macos-bazel.yml
- .github/workflows/macos-cmake.yml
- .github/workflows/test-runner.yml
- .github/workflows/windows-bazel.yml
- .github/workflows/windows-cmake.yml
Due to recent security changes, we need to disable the external account integration test until we figure out a way to get it working again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15004)
> ci: disable external account integration test

- google/cloud/storage/internal/patch_builder_details.cc
workaround for https://github.com/nlohmann/json/issues/2046
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15006)
> refactor(storage): avoid initializing json object with empty initializer list

- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/internal/session_pool_test.cc
When attempting to refresh sessions, we would `Erase` a session if it was "Not Found". `Erase` would remove the session from the pool, but did not update the session counts which could prevent creation of new sessions to replace those that were erased.
part of the work for #14958
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15009)
> fix(spanner): update session bookkeeping for session NotFound

- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15017)
> impl(spanner): lock mutex in total_sessions accessor

- ci/cloudbuild/builds/universe-domain.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15022)
> cleanup: disable universe-domain kms tests

- release/README.md
Part of creating a patch release requires creating CI builds on the branch to be released. While a bug in `ci/cloudbuild/convert-to-branch-triggers.sh` has been fixed, that fix is not present in branches that predate the fix (#14627). It's necessary to backport that fix in order to avoid overwriting the existing cloudbuild triggers and pointing them from main to the patch release branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15033)
> doc(release): update instructions for creating patch release to preserve existing cloudbuild triggers

- google/cloud/internal/curl_impl.cc
- google/cloud/internal/curl_impl.h
- google/cloud/internal/curl_impl_test.cc
- google/cloud/internal/curl_options.h
- google/cloud/rest_options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15044)
> feat: add option to allow setting CURLOPT_INTERFACE

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/google_cloud_cpp_spanner.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
- google/cloud/spanner/uuid.cc
- google/cloud/spanner/uuid.h
- google/cloud/spanner/uuid_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15023)
> impl(spanner): add uuid type

- .github/workflows/windows-cmake.yml
github rolled out a VM update that included cmake 4.0 by default, which caused build failures.
Also the storage, storage_grpc Debug build was running out of space. We'll see if splitting them into two builds helps any.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15061)
> ci(gha): pin windows cmake to 3.31.6

- google/cloud/spanner/uuid.cc
- google/cloud/spanner/uuid.h
- google/cloud/spanner/uuid_test.cc
Instead of processing the high and low 64 bits of the Uuid separately, just use the 128-bit value directly.
Also simplify the Uuid tests.
Fixes #15043.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15057)
> impl(spanner): do Uuid to/from string conversions using absl::uint128

- .github/workflows/windows-cmake.yml
We are having constant disk space error when building core4 in debug mode, so I disable it before we can reduce the PDB size.
We are having intermittent disk space error when building core1 in debug mode, so I split the features into new shard core5.
#15070
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15071)
> ci(gha): split shard and disable debug build for storage_grpc

- ci/cloudbuild/builds/lib/integration.sh
- google/cloud/credentials.h
- google/cloud/google_cloud_cpp_common.bzl
- google/cloud/google_cloud_cpp_common.cmake
- google/cloud/internal/curl_impl.cc
- google/cloud/internal/curl_impl.h
- google/cloud/ssl_certificate.h
- google/cloud/storage/tests/CMakeLists.txt
- google/cloud/storage/tests/mtls_object_basic_crud_integration_test.cc
- google/cloud/storage/tests/storage_client_integration_tests.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15062)
> impl: add experimental client SSL certificate support

- google/cloud/internal/curl_handle_factory.cc
Currently we have some experimental OpenSSL features that do not yet work with Windows. We need to ensure that we don't attempt to include those OpenSSL headers, as they may not be available, nor use any types defined in those headers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15087)
> impl: do not attempt to include openSSL headers in windows

- google/cloud/spanner/interval.cc
- google/cloud/spanner/interval.h
- google/cloud/spanner/interval_test.cc
In the pre-release specification for `TypeCode::INTERVAL`, the wire encoding was given as a string in "intervalstyle == postgres" format, and `spanner::Interval` was implemented accordingly.
By the time the feature was released in the backend, this encoding changed to be a string in ISO8601 duration format.
So:
- Change `Interval::operator std::string()` to return a ISO8601 duration string.
- Extend `MakeInterval(absl::string_view)` to recognize ISO8601 duration format.
- Update and extend the test cases accordingly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15077)
> feat(spanner): add ISO8601 duration support to spanner::Interval

- cmake/GoogleCloudCppCommonOptions.cmake
- generator/internal/pagination_test.cc
- google/cloud/internal/log_wrapper_test.cc
- google/cloud/internal/pagination_range_test.cc
- google/cloud/storage/internal/grpc/make_cord_test.cc
Because macros are bad, in order to turn on `-pedantic` we had to apply https://github.com/google/googletest/issues/2271 to all usages of `TYPED_TEST_SUITE`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15107)
> ci: enable pedantic in clang-tidy builds

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15094)
> feat(spanner): add spanner::Value support for TypeCode::INTERVAL

- generator/internal/auth_decorator_generator.cc
- generator/internal/client_generator.cc
- generator/internal/connection_generator.cc
- generator/internal/connection_impl_generator.cc
- generator/internal/connection_impl_rest_generator.cc
- generator/internal/idempotency_policy_generator.cc
- generator/internal/logging_decorator_generator.cc
- generator/internal/logging_decorator_rest_generator.cc
- generator/internal/metadata_decorator_generator.cc
- generator/internal/metadata_decorator_rest_generator.cc
- generator/internal/service_code_generator.cc
- generator/internal/service_code_generator.h
- generator/internal/stub_factory_generator.cc
- generator/internal/stub_generator.cc
- generator/internal/stub_rest_generator.cc
Adds a third category of includes that the generator emits for protobuf generated headers, i.e. "pb.h" files. This PR preserves the current behavior of treating them as system includes (using <>), but prepares us for eventually switching to local includes (using "").
This PR should not result any any changes to generated code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15116)
> impl(generator): add toggle for how proto includes are generated

- google/cloud/spanner/integration_tests/data_types_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15118)
> impl(spanner): add interval integration tests

- google/cloud/storage/internal/async/object_descriptor_reader_tracing.cc
- google/cloud/storage/internal/async/object_descriptor_reader_tracing_test.cc
`std::size_t` on some platforms didn't always translate to a type contained in Otel's `AttributeValue` type:
```
using AttributeValue =
nostd::variant<bool,
int32_t,
int64_t,
uint32_t,
double,
const char *,
nostd::string_view,
nostd::span<const bool>,
nostd::span<const int32_t>,
nostd::span<const int64_t>,
nostd::span<const uint32_t>,
nostd::span<const double>,
nostd::span<const nostd::string_view>,
// Not currently supported by the specification, but reserved for future use.
// Added to provide support for all primitive C++ types.
uint64_t,
// Not currently supported by the specification, but reserved for future use.
// Added to provide support for all primitive C++ types.
nostd::span<const uint64_t>,
// Not currently supported by the specification, but reserved for future use.
// See …
```
> impl(storage): explicitly cast span data to supported common::AttributeValue type

- google/cloud/internal/curl_impl.cc
- google/cloud/internal/curl_impl_test.cc
This resolves an issue where requests to the GCE metadata server (metadata.google.internal) could fail on GCE VMs if an HTTP/HTTPS proxy was configured
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15145)
> fix: Bypass proxy for GCE metadata server requests

- google/cloud/internal/curl_impl.cc
Implemented conditional proxy bypass for `metadata.google.internal` using `libcurl` version check. Only version 7.19.4 or later support `CURLOPT_NOPROXY`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15155)
> Fix: Bypass proxy for metadata based on libcurl version

- cmake/GoogleCloudCppFeatures.cmake
With this change, a diagnostic indicating that GOOGLE_CLOUD_CPP_STORAGE_ENABLE_GRPC has been deprecated and that DGOOGLE_CLOUD_CPP_ENABLE=storage_grpc should be used instead, is being emitted when the option GOOGLE_CLOUD_CPP_STORAGE_ENABLE_GRPC is used.
fixes:  #15046
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15144)
> feat(storage): add diagnostic about deprecated storage gRPC option.

- CHANGELOG.md
- google/cloud/dataform/v1/.repo-metadata.json
- google/cloud/dataform/v1/dataform_client.h
1. reorder new library announcement
2. regenerate dataform client based on googleapis changes.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15157)
> cleanup: regenerate library for dataform

- google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
- google/cloud/storage/internal/async/connection_impl_appendable_upload_test.cc
- google/cloud/storage/storage_client_grpc_unit_tests.bzl
This change introduces a new test file, connection_impl_appendable_upload_test.cc, to thoroughly verify the asynchronous appendable upload functionality.  Following tests are included in this commit:
StartAppendableObjectUploadSuccess
ResumeAppendableObjectUploadSuccess
AppendableUploadTooManyTransients
AppendableUploadPermanentError
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15200)
> feat(storage): Add unit test for AppendableUploadConnectionImpl

- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/handle_redirect_error.cc
- google/cloud/storage/internal/async/handle_redirect_error.h
- google/cloud/storage/internal/async/handle_redirect_error_test.cc
- google/cloud/storage/internal/async/writer_connection_impl.cc
This change will only allow transformation from write_obejct_spec to append_object_spec when error has write handle, because the failure without write handle needs write_object_spec as input for retry.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15224)
> feat(storage): Add check for writeHandle before reansforming write_object_spec to append_object_spec

- release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15231)
> doc: add vcpkg REF replacement command in release doc

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/internal/transaction_impl.h
- google/cloud/spanner/internal/transaction_impl_test.cc
fixes #15220
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15261)
> impl(spanner): add transaction to channel affinity for multiplexed sesssions

- google/cloud/bigtable/BUILD.bazel
- google/cloud/bigtable/internal/async_bulk_apply.cc
- google/cloud/bigtable/internal/async_row_reader.cc
- google/cloud/bigtable/internal/async_row_sampler.cc
- google/cloud/bigtable/internal/bulk_mutator.cc
- google/cloud/bigtable/internal/data_connection_impl.cc
- google/cloud/bigtable/internal/default_row_reader.cc
- google/cloud/bigtable/internal/operation_context.cc
- google/cloud/bigtable/internal/operation_context.h
- google/cloud/bigtable/internal/operation_context_test.cc
As an additional `Status` parameter was added to `OperationContext::PostCall`, I added a default constructed `Status` at the call sites that were non-trivial. Later tasks will address populating the correct value in those calls and potentially relocating where `OperationContext::PostCall` is invoked in the execution flow.
Whatever value for status used currently is immaterial as the Metric vectors are empty.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15280)
> impl(bigtable): update OperationContext to support metrics

- google/cloud/bigtable/internal/async_row_sampler.cc
- google/cloud/bigtable/internal/async_row_sampler.h
- google/cloud/bigtable/internal/async_row_sampler_test.cc
- google/cloud/bigtable/internal/data_connection_impl.cc
This PR adjusts the location where PostCall is called and adds calls to OnDone. The OperationContext is default constructed for the time being.
Also renamed member var context_ to client_context_ as there's enough different contexts that it's helpful to be explicit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15304)
> impl(bigtable): update AsyncRowSampler to support new OperationContext

- google/cloud/storage/internal/async/connection_impl.cc
We are getting the bucket not found error on finalization of ResumeAppendableObject because we are using the variable after moving them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15274)
> feat(storage): Fix the bucket name not found error

- google/cloud/bigtable/internal/async_row_reader.cc
- google/cloud/bigtable/internal/async_row_reader.h
- google/cloud/bigtable/internal/async_row_reader_test.cc
- google/cloud/bigtable/internal/data_connection_impl.cc
This PR adjusts the location where PostCall is called and adds calls to OnDone, ElementDelivery, and ElementRequest. The OperationContext is default constructed for the time being.
Also renamed member var context_ to client_context_ as there's enough different contexts that it's helpful to be explicit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15302)
> impl(bigtable): update AsyncRowReader to support new OperationContext

- google/cloud/bigtable/internal/data_connection_impl.cc
- google/cloud/bigtable/internal/default_row_reader.cc
- google/cloud/bigtable/internal/default_row_reader.h
- google/cloud/bigtable/internal/default_row_reader_test.cc
This PR adds calls to the hook methods on OperationContext for DefaultRowReader. Given the synchronous interaction with the application, this type poses some different challenges in calling the various hooks. The ability to cancel the server streaming operation mid-stream is particularly problematic. A future PR will need to update some of the OperationContext hooks to account for this, for now there are TODOs in this PR.
A helper method for ReadRows was introduced as the eventual collection of Metrics in the OperationContext instances for ReadRow and ReadRows are different and need to be created individually. DataConnectionImpl::ReadRow may need some additional attention to ensure OnDone is called correctly as OnDone may have already been called from DefaultRowReader::~DefaultRowReader. …
> impl(bigtable): update DefaultRowReader to support new OperationContext

- google/cloud/bigtable/CMakeLists.txt
- google/cloud/bigtable/bigtable_client_unit_tests.bzl
- google/cloud/bigtable/internal/data_connection_impl.cc
- google/cloud/bigtable/internal/data_connection_impl.h
- google/cloud/bigtable/internal/data_connection_impl_test.cc
- google/cloud/bigtable/internal/operation_context_factory.cc
- google/cloud/bigtable/internal/operation_context_factory.h
- google/cloud/bigtable/internal/operation_context_factory_test.cc
This PR adds the remaining OperationContext hooks to DataConnectionImpl. 
Updates the OperationContext initialization in DataConnectionImpl to use the OperationContextFactory
Implements the OperationContextFactory methods with placeholder Metrics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15320)
> impl(bigtable): update DataConnectionImpl to create and call OperationContext hooks

- ci/gha/builds/lib/cmake.sh
- ci/gha/builds/vcpkg-overlays/opentelemetry-cpp/portfile.cmake
This instructs the GHA builds using vcpkg to build opentelemetry with support for the C++14 STL.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15335)
> ci: add otel overlay to use STL

- MODULE.bazel
google/cloud/storage:storage_client_testing, which is available publically, depends on googletest.
https://github.com/googleapis/google-cloud-cpp/blob/855ac8994aa69817fc0c5c376162df1858d5f932/google/cloud/storage/BUILD.bazel#L184-L200
When clients take dependency on google/cloud/storage:storage_client_testing, the build fails if dev_dependency is set to True for googletest.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15342)
> feat: remove dev_dependency for googletest module

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
This PR separates out some minor refactoring from the precommit token PR to improve its readability.
I renamed `s` to `selector` in places where the functions were either private and/or had long implementations. My eyes kept crossing trying to remember if `s` was for status, session, or selector.
`GetStubBasedOnSessionMode` was added to remove the copy/pasting from the previous PR. I also made sure we were consistent on the order of getting the stub and capturing the current options.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15359)
> refactor(spanner): add helper function and rename some vars

- google/cloud/storage/async/object_descriptor.cc
- google/cloud/storage/async/object_descriptor_connection.h
- google/cloud/storage/async/object_descriptor_test.cc
- google/cloud/storage/async/options.h
- google/cloud/storage/async/resume_policy.cc
- google/cloud/storage/async/resume_policy.h
- google/cloud/storage/internal/async/object_descriptor_connection_tracing.cc
- google/cloud/storage/internal/async/object_descriptor_impl.cc
- google/cloud/storage/internal/async/object_descriptor_impl.h
- google/cloud/storage/internal/async/object_descriptor_impl_test.cc
- google/cloud/storage/internal/async/object_descriptor_reader_tracing.cc
- google/cloud/storage/internal/async/object_descriptor_reader_tracing_test.cc
- google/cloud/storage/mocks/mock_async_object_descriptor_connection.h
- google/cloud/storage/testing/mock_resume_policy.h
- google/cloud/storage/tests/async_client_integration_test.cc
Part of #15340 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15152)
> feat(storage): Handle large read ranges in bidi read. 

- google/cloud/spanner/internal/transaction_impl.cc
- google/cloud/spanner/internal/transaction_impl.h
- google/cloud/spanner/transaction.cc
- google/cloud/spanner/transaction_test.cc
When retrying an aborted read-write transaction on multiplexed sessions, the aborted transaction id needs to be included when creating the new transaction.
fixes #15222
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15361)
> impl(spanner): support multiplexed session transaction priority

- google/cloud/spanner/integration_tests/BUILD.bazel
- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/spanner_client_session_mode_sensitive_integration_tests.bzl
- google/cloud/spanner/options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15364)
> ci(spanner): inject mux sessions into some integration tests

- google/cloud/spanner/connection.cc
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/partial_result_set_resume_test.cc
- google/cloud/spanner/internal/partial_result_set_source.cc
- google/cloud/spanner/internal/partial_result_set_source.h
- google/cloud/spanner/internal/partial_result_set_source_test.cc
- google/cloud/spanner/results.h
The PrecommitToken method is only needed internally, so let's not add it to the public API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15368)
> refactor(spanner): do not expose PrecommitToken in public interface

- google/cloud/bigtable/internal/metrics.cc
- google/cloud/bigtable/internal/metrics.h
- google/cloud/bigtable/internal/metrics_test.cc
- google/cloud/bigtable/internal/operation_context_factory.cc
Notable Changes:
- Using `application_blocking_latencies` as the metric type was resulting in the following error:
```
2025-08-12T03:28:05.329599122Z [WARNING] <139799742625472> Cloud Monitoring Export failed with status=INVALID_ARGUMENT: Error in non-idempotent operation: One or more TimeSeries could not be written: timeSeries[1] (metric.type="bigtable.googleapis.com/internal/client/application_blocking_latencies", metric.labels={"status": "OK", "app_profile": "default", "method": "ReadRow", "client_name": "cpp.Bigtable/v2.41.0-rc", "client_uid": "<uid>"}): unknown metric type;
``` 
Using `application_latencies` as per https://github.com/googleapis/java-bigtable/blob/d8055c1fb75a616cda1503b92d7cddb9da47d42b/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics …
> impl(bigtable): implement application blocking latencies metrics

- google/cloud/storage/examples/storage_async_samples.cc
Added samples for the following operations, also added screenshot for all the sample working:
Creating appendable object (It was already there)
Resume appendable object
Performing single ranged read
Reading multiple ranges (It was already there, just renamed it, this screenshot reads two ranges the first one is succeeded but the second one is expectedly giving OUT OF RANGE error)
Reading entire object
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15365)
> feat(storage): Add samples for AppendableObject and OpenObject

- .github/workflows/macos-cmake.yml
- Use a local tap to install a specific CMake version to work around Homebrew environment issues on runners.
[gha: macOS & Windows / macOS-CMake / cmake + macos-14 + Core2 (pull_request_target)](https://github.com/googleapis/google-cloud-cpp/actions/runs/17333450720/job/49214631350?pr=15439) passes with this PR.
Fixes https://github.com/googleapis/google-cloud-cpp/issues/15440.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15439)
> fix(gha): Update CMake installation for macOS

- google/cloud/storage/async/client.cc
- google/cloud/storage/async/client_test.cc
- google/cloud/storage/internal/async/connection_impl.cc
- google/cloud/storage/internal/async/connection_impl_appendable_upload_test.cc
- google/cloud/storage/internal/async/writer_connection_impl.cc
- google/cloud/storage/internal/async/writer_connection_impl.h
- google/cloud/storage/internal/async/writer_connection_resumed.cc
- google/cloud/storage/internal/async/writer_connection_resumed_test.cc
For the the first connection in appendable object upload, we are getting object metadata in response, but we were only storing persisted size out of it, so updating the code so that we will store the object metadata.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15422)
> feat(storage): Update the appendable object function to store the Object metadata

- google/cloud/storage/internal/async/writer_connection_resumed.cc
Setting writing_ = false in SetFlushed() is premature because the Flush-Query operation is not complete until OnQuery() finishes. This prematurely signals that no write is in progress, opening a window where StartWriting() can be called again before OnQuery() restarts or terminates the WriteLoop(), leading to concurrent write/flush operations.
To fix this, I am removing writing_ = false; from SetFlushed(). The writing_ flag will now only be updated by WriteLoop() based on whether there is more data to send, or when an error occurs. This ensures writing_ correctly reflects whether an operation is in flight.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15551 …
> feat(storage): Remove unnecessary code which was causing race condition

- google/cloud/bigtable/benchmarks/CMakeLists.txt
- google/cloud/bigtable/benchmarks/benchmark.cc
- google/cloud/bigtable/benchmarks/benchmark.h
- google/cloud/bigtable/benchmarks/benchmark_options.cc
- google/cloud/bigtable/benchmarks/benchmark_options.h
- google/cloud/bigtable/benchmarks/bigtable_benchmark_programs.bzl
- google/cloud/bigtable/benchmarks/scan_async_throughput_benchmark.cc
- google/cloud/bigtable/benchmarks/scan_throughput_benchmark.cc
Adds scan_async_throughput_benchmark as an async version of scan_throughput_benchmark. Both now support profiling around ReadRows sections which require gperftools to be installed and can be enabled via:
```
PROFILER_PATH="/tmp/<filename>" bazel run -c opt --copt=-DPROFILE --copt=-g --linkopt='-lprofiler' //google/cloud/bigtable/benchmarks:scan_async_throughput_benchmark
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/15557)
> benchmark(bigtable): update sync and async scan benchmarks

- google/cloud/spanner/internal/partial_result_set_source.cc
- google/cloud/spanner/internal/partial_result_set_source.h
This constructor has been marked deprecated, and will eventually be removed to unblock a change to the internal implementation of `RepeatedPtrField` that will reduce its size by 8 bytes.
> refactor(spanner): Replace callers of RepeatedPtrField(Arena*) with Arena::Create

- google/cloud/bigtable/query_row.cc
- google/cloud/bigtable/query_row.h
- google/cloud/bigtable/query_row_test.cc
- google/cloud/bigtable/results.h
Porting RowStream from `google/cloud/spanner` to `google/cloud/bigtable`.
> feat(bigtable): add support for RowStream
