googleapis/google-cloud-cpp

google/cloud/storage/lifecycle_rule.cc
google/cloud/storage/lifecycle_rule.h
google/cloud/storage/lifecycle_rule_test.cc
google/cloud/storage/storage_class.h
google/cloud/storage/storage_class_test.cc

This fixes #3075
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3197)

feat:new helper function for 'archive' storage class

---

ci/kokoro/readme/common.cfg

The builds were actually duplicating the work in the install builds and
not checking the README instructions. Unfortunately the builds
"worked", but failed to detect the openSUSE:Tumbleweed problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3205)

ci: fix kokoro/readme builds configuration

---

super/external/googletest.cmake

I got lucky because the differences between the version in the super
build and 1.10.0 were not important enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3206)

bug: fix superbuild to use googletest-1.10.0

---

google/cloud/bigtable/table.cc

We just need to keep the error message from the status.
Addresses bug #3191
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3208)

bug: Pass along error message in Table::Apply retry loop 

---

google/cloud/storage/internal/retry_resumable_upload_session.cc
google/cloud/storage/internal/retry_resumable_upload_session.h
google/cloud/storage/internal/retry_resumable_upload_session_test.cc
google/cloud/storage/testing/storage_integration_test.cc
google/cloud/storage/testing/storage_integration_test.h
google/cloud/storage/tests/object_resumable_write_integration_test.cc

Sharing the retry policy through the lifetime of an upload is a bad idea.
Long lived uploads just fail because they started a long time ago, even
if there have been no errors. We need to use a new instance of the
retry policy for each `UploadChunk()` call, but share them with the
`ResetSession()` calls because these are part of the same logical
operation.
Fixes #3212.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3213)

bug: use separate policy instances for each UploadChunk request

---

bazel/google_cloud_cpp_deps.bzl
ci/kokoro/docker/Dockerfile.ubuntu-install
google/cloud/bigtable/instance_admin.cc
super/external/grpc.cmake

Upgrade the Bazel and CMake super builds to gRPC-1.24.3. Did not update
all the builds because that requires more changes (upgrading Protobuf
for example). This fixes the build problems on openSUSE/Tumbleweed.
I had to make a code change because, depending on the Protobuf version,
the `GetReflection()` function generated in a proto may be static or
not. clang-tidy generates a warning when the function is static and we
use it as a non-static member function. The code does not compile when
used as a static member function.
Note that the openSUSE/Tumbleweed PR builds are disabled, but I ran
it manually and it worked.
Fixes #3214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/goog …

chore: upgrade most builds to gRPC-1.24.3

---

ci/benchmarks/Dockerfile
google/cloud/bigtable/CMakeLists.txt
google/cloud/firestore/CMakeLists.txt
google/cloud/storage/CMakeLists.txt

The builds always required google test and the testing library
from `google-cloud-cpp-common`, even when the tests were
disabled. I noticed this while fixing the benchmarks Dockerfile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3220)

chore: speed up packaging builds

---

INSTALL.md
ci/kokoro/install/Dockerfile.centos
ci/kokoro/install/Dockerfile.opensuse-leap
ci/test-readme/dockerfile2markdown.sh

The CentOS instructions did not quite work out of the box. The main
problem was using `LD_LIBRARY_PATH` and `sudo`, the latter unsets the
environment variables. The gRPC and googleapis build need tools
installed in `/usr/local/` with shared libraries in that directory. One
fix for that is to make ld.so search `/usr/local/lib{,64}/` by default.
These directories will be needed anyway, our libraries (and our
dependencies), install .so's there.
There were other minor problems, like missing `sudo` in some of the
commands that need root privileges.
Finally, I changed the Dockerfile to create fewer layers (see #3224),
otherwise I could not iterate quickly on my workstation. I just worked
around the issue by issuing multiple commands in each `RUN` line.
--- …

doc: fix CentOS 7 build instructions

---

ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.opensuse-tumbleweed
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/readme/Dockerfile.centos-7
ci/kokoro/readme/Dockerfile.debian-stretch
ci/kokoro/readme/Dockerfile.opensuse-tumbleweed
ci/kokoro/readme/Dockerfile.ubuntu-bionic

As the first step to automatically generate ci/kokoro/{install,readme}
we need to change the names of several builds. This is done in several
steps: (1) add the builds with the new names to GitHub, (2) enable the
builds inside the Google systems, (3) disable the old builds inside the
Google systems (maybe atomically with 2), and (4) remove the old builds.
Because the changes happen in two separate SCMs they cannot be done
atomically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3227)

ci: normalize build names

---

google/cloud/storage/CMakeLists.txt
google/cloud/storage/internal/tuple_filter.h
google/cloud/storage/internal/tuple_filter_test.cc
google/cloud/storage/storage_client.bzl
google/cloud/storage/storage_client_unit_tests.bzl

This is a part of #3016.
Composing GCS objects consists of multiple operations under the hood.
Different subsets of the options passed to the recursive compose
operation have to be passed on to the underlying operations.
By GCS C++ client convention, options are passed as parameter packs,
hence in the general case the filtering has to be done in compile time.
An easy way to filter these parameters is to pack them in a
std::tuple, filter it and apply it via std::apply.
The intended use is available at https://github.com/dopiera/google-cloud-cpp/commit/60fa4402bb317c56a6c8cea6e558119c7024bcb7 and https://github.com/dopiera/google-cloud-cpp/commit/bd75ad53f05cdbfd3f32557357b4e9bb3cc08b38
--- …

feat: implement tuple filtering

---

ci/etc/install-config.sh
ci/etc/kokoro/install/project-config.sh
ci/etc/kokoro/install/run-installed-programs.sh
ci/etc/kokoro/readme/project-config.sh
ci/etc/publish-refdocs.sh
ci/etc/repo-config.sh

These files configure the generators for `ci/kokoro/readme` and
`ci/kokoro/install`. The files on those directories are not automatically
generated just yet, but this is (I hope) the last PR before we can do
so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3236)

ci: configuration files for CI generators

---

google/cloud/storage/client.h
google/cloud/storage/object_test.cc
google/cloud/storage/tests/object_integration_test.cc

This is a part of #3016.
It basically lists the objects and deletes them one-by-one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3235)

feat: implement deleting objects by prefix

---

ci/kokoro/define-docker-variables.sh
ci/kokoro/install/build.sh
ci/kokoro/readme/build.sh

Use a fuller version that (like we do in other repositories) defines the
Docker image for the ci/kokoro/{readme,install,docker} builds. Use the
new variables in the CI scripts.
Part of the work for #3228
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3240)

ci: improve define-docker-variables.sh

---

ci/test-readme/generate-install.sh

It was referring to the old build names for centos-7, ubuntu-bionic,
opensuse-tumbleweed, and debian-stretch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3243)

doc: fix generator for INSTALL.md

---

ci/etc/kokoro/install/run-installed-programs.sh
ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.debian-buster
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.fedora
ci/kokoro/install/Dockerfile.opensuse-leap
ci/kokoro/install/Dockerfile.opensuse-tumbleweed
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-trusty
ci/kokoro/install/Dockerfile.ubuntu-xenial
ci/kokoro/install/build.sh
ci/kokoro/install/common.cfg
ci/test-install/storage/storage_install_test.cc

The CI builds to verify our install instructions work compile a couple
of test programs against the installed code. The programs were not
executed though. This PR proposes to run the tests as part of these CI
builds, note that these run against the production environment.
Fixes #3244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3245)

ci: run test install programs in CI builds

---

.bazelignore
WORKSPACE
bazel/google_cloud_cpp_deps.bzl
ci/install-bazel.sh
ci/test-install/WORKSPACE

Also upgrade Bazel for this repository. Mostly this entails upgrading
several dependencies (notably gRPC). There are a couple of new
warnings in the Bazel build, I think those should be fixed in a
separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3248)

ci: upgrade builds to use Bazel 1.0

---

google/cloud/bigtable/client_options.cc
google/cloud/bigtable/client_options_test.cc

Addresses #3260.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3261)

bug: use CalculateDefaultConnectionPoolSize in set_connection_pool_size

---

google/cloud/bigtable/instance_config.h

BREAKING CHANGE: replacing the constructor to stop allowing duplicate cluster
Fixes #2589 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3262)

fix!: avoid duplicate cluster ids in bigtable::InstanceConfig

---

ci/kokoro/docker/build.sh
super/CMakeLists.txt
super/ExternalProjectHelper.cmake
super/external/c-ares.cmake
super/external/crc32c.cmake
super/external/curl.cmake
super/external/google-cloud-cpp-common.cmake
super/external/googleapis.cmake
super/external/googletest.cmake
super/external/grpc.cmake
super/external/protobuf.cmake
super/external/ssl.cmake
super/external/zlib.cmake

Some CMake configuration options were not consistently used in the super
build, including `CMAKE_BUILD_TYPE`, `BUILD_SHARED_LIBS`,
`CMAKE_CXX_COMPILER`, and `CMAKE_C_COMPILER`.
This is basically a copy of the `super/*` files from `google-cloud-cpp-common`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3265)

ci: make super build configuration more consistent

---

ci/kokoro/install/build.sh
ci/kokoro/readme/build.sh

Regenerate ci/kokoro/{install,readme} from the latest version in
g-c-cpp-common.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3264)

ci: fix Docker image caching

---

super/external/curl.cmake

Fixes #3269
curl now uses `BUILD_SHARED_LIBS` to set `CURL_STATICLIB`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3270)

cleanup: don't set CURL_STATICLIB in libcurl super build file

---

google/cloud/bigtable/benchmarks/CMakeLists.txt
google/cloud/bigtable/benchmarks/benchmark.cc
google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc
google/cloud/bigtable/benchmarks/setup.cc
google/cloud/bigtable/benchmarks/setup.h
google/cloud/bigtable/benchmarks/setup_test.cc

This benchmark compares the throughput of AsynReadRow vs. ReadRow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3276)

feat: implement Bigtable sync vs. async benchmark

---

doc/cutting-a-release.md

* Use the `git log` commands from `google-cloud-cpp-common` to show
only changes since the last release, and format them as they appear in
the release notes.
* Remove the part about updating `google/cloud/README.md` which is no
longer necessary since we have `google-cloud-cpp-common`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3282)

chore: update release process

---

google/cloud/storage/README.md

Includes the fix for corrupted resumable uploads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3284)

chore: update release notes for v0.16

---

google/cloud/storage/CMakeLists.txt
google/cloud/storage/internal/generic_request.h
google/cloud/storage/internal/generic_request_test.cc
google/cloud/storage/storage_client_unit_tests.bzl

This fixes #3285.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3287)

fix: GenericRequest::set_option() accepts crefs

---

google/cloud/storage/client.cc
google/cloud/storage/client.h
google/cloud/storage/examples/storage_object_samples.cc
google/cloud/storage/object_test.cc
google/cloud/storage/tests/object_insert_integration_test.cc
google/cloud/storage/tests/object_integration_test.cc

**BREAKING CHANGE:** Before this PR, the user had to create a prefix
(which could fail), pass it to `ComposeMany` and remove it afterwards. It
was a lot of boilerplate.
With this PR, the prefix name is picked at random and `ComposeMany`
handles creating and deleting the marker file.
This is needed for #3279.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3296)

feat!: move creating prefix marker to ComposeMany

---

google/cloud/bigtable/filters.h
google/cloud/bigtable/filters_test.cc
google/cloud/bigtable/tests/filters_integration_test.cc

Allow application developers to build chain filters dynamically, from a
collection (or range) of filters.
Fixes #3291
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3303)

feat: build Chain filter from a range

---

doc/cutting-a-release.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3314)

chore: releases should use release.sh now

---

google/cloud/storage/internal/curl_handle.cc
google/cloud/storage/internal/curl_handle_test.cc

Getting nothing is approximately the same as getting a timeout, so we
should treat that as a kUnavailable (one of the retryable errors). The
application can use the strict idempotency policy and some preconditions
if they worry about the operation being too destructive when sent twice
to the server.
Changed the code to make it easier to review what error codes are handled
already. Fixes #3315.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3316)

fix: handle CURLE_GOT_NOTHING as retryable

---

google/cloud/storage/internal/object_requests.h
google/cloud/storage/tests/object_integration_test.cc
google/cloud/storage/well_known_parameters.h

Somehow we completely missed this option in the initial implementation.
Fixes #3319
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3320)

feat: implement Delimiter option for ListObjects

---

google/cloud/storage/benchmarks/CMakeLists.txt

Benchmarks could benefit from using testing libraries, but they are not
available in build configurations which skip tests. Since benchmarks are
usually not needed they are now not built if tests aren't.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3322)

test: don't build benchmarks without tests

---

google/cloud/storage/client.h

Fixed a couple of typos, and documented an additional parameter for
`ListObjects()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3332)

doc: some fixes for storage client docs

---

doc/cutting-a-release.md

Related to googleapis/google-cloud-cpp-spanner#1187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3333)

chore: remove instructions for file checksums

---

google/cloud/bigtable/client_options.cc
google/cloud/bigtable/client_options.h
google/cloud/bigtable/client_options_test.cc

Use the GOOGLE_CLOUD_ENABLE_DIRECT_PATH environment variable to
automatically switch to the Bigtable direct path endpoint.
Fixes #3331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3338)

feat: use Bigtable direct path if configured

---

google/cloud/storage/testing/temp_file.cc

In some build / testing environments the unit tests cannot create files
in the current directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3345)

fix: use ::testing::TempDir for test files

---

google/cloud/storage/client.h
google/cloud/storage/client_test.cc
google/cloud/storage/client_write_object_test.cc
google/cloud/storage/examples/storage_client_mock_samples.cc
google/cloud/storage/object_test.cc

**BREAKING CHANGE**: the `google::cloud::storage::Client` constructor
now calls `RawClient::client_options()`, which may need changes in how
you initialize any Mocks for this class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3349)

fix!: insert logging layer only if requested

---

google/cloud/storage/internal/curl_resumable_upload_session.cc
google/cloud/storage/internal/curl_resumable_upload_session.h
google/cloud/storage/internal/http_response.cc
google/cloud/storage/internal/logging_client.cc
google/cloud/storage/internal/logging_resumable_upload_session.cc
google/cloud/storage/internal/retry_resumable_upload_session.cc
google/cloud/storage/tests/object_resumable_write_integration_test.cc

Applications can provide the `X-Upload-Content-Length` header in their
resumable uploads. This let's GCS know how many bytes to expect, and GCS
completes an upload as soon as that many bytes arrive. In this case the
response does not have a `Range:` header indicating the last committed
byte, and these responses must be handled differently.
Fixes #3342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3348)

fix: handle completed uploads in UploadChunk

---

google/cloud/bigtable/client_options_test.cc

Fix the name of an environment variable so `EnvironmentVariableRestore`
will re-establish its previous value at test end.  Without this, other
test cases will fail if the tests are executed in a particular order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3353)

fix: correct environment variable name

---

ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.centos-8
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.opensuse-leap
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-xenial
super/external/grpc.cmake

Workaround grpc/grpc#21280 by compiling against a specific commit
(without a tag) of the v1.26.x gRPC branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3363)

ci: use gRPC-1.26.x to workaround a known bug

---

ci/kokoro/docker/build.sh

We fall back on the previously cached docker image, but showing the log
would be useful in the rare cases when *not* having an up-to-date image
is a "Bad Thing":tm:.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3367)

ci: log when building the docker image fails

---

doc/cutting-a-release.md

Remove remnant text about removing a clone directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3369)

docs: update doc/cutting-a-release.md

---

ci/kokoro/docker/Dockerfile.fedora
ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/docker/Dockerfile.ubuntu
ci/kokoro/docker/Dockerfile.ubuntu-install
doc/setup-development-environment.md
google/cloud/storage/testbench/testbench.py

The builds broke when they picked up a new version of the Wekrzeug
module. In particular the changes around DispatcherMiddleware listed
here:
https://werkzeug.palletsprojects.com/en/master/changes/#version-0-15-0
I updated the testbench to use the new version, and then pinned the
builds to use that version, which should keep us from breaking in a
similar way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3377)

ci: pin python modules used in integration tests

---

google/cloud/bigtable/client_options_test.cc

Correct a typo in the environment-variable name from #3353.
Add a missing environment-variable `TearDown()` from #3338.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3374)

fix: correct environment handling in client_options_test

---

ci/kokoro/docker/Dockerfile.fedora
ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/docker/Dockerfile.ubuntu
ci/kokoro/docker/Dockerfile.ubuntu-install
doc/setup-development-environment.md
google/cloud/storage/testbench/gcs_bucket.py
google/cloud/storage/testbench/gcs_iam.py
google/cloud/storage/testbench/gcs_object.py
google/cloud/storage/testbench/gcs_project.py
google/cloud/storage/testbench/testbench.py
google/cloud/storage/testbench/testbench_utils.py

Python 2.7 went EOL on 2020-01-01. The builds are starting to fail
because some of our dependencies assume (with good reason I think)
they are working with Python 3.
Fixes #3056
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3402)

chore: upgrade to Python 3

---

google/cloud/storage/testbench/testbench_utils.py

I introduced a flake when making the changes for Python 3: strings,
even binary strings, are never equal to single characters.
Fixes #3403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3404)

fix: fix flake after python 3 changes

---

google/cloud/storage/benchmarks/benchmark_utils.cc
google/cloud/storage/benchmarks/benchmark_utils.h
google/cloud/storage/benchmarks/benchmark_utils_test.cc
google/cloud/storage/benchmarks/run_benchmarks_testbench.sh
google/cloud/storage/benchmarks/storage_throughput_benchmark.cc

Add configuration options to run the throughput benchmark with an
existing bucket and/or with existing objects. This can speed up the
benchmark and can help when using very large objects in the benchmark.
Add configuration options to read a randomly-sized range of the object,
this is helpful to show that the download time is largely linear with
the object size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3401)

feat: make throughput benchmark more flexible

---

ci/kokoro/ubuntu/build.sh

A few places used `${BAZEL_BIN}` while others used a naked `bazel`. When those two versions are incompatible the build can break. Also cleaned up some unused code and removed an IAM policy binding that was leaked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3412)

ci: use the same Bazel program for all invocations

---

google/cloud/storage/CHANGELOG.md

Only `google/cloud/storage` had changes in this release, so only that library will get updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3414)

chore: update release notes

---

ci/benchmarks/Dockerfile
ci/kokoro/docker/Dockerfile.ubuntu
ci/kokoro/docker/Dockerfile.ubuntu-install
ci/kokoro/install/Dockerfile.debian-buster
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-xenial
ci/kokoro/readme/Dockerfile.debian-buster
ci/kokoro/readme/Dockerfile.debian-stretch
ci/kokoro/readme/Dockerfile.ubuntu-bionic
ci/kokoro/readme/Dockerfile.ubuntu-xenial
google/cloud/storage/tests/parallel_upload_regression/Dockerfile
google/cloud/storage/tests/read_object_stall_regression/Dockerfile
google/cloud/storage/tests/write_deadlock_regression/Dockerfile

By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages . 
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
results in smaller image size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3417)

fix(Dockerfile): Some debian package manager tweaks

---

google/cloud/storage/client_service_account_test.cc
google/cloud/storage/download_options.h
google/cloud/storage/hashing_options.h
google/cloud/storage/internal/object_requests_test.cc
google/cloud/storage/internal/signed_url_requests_test.cc
google/cloud/storage/object_metadata.h
google/cloud/storage/override_default_project.h
google/cloud/storage/signed_url_options.h
google/cloud/storage/upload_options.h

g++ prior to version 7 hides inherited default constructors. They need
to be manually written. This is essential to dynamically generating
lists of options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3423)

fix: make options ctors work on all compilers

---

super/CMakeLists.txt

Sometimes we want to use a super build for development (or users might
use a super build for exploration), without BUILD_ALWAYS the code is not
compiled after a change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3428)

fix: use BUILD_ALWAYS in super build

---

google/cloud/storage/internal/signed_url_requests.cc
google/cloud/storage/internal/signed_url_requests.h
google/cloud/storage/internal/signed_url_requests_test.cc
google/cloud/storage/tests/signed_url_conformance_test.cc

This fixes #3344.
The test had to be reworked a bit because otherwise we'd have to put `if`s for every feasible combination of numbers of headers and parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3422)

feat: support query parameters in v4 signed URLs

---

ci/kokoro/ubuntu/build.sh

I accidentally removed this on #3416, and the variable is only used in
the nightly builds, so it passed all the tests until that night.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3436)

fix: restore CBT variable setting

---

google/cloud/storage/testbench/gcs_object.py
google/cloud/storage/testbench/testbench.py
google/cloud/storage/testbench/testbench_utils.py

Allow object name to be passed in resource metadata, and not requiring it to be populated as a query parameter.
Fixes #3442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3443)

feat(3442): support multi-part object name in resource metadata

---

google/cloud/storage/testbench/testbench.py

1. Adding Content-Length to response to give client expectations of payload length.
1. I didn't find ` / 2` necessary and removed it.
Fixes: #3444
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3445)

feat(3444): content-length to failure case `return-broken-stream`

---

google/cloud/storage/internal/signed_url_requests.cc
google/cloud/storage/internal/signed_url_requests.h
google/cloud/storage/tests/signed_url_conformance_test.cc

Adds support for x-goog-content-sha256 and x-amz-content-sha256 headers. Part of the work for #3329.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3435)

feat: support x-goog-content-sha256 for V4 signed URLs

---

google/cloud/storage/internal/signed_url_requests.cc

Small refactor to a single (local) function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3452)

fix: avoid repeating default V4 expiration definition

---

ci/kokoro/windows/common.cfg

I need to point the new Kokoro configs to the new scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3467)

ci: use new script with new configs

---

ci/kokoro/macos/build-bazel.sh
ci/kokoro/macos/build-cmake.sh
ci/kokoro/macos/build-new.sh
ci/kokoro/macos/common.cfg

This is the first step in a multi-step process to align the macOS
builds with the other repositories. Create new scripts to build with
Bazel and CMake, the top-level driver dispatches based on the name
of the Kokoro build or a command-line argument (for easier testing).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3468)

ci: add CMake build scripts for macOS

---

ci/kokoro/windows/build-new.bat

We installed Bazel 2.0, but the script was still picking up 0.24.1 from
somewhere. Changing the PATH should fix this.
Part of the work for googleapis/google-cloud-cpp-common#231 and googleapis/google-cloud-cpp-common#227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3469)

ci: actually use Bazel 2.0

---

ci/kokoro/docker/build-in-docker-bazel-dependency.sh
ci/kokoro/docker/build.sh

This is part of the work for #3472, it starts by creating a new build in
ci/kokoro/docker which will eventually replace
`kokoro/bazel-dependency`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3474)

refactor: create bazel-dependency in kokoro/docker

---

INSTALL.md
bazel/google_cloud_cpp_deps.bzl
ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/docker/Dockerfile.ubuntu-install
ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.centos-8
ci/kokoro/install/Dockerfile.debian-buster
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.fedora
ci/kokoro/install/Dockerfile.opensuse-leap
ci/kokoro/install/Dockerfile.opensuse-tumbleweed
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-xenial
ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/CONTROL
ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/portfile.cmake
super/external/google-cloud-cpp-common.cmake

Part of the work for googleapis/google-cloud-cpp-common#248
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3482)

ci: update builds to use g-c-cpp-common v0.23.0

---

INSTALL.md
bazel/google_cloud_cpp_deps.bzl
ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/docker/Dockerfile.ubuntu-install
ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.centos-8
ci/kokoro/install/Dockerfile.debian-buster
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.fedora
ci/kokoro/install/Dockerfile.opensuse-leap
ci/kokoro/install/Dockerfile.opensuse-tumbleweed
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-xenial
ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/CONTROL
ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/portfile.cmake
super/external/google-cloud-cpp-common.cmake

Part of the work for googleapis/google-cloud-cpp-common#248
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3483)

ci: update builds to use g-c-cpp-common v0.24.0

---

ci/kokoro/docker/build.sh

Part of the work for googleapis/google-cloud-cpp-common#256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3484)

ci: use the right distro version in builds

---

google/cloud/storage/internal/curl_download_request.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3487)

bug: express libcurl version in hex

---

google/cloud/bigtable/testing/table_integration_test.cc
google/cloud/bigtable/testing/table_integration_test.h
google/cloud/bigtable/tests/admin_async_future_integration_test.cc
google/cloud/bigtable/tests/admin_integration_test.cc
google/cloud/bigtable/tests/data_async_future_integration_test.cc
google/cloud/bigtable/tests/data_integration_test.cc
google/cloud/bigtable/tests/filters_integration_test.cc
google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
google/cloud/bigtable/tests/instance_admin_integration_test.cc
google/cloud/bigtable/tests/mutations_integration_test.cc
google/cloud/bigtable/tests/run_admin_integration_tests_production.sh
google/cloud/bigtable/tests/run_integration_tests_emulator.sh
google/cloud/bigtable/tests/run_integration_tests_production.sh

We want to use Bazel and CTest to run the integration tests, one of the
first steps is to have these tests receive any parameters through
environment variables. Neither Bazel nor CTest support passing
additional arguments to the tests through the command-line.
Part of the work for #3489
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3490)

cleanup: remove arguments in bigtable integration tests

---

.bazelrc

I am doing more builds on macOS and find myself forgetting to add
the magic flags needed by gRPC on that platform (and harmless in other
platforms).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3493)

fix: make it easier to manually build on macOS

---

ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build-in-docker-cmake.sh
google/cloud/bigtable/ci/run_integration_tests.sh
google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh
google/cloud/bigtable/tests/BUILD
google/cloud/bigtable/tests/CMakeLists.txt
super/CMakeLists.txt

For the CMake-based builds use CTest to run the Bigtable integration
tests. This allows us to parallelize the tests. This PR is a really
small improvement, we also need to parallelize the examples, and the
benchmark smoke test. But it serves as a good prototype.
I removed the workarounds for #441: I ran the test 100 times, with 4 cores
and the emulator no longer seems to crash. I will mark #441 as fixed separately.
Part of the work for #3489 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3502)

ci: use CTest to drive Bigtable integration tests

---

google/cloud/storage/tests/slow_reader_chunk_integration_test.cc
google/cloud/storage/tests/slow_reader_stream_integration_test.cc

Use a smaller increment between steps when testing against the
testbench, this is enough because the testbench fails within one
second, waiting a minute only makes sense when running against
production. With a shorter time we can run with a larger (4MiB)
object restoring the original number of iterations in the test.
Part of the work for #3489
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3508)

test(storage): improve running time slow reader test

---

ci/kokoro/windows/build-cmake.ps1
ci/kokoro/windows/build.ps1

Use a Debug build for faster PR builds, a future change will enable
a Release build for post-submit builds. Also parallelize the unit
tests it saves maybe 30 seconds, but I will take it. Prepare the
ground work for running the integration tests for this build too.
Part of the work for #3489
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3509)

ci: speed up the PR builds for Windows+CMake

---

ci/kokoro/windows/build-cmake-dependencies.ps1
ci/kokoro/windows/build.bat

We should not update the vcpkg cache in a PR as this may dirty the
cache for other PRs and it is a waste of time in most builds.
I also cleaned up the log to avoid progress meters.
Part of the work for #3489 and for googleapis/google-cloud-cpp-common#249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3513)

ci: PRs should not update the vcpkg cache

---

ci/kokoro/docker/build-in-docker-cmake.sh

Use the timeout feature in CTest, makes for more readable code.
I think this will minimize the problems documented in #3600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3606)

ci: simplify timeout for bigtable integration tests

---

bazel/crc32c.BUILD
bazel/googleapis.BUILD
ci/check-style.sh

We were missing WORKSPACE and *.BUILD files from the formatting step.
Fixes #3602
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3607)

cleanup: enforce formatting in more Bazel files

---

ci/kokoro/windows/build-cmake-dependencies.ps1

I disabled the vcpkg cache upload for continuous builds too, that
was a mistake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3619)

ci: actually update the vcpkg cache

---

ci/kokoro/docker/build.sh

This matches a build with the same name in `-spanner`, it compiles with
shared libraries using a super build.
Part of the work for #3581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3623)

ci: configure cmake-super build

---

ci/kokoro/docker/Dockerfile.ubuntu
ci/kokoro/docker/build-in-docker-cmake.sh
ci/kokoro/docker/build.sh
doc/setup-development-environment.md

- Deletes the `scan-build` stuff.
- Deletes the `CREATE_GRAPHVIZ` stuff, which I don't think was accessible/used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3628)

cleanup: removes dead code from build scripts

---

ci/kokoro/docker/dump-reports.sh

This cleanup was missed when I submitted #3628 yesterday.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3632)

cleanup: remove last reference to scan-build

---

google/cloud/storage/CMakeLists.txt
google/cloud/storage/internal/curl_client.cc
google/cloud/storage/storage_client.bzl
google/cloud/storage/storage_client_unit_tests.bzl
google/cloud/storage/well_known_parameters.cc
google/cloud/storage/well_known_parameters.h
google/cloud/storage/well_known_parameters_test.cc

This is needed for #3635.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3639)

refactor: PredefinedAcl knows proper header names

---

google/cloud/storage/client.cc
google/cloud/storage/client.h
google/cloud/storage/client_sign_policy_document_test.cc
google/cloud/storage/examples/run_examples_utils.sh
google/cloud/storage/examples/storage_bucket_samples.cc
google/cloud/storage/internal/policy_document_request.cc
google/cloud/storage/internal/policy_document_request.h
google/cloud/storage/internal/policy_document_request_test.cc
google/cloud/storage/policy_document.cc
google/cloud/storage/policy_document.h
google/cloud/storage/policy_document_test.cc
google/cloud/storage/signed_url_options.h
google/cloud/storage/tests/signed_url_conformance_test.cc

This is a part of #3326.
Proper policy character escaping is not yet implemented. It will be fixed in a future PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3611)

feat: implement POST policy signatures

---

ci/kokoro/macos/bazel.cfg
ci/kokoro/macos/build-cmake.sh
ci/kokoro/macos/cmake-super.cfg
ci/kokoro/macos/common.cfg

We use homebrew to install some of our dependencies (LibreSSL).
Homebrew automatically updates its list of packages when you install
something, which can be really slow. We disable this on pull requests
to keep those snappy. Also increase the timeout for continuous builds
because the continuous builds that are forced to do a homebrew
update can take more than two hours.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3644)

ci: avoid slow brew updates in PRs

---

ci/kokoro/macos/build-cmake.sh

Seems like the Kokoro machines have an older version of bash than my Laptop.
This should work with older versions too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3647)

ci: fix macos for older bash versions

---

ci/etc/integration-tests-config.sh
ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build-in-docker-cmake.sh
ci/kokoro/docker/build.sh
ci/kokoro/docker/coverage-presubmit.cfg
ci/kokoro/docker/coverage.cfg
google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/tests/CMakeLists.txt
google/cloud/storage/tests/object_checksum_integration_test.cc
google/cloud/storage/tests/object_file_integration_test.cc
google/cloud/storage/tests/object_hash_integration_test.cc
google/cloud/storage/tests/object_integration_test.cc
google/cloud/storage/tests/object_media_integration_test.cc
google/cloud/storage/tests/object_resumable_write_integration_test.cc
google/cloud/storage/tests/signed_url_integration_test.cc

The main goal in this change is to run some tests that can *only*
run in production during the code coverage builds. This is important
because we have no visibility into their coverage, and it will be
even more important when we import `-spanner` which only
runs integration tests against production.
Move the configuration parameters for integration tests to git.
Easier to track and change them if they are part of the code, and
there are no secrets in this configuration.
More importantly, soon we will want to run all kinds of tests against
production in this build, e.g., the Cloud Spanner and Cloud Pub/Sub
tests.
To make it easier to identify which tests are skipping production 
and/or the emulator I used the GTEST_SKIP() annotations more
consistently.
Fixes #3547 and fixes #3542.
---
This …

ci: coverage build runs some tests against production

---

cmake/FindProtobufWithTargets.cmake

Hi,
I have cmake 3.17.0 and protobuf manually installed from gRPC 1.27.3
protobuf-config.cmake is located here : /usr/local/lib/cmake/protobuf
But it can't be found by CMake without this fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3685)

fix(cmake): typo in find protobuf-config.cmake

---

google/cloud/storage/policy_document.h
google/cloud/storage/policy_document_test.cc

This is to allow users to create `PolicyDocumentV4` without specifying
an empty initializer list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3688)

feat: add explicit ctor to PolicyDocumentV4

---

ci/kokoro/docker/build.sh

When cleaning up the artifacts dir, we want to remove the top-level
`cmake-out` directory, but once we find it, we can stop descending into
it since we're going to delete the whole thing. This change is in
response to a comment that @devbww made to the original PR
https://github.com/googleapis/google-cloud-cpp/pull/3637
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3694)

feat: use -prune flag to find

---

google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh
google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh

Use the same configuration file for the integration tests against the
emulator vs. production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3697)

refactor: same config for emulator vs. production tests

---

google/cloud/bigtable/examples/bigtable_grpc_credentials.cc
google/cloud/bigtable/examples/data_snippets.cc
google/cloud/storage/examples/storage_bucket_acl_samples.cc
google/cloud/storage/examples/storage_website_samples.cc

The `RunAll()` function in the examples calls example functions directly,
bypassing the size validation for `argv`. When we are developing (or
changing) these functions the crashes from passing the wrong number of
arguments are fairly obscure. Using `std::vector::at` makes it easier to
debug the problems, and as this is not performance critical code, it
seems like a better tradeoff to use that accessor over `operator[]`.
Fixes #3696
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3700)

cleanup: use std::vector::at in examples

---

BUILD
google/cloud/bigtable/BUILD
google/cloud/storage/BUILD

Fixes: #3532
The goal is to get bazel users to *only* use these top-level BUILD
targets. This target is shorter and easier to type, and customers need
not rely on the directory structure that we choose to use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3702)

feat: add top-level BUILD file

---

ci/colors.sh
ci/kokoro/docker/build-in-docker-bazel-dependency.sh
ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build-in-docker-cmake.sh
ci/kokoro/docker/build.sh
ci/kokoro/docker/check-abi.sh
ci/kokoro/macos/build-bazel.sh
ci/kokoro/macos/build-cmake.sh
ci/kokoro/macos/build.sh

This shortens the log statements, gives them all the same timestamp
prefix, and removes the need to remember to reset the terminal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3704)

refactor: ci scripts now use log_<color> functions

---

google/cloud/bigtable/examples/bigtable_examples_common.h
google/cloud/storage/examples/storage_bucket_acl_samples.cc
google/cloud/storage/examples/storage_bucket_iam_samples.cc
google/cloud/storage/examples/storage_examples_common.cc
google/cloud/storage/examples/storage_examples_common.h
google/cloud/storage/examples/storage_examples_common_test.cc
google/cloud/storage/examples/storage_signed_url_v2_samples.cc
google/cloud/storage/examples/storage_signed_url_v4_samples.cc
google/cloud/storage/examples/storage_website_samples.cc

The examples get their configuration from environment variables and
need to validate that these are set and have some value. That code was
getting repetitive, so copied the code from the Bigtable examples.
Eventually this should all make it to the `-common` library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3707)

cleanup: remove repetitive code in storage examples

---

google/cloud/bigtable/examples/bigtable_grpc_credentials.cc
google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
google/cloud/bigtable/examples/bigtable_hello_table_admin.cc
google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
google/cloud/bigtable/examples/data_snippets.cc
google/cloud/bigtable/examples/table_admin_snippets.cc

As @devbww pointed out in #3707 , once we validate an
environment variable using `.value_or("")` is redundant. Use just
`.value()` it is cleaner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3708)

cleanup: use `.value()` to read validated env variables

---

google/cloud/storage/client.h
google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/examples/run_examples_utils.sh
google/cloud/storage/examples/storage_autorun_examples.bzl
google/cloud/storage/examples/storage_bucket_samples.cc
google/cloud/storage/examples/storage_policy_doc_samples.cc

This splits the storage policy doc samples to their own file, which is
automatically executed by CMake/Bazel.
Fixes #3667
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3709)

refactor: split storage policy doc samples

---

google/cloud/storage/examples/storage_policy_doc_samples.cc
google/cloud/storage/policy_document.cc
google/cloud/storage/policy_document.h

Implement an example that actually generates the text for a HTML form
associated with a signed policy document.
Fixes #3642
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3715)

feat(storage): policy doc example with form

---

google/cloud/firestore/BUILD
google/cloud/firestore/CMakeLists.txt
google/cloud/firestore/README.md

Cleans up the README.md to make it clearer that this library is not GA
and has no specific support guarantees. Also cleans up the build a bit
since it doesn't actually depend on -common.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3717)

cleanup: cleanup the firestore documentation and deps

---

google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/examples/run_examples_utils.sh
google/cloud/storage/examples/storage_autorun_examples.bzl
google/cloud/storage/examples/storage_bucket_cors_samples.cc
google/cloud/storage/examples/storage_bucket_samples.cc

This program is executed automatically by CMake/Bazel without any
additional scripts.
Fixes #3672
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3720)

refactor: split CORS examples to its own program

---

google/cloud/bigtable/examples/bigtable_examples_common.cc
google/cloud/bigtable/examples/bigtable_examples_common.h
google/cloud/bigtable/examples/bigtable_examples_common_test.cc

The Bigtable instance admin and table admin async examples will
benefit from a function to adapt an example of the form:
```C++
void F(
bigtable::TableAdmin, CompletionQueue cq,
std::vector<std::string> argv)
```
to something that just takes `std::vector<std::string>` as its only
argument. This PR creates two helper functions to create such adapters.
Part of the work for #3676
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3721)

feat: helper functions for bigtable async examples

---

ci/kokoro/windows/build-bazel.ps1
ci/kokoro/windows/build-quickstart-bazel.ps1

Remove any .tar files before trying to create them, because 7z fails
if they do exist.
Report more details about upload failures for better troubleshooting.
Shutdown each bazel invocation or we cannot tarball the Bazel cache.
Part of the work for #3534 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3727)

ci: improve error handling for Windows+Bazel caching

---

release/README.md
release/release.sh

This is part of: https://github.com/googleapis/google-cloud-cpp/issues/3539
This copies `releases/` from https://github.com/googleapis/google-cloud-cpp-common/tree/master/release into this directory, *preserving its git history*. I preserved the git history using `git filter-repo`, which is not part of the base git release, but it is *recommended* by the base git release (`git help filter-branch` recommends this). https://github.com/newren/git-filter-repo
I have not made any edits to this code, because I want this to be a clean copy from `-common`. I'll do a followup PR if there are edits that need to be made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/372 …

feat: moves release.sh (with history) to -cpp

---

ci/kokoro/windows/build-cmake-dependencies.ps1
ci/kokoro/windows/build-cmake.ps1
ci/kokoro/windows/build-quickstart-bazel.ps1
ci/kokoro/windows/build-quickstart-cmake.ps1
ci/kokoro/windows/build.ps1
ci/kokoro/windows/common.cfg
google/cloud/bigtable/quickstart/CMakeLists.txt
google/cloud/bigtable/quickstart/README.md
google/cloud/storage/quickstart/CMakeLists.txt
google/cloud/storage/quickstart/README.md

Changed the scripts to support multiple CMake-based builds on the same
workspace, this was useful to test locally on my VM.
Changed the vcpkg script to receive the directory and list of
dependencies from the command-line, this is needed to download and
compile google-cloud-cpp as a vcpkg package.
Configure different vcpkg caches for each build.
Change the quickstart CMake files to support static binaries.
Part of the work for #3732 and for #3733 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3736)

ci: quickstart build for Windows+CMake+vcpkg

---

google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/examples/run_examples_utils.sh
google/cloud/storage/examples/storage_autorun_examples.bzl
google/cloud/storage/examples/storage_object_samples.cc
google/cloud/storage/examples/storage_public_object_samples.cc

Use CMake/Bazel to drive the storage public object examples.
Fixes #3662
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3738)

refactor: run storage public object samples without scripts

---

ci/kokoro/windows/build-cmake-dependencies.ps1

I did not test the case where the build is running under the CI system
well enough. I think I got it right this time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3739)

ci: fix quickstart build for Windows+CMake

---

doc/cutting-a-release.md
release/release.sh

Fixes: #3539
Cleaned up the release.sh script to do the following:
1. Quote command-line args correctly when printing them in the `run`
function.
2. Automatically extract the release notes for the new version from
`CHANGELOG.md` and insert them into the new release that we create on
the GitHub UI (using the hub command).
3. Only clone the previous 90 days worth of commits, which should be
more than enough to get the recently released tags. This saves a lot of
time when cloning `-cpp`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3743)

feat: taught release.sh how to insert release notes

---

google/cloud/bigtable/examples/bigtable_grpc_credentials.cc
google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
google/cloud/bigtable/examples/bigtable_hello_table_admin.cc
google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
google/cloud/bigtable/examples/data_async_snippets.cc
google/cloud/bigtable/examples/data_snippets.cc
google/cloud/bigtable/examples/instance_admin_async_snippets.cc
google/cloud/bigtable/examples/opencensus/bigtable_opencensus.cc
google/cloud/bigtable/examples/table_admin_async_snippets.cc
google/cloud/bigtable/examples/table_admin_snippets.cc
google/cloud/storage/examples/storage_bucket_acl_samples.cc
google/cloud/storage/examples/storage_bucket_cors_samples.cc
google/cloud/storage/examples/storage_bucket_default_kms_key_samples.cc
google/cloud/storage/examples/storage_bucket_iam_samples.cc
google/cloud/storage/examples/storage_bucket_requester_pays_samples.cc
google/cloud/storage/examples/storage_notification_samples.cc
google/cloud/storage/examples/storage_object_cmek_samples.cc
google/cloud/storage/examples/storage_policy_doc_samples.cc
google/cloud/storage/examples/storage_public_object_samples.cc
google/cloud/storage/examples/storage_service_account_samples.cc
google/cloud/storage/examples/storage_signed_url_v2_samples.cc
google/cloud/storage/examples/storage_signed_url_v4_samples.cc
google/cloud/storage/examples/storage_website_samples.cc

Put any namespace aliases before the executable code. Removed unnecessary
using-declarations. Removed unused doxygen tags. Removed unnecessary
include directives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3750)

cleanup: fix inconsistencies in the examples

---

ci/etc/kokoro/install/run-installed-programs.sh
ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
ci/kokoro/docker/integration-nightly.cfg
ci/kokoro/docker/integration-presubmit.cfg
ci/kokoro/docker/integration.cfg
ci/kokoro/install/common.cfg
ci/kokoro/macos/common.cfg

Remove uses of the external configuration for integration tests, and
always use the configuration in `ci/etc/`. In some cases we were using
the presence of `${KOKORO_GFILE_DIR}/test-configuration.sh` as a marker
to indicate that the integration tests were configured. We now use the
service account credentials for that purpose, which are needed in any
case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3752)

cleanup(ci): simplify integration tests configuration

---

ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/coverage.cfg
ci/kokoro/docker/integration-nightly.cfg
ci/kokoro/docker/integration-presubmit.cfg
ci/kokoro/docker/integration.cfg
ci/kokoro/windows/common.cfg

I also cleaned up a shellcheck warning.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3754)

ci: use separate service account to setup test environment

---

google/cloud/storage/examples/storage_bucket_requester_pays_samples.cc

The storage_bucket_requester_pays example required too many privileges
from the caller. By explicitly providing a user project when acting on a
bucket that might have requesterPays billing the example works with much
reduced privileges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3768)

cleanup: reduce privileges required to run requester pays example

---

google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
google/cloud/bigtable/examples/instance_admin_async_snippets.cc
google/cloud/bigtable/examples/table_admin_async_snippets.cc
google/cloud/bigtable/examples/table_admin_snippets.cc

Somewhat ironic, I keep saying that the Cloud Bigtable quota does not
allow us to run the instance and table admin examples more than once a
day, production and then I forget to disable them for the `integration`
builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3769)

fix: disable Bigtable admin examples for most builds

---

bazel/googleapis.BUILD

This PR simplifies the `googleapis.BUILD` rules by using the canonical
rules that are defined in the googleapis repo if/when they exist,
and explicitly using a `# Do not sort` comment to make it clear that the
`grpc++` target must come last.
This also removes some bazel rule attributes that weren't needed, in an
effort to simplify a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3774)

refactor: simplify googleapis.BUILD rules

---

bazel/google_cloud_cpp_deps.bzl
bazel/googleapis.BUILD
google/cloud/bigtable/BUILD

With this version, we can now use the googleapis-provided BUILD files
for the Bigtable Admin V2 protos, so we don't need to define our own. I
also move the unnecessary proto deps out of the `googleapis.BUILD` file
to make the targets in there look more consistent -- they only exist so
that we can explicitly sort the `grpc++` target *after* the grpc proto
rules that depend on it (this is working around a grpc issue).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3779)

feat: update to new version of googleapis protos

---

google/cloud/storage/examples/BUILD
google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/examples/storage_client_mock_samples.cc
google/cloud/storage/examples/storage_examples_unit_tests.bzl

We do extract code from this to show users how to write their own mocks,
but the easiest way to run this program is to turn it into an actual
unit test.
In the process of getting this to run I discovered that some of the
examples were wrong, with the incorrect number of expectations and/or
incomplete implementation for the mocked functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3791)

fix: storage_client_mock_samples is a unit test

---

ci/colors.sh

When building in Kokoro it seems that TERM is not set and `tput` outputs
some warnings. This change avoids calling `tput` in that case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3801)

cleanup: avoid tput warnings in CI builds

---

ci/etc/quickstart-config.sh
ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
ci/kokoro/macos/build-quickstart-bazel.sh
ci/kokoro/macos/build-quickstart-cmake.sh
ci/kokoro/macos/build.sh
ci/kokoro/macos/upload-cache.sh

Kokoro+macOS runs bash==3.2.x, which does not support
associative arrays, so we need to use functions to get the
quickstart arguments and the list of libraries with a quickstart
program.
Part of the work for #3730 and #3731
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3800)

ci: use functions to get quickstart arguments

---

ci/check-style.sh
ci/kokoro/docker/Dockerfile.ubuntu
ci/kokoro/docker/Dockerfile.ubuntu-install

Changes this loop back to using `clang-format -i`. This used to cause a
problem when we were using clang-format-7, in that it would update every
file's timestamp even if no edits were made. However, since #3458
(2020-03-10), we're now using fedora with clang-format-9, and this
problem no longer exists. So we can go back to the faster `clang-format
-i`.
This PR reduces the "clang-format" step in the check-style.sh script
from about 30 seconds to about 4.
I also removed the clang-format-7 packages from the Dockerfiles that
don't use it, because it was just confusing to see a version being
installed that we don't use.
Part of https://github.com/googleapis/google-cloud-cpp/issues/3794
--- …

fix: speed up clang-format in check-style

---

google/cloud/storage/examples/storage_bucket_iam_samples.cc
google/cloud/storage/examples/storage_examples_common.cc
google/cloud/storage/examples/storage_examples_common.h
google/cloud/storage/examples/storage_examples_common_test.cc

It saves a little bit of boilerplate and avoids a special case where the
commands are defined.
I also made `storage_bucket_iam_samples` use it (more uses are in other
to-be-converted samples).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3795)

cleanup: add varargs support to `CreateCommandEntry`

---

ci/check-style.sh

In #3431 (March 4, 2020) we updated `cmake_format` from 0.6.0 to 0.6.8.
I _think_ that update "fixed" the problem w/ cmake_format that caused it
to change the timestamp on files even when it did not change them.
Therefore, I think we could change the `cmake_format` code in
`check-style.sh` to use something like `find ... | xargs -0 cmake_format
-i`, which would likely speed it up too.
Sadly, this change doesn't improve the speed very much. Maybe 11 sec ->
8 sec. It turns out that cmake-format itself is just really slow. But
this incantation is a bit simpler and matches how we do clang-format, so
it's probably worth the change anyway.
Fixes: #3794
--- …

fix: speed up cmake-format with in-place edit

---

ci/kokoro/docker/build.sh

This makes it so that files created by the container have the running
user's gid rather than 'root'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3807)

fix: set docker gid to runner user's gid

---

ci/etc/quickstart-config.sh
ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
ci/kokoro/macos/build-quickstart-bazel.sh
ci/kokoro/macos/build-quickstart-cmake.sh

Made the quickstart builds for Linux and macOS more similar, fixed a
number of shellcheck warnings, incidentally fixing #3798. Also made the
output more legible (I think). Also made sure all quickstarts are built,
even if some of them fail.
Fixes #3798 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3806)

ci: another iteration on quickstart builds for macOS

---

ci/check-style.sh

Change the `check-style.sh` script to record all the style failures and
report all of them at the end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3818)

ci: enforce shellcheck warnings

---

ci/check-style.sh
ci/kokoro/docker/Dockerfile.fedora-install

Runs as part of the `clang-tidy` build, like all the other formatting
checks.
Part of the work for googleapis/google-cloud-cpp-common#102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3831)

ci: enforce shell formatting with shfmt

---

google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/examples/run_examples_utils.sh
google/cloud/storage/examples/storage_bucket_samples.cc
google/cloud/storage/examples/storage_examples.bzl
google/cloud/storage/examples/storage_lifecycle_management_samples.cc

Fixes #3654
Note: after I merge the other outstanding PRs, `run_examples_utils.sh`
will be a no-op and can be removed - I'll do that separately for
clarity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3837)

refactor: run lifecycle management examples without scripts

---

bazel/curl.BUILD
ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
ci/kokoro/docker/build.sh

This PR enables the integration tests on the AddressSanitizer and
MemorySanitizer builds. The tsan and ubsan builds need more work before
we can enable them.
I had to change the `curl.BUILD` file: as it was the integration tests could
not run on Fedora, `libcurl` needs to know where the certificate authority
bundles are located. The CMake and Makefile builds for it figure this out
automatically, but we use Bazel for the sanitizer builds, and the file had a
location hard-coded for Ubuntu.
Part of the work for #3832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3839)

ci: enable integration tests for asan+msan builds

---

ci/etc/kokoro/install/project-config.sh
ci/etc/kokoro/install/run-installed-programs.sh
ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.centos-8
ci/kokoro/install/Dockerfile.debian-buster
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.fedora
ci/kokoro/install/Dockerfile.opensuse-leap
ci/kokoro/install/Dockerfile.opensuse-tumbleweed
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-xenial

With this change the ci/kokoro/install builds will automatically pickup
new `quickstart` libraries. Or at least, will automatically pick them up
when they are regenerated.
Fixes #3544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3843)

ci: run all quickstarts in install builds

---

bazel/curl.BUILD
bazel/google_cloud_cpp_deps.bzl
google/cloud/storage/tests/object_integration_test.cc
super/external/curl.cmake

We have not updated this in a while, and there are important bug fixes
in newer versions. I would prefer not to chase these bugs if they
manifest in our builds. Note that in some platforms we build against the
version installed on the platform, which can be much older.
One of the test had hard-coded assumptions about the number of file
descriptors created by a `storage::Client`. The number depends on the
version of libcurl used under the hood. Where possible I just changed
the test to make no such assumptions, we are looking for file descriptor
leaks in this test, we do not really care how many are created.
I think this will make some of the work in #3832 a little easier.
--- …

chore: upgrade libcurl to v7.69.1

---

google/cloud/storage/tests/object_insert_integration_test.cc

This test was supposed to print the most interesting log lines when it
did not find the expected output, but it actually printed nothing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3853)

fix: output on test failure was empty

---

ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/docker/Dockerfile.ubuntu-install

Reduces the duplication of version numbers in these files, which will
make it easier to update versions. The solution employed here is to
use `curl ... | tar -xzf - --strip-components=1` directly into the
`/var/tmp/build` directory. We'll do the build directly from there, then
remove `/var/tmp/build` after each build step. This makes it so the only
place each library's version is specified is in the curl URL.
Fixes https://github.com/googleapis/google-cloud-cpp/issues/3788
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3850)

refactor: simplify *-install Dockerfiles

---

.dockerignore

Turns out we do need the top-level .dockerignore file. The
`ci/kokoro/install` builds use it. It is not a big deal in the CI
builds, where the ignored directories are mostly empty, but it is a
problem when testing those builds in a development workspace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3857)

cleanup: restore dockerignore file

---

google/cloud/storage/internal/curl_client.cc
google/cloud/storage/internal/curl_download_request.cc
google/cloud/storage/internal/curl_wrappers.h
google/cloud/storage/internal/curl_wrappers_disable_sigpipe_handler_test.cc

This macro is (I think) more readable than using the hexadecimal
representation of version numbers, and it caught a couple of places
where I (at least I think it was me) used the wrong version number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3856)

cleanup: prefer CURL_AT_LEAST_VERSION()

---

.bazelrc
ci/kokoro/docker/Dockerfile.fedora
ci/kokoro/docker/build.sh

With this change all the sanitizer builds will compile using Clang 9.0,
we have other builds to test older versions of Clang and GCC, it seems
that we should use a recent compiler for builds that helps us in
development.
This makes the work in #3832 a little bit easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3855)

chore: update compiler for sanitizer builds

---

google/cloud/bigtable/examples/table_admin_async_snippets.cc

One of the examples was not consuming its arguments correctly. Because
this only runs in the nightly build we did not catch the problem during
the PR. And I missed it during the review, of course.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3859)

fix: argument handling in table admin async example

---

ci/kokoro/docker/build.sh

This enables the integration tests for the ThreadSanitizer and
UndefinedBehaviorSanitiser builds. To summarize the changes precending
this one:
- We removed the use of CURL_SHARE, a feature to share the connection
cache and other resources, because libcurl has outstanding issues with
this feature.
- We upgraded libcurl to 7.69.1 for the Bazel and CMake Super builds,
this was nice, but did not fix any problems.
- Two of the tests actually had errors detected by ThreadSanitizer, but
this was only in the test code.
- We upgrade the sanitizer builds to use clang-9.0, which could be
useful in the future.
Fixes #3832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/38 …

feat: enable integration tests for tsan and ubsan builds

---

google/cloud/storage/object_metadata.h

**BREAKING CHANGE:** This changes the type of two fields from
`google::cloud::optional<long>` to
`google::cloud::optional<std::int64_t>`. With MSVC this is not a
backwards compatible change (storing the result of `.value()` into a
`long` now loses precision). However, on that platform the fields were
not usable, they could not store the values that are typically generated
by the production environment. We apologize to any customers affected by
this change, but we think it is unlikely that anybody used the field on
that platform or we would have heard of the bug earlier.
Part of the work for #3540
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3870)

fix!: use correct type for generation numbers

---

google/cloud/storage/tests/object_compose_many_integration_test.cc

See coryan's comment on #3873 recommending we reduce the number of
iterations from 100 to 33.
before:
```
//google/cloud/storage/tests:object_compose_many_integration_test        PASSED in 35.8s
```
after:
```
//google/cloud/storage/tests:object_compose_many_integration_test        PASSED in 14.4s
```
Part of #3854
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3875)

test: reduce runtime of the "compose many" test

---

google/cloud/storage/benchmarks/BUILD
google/cloud/storage/benchmarks/CMakeLists.txt
google/cloud/storage/benchmarks/run_benchmarks_testbench.sh
google/cloud/storage/benchmarks/storage_benchmark_programs_manual_run.bzl
google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc

Add a "self-test" to this benchmark that is automatically run as part of
the CI builds, without any need for supporting driver scripts.
Part of the work for #3525 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3877)

refactor: auto run storage_file_transfer_benchmark

---

google/cloud/bigtable/benchmarks/CMakeLists.txt
google/cloud/bigtable/benchmarks/setup.cc
google/cloud/bigtable/benchmarks/setup_test.cc
google/cloud/bigtable/ci/run_integration_tests.sh

With this change all the bigtable benchmarks automatically run, without
the need of additional support scripts. Note that these benchmarks (and
their unit tests) are not compiled with Bazel, so they will not be
present in many builds. That is a matter for a separate bug and PR.
The support scripts will be removed in a future PR once we merge the
analogous changes for google/cloud/storage
Fixes #3526
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3882)

refactor: auto run the bigtable benchmarks

---

ci/kokoro/windows/build-bazel.ps1

I used a shell-ism in PowerShell, i.e. ${FOO:-no}, which is not a thing
in PowerShell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3886)

fix: CI script for Windows+Bazel used of env vars

---

google/cloud/storage/testing/object_integration_test.cc
google/cloud/storage/tests/object_plenty_clients_serially_integration_test.cc
google/cloud/storage/tests/object_plenty_clients_simultaneously_integration_test.cc

addresses devbww's comments on #3873
* use `opendir()` instead of `scandir()` to read the directory
* I do think eliding 3 entries makes sense since opening `/proc/self/fd`
is a side effect of taking the measurement. I updated the comment.
* contained the #ifdef to one place, which I think makes it easier to
read. The test still fails if we can't get the count on linux, and it
will also fail as a reminder to update it if we find a way to get
the count on non-linux.
part of #3854
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3876)

test: rework some logic for counting open files

---

ci/check-style.sh

This simplifies the our check-style.sh script by not parsing the `.gitignore` file. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3880)

refactor: use git-ls-files rather than parse .gitignore

---

ci/kokoro/docker/download-cache.sh
ci/kokoro/docker/upload-cache.sh
ci/kokoro/macos/build.sh
ci/kokoro/macos/download-cache.sh
ci/kokoro/macos/upload-cache.sh
ci/kokoro/windows/build-bazel.ps1
ci/kokoro/windows/build-cmake-dependencies.ps1
ci/kokoro/windows/build-quickstart-bazel.ps1

These scripts are used to run the builds locally, on a developer
workstations. With these changes the cache is not downloaded or
downloaded unless KOKORO_JOB_TYPE is configured, which hopefully
developers only will set when they mean to simulate the CI environment
and they understand the consequences.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3889)

ci: disable cache upload/download for non-CI builds

---

ci/kokoro/windows/build-bazel.ps1
ci/kokoro/windows/build-quickstart-bazel.ps1

This reduces the size of the download from about 13GiB to about 1.7GiB,
which should save about 5 minutes for the download time, while the
decompression takes only about 20 seconds. The cost is in creating the
compressed tarball, but this only happens on continuous builds, i.e.,
the PRs only see the benefits.
Fixes #3516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3891)

ci: compress cache tarball for Windows+Bazel

---

google/cloud/bigtable/benchmarks/setup.cc

On Windows+CMake+Debug builds the C++ library has a few more assertions,
and it crashed when we passed invalid ranges to the random number
generators.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3905)

fix: crash for bigtable's scan_throughput_benchmark

---

cmake/FindgRPC.cmake

I noticed these with CMake-3.17.1, but may have been present before. We
cannot `include()` a module (aka package) from another because
`find_package_handle_standard_args()` generate warnings. Load the module
using `find_package()` works as expected.
Part of the work for #3892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3906)

fix: remove CMake warnings loading modules

---

ci/check-style.sh

With the more C++ and CMake files being added, the check-style step is
getting slower. The cmake-format step is the slowest, and was taking
about 45 seconds on my laptop. clang-format was taking about 23 seconds.
This change parallelizes the executions of these steps with `xargs -P`.
The parallelism and number of arguments values were determined
experimentally on my machine.
With this change, the cmake-format step is about 11 seconds, and the
clang-format step is about 4 seconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3912)

perf: parallelize slow formatting steps

---

ci/generate-markdown/generate-packaging.sh
doc/packaging.md

There were two distros that we tested, but did not include in our
packaging docs: CentOS:8 and Debian:Buster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3913)

doc: update packaging docs with missing distros

---

.gitignore
ci/.dockerignore
ci/etc/kokoro/install/project-config.sh
ci/kokoro/cache-functions.sh
ci/kokoro/docker/download-cache.sh
ci/kokoro/docker/upload-cache.sh
ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.centos-8
ci/kokoro/install/Dockerfile.debian-buster
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.fedora
ci/kokoro/install/Dockerfile.opensuse-leap
ci/kokoro/install/Dockerfile.opensuse-tumbleweed
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-focal
ci/kokoro/install/Dockerfile.ubuntu-xenial
ci/kokoro/install/build.sh
ci/kokoro/install/common.cfg
ci/kokoro/macos/download-cache.sh
ci/kokoro/macos/upload-cache.sh
doc/packaging.md

On Pull-Request builds, and if available, download the
ccache tarball and store them in `ci/kokoro/install/ccache-contents`.
The Dockerfile then extracts this tarball in `/h/.ccache` and configures
ccache to use that directory.
At the end of a successful build update the tarball. If the build is a CI
build then upload the tarball to the GCS folder.
Fixes #3521 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3894)

ci: use ccache in ci/kokoro/install builds

---

ci/kokoro/install/build.sh

Ooops, I disabled the Docker cache when I enabled the ccache. The former is more important.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3917)

fix: use docker cache in ci/kokoro/instal builds

---

ci/kokoro/install/build.sh
ci/templates/kokoro/install/build.sh.in

I made so many mistakes in these changes. In hindsight I should
have broken this down in a change to create the ccache tarball
(without using it), and then a change to use it. As it was my local
testing failed because:
- I expected the docker cache to not work as the devtools changed
to include ccache, but then it did not work for other reasons too.
- I expected the local tests to fail (expect when I manually did the
steps) because the cache tarballs had not been populated.
So all the testing was ad-hoc and did not catch the problems.
This time it will work, for realsies, really :fearful:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3921)

fix: actually use the ccache tarball

---

.bazelrc
bazel/ubsan_suppressions.txt

I don't think these suppressions are needed anymore since we're now
including `--linkopt=-fsanitize-link-c++-runtime`. But we'll see what
all the builds say.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3922)

chore: removes ubsan suppressions

---

ci/kokoro/windows/build-cmake-dependencies.ps1

We do not have a pre-submit build for this, and the CI build is failing.
I think for a large change like importing `google-cloud-cpp-common` I
should have (and we all should in the future) run the CI build manually.
In any case, we removed the vcpkg ports directory because we no longer
need it, but the build still refers to it. We also installed `-common` via
vcpkg, but we do not need that either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3944)

fix: build for Windows+CMake

---

ci/kokoro/windows/build-32.bat
ci/kokoro/windows/build.ps1
google/cloud/storage/parallel_upload.h

I also added support scripts to compile with MSVC+x86 on Windows.
I am not sure we would enable CI builds for that platform, but it is
nice to be able to manually run the full build.
Fixes #3797
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3916)

fix: build problems on MSVC x86

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/internal-cleanup.md

Adds two more custom issue templates that might make it easier for us to file issues correctly. One benefit of these templates is they default set the labels correctly.
/cc @mr-salty who added the feature request template to `-spanner` and which I copied from here.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3947)

feat: adds Feature Request and Internal Cleanup templates

---

.clang-tidy

clang-tidy does not scan headers by default, you have to enable a
regular expression for it. As we import projects where the headers do
pass the clang-tidy checks, we should enable the checks for that
particular project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3948)

cleanup: enable clang-tidy in pubsub headers

---

ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.centos-8
ci/kokoro/install/Dockerfile.debian-buster
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.fedora
ci/kokoro/install/Dockerfile.opensuse-leap
ci/kokoro/install/Dockerfile.opensuse-tumbleweed
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-focal
ci/kokoro/install/Dockerfile.ubuntu-xenial
doc/packaging.md

We need to install `ccache` for these builds to support caching, and
somehow I regenerated these Dockerfiles with everything right except
installing ccache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3950)

ci: regenerate Dockerfiles for ci/kokoro/install

---

ci/kokoro/docker/build.sh
ci/kokoro/docker/publish-refdocs.sh
ci/kokoro/docker/upload-docs.sh
google/cloud/CMakeLists.txt
google/cloud/doc/common-main.dox

Fix the upload-refdocs.sh script to upload the common libraries.
The upload-docs.sh script has not uploaded anything to
googleapis.github.io in a few months. It seems that branch detection was
broken. I refactored the script to reuse the branch detection from
`build.sh` so we have only one place to fix in the future.
I added a landing page for the common libraries, nothing fancy, but
better than a blank page.
Fixes #3584 and fixes #3931 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3953)

doc: update documentation scripts

---

google/cloud/CMakeLists.txt
google/cloud/bigquery/CMakeLists.txt
google/cloud/bigtable/CMakeLists.txt
google/cloud/bigtable/testing/embedded_server_test_fixture.cc
google/cloud/bigtable/testing/table_integration_test.cc
google/cloud/bigtable/testing/table_integration_test.h
google/cloud/bigtable/testing/validate_metadata.cc
google/cloud/firestore/CMakeLists.txt
google/cloud/pubsub/CMakeLists.txt
google/cloud/storage/CMakeLists.txt
google/cloud/storage/oauth2/authorized_user_credentials_test.cc
google/cloud/storage/oauth2/compute_engine_credentials_test.cc
google/cloud/storage/oauth2/service_account_credentials_test.cc
google/cloud/storage/testing/mock_http_request.cc
google/cloud/storage/testing/mock_http_request.h
google/cloud/storage/testing/random_names.cc
google/cloud/storage/testing/storage_integration_test.cc
google/cloud/storage/testing/storage_integration_test.h
google/cloud/storage/tests/object_file_integration_test.cc
google/cloud/storage/tests/object_file_multi_threaded_test.cc
google/cloud/storage/tests/object_media_integration_test.cc
google/cloud/storage/tests/slow_reader_chunk_integration_test.cc
google/cloud/storage/tests/slow_reader_stream_integration_test.cc

That is, the code that gets compiled into `.a` files that our customers would
link, and including test support libraries. The code for tests and examples
will need additional work (and lots of it).
Fixed the existing (but unreported) clang-tidy warnings.
Part of the work for #3958
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3960)

fix: run clang-tidy on the code for library targes

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/integration_tests/CMakeLists.txt
google/cloud/pubsub/samples/CMakeLists.txt
google/cloud/pubsub/version.h

I made a cosmetic change in `version.h` to force a rebuild, and I like
the new code better anyway.
Part of the work for #3958
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3963)

fix: enable clang-tidy on all g/c/pubsub/ targets

---

google/cloud/bigquery/CMakeLists.txt
google/cloud/pubsub/CMakeLists.txt

Both bigquery/ and pubsub/ captured the git revision into a CMake
variable, but this is no longer needed as the build information is
shared with the common libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3966)

cleanup: remove unused CMake code

---

.clang-tidy

This PR copies over the settings that -spanner already has. The only new setting is `-readability-magic-numbers`, which I think is a good one to ignore anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3968)

chore: prepare clang-tidy to receive -spanner

---

google/cloud/connection_options_test.cc
google/cloud/internal/background_threads_impl_test.cc

Fixes: https://github.com/googleapis/google-cloud-cpp/issues/3962
This PR increases some `wait_for` timeouts in an attempt to minimize test flakes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3971)

fix: deflake by increasing some timeouts

---

ci/kokoro/windows/build-quickstart-cmake.ps1
google/cloud/bigtable/quickstart/CMakeLists.txt
google/cloud/bigtable/quickstart/README.md
google/cloud/storage/quickstart/CMakeLists.txt
google/cloud/storage/quickstart/README.md

Require CMake >= 3.15 for the quickstart examples, with that version we
can write slightly cleaner code to pick the MSVC runtime.
Fixes #3729
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3979)

cleanup: simplify quickstart CMakeLists.txt files

---

google/cloud/storage/client_sign_policy_document_test.cc
google/cloud/storage/internal/policy_document_request.cc
google/cloud/storage/internal/policy_document_request_test.cc
google/cloud/storage/tests/signed_url_conformance_test.cc
google/cloud/storage/tests/v4_signatures.json

This fixes #3943.
Update to commit
https://github.com/googleapis/conformance-tests/commit/dfdfff54cc4200fa7e1a2a7da6e3528389648214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3980)

chore: update conformance test

---

google/cloud/storage/tests/CMakeLists.txt
google/cloud/storage/tests/bucket_integration_test.cc
google/cloud/storage/tests/curl_download_request_integration_test.cc
google/cloud/storage/tests/curl_request_integration_test.cc
google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc
google/cloud/storage/tests/curl_sign_blob_integration_test.cc
google/cloud/storage/tests/error_injection_integration_test.cc
google/cloud/storage/tests/key_file_integration_test.cc
google/cloud/storage/tests/object_checksum_integration_test.cc
google/cloud/storage/tests/object_file_multi_threaded_test.cc
google/cloud/storage/tests/object_hash_integration_test.cc
google/cloud/storage/tests/object_insert_integration_test.cc
google/cloud/storage/tests/object_integration_test.cc
google/cloud/storage/tests/object_media_integration_test.cc
google/cloud/storage/tests/object_parallel_upload_integration_test.cc
google/cloud/storage/tests/object_plenty_clients_serially_integration_test.cc
google/cloud/storage/tests/object_plenty_clients_simultaneously_integration_test.cc
google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc
google/cloud/storage/tests/object_resumable_write_integration_test.cc
google/cloud/storage/tests/object_rewrite_integration_test.cc
google/cloud/storage/tests/object_write_streambuf_integration_test.cc
google/cloud/storage/tests/service_account_integration_test.cc
google/cloud/storage/tests/signed_url_conformance_test.cc
google/cloud/storage/tests/signed_url_integration_test.cc
google/cloud/storage/tests/slow_reader_chunk_integration_test.cc
google/cloud/storage/tests/slow_reader_stream_integration_test.cc
google/cloud/storage/tests/thread_integration_test.cc

part of #3958
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3982)

cleanup: enable clang-tidy for `storage/tests`

---

google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/examples/storage_bucket_acl_samples.cc
google/cloud/storage/examples/storage_bucket_cors_samples.cc
google/cloud/storage/examples/storage_bucket_default_kms_key_samples.cc
google/cloud/storage/examples/storage_bucket_iam_samples.cc
google/cloud/storage/examples/storage_bucket_requester_pays_samples.cc
google/cloud/storage/examples/storage_bucket_samples.cc
google/cloud/storage/examples/storage_default_object_acl_samples.cc
google/cloud/storage/examples/storage_event_based_hold_samples.cc
google/cloud/storage/examples/storage_examples_common.cc
google/cloud/storage/examples/storage_examples_common.h
google/cloud/storage/examples/storage_lifecycle_management_samples.cc
google/cloud/storage/examples/storage_notification_samples.cc
google/cloud/storage/examples/storage_object_acl_samples.cc
google/cloud/storage/examples/storage_object_cmek_samples.cc
google/cloud/storage/examples/storage_object_csek_samples.cc
google/cloud/storage/examples/storage_object_file_transfer_samples.cc
google/cloud/storage/examples/storage_object_hold_samples.cc
google/cloud/storage/examples/storage_object_resumable_write_samples.cc
google/cloud/storage/examples/storage_object_rewrite_samples.cc
google/cloud/storage/examples/storage_object_samples.cc
google/cloud/storage/examples/storage_object_versioning_samples.cc
google/cloud/storage/examples/storage_policy_doc_samples.cc
google/cloud/storage/examples/storage_public_object_samples.cc
google/cloud/storage/examples/storage_quickstart.cc
google/cloud/storage/examples/storage_retention_policy_samples.cc
google/cloud/storage/examples/storage_service_account_samples.cc
google/cloud/storage/examples/storage_signed_url_v2_samples.cc
google/cloud/storage/examples/storage_signed_url_v4_samples.cc
google/cloud/storage/examples/storage_website_samples.cc

part of #3958 (also see my comment there about whether we actually want
to do this).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3984)

cleanup: enable clang-tidy for `storage/examples`

---

google/cloud/storage/client_options.h
google/cloud/storage/client_options_test.cc
google/cloud/storage/tests/curl_request_integration_test.cc

I left the old function name there (marked `@deprecated`) so as to not break the API for users. I also changed the signature of the new function to accept the argument by-value, since a copy was always being made anyway -- this may reduce the total number of copies in some cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3991)

fix: typo in function name

---

.github/CODEOWNERS

This file contains the usernames of the code's owners. The file syntax
is similar to that of .gitignore. The owners will be automatically added
to the review line of PRs. This should make it easier for us to request
PR reviews, and it will definitely be easier for OSS contributors who
want to send a PR.
I've not used this feature personally, but I think it's worth trying
out. We can always remove this if it's harmful or not helpful.
More info: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
NOTE: It did not work on this particular PR. I still needed to manually add reviewers to this PR. But it should work on the *next* PR.
--- …

feat: adds .github/CODEOWNERS

---

ci/check-style.sh

Also add the `--quiet` option to silence the ...
```
All done! __ __ __
<N> files left unchanged.
```
output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3996)

cleanup: correct the URL for the black Python code formatter

---

.github/CODEOWNERS

This will make it easier for us to load balance PRs and stuff, and I think it will give us more options. I'm not sure of all the details, but I think it's worth a try.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3998)

fix: use github team as owner

---

google/cloud/CMakeLists.txt
google/cloud/completion_queue_test.cc
google/cloud/connection_options_test.cc
google/cloud/future_generic_test.cc
google/cloud/future_generic_then_test.cc
google/cloud/future_void_test.cc
google/cloud/future_void_then_test.cc
google/cloud/iam_bindings_test.cc
google/cloud/internal/async_retry_unary_rpc_test.cc
google/cloud/internal/backoff_policy_test.cc
google/cloud/internal/future_impl_test.cc
google/cloud/internal/invoke_result_test.cc
google/cloud/internal/random_test.cc
google/cloud/internal/throw_delegate_test.cc
google/cloud/log_test.cc
google/cloud/optional_test.cc
google/cloud/status_or_test.cc
google/cloud/status_test.cc
google/cloud/terminate_handler_test.cc

For `google_cloud_cpp_common_unit_tests` and `google_cloud_cpp_grpc_utils_unit_tests`.
Part of #3958.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4001)

cleanup: enable more clang-tidy warnings in tests

---

.clang-tidy
google/cloud/firestore/CMakeLists.txt
google/cloud/firestore/field_path.h

Part of #3958.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4002)

cleanup: enable clang-tidy for `firestore`

---

ci/check-style.sh

The "Verifying formatting" step is sometimes slow-ish, and when we run
clang-tidy from the command line, it would be nice to see what it's
doing. This PR adds timing output to each section of the check-style
script so the user can see what it's doing, and we'll know if a section
all of a sudden gets slow and can be optimized. The output looks like:
```
2020-05-05T18:41:32Z: Verify formatting
Running check-include-guards: ... 0.045 seconds
Running cmake-format:         ... 3.607 seconds
Running clang-format:         ... 1.981 seconds
Running buildifier:           ... 0.041 seconds
Running black:                ... 0.148 seconds
Running shfmt:                ... 0.024 seconds
Running shellcheck:           ... 1.237 seconds
Running include fixes:        ... 1.876 seconds
Running whitespace …
```

feat: outputs timing for check-style blocks

---

.bazelignore
bazel/google_cloud_cpp_deps.bzl

Also fixes the patterns in the `.bazelignore` file, which does
not understand globs at all. Only file paths, so we need to explicitly
list all of our quickstart/ directories that need to be ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4012)

feat: adds benchmark dep to bazel

---

ci/kokoro/windows/build.ps1

After the build runs we cleanup the ${env:KOKORO_ARTIFACTS_DIR}
directory (if present).  This is not supposed to break the build, but at
least once it did. With this change we put a try/catch to ignore all
errors for realsies.
Fixes #3803 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4017)

ci: ignore errors on build cleanup

---

google/cloud/spanner/internal/connection_impl_test.cc

The unit test for spanner::Client was logging errors when the default
gRPC credentials where unavailable, even though these credentials are
not used it the test. Fixed by using
`grpc::InsecureChannelCredentials()`.
Fixes #4041
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4049)

cleanup: fix (harmless) error log messages in test

---

BUILD

This target is the one recommend users use, and it's the one we use in
our spanner/quickstart/.
Part of https://github.com/googleapis/google-cloud-cpp/issues/3703
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4048)

fix: add top-level BUILD target for :spanner_client

---

google/cloud/bigtable/quickstart/BUILD
google/cloud/storage/quickstart/BUILD

Part of https://github.com/googleapis/google-cloud-cpp/issues/3703
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4050)

chore: bigtable, storage quickstarts use top-level build targets

---

google/cloud/bigtable/benchmarks/CMakeLists.txt
google/cloud/bigtable/benchmarks/bigtable_benchmarks_unit_tests.bzl
google/cloud/bigtable/benchmarks/random_mutation_test.cc

Fixes #4052 . Thanks to @devjgm for noticing this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4058)

fix: bigtable's random_mutation_test missing from build

---

google/cloud/bigquery/version.cc
google/cloud/bigquery/version.h
google/cloud/bigtable/version.cc
google/cloud/bigtable/version.h
google/cloud/pubsub/version.cc
google/cloud/pubsub/version.h
google/cloud/spanner/version.cc
google/cloud/spanner/version.h
google/cloud/storage/version.cc
google/cloud/storage/version.h
google/cloud/version.cc
google/cloud/version.h

We had multiple implementations of the version() and version_string()
functions, one on each library. This refactors the implementations to
use only the one from `google::cloud::`. I do not think we should remove
these functions, while rarely used they are part of the public API, and
we should avoid breaking changes when we can.
In the case of bigquery/ and pubsub/ we probably can remove the
functions, and I propose doing so in a followup PR.
Part of the work for #3712
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4062)

cleanup: refactor version() and version_string()

---

ci/kokoro/windows/build-quickstart-bazel.ps1

There were several mistakes in the build script preventing it from
uploading the cache on continuous builds. These go untected because
errors uploading and/or downloading the cache are intentionally
non-fatal.
Fixes #4061
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4064)

ci: fix cache refresh for quickstart-bazel build

---

ci/kokoro/docker/build-in-docker-cmake.sh
ci/kokoro/docker/build.sh
google/cloud/spanner/integration_tests/client_integration_test.cc
google/cloud/spanner/integration_tests/data_types_integration_test.cc
google/cloud/storage/examples/storage_object_samples.cc

This change minimizes the time spent on clang-tidy for PR builds.
On interactive builds and continuous builds the `clang-tidy` build works
as before: CMake calls `clang-tidy` for whatever TU it rebuilds, and so
(for the most part) only changed files run `clang-tidy`. Changes in
headers, of course, trigger a lot more `clang-tidy` work, but that might
be necessary.
On PR builds only the files changed w.r.t. to the target branch run through
`clang-tidy`. In some cases that might cause more files that necessary to
be examined, e.g. if the PR was based on an older version of `master`.
And in some it will cause fewer files, notably with header changes that
could affect the `clang-tidy` results.
The build times are about 8m with a warm cache.
Fixes #4057 
Here is an example of a PR build …

ci: speed up clang-tidy builds

---

ci/kokoro/docker/build-in-docker-cmake.sh

When compiling PR builds we run `clang-tidy` before compiling the code,
this skips the step to download and patch the lohmann json header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4078)

ci: fix clang-tidy PR builds for storage/*

---

google/cloud/internal/parse_rfc3339.cc

Hello.
Nothing special, just found incorrect (but working fine since both are 60) duration usage in the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4079)

cleanup: fixing misleading duration names usage

---

ci/kokoro/docker/Dockerfile.ubuntu-install
ci/kokoro/docker/build-in-docker-cmake.sh
ci/kokoro/docker/build.sh
google/cloud/spanner/benchmarks/CMakeLists.txt
google/cloud/spanner/benchmarks/benchmarks_config.cc
google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh
google/cloud/spanner/integration_tests/CMakeLists.txt
google/cloud/spanner/integration_tests/client_integration_test.cc
google/cloud/spanner/integration_tests/client_stress_test.cc
google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
google/cloud/spanner/samples/CMakeLists.txt

For CMake builds we use the emulator to run the spanner integration
tests. The main motivation is the `coverage` test, which needs to
serialize the tests and runs very slowly against production. Other
builds run fine against the emulator or against production, but testing
locally is usually faster.
The drop in code coverage (0.22%) can be fixed with via #4080, but I think
we should leave that to a future PR.
Fixes #4023
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4077)

ci: use emulator for the spanner integration tests

---

.clang-format
bazel/google_cloud_cpp_deps.bzl
ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.centos-8
ci/kokoro/install/Dockerfile.debian-buster
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.fedora
ci/kokoro/install/Dockerfile.opensuse-leap
ci/kokoro/install/Dockerfile.opensuse-tumbleweed
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-focal
ci/kokoro/install/Dockerfile.ubuntu-xenial
doc/packaging.md
google/cloud/spanner/BUILD
google/cloud/spanner/CMakeLists.txt
google/cloud/spanner/results_test.cc
super/CMakeLists.txt
super/external/abseil.cmake

Fixes: https://github.com/googleapis/google-cloud-cpp/issues/2309
Adds a dep on Abseil. Uses `absl::make_unique` in one test in Spanner just to show that the Abseil dep is working in all the builds.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4087)

feat!: add a dep on Abseil

---

google/cloud/bigtable/tests/CMakeLists.txt
google/cloud/bigtable/tests/admin_async_future_integration_test.cc
google/cloud/bigtable/tests/admin_iam_policy_integration_test.cc
google/cloud/bigtable/tests/admin_integration_test.cc
google/cloud/bigtable/tests/data_async_future_integration_test.cc
google/cloud/bigtable/tests/data_integration_test.cc
google/cloud/bigtable/tests/filters_integration_test.cc
google/cloud/bigtable/tests/instance_admin_emulator.cc
google/cloud/bigtable/tests/instance_admin_integration_test.cc
google/cloud/bigtable/tests/mutations_integration_test.cc

part of #3958
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4089)

cleanup: enable clang-tidy for `bigtable/tests`

---

cmake/EnableCoverage.cmake
cmake/EnableWerror.cmake
cmake/GoogleCloudCppCommon.cmake
google/cloud/CMakeLists.txt
google/cloud/bigquery/read_result.h
google/cloud/bigtable/examples/bigtable_examples_common.cc
google/cloud/bigtable/examples/bigtable_examples_common.h
google/cloud/google_cloud_cpp_common.bzl
google/cloud/google_cloud_cpp_common_unit_tests.bzl
google/cloud/internal/diagnostics_pop.inc
google/cloud/internal/diagnostics_push.inc
google/cloud/internal/disable_msvc_crt_secure_warnings.inc
google/cloud/internal/parse_rfc3339.cc
google/cloud/internal/strerror.cc
google/cloud/internal/strerror.h
google/cloud/internal/strerror_test.cc
google/cloud/log.cc
google/cloud/optional_test.cc
google/cloud/pubsub/integration_tests/CMakeLists.txt
google/cloud/spanner/CMakeLists.txt
google/cloud/spanner/integration_tests/CMakeLists.txt
google/cloud/spanner/internal/date.cc
google/cloud/spanner/testing/random_instance_name.cc
google/cloud/spanner/value.cc
google/cloud/storage/CMakeLists.txt
google/cloud/storage/internal/curl_handle.cc
google/cloud/storage/internal/object_requests.cc
google/cloud/storage/oauth2/service_account_credentials.cc
google/cloud/storage/parallel_uploads_test.cc

Fix all the warnings generated by MSVC, most of them were useful. I also
chose to use pragmas to disable warning 4996 (aka you are using an
insecure function) because we should keep that warning enable in as much
of our code as possible. Previously we were disabling it for full files.
Because users may compile with newer versions of the compiler this PR
also includes a CMake option to disable /WX (and -Werror), in case the
newer (or older I suppose) version of the compiler generates warnings we
have not handled.
Fixes #3068
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4095)

cleanup: enable /WX (aka -Werror) with MSVC

---

ci/kokoro/docker/build-in-docker-cmake.sh

Many of our headers are not clang-tidy clean, so we need to limit the
regular expression to whatever is on the `.clang-tidy` file.
There is some cleanup which can happen after #3958
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4097)

ci: only clang-tidy headers in the .clang-tidy regexp

---

google/cloud/internal/strerror_test.cc

The test is failing on Windows, but for some reason the CI builds are
passing. A bit of a mistery for me, but while we chase that, let's fix
the bug.
See #4103 for how this went undetected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4104)

fix: strerror test on Windows

---

google/cloud/bigtable/examples/CMakeLists.txt
google/cloud/bigtable/examples/bigtable_examples.bzl
google/cloud/bigtable/examples/data_filter_snippets.cc

first pull request for #3500. This covers examples for following tags.
- bigtable_filters_limit_row_sample
- bigtable_filters_limit_row_regex
- bigtable_filters_limit_cells_per_col
- bigtable_filters_limit_cells_per_row
- bigtable_filters_limit_cells_per_row_offset
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4069)

feat: add bigtable data filter samples

---

ci/kokoro/windows/build-bazel.ps1
ci/kokoro/windows/build-cmake-dependencies.ps1
ci/kokoro/windows/build-cmake.ps1
ci/kokoro/windows/build-quickstart-bazel.ps1
ci/kokoro/windows/build-quickstart-cmake.ps1
ci/kokoro/windows/build.ps1
google/cloud/internal/strerror_test.cc

Fixes #4103 
I tested by first building code that had a failing test. Note that this doe not cover every path where we need to explicitly handle the exit code, but at least it shows the pattern of `if ($LastExitCode) { Exit ${LastExitCode} }` works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4105)

fix: Windows CI scripts sometimes masked the exit code

---

google/cloud/BUILD
google/cloud/CMakeLists.txt
google/cloud/bigtable/BUILD
google/cloud/bigtable/CMakeLists.txt
google/cloud/bigtable/config.cmake.in
google/cloud/bigtable/row_reader.cc
google/cloud/connection_options.cc
google/cloud/spanner/BUILD
google/cloud/spanner/CMakeLists.txt
google/cloud/spanner/config.cmake.in
google/cloud/spanner/internal/connection_impl.cc
google/cloud/storage/BUILD
google/cloud/storage/CMakeLists.txt
google/cloud/storage/config.cmake.in
google/cloud/storage/parallel_upload.cc

Our installed cmake files were previously not listing `absl` as a dep, so callers were not able to link with our installed libraries and cmake files. This PR adds the correct cmake rules and also adds a non-test dep on `absl::make_unique` to common, bigtable, storage, and spanner, to show that the installed code actually works and links when running our quickstart tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4110)

fix: installed cmake files list absl as a dep

---

ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
ci/kokoro/gcloud-functions.sh
ci/retry-command.sh

* pass the number of retries and interval to `retry-program.sh`.
* apply 50% jitter to exponential backoff instead of 0-60s
* the existing cases pass the same parameters, so their behavior is
unchanged aside from the jitter changes.
Fixes #4113 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4118)

test: retry gcloud iam commands

---

ci/kokoro/docker/build-in-docker-bazel.sh
ci/lib/init.sh
google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh

We are running out of quota in production to run the Bigtable
integration tests. This change moves the Bazel-based builds to use the
emulators. A future PR will restore the nightly build to use production,
but we need to unblock progress first. The CMake-based builds already
use the emulator(s) for integration tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4121)

ci: use emulator for Bigtable+Bazel integration tests

---

google/cloud/CMakeLists.txt

Fixes: https://github.com/googleapis/google-cloud-cpp/issues/4128
Thanks to @sjoubert for reporting this.
I also filed https://github.com/googleapis/google-cloud-cpp/issues/4132 to set up a CI build to detect issues like this in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4131)

fix: use correct variable for SOVERSION

---

CMakeLists.txt

The `cmake_dependent_option` expression was incomplete.
Fixes #4130 and fixes #3926
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4133)

fix: enable grpc_utils if any gRPC-based library is

---

.clang-tidy
google/cloud/internal/async_read_stream_impl.h
google/cloud/internal/async_retry_unary_rpc.h
google/cloud/internal/completion_queue_impl.h
google/cloud/internal/disjunction.h
google/cloud/internal/filesystem.h
google/cloud/internal/future_base.h
google/cloud/internal/future_impl.h
google/cloud/internal/future_impl_test.cc
google/cloud/internal/future_then_impl.h
google/cloud/internal/future_then_meta.h
google/cloud/internal/invoke_result.h
google/cloud/internal/ios_flags_saver.h
google/cloud/internal/utility.h
google/cloud/optional_test.cc
google/cloud/status_or_test.cc
google/cloud/status_test.cc
google/cloud/testing_util/chrono_literals.h
google/cloud/testing_util/testing_types.cc
google/cloud/testing_util/testing_types.h

This time `grpc_utils`, `internal`, and `testing_util`.
Part of #3958.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4127)

cleanup: enable clang-tidy for additional headers

---

ci/kokoro/docker/build-in-docker-cmake.sh

This helps make tracking of clang-tidy warnings a little easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4137)

ci: log the clang-tidy config

---

google/cloud/bigtable/benchmarks/CMakeLists.txt
google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc
google/cloud/bigtable/benchmarks/benchmark.cc
google/cloud/bigtable/benchmarks/benchmark.h
google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc
google/cloud/bigtable/benchmarks/constants.h
google/cloud/bigtable/benchmarks/embedded_server_test.cc
google/cloud/bigtable/benchmarks/endurance_benchmark.cc
google/cloud/bigtable/benchmarks/format_duration_test.cc
google/cloud/bigtable/benchmarks/random_mutation.cc
google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc
google/cloud/bigtable/benchmarks/scan_throughput_benchmark.cc
google/cloud/bigtable/benchmarks/setup.cc
google/cloud/bigtable/benchmarks/setup.h
google/cloud/bigtable/benchmarks/setup_test.cc

Part of #3958.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4138)

cleanup: enable clang-tidy for `bigtable/benchmarks`

---

google/cloud/bigtable/examples/data_filter_snippets.cc

adding following examples;
- bigtable_filters_limit_col_family_regex
- bigtable_filters_limit_col_qualifier_regex
- bigtable_filters_limit_col_range
- bigtable_filters_limit_value_range
- bigtable_filters_limit_value_regex
- bigtable_filters_limit_timestamp_range
- bigtable_filters_limit_block_all
- bigtable_filters_limit_pass_all
- bigtable_filters_modify_strip_value
- bigtable_filters_modify_apply_label
- bigtable_filters_composing_chain
- bigtable_filters_composing_interleave
`Bigtable` now have more filter samples (#3500)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4141)

feat: more bigtable data filter samples

---

google/cloud/bigtable/examples/data_snippets.cc

These builds are failing with "Socket closed" errors (reported as
exceptions by the sample code, but that is not important). Whatever the
underlying gRPC error is, the mutations changed in this PR were not
idempotent and therefore not retried by the library, and because they
are only sample data for the code, this was entirely unnecessary.
I expect that with these changes the errors will be less common, and the
builds will be less flaky, but I cannot say if they will go away.
Part of the work for #4119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4148)

fix: reduce flakiness in macos/cmake-super build

---

google/cloud/CMakeLists.txt
google/cloud/bigtable/CMakeLists.txt
google/cloud/spanner/CMakeLists.txt
google/cloud/storage/CMakeLists.txt

Loading the Abseil CMake config files generates warnings with relatively
new versions of CMake. These are already fixed in the upcoming Abseil
release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4147)

cleanup: quiet warnings in find_package(absl)

---

.clang-tidy
google/cloud/connection_options.h
google/cloud/future_generic.h
google/cloud/future_void.h
google/cloud/iam_bindings.h
google/cloud/log.h
google/cloud/optional.h
google/cloud/status.h
google/cloud/status_or.h

Part of #3958.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4154)

cleanup: enable clang-tidy for `google/cloud` headers

---

bazel/google_cloud_cpp_deps.bzl
google/cloud/bigquery/internal/storage_stub.cc
google/cloud/storage/BUILD
google/cloud/storage/examples/BUILD
google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/examples/storage_examples.bzl
google/cloud/storage/examples/storage_grpc_samples.cc
google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/tests/CMakeLists.txt
google/cloud/storage/tests/grpc_integration_test.cc
google/cloud/storage/tests/storage_client_integration_tests.bzl

With these changes Bazel always compiles the GCS+gRPC plugin. The
application may still link only against the REST API, but our tests and
examples link against both, all the time. This does mean we have a gap
in our testing (applications that only want to link GCS with the REST
API, but using Bazel). Seems like a small gap to me.
Part of the work for #4143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4155)

feat: Bazel always compiles GCS+gRPC plugin

---

ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.centos-8
ci/kokoro/install/Dockerfile.debian-buster
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.fedora
ci/kokoro/install/Dockerfile.opensuse-leap
ci/kokoro/install/Dockerfile.opensuse-tumbleweed
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-focal
ci/kokoro/install/Dockerfile.ubuntu-xenial
doc/packaging.md
super/external/googleapis.cmake

Nothing interesting in that release, just puts us in sync with the Bazel
version of the protos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4224)

chore: update cpp-cmakefiles to v0.10.0

---

ci/kokoro/docker/build-in-docker-cmake.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4153)

cleanup: only dump clang-tidy config in CI builds

---

google/cloud/storage/tests/grpc_integration_test.cc

With MSVC+CMake when we disable the GCS+gRPC plugin we cannot
even include the gRPC-related headers. This is because Protobuf
requires some magic `-D...` options in the command-line, and these are
only present if you link the Protobuf library, and the point of disabling the
GCS+gRPC plugin is to **not** link said library.
This goes undetected on Bazel, where we always build the GCS+gRPC plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4221)

fix: MSVC+CMake builds with GCS+gRPC disabled

---

google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/internal/grpc_client_test.cc
google/cloud/storage/internal/grpc_resumable_upload_session.cc
google/cloud/storage/tests/object_file_integration_test.cc
google/cloud/storage/tests/object_insert_integration_test.cc
google/cloud/storage/tests/object_integration_test.cc
google/cloud/storage/tests/object_media_integration_test.cc
google/cloud/storage/tests/object_resumable_write_integration_test.cc

In most cases, I pointed the entry to the right GitHub issue. In some
cases the bug was fixed, and I took the opportunity to remove the
workaround. In a couple of cases the bug is in the server-side, and
I left the internal bug tracking number for those.
Part of the work for #4143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4220)

cleanup: fix TODO entries in GCS+gRPC plugin

---

ci/kokoro/docker/build-in-docker-cmake.sh

It's not always safe to append "\.h$" to a regex, so this PR changes our
clang-tidy filtering to two invocations. One to handle all .cc files,
where it can ignore the HeaderFitlerRegex. And a second invocation that
applies to all .h files that also match HeaderFitlerRegex.
Related: This should fix issues like [this one](https://source.cloud.google.com/results/invocations/bae42914-9b04-463a-9b8e-3156ce046a40/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Fclang-tidy-presubmit/log) where we were running clang-tidy on BUILD and CMakeLists.txt files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4225)

fix: clang-tidy HeaderFilterRegex was not working

---

google/cloud/storage/internal/grpc_client_test.cc

Use the matcher instead of manually comparing the protos with
MessageDifferencer.
Part of the work for #4143 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4227)

cleanup: prefer IsProtoEqual over custom comparisons

---

ci/kokoro/docker/build-in-docker-cmake.sh

The presubmit tests won't verify that, but I'll assert it,
and we'll learn whether I'm wrong as future edits are made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4231)

cleanup: `bigtable/benchmarks` is clang-clean after #4138

---

google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/internal/grpc_client_test.cc
google/cloud/storage/tests/object_media_integration_test.cc

For applications that want to read the last N bytes of a GCS object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4229)

feat: implement ReadLast option for GCS+gRPC plugin

---

ci/kokoro/docker/build-in-docker-cmake.sh

Until such time as the quota issues are resolved, just disable all the
bigtable integration tests that need to run against production.
Part of the work for #4234 it reduces the quota consumption to about
56 per PR. There is some loss of testing coverage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4235)

ci(CMake): disable all production Bigtable tests

---

.clang-tidy
ci/kokoro/docker/build-in-docker-cmake.sh
google/cloud/bigtable/examples/CMakeLists.txt
google/cloud/examples/CMakeLists.txt
google/cloud/examples/gcs2cbt.cc
google/cloud/storage/benchmarks/CMakeLists.txt
google/cloud/storage/benchmarks/benchmark_utils.cc
google/cloud/storage/benchmarks/benchmark_utils.h
google/cloud/storage/benchmarks/bounded_queue.h
google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc
google/cloud/storage/benchmarks/storage_latency_benchmark.cc
google/cloud/storage/benchmarks/storage_parallel_uploads_benchmark.cc
google/cloud/storage/benchmarks/storage_shard_throughput_benchmark.cc
google/cloud/storage/benchmarks/storage_throughput_benchmark.cc
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
google/cloud/storage/examples/CMakeLists.txt
google/cloud/testing_util/CMakeLists.txt

The clang-tidy `HeaderFilterRegex` now covers all `google/cloud`
header files, and `google_cloud_cpp_add_clang_tidy()` is applied
in every `CMakeLists.txt` file.
Tweak the "presubmit builds only tidy changed files" support to
extract the `HeaderFilterRegex` using `clang-tidy -dump-config`
so that unescaping is done before passing the RE to `grep`.
Part of #3958.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4238)

cleanup: enable clang-tidy across the board

---

google/cloud/storage/CMakeLists.txt
google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/internal/grpc_client_object_request_test.cc
google/cloud/storage/storage_client_grpc_unit_tests.bzl
google/cloud/storage/tests/object_media_integration_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4237)

fix: GCS+gRPC use the documented behavior for ReadLast

---

google/cloud/storage/CMakeLists.txt
google/cloud/storage/bucket_access_control.h
google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/internal/grpc_client.h
google/cloud/storage/internal/grpc_client_bucket_metadata_test.cc
google/cloud/storage/storage_client_grpc_unit_tests.bzl

Fixes #4174 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4247)

feat: proto conversions for BucketAccessControl

---

ci/kokoro/windows/common.cfg

The builds are taking (routinely) about 110m, we need to increase
the timeout to make room for new code, such as `cpp-cmakefiles`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4251)

ci: increase Windows build timeout to 180m

---

ci/kokoro/docker/build-in-docker-cmake.sh
external/googleapis/CMakeLists.txt

If clang-tidy does not find a header (like a generated `*.pb.h` file) it
gets really confused and generates many spurious errors.
To see such a spurious failure look at:
https://source.cloud.google.com/results/invocations/63b78a23-c7b7-4f0d-9f4c-61a9e29c7c90
If we prefer to move the `clang-tidy` phase until all the code is
generated, we can do that, just keep in mind that this will delay
clang-tidy results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4256)

ci: compile protos before running clang-tidy

---

google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/internal/grpc_client.h
google/cloud/storage/internal/grpc_client_bucket_metadata_test.cc

The BucketMetadata class has many different components (e.g.
BucketBilling, BucketWebsite, BucketVersioning), this adds conversion
functions for them.
Fixes #4164, fixes #4167, and fixes #4168
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4254)

feat: convert To/From protos for Bucket* structs

---

google/cloud/storage/BUILD
google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/internal/grpc_client.h
google/cloud/storage/internal/grpc_client_bucket_metadata_test.cc

In this change: `Bucket::Cors`, `Bucket::Encryption`,
`Bucket::IamConfiguration`, `Bucket::Logging`,
`Bucket::RetentionPolicy`.
This fixes #4169, fixes #4170, fixes #4171, and fixes #4172.
We never created a bug for `IamConfiguration` (it is new-ish).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4260)

feat: more To/FromProto for Bucket* structs

---

CMakeLists.txt
external/googleapis/CMakeLists.txt
google/cloud/CMakeLists.txt
google/cloud/pubsub/config-version.cmake.in

Always use GOOGLE_CLOUD_CPP_VERSION which is now set in the top-level
CMake file.
Also fixed the pubsub/config-version.cmake.in file which was referencing
GOOGLE_CLOUD_CPP_**PUBSUB**_VERSION, a variable that no longer exists.
Fixes #4265 and fixes #4266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4268)

fix: cleanup how shared libs get a VERSION

---

google/cloud/storage/client.cc
google/cloud/storage/client.h
google/cloud/storage/client_write_object_test.cc

This fixes #3432.
Before this change, `seekg` was called for proper behavior for every
`UploadChink`. Because it was `expected`, which was broken, the `seekg`
was effectively a noop, so everything worked, except for generating
warnings.
This PR also removes the `seekg` from that execution path altogether.
Playing with tests proved that unless there is a bug in the code, there
is no way to end up in a situation when `seekg` was called and even if
this situation occurred, it would be impossible to properly recover from
it. In order to not increase the likelihood of a corruption, I replaced
this logic with returning an error.
In order to make sure that resumable upload sessions are properly
handled, a `seekg` is added at the beginning to handle resuming a
stream.
--- …

fix: fix off-by-one in uploading streams to GCS

---

google/cloud/bigtable/cell.h
google/cloud/bigtable/cell_test.cc

This fixes #4108.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4240)

feat: add rvalue reference overloads to `Cell`

---

google/cloud/bigtable/row.h
google/cloud/bigtable/row_test.cc

This fixes #4107.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4239)

feat: add rvalue reference overloads to `Row`

---

google/cloud/bigtable/cell.h

Noticed some warnings indicating a struct/class mismatch in the forward declaration of Mutation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4274)

chore: fix forward declaration of Mutation to match definition

---

google/cloud/storage/benchmarks/benchmark_utils.cc
google/cloud/storage/benchmarks/benchmark_utils.h
google/cloud/storage/benchmarks/storage_throughput_benchmark.cc
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc

I will need this in the throughput_vs_cpu_benchmark.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4276)

refactor: move ApiName enum to common routines

---

google/cloud/storage/grpc_plugin.cc
google/cloud/storage/grpc_plugin.h

This overload cannot fail, its return type should indicate that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4278)

feat: DefaultGrpcClient(Options) cannot fail

---

ci/kokoro/docker/build-in-docker-cmake.sh

We were trying to run clang-tidy over removed files, that always fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4280)

ci: do not try to tidy removed files

---

super/external/grpc.cmake

By default gRPC compiles a C# extension shared library (`.so`) even if
all the dependencies (like Abseil) are compiled statically. In some
platforms that just breaks (mixing PIC code and non-PIC code
results in an error). Since we do not use this extension I think the
simplest thing is to disable it for super builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4282)

fix: super builds when compiling static libraries

---

google/cloud/storage/benchmarks/benchmark_utils.cc
google/cloud/storage/benchmarks/benchmark_utils.h
google/cloud/storage/benchmarks/benchmark_utils_test.cc
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc

I thought it would be useful to report throughput stats after N bytes,
but turns out we did not need that data. Removing the code because I
would rather not carry unused code around.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4283)

cleanup: remove ProgressReporter in benchmarks

---

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc

We only upload one chunk at a time, and therefore we only need to
compute random data up to the maximum chunk size. We were computing
random data up to a full object size, which can be several times larger.
Also reduce the amount of entropy consumed to initialize the random
number generators.
Part of the work for #4273 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4287)

feat(storage/benchmark): reduce random data size

---

ci/kokoro/docker/build.sh
ci/kokoro/gcloud-functions.sh

When enabled with the `DOCKER_USE_HOST_NETWORK` environment variable, our docker containers will share the host's networking. This can be useful when running on a host with a non-trivial networking configuration, such as DNS caches, etc, that you want to share with the docker container. 
This change also exposed an issue where some of our gcloud commands used
incidental gcloud accounts that existed on the system, other than the
service acount that we intended. This is fixed by passing `--account=""`
to some gcloud commands where we know we don't want to use any existing
system account.
I believe this should fix the issue that @devbww and I were having when running the integration tests on our GCE instances.
--- …

feat: optionally use host network in docker containers

---

google/cloud/storage/benchmarks/benchmark_utils.cc
google/cloud/storage/benchmarks/benchmark_utils.h
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc

If the GCS+gRPC plugin is enabled also benchmark uploads and downloads
using the plugin. That is, the benchmark now compares JSON, XML, and
gRPC with different object sizes.
This finally fixes #4273
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4291)

feat(storage/benchmark): use the GCS+gRPC plugin

---

google/cloud/storage/client.cc
google/cloud/storage/client.h
google/cloud/storage/client_write_object_test.cc
google/cloud/storage/internal/curl_client.cc
google/cloud/storage/internal/curl_request_builder.h
google/cloud/storage/internal/object_requests.h
google/cloud/storage/testbench/gcs_bucket.py
google/cloud/storage/tests/object_integration_test.cc
google/cloud/storage/upload_options.h

This fixes #3162.
Unfortunately, there does not seem to be a way to set the counterpart of
this header for gRPC version, so only cURL is supported.
Emulator is updated to support this too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4284)

feat: support X-Upload-Content-Length header

---

google/cloud/bigtable/examples/data_async_snippets.cc

fixes #4119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4296)

fix: flake in bigtable AsyncReadModifyWrite example

---

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_plots.py

Download the same file more than once to get data about warm downloads.
Shorten some field names in the output because the plots were unreadable
with longer names.
Not that it matters, because they are fixed numbers and unused in the
plots, but the download vs. upload buffer sizes were reported backwards,
ooops.
Fixes #4292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4299)

feat(storage/benchmarks): measure warm downloads

---

google/cloud/bigtable/examples/data_async_snippets.cc
google/cloud/bigtable/examples/data_snippets.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4300)

fix: potentially flaky examples in bigtable data snippets

---

google/cloud/spanner/ci/lib/spanner_emulator.sh
google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh

With this refactoring, we could start/stop the emulator from bazel
builds as well as cmake (which we use today). 98% of this change is copying existing code from one script to another.
Related to https://github.com/googleapis/google-cloud-cpp/issues/4297
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4309)

chore: refactored spanner emulator script into a library

---

google/cloud/storage/benchmarks/README.md
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc

The benchmark uses randomly sized application-level buffers to upload
and download objects. There are some sizes that are known to be much
better. For example, for uploads, anything that is a multiple of 256KiB.
Sometimes it is interesting to test with "bad" buffer sizes, but most
often it is better to use the right values.
There is also no reason to upload and download with the same buffer
sizes, this change uses different buffer sizes for each.
Furthermore, the benchmark called application-level buffers "chunks",
this was a poorly chosen name. There are other "chunks" in a resumable
upload, and this made things confusing.
Finally, changed the default values for these application level buffers
to something that is more reasonable.
Fixes #4303
--- …

feat(storage/benchmarks): quantize app buffers

---

ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.centos-8
ci/kokoro/install/Dockerfile.debian-buster
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.fedora
ci/kokoro/install/Dockerfile.opensuse-leap
ci/kokoro/install/Dockerfile.opensuse-tumbleweed
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-focal
ci/kokoro/install/Dockerfile.ubuntu-xenial
doc/packaging.md
google/cloud/storage/benchmarks/BUILD
google/cloud/storage/benchmarks/CMakeLists.txt
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
super/external/abseil-patch.cmake
super/external/abseil.cmake

Abseil has a configuration file that controls whether it uses some types
(`std::any`, `std::variant`, `std::string_view`, etc.) from the standard
library, provides its own, or dynamically discovers if they are
available in the library.
If you want to compile Abseil once, and then use with both C++11 and
C++17 compilers you need to edit `base/options.h` and pin these types to
the `absl::` versions. This is what we do in our CI builds, so we need
to patch the file.
Fixes #4305
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4311)

ci: patch Abseil base/options.h to pin C++11 types

---

ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build.sh

Reverts googleapis/google-cloud-cpp#4313
We still saw a timeout from spanner backup test after 15 minutes: https://source.cloud.google.com/results/invocations/9d52df69-7276-47a5-891a-46237d11178d/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Fintegration/log
```
[ RUN      ] BackupTestWithCleanup.BackupTestSuite
google/cloud/spanner/integration_tests/backup_integration_test.cc:169: Failure
Value of: backup
Expected: is OK
Actual: exhausted polling policy with no previous error [DEADLINE_EXCEEDED]
```
However, this was not a bazel timeout, it was a timeout in the code, I think, from this code:
https://github.com/googleapis/google-cloud-cpp/blob/0bf38cf1ecd2a317bd21d7a4e4ea94f428baf478/google/cloud/spanner/testing/policies.h#L29
I'm reverting this to stop the flakes. We …

revert: fix: re-enable spanner backup tests w/ increased timeout

---

google/cloud/bigtable/cell_test.cc

Do not assume that `google::cloud::bigtable::CellValueType` can be
directly converted to a `std::string`.  Here we just use `auto` to
avoid mentioning a specific type altogether.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4317)

cleanup: be careful with the type of bigtable::Cell::value()

---

google/cloud/BUILD
google/cloud/bigquery/BUILD
google/cloud/bigtable/BUILD
google/cloud/bigtable/benchmarks/BUILD
google/cloud/firestore/BUILD
google/cloud/spanner/BUILD
google/cloud/spanner/integration_tests/BUILD
google/cloud/storage/BUILD
google/cloud/storage/benchmarks/BUILD

Some (but not all) of our test targets for Bazel were prefixed with the
library that they tested. This is unnecessary with Bazel, as the targets
are already scoped to each BUILD file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4322)

cleanup: do not prefix Bazel test targets

---

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc

Sometimes we want to run a benchmark with fixed values for CRC32C and/or
MD5 hashing. This adds command line options to run the benchmarks with
either these options fixed to some value from the command-line, or to
chose a random value on each iteration (the default, as before).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4326)

feat(storage/benchmarks): control CRC32C/MD5 options

---

ci/generate-markdown/generate-spanner-readme.sh
ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
ci/kokoro/windows/build.ps1
doc/setup-development-environment.md
google/cloud/BUILD
google/cloud/README.md
google/cloud/spanner/README.md
google/cloud/spanner/benchmarks/README.md
google/cloud/spanner/doc/spanner-main.dox
google/cloud/spanner/quickstart/CMakeLists.txt
google/cloud/spanner/quickstart/README.md
release/release.sh

I was just going to remove the vcpkg references, but I found many
other references in the documentation and comments that needed fixing
too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4329)

cleanup: remove references to google-cloud-cpp-*

---

google/cloud/completion_queue.h
google/cloud/completion_queue_test.cc

The captured completion queue (`this`), could be destroyed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4330)

fix: memory stomping in CompletionQueue::RunAsync

---

google/cloud/storage/benchmarks/CMakeLists.txt
google/cloud/storage/benchmarks/storage_benchmarks.bzl
google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
google/cloud/storage/benchmarks/throughput_options.cc
google/cloud/storage/benchmarks/throughput_options.h
google/cloud/storage/benchmarks/throughput_options_test.cc

Move functions to parse the throughput_vs_cpu_benchmark options to a
common file in the benchmarks library. If nothing else it makes testing
easier, but I may create separate benchmarks soonish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4345)

refactor(storage/benchmarks): options parsing

---

README.md
ci/generate-markdown/generate-readme.sh

The move to a monorepo is finished.
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/3612
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4348)

feat: remove notice about moving to monorepo

---

google/cloud/internal/slow_iota_test.cc
google/cloud/internal/source_accumulators.h
google/cloud/internal/source_accumulators_test.cc
google/cloud/testing_util/fake_source.h

With this change we use flow control for FakeSource, which required
changing the existing accumulator and SlowIota (another test source) to
also use flow control. This completes the API for the test sources.
Fixes #4339 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4346)

feat(source<T>): flow control for FakeSource 

---

google/cloud/storage/benchmarks/CMakeLists.txt
google/cloud/storage/benchmarks/storage_benchmarks.bzl
google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
google/cloud/storage/benchmarks/throughput_result.cc
google/cloud/storage/benchmarks/throughput_result.h
google/cloud/storage/benchmarks/throughput_result_test.cc

Move the struct used to represent throughput results to its own file.
Again, this is useful for testing, but I anticipate I will need to write
more throughput benchmarks (e.g. a benchmark that *only* downloads
objects).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4351)

refactor(storage/benchmark): throughput results

---

google/cloud/testing_util/fake_source.h

This was breaking only on Windows+CMake, which we do not build on PRs. I
tested the fix manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4353)

fix(source<T>): correct int vs. std::size_t mismatch

---

ci/kokoro/docker/Dockerfile.centos
ci/kokoro/docker/Dockerfile.fedora
ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
ci/kokoro/docker/Dockerfile.ubuntu

Fixes: https://github.com/googleapis/google-cloud-cpp/issues/4272
The reason for this PR is that often when we're debugging an issue it
may be easiest to reproduce in the docker container, and to debug it, we
may need to install some debugging tools. We need root access in order
to install this software, and this change gives us that ability. For
example:
```sh
bash-4.2$ su -
Password:
[root@b54ad8707594 ~]#
```
Note that I did not use sudo because sudo requires the invoking user's
UID to appear in /etc/passwd, but since we run our container with
effectively `--user=$(id -u):$(id -g)`, the UID does not appear in the
container's /etc/passwd file and so sudo doesn't work.
--- …

ci: enable su to root in docker containers

---

google/cloud/storage/benchmarks/CMakeLists.txt
google/cloud/storage/benchmarks/storage_benchmarks.bzl
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
google/cloud/storage/benchmarks/throughput_experiment.cc
google/cloud/storage/benchmarks/throughput_experiment.h

Refactor the code to upload and/or download objects to classes. This
will make these experiments reusable in other benchmarks, and will also
allow us to add new experiments, such as "download using raw gRPC
calls".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4357)

refactor(storage/benchmark): wrap upload/download in classes

---

ci/kokoro/windows/build-bazel.ps1
ci/kokoro/windows/build-quickstart-bazel.ps1

Reverts googleapis/google-cloud-cpp#4355
This breaks the non-presubmit windows/bazel builds.
https://source.cloud.google.com/results/invocations/6cc3d1b6-3c2e-46ad-bc8a-6f183a577c82/targets
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4361)

Revert "fix: don't preserve symlinks in 7z archive"

---

google/cloud/storage/benchmarks/BUILD
google/cloud/storage/benchmarks/CMakeLists.txt
google/cloud/storage/benchmarks/benchmark_utils.cc
google/cloud/storage/benchmarks/benchmark_utils.h
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
google/cloud/storage/benchmarks/throughput_download_task.cc
google/cloud/storage/benchmarks/throughput_download_task.h
google/cloud/storage/benchmarks/throughput_experiment.cc
google/cloud/storage/benchmarks/throughput_experiment_test.cc
google/cloud/storage/benchmarks/throughput_options.cc

Implement experiments to download using raw gRPC and raw libcurl calls,
to make it easier to compare the results with other teams and measure
the "overhead" of the library. As usual, this ignores that the client
library adds functionality, such as retries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4362)

feat(storage/benchmarks): compare to raw downloads

---

google/cloud/internal/format_time_point.cc
google/cloud/internal/format_time_point.h
google/cloud/spanner/testing/database_integration_test.cc
google/cloud/spanner/testing/random_database_name.cc
google/cloud/spanner/testing/random_database_name.h
google/cloud/spanner/testing/random_instance_name.cc

Our CI builds create randomly named databases (for isolation). Normally
these are cleaned up by the tests that create them, from time to time
these may crash or get interrupted and the cleanup does not happen. From
now on the instances are prefixed by the date (in `db-YYYY-MM-DD`
format). Any database with an ID matching that format and older than 48
hours is automatically removed.
This is part of the work for #4070 and fixes #4033 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4364)

ci(spanner): auto cleanup old databases

---

google/cloud/storage/tests/signed_url_conformance_test.cc

The versions for MSVC are complicated, this also goes by 19.26 and 14.26.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4365)

fix: warnings with MSVC 2019 16.6

---

google/cloud/bigtable/examples/data_async_snippets.cc
google/cloud/bigtable/examples/data_snippets.cc

The default for the Cloud Bigtable library is to only retry idempotent
operations. On the macOS builds we are getting a lot of transient errors,
and with the default policy these result in broken builds.
I changed the default policy in the examples, taking care to not make
this part of any example showing how to initialize the library.
I also changed some examples to use safer (idempotent) mutations, because
we should show how to use the service correctly.
Part of the work for #4119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4369)

ci(macos): less flaky bigtable examples

---

google/cloud/spanner/CMakeLists.txt
google/cloud/spanner/spanner_client_testing.bzl
google/cloud/spanner/spanner_client_unit_tests.bzl
google/cloud/spanner/testing/cleanup_stale_databases.cc
google/cloud/spanner/testing/cleanup_stale_databases.h
google/cloud/spanner/testing/cleanup_stale_databases_test.cc
google/cloud/spanner/testing/database_integration_test.cc
google/cloud/spanner/testing/random_database_name.cc
google/cloud/spanner/testing/random_database_name.h
google/cloud/spanner/testing/random_database_name_test.cc

This is mildly embarrassing. C++ regular expressions must match the full
string, and I forgot to skip the '/' when splitting the last component
in the database name.
This fixes #4070 and really fixes #4033
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4371)

ci(spanner): auto drop databases for realsies

---

google/cloud/storage/tests/error_injection_integration_test.cc

Change `ErrorInjectionIntegrationTest.InjectRecvErrorOnRead` to use a
`LimitedErrorCountRetryPolicy`.  The 500ms `LimitedTimeRetryPolicy`
used previously could be hit if the `CurlDownloadRequest::Read()` call
was delayed sufficiently in `CurlDownloadRequest::WaitForHandles()`.
Now we also expect that we see all the injected errors before the final
success.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4390)

fix: deflake test that was hitting a 500ms timeout

---

google/cloud/spanner/query_partition_test.cc
google/cloud/spanner/read_partition_test.cc
google/cloud/spanner/sql_statement_test.cc
google/cloud/storage/tests/error_injection_integration_test.cc

The former will emit the failing `Status`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4392)

cleanup: prefer ASSERT_STATUS_OK(v) over ASSERT_TRUE(v.ok())

---

.bazelci/presubmit.yml

Eventually we would want new versions of Bazel to be tested against our
code before going out, though naturally the Bazel folks would only look
at our builds as a signal once they are sufficiently stable.
Fixes #3898 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4398)

ci: add configuration for Bazel CI system

---

google/cloud/storage/internal/http_response.cc
google/cloud/storage/internal/http_response.h
google/cloud/storage/internal/http_response_test.cc

as per https://cloud.google.com/storage/docs/resumable-uploads#practices.
Fixes #4396.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4397)

fix(storage): handle 408 errors as retryable

---

google/cloud/storage/examples/storage_service_account_samples.cc

`storage_service_account_samples` should only delete the HMAC keys
that it creates, rather than everything for the service account,
otherwise it can interfere with other tests running in parallel,
notably `service_account_integration_test`.
We could also try to delete old keys, but it isn't worth it since
these tests are only run against the testbench emulator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4403)

fix: eliminate data race between storage "service account" tests

---

google/cloud/pubsub/config-version.cmake.in

GOOGLE_CLOUD_CPP_CLIENT_VERSION is not defined so it's replaced by an empty string and version config is invalid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4411)

fix: empty version in cmake package

---

.bazelrc
ci/kokoro/docker/build.sh

This build runs asan + ubsan, which are all safe to
run together. Once this build is enabled, we can delete the separate
asan and ubsan builds.
Related to https://github.com/googleapis/google-cloud-cpp/issues/4413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4414)

feat: add xsan build

---

.bazelrc

The `-fsanitize=undefined` linkopt and 128-bit multiplication don't
play well together when using libstdc++, producing in a link error:
```
error: undefined reference to '__muloti4'
```
So, use libc++ instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4416)

fix: force use of libc++ with bazel --config=ubsan

---

ci/etc/integration-tests-config.ps1
ci/etc/integration-tests-config.sh

We moved the builds to use a different account, I would like to disable
and eventually remove kokoro-agent@, it is an old account with too many
privileges (though all its keys are now removed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4421)

cleanup: remove references to kokoro-agent@ account

---

google/cloud/completion_queue_test.cc

Mocking a CompletionQueue is not as trivial as one might thing because
gRPC alarms are finicky. We have a good mock class, we needed to use it
in this test too.
Fixes #4423 
For the record, I ran the test 500,000 times without problems. Before this
change 10,000 times was enough to trigger the bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4427)

fix: test with correct MockCompletionQueue

---

google/cloud/internal/async_retry_unary_rpc_test.cc
google/cloud/internal/pagination_range_test.cc
google/cloud/log_test.cc

It is not necessary to `Invoke()` a lambda in the context of
`WillOnce()` or `WillRepeatedly()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4428)

cleanup: remove unnecessary calls to testing::Invoke()

---

google/cloud/bigtable/table_admin_test.cc
google/cloud/future_generic_test.cc
google/cloud/future_generic_then_test.cc
google/cloud/future_void_test.cc
google/cloud/future_void_then_test.cc
google/cloud/internal/async_retry_unary_rpc_test.cc
google/cloud/internal/background_threads_impl_test.cc
google/cloud/spanner/database_admin_client_test.cc
google/cloud/spanner/database_admin_connection_test.cc
google/cloud/spanner/instance_admin_connection_test.cc
google/cloud/testing_util/CMakeLists.txt
google/cloud/testing_util/google_cloud_cpp_testing.bzl
google/cloud/testing_util/scoped_thread.h

when using this pattern:
```
EXPECT_EQ(std::future_status::ready, waiter.wait_for(500_ms));
waiter.get();
```
If `wait_for` times out, the subsequent `get()` may wait indefinitely,
until the test times out (which can take a long time, 25 minutes has
been observed).  Use `ASSERT_EQ` in these situations instead to make
the test fail immediately.
Part of #4425
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4426)

test: do not wait on unsatisfied futures

---

google/cloud/storage/tests/object_checksum_integration_test.cc
google/cloud/storage/tests/object_hash_integration_test.cc

Some of the integration tests for storage look for specific log lines to
verify the right data is sent to the server. Typically only one such
line is present, but if the library retries two or more might appear. I
ran into this in one of my builds, but seems to be fairly rare.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4445)

fix(storage): accept more than one matching log line

---

ci/kokoro/windows/build-bazel.ps1
ci/kokoro/windows/build.ps1

We only have PRs with Windows+Bazel+Debug. Release builds are
sufficiently different in MSVC (e.g. the STL behaves completely
different) that it makes sense to setup a release builds too.
This would have detected the problems in #4425
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4447)

ci: prepare for Windows+Bazel+Release builds

---

google/cloud/completion_queue.cc
google/cloud/completion_queue.h
google/cloud/completion_queue_test.cc

Prior to this change we sometimes ran the callable passed to
`CompletionQueue::RunAsync()` in the calling thread and not
in the thread pool, which was hard to reason about.
As part of these changes I also fixed the code to support
move-only callables, and added a test for it.
The code is "future proofed" to support a `void()` callable.
Which is interesting for a number of reasons (think "executors").
Fixes #4083 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4448)

fix: CompletionQueue::RunAsync is always async

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4452)

feat: updated CHANGELOG for 2020-07 release

---

bazel/curl.BUILD

We have custom Bazel rules for libcurl, as the library does not support
Bazel. Our rules were definining CURL_MAX_WRITE_SIZE to 64KiB when
*compiling* libcurl, but used the default (16KiB) when *using* libcurl.
This macro defines the maximum buffer passed to the write callback, and
we use it in the storage library to size our buffers. You can now see
how this is a problem. Lucky for us, when running against production the
actual data received is around 1500 bytes (the MTU maybe?) so things
worked, but trying to run the tests against the emulator did not work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4461)

fix: libcurl Bazel rules

---

ci/kokoro/docker/Dockerfile.fedora
ci/kokoro/docker/Dockerfile.fedora-libcxx-msan

The sanitizers (I tested AddressSanitizer, but I hope all of them),
produce must more readable stack traces if the llvm-symbolizer is
installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4462)

ci: install llvm-symbolizer for *san builds

---

google/cloud/testing_util/example_driver.cc

If there is an error we want to log as much detail as we can to help
troubleshoot the problem, before this change we just get a "terminated"
without any details.
See some of the recently captured logs in #4255 for motivation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4453)

feat: log exceptions in example driver

---

google/cloud/bigtable/async_row_reader.h
google/cloud/completion_queue.h
google/cloud/completion_queue_test.cc

Support callables that take no arguments (not even a CompletionQueue),
this is already useful in some tests, AsyncRowReader, and I think will
be useful if completion queues will model an executor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4450)

feat: CompletionQueue::RunAsync with no arguments

---

ci/kokoro/install/Dockerfile.opensuse-leap
doc/packaging.md

At some point in the last few days the dependencies changed, and now
`zlib-devel` needs to be explicitly installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4466)

ci: fix openSUSE (Leap) install build

---

ci/kokoro/docker/Dockerfile.fedora
ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
ci/kokoro/docker/build-in-docker-bazel.sh
google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
google/cloud/storage/benchmarks/throughput_experiment_test.cc
google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
google/cloud/storage/examples/storage_bucket_acl_samples.cc
google/cloud/storage/examples/storage_bucket_cors_samples.cc
google/cloud/storage/examples/storage_bucket_default_kms_key_samples.cc
google/cloud/storage/examples/storage_bucket_iam_samples.cc
google/cloud/storage/examples/storage_bucket_requester_pays_samples.cc
google/cloud/storage/examples/storage_bucket_samples.cc
google/cloud/storage/examples/storage_default_object_acl_samples.cc
google/cloud/storage/examples/storage_event_based_hold_samples.cc
google/cloud/storage/examples/storage_lifecycle_management_samples.cc
google/cloud/storage/examples/storage_notification_samples.cc
google/cloud/storage/examples/storage_object_acl_samples.cc
google/cloud/storage/examples/storage_object_cmek_samples.cc
google/cloud/storage/examples/storage_object_samples.cc
google/cloud/storage/examples/storage_object_versioning_samples.cc
google/cloud/storage/examples/storage_policy_doc_samples.cc
google/cloud/storage/examples/storage_retention_policy_samples.cc
google/cloud/storage/examples/storage_website_samples.cc
google/cloud/storage/testing/storage_integration_test.cc
google/cloud/storage/testing/storage_integration_test.h
google/cloud/storage/tests/bucket_integration_test.cc
google/cloud/storage/tests/grpc_integration_test.cc
google/cloud/storage/tests/thread_integration_test.cc
google/cloud/storage/tools/run_testbench_utils.sh

A single project (and we use a single project in our CI builds) can make
at most one CreateBucket or DeleteBucket request every 2 seconds. While
we have taken measures to minimize the number of times we touch
production (e.g. the CMake builds use the testbench, the Bazel builds
cache tests), sometimes there are enough CI builds hitting production
that we exceed this limit.
In this PR we take some additional measures to reduce the problems:
- The ci/kokoro/docker builds based on Bazel now use the GCS emulator
(aka testbench) for most tests (a few tests must use production, but
they do not create buckets AFAIK). This leaves the macOS and Windows
builds running against production.
- Any loops that create buckets with different configurations now pause
before each iteration. I do not think …

test: reduce flakiness in CreateBucket/DeleteBucket

---

google/cloud/internal/background_threads_impl_test.cc

Before this PR the tests would (a) pass without problems when not under
load, (b) when under load (a second build running simultaneously) it
would fail about 80 times out of 10,000. After this change the test
passed 20,000 times under load and another 20,000 times without load.
The worst case running time is about 11 seconds, which suggests to me
the shorter 500ms timeouts are not a good tradeoff as they cost some
flakiness in our builds.
Fixes #4469 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4470)

test: deflake background_threads_impl_test

---

ci/kokoro/docker/Dockerfile.ubuntu
ci/kokoro/docker/build.sh
google/cloud/storage/tools/run_testbench_utils.sh

The Ubuntu-based builds cannot start the storage testbench. This
seems to be a recent problem, as this worked on my workstation
with a cached Docker image, but failed when building the Docker
image from scratch. There are only a handful on Ubuntu-based
builds, and only `integration` and `integration-nightly` actually
use the testbench.
Added some additional logging to diagnose this problem, left it on
because it might help in the future.
This fixes #4471 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4472)

ci: fix storage testbench on ubuntu-based builds

---

google/cloud/completion_queue_test.cc

Very rarely this test would fail because the 20ms timer expired before
the very next line could run (scheduling is hard). Fixed the test by (a)
making the timer 500ms, and (b) put a loop to create a new timer if the
first few expired.
In a few cases this would be testing "nothing" as the timer could expire
before the completion queue really is shutdown, but that (rare) false
positive is better (I think) than rare false negatives.
Fixes #4384 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4474)

test: deflake CompletionQueueTest.ShutdownWithPending

---

cmake/GoogleCloudCppCommon.cmake

Reuse the documentation of the first member of a group for the other
members of the group. This makes it easy to duplicate documentation
for closely related functions without a slew of `@copydoc` commands.
https://www.doxygen.nl/manual/config.html#cfg_distribute_group_doc
Also, mention the sub-project in the "Generate HTML" message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4481)

doc: enable doxygen DISTRIBUTE_GROUP_DOC

---

google/cloud/bigtable/tests/data_async_future_integration_test.cc
google/cloud/spanner/client_test.cc
google/cloud/spanner/results_test.cc
google/cloud/spanner/value_test.cc
google/cloud/storage/internal/grpc_resumable_upload_session_test.cc
google/cloud/storage/internal/hmac_key_requests_test.cc
google/cloud/storage/tests/error_injection_integration_test.cc

just a small cleanup I noticed while working on another PR
I also found a couple cases that redundantly did both
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4485)

refactor: replace `EXPECT_TRUE(status.ok())` with `EXPECT_STATUS_OK()`

---

google/cloud/storage/BUILD
google/cloud/storage/internal/curl_request.cc
google/cloud/storage/internal/curl_request.h
google/cloud/storage/tests/BUILD
google/cloud/storage/tests/CMakeLists.txt
google/cloud/storage/tests/curl_request_integration_test.cc

Add a function to make HTTP requests gathering data from multiple
buffers. I expect to use this function in reducing the amount of data
copying during uploads, using (when possible) the buffer provided by the
application without any additional copying.
Part of the work for #2664
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4480)

feat(storage): HTTP requests with many buffers

---

google/cloud/storage/client.cc

Unfortunately our PR builds for Windows are based on Bazel which defines
`NOMINMAX` which hides these problems, and I missed them in my review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4490)

fix: workaround min/max macros on Windows

---

google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/internal/grpc_client.h
google/cloud/storage/internal/grpc_resumable_upload_session.cc
google/cloud/storage/internal/grpc_resumable_upload_session.h
google/cloud/storage/internal/grpc_resumable_upload_session_test.cc

The streaming uploads have a number of restrictions on message sizes,
chunk quantums, and final message flags. This refactors the code to keep
all this complexity in one place. It also dtakes advantage of the
`google.storage.v1.ServiceConstants` proto which did not exist or I
missed when we originally implemented this code. The code has more
conditional code now, but does not create more data copies than before.
Unfortunately a copy is more or less unavoidable because protos need to
own the payload and we cannot move it (both because we might need it on
a retry and because it is received as a `std::string const&`).
This will make other changes for #2664 much easier.
--- …

refactor(GCS+gRPC): simplify resumable upload code

---

google/cloud/storage/CMakeLists.txt
google/cloud/storage/client.h
google/cloud/storage/internal/curl_request.cc
google/cloud/storage/internal/object_streambuf.cc
google/cloud/storage/internal/object_streambuf.h
google/cloud/storage/internal/object_streambuf_test.cc
google/cloud/storage/internal/resumable_upload_session.cc
google/cloud/storage/testbench/gcs_bucket.py

With this change it is possible to avoid all copies of upload data until
the libcurl/openssl layer (at which point a copy is unavoidable). We say
"possible" because there are cases where some amount of data copies are
necessary (more on these later).
Some background first: resumable uploads in GCS work by uploading
"chunks". The size of these chunks (except the last one) must be
multiples of the upload quantum (256KiB). Uploading a chunk that is not
a multiple of the quantum implicitly finalizes the upload.
This means that any data smaller than a quantum *must* be buffered.
Applications should consider always providing buffers that are a
multiple of the quantum to avoid such buffering.
With that said, many applications upload data by calling
`std::ostream::write()` repeatedly, as long as …

feat(storage): reduce data copies in uploads

---

google/cloud/storage/internal/object_streambuf.cc
google/cloud/storage/internal/object_streambuf_test.cc

When closing a stream we need to send a chunk to finalize the upload. If
there was more than one upload quantum in the put area we first flushed
that data with one chunk, and then sent the finalization chunk, with
many zero bytes. It is more efficient to avoid the flush and send a
single finalization chunk.
Fixes #4499
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4504)

fix: avoid unnecessary chunk to finalize uploads

---

ci/kokoro/cache-functions.sh
ci/kokoro/macos/build.sh

The last few failures for #3645 the build timed out because uploading or downloading the cache made no progress in 3600s.  With this change the upload and/or download of the cache may timeout, but that would not break the build because they run with a `|| true` at the end.
Whether the overall build will still timeout for other reason, or the 20 minutes consumed by the cache upload/download timeout proves too much, that remains to be seen. In any case, I believe this would help, if nothing else, it would give us more information as something else would fail.
Part of the work for #3645 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4505)

ci: deflake macOS cache updates

---

google/cloud/storage/internal/curl_client.cc
google/cloud/storage/internal/curl_request.cc
google/cloud/storage/testbench/gcs_bucket.py
google/cloud/storage/tests/object_resumable_write_integration_test.cc

In some (we think relatively rare) cases we were using chunked
transfer encoding, which wastes bandwidth when the size of the transfer
is known (as it is in our case).
The problem only manifested itself when an upload stream had some data
in its buffers and the application provided a large enough call in
`.write()` to fill an upload chunk.
This change adds some metadata in the testbench to detect the transfer
encodings used for an upload, that seems better than examining the log
of the upload.
Fixes #4498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4506)

fix(storage): avoid chunked transfer encoding

---

ci/kokoro/macos/build.sh

By default Kokoro uploads the data from KOKORO_ARTIFACTS_DIR after
the build script exits. That can be a substantial amount of data, and
we do not use it. It is faster to just remove it.
Part of the work for #4507
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4508)

ci(macos): remove unused artifacts before exit

---

ci/kokoro/windows/build-cmake.ps1
google/cloud/bigtable/internal/bulk_mutator.cc
google/cloud/spanner/benchmarks/benchmarks_config.cc
google/cloud/spanner/benchmarks/benchmarks_config.h
google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
google/cloud/spanner/internal/time_format.cc
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc

Remove any remaining warnings under Windows+MSVC+x86, now the examples,
tests and benchmarks compile cleanly in 32-bit mode. I think we are
actually using the correct types, not just silencing warnings with
`static_cast<>` too.
To enable `/WX` (treat warnings as errors) I had to disable warnings
around an Abseil include, there is a TODO for a better fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4515)

fix: warnings under Windows+MSVC+x86

---

google/cloud/bigtable/internal/bulk_mutator.cc

Ironically I broke the 64-bit builds when fixing the 32-bit builds for
Windows. Tested both this time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4523)

fix: builds on 64-bit Windows

---

ci/kokoro/cache-functions.sh
ci/kokoro/docker/build.sh
ci/kokoro/macos/build.sh

Don't do any slicing or parallel uploads, the crcmod installed on the
Kokoro machines is too slow to support objects with multiple components.
Fixes #4524 but may need a full PR -> Full Build -> PR cycle before it has
any effect.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4526)

ci: restore bazel caching for *san builds

---

ci/generate-markdown/generate-bigtable-readme.sh
google/cloud/bigtable/README.md
google/cloud/bigtable/quickstart/quickstart.cc

Thanks to @cshaff0524 for the original PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4525)

doc(bigtable): restore quickstart's region tags

---

ci/kokoro/windows/cmake-release-x86.cfg

No presubmit build because CMake builds on Windows simply take too long.
A separate internal will enable this build on Kokoro.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4530)

ci: configure a Windows+MSVC+x86 build

---

ci/kokoro/windows/build.ps1

At the end of the Windows build we cleanup the artifacts directory, and
accidentally remove the build script itself in that process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4533)

ci: do not remove build script on cleanup

---

google/cloud/pubsub/BUILD
google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc
google/cloud/pubsub/internal/emulator_overrides.cc
google/cloud/pubsub/internal/emulator_overrides.h
google/cloud/pubsub/internal/emulator_overrides_test.cc
google/cloud/pubsub/internal/publisher_stub.cc
google/cloud/pubsub/internal/publisher_stub.h
google/cloud/pubsub/internal/subscriber_stub.cc
google/cloud/pubsub/internal/subscriber_stub.h
google/cloud/pubsub/pubsub_client.bzl
google/cloud/pubsub/pubsub_client_unit_tests.bzl

The `PUBSUB_EMULATOR_HOST` environment variable can be used to override
any default or application-defined endpoint in the *Connection objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4529)

feat(pubsub): use emulator environment variable

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/subscription.h
google/cloud/pubsub/topic.h

There are restrictions on the size of a topic and/or subscription id. I
included links to them from the `pubsub::Topic` and
`pubsub::Subscription` class. Also fixed the inline namespace to be the
"Right Thing"[tm].
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4535)

doc(pubsub): link the resource name restrictions

---

ci/kokoro/docker/build-in-docker-cmake.sh
google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh

#4536 will remind us to restore them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4537)

ci(GCS+gRPC): temporarily disable integration tests

---

ci/install-cloud-sdk.sh
ci/kokoro/docker/Dockerfile.centos
ci/kokoro/docker/Dockerfile.fedora
ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
ci/kokoro/docker/Dockerfile.ubuntu
ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build-in-docker-cmake.sh
google/cloud/pubsub/ci/lib/pubsub_emulator.sh
google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh
google/cloud/pubsub/ci/run_integration_tests_emulator_cmake.sh

To do this we need to install the Java runtime environment in the images
that run integration tests, so there are downsides to this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4534)

ci(pubsub): use emulator for integration tests

---

google/cloud/pubsub/integration_tests/CMakeLists.txt
google/cloud/pubsub/integration_tests/message_integration_test.cc
google/cloud/pubsub/integration_tests/pubsub_client_integration_tests.bzl
google/cloud/pubsub/internal/publisher_stub.cc
google/cloud/pubsub/internal/publisher_stub.h
google/cloud/pubsub/internal/subscriber_stub.cc
google/cloud/pubsub/internal/subscriber_stub.h

Implement the blocking, synchronous, non-streaming RPCs to publish and
pull messages. That will let us implement skeletons for
`pubsub::Publisher` and `pubsub::Subscriber`.
Part of the work for #3895 and #3896 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4538)

feat(pubsub): skeleton stubs to push/pull messages

---

google/cloud/pubsub/CMakeLists.txt

Exclude anything in the `pubsub_internal`, `pubsub_testing`, and/or
`internal` namespaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4547)

doc(pubsub): exclude non-public namespaces

---

google/cloud/pubsub/integration_tests/CMakeLists.txt

The labels in these tests always force running against production, fixed
now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4551)

ci(pubsub): really disable tests against production

---

google/cloud/spanner/client.cc
google/cloud/spanner/client_test.cc
google/cloud/spanner/internal/connection_impl.cc
google/cloud/spanner/internal/connection_impl.h
google/cloud/spanner/internal/connection_impl_test.cc
google/cloud/spanner/internal/transaction_impl.h
google/cloud/spanner/internal/transaction_impl_test.cc
google/cloud/spanner/row.cc
google/cloud/spanner/testing/matchers.h
google/cloud/spanner/transaction_test.cc

Change the signature of the transaction `Visit()` functor to take a
`StatusOr<TransactionSelector>&` instead of a `TransactionSelector&`.
This allows a functor that failed to allocate a transaction ID to
move the transaction into an error state (with a `Status`) instead
of leaving it as a "begin", for the use of future visitors like
`Commit()`.
Only `ConnectionImpl::CommitImpl()` and `RollbackImpl()` have been
modified to check for the error state.  Every other `ConnectionImpl`
transaction visitor currently assumes there is no error (which is OK
as no one currently imposes one).
Part of #4516.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4545)

feat: support moving a Transaction into an error state

---

google/cloud/bigtable/table_admin.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4601)

doc: remove not GA warning from bigtable backup methods

---

google/cloud/pubsub/internal/publisher_stub.cc
google/cloud/pubsub/internal/publisher_stub.h
google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection.h
google/cloud/pubsub/publisher_connection_test.cc
google/cloud/pubsub/testing/mock_publisher_stub.h

Change `pubsub_internal::PublisherStub` to use an asynchronous RPC for
`Publish()`, adjust the unit tests to use the new functions. Change the
default `pubsub::PublisherConnection` to use the configuration in
`pubsub::ConnectionOptions` to either use a completion queue provided by
the application (which must be serviced by one or more threads also provided
by the application), or to create its own completion queue and a (at the moment)
single background thread.
Fixes #4604
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4608)

feat(pubsub): use asynchronous RPC for Publish

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/integration_tests/message_integration_test.cc
google/cloud/pubsub/mocks/mock_subscriber_connection.h
google/cloud/pubsub/pubsub_client.bzl
google/cloud/pubsub/pubsub_client_mocks.bzl
google/cloud/pubsub/pubsub_client_unit_tests.bzl
google/cloud/pubsub/subscriber.h
google/cloud/pubsub/subscriber_test.cc

This PR implements a skeleton `Subscriber` class, with
enough functionality to be usable, but a fairly naive
implementation.
We also introduce a mock for `SubscriberConnection` and
a simple unit tests showing how to use it.
Fixes #4607 and fixes #3895
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4610)

feat(pubsub): a skeleton pubsub::Subscriber class

---

google/cloud/spanner/value.cc

Zero padding of years should be after the sign, not before it.
This broke a Spanner emulator test that expects `CivilDay(0, 0, 0)`
to produce `kInvalidArgument` on "-001-11-30" because the year is
less than 1, not `kFailedPrecondition` on "00-1-11-30" because the
string is syntactically illegal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4614)

fix(spanner): date formatting with negative years

---

google/cloud/pubsub/message.h
google/cloud/pubsub/message_test.cc

`google.pubsub.v1.PubsubMessage.data` is a "bytes" field, where
we want to accommodate a protobuf mapping to a type other than
`std::string`.  `google::cloud::pubsub::PubsubMessageDataType`
is an alias for that "bytes" type, for use in Google projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4613)

fix(pubsub): accommodate protobuf fields of type `bytes`

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/internal/default_ack_handler_impl.cc
google/cloud/pubsub/internal/default_ack_handler_impl.h
google/cloud/pubsub/internal/default_ack_handler_impl_test.cc
google/cloud/pubsub/pubsub_client.bzl
google/cloud/pubsub/pubsub_client_unit_tests.bzl
google/cloud/pubsub/subscriber_connection.cc

Move `pubsub_internal::DefaultAckHandlerImpl` to its own file, this is a
bit of an overkill right now. I am about to add more functionality,
which would be easier to test with this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4619)

refactor(pubsub): move default AckHandler

---

google/cloud/bigquery/read_result.h
google/cloud/bigquery/row_set.h
google/cloud/bigtable/async_row_reader.h
google/cloud/bigtable/row_reader.h
google/cloud/spanner/client.h
google/cloud/spanner/connection.h
google/cloud/spanner/iam_updater.h
google/cloud/spanner/partition_options.h
google/cloud/spanner/query_options.h
google/cloud/spanner/results.h
google/cloud/spanner/value.h
google/cloud/storage/bucket_metadata.h
google/cloud/storage/lifecycle_rule.h
google/cloud/storage/oauth2/google_credentials.h
google/cloud/storage/oauth2/service_account_credentials.h
google/cloud/storage/object_metadata.h
google/cloud/storage/well_known_headers.h
google/cloud/storage/well_known_parameters.h

Keep including `google/cloud/optional.h` and `google/cloud/spanner/date.h`
in our exported headers, even though the library does not need them. This
gives users who rely on transitive inclusion a chance to update references
from `google::cloud::optional` and `google::cloud::spanner::Date`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4621)

cleanup: restore inclusion of backwards-compatibility headers

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/integration_tests/message_integration_test.cc
google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/batching_publisher_connection.h
google/cloud/pubsub/internal/batching_publisher_connection_test.cc
google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection.h
google/cloud/pubsub/publisher_connection_test.cc
google/cloud/pubsub/pubsub_client.bzl
google/cloud/pubsub/pubsub_client_unit_tests.bzl

With this PR messages are batched in the `PublisherConnection()` layer
before making a `AsyncPublish()` call.  The application can request that
messages are flushed based on message count, total data size, or time.
Each future returned by `Publish()` is satisfied as its own work item in
the completion queue, effectively this means the messages are sent in
order, but the responses are handled in an unspecified order.
Part of the work for #4581 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4616)

feat(pubsub): batch messages in Publish()

---

google/cloud/pubsub/integration_tests/message_integration_test.cc
google/cloud/pubsub/internal/default_ack_handler_impl.cc
google/cloud/pubsub/internal/default_ack_handler_impl_test.cc
google/cloud/pubsub/internal/subscriber_stub.cc
google/cloud/pubsub/internal/subscriber_stub.h
google/cloud/pubsub/testing/mock_subscriber_stub.h

With this PR applications can NACK a message early, allowing other
subscribers to handle the same message. Changed the integration test to
exercise this path.
Fixes #4553 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4641)

feat(pubsub): implement AckHandler::nack

---

google/cloud/pubsub/samples/pubsub_samples_common.cc
google/cloud/pubsub/samples/pubsub_samples_common.h
google/cloud/pubsub/samples/pubsub_samples_common_test.cc
google/cloud/pubsub/samples/samples.cc

Some of the helper functions needed better names after the `Publisher`
-> `TopicAdminClient` renaming. And I need the current names to start
writing publisher and subscription examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4643)

cleanup(pubsub): use better naming in samples

---

google/cloud/pubsub/internal/batching_publisher_connection.cc

Another case of `sizeof(int)` < `sizeof(std::size_t)` and protobuf using
`int` to index its vector-like things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4663)

fix(pubsub): code now builds with MSVC 2019

---

google/cloud/pubsub/subscriber_connection.cc
google/cloud/pubsub/subscriber_connection.h
google/cloud/pubsub/subscriber_connection_test.cc

With this change there are no magic threads to run each subscriber.
Instead the work is executed in the background threads. To avoid
blocking for a long time while handling a large response the code the
library uses a different RunAsync() to execute each callback. For now
these are sequenced to work well with ordering keys. A future change
will allow applications to choose out of order execution.
Fixes #4555
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4653)

feat(pubsub): use CQ to run subscription callbacks

---

google/cloud/pubsub/internal/batching_publisher_connection.h
google/cloud/pubsub/internal/batching_publisher_connection_test.cc
google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection.h
google/cloud/pubsub/publisher_connection_test.cc

I shall write 100 times on the blackboard: "Cannot have crazy cycles in
thread ownership or you shall suffer evil deadlocks at shutdown".
FWIW, the test used to crash about 1 in 1000 times before, the same
test ran 100,000 times successfully after this change.
Fixes #4672
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4675)

fix(pubsub): correct ownership of background threads

---

google/cloud/pubsub/samples/pubsub_samples_common.cc
google/cloud/pubsub/samples/pubsub_samples_common.h
google/cloud/pubsub/samples/pubsub_samples_common_test.cc
google/cloud/pubsub/samples/samples.cc

`pubsub_publish` is the basic sample showing how to publish a message.
While `pubsub_subscriber_async_pull` shows how to receive messages.
Fixes #4662 and fixes #4660
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4664)

feat(pubsub): implement basic data samples

---

ci/kokoro/docker/build-in-docker-cmake.sh
ci/kokoro/windows/build-bazel.ps1
google/cloud/bigtable/examples/opencensus/bigtable_opencensus.cc
google/cloud/storage/internal/grpc_client.cc

Use `--per_file_copt` (TIL: thanks @devjgm) to enable warnings-as-errors
(aka `/WX`) on the Windows+MSVC+Bazel builds. We already use these flags
in the Windows+MSVC+CMake builds, but those do not run on PRs and
missed a couple of files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4676)

ci: enable warnings-as-errors for Windows+MSVC+Bazel

---

google/cloud/spanner/client.cc
google/cloud/spanner/client_test.cc
google/cloud/spanner/internal/connection_impl.cc
google/cloud/spanner/internal/connection_impl.h
google/cloud/spanner/internal/connection_impl_test.cc
google/cloud/spanner/internal/transaction_impl.h
google/cloud/spanner/internal/transaction_impl_test.cc
google/cloud/spanner/testing/matchers.h
google/cloud/spanner/transaction_test.cc

after further discussion, @devbww and I reversed the decision in #4545
to use `optional` to mark a `Transaction` invalid, and instead we will
store and propagate the `Status` of the failed `BeginTransaction`.
we also discussed how `Rollback` should function in various failure
scenarios, and I did some testing making manual RPCs to spanner.
When `Rollback` is called with an invalid `Transaction` it now
propagates the `Status` instead of returning `OK`. I also left a TODO
to change the behavior in the `has_begin` case to better match backend
behavior.
part of #4516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4670)

feat: store a Status when invalidating Transactions

---

ci/kokoro/docker/build.sh

It looks like since our check-style.sh script now uses `git ls-files`
we probably don't need to mount the cmake-build-debug/ directory, which
CLion uses by default. The only downside is that this directory is
created in everyone's repo dir (even if they don't use clion) as a dir
owned by root. So if we don't need it, and our CLion users' workflows
still work, it seems good to get rid of.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4679)

chore: remove no-longer-needed docker mount

---

google/cloud/spanner/internal/connection_impl.cc
google/cloud/spanner/internal/connection_impl_test.cc

this is a no-op because nothing yet sets a transaction invalid (aside
from the test).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4606)

feat: handle invalid transactions in `ConnectionImpl` methods

---

ci/kokoro/windows/build-cmake-dependencies.ps1

The current (as of 2020-07-24) version of vcpkg is not able to build our
dependencies. Pinning to the previous version seems to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4681)

ci: pin vcpkg version to workaround build problems

---

google/cloud/storage/well_known_headers.h

This is just a cleanup, the function does not need to be `static`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4684)

cleanup: template function unnecessarily static

---

google/cloud/bigtable/testing/embedded_server_test_fixture.h

Since there was at least one undefined function (see #4674) I decided to go looking for any others. This is all I found with the exception of functions intentionally undefined in some template meta programming crazy sauce.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4685)

cleanup: remove unused+undefined function

---

google/cloud/pubsub/internal/default_ack_handler_impl.cc
google/cloud/pubsub/internal/default_ack_handler_impl.h
google/cloud/pubsub/internal/default_ack_handler_impl_test.cc
google/cloud/pubsub/internal/subscriber_stub.cc
google/cloud/pubsub/internal/subscriber_stub.h
google/cloud/pubsub/subscriber_connection.cc
google/cloud/pubsub/subscriber_connection_test.cc
google/cloud/pubsub/testing/mock_subscriber_stub.h

With this change we use `AsyncPull()` to pull messages, and
`AsyncAcknowledgement()` and `AsyncModifyAckDeadline()` to ACK and NACK
the messages.
Fixes #4554
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4687)

feat(pubsub): use async RPCs for subscribers

---

ci/kokoro/windows/build-cmake-dependencies.ps1

While normally we do not care about the time for a full build (as
opposed to PRs) in this case I think we should: we have limited
bandwidth for Windows builds, and these are taking between 1 and 2
hours.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4697)

ci: speed up full builds for Windows+CMake

---

google/cloud/spanner/internal/connection_impl.cc
google/cloud/spanner/internal/connection_impl.h
google/cloud/spanner/internal/connection_impl_test.cc

No functional change. We were doing this in 2 places and there will soon
be additional cases where it is needed.
This is an alternative to #4605.  I think this is a more idiomatic and
simpler signature for `BeginTransaction` at the cost of a little more
boilerplate at the call sites. My main concern isn't the amount of
boilerplate (it's only a couple lines) but the fact that omitting it at
any site may lead to subtle problems that wouldn't be possible in #4605
where `BeginTransaction` modifies the TransactionSelector directly.
Part of #4516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4624)

refactor: refactor `BeginTransaction` to its own private method

---

ci/kokoro/windows/build-bazel.ps1
ci/kokoro/windows/build-cmake-dependencies.ps1
ci/kokoro/windows/build.ps1

We are informed that the problems in #4363 might be caused
by the CI machine running out of space in the boot partition.
This change aims to reduce the chances of that happening,
and to improve our ability to troubleshoot for that case.
Remove temporary files after they are no longer used, for
example, when refreshing the `vcpkg` cache we may need to
create all the `.o` files for the dependencies, but once these
are installed the `.o` files are no longer needed. Likewise, the
tarball for the Bazel cache is not needed after it is extracted.
Add some logging to report how much disk space is left before
and after some of the steps that consume significant disk.
---- …

ci: reduce root disk usage on Windows

---

google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/batching_publisher_connection.h
google/cloud/pubsub/internal/batching_publisher_connection_test.cc
google/cloud/pubsub/mocks/mock_publisher_connection.h
google/cloud/pubsub/publisher.h
google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection.h
google/cloud/pubsub/publisher_test.cc

This function allows applications to flush any messages sitting in the
`pubsub::PublisherConnection` buffers.
Part of the work for #4581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4654)

feat(pubsub): implement Publisher::Flush()

---

google/cloud/spanner/internal/connection_impl_test.cc
google/cloud/testing_util/CMakeLists.txt
google/cloud/testing_util/google_cloud_cpp_testing.bzl
google/cloud/testing_util/google_cloud_cpp_testing_unit_tests.bzl
google/cloud/testing_util/status_matchers.h
google/cloud/testing_util/status_matchers_test.cc

I replaced the `StatusContains` matcher I recently introduced with this.
It would be nice to do a LSC, not sure how easy it would be to automate.
There also might be an opportunity to consolidate assert_ok.
Part of #4693
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4694)

test: add StatusIs and IsOk matchers

---

google/cloud/spanner/CMakeLists.txt
google/cloud/spanner/client_test.cc
google/cloud/spanner/database_admin_client_test.cc
google/cloud/spanner/database_admin_connection_test.cc
google/cloud/spanner/instance_admin_connection_test.cc
google/cloud/spanner/integration_tests/BUILD
google/cloud/spanner/integration_tests/CMakeLists.txt
google/cloud/spanner/integration_tests/database_admin_integration_test.cc
google/cloud/spanner/internal/connection_impl_test.cc
google/cloud/spanner/internal/merge_chunk_test.cc
google/cloud/spanner/internal/partial_result_set_resume_test.cc
google/cloud/spanner/internal/partial_result_set_source_test.cc
google/cloud/spanner/keys_test.cc
google/cloud/spanner/mutations_test.cc
google/cloud/spanner/read_partition_test.cc
google/cloud/spanner/results_test.cc
google/cloud/spanner/sql_statement_test.cc
google/cloud/spanner/testing/matchers.h
google/cloud/spanner/value_test.cc

Spanner had its own (identical) implementation - eliminate it and update
all references.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4695)

test: use the "common" `IsProtoEqual` in spanner

---

ci/kokoro/docker/check-abi.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4702)

ci: ignore internal symbols in ABI checker

---

ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build.sh

Punch a hole in the docker and bazel environments wide enough to
override the default Spanner endpoint.
Fixes #4459.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4704)

test: enable running integration tests against a staging server

---

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
google/cloud/spanner/client.cc
google/cloud/spanner/integration_tests/session_pool_integration_test.cc
google/cloud/spanner/internal/metadata_spanner_stub.cc
google/cloud/spanner/internal/metadata_spanner_stub.h
google/cloud/spanner/internal/metadata_spanner_stub_test.cc
google/cloud/spanner/internal/spanner_stub.cc
google/cloud/spanner/internal/spanner_stub.h
google/cloud/spanner/internal/spanner_stub_test.cc
google/cloud/spanner/testing/validate_metadata.cc
google/cloud/spanner/testing/validate_metadata.h

Fixes: #4546
This PR gives the `MetadataSpannerStub` knowledge of the full database
resource name, which it then adds as a metadata (aka, a "header") using
the name "google-cloud-resource-prefix" to the `grpc::ClientContext` for
all non-admin calls. Admin operations will not use this header, though
they may in a future PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4703)

feat: add google-cloud-resource-prefix to non-admin operations

---

google/cloud/pubsub/ack_handler.cc
google/cloud/pubsub/ack_handler.h
google/cloud/pubsub/ack_handler_test.cc

The application may fail to nack or ack a message in the subscription
handler. In this case the library will automatically nack the message.
Fixes #4709
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4710)

feat(pubsub): automatically nack messages

---

ci/kokoro/docker/build-in-docker-cmake.sh
ci/kokoro/docker/check-abi.sh

The "check-abi" part of the build was done sequentially taking ~7
minutes on my machine. After this change it takes about 2.5 minutes.
I also changed the "update-abi" build to only update the expected ABI
files and skip the compliance check. The rationale for this change is
because if the user is asking to update the expected ABI is probably
because a previous "check-abi" run failed and that's how they know they
need to update the ABI.
One final small change is that the names in the report are changed from
"reference" and "current" to "expected" and "actual", which matches the
file names better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4712)

ci: parallelize check-abi build steps

---

google/cloud/pubsub/integration_tests/message_integration_test.cc
google/cloud/pubsub/internal/subscription_session.cc
google/cloud/pubsub/internal/subscription_session.h
google/cloud/pubsub/internal/subscription_session_test.cc
google/cloud/pubsub/samples/samples.cc

So far we have been using the return from the subscription handler to
schedule the next event. This is not correct if we want to limit the
number of messages being handled and support handlers that use some kind
of thread pool.
This is part of the work for #4583 but just because it makes testing easier.
I believe it will also help with #4645 but that remains to be seen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4711)

feat(pubsub): sequence message handle on ack/nack

---

google/cloud/storage/client.h
google/cloud/storage/internal/curl_client.cc
google/cloud/storage/internal/curl_client_test.cc
google/cloud/storage/internal/object_requests.cc
google/cloud/storage/internal/object_requests.h
google/cloud/storage/internal/object_requests_test.cc
google/cloud/storage/testbench/testbench.py
google/cloud/storage/tests/object_integration_test.cc

This PR is a part of #4404 
It seems that it is impossible to implement a test for this function.
- I dont know how to get the `upload_id` from `Object: insert`
- I dont know how to send a signal to interrupt a resumable upload so we can delete that resumable upload.
I think we should implement a function to return the `upload_id` to user. With that function we could actually resume a resumable upload ( if there is an interruption ) and write test for `DeleteResumableUpload`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4696)

feat(storage): add a function to delete resumable upload in client

---

google/cloud/pubsub/internal/subscription_session_test.cc

There was a flake (5/1000 runs) in the test code.
Fixes #4716
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4717)

test(pubsub): deflake SubscriptionSession test

---

google/cloud/pubsub/internal/batching_publisher_connection_test.cc
google/cloud/pubsub/internal/ordering_key_publisher_connection_test.cc

A `bytes` field may not be a `std::string` in some environments,
but it is convertible to one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4720)

test(pubsub): accommodate protobuf fields of type `bytes`

---

google/cloud/spanner/internal/connection_impl.cc
google/cloud/spanner/internal/connection_impl_test.cc

The test cases were not checking the transaction state on the
`StreamingRead` operations, so they missed this. Confirmed the new test
fails without the code change and passes with it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4722)

fix: use the updated transaction id in `ReadImpl`

---

cmake/FindgRPC.cmake

This problem is explained in #4146, this PR silences the warning
generated by an indirect find_package(absl) through find_package(gRPC)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4725)

clean: silence CMake warning from Abseil configs

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/internal/subscription_session.cc
google/cloud/pubsub/internal/subscription_session.h
google/cloud/pubsub/internal/subscription_session_test.cc
google/cloud/pubsub/pubsub_client.bzl
google/cloud/pubsub/subscriber_connection.h
google/cloud/pubsub/subscriber_connection_test.cc
google/cloud/pubsub/subscription_options.h

Automatically update the Ack deadline for all the events still being
processed (that is, those where the application has neither called
`ack()` nor `nack()`). The application can set a maximum ACK deadline
when the subscription is created, and this applies to the full batch of
messages received by the application even if the messages are
serialized. This is consitent with the golang implementation.
Several tests have different expectations because we avoid sending an
initial `AsyncModifyAckDeadline()` RPC until needed. We expect many
applications to process messages in the initial 10 seconds, so saving
the call seems worthwhile.
Fixes #4583
--- …

feat(pubsub): auto refresh ack deadline

---

google/cloud/spanner/internal/connection_impl.cc
google/cloud/spanner/internal/connection_impl_test.cc

I added a test and verifies it fails in the way we saw the emulator
tests fail without the code change:
```
[ RUN      ] ConnectionImplTest.ExecuteBatchDmlNoResultSets
google/cloud/spanner/internal/connection_impl_test.cc:1350: Failure
Value of: result
Expected: is OK
Actual: Begin transaction requested but no transaction returned (in ExecuteBatchDmlImpl). [INTERNAL]
```
Fixes #4723
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4724)

fix: handle `ExecuteBatchDml` returning OK with no results

---

google/cloud/pubsub/subscription_options.h

Thanks to @devbww for noticing this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4730)

cleanup(pubsub): remove redundant duration_cast<>

---

google/cloud/pubsub/publisher.h
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscriber.h

Show how to setup a custom thread pool for `pubsub::Publisher` and
`pubsub::Subscriber`.
Fixes #4586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4726)

doc(pubsub): a custom thread pool example

---

ci/kokoro/windows/build-cmake.ps1

Our builds are failing because one executable is reportedly created by
the CMake step, but the executable is no longer present by the time we
get to the CTest step.  Creating the executable first with CMake, and
then building everything else *seems* to workaround whatever the problem
is. This is a obviously brittle, but the best answer we have at the
moment.
This should reduce the incidence of #4539, but I do not claim it is a fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4734)

ci: workaround Windows+CMake+x86 build problems

---

google/cloud/storage/internal/compute_engine_util.cc
google/cloud/storage/oauth2/compute_engine_credentials.cc
google/cloud/storage/oauth2/compute_engine_credentials_test.cc

Sometimes a thing pretending to be the GCE metadata server responds
with invalid contents but with a success HTTP status code. We were
crashing in this case because we tried to create a StatusOr with an OK
status.
Fixes #4729
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4739)

fix(storage): GCE credentials response handling

---

google/cloud/storage/signed_url_options.h
google/cloud/storage/testbench/gcs_object.py

Fixes #4762 
I thought about just removing this function, it is not used in the
library at all. But it is a public API, and seems unnecessary to
make a breaking change for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4763)

cleanup(storage): fix typo in x-goog-* (was x-good-*)

---

google/cloud/internal/log_wrapper.cc
google/cloud/internal/log_wrapper.h
google/cloud/internal/log_wrapper_test.cc

When a function returns `future<StatusOr<T>>` we cannot log the results
immediately, they may not even exist! Previously we just logged whether
the returned future was ready, now we attach a callback to the future
which logs the value whenever it becomes available.
Because this may be much later in the log, the application might need a
token to match the request and response pairs. I am using a per-thread
counter and the thread id as an identifier.
Part of the work for #4561 and #3900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4746)

feat: log the result for future<StatusOr<T>>

---

google/cloud/storage/internal/nljson.h

We needed this function to workaround a googletest bug
(google/googletest#521). This bug was fixed a couple of years ago, but
we neglected to remove the workaround until now.
Fixes #4748
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4773)

cleanup(storage): remove nlohmann::PrintTo()

---

google/cloud/internal/log_wrapper.h
google/cloud/internal/log_wrapper_test.cc

This is yet another overload for `g::c::internal::LogWrapper` this time
for functions that return `future<Status>`. We will need this overload
in the log decorator for `pubsub::PublisherStub`.
Part of the work for #4561 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4772)

feat: a LogWrapper for future<Status>

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/integration_tests/message_integration_test.cc
google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/pubsub_client.bzl
google/cloud/pubsub/pubsub_client_unit_tests.bzl
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscription_admin_client.h
google/cloud/pubsub/subscription_mutation_builder.h
google/cloud/pubsub/subscription_mutation_builder_test.cc

I will soon need a `*Builder` class for `UpdateSubscription` and this
would have been almost a copy of `CreateSubscriptionBuilder`. In this PR
I am just renaming the class to `SubcriptionMutationBuilder`, a future
PR will add the functionality to support both `Create...` and
`Update...` operations.
Part of the work for #4572
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4771)

refactor(pubsub): rename CreateSubscriptionBuilder

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/integration_tests/message_integration_test.cc
google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/pubsub_client.bzl
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscription_admin_client.h
google/cloud/pubsub/subscription_mutation_builder.cc
google/cloud/pubsub/subscription_mutation_builder.h
google/cloud/pubsub/subscription_mutation_builder_test.cc

In this PR we change `pubsub::SubscriptionMutationBuilder` so it can
build both the protos for `CreateSubscription()` and
`UpdateSubscription()`.  I had to change the `pubsub::TopicAdminClient`
API in this change, I think it is now simpler in the common case.
Part of the work for #4572
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4774)

feat(pubsub): a builder for UpdateSubscriptionRequest

---

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/internal/subscriber_stub.cc
google/cloud/pubsub/internal/subscriber_stub.h
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscription_admin_client.h
google/cloud/pubsub/subscription_admin_connection.cc
google/cloud/pubsub/subscription_admin_connection.h
google/cloud/pubsub/testing/mock_subscriber_stub.h

Now that we have a builder for the `UpdateSubscription()` proto, we can
implement the function, an integration test, and an example.
This fixes #4572 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4777)

feat(pubsub): implement SubscriptionAdmin::UpdateSubcription

---

ci/kokoro/docker/clang-tidy.cfg
ci/kokoro/docker/msan.cfg
ci/kokoro/docker/ubsan.cfg

The msan, ubsan, and clang-tidy full builds are close to the 120m limit.
This PR increases the limit to avoid flakes that would otherwise succeed.
I will file some bugs with suggestions on how to reduce the build times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4782)

ci: increase timeout for slow builds

---

ci/kokoro/docker/build-in-docker-bazel.sh

This just makes the output a little clearer. Include any override
setting for the Spanner endpoint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4793)

ci: log when integration tests against production start

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/pubsub_client_unit_tests.bzl
google/cloud/pubsub/subscriber_connection.cc
google/cloud/pubsub/subscriber_connection_test.cc
google/cloud/pubsub/subscription_admin_connection.cc
google/cloud/pubsub/subscription_admin_connection.h
google/cloud/pubsub/subscription_admin_connection_test.cc

If configured, use the `SubscriberLogging` decorator for both
`SubscriptionAdminConnection` and `SubscriberConnection`.
Fixes #4561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4789)

feat(pubsub): enable logging for Subs*Connection

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/integration_tests/message_integration_test.cc
google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc
google/cloud/pubsub/pubsub_client.bzl
google/cloud/pubsub/pubsub_client_unit_tests.bzl
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscription_mutation_builder_test.cc
google/cloud/pubsub/topic_admin_client.h
google/cloud/pubsub/topic_admin_connection_test.cc
google/cloud/pubsub/topic_mutation_builder.h
google/cloud/pubsub/topic_mutation_builder_test.cc

Rename `pubsub::CreateTopicBuilder` to `pubsub::TopicMutationBuilder`,
we will need basically the same builder for both `CreateTopic()` and
`UpdateTopic()`. This PR is just about renaming, the new functionality
will come in a future PR.
Part of the work for #4566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4790)

refactor(pubsub): rename CreateTopicBuilder

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/pubsub_client.bzl
google/cloud/pubsub/topic_admin_client.h
google/cloud/pubsub/topic_admin_connection_test.cc
google/cloud/pubsub/topic_mutation_builder.cc
google/cloud/pubsub/topic_mutation_builder.h
google/cloud/pubsub/topic_mutation_builder_test.cc

Adds support for updates in `pubsub::TopicMutationBuilder`, though this
is not used beyond the unit test at this point.
Part of the work for #4566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4794)

feat(pubsub): support updates in TopicMutationBuilder

---

google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc
google/cloud/pubsub/internal/publisher_logging.cc
google/cloud/pubsub/internal/publisher_logging.h
google/cloud/pubsub/internal/publisher_logging_test.cc
google/cloud/pubsub/internal/publisher_stub.cc
google/cloud/pubsub/internal/publisher_stub.h
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/testing/mock_publisher_stub.h
google/cloud/pubsub/topic_admin_client.h
google/cloud/pubsub/topic_admin_connection.cc
google/cloud/pubsub/topic_admin_connection.h
google/cloud/pubsub/topic_admin_connection_test.cc

Add the function to the stub, connection, mocks, and decorators. Add a
simple example for Doxygen, the typical unit tests, and include this
function in the integration test. The emulator does not support this
function, so we need some workarounds which are labeled with TODO
entries.
Fixes #4566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4800)

feat(pubsub): implement TopicAdminClient::UpdateTopic

---

google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/publisher.h
google/cloud/pubsub/publisher_options.h
google/cloud/pubsub/samples/samples.cc

This shows how to use `PublisherOptions` to configure batching. I also
updated a number of comments so the example could be referenced from our
Doxygen docs.
Fixes #4626 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4812)

feat(pubsub): add batching example

---

google/cloud/pubsub/ack_handler.h
google/cloud/pubsub/ack_handler_test.cc
google/cloud/pubsub/internal/default_ack_handler_impl.h
google/cloud/pubsub/internal/default_ack_handler_impl_test.cc
google/cloud/pubsub/internal/subscription_session.cc
google/cloud/pubsub/internal/subscription_session_test.cc
google/cloud/pubsub/mocks/mock_ack_handler.h

When using dead-letter queues (DLQ, an upcoming feature for Cloud
Pub/Sub) the message might include a "delivery attempt" counter, which
approximately tell us how many times has Pub/Sub tried to deliver a
message. We need to expose this field, and choose to expose it as part
of the `AckHandler`, like we do for `ack_id()`.
Fixes #4799
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4807)

feat(pubsub): expose delivery_attempt field

---

google/cloud/pubsub/samples/samples.cc

Our existing sample to publish messages already shows how to handle
errors, I am adding the region tag to it.
Fixes #4655
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4813)

feat(pubsub): tag sample with publish_with_error_handler

---

ci/check-style.sh
ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
ci/kokoro/macos/build-bazel.sh
ci/kokoro/macos/build-quickstart-bazel.sh
ci/kokoro/windows/build-bazel.ps1
ci/kokoro/windows/build-quickstart-bazel.ps1

Fixes: https://github.com/googleapis/google-cloud-cpp/issues/4819
This simplifies our build scripts and future-proofs them so that our bazel builds always build everything. In bazel world `...` is the way to specify that (the trailing `:all` is unnecessary)`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4824)

ci: simplify bazel targets to consistently use `...` to build everything

---

ci/kokoro/docker/build-in-docker-cmake.sh
ci/kokoro/docker/build.sh

Part of https://github.com/googleapis/google-cloud-cpp/issues/4827
Following this, I'll remove the separate "ninja" build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4828)

ci: use Ninja for all cmake builds

---

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/internal/subscriber_logging.cc
google/cloud/pubsub/internal/subscriber_logging.h
google/cloud/pubsub/internal/subscriber_logging_test.cc
google/cloud/pubsub/internal/subscriber_stub.cc
google/cloud/pubsub/internal/subscriber_stub.h
google/cloud/pubsub/subscription_admin_connection.cc
google/cloud/pubsub/subscription_admin_connection.h
google/cloud/pubsub/subscription_admin_connection_test.cc
google/cloud/pubsub/testing/mock_subscriber_stub.h
google/cloud/pubsub/testing/random_names.cc
google/cloud/pubsub/testing/random_names.h

Bootstrap the snapshot CRUD functions. I cannot start with just one
function, that is not really testable, and I really don't want to create
a giant PR with all of them. This is basically a minimal set to enable
an integration test.
To keep this PR small we do not add the new functions to
`pubsub::SubscriptionAdminClient`, nor do we add the examples for them.
Part of the work for #4575 and #4577
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4825)

feat(pubsub): bootstrap snapshot CRUD

---

ci/kokoro/docker/build-in-docker-cmake.sh

Part of https://github.com/googleapis/google-cloud-cpp/issues/4837
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4838)

fix: don't use Ninja on coverage build

---

google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/batching_publisher_connection.h
google/cloud/pubsub/internal/batching_publisher_connection_test.cc
google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_option_test.cc
google/cloud/pubsub/publisher_options.cc
google/cloud/pubsub/publisher_options.h
google/cloud/pubsub/samples/samples.cc

Merge the BatchingOptions class into PublisherOptions.
Fixes #4811
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4836)

cleanup(pubsub): simplify PublisherOptions

---

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/internal/subscriber_logging.cc
google/cloud/pubsub/internal/subscriber_logging.h
google/cloud/pubsub/internal/subscriber_logging_test.cc
google/cloud/pubsub/internal/subscriber_stub.cc
google/cloud/pubsub/internal/subscriber_stub.h
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscription_admin_client.h
google/cloud/pubsub/subscription_admin_connection.cc
google/cloud/pubsub/subscription_admin_connection.h
google/cloud/pubsub/subscription_admin_connection_test.cc
google/cloud/pubsub/testing/mock_subscriber_stub.h

Add the function to the *Stub, *Connection, and *Client classes. Update
the unit tests, integration tests, and examples to include this
function.
Fixes #4573
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4835)

feat(pubsub): implement GetSnapshot()

---

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/internal/subscriber_logging.cc
google/cloud/pubsub/internal/subscriber_logging.h
google/cloud/pubsub/internal/subscriber_logging_test.cc
google/cloud/pubsub/internal/subscriber_stub.cc
google/cloud/pubsub/internal/subscriber_stub.h
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscription_admin_client.h
google/cloud/pubsub/subscription_admin_connection.cc
google/cloud/pubsub/subscription_admin_connection.h
google/cloud/pubsub/subscription_admin_connection_test.cc
google/cloud/pubsub/testing/mock_subscriber_stub.h

Implement the function in the *Stub, *Connection, and *Client classes.
Update the unit tests, integration test, and samples to also test the
new function.
Fixes #4574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4841)

feat(pubsub): implement ListSnapshots

---

google/cloud/pubsub/subscriber.h
google/cloud/pubsub/subscriber_test.cc

The options will be needed to setup flow and concurrency control.
Fixes #4735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4845)

feat(pubsub): Subscriber::Subscribe() takes options

---

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/internal/subscriber_logging.cc
google/cloud/pubsub/internal/subscriber_logging.h
google/cloud/pubsub/internal/subscriber_logging_test.cc
google/cloud/pubsub/internal/subscriber_stub.cc
google/cloud/pubsub/internal/subscriber_stub.h
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscription_admin_client.h
google/cloud/pubsub/subscription_admin_connection.cc
google/cloud/pubsub/subscription_admin_connection.h
google/cloud/pubsub/subscription_admin_connection_test.cc
google/cloud/pubsub/testing/mock_subscriber_stub.h

Implemented the function in the *Stub, *Connection, and *Client classes.
Updated the unit tests, integration tests, and samples to include this
new function. I had to disable some of the tests when running against
the emulator because the emulator does not support this function. Filed
a bug and updated our tracker for emulator workarounds.
Fixes #4576
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4846)

feat(pubsub): implement UpdateSnapshot()

---

ci/kokoro/windows/build-cmake.ps1

Fix build / link problem with `storage_well_known_parameters_test`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4847)

ci: workaround build failure on MSVC+x86

---

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc
google/cloud/pubsub/internal/publisher_logging.cc
google/cloud/pubsub/internal/publisher_logging.h
google/cloud/pubsub/internal/publisher_logging_test.cc
google/cloud/pubsub/internal/publisher_stub.cc
google/cloud/pubsub/internal/publisher_stub.h
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/testing/mock_publisher_stub.h
google/cloud/pubsub/topic_admin_client.h
google/cloud/pubsub/topic_admin_connection.cc
google/cloud/pubsub/topic_admin_connection.h
google/cloud/pubsub/topic_admin_connection_test.cc

Implement the function in the *Stub, *Connection, and *Client classes.
Modify the unit tests, integration tests, and samples to include this
function. The emulator does not support this function so we need some
workarounds in the integration tests and samples.
Fixes #4570 and fixes #4639
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4849)

feat(pubsub): implement DetachSubscription()

---

google/cloud/pubsub/subscription_mutation_builder.cc
google/cloud/pubsub/subscription_mutation_builder.h
google/cloud/pubsub/subscription_mutation_builder_test.cc

A few changes to make `pubsub::PushConfigBuilder` a real builder for the
`ModifyPushConfigRequest` proto. The unit test is a bit repetitive with
the existing test *using* the builder, but I think this is less bad than
having to reason about "why don't we need test X?"
Part of the work for #4843
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4851)

feat(pubsub): a builder for ModifyPushConfigRequest

---

google/cloud/spanner/value_test.cc

I missed updating one instance of TypeCode "STRUCT + 1", which was
used during the development of `spanner::Numeric`.  Oops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4864)

cleanup(spanner): use the correct form of the NUMERIC type code

---

google/cloud/pubsub/samples/samples.cc

Depending on the language the `pubsub_quickstart_subscriber` and
`pubsub_quickstart_create_topic` examples are either full programs, or
incomplete programs with "put your topic ID here", or aliases to
examples in a larger program. I chose the latter for C++ because at
least that makes sure we always compile and test these samples.
Fixes #4741 and fixes #4667
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4866)

doc(pubsub): more sample aliases

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/mocks/mock_topic_admin_connection.h
google/cloud/pubsub/pubsub_client_mocks.bzl
google/cloud/pubsub/pubsub_client_unit_tests.bzl
google/cloud/pubsub/topic_admin_client.h
google/cloud/pubsub/topic_admin_client_test.cc

Add a googlemock for `pubsub::TopicAdminConnection` and a unit test to
verify it is usable.
Fixes #4784
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4868)

feat(pubsub): a mock for TopicAdminConnection

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/mocks/mock_subscription_admin_connection.h
google/cloud/pubsub/pubsub_client_mocks.bzl
google/cloud/pubsub/pubsub_client_unit_tests.bzl
google/cloud/pubsub/subscription_admin_client_test.cc

Define a googlemock for `pubsub::SubscriptionAdminConnection` and write
a unit test to make sure it is usable.
Fixes #4785
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4870)

feat(pubsub): mock for SubscriptionAdminConnection

---

google/cloud/pubsub/publisher_options.h

Fixes #4671
As noted in the bug, originally I thought we should change the types, but after further thought, this is more of a documentation problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4873)

doc(pubsub): document publish batch limits

---

google/cloud/storage/internal/bucket_requests.cc
google/cloud/storage/lifecycle_rule.cc
google/cloud/storage/lifecycle_rule.h
google/cloud/storage/lifecycle_rule_test.cc

Implement new Object Lifecycle Management (OLM) conditions
based on:
- "noncurrent time", i.e., the time since the object version is
"archived" or no longer the "current" version.
- "custom time", i.e., a custom field in the object metadata.
This fixes #4275 and fixes #4432
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4871)

feat(storage): noncurrent and custom time OLM

---

google/cloud/pubsub/CMakeLists.txt

Change the generated Doxygen documentation to use a pre-release version
number. Our README file already states that the library is not GA, but I
want to publish the documentation, and putting a 1.x version number is
misleading.
Part of the work for #4874 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4881)

doc(pubsub): use pre-release numbers for Doxygen

---

.gitignore
ci/kokoro/docker/build.sh
ci/kokoro/docker/upload-docs.sh

On CI builds only (not when running locally) upload the Doxygen docs to `googleapis.github.io/google-cloud-cpp`.
Fixed the upload script to be able to test it manually, so one can do:
```sh
GENERATE_DOCS=yes ./ci/kokoro/docker/upload-docs.sh master cmake-out/ci-fedora-install-31-clang-tidy/
```
and upload the documents to `$USER.github.io/google-cloud-cpp/`, for example see:
https://coryan.github.io/google-cloud-cpp/latest/pubsub/index.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4882)

ci: restore github.io uploads

---

bazel/curl.BUILD

We're seeing strange errors in our CI related to libcurl. It's possible
that we're using some cached artifacts that were compiled w/ the wrong
settings.
See also https://docs.bazel.build/versions/2.0.0/remote-caching.html#exclude-specific-targets-from-using-the-remote-cache
Related to PR https://github.com/googleapis/google-cloud-cpp/pull/4869
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4885)

ci: don't cache curl build actions

---

google/cloud/spanner/integration_tests/database_admin_integration_test.cc

I also pulled this out of my CMEK branch (see #4468) to reduce the diff
there. There's still a small enhancement here which is adding the
`DatabaseExists` method; in the CMEK branch it also reduces the amount
of per-test boilerplate.
Part of #4312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4892)

test: refactor the database admin integration test

---

google/cloud/storage/examples/storage_object_samples.cc
google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/internal/object_requests.cc
google/cloud/storage/object_metadata.cc
google/cloud/storage/object_metadata.h
google/cloud/storage/object_metadata_test.cc
google/cloud/storage/testbench/gcs_object.py

Support the `customTime` field in `gcs::ObjectMetadata`. This is a
timestamp field, so it is represented by
`std::chrono::system_clock::timestamp` and the name in C++ is
`custom_time`. Because this field can be changed, we need support for it
in `Patch` and `Update`. I also wrote an example.
Fixes #4886
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4901)

feat(storage): custom_time in ObjectMetadata

---

google/cloud/storage/benchmarks/benchmark_make_random_test.cc
google/cloud/storage/examples/storage_examples_common.cc
google/cloud/storage/testing/random_names.cc

We create buckets with random names in our integration tests, when these
leak (either because the test crashes or we forget to cleanup) it is
nice to have the date in the name so we can tell which buckets are safe
to delete.  In a future PR we can automatically cleanup these buckets
too.
This will help with #4905
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4908)

ci: put current date in random bucket names

---

bazel/curl.BUILD

On Windows and macOS libcurl's configuration does not depend on the
distro, so we can make the builds more cacheable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4909)

ci: make libcurl more cacheable with Bazel

---

google/cloud/bigtable/row_reader_test.cc
google/cloud/bigtable/testing/table_integration_test.h
google/cloud/bigtable/tests/admin_async_future_integration_test.cc
google/cloud/bigtable/tests/admin_backup_async_future_integration_test.cc
google/cloud/bigtable/tests/admin_backup_integration_test.cc
google/cloud/bigtable/tests/admin_iam_policy_integration_test.cc
google/cloud/bigtable/tests/admin_integration_test.cc
google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
google/cloud/bigtable/tests/instance_admin_integration_test.cc
google/cloud/spanner/internal/database_admin_logging_test.cc
google/cloud/spanner/internal/instance_admin_logging_test.cc
google/cloud/spanner/internal/logging_result_set_reader_test.cc
google/cloud/spanner/internal/logging_spanner_stub_test.cc
google/cloud/spanner/internal/spanner_stub_test.cc
google/cloud/storage/internal/logging_resumable_upload_session_test.cc
google/cloud/storage/testing/storage_integration_test.h
google/cloud/storage/tests/bucket_integration_test.cc
google/cloud/storage/tests/grpc_integration_test.cc
google/cloud/storage/tests/object_basic_crud_integration_test.cc
google/cloud/storage/tests/object_checksum_integration_test.cc
google/cloud/storage/tests/object_file_integration_test.cc
google/cloud/storage/tests/object_hash_integration_test.cc
google/cloud/storage/tests/object_insert_integration_test.cc
google/cloud/storage/tests/object_integration_test.cc

Cleaned up most uses of `std::count_if()` in the tests in factor of a
`Contains()` or `Not(Contains())` matcher over the collection. The
matchers produce better error messages, and (maybe) better express what
we are testing for.
Thanks to @devbww for creating `ContainsOnce()` and for the review
in an earlier incarnation of this PR.

cleanup: prefer matchers over std::count_if

---

google/cloud/pubsub/internal/subscription_session.cc
google/cloud/pubsub/internal/subscription_session.h
google/cloud/pubsub/internal/subscription_session_test.cc

So far it has been easy to shutdown subscription sessions as the number
of operations outstanding is 1 or 2 (including the timers). As we
increase the concurrency we will need better code to handle potentially
multiple callbacks in flight, and maybe even multiple calls to
`AsynPull()` in flight. We also want to nack any pending messages that
will not be delivered to a callback as early as possible.
This change creates a helper class to track all asynchronous operations.
Recall that subscription sessions are just represented by a
`future<Status>`. When this future is canceled that starts the orderly
shutdown process. First, a helper class stops scheduling any additional
work. Next, the timer for the session is canceled. A helper class tracks
how many operations are pending, when the …

feat(pubsub): orderly shutdown subscription sessions

---

google/cloud/pubsub/internal/subscription_session.cc
google/cloud/pubsub/internal/subscription_session.h

I did not like creating member objects that were discarded in the first
function call. This is all a bit complicated because we need to create a
promise<> to receive the session final status, but this promise also
needs to hold the cancellation callback (albeit that can be indirect).
Fixes #4898

cleanup(pubsub): cancel callback in SubscriptionSession

---

bazel/curl.BUILD
ci/kokoro/docker/build-in-docker-bazel.sh

Make libcurl cacheable on CI builds, though it remains very much
not cache-friendly for manual builds. The build uses a `--define`
Bazel flag to configure the `CURL_CA_BUNDLE` macro, if the
`--define` flag is not provided we default to guessing the location
as before.
I think this is a reasonable tradeoff: the build works by default,
without special flags, but it is not cache-friendly. The CI builds
work more efficiently, but require a special flag.
Fixes #4902 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4911)

ci: make libcurl cacheable on Linux builds

---

google/cloud/storage/tests/bucket_integration_test.cc

Help trace bucket_integration_test failure noted in #4917.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4922)

ci: log bucket_name after CreateBucketForProject() failure

---

ci/kokoro/docker/build-in-docker-cmake.sh
cmake/EnableWerror.cmake
generator/internal/codegen_utils.cc
google/cloud/bigquery/internal/streaming_read_result_source.cc
google/cloud/bigtable/benchmarks/benchmark.cc
google/cloud/bigtable/benchmarks/endurance_benchmark.cc
google/cloud/internal/backoff_policy.cc
google/cloud/internal/big_endian.h
google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
google/cloud/spanner/bytes.cc
google/cloud/spanner/integration_tests/client_stress_test.cc
google/cloud/spanner/numeric.h
google/cloud/storage/benchmarks/benchmark_utils.cc
google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc
google/cloud/storage/benchmarks/storage_shard_throughput_benchmark.cc
google/cloud/storage/benchmarks/throughput_options.cc
google/cloud/storage/internal/metadata_parser.cc
google/cloud/storage/internal/policy_document_request_test.cc

Enable `-Wconversion -Wno-sign-conversion` on the CMake builds. We
discussed this as maybe introducing too many casts, but also maybe
helping us catch stuff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4907)

cleanup: build with -Wconversion

---

ci/kokoro/macos/build-bazel.sh
ci/kokoro/macos/download-cache.sh
ci/kokoro/macos/upload-cache.sh

Now that libcurl is cache-friendly with macOS we do not need the tarball
cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4924)

ci: use GCS Bazel cache for macOS

---

ci/kokoro/docker/build-in-docker-quickstart-bazel.sh

This build uses a different shell script, fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4927)

ci: use GCS cache for docker/quickstart-bazel build

---

ci/kokoro/docker/build-in-docker-quickstart-bazel.sh

This reverts commit f89b285bbc35107e5b8e3557829c5385795b0969.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4930)

revert: use GCS cache for docker/quickstart-bazel build

---

.bazelrc

Bazel creates "convenience" links in %workspace% pointing to the
location of several interesting directories. These links are wrong when
created inside a Docker container, which is the case for most of our
builds, better to not generate the links in the first place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4933)

ci: remove inconvenient convenience symlinks

---

google/cloud/pubsub/internal/subscription_session.cc
google/cloud/pubsub/internal/subscription_session.h
google/cloud/pubsub/internal/subscription_session_test.cc

`ShutdownSessionManager` was not actually waiting until all pending
operations were done. Timer management was a bit wonky too, this makes
it simpler, cancels the pending timer when the session is closed, and
therefore makes shutdown faster for some tests.
Add a couple of tests to reproduce the problems.
Fixes #4921
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4935)

fix(pubsub): actually wait for pending tasks

---

generator/internal/descriptor_utils.cc

Disable the warnings before including Abseil headers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4939)

fix(generator): absl warnings on MSVC+x86

---

google/cloud/pubsub/samples/samples.cc

The subscription samples need to signal a waiting thread when something
(typically the first message) happens. This change uses condition
variables to do this, maybe less elegant, but easier to understand for
most C++ developers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4937)

cleanup(pubsub): more familiar idioms in samples

---

google/cloud/connection_options.cc
google/cloud/connection_options.h
google/cloud/connection_options_test.cc
google/cloud/internal/background_threads_impl.cc
google/cloud/internal/background_threads_impl.h
google/cloud/internal/background_threads_impl_test.cc

Make the size of the background thread pool created by
google::cloud::ConnectionOptions` configurable. A future change will
set the default size to something more sensible than "one", though this
would need to be by service, for example, a subscription or publisher
*should* use several threads, but the admin APIs are probably fine with
one.
Fixes #4650
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4936)

feat: automatically create background thread pools

---

google/cloud/pubsub/internal/subscription_concurrency_control_test.cc

Another build breakage on MSVC+x86, this time signed vs. unsigned in a
`>=` comparison.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4942)

fix(pubsub): build with MSVC+x86

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/backoff_policy.h
google/cloud/pubsub/integration_tests/message_integration_test.cc
google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc
google/cloud/pubsub/pubsub_client.bzl
google/cloud/pubsub/retry_policy.h
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/topic_admin_client.h
google/cloud/pubsub/topic_admin_connection.cc
google/cloud/pubsub/topic_admin_connection.h
google/cloud/pubsub/topic_admin_connection_test.cc

Add retry loops for `pubsub::TopicAdminConnection`, and consequently for
`pubsub::TopicAdminClient`. In Cloud Pub/Sub all topic admin operations
are idempotent.
Fixes #4580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4959)

feat(pubsub): retry loop for TopicAdminConnection

---

google/cloud/pubsub/integration_tests/message_integration_test.cc
google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc
google/cloud/pubsub/samples/samples.cc

Now that the admin APIs retry (almost all) requests we need to handle
errors caused by duplicate `Create*()` or `Delete*()` requests.
Fixes #4328
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4962)

test(pubsub): better handling for retry errors

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/publisher_options.cc
google/cloud/pubsub/publisher_options.h
google/cloud/pubsub/pubsub_client.bzl

Make the default batching configuration match the settings for the
client libraries in other languages.
Fixes #4808
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4966)

feat(pubsub): align default batching configuration

---

google/cloud/testing_util/validate_metadata.cc

If a method does not have the google.api.http option, return
an empty map from `ExtractParamsFromMethod()` instead of an
invalid-argument error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4973)

fix: Do not require the google.api.http RPC option

---

google/cloud/CMakeLists.txt
google/cloud/google_cloud_cpp_grpc_utils.bzl
google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
google/cloud/internal/async_retry_loop.h
google/cloud/internal/async_retry_loop_test.cc
google/cloud/internal/retry_loop.h
google/cloud/internal/retry_loop_helpers.cc
google/cloud/internal/retry_loop_helpers.h

In the Cloud Pub/Sub library (and I think in all future libraries) the
signature for an asynchronous RPC is:
```cc
future<StatusOr<ResponseProto> AsyncFooBar(
CompletionQueue& cq, std::unique_ptr<grpc::ClientContext> ctx,
RequestProto const& request);
```
This PR introduces a retry loop for functions with that signature,
previous retry loops required a different return type and arguments. The
older signature was really hard to mock and test.
Part of the work for #4971 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4972)

feat: retry loop for asynchronous RPCs

---

google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/batching_publisher_connection.h
google/cloud/pubsub/internal/batching_publisher_connection_test.cc
google/cloud/pubsub/publisher.h
google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection.h
google/cloud/pubsub/publisher_connection_test.cc
google/cloud/pubsub/publisher_options.h

Cloud Pub/Sub libraries are expected to retry `Publish()` requests.
Because these are not idempotent I chose to disable retries by default,
but they can be turned no relatively easily.
Fixes #4971
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4976)

feat(pubsub): optionally retry Publisher::Publish

---

google/cloud/pubsub/publisher.h
google/cloud/pubsub/samples/samples.cc

Implement the `pubsub_publisher_retry_settings` example, showing how to
change the default retry configuration for a `pubsub::Publisher`.
Fixes #4646
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4979)

feat(pubsub): publisher_retry_settings example

---

google/cloud/pubsub/README.md
google/cloud/pubsub/quickstart/quickstart.cc

Thanks to @agasparovic-sabre for pointing out the typos.
I chose to remove the code to split `argv[0]`, it is not important and
distracts from the main point of this quickstart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4982)

doc(pubsub): simplify quickstart program

---

google/cloud/bigtable/examples/bigtable_examples_common.cc
google/cloud/spanner/testing/random_backup_name.cc
google/cloud/spanner/testing/random_database_name.cc
google/cloud/spanner/testing/random_instance_name.cc
google/cloud/storage/benchmarks/benchmark_make_random_test.cc
google/cloud/storage/examples/storage_examples_common.cc
google/cloud/storage/internal/curl_client.cc
google/cloud/storage/internal/generate_message_boundary_test.cc
google/cloud/storage/testing/random_names.cc
google/cloud/storage/testing/storage_integration_test.cc
google/cloud/storage/tests/object_media_integration_test.cc
google/cloud/storage/tests/object_rewrite_integration_test.cc

This is a flake in the making, it fails when the random bucket name
generator uses `3`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4985)

test(storage): fix test expectation

---

ci/kokoro/docker/Dockerfile.ubuntu

Apparently we need the `wheel` package to install `blinker`. I have no
idea why the install procedure for Python packages seems to change from
time to time on Ubuntu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4988)

ci: fix integration build

---

google/cloud/pubsub/samples/samples.cc

While this is (mostly) harmless, TSAN does not like us
accessing `count` while other threads are changing it.
The fix is to call `result.get()` before reading it, as this
waits for any threads / callbacks that might change
`count`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4986)

test(pubsub): fix race condition in example

---

google/cloud/bigtable/row_reader_test.cc
google/cloud/internal/log_wrapper_test.cc
google/cloud/pubsub/internal/publisher_logging_test.cc
google/cloud/pubsub/internal/subscriber_logging_test.cc
google/cloud/pubsub/publisher_connection_test.cc
google/cloud/pubsub/subscriber_connection_test.cc
google/cloud/pubsub/subscription_admin_connection_test.cc
google/cloud/pubsub/topic_admin_connection_test.cc
google/cloud/spanner/internal/database_admin_logging_test.cc
google/cloud/spanner/internal/instance_admin_logging_test.cc
google/cloud/spanner/internal/logging_result_set_reader_test.cc
google/cloud/spanner/internal/logging_spanner_stub_test.cc
google/cloud/spanner/internal/spanner_stub_test.cc
google/cloud/storage/internal/logging_resumable_upload_session_test.cc
google/cloud/storage/tests/object_checksum_integration_test.cc
google/cloud/storage/tests/object_file_integration_test.cc
google/cloud/storage/tests/object_hash_integration_test.cc
google/cloud/storage/tests/object_insert_integration_test.cc
google/cloud/testing_util/capture_log_lines_backend.cc
google/cloud/testing_util/capture_log_lines_backend.h

For Cloud Pub/Sub I need `CaptureLogLinesBackend` to be thread-safe.
Cloud Pub/Sub launches (and uses) multiple threads behind the scenes,
and TSAN detected some racy code in the tests. Most of our tests are
single-threaded, and could get away with a thread-unsafe backend, I
guess the happy days are over.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4987)

test: make test utility class thread-safe

---

google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/application_callback.h
google/cloud/pubsub/internal/session_shutdown_manager.cc
google/cloud/pubsub/internal/session_shutdown_manager.h
google/cloud/pubsub/internal/subscription_concurrency_control.cc
google/cloud/pubsub/internal/subscription_concurrency_control.h
google/cloud/pubsub/internal/subscription_concurrency_control_test.cc
google/cloud/pubsub/pubsub_client.bzl
google/cloud/pubsub/pubsub_client_testing.bzl
google/cloud/pubsub/testing/mock_subscription_message_source.h

Copy the functionality to perform concurrency control to a separate
class. For now, this class is only used in tests. A future PR will
replace `pubsub_internal::SubscriptionSession` with a class that uses
this new component.
Part of the work for #4970
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4998)

refactor(pubsub): split SubscriptionSession [4]

---

google/cloud/completion_queue.cc
google/cloud/completion_queue_test.cc

After a completion queue is shutdown we should not run any functions
scheduled via `RunAsync()` that is both surprising and makes it hard to
schedule a clean shutdown for application developers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5008)

fix: CompletionQueue shutdown disables RunAsync

---

generator/CMakeLists.txt

Abseil (at least the version we are using) incorrectly uses
`find_package()` instead of `find_dependency()` in its package file.
Newer versions of CMake produce scary looking warnings for this, we
silence them to avoid confusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5005)

cleanup: silence CMake warnings in absl package

---

google/cloud/pubsub/internal/default_subscription_batch_source.cc
google/cloud/pubsub/internal/default_subscription_batch_source.h
google/cloud/pubsub/internal/default_subscription_batch_source_test.cc
google/cloud/pubsub/internal/subscription_session.cc
google/cloud/pubsub/internal/subscription_session.h
google/cloud/pubsub/internal/subscription_session_test.cc
google/cloud/pubsub/subscriber_connection.cc
google/cloud/pubsub/subscriber_connection.h
google/cloud/pubsub/subscriber_connection_test.cc

With this change a subscription session (the result of calling
`Subscriber::Subscribe()`) has a retry loop.
Fixes #4699
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5022)

feat(pubsub): retry loops for subscriptions

---

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
google/cloud/spanner/integration_tests/data_types_integration_test.cc
google/cloud/spanner/numeric.h
google/cloud/spanner/samples/samples.cc
google/cloud/spanner/testing/database_integration_test.cc
google/cloud/spanner/value.h

Includes some amount of short-circuiting when running tests
against the Cloud Spanner Emulator, which does not yet support
`NUMERIC`.  This will be removed later.  See #5024.
Fixes #4527.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5025)

feat(spanner): start using NUMERIC types in database schema

---

google/cloud/pubsub/integration_tests/CMakeLists.txt
google/cloud/pubsub/integration_tests/pubsub_client_integration_tests.bzl
google/cloud/pubsub/integration_tests/subscription_lifecycle.cc
google/cloud/pubsub/integration_tests/subscription_lifecycle_test.cc
google/cloud/pubsub/internal/subscription_concurrency_control_test.cc
google/cloud/pubsub/internal/subscription_session.cc
google/cloud/pubsub/internal/subscription_session_test.cc
google/cloud/pubsub/subscription_options.h

Some applications may want to create a subscription, setup a handler for
messages and errors, and then just leave the subscription "running" in
the background, associated with its completion queue. Until this PR the
subscription was terminated when the associated `future<Status>`
finished.
Fixes #4970 and fixes #4983
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5027)

feat(pubsub): support fire & forget subscriptions

---

google/cloud/internal/port_platform.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5034)

fix: remove 'Bigtable' from generic error message

---

google/cloud/storage/internal/curl_wrappers.cc
google/cloud/storage/internal/curl_wrappers_disable_sigpipe_handler_test.cc
google/cloud/storage/internal/curl_wrappers_enable_sigpipe_handler_test.cc
google/cloud/storage/internal/curl_wrappers_locking_already_present_test.cc
google/cloud/storage/internal/curl_wrappers_locking_disabled_test.cc
google/cloud/storage/internal/curl_wrappers_locking_enabled_test.cc

Sometimes libcurl will report the SSL version as `NULL`, typically
because there are multiple SSL engines, or because there is no SSL
version (say when compiled only with Schannel). This change avoids
crashes in that case by returning an empty string for the SSL version
name.
This name is used to determine if SSL requires locking. I think an empty
string works correctly in that case. Only a limited number of *known*
SSL versions do require the locks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5037)

fix(storage): work with unknown SSL version in curl

---

google/cloud/testing_util/contains_once.h
google/cloud/testing_util/status_matchers.h

Use `testing_util_internal` instead. Why? Because we already have
`google::cloud::internal` and any usage of `internal::` becomes
ambiguous inside the `testing_util` namespace depending on what you
include.
Arguably we should avoid `internal::` altogether, this seemed (to me)
the minimal way to fix the ambiguity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5040)

cleanup: remove testing_util::internal namespace

---

google/cloud/pubsub/CMakeLists.txt

We need to publish the docs to https://googleapis.dev with the current
version or they do not show up in the "latest" link. Still mark the
current code as "Beta" so users know what to expect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5041)

doc(pubsub): update Doxygen version numbers

---

google/cloud/completion_queue.h
google/cloud/internal/completion_queue_impl.h
google/cloud/internal/default_completion_queue_impl.cc
google/cloud/internal/default_completion_queue_impl.h
google/cloud/testing_util/fake_completion_queue_impl.cc
google/cloud/testing_util/fake_completion_queue_impl.h

We want `MakeRelativeTimer()` to be mockable too, it is hard to verify
that backoff timers are "right" when using absolute times only.
This fixes #4718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5043)

feat(common): make CompletionQueueImpl mockable [3]

---

google/cloud/future_generic.h
google/cloud/future_generic_test.cc
google/cloud/future_void.h
google/cloud/future_void_test.cc
google/cloud/internal/future_base.h

Sometimes we need to create a `promise<T>` without any shared state,
typically because we won't be able to create the cancellation callback
until later in the code. One can create a promise and replace its shared
state, but that seems wasteful, like creating a `unique_ptr<>` with an
object only to reset it a few lines later. This PR introduces
`google::cloud::null_promise_t`, analogous to `nullopt_t` to initialize
such promises.
Motivated by #5026
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5046)

feat(common): create promises without shared state

---

google/cloud/internal/async_rpc_details.h

Part of the work for #5026
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5047)

feat(common): support cancels for asynchronous unary RPCs

---

cmake/GoogleCloudCppCommon.cmake
google/cloud/CMakeLists.txt
google/cloud/bigtable/CMakeLists.txt
google/cloud/pubsub/CMakeLists.txt
google/cloud/spanner/CMakeLists.txt
google/cloud/storage/CMakeLists.txt
google/cloud/testing_util/CMakeLists.txt

Abseil does not install its own pkg-config `.pc` files, so in our own
`.pc` files we need to list the `-l` options explicitly. With this
change we navigate the dependency graph for the CMake targets to
discover all these flags, instead of hard-coding them in our list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5051)

cleanup: automate Abseil pkg-config dependencies

---

google/cloud/BUILD

This was an unnecessary dep that @coryan discovered in
https://github.com/googleapis/google-cloud-cpp/pull/5051 and removed in
the CMakeLists.txt file. This PR cleans up the unneeded dep in the bazel
build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5054)

fix: remove unneeded dep

---

generator/CMakeLists.txt

Fixes #5052
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5053)

fix: Add missing dependency on libprotoc to google_cloud_cpp_generator

---

ci/kokoro/cache-functions.sh

Fixes https://github.com/googleapis/google-cloud-cpp/issues/4783, by using ccache during the full builds with cmake. https://github.com/googleapis/google-cloud-cpp/pull/4869 was already submitted, which enabled a bazel cache for all CI builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5063)

ci: enable ccache on all CI builds

---

ci/kokoro/docker/build-in-docker-bazel.sh

I don't think there's any need to do an explicit `bazel build`. Any code and tests will be compiled when they need to be run. Additionally, if a `bazel test` invocation uses slightly different flags than the `bazel build` invocation, the cache will not be hit and we'll unnecessarily compile stuff in the `bazel build` step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5066)

ci: remove unneeded explicit build step

---

google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh

The storage emulator also has a httpbin implementation, we use that
implementation on the CMake-based builds, and should also use it for the
Bazel-based builds.
I noticed because httpbin.org was down a few minutes ago.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5076)

test: use local httpbin for Bazel builds

---

google/cloud/storage/testbench/testbench.py

Because I (coryan) did not know about host-based routing the XML
emulation has used a different subdirectory `/xmlapi/`. The production
service uses the `Host: ` header to resolve the bucket for XML requests,
with this change the testbench does the same.
The old `/xmlapi/` path is still working, I will remove it once the
tests pass without it.
Part of the work for #5072 only tested manually so far.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5083)

feat(testbench): better emulation for XML requests

---

ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/docker/upload-coverage.sh

This reduces the uploaded report size from ~900MB to ~16MB, which may make our coverage reports less flaky.
Part of https://github.com/googleapis/google-cloud-cpp/issues/5082
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5086)

ci: merge coverage data before uploading

---

google/cloud/storage/CMakeLists.txt
google/cloud/storage/internal/curl_client.cc
google/cloud/storage/internal/curl_client.h
google/cloud/storage/internal/curl_wrappers.cc
google/cloud/storage/internal/curl_wrappers.h
google/cloud/storage/internal/curl_wrappers_test.cc
google/cloud/storage/storage_client_unit_tests.bzl

Some of our requests were using the wrong `Host:` header, luckily the
service is forgiving, and the testbench too.
Part of the work for #5072
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5085)

fix(storage): use correct host header

---

google/cloud/bigtable/benchmarks/benchmark.h
google/cloud/bigtable/instance_admin.h
google/cloud/bigtable/row_set.h
google/cloud/bigtable/table.h
google/cloud/bigtable/table_admin.h
google/cloud/bigtable/testing/inprocess_admin_client.h
google/cloud/bigtable/testing/mock_response_reader.h
google/cloud/firestore/field_path.h
google/cloud/internal/async_retry_unary_rpc.h
google/cloud/internal/retry_loop.h
google/cloud/internal/tuple.h
google/cloud/internal/utility.h
google/cloud/spanner/instance_admin_connection.h
google/cloud/spanner/internal/polling_loop.h
google/cloud/spanner/value.h
google/cloud/storage/client.h
google/cloud/storage/client_options.h
google/cloud/storage/internal/generic_request.h
google/cloud/storage/internal/sign_blob_requests.h
google/cloud/storage/internal/signed_url_requests.h
google/cloud/storage/oauth2/credentials.h
google/cloud/storage/policy_document.h
google/cloud/storage/signed_url_options.h
google/cloud/storage/upload_options.h
google/cloud/testing_util/example_driver.h

This changes nonretriable (which I don't think is a word) to non-retryable, but
happy to go either way on this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5090)

cleanup: Fix typos in Doxygen comments

---

CHANGELOG.md
google/cloud/storage/client_options.cc
google/cloud/storage/client_options.h
google/cloud/storage/client_options_test.cc
google/cloud/storage/internal/curl_client.cc
google/cloud/storage/internal/curl_client.h
google/cloud/storage/tests/object_media_integration_test.cc

The interaction of `ClientOptions::set_endpoint()` and the
`CLOUD_STORAGE_TESTBENCH_ENDPOINT` environment variable was inconsistent
across endpoints. For JSON endpoints `set_endpoint()` overrode the
`CLOUD_STORAGE_TESTBENCH_ENDPOINT` value, while for XML endpoints it was
the opposite.
In other libraries the environment variable always wins, so we are
changing the behavior here. This behavior was never documented, and it
was buggy, this is not a breaking change per-se, but should be
highlighted in the CHANGELOG.
I refactored the code to compute the different endpoints to standalone
functions. That makes them easier to test.
I used friend functions in `internal::` over member functions in
`ClientOptions` because we will (some day) remove the XML endpoints and
I do not want to make …

fix(storage): consistent endpoint computation

---

google/cloud/storage/client_options.cc
google/cloud/storage/client_options_test.cc
google/cloud/storage/testbench/testbench.py
google/cloud/storage/tests/object_basic_crud_integration_test.cc

Cleanup the library and the testbench to use the same paths for the XML
API on the testbench as we use in production. Wrote a test to verify the
testbench can be used via `ClientOptions::set_endpoint()`.
Part of the work for #5072
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5097)

cleanup(storage): remove testbench hack for XML

---

google/cloud/storage/doc/storage-main.dox
google/cloud/storage/internal/curl_client.cc
google/cloud/storage/internal/curl_client.h

When using emulators that do not support XML, application developers may
need to switch off the automatic XML switching in the client library. We
use an environment variable over a `ClientOptions` setting because (a)
this is an implementation detail that we want to change if needed, a
setting would require API changes, and (b) this appears to be needed
only for development / testing, presumably the application developers
don't want to change their code to test against an emulator vs.
production.
Fixes #5072
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5100)

feat(storage): disable XML via environment variable

---

google/cloud/storage/internal/curl_download_request.cc
google/cloud/storage/tests/CMakeLists.txt
google/cloud/storage/tests/small_reads_integration_test.cc
google/cloud/storage/tests/storage_client_integration_tests.bzl

If the application reads data using small(-ish) buffers the download
could stall. This only manifested on Windows.
Thanks to @orinem for the detailed analysis and fix suggestions.
Fixes #5096
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5104)

fix(storage): avoid stalls with small reads

---

ci/kokoro/cache-functions.sh
ci/kokoro/docker/build-in-docker-bazel.sh

Using a fresh cache for the msan build fixes the problem.  I am splitting each build to its own
cache directory, so we can clear the cache for one build at a time in the future.
Part of the work for #5106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5108)

ci: use per-build prefix for Bazel caches

---

ci/kokoro/docker/build-in-docker-cmake.sh
ci/kokoro/docker/build.sh
google/cloud/storage/tests/object_basic_crud_integration_test.cc
google/cloud/storage/tests/object_insert_integration_test.cc
google/cloud/storage/tests/object_integration_test.cc
google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc

The emulator doesn't support this, so production environment is needed.
This fixes #4492 .
A number of tests had to be weakened/disabled due to #5030, #5116 and
b/146890058.
This needs #5029.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031)

test: test gRPC data plane on GCS

---

google/cloud/storage/examples/storage_object_samples.cc

One of the examples was creating a bucket and not cleaning up after
itself.
Part of the fixes for #4905
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5128)

test: fix bucket leak from running example

---

ci/check-style.sh

This removes its summary output, which was messing up the alignment of
the console output. Misspelled words will still be output to the
console, which will mess up the output, but that's the non-expected
case, so it's fine with me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5131)

ci: make cspell output a bit quieter

---

google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/examples/cleanup_stale_buckets_test.cc
google/cloud/storage/examples/storage_bucket_acl_samples.cc
google/cloud/storage/examples/storage_bucket_cors_samples.cc
google/cloud/storage/examples/storage_bucket_default_kms_key_samples.cc
google/cloud/storage/examples/storage_bucket_iam_samples.cc
google/cloud/storage/examples/storage_bucket_requester_pays_samples.cc
google/cloud/storage/examples/storage_default_object_acl_samples.cc
google/cloud/storage/examples/storage_event_based_hold_samples.cc
google/cloud/storage/examples/storage_examples_common.cc
google/cloud/storage/examples/storage_examples_common.h
google/cloud/storage/examples/storage_examples_unit_tests.bzl
google/cloud/storage/examples/storage_lifecycle_management_samples.cc
google/cloud/storage/examples/storage_notification_samples.cc
google/cloud/storage/examples/storage_object_acl_samples.cc
google/cloud/storage/examples/storage_object_cmek_samples.cc
google/cloud/storage/examples/storage_object_samples.cc
google/cloud/storage/examples/storage_object_versioning_samples.cc
google/cloud/storage/examples/storage_policy_doc_samples.cc
google/cloud/storage/examples/storage_quickstart.cc
google/cloud/storage/examples/storage_retention_policy_samples.cc
google/cloud/storage/examples/storage_website_samples.cc

Previously the examples would remove any temporary buckets using just
`client.DeleteBucket()`, but if the sample code accidentally left an
object or two in the temporary bucket the `DeleteBucket()` call fails
and we leak the bucket (and its objects).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5136)

test: use helper to cleanup sample buckets

---

google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscription_mutation_builder.h

Fixes: #4637
This also introduces a new method
`SubscriptionMutationBuilder::clear_dead_letter_policy()` to accomplish this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5140)

feat(pubsub): Implement pubsub_dead_letter_remove sample

---

ci/kokoro/macos/build-bazel.sh

We already did this for Linux and Windows, we want to be able to clear
the cache for one build without affecting other builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5138)

ci: move macOS Bazel cache to its own prefix

---

ci/kokoro/docker/build-in-docker-quickstart-bazel.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5146)

ci: use GCS Bazel cache on Linux quickstart builds

---

google/cloud/storage/bucket_metadata.cc
google/cloud/storage/examples/cleanup_stale_buckets_test.cc
google/cloud/storage/examples/storage_bucket_samples.cc
google/cloud/storage/examples/storage_examples_common.cc
google/cloud/storage/examples/storage_examples_common.h
google/cloud/storage/testbench/gcs_bucket.py

The examples create buckets and sometimes fail to clean after
themselves, either because they are buggy, are terminated before they
can cleanup, or any other reason. With this change we remove any stale
buckets, i.e., buckets created over two days ago and that match the
prefix used by the examples.
I had to fix some timestamps hardcoded in the testbench, and improve
the debug logging to troubleshoot the problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5149)

test: automatically cleanup stale example buckets

---

google/cloud/storage/benchmarks/benchmark_make_random_test.cc
google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc
google/cloud/storage/examples/cleanup_stale_buckets_test.cc
google/cloud/storage/examples/storage_bucket_acl_samples.cc
google/cloud/storage/examples/storage_bucket_cors_samples.cc
google/cloud/storage/examples/storage_bucket_default_kms_key_samples.cc
google/cloud/storage/examples/storage_bucket_iam_samples.cc
google/cloud/storage/examples/storage_bucket_requester_pays_samples.cc
google/cloud/storage/examples/storage_bucket_samples.cc
google/cloud/storage/examples/storage_default_object_acl_samples.cc
google/cloud/storage/examples/storage_event_based_hold_samples.cc
google/cloud/storage/examples/storage_examples_common.cc
google/cloud/storage/examples/storage_examples_common.h
google/cloud/storage/examples/storage_examples_common_test.cc
google/cloud/storage/examples/storage_lifecycle_management_samples.cc
google/cloud/storage/examples/storage_notification_samples.cc
google/cloud/storage/examples/storage_object_acl_samples.cc
google/cloud/storage/examples/storage_object_cmek_samples.cc
google/cloud/storage/examples/storage_object_samples.cc
google/cloud/storage/examples/storage_object_versioning_samples.cc
google/cloud/storage/examples/storage_policy_doc_samples.cc
google/cloud/storage/examples/storage_quickstart.cc
google/cloud/storage/examples/storage_retention_policy_samples.cc
google/cloud/storage/examples/storage_website_samples.cc
google/cloud/storage/testing/random_names.cc
google/cloud/storage/testing/storage_integration_test.cc
google/cloud/storage/testing/storage_integration_test.h
google/cloud/storage/tests/grpc_integration_test.cc
google/cloud/storage/tests/thread_integration_test.cc

The integration tests could, but rarely did, use a different prefix for
the random bucket names used in the test. That makes it hard to clean
these up later. In this change we fix the prefix and do some refactoring
to always use `storage::testing::MakeRandomBucketName()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5151)

cleanup: fix bucket name prefix in integration tests

---

google/cloud/spanner/internal/connection_impl_test.cc

Reduce the amount of per-test boilerplate, largely by replacing lambdas
and places where protos were directly constructed with matchers and helpers.
* Add helper functions to create a `MockGrpcReader` that returns a
sequence of responses or an error status.
* Add and consistently use matchers for various request fields.
* Consistently use `StatusIs`.
* Use other helpers: `MakeCommitResponse`, `MakeTestTransaction`, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5150)

test(spanner): refactor connection_impl_test

---

google/cloud/storage/benchmarks/benchmark_make_random_test.cc
google/cloud/storage/benchmarks/benchmark_utils.cc
google/cloud/storage/benchmarks/benchmark_utils.h
google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc
google/cloud/storage/benchmarks/storage_parallel_uploads_benchmark.cc
google/cloud/storage/benchmarks/storage_shard_throughput_benchmark.cc
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
google/cloud/storage/benchmarks/throughput_options.cc
google/cloud/storage/benchmarks/throughput_options.h
google/cloud/storage/benchmarks/throughput_options_test.cc

Use a single prefix for all the benchmark buckets, that will make it
easier to clean them up later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5158)

cleanup(storage): normalize benchmark bucket prefix

---

google/cloud/storage/CMakeLists.txt
google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/examples/storage_examples_common.cc
google/cloud/storage/examples/storage_examples_common.h
google/cloud/storage/examples/storage_examples_unit_tests.bzl
google/cloud/storage/storage_client_testing.bzl
google/cloud/storage/storage_client_unit_tests.bzl
google/cloud/storage/testing/remove_stale_buckets.cc
google/cloud/storage/testing/remove_stale_buckets.h
google/cloud/storage/testing/remove_stale_buckets_test.cc

Move the functions to remove stale buckets to a common library so I can
use it to remove the stale buckets created by any integration tests and
benchmarks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5156)

refactor(storage): cleanup stale buckets code moves

---

ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build.sh

Bazel has better test-result caching, and these tests against production
can be slow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5155)

ci: use Bazel for GCS+gRPC integration build

---

google/cloud/storage/emulator/database.py
google/cloud/storage/emulator/emulator.py
google/cloud/storage/emulator/requirements.txt
google/cloud/storage/emulator/rest_server.py
google/cloud/storage/emulator/tests/test_utils.py
google/cloud/storage/emulator/tests_entry.py
google/cloud/storage/emulator/utils/__init__.py
google/cloud/storage/emulator/utils/acl.py
google/cloud/storage/emulator/utils/error.py
google/cloud/storage/emulator/utils/generation.py

This PR adds:
- Init for `Database`
- Entry point for `emulator` and `REST`
- `generation` to deal with precondition and generation in request.
- Unit tests
- `FakeRequest` to mimic the structure of a `Flask` request. It will be added more feature in later PRs.
Related to #4751
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5124)

test(storage): add more utils for gcs emulator

---

google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc
google/cloud/storage/testing/storage_integration_test.cc
google/cloud/storage/testing/storage_integration_test.h
google/cloud/storage/tests/bucket_integration_test.cc

Remove stale buckets created by the integration tests and/or the
benchmarks. In both cases I picked one of the integration tests
(`bucket_integration_test`) and one of the benchmarks
(`storage_file_transfer_benchmark`) to perform the cleanup. Doing this
in each test or benchmark is just duplication of work and asking for
"thundering herd"-type problems.
Fixes #4905
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5160)

test(storage): remove stale buckets

---

google/cloud/bigtable/examples/bigtable_examples_common.cc
google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
google/cloud/bigtable/examples/instance_admin_async_snippets.cc
google/cloud/bigtable/examples/table_admin_iam_policy_snippets.cc
google/cloud/storage/internal/bucket_requests.cc
google/cloud/storage/internal/http_response.cc
google/cloud/storage/notification_metadata.cc
google/cloud/storage/oauth2/service_account_credentials.cc

Part of the work for: #5121
This uses `absl::StrJoin` where it does not require too much refactoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5159)

refactor: use absl::StrJoin in simple cases

---

google/cloud/pubsub/internal/subscription_concurrency_control.cc
google/cloud/pubsub/internal/subscription_concurrency_control_test.cc
google/cloud/pubsub/internal/subscription_session_test.cc
google/cloud/pubsub/samples/samples.cc

When shutting down, a subscription session should wait for the callbacks
to return, in addition to waiting for the `AckHandler` to be used (i.e.
either `ack()` or `nack()` gettting called). Without this change it is
very easy to use the callbacks incorrectly, as calling
`std::move(h).ack()` eary in the function may start the shutdown process
and delete objects used later in the function.
Fixes #5148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5161)

feat(pubsub): wait for callback return *and* handler

---

google/cloud/spanner/client.h

The example showing how to use a custom retry policy was implemented,
but not referenced from the Doxygen documentation.
Fixes #5162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5164)

doc(spanner): use custom retry example

---

ci/kokoro/docker/build-in-docker-quickstart-cmake.sh

Currently `HEAD` for `vcpkg` is broken for us, and the latest release
does not support Cloud Pub/Sub. I am pinning to the last version that is
*not* broken as a workaround.
See microsoft/vcpkg#13790 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5167)

ci: pin vcpkg to specific SHA as workaround

---

google/cloud/storage/emulator/gcs/__init__.py
google/cloud/storage/emulator/gcs/bucket.py
google/cloud/storage/emulator/requirements.txt
google/cloud/storage/emulator/tests/test_gcs.py
google/cloud/storage/emulator/tests/test_utils.py
google/cloud/storage/emulator/utils/common.py

This PR adds:
- Initialization for `Bucket`.
- Some helper functions to support REST `fields` completely. ( Now we can do something like `fields=kind, items(acl(role, entity), name)`)
Related to #4751 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5166)

test(storage): add init bucket and filter_reponse

---

google/cloud/pubsub/samples/samples.cc

We prefer using condition variables over promises and futures in the
sample code, as C++ developers should be familiar with the former, but
may not be familiar with the latter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5178)

doc(pubsub): use codition variables in sample code

---

google/cloud/future_generic.h
google/cloud/future_generic_test.cc
google/cloud/internal/future_impl.h

We do not need the `&&` and `const&` overloads, this makes the code
simpler *and* it compiles with MSVC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5182)

cleanup(common): simplify promise::set_value()

---

google/cloud/CMakeLists.txt
google/cloud/completion_queue.h
google/cloud/google_cloud_cpp_grpc_utils.bzl
google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
google/cloud/internal/async_read_write_stream_impl.h
google/cloud/internal/async_read_write_stream_impl_test.cc

Implement a wrapper for bi-directional, asynchronous, streaming RPCs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5183)

feat(common): wrapper for bi-dir async streaming RPCs

---

google/cloud/pubsub/integration_tests/CMakeLists.txt
google/cloud/pubsub/integration_tests/pubsub_client_integration_tests.bzl
google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
google/cloud/pubsub/internal/subscriber_logging.cc
google/cloud/pubsub/internal/subscriber_logging.h
google/cloud/pubsub/internal/subscriber_logging_test.cc
google/cloud/pubsub/internal/subscriber_metadata.cc
google/cloud/pubsub/internal/subscriber_metadata.h
google/cloud/pubsub/internal/subscriber_metadata_test.cc
google/cloud/pubsub/internal/subscriber_stub.cc
google/cloud/pubsub/internal/subscriber_stub.h
google/cloud/pubsub/testing/mock_subscriber_stub.h

This adds `AsyncStreamingPull()`, a new member function to start a
streaming pull request. This is a bi-directional streaming RPC. It can
(and soon will) be used to receive messages, update leases, nack
messages, and ack messages. It also implements flow control from the
server side, simplifying some of the library code.
Part of the work for #5026
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5188)

feat(pubsub): add streaming pull function to stub

---

google/cloud/storage/internal/http_response_test.cc
google/cloud/storage/oauth2/authorized_user_credentials_test.cc
google/cloud/storage/oauth2/compute_engine_credentials_test.cc
google/cloud/storage/oauth2/service_account_credentials_test.cc

EXPECT_STATUS_OK prints the full status on failure instead of just the code.
In some places we were redundantly doing both and I removed the EXPECT_EQ.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5209)

test: replace EXPECT_EQ(kOk) with EXPECT_STATUS_OK

---

google/cloud/storage/benchmarks/storage_benchmarks.bzl
google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
google/cloud/storage/benchmarks/throughput_experiment.cc
google/cloud/storage/benchmarks/throughput_experiment_test.cc
google/cloud/storage/benchmarks/throughput_result.cc
google/cloud/storage/benchmarks/throughput_result.h
google/cloud/storage/benchmarks/throughput_result_test.cc

This may give us more information if googleapis#5202 recurs.
coryan: one thing that changed is the PrintAsCsv() format, is that going
to mess up any of your analysis? Should I change it?
INSERT,3145728,2097152,4194304,1,0,GRPC,234000,345000,OOR-status-message [OUT_OF_RANGE]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5203)

test(storage): store the full Status in ThroughputResult

---

google/cloud/spanner/internal/connection_impl.cc
google/cloud/spanner/internal/connection_impl_test.cc

The streaming call allows us to properly resume the operation via
`PartialResultSet::resume_token` (already handled lower in the stack).
part of #4714 (it almost fixes it, I just need to tweak some timeouts).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5197)

fix(spanner): use `ExecuteStreamingSql`for PDML operations

---

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
google/cloud/pubsub/internal/streaming_subscription_batch_source.h
google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc

Found some race conditions when using this against production.
Apparently the timing is different enough from the emulator that these
do not show up in the emulator even when running thousands of times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5210)

fix(pubsub): streaming pull race conditions

---

google/cloud/spanner/benchmarks/benchmarks_config_test.cc
google/cloud/spanner/bytes_test.cc
google/cloud/spanner/client_test.cc
google/cloud/spanner/database_admin_client_test.cc
google/cloud/spanner/database_admin_connection_test.cc
google/cloud/spanner/instance_admin_client_test.cc
google/cloud/spanner/instance_admin_connection_test.cc
google/cloud/spanner/internal/merge_chunk_test.cc
google/cloud/spanner/internal/partial_result_set_resume_test.cc
google/cloud/spanner/internal/partial_result_set_source_test.cc
google/cloud/spanner/internal/session_pool_test.cc
google/cloud/spanner/internal/spanner_stub_test.cc
google/cloud/spanner/numeric_test.cc
google/cloud/spanner/results_test.cc
google/cloud/spanner/row_test.cc
google/cloud/spanner/sql_statement_test.cc
google/cloud/spanner/testing/cleanup_stale_databases_test.cc
google/cloud/spanner/timestamp_test.cc
google/cloud/spanner/value_test.cc

This was mostly pretty mechanical, a couple files that might deserve a bit more attention:
* `bytes_test.cc`: uses `ContainsRegex` instead of two `HasSubstr` calls. That imposes an order on the two substrings that did not previously exist but it LGTM and passes.
* `numeric_test.cc`: replaced the `HasStatus` matcher with the equivalent `StatusIs` invocations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5211)

test: use `StatusIs` matcher in spanner tests

---

ci/kokoro/docker/build-in-docker-bazel.sh

I think I incompletely renamed a bash function. Because this feature is
rarely used this went unnoticed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5215)

ci: fix build script for Bazel

---

README.md
ci/generate-markdown/generate-readme.sh

Link directly to the quickstart guides from the top-level README. Also
include brief "make install" instructions, with some caveats, and links
to the more detailed instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5216)

doc: improve top-level README links

---

google/cloud/pubsub/subscriber.h

This code sample doesn't compile, I think it's better to just use the
quickstart sample.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5217)

doc(pubsub): Link subscriber doc to the quickstart

---

ci/kokoro/docker/build-in-docker-cmake.sh

This can help us detect any changes introduced by the build scripts,
such as modifications to the `*.bzl` files that happen after we invoke
`ci/check-style.sh`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5219)

ci: check for diffs post-build

---

CHANGELOG.md
google/cloud/pubsub/internal/streaming_subscription_batch_source.h
google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
google/cloud/pubsub/internal/subscription_session_test.cc
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscription_options.cc
google/cloud/pubsub/subscription_options.h
google/cloud/pubsub/subscription_options_test.cc

**BREAKING CHANGE**:
* Simplify the message flow control configuration, now that the library uses
streaming pulls, the low water marks are not used. The application developer
simply sets limits for the number of messages (and/or bytes) outstanding,
this limits are propagated to the service, and the service will stop streaming
if too many messages (or bytes) are outstanding. While the Pub/Sub library is
not GA, and this type of change is to be expected, we are close enough to a GA
release that we think highlight them is important.
Fixes #5195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5226)

cleanup(pubsub)!: simplify flow control config

---

google/cloud/storage/oauth2/service_account_credentials.cc
google/cloud/storage/oauth2/service_account_credentials.h
google/cloud/storage/oauth2/service_account_credentials_test.cc

Fixes: #5227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5230)

fix(storage): Make private_key_id optional for JSON credentials

---

google/cloud/storage/internal/grpc_client_failures_test.cc

These passed the PR build because we get false positives (and therefore
ignore) `misc-unused-using-decls` in the PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5240)

test: clang-tidy fixes

---

CHANGELOG.md
google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/batching_publisher_connection_test.cc
google/cloud/pubsub/publisher_option_test.cc
google/cloud/pubsub/publisher_options.h
google/cloud/pubsub/samples/samples.cc

**BREAKING CHANGE**
* Fix inconsistent naming for `PublisherOptions` attributes controlling the
maximum number of messages per batch and the maximum number of bytes per
batch.
Fixes #5196
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5242)

cleanup(pubsub)!: inconsistent names in PublisherOptions

---

CHANGELOG.md
google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/publisher.h
google/cloud/pubsub/publisher_connection_test.cc
google/cloud/pubsub/publisher_option_test.cc
google/cloud/pubsub/publisher_options.h
google/cloud/pubsub/samples/samples.cc

**BREAKING CHANGE**:
* Remove option to disable retries in `Publisher::Publish`. This is redundant as
the application can set a "no retries" retry policy. This is more consistent
with other Cloud Pub/Sub libraries. We include an example showing how to
configure a "no retries" retry policy.
Fixes #5206 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5244)

cleanup(pubsub)!: remove redundant publisher option

---

CHANGELOG.md
google/cloud/pubsub/benchmarks/endurance.cc
google/cloud/pubsub/integration_tests/message_integration_test.cc
google/cloud/pubsub/integration_tests/subscription_lifecycle_test.cc
google/cloud/pubsub/internal/subscription_session.cc
google/cloud/pubsub/internal/subscription_session.h
google/cloud/pubsub/internal/subscription_session_test.cc
google/cloud/pubsub/samples/mock_subscriber.cc
google/cloud/pubsub/samples/pubsub_samples_common.cc
google/cloud/pubsub/samples/pubsub_samples_common.h
google/cloud/pubsub/samples/pubsub_samples_common_test.cc
google/cloud/pubsub/samples/samples.cc
google/cloud/pubsub/subscriber.h
google/cloud/pubsub/subscriber_connection.cc
google/cloud/pubsub/subscriber_connection.h
google/cloud/pubsub/subscriber_connection_test.cc
google/cloud/pubsub/subscriber_test.cc

**BREAKING CHANGE**
* Change the `pubsub::Subscriber` API. A `Subscriber` is now bound to a specific
Cloud Pub/Sub subscription, with a fixed set of `SuscriptionOptions`, just
like a `pubsub::Publisher` is bound to a specific topic and a set of
`PublisherOptions`. In addition to making publishers and subscribers more
symmetrical, this makes the library more consistent with the Cloud Pub/Sub
library for other languages. Finally, note that we are planning to rename
`SubscriptionOptions` to `SubscriberOptions` in a future PR too.
Part of the work for #5204 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5247)

cleanup(pubsub)!: make Subscriber more consistent

---

ci/kokoro/docker/build-in-docker-cmake.sh

As discussed in #4230, running clang-tidy on a subset of files produces
some false positives in header files. However, the fix to that also
disabled some warnings for source files. This PR re-enables our full
set of warnings for source files, allowing presubmit to catch more issues
(see #5240 as an example of a break caused by this.)
To test, I forced the relevant section of the build script to run in a local build and added an unnecessary `using` declaration to a `.h` and `.cc ` file.  Note that both are scanned but the warning only appears for the `.cc` file (which would have been missed prior to this PR)
```
2020-10-14T01:27:21Z: Run clang-tidy on changed files in a presubmit build 
clang-tidy -p=cmake-out/ci-fedora-install-31-clang-tidy …
```

test: enable all clang-tidy presubmit warnings for source files

---

google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc

Soon I will need more fine grained control over the start steps for
`pubsub_internal::StreamingSubscriptionBatchSource`, this change just
prepares the test.
This will help with #5267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5282)

test(pubsub): more control over streaming start

---

google/cloud/pubsub/internal/session_shutdown_manager.cc
google/cloud/pubsub/internal/session_shutdown_manager.h
google/cloud/pubsub/internal/streaming_subscription_batch_source.cc

We need to keep the gRPC objects (the client context, the streaming RPC)
alive while an asynchronous request is pending, otherwise we may delete
these objects while gRPC is still using them.
Fixes #5287
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5291)

fix(pubsub): crashes for fire & forget sessions

---

google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
google/cloud/pubsub/internal/streaming_subscription_batch_source.h
google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc

For a streaming pull, the service may not be able to report some errors,
e.g, whether the caller has the right permissions, or whether the
subscription exists, until the first `Read()`. This change modifies the
startup sequence to include the first read. Inlining all of this in a
single lambda seemed too ugly, so we unroll into several callbacks.
Fixes #5267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5292)

fix(pubsub): handle errors on first Read()

---

ci/generate-markdown/generate-packaging.sh
doc/packaging.md
doc/setup-development-environment.md

Fixes: #5228
Thanks @hbchai to pointing out the necessity for `libbenchmark-dev`. It
appears that is required for the microbenchmarks, so it should be added
to the list of development dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5298)

bug: Fix building instructions w.r.t. testing

---

ci/kokoro/windows/build-bazel.ps1
google/cloud/storage/internal/policy_document_request.cc
google/cloud/storage/tests/BUILD
google/cloud/storage/tests/CMakeLists.txt
google/cloud/storage/tests/conformance_tests.proto
google/cloud/storage/tests/signed_url_conformance_test.cc
google/cloud/storage/tests/storage_client_integration_tests.bzl

The file was imported from:
https://github.com/googleapis/conformance-tests/blob/d505e92d98f4f319ba774606ac95f693da2145c8/storage/v1/proto/google/cloud/conformance/storage/v1/tests.proto
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294)

test: use protobufs, not json in conformance tests

---

google/cloud/spanner/integration_tests/database_admin_integration_test.cc

A `repeated` field size of 1 allows us to inspect the 0th element.
Also use `HasSubstr` in the expectation as the returned DDL statement
can have whitespace differences against the `UpdateDatabase()` argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5301)

test(spanner): correct guard on UpdateDatabaseDdlMetadata expectation

---

google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/batching_publisher_connection.h
google/cloud/pubsub/internal/batching_publisher_connection_test.cc
google/cloud/pubsub/internal/ordering_key_publisher_connection.cc
google/cloud/pubsub/internal/ordering_key_publisher_connection.h
google/cloud/pubsub/internal/ordering_key_publisher_connection_test.cc
google/cloud/pubsub/internal/rejects_with_ordering_key.cc
google/cloud/pubsub/internal/rejects_with_ordering_key.h
google/cloud/pubsub/internal/rejects_with_ordering_key_test.cc
google/cloud/pubsub/mocks/mock_publisher_connection.h
google/cloud/pubsub/publisher.h
google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection.h
google/cloud/pubsub/publisher_options.h
google/cloud/pubsub/samples/samples.cc

While a batch of messages with the same ordering key is pending (i.e.
sent but the response is not received) any additional messages should be
batched. Add an example showing how to use the `ResumePublish()` API.
Fixes #4803 and #4640
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5304)

feat(pubsub): sequence batches with ordering keys

---

ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
ci/kokoro/macos/build-quickstart-cmake.sh
ci/kokoro/windows/build-cmake-dependencies.ps1

Update to a more recent version (circa 2020-10-01), and use the
same version for Windows and Linux builds. The macOS script
is not used, but might as well update it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5307)

ci: update vcpkg revision

---

google/cloud/storage/internal/curl_handle.cc
google/cloud/storage/internal/curl_handle_test.cc

We were sometimes seeing `CURLE_HTTP2` "Error in the HTTP2 framing
layer" errors when downloading large (20G) files using HTTP2. Details
captured in b/171350177.
Retying these errors works around the problem. Changed the default
behavior to retry all curl errors that aren't explicitly handled
separately in the switch statement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5312)

fix: retry unexpected curl errors

---

google/cloud/storage/internal/access_control_common_parser.h

This was accidentally introduced today in https://github.com/googleapis/google-cloud-cpp/pull/5305. A big PR; easy to overlook this. The code works fine externally, but it breaks during our import script.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5313)

fix: include nlohmann with angle brackets

---

google/cloud/pubsub/samples/samples.cc

Now that ordering keys are GA we can enable the examples in production.
Fixes #5300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5310)

cleanup(pubsub): enable ordering examples in production

---

google/cloud/storage/tests/signed_url_conformance_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5316)

fix: avoid error_code, which doesn't exist internally

---

google/cloud/storage/tests/CMakeLists.txt
google/cloud/storage/tests/signed_url_conformance_test.cc
google/cloud/storage/tests/storage_client_integration_tests.bzl

We should always list all the tests in the CMake files, or they are not
included in the generated .bzl files. This is slightly annoying for
tests that only make sense when the GCS+gRPC plugin is enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5322)

cleanup(storage): always list all tests

---

google/cloud/pubsub/benchmarks/endurance.cc

We need more than 31 bits (or 32 bits) to count messages, smaller
counters overflow in a matter of hours.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5323)

cleanup(pubsub): use bigger counters in benchmark

---

google/cloud/internal/background_threads_impl.cc
google/cloud/internal/background_threads_impl_test.cc

Once we join the threads in a
`internal::AutomaticallyCreatedBackgroundThreads` we should clear the
pool to avoid crashes in the destructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5324)

fix(common): crashes on background thread shutdown

---

google/cloud/pubsub/internal/session_shutdown_manager.cc
google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
google/cloud/pubsub/internal/subscription_session.cc

During development I left a number of (optional) logging messages, most
of these are not useful for customers, so I am either deleting them (if
I thought even we would not need them), or moving them to `TRACE` level,
which is compiled-out anyway.
Fixes #4934
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5330)

cleanup(pubsub): disable trace logs

---

google/cloud/internal/pagination_range.h
google/cloud/internal/pagination_range_test.cc
google/cloud/pubsub/ack_handler.h
google/cloud/pubsub/publisher_connection.cc
google/cloud/pubsub/publisher_connection.h
google/cloud/pubsub/subscriber_connection.cc
google/cloud/pubsub/subscriber_connection.h
google/cloud/pubsub/subscription_admin_connection.cc
google/cloud/pubsub/subscription_admin_connection.h
google/cloud/pubsub/topic_admin_connection.cc
google/cloud/pubsub/topic_admin_connection.h

We expect applications to derive (typically mocks) from the
`*Connection` classes. To prevent breaking such applications in the
future these classes should not use pure-virtual functions, they should
return `kUnimplemented`.
Fixes #4817
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5329)

cleanup(pubsub): no pure virtuals in `*Connection`

---

google/cloud/pubsub/BUILD
google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/internal/subscription_message_queue.cc
google/cloud/pubsub/internal/subscription_message_queue.h
google/cloud/pubsub/internal/subscription_message_queue_test.cc

Messages without an ordering key are scheduled
in parallel, and therefore can be executed out of
order. Messages with an ordering key are scheduled
in sequence for the same ordering key. That is,
messages with key `key1` will be scheduled one
at a time, but messages with other keys may be
scheduled in parallel.
Fixes #5044 and fixes #5263 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5327)

feat(pubsub): preserve order for messages with ordering keys

---

google/cloud/storage/examples/storage_policy_doc_samples.cc

The submit element shouldn't have the `name` attribute - otherwise the
browser generates a respective field in the POST request and violates
the policy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5348)

test: fix unnecessary name attribute from submit

---

ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
ci/kokoro/macos/build-bazel.sh
ci/kokoro/macos/build-quickstart-bazel.sh
ci/kokoro/windows/build-bazel.ps1
ci/kokoro/windows/build-quickstart-bazel.ps1

Sometimes the bazel builds fail because they cannot fetch some
dependencies, even after a successful `bazel fetch ...`. I found all
these additional dependencies using `bazel build --nofetch ...`, they
all seem to be SDK-type things.
Part of the work for #4045
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5346)

ci: fetch more dependencies for Bazel builds

---

google/cloud/storage/internal/policy_document_request.cc
google/cloud/storage/internal/policy_document_request_test.cc
google/cloud/storage/tests/signed_url_conformance_test.cc
google/cloud/storage/tests/v4_signatures.json

This fixes #5073.
Turned out we were escaping too much. Json is already escaping the
backslashes for us, so no need to do it on our own. It was verified
againts production, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5347)

chore: update GCS V4 signed URLs conformance tests

---

ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
ci/kokoro/macos/build-quickstart-cmake.sh
ci/kokoro/windows/build-cmake-dependencies.ps1

Update vcpkg-based builds to get gRPC-1.33.x, this version includes
fixes for crashes during shutdown on some MSVC configurations.
Part of the work for #3933. I think it fixes it, but we need to wait after merging this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5354)

chore: update vcpkg-based to get newest gRPC

---

release/README.md

This is an item for discussion.  We may chose to *not* do this.
I think we should update the API baseline before each release.
The purpose of this baseline is to tell us if we are breaking the
API since the last release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5343)

doc: update the API baseline as part of releasing

---

ci/kokoro/docker/Dockerfile.fedora
ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/docker/Dockerfile.fedora-libcxx-msan

The msan docker image is always used with Fedora:33, changed the default to say that.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5366)

ci: restore ccache to fedora builds

---

google/cloud/pubsub/publisher.cc

Thanks to @remyabel for pointing these out.
I searched for others, the remaining ones seem legit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5364)

cleanup(pubsub): remove obsolete TODOs

---

google/cloud/pubsub/message.h
google/cloud/pubsub/message_test.cc
google/cloud/pubsub/samples/samples.cc

Avoids allocations and data copying when the application
just adds a few attributes inline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5365)

feat(pubsub): more efficient message builder

---

google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/batching_publisher_connection.h

Reduce contention when building the batch. Minimize memory allocation
overhead by batching directly into the request proto.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5367)

feat(pubsub): more efficient batching

---

ci/kokoro/docker/Dockerfile.ubuntu
ci/kokoro/docker/build.sh

The build is running on Fedora:31, which is going EOL very soon. We
cannot upgrade to Fedora:32 or 33 because they come with clang >= 10,
and there is a bug with tsan with those compilers.
Fixes #5132 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5370)

ci: move tsan build to Ubunt:18.04

---

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc

This gives us better throughput for subscribers, as acks/nacks open the
window to receive more messages. In addition, it makes not sense to wait
for more messages before sending the requests, as (a) subscribers do not
usually have other messages to send back to Cloud Pub/Sub, and (b) we
have to buffer any additional ack/nacks in the application because gRPC
only permits one Write() call at a time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5378)

feat(pubsub): do not delay acks and nacks

---

CHANGELOG.md
google/cloud/storage/bucket_metadata.h

Before GA the "Uniform Bucket Level Access" feature went by another name
(Bucket Policy Only), the corresponding field was (more or less) born
deprecated, and has not worked quite right since inception. This PR
announces that we will remove it in the release about 90 days from now.
I also noticed that UBLA was still marked "not GA", which was simply
wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5381)

doc(storage): announce removal of bucket_policy_only

---

google/cloud/pubsub/internal/subscriber_logging.cc
google/cloud/pubsub/internal/subscriber_logging.h
google/cloud/pubsub/internal/subscriber_logging_test.cc
google/cloud/pubsub/subscriber_connection.cc
google/cloud/pubsub/subscriber_connection_test.cc
google/cloud/pubsub/subscription_admin_connection.cc

The streaming RPCs produce an overwhelming amount of logging. Sometimes
it is useful to just log the start of the stream, leaving out the
details of each `Read()` and `Write()` call. We already have a
documented way to split the configuration, so I just re-used it in
Pub/Sub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5391)

feat(pubsub): split logging streaming RPCS

---

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc

Retry CreateDatabase() calls during benchmark setup that fail with
UNAVAILABLE. Up to three retries, with backoff intervals of 0s, 1s,
and 2s respectively.
Part of #4010.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5395)

test(spanner): deflake benchmark database creation

---

google/cloud/pubsub/connection_options.cc

My experiments (unpublished, in a branch), show that we hardly ever need
as many channels as the previous default set this to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5402)

feat(pubsub): reduce default channel count

---

google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/batching_publisher_connection.h
google/cloud/pubsub/internal/batching_publisher_connection_test.cc

`pubsub_internal::BatchingPublisherConnection` failed to flush before
accepting a message that would exceed the total bytes limit.
Fixes #5408
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5409)

fix(pubsub): sometimes published oversized batches

---

google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/batching_publisher_connection.h
google/cloud/pubsub/internal/batching_publisher_connection_test.cc

We were flushing after each `Publisher::ResumePublish()` which could
reorder messages. We need to track "corked because there was an error"
(which is affected by `Publisher::ResumePublish()`) and "corked because
we are waiting for a response", which should not.
Fixes #5412
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5415)

fix(pubsub): keep corked after ResumePublish

---

google/cloud/pubsub/internal/subscription_concurrency_control.cc
google/cloud/pubsub/internal/subscription_concurrency_control.h
google/cloud/pubsub/internal/subscription_concurrency_control_test.cc
google/cloud/pubsub/internal/subscription_message_queue.cc
google/cloud/pubsub/internal/subscription_message_queue.h
google/cloud/pubsub/internal/subscription_message_queue_test.cc
google/cloud/pubsub/internal/subscription_message_source.h
google/cloud/pubsub/testing/mock_subscription_message_source.h

Remove some unused arguments, that cleans up the internal interfaces,
and saves us some computation in the critical path. Not much, but every
bit counts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5422)

cleanup(pubsub): simplify SubscriptionMessageSource

---

google/cloud/pubsub/benchmarks/throughput.cc

Add options to control more of the low-level configuration of the client
library. Some of these have no effect at the moment (e.g.
--subscriber-io-channels), but it is easier to merge them as they are.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5419)

feat(pubsub): more throughput benchmark options

---

google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
google/cloud/storage/emulator/database.py
google/cloud/storage/emulator/emulator.py
google/cloud/storage/emulator/gcs/holder.py
google/cloud/storage/emulator/grpc_server.py
google/cloud/storage/emulator/utils/common.py
google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/tests/CMakeLists.txt
google/cloud/storage/tests/grpc_integration_test.cc
google/cloud/storage/tools/run_testbench_utils.sh

This PR:
- adds support for grpc.
- makes `grpc_integration_test` testing with both `media` and `metadata` since it is our ultimate goal.
- `CI` changes
`gevent` and `gRPC` can not work together, so I change the worker to `sync` and use `threads`. I also add a endpoint `start_grpc` to start the grpc server. The reason is `Gunicorn` will spawn a new subprocess when running `Flask` server. If we start `gRPC` server before the spawn of the subprocess, it's nearly impossible to share the `database` with the new subprocess because Python will copy everything in the memory from the parent process to the subprocess ( So we have 2 separate instance of `database` ). The endpoint will start the `gRPC` server in the same subprocess so there is only one instance of `database`.
Part of #4751 
---
This …

test(storage): add support for grpc

---

ci/kokoro/install/Dockerfile.centos-7
ci/kokoro/install/Dockerfile.centos-8
ci/kokoro/install/Dockerfile.debian-buster
ci/kokoro/install/Dockerfile.debian-stretch
ci/kokoro/install/Dockerfile.fedora
ci/kokoro/install/Dockerfile.opensuse-leap
ci/kokoro/install/Dockerfile.opensuse-tumbleweed
ci/kokoro/install/Dockerfile.ubuntu-bionic
ci/kokoro/install/Dockerfile.ubuntu-focal
ci/kokoro/install/Dockerfile.ubuntu-xenial
doc/packaging.md

Also removes reference to `/var/tmp` which makes no sense in context of the
packaging instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5433)

cleanup(doc): Make abseil packaging instructions consistent

---

google/cloud/pubsub/internal/batching_publisher_connection.cc
google/cloud/pubsub/internal/batching_publisher_connection.h
google/cloud/pubsub/internal/batching_publisher_connection_test.cc
google/cloud/pubsub/internal/sequential_batch_sink_test.cc
google/cloud/pubsub/publisher_connection.cc
google/cloud/testing_util/CMakeLists.txt
google/cloud/testing_util/async_sequencer.cc
google/cloud/testing_util/async_sequencer.h
google/cloud/testing_util/google_cloud_cpp_testing.bzl

This changes `pubsub_internal::BatchingPublisherConnection` to send
batches to a `BatchSink`. With this change the batches are always within
the constraints defined by the application.
I refactored some common testing code to `testing_utils`.
Part of the work for #5413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5438)

refactor(pubsub): use BatchSink to send batches 

---

google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
google/cloud/storage/emulator/database.py
google/cloud/storage/emulator/emulator.py
google/cloud/storage/emulator/gcs/holder.py
google/cloud/storage/emulator/gcs/object.py
google/cloud/storage/emulator/grpc_server.py
google/cloud/storage/emulator/tests/test_gcs.py
google/cloud/storage/emulator/tests/test_utils.py
google/cloud/storage/emulator/utils/common.py
google/cloud/storage/examples/CMakeLists.txt
google/cloud/storage/tests/CMakeLists.txt
google/cloud/storage/tests/grpc_integration_test.cc
google/cloud/storage/tools/run_testbench_utils.sh

Cherry-pick #5414 
---
Fixed the location of `testbench.log` in 42d223f
---
cbeb3c1
When `context is not None`, `rest_only` is always `None`
https://github.com/googleapis/google-cloud-cpp/blob/82eb19f09194b4e3efc4ed1201dcf652e1dc1712/google/cloud/storage/emulator/gcs/object.py#L141-L142
I don't check `if rest_only is not None` in `rest_metadata` so it causes an error here
https://github.com/googleapis/google-cloud-cpp/blob/82eb19f09194b4e3efc4ed1201dcf652e1dc1712/google/cloud/storage/emulator/gcs/object.py#L372
Step to reproduce 
```sh
bazel run //google/cloud/storage/examples:storage_grpc_sample -- grpc-read-write bucket
bazel run //google/cloud/storage/examples:storage_object_sample -- list-objects bucket
```
In the CI, this error will take place when there is a request for an object's …

test(storage): emulator supports gRPC

---

google/cloud/pubsub/benchmarks/throughput.cc

Include the messages per second in each report line, one could compute
this manually, but that is a drag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5451)

feat(pubsub): more details in throughput benchmark

---

google/cloud/pubsub/internal/subscription_lease_management.h
google/cloud/pubsub/internal/subscription_lease_management_test.cc

Use `absl::flat_hash_map<>` instead of `std::map<>`, most of the time
the number of items is small, but this yields (by my measurement) a 3%
improvement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5454)

feat(pubsub): improve lease management performance

---

google/cloud/pubsub/benchmarks/throughput.cc

Limit the number of messages per second generated by the publishing
threads, this is useful when we want to avoid the synchronization
overhead of message-based flow control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5447)

feat(pubsub): pace publisher in throughtput benchmark

---

google/cloud/storage/tests/object_resumable_write_integration_test.cc

fixes the CI build until #5460 can be resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5461)

test: disable broken WriteResumeFinalizedUpload test

---

google/cloud/internal/async_read_write_stream_impl_test.cc
google/cloud/testing_util/CMakeLists.txt
google/cloud/testing_util/google_cloud_cpp_testing_grpc.bzl
google/cloud/testing_util/mock_completion_queue_impl.h

I am going to need this class in a new test, refactor to a header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5463)

refactor(common): move CompletionQueue mock

---

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
google/cloud/pubsub/internal/streaming_subscription_batch_source.h
google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc

It is more efficient to send a large `StreamingPullRequest` protos in
the `Write()` calls. Saves in CPU and (more importantly) I/O. The
batching should have no impact to applications with low throughput, as
we only batch for 100ms and the typical deadlines are 100x larger.
This improved throughput by over 50%, at least in my local tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5464)

feat(pubsub): batch acks and nacks in streams

---

google/cloud/pubsub/internal/subscription_concurrency_control.cc
google/cloud/pubsub/internal/subscription_concurrency_control.h

A lighter-weight callable passed through, avoid copying `callback_`,
avoid creating unnecessary `std::shared_ptr<>` instances. None of these
things are terribly slow, but they add contention and we have to deal
with (ideally) 800,000 events/second.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5458)

feat(pubsub): more efficient callback dispatch

---

ci/kokoro/docker/check-abi.sh

Fixes: #5470
`gzip` files are binary and the default diff tool will show them as different
even if they are "identical". This uses `zdiff` to compare them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5472)

ci: only update ABI if there were changes

---

google/cloud/spanner/integration_tests/client_integration_test.cc
google/cloud/spanner/integration_tests/database_admin_integration_test.cc
google/cloud/spanner/samples/samples.cc
google/cloud/spanner/testing/database_integration_test.cc

This only entails changes to integration tests and samples as the
database-admin interfaces use protobufs directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5471)

feat(spanner): Point-In-Time Recovery (lite)

---

google/cloud/pubsub/internal/subscription_message_queue.cc
google/cloud/pubsub/internal/subscription_message_queue.h
google/cloud/pubsub/internal/subscription_message_source.h
google/cloud/pubsub/testing/mock_subscription_message_source.h

I missed these in earlier cleanups, acks and nacks do not need to return
a future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5489)

cleanup(pubsub): remove unused return value

---

doc/cpp-style-guide.md

Recent (months) updates to the
[GSG](https://google.github.io/styleguide/cppguide.html) have made
several of our differences unnecessary to note, because these
differences are now allowed by the GSG. I've removed these unneeded
sections. Specifically:
* Non-const reference arguments are now allowed and encouraged for
in/out params.
* Preincrement is explicitly preferred unless the postincrement
semantics are explicitly needed.
* The style guide prefers enumerator names `kLikeThis`, and we also
prefer that and it's enforced by our .clang-tidy config. Out styleguide
was just out of date on this point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5490)

doc(styleguide): remove sections obsoleted by GSG

---

google/cloud/storage/tests/object_resumable_write_integration_test.cc

per Carlos' suggestion on #5461
the test remains disabled for GRPC.
also added a TODO that should have been there from the start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5487)

test: re-enable WriteResumeFinalizedUpload test for REST API

---

generator/internal/descriptor_utils.cc
generator/internal/descriptor_utils_test.cc

Correct std::bool const& to just bool (and double, float, and enums)
Correct std::int32_t const& to just std::int32_t. (and all integral types)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5480)

fix(generator): correct method signature handling of pod values

---

ci/kokoro/docker/Dockerfile.fedora
ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
ci/kokoro/docker/Dockerfile.ubuntu
ci/kokoro/windows/build-bazel-dependencies.ps1
google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
google/cloud/storage/emulator/BUILD
google/cloud/storage/emulator/requirements.txt
google/cloud/storage/emulator/tests/test_gcs.py
google/cloud/storage/emulator/tests/test_utils.py

Since `Bazel` does not fully support `pytest`, I converted all those tests to `unittest`.
I have some questions
- Should we convert all the code that are using `testbench` to `emulator` ?
- When will we remove the `testbench` directory ?
Part of #4751 
We finally reach a milestone in `Complete GCS+gRPC plugin`. From now, we could implementing `GCS+gRPC` without worrying about testing 🚀
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5453)

test(storage): add emulator unit tests and cleanup

---

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc

The service closes streaming pull requests with `kUnavailable` if there
is no data to pull. We should not treat these as failures (not even as
transient failures), because we showed that we successfully connected to
the service, that the subscription exists, and that we have permissions
to pull data. The "problem" is that we do not have data yet.
Fixes #5506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5510)

fix(pubsub): treat some kUnavailable as success

---

ci/kokoro/docker/Dockerfile.fedora
ci/kokoro/docker/Dockerfile.fedora-install
ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
ci/kokoro/docker/Dockerfile.ubuntu

Fixes: #5238
- Add `ARG NCPU` in places where it was missing; seems inconsistent otherwise
- Removed redundant package install
- Fixed comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5516)

cleanup(ci): fix nits in Dockerfiles

---

google/cloud/spanner/database_admin_connection.cc
google/cloud/spanner/database_admin_connection.h
google/cloud/spanner/database_admin_connection_test.cc
google/cloud/spanner/instance_admin_connection.cc
google/cloud/spanner/instance_admin_connection.h
google/cloud/spanner/instance_admin_connection_test.cc

Salvage part of the abandoned #5112 so that `DatabaseAdminConnection`
and `InstanceAdminConnection` both have a `BackgroundThreads` handle
from which they can obtain a `CompletionQueue` to execute the pieces
of long-running operations.
Part of #4038.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5519)

cleanup(spanner): plumb ConnectionOptions into admin connection classes

---

google/cloud/storage/tests/object_file_integration_test.cc

I am trying to split unrelated change out of #5518 
This enables `TEST_F(ObjectFileIntegrationTest, UploadFileBinary)` against emulator since the new emulator has already supported binary data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5520)

test(storage): enable `TEST_F(ObjectFileIntegrationTest, UploadFileBinary)` against emulator

---

google/cloud/storage/internal/grpc_resumable_upload_session_url.cc
google/cloud/storage/internal/grpc_resumable_upload_session_url.proto

Avoid `package google.cloud.storage.v1.internal` so as not to
conflict with the `google::cloud::storage::v\d+` inline namespace.
Use `package google.storage.v1.internal` instead, which creates a
sub-namespace within the existing proto `google::storage::v1`.
Fixes #5350.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5530)

cleanup(storage): use google.storage.v1.internal for internal protos

---

google/cloud/storage/emulator/emulator.py
google/cloud/storage/emulator/gcs/holder.py
google/cloud/storage/emulator/utils/csek.py

This PR adds csek support for the new emulator.
I have some confusions. In the old testbench ( and also in the new emulator ), the base64 encoded encryption key sha256 is saved. However, on the [website](https://cloud.google.com/storage/docs/json_api/v1/objects) and [proto](https://github.com/googleapis/googleapis/blob/37ba54d7ed4da3052ceff96292631c3b6aae0e63/google/storage/v1/storage_resources.proto#L620-L621) definition file, it is written that `SHA256 hash value of the encryption key.` ( not base64 encoded ). Which one should be saved ?
Part of #4751 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5527)

test(storage): support csek for the new emulator

---

google/cloud/CMakeLists.txt
google/cloud/google_cloud_cpp_grpc_utils.bzl
google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
google/cloud/internal/stream_range.h
google/cloud/internal/stream_range_test.cc

Part of https://github.com/googleapis/google-cloud-cpp/issues/5521
This PR is part of the work needed for resumable streaming RPCs. This PR introduces a generic `StreamRange<T>`, which provides an input range of `T` and an iterator class for iterating it. This is a better, and reusable, version of the `RowStreamIterator` and `TupleStreamIterator` classes in spanner [link](https://github.com/googleapis/google-cloud-cpp/blob/43d6687ab1432ad56420c0292283cd3b615cf96f/google/cloud/spanner/row.h#L309). Indeed, those classes could easily be replaced by aliases to `StreamRange<T>`, except for small API breaks that would result, because those Spanner classes have weird constructors that this one doesn't have. We can discuss whether we want to make that change or not later.
--- …

feat: introduce a generic StreamRange<T>

---

google/cloud/CMakeLists.txt
google/cloud/google_cloud_cpp_common.bzl
google/cloud/google_cloud_cpp_common_unit_tests.bzl
google/cloud/google_cloud_cpp_grpc_utils.bzl
google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl

`StreamRange<T>` doesn't need gRPC, so moving to the "common" target will minimze its deps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5534)

chore: moved stream_range to common to avoid grpc dep

---

google/cloud/status_or.h
google/cloud/status_or_test.cc

This member is useful in generic programming, and it follows the
precedent set by `std::optional::value_type` and
[absl::StatusOr::value_type](https://github.com/abseil/abseil-cpp/blob/e19260fd7dbef881492fd73891e0be5bd4a09b95/absl/status/statusor.h#L184-L187)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5535)

feat: add value_type to StatusOr<T>

---

CHANGELOG.md
generator/integration_tests/golden/database_admin_connection.gcpcxx.pb.cc
generator/integration_tests/golden/database_admin_connection.gcpcxx.pb.h
generator/integration_tests/golden/golden_client_test.cc
generator/internal/connection_generator.cc
google/cloud/internal/pagination_range.h
google/cloud/internal/pagination_range_test.cc
google/cloud/pubsub/subscription_admin_client_test.cc
google/cloud/pubsub/subscription_admin_connection.cc
google/cloud/pubsub/subscription_admin_connection.h
google/cloud/pubsub/topic_admin_client_test.cc
google/cloud/pubsub/topic_admin_connection.cc
google/cloud/pubsub/topic_admin_connection.h
google/cloud/spanner/database_admin_client_test.cc
google/cloud/spanner/database_admin_connection.cc
google/cloud/spanner/database_admin_connection.h
google/cloud/spanner/instance_admin_client_test.cc
google/cloud/spanner/instance_admin_connection.cc
google/cloud/spanner/instance_admin_connection.h
google/cloud/spanner/testing/cleanup_stale_databases_test.cc

Fixes: https://github.com/googleapis/google-cloud-cpp/issues/5537
**BREAKING CHANGE**
This change removes a constructor that not intended to be part of the public API from several "Range" types in the Pub/Sub and Spanner APIs. The affected types are:
* `google/cloud/pubsub/subscription_admin_connection.h`
* `using ListSubscriptionsRange = google::cloud::internal::PaginationRange`
* `using ListSnapshotsRange = google::cloud::internal::PaginationRange`
* `google/cloud/pubsub/topic_admin_connection.h`
* `using ListTopicsRange = google::cloud::internal::PaginationRange`
* `using ListTopicSubscriptionsRange = google::cloud::internal::PaginationRange`
* `using ListTopicSnapshotsRange = google::cloud::internal::PaginationRange`
* `google/cloud/spanner/database_admin_connection.h`
* `using …

refactor!: PaginationRange<T> is now an alias to StreamRange<T>

---

google/cloud/pubsub/internal/subscription_session.cc
google/cloud/pubsub/internal/subscription_session_test.cc

In very rare circumstances (maybe as evidenced by the test) the library
would deadlock trying to shutdown a subscription. I noticed this in less
than 1 run over 10,000, and only when compiled with optimizations (TSAN
and ASAN masked the problem).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5541)

fix(pubsub): deadlock during fire & forget shutdown

---

ci/kokoro/docker/build-in-docker-bazel.sh
google/cloud/CMakeLists.txt
google/cloud/google_cloud_cpp_common.bzl
google/cloud/google_cloud_cpp_common_unit_tests.bzl
google/cloud/google_cloud_cpp_grpc_utils.bzl
google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
google/cloud/internal/pagination_range.h
google/cloud/internal/pagination_range_test.cc

`PaginationRange<T>` no longer has a dep on gRPC and it can also work with `Request` and `Response` objects that are either protobufs or plain old structs. This PR should allow GCS to use this `PaginationRange<T>` without taking a dep on GRPC or proto.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5540)

refactor: remove PaginationRange's dep on gRPC

---

google/cloud/pubsub/internal/subscription_session.cc

Obviously `self = shared_from_this();` can run outside the lock,
and once you move it out, the code can be simplified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5546)

cleanup(pubsub): simplify session timer rescheduling

---

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
google/cloud/pubsub/internal/streaming_subscription_batch_source.h
google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
google/cloud/pubsub/internal/subscription_session_test.cc

Sometimes the application may shutdown while a streaming pull is
"starting", i.e., going through the initial sequence of asynchronous
calls: `Start()` -> `Write()` -> `Read()`. The last one of these may
block basically forever. Therefore, it is necessary to have access to
the stream during this sequence to send a `Cancel()` request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5547)

fix(pubsub): deadlock during streaming pull shutdown

---

.bazelrc
ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
ci/kokoro/docker/build-in-docker-bazel.sh

Fixes: #5544
This also updates to libcxx version 11 (from 10), just because 11 happens to be the newest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5548)

fix: msan builds link w/ correct libc++abi

---

google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
google/cloud/storage/emulator/emulator.py
google/cloud/storage/emulator/tests/test_utils.py
google/cloud/storage/emulator/utils/common.py
google/cloud/storage/emulator/utils/error.py

3588248: 
Fix #5553 
So there is nothing to do with binary data. The real reason is in some request, data media contains `\r\n` which confuses the emulator: 
https://github.com/googleapis/google-cloud-cpp/blob/87da45a403d4022060d7d41a8b20d62791739668/google/cloud/storage/emulator/utils/common.py#L249
Fixed by using another method for parsing multipart.
be6b08b:
When `internal server error` takes place, the error message that is sent to the client library will contain the traceback.
I added a unittest for the error propagation. I move the unittests to after `start_emulator` since we need the emulator for the error propagation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/goog …

test(storage): fix emulator `parse_multipart`

---

google/cloud/internal/log_wrapper_test.cc

In some environments `grpc::Status` is marked as "must_use_result", and
these test lines would cause a breakage due to `-Wunused-result` if we
didn't do something with the `grpc::Status` that's returned from these
`LogWrapper()` calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5558)

fix: inspect returned grpc::Status

---

bazel/google_cloud_cpp_deps.bzl
external/googleapis/CMakeLists.txt
google/cloud/spanner/integration_tests/database_admin_integration_test.cc

Update the "com_google_googleapis" package to a recent snapshot.
This includes the `UpdateDatabaseDdlMetadata.throttled` field, and
requires adding `table_reference.proto` to the cmake lists.
The `UpdateDatabaseDdlMetadata.throttled` field indicates that the
`UpdateDatabase()` operation is throttled, e.g., due to resource
constraints. When resources become available the operation will
resume and the field will be false again.
This only updates an integration test. No samples are required for
this field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5562)

feat(spanner): Point-In-Time Recovery (lite) throttled DB update

---

google/cloud/spanner/numeric.cc
google/cloud/testing_util/command_line_parsing.cc

The code compiles and the unit tests run with MSVC 2017, specifically,
with:
```
cl.exe -?
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27044 for x64
```
I did not run the integration tests. Note that I only tested in 64-bit
mode (x64), I did not try a 32-bit build.
I think this answers the question in #5573
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5574)

fix: get the code to compile with MSVC 2017

---

ci/kokoro/windows/bazel-debug-2017-presubmit.cfg
ci/kokoro/windows/bazel-debug-2017.cfg
ci/kokoro/windows/bazel-release-2017-presubmit.cfg
ci/kokoro/windows/bazel-release-2017.cfg
ci/kokoro/windows/build-32.bat
ci/kokoro/windows/build-bazel.ps1
ci/kokoro/windows/build-quickstart-bazel.ps1
ci/kokoro/windows/build.bat
ci/kokoro/windows/build.ps1

Also included the configuration files for MSVC 2017 builds in this PR, I can split them if needed.
Part of the work for #5575.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5577)

ci: support configuring MSVC version in CI scripts

---

google/cloud/storage/emulator/tests/test_utils.py
google/cloud/storage/emulator/utils/common.py

The Storage multipart upload API allows for a multipart ending without "\r\n". The [RFC](https://tools.ietf.org/html/rfc7578) also does not specify that "\r\n” is required. This change allows for this flexibility in the emulator as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5578)

fix(storage): allow endings without \r\n in emulator multipart

---

generator/generator_test.cc
generator/integration_tests/generator_integration_test.cc
generator/integration_tests/golden/database_admin_client.gcpcxx.pb.h
generator/internal/client_generator.cc
generator/internal/descriptor_utils.cc
generator/internal/descriptor_utils.h
generator/internal/descriptor_utils_test.cc

- plumbed new plugin argument googleapis_commit_hash to CreateMethodVars via service_vars.
- used hash and GetSourceLocation to format permalinks to github.com/googleapis/googleapis
- changed doxygen param tags and added return tags using links where appropriate in Client class documentation
- had to rework test setups to use actual proto "files" so that GetSourceLocation would function
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5570)

feature(generator): add doxygen permalinks for proto message types

---

google/cloud/completion_queue_test.cc

Before this change the test would flake with TSAN under load (it would
not flake with `-c opt` under light load). This relaxes one of the
assertions, it still tests "something".
Fixes #5571 
Tested with 1600 iterations under TSAN:
```
CXX=clang++ CC=clang bazel test --config tsan --runs_per_test=1600 --jobs=64 --test_tag_filters=-integration-test //google/cloud:completion_queue_test
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5589)

test: deflake completion queue test

---

CMakeLists.txt
google/cloud/storage/benchmarks/CMakeLists.txt
google/cloud/testing_util/CMakeLists.txt

Our customers can enable only specific libraries, for example, they can
enable only the `storage` library. As the storage library does not
require gRPC, we should stop downloading and installing the gRPC
dependencies too (this is one of the main motivations to disable the
other libraries). In this PR we make 3 changes to make this easier to
use:
- Do not build the testing support libraries for gRPC unless gRPC is
needed by one of the top-level libraries.
- Do not build the storage benchmarks if gRPC is disabled, as they
depend directly on gRPC.
- Do not install the testing support libraries. These libraries are not
part of the public API, so installing them is not needed (it used to be,
to support `google-cloud-cpp-spanner` and other split repos). The other
changes are easier to implement …

fix: only build gRPC testing utilities if needed

---

google/cloud/bigtable/client_options.cc
google/cloud/bigtable/client_options.h
google/cloud/bigtable/internal/common_client.cc
google/cloud/bigtable/internal/common_client.h
google/cloud/bigtable/tests/data_integration_test.cc

This fixes #4996.
This works, however it is not in its final form. Currently, background
threads running `CompletionQueue` are created underhandedly, without
users' control in every Bigtable `{Admin,InstanceAdmin,Data}Client`.
The choice of the `{Admin,InstanceAdmin,Data}Client` is consistent with
Spanner and PubSub, where counterparts of those clients are called
Connections.
The next steps will contain removing the `CompletionQueue` from both the
underlying clients and the user-facing API and instead providing
`BackgroundThreads` to the ctors. I didn't decide to do this in chunks
because otherwise it would either be confusing, which CompletionQueues
are used or we'd have to duplicate the whole API to use the
CompletionQueue provided in the ctors.
More tests will be possible when …

feat: implement Bigtable connection refresh

---

google/cloud/pubsub/publisher.h
google/cloud/pubsub/publisher_test.cc

Part of #2310
This PR adds equality to `Publisher` only because `Publisher` is already copyable, and for the reasons in #2310, I _think_ copyability implies the need for equality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5608)

feat(pubsub): add equality to Publisher

---

google/cloud/bigtable/cluster_list_responses.h
google/cloud/bigtable/instance_list_responses.h

Fixes: #3598
Some `pb.h` files need to be included with double quotes, for example if
the proto is defined in our own library rather than an external library,
so I don't see any way to add a style checker to catch future
regressions. Therefore, this is just a current cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5610)

cleanup: include proto header w/ brackets

---

ci/check-style.sh

This is a clearer way to accomplish what
https://github.com/googleapis/google-cloud-cpp/pull/5615 was trying to do.
Better fix for https://github.com/googleapis/google-cloud-cpp/issues/4152
Example output (which is good):
```console
2020-12-11T19:33:59Z: Verify formatting 
Running check-include-guards: ... 0.041 seconds
Running cmake-format:         ... 8.163 seconds
Running Abseil header fixes:  ... 3.792 seconds
Running clang-format:         ... 5.168 seconds
Running buildifier:           ... 0.039 seconds
Running black:                ... 1.069 seconds
Running shfmt:                ... 0.017 seconds
Running shellcheck:           ... 1.757 seconds
Running cspell:               ... 41.633 seconds
Running include fixes:        ... 3.837 seconds
Running whitespace fixes:     ... 5.171 …
```

chore: explicitly avoid printf builtin

---

google/cloud/spanner/CMakeLists.txt
google/cloud/spanner/commit_options.h
google/cloud/spanner/query_options.h
google/cloud/spanner/query_options_test.cc
google/cloud/spanner/read_options.h
google/cloud/spanner/read_options_test.cc
google/cloud/spanner/request_priority.h
google/cloud/spanner/spanner_client.bzl

Introduce the `spanner::RequestPriority` enum (with low, medium
and high values), and add `absl::Optional<RequestPriority>` members
to `QueryOptions`, `ReadOptions`, and `CommitOptions`. These option
fields can be set by the user to mark a variety of `spanner::Client`
calls with a lower-than-default priority.
See the `RequestOptions.priority` Spanner protobuf field, which will
be set in an upcoming change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5624)

feat(spanner): introduce spanner::RequestPriority enum

---

ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build-in-docker-cmake.sh

This will facilitate the debugging of flakes by giving visibility
into calls prior to the failing one.
The tracing options are left at their default values of (currently):
```
single_line_mode=on
use_short_repeated_primitives=on
truncate_string_field_longer_than=128
```
Tested by injecting an error into an integration test and observing
the error report.
Fixes #4034.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5626)

test: enable RPC tracing for integration tests

---

google/cloud/storage/emulator/emulator.py
google/cloud/storage/internal/curl_client.cc
google/cloud/storage/internal/curl_resumable_upload_session.cc
google/cloud/storage/internal/curl_resumable_upload_session.h
google/cloud/storage/internal/object_requests.h
google/cloud/storage/tests/object_file_integration_test.cc

The Pull Request consists of below addition:
1. Propagate Custom Header in subsequent PUT requests when using Resumable uploads
2. Test case using GCS emulator
Fixes #5421
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5632)

feat(storage): propagate custom header with resumable upload PUT requests

---

ci/kokoro/docker/build-in-docker-bazel.sh
ci/kokoro/docker/build-in-docker-cmake.sh

This reverts #5626 and #5627.  Some tests generate so much output
(e.g., bigtable's DataIntegrationTest.TableSampleRowKeysTest) that
it makes it difficult to see what actually went wrong.
A more selective scheme (like a circular buffer) seems warranted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5636)

test: revert service tracing for integration tests

---

generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.cc
generator/internal/connection_generator.cc

`google/cloud/internal/polling_loop.h` includes `google/longrunning/operations.grpc.pb.h` and it only needed if the service has longrunning operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5638)

feature(generator): only include polling_loop if lro present

---

generator/integration_tests/golden/mocks/mock_database_admin_connection.gcpcxx.pb.h
generator/integration_tests/golden/mocks/mock_iam_credentials_connection.gcpcxx.pb.h
generator/internal/mock_connection_generator.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5641)

refactor(generator): remove generation of default destructor in mocks

---

generator/internal/descriptor_utils.cc
generator/internal/descriptor_utils_test.cc

When specifying the metadata_type or response_type in an `option (google.longrunning.operation_info)` annotation, the types only need to be fully qualified if they exist in a different package than the rpc. Thus, for unqualified types the generator will concatenate the rpc package with the type specified, if necessary.
Furthermore, it is not required that those types source .proto file is imported into the current file, so the generator cannot verify that the type exists at all if the source .proto is not tangentially imported somewhere in the dependency tree. The generator will make a best effort to find a descriptor for the type specified. If no descriptor can be found the generator will just handle it as a string literal.
fixes #5657 
fixes #5656
--- …

fix(generator): handle package local and non-imported deduced lro response types

---

google/cloud/spanner/samples/samples.cc

This is the final cleanup from https://github.com/googleapis/google-cloud-cpp/pull/5637.
Removing inner tagging now that new tags are live in docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5663)

docs: cleanup unnecessary tagging

---

google/cloud/completion_queue_test.cc
google/cloud/internal/default_completion_queue_impl.cc
google/cloud/internal/default_completion_queue_impl.h

Before this PR, the `StartOp` passed to
`CompletionQueueImpl::StartOperation` was called with the
`CompletionQueueImpl` lock held. This became problematic
because in #5665 we want to schedule timers on the `CompletionQueue`
when calling starting the operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666)

feat: allow cq actions in StartOperation

---

google/cloud/bigtable/CMakeLists.txt
google/cloud/bigtable/bigtable_client_unit_tests.bzl
google/cloud/bigtable/internal/common_client.cc
google/cloud/bigtable/internal/common_client.h
google/cloud/bigtable/internal/common_client_test.cc

This is a part of #2567.
Timers created by `CommonClient` to refresh connections are now
cancelled in the `CommonClient` dtor. This is needed to make sure that
no stray timers remain in the completion queue after the destruction of
`CommonClient`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5667)

feat: Cancel all connection refresh timers in dtor

---

google/cloud/storage/emulator/grpc_server.py
google/cloud/storage/emulator/utils/generation.py
google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/internal/grpc_client.h
google/cloud/storage/internal/grpc_client_bucket_request_test.cc
google/cloud/storage/tests/grpc_integration_test.cc

This PR:
- close #4180 (`ListBucketAcl`).
- close #4179 (`CreateBucketAcl`).
- close #4178 (`DeleteBucketAcl`).
- close #4177 (`GetBucketAcl`).
- close #4176 (`UpdateBucketAcl`).
- Fix an error in `SetPredefinedDefaultObjectAcl`.
- Fix an error in storage emulator which some messages raise because they don't have `if_generation_match` in their proto structure.
This PR is big. But we need `ListBucketAcl` for testing CRUD and vice versa. In addition, the code logic is short, the test is larger, but the test is quite repetitive or it is just a copy from an another test ( `BucketAccessControlCRUD` copied from `bucket_integration_test` ), so I think we could implement all these functions in one PR.
--- …

feat(storage): add `BucketAccessControl` CRUD and List for gRPC

---

google/cloud/storage/emulator/grpc_server.py
google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/internal/grpc_client.h
google/cloud/storage/internal/grpc_client_bucket_request_test.cc
google/cloud/storage/tests/grpc_integration_test.cc

This PR:
- close #4186 (`ListDefaultObjectAcl`).
- close #4185 (`CreateDefaultObjectAcl`).
- close #4184 (`DeleteDefaultObjectAcl`).
- close #4183 (`GetDefaultObjectAcl`).
- close #4182 (`UpdateDefaultObjectAcl`).
Based on #5669
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5682)

feat(storage): add `DefaultObjectAccessControl` CRUD and List for gRPC

---

google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc

This was only reported internally (see the operator handoff).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5685)

test(pubsub): deflake unit test

---

google/cloud/storage/emulator/grpc_server.py
google/cloud/storage/internal/grpc_client.cc
google/cloud/storage/internal/grpc_client.h
google/cloud/storage/internal/grpc_client_bucket_request_test.cc
google/cloud/storage/internal/grpc_client_test.cc
google/cloud/storage/internal/notification_requests.h
google/cloud/storage/notification_metadata.h
google/cloud/storage/tests/grpc_integration_test.cc

- Close #4187 ( `ToProto/FromProto` for `NotificationMetadata` ).
- Close #4188 ( `DeleteNotification` ).
- Close #4189 ( `CreateNotification` ).
- Close #4190 ( `GetNotification` ).
- Close #4191 ( `ListNotification` ).
Here is my approach for `Notification`. I am not sure this is the best way, especially with `notification_request`. Please take a look at it !
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5687)

feat(storage): add `Notifications` ToProto, FromProto, List, Create, Get and Delete for gRPC

---

ci/kokoro/docker/download-cache.sh
ci/kokoro/macos/download-cache.sh

They are hitting the ccache size limits, and getting less than 50% cache
hits.
Note that we will need to wait for a full build before this yields any benefits. OTOH,
the cache is full, a local build on my workstation requires 4.3G.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5686)

ci: speed up builds with shared libraries

---

google/cloud/completion_queue.cc
google/cloud/completion_queue.h
google/cloud/internal/async_connection_ready.cc
google/cloud/internal/async_connection_ready.h
google/cloud/internal/async_connection_ready_test.cc

Fixes #5670.  Before this change the `data_integration_test` was failing more in 5 out of 100 runs, after this change I got 1000 runs without failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5701)

fix(bigtable): crashes during client shutdown

---

google/cloud/spanner/samples/samples.cc

Several builds run against production and run relatively slow
operations, such as creating instances. With this change different
builds will pick a different location, and hopefully distribute the load
more fairly.
Motivated by the build breaks in #5701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5702)

test(spanner): deflake samples against production

---

google/cloud/spanner/internal/connection_impl_test.cc

If the intial read from a streaming operation fails when also
trying to implicitly start a transaction, ensure the library properly
recovers and completes the operation (using an explicit
`BeginTransaction` call).
This was definitely a gap in our test coverage; @thiagotnunes brought a
Java customer issue (https://github.com/googleapis/java-spanner/issues/799)
to my attention, so I wanted to ensure C++ users were not susceptible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5718)

test(spanner): add an additional transient failure test

---

ci/kokoro/install/Dockerfile.fedora
ci/verify_exported_targets/CMakeLists.txt
ci/verify_exported_targets/verify_exported_targets.cc
google/cloud/firestore/CMakeLists.txt
google/cloud/firestore/config.cmake.in

This change introduces a test to verify our exported targets remain
backwards compatible, that is, we do not accidentally remove a target
that we have exported in previous versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5739)

test: avoid breaking exported targets

---

.bazelrc
ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
ci/verify_exported_targets/.bazelrc
ci/verify_exported_targets/BUILD
ci/verify_exported_targets/WORKSPACE
google/cloud/firestore/BUILD

We are planning to deprecate and then retire some legacy targets for
Bazel, but until they are retired we need a test to verify we do not
remove them by accident.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5740)

test: verify legacy Bazel targets remain available

---

google/cloud/CMakeLists.txt
google/cloud/google_cloud_cpp_grpc_utils.bzl
google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
google/cloud/internal/streaming_read_rpc.cc
google/cloud/internal/streaming_read_rpc.h
google/cloud/internal/streaming_read_rpc_test.cc

Introduce a wrapper for gRPC's streaming read RPCs. Mostly because these
are easier to mock and decorate than the native gRPC types.
Part of the work for #5727
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5751)

feat: a wrapper for streaming read RPCs

---

google/cloud/bigtable/client_options.cc
google/cloud/bigtable/client_options.h
google/cloud/bigtable/client_options_test.cc
google/cloud/bigtable/internal/common_client.cc
google/cloud/bigtable/internal/common_client.h

Some applications (mostly tests it seems) create hundreds of clients,
and they need the initial refresh times to be longer.
Fixes #5723
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5753)

feat(bigtable): better control over channel refresh

---

google/cloud/CMakeLists.txt
google/cloud/google_cloud_cpp_grpc_utils.bzl
google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
google/cloud/internal/resumable_streaming_read_rpc.h
google/cloud/internal/resumable_streaming_read_rpc_test.cc

Usually streaming read RPCs need to be **resumed** if they fail in the
middle of the stream. This change introduces a class to implement the
"resume loop", an analog to the retry loop used for regular RPCs. The
differences between "resuming" and "retrying" are:
- Usually there is a token or some other indication sent to the service
to signal that a streaming RPC should start from the last message
received by a previous streaming RPC.
- Resuming making sense after *any* failures, and *any number* of
failures. Streaming RPCs typically represent downloads, or large reads
(otherwise pagination or a simple RPC would have been used), and it is
desirable to continue these operations as long as any progress is
made.
Fixes #5727
--- …

feat: implement generic ResumableStreamingReadRpc

---

CHANGELOG.md
external/googleapis/CMakeLists.txt
external/googleapis/legacy.cmake.in
generator/CMakeLists.txt
generator/integration_tests/CMakeLists.txt
generator/integration_tests/golden/CMakeLists.txt
google/cloud/CMakeLists.txt
google/cloud/bigtable/CMakeLists.txt
google/cloud/bigtable/benchmarks/CMakeLists.txt
google/cloud/bigtable/config.cmake.in
google/cloud/bigtable/examples/CMakeLists.txt
google/cloud/grpc_utils/config.cmake.in
google/cloud/iam/CMakeLists.txt
google/cloud/iam/config.cmake.in
google/cloud/logging/CMakeLists.txt
google/cloud/logging/config.cmake.in
google/cloud/pubsub/CMakeLists.txt
google/cloud/pubsub/config.cmake.in
google/cloud/spanner/CMakeLists.txt
google/cloud/spanner/config.cmake.in
google/cloud/storage/CMakeLists.txt
google/cloud/storage/benchmarks/CMakeLists.txt
google/cloud/testing_util/CMakeLists.txt

Export all the proto libraries with `google-cloud-cpp::` as a prefix.
Provide backwards compatibility targets for `googleapis-c++::`, add
warnings if those are used. Also made the analogous changes for
`pkg-config`. Changed the `{bigtable,pubsub,storage,spanner}_client`
targets to continue exporting the legacy target names.
Some additional cleanups in the `externals/googleapis/CMakeLists.txt`
file, mostly to make it easier to find `google_cloud_cpp_`.
Part of the changes for #5726
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5756)

cleanup(googleapis): consistent CMake target names

---

BUILD
ci/verify_current_targets/BUILD
ci/verify_current_targets/CMakeLists.txt

Simplify the test to verify our targets work by taking advantage of the
consistency fixes across CMake target names, pkg-config module names,
and Bazel targets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5775)

cleanup: simplify tests using consistent names

---

ci/kokoro/install/Dockerfile.fedora-components

The build was not really testing the runtime components, as it used
static libraries (I mistyped `BUILD_SHARED_LIBS` as `SHARED_LIBS`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5785)

ci: improve install/fedora-components build

---

ci/kokoro/docker/build-in-docker-cmake.sh
cmake/CompileProtos.cmake

Fix the destination directory for `.proto` files. Improve the
`clang-tidy` build to better detect such problems in the future.
Fixes #5708
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5783)

fix(googleapis): install directories for protos

---

README.md
ci/generate-markdown/generate-readme.sh

Our previous definition only described the public API, but did not say
much about the other things that applications must use to get to a
library (package names, library names, etc.) Updated the README to
include all of those.
I expect this will require some discussion, but I thought I could get the ball
rolling with a PR.
Part of the work for #5726 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5780)

doc: better define the public interface

---

google/cloud/bigtable/quickstart/BUILD
google/cloud/bigtable/quickstart/WORKSPACE
google/cloud/pubsub/quickstart/BUILD
google/cloud/pubsub/quickstart/WORKSPACE
google/cloud/spanner/quickstart/BUILD
google/cloud/spanner/quickstart/WORKSPACE
google/cloud/storage/quickstart/BUILD
google/cloud/storage/quickstart/WORKSPACE

Change the quickstart examples to use the new top-level largets (e.g.
`//:bigtable`). In the process I update the storage quickstart to
v1.24.0, and that requires shorter project names to build on Windows
:shrug:
Part of the work for #5726, fixes #5790
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5792)

cleanup: use new top-level targets for quickstart

---

google/cloud/storage/emulator/emulator.py
google/cloud/storage/emulator/gcs/iam.py
google/cloud/storage/emulator/gcs/project.py

Part of #5678 
`attach_enctype_error_multidict` is used only in `debug` mode.
https://github.com/pallets/flask/blob/192f4ae0b2a4e7d73c0b0472e53e33250175d786/src/flask/wrappers.py#L71-L81
I could not reproduce the issue locally. In the mean time, I will turn off `debug` in `flask`. I will be less active during this period. So it might take some time to resolve this issue properly. Sorry for any inconvenience.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5795)

ci: temporary disable flask debug

---

ci/kokoro/docker/Dockerfile.ubuntu

This includes `llvm-symbolizer`, which is needed by the tsan build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5794)

ci: install llvm-9 package
