google/cloud/storage/internal/grpc_client.cc
Turns out that the DirectPath configuration is simpler than I thought.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4388)
=> fix(GCS+gRPC): simplify DirectPath configuration

google/cloud/internal/time_utils.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4391)
=> fix: make potential narrowing cast of nanoseconds explicit

google/cloud/spanner/samples/samples.cc
Align the `spanner_delete_data` example with other languages. Use 3
different mutations (by key, by range, delete all), and explain how the
last one takes advantage of `ON DELETE CASCADE`. We use the same values
as C#, Java, Node.js, and Python), previously we used the same values as
Go. We use mutations in these examples, there does not seem to be any
consistency across languages on whether they should use SQL statements
or mutations.
Fixes #4336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4401)
=> fix(spanner): examples on how to delete data

google/cloud/spanner/samples/samples.cc
Fixes #4347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4405)
=> doc(spanner): add CreateInstance() example

ci/kokoro/docker/build-in-docker-bazel.sh
After #4403 we can now run the Service Account tests/examples in
parallel.
Also take this opportunity to unify the logging messages a little.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4406)
=> cleanup: test the hmac_service_account_targets in parallel

google/cloud/bigtable/tests/admin_backup_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4412)
=> chore: fix include delimiters for google/protobuf/util

google/cloud/spanner/internal/database_admin_metadata.cc
per https://google.aip.dev/client-libraries/4222 and https://github.com/googleapis/googleapis/blob/0a602be7b3835b51d59daf8f6f5dc2dc22f69d7e/google/spanner/admin/database/v1/spanner_database_admin.proto#L125
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4431)
=> fix: incorrect metadata key string

google/cloud/spanner/internal/session_pool_test.cc
It is not necessary to `Invoke()` a lambda in the context of
`WillOnce()` or `WillRepeatedly()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4429)
=> cleanup: remove unnecessary calls to testing::Invoke()

google/cloud/internal/backoff_policy.cc, google/cloud/internal/backoff_policy.h
Fixes #4425
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4442)
=> fix: broken builds on Windows+CMake+Release

ci/kokoro/docker/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4446)
=> cleanup: some further tweaks to build logging

google/cloud/spanner/internal/status_utils.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4455)
=> chore: fix spelling error in comment

release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4457)
=> chore: some tweaks to the CHANGELOG.md instructions

google/cloud/connection_options_test.cc
The test takes longer than 500ms under load on Windows. Before this
change I was able to break the test after about 2,000 iterations (again,
only under load), and with this PR the test has completed over 60,000
iterations.
This fixes #4451  (or at least reduces the incidence to the "I don't care" level)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4465)
=> test: reduce BackgroundThreads test flakiness

google/cloud/storage/CMakeLists.txt, google/cloud/storage/client.cc, google/cloud/storage/internal/complex_option.h, google/cloud/storage/internal/complex_option_test.cc, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/storage_client_unit_tests.bzl, google/cloud/storage/well_known_headers.h, google/cloud/storage/well_known_headers_test.cc, google/cloud/storage/well_known_parameters.h, google/cloud/storage/well_known_parameters_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4408)
=> feat: Add GenericRequest::ValueOr<>

.github/ISSUE_TEMPLATE/question.md, README.md, ci/generate-markdown/generate-readme.sh
Added a "Contact us" section to the main README.md file to encourage users to use the GitHub issues for contacting us. I also added a "Question" Issue template to make it easier and more acceptable for users to contact us with normal questions, kinda like they might uses a mailing list for.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4486)
=> docs: added question.md issue template

google/cloud/storage/client.cc, google/cloud/storage/client.h, google/cloud/storage/internal/object_requests.h, google/cloud/storage/tests/object_file_integration_test.cc, google/cloud/storage/upload_options.h
This PR is a part of #4437 
I would like to ask where I should write test for this PR. Thank you
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4473)
=> feat(storage): Add `UploadFromOffset` and `UploadLimit` to `UploadFile`

google/cloud/storage/internal/object_streambuf.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4519)
=> cleanup: missing include for absl::make_unique

google/cloud/storage/client.h, google/cloud/storage/internal/object_requests.h, google/cloud/storage/testbench/testbench.py, google/cloud/storage/tests/object_integration_test.cc, google/cloud/storage/well_known_parameters.h
Part of the work for #4493
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4518)
=> feat(storage): Add startOffset and endOffset

ci/generate-markdown/generate-packaging.sh, doc/packaging.md
Fixing ubuntu code name
ref: https://releases.ubuntu.com/20.04/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4542)
=> doc: fix Ubuntu code name

ci/kokoro/docker/build-in-docker-cmake.sh, ci/kokoro/macos/build-bazel.sh, ci/kokoro/macos/build-cmake.sh, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-cmake.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4550)
=> ci(GCS+gRPC): disable integration tests in all builds

google/cloud/pubsub/publisher_connection_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4588)
=> cleanup(pubsub): clarify unit test expectations

google/cloud/storage/hashing_options.h, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/hash_validator.cc, google/cloud/storage/internal/hash_validator.h, google/cloud/storage/internal/hash_validator_test.cc, google/cloud/storage/internal/object_requests_test.cc, google/cloud/storage/testbench/gcs_object.py, google/cloud/storage/tests/object_hash_integration_test.cc
Fixes #3395
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4591)
=> feat(storage): disable MD5Hash by default

.bazelrc, ci/kokoro/docker/build.sh
This was a configuration that I was trying to add, but it turns out it's too slow to run during CI. So this PR is just cleaning up unused code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4599)
=> cleanup: remove unused xsan configs

google/cloud/internal/parse_rfc3339.cc
This does not change any behavior, but it clarifies how we force
`std::mktime()` to ignore DST transitions, which allows it to be
used as the inverse to `std::gmtime()` under the assumption that
the "standard UTC offset" does not change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4602)
=> cleanup: clarify why mktime() can be mixed with gmtime()

google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/object_requests_test.cc
This PR is a part of work for #4404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4617)
=> feat(storage): a request type to delete pending resumable uploads

google/cloud/pubsub/ack_handler.h, google/cloud/pubsub/ack_handler_test.cc, google/cloud/pubsub/integration_tests/message_integration_test.cc, google/cloud/pubsub/mocks/mock_ack_handler.h, google/cloud/pubsub/subscriber_connection.cc, google/cloud/pubsub/subscriber_connection_test.cc
Fixes #4557
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4618)
=> cleanup(pubsub): return void from pubsub::AckHandler

google/cloud/pubsub/doc/pubsub-main.dox, google/cloud/pubsub/samples/samples.cc
The page is a bit incomplete, we need a quickstart, and an example on
how to use mocking, and so forth. We have separate issues open for that,
and having this file makes it easier to link those examples as we add
them.
Fixes #4587
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4623)
=> doc(pubsub): create landing page for Doxygen

google/cloud/spanner/value_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4661)
=> test: spanner::Value with neg year dates

google/cloud/BUILD, google/cloud/CMakeLists.txt, google/cloud/internal/format_time_point.cc
Related to: https://github.com/googleapis/google-cloud-cpp/issues/4458
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4680)
=> refactor: format_time_point simplified to use absl::Time

google/cloud/storage/client_options.cc, google/cloud/storage/client_options_test.cc
Fixes #4674
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4677)
=> fix(storage): missing CreateDefaultClientOptions overload

google/cloud/bigtable/benchmarks/setup.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4686)
=> refactor: use absl::FormatTime instead of std::strftime

google/cloud/storage/quickstart/README.md
@ns-osmolsky makes a good point in #4682
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4688)
=> doc(storage): include guidelines for bucket names

google/cloud/log.cc
Part of #4458.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4690)
=> refactor: use absl::Time for the google/cloud/log.h timestamp

ci/kokoro/windows/build-bazel.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4700)
=> ci: fix comment in build script

google/cloud/pubsub/internal/batching_publisher_connection_test.cc
Used to fail one or twice every 10,000 runs, no seeing failures in over
50,000 runs now.
Fixes #4727
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4732)
=> test(pubsub): deflake batching publisher connection test

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc
Rather than locally succeeding the rollback of a "has_begin"
transaction, try to allocate a transaction ID and then roll
it back.
This means that future operations on the transaction will
fail, as they should, instead of possibly creating another
transaction ID, or doing another no-op rollback.
Fixes #4705.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4731)
=> fix(spanner): begin a "has_begin" transaction in Rollback()

google/cloud/pubsub/subscriber.h, google/cloud/pubsub/subscriber_connection.h
The function was missing a minimal Doxygen block. I also removed an
obsolete TODO() entry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4733)
=> doc(pubsub): doxygen for Subscriber::Subscribe

google/cloud/spanner/numeric.h, google/cloud/spanner/value.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4738)
=> doc(spanner): note that NUMERIC columns are not yet available

google/cloud/pubsub/samples/samples.cc
Add the right region tags for existing examples.
Fixes #4630 and fixes #4632 and fixes #4633 and fixes #4638 and fixes #4658 and fixes #4659
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4766)
=> doc(pubsub): tag existing examples

google/cloud/pubsub/integration_tests/BUILD, google/cloud/pubsub/integration_tests/CMakeLists.txt, google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscription_admin_client.h, google/cloud/pubsub/subscription_admin_connection.cc, google/cloud/pubsub/subscription_admin_connection.h, google/cloud/pubsub/testing/mock_subscriber_stub.h
Fixes #4571
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4767)
=> feat(pubsub): implement GetSubscription()

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4768)
=> doc: update CHANGELOG for 2020-08 release

google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc, google/cloud/pubsub/internal/publisher_logging.cc, google/cloud/pubsub/internal/publisher_logging.h, google/cloud/pubsub/internal/publisher_logging_test.cc, google/cloud/pubsub/internal/publisher_stub.cc, google/cloud/pubsub/internal/publisher_stub.h, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/testing/mock_publisher_stub.h, google/cloud/pubsub/topic_admin_client.h, google/cloud/pubsub/topic_admin_connection.cc, google/cloud/pubsub/topic_admin_connection.h, google/cloud/pubsub/topic_admin_connection_test.cc
Implement the function in the stub (and its decorator), connection,
their mocks, the client, added the necessary unit tests, integration
tests, and a minimal sample.
Fixes #4567 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4786)
=> feat(pubsub): implement TopicAdminClient::GetTopic()

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4791)
=> fix(spanner): correct variable used to build instance config

google/cloud/storage/internal/grpc_resumable_upload_session_test.cc
When the application provides a large buffer in `.write()` we want to
upload the full buffer in a single streaming RPC call.  Add a new test
to do this, note that in the test the application-level buffer becomes a
"chunk" but the application never has direct control on those.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4797)
=> test(GCS+gRPC): verify large chunks create one stream

ci/kokoro/docker/build-in-docker-cmake.sh, ci/kokoro/macos/build-bazel.sh, ci/kokoro/macos/build-cmake.sh, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-cmake.ps1, google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
This fixes #4536
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4801)
=> ci(GCS+gRPC): restore integration tests

google/cloud/internal/pagination_range.h, google/cloud/internal/pagination_range_test.cc
Part of the work for #4568
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4806)
=> feat(common): non-proto values in PaginationRange

google/cloud/pubsub/publisher.h, google/cloud/pubsub/samples/samples.cc
Fixes #4631
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4805)
=> feat(pubsub): publish with attributes example

ci/kokoro/docker/build.sh
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/4788
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4816)
=> ci: remove gcc-4.8 build

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc, google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc, google/cloud/pubsub/internal/publisher_logging.cc, google/cloud/pubsub/internal/publisher_logging.h, google/cloud/pubsub/internal/publisher_logging_test.cc, google/cloud/pubsub/internal/publisher_stub.cc, google/cloud/pubsub/internal/publisher_stub.h, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/testing/mock_publisher_stub.h, google/cloud/pubsub/topic_admin_client.h, google/cloud/pubsub/topic_admin_connection.cc, google/cloud/pubsub/topic_admin_connection.h, google/cloud/pubsub/topic_admin_connection_test.cc
Implemented the usual unit test and integration test changes. Also
included an example and used the cloud site region tag.
Fixes #4568 and fixes #4634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4815)
=> feat(pubsub): implement ListTopicSubscriptions

ci/kokoro/docker/build.sh
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/4827
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4831)
=> ci: remove ninja build

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscription_admin_client.h
Fixes #4575 and fixes #4577 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4832)
=> feat(pubsub): implement {Create,Delete}Snapshot()

generator/internal/codegen_utils.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4833)
=> fix: windows narrowing conversion warning

google/cloud/bigtable/internal/rowreaderiterator.h, google/cloud/internal/pagination_range.h, google/cloud/internal/port_platform.h, google/cloud/status_or.h, google/cloud/storage/internal/range_from_pagination.h
Fixes #4829.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4839)
=> cleanup: GOOGLE_CLOUD_CPP_HAVE_CONST_REF_REF is now unconditionally true

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc, google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc, google/cloud/pubsub/internal/publisher_logging.cc, google/cloud/pubsub/internal/publisher_logging.h, google/cloud/pubsub/internal/publisher_logging_test.cc, google/cloud/pubsub/internal/publisher_stub.cc, google/cloud/pubsub/internal/publisher_stub.h, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/testing/mock_publisher_stub.h, google/cloud/pubsub/topic_admin_client.h, google/cloud/pubsub/topic_admin_connection.cc, google/cloud/pubsub/topic_admin_connection.h, google/cloud/pubsub/topic_admin_connection_test.cc
Implement the function in the *Stub, *Connection, and *Client class.
Change the unit tests, integration tests, and examples to include this
function.
Fixes #4569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4848)
=> feat(pubsub): implement ListTopicSnapshots()

generator/CMakeLists.txt, generator/google_cloud_cpp_generator.bzl, generator/google_cloud_cpp_generator_unit_tests.bzl, generator/internal/class_generator_interface.h, generator/internal/codegen_utils.cc, generator/internal/codegen_utils.h, generator/internal/codegen_utils_test.cc, generator/internal/printer.h, generator/internal/printer_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4840)
=> feature: add more utils, Printer, and ClassGeneratorInterface for generator

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc, google/cloud/pubsub/internal/subscriber_logging.cc, google/cloud/pubsub/internal/subscriber_logging.h, google/cloud/pubsub/internal/subscriber_logging_test.cc, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscription_admin_client.h, google/cloud/pubsub/subscription_admin_connection.cc, google/cloud/pubsub/subscription_admin_connection.h, google/cloud/pubsub/subscription_admin_connection_test.cc, google/cloud/pubsub/testing/mock_subscriber_stub.h
Add the function to the *Stub, *Connection, and *Client classes. Modify
the unit tests, integration tests and examples to show how this function
is used.
Fixes #4843 and fixes #4742 and fixes #4668
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4853)
=> feat(pubsub): implement ModifyPushConfig()

google/cloud/spanner/quickstart/README.md
A couple of paths were broken, and the formatting was different from other README files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4855)
=> doc(spanner): fix quickstart/README.md

google/cloud/storage/quickstart/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4857)
=> doc(storage): fix typo in quickstart/README.md

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc, google/cloud/pubsub/internal/subscriber_logging.cc, google/cloud/pubsub/internal/subscriber_logging.h, google/cloud/pubsub/internal/subscriber_logging_test.cc, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscription_admin_client.cc, google/cloud/pubsub/subscription_admin_client.h, google/cloud/pubsub/subscription_admin_connection.cc, google/cloud/pubsub/subscription_admin_connection.h, google/cloud/pubsub/subscription_admin_connection_test.cc, google/cloud/pubsub/testing/mock_subscriber_stub.h
Implemented the usual functions in the `*Stub`, `*Connection`, and
`*Client` classes. Add unit tests, integration tests, and samples for
the new functions.
Fixes #4578
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4858)
=> feat(pubsub): implement SubscriptionAdmin::Seek()

generator/CMakeLists.txt, generator/generator.cc, generator/generator.h, generator/generator_test.cc, generator/google_cloud_cpp_generator.bzl, generator/google_cloud_cpp_generator_unit_tests.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4859)
=> feature: add generator plugin entry point

.bazelignore, BUILD, ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh, ci/etc/quickstart-config.sh, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.fedora, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-focal, ci/kokoro/install/Dockerfile.ubuntu-xenial, google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsub/config.cmake.in, google/cloud/pubsub/quickstart/BUILD, google/cloud/pubsub/quickstart/CMakeLists.txt, google/cloud/pubsub/quickstart/Makefile, google/cloud/pubsub/quickstart/README.md, google/cloud/pubsub/quickstart/WORKSPACE, google/cloud/pubsub/quickstart/quickstart.cc
Add quickstart program for Cloud Pub/Sub, and compile it as part of the
quickstart and install builds.
Fixes #4648 and fixes #4582 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4854)
=> feat(pubsub): implement quickstart guide

google/cloud/pubsub/samples/samples.cc
This example shows how to setup a callback to report subscription
errors.
Fixes #4744
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4867)
=> feat(pubsub): subscriber_error_listener sample

ci/kokoro/docker/build-in-docker-bazel.sh
This tells all of our bazel builds to use a remote cache in a GCS
bucket. This will apply to all of our *docker* bazel builds, including
presubmit and CI builds. This should make both builds a bit faster, by
shifting CPU work (compiles) to network traffic (fetching cached
artifacts). This is probably a good trade off for our Kokoro machines.
Note: This PR is only changing thigns for our docker builds so we can
get experience with this `--remote_cache` option on bazel. The
ultimately plan would be to eneable this for macOS and Windows as well.
Related to: #4783
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4869)
=> ci: enable remote build cache for bazel 

generator/internal/service_generator.cc, generator/internal/stub_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4876)
=> fix: windows breakage from abseil

ci/kokoro/macos/build-bazel.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4887)
=> ci: enable bazel cache on macos

ci/kokoro/windows/build-bazel.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4894)
=> ci: enable bazel cache on windows

ci/kokoro/docker/publish-refdocs.sh
Fixes #4874
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4889)
=> doc(pubsub): start publishing doxygen docs

ci/kokoro/windows/build-bazel.ps1
Without this PR, the `bazel test` invocations wouldn't use the remote cache.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4897)
=> ci: use all build_flags in tests too

google/cloud/pubsub/samples/samples.cc
Show how to use custom attributes in a subscriber.
Fixes #4665
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4903)
=> feat(pubsub): pubsub_async_pull_custom_attributes sample

ci/kokoro/windows/build-bazel.ps1
Now that we have the GCS cache working, and the libcurl library is
cacheable on Windows we should be able to disable the tarball cache
altogether.
The windows/bazel build reports:
```
INFO: 3121 processes: 3116 remote cache hit, 5 local.
```
https://source.cloud.google.com/results/invocations/4df0be5f-6a84-4874-8e6a-ac49b257ccd6
That seems like a good hit rate :slightly_smiling_face: many of the tests
did not need to run because they reused the cache.
The windows/bazel-release build reports:
```
INFO: 3121 processes: 2331 remote cache hit, 790 local.
```
https://source.cloud.google.com/results/invocations/b36ac25e-cb99-4b25-8c74-cd990c04fd77
That is not nearly as good. OTOH, that build has been all over the place for the last few days.
=> ci: disable bazel tarball cache on Windows

generator/CMakeLists.txt, generator/google_cloud_cpp_generator.bzl, generator/google_cloud_cpp_generator_unit_tests.bzl, generator/internal/predicate_utils.cc, generator/internal/predicate_utils.h, generator/internal/predicate_utils_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4910)
=> feature(generator): add predicate utils to be used in method generation

google/cloud/pubsub/internal/subscription_session.cc, google/cloud/pubsub/internal/subscription_session.h
The previous names said *how* these functions did their work, but not
*what* they were trying to do. They are private functions in the
`internal::` namespace, but the code should be readable.
Fixes #4899
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4931)
=> cleanup(pubsub): rename message lease functions

google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc
This fixes #3300 and fixes #4781.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4780)
=> test: query parameters when resuming upload

generator/CMakeLists.txt, generator/generator.cc, generator/google_cloud_cpp_generator.bzl, generator/google_cloud_cpp_generator_unit_tests.bzl, generator/internal/codegen_utils.cc, generator/internal/codegen_utils.h, generator/internal/codegen_utils_test.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils.h, generator/internal/descriptor_utils_test.cc
Moved code from codegen_utils that dealt with interrogating descriptors for data into new file descriptor_utils.
Added code to extract substitution data from MethodDescriptor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4932)
=> feature(generator): add descriptor_utils

google/cloud/pubsub/publisher_connection.cc, google/cloud/pubsub/subscriber_connection.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4956)
=> cleanup(pubsub): better name for constants

google/cloud/internal/backoff_policy.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4957)
=> cleanup: fix typo in comment

google/cloud/pubsub/samples/samples.cc
This example shows how to set the number of I/O threads for a publisher.
Fixes #4636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4963)
=> feat(pubsub): publisher_concurrency_control sample

google/cloud/pubsub/samples/samples.cc
I probably misread the region tags when I typed them originally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4965)
=> cleanup(pubsub): fix or remove bad region tags

ci/generate-markdown/generate-pubsub-readme.sh, google/cloud/pubsub/README.md, google/cloud/pubsub/doc/pubsub-main.dox, google/cloud/pubsub/quickstart/README.md
Some tweaks to the README file and the Doxygen landing pages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4978)
=> doc(pubsub): more landing page improvements

google/cloud/bigtable/quickstart/README.md, google/cloud/spanner/quickstart/README.md, google/cloud/storage/quickstart/README.md
Apply some of the lessons from the latest review of the Pub/Sub
quickstart README to the other libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4980)
=> doc: update quickstart README files

google/cloud/spanner/integration_tests/client_stress_test.cc
Allow iterations [0...999] to have one failure, [1000...1999] to
have two failures, etc.  This is one additional failure per 1000
iterations then we previously allowed, acknowledging that even the
first iteration has a non-zero failure probability.
Also log the last failure status when there are too many failures.
Fixes #4759.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4989)
=> test: never expect that a stress-test has zero failures

generator/BUILD, generator/CMakeLists.txt, generator/main.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4993)
=> feature(generator): add plugin binary target

generator/CMakeLists.txt, generator/internal/printer.h, generator/internal/printer_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4995)
=> feature(generator): improve Printer missing variable diagnostic

google/cloud/spanner/samples/samples.cc
Add sample code for `spanner_create_table_with_datatypes`
and `spanner_insert_datatypes_data`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4999)
=> doc(spanner): add samples for "datatypes" region tags

ci/kokoro/windows/build-cmake-dependencies.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5003)
=> chore: upgrade vcpkg release to 2020.07

google/cloud/pubsub/internal/subscription_flow_control.cc, google/cloud/pubsub/internal/subscription_flow_control.h, google/cloud/pubsub/internal/subscription_flow_control_test.cc, google/cloud/pubsub/internal/subscription_session.cc
Implement flow control based on message size, so far only message count
was used for flow control.
Fixes #4645
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5004)
=> feat(pubsub): complete subscription flow control

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5001)
=> doc: update CHANGELOG for v1.17.0 release

google/cloud/pubsub/internal/subscription_concurrency_control_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5007)
=> fix(pubsub): build with MSVC+x86

google/cloud/internal/retry_policy.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4958)
=> cleanup: document RetryPolicy base class

google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscription_options.h
Shows how to set the flow control parameters for a subscription.
Fixes #4644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5009)
=> feat(pubsub): subscriber_flow_settings example

google/cloud/bigtable/quickstart/WORKSPACE, google/cloud/pubsub/quickstart/WORKSPACE, google/cloud/spanner/quickstart/WORKSPACE, google/cloud/storage/quickstart/WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5015)
=> chore: update quickstart WORKSPACE files for v1.17.1

release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5014)
=> doc: Update release process

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5016)
=> doc(spanner): add "spanner_query_with_*_parameter" samples

google/cloud/bigtable/instance_admin.cc, google/cloud/bigtable/internal/async_retry_op.h, google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll.h, google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll_test.cc, google/cloud/bigtable/internal/bulk_mutator.cc, google/cloud/bigtable/internal/bulk_mutator.h, google/cloud/bigtable/internal/unary_client_utils.h, google/cloud/bigtable/table.cc, google/cloud/bigtable/table_admin.cc, google/cloud/internal/async_retry_loop.h, google/cloud/internal/async_retry_loop_test.cc, google/cloud/internal/async_retry_unary_rpc.h, google/cloud/internal/async_retry_unary_rpc_test.cc, google/cloud/internal/retry_loop.h, google/cloud/internal/retry_loop_test.cc, google/cloud/internal/retry_policy.h, google/cloud/pubsub/internal/batching_publisher_connection.cc, google/cloud/pubsub/subscription_admin_connection.cc, google/cloud/pubsub/topic_admin_connection.cc, google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/partial_result_set_resume.cc, google/cloud/spanner/internal/partial_result_set_resume.h, google/cloud/spanner/internal/partial_result_set_resume_test.cc, google/cloud/spanner/internal/session_pool.cc, google/cloud/storage/internal/retry_client.cc
fixes #4975
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4977)
=> refactor: change retry loop functions to accept enum in lieu of bool

google/cloud/pubsub/samples/samples.cc
These came up during a review with @anguillanneuf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5020)
=> doc(pubsub): document default settings in samples

google/cloud/pubsub/mocks/mock_ack_handler.h, google/cloud/pubsub/mocks/mock_publisher_connection.h, google/cloud/pubsub/mocks/mock_subscriber_connection.h, google/cloud/pubsub/mocks/mock_subscription_admin_connection.h, google/cloud/pubsub/mocks/mock_topic_admin_connection.h, google/cloud/pubsub/publisher.h, google/cloud/pubsub/publisher_connection.h, google/cloud/pubsub/publisher_options.h, google/cloud/pubsub/subscriber.h, google/cloud/pubsub/subscriber_connection.h, google/cloud/pubsub/subscription_admin_connection.h, google/cloud/pubsub/subscription_options.h, google/cloud/pubsub/topic_admin_connection.h
Fix and/or add class and function comments for all public APIs. Fixed a
number of broken links and references. Add links to existing examples
where needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5021)
=> doc(pubsub): close Doxygen gaps

google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscriber.h, google/cloud/pubsub/subscriber_connection.h
Fixes #4622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5023)
=> feat(pubsub): subscriber retry settings example

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5029)
=> fix: add missing object ACLs in gRPC client

.bazelignore, google/cloud/bigtable/async_list_app_profiles_test.cc, google/cloud/bigtable/async_list_clusters_test.cc, google/cloud/bigtable/async_list_instances_test.cc, google/cloud/bigtable/async_row_reader_test.cc, google/cloud/bigtable/instance_admin_test.cc, google/cloud/bigtable/internal/async_longrunning_op_test.cc, google/cloud/bigtable/internal/async_retry_multi_page_test.cc, google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll_test.cc, google/cloud/bigtable/internal/bulk_mutator_test.cc, google/cloud/bigtable/mutation_batcher_test.cc, google/cloud/bigtable/table_admin_test.cc, google/cloud/bigtable/table_test.cc, google/cloud/completion_queue_test.cc, google/cloud/internal/async_retry_unary_rpc_test.cc, google/cloud/pubsub/internal/batching_publisher_connection_test.cc, google/cloud/pubsub/internal/ordering_key_publisher_connection_test.cc, google/cloud/pubsub/internal/subscription_session_test.cc, google/cloud/spanner/internal/session_pool_test.cc, google/cloud/testing_util/BUILD, google/cloud/testing_util/CMakeLists.txt, google/cloud/testing_util/fake_completion_queue_impl.cc, google/cloud/testing_util/fake_completion_queue_impl.h, google/cloud/testing_util/google_cloud_cpp_testing_grpc.bzl
Part of the work for #4718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5035)
=> refactor: MockCompletionQueue becomes FakeCompletionQueueImpl

google/cloud/bigtable/internal/google_bytes_traits.h, google/cloud/internal/compiler_info.cc, google/cloud/internal/port_platform.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5038)
=> fix(common): correct C++ version under MSVC

google/cloud/pubsub/doc/pubsub-main.dox
Ref: https://github.com/googleapis/google-cloud-cpp/issues/4860
This is my first time contributing in months. Let me start small.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5042)
=> doc(pubsub): fix typo

google/cloud/internal/async_retry_loop.h, google/cloud/internal/async_retry_loop_test.cc
Part of the work for #5026
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5045)
=> feat(common): cancel for internal::AsyncRetryLoop

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5049)
=> doc(spanner): adapt to new specification for NUMERIC samples

generator/internal/codegen_utils.cc, generator/internal/codegen_utils.h, generator/internal/codegen_utils_test.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils.h, generator/internal/descriptor_utils_test.cc, generator/internal/printer.h, generator/internal/printer_test.cc, generator/internal/stub_generator.cc, generator/internal/stub_generator.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056)
=> refactor(generator): introduce VarsDictionary type alias

google/cloud/pubsub/samples/pubsub_samples_common.cc, google/cloud/pubsub/samples/pubsub_samples_common.h, google/cloud/pubsub/samples/samples.cc
Fixes #4740
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5059)
=> feat(pubsub): add publish_with_ordering_keys sample

ci/kokoro/docker/upload-coverage.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5081)
=> ci: make debugging coverage reports easier

google/cloud/storage/internal/curl_client.h
These functions were declared but not used or implemented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5084)
=> cleanup(storage): removed unused member functions

ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5091)
=> ci: don't create bazel symlinks in quickstart dir

google/cloud/bigtable/async_row_reader.h, google/cloud/bigtable/instance_admin.cc, google/cloud/bigtable/internal/async_longrunning_op.h, google/cloud/bigtable/internal/async_poll_op.h, google/cloud/bigtable/internal/async_retry_multi_page.h, google/cloud/bigtable/internal/unary_client_utils.h, google/cloud/bigtable/mutation_batcher.h, google/cloud/bigtable/mutations.h, google/cloud/bigtable/table.cc, google/cloud/bigtable/table_admin.cc, google/cloud/internal/port_platform.h, google/cloud/internal/utility.h, google/cloud/pubsub/ack_handler.h, google/cloud/spanner/row.h, google/cloud/storage/benchmarks/throughput_result.h, google/cloud/storage/internal/generic_request.h, google/cloud/storage/parallel_upload.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5098)
=> cleanup: Fix more typos

google/cloud/pubsub/samples/samples.cc
Fixes: #4647
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101)
=> feat(pubsub): Implement pubsub_dead_letter_create_subscription sample

google/cloud/pubsub/samples/samples.cc
Fixes: #4743
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5103)
=> feat(pubsub): Implement pubsub_dead_letter_update_subscription sample

google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/instance_admin_connection.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5105)
=> cleanup(spanner): Update transferred issue numbers

google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/retry_policy.h
part of #4714
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5087)
=> fix: retry gRPC operations if the connection is unexpectedly terminated

ci/kokoro/docker/Dockerfile.fedora, ci/kokoro/docker/Dockerfile.fedora-install, ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
Part of the work for #5123. I think it might (or may not) be better to move the versions forward,
but this is a start.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5122)
=> ci: fix problems on Fedora-based builds

ci/kokoro/cache-functions.sh, ci/kokoro/docker/build.sh, ci/kokoro/macos/build.sh
Fixes #5113 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5117)
=> ci: disable tarball cache on full CI Bazel builds

generator/integration_tests/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5120)
=> fix(generator): add protobuf path for windows cmake

google/cloud/pubsub/samples/samples.cc
Fixes: #4627
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5129)
=> feat(pubsub): Implement pubsub_dead_letter_delivery_attempt sample

ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5118)
=> ci: use separate Bazel cache for Windows builds

ci/check-style.sh
I fat-fingered it and forgot to reinclude this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5133)
=> Fix: have cspell check cc files

ci/kokoro/docker/Dockerfile.fedora, ci/kokoro/docker/Dockerfile.fedora-install, ci/kokoro/docker/Dockerfile.fedora-libcxx-msan, ci/kokoro/docker/Dockerfile.ubuntu, google/cloud/storage/testbench/requirements.txt
Last night I downgraded one of the deps to get the builds to work. Today
I am upgrading all the deps to a consistent snapshot, and freezing even
more of them (I think all), to avoid random build breaks.
Fixes #5123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5134)
=> ci: upgrade dependencies for storage testbench

google/cloud/storage/client_sign_policy_document_test.cc, google/cloud/storage/internal/policy_document_request.cc, google/cloud/storage/internal/policy_document_request.h, google/cloud/storage/internal/policy_document_request_test.cc, google/cloud/storage/tests/signed_url_conformance_test.cc
This fixes #4830.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5126)
=> fix: enable codecvt in MSVC

ci/kokoro/macos/build-quickstart-bazel.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5142)
=> ci: use GCS Bazel cache for macOS quickstart build

google/cloud/pubsub/samples/samples.cc
Fixes: #4642
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5145)
=> feat(pubsub): Implement pubsub_enable_subscription_ordering sample

ci/kokoro/windows/build-quickstart-bazel.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5135)
=> ci: use GCS Bazel cache for Windows quickstart builds

generator/integration_tests/generator_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5152)
=> fix(generator): wrap absl headers with MSVC pragmas

google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/examples/BUILD, google/cloud/storage/examples/CMakeLists.txt, google/cloud/storage/examples/storage_examples_common.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5154)
=> refactor(storage): random bucket and object names

google/cloud/storage/internal/logging_client_test.cc
Part of the work for: #4513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5170)
=> feat(storage): Add ListBuckets test for storage::internal::LoggingClient

generator/internal/codegen_utils.cc, generator/internal/codegen_utils.h, generator/internal/codegen_utils_test.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5169)
=> refactor(generator): improve robustness of BuildNamespaces

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5172)
=> doc: update CHANGELOG for v1.19.0 releases

google/cloud/completion_queue_test.cc, google/cloud/internal/default_completion_queue_impl.cc
Fixes #5141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5176)
=> fix: race condition canceling CompletionQueue timers

google/cloud/log.cc, google/cloud/log_test.cc
The `GCP_LOG` backend using `std::clog` was not serializing its output,
that produced very difficult to read logs. Include the thread id in the
log, as it is sometimes interesting to know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5179)
=> feat(common): serialize output through std::clog

ci/generate-markdown/generate-packaging.sh, doc/packaging.md
Updated an improvised way to describe sentence, specially for professionals
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5177)
=> doc: improve verbiage in packaging.md

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/polling_loop.h, google/cloud/internal/polling_loop_test.cc, google/cloud/polling_policy.h, google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/polling_policy.h, google/cloud/spanner/spanner_client.bzl, google/cloud/spanner/spanner_client_unit_tests.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185)
=> refactor: relocate polling_loop.h from spanner to common

google/cloud/storage/benchmarks/throughput_result.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5212)
=> fix: MSVC+x86 build

google/cloud/storage/benchmarks/CMakeLists.txt
This was accidentally (I think) added in #5203.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5213)
=> fix: remove test from library sources list

ci/check-style.sh
Including some Abseil headers create problems on MSVC+x86, we have
"*_quiet.h" headers to workaround those problems. This check
automatically replaces direct includes of those headers with the
"*_quiet" counterparts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5221)
=> ci: automatically fix problematic Abseil includes

google/cloud/storage/emulator/gcs/bucket.py, google/cloud/storage/emulator/tests/test_gcs.py, google/cloud/storage/emulator/tests/test_utils.py, google/cloud/storage/emulator/utils/common.py
This PR:
- finalizes implementation for `gcs_bucket`
- refactors the filter response rest
- adds tests to make sure that everything works correctly.
Part of work for #4751
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5223)
=> test(storage): finish bucket and filter response

google/cloud/bigtable/filters.h, google/cloud/bigtable/filters_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5232)
=> feat(bigtable): convert protos to filters

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
In rare circumstances the application may decide to shutdown while the
streaming RPC is starting. In that case we need to check the shutdown
manager once the streaming RPC completes, and then maybe initiate the
sequence to shutdown the streaming RPC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5231)
=> fix(pubsub): handle start completion after shutdown

google/cloud/storage/client_write_object_test.cc, google/cloud/storage/internal/bucket_requests_test.cc, google/cloud/storage/internal/grpc_client_failures_test.cc, google/cloud/storage/internal/grpc_client_object_request_test.cc, google/cloud/storage/internal/grpc_object_read_source_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc, google/cloud/storage/internal/http_response_test.cc, google/cloud/storage/internal/logging_resumable_upload_session_test.cc, google/cloud/storage/internal/object_streambuf_test.cc, google/cloud/storage/internal/policy_document_request_test.cc, google/cloud/storage/internal/retry_client_test.cc, google/cloud/storage/internal/retry_resumable_upload_session_test.cc, google/cloud/storage/internal/signed_url_requests_test.cc, google/cloud/storage/oauth2/authorized_user_credentials_test.cc, google/cloud/storage/oauth2/compute_engine_credentials_test.cc, google/cloud/storage/oauth2/google_credentials_test.cc, google/cloud/storage/oauth2/service_account_credentials_test.cc, google/cloud/storage/object_stream_test.cc, google/cloud/storage/parallel_uploads_test.cc, google/cloud/storage/testing/remove_stale_buckets_test.cc, google/cloud/storage/tests/error_injection_integration_test.cc, google/cloud/storage/tests/object_checksum_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5234)
=> test(storage): use StatusIs in google/cloud/storage tests

google/cloud/storage/examples/storage_object_resumable_write_samples.cc
Fixes: #4923
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5239)
=> feat(storage): Create an example for Client::DeleteResumableUpload()

google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
Fixes #4850
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5243)
=> test(pubsub): enable DetachSubscription test

CODE_OF_CONDUCT.md
We are adopting a newer version of the contributor covenant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5250)
=> docs: update code of conduct to version 1.4.0

google/cloud/bigquery/internal/connection_impl.cc, google/cloud/bigtable/client_options.cc, google/cloud/bigtable/examples/data_snippets.cc, google/cloud/connection_options.cc, google/cloud/examples/gcs2cbt.cc, google/cloud/storage/client_options.cc, google/cloud/storage/internal/signed_url_requests.cc, google/cloud/storage/oauth2/service_account_credentials_test.cc, google/cloud/storage/tests/thread_integration_test.cc, google/cloud/testing_util/capture_log_lines_backend.cc
Part of the work for: #4458
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5255)
=> cleanup: use absl::StrSplit where appropriate

google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscription_builder.h, google/cloud/pubsub/subscription_builder_test.cc
Fixes #5200
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5253)
=> feat(pubsub): support subscription filters

google/cloud/pubsub/quickstart/BUILD, google/cloud/pubsub/quickstart/WORKSPACE
Fixes: #4856
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5268)
=> cleanup(pubsub): Use top-level target in Pub/Sub quickstart guide

google/cloud/storage/hmac_key_metadata.h
Fixes: #2148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5269)
=> cleanup(storage): Update HmacKey documentation with link

google/cloud/storage/emulator/database.py, google/cloud/storage/emulator/gcs/bucket.py, google/cloud/storage/emulator/gcs/object.py, google/cloud/storage/emulator/requirements.txt, google/cloud/storage/emulator/rest_server.py, google/cloud/storage/emulator/tests/test_utils.py, google/cloud/storage/emulator/utils/common.py
This PR adds:
- Rest handle for bucket and some changes so `bucket_integration_test` could pass with the new testbench.
- Object initializations ( `xml` and `resumable upload` will be added later )
- Object operations ( copy from `bucket` )
Part of #4751
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5273)
=> test(storage): add rest for bucket and gcs object

ci/kokoro/install/Dockerfile.opensuse-tumbleweed, doc/packaging.md
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/5277
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5278)
=> fix: breakage caused by tumbleweed update

cmake/GoogleCloudCppCommon.cmake
Fixes: #5275
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5281)
=> cleanup(common): Fix link in Doxygen TAGFILES

google/cloud/pubsub/benchmarks/endurance.cc, google/cloud/pubsub/integration_tests/subscriber_integration_test.cc, google/cloud/pubsub/internal/subscription_session.cc, google/cloud/pubsub/internal/subscription_session.h, google/cloud/pubsub/internal/subscription_session_test.cc, google/cloud/pubsub/samples/mock_subscriber.cc, google/cloud/pubsub/samples/pubsub_samples_common.cc, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscriber.h, google/cloud/pubsub/subscriber_connection.cc, google/cloud/pubsub/subscriber_connection.h, google/cloud/pubsub/subscriber_connection_test.cc, google/cloud/pubsub/subscriber_test.cc
**BREAKING CHANGE:** the existing description
in the CHANGELOG file covers this change too.
Part of the work for #5266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5285)
=> feat(pubsub)!: share connections for subscribers

CMakeLists.txt, cmake/CompileProtos.cmake, external/googleapis/CMakeLists.txt, google/cloud/CMakeLists.txt, google/cloud/storage/BUILD, google/cloud/storage/CMakeLists.txt, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_resumable_upload_session.cc, google/cloud/storage/internal/grpc_resumable_upload_session.h, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session_url.cc, google/cloud/storage/internal/grpc_resumable_upload_session_url.h, google/cloud/storage/internal/grpc_resumable_upload_session_url.proto, google/cloud/storage/internal/grpc_resumable_upload_session_url_test.cc, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/storage_client_grpc.bzl, google/cloud/storage/storage_client_grpc_unit_tests.bzl
This fixes #5030.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5189)
=> fix: handling of session URLs in gRPC

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/bigtable_client_unit_tests.bzl, google/cloud/bigtable/internal/async_bulk_apply_test.cc
This PR will close task#2 for #4100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5288)
=> test(bigtable): unit test for AsyncRetryBulkApply

google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/database_integration_test.cc
Extract explicit `extra_statements` variables for some calls
to `CreateDatabase()`.  This will facilitate merging of upcoming
features that add additional DDL statements to database creation,
and particularly so given the varied state of emulator support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5303)
=> refactor(spanner): some simple CreateDatabase() refactoring

README.md, google/cloud/storage/README.md, google/cloud/storage/quickstart/quickstart.cc
handles error in quickstart example in README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5274)
=> add error handling example from client->ReadObject() in README.md

ci/kokoro/windows/build-quickstart-bazel.ps1, ci/kokoro/windows/build-quickstart-cmake.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5306)
=> ci: add pubsub quickstart to Windows builds

google/cloud/storage/emulator/database.py, google/cloud/storage/emulator/gcs/__init__.py, google/cloud/storage/emulator/gcs/bucket.py, google/cloud/storage/emulator/gcs/object.py, google/cloud/storage/emulator/rest_server.py, google/cloud/storage/emulator/tests/test_gcs.py, google/cloud/storage/emulator/utils/__init__.py, google/cloud/storage/emulator/utils/common.py, google/cloud/storage/emulator/utils/csek.py
This PR adds some basic operations and rest handle for object.
Part of #4751
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5289)
=> test(storage): add rest handle for object

google/cloud/pubsub/internal/batching_publisher_connection_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5317)
=> fix: add string cast to work when bytes is a Cord

google/cloud/spanner/BUILD, google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/internal/session_pool.cc, google/cloud/spanner/internal/session_pool.h
Fixes TODO (issue no longer exists).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271)
=> cleanup(spanner): Use absl::FixedArray instead of vector

google/cloud/bigtable/tools/convert_acceptance_tests.py
The script to convert conformance tests into a series of C++ unit tests
needed some cleanups to make `pylint` happy. Mostly cosmetic (variable
names, line breaks, and such). I also split the code into smaller
functions to make it easier to see what is going on.
I just ran the script again and regenerated the code, identical output so
the changes are harmless.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5321)
=> cleanup(bigtable): pylint warnings

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/bigtable_client_unit_tests.bzl, google/cloud/bigtable/internal/async_poll_op_test.cc
This PR closes #4100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5332)
=> test(bigtable): unit tests for async_poll_op

generator/internal/idempotency_policy_generator.cc, generator/internal/predicate_utils.h
fixes #5314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5331)
=> fix(generator): convert predicate logic operators from classes to functions

google/cloud/pubsub/internal/subscription_message_queue.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5340)
=> fix(pubsub): MSVC+x86 errors

google/cloud/internal/absl_str_cat_quiet.h, google/cloud/internal/absl_str_join_quiet.h, google/cloud/internal/absl_str_replace_quiet.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5341)
=> fix: pop the diagnostic stack to restore defaults

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5325)
=> doc: update notes for the storage library

google/cloud/bigquery/CMakeLists.txt, google/cloud/bigquery/internal/storage_stub.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5320)
=> cleanup(bigquery): Fix absl related TODOs

google/cloud/bigquery/internal/storage_stub.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5345)
=> fix: MSVC+x86 build fixes

google/cloud/spanner/integration_tests/client_stress_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359)
=> refactor(spanner): Use testing_utils for command-line parsing

generator/internal/logging_decorator_generator.cc, generator/internal/metadata_decorator_generator.cc, generator/internal/stub_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5361)
=> refactor(generator): use new proto_grpc_path var everywhere

google/cloud/bigtable/testing/table_integration_test.cc, google/cloud/bigtable/tests/data_integration_test.cc, google/cloud/iam_bindings.cc, google/cloud/pubsub/internal/session_shutdown_manager.cc, google/cloud/storage/bucket_metadata.cc, google/cloud/storage/internal/bucket_acl_requests.cc, google/cloud/storage/internal/default_object_acl_requests.cc, google/cloud/storage/internal/notification_requests.cc, google/cloud/storage/internal/object_acl_requests.cc, google/cloud/storage/internal/sign_blob_requests.cc, google/cloud/storage/internal/signed_url_requests.cc, google/cloud/storage/lifecycle_rule.cc, google/cloud/storage/object_metadata.cc, google/cloud/storage/policy_document.cc, google/cloud/storage/tests/curl_download_request_integration_test.cc
Fixes: #2442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5363)
=> cleanup: Replace ad-hoc Join with Abseil StrJoin

generator/integration_tests/golden/golden_connection_test.cc
fixes #5362
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5371)
=> fix(generator): allow for flaky mock leak

generator/integration_tests/golden/database_admin_connection.gcpcxx.pb.cc, generator/integration_tests/golden/golden_connection_test.cc, generator/internal/connection_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5373)
=> fix(generator): use weak_ptr and deadline in cancel

google/cloud/pubsub/internal/publisher_stub.cc, google/cloud/pubsub/internal/subscriber_stub.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5376)
=> cleanup(pubsub): remove redundant code

google/cloud/pubsub/benchmarks/throughput.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5375)
=> fix: build problems with MSVC+x86

google/cloud/pubsub/doc/pubsub-main.dox, google/cloud/pubsub/subscriber.h, google/cloud/pubsub/subscriber_options.h, google/cloud/pubsub/subscription_admin_client.h, google/cloud/pubsub/topic_admin_client.h
Part of the work for #4860
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5382)
=> doc(pubsub): fix rendering for paragraphs

ci/generate-markdown/generate-pubsub-readme.sh, google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsub/README.md, google/cloud/pubsub/ack_handler.h, google/cloud/pubsub/doc/publisher-mock.dox, google/cloud/pubsub/doc/subscriber-mock.dox, google/cloud/pubsub/message.h, google/cloud/pubsub/publisher.h, google/cloud/pubsub/publisher_connection.h, google/cloud/pubsub/snapshot.h, google/cloud/pubsub/subscriber.h, google/cloud/pubsub/subscriber_connection.h, google/cloud/pubsub/subscriber_options.h, google/cloud/pubsub/subscription_admin_client.h, google/cloud/pubsub/subscription_admin_connection.h, google/cloud/pubsub/topic_admin_client.h, google/cloud/pubsub/topic_admin_connection.h
Several passes over the generated documentation to fix nits and improve things.
Fixes #4860
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5383)
=> doc(pubsub): fix documentation nits

google/cloud/CMakeLists.txt, google/cloud/pubsub/benchmarks/CMakeLists.txt, google/cloud/pubsub/integration_tests/CMakeLists.txt, google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/benchmarks/CMakeLists.txt, google/cloud/spanner/integration_tests/CMakeLists.txt, google/cloud/spanner/samples/CMakeLists.txt, google/cloud/storage/tests/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5385)
=> cleanup: more consistent cmake-format directives

ci/generate-markdown/dockerfile2markdown.sh, ci/generate-markdown/generate-packaging.sh, doc/packaging.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5393)
=> doc: minor fixes to packaging instructions

google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/mutation_batcher.h, google/cloud/bigtable/row_reader.h, google/cloud/bigtable/table.h, google/cloud/bigtable/table_admin.h
This fixes #3207.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5394)
=> docs: document Bigtable thread safety

release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5400)
=> doc(release): update release instructions

ci/kokoro/docker/Dockerfile.fedora, ci/kokoro/docker/Dockerfile.fedora-install, ci/kokoro/docker/Dockerfile.fedora-libcxx-msan, ci/kokoro/docker/Dockerfile.ubuntu, google/cloud/storage/emulator/gcs/object.py, google/cloud/storage/emulator/requirements.txt, google/cloud/storage/tools/run_testbench_utils.sh
Part of #4751
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5398)
=> test(storage): use new emulator for storage integration test

google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
Fixed a very rare race condition, which (a) will be triggered more often
with the (pending) changes to optimize `CompletionQueue::RunAsync()`,
and (b) I was able to reliably reproduce with some ~deviously~carefully
placed sleep calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5407)
=> fix(pubsub): deflake subscriber_integration_test

google/cloud/pubsub/internal/batching_publisher_connection_test.cc
The `BatchByMaximumHoldTime` test was flaky, it would fail under heavy
load because it assumed publishing an event took less than 5ms.
Fixes #5369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5410)
=> test(pubsub): deflake batching by time unit test

README.md, ci/generate-markdown/generate-readme.sh
Nothing much new here, just slightly clearer documentation wording.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5427)
=> doc: update README.md to comply w/ basic support requirements

ci/kokoro/docker/build.sh
Part of the work for: #4094
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5434)
=> ci: rename builds to gcc-10

ci/kokoro/docker/build.sh
Fixes: #4094
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5437)
=> ci: remove gcc 9 build

google/cloud/pubsub/internal/batching_publisher_connection.cc, google/cloud/pubsub/internal/batching_publisher_connection_test.cc
This is more efficient that dispatching each response back through the
completion queue. Since batches can be large (1,000 elements is not
usual) this can save thousands of I/O operations. With this change the
benchmark can sustain 250 MB/s using small (~1KiB) messages, and the
benchmark uses about 5 cores to do so. That is about 5 times better than
before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5441)
=> feat(pubsub): handle AsyncPull responses in batches

google/cloud/completion_queue_test.cc
Fixes #5440
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5442)
=> test: deflake CompletionQueue test

google/cloud/pubsub/benchmarks/throughput.cc
Report (separately) the throughput for publishing messages and processing
acks. This can show when the acks are not being processed fast enough,
or when the messages are queued.
I refactored the code because it was hard to follow what was going on
with all the lambdas. I reduced contention in the benchmark by tracking
pending messages for each sending thread separately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5439)
=> feat(pubsub): show ack throughput in benchmark

ci/generate-markdown/extract-install.sh, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.fedora, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-focal, ci/kokoro/install/Dockerfile.ubuntu-xenial, google/cloud/spanner/benchmarks/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5444)
=> doc: remove INSTALL.md references

google/cloud/pubsub/benchmarks/throughput.cc
Track the actual bytes sent and received, instead of just using the
bytes in the payload. This is useful when the publisher and subscriber
and running as separate programs, it is too easy to mismatch the
command-line options between the two.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5450)
=> feat(pubsub): improve throughput benchmark reports

bazel/google_cloud_cpp_deps.bzl, external/googleapis/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5443)
=> feat(spanner): use spanner_cmek_and_pitr_lite protos

bazel/google_cloud_cpp_deps.bzl, external/googleapis/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5452)
=> feat(spanner): use spanner_commit_stats protos

ci/cspell.json, generator/integration_tests/golden/database_admin_client.gcpcxx.pb.h, generator/internal/client_generator.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc
Generates doxygen compatible comment blocks for the Client class and its public member methods. Testing of this feature is done as part of the generator_integration_test.cc.
Not sure how to attach an image of the rendered doxygen, but it looks satisfactory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5457)
=> feature(generator): generate doxygen function headers for Client

google/cloud/pubsub/benchmarks/throughput.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5465)
=> fix(pubsub): nit in the throughput benchmark

generator/generator.cc
Recent changes to ServiceCodeGenerator, to guarantee immutability after construction, allows for safe generation of all code files concurrently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5466)
=> feature(generator): parallelize code generation

bazel/google_cloud_cpp_deps.bzl, external/googleapis/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5467)
=> cleanup(spanner): omit checksums on named-branch googleapis dep

google/cloud/storage/CMakeLists.txt, google/cloud/storage/oauth2/google_credentials_test.cc, google/cloud/storage/oauth2/service_account_credentials_test.cc, google/cloud/storage/storage_client_testing.bzl, google/cloud/storage/testing/constants.h, google/cloud/storage/testing/write_base64.cc, google/cloud/storage/testing/write_base64.h
Fixes: #3022
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5459)
=> cleanup(storage): Factor out test constants into common location

CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5475)
=> cleanup: remove obsolete TODO

.github/snippet-bot.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5476)
=> chore: tell snippet-bot to ignore ci/**

ci/etc/README.md, google/cloud/storage/doc/setup-test-resources.md
Fixes: #2420
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5483)
=> docs(storage): document how to create integration testing resources

google/cloud/pubsub/internal/batch_sink.h, google/cloud/pubsub/internal/batching_publisher_connection.cc, google/cloud/pubsub/internal/default_batch_sink.cc, google/cloud/pubsub/internal/default_batch_sink.h, google/cloud/pubsub/internal/sequential_batch_sink.cc, google/cloud/pubsub/internal/sequential_batch_sink.h, google/cloud/pubsub/testing/mock_batch_sink.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5484)
=> fix(pubsub): reduce data copying in publish

google/cloud/spanner/integration_tests/client_integration_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/database_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5481)
=> chore(spanner): update pitr-lite -v- emulator issue number

generator/internal/client_generator.cc, generator/internal/connection_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5478)
=> fix(generator): replace hard coded class names with substitution labels

google/cloud/pubsub/internal/batching_publisher_connection.cc
Reserve space for the next batch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5495)
=> feat(pubsub): minor optimization in publisher

google/cloud/pubsub/benchmarks/throughput.cc
I misread the code and/or description of the throughput benchmark for
other languages. They use a separate subcriber per thread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5499)
=> feat(pubsub): separate subscribers in benchmark

google/cloud/pubsub/benchmarks/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5500)
=> doc(pubsub): how to run throughput benchmark

google/cloud/completion_queue_test.cc
Fixes #5497
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5504)
=> test: deflake completion queue test

google/cloud/storage/tests/object_integration_test.cc
Removes the #3301 TODO.  The fixes were done earlier by @vnvo2409.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5508)
=> cleanup(storage): emulator supports binary data

ci/kokoro/docker/build-in-docker-cmake.sh
Fixes: #4132
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5488)
=> ci: detect incorrectly installed files

google/cloud/storage/tests/grpc_integration_test.cc
Close #5428
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5514)
=> test(storage): test `gRPC` `GetObjectMediaNotFound` against emulator

CMakeLists.txt
Fixes: #5511
cc: @devjgm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5517)
=> feat: add `GOOGLE_CLOUD_CPP_ENABLE` CMake variable

google/cloud/storage/client_options.cc
Fixes #5523 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5524)
=> fix(storage): use channel options for credentials

doc/setup-development-environment.md
This PR replaces the dependencies of the old testbench with the new emulator
Thank @remyabel !
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5528)
=> doc(storage): dependencies for the new emulator

generator/internal/predicate_utils_test.cc
Fixes: #5360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5533)
=> cleanup: refactor predicate_utils_test.cc to use string literals

google/cloud/internal/stream_range.h, google/cloud/internal/stream_range_test.cc
Constructors are part of a class's public API, yet in many cases,
they're also very close to an implementation detail. Even for non-public
classes in an `internal` namespace, if/when they are exposed to users
via an alias in a public namespace, those constructors become part of
that user-facing API.
Unless the constructor is necessarily part of the concept or abstraction
represented by the class, it's probably safest to make
implementation-detail constructors private and expose them only via
factory functions. This way, we can alias a private class into a
public namespace and not expose the constructors. And in order to call
the factory function, users would need to spell our `internal`
namespace, which is off limits.
So I think this is a better way to make sure we only expose the …
=> refactor: StreamRange<T> c'tor is now private

google/cloud/bigtable/client_options.cc, google/cloud/bigtable/client_options.h, google/cloud/bigtable/data_client.cc, google/cloud/bigtable/doc/bigtable-main.dox, google/cloud/bigtable/internal/common_client.h, google/cloud/bigtable/testing/table_integration_test.cc, google/cloud/bigtable/testing/table_integration_test.h, google/cloud/bigtable/tests/data_integration_test.cc, google/cloud/internal/log_wrapper.h, google/cloud/internal/log_wrapper_test.cc
This is related to task #4320 and creates a logging layer for synchronous data_client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5515)
=> feat(bigtable): create logging layer for Cloud Bigtable

google/cloud/storage/internal/curl_client.cc
The link will soon be obsolete and moved to the new destination.
Updating in anticipation of this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5551)
=> doc: update link in comment

google/cloud/storage/BUILD, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_read_source.cc
This makes the code in GCS ready for importing into the google codebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5561)
=> chore(storage): prepare GCS+gRPC for google import

google/cloud/spanner/integration_tests/database_admin_integration_test.cc
The `UpdateDatabaseDdlMetadata.throttled` field indicates that the
`UpdateDatabase()` operation is throttled, e.g., due to resource
constraints. When resources become available the operation will
resume and the field will be false again.
Here, as part of the `DatabaseAdminClientTest.DatabaseBasicCRUD`
test, we set a valid `version_retention_period` through an
`UpdateDatabase()` statement, and check that the throttled field
was returned correctly (as false).
No samples are required for this field.
Fixes #5257.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5560)
=> feat(spanner): Point-In-Time Recovery (lite) throttled DB update

google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/instance_admin_test.cc
Fixes #5563 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5565)
=> fix(bigtable): missing functions to change policies

generator/integration_tests/golden/database_admin_client.gcpcxx.pb.cc, generator/integration_tests/golden/database_admin_client.gcpcxx.pb.h, generator/internal/client_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5567)
=> refactor(generator): remove generation of ConnectionOptions Client constructor

google/cloud/spanner/database_admin_connection_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5572)
=> chore: fix test name to match file

README.md, ci/generate-markdown/generate-readme.sh
Fixes: #3847
Preview: https://github.com/devjgm/google-cloud-cpp/blob/api-support/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564)
=> doc(api-support): document API support guarantees

bazel/google_cloud_cpp_deps.bzl, external/googleapis/CMakeLists.txt, google/cloud/spanner/integration_tests/database_admin_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5596)
=> feat(spanner): use spanner_request_options protos

bazel/google_cloud_cpp_deps.bzl, external/googleapis/CMakeLists.txt, google/cloud/spanner/integration_tests/database_admin_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5597)
=> feat(spanner): use spanner_rpc_priority protos

CMakeLists.txt, ci/kokoro/macos/build-cmake.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5599)
=> chore: change libressl -> openssl on macos

google/cloud/internal/parse_rfc3339.cc, google/cloud/internal/parse_rfc3339.h, google/cloud/internal/parse_rfc3339_test.cc
Fixes: #530
Fixes: #5426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5603)
=> refactor: use absl::ParseTime rather than custom impl

generator/internal/codegen_utils.cc, generator/internal/codegen_utils_test.cc, generator/internal/predicate_utils.cc, generator/internal/predicate_utils.h, generator/internal/predicate_utils_test.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator.h
Adding support for detecting which services have longrunning operation methods and which do not. 
Modifying how includes are emitted to handle empty strings.
This PR is a chunk of a larger imminent PR that I could carve off.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5604)
=> feature(generator): add utility functions to handle non LRO services

ci/check-style.sh
Fixes: #4152
**BEFORE**
```console
2020-12-11T03:34:25Z: Verify formatting 
Running check-include-guards: ... 0.040 seconds
Running cmake-format:         ... 8.233 seconds
Running Abseil header fixes:  Running clang-format:         ... 3.706 seconds
... 5.161 seconds
Running buildifier:           ... 0.038 seconds
Running black:                Running shfmt:                ... 1.013 seconds
Running shellcheck:           ... 0.018 seconds
Running cspell:               ... 1.744 seconds
Running include fixes:        ... 41.134 seconds
Running whitespace fixes:     ... 3.757 seconds
... 5.062 seconds
```
**AFTER**
```console
2020-12-11T18:17:08Z: Verify formatting
Running check-include-guards: ... 0.039 seconds
Running cmake-format:         ... 9.790 seconds
Running Abseil header fixes:  ... …
```
=> chore: disable output buffering on shell printf

generator/integration_tests/golden/internal/database_admin_logging_decorator.gcpcxx.pb.cc, generator/integration_tests/golden/internal/database_admin_logging_decorator.gcpcxx.pb.h, generator/integration_tests/golden/internal/database_admin_metadata_decorator.gcpcxx.pb.cc, generator/integration_tests/golden/internal/database_admin_metadata_decorator.gcpcxx.pb.h, generator/internal/logging_decorator_generator.cc, generator/internal/metadata_decorator_generator.cc, generator/internal/stub_factory_generator.cc, generator/internal/stub_generator.cc
Testing for services without longrunning operations will be in the next PR. I left it out of this one to keep the size manageable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5617)
=> feature(generator): conditionally generate longrunning includes and helpers

ci/kokoro/docker/build-in-docker-bazel.sh, ci/kokoro/docker/build-in-docker-cmake.sh
Counterpart to #5626 for storage.  Fixes #4034.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5627)
=> test(storage): enable service tracing for integration tests

generator/internal/client_generator.cc, generator/internal/connection_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5629)
=> feature(generator): conditional generation of lro support in Client and Connection

generator/integration_tests/golden/database_admin_connection_idempotency_policy.gcpcxx.pb.h, generator/integration_tests/golden/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h, generator/internal/idempotency_policy_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5633)
=> fix(generator): unnecessary lro include in idempotency policy

generator/integration_tests/golden/golden_client_test.cc, generator/integration_tests/golden/iam_credentials_client_test.cc, generator/integration_tests/golden/mocks/mock_database_admin_connection.gcpcxx.pb.h, generator/integration_tests/golden/mocks/mock_iam_credentials_connection.gcpcxx.pb.h, generator/internal/codegen_utils.cc, generator/internal/codegen_utils.h, generator/internal/mock_connection_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5635)
=> refactor(generator): change namespace containing mocks to align with existing products

google/cloud/spanner/samples/samples.cc
These samples' region tags slightly differ from identical snippets in different languages. The following is the remedy:
1. Merge this PR to fix GitHub source (keep old tag for now)
2. Fix doc code includes to represent the better region tag
3. Submit a second PR to clean-up redundant region tag wrapping
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5637)
=> docs: homogenize region tags

generator/internal/codegen_utils.cc, generator/internal/codegen_utils_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5639)
=> feature(generator): accept commit hash from command line arg

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc
Set the `request_options.priority` fields in `ExecuteSqlRequest`,
`ExecuteBatchDmlRequest`, `ReadRequest`, and `CommitRequest` calls,
using the priority specified by the user in the corresponding
"options" parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5645)
=> feat(spanner): set protobuf request_options.priority fields

google/cloud/storage/internal/curl_handle_factory.cc
Fixes #5650
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5651)
=> fix(storage): incorrect CURL handle manipulation

google/cloud/storage/emulator/grpc_server.py, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_bucket_request_test.cc, google/cloud/storage/tests/grpc_integration_test.cc
Close #4163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5652)
=> feat(storage): add `UpdateBucket` for gRPC

ci/kokoro/docker/build-in-docker-cmake.sh, external/googleapis/CMakeLists.txt, external/googleapis/config.cmake.in
Add proto + gRPC libraries for the Speech (aka Speech-to-Text),
Text-To-Speech (aka TTS), and DialogFlow (v2 and v2beta1) services.
Fixes #5655
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5658)
=> feat: add frequently mentioned proto libraries

google/cloud/storage/tests/curl_download_request_integration_test.cc, google/cloud/storage/tests/curl_request_integration_test.cc, google/cloud/storage/tests/key_file_integration_test.cc, google/cloud/storage/tests/signed_url_integration_test.cc
Some of the integration tests perform raw HTTP requests, these need to
be in a retry loop, or they introduce flakes in the build.
Fixes #4757
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5664)
=> fix(storage): retry raw HTTP requests

external/googleapis/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5661)
=> feat: proto libraries for Logging and Monitoring services

google/cloud/bigtable/tests/instance_admin_emulator.cc
Fixes #2584
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5679)
=> feat(bigtable): enforce id limits in admin emulator

google/cloud/storage/client.h, google/cloud/storage/internal/default_object_acl_requests.h, google/cloud/storage/internal/default_object_acl_requests_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_bucket_request_test.cc
Close #5680
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5683)
=> feat(storage): add `IfMetagenerationMatch` and `IfMetagenerationNotMatch` for `ListDefaultObjectAcl`

google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
Fixes #5605
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5684)
=> test(spanner): deflake IAM integration tests

ci/custom-words.txt, generator/generator_test.cc, generator/integration_tests/golden/internal/iam_credentials_metadata_decorator.gcpcxx.pb.cc, generator/integration_tests/test.proto, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils.h, generator/internal/descriptor_utils_test.cc, generator/internal/metadata_decorator_generator.cc, generator/internal/predicate_utils.cc, generator/internal/predicate_utils.h, generator/internal/predicate_utils_test.cc
Modify generator to handle alternate formatting of resources in rpc specification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5692)
=> generator(feature): handle metadata resource info not following AIP-4222

bazel/google_cloud_cpp_deps.bzl, external/googleapis/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5694)
=> chore: uprev googleapis dependency

bazel/google_cloud_cpp_deps.bzl, ci/generate-markdown/generate-packaging.sh, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-focal, ci/kokoro/install/Dockerfile.ubuntu-xenial, doc/packaging.md, super/external/protobuf.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5696)
=> chore: uprev protobuf to 3.12.4

ci/kokoro/install/run-installed-programs.sh
This makes debugging easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5711)
=> ci: echo command to connect to install docker images

generator/integration_tests/golden/iam_credentials_client.gcpcxx.pb.cc, generator/integration_tests/golden/iam_credentials_client.gcpcxx.pb.h, generator/integration_tests/golden/iam_credentials_client_test.cc, generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.cc, generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.h, generator/integration_tests/golden/iam_credentials_connection_idempotency_policy.gcpcxx.pb.cc, generator/integration_tests/golden/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h, generator/integration_tests/golden/iam_credentials_connection_test.cc, generator/integration_tests/golden/iam_credentials_idempotency_policy_test.cc, generator/integration_tests/golden/iam_credentials_logging_decorator_test.cc, generator/integration_tests/golden/iam_credentials_metadata_decorator_test.cc, generator/integration_tests/golden/iam_credentials_stub_test.cc, generator/integration_tests/golden/internal/iam_credentials_logging_decorator.gcpcxx.pb.cc, generator/integration_tests/golden/internal/iam_credentials_logging_decorator.gcpcxx.pb.h, generator/integration_tests/golden/internal/iam_credentials_metadata_decorator.gcpcxx.pb.cc, generator/integration_tests/golden/internal/iam_credentials_metadata_decorator.gcpcxx.pb.h, generator/integration_tests/golden/internal/iam_credentials_stub.gcpcxx.pb.cc, generator/integration_tests/golden/internal/iam_credentials_stub.gcpcxx.pb.h, generator/integration_tests/golden/mocks/mock_iam_credentials_connection.gcpcxx.pb.h, generator/integration_tests/test.proto, generator/internal/client_generator.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, generator/internal/predicate_utils.cc, generator/internal/predicate_utils.h, generator/internal/predicate_utils_test.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5712)
=> feature(generator): support proto map type

google/cloud/storage/client.h, google/cloud/storage/emulator/database.py, google/cloud/storage/internal/object_requests.h, google/cloud/storage/tests/object_integration_test.cc, google/cloud/storage/well_known_parameters.h
Close #5704
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5713)
=> feat(storage): Support includeTrailingDelimiter in Client::ListObjects

google/cloud/storage/internal/grpc_client.cc
Close #5671
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5719)
=> fix(storage): Complete implementation of ListBuckets

generator/integration_tests/golden/iam_credentials_client.gcpcxx.pb.cc, generator/integration_tests/golden/iam_credentials_client.gcpcxx.pb.h, generator/integration_tests/golden/iam_credentials_client_test.cc, generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.cc, generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.h, generator/integration_tests/golden/iam_credentials_connection_idempotency_policy.gcpcxx.pb.cc, generator/integration_tests/golden/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h, generator/integration_tests/golden/iam_credentials_connection_test.cc, generator/integration_tests/golden/iam_credentials_idempotency_policy_test.cc, generator/integration_tests/golden/iam_credentials_logging_decorator_test.cc, generator/integration_tests/golden/iam_credentials_metadata_decorator_test.cc, generator/integration_tests/golden/iam_credentials_stub_test.cc, generator/integration_tests/golden/internal/iam_credentials_logging_decorator.gcpcxx.pb.cc, generator/integration_tests/golden/internal/iam_credentials_logging_decorator.gcpcxx.pb.h, generator/integration_tests/golden/internal/iam_credentials_metadata_decorator.gcpcxx.pb.cc, generator/integration_tests/golden/internal/iam_credentials_metadata_decorator.gcpcxx.pb.h, generator/integration_tests/golden/internal/iam_credentials_stub.gcpcxx.pb.cc, generator/integration_tests/golden/internal/iam_credentials_stub.gcpcxx.pb.h, generator/integration_tests/golden/mocks/mock_iam_credentials_connection.gcpcxx.pb.h, generator/integration_tests/test.proto, generator/internal/codegen_utils.cc, generator/internal/codegen_utils_test.cc, generator/internal/descriptor_utils.cc, generator/internal/predicate_utils.cc, generator/internal/predicate_utils_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5715)
=> feature(generator): support single repeated string field in pagination

bazel/google_cloud_cpp_deps.bzl, ci/generate-markdown/generate-packaging.sh, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-focal, ci/kokoro/install/Dockerfile.ubuntu-xenial, doc/packaging.md, super/external/protobuf.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5724)
=> chore: uprev protobuf to 3.14.0

ci/kokoro/install/Dockerfile.fedora, ci/verify_exported_targets/CMakeLists.txt, ci/verify_exported_targets/verify_exported_proto_targets.cc
This creates a test to verify the targets created in
`external/googleapis` remain usable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5741)
=> test: verify googleapis targets remain usable

ci/verify_exported_targets/BUILD
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5744)
=> ci: verify additional legacy Bazel targets

ci/kokoro/windows/build-cmake.ps1, google/cloud/bigtable/internal/common_client_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5743)
=> ci: workaround MSVC+release+x86 build problems

generator/integration_tests/golden/database_admin_client.gcpcxx.pb.cc, generator/integration_tests/golden/iam_credentials_client.gcpcxx.pb.cc, generator/internal/client_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5760)
=> fix(generator): move request parameter when passed by value

google/cloud/spanner/integration_tests/data_types_integration_test.cc, google/cloud/spanner/value.h
Fixes #5762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5763)
=> fix(spanner): compile with Clang 12

generator/generator.h, generator/integration_tests/generator_integration_test.cc, generator/internal/codegen_utils.cc, generator/internal/codegen_utils.h, generator/internal/codegen_utils_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5767)
=> feature(generator): optionally accept copyright year as command line argument

google/cloud/pubsub/ci/lib/pubsub_emulator.sh
Will hopefully reduce some flakiness I've been seeing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5778)
=> test(pubsub): allow more time for the emulator to listen

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/streaming_read_rpc_logging.h, google/cloud/internal/streaming_read_rpc_logging_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5773)
=> feature: add logging decorator for StreamingReadRpc

ci/kokoro/docker/build-in-docker-cmake.sh, ci/kokoro/install/Dockerfile.fedora-components, cmake/CompileProtos.cmake, cmake/GoogleCloudCppCommon.cmake, external/googleapis/CMakeLists.txt, google/cloud/CMakeLists.txt, google/cloud/bigtable/CMakeLists.txt, google/cloud/firestore/CMakeLists.txt, google/cloud/iam/CMakeLists.txt, google/cloud/logging/CMakeLists.txt, google/cloud/pubsub/CMakeLists.txt, google/cloud/spanner/CMakeLists.txt, google/cloud/storage/CMakeLists.txt
Use consistent install component names across all libraries. Add some
tests in the `clang-tidy` build to check for the most common errors with
components. Start a new build to validate the components install usable
libraries.
Part of the work for #5765
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5779)
=> cleanup: use consistent component names

google/cloud/firestore/CMakeLists.txt
Missed this one when making all components consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5784)
=> fix(firestore): use correct install components

google/cloud/storage/legacy.cmake.in
Fixes #5797
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5798)
=> fix(storage): remove unneeded dependency

google/cloud/internal/parse_rfc3339.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5799)
=> cleanup: use case insensitive absl::ParseTime

ci/generate-markdown/generate-packaging.sh, doc/packaging.md
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/5796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5800)
=> doc: add Abseil as a packaging dep

google/cloud/bigtable/internal/readrowsparser.h, google/cloud/bigtable/row_reader.h, google/cloud/bigtable/table_admin.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5806)
=> clean: remove outdated comments about throwing exceptions

generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, generator/internal/predicate_utils.cc, generator/internal/predicate_utils.h, generator/internal/predicate_utils_test.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5805)
=> feature(generator): add utils for streaming read generation

google/cloud/spanner/testing/cleanup_stale_instances.cc, google/cloud/spanner/testing/cleanup_stale_instances.h
In particular, list the requirements on the `std::regex` argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5817)
=> doc(spanner): document CleanupStaleInstances()

ci/kokoro/docker/build-in-docker-quickstart-cmake.sh, ci/kokoro/macos/build-quickstart-cmake.sh, ci/kokoro/macos/upload-cache.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816)
=> ci: cache vcpkg binary

google/cloud/future_generic_test.cc
Fixes #5109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5830)
=> cleanup(common): use bug number for TODO

ARCHITECTURE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5834)
=> doc: ARCHITECTURE.md a rough map for developers

ARCHITECTURE.md
Thanks to @devbww for the review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5837)
=> doc: multiple fixes to ARCHITECTURE.md

google/cloud/bigtable/examples/data_snippets.cc
Fixes #5758
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5839)
=> doc(bigtable): add configure_connection_pool sample

doc/contributor/howto-guide-setup-development-workstation.md
Fixes #5600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5842)
=> doc: add development setup for macOS

google/cloud/storage/tools/run_emulator_utils.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5840)
=> cleanup(storage): fix "launching emulator" banner

google/cloud/internal/setenv.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5845)
=> cleanup: simplify #include for `setenv`

cmake/SelectMSVCRuntime.cmake
A small improvement for the MSVC-based builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5853)
=> cleanup: use CMAKE_MSVC_RUNTIME_LIBRARY when possible

google/cloud/spanner/integration_tests/backup_integration_test.cc
Refactor the `BackupTest` class, mostly in preparation for adding
new PITR and CMEK backup/restore tests.
Cleanup some handling of timestamps by using `absl::Time` for all
time computation, and `spanner::Timestamp` for all expectations.
Remove the assertion that "the server only preserves micros" as the
loss of precision is really due to funneling through `time_point`.
Also only run `CleanupStaleInstances()` once when the test starts,
rather than before every test case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5868)
=> refactor(spanner): reorganize backup_integration_test

google/cloud/spanner/samples/samples.cc
This is mostly to ease the upcoming merge of backup/restore
samples for PITR and CMEK, which include some general fixes
like eliminating unused using declarations, adding missing
newlines, and correcting tag names.  Make those changes here
first so that the future merges are all about the features.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5874)
=> cleanup(spanner): tidy up spanner backup/restore samples

google/cloud/internal/common_options.h, google/cloud/internal/grpc_options.h
Address bww's post-merge comments on https://github.com/googleapis/google-cloud-cpp/pull/5864
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5875)
=> cleanup: small fixes to *_options.h

ci/generate-markdown/generate-packaging.sh, doc/packaging.md
Thanks to @ecourreges-orange for pointing this out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5886)
=> doc: fix inconsistent package vs. target names

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5890)
=> cleanup(spanner): simplify some *AdminClient samples

google/cloud/spanner/integration_tests/backup_integration_test.cc
Stop creating a randomly-named instance in us-west to run the
`CreateBackup()`/`GetBackup()`/`ListBackup()`/`DeleteBackup()`
test, but instead use a randomly-selected, existing instance
from the testing project (just like most other tests).
This then means there is no reason for this test to attempt to
cleanup stale instances.
Also remember to drop the temporary database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5879)
=> cleanup(spanner): stop creating an instance in BackupTest.BackupTest

ci/generate-markdown/generate-packaging.sh, doc/packaging.md
Fixes #5901
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5902)
=> doc: add dropdowns to packaging.md

google/cloud/storage/tests/object_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5911)
=> cleanup: fix TODO entry

google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsub/experimental/schema_admin_connection.cc, google/cloud/pubsub/experimental/schema_admin_connection_test.cc, google/cloud/pubsub/pubsub_client_unit_tests.bzl
Part of the work for #5706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5909)
=> feat(pubsub): use SchemaMetadata in SchemaAdminConnection

google/cloud/pubsub/experimental/schema_admin_client.cc, google/cloud/pubsub/experimental/schema_admin_client.h, google/cloud/pubsub/experimental/schema_admin_client_test.cc, google/cloud/pubsub/integration_tests/schema_admin_integration_test.cc
Part of the work for #5706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5913)
=> feat(pubsub): implement SchemaAdminClient part 2/2

google/cloud/pubsub/experimental/schema_admin_client.h, google/cloud/pubsub/samples/pubsub_samples_common.cc, google/cloud/pubsub/samples/pubsub_samples_common.h, google/cloud/pubsub/samples/pubsub_samples_common_test.cc, google/cloud/pubsub/samples/samples.cc
Part of the work for #5706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5914)
=> feat(pubsub): implement schema admin examples 1/2

ci/kokoro/docker/Dockerfile.fedora-install
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5917)
=> ci: pin cspell@5.2.4 to improve docker image consistency

google/cloud/pubsub/experimental/schema_admin_client.h, google/cloud/pubsub/samples/BUILD, google/cloud/pubsub/samples/CMakeLists.txt, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/samples/samples.proto
Part of the work for #5706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5916)
=> feat(pubsub): implement schema admin examples 2/2

google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/topic_admin_client.h, google/cloud/pubsub/topic_builder.h, google/cloud/pubsub/topic_builder_test.cc
And also add the necessary examples to show how to use this feature.
Fixes #5706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5920)
=> feat(pubsub): support schemas when creating topics

google/cloud/bigtable/cluster_config.h, google/cloud/bigtable/cluster_config_test.cc, google/cloud/bigtable/table_admin.cc, google/cloud/bigtable/table_admin.h
Fixes #5892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5921)
=> feat(bigtable): add CMEK attributes to admin APIs

google/cloud/iam_policy.h, google/cloud/storage/emulator/emulator.py, google/cloud/storage/emulator/gcs/bucket.py, google/cloud/storage/emulator/grpc_server.py, google/cloud/storage/iam_policy.h, google/cloud/storage/internal/bucket_requests.cc, google/cloud/storage/internal/bucket_requests.h, google/cloud/storage/internal/bucket_requests_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_bucket_request_test.cc, google/cloud/storage/internal/grpc_client_failures_test.cc, google/cloud/storage/tests/grpc_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5937)
=> feat(storage): implement {Get,Set}NativeBucketIamPolicy

doc/adr/2021-03-01-deprecated-functions-do-not-have-examples.md, doc/adr/2021-03-0X-deprecated-functions-do-not-have-examples.md
Let's discuss in this PR, and if we agree I will merge (after changing dates).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5932)
=> doc(ADR): deprecated functions do not have examples

google/cloud/spanner/samples/samples.cc
A changed requirement on the PITR `CreateBackup()` sample: use the
current time (from Spanner) as the `version_time` instead of using
the `earliest_version_time` of the database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5943)
=> cleanup(spanner): new version time in spanner_create_backup sample

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5945)
=> doc: prepare CHANGELOG.md for v1.25.0 release

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_failures_test.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/tests/object_integration_test.cc
Fixes: #5910
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5941)
=> feat(storage): implement storage::GrpcClient::DeleteResumableUpload

google/cloud/connection_options.h, google/cloud/connection_options_test.cc
This refactoring takes advantage of the fact that `Options` now offers a
`get<T>()` const-ref accessor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5949)
=> refactor: reimplement ConnectionOptions in terms of Options more

google/cloud/storage/emulator/grpc_server.py, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_bucket_request_test.cc, google/cloud/storage/internal/grpc_client_failures_test.cc, google/cloud/storage/tests/grpc_integration_test.cc
Fixes: #4159
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5957)
=> feat(storage): implement storage::GrpcClient::TestBucketIamPermissions

google/cloud/bigtable/cluster_list_responses.h, google/cloud/bigtable/iam_binding.h, google/cloud/bigtable/instance_list_responses.h, google/cloud/bigtable/mutation_batcher.h, google/cloud/pubsub/internal/publisher_stub.cc, google/cloud/pubsub/internal/publisher_stub.h, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h, google/cloud/spanner/database_admin_connection.h, google/cloud/spanner/instance_admin_connection.h, google/cloud/spanner/internal/database_admin_stub.cc, google/cloud/spanner/internal/database_admin_stub.h, google/cloud/spanner/internal/instance_admin_stub.cc, google/cloud/spanner/internal/instance_admin_stub.h, google/cloud/spanner/internal/partial_result_set_reader.h, google/cloud/spanner/internal/partial_result_set_source.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5965)
=> cleanup: prefer including .pb.h files over .grpc.pb.h

google/cloud/storage/internal/object_requests.cc
Probably the performance impact (if any) is trivial in this case. 
Fixes #5961.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5971)
=> cleanup(storage): avoid using sscanf()

google/cloud/spanner/integration_tests/client_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5981)
=> test(spanner): exercise enumeration of optimizer versions

google/cloud/storage/client.h
Fixes #5978
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5983)
=> doc(storage): describe how to use optional parameters

ci/kokoro/docker/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5982)
=> refactor(generator): only require golden hash check on integration and CI builds

CHANGELOG.md, google/cloud/bigtable/async_row_reader_test.cc, google/cloud/bigtable/filters_test.cc, google/cloud/bigtable/internal/async_longrunning_op_test.cc, google/cloud/bigtable/row_reader_test.cc, google/cloud/completion_queue_test.cc, google/cloud/internal/async_connection_ready_test.cc, google/cloud/spanner/client_test.cc, google/cloud/spanner/integration_tests/client_stress_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/results_test.cc, google/cloud/spanner/value_test.cc, google/cloud/storage/client_sign_url_test.cc, google/cloud/storage/internal/complex_option_test.cc, google/cloud/storage/internal/generic_request_test.cc, google/cloud/storage/tests/object_hash_integration_test.cc, google/cloud/testing_util/validate_metadata.cc
I think these were all unintentional.  Nevertheless, they are hurtful
to some people and there is no need to use them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5988)
=> cleanup: avoid potentially disrespectful terms

ci/kokoro/windows/build-cmake-dependencies.ps1
vcpkg downloads a number of tools (7z, CMake, Ninja) when it runs for
the first time. These downloads do not have a retry loop, so we need to
perform the retries ourselves.
Fixes #6008
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6010)
=> ci: retry initial vcpkg install

ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build.bat
Somehow I wrote the loop to perform a `bazel fetch` but did not include
the line to actually fetch things.
I checked other places where I could have cut&pasted this mistake and
they were right.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6009)
=> ci: perform bazel fetch for Windows build

google/cloud/spanner/internal/options_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6015)
=> test(spanner): sometimes the credentials are null

google/cloud/spanner/client.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h, google/cloud/spanner/internal/connection_impl_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6017)
=> refactor(spanner): connection_impl now uses new Options

ci/generate-markdown/README.md, ci/kokoro/docker/build.sh, ci/kokoro/docker/dump-reports.sh, ci/kokoro/docker/upload-coverage.sh, doc/contributor/howto-guide-setup-development-workstation.md
Fixes: #6013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6018)
=> feat(ci): remove sudo from scripts

google/cloud/spanner/samples/samples.cc
It was using the wrong instance + database id combination for one of the
tests. I did some refactoring because it was hard to see how these tests
worked or to reason about what instances / databases where created when.
Fixes #6020
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6021)
=> test(spanner): fix driver for slow samples

google/cloud/spanner/client.h, google/cloud/spanner/database_admin_connection.h, google/cloud/spanner/instance_admin_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6029)
=> doc(spanner): fix expected option lists

ARCHITECTURE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6036)
=> doc(ARCHITECTURE): fix typo

google/cloud/pubsub/integration_tests/subscriber_integration_test.cc, google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc, google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc, google/cloud/pubsub/internal/batching_publisher_connection_test.cc, google/cloud/pubsub/internal/default_batch_sink_test.cc, google/cloud/pubsub/internal/ordering_key_publisher_connection_test.cc, google/cloud/pubsub/internal/publisher_logging_test.cc, google/cloud/pubsub/internal/publisher_metadata_test.cc, google/cloud/pubsub/internal/publisher_round_robin_test.cc, google/cloud/pubsub/internal/rejects_with_ordering_key_test.cc, google/cloud/pubsub/internal/schema_logging_test.cc, google/cloud/pubsub/internal/sequential_batch_sink_test.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc, google/cloud/pubsub/internal/subscriber_logging_test.cc, google/cloud/pubsub/internal/subscriber_metadata_test.cc, google/cloud/pubsub/internal/subscriber_round_robin_test.cc, google/cloud/pubsub/internal/subscription_concurrency_control_test.cc, google/cloud/pubsub/internal/subscription_lease_management_test.cc, google/cloud/pubsub/internal/subscription_session_test.cc, google/cloud/pubsub/publisher_connection_test.cc, google/cloud/pubsub/publisher_test.cc, google/cloud/pubsub/subscriber_connection_test.cc, google/cloud/pubsub/subscriber_test.cc, google/cloud/pubsub/subscription_admin_client_test.cc, google/cloud/pubsub/subscription_admin_connection_test.cc, google/cloud/pubsub/topic_admin_client_test.cc, google/cloud/pubsub/topic_admin_connection_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6030)
=> cleanup(pubsub): cleanup Status/StatusOr<T> gmock matchers

generator/integration_tests/BUILD, generator/integration_tests/generator_integration_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_client_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_client_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_logging_decorator_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_stub_test.cc, generator/internal/codegen_utils_test.cc, generator/internal/descriptor_utils_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6033)
=> cleanup(generator): cleanup Status/StatusOr<T> gmock matchers

google/cloud/bigtable/internal/readrowsparser_acceptance_tests.inc, google/cloud/bigtable/internal/readrowsparser_test.cc, google/cloud/bigtable/tools/convert_acceptance_tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6039)
=> cleanup(bigtable): cleanup Status/StatusOr<T> gmock matchers

ARCHITECTURE.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6045)
=> doc(ARCHITECTURE): add section about `Options`

ci/kokoro/docker/build-in-docker-bazel.sh, ci/kokoro/docker/build-in-docker-cmake.sh, ci/kokoro/macos/build-bazel.sh, ci/kokoro/macos/build-cmake.sh, ci/kokoro/windows/build-bazel.ps1, google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh, google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh, google/cloud/bigtable/tests/data_integration_test.cc, google/cloud/internal/log_impl_test.cc, google/cloud/log_test.cc, google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh, google/cloud/pubsub/ci/run_integration_tests_emulator_cmake.sh, google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh, google/cloud/spanner/samples/samples.cc, google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh, google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh, google/cloud/testing_util/example_driver.cc
Part of the work for #4758 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6050)
=> test: log the last few RPCs on sample failures

google/cloud/bigtable/examples/table_admin_snippets.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6051)
=> fix(bigtable): multiple region tags on same line

google/cloud/pubsub/samples/samples.cc
Making the integration tests reliable requires verifying that
subscribers actually receive events and that they shutdown properly. We
were weaving the code to do this in the middle of the example, which was
not very readable. Now the code surrounds the example (with some
refactoring), but does not appear in the extracted Doxygen or the cloud
site examples.
Fixes #5598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6061)
=> cleanup(pubsub): make some examples more readable

google/cloud/storage/parallel_upload.cc, google/cloud/storage/parallel_upload.h, google/cloud/storage/parallel_uploads_test.cc
Part of the work for #6060
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6064)
=> fix(storage): move disabling consts

google/cloud/iam_bindings.h
Part of the work for #6060
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6068)
=> fix(common): move disabling consts

google/cloud/internal/diagnostics_push.inc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6072)
=> cleanup: fix #warning message for unsupported "diagnostic push"

google/cloud/storage/client.h, google/cloud/storage/object_stream.h
Fixes #5828
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6075)
=> doc(storage): better description for ObjectWriteStream

ci/lib/io.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6079)
=> fix(ci): check for tty before calling tput

google/cloud/bigquery/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6098)
=> fix(bigquery): pkg-config dep for protos

ci/cloudbuild/triggers/cmake-install-ci.yaml, ci/cloudbuild/triggers/cmake-install.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6100)
=> ci: add yaml configs for cmake-install build

google/cloud/bigquery/integration_tests/bigquery_read_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6102)
=> feature(bigquery): add success case integration tests

ci/cloudbuild/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6110)
=> ci: fix typo

ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6107)
=> chore: add patch to Dockerfile.fedora-libcxx-msan

ci/cloudbuild/builds/integration.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6117)
=> ci: use io::log_h2 in GCB integration build

.bazelignore, ci/etc/integration-tests-config.sh, google/cloud/bigquery/quickstart/BUILD, google/cloud/bigquery/quickstart/CMakeLists.txt, google/cloud/bigquery/quickstart/Makefile, google/cloud/bigquery/quickstart/README.md, google/cloud/bigquery/quickstart/WORKSPACE, google/cloud/bigquery/quickstart/quickstart.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6116)
=> feature(bigquery): add quickstart

ci/cloudbuild/builds/cmake-super.sh, ci/cloudbuild/triggers/cmake-super-ci.yaml, ci/cloudbuild/triggers/cmake-super.yaml, ci/cloudbuild/ubuntu-bionic.Dockerfile
The build yaml files are included in this PR, but they won't be enabled until after this PR is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6128)
=> ci(gcb): add cmake-super build on ubuntu-bionic

ci/cloudbuild/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6131)
=> doc(ci): document GCB testing principles

ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.fedora, ci/kokoro/install/Dockerfile.fedora-components, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-focal, ci/kokoro/install/Dockerfile.ubuntu-xenial, google/cloud/bigquery/quickstart/Makefile, google/cloud/bigquery/quickstart/quickstart.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6129)
=> chore(bigquery): enable quickstart building

ci/cloudbuild/builds/integration.sh, google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6141)
=> ci(gcb): enable storage integration tests

ci/cloudbuild/builds/integration.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6144)
=> ci: fix typos in some comments

ci/cloudbuild/builds/integration.sh, ci/kokoro/docker/build-in-docker-bazel.sh, ci/kokoro/macos/build-bazel.sh, ci/kokoro/windows/build-bazel.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6147)
=> ci: fix tracing configuration for storage library

google/cloud/future_generic_test.cc, google/cloud/future_void_test.cc
Fixes #6157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6159)
=> test(common): deflake another future test

ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6158)
=> chore(bigquery): add windows quickstart env var

CMakeLists.txt, cmake/SelectMSVCRuntime.cmake
Fixes #5852
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6190)
=> cleanup: require CMake >= 3.15 with MSVC

google/cloud/storage/client_options.cc, google/cloud/storage/client_options.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6200)
=> refactor(storage): compute default options in a single function

ci/cloudbuild/triggers/clang-38-ci.yaml, ci/cloudbuild/triggers/clang-38-pr.yaml, ci/cloudbuild/triggers/gcc-54-ci.yaml, ci/cloudbuild/triggers/gcc-54-pr.yaml
This fixes a bug that I introduced in #6135.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6217)
=> ci(gcb): run clang-38 and gcc-54 builds on xenial

doc/contributor/howto-guide-setup-cmake-environment.md, doc/contributor/howto-guide-setup-development-workstation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6216)
=> docs: fix typos

google/cloud/storage/tests/bucket_integration_test.cc
Fixes #6232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6234)
=> fix(storage): deflake IAM integration test

.dockerignore, ci/.dockerignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6237)
=> cleanup: tweak dockerignore to rebuild images less often

ci/cloudbuild/build.sh
With the addition of #6239 and other upcoming "demo" builds, we'll have
a several trigger files defining builds that all use the same underlying
build script. For example, the demo builds will all use the same
`demo-install.sh` script. So in order to run these builds from the
command-line conveniently with `build.sh`, we need a way to say "run the
build defined by trigger X".
This PR adds the `--trigger=name` flag, which takes the name of a build
trigger file where it will extract the build script and distro.
BREAKING CHANGE (not user facing): If anyone else was already using this
script for builds, the following syntax is changing.
```
build.sh asan  # Will no longer work; Instead use
build.sh -t asan-pr
```
This PR also expands the help docs for this script to hopefully make it
easier …
=> ci(gcb): build.sh now has a --trigger flag

google/cloud/storage/quickstart/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6249)
=> doc(storage): wrong arguments for quickstart program

ci/cloudbuild/builds/noex.sh, ci/cloudbuild/triggers/noex-ci.yaml, ci/cloudbuild/triggers/noex-pr.yaml
The triggers will be active after I merge this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6250)
=> ci(gcb): enable noex build

ci/cloudbuild/builds/cxx17.sh, ci/cloudbuild/triggers/cxx17-ci.yaml, ci/cloudbuild/triggers/cxx17-pr.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6252)
=> ci(gcb): add cxx17 build

ci/cloudbuild/builds/libcxx.sh, ci/cloudbuild/triggers/libcxx-ci.yaml, ci/cloudbuild/triggers/libcxx-pr.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6253)
=> ci(gcb): add libcxx build

ci/cloudbuild/builds/msan.sh, ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile, ci/cloudbuild/triggers/msan-ci.yaml, ci/cloudbuild/triggers/msan-pr.yaml
This build is a little strange because it requires a custom-built
libc++, which we build in the Dockerfile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6259)
=> ci(gcb): add msan build

ci/cloudbuild/builds/coverage.sh, ci/cloudbuild/builds/lib/integration.sh
Fixes: #6276
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6277)
=> ci(gcb): run slow spanner instance tests during coverage build

ci/cloudbuild/README.md, ci/cloudbuild/build.sh, ci/cloudbuild/builds/README.md
These are a couple small cleanups and documentation improvements that I
had lying around.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6281)
=> ci(gcb): misc cleanups

ci/cloudbuild/cloudbuild.yaml
This will be empty for non-PR builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6287)
=> ci(gcb): include PR number as a build tag

generator/integration_tests/golden/CMakeLists.txt, generator/integration_tests/golden/google_cloud_cpp_generator_golden_tests.bzl, generator/integration_tests/golden/tests/golden_thing_admin_option_defaults_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6288)
=> fix(generator): missing tests

ci/cloudbuild/builds/check-abi.sh, ci/cloudbuild/dockerfiles/fedora.Dockerfile, ci/cloudbuild/triggers/check-abi-ci.yaml, ci/cloudbuild/triggers/check-abi-pr.yaml
This build does not yet include an "update abi" mode, but that'll come
in a later PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6314)
=> ci(gcb): add check-abi build

google/cloud/storage/tests/grpc_integration_test.cc
Now that we have builds running all the integration tests using the
hybrid client this is redundant. Removing the integration test will
simplify other cleanups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6320)
=> cleanup(storage): remove redundant integration test

ci/cloudbuild/builds/checkers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6322)
=> ci(gcb): add generator hash checks to checkers build

ci/kokoro/docker/build-in-docker-bazel.sh, ci/kokoro/docker/build-in-docker-cmake.sh, ci/kokoro/docker/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6318)
=> ci: some further tweaking of build.sh logging

google/cloud/spanner/database_admin_connection.h, google/cloud/spanner/instance_admin_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6317)
=> cleanup(spanner): quash some doxygen warnings

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/read_partition.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6326)
=> cleanup(spanner): adjust naming of RequestOptions.Priority values

google/cloud/internal/credentials.h, google/cloud/internal/credentials_test.cc, google/cloud/internal/grpc_access_token_authentication.cc, google/cloud/internal/grpc_access_token_authentication.h, google/cloud/internal/grpc_access_token_authentication_test.cc, google/cloud/storage/internal/access_token_credentials.cc, google/cloud/storage/internal/access_token_credentials.h, google/cloud/storage/internal/access_token_credentials_test.cc
Fixes #6302
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6325)
=> feat: support errors in DynamicAccessTokenCredentials

ci/cloudbuild/builds/asan.sh, ci/cloudbuild/builds/clang-tidy.sh, ci/cloudbuild/builds/cmake-clang.sh, ci/cloudbuild/builds/cmake-gcc.sh, ci/cloudbuild/builds/coverage.sh, ci/cloudbuild/builds/cxx17.sh, ci/cloudbuild/builds/gcs-grpc.sh, ci/cloudbuild/builds/integration.sh, ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/builds/libcxx.sh, ci/cloudbuild/builds/msan.sh, ci/cloudbuild/builds/noex.sh, ci/cloudbuild/builds/tsan.sh, ci/cloudbuild/builds/ubsan.sh, ci/cloudbuild/builds/xsan.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6329)
=> ci(gcb): run integration tests with cmake builds

ci/cloudbuild/builds/rotate-keys.sh
Fixes: #6167
See the comments at the top of `rotate-keys.sh` for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6331)
=> ci(gcb): add rotate-keys *manual* build

ci/cloudbuild/cloudbuild.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6335)
=> ci: remove docker pull noise from main step

ci/cloudbuild/builds/log-linker.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6338)
=> ci(gcb): make GCB logs link directly to PR

.github/DEPENDENCIES.md, .github/dependabot.yml, .github/workflows/dependencies.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6339)
=> ci: enable dependabot

release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6341)
=> doc(release): update our release instructions for GCB changes

ci/cloudbuild/build.sh, ci/cloudbuild/builds/publish-docs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6355)
=> fix(gcb): set env vars so --local builds work

ci/cloudbuild/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6362)
=> doc: add link and heading to gcb readme

ci/cloudbuild/builds/bazel-targets.sh, ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/triggers/bazel-targets-ci.yaml, ci/cloudbuild/triggers/bazel-targets-pr.yaml
Fixes: #6372
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6382)
=> ci(gcb): add builds to verify current/deprecated targets

ci/cloudbuild/builds/integration-daily.sh, ci/cloudbuild/builds/integration-nightly.sh, ci/cloudbuild/builds/lib/integration.sh
Fixes: #6384
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6386)
=> ci(gcb): add integration-daily build to GCB

generator/internal/descriptor_utils_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6392)
=> chore(generator): formatting

google/cloud/storage/internal/access_token_credentials.h, google/cloud/storage/tests/unified_credentials_integration_test.cc
Part of the work for #6309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6396)
=> cleanup: remove remnants of AccessTokenSource

google/cloud/bigtable/table_sample_row_keys_test.cc
Fixes #6398 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6400)
=> cleanup(bigtable): remove duplicate test

ci/cloudbuild/notifiers/logs/function/function.cc
A small improvement for #6397.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6405)
=> ci(gcb): add title for public logs index.html page

ci/cloudbuild/notifiers/logs/README.md, ci/cloudbuild/notifiers/logs/function/function.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6404)
=> ci: support testing for the logs notifier

ci/cloudbuild/notifiers/logs/function/CMakeLists.txt, ci/cloudbuild/notifiers/logs/function/function.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6406)
=> refactor: make logs notifier easier to explain

ci/cloudbuild/notifiers/logs/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6411)
=> ci: fix mistake in test instructions

ci/cloudbuild/build.sh, ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/builds/lib/quickstart.sh
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/6410
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6412)
=> ci: enable integration tests from local docker

ci/cloudbuild/builds/check-abi.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6414)
=> ci: fix abi compat_report to be written in cmake-out

.github/trusted-contribution.yml
This will automate the GCB triggers for renovate robotic PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6415)
=> chore: configure trusted-contribution bot

ci/cloudbuild/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6416)
=> ci: avoid root-owned /h/.config/gcloud dir

.github/renovate.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6419)
=> chore: configure renovate to run weekly

ci/cloudbuild/builds/demo-install.sh, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile, ci/generate-markdown/dockerfile2markdown.sh, ci/generate-markdown/generate-packaging.sh
Fixes: #6241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6423)
=> ci: use tags that don't conflict w/ snippet-bot

ci/cloudbuild/builds/lib/quickstart.sh, google/cloud/bigquery/quickstart/Makefile, google/cloud/bigtable/quickstart/Makefile, google/cloud/pubsub/quickstart/Makefile, google/cloud/spanner/quickstart/Makefile, google/cloud/storage/quickstart/Makefile
Fixes: #6427
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6428)
=> ci: quickstart Makefile doesn't leave binary in repo

CHANGELOG.md, super/ExternalProjectHelper.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6448)
=> doc: updates notes about super builds

ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6451)
=> cleanup(gcb): no need for multi-stage images

ci/check-style.sh, ci/cloudbuild/builds/checkers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6454)
=> cleanup(gcb): do not force color diffs

google/cloud/internal/streaming_read_rpc.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6456)
=> cleanup(common): fix include for streaming_read_rpc.cc

ci/cloudbuild/builds/lib/integration.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6469)
=> ci: reduce noise from pip install

ci/cloudbuild/cloudbuild.yaml
Fixes: #6458
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6470)
=> ci(gcb): cancel ongoing builds on new PR push

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6479)
=> chore(spanner): correct some sample tags

google/cloud/iam/integration_tests/iam_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6476)
=> refactor(iam): modify list rpcs in success test cases to verify created entities

google/cloud/storage/tests/error_injection_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6492)
=> cleanup(storage): fix clang-tidy-12 warnings

google/cloud/kms_key_name_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6494)
=> fix(common): compilation errors with GCC 11

google/cloud/iam/integration_tests/iam_integration_test.cc, google/cloud/storage/tests/error_injection_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6495)
=> fix(iam): list contains criteria in role integration test

google/cloud/bigtable/benchmarks/benchmark.cc, google/cloud/bigtable/benchmarks/benchmark.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6496)
=> test(bigtable): fix UBSAN errors with clang-12

ci/cloudbuild/triggers/asan-ci.yaml, ci/cloudbuild/triggers/asan-pr.yaml, ci/cloudbuild/triggers/ubsan-ci.yaml, ci/cloudbuild/triggers/ubsan-pr.yaml, ci/cloudbuild/triggers/xsan-ci.yaml, ci/cloudbuild/triggers/xsan-pr.yaml
I tested these manually before, and I am running the tests again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6519)
=> ci: use Fedora:34 for asan/ubsan/xsan

ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
Part of the work for #6524 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6528)
=> ci: upgrade demo-install-fedora build to Fedora:34

ci/cloudbuild/triggers/publish-docs-ci.yaml, ci/cloudbuild/triggers/publish-docs-pr.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6534)
=> ci: upgrade publish-docs build to Fedora:34

ci/cloudbuild/builds/cmake-oldest-deps.sh
In my local tests this seems to shave a minute or two off overal build
times for this build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6544)
=> ci(gcb): use ccache when building vcpkg binary

google/cloud/spanner/samples/samples.cc
If PickConfig() cannot find an instance config that satisfies its
filters, have it return the first instance config (if one exists).
This makes it work naturally when run against the Spanner emulator,
or any other test service where the configs are not so predictable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6539)
=> cleanup(spanner): make samples PickConfig() less restrictive

ci/cloudbuild/builds/cmake-oldest-deps.sh, ci/cloudbuild/builds/quickstart-cmake.sh, ci/kokoro/macos/build-quickstart-cmake.sh, ci/kokoro/windows/build-cmake-dependencies.ps1
AFAICT this will use the same version for all builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6549)
=> chore: upgrade vcpkg to latest release

google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/object_read_range_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
Add some tests for `gcs::ReadRange()`, `gcs::ReadFromOffset()`, and
`gcs::ReadLast()`.
Part of the work for #6516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6551)
=> test(storage): more detailed tests for ReadRange

google/cloud/storage/tests/object_read_range_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6555)
=> test(storage): fix build for Windows+x86

google/cloud/storage/internal/grpc_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6556)
=> fix(storage): compile GCS+gRPC with Windows+x86

google/cloud/bigtable/testing/mock_response_reader.h
This class currently encourages an ownership hack that works around a gRPC API
issue that is [being fixed](https://github.com/grpc/proposal/pull/238). At that
point the tests that use this class will start failing, because they manage it
using **two different `std::unique_ptr` objects**.
Prevent them failing by overriding the upcoming `Destroy` method to do nothing.
This preserves the existing behavior. Because I haven't used the `override`
keyword, this works before and after the gRPC change, decoupling this issue
from the import of the gRPC change.
Longer term it would be better to make the use of this class not require the
ownership hack at all, but that is a larger project. In the meantime this
change unblocks fixing the need for such hacks for other subclasses that don't
want to …
=> cleanup: prevent behavior change from a gRPC change

CMakeLists.txt, ci/cloudbuild/builds/publish-docs.sh, cmake/GoogleCloudCppCommon.cmake, google/cloud/CMakeLists.txt, google/cloud/bigquery/CMakeLists.txt, google/cloud/iam/CMakeLists.txt, google/cloud/logging/CMakeLists.txt, google/cloud/pubsub/CMakeLists.txt, google/cloud/spanner/CMakeLists.txt, google/cloud/storage/CMakeLists.txt
Part of: #6543
This fixes all the remaining doxygen errors by ensuring that the needed protos are all generated before doxygen runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6573)
=> fix: all remaining doxygen errors

ci/cloudbuild/notifiers/alerts/function/function.cc
Fixes: #6581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6582)
=> ci(gcb): alert on all non-ok statuses

ci/cloudbuild/triggers/cmake-install-ci.yaml, ci/cloudbuild/triggers/cmake-install-pr.yaml, ci/cloudbuild/triggers/noex-ci.yaml, ci/cloudbuild/triggers/noex-pr.yaml, ci/cloudbuild/triggers/shared-ci.yaml, ci/cloudbuild/triggers/shared-pr.yaml
Part of #6524.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6591)
=> ci: upgrade cmake-install, noex, and shared to Fedora:34

google/cloud/bigtable/async_list_app_profiles_test.cc, google/cloud/bigtable/async_list_clusters_test.cc, google/cloud/bigtable/async_list_instances_test.cc, google/cloud/bigtable/instance_admin_test.cc, google/cloud/bigtable/internal/async_longrunning_op_test.cc, google/cloud/bigtable/internal/async_poll_op_test.cc, google/cloud/bigtable/internal/async_retry_multi_page_test.cc, google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll_test.cc, google/cloud/bigtable/internal/logging_instance_admin_client_test.cc, google/cloud/bigtable/table_admin_test.cc, google/cloud/bigtable/testing/mock_async_failing_rpc_factory.h, google/cloud/bigtable/testing/mock_mutate_rows_reader.h, google/cloud/bigtable/testing/mock_read_rows_reader.h, google/cloud/bigtable/testing/mock_response_reader.h, google/cloud/completion_queue_test.cc
Obviously we do not need 3 copies of this class.
Fixes #6592.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6594)
=> cleanup: deduplicate MockAsyncResponseReader<R>

cmake/GoogleCloudCppCommon.cmake, google/cloud/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6596)
=> ci: support new gRPC examples in publish-docs

ci/cloudbuild/README.md, ci/cloudbuild/cloudbuild.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6598)
=> ci(gcb): move builds to custom worker pool

google/cloud/storage/emulator/database.py, google/cloud/storage/emulator/gcs/holder.py, google/cloud/storage/emulator/tests/test_gcs.py, google/cloud/storage/emulator/tests/test_utils.py
Round two of #6477
cc: @tritone 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6574)
=> fix(storage): address behavior bugs

google/cloud/BUILD, google/cloud/grpc_utils/BUILD, google/cloud/storage/internal/object_streambuf.cc, google/cloud/storage/tests/object_insert_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6624)
=> cleanup: standardize some TODO's

ci/cloudbuild/builds/log-linker.sh, cmake/FindgRPC.cmake, google/cloud/spanner/BUILD, google/cloud/spanner/benchmarks/benchmarks_config.cc, google/cloud/spanner/benchmarks/benchmarks_config.h, google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc, google/cloud/spanner/internal/session_pool.cc, google/cloud/status_or.h, google/cloud/testing_util/chrono_literals.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6626)
=> cleanup(common): update/remove TODOs for some closed issues

google/cloud/pubsub/internal/subscription_lease_management.cc, google/cloud/pubsub/internal/subscription_lease_management.h, google/cloud/pubsub/internal/subscription_lease_management_test.cc, google/cloud/pubsub/internal/subscription_session.cc, google/cloud/pubsub/internal/subscription_session.h, google/cloud/pubsub/internal/subscription_session_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6631)
=> refactor(pubsub): remove timer factory

google/cloud/storage/emulator/README.md, google/cloud/storage/emulator/database.py, google/cloud/storage/emulator/emulator.py, google/cloud/storage/emulator/requirements.txt, google/cloud/storage/emulator/tests/test_utils.py, google/cloud/storage/emulator/utils/common.py
cc: @tritone 
Adding Retry Test API support to the emulator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6611)
=> feat(storage): add Retry Test API to emulator

google/cloud/iam/integration_tests/iam_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6638)
=> fix(iam): flake in service account and key crud integration tests

doc/adr/2021-05-18-credential-failures-participate-in-retry-loop.md
Fixes #6337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6603)
=> doc(adr): handling token refresh failures

google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6645)
=> refactor(spanner): reuse Experiment methods in single rows benchmark

google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
Towards addressing: https://github.com/googleapis/google-cloud-cpp/issues/6641
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6644)
=> test(storage): add flaky test retries to bazel build

ci/cloudbuild/triggers/cxx17-ci.yaml, ci/cloudbuild/triggers/cxx17-pr.yaml
Part of the work for #6524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6647)
=> ci: upgrade cxx17 to Fedora:34

google/cloud/spanner/benchmarks/README.md, google/cloud/spanner/benchmarks/benchmarks_config.cc, google/cloud/spanner/benchmarks/benchmarks_config.h, google/cloud/spanner/benchmarks/benchmarks_config_test.cc, google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc, google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
Fixes #4032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6659)
=> feat(spanner): use multiple channels instead of multiple client for the multiple rows cpu benchmark

ci/cloudbuild/dockerfiles/fedora-34.Dockerfile
... since "checkers" now uses its own Dockerfile: https://github.com/googleapis/google-cloud-cpp/pull/6661
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6663)
=> ci: remove deps that are no longer needed

ci/cloudbuild/builds/checkers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6669)
=> ci: fix test condition per devbww

ci/cloudbuild/builds/checkers.sh
This PR reorders the checkers so that the slow ones are run last to give
the user more useful feedback quicker. It also makes the `shellcheck`
step run in parallel, which cuts its time in half. Moved a couple other
checks to more logical places in the order.
At this point `cmake-format` and `clang-format` are the slowest, taking about 10 seconds each.
Not sure there's anything to be done about this, but I think it's probably fine for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6668)
=> ci: move slow checkers last

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6665)
=> refactor(spanner): simplify multiple rows benchmark experiments

ci/kokoro/macos/build-cmake.sh, ci/kokoro/macos/build.sh
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/6680
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/6440
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6681)
=> ci(macos): homebrew tweaks to work on intel and ARM macs

ci/kokoro/macos/build-cmake.sh
TIL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6684)
=> ci(macos): use brew --prefix

google/cloud/pubsub/internal/subscription_message_queue_test.cc
Fixes #6683
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6686)
=> test(pubsub): reduce system entropy used by test

ci/lib/io.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6693)
=> ci: log timestamp with io::log_h{1,2}

ci/cloudbuild/cache.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6702)
=> ci(cache): log cache file sizes

ci/cloudbuild/triggers/bazel-targets-ci.yaml, ci/cloudbuild/triggers/bazel-targets-pr.yaml, ci/cloudbuild/triggers/gcs-grpc-ci.yaml, ci/cloudbuild/triggers/gcs-grpc-pr.yaml, ci/cloudbuild/triggers/generate-libraries-ci.yaml, ci/cloudbuild/triggers/generate-libraries-pr.yaml, ci/cloudbuild/triggers/libcxx-ci.yaml, ci/cloudbuild/triggers/libcxx-pr.yaml
Part of the work for #6524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6708)
=> ci: update builds to Fedora:34

google/cloud/bigtable/admin_client.h, google/cloud/bigtable/data_client.h, google/cloud/bigtable/instance_admin_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6715)
=> cleanup(bigtable): remove unused forward class declarations

generator/integration_tests/golden/golden_kitchen_sink_connection.cc, generator/integration_tests/golden/golden_thing_admin_connection.cc, generator/internal/connection_generator.cc, google/cloud/bigquery/bigquery_read_connection.cc, google/cloud/iam/iam_connection.cc, google/cloud/iam/iam_credentials_connection.cc, google/cloud/logging/logging_service_v2_connection.cc
Keep the background threads in the `*Connection` class. Initialize it
from the `google::cloud::Options` parameter. A future PR will use
the background threads (and its completion queue) in the `*Stub`.
Part of the work for #6721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6728)
=> feat: support background threads in generated libraries

.github/renovate.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6738)
=> chore: teach renovate how to update bazelisk

ci/kokoro/windows/build-32.bat, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-quickstart-bazel.ps1, ci/kokoro/windows/build.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6747)
=> ci(windows): use bazelisk

ci/cloudbuild/builds/log-linker.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6751)
=> ci: include link to all kokoro logs

google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/create_client_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
These functions are marked as deprecated (via comments), and no longer
recommended, but should be tested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6754)
=> test(storage): more tests for backwards compability

google/cloud/iam/integration_tests/iam_credentials_integration_test.cc
Part of the work for #6724
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6774)
=> test(iam): disable more integration tests

ci/cloudbuild/builds/lib/integration.sh
Part of: https://github.com/googleapis/google-cloud-cpp/issues/6724
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6775)
=> ci: disable iam integration until its deflaked

ci/cloudbuild/builds/lib/integration.sh
Fixes #6772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6776)
=> test(bigquery): enable integration tests in GCB builds

google/cloud/iam/integration_tests/iam_credentials_integration_test.cc, google/cloud/iam/integration_tests/iam_integration_test.cc, google/cloud/logging/integration_tests/logging_integration_test.cc
This change will make it easier to change the integration tests for
generated libraries.
Part of the changes for #6721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6780)
=> refactor: easier to change integration tests

bazel/google_cloud_cpp_deps.bzl, external/googleapis/CMakeLists.txt, google/cloud/bigquery/bigquery_read_client.h, google/cloud/iam/iam_client.h, google/cloud/iam/iam_credentials_client.h, google/cloud/logging/logging_service_v2_client.h
For `google.spanner.admin.instance.v1.Instance.processing_units`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6786)
=> chore: update googleapis version

google/cloud/pubsub/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6784)
=> doc(pubsub): an example for publisher flow control

google/cloud/pubsub/internal/batching_publisher_connection_test.cc
Under load the two messages in the `DefaultMakesProgress` test can be
merged into a single batch, with this change the test handles both
cases. We have other tests to verify the batches are "large enough", so
there is no need to do that in this test too.
Fixes #6537
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6791)
=> test(pubsub): deflake BatchingPublisherConnection test

google/cloud/storage/client_write_object_test.cc
This new test verifies that resumable uploads abort (do not finalize) if
one of the intermediate `UploadChunk()` requests has a permanent error
or otherwise exhaust the retry policy. I wrote this test expecting that
the library had a bug and needed fixing, but turns out I do not give
myself enough credit.
Fixes #6779
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6790)
=> test(storage): resumable uploads abort on errors

ci/cloudbuild/builds/lib/bazel.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6806)
=> ci(gcb): disable test caching on daily builds too

google/cloud/internal/minimal_iam_credentials_stub.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6813)
=> fix(common): remove blocking call in MinimalIamCredentials

generator/integration_tests/generator_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6815)
=> test(generator): fix crashes on test failure

generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6814)
=> refactor(generator): de-duplicate mock stubs

google/cloud/internal/async_polling_loop.cc, google/cloud/internal/async_polling_loop_test.cc
Using `std::weak_ptr<>` leaves nothing holding ownership of the
`AsyncPollingLoopImpl` object. With this change the continuations for
the timer and asynchronous operations own the object, and they in turn
are owned by the completion queue.
Part of the work for #6821 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6816)
=> fix(common): lifetime management in AsyncPollingLoop

ci/cloudbuild/builds/lib/bazel.sh, ci/kokoro/macos/builds/bazel.sh, ci/kokoro/macos/builds/quickstart-bazel.sh, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-quickstart-bazel.ps1, google/cloud/bigquery/quickstart/README.md, google/cloud/bigtable/doc/bigtable-hello-instance-admin.dox, google/cloud/bigtable/doc/bigtable-hello-table-admin.dox, google/cloud/bigtable/doc/bigtable-hello-world.dox, google/cloud/bigtable/doc/bigtable-main.dox, google/cloud/bigtable/doc/bigtable-samples-data-client.dox, google/cloud/bigtable/doc/bigtable-samples-grpc-credentials.dox, google/cloud/bigtable/quickstart/README.md, google/cloud/pubsub/doc/pubsub-main.dox, google/cloud/pubsub/quickstart/README.md, google/cloud/spanner/doc/spanner-main.dox, google/cloud/spanner/quickstart/README.md, google/cloud/spanner/samples/README.md, google/cloud/storage/doc/storage-main.dox, google/cloud/storage/quickstart/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6825)
=> cleanup(doc): master -> main

google/cloud/internal/polling_loop.h
This is just a cleanup after some of the work for #6821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6823)
=> refactor(common): re-use value extractors in synchronous polling loop

google/cloud/pubsub/internal/batching_publisher_connection_test.cc
I believe this fixes #5774. I could be wrong, but we can re-open the bug if I am.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6828)
=> test(pubsub): deflake batching_publisher_connection_test

ci/cloudbuild/builds/lib/vcpkg.sh, ci/kokoro/macos/builds/quickstart-cmake.sh, ci/kokoro/windows/build-cmake-dependencies.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6829)
=> chore: retrieve repo via vcpkg by commit hash

google/cloud/bigtable/doc/bigtable-main.dox, google/cloud/bigtable/doc/bigtable-samples-grpc-credentials.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6838)
=> doc(bigtable): add IAM examples to Bigtable gRPC doc, fix typos/hyperlinks

google/cloud/bigtable/examples/data_snippets.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6834)
=> docs: fix connection pool size for samples

google/cloud/pubsub/internal/batching_publisher_connection_test.cc
This fixes the import.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6850)
=> fix: cast to std::string which works with string and Cord

google/cloud/internal/extract_long_running_result.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6849)
=> fix: include which breaks during our import

ci/cloudbuild/builds/lib/cmake.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6857)
=> ci(cmake): ctest will print output from failed tests

google/cloud/pubsub/internal/batching_publisher_connection_test.cc
I think this is the third time I declare these to be fixed. In all cases
it seems that better control of the background threads was needed, so I
searched for any other background thread problems, could not find any.
Fixes #5774 (again)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6858)
=> test(pubsub): deflake batching_publisher_connection

doc/contributor/howto-guide-setup-development-workstation.md, google/cloud/examples/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6863)
=> cleanup(doc): fix some links

google/cloud/bigtable/doc/bigtable-hello-instance-admin.dox, google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc, google/cloud/bigtable/examples/bigtable_table_admin_backup_snippets.cc, google/cloud/bigtable/examples/data_async_snippets.cc, google/cloud/bigtable/examples/data_snippets.cc, google/cloud/bigtable/examples/table_admin_iam_policy_snippets.cc
* fix usage for `async-read-modify-write`
* take `row-key` as an argument for `apply`
* typos/readability changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6862)
=> cleanup(bigtable): miscellaneous example cleaning

google/cloud/bigtable/examples/data_async_snippets.cc, google/cloud/bigtable/examples/read_snippets.cc
`AsyncReadRowsWithLimit()` contained identical code to `AsyncReadRows()`. They were both using the same [overload](https://github.com/googleapis/google-cloud-cpp/blob/a5d37eee2c1b5010738d51e3b7611d03cc6afa13/google/cloud/bigtable/table.h#L926) of `Table::AsyncReadRows`
I decided to make the limit settable via command line. And did the same for the synchronous version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6867)
=> cleanup(bigtable): fix AsyncReadRowsWithLimit example

google/cloud/examples/grpc_credential_types.cc
Add some debugging messages to help troubleshooting, and flush these
debug messages to make it easier to grok any errors.
Part of the work for #6731
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6845)
=> test: improve output for troubleshooting

google/cloud/storage/internal/grpc_client_test.cc
Fixes #4217
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6877)
=> cleanup(storage): remove obsolete TODO entry

google/cloud/storage/tests/object_media_integration_test.cc, google/cloud/storage/tests/object_resumable_write_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6886)
=> cleanup(storage): enable more integration tests with gRPC

google/cloud/storage/benchmarks/CMakeLists.txt, google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/benchmarks/benchmark_utils.h, google/cloud/storage/benchmarks/create_dataset.cc, google/cloud/storage/benchmarks/create_dataset_options.cc, google/cloud/storage/benchmarks/create_dataset_options.h, google/cloud/storage/benchmarks/create_dataset_options_test.cc, google/cloud/storage/benchmarks/storage_benchmark_programs.bzl, google/cloud/storage/benchmarks/storage_benchmarks.bzl, google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
I will need to run benchmarks over a fixed dataset. This is a small tool
to create these datasets.
Part of the work for #6884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6887)
=> feat(storage): create datasets for benchmarks

google/cloud/storage/internal/object_streambuf.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6889)
=> cleanup(storage): reduce tracing noise

generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_stub.h, generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6890)
=> cleanup(generator): remove additional mock dups

google/cloud/storage/internal/object_streambuf.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6892)
=> feat(storage): micro-optimization for downloads

google/cloud/storage/benchmarks/throughput_experiment_test.cc
Fixes #6893
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6898)
=> test(storage): deflake benchmark integration test

google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/object_write_preconditions_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
Verify that `ObjectWrite()` and preconditions work as expected.
Motivated by #6896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6904)
=> test(storage): verify writes with pre-conditions work

google/cloud/iam/samples/iam_samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6918)
=> fix(iam): SetIamPolicy sample from attempting concurrent changes

google/cloud/storage/tests/bucket_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6914)
=> test(storage): public access prevention in prod

release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6920)
=> doc: update release/README.md

google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/benchmarks/benchmark_utils.h, google/cloud/storage/benchmarks/create_dataset_options.cc, google/cloud/storage/benchmarks/throughput_options.cc
Part of the work for #6884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6924)
=> refactor(storage): benchmark command-line parsing

google/cloud/storage/testing/storage_integration_test.h, google/cloud/storage/tests/object_integration_test.cc
And removed a test function that was only used in the one test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6938)
=> cleanup(storage): simplify one of the integration tests

google/cloud/storage/tools/run_emulator_utils.sh
This is to help troubleshoot #6878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6936)
=> test(storage): better logging on emulator startup

google/cloud/internal/format_time_point_test.cc, google/cloud/internal/parse_rfc3339.cc, google/cloud/internal/parse_rfc3339.h, google/cloud/internal/parse_rfc3339_test.cc, google/cloud/storage/bucket_metadata_test.cc, google/cloud/storage/client_sign_policy_document_test.cc, google/cloud/storage/client_sign_url_test.cc, google/cloud/storage/internal/minimal_iam_credentials_rest.cc, google/cloud/storage/internal/policy_document_request_test.cc, google/cloud/storage/internal/signed_url_requests_test.cc, google/cloud/storage/object_metadata_test.cc, google/cloud/storage/policy_document_test.cc, google/cloud/storage/testing/remove_stale_buckets_test.cc
Fixes #6935
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6943)
=> fix(common): ParseRfc3339 returns StatusOr<>

google/cloud/storage/internal/curl_handle.cc, google/cloud/storage/internal/curl_handle.h, google/cloud/storage/internal/curl_handle_test.cc, google/cloud/storage/internal/curl_request.cc
Fixes #6934
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6944)
=> cleanup(storage): CurlHandle::SetOption assertions

google/cloud/bigtable/client_options_test.cc
Add missing unit tests for some of the `ClientOptions`. This will give us more confidence to transition the `ClientOptions` implementation to use `Options`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6945)
=> test(bigtable): increase ClientOptions test coverage

google/cloud/spanner/integration_tests/data_types_integration_test.cc, google/cloud/spanner/testing/database_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6950)
=> test(spanner): verify that NUMERIC can be used as a table key

google/cloud/iam/CMakeLists.txt, google/cloud/iam/doc/iam-credentials-mock.dox, google/cloud/iam/doc/iam-main.dox, google/cloud/iam/doc/iam-mock.dox
Rendered html pages look as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6964)
=> doc(iam): add doxygen landing pages

google/cloud/testing_util/command_line_parsing.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6974)
=> cleanup: delete extra line

ci/kokoro/macos/build.sh, ci/kokoro/macos/builds/cmake-vcpkg.sh
Part of the work for #6424 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6972)
=> ci: use vcpkg for macOS build

google/cloud/bigquery/doc/bigquery-main.dox, google/cloud/bigquery/doc/bigquery-read-mock.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6978)
=> doc(bigquery): add doxygen landing pages

google/cloud/storage/internal/object_write_streambuf.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6985)
=> cleanup(storage): prepare for import into google

google/cloud/storage/internal/object_read_streambuf.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6986)
=> fix(storage): build with MSVC+x86

google/cloud/storage/tests/small_reads_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6989)
=> fix(storage): build with MSVC+x86, take 2

doc/contributor/howto-guide-setup-development-workstation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6999)
=> doc: update Windows development instructions

google/cloud/storage/internal/object_write_streambuf.cc, google/cloud/storage/object_write_stream.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7004)
=> cleanup: prepare for import into Google

google/cloud/bigtable/benchmarks/random_mutation.cc, google/cloud/bigtable/benchmarks/setup.cc, google/cloud/bigtable/client_options.cc, google/cloud/internal/build_info.cc.in, google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/internal/generate_message_boundary_test.cc, google/cloud/storage/oauth2/google_application_default_credentials_file.cc, google/cloud/storage/well_known_parameters.cc, google/cloud/version.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6995)
=> cleanup: remove non-trivially destructible static variables

google/cloud/iam/quickstart/Makefile, google/cloud/iam/quickstart/README.md, google/cloud/iam/quickstart/WORKSPACE
Fixes #7009
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7010)
=> docs(iam): update all pubsub -> iam

google/cloud/bigquery/quickstart/Makefile, google/cloud/iam/quickstart/CMakeLists.txt, google/cloud/iam/quickstart/Makefile, google/cloud/pubsub/quickstart/CMakeLists.txt, google/cloud/pubsub/quickstart/Makefile, google/cloud/spanner/ci/run_integration_tests_emulator_bazel.sh, google/cloud/storage/quickstart/Makefile, google/cloud/storage/quickstart/grpc/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7011)
=> cleanup: make sure everything has the correct library name

ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-xenial.Dockerfile, ci/etc/oldest-deps/vcpkg.json, ci/generate-markdown/generate-packaging.sh, doc/packaging.md, external/googleapis/CMakeLists.txt, generator/integration_tests/generator_integration_test.cc
This change requires updating the minimum version of Protobuf, so I also
updated the documentation and our build images.
Part of the work for #6982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7015)
=> feat(storage): add storage v2 protos

google/cloud/storage/hashing_options.h
Fixes #7027
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7033)
=> doc(storage): fix hashing options documentation

google/cloud/iam/samples/CMakeLists.txt, google/cloud/iam/samples/iam_client_samples.bzl, google/cloud/iam/samples/iam_credentials_samples.cc, google/cloud/iam/samples/iam_samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7022)
=> doc(iam): add IAM credentials samples

google/cloud/iam/samples/iam_credentials_samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7035)
=> doc(iam): correct region tag underscores

CHANGELOG.md, google/cloud/storage/doc/storage-mocking.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7042)
=> doc(storage): warn customers about changes for mocks

bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-xenial.Dockerfile, doc/packaging.md
This reverts commit 25c957c80be2965a9217ad5457cc9fe91e8b2cb9.
This reverts commit ab4225d7568962b6f0907a4aecc57ac28c3db273.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7049)
=> chore(deps): revert updates to gRPC 1.39.0

google/cloud/storage/testing/storage_integration_test.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7063)
=> test(storage): make ScheduleForDelete() thread-safe

bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-xenial.Dockerfile, doc/packaging.md
This reverts commit ba41d5a99818922b09eee5da148786c1d68c17f5.
This PR effectively upgrades gRPC to 1.39.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7062)
=> Revert "chore(deps): revert updates to gRPC 1.39.0 (#7049)"

BUILD, README.md, ci/generate-markdown/generate-readme.sh, ci/verify_current_targets/BUILD, ci/verify_current_targets/CMakeLists.txt, google/cloud/examples/BUILD, google/cloud/examples/CMakeLists.txt, google/cloud/iam/CMakeLists.txt, google/cloud/iam/doc/iam-main.dox, google/cloud/iam/integration_tests/BUILD, google/cloud/iam/integration_tests/CMakeLists.txt, google/cloud/iam/samples/BUILD, google/cloud/iam/samples/CMakeLists.txt
#7072 filed to remove experimental-iam references after the next release has been cut.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7069)
=> doc(iam): promote library from preview to GA

.bazelignore, BUILD, CHANGELOG.md, ci/etc/quickstart-config.sh, google/cloud/bigquery/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7083)
=> doc(iam): polish GA release

google/cloud/storage/internal/curl_request_builder.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7089)
=> cleanup(storage): add a missing include

generator/integration_tests/CMakeLists.txt, generator/integration_tests/golden/tests/golden_kitchen_sink_client_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_stub_test.cc
fixes #5854
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7092)
=> chore(generator): enable clang-tidy for integration tests

google/cloud/testing_util/scoped_log.cc
1. Split the `LogRecord::message` outside the lock.
2. Move the split lines into `log_lines_` instead of copying.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7093)
=> testing(common): two small ScopedLog::Backend::Process() optimizations

google/cloud/bigtable/benchmarks/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7094)
=> testing(bigtable): correct test source-file name

google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7096)
=> test(storage): missing separators in benchmark output

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7100)
=> chore(release): update changelog for 2021-08 release

release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7105)
=> chore(release): update release instructions

ci/kokoro/windows/common.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7110)
=> ci: remove unneeded gfile resource

ci/kokoro/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7111)
=> chore(docs): remove reference to GCR for kokoro

google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.h, google/cloud/storage/benchmarks/aggregate_throughput_options_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7112)
=> feat(GCS+gRPC): timeout downloads in benchmark

ci/generate-markdown/generate-spanner-readme.sh, ci/generate-markdown/generate-storage-readme.sh, google/cloud/spanner/README.md, google/cloud/storage/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7117)
=> cleanup: fix too many backticks for clode block

release/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7121)
=> chore: simplify release.sh version increment

ci/cloudbuild/builds/lib/vcpkg.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7120)
=> chore: update vcpkg commit hash for version containing v1.30.0

google/cloud/storage/internal/retry_object_read_source.cc
No need to log each "read" from the HTTP or gRPC download. I left some
logging for the error case because those seem interesting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7123)
=> cleanup(storage): reduce logging in normal case

google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc
I missed logging some options during startup. Also flush the log when a
download fails, that makes troubleshooting easier with the `lastN`
logger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7122)
=> test(storage): better logging in benchmark

google/cloud/spanner/internal/connection_impl_test.cc
This simplifies/generalizes coverage for request_priority,
and opens a pathway for adding new options to the mix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7125)
=> test(spanner): generalize ConnectionImplTest.QueryOptions

generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/internal/client_generator.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator.h, generator/internal/service_code_generator_test.cc, google/cloud/iam/iam_credentials_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7115)
=> feature(generator): support adding include directives for certain well known protobuf types

generator/internal/codegen_utils.cc, generator/internal/descriptor_utils.cc, generator/internal/service_code_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7131)
=> chore(generator): use single quotes in StrSplit calls

google/cloud/storage/oauth2/authorized_user_credentials.h, google/cloud/storage/oauth2/authorized_user_credentials_test.cc, google/cloud/storage/oauth2/service_account_credentials.h, google/cloud/storage/oauth2/service_account_credentials_test.cc
We were caching the `internal::CurlRequest` object to save some
computation and connection setup time, but these requests are made about
once an hour: the peer often resets the connection before we get to
reuse it. Also it creates the impression that we are leaking sockets. It
is cleaner (I think) to release these as soon as possible.
Fixes #7126
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7136)
=> fix(storage): release handles for oauth2 refresh

google/cloud/status_or.h
This avoids most of the complicated parts of the implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7132)
=> refactor(statusor): use absl::optional rather than union

google/cloud/storage/doc/storage-mocking.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7130)
=> doc(doxygen): fix typo in storage-mocking.dox: ueeful -> useful

google/cloud/spanner/internal/connection_impl_test.cc
Extend `ConnectionImplTest.QueryOptions` to cover all `Client::*` calls
that are affected by `spanner::QueryOptions` and the matching elements of
`spanner::ReadOptions` and `spanner::CommitOptions`, plus the stand-alone
`spanner::RequestPriorityOption`.
Also generalize the protobuf builder so that it will be easier to add
new option fields in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7141)
=> test(spanner): extend and generalize ConnectionImplTest.QueryOptions

README.md, ci/generate-markdown/generate-bigquery-readme.sh, ci/generate-markdown/generate-bigtable-readme.sh, ci/generate-markdown/generate-iam-readme.sh, ci/generate-markdown/generate-pubsub-readme.sh, ci/generate-markdown/generate-readme.sh, ci/generate-markdown/generate-spanner-readme.sh, ci/generate-markdown/generate-storage-readme.sh, google/cloud/README.md, google/cloud/bigquery/README.md, google/cloud/bigtable/README.md, google/cloud/iam/README.md, google/cloud/pubsub/README.md, google/cloud/spanner/README.md, google/cloud/storage/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7149)
=> doc: correct minimum MSVC version

google/cloud/bigquery/CMakeLists.txt, google/cloud/bigquery/config.cmake.in, google/cloud/iam/CMakeLists.txt, google/cloud/iam/config.cmake.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7151)
=> fix: experimental bigquery iam cmake target installation

ci/kokoro/windows/build-quickstart-bazel.ps1
Fixes #7145. Note that I fixed IAM as part of another PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7157)
=> ci: compile and run BigQuery quickstart on Windows

google/cloud/bigtable/quickstart/Makefile, google/cloud/pubsub/quickstart/Makefile, google/cloud/spanner/quickstart/Makefile, google/cloud/storage/quickstart/Makefile
Use the newer `google_cloud_cpp_*` package names.
Thanks to @dbolduc for letting me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7159)
=> doc: update quickstart Makefiles

google/cloud/pubsub/internal/batching_publisher_connection_test.cc
Fixes #7021
Basically the same as #7008, the problem was that super rarely the two messages would be sent in two batches instead of one, due to the hold timer. And we only get the future for one batch.
This change ensures that both messages are sent in a single batch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7162)
=> test(pubsub): deflake default batching publisher test

README.md, ci/generate-markdown/generate-readme.sh, ci/kokoro/macos/builds/cmake-vcpkg.sh, doc/contributor/howto-guide-setup-development-workstation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7164)
=> cleanup: remove references to super builds from ci, docs

google/cloud/spanner/samples/samples.cc
Update the `spanner_set_transaction_tag` sample to match the
most recent revision of the client-library specification, but
also fix a couple of problems the spec still has.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7165)
=> test(spanner): update spanner_set_transaction_tag sample

CMakeLists.txt, ci/cloudbuild/builds/publish-docs.sh, cmake/GoogleCloudCppCommon.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7169)
=> doc: require an explicit flag to enable Doxygen

google/cloud/bigtable/async_row_reader.h, google/cloud/bigtable/cell.h, google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/internal/async_poll_op.h, google/cloud/bigtable/internal/async_retry_multi_page.h, google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll.h, google/cloud/bigtable/table.h, google/cloud/bigtable/table_admin.h, google/cloud/connection_options.h, google/cloud/future_generic.h, google/cloud/internal/async_read_stream_impl.h, google/cloud/internal/async_retry_unary_rpc.h, google/cloud/internal/future_impl.h, google/cloud/storage/internal/bucket_acl_requests.h, google/cloud/storage/internal/common_metadata.h, google/cloud/storage/internal/default_object_acl_requests.h, google/cloud/storage/internal/generic_object_request.h, google/cloud/storage/internal/object_acl_requests.h, google/cloud/storage/oauth2/service_account_credentials.h
Fixes: #4112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7173)
=> cleanup: remove unneeded NOLINT since clang-tidy upgrade

CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7178)
=> typo: hositng -> hosting

ci/cloudbuild/builds/lib/vcpkg.sh, ci/kokoro/macos/builds/cmake-vcpkg.sh, ci/kokoro/windows/build-cmake-dependencies.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7174)
=> chore: update vcpkg hash to version that includes v1.30.1

BUILD, README.md, ci/generate-markdown/generate-readme.sh, ci/kokoro/macos/builds/quickstart-cmake.sh, ci/verify_current_targets/CMakeLists.txt, google/cloud/bigquery/CMakeLists.txt, google/cloud/bigquery/config.cmake.in, google/cloud/bigquery/quickstart/BUILD, google/cloud/bigquery/quickstart/CMakeLists.txt, google/cloud/iam/CMakeLists.txt, google/cloud/iam/config.cmake.in, google/cloud/iam/quickstart/BUILD, google/cloud/iam/quickstart/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7109)
=> chore: remove experimental bigquery and iam targets

doc/contributor/howto-guide-forks-and-pull-requests.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7189)
=> doc: fix nits in developer guide

google/cloud/storage/benchmarks/CMakeLists.txt, google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_options.h, google/cloud/storage/benchmarks/aggregate_upload_throughput_options_test.cc, google/cloud/storage/benchmarks/benchmark_utils.h, google/cloud/storage/benchmarks/storage_benchmark_programs.bzl, google/cloud/storage/benchmarks/storage_benchmarks.bzl, google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
This is a new benchmark to measure the aggregate throughput of multiple
threads performing parallel uploads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7190)
=> feat(storage): aggregate upload benchmark

bazel/google_cloud_cpp_deps.bzl, external/googleapis/CMakeLists.txt, google/cloud/bigquery/bigquery_read_client.h, google/cloud/iam/iam_client.h, google/cloud/iam/iam_credentials_client.h, google/cloud/logging/logging_service_v2_client.h, google/cloud/spanner/admin/database_admin_client.h, google/cloud/spanner/admin/instance_admin_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7193)
=> chore: update googleapis protos to circa 2021-08-19

google/cloud/internal/time_utils.h, google/cloud/pubsub/subscription_builder.h, google/cloud/pubsub/topic_builder.h, google/cloud/pubsub/topic_builder_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7196)
=> feat(pusub): support Topic retention duration

google/cloud/storage/client.cc, google/cloud/storage/lifecycle_rule.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7201)
=> cleanup: checkers

google/cloud/bigtable/client_options_test.cc
This is mostly a cleanup to improve readability but there are 2 functional changes.
Our `ClientOptions()` constructor [defaults values](https://github.com/googleapis/google-cloud-cpp/blob/f023e8063e891b5e0670396e120c877dc0fbc3ba/google/cloud/bigtable/client_options.cc#L58-L77) for certain gRPC channel arguments. Well, gRPC uses the first value set. So any subsequent use of [these methods](https://github.com/googleapis/google-cloud-cpp/blob/f023e8063e891b5e0670396e120c877dc0fbc3ba/google/cloud/bigtable/client_options.h#L285-L299) have no effect.... and it's always been that way..... nice....
So,
1. Remove the tests related to max send/receive message size. (The tests only passed because the [test values](https://github.com/googleapis/google-cloud-cpp/blob/7b4f932b0a0a73bb0df64337da480c78968 …
=> test(bigtable): cleanup bigtable ClientOptions unit test

google/cloud/bigtable/examples/data_filter_snippets.cc
Fixes: #6868
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7213)
=> cleanup(bigtable): make filter samples consistent with Python samples

doc/contributor/howto-guide-setup-development-workstation.md
Fixes: #7179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7210)
=> docs: add instructions on generating compile_commands.json

google/cloud/spanner/results.h, google/cloud/stream_range.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7236)
=> doc: fix some comments that were wrong

ci/cloudbuild/builds/lib/vcpkg.sh, ci/etc/vcpkg-config.ps1, ci/etc/vcpkg-config.sh, ci/kokoro/macos/builds/cmake-vcpkg.sh, ci/kokoro/macos/builds/quickstart-cmake.sh, ci/kokoro/windows/build-cmake-dependencies.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7240)
=> chore(ci): put vcpkg release version in own config file

google/cloud/storage/internal/curl_request.cc, google/cloud/storage/internal/curl_request.h, google/cloud/storage/tests/curl_download_request_integration_test.cc, google/cloud/storage/tests/curl_request_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7244)
=> fix: release CurlRequest handles on error

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7245)
=> chore(release): update changelog for 2021-09 release

release/changes.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7248)
=> chore: teach cleanup.sh to skip refactor PRs

google/cloud/bigtable/README.md, google/cloud/bigtable/quickstart/quickstart.cc
Fixes #7231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7251)
=> cleanup(bigtable): update quickstart to use preferred method

google/cloud/bigtable/README.md, google/cloud/bigtable/quickstart/quickstart.cc
Reverts googleapis/google-cloud-cpp#7251
I need to wait for vcpkg to update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7253)
=> Revert "cleanup(bigtable): update quickstart to use preferred method"

google/cloud/storage/tests/object_basic_crud_integration_test.cc, google/cloud/storage/tests/object_hash_integration_test.cc, google/cloud/storage/tests/object_insert_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7259)
=> cleanup(GCS+gRPC): use a separate bug to track disabled tests

ci/etc/vcpkg-config.ps1, ci/etc/vcpkg-config.sh, google/cloud/bigtable/README.md, google/cloud/bigtable/quickstart/quickstart.cc
Fixes #7231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7275)
=> chore(bigtable): update quickstart to use preferred method

google/cloud/storage/BUILD, google/cloud/storage/CMakeLists.txt, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_failures_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session_url.cc, google/cloud/storage/internal/grpc_resumable_upload_session_url.h, google/cloud/storage/internal/grpc_resumable_upload_session_url_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7290)
=> cleanup(GCS+gRPC): simplify support for resumable uploads

google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/tests/curl_request_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7291)
=> feat(storage): support base URLs with existing query parameters

google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc
Convert the g/c/spanner/admin integration tests to start using the
generated admin APIs.  This makes things only a little more verbose
as the handwrought APIs weren't that thick in the first place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7302)
=> test(spanner): integration tests for generated Spanner admin APIs

google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/grpc_object_read_source.h
Fixes #4325
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7303)
=> feat(GCS+gRPC): reduce data copying in downloads

google/cloud/pubsub/publisher_connection_test.cc
Fixes #7006 
The test would flake when we hit the loop to satisfy the `AsyncSequencer` promises before `publish_count` was asynchronously incremented by the mock publisher.
This change adds a lock to ensure that we do not enter the loop until all messages have been received (and thus `publish_count` is correct, and thus all promises are satisfied).
I am open to better ways of doing this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7312)
=> test(pubsub): deflake flow control

google/cloud/grpc_options.cc, google/cloud/grpc_options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7331)
=> cleanup: cosmetic cleanup

google/cloud/pubsub/internal/schema_stub.cc, google/cloud/pubsub/internal/schema_stub.h, google/cloud/pubsub/schema_admin_connection.cc, google/cloud/pubsub/schema_admin_connection.h, google/cloud/pubsub/schema_admin_connection_test.cc, google/cloud/pubsub/topic_admin_connection.cc
Part of the work for #6306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7338)
=> feat(pubsub): configure SchemaAdminConnection with Options

google/cloud/bigtable/internal/async_row_sampler.cc, google/cloud/pubsub/internal/defaults.cc, google/cloud/pubsub/schema_admin_client.cc, google/cloud/pubsub/schema_admin_client.h, google/cloud/pubsub/schema_admin_client_test.cc, google/cloud/pubsub/subscription_builder_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7343)
=> cleanup: fix includes

google/cloud/pubsub/publisher.h, google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscriber.h
Fixes #7347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7355)
=> cleanup(pubsub): use new `GrpcCompletionQueueOption`

google/cloud/storage/quickstart/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7358)
=> doc: add gRPC steps to storage quickstart

google/cloud/storage/internal/bucket_requests.cc
Another function that was getting too large for comfort.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7362)
=> refactor(storage): split computed bucket patch

ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/generate-markdown/generate-packaging.sh, doc/packaging.md
Fixes #7363
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7364)
=> fix: update Debian 11 (Bullseye) packaging instructions

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/integration_tests/backup_extra_integration_test.cc
Back to the present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7371)
=> cleanup(spanner): Fix copyright years

google/cloud/storage/tests/curl_request_integration_test.cc, google/cloud/storage/tests/key_file_integration_test.cc, google/cloud/storage/tests/signed_url_integration_test.cc
We used to be able to re-use a `CurlRequest`, but libcurl is getting
more and more strict about API calls, and this test fails completely if
we need to retry a request. Fortunately the code paths in production do
*not* reuse requests, but some of the tests did.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7374)
=> test(storage): do not use `CurlRequest` in tests

ci/cloudbuild/build.sh
This would be useful in my workstation. I believe it would change nothing for other folks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7385)
=> ci: support alternative docker networks

release/README.md, release/changes.sh
- Let's order "spanner" before "storage"
- `s/google-cloud-biquery/google-cloud-bigquery/`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7391)
=> cleanup: tweak some items in the release process

google/cloud/bigtable/tools/generate_rpc_policy_parameters.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7393)
=> cleanup: remove unused import

google/cloud/storage/examples/storage_bucket_samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7400)
=> cleanup(storage): fix example bucket leaks

bazel/crc32c.BUILD, bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-xenial.Dockerfile, doc/packaging.md
Fixes #6800
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7414)
=> chore(deps): update google/crc32c to 1.1.2

generator/internal/descriptor_utils_test.cc, generator/internal/printer_test.cc, generator/internal/service_code_generator_test.cc, generator/testing/printer_mocks.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7537)
=> cleanup(generator): use printer mocks

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7546)
=> doc: update CHANGELOG for v1.33.0 release

ci/cloudbuild/builds/gcs-grpc.sh
Part of the work for #7257
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7553)
=> test(storage): restore GCS+gRPC integration tests

.github/workflows/codeql-analysis.yml, README.md, ci/cloudbuild/builds/lib/vcpkg.sh, ci/generate-markdown/generate-readme.sh, ci/kokoro/macos/builds/cmake-vcpkg.sh, ci/kokoro/macos/builds/quickstart-cmake.sh, doc/contributor/howto-guide-setup-cmake-environment.md, doc/contributor/howto-guide-setup-development-workstation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7557)
=> ci: vcpkg now requires $VCPKG_ROOT

google/cloud/storage/tests/grpc_integration_test.cc
Part of the work for #7257 I missed these in my last PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7558)
=> test(GCS+gRPC): missed restoring some integration tests

.github/workflows/codeql-analysis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7560)
=> cleanup: codeql yaml

google/cloud/bigtable/tests/admin_integration_test.cc, google/cloud/bigtable/tests/data_integration_test.cc, google/cloud/bigtable/tests/instance_admin_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7568)
=> cleanup(bigtable): slightly better logging tests

google/cloud/CMakeLists.txt, google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/admin/integration_tests/CMakeLists.txt, google/cloud/bigtable/benchmarks/CMakeLists.txt, google/cloud/bigtable/examples/CMakeLists.txt, google/cloud/bigtable/tests/CMakeLists.txt, google/cloud/pubsub/samples/CMakeLists.txt, google/cloud/storage/CMakeLists.txt, google/cloud/storage/benchmarks/CMakeLists.txt, google/cloud/storage/examples/CMakeLists.txt, google/cloud/storage/tests/CMakeLists.txt, google/cloud/testing_util/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7573)
=> chore: pin copyright year in generated code

google/cloud/iam/integration_tests/iam_integration_test.cc
fixes #7129 
changes all get/query/test rpcs to kIdempotent to allow for retries on retryable error codes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7580)
=> chore: add more aggressive idempotency policy to reduce IAM test flakes

ci/cloudbuild/builds/gcs-grpc.sh, google/cloud/storage/tests/grpc_integration_test.cc
Using  #7257 to revert this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7581)
=> test(GCS+gRPC): disable production integration tests

google/cloud/iam/samples/iam_samples.cc
fixes #7330
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7582)
=> chore: increase retry time for GetSeviceAccountKey in sample

generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7590)
=> cleanup(generator): rename tests

bazel/google_cloud_cpp_deps.bzl, external/googleapis/CMakeLists.txt, google/cloud/bigquery/bigquery_read_client.h, google/cloud/bigtable/admin/bigtable_instance_admin_client.h, google/cloud/bigtable/admin/bigtable_table_admin_client.h, google/cloud/iam/iam_client.h, google/cloud/iam/iam_credentials_client.h, google/cloud/logging/logging_service_v2_client.h, google/cloud/spanner/admin/database_admin_client.h, google/cloud/spanner/admin/instance_admin_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7598)
=> chore(deps): update googleapis circa 2021-11-12

generator/BUILD, generator/CMakeLists.txt, generator/internal/auth_decorator_generator.cc, generator/internal/connection_generator.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, generator/internal/idempotency_policy_generator.cc, generator/internal/logging_decorator_generator.cc, generator/internal/metadata_decorator_generator.cc, generator/internal/mock_connection_generator.cc, generator/internal/option_defaults_generator.cc, generator/internal/options_generator.cc, generator/internal/predicate_utils.cc, generator/internal/stub_factory_generator.cc, generator/internal/stub_generator.cc
Also remove unused dependencies and headers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7608)
=> fix(generator): add missing dependency for library

google/cloud/pubsublite/admin_client.h
Ooops, the Pub/Sub Lite PR was based on an older version of the
generator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7609)
=> fix(pubsublite): regenerate the code with new links

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, google/cloud/bigtable/admin/bigtable_instance_admin_client.cc, google/cloud/bigtable/admin/bigtable_instance_admin_client.h, google/cloud/bigtable/admin/bigtable_instance_admin_connection.cc, google/cloud/bigtable/admin/bigtable_instance_admin_connection.h, google/cloud/bigtable/admin/bigtable_instance_admin_connection_idempotency_policy.cc, google/cloud/bigtable/admin/bigtable_instance_admin_connection_idempotency_policy.h, google/cloud/bigtable/admin/internal/bigtable_instance_admin_auth_decorator.cc, google/cloud/bigtable/admin/internal/bigtable_instance_admin_auth_decorator.h, google/cloud/bigtable/admin/internal/bigtable_instance_admin_logging_decorator.cc, google/cloud/bigtable/admin/internal/bigtable_instance_admin_logging_decorator.h, google/cloud/bigtable/admin/internal/bigtable_instance_admin_metadata_decorator.cc, google/cloud/bigtable/admin/internal/bigtable_instance_admin_metadata_decorator.h, google/cloud/bigtable/admin/internal/bigtable_instance_admin_stub.cc, google/cloud/bigtable/admin/internal/bigtable_instance_admin_stub.h, google/cloud/bigtable/admin/mocks/mock_bigtable_instance_admin_connection.h
I was mostly interested in the changes for Cloud Tasks. In addition, we
got some new features for Cloud Bigtable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7614)
=> chore(deps): update googleapis circa 2021-11-16

doc/adding_new_libraries.md
Use some shell variables to make most of the code snippets
cut&paste-able. Help folks identify gotchas with the Bazel rules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7612)
=> doc: improve instructions for new libraries

ci/cloudbuild/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7625)
=> ci: do not fall through from cloud mode to docker mode

doc/adding_new_libraries.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7630)
=> doc: another pass on the instructions for new libs

generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator_test.cc, google/cloud/pubsublite/README.md, google/cloud/tasks/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7638)
=> feat(generator): improve initial README files

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7653)
=> chore(deps): update googleapis/googleapis circa 2021-11-22

ci/cloudbuild/builds/publish-docs.sh
Fixes #7661
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7663)
=> ci: upload docs

doc/contributor/howto-guide-setup-development-workstation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7668)
=> doc: update instructions for macOS

google/cloud/async_operation.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7682)
=> doc(common): add a note about AsyncGrpcOperation and OptionsSpan

CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7687)
=> cleanup: only stop build based on our requirements

README.md, ci/generate-markdown/generate-packaging.sh, ci/generate-markdown/generate-readme.sh, doc/contributor/howto-guide-setup-cmake-environment.md, doc/contributor/howto-guide-setup-development-workstation.md, doc/contributor/working-with-bazel-and-cmake.md, doc/packaging.md, generator/internal/scaffold_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7697)
=> doc: prefer who vs. that for people

ci/cloudbuild/dockerfiles/debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34-cxx11.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, doc/packaging.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7699)
=> chore: Actually disable nlohmann/json test compilation which doesn't work on mac

google/cloud/storage/internal/http_response.cc, google/cloud/storage/internal/http_response_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7702)
=> fix(storage): more strict parsing for HttpResponse

release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7709)
=> doc: simplify release instructions

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7708)
=> chore: prepare CHANGELOG for v1.34.1 release

release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7711)
=> doc: fix typo in release/README.md

google/cloud/storage/bucket_metadata.cc, google/cloud/storage/bucket_metadata.h, google/cloud/storage/bucket_metadata_test.cc
Fixed #7365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7730)
=> cleanup(storage): remove pre-GA workarounds for PAP

ci/install-cloud-sdk.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7737)
=> chore: update cloud sdk

ci/kokoro/macos/builds/bazel.sh, ci/kokoro/macos/builds/quickstart-bazel.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7744)
=> chore: remove stale bazelisk cache

google/cloud/internal/background_threads_impl.cc
Trying to destroy an `AutomaticallyCreatedBackgroundThreads` from one
of its threads is a trap all too easy for us, or a customer, to fall into.
And the ramification (`std::~thread()` calling `std::terminate()`)
is difficult to debug.  So, catch the error, and fail quickly.
Part of #7740.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7747)
=> cleanup(common): fail early when trying to join the current thread

ci/cloudbuild/builds/cmake-install.sh, ci/etc/expected_install_directories
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7760)
=> cleanup(common): relocate expected install directory

bazel/curl.BUILD
Fixes #7462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7761)
=> feat(storage): enable c-ares for libcurl under Bazel

google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.h, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc, google/cloud/storage/lifecycle_rule.h
Fixes #4165
Fixes #4166
Fixes #4167
Fixes #4168
Fixes #4169 
Fixes #4171
Fixes #4172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7766)
=> feat(GCS+gRPC): implement parser for BucketMetadata components

cmake/CompileProtos.cmake, cmake/CreateBazelConfig.cmake, cmake/EnableCxxExceptions.cmake, cmake/EnableWerror.cmake, cmake/FindCurlWithTargets.cmake, cmake/FindGMockWithTargets.cmake, cmake/FindProtobufWithTargets.cmake, cmake/FindgRPC.cmake, cmake/GoogleCloudCppCommon.cmake, cmake/GoogleapisConfig.cmake, cmake/IncludeNlohmannJson.cmake, cmake/SelectMSVCRuntime.cmake
Incidentally this fixes the generation for `*.bzl` files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7776)
=> cleanup: more http vs. https fixes

.bazelci/presubmit.yml, bazel/BUILD.bazel, bazel/crc32c.BUILD, bazel/google_cloud_cpp_deps.bzl, bazel/googleapis.BUILD, bazel/nlohmann_json.BUILD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7778)
=> cleanup: http vs. https in Bazel support

external/googleapis/CMakeLists.txt, external/googleapis/config-version.cmake.in, external/googleapis/config.cmake.in, external/googleapis/config.pc.in, external/googleapis/legacy.cmake.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7779)
=> cleanup: http vs. https in external/googleapis/

.bazelrc, .cmake-format.py, BUILD, CMakeLists.txt, WORKSPACE.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7780)
=> cleanup: http vs. https at top-level

google/cloud/testing_util/async_sequencer.h, google/cloud/testing_util/async_sequencer_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7784)
=> test: count async sequencer cancels by name

google/cloud/internal/async_retry_loop_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7783)
=> test: modernize RetryLoop tests

generator/integration_tests/generator_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7791)
=> test(generator): golden files copyright year mismatch

release/release.sh
Parsing the `CHANGELOG.md` file to extract the release notes is now done
with awk, and it's more robust than before, because it stops on a line
that looks like `## vX.Y.Z` rather than just `## `. This also uses
`gh`'s explicit `--title` flag to set the title to only the release tag
name (e.g. "v1.35.0").
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7802)
=> refactor(internal): improve release.sh release notes

generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7804)
=> fix(generator): use real tabs in generated Makefile

doc/contributor/howto-adding-generated-libraries.md, doc/contributor/howto-guide-adding-generated-libraries.md
Also moved the document to the right directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7805)
=> doc: some gotchas on adding generated libraries

doc/contributor/howto-guide-adding-generated-libraries.md
Fill in some details on more manual steps. Also recommend doing multiple
commits, because it would be easier to review the changes if the commits
with generated stuff are separate from commits with manual stuff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7818)
=> doc: more details on the generated library howto

generator/internal/scaffold_generator.cc
Will make ease the work in #7807
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7828)
=> feat(generator): improve quickstart skeleton

google/cloud/grpc_utils/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7830)
=> cleanup: deprecated rules should be manual

doc/contributor/howto-guide-adding-generated-libraries.md
top level `BUILD` was renamed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7837)
=> cleanup(doc): fix filename

generator/generator_config.proto, generator/internal/codegen_utils_test.cc, generator/internal/descriptor_utils.cc, generator/standalone_main.cc
Fixes #5935
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7833)
=> feat(generator): add options to disable client class

generator/generator.h
Fixes #5899
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7838)
=> feat(generator): support optional fields

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, external/googleapis/protodeps/speech.deps, external/googleapis/protolists/speech.list, google/cloud/assuredworkloads/assured_workloads_client.h
This includes the latest (and close to final) version of the storage/v2
protos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7840)
=> chore(deps): update googleapis circa 2021-01-06

google/cloud/secretmanager/doc/main.dox, google/cloud/tasks/doc/main.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7843)
=> doc: more nits around GA libraries

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_rest_internal.bzl, google/cloud/google_cloud_cpp_rest_internal_unit_tests.bzl, google/cloud/internal/rest_request.cc, google/cloud/internal/rest_request.h, google/cloud/internal/rest_request_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832)
=> impl: add RestRequest class

generator/internal/scaffold_generator.cc, google/cloud/accessapproval/CMakeLists.txt, google/cloud/assuredworkloads/CMakeLists.txt, google/cloud/bigquery/CMakeLists.txt, google/cloud/bigtable/CMakeLists.txt, google/cloud/billing/CMakeLists.txt, google/cloud/iam/CMakeLists.txt, google/cloud/kms/CMakeLists.txt, google/cloud/logging/CMakeLists.txt, google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsublite/CMakeLists.txt, google/cloud/scheduler/CMakeLists.txt, google/cloud/spanner/CMakeLists.txt, google/cloud/websecurityscanner/CMakeLists.txt, google/cloud/workflows/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7844)
=> fix: add mock library aliases

doc/contributor/howto-guide-declare-a-library-ga.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7842)
=> doc: a HOW-TO guide to declare libraries GA

generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator_test.cc
Also made some small tweaks to simplify the hand-editing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7850)
=> feat(generator): more consistent links in scaffold

google/cloud/storage/bucket_metadata.h, google/cloud/storage/internal/common_metadata.h, google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.h, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc
Fixes #4173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7845)
=> feat(GCS+gRPC): ToProto/FromProto for BucketMetadata

generator/internal/scaffold_generator.cc, google/cloud/assuredworkloads/doc/main.dox, google/cloud/billing/doc/main.dox, google/cloud/kms/doc/main.dox, google/cloud/logging/doc/main.dox, google/cloud/pubsublite/doc/main.dox, google/cloud/scheduler/doc/main.dox, google/cloud/secretmanager/doc/main.dox, google/cloud/tasks/doc/main.dox, google/cloud/webrisk/doc/main.dox, google/cloud/websecurityscanner/doc/main.dox, google/cloud/workflows/doc/main.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7859)
=> feat(generator): remove unused links in generated main.dox

doc/contributor/howto-guide-declare-a-library-ga.md, google/cloud/secretmanager/README.md, google/cloud/tasks/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7862)
=> doc: one more thing when declaring GA

google/cloud/storage/examples/storage_bucket_samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7867)
=> sample(storage): update sample region tags for turbo replication

google/cloud/internal/rest_response_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7879)
=> impl: add tests for HttpStatusCode to Status mapping

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/async_read_write_stream_logging.h, google/cloud/internal/async_read_write_stream_logging_test.cc
Part of the work for #7795
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7878)
=> impl(common): helpers for bi-dir logging streams

google/cloud/storage/internal/object_write_streambuf_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7882)
=> test(storage): simplify ObjectWriteStreambuf unit test

google/cloud/storage/internal/retry_resumable_upload_session.cc
Also fix some nits in the comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7881)
=> cleanup(storage): improve debugging information

BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7890)
=> cleanup: sort targets

doc/contributor/howto-guide-adding-generated-libraries.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7895)
=> docs: update generate library instructions

doc/contributor/howto-guide-adding-generated-libraries.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7901)
=> doc: test generated libraries with Bazel

ci/cloudbuild/builds/checkers.sh, doc/contributor/howto-guide-adding-generated-libraries.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7902)
=> ci: reorder checker steps

generator/internal/scaffold_generator.cc, google/cloud/accesscontextmanager/README.md, google/cloud/webrisk/README.md
This was bugging me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7908)
=> cleanup: capitalization

external/googleapis/CMakeLists.txt
Part of the work for #7907
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7909)
=> feat(googleapis): library for google/rpc/code.proto

generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7913)
=> fix(generator): trim spaces from parameter name before lookup

generator/internal/scaffold_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7914)
=> feat(generator): tiniest improvement in scaffold

doc/contributor/howto-guide-adding-generated-libraries.md
Some changes based on today's experience.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7919)
=> doc: more tweaks on the generated libraries howto

external/googleapis/protolists/dialogflow.list, external/googleapis/protolists/logging.list, external/googleapis/protolists/websecurityscanner.list, external/googleapis/update_libraries.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7924)
=> chore: use update_libraries.sh to order the protolists

google/cloud/internal/streaming_read_rpc_logging_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7930)
=> cleanup: fix hard-coded type in a test

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/streaming_write_rpc_logging.h, google/cloud/internal/streaming_write_rpc_logging_test.cc
Part of the work for #7929 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7928)
=> impl(common): logging decorator for streaming write RPCs

google/cloud/internal/async_read_write_stream_logging_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7931)
=> cleanup(common): better testing for AsyncReadWriteStreamLogging

google/cloud/internal/curl_handle.h, google/cloud/internal/curl_handle_factory.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7932)
=> impl: add GetCurlHandle factory function

generator/integration_tests/golden/golden_kitchen_sink_connection.cc, generator/integration_tests/golden/golden_kitchen_sink_connection.h, generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_connection.h, generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc, generator/internal/connection_generator.cc, generator/internal/mock_connection_generator.cc, google/cloud/logging/logging_service_v2_connection.cc, google/cloud/logging/logging_service_v2_connection.h, google/cloud/logging/mocks/mock_logging_service_v2_connection.h
Part of the work for #7795
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7933)
=> feat(generator): support bidir streams in Connection

google/cloud/internal/curl_handle.cc, google/cloud/internal/curl_handle.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7953)
=> refactor: relocate response code error handling into CurlHandle

ci/cloudbuild/builds/cmake-install.sh, ci/etc/expected_install_directories
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7962)
=> ci: move expected dir to cmake install

google/cloud/bigquery/samples/BUILD.bazel, google/cloud/iam/samples/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7984)
=> cleanup: do not use deprecated rules

google/cloud/storage/internal/storage_stub_factory.cc, google/cloud/storage/internal/storage_stub_factory.h, google/cloud/storage/internal/storage_stub_factory_test.cc
Part of #7963
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7978)
=> cleanup(GCS+gRPC): better testing for StorageStub factory

generator/generator_config.textproto
Fixes #7997
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7998)
=> cleanup(notebooks): avoid generating stub twice

doc/contributor/howto-guide-adding-generated-libraries.md, external/googleapis/update_libraries.sh
Prefer using the `*_cc_grpc` rules in `update_libraries.sh` as they
require less manual editing. Reduce the number of files we need to
commit. Change the recommended builds to make the smallest possible
Bazel test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8006)
=> doc: more tweaks to library generation

external/googleapis/CMakeLists.txt
Part of: #7892
This is needed by the upcoming library for Google Cloud Build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8007)
=> impl: add httpbody.proto to CMake build

google/cloud/storage/CMakeLists.txt, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/internal/grpc_common_request_params.h, google/cloud/storage/internal/grpc_object_request_parser.cc
Part of the work for #4212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8024)
=> refactor(GCS+gRPC): helper to convert requests

external/googleapis/CMakeLists.txt
This will make a followup change easier to grok, and will keep things tidy in the future.
Part of the work for #8034
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8036)
=> refactor(googleapis): sort things in CMakeLists.txt

external/googleapis/CMakeLists.txt
Also simplify the steps to add simple proto libraries to the list.
Part of the work for #8034
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8039)
=> feat: more proto libraries in google/api
