googleapis/google-cloud-cpp

google/cloud/internal/resumable_streaming_read_rpc.h, google/cloud/internal/resumable_streaming_read_rpc_test.cc
Permanent errors in streaming RPCs can be resumed **only if** the stream
had at least some data received. Otherwise we resume each stream at
least twice, for no benefit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5801)
=> fix(common): streaming RPC permanent error handling

ci/kokoro/docker/build-in-docker-quickstart-cmake.sh, ci/kokoro/macos/build-quickstart-cmake.sh, ci/kokoro/windows/build-cmake-dependencies.ps1
In https://github.com/googleapis/google-cloud-cpp/pull/5791 we upgraded
grpc and Abseil, and then in
https://github.com/googleapis/google-cloud-cpp/pull/5799 we changed some
code to rely on new Abseil behavior. This broke tests on Windows because
they were pinned to an older version of vcpkg and therefore and older
version of Abseil.
This PR bumps our vcpkg snapshot to its current head. This should pull
in a newer version of Abseil and grpc that should make our test pass.
However, the newer versions are still not quite as new as we use in our
other builds, because vcpkg does not have the absolute newest releases
of grpc and Abseil. This should be fine.
--- …
=> ci: update vcpkg version

ci/generate-markdown/generate-packaging.sh, ci/kokoro/docker/build-in-docker-quickstart-cmake.sh, ci/kokoro/macos/build-quickstart-cmake.sh, ci/kokoro/windows/build-cmake-dependencies.ps1, doc/packaging.md, google/cloud/bigtable/quickstart/CMakeLists.txt, google/cloud/pubsub/quickstart/CMakeLists.txt, google/cloud/spanner/quickstart/CMakeLists.txt, google/cloud/storage/quickstart/CMakeLists.txt
Now that the targets are in a release, and the release is published in
vcpkg, we can use the new targets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5804)
=> cleanup: quickstarts use google-cloud-cpp:: targets

google/cloud/storage/internal/grpc_client.cc
This only affects the GCS+gRPC plugin, it enables a better load
balancer when using Direct Path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5807)
=> feat(storage): use correct load balancer for direct path

google/cloud/testing_util/BUILD
Use the standard Bazel configs in `@bazel_tools//src/conditions/...` to
determine what is the target OS and CPU, and use that to determine if
`getrusage()` exists and it supports `RUSAGE_THREAD`. This seems
"better" than our custom config settings, at least they compile the code
with the right flags on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5808)
=> test: detect OS using standard Bazel configs

ci/kokoro/docker/Dockerfile.ubuntu, ci/kokoro/docker/build-in-docker-quickstart-cmake.sh, ci/kokoro/docker/upload-cache.sh, ci/kokoro/macos/build-quickstart-cmake.sh
We're already caching the `$HOME/.cache` directory, which is where
vcpkg caches its data, so we don't need to cache/restore it again.
Related to https://github.com/googleapis/google-cloud-cpp/issues/5356
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5812)
=> ci: remove redundant vcpkg-quickstart-cache

ci/kokoro/docker/build.sh
Run the "slow" Spanner integration tests in "integration-nightly" to
increase coverage without impacting normal pre/post-merge testing.
Before:
//google/cloud/spanner/integration_tests:backup_integration_test    0.4s
//google/cloud/spanner/samples:samples                            137.8s
After:
//google/cloud/spanner/integration_tests:backup_integration_test  676.2s
//google/cloud/spanner/samples:samples                            766.8s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5815)
=> test(spanner): run slow integration tests in nightly build

ci/kokoro/docker/upload-cache.sh, ci/kokoro/macos/upload-cache.sh
Rather than caching all of ~/.cache, we only cache certain subdirs under
there. This will effectively STOP caching ~/.cache/bazel. But from the
rationale in https://github.com/googleapis/google-cloud-cpp/issues/5819,
that may be a good thing.
NOTE: This PR may make the bazel builds SLOWER, so we may end up reverting this PR. That's fine.
We won't know if this makes things slower until after this commit makes it through a full CI build where we upload 
new cache files that no longer contain the ~/.cache/bazel dir. Then the following builds will NOT be using it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5822)
=> ci: only cache certain .cache/ dirs

ci/kokoro/macos/build-quickstart-bazel.sh, ci/kokoro/macos/build-quickstart-cmake.sh, ci/kokoro/macos/build.sh, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-cmake.ps1, ci/kokoro/windows/build-quickstart-bazel.ps1, ci/kokoro/windows/build-quickstart-cmake.ps1
Windows and macOS builds need to download the `roots.pem` file from the
gRPC GitHub repository. This rarely fails, but when it does, we should
retry a couple of times.
Fixes #5699
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5826)
=> ci: deflake downloads for roots.pem

google/cloud/storage/internal/object_streambuf.cc
Remove TODO() for myself, and it was simple to actually take the action
suggested in the TODO.
Part of the fixes for #5109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5829)
=> cleanup(storage): error streams cannot validate data

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_experiment.h, google/cloud/storage/benchmarks/throughput_experiment_test.cc, google/cloud/storage/grpc_plugin.cc, google/cloud/storage/grpc_plugin.h, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/internal/hybrid_client.h
This is useful in benchmarks (to isolate gRPC demuxing effects), and may
be useful for applications that want to keep traffic separated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5838)
=> feat(storage): gRPC clients can have their own channel

ci/kokoro/docker/build.sh
Otherwise I get a "permission denied" error. See [docker documentation](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5841)
=> ci: add Z switch so mounts work on selinux systems

ci/kokoro/windows/build-cmake-dependencies.ps1, ci/kokoro/windows/build.ps1
Use a tarball (instead of `git clone`) to get the vcpkg ports data.
Download the vcpkg binary from GitHub to speed up the build. Use the
vcpkg binary cache instead of uploading the full `installed` directory,
take advantage of `gsutil rsync` for uploading and downloading the vcpkg
binary cache.
Fixes #5818
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5847)
=> ci: improve vcpkg download and usage

CMakeLists.txt, cmake/SelectMSVCRuntime.cmake
My previous cleanup was incorrect. CMake protects usage of
CMAKE_MSVC_RUNTIME_LIBRARY with a policy, the variable (or rather the
MSVC_RUNTIME_LIBRARY property set by this variable) has no effect if the
CMP0091 policy is set to OLD, as would be in our builds because we say
that version 3.5 is the behavior we want in cmake_minimum_required().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5856)
=> fix: support for static builds with MSVC

google/cloud/BUILD, google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_common.bzl, google/cloud/google_cloud_cpp_common_unit_tests.bzl, google/cloud/options.h, google/cloud/options_test.cc
Note: Let's feel free to discuss alternative naming for the interface methods on this class. Currently they are
* `.set<T>(...)`
* `.unset<T>()`
* `.get<T>()`
* `.get_or<T>(...)`
I'm open to better names, but they should likely all go together naturally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5843)
=> feat: introduce a dynamic Options class that all services can use

google/cloud/tracing_options.cc, google/cloud/tracing_options.h, google/cloud/tracing_options_test.cc
This makes the class a little easier to use as a regular value type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5858)
=> feat: added equality to TracingOptions

google/cloud/options.h, google/cloud/options_test.cc
This gives us the ability to mutate options directly within `Options`
class. This also gives us the ability to get options that will not move
so that we can return references to them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5860)
=> feat: add support for get_pointer

google/cloud/options.h, google/cloud/options_test.cc
Reverts googleapis/google-cloud-cpp#5860
Per the reasons in https://github.com/googleapis/google-cloud-cpp/pull/5860#issuecomment-780593237
We can add these functions (or similar ones) later if/when they are actually needed again. At the moment, I no longer need these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5863)
=> Revert "feat: add support for get_pointer"

google/cloud/spanner/database_admin_client.cc, google/cloud/spanner/database_admin_client_test.cc, google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/internal/transaction_impl_test.cc, google/cloud/spanner/results.cc, google/cloud/spanner/results_test.cc, google/cloud/spanner/timestamp.cc, google/cloud/spanner/timestamp.h, google/cloud/spanner/timestamp_test.cc, google/cloud/spanner/transaction.cc
`spanner::Timestamp` and `protobuf::Timestamp` are fundamental parts
of the Spanner admin API (and even more so with the introduction of
PITR), but there was no mechanism provided to the user for converting
between them.
So, `internal::TimestampFromProto()` and `internal::TimestampToProto()`
are here refactored as `spanner::MakeTimestamp(protobuf::Timestamp)`
and `spanner::Timestamp::get<protobuf::Timestamp>()` respectively.
This means Spanner no longer depends on the "internal/time_utils.h"
grab bag.
This also reverses a decision made in #5844 concerning the impossibility
of failure in `protobuf::Timestamp` to `spanner::Timestamp` conversions.
While failure is impossible for `protobuf::Timestamp` values that abide
by the "MUST" comments, in general we must be prepared to handle values …
=> refactor(spanner): spanner::Timestamp/protobuf::Timestamp conversions

google/cloud/bigtable/quickstart/README.md, google/cloud/bigtable/quickstart/WORKSPACE, google/cloud/pubsub/quickstart/README.md, google/cloud/pubsub/quickstart/WORKSPACE, google/cloud/spanner/quickstart/README.md, google/cloud/spanner/quickstart/WORKSPACE, google/cloud/storage/quickstart/README.md, google/cloud/storage/quickstart/WORKSPACE
Bazel on Windows can generate excessively long pathnames. Document how
to use the `--output_user_root=` option to shorten the paths, and try to
minimize the problem (again?) by shortening the workspace names.
Thanks to @rastogi-ayush for the suggestion in #5865
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5869)
=> doc: workarounds for Bazel and path length problems

ci/kokoro/docker/build-in-docker-quickstart-cmake.sh, ci/kokoro/macos/build-quickstart-cmake.sh, ci/retry-command.sh
We have seen download errors here, so make a single retry after a
short pause. (See microsoft/vcpkg#11073 for a request to have
vcpkg do this itself.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5873)
=> ci: retry "vcpkg install google-cloud-cpp" once

ci/install-bazel.sh, ci/install-cloud-sdk.sh
Curl seems to be more commonly available on default installs of
operating systems, including macOS, so it's nice to prefer curl rather
than wget so we can avoid the user having to install wget when we could
have used curl.
Note: most of our CI scripts were already depending on curl, so this
shouldn't introduce a new dep, rather I think it should remove a dep.
Also, I'm not using the "--silent" option because I think the download progress info may be useful. But if others disagree and think this should be silent, I can change to that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5882)
=> ci: prefer curl which is avail by default more often

ci/lib/init.sh
macOS doesn't have this command by default. Users have to `brew install
coreutils` to get it, so it's nice to avoid the dep when possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5883)
=> ci: avoid dep on realpath(1)

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/timestamp.cc
The `protobuf::util::TimeUtil` names introduced in #5876 need
to be qualified with `google` to satisfy the requirements of
some existing, downstream name mangling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5880)
=> chore(spanner): fully qualify google::protobuf::util names

ci/install-bazel.sh
Bazel doesn't (yet?) offer a darwin + arm64 package, but the x86_64
package works fine emulated.
Fixes https://github.com/googleapis/google-cloud-cpp/issues/5878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5884)
=> ci: use x86_64 bazel package on macOS M1

google/cloud/spanner/testing/pick_random_instance.cc, google/cloud/spanner/testing/pick_random_instance.h
Support filtering of `PickRandomInstance()` candidates (1) on the server
side, by exposing the `ListInstances` filter, and (2) on the client side,
via a predicate over `Instance` and `InstanceConfig`.
This will be needed to support the upcoming CMEK integration tests (at
least in their current configuration), where the selected instance must
be in the single location we use to store the encryption keys.
Also use server-side filtering to implement the restriction of instance
IDs to "test-instance-*".
Fixes #5588.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5885)
=> test(spanner): support filtering of `PickRandomInstance()` candidates

generator/integration_tests/golden/golden_kitchen_sink_client.gcpcxx.pb.h, generator/integration_tests/test.proto, generator/internal/client_generator.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils.h, generator/internal/descriptor_utils_test.cc
When protobuf::io::Printer is provided text with single delimiters $, the text needs to be massaged to change all $ to $$ in order to avoid the Printer thinking that a substitution variable is incorrectly specified. Printer will replace all instances of $$ with a single $ in its emitted output, preserving the original text.
Occurrences of $ in the value of a substitution variable does not require escaping as Printer does not recursively attempt to substitute into the body of a substitution variable, even if some $label$ exists. Printer just emits $label$.
While unit tests exists for all various places $ can occur, the integration test build will fail with some placements of $ because the grpc plugin does not escape them properly. There is already an existing issue for this with grpc.
Also …
=> fix(generator): properly escape delimiter character

ci/check-style.sh, ci/kokoro/docker/build-in-docker-cmake.sh, ci/kokoro/docker/build.sh
I made a number of changes to quiet up the builds, including:
- stop cspell from listing all the files in the repository
- stop `cmake --install` from listing all the installed files
- do not dump the clang-tidy configuration
- avoid logging actions that will not happen
I tried enabling `ctest --quiet`, but it does not print failures in that
case, we need something more involved, like logging to a file and
printing the file if there is an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5891)
=> cleanup: make CMake builds less verbose

google/cloud/CMakeLists.txt, google/cloud/bigtable/app_profile_config.cc, google/cloud/bigtable/examples/bigtable_hello_instance_admin.cc, google/cloud/bigtable/instance_update_config.h, google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc, google/cloud/bigtable/tests/instance_admin_integration_test.cc, google/cloud/google_cloud_cpp_common.bzl, google/cloud/google_cloud_cpp_common_unit_tests.bzl, google/cloud/internal/algorithm.h, google/cloud/internal/algorithm_test.cc, google/cloud/storage/tests/bucket_integration_test.cc
I also looked around for uses of `std::find` and `std::find_if` that were logically performing a "contains", and changed those to call this helper.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5898)
=> cleanup: add internal-only Contains() and ContainsIf() helpers

google/cloud/connection_options_test.cc, google/cloud/internal/common_options.h, google/cloud/internal/grpc_options.h
These options were in the `google/cloud/internal/` directory, but they were accidentally not in the `google::cloud::internal` namespace. Fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5900)
=> cleanup: internal/*_options.h were not in the internal namespace

google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
Carry over similar changes from backup_integration_test.  In
particular, only run `CleanupStaleInstances()` once, when the
test starts, rather than before every test case.  But follow
a previous suggestion to do so unconditionally, instead of
only when "slow" tests are enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5895)
=> cleanup(spanner): cleanup instance_admin_integration_test

google/cloud/spanner/integration_tests/BUILD, google/cloud/spanner/samples/BUILD
We now run the GOOGLE_CLOUD_CPP_SPANNER_SLOW_INTEGRATION_TESTS
overnight, with a couple of new ones either recently submitted
or in the works, so extend the timeout.
The change from 15m to 60m could cause a failure delay if you
hit a hang without even running the slow tests, but so be it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5926)
=> test(spanner): extend samples and integration-test timeouts

CHANGELOG.md, google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc, google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/table_admin.h, google/cloud/bigtable/tests/instance_admin_integration_test.cc, google/cloud/bigtable/version.h, google/cloud/storage/bucket_test.cc, google/cloud/storage/client.h, google/cloud/storage/examples/storage_bucket_iam_samples.cc, google/cloud/storage/tests/bucket_integration_test.cc, google/cloud/storage/version.h
These functions were already deprecated in the Doxygen documentation,
and have been since before 2019-08-01.
Thanks to @remyabel for pointing out that there were several TODO
entries for #2857 outstanding.
Part of the work for #5929 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5928)
=> cleanup: issue deprecation warnings for some IAM functions

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_common.bzl, google/cloud/internal/common_options.h, google/cloud/internal/common_options_test.cc, google/cloud/internal/grpc_options.h, google/cloud/internal/grpc_options_test.cc, google/cloud/internal/options.cc, google/cloud/internal/options.h, google/cloud/internal/options_test.cc
This PR adds the strict options checking function described in https://github.com/googleapis/google-cloud-cpp/issues/5738#issuecomment-779897018
Callers (i.e., our factory functions) will be able to check that a user-provided `Options` object contains only the set of expected options. Any unexpected options will be `GCP_LOG(WARNING)`'d. The log message will include the _mangled name_ of each unexpected option. See https://github.com/googleapis/google-cloud-cpp/issues/5738#issuecomment-786960263 for more discussion of this point.
Our factory functions will call this like:
```cc
spanner::MakeConnection(..., Options const& opts) {
internal::CheckExpectedOptions<internal::CommonOptions, internal::GrpcOptions>(options, …
```
=> feat: adds internal::CheckExpectedOptions<T>(...)

google/cloud/connection_options.h, google/cloud/connection_options_test.cc, google/cloud/internal/common_options.h, google/cloud/internal/common_options_test.cc, google/cloud/internal/grpc_options.cc, google/cloud/internal/grpc_options.h, google/cloud/internal/grpc_options_test.cc, google/cloud/internal/options.h, google/cloud/internal/options_test.cc
Fixes my concerns described in https://github.com/googleapis/google-cloud-cpp/pull/5864
The API changes in this PR
* "Option" structs now must contain a public `Type` member typedef indicating the type of the option's value. It no longer needs to have a public `.value` data member, and we no longer care how to construct one -- indeed, we never construct an "option" class at all.
* All uses of `absl::optional` are gone, as any "getter" method that might have to indicate that the value was not there. Instead, the only pure "getter" is `.get_or<T>(default_value)`, which returns by value, and can never fail because the caller must provide a default value to return if the option was not set (note: the default can simply be …
=> refactor: simplify the Options API, easier to use, improved efficiency

google/cloud/connection_options.h, google/cloud/connection_options_test.cc
A value (copy) is needed because we move the fields from the old
`ConnectionOptions` to the new `Options`. Previously it was requiring an
rvalue reference, which annoyingly required the caller to have to make
an explicit copy sometimes (e.g., if the caller only had a const-ref and
couldn't move).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5940)
=> cleanup: internal::MakeOptions accepts by value

google/cloud/connection_options.h, google/cloud/internal/grpc_options.cc, google/cloud/internal/grpc_options.h, google/cloud/internal/grpc_options_test.cc
This PR also adds a `internal::DefaultBackgroundThreadsFactory()` function. This function will be convenient to use as a default value when our factories inspect an option like:
```
auto f = opts.get_or<GrpcBackgroundThreadsFactoryOption>(internal::DefaultBackgroundThreadsFactory);
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5942)
=> refactor: renamed option to GrpcBackgroundThreadsFactoryOption

google/cloud/pubsub/samples/samples.cc
I did not pay enough attention to the difference between the AVRO and
protocol buffer samples.
Part of the work for #5706 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5944)
=> doc(pubsub): fix region tags for two examples

google/cloud/internal/options.h, google/cloud/internal/options_test.cc
It turns out that we actually can provide a const `get<T>()` method that
returns a const-ref by defining that it returns a reference to a static
value-initialzied default value. I think this will be very useful for
cases where we want to query an option with changing or setting it. For
example, in a number of places we inspect the `TracingComponentsOption`
which is a `std::set<std::string>` to see if it contains an element.
Using `.get<T>()` would let us do this without copying the `set` every
time. I believe this will also allow us to re-implement
`ConnectionOptions` in terms of `Options`, since it can now return
const-refs, even to unset options.
--- …
=> refactor: add Options::get<T>()

google/cloud/spanner/samples/samples.cc
Prefer streaming `google::cloud::spanner::Timestamp` values directly
over converting via `google::protobuf::util::TimeUtil::ToString()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5951)
=> cleanup(spanner): prefer spanner::Timestamp streaming

google/cloud/connection_options.h, google/cloud/connection_options_test.cc, google/cloud/internal/common_options.h, google/cloud/internal/common_options_test.cc, google/cloud/internal/grpc_options.cc
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/5952
Per the reasons in #5952, the type is changing form `std::set` ->
`std::vector` to convey that multiple can be set and the order matters.
This also renames the option from `UserAgentPrefixOption` ->
`UserAgentProductsOption` to better reflect the terminology used in
https://tools.ietf.org/html/rfc7231#section-5.5.3. It's also plural to
indicate that multiple can be set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5953)
=> refactor: rename user-agent option and change type

google/cloud/internal/common_options_test.cc, google/cloud/internal/grpc_options.cc, google/cloud/internal/grpc_options_test.cc, google/cloud/internal/options.h, google/cloud/internal/options_test.cc
(sorry for all these `Options` API changes, but it's still internal and these should happen before it's public.)
After adding a const-ref-returning `Options::get<T>()`, I think there's
very little need for `get_or`. AFAICT, all uses of "get_or" are more
clearly written as "get", and they're more efficient. Additionally, the
functionality provided by "get_or" is "convenient" at best, and could be
completely implemented as a non-member helper function, thus improving
encapsulation.
It's always easier to add APIs than remove them, so we should err on the
side of removing this before the API is public.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5955)
=> refactor: remove Options::get_or

google/cloud/bigtable/client_options.cc, google/cloud/bigtable/client_options_test.cc
This ensures dropped connections are detected promptly.
Fixes #5662
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5969)
=> feat(bigtable): enable keepalive pings by default

generator/internal/stub_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5972)
=> fix(generator): remove hardcoded method and response type in streaming rpc stub

google/cloud/storage/internal/curl_resumable_upload_session.cc, google/cloud/storage/internal/curl_resumable_upload_session_test.cc, google/cloud/storage/object_stream.h
Our documentation said the upload session id could change. This does not
seem to happen in production, and the APIs are harder to use if we
accept changes.  I modified to the doxygen documentation, and prevented
changes from having any effect (even if the changes are not supposed to
happen).
Fixes #5975
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5979)
=> fix(storage): do not update upload session ids

google/cloud/storage/internal/object_metadata_parser.cc, google/cloud/storage/object_metadata_test.cc, google/cloud/storage/tests/object_integration_test.cc
The library was ignoring any `custom_time()` attributes set in the
object metadata for inserts or writes.
Fixes #5977
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5980)
=> fix(storage): correctly set customTime on inserts

google/cloud/internal/options.cc, google/cloud/internal/options.h, google/cloud/internal/options_test.cc
Also changed `CheckExpectedOptions` to use doxygen-style `/** */` comments since it was wrong and looked funny next to `MergeOptions()` w/ the doxygen-style comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5991)
=> feat(internal): add internal::MergeOptions()

google/cloud/spanner/internal/options.cc, google/cloud/spanner/internal/options_test.cc, google/cloud/spanner/session_pool_options.h, google/cloud/spanner/session_pool_options_test.cc
This will allow us to remove `SessionPoolOptions` in factory functions that take the new `Options` class. The new options are in `spanner_internal` for now. They'll be made public as soon as we decide to make `Options` public.
There should be no API or semantic change in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5992)
=> refactor(spanner): implement SessionPoolOptions in terms of Options

google/cloud/bigtable/client_options.cc, google/cloud/bigtable/client_options.h, google/cloud/bigtable/instance_admin.cc, google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/instance_admin_client.cc, google/cloud/bigtable/instance_admin_client.h, google/cloud/bigtable/internal/common_client.h, google/cloud/bigtable/internal/logging_instance_admin_client.h, google/cloud/bigtable/testing/mock_instance_admin_client.h, google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This is a part of #2567.
Eventually, most `Async*` calls will be removed from the Bigtable API
but those which will remain (in `Table`) will have the `CompletionQueue`
argument removed. Instead, the `CompletionQueue` will be bound with
the `Table` object. In the same spirit, we're binding it with
`InstanceAdmin` in this PR. This allows to eliminate creating threads on
all calls which return `future<>`s but do not take a `CompletionQueue`
argument.
A decision was made to store the background threads in `InstanceAdmin`
rather than `CommonClient` even though `CommonClient` seems to resemble
other clients better. This is because `CommonClient` must not be the
owner of the background threads executing the completion queue
associated with itself because at some point the completion queue may …
=> feat: bind `CompletionQueue` with InstanceAdmin

google/cloud/spanner/client.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h, google/cloud/spanner/internal/connection_impl_test.cc
There's no need for a factory to construct
`spanner_internal::ConnectionImpl`. We can just construct it directly
from `client.cc`. I don't think the factory was adding any value, but it
was adding an extra layer of things to plumb parameters through.
This also makes the code easier to follow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5995)
=> refactor(spanner): remove unnecessary MakeConnection factory

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/options.cc, google/cloud/spanner/internal/options.h, google/cloud/spanner/internal/options_test.cc
These options are internal-only and spanner specific. They will not be
used by customers and we can change them if/when we have other
user-facing options that we want our customers to use. In the mean time,
our implementation can use these options to pass around RetryPolicy and
BackoffPolicy objects inside an `Options`, without having to pass them
as separate arguments.
Note: these options hold the policies in `std::shared_ptr<T>` rather
than unique_ptr. This is because `Options` uses `absl::any`, which
doesn't work with move-only types. However, I think shared_ptr should be
fine for these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5994)
=> refactor(spanner): adds internal-only spanner-specific Retry and Backoff options

ci/kokoro/macos/build-quickstart-bazel.sh, ci/kokoro/macos/build-quickstart-cmake.sh, ci/kokoro/macos/build.sh, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-cmake.ps1, ci/kokoro/windows/build-quickstart-bazel.ps1, ci/kokoro/windows/build-quickstart-cmake.ps1, google/cloud/bigtable/examples/README.md, google/cloud/bigtable/quickstart/README.md, google/cloud/pubsub/quickstart/README.md, google/cloud/spanner/quickstart/README.md, google/cloud/spanner/samples/README.md
That is a shorter URL, and seems better to use a google.com address to
get it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5999)
=> cleanup: get roots.pem from https://pki.google.com

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc, google/cloud/spanner/client.cc, google/cloud/spanner/connection_options.cc, google/cloud/spanner/connection_options.h, google/cloud/spanner/connection_options_test.cc, google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/integration_tests/session_pool_integration_test.cc, google/cloud/spanner/internal/database_admin_stub.cc, google/cloud/spanner/internal/database_admin_stub.h, google/cloud/spanner/internal/instance_admin_stub.cc, google/cloud/spanner/internal/instance_admin_stub.h, google/cloud/spanner/internal/spanner_stub.cc, google/cloud/spanner/internal/spanner_stub.h, google/cloud/spanner/internal/spanner_stub_test.cc
There's no user-facing change in this PR. This just changes the lowest-layer of the Spanner stack to start accepting the new `Options`, so we can make these changes in bite-sized PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5998)
=> refactor(spanner): changes the "stub" layer to use `Options`

google/cloud/bigtable/testing/random_names.cc, google/cloud/bigtable/testing/random_names_test.cc
Thanks to @devbww for noticing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6002)
=> cleanup(bigtable): remove ill-conceived static checks

google/cloud/bigtable/admin_client.cc, google/cloud/bigtable/admin_client.h, google/cloud/bigtable/internal/logging_admin_client.h, google/cloud/bigtable/table_admin.cc, google/cloud/bigtable/table_admin.h, google/cloud/bigtable/testing/inprocess_admin_client.h, google/cloud/bigtable/testing/mock_admin_client.h
This is a part of #2567 and a continuation of #5967.
This MR makes all synchronous operations on `TableAdmin`
execute on a `CompletionQueue` bound with that `TableAdmin`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6004)
=> feat: bind `CompletionQueue` with `TableAdmin`

google/cloud/bigtable/tests/data_integration_test.cc
This fixes a table leaked from the integration tests. Earlier today I
push changes to garbage collect all tables leaked for any reason, but
this is a little more tidy.
Looks like the title should be "last table leak".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6003)
=> test(bigtable): plug one table leak

bazel/curl.BUILD
```
➜  google-cloud-cpp git:(master) ✗ ls /etc/arch-release                    
/etc/arch-release
➜  google-cloud-cpp git:(master) ✗ ls -l /etc/ssl/certs/ca-certificates.crt
lrwxrwxrwx 1 root root 49 Jul 28  2020 /etc/ssl/certs/ca-certificates.crt -> ../../ca-certificates/extracted/tls-ca-bundle.pem
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6011)
=> Arch build support: ca-certificates.crt location

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/internal/async_retry_loop.h, google/cloud/internal/async_retry_loop_test.cc, google/cloud/internal/async_retry_unary_rpc.h, google/cloud/internal/async_retry_unary_rpc_test.cc, google/cloud/internal/setup_context.h
Part of the work for #4926.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6014)
=> fix(bigtable): set timeouts for asynchronous operations

google/cloud/spanner/client.cc, google/cloud/spanner/integration_tests/session_pool_integration_test.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/options.cc, google/cloud/spanner/internal/options_test.cc, google/cloud/spanner/internal/session_pool.cc, google/cloud/spanner/internal/session_pool.h, google/cloud/spanner/internal/session_pool_test.cc
There's a little crud in the code because some classes (e.g.
ConnectionImpl) are hybrid using the new and old Options. This naturally
be cleaned up when we move everything to Options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6006)
=> refactor(spanner): session_pool now uses Options

google/cloud/spanner/samples/samples.cc
A newly changed requirement on the PITR `CreateBackup()` sample
(see #5943 for the previous change) to hide the source of the
`version_time` from the snippet altogether by passing it as a
parameter.  Let's extend that decision to `expire_time` too.
In the process, let's avoid cross-clock-domain issues as well,
by only using timestamps originated by the service.  In these
cases we only need "now", from `SELECT CURRENT_TIMESTAMP()`
instead of from `absl::Now()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6016)
=> cleanup(spanner): new version time in spanner_create_backup sample

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_common.bzl, google/cloud/google_cloud_cpp_common_unit_tests.bzl, google/cloud/internal/type_list.h, google/cloud/internal/type_list_test.cc
Also adds the ability to concatenate type lists. This makes it so we
don't need to use `std::tuple` and `std::tuple_cat` when we only care
about the types and we don't care about values. This is important
because `std::tuple_cat` breaks with large type lists on clang-3.8.
I plan to use this in `google/cloud/internal/options.h` in a following
PR to avoid breakages like this: https://source.cloud.google.com/results/invocations/f5efd65c-943c-4050-85d2-5ee41289e702/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Fclang-3.8-presubmit/log
Note: If/when we get rid of clang-3.8, we could easily replace this with
calls to `<tuple>` stuff, if we think that's simpler.
--- …
=> feat(internal): add internal-only `TypeList`

google/cloud/internal/common_options.h, google/cloud/internal/common_options_test.cc, google/cloud/internal/grpc_options.h, google/cloud/internal/grpc_options_test.cc, google/cloud/internal/options.h, google/cloud/internal/options_test.cc, google/cloud/spanner/client.cc, google/cloud/spanner/internal/options.h, google/cloud/spanner/session_pool_options.h
This PR avoids `std::tuple` in favor of our own `TypeList` for creating
lists of options. This PR also introduces a `OptionList<...>`, which is
a template alias to allow us to define lists of related options. I also
add this list to two places in Spanner that were missing.
This will fix the error in https://source.cloud.google.com/results/invocations/f5efd65c-943c-4050-85d2-5ee41289e702/targets
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6024)
=> refactor(internal): create OptionList<...> implemented with TypeList

google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc
This is the function that *will be* the preferred user-facing
"MakeConnection" function. It's requires a `spanner::Database` argument,
and nothing else. A single, optional `Options` argument may be specified
to configure aspects of the returned `Connection`. Appropriate defaults
will be used for any unspecified option, so `{}` is a valid (and the
default) argument.
The other `MakeConnection` overloads will continue to exist and they
will simply forward to this one new/preferred overload. The old
overloads will NOT be deprecated, so we will not break existing callers.
However, we will clearly document all the overloads to make it clear
that the new overload should be preferred, so that customers do not
struggle to decide which overload to choose.
Of course, this is all "internal" for now, …
=> refactor(spanner): add spanner_internal::MakeConnection

google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/database_admin_connection.h, google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/internal/options.cc, google/cloud/spanner/internal/options.h, google/cloud/spanner/internal/options_test.cc
This PR changes adds a `MakeDatabaseAdminConnection` overload (currently
in `spanner_internal`) that accepts the new `Options`. This is the
overload that _will be_ the recommended user-facing factory once
`Options` become public. All other factories forward to this one (except
for the one overload that exists only for testing.)
This PR also adds `spanner_internal::DefaultAdminOptions`, which will create
the correct defaults for Spanner's admin operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6026)
=> refactor(spanner): db admin connection uses new Options

google/cloud/spanner/internal/options.cc
There's no actual change in the resulting user-agent string, just changing to use the common `UserAgentPrefix()` function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6028)
=> refactor(spanner): use common UserAgentPrefix function

google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/instance_admin_connection.h, google/cloud/spanner/instance_admin_connection_test.cc
This PR defines an `MakeInstanceAdminConnection` that accepts the new
`Options` (within `spanner_internal`), and this will be the preferred
factory as soon as Options is public.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6027)
=> refactor(spanner): instance admin uses new Options

google/cloud/spanner/internal/options.cc, google/cloud/spanner/internal/options_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6035)
=> refactor(spanner): DefaultAdminOptions don't need SessionPool options

google/cloud/spanner/connection_options.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h
Cleans up some TODOs related to
https://github.com/googleapis/google-cloud-cpp/issues/5738.
Some of the TODOs are able to be completed now.
The TODO in connection_option.cc was not done, but I decided that it
doesn't actually need to be done. Caching the endpoint in a
function-local static is purely a performance optimization, which we
could do at any point if it's an _actual_ performance issue in practice.
Until then, it's safest to preserve backward compatible semantics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6043)
=> cleanup(spanner): remove some TODOs

google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc, google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/database_admin_connection.h, google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/instance_admin_connection.h, google/cloud/spanner/instance_admin_connection_test.cc, google/cloud/spanner/integration_tests/session_pool_integration_test.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/internal/defaults.cc, google/cloud/spanner/internal/defaults_test.cc, google/cloud/spanner/internal/session_pool.cc, google/cloud/spanner/internal/session_pool_test.cc, google/cloud/spanner/options.h, google/cloud/spanner/session_pool_options.h, google/cloud/spanner/session_pool_options_test.cc
This is a mechanical rename PR, where some existing types and functions are moving from `spanner_internal::` -> `spanner::` to become public. In a few places I manually tweaked the resulting comments.
* All the types in `google/cloud/spanner/options.h` are now "public" in the `spanner::` namespace
* `spanner::MakeConnection()` now recommends use of the `Options` overload
* `spanner::MakeDatabaseAdminConnection()` now recommends use of the `Options` overload
* `spanner::MakeInstanceAdminConnection()` now recommends use of the `Options` overload
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6046 …
=> feat(spanner): connection factories now prefer `Options`

google/cloud/testing_util/BUILD
On macos 11 intel, we will have the following compilation problem:
```
ERROR: Analysis of target '//google/cloud/pubsub/samples:samples' failed; build aborted: /Users/vovannghia/programming/google-cloud-cpp/google/cloud/testing_util/BUILD:43:11: Illegal ambiguous match on configurable attribute "defines" in //google/cloud/testing_util:google_cloud_cpp_testing:
@bazel_tools//src/conditions:darwin_x86_64
@bazel_tools//src/conditions:darwin
```
This PR removes `@bazel_tools//src/conditions:darwin` configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6044)
=> common: fix ambiguous match bazel error on macos 11 intel

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc, google/cloud/pubsub/samples/samples.cc
If an application canceled a session before the first `Write()` call
completes in the startup sequence.
Changed `pubsub/samples/samples.cc` to make it easier to troubleshoot
this problem, I am keeping the change because it feels generally useful.
Fixes #6053
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6055)
=> fix(pubsub): deadlocks for cancel during session startup

google/cloud/bigtable/instance_admin_test.cc
Clang's static analyzer sees the raw call to `new` as potentially
leaking. It is not, but it is also not consistent with how we assign
proto message fields elsewhere in the code, so I changed it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6067)
=> cleanup(bigtable): cleanup static analyzer nit

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/lifecycle_rule.cc
We were using objects after move-assigning from them. Found using
Clang's static analyzer.
Also cleaned up a (mostly harmless) unused assignment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6066)
=> fix(storage): use after move problems

google/cloud/iam_binding.h, google/cloud/iam_bindings.cc, google/cloud/iam_bindings.h, google/cloud/iam_bindings_test.cc, google/cloud/iam_policy.h, google/cloud/storage/internal/bucket_requests.cc, google/cloud/storage/internal/bucket_requests_test.cc, google/cloud/version.h
These types are only used in (already) deprecated IAM functions. I
wanted to deprecate each type, but that requires too many changes to
disable the diagnostics where we use the types. Instead I updated the
documentation and used deprecation attributes in the functions a
customer would use if they used the type.
Part of the work for #5929
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6069)
=> cleanup: deprecate some IAM types

generator/CMakeLists.txt, google/cloud/CMakeLists.txt, google/cloud/bigquery/CMakeLists.txt, google/cloud/bigtable/CMakeLists.txt, google/cloud/iam/CMakeLists.txt, google/cloud/logging/CMakeLists.txt, google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsub/benchmarks/CMakeLists.txt, google/cloud/spanner/CMakeLists.txt, google/cloud/storage/CMakeLists.txt, google/cloud/storage/benchmarks/CMakeLists.txt
With older versions of Abseil doing `find_package(absl)` generated some
ugly warnings. This got fixed with the update to the 2020-09 release.
Fixes #4146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6076)
=> cleanup: remove workarounds for absl package

google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh, google/cloud/bigtable/tools/run_emulator_utils.sh
On Bazel builds it is worthwhile to use fixed ports for the emulators,
as Bazel invalidates the test results cache if the port changes. This
should save about 30 seconds in the PR builds.
Fixes #4125
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6077)
=> test(bigtable): fix ports for emulators with Bazel

ci/cloudbuild/build.sh, ci/cloudbuild/cache.sh, ci/cloudbuild/cloudbuild.yaml
Adds a `ci/cloudbuild/cache.sh` script that is responsible for `save`'ing and `restore`'ing our build caches to/from GCS.
There are also two new build steps in the `cloudbuild.yaml` file that call this script at the appropriate times.
NOTE: The `~/.cache/bazel` directory is not currently cached. It was huge and it wasn't clear if it was beneficial. I'll look into
fixing that later, or just using the normal remote build cache for bazel.
This PR also creates a home directory mount of `/h` that's visible to all build steps so they can all read/write to the homedir.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6084)
=> feat(ci): add caching to GCB builds

ci/cloudbuild/builds/asan.sh, ci/cloudbuild/builds/bazel+clang.sh, ci/cloudbuild/builds/bazel+gcc.sh, ci/cloudbuild/builds/lib/bazel.sh, ci/cloudbuild/builds/ubsan.sh, ci/cloudbuild/cloudbuild.yaml
This PR also introduces the pattern of shell libraries that the builds
in `ci/cloudbuild/builds/` can use with `source module`. This PR adds
the `lib/bazel.sh` library which computes the common bazel flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6086)
=> ci: add bazel remote caching to GCB builds

ci/cloudbuild/builds/clang-tidy.sh, ci/cloudbuild/builds/cmake+clang.sh, ci/cloudbuild/builds/cmake+gcc.sh, ci/cloudbuild/builds/lib/cmake.sh
This PR adds a `ci/cloudbuild/builds/lib/cmake.sh` module that
automatically prints ccache stats at the end of cmake-based builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6088)
=> ci: print ccache stats at the end of cmake builds

.bazelrc, ci/cloudbuild/builds/xsan.sh
Adds an `xsan` GCB build. This runs several sanitizers that are not already run elsewhere, such as 
`-fsanitize=float-divide-by-zero` and `-fsanitize=nullability`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6090)
=> ci: add an xsan GCB build

ci/cloudbuild/trigger.sh, ci/cloudbuild/triggers/asan-ci.yaml, ci/cloudbuild/triggers/asan.yaml, ci/cloudbuild/triggers/clang-tidy-ci.yaml, ci/cloudbuild/triggers/clang-tidy.yaml, ci/cloudbuild/triggers/cmake-clang-ci.yaml, ci/cloudbuild/triggers/cmake-clang.yaml, ci/cloudbuild/triggers/cmake-gcc-ci.yaml, ci/cloudbuild/triggers/cmake-gcc.yaml, ci/cloudbuild/triggers/ubsan.yaml, ci/cloudbuild/triggers/xsan-ci.yaml
The list of triggers and yaml files will grow, but for now, I'm just
copying what currently exists in the UI.
This PR also adds a script, `trigger.sh`, to make it easier for us to
manipulate these trigger yaml files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6092)
=> ci: add yaml files for current triggers

external/googleapis/CMakeLists.txt
Looks like this typo slipped in during [this PR](https://github.com/googleapis/google-cloud-cpp/pull/5756/files#diff-a5ee3f8b8c970f368418195cd806ad21e60d9d50dddab1fa22a8a62474ff7d66L726)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6095)
=> fix: pkg-config requires typo

external/googleapis/CMakeLists.txt
I think these slipped in during
https://github.com/googleapis/google-cloud-cpp/pull/5756 also.
FYI: I'm creating a CI build that will catch these in the future...
that's how I found these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6097)
=> fix: two more pkg-config requires typos

ci/cloudbuild/builds/cmake-install.sh
Adds a `cmake-install` GCB build that compiles and installs our repo following the instructions at https://github.com/googleapis/google-cloud-cpp/blob/master/doc/packaging.md#installing-google-cloud-cpp (pretty closely). It then validates the installed artifacts:
* It looks at the installed directory structure.
* It looks at the file extensions of the installed files
* It validates all installed pkg-config files with `pkg-config --validate <file>`
Any error breaks the build, but it tries to continue to display as many errors as possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6099)
=> ci: add cmake-install GCB build

bazel/google_cloud_cpp_deps.bzl, ci/kokoro/docker/Dockerfile.fedora, ci/kokoro/docker/Dockerfile.fedora-install, external/googleapis/CMakeLists.txt
When developing a new feature based on simple changes to the
googleapis repo, it may well be easier to apply a patch to the
downloaded proto files rather than dealing with branches.
Those googleapis branches are often not kept up to date, so it
can be difficult to rebase branches in this repo, which hinders
developing at head. Patching also allows for the possibility of
layering changes from multiple googleapis branches.
This PR doesn't change any behavior, but it does leave indicators
for where patches can be applied in both the CMake and bazel
builds, as well as adding the "patch" binary to the docker images.
I recently used this mechanism to check whether a proposed proto
rearrangement would affect the build for the Cloud Spanner client.
An additional lesson from that effort was that …
=> chore: building blocks for patching googleapis after download

ci/cloudbuild/build.sh, ci/cloudbuild/cloudbuild.yaml
This PR simplifies the `ci/cloudbuild/build.sh` script so that it now
takes an (optional) `--project` flag (the same as `gcloud`), and it no
longer requires/supports the `--cache_bucket` flag. The cache bucket is
now computed from the specified (or defaulted) project ID, and it's the
same cache bucket that Google Cloud Build uses for its source upload.
The bucket is: `${PROJECT_ID}_cloudbuild`. The nice thing is that GCB
creates this bucket if necessary automatically, and we re-use this same
bucket for our build cache and bazel cache. So we only have a single
"cloudbuild" bucket now, instead of two.
I also changed the "base" branch cache key to be named "main", since
this will eventually match our `main` branch, and that's the build that
it corresponds to. I did this now since changing …
=> refactor(ci): simplified gcb build.sh to accept --project

ci/cloudbuild/build.sh
Manual build caches show up named like `manual-<user>`. The username
part should use the gcloud account rather than the `id -un`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6109)
=> ci: use Cloud ID rather than unix ID

ci/cloudbuild/builds/integration.sh
This runs most integration tests in Google Cloud Build using bazel. They
use emulators when possible. Some tests are not yet enabled because they
require a bit more work, but there are TODOs mentioning what's missing.
Note that these integration tests do not require any special service account files.
The cloud build account has the needed access rights to run these. And team members can run
these from their workstation, again without needing service account files, with a command like:
```
./ci/cloudbuild/build.sh --project cloud-cpp-testing-resources integration
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6112)
=> ci: add integration tests to GCB

ci/cloudbuild/build.sh, ci/cloudbuild/builds/cmake-install.sh, ci/lib/io.sh
In GCB, our builds run without a TTY so the colors in our logs don't
show up. To make log sections easier to spot visually in a sea of
black-n-white, I'm adding `io::log_h1` and `io::log_h2` to make it easy
to output H1 and H2 (think of html heading tags) headings in boxes to
make them visually distinct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6114)
=> ci: add h1 and h2 heads to ci/lib/io.sh

ci/cloudbuild/cloudbuild.yaml
This will delete the BUILD_ID-specific docker image at the end of a
successful build. It will also clean up 4-week old images that were left
around from failed builds that didn't get to the cleanup step.
This PR also changes the image name to something nicer and shorter, and this will let us manually
clean up all the old images that are now lying around.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6111)
=> ci: garbage collect docker images in GCB

ci/cloudbuild/build.sh, ci/cloudbuild/cloudbuild.yaml
This flag is better than looking for a special string of "local" in
`DISTRO`. This also sets up the script for the next flag, which will be
`--docker` to run the build in docker on the current machine instead of
submitting to cloud build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6119)
=> ci: add --local flag to GCB build.sh

ci/cloudbuild/build.sh
This makes it easier to run a build because `--distro` need not be
specified. Example:
```
build.sh asan  # Runs build in GCB using `fedora`
build.sh --local asan  # Runs build on local machine; distro unnecessary
```
I also removed the `-d` shorthand for distro since it will likely be
rarely used, and foresee wanting to use that short flag to mean
`--docker` (upcoming).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6121)
=> ci(gcb): distro can now be looked up from trigger file

google/cloud/spanner/integration_tests/backup_integration_test.cc, google/cloud/spanner/samples/samples.cc
A decision was made to simplify the CMEK samples by eliminating
verification of the encryption key used in the `CreateDatabase()`,
`CreateBackup()`, and `RestoreDatabase()` calls.  Any reduction
in coverage has been made up by additions to the integration test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6120)
=> feature(spanner): update CMEK samples

.bazelignore, .gitignore, ci/cloudbuild/build.sh
This PR adds the `-d | --docker` flags to run the specified build using
the local docker. This let's users run our GCB builds locally in an
environment that's very similar (exact? pretty close) to the GCB
environment. This also makes debugging easier. Users can start a bash
shell in the specified docker container by passing the `-s | --docker_shell`
flag.
Examples:
```
build.sh cmake-install  # Runs build on GCB
build.sh cmake-install --local  # Runs build on your local machine
build.sh cmake-install --docker  # Runs build in docker
build.sh cmake-install --docker-shell  # Starts shell in docker
```
These docker builds create a "build-out" directory on the host system to
store all their output (similar to our current "cmake-out" directory,
but not cmake-specific). All their build output …
=> ci(gcb): add --docker flag

ci/cloudbuild/build.sh
These builds can run in a variety of environments, in Google Cloud
Build, a local docker, or on the local machine. It can be useful to
see some stats about the local machine runing the build.
Example output from a cloud build run:
```
Step #2: ====================
Step #2: |   Machine Info   |
Step #2: ====================
Step #2:     local: Sat Mar 27 17:32:03 UTC 2021 (+0000)
Step #2:       utc: Sat Mar 27 17:32:03 UTC 2021
Step #2:    kernel: #41~18.04.1-Ubuntu SMP Fri Feb 26 22:23:13 UTC 2021
Step #2:        os: PRETTY_NAME="Fedora 33 (Container Image)"
Step #2:     nproc: 32
Step #2:       mem: 28.21 GiB
Step #2:       gcc: gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
Step #2:     clang: clang version 11.0.0 (Fedora 11.0.0-2.fc33)
Step #2:        cc: cc (GCC) 10.2.1 20201125 (Red …
```
=> ci(gcb): print info about machine doing local build

ci/cloudbuild/build.sh, ci/cloudbuild/cloudbuild.yaml
Per @devbww's comments on
https://github.com/googleapis/google-cloud-cpp/pull/6123, we set
`TZ=:UTC` for docker and GCB builds so our logs -- and others' logs --
show up in UTC to make them easily comparable. This PR also logs the
time that google.com thinks it is, which would help us diagnose issues
caused by time synchronization issues (which we've seen on Kokoro).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6124)
=> ci(gcb): set TZ=:UTC; log google_time

ci/cloudbuild/trigger.sh, ci/cloudbuild/triggers/asan-ci.yaml, ci/cloudbuild/triggers/asan.yaml, ci/cloudbuild/triggers/clang-tidy-ci.yaml, ci/cloudbuild/triggers/cmake-clang-ci.yaml, ci/cloudbuild/triggers/cmake-clang.yaml, ci/cloudbuild/triggers/cmake-gcc-ci.yaml, ci/cloudbuild/triggers/cmake-gcc.yaml, ci/cloudbuild/triggers/cmake-install-ci.yaml, ci/cloudbuild/triggers/cmake-install.yaml, ci/cloudbuild/triggers/integration-ci.yaml, ci/cloudbuild/triggers/integration.yaml, ci/cloudbuild/triggers/ubsan-ci.yaml, ci/cloudbuild/triggers/ubsan.yaml, ci/cloudbuild/triggers/xsan-ci.yaml, ci/cloudbuild/triggers/xsan.yaml
Adds flags to output the YAML configs for a named build. The generated
YAML config can then be manually tweaked (if needed), and checked in.
Generating the config doesn't actually submit the file to GCB. To do
that, you must then use `trigger.sh --import <new-yaml-file>`.
I also used these flags to generate configs for a few builds that were
missing triggers and therefore weren't running (like integration and
xsan).
I also simplified the yaml configs:
- I removed the created time and trigger IDs, which are output-only
fields
- I removed the trigger tags, which don't really do anything useful, and
are difficult to generate automatically
--- …
=> ci(gcb): adds flags to generate yaml triggers

ci/cloudbuild/builds/lib/bazel.sh, ci/cloudbuild/builds/quickstart-bazel.sh, ci/cloudbuild/builds/quickstart-cmake.sh, ci/cloudbuild/cloudbuild.yaml, ci/cloudbuild/triggers/quickstart-bazel-ci.yaml, ci/cloudbuild/triggers/quickstart-bazel.yaml, ci/cloudbuild/triggers/quickstart-cmake-ci.yaml, ci/cloudbuild/triggers/quickstart-cmake.yaml, ci/cloudbuild/ubuntu-bionic.Dockerfile, ci/etc/quickstart-config.sh
The `quickstart-cmake` builds use ccache to speed up the building of the `vcpkg` binary itself. And it uses `VCPKG_BINARY_SOURCES` to speed up vcpkg's installation of `google-cloud-cpp`. 
I'll enable these triggers after this PR merges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6132)
=> ci(gcb): add quickstart-cmake and quickstart-bazel builds

ci/cloudbuild/builds/tsan.sh, ci/cloudbuild/triggers/tsan-ci.yaml, ci/cloudbuild/triggers/tsan.yaml
Will make all the *san builds run integration tests in a future PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6134)
=> ci(gcb): add tsan build

ci/cloudbuild/builds/lib/bazel.sh
This also changes the H2 log to a regular log because the h2 banner made
it look like all the following bazel build output was part of the
prefetching. Output now looks like:
```
==================================
|   Starting local build: asan   |
==================================
2021-03-30T21:16:12Z: Prefetching bazel deps...
Starting local Bazel server and connecting to it...
INFO: All external dependencies fetched successfully.
Loading: 125 packages loaded
==> 🕑 prefetching done in 5.045 seconds
INFO: Analyzed 532 targets (1 packages loaded, 5924 targets configured).
INFO: Found 182 targets and 350 test targets...
...
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/go …
=> ci(gcb): time the bazel prefetching

ci/cloudbuild/builds/lib/bazel.sh
Bash's `time` builtin writes to stderr, and GCB sometimes mixes up
output order between stdout and stderr. So this PR outputs the blank
line to stderr so that it will always follow the `time` output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6146)
=> ci(gcb): write newline to stderr to match time

ci/cloudbuild/builds/integration.sh, google/cloud/storage/examples/storage_policy_doc_samples.cc, google/cloud/storage/examples/storage_signed_url_v2_samples.cc, google/cloud/storage/examples/storage_signed_url_v4_samples.cc
The storage client library defaults to the account used in the
credentials as the signing account for signed URLs. This does not work
for users running the examples in the command-line, as only service
accounts can sign urls. It also does not work for the cloud builds,
where the account used for authentication cannot sign blobs as itself,
but can sign blobs as "other" accounts.
This PR changes the examples to require a signing account parameter.
Fortunately, we already had a convenient environment variable with such
an account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6149)
=> doc(storage): always use signing account in examples

ci/cloudbuild/builds/integration.sh, ci/cloudbuild/fedora.Dockerfile
The keyfiles will be stored in a special GCS bucket that the cloudbuild
account has access to read. The keyfiles are named `key-YYYY-MM.ext` to
make it easier to rotate the keys. The idea is that GCB jobs should
always look for the key w/ the current month. Rotating the keys will be
done separately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6150)
=> ci(gcb): enable GCS tests that require json and p12 keyfiles

google/cloud/internal/retry_loop_helpers.cc, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_object_read_source.cc, google/cloud/storage/internal/retry_resumable_upload_session.cc
When adding detail to a `Status` message, but keeping the same
code, use `status.message()` to obtain the previous text, rather
than streaming `status`, as the latter will contain " [CODE]",
which will then be duplicated when the new value is streamed.
For example, when prefixing "func: " to an existing `Status` of
"file [NOT_FOUND]", we want to produce "func: file [NOT_FOUND]"
and not "func: file [NOT_FOUND] [NOT_FOUND]".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6162)
=> cleanup: do not duplicate the Status code within its message

google/cloud/storage/internal/curl_handle_factory.cc, google/cloud/storage/internal/curl_handle_factory.h
Replace `std::vector<>` with `std::deque<>` because when the pool grows
too large we want to remove the *oldest* handles (fron the front). Also,
use a while loop during cleanup because it makes the intent clearer. I
expect that while loop to run at most once, but why force humans to
think this through?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6169)
=> feat(storage): reduce overhead in pooled handle factory

google/cloud/bigtable/client_options.cc, google/cloud/bigtable/client_options_test.cc
Since the bigtable main endpoint `bigtable.googleapis.com` has rollout to DirectPath, we no longer need the DirectPath specific endpoing `directpath-bigtable.googleapis.com`, and we should move all the tests to use the main endpoint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6175)
=> cleanup(bigtable): remove DirectPath specific endpoint

google/cloud/storage/client_options.cc, google/cloud/storage/client_options.h, google/cloud/storage/client_options_test.cc
This just changes the implementation of `storage::ClientOptions` to be
based on `google::cloud::Options`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6183)
=> refactor(storage): use g::c::Options in ClientOptions

ci/cloudbuild/builds/lib/cmake.sh
This should help us understand our build performance and possibly
diagnose timeouts like
https://github.com/googleapis/google-cloud-cpp/issues/6184
The output looks like:
```
T+10.458s [611/1832] Running gRPC C++ protocol buffer compiler on /wo...ogleapis/src/googleapis_download/google/cloud/bigquery/v2/model.proto
google/cloud/bigquery/v2/model.proto:28:1: warning: Import google/api/annotations.proto is unused.
T+10.701s [619/1832] Building CXX object external/googleapis/CMakeFil...protos.dir/google/cloud/bigquery/datatransfer/v1/datatransfer.pb.cc.o
external/googleapis/google/cloud/bigquery/datatransfer/v1/datatransfer.pb.cc:2271:13: warning: 'transfer_type' is deprecated [-Wdeprecated-declarations]
```
--- …
=> ci(gcb): add elapsed time to Ninja builds

doc/contributor/howto-guide-setup-cmake-environment.md, super/ExternalProjectHelper.cmake, vcpkg.json
Use the (relatively new) vcpkg "manifest mode" to download and build
dependencies for developers using CMake. We are keeping the superbuild
files for now, though I am not sure we need to.
Part of the work for #5803
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6191)
=> cleanup: prefer vcpkg to manage dependencies

ci/kokoro/windows/build-cmake.ps1
Part of the work for #6192. Manually triggering the build works with this PR:
https://source.cloud.google.com/results/invocations/f2bb1b2e-d029-4a7f-a416-fe66f6686bfd
I do not believe this PR "fixes" anything, but at least improves the logs in a failure. That should
make troubleshooting easier. I know believe #6192 was a flake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6193)
=> ci: improve Windows+CMake logs

ci/kokoro/windows/build-cmake-dependencies.ps1
Use a more recent version of vcpkg and the vcpkg-tool. These include
support for cross-compilation, and our manifest file describe such
dependencies.
Part of the work for #6192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6194)
=> ci: windows update vcpkg version

ci/kokoro/lib/cache.sh, ci/kokoro/macos/build-quickstart-cmake.sh, ci/kokoro/macos/build.sh
The build scripts had gone stales since they were disabled. I made a number
of changes:
- Update the vcpkg version to work well with manifests.
- The Kokoro pool we are using does not have CMake or Ninja pre-installed. Use the versions downloaded by vcpkg. Better to download them only once.
- Manually re-install `gcloud` and `gsutil` because the version pre-installed in this pool seems broken.
Part of the work for #3731 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6197)
=> ci: fix quickstart+CMake builds on macOS

google/cloud/storage/client_options.cc, google/cloud/storage/client_options.h, google/cloud/storage/client_options_test.cc, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_client.h, google/cloud/storage/internal/curl_handle_factory.cc, google/cloud/storage/internal/curl_handle_factory.h, google/cloud/storage/internal/curl_handle_factory_test.cc, google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/internal/curl_request_builder.h, google/cloud/storage/internal/curl_resumable_upload_session_test.cc, google/cloud/storage/internal/curl_wrappers.cc, google/cloud/storage/internal/curl_wrappers.h, google/cloud/storage/internal/curl_wrappers_disable_sigpipe_handler_test.cc, google/cloud/storage/internal/curl_wrappers_enable_sigpipe_handler_test.cc, google/cloud/storage/internal/curl_wrappers_locking_already_present_test.cc, google/cloud/storage/internal/curl_wrappers_locking_disabled_test.cc, google/cloud/storage/internal/curl_wrappers_locking_enabled_test.cc, google/cloud/storage/oauth2/authorized_user_credentials.h, google/cloud/storage/oauth2/service_account_credentials.h, google/cloud/storage/tests/curl_request_integration_test.cc
Change `google::cloud::internal::CurlClient` to receive a
`google::cloud::Options` for its configuration. Several related classes
and functions in `internal::` needed adjusting to their interfaces too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6203)
=> refactor(storage): use g::c::Options in CurlClient

google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/client_options.cc, google/cloud/storage/client_options.h, google/cloud/storage/client_options_test.cc, google/cloud/storage/grpc_plugin.cc, google/cloud/storage/internal/curl_client.h, google/cloud/storage/internal/curl_resumable_upload_session_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_failures_test.cc, google/cloud/storage/internal/grpc_client_object_request_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/internal/hybrid_client.h, google/cloud/storage/testing/storage_integration_test.cc, google/cloud/storage/tests/grpc_integration_test.cc
Change `storage::internal::GrpcClient` and
`storage::internal::HybridClient` to use `google::cloud::Options`. I had
to define exactly where the defaults are applied to an `Options` object,
for now this is in the `*Client::Create()` factory functions, it may get
refined later.
Some additional refactoring in `storage::ClientOptions` and
`storage::internal::CurlClient` to share the initialization of default
options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6209)
=> refactor(storage): use g::c::Options for GrpcClient

ci/cloudbuild/notifiers/bigquery.yaml, ci/cloudbuild/notifiers/bigquery/README.md, ci/cloudbuild/notifiers/bigquery/bigquery.yaml, ci/cloudbuild/notifiers/bigquery/deploy.sh
This PR adds adds a GCB notifier that runs as a Cloud Run service, consumes GCB pub/sub notifications, and writes them to a BigQuery table.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6211)
=> ci(gcb): add bigquery notifier

cmake/EnableCxxExceptions.cmake
Thanks to @MrMoose for cluing us to how this warning was more confusing than it needed to be (see #6202).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6218)
=> doc: clarify warnings about disabling exceptions

ci/cloudbuild/builds/integration.sh, ci/cloudbuild/fedora.Dockerfile, ci/cloudbuild/ubuntu-bionic.Dockerfile
Some of our emulators expect this path to be set, and it makes sense to
set it in the Dockerfile where the cloud SDK is installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6219)
=> ci(gcb): set CLOUD_SDK_LOCATION in Dockerfile

ci/cloudbuild/build.sh, ci/cloudbuild/cloudbuild.yaml
I'll need the PROJECT_ID in an upcoming PR. I don't need BUILD_ID yet,
but it seemed useful to pass along too.
PROJECT_ID shadowed a variable in the build.sh script, so I renamed the
flag arguments in the build.sh script to have a `_FLAG` suffix. The
`build.sh` changes are purely renames.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6222)
=> ci(gcb): pass PROJECT_ID and BUILD_ID to build scripts

.gitignore, ci/cloudbuild/triggers/bazel-clang-ci.yaml, ci/cloudbuild/triggers/bazel-clang.yaml, ci/cloudbuild/triggers/bazel-gcc-ci.yaml, ci/cloudbuild/triggers/bazel-gcc.yaml
We were ignoring all `bazel-*` files, which included some trigger files
that I thought were checked in. The triggers are active and running, but
apparently they weren't in git.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6223)
=> fix(ci): gitignore pattern that was too broad

ci/cloudbuild/triggers/bazel-clang-pr.yaml, ci/cloudbuild/triggers/bazel-gcc-pr.yaml
These triggers are currently active, but the trigger files weren't
committed to git due to an overly broad `.gitignore` file. That was
fixed in https://github.com/googleapis/google-cloud-cpp/pull/6223 and so
these files can be added now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6225)
=> ci(gcb): add missing bazel trigger files

ci/cloudbuild/builds/asan.sh, ci/cloudbuild/builds/integration.sh, ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/builds/tsan.sh, ci/cloudbuild/builds/ubsan.sh, ci/cloudbuild/builds/xsan.sh
Fixes #6179
Part of #6181
The basic idea of this PR is that the `builds/integration.sh` script was refactored into a `builds/lib/integration.sh` library, and the `args` and the `bazel_with_emulators` functionality was split into two functions. This will allow us to run the integration tests with emulators and against prod (in a future PR).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6227)
=> ci(gcb): run integration tests from sanitizer builds

ci/cloudbuild/builds/clang-tidy.sh, ci/cloudbuild/cloudbuild.yaml, ci/cloudbuild/fedora.Dockerfile, ci/cloudbuild/triggers/clang-tidy-pr.yaml
Fixes #6170
This PR starts using https://github.com/matus-chochlik/ctcache, which is
a clang-tidy cache, to speed up our clang-tidy builds. This PR also
re-enables clang-tidy for PR builds because they should be fast enough
now.
In my experiments using ctcache vs using no clang-tidy cache, I see
builds taking ~7% *longer* on clean full builds. This makes sense as the
cache needs to compute hashes, check for cache hits, etc. But on builds
with a populated `~/.cache/ctcache` I see builds completing ~50%
*faster*. I think these stats look good, and I think this is worth
trying.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6228)
=> ci(gcb): use ctcache to speed up clang-tidy builds

ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/fedora.Dockerfile
In order to verify that our installed artifacts work, this PR compiles
our quickstarts against our installed artifacts.
Part of #6163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6233)
=> ci(gcb): build quickstarts during install test

ci/cloudbuild/builds/demo-install.sh, ci/cloudbuild/demo-centos-7.Dockerfile, ci/cloudbuild/triggers/demo-centos-7-ci.yaml, ci/cloudbuild/triggers/demo-centos-7-pr.yaml
Part of #6163
This is the first example of how I plan to move what we currently call
"install" builds (defined in `ci/kokoro/install`) over to GCB where I
plan to call them "demo" builds. The idea is that we'll have a single
script called `demo-install.sh` (in this PR) that installs
`google-cloud-cpp`, and then tests the install by running the
quickstarts. We'll then have a number of `demo-<os>.Dockerfile` files
(`demo-centos-7.Dockerfile` is included in this PR), and a number of
trigger files, which associate a `demo-<os>` distro with the one
`demo-install.sh` script.
In subsequent PRs, I'll add more `demo-<os>.Dockerfile`s, and more
triggers for the other platforms.
Separately, I'll also update the packaging scripts to use these new
files for generating the `packaging.md` file.
Note …
=> ci(gcb): add demo-centos-7 install build

ci/cloudbuild/builds/demo-install.sh, ci/cloudbuild/demo-centos-8.Dockerfile, ci/cloudbuild/demo-debian-buster.Dockerfile, ci/cloudbuild/demo-debian-stretch.Dockerfile, ci/cloudbuild/demo-fedora.Dockerfile, ci/cloudbuild/demo-opensuse-leap.Dockerfile, ci/cloudbuild/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/demo-ubuntu-xenial.Dockerfile, ci/cloudbuild/triggers/demo-centos-8-ci.yaml, ci/cloudbuild/triggers/demo-centos-8-pr.yaml, ci/cloudbuild/triggers/demo-debian-buster-ci.yaml, ci/cloudbuild/triggers/demo-debian-buster-pr.yaml, ci/cloudbuild/triggers/demo-debian-stretch-ci.yaml, ci/cloudbuild/triggers/demo-debian-stretch-pr.yaml, ci/cloudbuild/triggers/demo-fedora-ci.yaml, ci/cloudbuild/triggers/demo-fedora-pr.yaml, ci/cloudbuild/triggers/demo-opensuse-leap-ci.yaml, ci/cloudbuild/triggers/demo-opensuse-leap-pr.yaml, ci/cloudbuild/triggers/demo-ubuntu-bionic-ci.yaml, ci/cloudbuild/triggers/demo-ubuntu-bionic-pr.yaml, ci/cloudbuild/triggers/demo-ubuntu-focal-ci.yaml, ci/cloudbuild/triggers/demo-ubuntu-focal-pr.yaml, ci/cloudbuild/triggers/demo-ubuntu-xenial-ci.yaml, ci/cloudbuild/triggers/demo-ubuntu-xenial-pr.yaml
Fixes: #6163
This PR adds "demo" builds (new parlance) for all the old "install" builds (old parlance).
This looks like a big PR, but it's pretty mechanical. Mostly copying the old "install" Dockerfiles, and generating new trigger yaml files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6245)
=> ci(gcb): add all remaining demo builds

CHANGELOG.md, CMakeLists.txt, ci/cloudbuild/builds/clang-tidy.sh, ci/kokoro/docker/build-in-docker-cmake.sh, ci/kokoro/install/Dockerfile.debian-buster, doc/packaging.md
Our `generator/` code is an implementation that our users will rarely,
if ever, need to build or use directly. So it seems it would be better
to not compile it by default in our CMake builds. This PR changes the
generator to not be build by default in CMake builds.
It also explicitly enables the generator in our clang-tidy builds
(kokoro and GCB) so that the generator is checked. All the sanitizer
builds use bazel so they will be unaffected.
This is technically a breaking change, but it's very unlikely to affect
anyone in practice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6243)
=> ci!: generator/ is no longer built by default in CMake

ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile
Fixes: #6247
`ldconfig` doesn't always add stuff in `/usr/local/lib` directories, so
in Dockerfiles when we install a bunch of stuff that might land in
`/usr/local`, we should be sure to run ldconfig on /usr/local before we
attempt to use those things (or expect pkg-config to find them).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6248)
=> fix(gcb): ldconfig /usr/local/lib after installing stuff

google/cloud/storage/examples/CMakeLists.txt, google/cloud/storage/examples/storage_auth_samples.cc, google/cloud/storage/examples/storage_examples.bzl, google/cloud/storage/oauth2/google_credentials.cc
My tests were wrong, this does not work in production. Fortunately they
were not used unless the service account keyfile was manually loaded.
This backports #6230 to the v1.26.x branch. Fixes #6231 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6238)
=> fix(storage): disable self-signed JWT authentication

google/cloud/storage/CMakeLists.txt, google/cloud/storage/bucket_test.cc, google/cloud/storage/client_bucket_acl_test.cc, google/cloud/storage/client_default_object_acl_test.cc, google/cloud/storage/client_notifications_test.cc, google/cloud/storage/client_object_acl_test.cc, google/cloud/storage/client_object_copy_test.cc, google/cloud/storage/client_service_account_test.cc, google/cloud/storage/client_sign_policy_document_test.cc, google/cloud/storage/client_sign_url_test.cc, google/cloud/storage/client_write_object_test.cc, google/cloud/storage/object_test.cc, google/cloud/storage/parallel_uploads_test.cc, google/cloud/storage/storage_client_testing.bzl, google/cloud/storage/testing/client_unit_test.cc, google/cloud/storage/testing/client_unit_test.h, google/cloud/storage/testing/mock_client.h
Not a lot of code saving, but will simplify the next change where I
want to deprecate the `storage::Client()` constructor from a
`std::shared_ptr<RawClient>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6256)
=> refactor(storage): common code for client unit tests

ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/builds/lib/quickstart.sh, ci/cloudbuild/builds/shared.sh, ci/cloudbuild/triggers/shared-ci.yaml, ci/cloudbuild/triggers/shared-pr.yaml, external/googleapis/CMakeLists.txt
Also fixed an issue where the pubsub protos were missing a needed dep.
This PR refactors the logic to run the CMake and Makefile quickstart
builds into a library, because it turns out that this is a useful way to
verify that our installed artifacts work, and we end up calling this
from a few places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6257)
=> ci(gcb): add shared library build

google/cloud/spanner/database_admin_connection_test.cc
Suppress the warning about leaking the mock stub until #4038
is fixed.
Fixes #6145.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6261)
=> chore(spanner): quash warning about a leaked mocked object

google/cloud/storage/benchmarks/throughput_experiment_test.cc, google/cloud/storage/client.cc, google/cloud/storage/client.h, google/cloud/storage/client_test.cc, google/cloud/storage/client_write_object_test.cc, google/cloud/storage/examples/storage_client_mock_samples.cc, google/cloud/storage/grpc_plugin.cc, google/cloud/storage/object_test.cc, google/cloud/storage/parallel_upload.h, google/cloud/storage/testing/mock_client.h, google/cloud/storage/testing/remove_stale_buckets_test.cc, google/cloud/storage/testing/retry_tests.h, google/cloud/storage/testing/storage_integration_test.cc, google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc, google/cloud/storage/tests/curl_sign_blob_integration_test.cc, google/cloud/storage/tests/object_resumable_write_integration_test.cc, google/cloud/storage/tests/object_write_streambuf_integration_test.cc
`storage::Client` has a number of functions that expose more details of
the implementation than they should, or are only intended for tests,
benchmarks, or to implement additional functionality in the library.
This change marks these functions as deprecated, and recommends what to
do instead. We also changed our tests, examples, and implementation to
use a helper in `google::cloud::internal` to access this functionality.
Part of the changes for #6161
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6258)
=> cleanup(storage): deprecate overly permissive functions

super/ExternalProjectHelper.cmake
CMake `message(WARNING "message to display")` uses a simple markup
language, where newlines in non-indented text are presumed to
delineate paragraphs that should be wrapped and separated. Avoid
that by adding a little indentation, so the text renders as a
single block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6265)
=> cleanup: avoid CMake warning-message markup

ci/kokoro/docker/build-in-docker-bazel.sh, ci/kokoro/docker/build-in-docker-cmake.sh, ci/kokoro/docker/build.sh, ci/lib/io.sh, google/cloud/storage/tools/run_emulator_utils.sh
Add `io::log_cmdline` for logging command execution. It prefixes
the command with `${PS4}`, just like `set -x` would in the shell.
This helps to delineate the command from normal output.
Also print the command in a bold typeface when possible, making
it even easier to distinguish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6264)
=> ci: introduce io::log_cmdline

ci/cloudbuild/builds/gcs-grpc.sh, ci/cloudbuild/triggers/gcs-grpc-ci.yaml, ci/cloudbuild/triggers/gcs-grpc-pr.yaml
From my understanding of the existing gcs-grpc build, I _think_ this is equivalent and testing the right things. However, is there a way for me to verify that the correct gcs + grpc logic/tests were run? Here's [output from a manual run](https://pantheon.corp.google.com/cloud-build/builds/3ff77a4e-3058-4134-8a22-8293cfdae02c?project=cloud-cpp-testing-resources) I did of this build in case this will show you whether or not the correct things ran.
Context: **current** `gcs-grpc` build:
https://github.com/googleapis/google-cloud-cpp/blob/21f3d910814fd9b5df5e511eecf3c141e2a3e1db/ci/kokoro/docker/build.sh#L278-L292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/626 …
=> ci(gcb): add gcs-grpc build

generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_logging_decorator_test.cc, google/cloud/bigtable/testing/mock_async_failing_rpc_factory.h, google/cloud/spanner/samples/mock_execute_query.cc, google/cloud/storage/examples/storage_client_mock_samples.cc
A small followup to #6263.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6269)
=> cleanup: use wildcard matcher (_) even more sparingly

ci/cloudbuild/build.sh, ci/cloudbuild/builds/coverage.sh, ci/cloudbuild/cloudbuild.yaml, ci/cloudbuild/triggers/coverage-ci.yaml, ci/cloudbuild/triggers/coverage-pr.yaml
This seems to be working in my tests. For now, it's configured to upload
coverage data to devjgm's personal codecov account at
https://app.codecov.io/gh/devjgm/google-cloud-cpp/. Once we see that
this build works and uploads coverage data correctly, we can change it
to use the _real_ token, which can be done in Secret Manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6270)
=> ci(gcb): enable coverage build

ci/cloudbuild/builds/coverage.sh
The coverage build [failed][failure-log] with
```
lcov: ERROR: no valid records found in tracefile /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/generator/integration_tests/generator_integration_test/coverage.dat
```
I'm not sure why that failed, but in looking into it, I noticed I was
missing some needed flags for coverage, so maybe this is the problem and
will fix it. Note, that I was unable to reproduce the failure in any of
my tests, so I'm not sure if this will fix it, but I think we need these
flags anyway.
[failure-log]: https://pantheon.corp.google.com/cloud-build/builds;region=global/5f4c6f26-4330-44bd-8415-b75c43be2276;step=2?project=cloud-cpp-testing-resources
--- …
=> ci(gcb): fix coverage build (hopefully)

ci/cloudbuild/trigger.sh, ci/cloudbuild/triggers/coverage-ci.yaml, ci/cloudbuild/triggers/coverage-pr.yaml, ci/cloudbuild/triggers/cxx17-ci.yaml, ci/cloudbuild/triggers/cxx17-pr.yaml, ci/cloudbuild/triggers/gcs-grpc-ci.yaml, ci/cloudbuild/triggers/gcs-grpc-pr.yaml, ci/cloudbuild/triggers/libcxx-ci.yaml, ci/cloudbuild/triggers/libcxx-pr.yaml, ci/cloudbuild/triggers/msan-ci.yaml, ci/cloudbuild/triggers/msan-pr.yaml, ci/cloudbuild/triggers/noex-ci.yaml, ci/cloudbuild/triggers/noex-pr.yaml, ci/cloudbuild/triggers/shared-ci.yaml, ci/cloudbuild/triggers/shared-pr.yaml
Also fix the `trigger.sh` script that was generating these files w/o the
`_TRIGGER_TYPE` set correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6275)
=> ci(gcb): fix missing trigger type in some builds

ci/cloudbuild/builds/lib/quickstart.sh
Fixes: #6278
This is needed to find the shared libraries that the Makefile
quickstarts will need to link with.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6280)
=> ci(gcb): set LD_LIBRARY_PATH when running `quickstart`

google/cloud/storage/CMakeLists.txt, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/client.cc, google/cloud/storage/client.h, google/cloud/storage/client_options.cc, google/cloud/storage/client_options.h, google/cloud/storage/client_options_test.cc, google/cloud/storage/examples/storage_grpc_samples.cc, google/cloud/storage/google_cloud_cpp_storage.bzl, google/cloud/storage/grpc_plugin.cc, google/cloud/storage/grpc_plugin.h, google/cloud/storage/idempotency_policy.h, google/cloud/storage/internal/curl_client.h, google/cloud/storage/internal/curl_client_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_failures_test.cc, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/internal/hybrid_client.h, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client.h, google/cloud/storage/internal/retry_client_test.cc, google/cloud/storage/internal/retry_object_read_source_test.cc, google/cloud/storage/options.h, google/cloud/storage/testing/storage_integration_test.cc
Change the classes derived from `RawClient` to use a `g::c::Options`
object as its only configuration parameter. These classes assume the
object is fully initialized, and contains the default values if needed.
Add options to pass the retry, backoff, and idempotency policies as
option values too.
Part of the changes for #6161
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6282)
=> refactor(storage): use g::c::Options in RawClients

ci/cloudbuild/build.sh, ci/cloudbuild/cloudbuild.yaml
By default GCB writes logs to a bucket they GCB controls and that we
have no access to. This PR changes our builds to write to our own
bucket, which will give us the ability to control the lifetime and
permissions for the build logs.
NOTE: This PR doesn't change anything wrt to log visibility or anything. This PR simply makes our build logs live in our bucket that we control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6284)
=> ci(gcb): write logs to our own bucket

ci/cloudbuild/build.sh, ci/cloudbuild/cloudbuild.yaml
`_CACHE_TYPE` somewhat made sense when it was only used for the caching
URLs, but now that it's also used for the logging bucket directory it
needs a cache-agnostic name. This name seems a bit better, but I'm open
to other names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6285)
=> ci(gcb): rename _CACHE_TYPE -> _TRIGGER_SOURCE

google/cloud/storage/emulator/database.py
Object list calls from the Go library weren't working against
the emulator because the endOffset is sent as an empty string
by the library. This matches the actual service behavior for
this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6296)
=> test(storage): fix emulator offset handling

generator/generate-libraries.sh
Switch generate-libraries build to use new standalone binary for the microgenerator and the new textproto config file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6290)
=> refactor(generator): generate libraries using generator config file

ci/cloudbuild/builds/log-linker.sh, ci/cloudbuild/cloudbuild.yaml, ci/cloudbuild/dockerfiles/debian-github.Dockerfile, ci/cloudbuild/triggers/log-linker-pr.yaml
Adds a build script that posts a comment to PRs with a link to the GCB logs. One of the link will (soon) contain publicly accessible logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6292)
=> ci(gcb): add the log-linker script

google/cloud/storage/benchmarks/throughput_experiment.cc
Decouple the initialization of the `grpc::Channel` objects used for
`*RawGrpc` experiments. The previous approach used implementation
details for the GCS+gRPC plugin, which are about to change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6297)
=> cleanup(storage): simplify RawGrpc initialization

ci/cloudbuild/build.sh, ci/cloudbuild/builds/log-linker.sh, ci/cloudbuild/cloudbuild.yaml
PR and CI builds will write build logs to `gs://cloud-cpp-community-publiclogs`, which we will (soon) be able to make publicly viewable.
Manually triggered builds will continue to be written to `${PROJECT_ID}_cloudbuild`, which means that manually triggered build logs will NOT be public, as they are today.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6298)
=> ci(gcb): write build logs to `cloud-cpp-community-publiclogs` bucket

ci/cloudbuild/builds/check-abi.sh
Oops. I introduced this bug at the last minute before sending my
previous PR for review. The bug was introduced in https://github.com/googleapis/google-cloud-cpp/pull/6314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6315)
=> ci(gcb): fix bug in check-abi

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/grpc_access_token_authentication.cc, google/cloud/internal/grpc_access_token_authentication.h, google/cloud/internal/grpc_access_token_authentication_test.cc, google/cloud/internal/grpc_channel_credentials_authentication.cc, google/cloud/internal/grpc_channel_credentials_authentication.h, google/cloud/internal/grpc_channel_credentials_authentication_test.cc, google/cloud/internal/unified_grpc_credentials.cc, google/cloud/internal/unified_grpc_credentials.h, google/cloud/internal/unified_grpc_credentials_test.cc
To use the unified authentication client credentials with gRPC we need
to map said credentials to the gRPC authentication abstractions. These
come in two flavors:
- For short-lived tokens (such as access tokens), one needs to create a
`grpc::CallCredentials` object and pass it to `grpc::ClientContext`
before each call.
- For long-lived credentials (e.g. `grpc::GoogleDefaultCredentials`) the
credentials are associated with the gRPC channel and gRPC takes care
of refreshing them.
This suggests that we need an abstraction to (a) create properly
configured channels when the unified credentials can be represented by a
`grpc::ChannelCredentials`, and (b) create (and if necessary cache) the
right `grpc::CallCredentials` and then set them before each RPC.
This change introduces the first versions …
=> feat(common): support unified credentials in gRPC

ci/cloudbuild/build.sh
Our GCB builds expect secrets for the `CODECOV_TOKEN` and the
`LOG_LINKER_PAT`. These exist in our main GCB project, but not in our
personal projects. This PR creates these secrets with empty data if
they don't already exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6316)
=> ci(gcb): create secrets if necessary

ci/cloudbuild/builds/check-abi.sh
This PR is my proposal for merging the behavior of the old (kokoro)
"update-abi" build behavior _into_ the new (GCB) "check-abi" build.
Specifically, this change makes GCB's `check-abi` build always replace
the "expected" ABI dump files in `ci/test-abi/*.gz` with the newly
generated dumps that were created for the `check-abi` build, and it
leaves these new `*.gz` files edited in the local repo. If the user
wants to update the ABI they only need to create a new PR w/ the changed
`*.gz` files. If they don't want to update the `*.gz` files, they can
just `git restore ci/test-abi`. In both cases, the return value of the
`check-abi` build is successful if there were no ABI incompatibilities
and an error if there were incompatibilities. And again, whether or not
to check-in the changed `.gz` …
=> ci(gcb): add 'update abi' behavior to 'check-abi'

ci/cloudbuild/builds/clang-tidy.sh
We need to enable the GCS+gRPC plugin on the clang-tidy build or the
files for it do not get "tidied".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6324)
=> ci: clang-tidy the GCS+gRPC plugin code

google/cloud/internal/grpc_access_token_authentication_test.cc, google/cloud/internal/grpc_channel_credentials_authentication_test.cc, google/cloud/internal/unified_grpc_credentials_test.cc, google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/grpc_object_read_source.h, google/cloud/storage/internal/grpc_object_read_source_test.cc, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/storage_client_integration_tests.bzl, google/cloud/storage/tests/unified_credentials_integration_test.cc
Modify the storage library to support the unified authentication client
(aka `google::cloud::{internal::}Credentials`). This is not yet exposed
in the public API, but applications will be able to initialize a
`gcs::Client` with a single credential, and it will work for both REST
and gRPC. Moreover, this supports credentials that dynamically create
access tokens, which we could not do before.
This is a backwards compatible change, using `oauth2::Credentials` (or
`grpc::ChannelCredentials` for the GCS+gRPC plugin) still works.
Fixes #3105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6323)
=> feat(storage): use the unified authentication client

ci/cloudbuild/builds/clang-tidy.sh, ci/cloudbuild/builds/cmake-clang.sh, ci/cloudbuild/builds/cmake-gcc.sh, ci/cloudbuild/builds/cxx17.sh, ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/builds/noex.sh, ci/cloudbuild/builds/shared.sh
Comparing with the [last](https://pantheon.corp.google.com/cloud-build/builds;region=global/0cf38447-5b73-40bd-97b4-862a47d3a4fa;step=2?project=cloud-cpp-testing-resources) clang-tidy-pr build (which actually executed the integration tests).
The test time changed:
| Stage | Before | After |
| ------ | -------- | ------ |
| Unit | 58s | 12s |
| Pub/Sub | 19s | 10s |
| Bigtable | 19s | 6s |
| Storage | 176s | 84s |
| Spanner | 130s | 46s |
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6334)
=> ci: parallelize unit and integration test with CTest

ci/cloudbuild/build.sh, ci/cloudbuild/builds/publish-docs.sh, ci/cloudbuild/cloudbuild.yaml, ci/cloudbuild/triggers/publish-docs-ci.yaml, ci/cloudbuild/triggers/publish-docs-pr.yaml
Fixes: #6174
This build will publish docs to the public site (googleapis.dev) on all
post-submit CI builds. For PR builds, docs will be published to the
staging.googleapis.dev site. When a CI build is triggered for a release
branch, docs will be published with the releases version number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6340)
=> ci(gcb): add publish-docs build

ci/cloudbuild/builds/scan-build.sh
Fixes: #6345
This is a build that we may want to run sometimes by hand, and so here's
the build script for it. At this point, there's no build trigger for
this build, though we could add one if it seems useful. For now, this
build exists so we don't forget how to run a scan-build over our code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6356)
=> ci(gcb): add scan-build but no trigger

.github/renovate.json, renovate.json
* Tidy up top-level directory.
* Ignore `com_github_googleapis_googleapis` because it should be kept in sync with CMake.
Part of the work for #6346
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6359)
=> ci: tell Renovate to ignore googleapis/googleapis

ci/cloudbuild/builds/checkers.sh
Much like how the checkers build formats files and leaves the edited
files in place, the markdown files will now be automatically generated
by the checkers build. Any result diffs will result in a build break
(as before), but now the edited files will be left in place so that the
user doesn't need to do a second step of manually running the generator.
With this change, once we stop kokoro, we can also remove
`ci/check-markdown.sh`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6369)
=> ci(gcb): checkers build generates markdown

ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/builds/demo-install.sh, ci/cloudbuild/builds/lib/quickstart.sh, ci/cloudbuild/builds/shared.sh
This build tests CMake installs of the `google_cloud_cpp_development`
and `google_cloud_cpp_runtime` components. The essence of the test is
that it installs the "development" component, compiles the quickstart
programs, then it deletes the entire dev install, then installs _only_
the "runtime" component, then runs the quickstart programs. The
quickstarts should work with only the runtime component installed.
This PR splits the previous `quickstart::run_cmake_and_make` into two
functions: `quickstart::build_cmake_and_make` and
`quickstart::run_cmake_and_make`. This way we can execute previously
compiled quickstart binaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google- …
=> ci(gcb): test component installs

.github/renovate.json
Part of the work for #6346.
I am not 100% sure this works. I managed to run the `renovate` CLI locally, and the logs look promising, but there is no way to tell (I think) until we let the robot create some PRs.  I disabled the normal `docker` updates because they update the image versions, and I do not think we want that in our case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6364)
=> ci: automatically update Dockerfiles with Renovate

google/cloud/spanner/internal/defaults_test.cc
Clear any prevailing `GOOGLE_CLOUD_CPP_SPANNER_DEFAULT_ENDPOINT`
setting when testing `spanner_internal::Default{,Admin}Options()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6373)
=> test(spanner): isolate unit test from prevailing environment

ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile
Use `tar --strip-components=1` to avoid repeating the version number.
Part of the work for #6346
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6376)
=> ci: make Dockerfiles easier to update

ci/generate-markdown/dockerfile2markdown.sh, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.fedora, ci/kokoro/install/Dockerfile.fedora-components, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-focal, ci/kokoro/install/Dockerfile.ubuntu-xenial, doc/packaging.md
I neglected these Dockefiles in my similar PR for `ci/cloudbuild`
because they are going to be retired "soon". However, we will need to
update the `doc/packaging.md` file at that time, and will need to update
the scripts to generate this document too. Seems easier to do now while
the changes are fresh in my mind.
Part of the work for #6346
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6379)
=> ci: make install Dockerfiles easier to update

google/cloud/internal/credentials.cc, google/cloud/internal/credentials.h, google/cloud/internal/credentials_test.cc, google/cloud/internal/grpc_access_token_authentication.cc, google/cloud/internal/grpc_access_token_authentication.h, google/cloud/internal/grpc_access_token_authentication_test.cc, google/cloud/internal/unified_grpc_credentials.cc, google/cloud/storage/internal/access_token_credentials.cc, google/cloud/storage/internal/access_token_credentials.h, google/cloud/storage/internal/access_token_credentials_test.cc, google/cloud/storage/internal/unified_rest_credentials.cc, google/cloud/storage/internal/unified_rest_credentials_test.cc, google/cloud/storage/tests/unified_credentials_integration_test.cc
I think adding `DynamicAccessTokenCredentials` was premature, maybe
we will need something like it later, but it seems that for credentials that
create access tokens dynamically the APIs needed by gRPC and REST
are simply too different.
Part of the work for #6310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6387)
=> cleanup: remove support for dynamic access token

ci/cloudbuild/builds/cmake-deps.sh, ci/cloudbuild/builds/cmake-oldest-deps.sh, ci/cloudbuild/dockerfiles/fedora.Dockerfile, ci/cloudbuild/triggers/cmake-oldest-deps-ci.yaml, ci/cloudbuild/triggers/cmake-oldest-deps-pr.yaml, ci/etc/oldest-deps/vcpkg.json
This build compiles with older versions of each dependency. Its only
purpose is to verify compilation (and basic testing), so we only run
this in one platform. I used vcpkg to fetch the older versions of the
deps, including their dependencies at the time.
The only magic number is the `vcpkg` baseline, which is obtained by
looking at the history of:
https://github.com/microsoft/vcpkg/blob/master/versions/baseline.json
and finding the commit that has all the versions we want. In this build
vcpkg reports:
```
abseil[core]:x64-linux -> 2020-09-23#3
benchmark[core]:x64-linux -> 1.5.2
c-ares[core]:x64-linux -> 1.17.1
crc32c[core]:x64-linux -> 1.1.1
curl[core,non-http,openssl,ssl]:x64-linux -> 7.74.0#3
grpc[core]:x64-linux -> 1.33.1#3
gtest[core]:x64-linux -> 1.10.0#4 …
```
=> ci: build with older versions of each dep

google/cloud/internal/grpc_access_token_authentication.cc, google/cloud/internal/grpc_access_token_authentication.h, google/cloud/internal/grpc_channel_credentials_authentication.cc, google/cloud/internal/grpc_channel_credentials_authentication.h, google/cloud/internal/unified_grpc_credentials.h
Supporting asynchronous gRPC requests requires that fetching any
`grpc::CallCredentials` [1] asynchronously too, or the application would
experience blocking while starting the asynchronous RPC.
As an optimization I will introduce an optional `${service}Auth` layer,
analogous to `${service}Logging` or `${service}Metadata`, this is to
save the relatively expensive creation of a future when the type of
credentials do not require them.
This change does not include any integration tests, those will come
later as they require even more infrastructure.
Fixes #6310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6391)
=> feat(common): support asynchronous RPCs in GrpcAuthenticationStrategy

google/cloud/storage/tests/object_file_multi_threaded_test.cc, google/cloud/storage/tools/run_emulator_utils.sh
The emulator was running with only 10 threads. This does not seem like
enough on CI machines with 32 cores, where the 60-odd integration tests
run in parallel, and some of these integration tests ran 128 threads.
I also reduced the number of parallel threads in the
object_file_multi_threaded_test.cc, it just seemed like too many threads
now that the machines are much larger.
I think this fixes #6399
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6403)
=> test: avoid overwhelming the emulator

ci/cloudbuild/dockerfiles/fedora.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-xenial.Dockerfile, external/googleapis/CMakeLists.txt
Similar to #6104, where we added the "patch" binary to the kokoro
docker images to support patching of googleapis after download.
Also update the CMake `PATCH_COMMAND` example to reflect the new
cloudbuild mount point for `${PROJECT_ROOT}`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6407)
=> ci(gcb): add patch to cloudbuild docker images

ci/cloudbuild/notifiers/logs/README.md, ci/cloudbuild/notifiers/logs/function/CMakeLists.txt, ci/cloudbuild/notifiers/logs/function/function.cc, ci/cloudbuild/notifiers/logs/function/vcpkg.json
Store some key information about each build in the log metadata, that
way we can display it when we scan the logs. We can also include the
command needed to reproduce the build locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6408)
=> ci: improve build logs summary

ci/cloudbuild/build.sh
I suggested using a read-only mount, but one needs write permissions to
run the Pub/Sub emulator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6413)
=> ci: fix mount point for gcloud config

ci/cloudbuild/builds/check-api.sh, ci/cloudbuild/triggers/check-api-ci.yaml, ci/cloudbuild/triggers/check-api-pr.yaml, release/README.md
Note that some places I left a**b**i in the name. For example, the dump
files are really a**b**i dump files, even though we're only using them
to check for a**p**i compliance. But this rename better reflects what
we're actually trying to test with this build: that our source-level
a**p**i isn't broken.
If this mixed a**b**i vs a**p**i naming seems too confusing, I'd be
happy to drop this PR and keep the old a**b**i naming. Possibly even go
all the way the other direction toward a**p**i would be OK too, if
someone else preferred that naming.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6422)
=> ci: rename check-abi -> check-api

ci/cloudbuild/build.sh, ci/cloudbuild/builds/lib/integration.sh, google/cloud/spanner/internal/defaults.cc
Teaches `build.sh` to forward all `GOOGLE_CLOUD_*` environment variables to the docker container, which
allows us to set/override things in build scripts, such as `GOOGLE_CLOUD_CPP_SPANNER_DEFAULT_ENDPOINT`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6431)
=> ci: forward GOOGLE_CLOUD_* env to docker

.github/trusted-contribution.yml
The `trusted-contribution-gcf` robot can help start the Kokoro builds.
We thought it would help with GCB builds too, but it did not: GCB
ignores its comments. Until we get this working the comments are just
noise, so let's remove them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6434)
=> chore: disable trusted-contribution-gcf comments

google/cloud/internal/async_retry_loop_test.cc
The expectation in `AsyncRetryLoopTest.ExhaustedDuringBackoff` assumes
that the retry loop will call the functor before the retry policy is
exhausted.  This can't be (easily) guaranteed, so let's just extend
the retry time limit a little in order to increase the probability
that the functor is called at least once.
Fixes #6266.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6436)
=> test(common): reduce timing flakiness in async_retry_loop test

google/cloud/internal/credentials.cc, google/cloud/internal/credentials.h, google/cloud/internal/credentials_test.cc, google/cloud/internal/grpc_impersonate_service_account.cc, google/cloud/internal/grpc_impersonate_service_account.h, google/cloud/internal/grpc_impersonate_service_account_integration_test.cc
This introduces a unified representation for service account
impersonation credentials. Service account impersonation credentials
allow a program to run with a given set of credentials (the base
credentials), but make RPCs using the credentials of a target service
account. This is often used to delegate billing to another service
account, or to support some forms of multi-tenancy.
Part of the changes for #6309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6429)
=> feat(common): credentials for service account impersonation

google/cloud/storage/client.h, google/cloud/storage/client_test.cc
I deprecated some constructors (but did not remove them), carefully
change our code to not use them, but the implementation was broken.
Thanks to @devbww for noticing the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6439)
=> fix(storage): missing implementation for constructor

ci/cloudbuild/builds/lib/integration.sh
The Bigtable emulator crashes from time to time. This slows down the
tests, and makes it appear as-if the tests are "hanging". Moving these
tests to the end makes it easier to create PRs when the changes do not
affect Bigtable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6442)
=> cleanup: run bigtable integration tests last

google/cloud/storage/tests/bucket_integration_test.cc, google/cloud/storage/tests/object_list_objects_versions_integration_test.cc
Avoid using a shared bucket for tests that depend on the metageneration
being stable. Avoid changing the metadata for a bucket when we can use a
new bucket for the purpose.
Fixes #6260
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6445)
=> test(storage): deflake bucket integration test

google/cloud/storage/tests/curl_download_request_integration_test.cc
Seems like my first attempt to introduce a retry loop also introduced a
bug.
Fixes #5954
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6452)
=> test(storage): deflake integration test

ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/cloudbuild.yaml, ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile, ci/cloudbuild/dockerfiles/fedora.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic.Dockerfile
Avoids duplicating the dependencies in Dockerfiles and the `requirements.txt` files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6457)
=> ci: install emulator dependencies using requirements file

google/cloud/storage/emulator/README.md, google/cloud/storage/emulator/gcs/bucket.py, google/cloud/storage/emulator/requirements.txt, google/cloud/storage/emulator/tests/test_gcs.py, google/cloud/storage/emulator/tests/test_utils.py, google/cloud/storage/emulator/utils/common.py
I saw string manipulation to handle multipart and found MultipartDecoder class as a potential replacement supported in `requests-toolbelt`.
Additional changes:
1. Updated emulator README.md on how to run test.
2. Ran linter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6453)
=> fix(storage): update emulator to use MultipartDecoder

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/streaming_write_rpc.cc, google/cloud/internal/streaming_write_rpc.h, google/cloud/internal/streaming_write_rpc_test.cc
Introduce a wrapper for streaming write RPCs. This is similar to
`google::cloud::internal::StreamingReadRpc<>`, with some important
differences:
- There is an extra template parameter to represent the final response.
Note that this value only makes sense when the operation completes
successfully.
- There is a `WritesDone()` member function to close the stream, which
returns a `StatusOr<ResponseType>`. Sometimes the application wants
to close the stream without sending more data.
Part of the changes for #6309 but really all of GUAC for the storage library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6455)
=> feat(common): a wrapper for streaming write RPCs

google/cloud/bigtable/filters_test.cc, google/cloud/bigtable/iam_binding.cc, google/cloud/bigtable/instance_admin_test.cc, google/cloud/bigtable/internal/async_poll_op_test.cc, google/cloud/bigtable/mutation_batcher_test.cc, google/cloud/bigtable/table_admin_test.cc, google/cloud/bigtable/table_config_test.cc, google/cloud/bigtable/table_readmodifywriterow_test.cc, google/cloud/bigtable/testing/mock_async_failing_rpc_factory.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6468)
=> cleanup(bigtable): prefer proto matchers over MessageDifferencer

google/cloud/storage/emulator/emulator.py, google/cloud/storage/emulator/tests/test_utils.py, google/cloud/storage/emulator/utils/__init__.py, google/cloud/storage/emulator/utils/handle_gzip.py
Adding a middleware to decompress request bodies that are gzip'd which is used by Go and Java from integration testing against the emulator. 
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/3446
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6472)
=> fix(storage): support gzip request body in emulator

google/cloud/storage/emulator/emulator.py, google/cloud/storage/emulator/tests/test_utils.py, google/cloud/storage/emulator/utils/common.py, google/cloud/storage/emulator/utils/error.py
Cloud Storage supports an override header `X-Http-Method-Override` for PATCH requests over POST and the Java Storage library uses it. Wow. This adds support to the Storage emulator as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6474)
=> feat(storage): support method overrides in emulator

google/cloud/internal/streaming_read_rpc.h, google/cloud/internal/streaming_read_rpc_test.cc, google/cloud/internal/streaming_write_rpc.h, google/cloud/internal/streaming_write_rpc_test.cc
This is part of a larger refactoring in the GCS+gRPC plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6473)
=> feat(common): streaming RPCs that always fail

google/cloud/spanner/testing/pick_random_instance.cc
The Spanner-emulator `InstanceAdminClient::ListInstances()` does
not heed the `filter` parameter to restrict the set of instances
included in the response.  This meant that `PickRandomInstance()`
could return an ephemeral instance created, and soon to be deleted,
by a concurrent test.  And that leads to flakiness at best.
So, repeat the name filtering of instances in responses received
from the emulator.  And now that we are adding that check, make
an unexpected name from a real server return an error.
Fixes #6471.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6478)
=> test(spanner): PickRandomInstance

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/grpc_object_read_source.h, google/cloud/storage/internal/grpc_object_read_source_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session.cc, google/cloud/storage/internal/grpc_resumable_upload_session.h, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc
Use the `google::cloud::internal::Streaming{Read,Write}Rpc` wrappers,
they are (allegedly) easier to mock and use. I will be splitting the
`storage::internal::GrpcClient` class even more in a future PR, and this
change makes that easier.
Part of the work for #6309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6484)
=> refactor(storage): use streaming RPC wrappers

google/cloud/storage/CMakeLists.txt, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/storage_auth.cc, google/cloud/storage/internal/storage_auth.h, google/cloud/storage/internal/storage_auth_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/storage_client_grpc_unit_tests.bzl, google/cloud/storage/storage_client_testing.bzl, google/cloud/storage/testing/mock_storage_stub.h
Separate the wrappers around the gRPC code to its own file. That makes
it easier to add decorators in the style of other gRPC-based libraries,
particularly it is easier to add the auth decorator, which should be
used only when needed.
Part of the work for #6309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6485)
=> refactor(storage): split gRPC Client vs. Stub

google/cloud/bigtable/tests/data_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6491)
=> cleanup(bigtable): fix clang-tidy-12 warnings

ci/cloudbuild/dockerfiles/ubuntu-focal.Dockerfile, ci/cloudbuild/triggers/cmake-oldest-deps-ci.yaml, ci/cloudbuild/triggers/cmake-oldest-deps-pr.yaml
Picking Fedora to run the `cmake-oldest-deps` build was not a great idea
(it was mine). Fedora moves fast, picking new compilers very 6 months,
and dropping support every 12 months. We want this build to use
something more stable. This change moves the build to Ubuntu:20.04
(Focal Fossa), it was released in 2020-04, should remain supported until
2025-04. Most likely we will be forced to update the minimum version for
our deps before then.
In case you are wondering: yes, the older versions of our deps do not
compile with Fedora:34.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6497)
=> ci: move `cmake-oldest-deps` build to Ubuntu:20.04

google/cloud/internal/credentials.h, google/cloud/internal/credentials_test.cc, google/cloud/internal/grpc_impersonate_service_account.cc, google/cloud/internal/unified_grpc_credentials.cc, google/cloud/internal/unified_grpc_credentials.h, google/cloud/internal/unified_grpc_credentials_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_failures_test.cc, google/cloud/storage/internal/grpc_client_object_request_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc, google/cloud/storage/internal/unified_rest_credentials.cc, google/cloud/storage/tests/unified_credentials_integration_test.cc
This weaves the support for service account impersonation through the
gRPC and REST adapters. This change includes an integration test for
`google::cloud::storage` using this new credential type.
Part of the work for #6309, some cleanup afterwards and I can close it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6488)
=> feat(storage): support service account impersonation

google/cloud/storage/internal/curl_handle.h
I think the compiler caught me doing naughty things with
`std::nullptr_t`, `nullptr`, and C functions consuming varargs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6501)
=> fix(storage): compile with GCC 11 in C++17 mode

ci/cloudbuild/builds/publish-docs.sh
Uses a less offensive term, and a clearer term since the docs are indeed
for the newest unreleased version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6515)
=> ci: rename publish docs head version to HEAD

ci/custom-words.txt, google/cloud/internal/credentials.cc, google/cloud/internal/credentials.h, google/cloud/internal/credentials_test.cc, google/cloud/internal/grpc_impersonate_service_account_integration_test.cc, google/cloud/storage/internal/impersonate_service_account_credentials_test.cc
Also documented the public APIs, and fixed the return type for the
service account impersonation case. The APIs are still in `internal::`,
but it will be easier to move them.
This one fixes #6309 for realsies :face_with_head_bandage:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6500)
=> cleanup: consolidate unified credentials public APIs

google/cloud/internal/credentials.cc, google/cloud/internal/credentials.h, google/cloud/internal/credentials_test.cc, google/cloud/internal/unified_grpc_credentials.cc, google/cloud/internal/unified_grpc_credentials_test.cc, google/cloud/storage/internal/unified_rest_credentials.cc, google/cloud/storage/internal/unified_rest_credentials_test.cc
We use insecure credentials to run integration tests against the
emulators, or to run unit tests that need to initialize a (maybe mocked)
client. This change introduces a common way to require such credentials
for both REST-based and gRPC-based libraries.
Fixes #6462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6518)
=> feat: implement unified insecure credentials

ci/cloudbuild/builds/tsan.sh, ci/cloudbuild/triggers/tsan-ci.yaml, ci/cloudbuild/triggers/tsan-pr.yaml
Part of the work for #6524
Manual [test log](https://console.cloud.google.com/cloud-build/builds;region=global/b5bf8568-629c-4698-b657-c7bbdb4cedec;tab=detail?project=cloud-cpp-testing-resources)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6525)
=> ci: move tsan build to Fedora:34

CMakeLists.txt
Fixes: #6541
I introduced this bug in https://github.com/googleapis/google-cloud-cpp/pull/6243
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6542)
=> fix: cmake build generator when requested

google/cloud/spanner/read_partition.h
Quash "no matching class member found" Doxygen warning for
`google::cloud::spanner::ReadPartition` constructor.
Part of #6543.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6548)
=> cleanup(spanner): quash Doxygen warning

google/cloud/spanner/samples/samples.cc
This will allow for sample commands that want to modify `argv`,
by consuming options for example, before using the argument values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6550)
=> cleanup(spanner): pass argv to run-once commands by (moved) value

CMakeLists.txt, ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/builds/demo-install.sh, ci/generate-markdown/generate-packaging.sh, doc/packaging.md, generator/CMakeLists.txt, generator/integration_tests/CMakeLists.txt, google/cloud/bigtable/CMakeLists.txt, google/cloud/iam/CMakeLists.txt, google/cloud/pubsub/CMakeLists.txt, google/cloud/spanner/CMakeLists.txt, google/cloud/storage/CMakeLists.txt
Package maintainers may want to disable compilation of benchmarks,
integration tests, samples, etc. They do not install those, so it is
just wasted time for them and the downstreams users for source-based
package systems (e.g. vcpkg).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6559)
=> feat: make benchmarks and samples optional

ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, doc/packaging.md
Add the patch tool to additional docker images, for cases where
it might be needed to update downloaded source in a demo build.
This is only intended for use when developing a new feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6554)
=> chore: add patch tool to more docker images

cmake/GoogleCloudCppCommon.cmake, google/cloud/CMakeLists.txt, google/cloud/bigquery/CMakeLists.txt, google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/table_admin.h, google/cloud/firestore/CMakeLists.txt, google/cloud/iam/CMakeLists.txt, google/cloud/logging/CMakeLists.txt, google/cloud/pubsub/CMakeLists.txt, google/cloud/spanner/CMakeLists.txt, google/cloud/storage/CMakeLists.txt, google/cloud/storage/grpc_plugin.h, google/cloud/stream_range.h
The main fix in here is predefining several macros that our code uses
that confuse doxygen. I predefine them to noop value or some sensible
and simple value. This fixes most of the errors.
Part of: https://github.com/googleapis/google-cloud-cpp/issues/6543
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6563)
=> ci: fix several doxygen errors

CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6562)
=> fix: correct CMake variable to disable examples

google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh, google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
Instead of using one of the examples to create a bucket in the emulator,
use `curl(1)`.
Fixes #6533
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6567)
=> ci: simplify storage CI script

CMakeLists.txt
`GOOGLE_CLOUD_CPP_ENABLE_EXAMPLES` is dependent on
`GOOGLE_CLOUD_CPP_ENABLE_CXX_EXCEPTIONS`, but that was unset prior to
its first use, so `GOOGLE_CLOUD_CPP_ENABLE_EXAMPLES` was never getting
enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6571)
=> fix: GOOGLE_CLOUD_CPP_ENABLE_EXAMPLES depends condition

ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/notifiers/logs/README.md, ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh, ci/kokoro/macos/build-bazel.sh, ci/kokoro/macos/build-cmake.sh, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-cmake.ps1, google/cloud/examples/BUILD, google/cloud/examples/CMakeLists.txt, google/cloud/examples/README.md, google/cloud/examples/grpc_credential_types.cc, google/cloud/examples/hello_world_http/CMakeLists.txt, google/cloud/examples/hello_world_http/hello_world_http.cc, google/cloud/examples/hello_world_http/vcpkg.json
Use the `GenerateIdToken()` method in
`google::cloud::iam::IAMCredentialsClient`, and shows how to use the
returned value to make a HTTP request to a service in Cloud Run.
Fixes #6481 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6569)
=> feat: example using identity tokens

ci/cloudbuild/cloudbuild.yaml
On post-submit (ci) builds, we have no `${_PR_NUBMER}`, so we see
non-fatal errors in the logs like:
```
+ gcloud builds list --limit 1 '--format=value(id)' --filter 'tags=pr AND tags= AND tags=publish-docs AND substitutions.COMMIT_SHA != 2f69122b4f2b20c85e2e55c1b2c753c21a85d912 AND create_time > 2021-05-14T16:23:37.115578690Z'
ERROR: (gcloud.builds.list) Logical operator not expected [tags=pr AND tags= *HERE* AND tags=publish-docs AND substitutions.COMMIT_SHA != 2f69122b4f2b20c85e2e55c1b2c753c21a85d912 AND create_time > 2021-05-14T16:23:37.115578690Z].
+ exit 0
```
This PR will avoid those errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6572)
=> fix(ci): ci builds don't have a PR number

google/cloud/CMakeLists.txt
To include this in doxygen output we'll need to fetch the functions
framework dep, which we could do, but that would be a big-ish change for
doxygen. Maybe we can consider that later, but for now, I think
excluding this from doxygen sounds better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6576)
=> ci: exclude hello_world_http from doxygen

google/cloud/completion_queue_test.cc, google/cloud/testing_util/mock_async_response_reader.h
This is the same story as ee82393b. I didn't realize that there were two
other copies of this class.
@coryan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6590)
=> cleanup: prevent behavior change from a gRPC change

google/cloud/storage/CMakeLists.txt, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl
This will make it easier to use the plugin in applications and
benchmarks, so far we have been using ad-hoc functions to create
separate channels in each thread or some similar hack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6584)
=> feat(storage): round-robin stub for GCS+gRPC

ci/cloudbuild/builds/lib/integration.sh, google/cloud/examples/BUILD, google/cloud/examples/CMakeLists.txt, google/cloud/examples/README.md, google/cloud/examples/grpc_credential_types.cc, google/cloud/examples/hello_world_grpc/.dockerignore, google/cloud/examples/hello_world_grpc/CMakeLists.txt, google/cloud/examples/hello_world_grpc/Dockerfile, google/cloud/examples/hello_world_grpc/hello_world.proto, google/cloud/examples/hello_world_grpc/hello_world_grpc.cc, google/cloud/examples/hello_world_grpc/vcpkg.json
Application developers may want to deploy gRPC services to Cloud Run, to
authenticate with these services one must use `GenerateIdentityToken()`
in the IAM credentials service, and pass the resulting token to the gRPC
library. This example uses a small "Hello World"-type gRPC service to
demonstrate this use-case.
Fixes #6482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6583)
=> feat: an example using identity tokens with gRPC

google/cloud/internal/async_retry_loop_test.cc
The expectation in `AsyncRetryLoopTest.ExhaustedDuringBackoff` assumes
that the retry loop will call the functor before the retry policy is
exhausted. Previously (in #6436) extended the retry time limit a little
in order to increase the probability that the functor is called at least
once. Now we replace the time-based retry policy with an error-count
one, which guarantees the (failing) functor is called once.
Really fixes #6266.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6585)
=> test(common): eliminate flakiness in async_retry_loop test

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_experiment.h, google/cloud/storage/benchmarks/throughput_experiment_test.cc, google/cloud/storage/grpc_plugin.cc, google/cloud/storage/grpc_plugin.h, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/internal/hybrid_client.h
Like our other gRPC-based libraries we need to support multiple channels
behind the same client to get good throughput. This implements the
"round robin" layer for that case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6593)
=> feat(storage): support multiple channels in GCS+gRPC

ci/cloudbuild/cache.sh
Sometimes it's useful to use the cached artifacts that were used in a GCB build even when running locally in docker. This may help reproduce build breaks if they're cache related. This prints the command to run locally to pull the production cache
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6597)
=> ci: log cache.sh command

ci/cloudbuild/builds/lib/integration.sh, google/cloud/examples/BUILD, google/cloud/examples/CMakeLists.txt, google/cloud/examples/README.md, google/cloud/examples/grpc_credential_types.cc, google/cloud/examples/hello_world_grpc/hello_world.proto, google/cloud/examples/hello_world_grpc/hello_world_grpc.cc
They cannot be imported into Google's code with the protos in the global
namespace, they conflict with other protos.
I changed the name of the Cloud Run deployment so we can have two
running, once this PR is merged I will send a second one to change
the name back and delete the `*-r2` deployment once that is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6600)
=> cleanup: move gRPC example protos to a package

google/cloud/bigtable/tests/CMakeLists.txt, google/cloud/bigtable/tests/bigtable_client_integration_tests.bzl, google/cloud/bigtable/tests/data_async_future_integration_test.cc, google/cloud/bigtable/tests/data_integration_test.cc, google/cloud/bigtable/tests/table_sample_rows_integration_test.cc
Pros:
* could save test time (since the async test was added)
* could have implications for #441, as we are no longer calling `SampleRowKeys` and `DropRowRange` on the same table in the emulator
Cons:
* increases `CreateTable` calls from 7 to 8 per build. We still should be fine on the GCB quota though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599)
=> refactor(bigtable): pull out tests for SampleRows, AsyncSampleRows into their own test fixture

ci/cloudbuild/README.md, ci/cloudbuild/cloudbuild.yaml
Reverts googleapis/google-cloud-cpp#6598
This doesn't seem to work for me today. I'm going to revert while I debug so that others aren't impacted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6601)
=> Revert "ci(gcb): move builds to custom worker pool"

ci/cloudbuild/README.md, ci/cloudbuild/builds/log-linker.sh, ci/cloudbuild/cloudbuild.yaml
Take two (https://github.com/googleapis/google-cloud-cpp/pull/6601)
Use a Google Cloud Build custom worker pool to run all of our builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6602)
=> ci(gcb): move builds to custom worker pool

ci/cloudbuild/builds/lib/integration.sh, google/cloud/examples/README.md
I created a `*-r2` version of this deployment to rename the protos, now
that those changes are merged we can go back to simpler names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6608)
=> cleanup: simplify hello-world-grpc deployment

ci/cloudbuild/build.sh, ci/lib/io.sh
Rebrand `io::log_cmdline` as `io::log_and_run`, which, as the
name suggests, now also executes the command so as to eliminate
duplication at the call site.  This version also adds quoting.
Introduce `io::log_and_run` into the `ci/cloudbuild/build.sh`
script. Additions to any of the `ci/cloudbuild/builds/*.sh`
scripts can be made as the need arises.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6609)
=> ci: reintroduce logging of important build commands

google/cloud/CMakeLists.txt, google/cloud/credentials.cc, google/cloud/credentials.h, google/cloud/google_cloud_cpp_common.bzl, google/cloud/google_cloud_cpp_common_unit_tests.bzl, google/cloud/internal/credentials_impl.cc, google/cloud/internal/credentials_impl.h, google/cloud/internal/credentials_impl_test.cc, google/cloud/internal/grpc_access_token_authentication.h, google/cloud/internal/grpc_async_access_token_cache.h, google/cloud/internal/grpc_impersonate_service_account_integration_test.cc, google/cloud/internal/unified_grpc_credentials.h, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/impersonate_service_account_credentials.h, google/cloud/storage/internal/impersonate_service_account_credentials_test.cc, google/cloud/storage/internal/minimal_iam_credentials_rest.h, google/cloud/storage/internal/unified_rest_credentials.cc, google/cloud/storage/internal/unified_rest_credentials.h, google/cloud/storage/internal/unified_rest_credentials_test.cc, google/cloud/storage/tests/unified_credentials_integration_test.cc
Expose the public APIs for `google::cloud::Credentials`. Currently there
are no public APIs to *accept* these credentials in any libraries, that
will come in separate PRs.
Fixes #6293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6614)
=> feat(common): make unified Credentials public

google/cloud/spanner/client.cc
While the advertised `spanner::SessionPoolOptionList` should
not include `spanner_internal::SessionPoolClockOption`, that
option will be set in the `spanner::SessionPoolOptions` passed
to `spanner::MakeConnection()`, so we should not warn about its
presence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6619)
=> fix(spanner): do not warn about SessionPoolClockOption

google/cloud/pubsub/internal/subscription_lease_management.cc, google/cloud/pubsub/internal/subscription_lease_management.h, google/cloud/pubsub/internal/subscription_lease_management_test.cc, google/cloud/pubsub/internal/subscription_session.cc, google/cloud/pubsub/subscriber_options.cc, google/cloud/pubsub/subscriber_options.h, google/cloud/pubsub/subscriber_options_test.cc
Fixes #6283 
Note that this change gives the users the ability to set their desired deadline extension (in seconds). It does not calculate and use the p99 latency, like the other Pub/Sub libraries do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6620)
=> feat(pubsub): add ability to set the ack deadline extension

ci/cloudbuild/builds/lib/bazel.sh, ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/builds/scan-build.sh, ci/cloudbuild/cache.sh, ci/cloudbuild/trigger.sh, ci/cspell.json, google/cloud/storage/emulator/README.md, release/README.md
Avoid prefixing paths with `./` except in the cases where we
really want to execute something from the current directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6629)
=> cleanup: avoid the dot-slash idiom when it serves no purpose

ci/cloudbuild/cloudbuild.yaml
This change likely fixes #6327. 
As of today, Kaniko `v1.6.0` is the newest released version. Using that version directly results in the crash described in https://github.com/GoogleContainerTools/kaniko/issues/1604. However, using the `v1.6.0-debug` image works, I _think_ because of a different version of the `docker-credentials-gcr` helper as I described in https://github.com/GoogleContainerTools/kaniko/issues/1604#issuecomment-848287852
Updating Kaniko may also help #6336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6634)
=> ci(gcb): update kaniko version and retry pushes

google/cloud/storage/client.h, google/cloud/storage/examples/storage_auth_samples.cc, google/cloud/storage/examples/storage_client_mock_samples.cc, google/cloud/storage/examples/storage_object_csek_samples.cc, google/cloud/storage/examples/storage_object_resumable_write_samples.cc, google/cloud/storage/examples/storage_object_samples.cc
Change the examples to use the unified credentials. In the process I
discovered that many examples included `storage/oauth2/credentials.h`
without using it.
Part of the work for #6612
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6646)
=> cleanup(storage): use unified credentials in examples

google/cloud/storage/client_test.cc, google/cloud/storage/examples/storage_client_mock_samples.cc, google/cloud/storage/object_test.cc, google/cloud/storage/testing/mock_client.h
This makes it easier to use a `MockClient`, and avoids using
`storage::oauth2::Credentials` in the examples for `MockClient`.
Part of the work for #6612 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6649)
=> cleanup(storage): simplify MockClient initialization

google/cloud/storage/client_sign_policy_document_test.cc, google/cloud/storage/client_sign_url_test.cc
Using the unified credentials simplifies some of the unit tests, so why
not?
Part of the work for #6612
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6650)
=> cleanup(storage): use unified credentials in unit tests

google/cloud/storage/client.h, google/cloud/storage/examples/storage_auth_samples.cc
Some of the Doxygen documentation still referenced the
`google::cloud::oauth2::*` classes.
Part of the work for #6612
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6648)
=> cleanup(storage): update docs for unified credentials

ci/cloudbuild/builds/lib/integration.sh, ci/generate-markdown/generate-bigtable-readme.sh, ci/generate-markdown/generate-packaging.sh, ci/generate-markdown/generate-pubsub-readme.sh, ci/generate-markdown/generate-readme.sh, ci/generate-markdown/generate-spanner-readme.sh, ci/generate-markdown/generate-storage-readme.sh, ci/install-bazel.sh, ci/lib/io.sh, release/release.sh
It seems that Fedora:34 recently got a new version of ShellCheck, which
warns about `readonly FOO=$(program)`:
https://github.com/koalaman/shellcheck/wiki/SC2155
Replace those by a separate assignment immediately followed by declaring
the variable `readonly`.
For future reference, the RPM changes can be tracked here:
https://src.fedoraproject.org/rpms/ShellCheck/commits/f34
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6652)
=> cleanup: fix ShellCheck errors

google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/examples/storage_grpc_samples.cc, google/cloud/storage/grpc_plugin.cc, google/cloud/storage/grpc_plugin.h, google/cloud/storage/quickstart/grpc/quickstart.cc, google/cloud/storage/tests/unified_credentials_integration_test.cc
Now that the plugin is initialized with the unified credentials it can
never "fail" (it can return a client that always fails). Likewise, the
credentials are easier to initialize, setting the unified credentials
works for both `internal::CurlClient` and `internal::GrpcClient`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6651)
=> cleanup(storage): simplify gRPC plugin initialization

google/cloud/pubsub/internal/subscription_lease_management.cc
Without this change some of the tests took 8 seconds to complete,
and presumably applications would take longer to shutdown too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6662)
=> fix(pubsub): save refresh timer for cancellation

ci/cloudbuild/dockerfiles/checkers.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile, ci/cloudbuild/triggers/checkers-ci.yaml, ci/cloudbuild/triggers/checkers-pr.yaml
This is useful because the "checkers" build is unique in that it doesn't
actually compile any code, rather it simply checks things _about_ the
code, such as formatting, whitespace, etc. Therefore, the docker
container in which it runs may likely need to be quite different than
normal builds which will need compilers, etc. To keep a bit separate and
to minimize unneeded cross-dependencies, it seems reasonable to split
this build out into its own dockerfile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6661)
=> ci: split checkers build to its own Dockerfile

ci/cloudbuild/builds/checkers.sh
This PR speeds up the `Running Abseil header fixes`, `Running include fixes`, and `Running whitespace fixes` steps by making each step work in parallel with `xargs -P`. This cuts the overall `checkers-pr` time in half on my laptop. For the mentioned three steps they drop from about 15 seconds to about 3 seconds.
Speed improvements to this build are valuable because this is a build that most of us run frequently, and certainly before sending a PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6660)
=> ci: run sed checkers in parallel

google/cloud/pubsub/internal/subscriber_logging.cc, google/cloud/pubsub/internal/subscriber_logging.h, google/cloud/pubsub/internal/subscriber_logging_test.cc, google/cloud/pubsub/internal/subscriber_metadata.cc, google/cloud/pubsub/internal/subscriber_metadata.h, google/cloud/pubsub/internal/subscriber_metadata_test.cc, google/cloud/pubsub/internal/subscriber_round_robin.cc, google/cloud/pubsub/internal/subscriber_round_robin.h, google/cloud/pubsub/internal/subscriber_round_robin_test.cc, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h, google/cloud/pubsub/testing/mock_subscriber_stub.h
The client libraries in other languages use unary RPCs to ack/nack
messages, even though one can piggy back these through the streaming
pull request. Soon we will want to examine the return value of these
Ack/Nack operations, and we cannot use the streaming RPC for those.
Part of the work for #6195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6666)
=> feat(pubsub): direct Ack/Nack through SubscriberStub

.github/renovate.json
Fixes #6657 
(we cant run a postUpgradeTask, but having renovate update `packaging.md` will probably catch all of the breaks due to checkers-pr)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6672)
=> chore(deps): renovate-bot also updates packaging.md

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source.h, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc, google/cloud/pubsub/internal/subscription_session_test.cc, google/cloud/pubsub/subscriber_connection_test.cc
Change the Pub/Sub client to prefer unary RPCs for Ack and Nack
messages. A future version will expose the error codes from them and it
would be useful to have them.
Fixes #6195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6674)
=> feat(pubsub): use unary RPCs for Ack/Nack

bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/triggers/coverage-ci.yaml, ci/cloudbuild/triggers/coverage-pr.yaml
Fedora:34 uses GCC 11, and the version of BoringSSL used by gRPC-1.37.1
does not compile with that version of GCC. Therefore, we load our own
(newer) version of BoringSSL.
Part of the work for #6524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6679)
=> ci: move coverage build to Fedora:34

ci/cloudbuild/builds/quickstart-cmake.sh, ci/kokoro/macos/build-quickstart-cmake.sh, ci/kokoro/windows/build-cmake-dependencies.ps1
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/6687
This version of vcpkg sees the `vcpkg.json` file at the top of our repo
and thinks we're using it in manifest mode, so we need to run the vcpkg
commands from w/in the vcpkg dir.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6688)
=> ci: upgrade to vcpkg 2021.05.12 which understands Apple M1

ci/kokoro/macos/build.sh
We're now running on macOS machines that shouldn't need this time
synchronization. Removing this simplifies the build scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6690)
=> ci(macos): stop syncing macos clocks

google/cloud/spanner/client.h, google/cloud/spanner/internal/defaults.cc, google/cloud/spanner/internal/defaults_test.cc
The RPC tracing `ConnectionOption` defaults were not being set from
the new `MakeConnection(Database const&, Options)` overload, which
meant we were missing some tracing from integration tests and samples.
So, pick up the defaults (from `${GOOGLE_CLOUD_CPP_ENABLE_TRACING}`
and `${GOOGLE_CLOUD_CPP_TRACING_OPTIONS}`) when each option has not
already been set.
Add new `DefaultOptions()` test cases. Also tighten the context of
existing test cases that similarly depend on the environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6691)
=> fix(spanner): pick up tracing-option defaults in SetBasicDefaults()

ci/cloudbuild/builds/lib/integration.sh, ci/kokoro/macos/build-bazel.sh, ci/kokoro/macos/build-cmake.sh, ci/kokoro/windows/build-bazel.ps1, google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh, google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh, google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh, google/cloud/pubsub/ci/run_integration_tests_emulator_cmake.sh, google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh, google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh, google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
Include streaming RPCs in the "lastN" tracing after an integration-test
or sample failure. This will make it a little easier to understand the
log after an occasional and difficult-to-reproduce error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6695)
=> test(common): also log streaming RPCs after test/sample failure

ci/kokoro/macos/build-cmake.sh, ci/kokoro/macos/build-quickstart-cmake.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6698)
=> ci(macos): install ccache when needed

ci/cloudbuild/builds/cmake-oldest-deps.sh, ci/cloudbuild/builds/lib/vcpkg.sh, ci/cloudbuild/builds/quickstart-cmake.sh
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/6699
This PR factors the code to fetch the vcpkg repo into a library that's
reused in a couple places. It also clones the repo at a recent release
tag rather than cloning at HEAD which may break our builds and is not
hermetic, or downloading a tarball, which lacks git history.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6701)
=> ci(vcpkg): create lib/vcpkg.sh used by several builds

ci/kokoro/macos/build-cmake.sh, ci/kokoro/macos/build-quickstart-cmake.sh, ci/kokoro/macos/build.sh
This PR will verify that needed packages are installed (via brew), else they'll be installed. Versions are printed, but they're not verified to be any particular value.
UPDATE: It turns out that we do still need to always re-install the `google-cloud-sdk` package, sadly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6712)
=> ci(macos): simplify the brew install commands

ci/cloudbuild/build.sh, ci/lib/io.sh
Append "(+\<delta\>s)" to the `io::internal::timestamp()` to more
clearly indicate the duration since the beginning of the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6716)
=> ci: add a seconds delta to the "io" timestamps

google/cloud/storage/internal/curl_handle.cc, google/cloud/storage/internal/curl_handle.h
Sometimes the debug callback gets invoked with a zero-sized buffer. We
were creating a log line for each, and in some cases this can generate a
lot of noise. With this change we only log the number of times this took
place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6725)
=> cleanup(storage): reduce noise in debug log

ci/cloudbuild/build.sh
Uses the bash `:` builtin and `:=` in the parameter expansion to set
some bash variables with default values in a more succinct way.
See:
- https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Bourne-Shell-Builtins
- https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6722)
=> cleanup(ci): use bash colon builtin to set vars with defaults

generator/integration_tests/golden/golden_kitchen_sink_connection.cc, generator/integration_tests/golden/golden_kitchen_sink_connection.h, generator/integration_tests/golden/golden_thing_admin_connection.cc, generator/integration_tests/golden/golden_thing_admin_connection.h, generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc, generator/internal/connection_generator.cc, google/cloud/bigquery/bigquery_read_connection.cc, google/cloud/bigquery/bigquery_read_connection.h, google/cloud/iam/iam_connection.cc, google/cloud/iam/iam_connection.h, google/cloud/iam/iam_credentials_connection.cc, google/cloud/iam/iam_credentials_connection.h, google/cloud/logging/logging_service_v2_connection.cc, google/cloud/logging/logging_service_v2_connection.h
The overload for `Make*Connection()` taking a `*Stub` needs to be
internal-only. It is used in tests, and may be used to add decorators,
but should not be used by application developers.
Part of the changes for #6721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6723)
=> cleanup: move Make*Connection overload to internal

google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc, google/cloud/spanner/integration_tests/client_integration_test.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/query_options.h, google/cloud/spanner/query_options_test.cc, google/cloud/spanner/samples/samples.cc
Support setting `optimizer_statistics_package` (1) on `Client` query
operations, (2) in `Client` construction (via `ClientOptions`), or
(3) from `${SPANNER_OPTIMIZER_STATISTICS_PACKAGE}`.
The first setting in that list will be passed to the backend in each
`ExecuteSqlRequest`.
Include examples in the `spanner_create_client_with_query_options`
and `spanner_query_with_query_options` samples.
Fixes #4820.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6727)
=> feature(spanner): add optimizer_statistics_package to QueryOptions

ci/kokoro/macos/build-cmake.sh, ci/kokoro/macos/build-quickstart-cmake.sh
This matches our Ninja output from our GCB builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6736)
=> ci(macos): print elapsed time in Ninja builds

ci/cloudbuild/builds/gcs-grpc.sh, ci/cloudbuild/builds/install-gcs-grpc.sh, ci/kokoro/macos/build-bazel.sh, ci/kokoro/windows/build-bazel.ps1, google/cloud/storage/benchmarks/throughput_experiment_test.cc, google/cloud/storage/client_test.cc, google/cloud/storage/internal/grpc_client.cc
The integration tests against production were disabled because
production was broken. It has been working for a few weeks, so time to
enable them again. In the process I discovered that:
* I had broken the initialization of credentials, since the tests were
running against the emulator only that went unnoticed.
* One of the unit test failed if `CLOUD_STORAGE_ENABLE_TRACING` was set.
Fixes #6062
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6737)
=> cleanup(storage): restore GCS+gRPC production integration tests

ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile, doc/packaging.md
@dbolduc noticed a build break in our demo-centos-8 build and also found
the cause and the fix https://bugs.centos.org/view.php?id=18212.
Example build break: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/6739/92e59f91cb066b67edd3dd7d04060f2787fa53c9/demo-centos-8-demo-install/log-259d8ad0-178c-48f6-a48b-462775bc0df7.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6741)
=> fix(ci): avoid centos-8 bug w/ dnf update

ci/cloudbuild/build.sh
This lets us easily run our existing bazel builds with different
versions of bazel. Examples
```shell
$ ci/cloudbuild/build.sh -t asan-pr --docker
$ USE_BAZEL_VERSION=3.5.0 ci/cloudbuild/build.sh -t asan-pr --docker
$ USE_BAZEL_VERSION=latest ci/cloudbuild/build.sh -t asan-pr --docker
$ USE_BAZEL_VERSION=last_green ci/cloudbuild/build.sh -t asan-pr --docker
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6739)
=> ci: pass USE_BAZEL_VERSION to docker

google/cloud/storage/internal/storage_auth_test.cc, google/cloud/testing_util/CMakeLists.txt, google/cloud/testing_util/google_cloud_cpp_testing_grpc.bzl, google/cloud/testing_util/mock_grpc_authentication_strategy.h
I need to write tests for the generated `*Auth` decorators, this will
come handy there.
Part of the work for #6721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6745)
=> refactor: move mock for GrpcAuthenticationStrategy

ci/kokoro/lib/cache.sh, ci/kokoro/macos/build.sh, ci/kokoro/macos/builds/bazel.sh, ci/kokoro/macos/builds/cmake-super.sh, ci/kokoro/macos/builds/quickstart-bazel.sh, ci/kokoro/macos/builds/quickstart-cmake.sh, ci/kokoro/macos/download-cache.sh, ci/kokoro/macos/upload-cache.sh
Assuming that consistency is good, making the mac scripts look similar
to the `ci/cloudbuild/` scripts is probably good too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6748)
=> ci(mac): refactor build scripts to look more like GCB scripts

google/cloud/spanner/integration_tests/client_integration_test.cc
I did not track down exactly why, but the error code from the
emulator when reading the INFORMATION_SCHEMA.SPANNER_STATISTICS
table has changed from `kInvalidArgument` in the Cloud SDK
build to `kUnimplemented` in an emulator built from source.
So, allow both.
We could be even less restrictive (like `Not(IsOk())`), but
being as exacting as possible allows us to learn of changes
in emulator behavior. For example, in some places we still
`if (emulator) GTEST_SKIP()`, but that will never let us know
when the emulator starts supporting a feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6756)
=> test(spanner): relax emulator SPANNER_STATISTICS expectation

generator/integration_tests/generator_integration_test.cc, google/cloud/internal/filesystem.cc, google/cloud/internal/filesystem.h, google/cloud/internal/filesystem_test.cc, google/cloud/internal/unified_grpc_credentials_test.cc, google/cloud/storage/client_options_test.cc, google/cloud/storage/internal/unified_rest_credentials_test.cc, google/cloud/storage/oauth2/google_credentials_test.cc, google/cloud/storage/oauth2/service_account_credentials_test.cc, google/cloud/storage/testing/temp_file.cc, google/cloud/storage/tests/object_file_integration_test.cc
With googletest >= 1.11 ::testing::tempDir() does not seem to end in a
forward slash. That is a problem because in many places we did
`::testing::TempDir() + path` to create a filepath, which can be invalid
or confuse things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6758)
=> refactor: use helper to join testing::TempDir()

.github/renovate.json
Run the project on all weekdays, we get too many PRs on Monday, and
maybe they are not keeping up.
Exclude the "boringssl" dependency (this is for Bazel), we are using a
branch and the PRs are constantly trying to "update" us to the default
branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6766)
=> chore: tweak renovate configuration

google/cloud/iam/integration_tests/iam_credentials_integration_test.cc
These tests fail on every PR that affects them, not for all builds, but
for enough of them to require manual intervention on the PR. Note that
PRs that do not affect these tests pass cleanly because the test results
are cached in that case.
This is a workaround for #6724 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6768)
=> test(iam): disable flaky integration tests

bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile, google/cloud/storage/benchmarks/throughput_result_test.cc, google/cloud/testing_util/expect_exception.h, super/external/googletest.cmake
Update the builds to use googletest-1.11.0. It seems like this triggers
some more warnings with Clang-12. One of them was useful (yay!), the
other looked like a false positive and I disabled it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6759)
=> chore: update googletest to 1.11.0

ci/cloudbuild/builds/lib/bazel.sh
@coryan observed that our flakiness data from looking at CI builds only
was not accurate for bazel builds because the PR builds would have
already populated the cache, and the following CI build would just hit
the cache and not even run the test, thus hiding potential flakes.
This PR avoids that issue by forcing CI builds to ignore the
test-results cache with `--cache_test_results=no`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6773)
=> ci: disable test result cache on CI builds

ci/cloudbuild/builds/lib/integration.sh
Some of these tests were only running on the macOS and Windows builds.
Part of the work for #6721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6771)
=> ci: run integration tests for generated libraries

ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/builds/msan.sh, ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile, generator/integration_tests/BUILD, google/cloud/internal/filesystem.cc
I had to disable the integration test for the generator, some function
inside protobuf uses an unitialized variable (maybe).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6782)
=> ci: use Fedora:34 for msan build

google/cloud/storage/emulator/emulator.py
This removes the `nextPageToken` field in the storage emulator list operations responses for the following reasons.
- The emulator currently is designed to return all items altogether, therefore no nextPageToken is needed.
-  Currently, [python-api-core](https://github.com/googleapis/python-api-core/blob/11032cf08ecc16dd252a6cda8b33b0b28ec4f4ba/google/api_core/page_iterator.py#L404) determines whether or not there are more pages with result by checking if `nextPageToken` is None. Therefore, empty page tokens causes infinite loops.
- Inspecting the JSON API with a one-page result `storage.objects.list`, it appears that there is no nextPageToken field within the response.
Fixes #6635
--- …
=> cleanup(storage): remove nextPageToken field in emulator list operations

ci/cloudbuild/builds/lib/integration.sh, google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh, google/cloud/storage/emulator/ci/run_integration_tests_bazel.sh, google/cloud/storage/tools/run_emulator_utils.sh
Use a different instance of the emulator to run the **emulator** tests
vs. the tests that **use** the emulator. The emulator tests
intentionally crash some of the emulator workers, which then causes
problems for the regular tests. Note that the emulator tests themselves
are still flaky, but they are very fast so using `--flake-test_attempts`
mostly avoids the problem.
Part of the work for #6641
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6792)
=> test(storage): deflake integration tests

ci/cloudbuild/cloudbuild.yaml
We've been seeing some timeouts from the `integration-daily`
build since disabling CI-build test-result caching.  This
should not be too surprising given that the slow Spanner
backup/instance tests and samples already take a good part
of the allotted 1h, and are subject to scheduling delays in
the backend.  So, increase the timeout to 2h.
I couldn't, for the life of me, figure out how to parameterize
the timeout with a `gcloud builds submit --substitutions=`,
and chose not to move the value out to a `--timeout=` flag,
so this simply raises the limit for all builds.  Alternative
ideas are welcomed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6795)
=> ci: increase the GCB timeout

google/cloud/storage/tests/thread_integration_test.cc
Some additional cleanups, but the key change is to **not** check each
`InsertObject()` operation as these may fail when there is a retry.
Fixes #6785
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6805)
=> test(storage): deflake thread_integration_test

ci/cloudbuild/builds/lib/integration.sh, google/cloud/spanner/ci/lib/spanner_emulator.sh, google/cloud/spanner/ci/run_integration_tests_emulator_bazel.sh
Avoids some flakes by using the emulator. We still have
some builds hitting production, mostly macOS and Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6812)
=> ci: use emulator for Spanner and Bazel

google/cloud/internal/async_long_running_operation.h, google/cloud/internal/async_long_running_operation_test.cc, google/cloud/internal/extract_long_running_result.cc, google/cloud/internal/extract_long_running_result.h, google/cloud/internal/extract_long_running_result_test.cc
Some long-running operations return their value in the `response` field,
while others use the `metadata` field, with this change both are
supported.
Part of the work for #6821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6822)
=> feat(common): support response in long-running operations

google/cloud/internal/async_long_running_operation.h, google/cloud/internal/async_long_running_operation_test.cc, google/cloud/internal/async_polling_loop.cc, google/cloud/internal/async_polling_loop.h, google/cloud/internal/async_polling_loop_test.cc
Add support for cancelling long-running operations, applications may
decide to stop a very slow operation.
Part of the work for #6821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6824)
=> feat(common): long-running operations cancel support

google/cloud/internal/async_long_running_operation.h, google/cloud/internal/async_long_running_operation_test.cc, google/cloud/internal/async_polling_loop_test.cc
This time for realsies, I need to return the future created by
`AsyncPollingLoop()` because this is where the cancel callback is
initialized.
Part of the work for #6821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6831)
=> feat(common): cancel long-running operations

generator/integration_tests/golden/golden_thing_admin_connection.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.h, generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.cc, generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.h, generator/integration_tests/golden/internal/golden_thing_admin_logging_decorator.cc, generator/integration_tests/golden/internal/golden_thing_admin_logging_decorator.h, generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.cc, generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.h, generator/integration_tests/golden/internal/golden_thing_admin_stub.cc, generator/integration_tests/golden/internal/golden_thing_admin_stub.h, generator/integration_tests/golden/mocks/mock_golden_thing_admin_stub.h, generator/integration_tests/golden/tests/golden_thing_admin_auth_decorator_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_logging_decorator_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_stub_factory_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_stub_test.cc, generator/internal/auth_decorator_generator.cc, generator/internal/connection_generator.cc, generator/internal/logging_decorator_generator.cc, generator/internal/metadata_decorator_generator.cc, generator/internal/stub_generator.cc
For long-running operations we need to generate three different RPCs:
one to start the operation (e.g. `CreateDatabase()`), one to poll the
operation (`GetOperation()`), and one to cancel the operation
(`CancelOperation()`).  With this change all the three RPCs are
generated as asynchronous RPCs.
The `*Connection` class can use these asynchronous RPCs in the
background, using the background threads. This (1) avoids creating a
detached thread to poll the operation, (2) uses code that is more easily
unit tested separate from the generated libraries.
Fixes #6821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6830)
=> feat(generator): use async for long-running operations

ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile, doc/packaging.md
Reverts googleapis/google-cloud-cpp#6827
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6840)
=> Revert "chore(deps): update dependency grpc/grpc to v1.38.1"

bazel/google_cloud_cpp_deps.bzl
Reverts googleapis/google-cloud-cpp#6826
Rolling this back because grpc 1.38.1 breaks our builds that use `pkg-config`. See also https://github.com/googleapis/google-cloud-cpp/pull/6840
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6841)
=> Revert "chore(deps): update dependency com_github_grpc_grpc to v1.38.1"

google/cloud/storage/tests/bucket_integration_test.cc, google/cloud/storage/tests/grpc_integration_test.cc, google/cloud/storage/tests/object_list_objects_versions_integration_test.cc
A single project cannot create more than 1 bucket every 2 seconds. Some
of our integration tests (which do hit production) create buckets and
need a tuned client to backoff for at least 2 seconds on transient
problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6833)
=> test(storage): tune bucket creation

ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/triggers/demo-rockylinux-8-ci.yaml, ci/cloudbuild/triggers/demo-rockylinux-8-pr.yaml
In this PR we just create the support files for Rocky Linux 8, a future
PR will remove the CentOS 8 files.
Part of the work for #6836
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6837)
=> ci: move CentOS 8 builds to Rocky Linux 8

google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/instance_admin_connection_test.cc, google/cloud/spanner/internal/instance_admin_logging.cc, google/cloud/spanner/internal/instance_admin_logging.h, google/cloud/spanner/internal/instance_admin_logging_test.cc, google/cloud/spanner/internal/instance_admin_metadata.cc, google/cloud/spanner/internal/instance_admin_metadata.h, google/cloud/spanner/internal/instance_admin_metadata_test.cc, google/cloud/spanner/internal/instance_admin_stub.cc, google/cloud/spanner/internal/instance_admin_stub.h, google/cloud/spanner/testing/mock_instance_admin_stub.h
Use the new, common `async_long_running_operation.h` support
to implement `InstanceAdminConnection::CreateInstance()` and
`UpdateInstance()` using the existing background threads (and
not a detached `std::thread`).
Part of #4038.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6835)
=> refactor(spanner): Use background threads for instance-admin LROs

ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, doc/packaging.md
There's a [bug] w/ CentOS-7's version of `pkg-config` that can cause
invocations to take a reeeeeaaaaly long time to complete. We discovered
this when upgrading to grpc-1.38.1 and had to [rollback] the upgrade.
The fix to `pkg-config` was rolled out about 8 years ago in `pkg-config`
0.28. This PR upgrades the pkg-config we use on CentOS-7 to the latest
as of this writing. After this, I think we should be able to upgrade
grpc again.
[bug]: https://bugs.freedesktop.org/show_bug.cgi?id=54716
[rollback]: https://github.com/googleapis/google-cloud-cpp/pull/6840
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6846)
=> chore(deps): upgrade pkg-config on CentOS-7 to avoid bug

google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/internal/database_admin_logging.cc, google/cloud/spanner/internal/database_admin_logging.h, google/cloud/spanner/internal/database_admin_logging_test.cc, google/cloud/spanner/internal/database_admin_metadata.cc, google/cloud/spanner/internal/database_admin_metadata.h, google/cloud/spanner/internal/database_admin_metadata_test.cc, google/cloud/spanner/internal/database_admin_stub.cc, google/cloud/spanner/internal/database_admin_stub.h, google/cloud/spanner/testing/mock_database_admin_stub.h
Use the new, common `async_long_running_operation.h` support
to implement `DatabaseAdminConnection::CreateDatabase()`,
`UpdateDatabase()`, `CreateBackup()`, and `RestoreDatabase()`
using the existing background threads (and not a detached
`std::thread`).
Part of #4038.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6853)
=> refactor(spanner): Use background threads for database-admin LROs

google/cloud/bigtable/examples/bigtable_table_admin_backup_snippets.cc, google/cloud/bigtable/table_admin.h
Fixes #5931
there are non-functional things I want to cleanup in the test (like variable names: `table_1`, `table_id_1`, `backup_id_1`) but I will do so in a subsequent PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6847)
=> feat(bigtable): add Backup IAM Policy snippets

google/cloud/storage/emulator/gcs/bucket.py
This removes `resourceId` from [`Bucket.set_iam_policy()`](https://github.com/googleapis/google-cloud-cpp/blob/bc730c84eb344fc6350271f7331fab14ef68a77a/google/cloud/storage/emulator/gcs/bucket.py#L247) request body in the storage emulator. This field is ignored in a [storage.buckets.setIamPolicy](https://cloud.google.com/storage/docs/json_api/v1/buckets/setIamPolicy#request-body) request and not included in the [google.iam.v1 Policy proto](https://github.com/googleapis/googleapis/blob/dba65e3c28aa8e26c4d5b8ec9c80fbd0d0f29864/google/iam/v1/policy.proto#L88).  
Fixes #6843
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6852)
=> cleanup(storage): remove resourceId from emulator Bucket.set_iam_policy

ci/cloudbuild/builds/lib/integration.sh, google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh, google/cloud/bigtable/tools/run_emulator_utils.sh
This PR doesn't really fix anything, but I spent some time looking into
BT emulator flakes and noticed some small cleanups that I could do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6859)
=> cleanup: bigtable emulator scripts

google/cloud/internal/async_polling_loop.cc, google/cloud/spanner/database_admin_connection_test.cc
Cancellation of a long-running operation (1) happens asynchronously
with the flow of callbacks, and (2) requires access to the currently
running operation name. This means we must serialize reads/writes of
that name, so introduce a member mutex.
And given that we now have a mutex, use it to guard `canceled_`
as well, avoiding the need for atomic operations. Also mark the
operation as cancelled when that happens before the operation name
is first set.
Finally, update the `DatabaseAdminConnectionTest.CreateBackupCancel`
test to allow for `AsyncCancelOperation()` not being called before
the polling policy expires.
Fixes #6854.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google …
=> fix(common): synchronize cancel for long-running operations

google/cloud/spanner/internal/database_admin_logging_test.cc, google/cloud/spanner/internal/database_admin_metadata_test.cc, google/cloud/spanner/internal/instance_admin_logging_test.cc, google/cloud/spanner/internal/instance_admin_metadata_test.cc, google/cloud/spanner/internal/partial_result_set_source_test.cc, google/cloud/spanner/samples/mock_execute_query.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6866)
=> cleanup(spanner): Prefer absl::make_unique<T>() over std::unique_ptr<T>(new T)

google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc, google/cloud/bigtable/examples/data_snippets.cc
All of the methods in `RunInstanceOperations()` are called immediately below it, with the same configuration in `RunAll()`.
Remove second testing of `CheckAndMutate()` example (it is tested immediately above).
Move the print from `ReadRow()` into `ReadModifyWrite()` (so there is useful feedback when it is called). Then delete unused `ReadRow()` because the real method is tested in `read_snippets.cc`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6869)
=> cleanup(bigtable): delete extraneous example tests

google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc, google/cloud/storage/benchmarks/storage_parallel_uploads_benchmark.cc, google/cloud/storage/benchmarks/storage_shard_throughput_benchmark.cc, google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
The benchmarks were creating buckets with `PredefinedAcl::Private()`,
that is, a bucket that requires project owner privileges to create
objects in it. This changes the bucket permissions to
`PredefinedAcl::ProjectPrivate()`, that is, a bucket where project
editors can create objects.
I also changed the benchmarks to use the `PredefinedAcl::*()` helper
functions, they are there to prevent misspelling, might as well use
them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6871)
=> cleanup(storage): run benchmarks with fewer privileges

google/cloud/storage/internal/curl_handle.cc, google/cloud/storage/internal/curl_handle.h, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/storage_client_integration_tests.bzl, google/cloud/storage/tests/tracing_integration_test.cc
With some MSVC configurations (2019+Debug, 2017+Debug, or 2017+Release)
enabling HTTP tracing creates a crash. I think because in other
compilers the move constructor and assignments are not used, and luckily
that means the pointers were stable, but this is not the case for those
versions/configurations of MSVC.
The integration test crashes before this change and succeeds after the
change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6870)
=> fix(storage): crashes with tracing enabled

google/cloud/storage/CMakeLists.txt, google/cloud/storage/auto_finalize.cc, google/cloud/storage/auto_finalize.h, google/cloud/storage/auto_finalize_test.cc, google/cloud/storage/client.cc, google/cloud/storage/client.h, google/cloud/storage/examples/storage_object_resumable_write_samples.cc, google/cloud/storage/google_cloud_cpp_storage.bzl, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/object_streambuf.cc, google/cloud/storage/internal/object_streambuf.h, google/cloud/storage/internal/object_streambuf_test.cc, google/cloud/storage/object_stream.cc, google/cloud/storage/object_stream.h, google/cloud/storage/object_stream_test.cc, google/cloud/storage/parallel_upload.cc, google/cloud/storage/storage_client_unit_tests.bzl, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/auto_finalize_integration_test.cc, google/cloud/storage/tests/object_write_streambuf_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
Some applications need to delay upload finalization until they
explicitly call `.Close()`, even if the upload stream's destructor is
called. Typically such applications may use resumable uploads,
checkpoint the session id in some external storage, and would prefer to
resume the upload with a new stream object rather than having the
library automatically finalize the upload.
Fixes #6844
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6874)
=> feat(storage): make auto-finalization optional

google/cloud/internal/streaming_read_rpc.h
With gRPC, one must finish a streaming RPC before destroying it, which
also requires capturing the output. We do this in the destructor, and
print a warning if some error goes undetected. However, `kCancelled` is
not an unexpected error, the destructor cancels the RPC, there is no
reason to print anything in this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6876)
=> cleanup(common): avoid spurious warnings

ci/cloudbuild/builds/lib/bazel.sh
Recently we moved to `--cache_test_results=no` for CI, and then
daily bazel builds (see #6773 and #6806).  An upshot of this was
that we also moved to `--cache_test_results=yes` for the other
bazel builds.
However, `--cache_test_results=yes` is not the same as defaulting
the flag.  In particular, `yes` indicates that test failures
should be cached, which is undesirable when those tests are flaky.
So restore those other bazel builds to the default caching mode
of `--cache_test_results=auto`, which always reruns failed tests
(and also reruns under `--runs_per_test`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6879)
=> ci: use cache_test_results=auto for non-ci/daily bazel builds

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_experiment.h, google/cloud/storage/benchmarks/throughput_experiment_test.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
Now that the GCS+gRPC plugin supports multiple channels it makes more
sense to use the same client in all threads, at least by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6882)
=> feat(storage): share client in throughput benchmark

google/cloud/storage/emulator/grpc_server.py, google/cloud/storage/internal/grpc_resumable_upload_session.cc, google/cloud/storage/internal/grpc_resumable_upload_session.h, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc, google/cloud/storage/tests/auto_finalize_integration_test.cc, google/cloud/storage/tests/grpc_integration_test.cc
To make resumable uploads resumable we need to close the stream after
each chunk, and the byte accounting needed some fixing. I was able to
simplify some of the code after these changes.
In the process I discovered and fixed a bug in the emulator: it did not
handle partial uploads correctly.
The "last committed byte" accounting could use a cleanup, but that is
a matter for a future PR (see #6880).
Fixes #6875.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6881)
=> fix(GCS+gRPC): resumable uploads can resume

google/cloud/storage/bucket_metadata.cc, google/cloud/storage/bucket_metadata.h, google/cloud/storage/bucket_metadata_test.cc, google/cloud/storage/emulator/gcs/bucket.py, google/cloud/storage/examples/storage_bucket_samples.cc, google/cloud/storage/internal/bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_client_bucket_metadata_test.cc, google/cloud/storage/tests/bucket_integration_test.cc
This is a new metadata field in the storage Bucket. This PR also fixes
some typos and blunders in the existing tests for
BucketIamConfiguration.
Blegh, I accidentally closed the second version of this PR, and can't reopen. Third try.
Fixes #5491 
@shaffeeullah
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6755)
=> feat(storage): implement "public access prevention"

google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/grpc_object_read_source.h, google/cloud/storage/internal/grpc_object_read_source_test.cc
The checksum headers could be duplicated in many `Read()` requests.
Because headers are stored in a multimap associated with each
`storage::ObjectReadStream` this resulted in slower processing and
additional memory consumed during the download.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6891)
=> fix(GCS+gRPC): avoid duplicate headers in downloads

google/cloud/storage/examples/CMakeLists.txt, google/cloud/storage/examples/storage_examples.bzl, google/cloud/storage/examples/storage_object_preconditions_samples.cc, google/cloud/storage/internal/http_response.cc, google/cloud/storage/internal/http_response.h, google/cloud/storage/internal/http_response_test.cc, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/object_read_preconditions_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
GCS returns a 304 (Not Modified) for downloads with a
`ifMetagenerationNotMatch` pre-condition that is not met.  Methinks that
is a confusing error to return ("not modified" for a read-only operation
that was not going to modify anything? wut?).  In any case, we need to
map this to our error namespace, and `kFailedPrecondition` seems like
the best mapping.
I added integration tests for the failure and success cases of each
pre-condition, so far we only had unit tests and obviously we were
missing some problems. I also added some samples because we got
questions about how to do this.
Note: some tests are disabled, will fix as part of #6896
--- …
=> fix(storage): treat 304 errors as kFailedPrecondition

ci/cloudbuild/builds/rotate-keys.sh
Our `rotate-keys` build failed with the following error:
```
ERROR: (gcloud.iam.service-accounts.keys.delete) argument --iam-account: Must be specified.
Usage: gcloud iam service-accounts keys delete KEY-ID --iam-account=IAM_ACCOUNT [optional flags]
optional flags may be  --help
```
So we should switch our flag from `--account=` to `--iam-account=`.
This is confirmed by the [documentation](https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/keys/delete).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6899)
=> fix(ci): fix iam account flag when deleting keys

google/cloud/storage/internal/curl_client.cc, google/cloud/storage/tests/object_read_preconditions_integration_test.cc
The `x-goog-if-*-match:` headers do not work for reads in XML.
AFAICT, this is a bug in the service, but it will take several months for it to
be fixed (assuming the team has the time).  I think it is better to the library
to work correctly in the interim, we can restore the functionality when the
service is fixed.
Using JSON has a small performance hit, but that is shrinking over time,
and these features are used rarely, if ever.
Fixes #6896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6900)
=> fix(storage): use JSON for reads with pre-conditions

ci/cloudbuild/builds/integration-daily.sh, ci/cloudbuild/builds/lib/integration.sh, google/cloud/spanner/testing/policies.h
Add a hook for running integration tests without the emulator,
execute the Spanner tests from it, and call the hook during
the `integration-daily` build.
The Spanner samples/tests have cases that are skipped or
short-circuited when running against the emulator, so we lost
some coverage when we move to using the emulator exclusively
from the "normal" builds.  Now we'll at least hit those cases
during `integration-daily`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6888)
=> ci(spanner): run spanner integration tests against prod

google/cloud/storage/emulator/utils/common.py, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/object_insert_preconditions_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
Fix the header name (`metageneration` should be one word) for `IfMetagenerationMatch`. Add
integration tests for all pre-conditions too.
Motivated by #6896.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6903)
=> fix(storage): use correct header for XML pre-conditions

generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_stub.h, google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/internal/resumable_streaming_read_rpc.h, google/cloud/internal/resumable_streaming_read_rpc_test.cc, google/cloud/internal/streaming_read_rpc.cc, google/cloud/internal/streaming_read_rpc.h, google/cloud/internal/streaming_read_rpc_logging.cc, google/cloud/internal/streaming_read_rpc_logging.h, google/cloud/internal/streaming_read_rpc_logging_test.cc, google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/grpc_object_read_source_test.cc, google/cloud/storage/object_stream.h, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/object_read_headers_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
gRPC returns metadata for all requests, including streaming RPCs. In the
storage service this is very useful for troubleshooting, this change
weaves the metadata (and some additional bits from
`grpc::ClientContext`) through the different layers. The metadata is
exposed as "headers", because that matches the existing APIs (and gRPC
uses HTTP/2 headers under the hood anyway).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6902)
=> feat(GCS+gRPC): capture streaming RPCs metadata

google/cloud/storage/client.h, google/cloud/storage/tests/object_parallel_upload_integration_test.cc
In `ParallelUploadFile()` we were not allowing overwrites of the target
object. In some cases applications may absolutely want to overwite the
target (say because they are replacing its contents). In some
applications they may not, in which case they can provide a
pre-condition.
Fixes #6907
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6908)
=> fix(storage): allow overwrites in parallel uploads

CHANGELOG.md, google/cloud/bigtable/table.cc, google/cloud/bigtable/table.h, google/cloud/bigtable/version.h
Fixes #2567 
Note: this leaves a lot of `*Impl()`'s that are called only once. I will refactor these in a subsequent PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6921)
=> cleanup(bigtable)!: remove async functions that take `CompletionQueue` as a param

google/cloud/storage/client.h, google/cloud/storage/object_test.cc, google/cloud/storage/parallel_upload.h, google/cloud/storage/parallel_uploads_test.cc
Some of our helper functions (`ParallelFileUpload()`,
`DeleteObjectsByPrefix()`) used pre-conditions to avoid deleting new
versions of an object. In most cases that is too restrictive, it
prevents acting on an object that has been modified, even if the version
we want is still available. We can use `storage::Generation()` to just
delete the version we want, even if there is a newer version.
Fixes #6910
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6923)
=> fix(storage): pre-conditions are too restrictive

google/cloud/storage/benchmarks/CMakeLists.txt, google/cloud/storage/benchmarks/storage_benchmark_programs.bzl
The emulator has (as of maybe 6 months ago) enough features to support
the benchmarks, so we can simplify the CMake files.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6925)
=> test(storage): emulator supports the benchmarks too

google/cloud/spanner/client.cc, google/cloud/storage/internal/grpc_client.cc
Applications might set this option to zero or a negative number, this is
almost always a bug or an accident. It seems reasonable to use `1` in
such cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6926)
=> fix: GrpcNumChannels option can be zero

google/cloud/storage/benchmarks/CMakeLists.txt, google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.h, google/cloud/storage/benchmarks/aggregate_throughput_options_test.cc, google/cloud/storage/benchmarks/storage_benchmark_programs.bzl, google/cloud/storage/benchmarks/storage_benchmarks.bzl, google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
A new benchmark for aggregate download bandwidth. The existing
benchmarks perform both uploads and downloads as part of the run, which
limits the total download banwidth. Moreover, their output is per
download, which makes it hard to aggregate the results across multiple
processes. This benchmark does not suffer from those problems, but it is
more limited in that it just measures one configuration at a time.
Part of the work for #6884, I will not call it fixed yet because I would also
like to capture CPU usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6927)
=> feat(storage): benchmark aggregate download banwidth

google/cloud/storage/internal/bucket_metadata_parser.cc, google/cloud/storage/internal/common_metadata_parser.h, google/cloud/storage/internal/lifecycle_rule_parser.cc, google/cloud/storage/internal/metadata_parser.cc, google/cloud/storage/internal/metadata_parser.h, google/cloud/storage/internal/metadata_parser_test.cc, google/cloud/storage/internal/object_access_control_parser.cc, google/cloud/storage/internal/object_metadata_parser.cc, google/cloud/storage/internal/object_requests.cc
These functions were still using exceptions to signal errors.
Par of the work for #6935
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6937)
=> fix(storage): use StatusOr<T> for metadata parsing

google/cloud/storage/internal/bucket_metadata_parser.cc, google/cloud/storage/internal/common_metadata_parser.h, google/cloud/storage/internal/metadata_parser.cc, google/cloud/storage/internal/metadata_parser.h, google/cloud/storage/internal/metadata_parser_test.cc, google/cloud/storage/internal/object_metadata_parser.cc
Part of the work for #6935.  I will fix `ParseRfc3339()` in a followup PR, I did not want to make changes across services in the same PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6939)
=> fix(storage): parsing timestamps should return status

google/cloud/pubsub/benchmarks/throughput.cc, google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc, google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/testing_util/timer.cc, google/cloud/testing_util/timer.h
This is some slight refactoring / reorganization to make the
`testing_util::Timer` class more friendly towards tracking cumulative
usage. I will need this for storage's aggregate throughput benchmark,
and I think it is easier to use anyway.
Part of the work for #6884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6932)
=> test: simplify helpers to track usage

google/cloud/storage/internal/hmac_key_metadata_parser.cc
Prefer `storage::internal::ParseTimestampField()` over
`g::c::internal::ParseRfc3339()` as the former validates the field type
and handles empty fields.
Part of the work for #6935
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6942)
=> refactor(storage): prefer ParseTimestampField

google/cloud/pubsub/benchmarks/throughput.cc, google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc, google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc, google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/testing_util/timer.cc, google/cloud/testing_util/timer.h
Capture CPU usage in the `aggregate_throughput_benchmark`. This is
useful when trying to compare the costs of different protocols.
Fixes #6884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6941)
=> feat(storage): CPU usage in throughput benchmark

google/cloud/storage/CMakeLists.txt, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_insert_object_media_test.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl, google/cloud/storage/testing/mock_storage_stub.h
Small uploads can include the metadata, the data, and the checksums in a
single `Write()` call. This adds a test to verify the plugin actually
does so.
Fixes #4383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6951)
=> test(GCS+gRPC): verify small uploads are optimized

google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc
In the aggregate_throughput benchmark we do not want to sleep for longer
than the total running time, or the main thread would be sleeping while
no work is done by the worker threads, and the elapsed time measurement
would include time when no work was being done.
Likewise, we want to wait until all threads are done with their
downloads before reporting the aggregate bandwidth.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6953)
=> feat(storage): more accurate aggregate bandwidth results

google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/instance_admin_connection_test.cc
Use full text protos, which set every field, to test the Spanner
GetDatabase/ListDatabases and GetInstanceConfig/ListInstanceConfigs
admin-connection APIs, rather than only individually assigning and
checking certain fields.  While these APIs are quite thin, this
gives us a little more confidence that we're not missing anything.
It also allows us to add new fields without changing the control
flow in the test.  That was the primary goal in this case, so as
to get coverage for the new "configurable leader placement" fields
`google.spanner.admin.database.v1.Database.default_leader` and
`google.spanner.admin.instance.v1.InstanceConfig.leader_options`.
In addition, the `GetDatabaseWithEncryption` test becomes redundant.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> test(spanner): use text protos to test admin-connection APIs

google/cloud/internal/base64_transforms.cc, google/cloud/internal/base64_transforms.h, google/cloud/storage/internal/openssl_util.cc
Use the transforms in `google::cloud::internal::` to convert from and to
base64 encoding. For the moment these continue to through exceptions on
errors, a future PR will convert the remaining exception to
`StatusOr<>`.
I performed some refactoring in the base64 transforms: in spanner the
base64 decoding is always performed after the source is validated, in
storage that is not the case.
Part of the work for #6946
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6956)
=> feat(storage): use Base64 transforms

google/cloud/storage/hashing_options.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_object_read_source_test.cc, google/cloud/storage/internal/openssl_util.cc, google/cloud/storage/internal/openssl_util.h, google/cloud/storage/internal/openssl_util_test.cc
Avoid going through the base64 representation used in the REST protocol,
as this requires weaving error handling through many layers.
Part of the work for #6946
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6959)
=> cleanup(GCS+gRPC): compute MD5 hashes directly

google/cloud/storage/internal/grpc_object_read_source_test.cc
It was missing (useful) `EXPECT_CALL()` checks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6960)
=> cleanup(GCS+gRPC): reduce noise from unit test

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_object_request_test.cc, google/cloud/storage/tests/object_checksum_integration_test.cc, google/cloud/storage/tests/object_hash_integration_test.cc
The proto file says that neither the `md5_hash` nor the `crc32c` fields
should be set when uploading an `Object`:
https://github.com/googleapis/googleapis/blob/1eade8161f2ef102282869bc3eb18841807b2b46/google/storage/v1/storage_resources.proto#L691-L694
https://github.com/googleapis/googleapis/blob/1eade8161f2ef102282869bc3eb18841807b2b46/google/storage/v1/storage_resources.proto#L676-L679
Also improved the documentation on how to obtain these hashes for tests.
I disabled some tests that used to pass because the service does not ignore
the hashes in the `Object` resource. The documentation says it does (see
the links), so my tests were passing by accident and the service can change
at any time.  Once I fix #4156 and #4157 these tests can be enabled again.
Part of the work for #6946, and …
=> fix(GCS+gRPC): no hashes in Object resource

google/cloud/storage/client.cc, google/cloud/storage/client_sign_policy_document_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_object_read_source_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session_url.cc, google/cloud/storage/internal/openssl_util.cc, google/cloud/storage/internal/openssl_util.h, google/cloud/storage/internal/openssl_util_test.cc, google/cloud/storage/internal/self_signing_service_account_credentials_test.cc, google/cloud/storage/oauth2/service_account_credentials_test.cc, google/cloud/storage/testing/write_base64.cc, google/cloud/storage/tests/curl_sign_blob_integration_test.cc, google/cloud/storage/tests/signed_url_conformance_test.cc, google/cloud/storage/well_known_headers.cc
Use StatusOr<> to signal errors when decoding base64 strings. This
required changes at the call sites, which I generally handled as
follows:
- In tests, where the decoding is known to work, I just call `.value()`.
- In functions ready to return `StatusOr<>` I just propagate the
failure.
- In other functions, I changed the chain of calls until all of them had
a `Status` or `StatusOr<>`.
Fixes #6946
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6961)
=> cleanup(storage): error handling in base64 decoding

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_insert_object_media_test.cc, google/cloud/storage/internal/grpc_client_object_request_test.cc, google/cloud/storage/tests/object_checksum_integration_test.cc
With this change `ObjectInsert()` uses all the checksum options,
allowing applications to provide checksums (when known in advance),
disabling some checksums, or letting the library compute them.
Part of the work for #4156 and for #4157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967)
=> feat(GCS+gRPC): checksums on ObjectInsert

google/cloud/spanner/client.cc, google/cloud/spanner/internal/defaults.cc, google/cloud/spanner/internal/session_pool.cc
Looks like we were
1. defaulting the options
2. making at least one stub 
3. checking to see if there was a mismatch between number of stubs and `GrpcNumChannelsOption` (only happens if option is <= 0)
4. if there is a mismatch, recalculate the `SessionPoolMinSessionOption` (by calling `DefaultOptions()` again).
This can be simpler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6973)
=> refactor(spanner): constrain number of channels when we default options

ci/cloudbuild/builds/clang-38.sh, ci/cloudbuild/builds/gcc-54.sh, ci/cloudbuild/dockerfiles/ubuntu-xenial.Dockerfile, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/tests/curl_request_integration_test.cc
Part of the work for #6424
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6971)
=> ci: gcc-3.8 and gcc-5.4 do not need super builds

ci/cloudbuild/build.sh, ci/install-cloud-sdk.sh
The latest version should include fixes for the Cloud Bigtable emulator.
Part of the fixes for #441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6981)
=> chore: update google-cloud-sdk

google/cloud/storage/examples/storage_client_mock_samples.cc, google/cloud/storage/internal/hash_validator.h, google/cloud/storage/internal/object_read_streambuf.cc, google/cloud/storage/internal/object_read_streambuf.h, google/cloud/storage/tests/small_reads_integration_test.cc
Simplify the implementation of `storage::internal::ObjectReadStreambuf`.
The class had two different paths to get more data from the underlying
`internal::ObjectReadSource`, this change makes all reads through the
`xsgetn()` function.
In addition, the class was sloppy with the hash validator, potentially
using it after it was moved-from, luckily this was harmless, but no
reason to keep doing so.
I added some integration tests to cover corner cases that were only
detected by accident in other tests.
Part of the work for #4156 and #4157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6983)
=> cleanup(storage): simplify ObjectReadStreambuf

google/cloud/bigtable/client_options.cc, google/cloud/bigtable/client_options.h
@devjgm pointed out that there was no need to accept `Options` in a constructor which we do not want anyone to use.
Technically this is a breaking change since #6949, but I think it is fine to make such a change between releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6988)
=> cleanup(bigtable): unmodify the obsolete constructor

google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.h, google/cloud/storage/benchmarks/aggregate_throughput_options_test.cc, google/cloud/storage/grpc_plugin.h, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_test.cc
Make it easier to experiment with configuration options for the GCS+gRPC
plugin. This is useful in benchmarking, and might be useful in the final
form of the plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6991)
=> feat(GCS+gRPC): option to configure plugin

google/cloud/bigtable/benchmarks/benchmark.cc, google/cloud/bigtable/benchmarks/embedded_server_test.cc, google/cloud/bigtable/examples/bigtable_grpc_credentials.cc
part of the work for #6307 
Use the preferred constructor in our benchmarks and examples. The only remaining reference to the credentials constructor is in a test for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6992)
=> cleanup(bigtable): prefer `ClientOptions` constructor that uses `Options`

google/cloud/storage/internal/object_write_streambuf.cc
Part of the work for #4156 and for #4157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6993)
=> cleanup(storage): prevent use-after-move

google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_handle.cc, google/cloud/storage/internal/curl_handle.h
This is most useful in benchmarks, but could be handy
when troubleshooting connection problems. Specially
if proxies or VPC-SC are involved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6994)
=> feat(storage): capture peer addres for REST

ci/cloudbuild/build.sh
This gives all of our `build.sh -s ...` sessions a consistent prompt
that shows the name of the distro that we're running in which can be
useful, because sometimes we need to know `apt` vs `dnf` etc.
For example, with this I get
```console
$ build.sh -t asan-pr -s
...
docker:fedora-34$ 
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6997)
=> ci: add DISTRO to bash prompt in build.sh --docker

ci/cloudbuild/builds/clang-60.sh, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, ci/cloudbuild/triggers/clang-60-ci.yaml, ci/cloudbuild/triggers/clang-60-pr.yaml
This is towards removing the Clang-3.8 build.
Part of the work for #6982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6998)
=> ci: create build for Clang-6.0

ci/cloudbuild/build.sh
This restores network isolation between the container and the docker
host, which should allow for using fixed ports from concurrent
containers without interference. The DNS cache problems alluded to
from #4288 appear to be a thing of the past.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7003)
=> ci: change to docker "bridge" network driver

google/cloud/bigtable/tools/run_emulator_utils.sh, google/cloud/pubsub/ci/lib/pubsub_emulator.sh, google/cloud/spanner/ci/lib/spanner_emulator.sh, google/cloud/storage/tools/run_emulator_utils.sh
I think this will deflake the storage builds.  Consider this:
- The script to startup the emulator uses the log file to discover the
port where it is running.
- The script launches the emulator in the background and then
immediately tries to read its log
- The script fails with "cannot connect", which it is only attempted
after the port is found.
- The script then prints an empty emulator log, which could not happen
if the port was found!
But really what is going on is that the shell calls `fork(2)` to start
the emulator, but before it gets to call `exec(2)`, or before it even
redirects `stdout` the parent process reads the file, finds the *old*
ports, then tries to connect. That fails, of course, then it prints the
log file, but that might be empty, or incomplete, or completely …
=> test: avoid using old emulator logs in startup

google/cloud/pubsub/publisher_connection_test.cc
Fixes #7006 
The issue was that (very rarely) the hold timer would expire and [flush](https://github.com/googleapis/google-cloud-cpp/blob/8db6bac678ab450c4d46fee68d94c94bbc3be94a/google/cloud/pubsub/internal/batching_publisher_connection.cc#L163) the batch of messages before all messages in the test had been published. This would lead to the mock's `AsyncPublish` being called more than once.
This change makes it so that we ack all batches, instead of just [the first batch](https://github.com/googleapis/google-cloud-cpp/blob/8db6bac678ab450c4d46fee68d94c94bbc3be94a/google/cloud/pubsub/publisher_connection_test.cc#L156).
Other fixes considered:
* adding a `bool AsyncSequencer::Empty()`. This seems like it was against the design of the sequencer, which [allows for push and pop to be called …
=> test(pubsub): deflake flow control test

google/cloud/storage/internal/hash_function.cc
Apparently I introduced the same problem as before in the few commits since the last import attempt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7013)
=> cleanup: prepare for import into google

google/cloud/storage/tests/object_plenty_clients_serially_integration_test.cc, google/cloud/storage/tests/object_plenty_clients_simultaneously_integration_test.cc
These tests are looking for leaks, but were failing when the number of
file descriptors *decreased*, they should only fail if they increased.
Fixes #7007
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7017)
=> test(storage): deflake "plenty clients" tests

generator/integration_tests/generator_integration_test.cc
Using a `TestWithParam<absl::string_view>` produces very unreadable
failures: the string view is printed one character at a time. And we
should use `ASSSERT_STATUS_OK()` before using an `StatusOr<T>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7019)
=> test(generator): make failures more readable

ci/cloudbuild/build.sh
This makes it easy to delete build-output directories to start with a
fully clean build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7026)
=> ci: add --docker-clean flag to build.sh

google/cloud/storage/emulator/emulator.py, google/cloud/storage/emulator/gcs/holder.py, google/cloud/storage/emulator/gcs/object.py, google/cloud/storage/emulator/grpc_server.py, google/cloud/storage/emulator/tests/test_holder.py, google/cloud/storage/emulator/utils/common.py, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/testing/storage_integration_test.h, google/cloud/storage/tests/object_checksum_integration_test.cc, google/cloud/storage/tests/object_hash_integration_test.cc
If the application provides a `gcs::Crc32ChecksumValue()` or
`gcs::MD5HashValue()` to `InsertObject()` we should use those values to
create the metadata portion of the upload. Otherwise we are losing an
opportunity to validate the data integrity during the upload.
I discovered this while refactoring and restructuring the integration
tests for CRC32C checksums and MD5 hashes. Apologies for the massive
changes in the tests for what amounts to a small fix.
The tests now have 3 portions, one for `InsertObject()`, one for
`WriteObject()` and one for `ReadObject()`. Unlike before, the code for
XML and JSON tests is shared, though this required some changes in the
emulator to make it easier to detect what hash fields (if any) were
including in the upload.
For `InsertObject()` and `WriteObject()` …
=> fix(storage): use hash values in InsertObject()

google/cloud/bigtable/mutation_batcher.cc, google/cloud/bigtable/mutation_batcher.h, google/cloud/bigtable/mutation_batcher_test.cc
Fixes #6205 as our users **should not** run into that exact "queued mutations" error any more.
One thing I noticed is that we do not do any bounding for the [knobs](https://github.com/dbolduc/google-cloud-cpp/blob/feda70036bd9847a190249fd0fbef271300045c3/google/cloud/bigtable/mutation_batcher.h#L63-L67) to set the limit (they can, for example, set mutations per request to be a gajillion). This is why I said "should not" instead of "can not".
I would sleep easier if we did not let them set values above the Bigtable imposed limits.... I will fix in a later PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7028)
=> feat(bigtable): cap outstanding mutation number for mutation batcher

google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/hash_function.cc, google/cloud/storage/internal/hash_validator.cc
All GCS options are implemented as an `absl::optional<T>`, in the case
of `DisableMD5Hash` and `DisableCrc32cChecksum` this is
`absl::optional<bool>`. The MD5 hashes are disabled by default, this is
achieved by having the default constructor for `DisableMD5Hash`
initialize the option to `true`. CRC32C checksums are enabled by
default, the default constructor initializes the optional to
`absl::nullopt` (this is consistent with all the other options).
After this change we always use these options by doing:
```cc
auto value = request.GetOption<Disable*>().value_or(false);
```
This makes the usage consistent, and only the constructor encodes
what the default is.
Fixes #7029
--- …
=> cleanup(storage): use Disable{MD5*,Crc32c*} consistently

google/cloud/storage/client.cc, google/cloud/storage/client_write_object_test.cc, google/cloud/storage/internal/curl_resumable_upload_session.cc, google/cloud/storage/internal/curl_resumable_upload_session.h, google/cloud/storage/internal/curl_resumable_upload_session_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session.cc, google/cloud/storage/internal/grpc_resumable_upload_session.h, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc, google/cloud/storage/internal/hash_function.cc, google/cloud/storage/internal/hash_function_impl_test.cc, google/cloud/storage/internal/logging_resumable_upload_session.cc, google/cloud/storage/internal/logging_resumable_upload_session.h, google/cloud/storage/internal/logging_resumable_upload_session_test.cc, google/cloud/storage/internal/object_write_streambuf.cc, google/cloud/storage/internal/object_write_streambuf.h, google/cloud/storage/internal/object_write_streambuf_test.cc, google/cloud/storage/internal/resumable_upload_session.h, google/cloud/storage/internal/retry_resumable_upload_session.cc, google/cloud/storage/internal/retry_resumable_upload_session.h, google/cloud/storage/internal/retry_resumable_upload_session_test.cc, google/cloud/storage/object_write_stream.cc, google/cloud/storage/parallel_upload.cc, google/cloud/storage/parallel_uploads_test.cc, google/cloud/storage/testing/mock_client.h, google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc, google/cloud/storage/tests/object_checksum_integration_test.cc, google/cloud/storage/tests/object_hash_integration_test.cc, google/cloud/storage/tests/object_resumable_write_integration_test.cc, google/cloud/storage/tests/object_write_streambuf_integration_test.cc
gRPC supports sending the object checksums in the last chunk of a
resumable upload. This changes the `internal::ResumableUploadSession`
class to receive these checksums, and weaves them through all the
decorators and tests. I also changed `internal::ObjectWriteStream` to
compute and store the checksums, and only validate them later.
Fixes #4156 and fixes #4157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7031)
=> feat(GCS+gRPC): upload checksums with last chunk

google/cloud/storage/emulator/gcs/bucket.py, google/cloud/storage/emulator/gcs/holder.py, google/cloud/storage/emulator/gcs/object.py, google/cloud/storage/emulator/tests/test_bucket.py, google/cloud/storage/emulator/tests/test_holder.py, google/cloud/storage/emulator/tests/test_object.py, google/cloud/storage/emulator/utils/common.py
Before moving to the storage v2/ protos it would be good to have tests
verifying that all resource (`Object`, `Bucket`, `BucketAccessControl`,
etc.) fields are preserved as the are received from REST, stored in
protos, and returned as REST.
Part of the work for #6982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7032)
=> test(storage): test all resource fields in emulator

google/cloud/bigtable/mutation_batcher.cc, google/cloud/bigtable/mutation_batcher.h, google/cloud/bigtable/mutation_batcher_test.cc
Fixes #7030
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7036)
=> cleanup(bigtable): strictly enforce bigtable limits in mutation batcher

google/cloud/storage/object_read_stream.cc, google/cloud/storage/object_stream_test.cc, google/cloud/storage/object_write_stream.cc
The `storage::Object*Stream` classes should not crash when used after
moved-from. They do not guarantee what value they hold, but crashing on
functions that just query their state is unexpected. Note that we have
not defined what pre-conditions are required by each function, so we
could have decided to make it UB to call these functions. That seems too
hostile when "not crash but returns some undefined value" is less
hostile and about as easy to implement.
Fixes #7044
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7045)
=> fix(storage): avoid crashes after move

google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/samples/samples.cc
Until I can determine how to provision keys in multi-region instances
and avoid "Incompatible CryptoKey location" errors, avoid randomly
selecting a "test-instance-mr-*" instance during testing of CMEKs.
[The "test-instance-mr-*" instances were recently added to start
testing multi-region features.]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7047)
=> testing(spanner): avoid multi-region instances during CMEK testing

google/cloud/spanner/samples/samples.cc
The granular instance configuration (LCI) public preview has completed
roll-out, which means we can now exercise the feature without concern
for the allow-listing process.
Fixes #6894.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7050)
=> testing(spanner): remove the restriction on low-cost-instance location

google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.h, google/cloud/storage/benchmarks/aggregate_throughput_options_test.cc
This is a complete re-design of the aggregate throughput benchmark. We
are finding that there is too much variability in the results, so we
need a benchmark that can better capture the changes from one iteration
to the next.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7056)
=> feat(storage): aggregate throughput benchmark redesign

README.md, ci/generate-markdown/generate-readme.sh
Reordered command line options, "-C" option is part of the git's general options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7057)
=> doc: fix cmake instructions in top-level README

ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-xenial.Dockerfile, doc/packaging.md
I used `${NCPU:-4}` (with a default value) in all the `demo-*` files. I used `${NCPU}` in the non-demo files, because its always set in our builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7060)
=> ci: parallelize docker RUN builds whenver possible

ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile, doc/packaging.md
Fixes: #7052
This avoids Fedora's `pkgconf` (a drop-in replacement for `pkg-config`)
because it's too slow when dealing with `.pc` files with lots of
`Requires:` deps, which we have with Abseil. Instead, we use the normal
`pkg-config` binary, which seems to work better.
After this PR, we should be able to upgrade to gRPC 1.39.0 (`git revert
ba41d5a99818922b09eee5da148786c1d68c17f5`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7061)
=> ci: avoid fedora's `pkgconf` which is slow

google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request.h
Use absl::FunctionRef<> to avoid a template member function and make the
code structure match the `.h` file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7065)
=> cleanup(storage): simplify CurlDownloadRequest

generator/generator_test.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, generator/internal/predicate_utils.cc, generator/internal/predicate_utils_test.cc, generator/internal/service_code_generator_test.cc, google/cloud/log.h, google/cloud/log_test.cc, google/cloud/storage/internal/curl_handle.cc, google/cloud/storage/internal/curl_handle_test.cc
`GCP_LOG(FATAL)` now calls `std::abort()` during destruction
of its `Logger`, so control will never return to the caller.
This makes it more closely resemble the behavior of Abseil
logging, which eliminates some confusion between authors and
code readers, and which may also be a feature down the line.
This required some refactoring in a few places because the
control flow is more hidden, and `[[unreachable]]` isn't a
standard attribute yet.
Some, but not all, existing `GCP_LOG(FATAL)` invocations
were immediately followed by calls to `std::exit(1)`. These
were removed. The streaming arguments were also purged of
any trailing newlines and flushes, which `GCP_LOG()` already
handles.
Finally, `storage::AssertOptionSuccess()` was changed to
use `GCP_LOG(FATAL)` instead of `ThrowLogicError()`, …
=> feat(common): make GCP_LOG(FATAL) terminate execution

google/cloud/storage/internal/curl_download_request.cc
In libcurl the callback to receive data is called the "write callback",
I believe because this is the callback where you (the application
developer) write data to the destination file. I always found this
confusing: I am reading data from GCS and use the "write callback" for
it.
In this particular case my confusion manifested as returning
`CURL_READFUNC_PAUSE` from the write callback, when one is supposed to
use `CURL_WRITEFUNC_PAUSE`. Both are macros that expand to the same
value, so the confusion was harmless, but let's fix it anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7066)
=> cleanup(storage): correct return value for WriteCallback

google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request.h, google/cloud/storage/tests/curl_download_request_integration_test.cc
Downloads can be interrupted by the application. Sometimes this results
in incomplete cleanup of the handle, which when reused would start
failing some `curl_easy_setopt()` calls.
Fixes #7051
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7064)
=> fix(storage): cleanup interrupted downloads

google/cloud/testing_util/command_line_parsing.cc
We missed this extra argument refactoring storage benchmarks in #2671
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7067)
=> cleanup: fix usage string

release/README.md, release/release.sh
Fixes: #6682
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7071)
=> chore(release): change release.sh to use `gh` instead of `hub`

google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request.h
With this change there is a single place where the status of the HTTP
download is captured, and a single place where we cleanup the CURL* and
CURLM* handles.
Part of the work for #6160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7073)
=> cleanup(storage): simplify CurlDownloadRequest shutdown

bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-xenial.Dockerfile, doc/packaging.md
We were fetching the protobuf dep from the "google" github org, and that
worked for years, but today it broke. Changing to fetching from the
`protocolbuffers/` org seems to work and seems like the right thing to
do anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7076)
=> fix(dep): fetch protobuf tarball from the 'protocolbuffers' org

generator/internal/descriptor_utils.cc
In #7058 we removed a `std::exit(1)` call after `GCP_LOG(FATAL)`
from `CppTypeToString()` now that the `FATAL` logging does not
return.  However, as mentioned in #7058, this obscures the flow
from the compiler, resulting in a spurious "control reaches end
of non-void function" error.
In this case there is no simple way to rework the function to avoid
that diagnosis, so we quash the error by adding an unreachable
`return`, together with a traditional `/*NOTREACHED*/` comment.
Note: Abseil has an `ABSL_INTERNAL_UNREACHABLE` attribute, which
may be exported in the future to better handle situations like this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7074)
=> fix(common): quash "control reaches end of non-void function" error

google/cloud/storage/CMakeLists.txt, google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request.h, google/cloud/storage/internal/curl_handle.h, google/cloud/storage/internal/curl_request.cc, google/cloud/storage/internal/curl_request.h, google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/internal/curl_request_builder.h, google/cloud/storage/internal/curl_wrappers.cc, google/cloud/storage/internal/curl_wrappers.h, google/cloud/storage/internal/curl_wrappers_test.cc, google/cloud/storage/options.h, google/cloud/storage/storage_client_unit_tests.bzl, google/cloud/storage/tests/curl_download_request_integration_test.cc, google/cloud/storage/tests/curl_request_integration_test.cc
This is an experimental feature to set the HTTP version. Disabling
HTTP/2 can result in better load balancing as load balancers are not
aware of HTTP/2 streams.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7077)
=> feat(storage): support setting HTTP version

google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request.h, google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/internal/curl_request_builder.h, google/cloud/storage/tests/curl_download_request_integration_test.cc
Other than in tests, we always used the class in a `std::unique_ptr<>`.
We can make the class non-copyable and non-moveable, and simply return a
`std::unique_ptr<CurlDownloadRequest>` from the `CurlRequestBuilder`.
This will also workaround some bugs in MSVC (or at least I believe they
are bugs).
This is part of the work for #6160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7082)
=> cleanup(storage): simplify CurlDownloadRequest creation

google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_handle_factory.cc, google/cloud/storage/internal/curl_handle_factory.h, google/cloud/storage/tests/curl_download_request_integration_test.cc
Release the CURL* handles as soon as we are done using them. The
downloads used to hold on to these until the `CurlDownloadRequest`
object was deleted, which in turn could live until the
`storage::ObjectReadStream` was deleted.
Fixes #6160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7085)
=> feat(storage): release download handles sooner

google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request.h, google/cloud/storage/tests/curl_download_request_integration_test.cc
We keep CURL* handles in a pool, to reduce the cost of setting up TCP
connections and the SSL handshake. When there is a CURL error we
returned these handles to the pool. This is probably a bad idea,
particularly if the error is caused by timeouts or slow downloads, where
we would want to start over with a new connection.
Fixes #7079
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7088)
=> feat(storage): discard handles after an error

generator/internal/predicate_utils_test.cc, google/cloud/internal/log_impl.cc, google/cloud/internal/log_impl.h, google/cloud/internal/log_impl_test.cc, google/cloud/log.cc, google/cloud/log.h, google/cloud/log_test.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/storage/internal/curl_handle_test.cc, google/cloud/storage/tests/curl_request_integration_test.cc
It is desirable that FATAL log messages are never discarded,
especially now that GCP_LOG(FATAL) calls `std::abort` (see #7058).
To that end, ...
- Don't allow FATAL logging to be compile-time disabled.
- Always instantiate a `StdClogBackend` in `DefaultLogBackend()`.
- Give that default `StdClogBackend` a "mininum log severity" from
the first of the following conditions:
* If `${GOOGLE_CLOUD_CPP_EXPERIMENTAL_LOG_CONFIG}` is valid,
use the lowest enabled severity.
* If `${GOOGLE_CLOUD_CPP_ENABLE_CLOG}` is a valid severity,
use that.
* If `${GOOGLE_CLOUD_CPP_ENABLE_CLOG}` is otherwise set,
use the lowest enabled severity (backwards compatibility).
* If `${GOOGLE_CLOUD_CPP_ENABLE_CLOG}` is unset, use FATAL.
This means that FATAL messages should always be logged. But note
that …
=> feat(common): always clog GCP_LOG(FATAL) messages

google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.h, google/cloud/storage/benchmarks/aggregate_throughput_options_test.cc
Add an option to control how "hot" is the data in the aggregate
throughput benchmark. Recall that the aggregate throughput benchmark
runs in iterations, during which a full dataset is downloaded. With this
option the same dataset can be downloaded multiple times. This can be
used, for example, to configured the benchmark to read a single file of
1GiB a thousand times in each iteration, which approximates a workload
reading "hot" data. In contrast, configuring the benchmark to read a
dataset of 1024 files of 1GiB each just once approximates an application
reading "cold" data.
Also introduced an option to label the data, so it is easier to load
multiple benchmark results into analysis tools (coLab, Python pandas, R,
etc.) without having to parse the output filenames to annonate the …
=> feat(storage): control data hotness in benchmark

ci/cloudbuild/builds/lib/integration.sh, google/cloud/bigtable/benchmarks/BUILD, google/cloud/bigtable/benchmarks/CMakeLists.txt, google/cloud/bigtable/benchmarks/bigtable_benchmark_common.bzl, google/cloud/bigtable/benchmarks/bigtable_benchmark_programs.bzl, google/cloud/bigtable/benchmarks/bigtable_benchmarks_unit_tests.bzl, google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, google/cloud/bigtable/benchmarks/mutation_batcher_throughput_options.cc, google/cloud/bigtable/benchmarks/mutation_batcher_throughput_options.h, google/cloud/bigtable/benchmarks/mutation_batcher_throughput_options_test.cc
Fixes #7024 
A new benchmark to measure the throughput of `bigtable::MutationBatcher` given maximum number of mutations per batch and maximum number of outstanding batches.
There are no initial splits provided to the table. I considered splitting based on:
* % of table - e.g. always split into 10 shards with 10% of the rows in each.
* \# of rows in split - e.g. split such that each shard will contain 1,000,000 rows
* \# of threads - e.g. launch T threads. split such that each shard contains 1/T of the data
(Our other benchmarks launch 10 threads and split the 10M rows into 10 shards. This is where my example numbers are coming from) 
But my current thinking is that it wouldn't be helpful at this time. I assume that the advantage of initial splits come when you concurrently send batches …
=> feat(bigtable): add benchmark to measure MutationBatcher throughput

google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_throughput_options.h, google/cloud/storage/benchmarks/aggregate_throughput_options_test.cc
Add options to prefer HTTP/1.1 over HTTP/2 when using REST, and to use a
different `gcs::Client` when using either gRPC or REST.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7091)
=> feat(storage): more tuning parameters for benchmark

google/cloud/bigtable/mutation_batcher.cc, google/cloud/bigtable/mutation_batcher_test.cc
Fixes #7023 
The main purpose of updating these defaults is to avoid running into a queued mutations error.
Even though we have not collected a ton of data at this time, I would rather get this update into the release than not.
These values were discovered by testing a single batcher in a single threaded environment. More thorough benchmarking to pin down these values is in progress. The values are subject to change, as we learn more from our experiments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7095)
=> cleanup(bigtable): update MutationBatcher defaults

release/README.md, release/changes.sh
This script generates copy-n-pasteable markdown that can serve as the starting point for a human creating the release notes for our releases. It removes "uninteresting" PRs, and outputs markdown with properly linked section headings and PR numbers. A human will then need to manually tweak the output a bit, but this will helpful be a helpful starting point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7102)
=> chore: add release/changes.sh to help automate release CHANGELOG creation

google/cloud/storage/CMakeLists.txt, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_read_object_test.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl, google/cloud/storage/testing/mock_storage_stub.h
Timeouts for downloads (or any streaming operation) are tricky. A
download can take anywhere from a few milliseconds, to tens of thousands
of seconds. For the REST-based implementation we do not use timeouts for
the full operation, we use a "minimum observed bandwidth" requirement.
There does not seem to a an easy way to implement this in gRPC. While I
work in an implementation setting a timeout (of any kind) is a good
start: at least the programs won't hang forever waiting for stalled
downloads.
Part of the work for #4216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7108)
=> feat(GCS+gRPC): initial support for download timeouts

google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc
Change the benchmark to use a single queue (LIFO) with the set of
objects to download, and have all the threads service this queue.
Previously we separated the objects in groups and assigned them to
threads. The previous approach wastes threads if one (or a small
fraction) of the downloads gets stalled. I think the new approach better
models a well-designed application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7113)
=> feat(storage): make benchmark more robust on stalls

ci/kokoro/macos/builds/bazel.sh, ci/kokoro/macos/builds/cmake-vcpkg.sh, ci/kokoro/macos/common.cfg, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-cmake.ps1, ci/kokoro/windows/build-quickstart-bazel.ps1, ci/kokoro/windows/build-quickstart-cmake.ps1, ci/kokoro/windows/common.cfg, google/cloud/storage/tests/key_file_integration_test.cc, google/cloud/storage/tests/object_insert_integration_test.cc
Testing GCS with P12 keys is still being run on Linux with GCB, but we
probably don't need to duplicate that test on macos and windows, which
requires us to maintain and rotate separate keys.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7114)
=> ci(kokoro): remove GCS P12 keyfile test from mac+win

google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc, google/cloud/spanner/doc/spanner-main.dox, google/cloud/spanner/query_options.h
`Client::OverlayQueryOptions()` was misbehaving on two fronts:
- The environment option for `optimizer_statistics_package` was
using the value of `${SPANNER_OPTIMIZER_VERSION}` instead of
`${SPANNER_OPTIMIZER_STATISTICS_PACKAGE}`.
- It was not setting an output value for `request_priority` at all.
At least part of the reason for these errors was that the test:
- assumed the behavior could be changed by modifying the environment
whereas the implementation only read the environment once, and
- only a single `MockConnection`, with accumulated parameter matches,
was used across all test cases.
So, fix the implementation, and revamp the test to be more direct
(which eliminates the mocking) and to exercise RequestPriority.
Also add a note to `query_options.h` to update `OverlayQueryOptions()` …
=> fix(spanner): fix Client::OverlayQueryOptions() to merge correctly

google/cloud/internal/log_impl_test.cc, google/cloud/log.cc, google/cloud/log.h, google/cloud/log_test.cc
When using the `lastN` backend one wants the id of the thread that
created the log, not the id of the thread that is flushing the logs.
Arguably we may also want a `lastNInThread` logger, at least some of the
the time, but that is a matter for a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7119)
=> feat(common): capture thread that creates log record

google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/grpc_object_read_source_test.cc
The GCS+gRPC version of `ObjectReadSource` was behaving differently from
the REST version. It was returning the last bytes received before the
stream closed, which sets `IsOpen()` to return `false`. The caller
checks `IsOpen` and assumes the last returned status indicates whether
there was an error.
It is possible we want the return type to be `StatusAnd`, but that would
require changing all kinds of APIs that we expose for mocking. Better to
have GCS+gRPC and REST behave consistently, if a bit weirdly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7128)
=> fix(GCS+gRPC): return status on stream closure

google/cloud/stream_range.h
`=default` will implicitly set an appropriate noexcept specification, so the `IsMoveNoexcept()` function is unnecessary and possibly even subtly wrong. The clang-tidy warning `performance-noexcept-move-constructor` incorrectly triggers on this case, so the NOLINTs are still needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7134)
=> refactor(stream_range): remove unnecessary noexcept spec

google/cloud/storage/CMakeLists.txt, google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request.h, google/cloud/storage/internal/curl_download_request_test.cc, google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/grpc_object_read_source.h, google/cloud/storage/internal/grpc_object_read_source_test.cc, google/cloud/storage/internal/hash_validator.h, google/cloud/storage/internal/hash_validator_impl.cc, google/cloud/storage/internal/hash_validator_impl.h, google/cloud/storage/internal/hash_validator_test.cc, google/cloud/storage/internal/object_read_source.h, google/cloud/storage/internal/object_read_streambuf.cc, google/cloud/storage/internal/retry_object_read_source.cc, google/cloud/storage/internal/retry_object_read_source_test.cc, google/cloud/storage/storage_client_unit_tests.bzl, google/cloud/storage/tests/curl_download_request_integration_test.cc, google/cloud/storage/tests/object_read_headers_integration_test.cc
REST uses HTTP headers to return some information. We are mainly
interseted in the the object generation (to resume downloads for the
same object), and the data hashes (for data integrity). Previously the
GCS+gRPC implementation attempted to inject these headers into the
results to keep the changes to the library smaller. This proved messy.
Now we return these values in member variables of the
`internal::ReadSourceResult` struct. Each protocol knows how to parse
its messages and put the right information into these new member
variables. The struct gained a couple of constructors for backwards
compatibility, though in `storage::internal::` it is used for mocking
:disappointed:
Fixes #7124
--- …
=> refactor(storage): isolate header parsing to REST

ci/cloudbuild/build.sh, ci/cloudbuild/cloudbuild.yaml
I did some cleanup and refactoring to `ci/cloudbuild/build.sh` to make
it a little nicer to use in the common case. Changes:
1. `--docker` mode is now **the default build mode**, and may be
specified but does not need to be. So now the following are equivalent
```shell
$ build.sh -t asan-pr  # assumes --docker
$ build.sh -t asan-pr --docker
```
2. `--cloud=project` is **a new flag** to run the build on GCB in the
named project.
3. The `--project=name` flag **has been removed**. If you were using
this flag, use `--cloud=name` instead. I suspect this was rarely used.
4. The build script name may now be specified using the `--build` flag.
Previously this script was specified as a non-flag `$1` to the script.
This was inconsistent.
5. Documentation simplified and clarified. Examples now show …
=> refactor(build.sh): make build.sh --docker the default

google/cloud/spanner/internal/session_pool.cc
Use low refresh priority for the "SELECT 1" "send and forget"
session-refresh query.
Also add a note about the default transaction mode used for
that query.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7140)
=> feat(spanner): send session-refresh request at low priority

google/cloud/storage/BUILD, google/cloud/storage/quickstart/grpc/BUILD
One of the (internal) library names was too long for Windows, that broke
the build. In addition, the GCS+gRPC quickstart was linking the wrong
library.
Part of the work for #6467
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7147)
=> fix(GCS+gRPC): quickstart build with Bazel+Windows

google/cloud/spanner/integration_tests/client_integration_test.cc, google/cloud/spanner/samples/samples.cc
Test support to:
- read leader options via `GetInstanceConfig()` and `ListInstanceConfigs()`,
- set a default leader via `CreateDatabase()` and `UpdateDatabase()`, and
- read the default leader via `GetDatabase()`, `GetDatabaseDdl()`,
`ListDatabases()`, and the `INFORMATION_SCHEMA` table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7148)
=> test(spanner): configurable leader placement support

CHANGELOG.md, google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/status_or.h
This function would allow callers to assign to the contained `Status`
and potentially violate class invariants. For example:
```cc
StatusOr<Foo> sor;  // constructed with kUnknown and no Foo
sor.status() = Status{};  // BUG
auto v = sor.value();  // :-|
```
This PR fixes the above API bug by removing the `status()` accessor that
returns the lvalue to non-const T.
I also remove the `status()` overload that returns the rvalue-ref to
const-T, because I don't think it adds any new functionality to the
class, and a "move" isn't actually happening behind the scenes. Also,
the two access that remain (`const &` and `&&`) are the same two that
`absl::StatusOr` [1] has, so we match there.
[1]: https://github.com/abseil/abseil-cpp/blob/bf31a10b65d945665cecfb9d8807702ae4a7fde1/absl/status/statusor.h#L …
=> fix(statusor)!: remove status() accessor returning non-const lvalue 

CHANGELOG.md, google/cloud/bigquery/CMakeLists.txt, google/cloud/bigquery/config.cmake.in, google/cloud/iam/CMakeLists.txt, google/cloud/iam/config.cmake.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7160)
=> chore: update main with v1.30.1 changes

generator/generator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_stub_test.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, generator/internal/predicate_utils_test.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator_test.cc, google/cloud/firestore/field_path.h, google/cloud/internal/async_rpc_details.h, google/cloud/pubsub/internal/session_shutdown_manager.cc, google/cloud/spanner/instance_admin_connection_test.cc, google/cloud/spanner/internal/partial_result_set_source_test.cc, google/cloud/spanner/row_test.cc, google/cloud/spanner/sql_statement_test.cc, google/cloud/spanner/value.cc, google/cloud/storage/examples/storage_bucket_acl_samples.cc, google/cloud/storage/examples/storage_object_acl_samples.cc, google/cloud/storage/internal/curl_handle_factory_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/object_read_streambuf.cc, google/cloud/terminate_handler.cc, google/cloud/terminate_handler.h, google/cloud/terminate_handler_test.cc
This may not be all of them, but it's the ones that I could find with a relatively simple PCRE of `\bconst\s[\w\d:_<>]+\s?[&*]`
No semantic changes, just const moving.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7163)
=> cleanup: fix west const to east const

ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/cloudbuild/triggers/demo-debian-bullseye-ci.yaml, ci/cloudbuild/triggers/demo-debian-bullseye-pr.yaml, ci/generate-markdown/generate-packaging.sh, doc/packaging.md
The release is imminent, it is easy to set up a build for it. In about a
year we should retire the Debian:9 (Stretch) builds as this is under LTS
support and will be EOL in June.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7177)
=> ci: add Debian:11 (Bullseye) build files

CMakeLists.txt, google/cloud/storage/CMakeLists.txt
Use the recommended CMake variable to configure the GCS+gRPC plugin.
Part of the work for #6467
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7176)
=> cleanup(GCS+gRPC): configure via GOOGLE_CLOUD_CPP_ENABLE

CMakeLists.txt
Refactor some of the loops using GOOGLE_CLOUD_CPP_ENABLE to functions so
the variables are properly scoped and can be more meaningful.
Simplify how we determine if gRPC needs to be enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7181)
=> cleanup: scope GOOGLE_CLOUD_CPP_ENABLE uses

google/cloud/storage/benchmarks/CMakeLists.txt, google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_download_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_download_throughput_options.h, google/cloud/storage/benchmarks/aggregate_download_throughput_options_test.cc, google/cloud/storage/benchmarks/storage_benchmark_programs.bzl, google/cloud/storage/benchmarks/storage_benchmarks.bzl, google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
I need to create a benchmark for aggregate upload throughput. Changing
the name of the current benchmark so the situation is clearer once I
start adding files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7182)
=> refactor(storage): rename aggregate throughput bm

generator/generator_config.textproto
Configure generation of the Spanner database/instance admin APIs:
- in `google::cloud::spanner_admin` namespace
- in `google/cloud/spanner/admin` include path
This will allow them to co-exist with the hand-wrought APIs until
the latter can be deprecated and eventually removed.
The actual merge of the generated code will be in followup PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7183)
=> feat(spanner): add generated admin APIs

ci/cloudbuild/builds/integration-daily.sh, google/cloud/spanner/testing/policies.h
Creating/restoring backups are not only long-running operations,
but their service time is variable (apparently because they are
batch-scheduled in the backend).
So:
- Extend the timeout for "eternal" integration tests in the
`integration-daily` build (where they run against prod) from
1h (the default) to 2h.  This now matches the GCB timeout.
- Extend the per-operation polling timeout from 30m to 60m.
Fixes #4306.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7195)
=> test(spanner): extend timeouts for "slow" database operations

google/cloud/grpc_options.cc, google/cloud/grpc_options.h, google/cloud/grpc_options_test.cc
Part of the work for #6307 
Add a common option to give users full control over their gRPC channel configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7194)
=> feat(common): add GrpcChannelArgumentsNativeOption

google/cloud/bigtable/client_options_test.cc, google/cloud/grpc_options.cc, google/cloud/grpc_options.h, google/cloud/grpc_options_test.cc
If a library wants to default a gRPC channel argument, it will need to check if the user has set it. Move the functions that do this into common.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7199)
=> refactor: move gRPC Channel Argument helpers to common

generator/generator.h, generator/generator_config.proto, generator/generator_config.textproto, generator/integration_tests/generator_integration_test.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_option_defaults.cc, generator/integration_tests/golden/internal/golden_thing_admin_option_defaults.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_option_defaults_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_option_defaults_test.cc, generator/internal/codegen_utils.cc, generator/internal/codegen_utils_test.cc, generator/internal/descriptor_utils.cc, generator/internal/option_defaults_generator.cc, generator/standalone_main.cc, google/cloud/spanner/admin/internal/database_admin_option_defaults.cc, google/cloud/spanner/admin/internal/instance_admin_option_defaults.cc
Add two ServiceConfiguration fields to customization the generation
of `<Service>DefaultOptions()`.
- `service_endpoint_env_var`: Overrides the default environment
variable name, `GOOGLE_CLOUD_CPP_<SERVICE>_ENDPOINT`, used to
override the default value of the `EndpointOption`.
- `emulator_endpoint_env_var`: Enables an extra override of the
`EndpointOption` from an additional environment variable. When
used, it also sets the `GrpcCredentialOption` with insecure
channel credentials.
Use both of these new configuration fields for the generation of
the Spanner database/instance-admin services so that they match
the use of the existing `GOOGLE_CLOUD_CPP_SPANNER_DEFAULT_ENDPOINT`
and `SPANNER_EMULATOR_HOST` environment variables respectively.
--- …
=> feat(generator): customization hooks for endpoint configuration

google/cloud/bigtable/version.h, google/cloud/pubsub/version.h, google/cloud/spanner/version.h, google/cloud/storage/version.h
This is a cleanup related to #5976
There's no semantic change here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7204)
=> cleanup: define inline ns to be GOOGLE_CLOUD_CPP_NS

google/cloud/bigtable/client_options.cc, google/cloud/bigtable/client_options.h, google/cloud/bigtable/client_options_test.cc, google/cloud/bigtable/internal/defaults.cc
Part of the work for #6307 
Note that:
1. `std::string connection_pool_name_` cannot be removed because `ClientOptions::connection_pool_name()` returns a `std::string const&`. (Well, maybe it can, but I don't know how to do it)
2. The functionality of setting a connection pool name is captured by both `GrpcChannelArgumentsOption` and `GrpcChannelArgumentsNativeOption`. (just add a string to the map, or use `SetString()` on the native object)
We could add language that tells users to avoid the `ClientOptions` setters, in favor of doing all configuring through `Options`. But I sort of think we should just wait until every use of `ClientOptions` has an `Options` alternative, and then we add language that tells users to avoid the `ClientOptions` class altogether. A second opinion on this …
=> refactor(bigtable): replace grpc::ChannelArguments with Options

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/google_cloud_cpp_spanner.bzl, google/cloud/spanner/integration_tests/data_types_integration_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/json.h, google/cloud/spanner/json_test.cc, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/spanner_client_unit_tests.bzl, google/cloud/spanner/testing/database_integration_test.cc, google/cloud/spanner/value.cc, google/cloud/spanner/value.h, google/cloud/spanner/value_test.cc
`google::cloud::spanner::JSON` is just a strongly-typed string.
That is, a `JSON` value can be constructed from, and converted
to a `std::string`. `JSON` values can also be compared (by string)
for equality, and streamed.
There is no syntax checking of JSON strings in the client library.
All checking is done on the server. The user is expected to build
`JSON` values from well-formatted strings, probably produced by
a separate JSON library. Similarly, `JSON` values should be parsed
by that separate library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7212)
=> feat(spanner): support for JSON as a column type

google/cloud/bigtable/internal/defaults.cc, google/cloud/bigtable/internal/defaults_test.cc, google/cloud/bigtable/options.h
Fixes #7235 
I went with @coryan's suggestion to just use the maximum instead of flipping the bounds when an invalid range is supplied. It led to simpler code and probably simpler documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7237)
=> fix(bigtable): ensure connection refresh period is valid

google/cloud/bigtable/benchmarks/benchmark_options_test.cc
The time could advance, changing the output by the time we initialize it. The check was unnecessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7250)
=> cleanup(bigtable): don't test time output, which could change

google/cloud/storage/examples/storage_object_resumable_write_samples.cc
Deleting a resumable upload can be retried, and when it is, the result
may be `kNotFound` as the upload is deleted in a previous attempt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7252)
=> doc(storage): handle kNotFound in example

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_insert_object_media_test.cc, google/cloud/storage/internal/grpc_client_read_object_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc, google/cloud/storage/internal/storage_auth.cc, google/cloud/storage/internal/storage_auth.h, google/cloud/storage/internal/storage_auth_test.cc, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h
I thought the previous PR was too large already, and pushed this cleanup
for later. Now it is "later". All these changes are in `internal`
classes, nothing is breaking.
Part of the work for #6982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7255)
=> cleanup(GCS+gRPC): rename stub functions to match protos

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_object_request_test.cc
Handle some unlikely errors when converting REST requests to their proto
counterparts.
More work related to #6982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7256)
=> cleanup(GCS+gRPC): handle errors in common parameters

ci/kokoro/windows/build-32.bat, ci/kokoro/windows/build.bat, ci/kokoro/windows/install-bazelisk.ps1
Download Bazelisk directly from its GitHub releases. Use a retry loop to
deal with flakes. Also install for the 32-bit builds, currently unused,
but I think the consistency is worth the couple of seconds added to
these builds.
Fixes #6787
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7258)
=> ci: deflake bazelisk installation

google/cloud/storage/internal/curl_handle_factory.h, google/cloud/storage/oauth2/authorized_user_credentials_test.cc, google/cloud/storage/oauth2/compute_engine_credentials_test.cc, google/cloud/storage/oauth2/service_account_credentials.h, google/cloud/storage/oauth2/service_account_credentials_test.cc, google/cloud/storage/testing/mock_http_request.h
I accidentally dropped the `options_` parameter when moving the request
construction from the constructor to when the request is issued. This
restores the use of the `options_` parameter and adds unit tests to
prevent such breaks in the future.
Part of the work for #7260
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7261)
=> fix(storage): use CA info options in credentials

CHANGELOG.md
Capture the v1.31.1 release in the `main` CHANGELOG.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7267)
=> chore: update main changelog

generator/integration_tests/golden/.clang-format
It appears (by experiment) that `DisableFormat: true` does not
imply `SortIncludes: false` for `clang-format`. This means that
a `CompareGeneratedToGolden` test could fail if a `checkers`
build is run between generation and the `generator_integration_test`.
So, explicitly disable the sorting of includes for golden files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7271)
=> cleanup(generator): do not sort includes for golden files

google/cloud/pubsub/publisher_connection.cc
we `std::move(options)` in the `make_connection` lambda which captures by reference. Then we keep using `options`... 
I am not sure how to test for this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7270)
=> fix(pubsub): dont move PublisherOptions that we are still using

generator/integration_tests/golden/golden_thing_admin_client.cc, generator/integration_tests/golden/golden_thing_admin_client.h, generator/integration_tests/golden/tests/golden_thing_admin_client_test.cc, generator/internal/client_generator.cc, generator/internal/client_generator.h, google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_common.bzl, google/cloud/iam/iam_client.cc, google/cloud/iam/iam_client.h, google/cloud/iam/integration_tests/iam_integration_test.cc, google/cloud/iam_updater.h, google/cloud/spanner/iam_updater.h
For generated clients with standard `GetIamPolicy()` and `SetIamPolicy()`
operations, also generate a `SetIamPolicy()` overload that implements an
optimistic concurrency control loop, where the `Policy.etag` field is
used to prevent simultaneous updates of a policy from overwriting each
other.
Fixes #7168.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7276)
=> feat(generator): generate a SetIamPolicy() overload with an OCC loop

google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_client.h
Refactor a template member function that no longer needs to be a
template. This will enable further changes related to
RestoreResumableSession.
This is motivated by the comments in #7272, so let's call it part of the work for #6982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7281)
=> refactor(storage): simplify internal::CurlClient

google/cloud/iam/integration_tests/iam_integration_test.cc
Now that we have `IamIntegrationTest.SetIamPolicyUpdaterSuccess` to test the
SetIamPolicy() rerun loop, liberalize `IamIntegrationTest.SetIamPolicySuccess`
to `IamIntegrationTest.SetIamPolicySuccessOrAborted` to allow for the possible
failure of a single read-modify-write operation.
Fixes #7166.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7284)
=> test(iam): allow for possibility of kAborted from raw SetIamPolicy()

google/cloud/storage/internal/curl_handle_factory.cc, google/cloud/storage/internal/curl_wrappers.cc
This removes one use of a <mutex> feature that would make it easier if
we one day move to absl::Mutex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7286)
=> refactor(call_once): use function-local static instead of call_once

google/cloud/storage/CMakeLists.txt, google/cloud/storage/google_cloud_cpp_storage.bzl, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_client.h, google/cloud/storage/internal/curl_resumable_upload_session.cc, google/cloud/storage/internal/curl_resumable_upload_session.h, google/cloud/storage/internal/curl_resumable_upload_session_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_resumable_upload_session.cc, google/cloud/storage/internal/grpc_resumable_upload_session.h, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/internal/hybrid_client.h, google/cloud/storage/internal/logging_client.cc, google/cloud/storage/internal/logging_client.h, google/cloud/storage/internal/raw_client.cc, google/cloud/storage/internal/raw_client.h, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client.h, google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc, google/cloud/storage/version.h
The `RawClient::RestoreResumableUpload()` function is not really used,
and it lacks a parameter with the original request (which may have set
options, such as custom headers). With this cleanup the function is
deprecated. This enables a change to fully support standard parameters
when restoring resumable uploads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7283)
=> refactor(storage): reduce indirection on restoring uploads

google/cloud/storage/CMakeLists.txt, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_configure_client_context.h, google/cloud/storage/internal/grpc_configure_client_context_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl, google/cloud/storage/tests/grpc_integration_test.cc, google/cloud/testing_util/validate_metadata.cc, google/cloud/testing_util/validate_metadata.h
The REST API has a small number of "standard" query parameters which are
not part of the gRPC requests. They are implemented using special
`x-goog-*` "metadata" via the `grpc::ClientContext`. These are
documented at:
https://cloud.google.com/apis/docs/system-parameters
With this change the GCS+gRPC plugin fills out those headers from the
`*Request` object.
Fixes #4215 and fixes #6982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7272)
=> feat(GCS+gRPC): implement standard parameters

google/cloud/storage/internal/curl_resumable_upload_session.cc, google/cloud/storage/internal/curl_resumable_upload_session_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7292)
=> feat(storage): use generic parameters when resuming uploads

generator/integration_tests/golden/internal/golden_kitchen_sink_option_defaults.cc, generator/integration_tests/golden/internal/golden_thing_admin_option_defaults.cc, generator/internal/option_defaults_generator.cc, google/cloud/bigquery/internal/bigquery_read_option_defaults.cc, google/cloud/iam/internal/iam_credentials_option_defaults.cc, google/cloud/iam/internal/iam_option_defaults.cc, google/cloud/logging/internal/logging_service_v2_option_defaults.cc, google/cloud/spanner/admin/internal/database_admin_option_defaults.cc, google/cloud/spanner/admin/internal/instance_admin_option_defaults.cc
Ignore the endpoint-override environment variable not only when it is
unset, but also when it is set and empty.  This preserves the behavior
we had already set for `${GOOGLE_CLOUD_CPP_SPANNER_DEFAULT_ENDPOINT}`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7293)
=> fix(generator): ignore empty endpoint-override env vars

ci/cloudbuild/cloudbuild.yaml
Increase the GCB timeout by 5m so that it is strictly greater than
the bazel timeout for the `integration-daily` Spanner integration
tests against prod, giving the bazel timeout the chance to fire first
and produce its test summary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7296)
=> ci(gcb): increase the GCB timeout

google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc, google/cloud/storage/client_options.cc, google/cloud/storage/client_options.h, google/cloud/storage/client_options_test.cc, google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request.h, google/cloud/storage/internal/curl_request.cc, google/cloud/storage/internal/curl_request.h, google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/internal/curl_request_builder.h, google/cloud/storage/internal/grpc_client_read_object_test.cc, google/cloud/storage/options.h, google/cloud/storage/tests/object_media_integration_test.cc
With this PR the application can set timeouts for uploads, downloads, or
any other requests. Previously only downloads got timeouts, based on
whether the download "stalled". Now all requests, including uploads
(which are really just a sequence of PUT requests) have a minimum rate
configured.
The application expresses timeouts as "maximum stall time", that is, the
maximum time when no bytes are transferred. Since no bytes are
transferred while the connection is being setup, the same option
configures the maximum connection time.
Fixes #5180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7295)
=> feat(storage): support timeouts for all requests

generator/integration_tests/golden/golden_kitchen_sink_connection.h, generator/integration_tests/golden/golden_thing_admin_connection.h, generator/integration_tests/golden/internal/golden_kitchen_sink_option_defaults.h, generator/integration_tests/golden/internal/golden_thing_admin_option_defaults.h, generator/internal/connection_generator.cc, generator/internal/option_defaults_generator.cc, google/cloud/bigquery/bigquery_read_connection.h, google/cloud/bigquery/internal/bigquery_read_option_defaults.h, google/cloud/iam/iam_connection.h, google/cloud/iam/iam_credentials_connection.h, google/cloud/iam/internal/iam_credentials_option_defaults.h, google/cloud/iam/internal/iam_option_defaults.h, google/cloud/logging/internal/logging_service_v2_option_defaults.h, google/cloud/logging/logging_service_v2_connection.h, google/cloud/spanner/admin/database_admin_connection.h, google/cloud/spanner/admin/instance_admin_connection.h, google/cloud/spanner/admin/internal/database_admin_option_defaults.h, google/cloud/spanner/admin/internal/instance_admin_option_defaults.h
There is no need for defaulted `Options options = {}` arguments in
internal interfaces.  We always have an `Options` value to pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7297)
=> cleanup(generator): don't use defaulted options in internal APIs

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_resumable_upload_session.cc
This change makes the gRPC plugin support timeouts for all requests,
just like we do in REST.  The REST timeouts are more clever, based on
progress vs. completion, I am planning to create a separate bug to
improve GCS+gRPC and support progress-based timeouts too.
Fixes #4216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7299)
=> feat(GCS+gRPC): support timeouts for all requests

google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc
Not every Cloud Spanner multi-region instance configuration has
a corresponding key ring location in Cloud KMS, so it may not be
possible to create CMEK-enabled databases in such instances.
Fixes #7304.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7307)
=> test(spanner): avoid multi-region instances in CMEK backup test

CMakeLists.txt, external/googleapis/CMakeLists.txt
For our builds this change has (basically) no effect. For builds
importing `google-cloud-cpp` via `git submodule` or `FetchContent` or
something similar, this isolates the downloaded googleapis files to a
subdirectory of the build.
Fixes #7298 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7301)
=> cleanup: upstream patches from conan recipe

generator/integration_tests/golden/internal/golden_kitchen_sink_option_defaults.cc, generator/integration_tests/golden/internal/golden_thing_admin_option_defaults.cc, generator/internal/option_defaults_generator.cc, google/cloud/bigquery/internal/bigquery_read_option_defaults.cc, google/cloud/iam/internal/iam_credentials_option_defaults.cc, google/cloud/iam/internal/iam_option_defaults.cc, google/cloud/logging/internal/logging_service_v2_option_defaults.cc, google/cloud/polling_policy.h, google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/admin/internal/database_admin_option_defaults.cc, google/cloud/spanner/admin/internal/instance_admin_option_defaults.cc
Add support for constructing a `google::cloud::GenericPollingPolicy` from
`std::shared_ptr<BasePolicy>` values (in addition to the existing support
for `ConcretePolicy` values).
This means that a polling policy can be created from dynamic retry-policy
and backoff-policy values.
Use this in generated `$service_name$DefaultOptions()` functions to build
the default `$service_name$PollingPolicyOption`, for services with long-
running operations, from the prevailing retry and backoff policies (be
they defaulted or not) instead of from some other hard-coded policies.
One slight operation difference for completely defaulted policies is that
the LRO polling policy will now start its doubling exponential backoff at
1s (matching the backoff policy for retry loops) instead of 10s.
---
This change …
=> feat(generator): a better default polling policy for generated LROs

google/cloud/bigtable/client_options.h, google/cloud/bigtable/table.h, google/cloud/connection_options.h, google/cloud/grpc_options.h, google/cloud/internal/async_read_write_stream_impl.h, google/cloud/internal/retry_policy.h, google/cloud/internal/streaming_read_rpc.h, google/cloud/internal/streaming_write_rpc.h, google/cloud/kms_key_name.h, google/cloud/pubsub/publisher_options.h, google/cloud/pubsub/schema_admin_client.h, google/cloud/spanner/backup.h, google/cloud/spanner/database.h, google/cloud/spanner/instance.h, google/cloud/spanner/internal/session_pool.h, google/cloud/spanner/row.h, google/cloud/storage/grpc_plugin.h, google/cloud/storage/internal/hash_validator.h, google/cloud/storage/internal/policy_document_request.h, google/cloud/storage/object_read_stream.h, google/cloud/storage/object_write_stream.h, google/cloud/testing_util/example_driver.h, google/cloud/testing_util/validate_metadata.h
Capitalize initial letter for `@name`, `@note`, `@returns`, and `@warning` doxygen comments.
I didn't touch `@param [[:alpha:]]* [[:alpha:]]`, but I would be happy to. By my count there are:
| Initial Capitalization | Lines | Files |
|-|-|-|
| Lowercase | 455 | 68 |
| Uppercase | 60 | 6 |
I think using Uppercase with would be slightly better, but I don't really want to change the majority of the instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7310)
=> cleanup(docs): initial capitalization

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7311)
=> doc(spanner): convert Spanner samples to use the generated admin APIs

google/cloud/pubsub/internal/flow_controlled_publisher_connection.cc, google/cloud/pubsub/internal/flow_controlled_publisher_connection_test.cc
Fixes #7309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7313)
=> fix(pubsub): avoid deadlocks in publish flow control

google/cloud/pubsub/internal/defaults.cc, google/cloud/pubsub/internal/defaults_test.cc, google/cloud/pubsub/options.h, google/cloud/pubsub/publisher_options.h, google/cloud/pubsub/publisher_options_test.cc
This is technically a breaking change of anyone who lives at HEAD and who has updated in the last 22 hours.
I would just prefer to use shorter names, that are more consistent with other Options in our library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7315)
=> cleanup(pubsub): rename Maximum to Max in Options

google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc, google/cloud/spanner/samples/samples.cc
Embue each `DatabaseAdminConnection` that might be used to restore a
database during an integration test with a LRO polling time limit that
is at least as long as the timeout for the entire test.  It is no use
giving up on the operation before we would give up altogether.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7318)
=> test(spanner): extend RestoreDatabase() polling retry time

google/cloud/pubsub/internal/defaults.cc, google/cloud/pubsub/internal/defaults.h, google/cloud/pubsub/internal/defaults_test.cc, google/cloud/pubsub/options.h, google/cloud/pubsub/subscriber_options.cc, google/cloud/pubsub/subscriber_options.h, google/cloud/pubsub/subscriber_options_test.cc
part of the work for #6306 
**Some choices:**
A value of `0` supplied to `MaxConcurrencyOption` uses `DefaultMaxConcurrency()`. Perhaps it would be simpler if a `0` value just becomes `1` or `4`, and an unset option uses `DefaultMaxConcurrency()`. But I know the value cannot stay `0`.
I made new Options for `MaxOutstanding(Bytes|Messages)Option` even though they seem very similar to `MaxPending(Bytes|Messages)Option`. I think it is best to separate the publisher options from the subscriber options, and to rely on the `PublisherOptionList` and `SubscriberOptionList` to check that the user has set the correct one. Maybe publisher/subscriber should be mentioned in the option name?
I am including the `@snippet`s for `MaxOutstanding(Bytes|Messages)Option` even though they point to a sample in …
=> feat(pubsub): introduce SubscriberOptionList

google/cloud/pubsub/internal/defaults_test.cc, google/cloud/pubsub/publisher_options_test.cc
Make the publisher options default test check only that a default is set (instead of checking the exact value of a default)
Also add a mini test to ensure we are outputting warnings if an option not in the expected `OptionList` is supplied to the `PublisherOptions` constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7320)
=> test(pubsub): update pubsub options tests

google/cloud/pubsub/publisher_connection_test.cc, google/cloud/storage/version.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7323)
=> fix(storage): build with MSVC+x86

google/cloud/storage/version.h
Recent-enough versions of MSVC seem to support `[[deprecated]]` with
fewer false positives, so enable the warnings again.
Fixes #7322 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7325)
=> fix(storage): restore deprecation warnings on MSVC

ci/kokoro/windows/build-cmake-dependencies.ps1
There is no need to cleanup the vcpkg buildtrees, as the CI machines
have larger disks *and* we mostly use vcpkg binary caching. Not
important for the actual CI builds, but useful when running the script
locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7324)
=> ci: minor speedup for Windows+CMake build

ARCHITECTURE.md, google/cloud/examples/grpc_credential_types.cc, google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc, google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc, google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc, google/cloud/spanner/testing/cleanup_stale_databases.cc, google/cloud/spanner/testing/cleanup_stale_databases.h, google/cloud/spanner/testing/cleanup_stale_databases_test.cc, google/cloud/spanner/testing/cleanup_stale_instances.cc, google/cloud/spanner/testing/database_integration_test.cc, google/cloud/spanner/testing/instance_location.cc, google/cloud/spanner/testing/pick_instance_config.cc, google/cloud/spanner/testing/pick_instance_config.h, google/cloud/spanner/testing/pick_random_instance.cc
Migration to generated `InstanceAdminClient` and `DatabaseAdminClient` for:
- google/cloud/examples
- google/cloud/spanner/benchmarks
- google/cloud/spanner/integration_tests (non-API specific)
- google/cloud/spanner/testing (test helpers)
Also update ARCHITECTURE.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7327)
=> cleanup(spanner): further migration to generated admin APIs

google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc
The `integration-daily` build runs `backup_integration_test` for
both versions of the Spanner admin APIs (hand-written and generated)
concurrently.  This risks each invocation randomly selecting the same
test instance, and then hitting the hard limit of one ongoing restore
database operation per instance".
So, partition the instances into two groups, "legacy" and "generated",
using the "restore-database-partition" label, and have the tests
select an instance only from their respective partition.
Fixes #7306.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7329)
=> test(spanner): partition concurrent RestoreDatabase() calls by instance

google/cloud/kms_key_name_test.cc, google/cloud/project_test.cc, google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/backup_test.cc, google/cloud/spanner/create_instance_request_builder.h, google/cloud/spanner/create_instance_request_builder_test.cc, google/cloud/spanner/database_test.cc, google/cloud/spanner/instance_test.cc, google/cloud/spanner/internal/database_admin_metadata_test.cc, google/cloud/spanner/internal/instance_admin_metadata_test.cc, google/cloud/spanner/internal/metadata_spanner_stub_test.cc, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/update_instance_request_builder_test.cc
Eliminate some hand construction of resource names when we have higher
level APIs for doing just that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7328)
=> cleanup(spanner): prefer obj.FullName() for producing resource names

google/cloud/internal/retry_policy.h, google/cloud/pubsub/internal/defaults.cc, google/cloud/pubsub/internal/defaults.h, google/cloud/pubsub/internal/defaults_test.cc, google/cloud/pubsub/options.h, google/cloud/pubsub/subscriber_options.cc
Part of the work for #6306 
This change may seem strange on its own, because the code it is "replacing" is not touched in this PR. I did this because the full change is too large, and I want the PR's to be manageable. A (somewhat accurate) draft of the bigger picture can be found [here](https://github.com/dbolduc/google-cloud-cpp/commits/pubsub-options-big-picture).
Here are the sources for the default values:
* The logic related to `PUBSUB_EMULATOR_HOST` comes from `internal/emulator_overrides*` which will eventually be removed.
* The defaults for options from `GrpcOptionList` and `CommonOptionList` come from: [connection_options.cc](https://github.com/googleapis/google-cloud-cpp/blob/99a1cfd88cd67ed0e88c6c50712964ba8b3306c7/google/cloud/pubsub/connection_options.cc), except for …
=> feat(pubsub): add policy options; default common options

google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc
We ran the risk of the `CreateBackup()`/`UpdateBackup()` expiry time not
being at least 6 hours from the time the backup request was processed due
to the latency of intermediate operations.  So, extend the tolerance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7337)
=> test(spanner): extend backup expiry times to be well clear of 6h min

google/cloud/pubsub/integration_tests/subscriber_integration_test.cc, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h, google/cloud/pubsub/schema_admin_connection_test.cc, google/cloud/pubsub/subscription_admin_connection.cc, google/cloud/pubsub/subscription_admin_connection.h, google/cloud/pubsub/subscription_admin_connection_test.cc
Part of the work for #6306 
Still TODO for the task:
* `MakePublisherConnection` and `MakeSubscriberConnection` functions need to take `Options`. (These may be more involved, than the previous 3 PRs)
* Then just cleanups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7339)
=> feat(pubsub): configure SubscriptionAdminConnection with Options

google/cloud/pubsub/internal/batching_publisher_connection.cc, google/cloud/pubsub/internal/batching_publisher_connection.h, google/cloud/pubsub/internal/batching_publisher_connection_test.cc, google/cloud/pubsub/internal/default_batch_sink.cc, google/cloud/pubsub/internal/default_batch_sink.h, google/cloud/pubsub/internal/default_batch_sink_test.cc, google/cloud/pubsub/internal/flow_controlled_publisher_connection.h, google/cloud/pubsub/internal/flow_controlled_publisher_connection_test.cc, google/cloud/pubsub/publisher_connection.cc, google/cloud/pubsub/publisher_connection.h, google/cloud/pubsub/publisher_connection_test.cc, google/cloud/pubsub/testing/test_retry_policies.h
Part of the work for #6306 
Only `SubscriberConnection` remains.... (for the feature part of the task, the rest is cleanup)
Note: We are now done with the `CreateDefaultPublisherStub` function that takes `ConnectionOptions`. My plan is to clean that up all at one time, along with the following, which are all used in some way by `the SubscriberConnection`:
* the `CreateDefaultSubscriberStub` function that takes `ConnectionOptions`
* the `CreateChannel` function that takes `ConnectionOptions`
* the emulator overrides
* default retry policies
* test retry policies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7341)
=> feat(pubsub): configure PublisherConnection with Options

google/cloud/pubsub/integration_tests/subscriber_integration_test.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source.h, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc, google/cloud/pubsub/internal/subscription_session.cc, google/cloud/pubsub/internal/subscription_session.h, google/cloud/pubsub/internal/subscription_session_test.cc, google/cloud/pubsub/subscriber_connection.cc, google/cloud/pubsub/subscriber_connection.h, google/cloud/pubsub/subscriber_connection_test.cc
Part of the work for #6306 (so close....)
Half of `subscription_session_test.cc` used different test policies. Changing it to the test policies that every other test uses seems to be fine.
Only cleanups remain:
* tidying up code
* preferring the new methods in examples, benchmarks, quickstart
* deprecating old methods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7342)
=> feat(pubsub): configure SubscriberConnection with Options

google/cloud/pubsub/benchmarks/endurance.cc, google/cloud/pubsub/benchmarks/throughput.cc, google/cloud/pubsub/integration_tests/schema_admin_integration_test.cc, google/cloud/pubsub/integration_tests/subscriber_integration_test.cc, google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc, google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc, google/cloud/pubsub/samples/pubsub_samples_common.cc, google/cloud/pubsub/samples/samples.cc
Part of the work for #6306 
The only remaining calls to the old functions are captured in: #7347 and #7344
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7349)
=> cleanup(pubsub): switch over to new Make*Connection functions in tests, benchmarks, examples

google/cloud/grpc_options.h, google/cloud/grpc_options_test.cc
`GrpcBackgroundThreadPoolSizeOption` was missing from `GrpcOptionList`
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7351)
=> cleanup: add missing option to option list

google/cloud/bigtable/benchmarks/benchmark_options_test.cc, google/cloud/bigtable/metadata_update_policy_test.cc, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/testing/table_integration_test.cc, google/cloud/bigtable/tests/filters_integration_test.cc, google/cloud/grpc_options_test.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/internal/tuple_utils_test.cc, google/cloud/storage/internal/bucket_requests_test.cc, google/cloud/storage/internal/curl_handle_factory_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session_url_test.cc, google/cloud/storage/internal/hmac_key_requests_test.cc, google/cloud/storage/internal/object_requests_test.cc, google/cloud/storage/internal/policy_document_request_test.cc, google/cloud/storage/internal/signed_url_requests_test.cc, google/cloud/storage/internal/storage_auth_test.cc, google/cloud/storage/lifecycle_rule_test.cc, google/cloud/storage/policy_document_test.cc, google/cloud/storage/tests/object_basic_crud_integration_test.cc, google/cloud/storage/tests/object_file_integration_test.cc, google/cloud/storage/tests/object_list_objects_versions_integration_test.cc, google/cloud/testing_util/command_line_parsing_test.cc
I left:
* [this](https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/spanner/internal/tuple_utils.h#L72) and [this](https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/testing_util/scoped_log.h#L38) because they are comments
* [this](https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/internal/compiler_info_test.cc#L37) because it's in an `#if` block
* and things like `::testing::Values` or `::testing::InSequence` which I didn't think were worth changing
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7352)
=> cleanup: using directives for some tests

google/cloud/bigtable/benchmarks/benchmark.cc, google/cloud/bigtable/client_options.cc, google/cloud/bigtable/client_options_test.cc, google/cloud/bigtable/instance_admin_test.cc, google/cloud/bigtable/internal/async_longrunning_op_test.cc, google/cloud/bigtable/internal/async_poll_op_test.cc, google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll_test.cc, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/testing/table_test_fixture.cc, google/cloud/bigtable/tests/instance_admin_integration_test.cc, google/cloud/grpc_options.cc, google/cloud/grpc_options.h, google/cloud/grpc_options_test.cc, google/cloud/pubsub/subscriber_connection_test.cc
Fixes #7346 
I went with `GrpcCompletionQueueOption` as the name.
I went with `GrpcCompletionQueueOption` > `GrpcBackgroundThreadsFactoryOption` > `GrpcBackgroundThreadPoolSizeOption`. (I put the CQ option first in case we ever deprecate the factory option.)
For testing the precedence, we have `a > b > c` so I just checked that `a > b && b > c`
I did not propagate the test for the option into things like Spanner, which tests other options from `GrpcOptionList`. We should think about how to test common options that show up in all of our libraries. Do we want to duplicate a common test N times? maybe.
Bigtable's `client_options_test.cc` should always have been using the `MakeBackgroundThreadsFactory(opts)` method instead of checking the option.
--- …
=> feat(common): add ability to supply a user-run CQ to gRPC options

google/cloud/storage/internal/bucket_metadata_parser.cc
The functions to convert `g::c::s::BucketMetadata` to and from JSON
strings was getting too long and hard to grok. Soon, I will need to add
a couple more attributes, seems like a good time to split these
functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7361)
=> refactor(storage): split JSON parsing and generation

google/cloud/storage/internal/bucket_metadata_parser.cc
`absl::FunctionRef` is a non-owning wrapper, so the temporary function
objects used to initialize the `parsers[]` array will be destroyed before
they can be used. So, change to the `std::function` value type instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7366)
=> fix(storage): eliminate dangling function references

google/cloud/bigtable/options.h
Just making a note in the documentation for this behavior:
https://github.com/googleapis/google-cloud-cpp/blob/113dc999516ce9e0c00705654ecb3a06bfbc6e37/google/cloud/bigtable/internal/common_client.h#L220-L222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7373)
=> docs(bigtable): add documentation for no automatic channel refresh

google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_request.cc, google/cloud/storage/internal/curl_request.h, google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/internal/curl_request_builder.h, google/cloud/storage/internal/minimal_iam_credentials_rest.cc, google/cloud/storage/oauth2/authorized_user_credentials.h, google/cloud/storage/oauth2/compute_engine_credentials.h, google/cloud/storage/oauth2/service_account_credentials.h, google/cloud/storage/tests/curl_request_integration_test.cc, google/cloud/storage/tests/key_file_integration_test.cc, google/cloud/storage/tests/signed_url_integration_test.cc
Use `&&` overloads to prevent us (these are internal-only classes) from
re-using a `internal::CurlRequestBuilder` or `internal::CurlRequest`
after the destructive operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7376)
=> cleanup(storage): prevent reuse of CurlRequest*

.bazelrc, bazel/workspace_status_command.sh, google/cloud/BUILD, google/cloud/spanner/spanner_version_test.cc
- Use bazel's `workspace_status_command` to report the git commit.
- Substitute it into `google::cloud::internal::build_metadata()`.
- Test that `build_metadata()` does not contain a "@" delimiter.
Fixes #4035.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7378)
=> fix: substitute build metadata (git commit) in bazel builds

google/cloud/storage/tests/curl_download_request_integration_test.cc, google/cloud/storage/tests/curl_request_integration_test.cc
My current hypothesis is that the https://nghttp2.org/ certificate
expired, so change version of httpbin.
Fixes #7381
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7382)
=> test(storage): switch integration tests to httpbin.org

generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc, generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc, generator/internal/metadata_decorator_generator.cc, google/cloud/bigquery/internal/bigquery_read_metadata_decorator.cc, google/cloud/iam/internal/iam_credentials_metadata_decorator.cc, google/cloud/iam/internal/iam_metadata_decorator.cc, google/cloud/internal/api_client_header.cc, google/cloud/internal/api_client_header.h, google/cloud/internal/api_client_header_test.cc, google/cloud/logging/internal/logging_service_v2_metadata_decorator.cc, google/cloud/spanner/admin/internal/database_admin_metadata_decorator.cc, google/cloud/spanner/admin/internal/instance_admin_metadata_decorator.cc
1. Strip the leading "v" from the value of the "gccl" component in the
`X-Goog-Api-Client` header so that what remains is a valid semantic
version string (see https://semver.org/).
2. Add a "generator" build identifier to the "gccl" semver for requests
sent from generated clients.
The upshot is that the library-version component of the client header
will be `gccl/<major>.<minor>.<patch>+<git-hash>.generator`, allowing
us to identify requests from generated clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7383)
=> feat(generator): add "generator" to API client header "gccl" semver

ci/cloudbuild/builds/lib/integration.sh, google/cloud/storage/bucket_metadata.cc, google/cloud/storage/bucket_metadata.h, google/cloud/storage/bucket_metadata_test.cc, google/cloud/storage/examples/storage_bucket_samples.cc
Only tests can use the value. Change the examples to use the new value.
Leave the existing region tags in place so the website continues to find
said region tags, but point customers to use the right functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7377)
=> doc(storage): 'unspecified' value for PAP is deprecated

ci/cloudbuild/builds/lib/integration.sh, google/cloud/storage/bucket_metadata.cc, google/cloud/storage/bucket_metadata.h, google/cloud/storage/bucket_metadata_test.cc, google/cloud/storage/examples/storage_bucket_samples.cc, google/cloud/storage/internal/bucket_metadata_parser.cc, google/cloud/storage/internal/bucket_requests.cc, google/cloud/storage/internal/bucket_requests_test.cc, google/cloud/storage/tests/bucket_integration_test.cc
Add support for the `rpo` (Recovery-Point Objective) attribute. Add a
new integration test and some examples to verify it works correctly.
Update the version of the storage testbench because it needed changes to
support this RPO feature too.
Fixes #7380 and fixes #7379
I will submit this after the imminent release.
/fyi: @ddelgrosso1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7384)
=> feat(storage): add bucket attributes for RPO

google/cloud/storage/internal/object_write_streambuf.cc, google/cloud/storage/tests/object_write_stream_integration_test.cc
The library was crashing if the application called `.Close()` twice on a
`storage::ObjectWriteStream`. Arguably one should not do that, but I
think a crash is really sad behavior in this case, and it is trivial to
return the status from the previous `.Close()`.
I think @devbww asked me about this in the original review, and I had
convinced myself the pre-conditions prevented the code from running
twice. I was wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7390)
=> fix(storage): prevent crashes on double Close()

.github/workflows/codeql-analysis.yml
This sets up a GitHub action to run the CodeQL security scans. It only
runs once a day because it is too slow for PRs. It is unclear if this is
useful (beyond bragging rights), but it is worth testing for a while.
Previous results (no alerts) visible at:
https://github.com/coryan/google-cloud-cpp/runs/3792838206?check_suite_focus=true
https://github.com/coryan/google-cloud-cpp/security/code-scanning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7398)
=> ci: use CodeQL for security scans

google/cloud/bigtable/admin_client.cc, google/cloud/bigtable/client_options.h, google/cloud/bigtable/data_client.cc, google/cloud/bigtable/data_client.h, google/cloud/bigtable/instance_admin_client.cc
The main point of this change was to define `DefaultDataClient` and `DefaultAdminClient` in an anonymous namespace so they don't show up in our [docs](https://googleapis.dev/cpp/google-cloud-bigtable/latest/annotated.html). 
But then I got carried away making the clients conform. This means:
* moving `InstanceAdminTraits` definition into class
* removing untrue comment about early private section
* `(::)google::bigtable::v2` -> `btproto`
* `(::)google::bigtable::admin::v2` -> `btadmin`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7397)
=> cleanup(bigtable): make default clients conform

google/cloud/storage/tests/bucket_integration_test.cc
Seems like there is a rollout ongoing, which changes the default RPO
value returned for multi-region and dual-region buckets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7401)
=> test(storage): ignore RPO on insert

google/cloud/storage/testing/remove_stale_buckets.cc, google/cloud/storage/testing/remove_stale_buckets.h, google/cloud/storage/testing/remove_stale_buckets_test.cc, google/cloud/storage/testing/storage_integration_test.cc
Cleaning up any buckets with the `requester_pays==true` attribute
requires passing the `UserProject` option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7399)
=> test(storage): special cleanup for requester pay

google/cloud/pubsub/internal/defaults.cc, google/cloud/pubsub/internal/defaults.h, google/cloud/pubsub/internal/defaults_test.cc, google/cloud/pubsub/publisher_options.cc, google/cloud/pubsub/publisher_options_test.cc, google/cloud/pubsub/subscriber_options.cc, google/cloud/pubsub/subscriber_options_test.cc
When `PublisherOptions` is constructed, we default all options, including ones covered by `ConnectionOptions`, for example, `GrpcCredentialOption`.
https://github.com/googleapis/google-cloud-cpp/blob/c1a44cd759dcb0fd89293a558d759bdbb95c8f50/google/cloud/pubsub/publisher_options.cc#L25
https://github.com/googleapis/google-cloud-cpp/blob/c1a44cd759dcb0fd89293a558d759bdbb95c8f50/google/cloud/pubsub/internal/defaults.cc#L113
This means that when we merge options here ....
https://github.com/googleapis/google-cloud-cpp/blob/c1a44cd759dcb0fd89293a558d759bdbb95c8f50/google/cloud/pubsub/publisher_connection.cc#L94-L100
.... we try to merge user-set options contained in `ConnectionOptions` but ignore them because those options all have default values from `PublisherOptions`.
(I am saying we, but …
=> fix(pubsub): do not overwrite ConnectionOptions

google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc
Another instance of #7515.  Related to #7510.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7536)
=> test(spanner): bump create-database timeout from ~120s to ~300s

generator/internal/auth_decorator_generator.cc, google/cloud/bigquery/internal/bigquery_read_auth_decorator.cc, google/cloud/iam/internal/iam_auth_decorator.cc, google/cloud/iam/internal/iam_credentials_auth_decorator.cc, google/cloud/logging/internal/logging_service_v2_auth_decorator.cc
Auth decorators without a longrunning operations did not have a blank line before the closing namespace
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7543)
=> cleanup(generator): new line in auth cc

ci/cloudbuild/builds/lib/integration.sh
Some linux builds are failing with this error:
```
ERROR: Command errored out with exit status 128:
command: git clone --filter=blob:none -q git://github.com/googleapis/storage-testbench /tmp/pip-req-build-3egrh31a
cwd: None
Complete output (3 lines):
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
Link says: 
> If you’re having trouble cloning a repository, make sure the URL starts with `ssh://`, `https://`, or `git@github.com`
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7551)
=> ci: fix testbench install on linux

google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc, google/cloud/spanner/testing/database_integration_test.cc
Increase the time spent waiting for the creation of a test database
from 300 one-second polls to 600.  Indications are that the service
can just be slow on occasion.
See previous changes #7515 and #7536.  Related to #7510.
Also tweak the poll-loop termination condition to be more exacting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7549)
=> test(spanner): bump create-database timeout from ~300s to ~600s

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/object_basic_crud_integration_test.cc
I was confused about the JSON format for Object ids the wrong synthetic values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7559)
=> fix(GCS+gRPC): correct format Object ids

google/cloud/storage/tests/thread_integration_test.cc
I made this change because another PR #7563 keeps failing, and (1) that PR should not affect this test, (2) the failure is specific to one build, and (3) I am like :confused: and want to rule one some weird thing in Kokoro or something.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7564)
=> test(storage): reduce iterations in integration test

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session.cc, google/cloud/storage/object_metadata.cc, google/cloud/storage/tests/object_basic_crud_integration_test.cc
The JSON API provides links to the media and metadata contents of each
object as part of the object metadata. The gRPC API does not provide
such links. While not strictly necessary, I think it is nice to create
synthetic versions of these links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7563)
=> feat(GCS+gRPC): synthetic object metadata links

google/cloud/bigtable/tests/admin_backup_integration_test.cc, google/cloud/bigtable/tests/admin_iam_policy_integration_test.cc
These tests should use the table created by `TableTestEnvironment`, instead of creating/deleting another table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7566)
=> test(bigtable): create table once

google/cloud/bigtable/tests/admin_backup_integration_test.cc, google/cloud/bigtable/tests/admin_iam_policy_integration_test.cc, google/cloud/bigtable/tests/admin_integration_test.cc, google/cloud/bigtable/tests/instance_admin_integration_test.cc
I am going to copy the admin integration tests and convert them to test the generated API. This PR tidies up the tests so that the conversion step will be easier to grok.
Most of this is renaming. Some of it is functional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7569)
=> cleanup(bigtable): cleanup admin integration tests

google/cloud/bigtable/admin/integration_tests/admin_backup_integration_test.cc, google/cloud/bigtable/admin/integration_tests/admin_iam_policy_integration_test.cc, google/cloud/bigtable/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/bigtable/admin/integration_tests/table_admin_integration_test.cc
Fixes #7526 
Most of the changes in here involve methods that go from accepting an ID (e.g. `table-id` ) to accepting a full name (e.g. `projects/project-id/instances/instance-id/tables/table-id`)
There is also a change to the `WaitForConsistency` test in `table_admin_integration_test.cc`. Our generated clients do not have a method like `TableAdmin::WaitForConsistency`, so I implemented a simple version in a retry loop. I did not create an asynchronous retry loop, making asynchronous calls. It seemed too complicated, and I did not want to write a test to test the test.
Note that `bigtable/testing/table_integration_test.*` still uses the old APIs. That will be updated to the generated APIs in a future PR.
--- …
=> test(bigtable): convert admin integration tests to use generated code

google/cloud/storage/internal/grpc_client.cc
The `GOOGLE_STORAGE_GRPC_ENDPOINT` environment variable can be used to
override the default gRPC endpoint. This is mostly used for tests using
the testbench, and thus defaulted to also switching the credentials to
insecure credentials.  With this change the credentials are kept
unchanged unless you also set `CLOUD_STORAGE_EMULATOR_ENDPOINT`. If that
is set you definitely want to use the emulator and the credentials must
be changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7572)
=> feat(GCS+gRPC): endpoint overrides with secure credentials

google/cloud/bigtable/admin/integration_tests/admin_backup_integration_test.cc, google/cloud/bigtable/admin/integration_tests/admin_iam_policy_integration_test.cc, google/cloud/bigtable/admin/integration_tests/table_admin_integration_test.cc, google/cloud/bigtable/testing/table_integration_test.cc, google/cloud/bigtable/testing/table_integration_test.h
Part of the work for #7528 
Note that deleting the member variables for `admin_client_` and `table_admin_` does not affect the old tests, because the member variables are also defined in the derived classes like `AdminBackupIntegrationTest`.
(I probably should have included this change with the last PR)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7574)
=> cleanup(bigtable): implement `TableIntegrationTest` using preferred API

google/cloud/storage/tests/thread_integration_test.cc
The changes to make this test pass on macOS accidentally made it slower
on machines with lots of cores (such as my workstation).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7576)
=> test(storage): speed up thread_integration_test

generator/generator.cc, generator/generator_config.proto, generator/generator_config.textproto, generator/internal/codegen_utils.cc, generator/internal/codegen_utils_test.cc, generator/standalone_main.cc
Sometimes a single `service_proto_path` defines multiple
services, but we don't want to generate all of them.
Use this to omit generation of "BigQueryWrite".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7583)
=> feature(generator): add support for "omitted_services"

.codecov.yml
Ignore directories containing generated code.  This also ignores
some hand-written pieces like `integration_tests` and `samples`,
but we're not particularly interested in coverage data for those
either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7585)
=> ci: ignore generated code in coverage build

google/cloud/spanner/row.cc, google/cloud/spanner/row.h, google/cloud/spanner/row_test.cc
@devbww and I debugged a use-after move issue that boiled down to these
two Row iterators inspecting a data member (e.g., `row_` and `tup_`) on
subsequent invocations of `op++`, after a caller may have rightfully
moved the object. To avoid this issue, we keep an extra bool in both
iterators to avoid the need to inspect the StatusOr data member again.
Note: This issue didn't show up in our code or builds. It showed up only
when trying to make a different change to `Status`.
Kudos to @devbww for helping to track this down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7588)
=> fix(spanner): avoid use-after-move bugs

google/cloud/spanner/row.h
`g::c::spanner::GetSingularRow` extracts and moves the singular row in
the given range, and so it should not take the argument by forwarding
reference, because the caller may pass an lvalue, and it
would be surprising if this function moved a value out of the named
lvalue in the calling function.
Accepting the range by value fixes this by either forcing a copy at the
call site if the caller has an lvalue that they don't want to be
modified, or else the caller can `std::move` the argument, in which case
no copies of the row will be performed -- only moves. I think this is
the best way to make the function unsurprising and allow the caller to
avoid all copies.
--- …
=> fix(spanner): GetSingularRow accepts by value

generator/integration_tests/generator_integration_test.cc, generator/internal/service_code_generator.cc
Allow `<service>.<method>` names in the `omitted_rpcs` and
`gen_async_rpcs` lists (in addition to just `<method>`) for
cases where two services defined in the same file share an
RPC name, but we want to treat the RPCs differently.
This isn't anything we need now, but is something I considered
during the recent `omitted_services` change, and it seemed best
to provide the groundwork while I had it in mind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7586)
=> feat(generator): support service-qualified names in RPC lists

generator/integration_tests/golden/golden_kitchen_sink_connection.cc, generator/integration_tests/golden/golden_thing_admin_connection.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc, generator/internal/connection_generator.cc, google/cloud/bigquery/bigquery_read_connection.cc, google/cloud/bigtable/admin/bigtable_instance_admin_connection.cc, google/cloud/bigtable/admin/bigtable_table_admin_connection.cc, google/cloud/iam/iam_connection.cc, google/cloud/iam/iam_credentials_connection.cc, google/cloud/logging/logging_service_v2_connection.cc, google/cloud/spanner/admin/database_admin_connection.cc, google/cloud/spanner/admin/instance_admin_connection.cc
Check expected options passed to the `Connection`
I don't think it is necessary to add a checks in the `internal::MakeConnection` methods
Note that the test in `golden_thing_admin_connection_test.cc` has a different name than other tests in the file. There is a [separate PR](https://github.com/googleapis/google-cloud-cpp/pull/7590) to change the current test names to be `GoldenThingAdminConnectionTest`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7591)
=> cleanup(generator): log unexpected options

ci/cloudbuild/builds/cmake-install.sh, ci/etc/full_feature_list, generator/standalone_main.cc
When adding new generated libraries we need to update the feature list
used by the CI builds (currently just `cmake-install`). With this change
that update is automated, reducing the work for each library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7599)
=> feat: automatically update feature list

cmake/GoogleCloudCppCommon.cmake, generator/scaffold/CMakeLists.txt.in, google/cloud/CMakeLists.txt, google/cloud/bigquery/CMakeLists.txt, google/cloud/bigtable/CMakeLists.txt, google/cloud/iam/CMakeLists.txt, google/cloud/logging/CMakeLists.txt, google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsublite/CMakeLists.txt, google/cloud/spanner/CMakeLists.txt, google/cloud/storage/CMakeLists.txt
So far, we have been recursively scanning the source directory of each
library and then excluding some files. This is tedious, particularly in
the opt-level `google/cloud` directory. And also brittle, as adding a
new directory requires changes in multiple places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7596)
=> cleanup: explicitly list Doxygen sources

BUILD, ci/cloudbuild/builds/cmake-install.sh, ci/etc/expected_install_directories, ci/etc/full_feature_list, doc/adding_new_libraries.md, generator/generator_config.textproto, google/cloud/pubsublite/BUILD, google/cloud/pubsublite/CMakeLists.txt, google/cloud/pubsublite/README.md, google/cloud/pubsublite/config.cmake.in, google/cloud/pubsublite/google_cloud_cpp_pubsublite.bzl, google/cloud/pubsublite/google_cloud_cpp_pubsublite_mocks.bzl, google/cloud/pubsublite/retry_traits.h
This makes the Pub/Sub library usable, though it is still marked as
"experimental".
This grows my little script to create new libraries a little bit. I
think I will remove it soon (the script, `create_scaffold.cmake`), but I
want to unblock Pub/Sub Lite, so here we are.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7602)
=> feat: enable the Pub/Sub Lite library

generator/internal/scaffold_generator.cc
Some services have multiple variants, like `google/cloud/tasks/v2` and
`google/cloud/tasks/v2beta3`. This change prevents the second directory
to match as we search the JSON object for the entry containing a given
proto file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7611)
=> fix(generator): more precise matching of directories

google/cloud/internal/async_polling_loop.cc, google/cloud/spanner/samples/samples.cc
Get a little visibility into the LRO polling loop in the tracing
log, most notably to see how long we are waiting between polls.
Part of #7562.  The issue looks important, and after failing to
diagnose the problem from the two occurrences we've seen so far,
and failing to reproduce it, the next best thing is to try to
get a little bit more data when it happens again.
And also to that end, add a timestamp to the beginning of each
of the Spanner samples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7615)
=> feat(common): add tracing for the LRO polling loop

google/cloud/bigquery/doc/bigquery-read-mock.dox, google/cloud/iam/doc/iam-credentials-mock.dox, google/cloud/iam/doc/iam-mock.dox, google/cloud/log_test.cc, google/cloud/pubsub/doc/publisher-mock.dox, google/cloud/pubsub/doc/subscriber-mock.dox
`googletest` has changed its default branch name and the
location of its docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7621)
=> doc: update https://github.com/google/googletest links

google/cloud/status.h, google/cloud/status_test.cc
With this PR, `google::cloud::Status` now ignores the `message` it's constructed with if the `code` is OK. This behavior matches `absl::Status` (which we don't use, but FWIW). We believe the previous behavior where the message was _not_ dropped on OK statuses was a bug, because that can result in "OK" Statuses being not equal. Consider:
```cc
Status ok1{StatusCode::kOk, ""};
Status ok2{StatusCode::kOk, "blah"};
assert(ok1.ok() && ok2.ok());
assert(ok1 != ok2);  // OLD BEHAVIOR -- CONSIDERED A BUG
assert(ok1 == ok2);  // NEW BEHAVIOR -- ALL OKs ARE EQUIVALENT
```
This new behavior differs from `grpc::Status`, which _does_ allow message strings on an OK status. But I imagine this is an oversight due to how it was implemented, and not actually desired behavior.
Requiring that all OK statuses …
=> refactor(common): Status ignores message if code==OK

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc, google/cloud/spanner/samples/samples.cc
Instance labels give us the flexibility to control where tests
are run through configuration, which we're using to temporarily
avoid regions with high contention.
* Use "samples:yes" for //google/cloud/spanner/samples:samples.
* Allow "restore-database-partition:all", mostly for the staging
service where we don't have enough instance quota for the four
`{generated,legacy}-{core,extra}` backup/restore partitions.
Also change to using explicit AND operators in the filters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7626)
=> test(spanner): expand use of test instance labelling

ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh
Leave a breadcrumb for a simple edit to use the staging service when
testing new Spanner features.  In the future we may want to support
plumbing this through from `build.sh`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7627)
=> ci: hint for using the Spanner staging service for integration tests

google/cloud/internal/throw_delegate_test.cc, google/cloud/status.h, google/cloud/status_or_test.cc, google/cloud/status_test.cc, google/cloud/storage/benchmarks/throughput_result_test.cc, google/cloud/storage/internal/logging_resumable_upload_session_test.cc, google/cloud/testing_util/status_matchers_test.cc
Upcoming we are going to implement a change where we sometimes log
additional "error info" data when streaming a Status object. This
additional data will have newlines in it, and it would seem weird if
status code came last one the final line of the logged message. It
seems more natural for the streamed output to start with the code,
followed by the message, and any additional data. This format also
matches `absl::Status`, fwiw.
I'm not picky about the specific format syntax. I chose something like
`UNKNOWN: some message`, but I'd be just as happy to go back to using
square brackes around the code, with or without a colon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google- …
=> refactor: g::c::Status now logs code first then message

google/cloud/storage/client.h, google/cloud/storage/client_notifications_test.cc, google/cloud/storage/examples/storage_notification_samples.cc
Fixes #1098 
I tried to use `@copydoc` but it does not render correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7633)
=> feat(storage): default payload format for CreateNotification

google/cloud/storage/client.h, google/cloud/storage/client_test.cc
We did not have `operator==` and `operator!=` defined for this class.
Other `*Client` classes have this operator, and it will be useful when I
try to describe connection pooling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7634)
=> feat(storage): `storage::Client` is a value type

google/cloud/stream_range.h
Similar to: #7588
This code allowed callers to (rightfully) move-out the `StatusOr` that
was held in `current_`. Therefore, it's a bug if we then consult the
status of `current_.ok()`, because it may be in a moved-from state.
The fix is to track the `current_ok_` bit separately, so that we only
ever assign to `current_` and never read it after it could have been
moved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7635)
=> fix: avoid use-after-move StatusOr

google/cloud/bigtable/app_profile_config.cc, google/cloud/bigtable/app_profile_config.h, google/cloud/bigtable/app_profile_config_test.cc
I needed an easy win today, so add support for [multi-cluster routing](https://cloud.google.com/bigtable/docs/app-profiles#routing) in Bigtable, in accordance with [this proto change](https://github.com/googleapis/googleapis/commit/5f761138c64054797b7e25164798d573ff4c1c62#diff-712127d2a900984d269e05e237ccc6552f798034cd7d97256374e12cfb8da77cR198-R202).
Now you can specify an exact subset of clusters to route to when using multi-cluster routing. Providing no clusters to the multi-cluster routing remains the same, routing to the nearest cluster in the instance.
As far as I can tell, there are no snippets needed for this update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/googl …
=> feat(bigtable): add multi-cluster routing for specific clusters

google/cloud/status.cc, google/cloud/status.h, google/cloud/status_or.h, google/cloud/status_or_test.cc, google/cloud/status_test.cc
Related to: https://github.com/googleapis/google-cloud-cpp/issues/7429
Background: "OK" statuses are the common case, and they don't have message strings,
payload data, etc. Only non-OK Statuses need this extra data, so paying
the cost of these fields for OK statuses is wasteful.
This PR refactors `google::cloud::Status` to hold an opaque `Impl*` that
holds all the error data for non-OK statuses. OK statuses are
represented by `impl_ == nullptr`, which requires no allocations (again,
this is the common case). This allows us to associate whatever data we
need with non-OK Statuses without hurting the OK case.
**What's the moved-from state?** We continue to not define the moved-from state for
`Status`. It's a valid state, but unspecified. However, the implementation in this PR
is such that …
=> refactor: optimize Status moving error data to heap-allocated Impl

google/cloud/storage/client.h
Fixes #1554
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7637)
=> doc(storage): describe connection pool

doc/adding_new_libraries.md, generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator_test.cc, google/cloud/pubsublite/CMakeLists.txt, google/cloud/tasks/CMakeLists.txt
The generated `CMakeLists.txt` files can use `file(GLOB)` to eliminate
the need to edit most generated files. We still can edit these files, of
course, but now it is not required in most cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7641)
=> feat(generator): reduce required editing on scaffold

external/googleapis/CMakeLists.txt, external/googleapis/protodeps/texttospeech.deps, external/googleapis/protolists/texttospeech.list, external/googleapis/update_libraries.sh
Use a script to generate the dependencies (as text files) and some CMake
functions to load them. Same format as we use for the generated
libraries scaffold.
I think this will fix the CI flakes.  Obviously it could be used to fix / automate
other libraries. I will do that later, I just want to get a fix out ASAP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7643)
=> fix: update texttospeech proto library deps

google/cloud/BUILD, google/cloud/CMakeLists.txt, google/cloud/grpc_error_delegate.cc, google/cloud/grpc_error_delegate_test.cc, google/cloud/status.cc, google/cloud/status.h, google/cloud/status_test.cc
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/7429
This PR adds a `google::cloud::ErrorInfo` class, which mirrors
[ErrorInfo][error-info-proto], and can also work with an equivalent
type in a REST world. We expose programmatic access to this via the
`g::c::Status::error_info()` accessor. We also log this data when
streaming a `g::c::Status` if it's present.
As of today, very few (if any) GCP services actually return this proto,
so I don't expect to see it much yet.
Alternative options:
* We could move `ErrorInfo` into it's own `error_info.h` file. It's pretty closely related to `Status`, so I'm OK w/ it where it is, but I'm also happy to move it if people think that's preferable.
* We can discuss the logging format that we want to use when streaming the `ErrorInfo`. I chose …
=> feat: expose and log ErrorInfo if present 

google/cloud/spanner/testing/pick_random_instance.cc
Avoid incorrect grouping of complex user filters with the
instance-name conjunction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7645)
=> test(spanner): parenthesize the user-supplied instance filter

google/cloud/spanner/samples/samples.cc
When no instance configs match our `included_prefix - excluded`
criteria, we return one anyway.  Previously we returned the first
one we saw during the enumeration, but now we return the last.
This only makes a practical difference when running against the
Spanner staging service, where we want to favor `us-central1`
over `cloud-devel-global-config`.
In the longer run we probably want to avoid having any criteria
or default favorites encoded in the source, and instead specify
our preferences using configuration data.  But in the short term
this restores the ability to test using the staging service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7646)
=> test(spanner): use the last instance config as the PickConfig() default

ci/cloudbuild/dockerfiles/ubuntu-focal.Dockerfile, ci/cloudbuild/triggers/quickstart-bazel-ci.yaml, ci/cloudbuild/triggers/quickstart-bazel-pr.yaml, ci/cloudbuild/triggers/quickstart-cmake-ci.yaml, ci/cloudbuild/triggers/quickstart-cmake-pr.yaml
Update the docker image for `quickstart-*` builds to Ubuntu:20.04
(Focal). This includes a newer version of CMake that I want to use to
parallelize the CMake-based builds. I also upgraded the Bazel build for
consistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7647)
=> ci: update quickstart build image

.cmake-format.py, ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/builds/lib/quickstart.sh, ci/cloudbuild/builds/quickstart-cmake.sh, ci/cloudbuild/builds/shared.sh, ci/verify_quickstart/CMakeLists.txt
Each quickstart build compiles a single file with CMake, running them
sequentially is wasteful, and will not scale if we add quickstarts for
generated libraries.
We could try something similar for quickstart + Bazel.  My first attempts
did not work well as each `bazel build` invocation compiles all the
dependencies (Abseil, gRPC, protobuf) in parallel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7648)
=> ci: parallelize CMake quickstart builds

ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, doc/packaging.md
Same problem as Fedora, the default `pkgconfig` tool is slow with some
Abseil libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7651)
=> ci: speedup Rocky Linux build

google/cloud/storage/internal/http_response.cc, google/cloud/storage/internal/http_response_test.cc
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/7644
Follows https://cloud.google.com/apis/design/errors#http_mapping and parses the "error info" json object from responses when it's available, and uses it to set the fields of the returned `g::c::Status`.
**Note to reviewers**: I'm new to using nlohmann::json, so please review that code closely and tell me what I'm doing wrong. I may be doing things very inefficiently or not following the right best practices. Please let me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7654)
=> feat: GCS parse "error info" from JSON when available

generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/golden_thing_admin_client.h, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, google/cloud/bigquery/bigquery_read_client.h, google/cloud/bigtable/admin/bigtable_instance_admin_client.h, google/cloud/bigtable/admin/bigtable_table_admin_client.h, google/cloud/iam/iam_client.h, google/cloud/iam/iam_credentials_client.h, google/cloud/logging/logging_service_v2_client.h, google/cloud/pubsublite/admin_client.h, google/cloud/spanner/admin/database_admin_client.h, google/cloud/spanner/admin/instance_admin_client.h, google/cloud/tasks/cloud_tasks_client.h
Changed doxygen comments to use `///` in lieu of `/**` and `*/` to try and avoid misformatting from wrapped comments containing `/*` sequences.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7652)
=> chore(generator): change doxygen commnent character sequence

google/cloud/storage/client_options.cc, google/cloud/storage/client_options.h, google/cloud/storage/client_options_test.cc, google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request.h, google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/internal/curl_request_builder.h, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/options.h
Use a separate option for download timeouts.  Some customers need to
tune the downloads differently than other operations.
Fixes #7613
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7655)
=> feat(storage): separate option for download timeouts

google/cloud/storage/client_write_object_test.cc, google/cloud/storage/internal/resumable_upload_session.cc, google/cloud/storage/internal/resumable_upload_session_test.cc, google/cloud/storage/internal/retry_resumable_upload_session.cc, google/cloud/storage/internal/retry_resumable_upload_session.h, google/cloud/storage/internal/retry_resumable_upload_session_test.cc
Our debug message on session rewinds (i.e., when the "last committed
byte" goes backwards) was not sufficient. Adding some additional
debugging to make it easier to troubleshoot, should this ever happen
again.
Fixes #7610
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7662)
=> feat(storage): better debugging for session rewinds

cmake/GoogleapisConfig.cmake, generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/golden_thing_admin_client.h, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, google/cloud/bigquery/bigquery_read_client.h, google/cloud/bigtable/admin/bigtable_instance_admin_client.h, google/cloud/bigtable/admin/bigtable_table_admin_client.h, google/cloud/iam/iam_client.h, google/cloud/iam/iam_credentials_client.h, google/cloud/logging/logging_service_v2_client.h, google/cloud/pubsublite/admin_client.h, google/cloud/secretmanager/secret_manager_client.h, google/cloud/spanner/admin/database_admin_client.h, google/cloud/spanner/admin/instance_admin_client.h, google/cloud/tasks/cloud_tasks_client.h
The protobuf documentation seems to use reference-style markdown links
for protos in the comments, i.e., each reference to `Foo` is formatted
as `[Foo][google.blah.blah.v1.Foo]`.  This formatting is very
distracting if left verbatim, but it can be turned into a link if we
define `google.blah.blah.v1.Foo` as a link reference in Doxygen's
markdown.
With this change the input and output types of each method get such
reference link definitions. The definitions themselves are not visible,
but they make the generated Doxygen output easier to read.
This does not solve the problem when the referenced entity is not an
input or output type of the method, or when it references another
method. But it works in enough cases to make the change worthwhile.
---
This change …
=> feat(generator): link each method input and output types

generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/golden_thing_admin_client.h, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, google/cloud/bigquery/bigquery_read_client.h, google/cloud/iam/iam_client.h, google/cloud/iam/iam_credentials_client.h, google/cloud/logging/logging_service_v2_client.h, google/cloud/pubsublite/admin_client.h, google/cloud/secretmanager/secret_manager_client.h, google/cloud/spanner/admin/database_admin_client.h, google/cloud/spanner/admin/instance_admin_client.h, google/cloud/tasks/cloud_tasks_client.h
Customers often wonder about the performance, thread-safety, and
connection pooling in our `*Client` classes. This changes the generator
to include this information in the generated code.
Fixes #7672
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7673)
=> feat(generator): document details about `*Client`

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7675)
=> doc: update CHANGELOG for v1.34.0 release

google/cloud/internal/async_connection_ready.cc, google/cloud/internal/async_read_stream_impl.h, google/cloud/internal/async_read_write_stream_impl.h, google/cloud/internal/async_retry_loop_test.cc, google/cloud/internal/async_rpc_details.h, google/cloud/internal/default_completion_queue_impl.cc, google/cloud/options.cc, google/cloud/options.h, google/cloud/options_test.cc, google/cloud/testing_util/fake_completion_queue_impl.cc
Provide access to the prevailing `Options` for an operation without having
to plumb function parameters through the various and sundry layers, like
connection.
This also means that helper libraries can determine things like whether a
tracing component is enabled, without having to distort their APIs.
For example, if all `ServiceClient::Operation()` calls are implemented like
```
class ServiceClient {
public
ServiceClient(std::shared_ptr<ServiceConnection> connection,
Options options = {})
: connection_(std::move(connection)),
options_(ServiceDefaultOptions(std::move(options))) {}
T Operation(..., Options options = {}) {
internal::OptionsSpan span(internal::MergeOptions(options, options_));
...
}
private:
std::shared_ptr<ServiceConnection> connection_;
Options options_;
};
```
then the …
=> feat(common): add support for call-tree-specific options

external/googleapis/CMakeLists.txt
Old versions of protobuf (prior to 3.15, we require 3.15.8) generated
code that could not be compiled with older compilers (GCC < 6, we
require >= 6.x). In other words, this workaround is not necessary for
two reasons, we can safely remove it I think.
Fixes #5660
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7681)
=> cleanup: remove workaround for old protobuf+compiler

CMakeLists.txt
Add warnings when the library is configured with a compiler we do not
test with, and fatal messages for versions where we know our
dependencies won't work.
I also made some cosmetic fixes to the top-level CMakeLists.txt file,
just to make it more readable for us.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7684)
=> cleanup: warn about untested compiler versions

google/cloud/bigtable/instance_admin.cc
Fixes #3756
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7685)
=> cleanup(bigtable): remove workaround for old protobuf versions

ci/cloudbuild/builds/cmake-install.sh, ci/etc/expected_install_directories, generator/integration_tests/golden/golden_kitchen_sink_client.cc, generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/golden_thing_admin_client.cc, generator/integration_tests/golden/golden_thing_admin_client.h, generator/internal/client_generator.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, google/cloud/bigquery/bigquery_read_client.cc, google/cloud/bigquery/bigquery_read_client.h, google/cloud/iam/iam_client.cc, google/cloud/iam/iam_client.h, google/cloud/iam/iam_credentials_client.cc, google/cloud/iam/iam_credentials_client.h, google/cloud/logging/logging_service_v2_client.cc, google/cloud/logging/logging_service_v2_client.h, google/cloud/pubsublite/admin_client.cc, google/cloud/pubsublite/admin_client.h, google/cloud/secretmanager/secret_manager_client.cc, google/cloud/secretmanager/secret_manager_client.h, google/cloud/spanner/admin/database_admin_client.cc, google/cloud/spanner/admin/database_admin_client.h, google/cloud/spanner/admin/instance_admin_client.cc, google/cloud/spanner/admin/instance_admin_client.h, google/cloud/tasks/cloud_tasks_client.cc, google/cloud/tasks/cloud_tasks_client.h
The generated client constructor now takes a defaulted `Options` argument,
which is merged with the default options for the service, and then stored
as a member.
Similarly, the generated client operations also take a defaulted `Options`
argument, which is then merged with the client options from above, and
installed as the prevailing options for the duration of the operation by
instantiating an `OptionsSpan`.
Any module within the scope of that operation, or its continuations, can
then retrieve those prevailing options.  So, for example, a metadata
decorator could add a header based on a per-operation option, or a retry
policy might modify its behavior based on another option.
--- …
=> feat(generator): add options support to generated clients

CHANGELOG.md, google/cloud/bigtable/rpc_backoff_policy.cc, google/cloud/bigtable/rpc_backoff_policy.h, google/cloud/bigtable/rpc_backoff_policy_test.cc, google/cloud/internal/backoff_policy.cc, google/cloud/internal/backoff_policy.h, google/cloud/internal/backoff_policy_test.cc
When calling `.clone()` on an exponential backoff policy, copy the initial state instead of the current state. This may result in a change of behavior, but we see it as a bug that ought to be fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7696)
=> fix(common): backoff policy clones initial state

google/cloud/bigtable/testing/table_test_fixture.h, google/cloud/internal/async_read_write_stream_auth.h, google/cloud/internal/async_read_write_stream_auth_test.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc, google/cloud/pubsub/internal/subscriber_auth.cc, google/cloud/pubsub/internal/subscriber_auth.h, google/cloud/pubsub/internal/subscriber_auth_test.cc, google/cloud/pubsub/internal/subscriber_logging.cc, google/cloud/pubsub/internal/subscriber_logging.h, google/cloud/pubsub/internal/subscriber_metadata.cc, google/cloud/pubsub/internal/subscriber_metadata.h, google/cloud/pubsub/internal/subscriber_round_robin.cc, google/cloud/pubsub/internal/subscriber_round_robin.h, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h, google/cloud/pubsub/testing/mock_subscriber_stub.h
Also fix a bug where if it was cancelled while auth was being set up, neither the spawning context nor the created stream would be cancelled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7692)
=> fix(pubsub): Change AsyncReadWriteStreamAuth to be usable with unique_ptr

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_common.bzl, google/cloud/internal/non_constructible.h, google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsub/google_cloud_cpp_pubsub.bzl, google/cloud/pubsub/publisher_connection.cc, google/cloud/pubsub/publisher_connection.h, google/cloud/pubsub/schema_admin_connection.cc, google/cloud/pubsub/schema_admin_connection.h, google/cloud/pubsub/subscriber_connection.cc, google/cloud/pubsub/subscriber_connection.h, google/cloud/pubsub/subscription_admin_connection.cc, google/cloud/pubsub/subscription_admin_connection.h, google/cloud/pubsub/topic_admin_connection.cc, google/cloud/pubsub/topic_admin_connection.h
This type will be generally useful when converting interfaces to
use `google::cloud::Options`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7701)
=> chore: move non_constructible.h to google/cloud/internal

google/cloud/spanner/integration_tests/session_pool_integration_test.cc, google/cloud/spanner/internal/logging_spanner_stub.cc, google/cloud/spanner/internal/logging_spanner_stub.h, google/cloud/spanner/internal/metadata_spanner_stub.cc, google/cloud/spanner/internal/metadata_spanner_stub.h, google/cloud/spanner/internal/session_pool.cc, google/cloud/spanner/internal/session_pool.h, google/cloud/spanner/internal/session_pool_test.cc, google/cloud/spanner/internal/spanner_stub.cc, google/cloud/spanner/internal/spanner_stub.h, google/cloud/spanner/testing/mock_spanner_stub.h
Prefer `AsyncRetryLoop` which uses our `CompletionQueue` instead of the `grpc::CompletionQueue`. The mocks are also nicer.
With this PR, the only remaining uses of `StartRetryAsyncUnaryRpc` are in Bigtable. Eventually they will be removed as part of the effort to modernize Bigtable.
Also change the return type of `SessionPool::AsyncDeleteSession` to drop the `protobuf::Empty`. This function is not called outside of an integration test at the moment, but we plan to use it later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7704)
=> refactor(spanner): prefer AsyncRetryLoop to StartRetryAsyncUnaryRpc

google/cloud/storage/tools/run_emulator_utils.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7712)
=> ci: always print emulator log on errors

ci/cloudbuild/builds/lib/integration.sh, google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
Always install the storage emulator in $HOME/.local, so we can predict
where all its files are, and we can clean up before an install.  Ensure
the test cache is invalidated by newer versions of the storage emulator.
Part of the work for #7677
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7713)
=> ci: storage emulator and caching

google/cloud/storage/CMakeLists.txt
We were missing a direct dependency on Windows. It probably went
unnoticed because in our tests we get this dependency indirectly. It is
important for Conda support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7718)
=> fix: missing dependency for WIN32

google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/object_read_source.h, google/cloud/storage/internal/object_read_streambuf.cc, google/cloud/storage/internal/object_read_streambuf.h, google/cloud/storage/object_read_stream.h, google/cloud/storage/tests/object_read_headers_integration_test.cc
A lot of useful metadata information is included the the metadata
headers for a GCS download over REST, and as an initial `Object` proto
for gRPC. This information is needed to perform consistent reads from
versioned objects (or detect inconsistent reads from objects without
versioning).  I will need this information as part of the changes for
Arrow too.
Fixes #7677
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7694)
=> feat(storage): capture metadata info in downloads

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc, google/cloud/spanner/commit_options.cc, google/cloud/spanner/commit_options.h, google/cloud/spanner/commit_options_test.cc, google/cloud/spanner/google_cloud_cpp_spanner.bzl, google/cloud/spanner/options.h, google/cloud/spanner/samples/samples.cc
Part of #7690 to add an `Options opts = {}` argument to `Commit()`
and `Rollback()` operations.  Add new `TransactionTagOption` and
`CommitReturnStatsOption` types to accompany `RequestPriorityOption`.
This means the caller no longer needs `CommitOptions` (although it is
still used in the `Connection` layer).
Run the `Client` options through `spanner_internal::DefaultOptions()`.
Note that per-operation options strictly override those client-level
options.
Add `OptionsSpan` local variables to `Commit()` and `Rollback()`
(and also `ExecuteBatchDml()`, which already took plain `Options`).
Clarify which constructor and operation overloads are for backwards
compatibility so that they will be easier to deprecate/remove later.
Also clarify some doxygen comments about `Options` parameters. …
=> feat(spanner): add per-operation options to Commit() and Rollback()

google/cloud/storage/tests/service_account_integration_test.cc
Fixes #3806.  The internal bug was fixed circa 2019-07-01
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7723)
=> cleanup(storage): remove old workaround for HMAC keys

google/cloud/internal/filesystem.h, google/cloud/internal/filesystem_test.cc
Part of: https://github.com/googleapis/google-cloud-cpp/issues/2310
`google::cloud::internal::file_status` is a value type supporing
assignment and therefore should also support equality. And indeed since
C++20, the std version does as well: https://en.cppreference.com/w/cpp/filesystem/file_status/operator%3D%3D
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7724)
=> feat: file_status supports op==

google/cloud/bigtable/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/bigtable/tests/instance_admin_emulator.cc
If you try to delete an app profile, the Bigtable service will not take you seriously unless you set ignore warnings to true.
This change makes the instance admin emulator better reflect the functionality of the service. It also updates the integration test to set ignore warnings. (I did not realize this before, because the test is not run against production; only the emulator).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7725)
=> test(bigtable): ignore warning when deleting app profile

generator/internal/scaffold_generator.cc
Some simple tools won't like (what looks like) a line in a cc file
beginning with a horizontal tab.  Here it is really part of a multi-
line raw string literal, so we can simply replace it with `\t`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7726)
=> chore(generator): use an escape sequence instead of a literal tab

google/cloud/spanner/client_options.cc, google/cloud/spanner/client_options_test.cc, google/cloud/spanner/options.h, google/cloud/spanner/query_options.cc, google/cloud/spanner/query_options_test.cc
Revisit a decision from a few days ago on the naming of the Spanner
optimizer options, before they find more widespread release.  To wit,
```
s/RequestOptimizer/QueryOptimizer/
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7728)
=> ore(spanner): rename spanner optimizer options

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/bigtable_client_testing.bzl, google/cloud/bigtable/doc/bigtable-samples-grpc-credentials.dox, google/cloud/bigtable/examples/bigtable_examples_common.cc, google/cloud/bigtable/examples/bigtable_examples_common.h, google/cloud/bigtable/examples/bigtable_examples_common_test.cc, google/cloud/bigtable/examples/bigtable_hello_app_profile.cc, google/cloud/bigtable/examples/bigtable_hello_instance_admin.cc, google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc, google/cloud/bigtable/testing/cleanup_stale_resources.cc, google/cloud/bigtable/testing/cleanup_stale_resources.h, google/cloud/bigtable/testing/cleanup_stale_resources_test.cc
Part of the work for #7528 
Some things to note:
* In `examples/bigtable_instance_admin_snippets.cc`, the project ID was previously consumed by `InstanceAdmin`. With the generated APIs, we have to pass it to each command. This explains some of the changes around the argument parsing.
* Funcitonal change to `TestIamPermissions`. Previously it was only used for testing permissions on an instance (so the inputs were project ID, instance ID). Now we test permissions on any resource by passing in the fully qualified resource name. (so you can test permissions for a cluster).
* Oh and I decided to just add the Table Admin mocks now alongside the Instance Admin mocks, even though they aren't used yet.
--- …
=> cleanup(bigtable): prefer generated instance admin API

google/cloud/bigtable/testing/cleanup_stale_resources.cc, google/cloud/bigtable/testing/cleanup_stale_resources_test.cc
I introduced this bug in #7729. `ListInstances` expects a project name. It should not be passed an instance name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7731)
=> cleanup(bigtable): fix cleanup of stale instances

ci/cloudbuild/builds/lib/integration.sh
Since, #7737, Cloud SDK now has @coryan's bigtable emulator fixes. It should be safe to remove the workaround now.
Fixes #441 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7738)
=> ci: remove bigtable emulator retry loop

ci/cloudbuild/builds/lib/integration.sh
Reverts googleapis/google-cloud-cpp#7738
We saw a bunch of flakes related to `bigtable/examples/table_admin_snippets.cc`. Let's cover them up with the retry loop for now, while I investigate further.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7739)
=> Revert "ci: remove bigtable emulator retry loop"

generator/integration_tests/golden/golden_kitchen_sink_client.cc, generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/golden_thing_admin_client.cc, generator/integration_tests/golden/golden_thing_admin_client.h, generator/internal/client_generator.cc, google/cloud/bigquery/bigquery_read_client.cc, google/cloud/bigquery/bigquery_read_client.h, google/cloud/bigtable/admin/bigtable_instance_admin_client.cc, google/cloud/bigtable/admin/bigtable_instance_admin_client.h, google/cloud/bigtable/admin/bigtable_table_admin_client.cc, google/cloud/bigtable/admin/bigtable_table_admin_client.h, google/cloud/iam/iam_client.cc, google/cloud/iam/iam_client.h, google/cloud/iam/iam_credentials_client.cc, google/cloud/iam/iam_credentials_client.h, google/cloud/logging/logging_service_v2_client.cc, google/cloud/logging/logging_service_v2_client.h, google/cloud/pubsublite/admin_client.cc, google/cloud/pubsublite/admin_client.h, google/cloud/secretmanager/secret_manager_client.cc, google/cloud/secretmanager/secret_manager_client.h, google/cloud/spanner/admin/database_admin_client.cc, google/cloud/spanner/admin/database_admin_client.h, google/cloud/spanner/admin/instance_admin_client.cc, google/cloud/spanner/admin/instance_admin_client.h, google/cloud/tasks/cloud_tasks_client.cc, google/cloud/tasks/cloud_tasks_client.h
It is nicer to have the signature-extension operations generated
right next to their request-proto overloads.  This is particularly
true in the client header, which we expect customers to read.
The only true edit is `generator/internal/client_generator.cc`.
The remainder of the PR is updated golden files and regenerated
service interfaces.
Fixes #5997
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7743)
=> chore(generator): colocate client operation overloads

google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc, google/cloud/spanner/samples/samples.cc
Check that the metadata is of the desired type in the left-hand
side of the `ListBackupOperations()` filter AND expression, before
looking at its value.
This appears to be a recent change in behavior for the production
service, which previously accepted the original ordering, but now
would say: "INVALID_ARGUMENT: Invalid ListBackupOperations request."
Also change the filter subexpressions to be exact matches, rather
than just "contains", so as to make the filtering more precise.
Finally, take this opportunity to log the name of running sample,
which makes it easier to delineate the RPC log.
Fixes #7741.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7746)
=> fix(spanner): switch order of ListBackupOperations() filter conjuncts

google/cloud/bigtable/tests/data_integration_test.cc, google/cloud/bigtable/tests/filters_integration_test.cc, google/cloud/bigtable/tests/mutations_integration_test.cc
Part of #151 
The bigtable emulator can now handle these tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7758)
=> test(bigtable): run a few more tests against emulator

generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc, google/cloud/internal/async_long_running_operation_test.cc, google/cloud/internal/async_polling_loop.cc, google/cloud/internal/async_polling_loop_test.cc
* Do not drop a cancellation request made before we receive
the `longrunning::Operation`.
Instead, remember that a cancellation request was made,
and then cancel the operation once we know it has started.
This (probabilistically) saves a significant chunk of time
in the `spanner_cancel_backup_create` sample, as we now
always cancel the `CreateBackup()`.
* Do not fabricate a cancelled `Status`.
The only way we really know an operation has been cancelled
is by examining the `GetOperation()` response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7762)
=> fix(common): revamp the async polling loop

google/cloud/storage/CMakeLists.txt, google/cloud/storage/bucket_access_control.h, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/internal/access_control_common.h, google/cloud/storage/internal/grpc_bucket_access_control_parser.cc, google/cloud/storage/internal/grpc_bucket_access_control_parser.h, google/cloud/storage/internal/grpc_bucket_access_control_parser_test.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl
Fixes #4174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7763)
=> feat(GCS+gRPC): implement BucketAccessControl parser

ci/kokoro/windows/build.ps1
The cache for Windows builds just contains vcpkg binary files, these are independent
of the branch being targeted as the cache is a content cache. We can remove the branch
name from the cache path and simplify the script a itty-tiny-little-bit.
Fixes #3517
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7764)
=> ci: remove hardcoded branches on windows builds

google/cloud/storage/CMakeLists.txt, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.h, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl
Fixes #4164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7765)
=> feat(GCS+gRPC): implement BucketBilling parser

google/cloud/internal/async_retry_loop.h
if `Cancelled() == true`, we have already set the state to Done and filled the promise. https://github.com/googleapis/google-cloud-cpp/blob/508e008ffd7c7a0fbdb092660378464d185f7c8b/google/cloud/internal/async_retry_loop.h#L212-L216
and the call to `SetDone()` does nothing https://github.com/googleapis/google-cloud-cpp/blob/508e008ffd7c7a0fbdb092660378464d185f7c8b/google/cloud/internal/async_retry_loop.h#L193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7767)
=> cleanup: simplify logic

google/cloud/pubsublite/internal/stream_factory.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7770)
=> cleanup(pubsublite): fix clang-tidy errors

google/cloud/testing_util/CMakeLists.txt, google/cloud/testing_util/async_sequencer.h, google/cloud/testing_util/async_sequencer_test.cc, google/cloud/testing_util/google_cloud_cpp_testing_unit_tests.bzl
Add functionality to `AsyncSequencer` to keep track of the total number of cancelled futures. Moving the functionality here will allow us to rewrite (and simplify) [the logic](https://github.com/googleapis/google-cloud-cpp/blob/5d19d3d16eb458414ff96162f3080b09d40369df/google/cloud/internal/async_retry_loop_test.cc#L58-L98) in `internal/async_retry_loop_test.cc`
Also add simple tests for the class. I don't think it will hurt to have them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7771)
=> test: add cancel count to AsyncSequencer

ci/cloudbuild/builds/check-api.sh, ci/cloudbuild/builds/clang-60.sh, ci/cloudbuild/builds/clang-tidy.sh, ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/builds/cxx11.sh, ci/cloudbuild/builds/cxx20.sh, ci/cloudbuild/builds/gcc-54.sh, ci/cloudbuild/builds/gcc-63.sh, ci/cloudbuild/builds/install-gcs-grpc.sh, ci/cloudbuild/builds/lib/cmake.sh, ci/cloudbuild/builds/lib/features.sh, ci/cloudbuild/builds/noex.sh, ci/cloudbuild/builds/publish-docs.sh, ci/cloudbuild/builds/scan-build.sh, ci/cloudbuild/builds/shared.sh
The `pubsublite` library now contains hand-crafted as well as
automatically generated code. We need to build this library in most
cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7772)
=> ci: enable Pub/Sub Lite in CMake builds

doc/cpp-style-guide.md, release/changes.sh, release/release.sh
There are a couple in the LICENSE files, but the internal instructions for this are pretty clear that this file should be used verbatim.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7781)
=> cleanup: fix remaining http vs. https

google/cloud/internal/log_wrapper.cc, google/cloud/internal/log_wrapper_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7782)
=> feat(common): include the request/response type name in the RPC log

google/cloud/internal/async_retry_loop.h, google/cloud/internal/async_retry_loop_test.cc
Fixes #7788 
I could not write a unit test that would reliably introduce the race condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7789)
=> fix: extremely rare race conditions in retry loop

ci/cloudbuild/builds/lib/integration.sh, google/cloud/bigtable/examples/table_admin_snippets.cc
There seems to be lifetime issues around calling `TableAdmin::WaitForConsistency()`. Before #7733, the object's lifetime existed outside the scope of the sample method, so we never saw the bug surface. See #7740 for more details.
This PR adds a workaround for that bug. It is a dumb band-aid, but it seems more appropriate than retrying the entire CI build for Bigtable when the error is encountered.
I think the wisest course of action, moving forward, is to:
1. Implement #7732. This will not fix the lifetime issues, but it will allow us to drop the workaround.
2. Fix the lifetime issues, by reimplementing `TableAdmin` on top of the generated APIs (#7530), naturally as part of the effort to Modernize Bigtable.
--- …
=> ci: workaround bigtable table admin snippets bug

CHANGELOG.md, README.md, ci/generate-markdown/generate-readme.sh, google/cloud/secretmanager/README.md, google/cloud/tasks/README.md
Loggin is missing a bidir streaming API, Pub/Sub Lite is missing the data APIs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7792)
=> doc: declare Secret Manager and Task as GA

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7798)
=> fix: typo that breaks release/release.sh

google/cloud/grpc_utils/BUILD.bazel, google/cloud/grpc_utils/async_operation.h, google/cloud/grpc_utils/completion_queue.h, google/cloud/grpc_utils/grpc_error_delegate.h, google/cloud/grpc_utils/version.h
When we moved the symbols from `google::cloud::grpc_utils::*` to
`google::cloud::*` (and same thing with files) we created backwards
compatibility targets, headers and symbols, but did not specify when
they would get removed.  This adds all the warnings in all the right
places.
Part of the work for #3932
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7799)
=> cleanup: deprecate grpc_utils/ files and symbols

BUILD
I should have done this at the same time as we declared these libraries GA.
I think we can wait until the 1.36.0 release to remove the experimental targets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7806)
=> fix: add GA targets for secretmanager and tasks

BUILD.bazel, ci/verify_current_targets/BUILD.bazel
For experimental targets I just removed any `*-mocks` targets. For GA
targets I created a `*_mocks` and deprecated the `*-mocks` rule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7831)
=> cleanup: prefer *_mocks for top-level Bazel rules

google/cloud/grpc_options.cc, google/cloud/grpc_options.h, google/cloud/grpc_options_test.cc, google/cloud/internal/async_polling_loop.cc, google/cloud/internal/async_polling_loop_test.cc, google/cloud/internal/async_retry_loop.h, google/cloud/internal/async_retry_loop_test.cc, google/cloud/internal/retry_loop.h, google/cloud/internal/retry_loop_test.cc
Add ability to configure the `grpc::ClientContext` before each RPC call. For now, this has been developed in an `internal` namespace. The options may never be made public, but I figured it wouldn't hurt to document them anyway.
Part of the work for #7529. [This comment](https://github.com/googleapis/google-cloud-cpp/issues/7529#issuecomment-1006772608) is worth reading to understand the context of this change. Especially the **Downside** section, which could invalidate the entire PR.
Some Notes/Choices:
* `GrpcSetupPollOption` takes effect on cancel requests. (Even though there is no equivalent function in Bigtable). I could use a second opinion on whether the option should apply to both cancels and polls, or just polls.
* There is no configuration done on the context used when we …
=> impl(common): add an (internal) option to setup grpc::ClientContext

google/cloud/secretmanager/CMakeLists.txt, google/cloud/secretmanager/config.cmake.in, google/cloud/tasks/CMakeLists.txt, google/cloud/tasks/config.cmake.in
I missed these when declaring the libraries GA.
I will be writing a document to describe all the steps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7841)
=> cleanup: CMake changes to declare libraries GA

generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/golden_thing_admin_client.cc, generator/integration_tests/golden/golden_thing_admin_client.h, generator/integration_tests/golden/golden_thing_admin_connection.cc, generator/integration_tests/golden/golden_thing_admin_connection.h, generator/integration_tests/golden/golden_thing_admin_connection_idempotency_policy.cc, generator/integration_tests/golden/golden_thing_admin_connection_idempotency_policy.h, generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.cc, generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.h, generator/integration_tests/golden/internal/golden_thing_admin_logging_decorator.cc, generator/integration_tests/golden/internal/golden_thing_admin_logging_decorator.h, generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.cc, generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.h, generator/integration_tests/golden/internal/golden_thing_admin_stub.cc, generator/integration_tests/golden/internal/golden_thing_admin_stub.h, generator/integration_tests/golden/mocks/mock_golden_thing_admin_connection.h, generator/integration_tests/golden/mocks/mock_golden_thing_admin_stub.h, generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_stub_test.cc, generator/integration_tests/test.proto, generator/internal/metadata_decorator_generator.cc
Fix the generated code for long-running operations without a routing
header. It was calling `Foo()` when it needed to call `**Async**Foo()`
The interesting change is in `generator/internal/metadata_decorator_generator.cc`, the rest is just how testing for this stuff works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7852)
=> fix(generator): long-running ops and routing header

doc/contributor/howto-guide-adding-generated-libraries.md, generator/internal/scaffold_generator.cc
This eliminates a step in generating new libraries.
Fixes #7642
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7855)
=> feat(generator): use globs for geneated BUILD file

google/cloud/bigtable/polling_policy.h, google/cloud/bigtable/polling_policy_test.cc
The bigtable part of #7853
`bigtable::GenericPollingPolicy<>` was cloning its current state, instead of its initial state. The idea is just to initially clone the objects. The current state of the polling policy is maintained by those clones. When the polling policy itself is cloned, it uses the initial objects to copy its initial state.
Also add a test for `WaitPeriod` to get better coverage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7854)
=> fix(bigtable): polling policy clones initial state

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_common_unit_tests.bzl, google/cloud/polling_policy.h, google/cloud/polling_policy_test.cc
Fixes #7853
Use the initial state of the polling policy as the prototype for clones. Add documentation and unit tests for `GenericPollingPolicy`.
Fixes #7562 
@devbww made the connection to the Spanner `samples.cc` flake.
We make the polling policy out of a retry policy with a 60 minute timeout at the start of the test. But then when we clone the polling policy for individual polling loops, we are just reusing the original retry policy. So the test goes on, but after 60 mins, the retry policy is exhausted, and any polling loop will be terminated.
`CloneWithPointers` is the test for this flake, which now passes, but would previously have failed.
--- …
=> fix(common): polling policy clones initial state

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/polling_policy.cc, google/cloud/bigtable/polling_policy.h, google/cloud/bigtable/polling_policy_test.cc, google/cloud/bigtable/rpc_backoff_policy.cc, google/cloud/bigtable/rpc_backoff_policy.h, google/cloud/bigtable/rpc_backoff_policy_test.cc, google/cloud/bigtable/rpc_retry_policy.cc, google/cloud/bigtable/rpc_retry_policy.h, google/cloud/bigtable/rpc_retry_policy_test.cc
Part of the work for #7529. (This is the same code as #7594)
Add conversion methods for bigtable retry, backoff, polling policies -> common retry, backoff, polling policies. The retry is templated because the Instance and Table Admin options have different types.
https://github.com/googleapis/google-cloud-cpp/blob/4082229488f2099f064954b2f317221fe3bb6442/google/cloud/bigtable/admin/bigtable_instance_admin_options.h#L36
https://github.com/googleapis/google-cloud-cpp/blob/4082229488f2099f064954b2f317221fe3bb6442/google/cloud/bigtable/admin/bigtable_table_admin_options.h#L36
The conversion to `Options`, as described in the issue, will be added in a subsequent PR. The `Setup(grpc::ClientContext&)` functionality will be captured then.
--- …
=> impl(bigtable): convert to common policies

CHANGELOG.md, google/cloud/storage/internal/retry_resumable_upload_session.cc, google/cloud/storage/internal/retry_resumable_upload_session.h, google/cloud/storage/internal/retry_resumable_upload_session_test.cc
Resumable upload responses use the `Range` header to report how many
bytes were committed. Sometimes, maybe once every few million uploads,
the header is missing. This indicates that nothing was committed.
The library was treating this as a permanent error. The correct behavior
is to query the status of the upload and try again.
Fixes #7835
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7877)
=> fix(storage)!: handle missing range header in uploads

ci/cloudbuild/builds/lib/integration.sh, doc/contributor/howto-guide-setup-development-workstation.md, google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh, google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
Incidentally fixes #7899 and prepare for removing the magically created buckets in the testbench.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7910)
=> chore(deps): update to latest storage-testbench

generator/internal/client_generator.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils.h, generator/internal/descriptor_utils_test.cc
Fixes #7923 
Fix the generator so that the doxygen parameter comments are limited to the method signature in question (instead of all of them). I could have added an extra paremeter that was -1 for a protobuf request or N for the Nth method signature. But that seemed like bad code. So I took the opportunity to refactor the logic a bit, and clean up some things.
The diff is not great here. The old `FormatProtobufRequestParameters` was actually only two lines of code, so I inlined it. The other method was simplified a bit. Also, there is one less `enum` in the world.
In order to update the unit test so that it would have previously failed, I added a comment and method signature to the unit test proto. This explains why some of the line numbers in unrelated tests had to change.
I did not add …
=> fix(generator): multiple method signatures doxygen

generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.h, generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_stub.h, generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc, generator/integration_tests/test.proto, generator/internal/auth_decorator_generator.cc, generator/internal/logging_decorator_generator.cc, generator/internal/metadata_decorator_generator.cc, generator/internal/predicate_utils.cc, generator/internal/predicate_utils.h, generator/internal/predicate_utils_test.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator.h, generator/internal/service_code_generator_test.cc, generator/internal/stub_generator.cc, google/cloud/logging/internal/logging_service_v2_auth_decorator.cc, google/cloud/logging/internal/logging_service_v2_auth_decorator.h, google/cloud/logging/internal/logging_service_v2_logging_decorator.cc, google/cloud/logging/internal/logging_service_v2_logging_decorator.h, google/cloud/logging/internal/logging_service_v2_metadata_decorator.cc, google/cloud/logging/internal/logging_service_v2_metadata_decorator.h, google/cloud/logging/internal/logging_service_v2_stub.cc, google/cloud/logging/internal/logging_service_v2_stub.h
Start support for bidir streaming RPCS in the generator. In this change
only the `*Stub` classes and its decorators get the stubs.
Part of the work for #7795
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7885)
=> impl(generator): bidir streaming RPCs in Stubs

generator/integration_tests/golden/golden_kitchen_sink_connection.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.h, generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_stub.h, generator/internal/auth_decorator_generator.cc, generator/internal/connection_generator.cc, generator/internal/logging_decorator_generator.cc, generator/internal/metadata_decorator_generator.cc, generator/internal/stub_generator.cc, google/cloud/logging/internal/logging_service_v2_auth_decorator.cc, google/cloud/logging/internal/logging_service_v2_auth_decorator.h, google/cloud/logging/internal/logging_service_v2_logging_decorator.cc, google/cloud/logging/internal/logging_service_v2_logging_decorator.h, google/cloud/logging/internal/logging_service_v2_metadata_decorator.cc, google/cloud/logging/internal/logging_service_v2_metadata_decorator.h, google/cloud/logging/internal/logging_service_v2_stub.cc, google/cloud/logging/internal/logging_service_v2_stub.h, google/cloud/logging/logging_service_v2_connection.cc
Remove the alias for bidir streaming RPC return types. I realized they
could conflict with any other method name defined in the same interface.
I also changed the completion queue parameter in the `Stub` classes from
`CompletionQueue&` to `Completion const&`. There is one place, in the
`*Auth` decorator, where taking by-value would save us one refcount
twiddle. Since this class is optional, and that save would require C++14
(or a helper functor to capture by move), and the classes are in
`internal::` I decided to just go with the reference.
Part of the work for #7795
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7937)
=> fix(generator): bidir streaming RPCs improvements

generator/generator_config.proto, generator/integration_tests/generator_integration_test.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.h, generator/integration_tests/golden/internal/golden_thing_admin_stub.h, generator/internal/codegen_utils.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, generator/internal/stub_generator.cc, generator/standalone_main.cc
Allows additional proto files to be specified in the config. The files are used for type lookups during code generation and to format include statements in the <service_name>_stub.h files. The proto files are also run through protoc in order to produce the accompanying pb.h and pb.cc files.
fixes #7922
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7940)
=> impl(generator): support additional proto files for lro return types

generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.h, generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_stub.h, generator/integration_tests/golden/tests/golden_kitchen_sink_auth_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc, generator/integration_tests/test.proto, generator/internal/auth_decorator_generator.cc, generator/internal/logging_decorator_generator.cc, generator/internal/metadata_decorator_generator.cc, generator/internal/predicate_utils.cc, generator/internal/predicate_utils.h, generator/internal/predicate_utils_test.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator.h, generator/internal/service_code_generator_test.cc, generator/internal/stub_generator.cc
Change the generator to support streaming write (aka client-side
streaming) RPCs in the `*Stub` class and its decorators. Changed the
golden files to include one such method. Change the unit tests for the
golden files to test the generated code.
The generated libraries are unaffected by this change, as none of the
libraries we have uses streaming write RPCs.
Part of the work for #7929
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7941)
=> feat(generator): streaming-write RPCs for Stubs

generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.h, generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_stub.h, generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc, generator/internal/auth_decorator_generator.cc, generator/internal/logging_decorator_generator.cc, generator/internal/metadata_decorator_generator.cc, generator/internal/stub_generator.cc, google/cloud/bigquery/internal/bigquery_read_auth_decorator.cc, google/cloud/bigquery/internal/bigquery_read_auth_decorator.h, google/cloud/bigquery/internal/bigquery_read_logging_decorator.cc, google/cloud/bigquery/internal/bigquery_read_logging_decorator.h, google/cloud/bigquery/internal/bigquery_read_metadata_decorator.cc, google/cloud/bigquery/internal/bigquery_read_metadata_decorator.h, google/cloud/bigquery/internal/bigquery_read_stub.cc, google/cloud/bigquery/internal/bigquery_read_stub.h, google/cloud/logging/internal/logging_service_v2_logging_decorator.cc
The generator was emitting `internal::Foo` for some helpers in
`google::cloud::internal`. This works perfectly fine for generated
libraries, but I want to use some of the generated code in
`google::cloud::storage::internal` where the names become ambiguous.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7948)
=> cleanup(generator): fully qualify some helpers

doc/contributor/howto-guide-adding-generated-libraries.md
This may trip some presubmit checks in downstream code bases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7950)
=> chore: trim some end-of-line whitespace

google/cloud/storage/CMakeLists.txt, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/storage_stub_factory.cc, google/cloud/storage/internal/storage_stub_factory.h, google/cloud/storage/internal/storage_stub_factory_test.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl
Split the factory function for `StorageStub` (with decorators) to its
own `.h` and `.cc` files. This will help as I add additional decorators
and member functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7952)
=> refactor(GCS+gRPC): move stub factory function

google/cloud/storage/internal/storage_auth.cc, google/cloud/storage/internal/storage_auth.h, google/cloud/storage/internal/storage_auth_test.cc, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h
This will make it easier to use (even via cut&paste) the generated
`StorageStub` and any decorators.
Part of the work for #7963
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7964)
=> cleanup(GCS+gRPC): remove aliases for streaming RPC wrappers

generator/generator_config.proto, generator/internal/codegen_utils_test.cc, generator/internal/descriptor_utils.cc, generator/standalone_main.cc
Sometimes it is useful to not generate the `*Connection` class and its
friends.
Part of the work for #7963
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7965)
=> feat(generator): add option to disable *Connection

generator/generator_config.proto, generator/internal/codegen_utils_test.cc, generator/internal/descriptor_utils.cc, generator/standalone_main.cc
Part of the work for #7963.  I am planning to generate as much of the code in GCS+gRPC as possible, but
the stub factory needs to be completely custom.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7979)
=> feat(generator): add option to omit Stub factory

ci/cloudbuild/builds/cmake-install.sh
We often run this build manually. It was tedious to manually check the
exit code, so now the script prints "SUCCESS" when it completes
successfully. It was also tedious to search the log for errors, so now
it stops on the first failure, like most of our CI scripts do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7996)
=> ci: stop cmake-install build on the first error

ci/cloudbuild/builds/generate-libraries.sh
I find myself running this manually more often these days, and the formatting slowness was bothering me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7995)
=> ci: speedup generate-libraries build

google/cloud/storage/CMakeLists.txt, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_auth_decorator_test.cc, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/internal/storage_stub_factory.cc, google/cloud/storage/internal/storage_stub_factory.h, google/cloud/storage/internal/storage_stub_factory_test.cc, google/cloud/storage/testing/mock_storage_stub.h
Move the `StorageStub` class and its decorators to the
`google::cloud::storage_internal` namespace. This is the namespace used
by the generator. It seems better to move the types than trying to tweak
the generator to use a special namespace just in this case.
Part of the work for #7963
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8001)
=> refactor(GCS+gRPC): move stubs to `storage_internal`

generator/standalone_main.cc
I missed this when adding support to disable the `*Connection` generation.
Part of the work for #7963 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8005)
=> fix(generator): no include/../mocks without a connection

google/cloud/internal/rest_response.cc, google/cloud/internal/rest_response_test.cc, google/cloud/storage/oauth2/authorized_user_credentials.cc, google/cloud/storage/oauth2/authorized_user_credentials_test.cc, google/cloud/storage/oauth2/compute_engine_credentials.cc, google/cloud/storage/oauth2/compute_engine_credentials_test.cc, google/cloud/storage/oauth2/google_credentials.cc, google/cloud/storage/oauth2/google_credentials_test.cc, google/cloud/storage/oauth2/service_account_credentials.cc, google/cloud/storage/oauth2/service_account_credentials_test.cc, google/cloud/storage/storage_iam_policy_test.cc
Prefer using `!is_object()` over `is_discarded()` to detect parsing
errors. In many cases this change made no difference (e.g. where there
was an implicit check via `.count()`). In a few places the new tests
triggered latent bugs. One of these bugs was real, but it is hard to say
which one.
Fixes #8027
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8033)
=> fix(storage): improve JSON validation

google/cloud/bigtable/instance_admin.h
Part of the work for #7534 
We need to store the project id ourselves, so we can eventually drop our dependence on the legacy `client_`.
The full change (short of a CHANGELOG entry) is here: https://github.com/dbolduc/google-cloud-cpp/compare/bigtable-convert-instance-admin
The diff is 4500 lines. I am trying to break it up into something more palatable. My plan is to break it into the following PRs:
1. project id change (this PR)
2. add the logic for storing a generated Connection (without ever using the new connection)
3. add the mechanism to convert bigtable policies passed to the constructor into `Options`.
4. (BREAKING): Reimplement `InstanceAdmin` in terms of the generated Connection. Rewrite the unit tests. Update the CHANGELOG. (This will be a tedious PR).
5. Gut the …
=> cleanup(bigtable): store project id in InstanceAdmin

.codecov.yml
We do not need to worry about test coverage in generated code, we have
separate tests for the generator (and for the code it generates).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8060)
=> ci(storage): ignore coverage for generated code

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/bigtable_client_unit_tests.bzl, google/cloud/bigtable/instance_admin_new_test.cc, google/cloud/bigtable/instance_admin_test.cc
Split the test in two. I will keep the new one, and eventually delete the old one. I tried to have the new one be named "instance_admin_test.cc" and the old one be named "instance_admin_legacy_test.cc", but I could not get the diff that I wanted.
If we think this is being too careful, we can go with #8055 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8057)
=> test(bigtable): split instance admin test in two

google/cloud/bigtable/polling_policy_test.cc, google/cloud/bigtable/rpc_retry_policy_test.cc, google/cloud/internal/retry_policy_test.cc, google/cloud/polling_policy_test.cc
The intention is to combat #7269. If we don't mock a clock type, we are just going to have to increase the tolerance.
This PR increases the absolute tolerance, while keeping the relative tolerance constant. The worst test will increase by 200ms. That seems reasonable to me.
All recorded flakes have been polling policies, probably because they make an extra call to invoke the retry policy predicate. I modified the retry policy tests anyway. I could be easily convinced that they should be left alone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8052)
=> cleanup: increase absolute tolerance for timed tests

google/cloud/bigtable/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/bigtable/admin/integration_tests/table_admin_integration_test.cc, google/cloud/bigtable/tests/admin_integration_test.cc, google/cloud/bigtable/tests/data_integration_test.cc, google/cloud/bigtable/tests/instance_admin_integration_test.cc
Instead of checking that nothing at all is logged, only check that the logging decorator is not in use. (I have tests breaking due to extraneous logs from `CheckExpectedOptions<>`)
All of this has been prophesied by @devbww
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8062)
=> test(bigtable): relax logging tests

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/samples/samples.cc
Apply any retry/backoff/polling policies in the client options
instead of the connection options.  This makes more logical
sense (particularly so when we consider per-operation options),
and is actually required until we fix #8054.
Fixes #8037.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8064)
=> fix(spanner): apply policy options in (generated) client ctor

google/cloud/bigtable/admin_client.cc, google/cloud/bigtable/data_client.cc, google/cloud/bigtable/instance_admin_client.cc, google/cloud/bigtable/internal/common_client.h, google/cloud/bigtable/internal/defaults.cc, google/cloud/bigtable/internal/defaults.h, google/cloud/bigtable/internal/defaults_test.cc
In legacy Bigtable, we compute the default endpoints for the Data, InstanceAdmin, and TableAdmin APIs all at once. They are stored as Bigtable-specific options.
The generated Connection does not know about these options. So we must extract the proper endpoint and set it as the `EndpointOption`. While we're here, simplify the `CommonClient<>` class, even though it will be going [bye-bye](https://www.youtube.com/watch?v=B6XAZgTxbDc) soon.
I should consider deprecating `DataEndpointOption`, `AdminEndpointOption`, `InstanceAdminEndpointOption` in favor of internal versions of those options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8069)
=> refactor(bigtable): use `EndpointOption`

google/cloud/storage/internal/resumable_upload_session_test.cc
I am not sure why we don't get this warning in the clang-tidy build, but fixing anyway:
```
external/com_google_absl/absl/types/optional.h: In instantiation of 'constexpr decltype (absl::lts_20211102::optional_internal::convertible_to_bool((v == (* x)))) absl::lts_20211102::operator==(const U&, const absl::lts_20211102::optional<T>&) [with T = long unsigned int; U = int; decltype (absl::lts_20211102::optional_internal::convertible_to_bool((v == (* x)))) = bool]':
external/com_google_googletest/googletest/include/gtest/gtest.h:1545:11:   required from 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = absl::lts_20211102::optional<long unsigned int>]'
external/com_google_googletest/googletest/include/gtest/gtest.h:156 …
```
=> test(storage): fix unsigned vs. signed warnings

google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc
The `rpc_failure_threshold_integration_test` was running very slowly
against the emulator.  The test is not that useful against the emulator,
but we do not want it to rot.  I changed the test to detect that it is
running against the emulator, and then simply reduce the running time, and
ignore the statistical results as they become unreliable.
Motivated by #4039
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8072)
=> test(spanner): speed up test with emulator

google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/instance_admin_client.cc, google/cloud/bigtable/instance_admin_client.h, google/cloud/bigtable/instance_admin_new_test.cc
Part of the work for #7534.
This PR adds the mechanism for storing generated connections in `InstanceAdmin`. This code is unused and sits side by side with the old way (using `InstanceAdminClient`). This PR is one step in the conversion process. The big picture can be found [here](https://github.com/googleapis/google-cloud-cpp/compare/main...dbolduc:bigtable-convert-instance-admin).
Previous code could have one `InstanceAdminClient` that is shared by N `InstanceAdmin`s. In this case, we want the N `InstanceAdmin`s to all share the same `bigtable_admin::BigtableInstanceAdminConnection`. So we make the connection upon construction of the `InstanceAdminClient` and give the `InstanceAdmin` access to it.
Temporary things:
* The added constructor will make an `InstanceAdmin` that cannot make …
=> impl(bigtable): implement connection mechanism in legacy InstanceAdmin

google/cloud/pubsublite/internal/stream_factory.h, google/cloud/pubsublite/internal/stream_factory_test.cc
These are still useful to provide the input factory in a structured way for the (eventual) ResumableStreamingReadWriteRpc matching the patterns of https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/internal/resumable_streaming_read_rpc.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8075)
=> fix(pubsublite): Restructure stream_factory.h to use generated stubs

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/admin_client.h, google/cloud/bigtable/bigtable_client_unit_tests.bzl, google/cloud/bigtable/table_admin.cc, google/cloud/bigtable/table_admin.h, google/cloud/bigtable/table_admin_test.cc
Part of the work for #7530 
Store the project id so that we have one less dependence on `client_`. (Eventually `client_` will be removed entirely).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8085)
=> refactor(bigtable): store project id in TableAdmin

google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc
Sort the functions in this class so they match the order of declaration
in the `StorageStub`. A bit silly, but makes it easier to grok the PR
changes, and possibly allows me to send more PRs in parallel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8088)
=> refactor(GCS+gRPC): reorder GrpcObjectRequestParser

google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/instance_admin_test.cc
Part of the work for #7534 
Convert bigtable policies to common policies (stored as `Options policies_`) upon construction of the `InstanceAdmin` class. We do not use these yet. They will eventually be passed in calls made to the `Connection`. For example, like [this](https://github.com/dbolduc/google-cloud-cpp/blob/7d95be046ae60682ba533eba0f2162aecc0da29c/google/cloud/bigtable/instance_admin.cc#L78-L80).
The plan is to use the `LegacyConstructorWithPolicies` test to ensure that custom policies passed in the constructor are stored in `policies_`. Then for each individual RPC, we will only check that the expected policy options are set (but we will not check their values). For example, like [this](https://github.com/dbolduc/google-cloud-cpp/blob/7d95be046ae60682ba533eba0f2162aecc0da29c/goog …
=> impl(bigtable): convert policies to options in InstanceAdmin

README.md, ci/cloudbuild/builds/lib/bazel.sh, ci/generate-markdown/generate-readme.sh, ci/kokoro/macos/builds/bazel.sh, ci/kokoro/macos/builds/quickstart-bazel.sh
Fixes: #8084
Related to: #8078
Bazel 5.0 is now GA, so we can drop support for 3.x. This will enable us
to use bazel `@platforms`, which will make some of our `select()`s nicer
and work better in a cross-platform way.
Note: our Windows builds already required bazel 4.0, so now they're all consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8095)
=> feat: upgrade bazel, require >= 4.0

CMakeLists.txt
The examples in `google/cloud/examples` require `iam` and `spanner`, in
addition to `storage` and `bigtable`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8110)
=> cleanup: update requirements for top-level examples

bazel/crc32c.BUILD, bazel/curl.BUILD
Fixes: #8078
Now that we require bazel >= 4.0, we can use the recommended
`@platforms` way to specify build constraints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8101)
=> ci: use bazel @platforms for config settings

google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc, google/cloud/spanner/connection.h, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h, google/cloud/spanner/mocks/mock_spanner_connection.h
Store the `Connection` options so that they may be made available to
merge into the `Client` options.
Use those stored options to implement four `Connection` data elements
that were previously extracted during construction.  (When all `Client`
operations have been taught how to set the "current options" we will
be able to use those instead.)
Part of #7690.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8090)
=> feat(spanner): merge connection options into client options

ci/cloudbuild/builds/lib/integration.sh
Exclude hand-written files from the "generator integration test" diff
used to check that the golden files are up-to-date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8126)
=> chore(ci): exclude ungenerated files from post-generation diff

ci/cloudbuild/builds/cmake-install.sh, external/googleapis/CMakeLists.txt
Part of: #8118
A CMake target for `google/devtools/source/v1/source_context.proto` is needed by the Cloud Debugger API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8127)
=> chore: add cmake target for needed proto file
