- .travis.yml
This fixes #60. Please notice that this PR already has the build disabled.
> Disable macOS builds on pull requests.

- .editorconfig
> Added EditorConfig support. [skip ci]

- CMakeLists.txt
- bigtable/CMakeLists.txt
We were not consistent and with the EditorConfig submitted we have a fighting chance.
> Indent all CMake files to 4 spaces.

- bigtable/client/client_options.cc
- bigtable/client/client_options.h
- bigtable/client/client_options_test.cc
Fixes Issue #53. I can add getters if needed.
> Added setters for Channel Arguments.

- bigtable/CMakeLists.txt
- bigtable/admin/column_family_test.cc
- bigtable/client/filters_test.cc
- bigtable/client/rpc_backoff_policy_test.cc
- bigtable/client/rpc_retry_policy_test.cc
- bigtable/client/table_apply_test.cc
- bigtable/client/table_bulk_apply_test.cc
- bigtable/client/testing/chrono_literals.h
- bigtable/client/testing/mock_client.h
- bigtable/client/testing/table_test_fixture.cc
- bigtable/client/testing/table_test_fixture.h
> Refactor testing subdirectory

- bigtable/CMakeLists.txt
- bigtable/admin/table_admin.cc
- bigtable/admin/table_admin.h
- bigtable/admin/table_admin_test.cc
- bigtable/admin/table_config.cc
- bigtable/admin/table_config.h
- bigtable/admin/table_config_test.cc
- bigtable/tests/integration_test.cc
- bigtable/tests/run_integration_tests.sh
This is another PR in the series to fix #79.  It implements the CreateTable() function.
> Implement CreateTable() for the admin client

- bigtable/client/cell.h
- bigtable/client/client_options.h
- bigtable/client/data.h
- bigtable/client/detail/bulk_mutator.h
- bigtable/client/idempotent_mutation_policy.h
- bigtable/client/mutations.h
- bigtable/client/row.h
- bigtable/client/rpc_backoff_policy.h
- bigtable/client/rpc_retry_policy.h
- bigtable/client/testing/mock_client.h
- bigtable/client/version.h
Address the comment raised in #102 for the current headers.
> Fix #include guards.

- bigtable/client/detail/bulk_mutator.cc
- bigtable/client/detail/bulk_mutator_test.cc
- bigtable/tests/integration_test.cc
Found a bug while doing integration tests.  Added the integration test, improved the unit tests to detect such bugs, and fixed the code (of course).
> Fix implementation of Table::BulkApply()

- ci/upload-codecov.sh
Another script that needed fixing after #138.
> Fix code coverage upload after #138.

- bigtable/tests/filters_integration_test.cc
This just removes a few TODO() entries, uses the `Table::ReadRows()` API instead of implementing a hack for the test.
> Simplify integration tests, use Table::ReadRows().

- bigtable/CMakeLists.txt
- bigtable/client/row_reader_test.cc
- bigtable/client/table.cc
- bigtable/client/table.h
- bigtable/client/table_readrow_test.cc
- bigtable/client/table_readrows_test.cc
- bigtable/client/testing/mock_response_stream.h
- bigtable/client/testing/table_test_fixture.h
> Implement Table::ReadRow()

- bigtable/client/row_reader.cc
- bigtable/client/row_reader.h
- bigtable/client/row_reader_test.cc
> Implement RowReader::Cancel()

- .appveyor.yml
- CMakeLists.txt
- bigtable/CMakeLists.txt
- ci/build-windows.ps1
- ci/install-windows.ps1
- cmake/IncludeAbseil.cmake
This is Appveyor build for google-cloud-cpp client. Fixes #23.
> Clean Appveyor build.

- bigtable/tests/run_integration_tests.sh
The emulator can be launched in a separate shell and reused.
Also remove a dead code test for error, the return
code for processes launched in the background
is assigned only after `wait`.
> Make the integration tests script friendlier to manual runs.

- bigtable/client/rpc_backoff_policy.cc
- bigtable/client/rpc_backoff_policy.h
- bigtable/client/rpc_backoff_policy_test.cc
This add RandomizedBackoffPolicy to RPCBackoffPolicy class. Fixes #57.
> Added class to randomize sleep period.

- .clang-format
A tiny improvement to our clang-format(1) configuration.
> Enforce pointer/reference alignment consistency.

- bigtable/CMakeLists.txt
- bigtable/client/testing/table_integration_test.cc
- bigtable/client/testing/table_integration_test.h
- bigtable/tests/data_integration_test.cc
- bigtable/tests/filters_integration_test.cc
- bigtable/tests/run_integration_tests.sh
issue #194, data_integration_test is converted to gtest
> Data int test to gtest

- bigtable/client/mutations.h
- bigtable/client/mutations_test.cc
- bigtable/tests/data_integration_test.cc
pull request for changes of #164
> SingleRowMutation supports variadic Mutation list

- bigtable/doc/no-exception-support.md
- doc/style-guide.md
> Document how we support C++ without exceptions [skip ci].

- bigtable/client/internal/readrowsparser_test.cc
- bigtable/client/testing/table_integration_test.cc
- bigtable/tests/admin_integration_test.cc
- bigtable/tests/data_integration_test.cc
- bigtable/tests/filters_integration_test.cc
> Do not use absl::StrJoin()

- bigtable/CMakeLists.txt
- bigtable/admin/table_admin_test.cc
- bigtable/client/client_options_test.cc
- bigtable/client/internal/port_platform.h
- bigtable/client/internal/readrowsparser_acceptance_tests.inc
- bigtable/client/internal/readrowsparser_test.cc
- bigtable/client/internal/throw_delegate.cc
- bigtable/client/mutations_test.cc
- bigtable/client/row_reader.cc
- bigtable/client/row_reader_test.cc
- bigtable/client/table.cc
- bigtable/client/table_apply_test.cc
- bigtable/client/table_bulk_apply_test.cc
- bigtable/client/table_readrows_test.cc
- bigtable/client/version.h
- bigtable/tools/convert_acceptance_tests.py
- doc/no-exception-support.md
Created new macro (GOOGLE_CLOUD_CPP_HAVE_EXCEPTIONS), use that
instead, this fixes #254.
> Do not use ABSL_HAVE_EXCEPTIONS.

- bigtable/CMakeLists.txt
- bigtable/client/internal/bulk_mutator_test.cc
- bigtable/client/internal/make_unique.h
- bigtable/client/internal/readrowsparser.h
- bigtable/client/row_reader.cc
- bigtable/client/row_reader.h
- bigtable/client/row_reader_test.cc
- bigtable/client/table.cc
- bigtable/client/table_bulk_apply_test.cc
- bigtable/client/table_readrow_test.cc
- bigtable/client/table_test.cc
- bigtable/client/testing/table_integration_test.cc
- bigtable/tests/admin_integration_test.cc
- bigtable/tests/data_integration_test.cc
> Do not use absl::make_unique.

- bigtable/CMakeLists.txt
- bigtable/admin/table_admin.cc
- bigtable/admin/table_admin_test.cc
- bigtable/benchmarks/setup.cc
- bigtable/client/client_options.cc
- bigtable/client/data_client.h
- bigtable/client/internal/readrowsparser.h
- bigtable/client/internal/readrowsparser_test.cc
- bigtable/client/row_range.h
- bigtable/client/table.h
- bigtable/client/version.cc
- bigtable/tests/admin_integration_test.cc
> Do not use absl::StrCat()

- bigtable/CMakeLists.txt
- bigtable/benchmarks/apply_read_latency_benchmark.cc
- bigtable/benchmarks/benchmark.cc
- bigtable/benchmarks/benchmark.h
- bigtable/benchmarks/benchmark_test.cc
- bigtable/benchmarks/format_duration_test.cc
- bigtable/benchmarks/scan_throughput_benchmark.cc
> Remove usage of absl::FromChrono().

- bigtable/client/internal/rowreaderiterator.cc
- bigtable/client/internal/rowreaderiterator.h
- bigtable/client/internal/throw_delegate.cc
- bigtable/client/internal/throw_delegate.h
- bigtable/client/row_reader.cc
- bigtable/client/row_reader.h
> Do not use absl::optional<>

- bigtable/tests/admin_integration_test.cc
Added two new integration test for DropRowsByPrefix and DropAllRows in admin_integration_test.cc.
> Issue#141: Addition of DropRows* integration test

- bigtable/CMakeLists.txt
- bigtable/tests/mutations_integration_test.cc
- bigtable/tests/run_integration_tests.sh
Due to some issue with my local branch, need to rebase the branch with upstream/master.
And due to that may be previous PR got closed. So raised this new PR.
> Create integration tests for all mutations.

- bigtable/CMakeLists.txt
- bigtable/admin/CMakeLists.txt
- bigtable/benchmarks/CMakeLists.txt
- bigtable/client/CMakeLists.txt
- bigtable/tests/CMakeLists.txt
- ci/build-docker.sh
This fixes #259.  I think it will make the changes for #103
easier, so start with them.
> Separate CMakeLists.txt into smaller files.

- bigtable/tests/filters_integration_test.cc
During testing following issue found for filter_integration_test
Issue : In test cases, table was created but not deleted.
==> This was causing the issue for empty instance check during startup of the test cases, for second onward run of the testing.
Following changes are done in the test case.
1. Changes done for deletion of the created table for each test case.
2. Removed unnecessary includes.
3. Changed bigtable::testing namespace to anonymous name space.
4. Some cosmetic changes.
> filter_integration_test : Issue fixed for empty instance check at test startup

- bigtable/client/read_modify_write_rule.h
- bigtable/client/read_modify_write_rule_test.cc
> Implement ReadModifyWriteRule::IncrementAmount()

- bigtable/client/CMakeLists.txt
- bigtable/client/table.cc
- bigtable/client/table.h
- bigtable/client/table_check_and_mutate_row_test.cc
- bigtable/tests/data_integration_test.cc
This fixes #208.  It adds the implementation, unit tests, and integration tests.
> Implement check and mutate row

- ci/build-jenkins.sh
Creates a script to refactor all the Jenkins configs.  Also the script
can be kept in sync with the code, should we move or rename the
benchmarks again.
> Jenkins scripting

- bigtable/client/admin_client.h
- bigtable/client/column_family.h
- bigtable/client/data_client.cc
- bigtable/client/data_client.h
- bigtable/client/grpc_error.cc
- bigtable/client/instance_admin_client.h
- bigtable/client/row_range.h
- bigtable/client/table_config.h
Fix a lot of documentation nits.  This is part of the fixes for #342.
> Fix missing documentation

- bigtable/client/CMakeLists.txt
- bigtable/client/table.cc
- bigtable/client/table.h
- bigtable/client/table_sample_row_keys_test.cc
This PR is for SampleRowKeys Implementation(Sync). Fixes #209
> Sample row keys

- bigtable/client/table.cc
- bigtable/tests/data_integration_test.cc
> Integration test for Table::SampleRows().

- bigtable/client/table.h
- bigtable/client/table_sample_row_keys_test.cc
> Default container

- doc/cpp-style-guide.md
Update based on another review.
> Update boilerplate instructions [skip ci].

- README.md
- bigtable/README.md
You probably want to check these files in my branch to see how these look:
https://github.com/coryan/google-cloud-cpp/tree/declare-alpha
> Update README files to declare this is an Alpha release.

- bigtable/CMakeLists.txt
> Update googleapis to current `master`.

- bigtable/client/internal/table_admin.cc
- bigtable/client/internal/table_admin.h
- bigtable/client/internal/table_admin_test.cc
- bigtable/client/table_admin.cc
- bigtable/client/table_admin.h
- bigtable/client/table_admin_strong_types.h
- bigtable/client/table_admin_test.cc
This contains APIs necessary for fixing #377 and #378.
> Consistency API implementation

- bigtable/client/internal/table_admin.cc
- bigtable/client/internal/table_admin.h
- bigtable/client/internal/table_admin_test.cc
- bigtable/client/table_admin.cc
- bigtable/client/table_admin.h
- bigtable/client/table_admin_test.cc
> Delete snapshot API.

- bigtable/client/CMakeLists.txt
- bigtable/client/cluster_config.cc
- bigtable/client/cluster_config.h
- bigtable/client/cluster_config_test.cc
- bigtable/client/instance_admin.h
- bigtable/client/instance_config.cc
- bigtable/client/instance_config.h
- bigtable/client/instance_config_test.cc
This is part of the fixes for #418.  It introduces wrappers for the protos to create an instance.
> Implement create instance pr1

- bigtable/client/internal/table.cc
- bigtable/client/internal/table.h
- bigtable/client/internal/table_test.cc
- bigtable/client/table.cc
- bigtable/client/table_test.cc
> Make bigtable::Table CopyAssignable.

- bigtable/client/internal/table_admin.cc
- bigtable/client/internal/table_admin.h
- bigtable/client/internal/table_admin_test.cc
- bigtable/client/metadata_update_policy.cc
- bigtable/client/metadata_update_policy.h
- bigtable/client/metadata_update_policy_test.cc
- bigtable/client/table_admin.cc
- bigtable/client/table_admin.h
- bigtable/client/table_admin_test.cc
> List snapshot

- bigtable/client/internal/table.cc
- bigtable/client/internal/table_admin.cc
- bigtable/client/internal/unary_rpc_utils.h
> Optimize error messages in RpcUtils.

- .travis.yml
- ci/build-linux.sh
This is the latest LTS release for Ubuntu, good practice to test
on it.
> Run one CI build on Ubuntu 18.04.

- bigtable/client/instance_config.h
One of those where the main branch got more strict checks, and
a PR did not include the additional checks in its build.
> Fix build breakage.

- bigtable/client/BUILD
- storage/client/BUILD
- storage/client/CMakeLists.txt
- storage/client/storage_client.bzl
- storage/client/storage_client_unit_tests.bzl
Add Bazel support to the skeleton library.
> Add Bazel support for the storage/ directory.

- bigtable/client/instance_admin.h
- bigtable/examples/bigtable_samples_instance_admin.cc
It was missed in previous #419 PR, hence created new PR for sample snippet
> Add sample snippet for InstanceAdmin::GetInstance()

- bigtable/examples/bigtable_samples.cc
- bigtable/examples/run_examples_emulator.sh
- bigtable/examples/run_examples_production.sh
- bigtable/examples/run_examples_utils.sh
- bigtable/tests/integration_tests_utils.sh
- bigtable/tests/run_integration_tests_emulator.sh
- bigtable/tools/run_emulator_utils.sh
- ci/build-docker.sh
- ci/build-jenkins.sh
Create scripts to run the samples during the CI build.  I found bugs in them that have been unnoticed because we never execute them.
> Run samples in ci build

- bigtable/client/CMakeLists.txt
- bigtable/client/bigtable_client.bzl
- bigtable/client/internal/bulk_mutator.cc
- bigtable/client/internal/bulk_mutator.h
- bigtable/client/internal/bulk_mutator_test.cc
- bigtable/client/internal/table.cc
- bigtable/client/internal/table.h
- bigtable/client/internal/table_test.cc
- bigtable/client/row_reader.cc
- bigtable/client/row_reader.h
- bigtable/client/row_reader_test.cc
- bigtable/client/table.h
- bigtable/client/table_strong_types.h
> AppProfileID in Table:: member functions.

- bigtable/client/client_options_test.cc
- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_common.bzl
- google/cloud/internal/setenv.cc
- google/cloud/internal/setenv.h
- storage/client/CMakeLists.txt
- storage/client/credentials.cc
- storage/client/internal/service_account_credentials.cc
- storage/client/internal/service_account_credentials.h
- storage/client/internal/service_account_credentials_test.cc
- storage/client/storage_client.bzl
This fixes #523.  Note that on Windows the environment variable is
called something else.
> Default credentials raise if HOME is not set.

- .travis.yml
Part of the fixes for #19. Some of the comments were out of date,
also the order of the environment variables did not make sense.
> Cleanup the travis yaml file.

- bigtable/client/instance_admin.cc
- bigtable/client/instance_admin.h
- bigtable/client/instance_admin_test.cc
- bigtable/client/internal/instance_admin.cc
- bigtable/client/internal/instance_admin.h
- bigtable/client/internal/instance_admin_test.cc
- bigtable/examples/bigtable_samples_instance_admin.cc
- bigtable/tests/instance_admin_integration_test.cc
Added Instance_id to the api ListClusters.
Some of the test cases are not run on the emulator.
Please let me know how to test these test cases, e.g. example is not running with emulator
> #490: Addition of instance_id in ListClusters api

- bigtable/tests/integration_tests_utils.sh
- ci/kokoro/ubuntu/build.sh
- ci/kokoro/ubuntu/continuous.cfg
- ci/kokoro/ubuntu/presubmit.cfg
- google/cloud/internal/throw_delegate.cc
Initial Kokoro configurations.  This will have no effect until the companion CL (cl/193853372) is submitted.  In fact, they should be merged before the CL is.
> Create kokoro configs

- firestore/client/field_path.cc
- firestore/client/field_path.h
- firestore/client/field_path_test.cc
> Improve code coverage for firestore::FieldPath.

- CMakeLists.txt
- README.md
- ci/Dockerfile.ubuntu
- ci/Dockerfile.ubuntu-trusty
- storage/CMakeLists.txt
Per the discussion on the internal thread, document what versions we need of each compiler, tool, and library.
> Require clang-3.8 and list dependencies.

- bigtable/tests/admin_integration_test.cc
I also created #593 because I think these tests are gettng repetitive.
> Make the TableAdmin integration tests easier to follow.

- bigtable/client/cluster_config.h
- bigtable/client/instance_admin.cc
- bigtable/client/instance_admin.h
- bigtable/client/instance_admin_client.cc
- bigtable/client/instance_admin_client.h
- bigtable/client/instance_admin_test.cc
- bigtable/client/testing/mock_instance_admin_client.h
- bigtable/examples/bigtable_samples_instance_admin.cc
- bigtable/tests/instance_admin_emulator.cc
- bigtable/tests/instance_admin_integration_test.cc
The PR includes unit tests, integration test, sample code and actual function implementation.
> implementation of InstanceAdmin::UpdateCluster

- bigtable/ci/run_integration_tests.sh
The bigtable emulator crashes sometimes (see #441 for details),
and when it does we need to restart the build or tests. Instead
of manually restarting things have a robot do it.
> Workaround emulator crashes in CI builds.

- google/cloud/firestore/field_path.cc
- google/cloud/firestore/field_path.h
- google/cloud/firestore/field_path_test.cc
> Move `firestore::` namespace to `google::cloud::`

- .travis.yml
- ci/build-macosx.sh
- ci/install-macosx.sh
This is part of the fixes for #118.
Before:
https://travis-ci.org/coryan/google-cloud-cpp/jobs/387211269
After:
https://travis-ci.org/coryan/google-cloud-cpp/jobs/387232549
> Enable ccache on macOS

- .github/issue_template.md
And then a cleanup for clarity.
> Include Google Cloud Storage as a component [skip ci].

- ci/check-style.sh
- google/cloud/bigtable/internal/bulk_mutator.cc
- google/cloud/bigtable/internal/bulk_mutator_test.cc
- google/cloud/bigtable/internal/table_test.cc
- google/cloud/bigtable/row_reader_test.cc
- google/cloud/bigtable/table_bulk_apply_test.cc
> Fully qualify grpc::StatusCode values.

- google/cloud/storage/CMakeLists.txt
- google/cloud/storage/object_metadata.cc
- google/cloud/storage/object_metadata.h
- google/cloud/storage/object_metadata_test.cc
- google/cloud/storage/storage_client.bzl
- google/cloud/storage/storage_client_unit_tests.bzl
We will use this class soon to create objects (#553).
> Introduce ObjectMetadata class.

- google/cloud/bigtable/examples/bigtable_samples.cc
This fixes #646. We want to show best-practices to our customers.
> Pass bigtable::Table by value in the samples.

- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_common_unit_tests.bzl
- google/cloud/internal/optional.h
- google/cloud/internal/optional_test.cc
Add unit test and fix the implementation of optional<T>. This is
(still) not a full implementation, nor do we intend to build one.
Thanks to @deepankarsharma who caught the problems during
his review.
> Fix implementation of optional<T>.

- doc/adr/2018-06-13-storage-always-retries.md
- doc/adr/adr-template.md
Based on our discussion during #705.
> Propose new ADR [skip ci].

- ci/colors.sh
- google/cloud/storage/examples/run_examples_production.sh
- google/cloud/storage/examples/run_examples_testbench.sh
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/tests/run_integration_tests_testbench.sh
- google/cloud/storage/tools/run_testbench_utils.sh
The examples should run against the fake to avoid
bitrot.
> Run the examples against the GCS fake.

- google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/instance_admin_test.cc
- google/cloud/bigtable/internal/instance_admin.cc
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/internal/instance_admin_test.cc
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_integration_test.cc
This PR contains implementation, unit tests and sample snippets. This is part of #643.
> InstanceAdmin::GetCluster Implementation and Unit Tests

- google/cloud/bigtable/examples/bigtable_samples.cc
This is a simpler model, no need to complicate the code for users.
This fixes #645.
> Pass bigtable::TableAdmin by value in sample snippets.

- google/cloud/bigtable/polling_policy_test.cc
- google/cloud/bigtable/rpc_retry_policy_test.cc
Changes done as per your suggestions. 
Tested on production successfully.
> Polling Policy one failure case handling on server overload

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/internal/default_client.h
- google/cloud/storage/tests/testbench.py
This fixes #746. Thanks to @frankyn for identifying the problem.
> Fix insert object operation

- google/cloud/bigtable/internal/rowreaderiterator.h
- google/cloud/internal/optional.h
- google/cloud/internal/optional_test.cc
Since we have an optional template class, might as well use it.
Note that I had to fix a few things in optional<T> to get it to
work.
> Implement bigtable::OptionalRow using optional<T>.

- ci/check-include-guards.gawk
- ci/check-style.sh
- google/cloud/internal/backoff_policy.h
The script to check include guards was not really exiting with
an error code.  Fixed that and the one include guard that managed
to sneak by.
> Fix include guard and the script to check them.

- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/internal/table.cc
- google/cloud/bigtable/internal/unary_client_utils.h
- google/cloud/bigtable/metadata_update_policy.cc
- google/cloud/bigtable/metadata_update_policy.h
- google/cloud/bigtable/polling_policy.h
- google/cloud/bigtable/row_reader.cc
- google/cloud/bigtable/row_reader_test.cc
- google/cloud/bigtable/rpc_backoff_policy.cc
- google/cloud/bigtable/rpc_backoff_policy.h
- google/cloud/bigtable/rpc_backoff_policy_test.cc
- google/cloud/bigtable/rpc_retry_policy.cc
- google/cloud/bigtable/rpc_retry_policy.h
- google/cloud/bigtable/rpc_retry_policy_test.cc
> changed snake_case functions which are not simple accessors

- google/cloud/storage/client.h
- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/internal/curl_wrappers.cc
- google/cloud/storage/internal/default_client.h
- google/cloud/storage/internal/read_object_range_request.cc
- google/cloud/storage/tests/CMakeLists.txt
- google/cloud/storage/tests/curl_request_integration_test.cc
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/tests/run_integration_tests_production.sh
- google/cloud/storage/tests/run_integration_tests_testbench.sh
- google/cloud/storage/tests/testbench.py
Including integration tests and sample snippets.
> Implement Read() API.

- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
I should have included these in the previous PR.
> Add sample for ListObjects().

- google/cloud/internal/setenv.cc
- google/cloud/storage/internal/parse_rfc3339.cc
https://msdn.microsoft.com/en-us/library/b0084kay.aspx
> Fix WIN32 macro.

- google/cloud/storage/tests/curl_request_integration_test.cc
Coverage dipped below 95%, fixing some low hanging fruit.
> Fix coverage for CurlRequest.

- google/cloud/storage/CMakeLists.txt
- google/cloud/storage/storage_client_unit_tests.bzl
Somehow I forgot to add this to the CMake file.
> Actually compile and run the credentials test.

- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/internal/instance_admin.h
> Use PollingPolicy in InstanceAdmin operations.

- google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
- google/cloud/bigtable/examples/run_examples_emulator.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.cc
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/internal/instance_admin_test.cc
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_integration_test.cc
This is part of the fixes for #780. It implements GetAppProfile(), DeleteAppProfile(),
the unit tests for each, the samples for each, runs the examples as part of the CI
build, and extends the integration test to use both functions.
> Implement GetAppProfile() and DeleteAppProfile().

- google/cloud/bigtable/tests/instance_admin_emulator.cc
The instance emulator was returning the same cluster multiple
times if there was more than one instance created in the emulator.
This was found just by code inspection, it was not causing
problems because we never use the emulator with multiple
instances or projects.
> Fix ListClusters() in instance emulator.

- google/cloud/bigtable/tests/admin_integration_test.cc
- google/cloud/bigtable/tests/instance_admin_integration_test.cc
> Simplify integration tests  table, instance and cluster admin operations.

- google/cloud/bigtable/examples/BUILD
- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
- google/cloud/bigtable/table.h
This is part of the fixes for #329. It could be improved, for
example by writing a companion Doxygen document that explains
each step, but it is fairly self-explanatory as-is (I think).
> An example of using application profiles.

- google/cloud/storage/internal/insert_object_media_request.h
- google/cloud/storage/internal/insert_object_media_request_test.cc
- google/cloud/storage/well_known_parameters.h
> Implement missing request parameters for storage::InsertObjectMediaRequest

- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/testbench.py
This is part of the work for #822. It implements an incomplete
client::ListObjects, but this is a good stopping point to keep
the PRs small-ish.
> Initial Client::ListBuckets.

- google/cloud/storage/internal/credential_constants.h
- google/cloud/storage/internal/openssl_util.h
- google/cloud/storage/internal/service_account_credentials.h
- google/cloud/storage/internal/service_account_credentials_test.cc
- google/cloud/storage/retry_policy_test.cc
These were pointed out in review when merging code into the internal repo that mirrors this GitHub repo (in changelist 203784390).
> Clean up style nits following 4613a08.

- google/cloud/storage/internal/generic_object_request.h
I merged before noticing you had asked for this change in the review.
> Fix description of GenericObjectRequest.

- google/cloud/storage/examples/run_examples_utils.sh
Refactor common code to run the examples to a function.
> Simplify driver for storage examples.

- google/cloud/storage/client.h
- google/cloud/storage/client_object_acl_test.cc
- google/cloud/storage/examples/storage_object_acl_samples.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/tests/testbench.py
This fixes #839. It implements the API, the unit tests, the
integration test, and the example.
> Implement Client::DeleteObjectAcl

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/tests/bucket_integration_test.cc
- google/cloud/storage/tests/run_integration_tests_testbench.sh
- google/cloud/storage/tests/testbench.py
Some of the tests were passing when they should not, others were
simply missing. This gets things running again.
> Fix integration tests and examples.

- google/cloud/storage/bucket_metadata.cc
- google/cloud/storage/bucket_metadata.h
- google/cloud/storage/bucket_metadata_test.cc
> Implement BucketMetadata::encryption.

- google/cloud/storage/bucket_metadata.cc
- google/cloud/storage/bucket_metadata.h
- google/cloud/storage/bucket_metadata_test.cc
> Implement BucketMetadata.logging

- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/instance_admin_test.cc
- google/cloud/bigtable/internal/instance_admin.cc
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/internal/instance_admin_test.cc
- google/cloud/bigtable/metadata_update_policy.cc
- google/cloud/bigtable/metadata_update_policy.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_emulator.cc
- google/cloud/bigtable/tests/instance_admin_integration_test.cc
This contains IAMPolicy APIs, unit tests and integration test for them.
> IAMPolicy APIs

- google/cloud/CMakeLists.txt
- google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/instance_admin_test.cc
- google/cloud/bigtable/internal/instance_admin.cc
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/internal/instance_admin_test.cc
- google/cloud/bigtable/tests/instance_admin_emulator.cc
- google/cloud/bigtable/tests/instance_admin_integration_test.cc
- google/cloud/google_cloud_cpp_common.bzl
- google/cloud/iam_binding.h
- google/cloud/iam_bindings.cc
- google/cloud/iam_bindings.h
- google/cloud/iam_bindings_test.cc
- google/cloud/iam_policy.h
This finishes #416. It tweaks the APIs for IAM to make them
similar to other APIs in InstanceAdmin, and implements the
examples for those APIs.
> Complete IAM implementation.

- google/cloud/storage/bucket_access_control.cc
- google/cloud/storage/bucket_access_control.h
- google/cloud/storage/internal/access_control_common.cc
- google/cloud/storage/internal/access_control_common.h
- google/cloud/storage/object_access_control.cc
- google/cloud/storage/object_access_control.h
> Fix optional fields in *AccessControl.

- google/cloud/bigtable/doc/bigtable-main.dox
- google/cloud/bigtable/doc/bigtable-quickstart.dox
- google/cloud/bigtable/examples/BUILD
- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/bigtable_quickstart.cc
Evidently different from the hello world example.
> Implement the Quickstart example.

- google/cloud/storage/CMakeLists.txt
- google/cloud/storage/internal/curl_request_builder.h
- google/cloud/storage/internal/object_acl_requests.cc
- google/cloud/storage/internal/object_acl_requests.h
- google/cloud/storage/internal/object_acl_requests_test.cc
- google/cloud/storage/object_access_control.h
- google/cloud/storage/storage_client.bzl
- google/cloud/storage/well_known_headers.h
This is part of the work for #843, it implements the request
object.
> Implement request for PatchObjetAcl.

- google/cloud/storage/storage_class.h
Does not matter yet, but later it will be a problem.
> Storage class functions should be inline.

- README.md
- google/cloud/bigtable/README.md
All the bugs for the milestone are closed.
/cc: @jabubake @billyjacobson @jefesaurus.
> Propose upgrading client to Beta [skip ci].

- google/cloud/bigtable/README.md
Update the release notes on the new v0.2.x branch.
> Update v0.2.x release notes [skip ci].

- google/cloud/storage/bucket_metadata.cc
- google/cloud/storage/bucket_metadata.h
- google/cloud/storage/bucket_metadata_test.cc
This is part of the work for #934. It fixes BucketMetadata.
> Fix optional fields in BucketMetadata.

- google/cloud/storage/bucket_metadata.cc
- google/cloud/storage/bucket_metadata.h
- google/cloud/storage/bucket_metadata_test.cc
- google/cloud/storage/internal/bucket_requests.cc
- google/cloud/storage/internal/bucket_requests.h
- google/cloud/storage/internal/bucket_requests_test.cc
- google/cloud/storage/internal/common_metadata.h
- google/cloud/storage/well_known_parameters.h
This is part of the changes for #821. It introduces the request
object to create a bucket, and the corresponding query parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/977)
> Implement Client::CreateBucketRequest.

- google/cloud/storage/bucket_test.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/internal/bucket_requests.cc
- google/cloud/storage/internal/bucket_requests.h
- google/cloud/storage/internal/bucket_requests_test.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/testbench.py
This fixes #820. This PR implements the API, a unit test, and
ads some sample code.  The sample does not run in the CI build
because we need #821 for that. Likewise, we cannot implement an
integration test without #821.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/978)
> Implement Client::DeleteBucket.

- google/cloud/bigtable/internal/table.h
- google/cloud/bigtable/table.h
Addresses issue #336.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/918)
> Issue#336 code optimization

- google/cloud/storage/bucket_metadata.h
- google/cloud/storage/bucket_test.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/bucket_integration_test.cc
- google/cloud/storage/tests/testbench.py
This is part of the work for #821. It implements the API, the
unit tests, and the code samples. The code samples do *NOT* run
in the CI build yet, because we need to implement DeleteBucket
or the tests will constantly leak buckets. For the same reason,
the integration tests do not call this API either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/983)
> Implement Client::CreateBucket

- google/cloud/storage/tests/testbench.py
This will be used in the DefautlObjectAccessControls CRUD APIs,
such as #836.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/984)
> Implement DefaultObjectAcl support in testbench.

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/tests/bucket_integration_test.cc
- google/cloud/storage/tests/testbench.py
This fixes #821. It implements the integration tests, and runs
the examples as part of the CI build. Oh, and I fixed some bugs
caught by actually running these things `</shame>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/987)
> Integration tests for CreateBucket/DeleteBucket.

- google/cloud/storage/client.h
- google/cloud/storage/client_bucket_acl_test.cc
- google/cloud/storage/examples/storage_bucket_acl_samples.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
This is part of the fixes for #828. It implements the API, the unit tests,
and the code samples. The integration tests will come in a future PR,
we should merge #970 and fix #827 first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/979)
> Implement Client::GetBucketAcl.

- google/cloud/storage/client.h
- google/cloud/storage/client_bucket_acl_test.cc
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_acl_samples.cc
- google/cloud/storage/internal/bucket_acl_requests.h
- google/cloud/storage/internal/bucket_acl_requests_test.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/bucket_integration_test.cc
This fixes #829. It implements the API, unit tests, extends
the integration test to use this new API, and adds a sample
snippet.
FYI: I enabled reviewable.io so we can take it for a spin.
/cc: @houglum FYI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/970)
> Implement Client::CreateBucketAcl.

- google/cloud/storage/bucket_metadata.cc
- google/cloud/storage/bucket_metadata_test.cc
- google/cloud/storage/bucket_test.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/internal/bucket_requests.cc
- google/cloud/storage/internal/bucket_requests.h
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/bucket_integration_test.cc
- google/cloud/storage/tests/testbench.py
This fixes #824. It implements the API, unit tests, extends the
integration test to run this API, and a (very small) example. The
integration tests and example are part of the CI build.
Also fixed BucketMetadata because I accidentally droppped one of
my commits earlier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/988)
> Implement Client::UpdateBucket.

- ci/define-example-runner.sh
- ci/run-example.sh
- google/cloud/bigtable/examples/run_examples_emulator.sh
- google/cloud/bigtable/examples/run_examples_production.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/storage/examples/run_examples_testbench.sh
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_default_object_acl_samples.cc
This fixes #884.  With this change the bigtable and storage examples are driven by the same bash functions. Also, the storage examples are easier to grok.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/995)
> Refactor example driver scripts.

- bazel/google_cloud_cpp_deps.bzl
- ci/test-install/Makefile
- ci/travis/build-docker.sh
- cmake/ExternalProjectHelper.cmake
- cmake/IncludeGrpc.cmake
- cmake/external/grpc.cmake
This fixes #957. With gRPC 1.14.0 we can start create an example of
using OpenCensus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/980)
> Update to grpc-1.14.0.

- google/cloud/storage/client.h
- google/cloud/storage/client_bucket_acl_test.cc
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_acl_samples.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/bucket_integration_test.cc
This fixes #831. It adds the API, the unit tests, extends the
integration test to use the new API, adds the examples, and runs the
example as part of the CI build.
/cc: @houglum
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1000)
> Implement Client::UpdateBucketAcl().

- google/cloud/storage/bucket_metadata.cc
- google/cloud/storage/bucket_metadata.h
- google/cloud/storage/bucket_metadata_test.cc
- google/cloud/storage/bucket_test.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/internal/bucket_requests.cc
- google/cloud/storage/internal/bucket_requests_test.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/bucket_integration_test.cc
- google/cloud/storage/tests/testbench.py
This fixes #823, and computes the Bucket CRUD stuff. It implements the
API, the unit tests, an integration test, code snippets, and runs the
snippets in the CI build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1001)
> Implement Client::PatchBucket.

- google/cloud/storage/CMakeLists.txt
- google/cloud/storage/internal/curl_streambuf.cc
- google/cloud/storage/internal/http_response.cc
- google/cloud/storage/internal/http_response_test.cc
- google/cloud/storage/object_stream.cc
- google/cloud/storage/object_stream.h
- google/cloud/storage/storage_client.bzl
- google/cloud/storage/storage_client_unit_tests.bzl
- google/cloud/storage/tests/object_integration_test.cc
The code was just never signalling eof() so the application would not
know to check the status code. Now the stream reports eof() immediately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1006)
> Handle attempts to download non-existent objects.

- google/cloud/storage/client.h
- google/cloud/storage/internal/curl_request_builder.h
- google/cloud/storage/internal/list_objects_request.h
- google/cloud/storage/testing/mock_http_request.h
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/tests/testbench.py
- google/cloud/storage/well_known_parameters.h
We missed the optional parameter to iterate over all the object
versions, this comes handy when you want to delete all the object
versions in a bucket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1008)
> Implement Versions parameter for ListObjects.

- google/cloud/storage/well_known_parameters.h
This is just cleanup to make it easier to maintain this file.
/cc: @houglum
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1015)
> Alphabetize well-known parameters.

- google/cloud/storage/internal/object_requests.cc
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/internal/object_requests_test.cc
- google/cloud/storage/object_metadata.cc
- google/cloud/storage/object_metadata.h
- google/cloud/storage/object_metadata_test.cc
This is part of the changes for #817. Implement the request class which
will used for Client::UpdateObject().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1013)
> Implement UpdateObjectRequest.

- google/cloud/storage/internal/generic_request.h
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/well_known_parameters.h
This fixes #1025. It adds the parameter to all requests, and adds
an integration test that uses the parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1038)
> Implement the QuotaUser parameter.

- google/cloud/storage/internal/generic_request.h
- google/cloud/storage/tests/bucket_integration_test.cc
- google/cloud/storage/tests/testbench.py
- google/cloud/storage/well_known_parameters.h
This fixes #1024. It implements the parameter, extends the testbench
with minimal support for an integration test, and adds the integration
test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1039)
> Implement Fields optional query parameter.

- google/cloud/bigtable/admin_client.cc
- google/cloud/bigtable/admin_client.h
- google/cloud/bigtable/internal/table_admin.h
- google/cloud/bigtable/table_admin.cc
- google/cloud/bigtable/table_admin.h
- google/cloud/bigtable/table_admin_test.cc
- google/cloud/bigtable/testing/inprocess_admin_client.cc
- google/cloud/bigtable/testing/inprocess_admin_client.h
- google/cloud/bigtable/testing/mock_admin_client.h
Basic Implementation of CreateTableFromSnapshot, Unit test case creation is in progress
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/994)
> Adding basic implementation of CreateTableFromSnapshot

- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/object_metadata.cc
- google/cloud/storage/object_metadata.h
- google/cloud/storage/object_metadata_test.cc
- google/cloud/storage/object_test.cc
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/tests/testbench.py
This fixes #817. It implements the API, the usual unit tests, expands
the integration tests to use the API, adds an example, and runs the
example in the CI builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1027)
> Implement Client::UpdateObject().

- .codecov.yml
- ci/define-example-runner.sh
- google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
- google/cloud/bigtable/examples/bigtable_samples.cc
- google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
- google/cloud/bigtable/examples/bigtable_samples_instance_admin_ext.cc
- google/cloud/bigtable/examples/run_examples_emulator.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/storage/examples/run_examples_utils.sh
The examples are part of the code we expose to our users, and needs
to be tested and executed.  In this PR:
* We run all examples for the storage client, some were missed in previous passes.
* We verify that calling the examples without an argument produces a `Usage` message.
* We change the some of the Bigtable examples to produce better usage messages.
* We enable coverage reporting for Cloud Bigtable examples, it was disabled because we never executed the examples before (see #492).
This pushes the coverage for the bigtable examples from around 45% to over 90%.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1045)
> Improve coverage of all examples.

- google/cloud/storage/internal/object_requests.cc
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/internal/object_requests_test.cc
- google/cloud/storage/object_metadata.cc
- google/cloud/storage/object_metadata.h
- google/cloud/storage/object_metadata_test.cc
This is part of the changes for #815.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1062)
> Implement ObjectPatchRequest.

- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
Lots of repetitive code moved to a single function.
/cc: @houglum
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1074)
> Refactor CurlRequestBuider setup.

- google/cloud/bigtable/internal/table.h
- google/cloud/bigtable/internal/table_test.cc
- google/cloud/bigtable/table.h
- google/cloud/bigtable/table_test.cc
It was not passing the app profile id value. Add some accessors and
tests to verify it works correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1075)
> Fix constructor with AppProfile and Policies.

- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/object_test.cc
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/tests/testbench.py
This fixes #815. It implements the Patch API, the usual unit tests,
expands the integration tests to use the new API, adds examples, and
runs the examples as part of the CI build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1072)
> Implement Client::PatchObject.

- google/cloud/storage/tests/testbench.py
This extends the testbench to "support" the notification APIs.
Part of the work for #1033, #1034, #1035, and #1036.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1083)
> Implement Notification APIs in testbench.

- CONTRIBUTING.md
Update recommended Ubuntu version to what we actually use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1092)
> Update recommended Ubuntu version.

- google/cloud/bigtable/examples/bigtable_samples.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/table_admin.h
this fixes #1061
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1093)
> Implement sample snippet for TableAdmin::WaitForConsistencyCheck

- google/cloud/storage/internal/object_requests.cc
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/internal/object_requests_test.cc
- google/cloud/storage/object_metadata.cc
- google/cloud/storage/object_metadata.h
- google/cloud/storage/well_known_parameters.h
This is part of the work for #812. It implements the request object
for `Objects: copy`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1085)
> Implement CopyObjectRequest.

- google/cloud/storage/client.h
- google/cloud/storage/client_notifications_test.cc
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_notification_samples.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/bucket_integration_test.cc
This fixes #1034. It implements the API, the usual unit tests, extends
the integration test to call the API, adds a sample, and runs the sample
as part of the CI build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1106)
> Implement Client::GetNotification().

- google/cloud/storage/tests/testbench.py
This is part of the work for #846, #847, and #848.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1114)
> Implement IAM functions in testbench.

- google/cloud/storage/bucket_metadata.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1133)
> Make comments a real Doxygen commit.

- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_common.bzl
- google/cloud/iam_bindings.cc
- google/cloud/iam_bindings.h
- google/cloud/iam_policy.cc
- google/cloud/iam_policy.h
- google/cloud/storage/internal/bucket_requests.cc
- google/cloud/storage/internal/bucket_requests.h
- google/cloud/storage/internal/bucket_requests_test.cc
This is part of the work for #846.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1124)
> Implement parser for GetIamPolicy responses.

- google/cloud/bigtable/doc/bigtable-samples.dox
- google/cloud/bigtable/examples/BUILD
- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/README.md
- google/cloud/bigtable/examples/bigtable_samples.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_snippets.cc
- google/cloud/bigtable/table_admin.h
Part of the fixes for #1107
Need to create another PR for this Issue for data_admin_snippets.cc for following examples
Apply, BulkApply, ReadRow, ReadRows, ReadRowsWithLimit, CheckAndMutate, ReadModifyWrite, SampleRows, SampleRowsCollections,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1142)
> Issue 1107 split table admin samples

- google/cloud/iam_bindings.h
- google/cloud/storage/bucket_test.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/BUILD
- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_iam_samples.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/bucket_integration_test.cc
This fixes #846. It implements the API, the usual unit tests, adds a new
integration test for the API (which will get better once we implement
the SetBucketIamPolicy() function), adds some sample code, and makes
sure to run the sample code in the CI builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1140)
> Implement Client::GetBucketIamPolicy()

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
This fixes #1116. It creates examples to get, set, and remove labels.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1129)
> Implement examples using Bucket labels.

- google/cloud/iam_bindings.cc
- google/cloud/iam_bindings_test.cc
- google/cloud/storage/bucket_test.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_iam_samples.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/bucket_integration_test.cc
This fixes #847. I had to fix some of the support classes (IamBindings),
and then implement the API, the usual unit tests, extend the integration
tests to use the new API. This time I added two examples, in line with
the rest of the languages, and the examples are included in the CI
builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1150)
> Implement Client::SetBucketIamPolicy().

- google/cloud/storage/tests/testbench.py
This is part of the fixes for #816.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1144)
> Support for `Objects: rewrite` in the testbench.

- google/cloud/storage/client.h
- google/cloud/storage/well_known_headers.h
A few Doxygen doc comments were missing the example paragraph, or the
code snippet. Made a pass and fixed the ones I found.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1158)
> Cleanup some missing documentation elements.

- google/cloud/storage/tests/testbench.py
The testbench needed some TLC. I cleaned up missing return types, which
are super helpful in my IDE, removed redundant comments, use
lookup_bucket() to find buckets and raise the right error when not
found, and generally removed warnings from the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1160)
> General cleanup of the testbench.

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
This fixes #1117. It creates examples to query, enable, and disable the
billing configuration in a bucket. It also creates examples to upload
and download using the `userProject` parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1152)
> Implement examples using "requester pays" billing.

- google/cloud/bigtable/testing/table_integration_test.cc
- google/cloud/bigtable/testing/table_integration_test.h
- google/cloud/bigtable/tests/admin_integration_test.cc
- google/cloud/bigtable/tests/run_integration_tests_emulator.sh
This fixes #1054.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1139)
> Integration test for CheckConsistency

- google/cloud/storage/benchmarks/run_benchmarks_testbench.sh
- google/cloud/storage/benchmarks/storage_latency_benchmark.cc
- google/cloud/storage/benchmarks/storage_throughput_benchmark.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/generic_request.h
- google/cloud/storage/object_stream.cc
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/tests/testbench.py
The XML API offers significantly better performance than the JSON API
for read and write operations. The library automatically selects the
XML API if the application is not using features only offered by the
JSON API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1159)
> Use XML for read and write operations.

- google/cloud/storage/internal/authorized_user_credentials_test.cc
- google/cloud/storage/internal/credential_constants.h
- google/cloud/storage/internal/service_account_credentials.h
- google/cloud/storage/internal/service_account_credentials_test.cc
- google/cloud/storage/tools/make_jwt_assertion_for_test_data.py
- Fixes issue #769
- Fixes issue #770
- Fixes issue #771
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1143)
> Fixes several TODOs in Credential-related code.

- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
This adds an example to rotate CSEK, that fixes #1119.
It also adds an example of "renaming" which is really a rewrite+delete,
that fixes #1115.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1168)
> Implement more examples based on RewriteObject.

- google/cloud/storage/examples/storage_quickstart.cc
Add Storage Quickstart region tag `storage_quickstart`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1176)
> [Storage] Add Storage Quickstart region tag.

- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_snippets.cc
- google/cloud/bigtable/table_admin.h
Fixes issue #1059
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1173)
> Issue#1059 adding snippets for GenerateConsistencyToken

- google/cloud/bigtable/examples/table_admin_snippets.cc
- google/cloud/bigtable/table_admin.h
Fixes issue #1057
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1174)
> Issue#1057 adding snippets for CreateTableFromSnapshot

- ci/build-jenkins.sh
- google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc
- google/cloud/bigtable/benchmarks/benchmark.cc
- google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc
- google/cloud/bigtable/benchmarks/endurance_benchmark.cc
- google/cloud/bigtable/benchmarks/scan_throughput_benchmark.cc
- google/cloud/bigtable/benchmarks/setup.cc
- google/cloud/bigtable/benchmarks/setup.h
- google/cloud/bigtable/benchmarks/setup_test.cc
- google/cloud/bigtable/ci/run_integration_tests.sh
This fixes #1051.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1188)
> benchmark takes app_profile_id as input

- .gitignore
- google/cloud/storage/testbench/error_response.py
- google/cloud/storage/testbench/testbench.py
This is part of the work for #1187.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1205)
> Move ErrorResponse to its own file.

- google/cloud/storage/client.h
Several fixes to the `google::cloud::storage::Client` class documentation.
First, the top-level description of the class no longer warns that it is an incomplete class, that is no longer true (or at least it is more false than true). The description says how expensive it is to create the class, and the thread-safety guarantees of the class (fixes #803).
Second, the operations are grouped by resource, Doxygen sorts alphabetically by default which makes it hard to see how the functions relate to each other.
Finally, fixed a small TODO where `CopyObject` was supposed to reference `RewriteObject` as a better alternative.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/goog …
> Improve client documentation

- doc/landing/index.html
- doc/landing/version-redirect.html
Also update the default version to 0.2.0, this change is already
deployed to github.io.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1227)
> Update landing pages to also link Storage docs.

- google/cloud/storage/testbench/testbench.py
- google/cloud/storage/testbench/testbench_utils.py
- google/cloud/storage/tests/bucket_integration_test.cc
We were no doing any integration tests for failures, we should at least
verify that the exceptions raised match our minimal expectations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1206)
> Improve code coverage for Bucket operations.

- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/testbench/testbench.py
- google/cloud/storage/tests/object_integration_test.cc
We were no doing any integration tests for failures, we should at least
verify that the exceptions raised match our minimal expectations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1209)
> Improve code coverage for Object operations.

- .cmake-format.py
- cmake/external/c-ares.cmake
- cmake/external/grpc.cmake
We can use the defaults for some of the steps, which makes the code
smaller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1231)
> Simplified external project for grpc and c-ares.

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
I needed an example of uploading a file to include gcs2cbt in the CI
builds. And once you upload a file, you want an example of downloading a
file too.  Eventually we will have direct functions to do this, but the
examples are useful as they stand.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1245)
> Create examples that upload and download files.

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/CMakeLists.txt
- google/cloud/bigtable/tests/bigtable_client_integration_tests.bzl
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
- google/cloud/bigtable/tests/run_integration_tests_emulator.sh
Fixes issue #1263
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1283)
> Issue#1263 Implement noex::InstanceAdmin::GetInstance

- google/cloud/bigtable/doc/bigtable-main.dox
This is an attempt to fix #1211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1290)
> Better landing page for Bigtable Doxygen Documentation

- google/cloud/storage/testbench/gcs_bucket.py
- google/cloud/storage/testbench/testbench.py
This is part of the work to break the testbench script into smaller
pieces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1293)
> Move GcsBucket class to its own file.

- google/cloud/internal/backoff_policy.cc
- google/cloud/internal/backoff_policy_test.cc
- google/cloud/storage/tests/curl_download_request_integration_test.cc
- google/cloud/storage/tests/object_integration_test.cc
MSVC is much better than other compilers at telling you when the
integral types you are using may not be safe. Fixed the warnings by
using the right types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1299)
> Fix potential data loss warnings.

- google/cloud/storage/testbench/gcs_object.py
- google/cloud/storage/testbench/testbench.py
This is part of the work to break the testbench script into smaller
pieces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1302)
> Move GcsObjectVersion class to a separate file.

- google/cloud/bigtable/admin_client.cc
- google/cloud/bigtable/admin_client.h
- google/cloud/bigtable/internal/table_admin.h
- google/cloud/bigtable/testing/inprocess_admin_client.cc
- google/cloud/bigtable/testing/inprocess_admin_client.h
- google/cloud/bigtable/testing/mock_admin_client.h
- google/cloud/bigtable/testing/table_integration_test.cc
- google/cloud/bigtable/testing/table_integration_test.h
- google/cloud/bigtable/tests/admin_async_integration_test.cc
This fixes #1249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1309)
> Implemenation of AsyncCreateTable

- google/cloud/storage/tests/object_integration_test.cc
This is part of the work for #1282. A small cleanup, larger later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1307)
> Refactor code to generate random lines.

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
- google/cloud/bigtable/tests/run_integration_tests_emulator.sh
Fixes issue #1268
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1313)
> Issue#1268 Implement noex::InstanceAdmin::AsyncGetCluster

- google/cloud/bigtable/admin_client.cc
- google/cloud/bigtable/admin_client.h
- google/cloud/bigtable/internal/table_admin.h
- google/cloud/bigtable/testing/inprocess_admin_client.cc
- google/cloud/bigtable/testing/inprocess_admin_client.h
- google/cloud/bigtable/testing/mock_admin_client.h
- google/cloud/bigtable/tests/admin_async_integration_test.cc
This fixes #1251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1315)
> Implement noex::TableAdmin::AsyncModifyColumnFamilies

- google/cloud/bigtable/doc/bigtable-samples-data-client.dox
Fixes issue #1189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1201)
> Issue#1189 : added documentation of CheckAndMutate to modify a value only if it exists

- google/cloud/bigtable/admin_client.cc
- google/cloud/bigtable/admin_client.h
- google/cloud/bigtable/internal/table_admin.h
- google/cloud/bigtable/testing/inprocess_admin_client.cc
- google/cloud/bigtable/testing/inprocess_admin_client.h
- google/cloud/bigtable/testing/mock_admin_client.h
- google/cloud/bigtable/tests/admin_async_integration_test.cc
This fixes #1252  and #1253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1317)
> Implementing noex::TableAdmin::AsyncDropRowsByPrefix and noex::TableAdmin::AsyncDropAllRows

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
Fixes issue #1267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1318)
> Adding Implementation for noex::InstanceAdmin::AsyncDeleteCluster

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1324)
> Document a oneliner to only reformat changed files

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
Fixes issue #1264
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1320)
> Adding Implementation of noex::InstanceAdmin::DeleteInstance

- google/cloud/bigtable/admin_client.cc
- google/cloud/bigtable/admin_client.h
- google/cloud/bigtable/internal/table_admin.h
- google/cloud/bigtable/testing/inprocess_admin_client.cc
- google/cloud/bigtable/testing/inprocess_admin_client.h
- google/cloud/bigtable/testing/mock_admin_client.h
- google/cloud/bigtable/tests/snapshot_async_integration_test.cc
This fixes #1257
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1348)
> implementation of noex::TableAdmin::AsyncDeleteSnapshot

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
Fixes issue #1270
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1343)
> Adding Implementation for noex::InstanceAdmin::AsyncGetAppProfile

- google/cloud/storage/client.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/tests/object_media_integration_test.cc
This fixes #560. It introduces a new member function to download an
object directly to a file. There is the usual integration tests and code
samples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1356)
> Implement download to file

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
Fixes issue #1273
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1355)
> Adding Implementation for noex::InstanceAdmin::AsyncDeleteAppProfile

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/testbench/gcs_bucket.py
- google/cloud/storage/testbench/gcs_object.py
This creates examples showing how to set and release event based holds
and temporary holds. Part of the work for #1029.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1346)
> Implement examples for object holds.

- google/cloud/internal/future_impl.h
- google/cloud/internal/future_impl_test.cc
This implements the shared state for `promise<void>` and `future<void>`.
It is still incomplete, but I am trying to keep the PRs small. Part of
the work for #1345.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1362)
> Implement future+promises shared state for void.

- doc/adr/2018-10-30-storage-metadata-fields-and-optional.md
This is just rewriting #934 as a ADR [skip ci].
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1358)
> Record decision about optional fields as ADR.

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
Fixes issue #1269
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1371)
> Adding Implementation for noex::InstanceAdmin::AsyncCreateAppProfile

- google/cloud/storage/internal/compute_engine_util.cc
I merged the last PR before I saw the style checker complaining at me.
This will appease the style checking gods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1377)
> Make variable names lower_snake_case.

- google/cloud/CMakeLists.txt
- google/cloud/README.md
- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
This PR updates the release notes in the `v0.3.x` branch.
The same commit is being merged into `master` on a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1379)
> Update release notes.

- google/cloud/storage/idempotency_policy.cc
- google/cloud/storage/idempotency_policy_test.cc
Part of the work for #714. Implement the policy for
SetBucketIamPolicyRequest, GetBucketIamPolicyRequest, and
TestBucketIamPermissionsRequest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1382)
> Implement StrictIdempotencyPolicy for IAM ops.

- doc/cutting-a-release.md
This fixes #1352.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1392)
> New document on how to cut a release [skip ci].

- google/cloud/bigtable/CMakeLists.txt
- google/cloud/bigtable/bigtable_client_unit_tests.bzl
- google/cloud/bigtable/data_client.cc
- google/cloud/bigtable/data_client.h
- google/cloud/bigtable/internal/table.h
- google/cloud/bigtable/internal/table_async_check_and_mutate_row_test.cc
- google/cloud/bigtable/testing/inprocess_data_client.cc
- google/cloud/bigtable/testing/inprocess_data_client.h
- google/cloud/bigtable/testing/mock_data_client.h
- google/cloud/bigtable/tests/data_async_integration_test.cc
Following the synchronous version, there are no retries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1384)
> Implement AsyncCheckAndMutateRow

- google/cloud/internal/future_impl.h
- google/cloud/internal/future_impl_test.cc
This is part of the work for #1345. It implements the shared state for
`future<T>` and `promise<T>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1403)
> Implement shared state for future<T>.

- google/cloud/bigtable/admin_client.cc
- google/cloud/bigtable/admin_client.h
- google/cloud/bigtable/testing/inprocess_admin_client.cc
- google/cloud/bigtable/testing/inprocess_admin_client.h
- google/cloud/bigtable/testing/mock_admin_client.h
This is a part of #1256.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1415)
> Add *Consistency* calls to TableAdminClient.

- google/cloud/internal/future_impl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1416)
> Fix MSVC warnings.

- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_common_unit_tests.bzl
- google/cloud/internal/future_base.h
- google/cloud/internal/future_generic.h
- google/cloud/internal/future_generic_then_test.cc
- google/cloud/internal/future_void.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1417)
> Refactor is_ready() to future_base<T>.

- google/cloud/internal/future_generic.h
- google/cloud/internal/future_generic_then_test.cc
- google/cloud/internal/future_impl.h
- google/cloud/internal/future_then_impl.h
- google/cloud/internal/future_void.h
This is part of the changes for #1345.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1418)
> Implement future<T>::then().

- google/cloud/storage/idempotency_policy.cc
- google/cloud/storage/idempotency_policy_test.cc
This is part of the work for #714. It implements StrictIdempotencyPolicy
for notifications and the service account. This completes the
implementation of the class, no more TODO() entries, yay!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1409)
> Finish implementation of StrictIdempotencyPolicy.

- google/cloud/bigtable/internal/completion_queue_impl.h
There are race conditions possible in AsyncUnaryRpcFunctor and
AsyncTimerFunctor similar to the one in #1419.
Please refer to comments in the code for specific explanations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1420)
> Fix races in Async{UnaryRpc,Timer}Functor.

- google/cloud/storage/examples/storage_object_samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1437)
> Fix a storage region tag

- google/cloud/storage/testing/storage_integration_test.h
- google/cloud/storage/tests/CMakeLists.txt
- google/cloud/storage/tests/bucket_integration_test.cc
- google/cloud/storage/tests/object_insert_integration_test.cc
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/tests/object_media_integration_test.cc
- google/cloud/storage/tests/run_integration_tests_production.sh
- google/cloud/storage/tests/run_integration_tests_testbench.sh
- google/cloud/storage/tests/storage_client_integration_tests.bzl
This is partly to make the object integration test smaller (#1282) and
partly to make room for the new InsertObjectMedia() tests that will also
accept the object metadata values (#1311).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1435)
> Refactor InsertObjectMedia() integration tests.

- google/cloud/internal/future_generic_then_test.cc
- google/cloud/internal/future_void_then_test.cc
Part of the changes for #1345.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1443)
> Fix remaining test TODOs.

- google/cloud/bigtable/internal/async_poll_op.h
- google/cloud/bigtable/internal/async_poll_op_test.cc
This very much follows the decisions from #1398.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1441)
> Make AsyncPollOp cancellable.

- google/cloud/bigtable/internal/async_poll_op.h
This is a part of #1256.
It's almost a copy-paste from `AsyncRetryOp`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1447)
> Statically check Operation's traits in AsyncPollOp

- README.md
Also make the Travis badge say that it is from Travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1451)
> Enable Kokoro badges [skip ci].

- google/cloud/bigtable/internal/async_poll_op_test.cc
- google/cloud/bigtable/internal/async_retry_op_test.cc
This follows the sugestions from #1441.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1444)
> Improve Async{Poll,Retry} test readbility.

- google/cloud/bigtable/tests/admin_async_integration_test.cc
This is shamelessly stolen from the sync version and slightly modified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1455)
> Add an integration test for AsyncAwaitConsistency.

- google/cloud/internal/filesystem.cc
- google/cloud/internal/filesystem.h
- google/cloud/internal/filesystem_test.cc
I am planning to do uploads of small files using simple (or multipart)
uploads, and uploads of large files using resumable uploads. I need some
function to give me a file size, so here it is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1458)
> Implement file_size() function.

- google/cloud/bigtable/examples/BUILD
- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/run_examples_emulator.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_async_snippets.cc
- google/cloud/bigtable/internal/table_admin.h
- google/cloud/bigtable/table_admin.cc
- google/cloud/bigtable/table_admin.h
- google/cloud/bigtable/tests/CMakeLists.txt
- google/cloud/bigtable/tests/admin_async_future_integration_test.cc
- google/cloud/bigtable/tests/bigtable_client_integration_tests.bzl
- google/cloud/bigtable/tests/run_integration_tests_emulator.sh
This implements the first operations in the Cloud Bigtable client that
return futures-from-the-future as the result of the operation. The
application can then attach a callback or block until the future
completes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1456)
> Implement async operations that return futures.

- google/cloud/storage/idempotency_policy.cc
- google/cloud/storage/idempotency_policy.h
- google/cloud/storage/idempotency_policy_test.cc
- google/cloud/storage/internal/object_requests.cc
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/internal/object_requests_test.cc
This is part of the work for #559.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1461)
> Implement request types for resumable uploads.

- ci/travis/upload-docs.sh
- doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1463)
> More updates to the release steps.

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
This is required for #1260.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1468)
> Add AsyncCreateCluster to InstanceAdminClient.

- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/internal/table.h
- google/cloud/bigtable/internal/table_admin.h
This fixes #1385.
This is required to implemnt cancellations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1479)
> Return AsyncOperation from all async operations.

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
Fixes issue #1259
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1473)
> Implement AsyncCreateInstance

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
This is needed for #1265.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1481)
> Add AsyncListClusters to InstanceAdminClient.

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
Fixes issue #1271
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1482)
> Implement InstanceAdmin::AsyncUpdateAppProfile

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
Fixes issue #1261
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1492)
> Adding implementation of AsyncUpdateInstance

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
Fixes Issue #1266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1509)
> Adding implementation of AsyncUpdateCluster

- google/cloud/storage/testing/mock_client.h
This will be needed when testing LoggingResumableUploadSession and
RetryResumableUploadSession.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1515)
> Define a mock for ResumableUploadSession.

- google/cloud/storage/client.h
- google/cloud/storage/client_object_copy_test.cc
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/idempotency_policy_test.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client_test.cc
- google/cloud/storage/internal/object_requests.cc
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/internal/object_requests_test.cc
- google/cloud/storage/tests/object_integration_test.cc
The ObjectMetadata parameter should be optional for this function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1519)
> Use WithObjectMetadata in ComposeObject().

- google/cloud/storage/client.h
- google/cloud/storage/client_object_copy_test.cc
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/idempotency_policy_test.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client_test.cc
- google/cloud/storage/internal/object_requests.cc
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/internal/object_requests_test.cc
- google/cloud/storage/tests/object_integration_test.cc
The ObjectMetadata parameter for RewriteObject should be really an
optional parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1518)
> Use WithObjectMedata in RewriteObject.

- google/cloud/bigtable/internal/table_test.cc
- google/cloud/bigtable/tests/mutations_integration_test.cc
- google/cloud/internal/retry_policy_test.cc
- google/cloud/storage/bucket_metadata.h
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/list_objects_reader.cc
The actual bugs were fixed, we neglected to cleanup the TODOs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1548)
> Remove obsolete TODOs.

- google/cloud/storage/internal/curl_client_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1552)
> Improve code coverage in CurlClient tests.

- google/cloud/bigtable/CMakeLists.txt
- google/cloud/bigtable/bigtable_client.bzl
- google/cloud/bigtable/bigtable_client_unit_tests.bzl
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/async_list_clusters.h
- google/cloud/bigtable/internal/async_list_clusters_test.cc
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
This fixes #1265.
It's basically an instantiation of AsyncRetryMultiPage with tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1555)
> Implement AsyncListClusters.

- google/cloud/storage/client.cc
- google/cloud/storage/client.h
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/logging_resumable_upload_session.cc
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/object_media_integration_test.cc
With this change UploadFile() uses resumable uploads for large files
(how large is a configuration parameter).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1550)
> Use resumable uploads for large files.

- google/cloud/README.md
- google/cloud/bigtable/README.md
We may need to update these notes again before cutting a release, but I thought some initial draft would be good.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1569)
> Update Bigtable release notes [skip ci].

- google/cloud/storage/README.md
We may need to update these notes again before cutting a release, but I thought some initial draft would be good.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1568)
> Update storage release notes. [skip ci]

- google/cloud/storage/client.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
Just to show how these are used. Thanks to @frankyn for nudging me to
create them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1577)
> Implement examples using non-default policies.

- google/cloud/bigtable/CMakeLists.txt
- google/cloud/bigtable/async_instance_data.h
- google/cloud/bigtable/async_instance_list_responses.h
- google/cloud/bigtable/bigtable_client.bzl
- google/cloud/bigtable/bigtable_client_unit_tests.bzl
- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/async_list_instances.h
- google/cloud/bigtable/internal/async_list_instances_test.cc
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
Fixes Issue #1262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1572)
> Async list instances

- google/cloud/bigtable/CMakeLists.txt
- google/cloud/bigtable/bigtable_client.bzl
- google/cloud/bigtable/bigtable_client_unit_tests.bzl
- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/async_list_app_profiles.h
- google/cloud/bigtable/internal/async_list_app_profiles_test.cc
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
Fixes Issue #1272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1609)
> Issue 1272 async list app profiles

- google/cloud/storage/oauth2/authorized_user_credentials.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1615)
> Fix typo in Auth2.0 link.

- bazel/google_cloud_cpp_deps.bzl
- cmake/external/grpc.cmake
Update to gRPC-1.17.0, no particular reason other than the passage of time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1620)
> Update to gRPC-1.17.0

- .clang-tidy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1626)
> Make .clang-tidy file more readable.

- google/cloud/log.h
I didn't get a chance to comment on PR #1628 before it got submitted, so rather than providing comments, here's a proposed patch to the comment wording.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1629)
> Fix comment wording for PR #1628. [skip ci]

- google/cloud/bigtable/CMakeLists.txt
- google/cloud/bigtable/async_cluster_list_responses.h
- google/cloud/bigtable/bigtable_client.bzl
- google/cloud/bigtable/internal/async_list_clusters.h
Fixes Issue# 1573
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1632)
> Move ClusterList from bigtable/internal to bigtable/

- README.md
Since we went through the trouble of setting the build up and getting the code to compile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1711)
> Display the build status for Kokoro+macOS. [skip ci]

- CONTRIBUTING.md
This section of the CONTRIBUTING document is intended for users unfamiliar with GitHub. I had forgotten about it, but today I remembered!  Updated it a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1709)
> Improve the onboarding instructions. [skip ci]

- CONTRIBUTING.md
I forgot to document the options here in the last couple of changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1712)
> Document new build script options [skip ci].

- google/cloud/bigtable/examples/BUILD
- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_emulator.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/tests/CMakeLists.txt
- google/cloud/bigtable/tests/bigtable_client_integration_tests.bzl
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
- google/cloud/bigtable/tests/run_integration_tests_emulator.sh
Issue Fixex#1524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1724)
> Instance admin async get instance

- google/cloud/bigtable/examples/README.md
- google/cloud/bigtable/examples/run_examples_emulator.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1728)
> Don't use hard-coded zones in examples

- google/cloud/storage/internal/bucket_acl_requests_test.cc
- google/cloud/storage/internal/default_object_acl_requests_test.cc
- google/cloud/storage/internal/object_acl_requests_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1743)
> Improve code coverage for *Acl parsers.

- ci/travis/build-docker.sh
- ci/travis/build-linux.sh
- ci/travis/dump-logs.sh
- ci/travis/linux-config.sh
- ci/travis/upload-codecov.sh
- ci/travis/upload-docs.sh
Too many scripts defined `IMAGE` and `BUILD_OUTPUT`, refactor to a
common place so it is easier to change in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1764)
> Refactor definition of variables.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Fixes #1523
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1767)
> Bigtable: Implementation of AsyncListInstances function

- ci/coverity-scan.sh
Coverity Scan is a static analysis tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1775)
> A script to compile with Coverity Scan.

- CONTRIBUTING.md
This is the build I use to catch most problems before sending the code
for review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1789)
> A better recommendation for a local build.

- google/cloud/bigtable/internal/async_read_row_operation.h
- google/cloud/bigtable/internal/table.h
- google/cloud/bigtable/tests/data_async_integration_test.cc
This fixes #1277
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1742)
> implementing AsyncReadRow to read single row asynchronously

- google/cloud/bigtable/internal/async_retry_unary_rpc.h
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/internal/table_admin.h
- google/cloud/bigtable/tests/admin_async_integration_test.cc
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
- google/cloud/bigtable/tests/snapshot_async_integration_test.cc
This fixes #1325.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1795)
> Removal of google::protobuf::Empty as a Response from Async APIs.

- google/cloud/status.h
- google/cloud/storage/bucket_access_control.cc
- google/cloud/storage/bucket_metadata.cc
- google/cloud/storage/internal/access_control_common.cc
- google/cloud/storage/internal/bucket_acl_requests.cc
- google/cloud/storage/internal/bucket_requests.cc
- google/cloud/storage/internal/common_metadata.h
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client_test.cc
- google/cloud/storage/internal/curl_download_request.cc
- google/cloud/storage/internal/curl_handle.cc
- google/cloud/storage/internal/curl_streambuf.cc
- google/cloud/storage/internal/curl_upload_request.cc
- google/cloud/storage/internal/default_object_acl_requests.cc
- google/cloud/storage/internal/notification_requests.cc
- google/cloud/storage/internal/object_acl_requests.cc
- google/cloud/storage/internal/object_requests.cc
- google/cloud/storage/lifecycle_rule.cc
- google/cloud/storage/list_objects_reader.cc
- google/cloud/storage/notification_metadata.cc
- google/cloud/storage/object_access_control.cc
- google/cloud/storage/object_metadata.cc
- google/cloud/storage/service_account.cc
This is for consistency with other StatusCode things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1814)
> Rename StatusCode enum values to kPascalCase style.

- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_common_unit_tests.bzl
- google/cloud/internal/throw_delegate_test.cc
- google/cloud/status.cc
- google/cloud/status.h
- google/cloud/status_or_test.cc
- google/cloud/status_test.cc
- google/cloud/storage/internal/logging_resumable_upload_session_test.cc
- google/cloud/storage/tests/object_media_integration_test.cc
This way we can create better error messages.
Also fixed a typo from a previous PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1820)
> Add functions to convert StatusCode to string.

- google/cloud/storage/object_rewriter.h
I made the change locally but forgot to push it before merging, sorry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1832)
> Missed this change from the review.

- google/cloud/internal/throw_delegate_test.cc
- google/cloud/status.h
- google/cloud/status_or_test.cc
- google/cloud/storage/client.cc
- google/cloud/storage/internal/curl_client_test.cc
- google/cloud/storage/internal/curl_resumable_streambuf.cc
- google/cloud/storage/internal/http_response_test.cc
- google/cloud/storage/internal/logging_resumable_upload_session_test.cc
- google/cloud/storage/internal/retry_client_test.cc
- google/cloud/storage/list_objects_reader_test.cc
- google/cloud/storage/retry_policy.h
- google/cloud/storage/testing/retry_tests.h
- google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc
Make it more similar to the internal version.
This fixes #1813.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1842)
> Simplify Status class.

- ci/test-install/storage_install_test.cc
- google/cloud/storage/benchmarks/storage_latency_benchmark.cc
- google/cloud/storage/benchmarks/storage_throughput_benchmark.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/object_test.cc
- google/cloud/storage/tests/curl_resumable_streambuf_integration_test.cc
- google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc
- google/cloud/storage/tests/object_insert_integration_test.cc
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/tests/object_media_integration_test.cc
- google/cloud/storage/tests/object_resumable_write_integration_test.cc
Changed tests and examples to check the return status.
This fixes #1664.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1841)
> Return StatusOr<void> from Client::DeleteObject.

- google/cloud/internal/throw_delegate_test.cc
- google/cloud/status.cc
- google/cloud/status.h
- google/cloud/storage/internal/curl_client_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1845)
> Change StatusCode to a enum class.

- google/cloud/storage/bucket_test.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/storage_bucket_iam_samples.cc
- google/cloud/storage/tests/bucket_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1846)
> Change Bucket IAM functions to return StatusOr.

- google/cloud/storage/bucket_metadata.cc
- google/cloud/storage/bucket_metadata.h
- google/cloud/storage/bucket_metadata_test.cc
- google/cloud/storage/internal/bucket_requests_test.cc
- google/cloud/storage/testbench/gcs_bucket.py
- google/cloud/storage/tests/bucket_integration_test.cc
This fixes #1847 .
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1850)
> Rename BucketOnlyPolicy to BucketPolicyOnly.

- google/cloud/storage/client.h
- google/cloud/storage/client_service_account_test.cc
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/tests/service_account_integration_test.cc
This fixes #1639.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1852)
> Use StatusOr in Client::GetServiceAccount.

- google/cloud/storage/client.h
- google/cloud/storage/client_object_copy_test.cc
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/tests/object_integration_test.cc
This fixes #1671.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1855)
> Return StatusOr from Client::CopyObject.

- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/list_buckets_reader.cc
- google/cloud/storage/list_buckets_reader.h
- google/cloud/storage/list_buckets_reader_test.cc
- google/cloud/storage/tests/bucket_integration_test.cc
This fixes #1682.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1854)
> Use StatusOr for ListBuckets.

- google/cloud/storage/bucket_test.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/tests/bucket_integration_test.cc
This fixes #1673.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1853)
> Use StatusOr for Client::LockBucketRetentionPolicy.

- google/cloud/storage/client.h
- google/cloud/storage/client_object_copy_test.cc
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/tests/object_integration_test.cc
This fixes #1661.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1857)
> Use StatusOr in Client::ComposeObject.

- google/cloud/storage/client.cc
- google/cloud/storage/client.h
- google/cloud/storage/client_sign_url_test.cc
- google/cloud/storage/examples/storage_object_samples.cc
This fixes #1638.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1858)
> Use StatusOr in Client::CreateV2SignedUrl.

- google/cloud/storage/client.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/tests/object_media_integration_test.cc
This fixes #1666.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1856)
> Use StatusOr in Client::UploadFile.

- google/cloud/storage/client.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/tests/object_media_integration_test.cc
This fixes #1665.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1860)
> Use StatusOr in Client::DownloadFile.

- google/cloud/storage/tests/run_integration_tests_production.sh
- google/cloud/storage/tests/run_integration_tests_testbench.sh
I completely forgot in the previous PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1863)
> Add new integration tests to driver scripts.

- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/instance_admin.cc
- google/cloud/bigtable/internal/instance_admin.h
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
this fixes #1274.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1843)
> implementation of noex::InstanceAdmin:AsyncGetIamPolicy

- google/cloud/storage/examples/storage_bucket_iam_samples.cc
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/examples/storage_notification_samples.cc
- google/cloud/storage/examples/storage_object_samples.cc
Hi,
PR will fix GCS sample region tags that are inconsistent with the Sample Tracker.
PLMK if more information is needed. Thank you!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1867)
> [Storage] Fix region tags

- bazel/google_cloud_cpp_deps.bzl
> Update googletest for Bazel

- google/cloud/storage/client.h
- google/cloud/storage/examples/storage_bucket_samples.cc
> Don't throw exception inside ListBuckets()

- google/cloud/storage/client.h
More of the changes for #1888.
> Additional documentation fixes.

- google/cloud/storage/examples/storage_bucket_acl_samples.cc
- google/cloud/storage/examples/storage_bucket_iam_samples.cc
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/examples/storage_default_object_acl_samples.cc
- google/cloud/storage/examples/storage_notification_samples.cc
- google/cloud/storage/examples/storage_object_acl_samples.cc
- google/cloud/storage/examples/storage_object_samples.cc
Let me know if I miss any.
This fixes #1889.
> Fix the formatting and naming in examples.

- google/cloud/storage/doc/storage-main.dox
- google/cloud/storage/examples/storage_quickstart.cc
This fixes the problems with the landing page, part of the work for #1888.  I have uploaded the generated documentation to:
https://coryan.github.io/google-cloud-cpp/latest/storage/index.html
> Improve storage landing page.

- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
This shows how to use WithObjectMetadata in InsertObject(). Also fixed
the documentation to list WithObjectMedata as one of the options.
This fixes #1923.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1925)
> Add an example for multipart uploads.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1931)
> Fix Travis CI link [skip ci].

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/examples/storage_object_acl_samples.cc
- google/cloud/storage/examples/storage_object_samples.cc
Some of the examples did not check their argc count properly.  Fixes #1929.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1936)
> Cleanup argc checking in storage/examples.

- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
Write an example showing how to use `Client::ReadObject` with a range
option.
This fixes #1819.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1940)
> Implement example to read a row range.

- google/cloud/bigtable/data_client.cc
- google/cloud/bigtable/data_client.h
- google/cloud/bigtable/internal/table.cc
- google/cloud/bigtable/internal/table.h
- google/cloud/bigtable/testing/inprocess_data_client.cc
- google/cloud/bigtable/testing/inprocess_data_client.h
- google/cloud/bigtable/testing/mock_data_client.h
- google/cloud/bigtable/tests/data_async_integration_test.cc
This fixes #1236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1935)
> Implementation of noex AsyncReadModifyWriteRow

- google/cloud/README.md
- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
Updating release notes in preparation for a release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1955)
> updated release notes [skip ci]

- doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1964)
> Updated Release instructions

- ci/kokoro/docker/asan-presubmit.cfg
- ci/kokoro/docker/asan.cfg
- ci/kokoro/docker/build.sh
- ci/kokoro/docker/centos-7-presubmit.cfg
- ci/kokoro/docker/centos-7.cfg
- ci/kokoro/docker/noex-presubmit.cfg
- ci/kokoro/docker/noex.cfg
- ci/kokoro/docker/ubsan-presubmit.cfg
- ci/kokoro/docker/ubsan.cfg
Change the configurations to set a single environment variable, and then
the script uses that to set the right combination of DISTRO,
DISTRO_VERSION, CMAKE_FLAGS, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1979)
> Simplify Kokoro configs.

- google/cloud/bigtable/internal/async_poll_op_test.cc
- google/cloud/bigtable/internal/async_retry_multi_page_test.cc
- google/cloud/bigtable/internal/async_retry_op_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1984)
> adds virtual d'tor to some test classes that have virtual functions

- INSTALL.md
- README.md
- ci/test-readme/Dockerfile.centos-install
- ci/test-readme/Dockerfile.fedora-install
- ci/test-readme/Dockerfile.ubuntu-install
- cmake/IncludeGrpc.cmake
- cmake/IncludeProtobuf.cmake
- google/cloud/storage/CMakeLists.txt
Document how to install on Ubuntu and CentOS (other distributions will
follow). I want folks to review the structure and then we can see add
the remaining platforms.
This is an initial draft, I expect a lot of discussion. Note that the instructions are long
and not that easy to follow. Any advice on how to make them simpler is appreciated.
The dockerfiles allow us to validate the instructions in a semi-automated way,
eventually we could run them as part of the CI builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1942)
> Initial `make install` instructions.

- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_common_unit_tests.bzl
- google/cloud/google_cloud_cpp_testing.bzl
- google/cloud/testing_util/assert_ok.cc
- google/cloud/testing_util/assert_ok.h
- google/cloud/testing_util/assert_ok_test.cc
This fixes #1980.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1988)
> Implement {ASSERT,EXPECT}_OK.

- google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
- google/cloud/bigtable/examples/bigtable_samples_instance_admin_ext.cc
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/instance_admin_test.cc
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
- google/cloud/bigtable/tests/instance_admin_integration_test.cc
This fixes #1967.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1992)
> Migrate instance admin API to StatusOr<>.

- README.md
- google/cloud/storage/README.md
Change the README files to label the GCS client library as Beta.
Remove some strange text in the top-level README too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2000)
> Declare GCS client library as Beta.

- INSTALL.md
- ci/test-readme/Dockerfile.ubuntu-xenial
- ci/test-readme/generate-install.sh
Add instructions to install on Ubuntu:16.04 (Xenial Xerus).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2007)
> Implement ubuntu:xenial install script.

- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/table.cc
- google/cloud/bigtable/table.h
- google/cloud/bigtable/table_check_and_mutate_row_test.cc
- google/cloud/bigtable/tests/data_integration_test.cc
Fixes #1966
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2008)
> Return StatusOr from Table::CheckAndMutateRow()

- .travis.yml
- ci/install-bazel.sh
- ci/kokoro/macos/build.sh
Use the same script from Kokoro and Travis, so it is easier to maintain.
Also verify the download by also downloading the SHA256 checksum, that
is not secure, but the objective is to prevent accidents, not malice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2018)
> Refactor Bazel installation.

- google/cloud/bigtable/testing/mock_response_reader.h
This will make imports of this code easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2034)
> added needed include for async_stream.h

- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/table.h
- google/cloud/bigtable/table_readmodifywriterow_test.cc
- google/cloud/bigtable/tests/data_integration_test.cc
Fixes #1968
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2037)
> Return StatusOr for Table::ReadModifyWriteRow()

- doc/setup-development-environment.md
Updated with newer version of Windows, and also recommend using Ninja as
the CMake backend. Ninja is much faster, and that is nice when doing
manual builds.
This came up during our in-person meetings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2043)
> Update instructions to setup windows workstation. [skip ci]

- doc/setup-development-environment.md
I figured we should also document how to setup a Linux VM for development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2050)
> Update instructions to setup Linux VM [skip ci].

- google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc
- google/cloud/bigtable/benchmarks/embedded_server_test.cc
- google/cloud/bigtable/benchmarks/endurance_benchmark.cc
- google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
- google/cloud/bigtable/examples/bigtable_hello_world.cc
- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/table.cc
- google/cloud/bigtable/table.h
- google/cloud/bigtable/table_apply_test.cc
- google/cloud/bigtable/tests/data_integration_test.cc
- google/cloud/bigtable/tests/mutations_integration_test.cc
Fixes #1969
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2044)
> Return StatusOr for Table::Apply()

- README.md
- ci/test-readme/generate-readme.sh
I thought it would be nice to advertise that we actually test these
install instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2067)
> Show badges for the install build too.

- ci/test-install/bigtable_install_test.cc
- google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc
- google/cloud/bigtable/benchmarks/endurance_benchmark.cc
- google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
- google/cloud/bigtable/examples/bigtable_hello_world.cc
- google/cloud/bigtable/examples/bigtable_quickstart.cc
- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/opencensus/bigtable_opencensus.cc
- google/cloud/bigtable/table.cc
- google/cloud/bigtable/table.h
- google/cloud/bigtable/table_readrow_test.cc
- google/cloud/bigtable/tests/data_integration_test.cc
Fixes #1970
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2066)
> Return StatusOr for Table::ReadRow()

- google/cloud/bigtable/internal/mutation_batcher.cc
- google/cloud/bigtable/internal/mutation_batcher.h
This is going to be needed in the following commits because there are
going to be several triggers for admission.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2072)
> Refactor admission into a separate function.

- google/cloud/internal/backoff_policy.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2069)
> Add the `scaling` parameter to the `ExponentialBackoffPolicy` examples.

- ci/test-readme/Dockerfile.centos
- ci/test-readme/Dockerfile.debian
- ci/test-readme/Dockerfile.fedora
- ci/test-readme/Dockerfile.opensuse
- ci/test-readme/Dockerfile.opensuse-leap
- ci/test-readme/Dockerfile.ubuntu
- ci/test-readme/Dockerfile.ubuntu-trusty
- ci/test-readme/Dockerfile.ubuntu-xenial
- ci/travis/Dockerfile.centos
- ci/travis/Dockerfile.fedora
- ci/travis/Dockerfile.ubuntu
- ci/travis/Dockerfile.ubuntu-install
- ci/travis/Dockerfile.ubuntu-trusty
Fixes #2059 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2070)
> Remove MAINTAINER directives in Dockerfiles.

- google/cloud/bigtable/table_admin.cc
- google/cloud/bigtable/table_admin.h
- google/cloud/bigtable/table_admin_test.cc
- google/cloud/bigtable/tests/snapshot_async_integration_test.cc
- google/cloud/bigtable/tests/snapshot_integration_test.cc
Fixes #2060
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2076)
> Use StatusOr in TableAdmin::SnapshotTable

- google/cloud/bigtable/mutations.h
- google/cloud/bigtable/mutations_test.cc
Fixes #2062
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2091)
> Add size() for BulkMutation

- google/cloud/bigtable/internal/mutation_batcher.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2102)
> Fix int overflow in MutationBatcher config.

- google/cloud/examples/gcs2cbt.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2117)
> Switch gcs2cbt to use MutationBatcher.

- google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
- google/cloud/bigtable/examples/bigtable_hello_world.cc
- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/opencensus/bigtable_opencensus.cc
- google/cloud/bigtable/internal/rowreaderiterator.cc
- google/cloud/bigtable/internal/rowreaderiterator.h
- google/cloud/bigtable/internal/table.cc
- google/cloud/bigtable/internal/table.h
- google/cloud/bigtable/internal/table_test.cc
- google/cloud/bigtable/row_reader.cc
- google/cloud/bigtable/row_reader.h
- google/cloud/bigtable/row_reader_test.cc
- google/cloud/bigtable/table.cc
- google/cloud/bigtable/table_readrows_test.cc
- google/cloud/bigtable/testing/table_integration_test.cc
- google/cloud/bigtable/tests/data_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2118)
> Use StatusOr<> in `ReadRows`

- google/cloud/storage/client.cc
- google/cloud/storage/client.h
- google/cloud/storage/internal/signed_url_requests.cc
- google/cloud/storage/internal/signed_url_requests.h
- google/cloud/storage/internal/signed_url_requests_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2124)
> Rename SignUrlRequest to V2SignUrlRequest.

- google/cloud/storage/hashing_options.cc
- google/cloud/storage/internal/hash_validator.cc
- google/cloud/storage/internal/openssl_util.cc
- google/cloud/storage/internal/openssl_util.h
- google/cloud/storage/oauth2/service_account_credentials.h
- google/cloud/storage/well_known_headers.cc
This "struct" only had static member functions. I just moved the private
member functions to the .cc file and things are copacetic.
There is more cleanup that we could do in this file, I am planning to send
those as separate PRs.
This fixes #774.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2141)
> Remove OpenSslUtils struct.

- google/cloud/bigtable/mutations.h
Fixes #2100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2139)
> Add estimated_size_in_bytes() accessor to BulkMutation

- google/cloud/storage/internal/openssl_util.cc
Removed a lot of `static_cast<>`, specially around `unique_ptr<>`.  Also removed a `const_cast<>` that was not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2147)
> Remove unnecessary casts.

- google/cloud/storage/internal/openssl_util.cc
We can use the same function to attach the Base64 filter to the encoding
and decoding chains, for reduced code and less magic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2151)
> Refactor function to create Base64 BIO chains.

- google/cloud/storage/testbench/gcs_bucket.py
- google/cloud/storage/testbench/gcs_object.py
- google/cloud/storage/testbench/gcs_project.py
- google/cloud/storage/testbench/testbench.py
I am about to add more complex functionality for the `projects/`
endpoint (to deal with HMAC keys), so we need a little refactoring to
keep these new functions in their own file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2152)
> Refactor GCS project components in the testbench.

- google/cloud/storage/internal/openssl_util.cc
There is no need to implement retry loops because writes to a
BIO_s_mem() buffer are guaranteed to not block. Well, we could run out
of memory, but in that case the retry loop does not help either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2153)
> Simplify Base64Encode() implementation.

- google/cloud/storage/client.cc
- google/cloud/storage/client.h
- google/cloud/storage/client_sign_url_test.cc
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
Add a new function to create V4 signed URLs, rename the old function to
explicitly say "V2". This PR also includes unit tests and examples.
This fixes #1598.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2130)
> Implement V4 signed URLs.

- google/cloud/storage/testbench/gcs_project.py
This PR implements the testbench changes to support `HmacKeys: insert`,
the changes to the library will come in separate PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2156)
> Implement `HmacKeys: insert` in testbench.

- ci/check-abi.sh
The intention in this script was to dump the HTML reports in a location
where dump-logs.sh could find them. That second script prints the report
in text format in the build log. They got out of sync a while back when
I moved the output directory for binaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2155)
> Update check-abi script.

- google/cloud/storage/client.h
- google/cloud/storage/examples/BUILD
- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/examples/storage_service_account_samples.cc
With the addition of HMAC key-related functions it makes sense to create
a separate example for all the service account-related stuff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2164)
> Refactor service account examples.

- google/cloud/bigtable/CMakeLists.txt
- google/cloud/bigtable/bigtable_client.bzl
- google/cloud/bigtable/examples/data_async_snippets.cc
- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/table_admin_async_snippets.cc
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/internal/async_future_from_callback.cc
- google/cloud/bigtable/internal/async_future_from_callback.h
- google/cloud/bigtable/internal/async_future_from_callback_test.cc
- google/cloud/bigtable/internal/grpc_error_delegate.cc
- google/cloud/bigtable/table.cc
- google/cloud/bigtable/table.h
- google/cloud/bigtable/table_admin.cc
- google/cloud/bigtable/table_admin.h
- google/cloud/bigtable/tests/admin_async_future_integration_test.cc
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2133)
> Migrate MakeAsyncFutureFromCallback to StatusOr.

- google/cloud/bigtable/internal/bulk_mutator.cc
- google/cloud/bigtable/internal/bulk_mutator_test.cc
- google/cloud/bigtable/internal/table.cc
- google/cloud/bigtable/internal/table_async_bulk_apply_test.cc
- google/cloud/bigtable/internal/table_test.cc
- google/cloud/bigtable/mutations.h
- google/cloud/bigtable/mutations_test.cc
- google/cloud/bigtable/table_bulk_apply_test.cc
Fixes #2093
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2169)
> Remove Mutation body from FailedMutation

- ci/travis/dump-reports.sh
Fixes the script in case we ever ran into files with spaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2179)
> Properly handle files with spaces.

- google/cloud/storage/CMakeLists.txt
- google/cloud/storage/client.h
- google/cloud/storage/internal/range_from_pagination.h
- google/cloud/storage/list_buckets_reader.cc
- google/cloud/storage/list_buckets_reader.h
- google/cloud/storage/list_buckets_reader_test.cc
- google/cloud/storage/list_objects_reader.cc
- google/cloud/storage/list_objects_reader.h
- google/cloud/storage/list_objects_reader_test.cc
- google/cloud/storage/storage_client.bzl
I am going to need a third version of these classes to list HMAC keys,
and that is too much cut&paste, even for me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2171)
> Refactor List{Object,Bucket}Reader classes.

- CONTRIBUTING.md
- README.md
- doc/adr/2018-06-18-storage-request-parameters-are-function-arguments.md
- doc/adr/2018-10-30-storage-metadata-fields-and-optional.md
- doc/managing-dependencies-in-cmake.md
- doc/setup-development-environment.md
- google/cloud/README.md
- google/cloud/bigtable/README.md
- google/cloud/bigtable/doc/bigtable-main.dox
- google/cloud/bigtable/doc/bigtable-samples-data-client.dox
- google/cloud/bigtable/doc/bigtable-samples-instance-admin.dox
- google/cloud/bigtable/examples/README.md
- google/cloud/bigtable/examples/opencensus/README.md
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/table_admin_test.cc
- google/cloud/bigtable/tests/run_integration_tests_emulator.sh
- google/cloud/bigtable/tools/generate_rpc_policy_parameters.py
- google/cloud/firestore/README.md
- google/cloud/firestore/firestore_client.pc
Eliminates end-of-line and end-of-file trailing whitespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2187)
> Remove trailing whitespace

- google/cloud/storage/testbench/testbench.py
TIL: Flask does not handle identifiers with slashes unless you use the
`path:` directive:
http://flask.pocoo.org/snippets/76/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2189)
> Handle object names with slashes.

- google/cloud/storage/client.cc
The previous messages used confusing naming for what file was a problem.
The new messages are more explicit, calling out what role does the file
in question is playing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2193)
> Improve error messages in {Upload,Download}File.

- google/cloud/storage/internal/bucket_requests_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2197)
> Fix trivial typo.

- google/cloud/storage/testbench/gcs_project.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2198)
> Add `HmacKeys: list` API to the testbench.

- doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2202)
> Mention pushing the release to Microsoft vcpkg

- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_service_account_samples.cc
- google/cloud/storage/tests/service_account_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2201)
> Examples and integration test for ListHmacKeys().

- google/cloud/storage/examples/run_examples_testbench.sh
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
Fixes #2178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2183)
> Create an example listing objects with a prefix.

- google/cloud/storage/internal/access_control_common.h
- google/cloud/storage/lifecycle_rule.h
- google/cloud/storage/object_metadata.h
Fixes #2200
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2204)
> Fix comparison functions

- google/cloud/bigtable/completion_queue.cc
- google/cloud/bigtable/completion_queue.h
- google/cloud/bigtable/completion_queue_test.cc
This PR adds CompletionQueue functions to create timers that just return
a `google::cloud::future<>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2206)
> Implement asynchronous timers with futures.

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/examples/storage_object_samples.cc
Fixes #2174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2194)
> Create storage examples for object versioning.

- google/cloud/storage/client.h
- google/cloud/storage/client_service_account_test.cc
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_service_account_samples.cc
- google/cloud/storage/idempotency_policy.cc
- google/cloud/storage/idempotency_policy.h
- google/cloud/storage/idempotency_policy_test.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/hmac_key_requests.cc
- google/cloud/storage/internal/hmac_key_requests.h
- google/cloud/storage/internal/hmac_key_requests_test.cc
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testbench/gcs_project.py
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/service_account_integration_test.cc
Another operation for HmacKeys. Usual battery of tests and examples.
This fixes #2160.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2215)
> Implement Client::GetHmacKey.

- google/cloud/storage/client.h
- google/cloud/storage/client_service_account_test.cc
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_service_account_samples.cc
- google/cloud/storage/hmac_key_metadata.h
- google/cloud/storage/hmac_key_metadata_test.cc
- google/cloud/storage/idempotency_policy.cc
- google/cloud/storage/idempotency_policy.h
- google/cloud/storage/idempotency_policy_test.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/curl_client.h
- google/cloud/storage/internal/hmac_key_requests.cc
- google/cloud/storage/internal/hmac_key_requests.h
- google/cloud/storage/internal/hmac_key_requests_test.cc
- google/cloud/storage/internal/logging_client.cc
- google/cloud/storage/internal/logging_client.h
- google/cloud/storage/internal/raw_client.h
- google/cloud/storage/internal/retry_client.cc
- google/cloud/storage/internal/retry_client.h
- google/cloud/storage/testbench/gcs_project.py
- google/cloud/storage/testing/mock_client.h
- google/cloud/storage/tests/service_account_integration_test.cc
Implement the `Client::UpdateHmacKey()` function, with the usual
battery of tests, examples and documentation.
Let me know if I should break this PR into smaller chunks.
Fixes #2161.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2218)
> Implement UpdateHmacKey().

- google/cloud/storage/examples/storage_bucket_samples.cc
Fixes #2182
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2228)
> Implement examples of lifecycle management.

- google/cloud/storage/testbench/gcs_object.py
The testbench was using the same variable to keep track of the latest
generation of an object, as well as the generator for new generation
numbers. That works kind of Okay until you start deleting revisions.
With this PR we use two different variables to track this.
No tests were harmed in the creation of this PR, but it enables future
tests that would not work otherwise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2229)
> Fix object revision tracking

- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
- google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
- google/cloud/bigtable/tests/instance_admin_integration_test.cc
- google/cloud/storage/tests/bucket_integration_test.cc
- google/cloud/storage/tests/curl_resumable_streambuf_integration_test.cc
- google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc
- google/cloud/storage/tests/object_checksum_integration_test.cc
- google/cloud/storage/tests/object_hash_integration_test.cc
- google/cloud/storage/tests/object_insert_integration_test.cc
- google/cloud/storage/tests/object_integration_test.cc
- google/cloud/storage/tests/object_media_integration_test.cc
- google/cloud/storage/tests/object_resumable_write_integration_test.cc
- google/cloud/storage/tests/object_rewrite_integration_test.cc
- google/cloud/storage/tests/service_account_integration_test.cc
- google/cloud/storage/tests/thread_integration_test.cc
This fixes most of the integration tests to follow the design
established in #2230.
Part of the work for #2181.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2235)
> Do not initialize statics in constructors.

- google/cloud/bigtable/table.cc
Part of the work for #2097 .
Third request in a series of pull requests to move functions from noex:;Table to Table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2247)
> Remove noex::Table::Apply() and BulkApply()

- google/cloud/bigtable/table_admin.cc
- google/cloud/bigtable/table_admin.h
Moving following functions in this PR
`GetSnapshot`, `DeleteSnapshot` and `ListSnapshots`
Please see #2098 for more insight.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2240)
> Moving non Async functions from `noex::TableAdmin` to `TableAdmin`.

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
Fixes #2176 
This is modelled after `gsutil rewrite -k`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2244)
> Create an example changing object encryption from CSEK to CMEK.

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
Fixes #2175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2243)
> Create an example to print the CMEK key in an object.

- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/examples/storage_object_samples.cc
I copied the wrong region tags into the previous set of bugs.
See #2256 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2257)
> Fix several region tags.

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
Ref: #2256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2263)
> Create examples for bucket static website configuration.

- google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
- google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
- google/cloud/bigtable/examples/table_admin_snippets.cc
This PR is part of work for #2253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2267)
> Adding region tag in BigTable C++ client samples for better documentation.

- google/cloud/storage/config.cmake.in
Fixes #2281
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2282)
> Add some missing dependencies to storage's config.cmake.in

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
Ref: #2256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2280)
> Create sample for adding CORS configuration to a bucket.

- .travis.yml
- ci/kokoro/docker/build.sh
- ci/travis/build-docker.sh
- ci/travis/build-linux.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2279)
> Pass CMake flags if we disable testing

- google/cloud/bigtable/examples/run_examples_emulator.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/tests/run_integration_tests_emulator.sh
- google/cloud/examples/run_gcs2cbt_emulator.sh
- google/cloud/storage/benchmarks/run_benchmarks_testbench.sh
- google/cloud/storage/examples/run_examples_testbench.sh
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/tests/run_integration_tests_testbench.sh
Fixes #1460
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2291)
> Replaced (date +%s) with {RANDOM}

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_acl_samples.cc
Ref: #2256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2295)
> Implement add bucket owner sample.

- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/table_admin_snippets.cc
Adding region tag in Bigtable C++ client samples for better documentation.
This PR is part of work for #2253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2307)
> Adding region tag in Bigtable C++ client samples

- google/cloud/bigtable/examples/data_async_snippets.cc
- google/cloud/bigtable/table.cc
- google/cloud/bigtable/table.h
- google/cloud/bigtable/tests/data_async_future_integration_test.cc
Part of the work for #2097 
Fourth request in a series of pull requests to move functions from noex:;Table to Table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2292)
> Do not depend on noex::Table::AsyncApply().

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_acl_samples.cc
Ref: #2256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2318)
> Implement remove/add object owner samples.

- google/cloud/bigtable/table_admin.cc
This change is for moving `noex::TableAdmin::AsyncCreateTable` to
`TableAdmin::AsyncCreateTable`.
This PR is part of  #2098.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2317)
> Moving `noex::TableAdmin` async functions to `TableAdmin`

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_samples.cc
Ref: #2256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2321)
> Implement storage create bucket with storage class/location sample.

- cmake/DownloadNlohmannJson.cmake
Some of the CI builds are failing because this file fails to download.
Use the standard technique: make multiple attempts to download, using an
exponential backoff.
Typically we rely on ExternalProject_Add() to implement the download
retry loop, but for this file we cannot because early versions of
ExternalProject_Add() cannot download single files.
This fixes #761.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2325)
> Make multiple attempts to download json.hpp.

- doc/adr/2019-03-26-binary-distributions.md
Fixes #333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2329)
> Added binary-distributions adr [skip ci]

- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
Fixes  #2296
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2326)
> Create code snippet for bigtable_get_family

- doc/adr/2019-03-26-binary-distributions.md
I did not notice this in my review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2332)
> Fix ADR status [skip ci].

- google/cloud/bigtable/internal/table_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2338)
> Fix missing `using` declaration.

- INSTALL.md
- ci/test-readme/generate-install.sh
- google/cloud/bigtable/doc/bigtable-main.dox
- google/cloud/storage/doc/storage-main.dox
This fixes #2086.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2335)
> Add instructions on how to use the installed libraries.

- README.md
Update the shields in the README file.  You can see them here:
https://github.com/coryan/google-cloud-cpp/blob/update-README-shields/README.md
We were missing a few and it was getting unwieldy, so I grouped them.  I am not sure I like the grouping or the ragged formatting, if you have suggestions please speak up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2343)
> Update README shields.

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
Ref: #2256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2342)
> Add change object storage class sample.

- google/cloud/storage/client_object_copy_test.cc
- google/cloud/storage/client_service_account_test.cc
- google/cloud/storage/internal/bucket_acl_requests.cc
- google/cloud/storage/internal/bucket_acl_requests.h
- google/cloud/storage/internal/bucket_acl_requests_test.cc
- google/cloud/storage/internal/bucket_requests.cc
- google/cloud/storage/internal/bucket_requests.h
- google/cloud/storage/internal/bucket_requests_test.cc
- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/default_object_acl_requests.cc
- google/cloud/storage/internal/default_object_acl_requests.h
- google/cloud/storage/internal/default_object_acl_requests_test.cc
- google/cloud/storage/internal/hmac_key_requests.cc
- google/cloud/storage/internal/hmac_key_requests.h
- google/cloud/storage/internal/hmac_key_requests_test.cc
- google/cloud/storage/internal/notification_requests.cc
- google/cloud/storage/internal/notification_requests.h
- google/cloud/storage/internal/notification_requests_test.cc
- google/cloud/storage/internal/object_acl_requests.cc
- google/cloud/storage/internal/object_acl_requests.h
- google/cloud/storage/internal/object_acl_requests_test.cc
- google/cloud/storage/internal/object_requests.cc
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/internal/object_requests_test.cc
Fixes #1865
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2345)
> Cleanup some FromHttpResponse fn's to take std::string

- google/cloud/storage/client.h
- google/cloud/storage/examples/storage_default_object_acl_samples.cc
- google/cloud/storage/examples/storage_object_acl_samples.cc
Fixes #2319
Fixes #2320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2346)
> Fix some region tags for storage samples.

- google/cloud/bigtable/admin_client.h
- google/cloud/bigtable/internal/async_longrunning_op.h
- google/cloud/bigtable/internal/async_longrunning_op_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2347)
> Implement longrunning ops via StartAsyncPollOp.

- google/cloud/storage/examples/storage_object_samples.cc
Adding region tags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2354)
> storage: add region tags for PUT signed URL sample

- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
Fixes #2302
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2353)
> Create code snippet for bigtable_delete_all_cells

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Fixes #1525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2362)
> Implement bigtable::InstanceAdmin::AsyncDeleteInstance

- google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/table_admin_snippets.cc
Region tags are modified as per #2254. 
Closes #2254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2367)
> Adding region tags to snippets

- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
Fixes #2303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2369)
> Create code snippet for bigtable_delete_particular_cells

- google/cloud/bigtable/examples/data_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/table.cc
- google/cloud/bigtable/table.h
- google/cloud/bigtable/tests/data_async_future_integration_test.cc
Fixes #1489 
Part of #2097
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2382)
> Implement bigtable::Table::AsyncCheckAndMutateRow

- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_async_snippets.cc
- google/cloud/bigtable/table_admin.cc
- google/cloud/bigtable/table_admin.h
- google/cloud/bigtable/tests/admin_async_future_integration_test.cc
Implementation of TableAdmin::AsyncModifyColumnFamilies.
This closes #1497.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2394)
> Implementation of TableAdmin::AsyncModifyColumnFamilies

- google/cloud/README.md
- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
Following instructions at https://github.com/googleapis/google-cloud-cpp/blob/master/doc/cutting-a-release.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2403)
> release notes

- google/cloud/bigtable/internal/async_retry_multi_page.h
- google/cloud/bigtable/internal/async_retry_multi_page_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2393)
> Implement future-base async multi-page requests.

- google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll.h
- google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll_test.cc
- google/cloud/internal/future_then_impl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2357)
> Async start a longrunning op and poll for result.

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_service_account_samples.cc
We want separate samples to enable and disable a HMAC Key for
consistency with the samples for other languages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2410)
> Create HMAC Key samples.

- google/cloud/optional.h
Fixes #2392.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2418)
> Make optional's relational operators free functions.

- google/cloud/storage/doc/setup-test-resources.md
I needed to document how to create a service account for HMAC keys, so I started this doc. The rest of it will follow in a future PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2425)
> Start document to create testing resources.

- google/cloud/bigtable/examples/bigtable_samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2433)
> Fix typos in region tags.

- google/cloud/bigtable/examples/bigtable_hello_world.cc
I checked this against the internal tracker, and fixed the region tags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2437)
> Fix region tags for bigtable_hello_world.

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_iam_samples.cc
This fixes #2413.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2439)
> Implement "Make Bucket public using IAM" sample.

- google/cloud/storage/internal/sign_blob_requests_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2429)
> Fix inconsistencies in SignBlob{Request,Response} tests.

- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
Fixes #2313
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2416)
> Create code snippet for bigtable_row_exists

- google/cloud/storage/examples/storage_service_account_samples.cc
Maybe in a few years I will live down the embarrassment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2445)
> Fix cut&paste mistakes in HMAC key examples.

- google/cloud/status.h
Fixes #2391.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2443)
> Moved Status operator== and operator!= from member to free functions

- google/cloud/storage/client.h
I read the comment wrong and thought it was unnecessary, my mistake,
restoring it in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2453)
> Restore accidentally removed comment.

- google/cloud/storage/client_sign_policy_document_test.cc
There were a couple of typos left-over from copy/paste.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2454)
> Fix test names.

- README.md
- ci/test-install/submodule/CMakeLists.txt
- ci/test-readme/Dockerfile.centos
- ci/test-readme/Dockerfile.debian
- ci/test-readme/Dockerfile.fedora
- ci/test-readme/Dockerfile.opensuse
- ci/test-readme/Dockerfile.opensuse-leap
- ci/test-readme/Dockerfile.ubuntu
- ci/test-readme/Dockerfile.ubuntu-trusty
- ci/test-readme/Dockerfile.ubuntu-xenial
- ci/travis/build-docker.sh
Fixes #2395 
This depends on #2455
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2462)
> Add test for using google-cloud-cpp as a submodule.

- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2470)
> Fix typos in these READMEs: support->supports

- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_async_snippets.cc
- google/cloud/bigtable/table_admin.cc
- google/cloud/bigtable/table_admin.h
- google/cloud/bigtable/tests/admin_async_future_integration_test.cc
This commit includes
1. Implement the function.
2. Implement an integration test for this function.
3. Implement an example for this function.
4. Execute the example as part of the CI build.
This closes #1498.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2464)
> Implementation of `TableAdmin::AsyncDropRowsByPrefix`

- README.md
- doc/managing-dependencies-in-cmake.md
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/storage/examples/run_examples_utils.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2479)
> Purge some newly-introduced trailing whitespace

- google/cloud/README.md
- google/cloud/bigtable/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2478)
> Add v0.8.1 release notes

- google/cloud/bigtable/mutation_batcher.cc
This fixes #2140.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2465)
> Fix a race condition in MutationBatcher.

- README.md
- google/cloud/storage/README.md
This fixes #2363.
Please read go/cloud-cxx:gcs-versioning if you have questions about the versioning scheme.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2430)
> Improve README for storage client.

- ci/check-style.sh
- ci/coverity-scan.sh
- ci/define-example-runner.sh
- ci/install-retry.sh
- ci/test-readme/dockerfile2markdown.sh
- ci/travis/build-docker.sh
- ci/travis/dump-reports.sh
- google/cloud/bigtable/ci/run_integration_tests.sh
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/tools/run_testbench_utils.sh
Part 3 of #2463
To make the changes easier to review and to spot any potential mistakes (since ShellCheck sometimes has false positives), I am releasing these changes incrementally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2474)
> Fix portability/logical errors in shell scripts.

- google/cloud/bigtable/CMakeLists.txt
- google/cloud/bigtable/async_list_instances_test.cc
- google/cloud/bigtable/bigtable_client_unit_tests.bzl
- google/cloud/bigtable/instance_admin.cc
The test is a slightly modified copy of its noex counterpart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2482)
> Reimplement AsyncListInstances via futures.

- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_async_snippets.cc
- google/cloud/bigtable/table_admin.cc
- google/cloud/bigtable/table_admin.h
- google/cloud/bigtable/tests/admin_async_future_integration_test.cc
This change includes
1. Implement the function.
2. Implement an integration test for this function.
3. Implement an example for this function.
4. Execute the example as part of the CI build.
This closes #1501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2484)
> Implementation of `TableAdmin::AsyncDropAllRows`

- google/cloud/bigtable/CMakeLists.txt
- google/cloud/bigtable/async_list_clusters_test.cc
- google/cloud/bigtable/bigtable_client_unit_tests.bzl
- google/cloud/bigtable/instance_admin.cc
The test is a modified version of its noex counterpart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2483)
> Reimplement AsyncListClusters with futures.

- google/cloud/bigtable/README.md
Get it to the same standard as the Google Cloud Storage README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2485)
> Update the README for Cloud Bigtable.

- google/cloud/bigtable/CMakeLists.txt
- google/cloud/bigtable/async_list_app_profiles_test.cc
- google/cloud/bigtable/bigtable_client_unit_tests.bzl
- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2491)
> Implement InstanceAdmin::AsyncListAppProfiles.

- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_snippets.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2492)
> Implement bigtable_get_family_metadata example.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2494)
> Implement InstanceAdmin::AsyncCreateInstance.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2511)
> Implement InstanceAdmin::AsyncUpdateCluster.

- ci/build-jenkins.sh
- ci/check-style.sh
- ci/coverity-scan.sh
- ci/define-example-runner.sh
- ci/kokoro/install/build.sh
- ci/kokoro/ubuntu/build.sh
- ci/travis/build-docker.sh
- ci/travis/install-linux.sh
- ci/travis/upload-codecov.sh
- ci/travis/upload-docs.sh
- google/cloud/bigtable/examples/run_examples_emulator.sh
- google/cloud/bigtable/examples/run_examples_production.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_snippets.cc
- google/cloud/bigtable/tests/run_integration_tests_emulator.sh
- google/cloud/bigtable/tools/run_emulator_utils.sh
- google/cloud/ci/run_integration_tests.sh
- google/cloud/storage/benchmarks/run_benchmarks_testbench.sh
- google/cloud/storage/examples/run_examples_utils.sh
Part 5 of #2463
To make the changes easier to review and to spot any potential mistakes (since ShellCheck sometimes has false positives), I am releasing these changes incrementally.
I intentionally ignore variables that are meant to be arguments or lists because when enclosing them in quotes, things break. They are false positives and we need an inline comment to suppress the warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2476)
> Put quotes around variables where necessary.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2495)
> Implement InstanceAdmin::AsyncCreateCluster.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2512)
> Implement InstanceAdmin::AsyncUpdateInstance.

- ci/check-abi.sh
I changed one of the scripts while @remyabel was fixing all these
warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2515)
> Fix new ShellCheck warnings.

- google/cloud/bigtable/examples/data_async_snippets.cc
- google/cloud/bigtable/table.cc
- google/cloud/bigtable/table.h
- google/cloud/bigtable/tests/data_async_future_integration_test.cc
The new implementations do not depend on the code in `noex::Table`.
Part of the work for #2097.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2518)
> Refactor Table::*ReadModifyWriteRow().

- google/cloud/storage/bucket_metadata.h
- google/cloud/storage/client.h
This was requested in b/130578311. I fixed a few other comments as I was
reading these files anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2517)
> Add links to best practices for bucket policy only.

- ci/define-example-runner.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_snippets.cc
This change implements the remaining column family examples for Cloud
Bigtable.
This fixes #2510, fixes #2507, and fixes #2288.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2514)
> Implement remaining column family examples.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2521)
> Fix chocolately link. [skip ci]

- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
This fixes #2505 and fixes #2506.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2523)
> Implement remaining bigtable_read_* samples.

- ci/travis/upload-codecov.sh
ETOOMANYQUOTES.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2526)
> Restore code coverage uploads.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2516)
> Implement InstanceAdmin::AsyncUpdateAppProfile.

- google/cloud/bigtable/admin_client.cc
- google/cloud/bigtable/admin_client.h
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_async_snippets.cc
- google/cloud/bigtable/table_admin.cc
- google/cloud/bigtable/table_admin.h
- google/cloud/bigtable/testing/inprocess_admin_client.cc
- google/cloud/bigtable/testing/inprocess_admin_client.h
- google/cloud/bigtable/testing/mock_admin_client.h
- google/cloud/bigtable/tests/admin_async_future_integration_test.cc
Following tasks are included in this PR
1. Implement the function.
2. Implement an integration test for this function.
3. Implement an example for this function.
4. Execute the example as part of the CI build.
This closes #1494.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2527)
> implementation of `TableAdmin::AsyncListTables`

- google/cloud/bigtable/completion_queue_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2528)
> Fix typos and comments in the CompletionQueue test.

- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_async_snippets.cc
- google/cloud/bigtable/table_admin.cc
- google/cloud/bigtable/table_admin.h
- google/cloud/bigtable/testing/table_integration_test.cc
- google/cloud/bigtable/tests/admin_async_future_integration_test.cc
- google/cloud/bigtable/tests/run_integration_tests_emulator.sh
This change includes following
1. Implement the function `TableAdmin::AsyncGenerateConsistencyToken` and `TableAdmin::AsyncCheckConsistency`.
2. Implement integration tests for these functions.
3. Implement examples for these functions.
4. Execute the examples as part of the CI build.
This closes #1499
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2530)
> Adding `AsyncGenerateConsistencyToken` and `AsyncCheckConsistency` to `TableAdmin`.

- CONTRIBUTING.md
- ci/travis/Dockerfile.ubuntu
- ci/travis/Dockerfile.ubuntu-install
- doc/setup-development-environment.md
- google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
- google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/table_admin_snippets.cc
- google/cloud/storage/examples/storage_bucket_acl_samples.cc
- google/cloud/storage/examples/storage_bucket_iam_samples.cc
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/examples/storage_default_object_acl_samples.cc
- google/cloud/storage/examples/storage_notification_samples.cc
- google/cloud/storage/examples/storage_object_acl_samples.cc
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/examples/storage_service_account_samples.cc
The only changes involve spacing around adorned array types (e.g.,
"char* []" -> "char*[]".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2535)
> Move to clang-format-7

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/instance_admin_test.cc
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This fixes #1538.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2546)
> Implement AsyncTestIamPermissions.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/instance_admin_test.cc
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This fixes #1528.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2550)
> Reimplement AsyncDeleteCluster.

- google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
The snippets included code to parse the command-line arguments and to
print usage messages. These are not interesting to any user. Use the
same inline lambda trick from other code samples to keep the extracted
sample code simpler to read.
This fixes #2556.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2566)
> Cleanup the InstanceAdmin snippets.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/instance_admin_test.cc
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This fixes #1536.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2555)
> Implement InstanceAdmin::AsyncGetIamPolicy.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This fixes #1531.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2551)
> Implement InstanceAdmin::AsyncCreateAppProfile.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This fixes #1531.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2552)
> Implement InstanceAdmin::AsyncGetAppProfile.

- ci/check-style.sh
Adding `IncludeBlocks: Merge` apparently triggers a bug in
clang-format, where it changes the timestamp of the file even if
there are no formatting changes. I think we want that directive, so I
changed the check-style.sh script to workaround the issue.
While testing this I discovered that cmake-format has the same problem,
so I worked around that bug too.
Finally, I made some cosmetic changes to make my IDE happy inside this
script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2568)
> Preserve timestamps for unchanged files.

- google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
- google/cloud/bigtable/examples/bigtable_samples.cc
- google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/table_admin_snippets.cc
We had a number of region tags that are not tracked by the DPE tools, removed them because they serve no purpose and make it hard to track down real problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2570)
> Remove invalid region tags.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This fixes #1535.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2553)
> Implement InstanceAdmin::AsyncDeleteAppProfile.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin.h
- google/cloud/bigtable/instance_admin_client.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/instance_admin_test.cc
- google/cloud/bigtable/testing/mock_instance_admin_client.h
- google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
This fixes #1537.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2571)
> Implement InstanceAdmin::AsyncSetIamPolicy.

- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_snippets.cc
This is another one of the DPE-required samples for Cloud Bigtable.
This fixes #2509.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2582)
> Implement bigtable_get_or_create_family example.

- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_snippets.cc
This is one of the required DPE examples, it shows how to iterate
over the column families of a table and print them.
Fixes #2508.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2580)
> Implement bigtable_list_column_families sample.

- google/cloud/spanner/BUILD
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/spanner_tool.cc
I think these changes make it easier to build larger experiments for Spanner. If you prefer another structure just let me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2569)
> Spanner experiments

- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_snippets.cc
This is another of the DPE-required examples.
This fixes #2498.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2581)
> Implement bigtable_get_or_create_table example.

- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_snippets.cc
This is another DPE-required example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2587)
> Implement bigtable_check_table_exists example.

- google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/instance_config.h
The description says "Create replicated cluster in current project" which
I think this sample satisfies. This is another DPE-required example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2588)
> Implement bigtable_create_replicated_cluster example.

- google/cloud/bigtable/examples/bigtable_hello_world.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2608)
> Adding delete table region tag for hello world

- ci/check-abi.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2607)
> Fix typo on check-abi.sh script.

- google/cloud/bigtable/tests/admin_integration_test.cc
The integration test for WaitForConsistencyCheck was not reporting
errors correctly. Also the names of the tests where just redundant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2612)
> Improve error messages in integration test.

- google/cloud/bigtable/internal/async_list_app_profiles.h
- google/cloud/storage/oauth2/authorized_user_credentials.h
- google/cloud/storage/oauth2/compute_engine_credentials.h
- google/cloud/storage/oauth2/service_account_credentials.h
All but one of them was harmless, but I would rather be able to search
and find none than think which ones are Okay.
This fixes #2598.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2613)
> Remove namespace aliases from header files.

- google/cloud/bigtable/doc/bigtable-hello-world.dox
- google/cloud/bigtable/doc/bigtable-main.dox
- google/cloud/bigtable/doc/bigtable-quickstart.dox
- google/cloud/storage/doc/storage-main.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2614)
> Fix broken links and link INSTALL.md directly.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
Part of the work for #2604
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2610)
> Use explicit return types in instance_admin_async_snippets.cc

- google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
Part of the work for #2604.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2616)
> Use explicit return types in bigtable_instance_admin_snippets.cc.

- google/cloud/bigtable/examples/data_snippets.cc
Part of the work for #2604.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2618)
> Use explicit return type in data_snippets.cc

- ci/check-style.sh
I think we talked about this but never filed a bug or anything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2620)
> Copy permissions only when needed.

- google/cloud/bigtable/examples/data_async_snippets.cc
Part of the changes for #2604.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2619)
> Explicit return types in data_async_snippets.cc

- google/cloud/bigtable/examples/table_admin_async_snippets.cc
Part of the work for #2604.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2621)
> Use explicit return types in table_admin_async_snippets.

- google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
- google/cloud/bigtable/examples/bigtable_hello_world.cc
- google/cloud/bigtable/examples/bigtable_quickstart.cc
Part of the work for #2604.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2623)
> Explicit return types in quickstart and hello world.

- google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
- google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
It just does not make sense for some code snippets to look different and be on a different file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2628)
> Consolidate InstanceAdmin snippets to one file.

- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
Use `using google::cloud::future;` like in the other examples, and name
the futures foo_future.
This fixes #2604.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2629)
> Make the instance_admin_async_snippet consistent.

- google/cloud/storage/doc/storage-main.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2630)
> Another pass fixing nits.

- google/cloud/README.md
- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2627)
> 0.9.0 release notes [skip ci]

- google/cloud/bigtable/doc/bigtable-hello-world.dox
- google/cloud/bigtable/examples/bigtable_hello_world.cc
Make sure any reference to functions or classes are actual links to the
documentation. Also cross-reference other functions or classes that the
user might be interested in, for example, if we show one type of
mutation, link the other types too.
The output can be reviewed at:
https://coryan.github.io/google-cloud-cpp/0.2637.0/bigtable/bigtable-hello-world.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2637)
> Fix doxygen page for Hello World example.

- google/cloud/storage/doc/storage-main.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2644)
> Fix nits in storage-main.dox.

- google/cloud/bigtable/table_admin.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2645)
> Doxygen comments for TableView constants.

- .github/issue_template.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2675)
> Fix status of storage library in issue template.

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2677)
> Fix documentation for GOOGLE_CLOUD_CPP_DEPENDENCY_PROVIDER.

- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/internal/hash_validator.cc
- google/cloud/storage/internal/hash_validator.h
- google/cloud/storage/internal/hash_validator_test.cc
I am going to need these functions outside curl_client.cc. This
refactors the functions to make them usable from other locations, and
adds some testing for good measure.
Part of the work for #2655.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2686)
> cleanup: Refactor CreateHashValidator factory functions.

- google/cloud/bigtable/instance_admin.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2694)
> Fix missing include reported internally by iwyu.

- google/cloud/storage/benchmarks/CMakeLists.txt
- google/cloud/storage/benchmarks/benchmark_utils.cc
- google/cloud/storage/benchmarks/benchmark_utils.h
- google/cloud/storage/benchmarks/run_benchmarks_testbench.sh
- google/cloud/storage/benchmarks/storage_benchmark_programs.bzl
- google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
Introduce a new benchmark to measure the throughput when uploading and
downloading objects, as well as the CPU cost (think "cpu cycles per
uploaded byte") to achieve that throughput. We will use this benchmark
to evaluate some performance improvements I have in mind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2695)
> A throughput vs. CPU benchmark.

- google/cloud/bigtable/data_client.h
- google/cloud/bigtable/instance_admin.cc
- google/cloud/bigtable/instance_admin_client.h
- google/cloud/bigtable/internal/unary_client_utils.h
- google/cloud/bigtable/table.cc
- google/cloud/bigtable/table_admin.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2702)
> chore(bigtable): Remove some "namespace noex" remnants

- google/cloud/bigtable/rpc_backoff_policy.h
- google/cloud/bigtable/rpc_retry_policy.h
TODO entries should refer to a GitHub issue, not a person. That was
probably my mistake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2707)
> Fix TODO references.

- google/cloud/storage/bucket_metadata.cc
- google/cloud/storage/bucket_metadata.h
- google/cloud/storage/bucket_metadata_test.cc
- google/cloud/storage/bucket_test.cc
- google/cloud/storage/internal/bucket_requests.cc
- google/cloud/storage/internal/bucket_requests_test.cc
This closes #2609
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2705)
> Add location_type field to BucketMetadata

- ci/travis/build-docker.sh
- google/cloud/storage/CMakeLists.txt
This closes #2441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2723)
> Adding install rule to install storage/testing/mock_client.h

- google/cloud/bigtable/async_row_reader.h
- google/cloud/bigtable/async_row_reader_test.cc
- google/cloud/bigtable/examples/data_async_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/table.cc
- google/cloud/bigtable/table.h
- google/cloud/bigtable/tests/data_async_future_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2726)
> Implement Table::AsyncReadRow.

- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
updated release notes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2728)
> updated release notes for v0.10.0

- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
merging cherry picked release notes commit from master to v0.10.x branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2734)
> updated release notes for v0.10.0 (#2728)

- ci/install-cloud-sdk.sh
It has been a few months, time to update it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2745)
> chore: Update Cloud SDK version.

- ci/kokoro/docker/build.sh
- ci/travis/Dockerfile.fedora-install
- ci/travis/build-docker.sh
- google/cloud/bigtable/internal/rowreaderiterator.cc
Too many false positives to enable automatically, but it does produce
interesting messages. I want to be able to run it manually without too
much effort.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2741)
> Support running scan-build manually.

- INSTALL.md
- README.md
- ci/test-readme/Dockerfile.centos
- ci/test-readme/Dockerfile.debian
- ci/test-readme/Dockerfile.fedora
- ci/test-readme/Dockerfile.opensuse
- ci/test-readme/Dockerfile.opensuse-leap
- ci/test-readme/Dockerfile.ubuntu
- ci/test-readme/Dockerfile.ubuntu-trusty
- ci/test-readme/Dockerfile.ubuntu-xenial
- ci/test-readme/dockerfile2markdown.sh
- ci/test-readme/generate-install.sh
Also I updated the README.md and INSTALL.md.
Fixes #2594
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2761)
> Retry network commands for less flake

- .gitignore
Visual Studio Code is convenient when debugging Windows issues, we need
to ignore the directories where it stores metadata though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2775)
> chrore: Add Visual Studio Code files.

- ci/kokoro/refdocs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2785)
> Use correct docs version

- cmake/external/grpc.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2795)
> bug: Fix typo in external project include guard.

- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/tests/run_integration_tests_production.sh
This fixes #2435. Production seems to be working consistently now.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2798)
> Restore HMAC Key integration tests.

- google/cloud/bigtable/tests/filters_integration_test.cc
I missed these problems in the last PR to reduce friction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2800)
> cleanup: Another small amount of import friction.

- google/cloud/README.md
- google/cloud/bigtable/README.md
- google/cloud/firestore/README.md
- google/cloud/storage/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2809)
> Update the docs link to googleapis.dev

- google/cloud/status_or.h
- google/cloud/status_or_test.cc
Fixes #2825
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2828)
> feat: Add equality support to StatusOr<T>

- google/cloud/storage/doc/storage-main.dox
- google/cloud/storage/doc/storage-mocking.dox
- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_client_mock_samples.cc
- google/cloud/storage/testing/mock_client.h
This is part of #2710
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2822)
> Storage client mock

- google/cloud/grpc_utils/CMakeLists.txt
- google/cloud/grpc_utils/config.cmake.in
Fixes #2836
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2839)
> Fix how grpc_utils loads gRPC

- README.md
- google/cloud/README.md
- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
I will probably update these a couple more times before cutting the release on Monday, but I figured folks could take a look at them sooner rather than later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2829)
> doc: Update release notes.

- google/cloud/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2846)
> doc: Fix release notes.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2847)
> cleanup: Remove Travis code coverage build.

- cmake/IncludeGMock.cmake
- google/cloud/testing_util/CMakeLists.txt
- google/cloud/testing_util/config.cmake.in
Fixes https://github.com/googleapis/google-cloud-cpp/issues/2842
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2848)
> bug: Include 'IncludeGMock.cmake' in testing_util/config.cmake.in

- google/cloud/storage/internal/curl_client.cc
- google/cloud/storage/tests/object_hash_integration_test.cc
This will fix #2832.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2876)
> Use correct field name for MD5 hash.

- google/cloud/CMakeLists.txt
- google/cloud/bigtable/CMakeLists.txt
- google/cloud/storage/CMakeLists.txt
This fixes #2873
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2879)
> doc: Explain why some subdirectories are disabled.

- ci/kokoro/docker/upload-docs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2887)
> cleanup: Fix shellcheck warning in upload-docs.sh

- ci/kokoro/install/Dockerfile.opensuse
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2896)
> chore: removed attempt to install pkgconfig in opensuse

- ci/kokoro/docker/check-abi-presubmit.cfg
- ci/kokoro/docker/check-abi.cfg
- ci/kokoro/docker/check-abi.sh
- ci/kokoro/docker/dump-reports.sh
We're only interested in source compatibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2901)
> Disable ABI compatibility checks.

- README.md
- doc/setup-development-environment.md
closes issue #2908
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2909)
> docs: add a necessary flag for windows in README

- google/cloud/storage/examples/storage_bucket_samples.cc
cc: @JesseLovelace
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2920)
> Add tracking region tag to GetBucketMetadata

- google/cloud/storage/CMakeLists.txt
- google/cloud/storage/benchmarks/benchmark_parser_test.cc
- google/cloud/storage/benchmarks/benchmark_utils.cc
- google/cloud/storage/benchmarks/benchmark_utils.h
- google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc
- google/cloud/storage/benchmarks/storage_latency_benchmark.cc
- google/cloud/storage/benchmarks/storage_throughput_benchmark.cc
- google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
Fixes #2878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2916)
> feat: Change storage/benchmarks to compile with exceptions disabled.

- ci/kokoro/windows/build-dependencies.ps1
- ci/kokoro/windows/continuous-win-2019.cfg
- ci/kokoro/windows/presubmit-win-2019.cfg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2921)
> testing: Add kokoro build on windows 2019

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2922)
> Updating Macos build instructions for Mojave

- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2910)
> Bigtable write samples

- ci/kokoro/docker/build.sh
- ci/kokoro/readme/Dockerfile.centos
- ci/kokoro/readme/Dockerfile.debian
- ci/kokoro/readme/Dockerfile.fedora
- ci/kokoro/readme/Dockerfile.opensuse
- ci/kokoro/readme/Dockerfile.opensuse-leap
- ci/kokoro/readme/Dockerfile.ubuntu
- ci/kokoro/readme/Dockerfile.ubuntu-trusty
- ci/kokoro/readme/Dockerfile.ubuntu-xenial
- super/CMakeLists.txt
Fixes #2905
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2925)
> cleanup: Move ci/super to super

- ci/kokoro/docker/Dockerfile.ubuntu
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
Fixes #2891
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2931)
> feat: Add Ninja build.

- google/cloud/README.md
- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2933)
> doc: update release notes

- bazel/curl.BUILD
will unblock #666
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2938)
> fix: Fix windows include path in curl.BUILD

- google/cloud/storage/benchmarks/CMakeLists.txt
- google/cloud/storage/benchmarks/benchmark_utils.cc
- google/cloud/storage/benchmarks/benchmark_utils.h
- google/cloud/storage/benchmarks/benchmark_utils_test.cc
- google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
- google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2944)
> Make GCS throughput benchmark record progress.

- google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
This is in order to be able to compare apples to apples. Results are
very unstable and the way to circumvent it is to reuse the same client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2943)
> Random CRC and MD5 in storage throughput benchmark

- ci/kokoro/install/build.sh
- ci/kokoro/readme/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2975)
> chore: Use the Docker cache for interactive builds.

- INSTALL.md
- ci/kokoro/docker/Dockerfile.fedora-install
- ci/kokoro/docker/Dockerfile.ubuntu-install
- ci/kokoro/install/Dockerfile.centos
- ci/kokoro/install/Dockerfile.debian
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.ubuntu
- ci/kokoro/install/Dockerfile.ubuntu-trusty
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- super/external/googleapis.cmake
Need to update the googleapis version to pick some fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2976)
> chore: Update cpp-cmakefiles.

- INSTALL.md
- WORKSPACE
- bazel/curl.BUILD
- bazel/google_cloud_cpp_deps.bzl
- ci/test-install/WORKSPACE
- ci/test-readme/generate-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2985)
> Upgrade grpc to 1.23.0.

- ci/kokoro/docker/build.sh
- ci/kokoro/docker/common.cfg
fixes #2984
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2986)
> chore: reduce docker timeout from 120 minutes to 60 minutes

- google/cloud/storage/tests/slow_reader_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2992)
> cleanup: use existing function to generate data.

- google/cloud/storage/tests/error_injection_integration_test.cc
- google/cloud/storage/tests/run_integration_tests_testbench.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2995)
> Actually enable the error injection test.

- google/cloud/storage/tests/error_injection_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2996)
> cleanup: Add missing TODO comment.

- .bazelrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3008)
> chore: Sanitizer builds work better with debug info.

- .bazelrc
- ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
- ci/kokoro/docker/build.sh
- google/cloud/future_generic_test.cc
- google/cloud/future_void_test.cc
- google/cloud/internal/future_impl.h
- google/cloud/storage/internal/curl_wrappers_disable_sigpipe_handler_test.cc
This change configures (but does not enable) the tsan (ThreadSanitizer)
and msan (MemorySanitizer) builds. The are a couple of changes in the
code:
- tsan found a real race condition in `google::cloud::promise<T>`, also
created a couple of unit tests to repro the bug with minimal overhead.
- msan yields a false positive for one of the tests related to signal
handlers. I chose to simply disable the test in this case.
A separate change inside Google will enable these builds.
Fixes #62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3011)
> chore: Configure tsan and msan builds.

- google/cloud/storage/tests/curl_download_request_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3031)
> fix: eliminate a SIGSEGV from test

- CMakeLists.txt
- google/cloud/CMakeLists.txt
- google/cloud/bigtable/CMakeLists.txt
Fixes #3024
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3025)
> feat: Add ability to disable building libraries

- ci/kokoro/Dockerfile.refdocs
- ci/kokoro/refdocs_wrapper.sh
fixes #2906
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3039)
> feat: Always build the base image for the refdocs job

- doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3041)
> fix: Correct a misplaced closing brace in release doc

- google/cloud/storage/tests/curl_request_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3048)
> test: Add a test for telemetry header

- google/cloud/storage/internal/retry_object_read_source.cc
- google/cloud/storage/internal/retry_object_read_source.h
Fixes #3049
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3050)
> feat: reset retry policy for each retry loop

- google/cloud/storage/client.h
- google/cloud/storage/download_options.h
- google/cloud/storage/internal/object_requests.cc
- google/cloud/storage/internal/object_requests.h
- google/cloud/storage/internal/object_requests_test.cc
- google/cloud/storage/internal/retry_object_read_source.cc
- google/cloud/storage/internal/retry_object_read_source.h
- google/cloud/storage/internal/retry_object_read_source_test.cc
- google/cloud/storage/testbench/testbench.py
- google/cloud/storage/tests/object_media_integration_test.cc
This PR tries to fix #3006.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3058)
> feat: added ReadLast option for reading object from end

- INSTALL.md
- README.md
- doc/setup-cmake-environment.md
- doc/setup-development-environment.md
This fixes #3070
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3071)
> docs:Adapt documentation for super build.

- google/cloud/storage/internal/curl_download_request.cc
- google/cloud/storage/internal/retry_object_read_source.cc
- google/cloud/storage/testbench/testbench.py
- google/cloud/storage/tests/object_media_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3072)
> bug: restart downloads with retryable HTTP errors.

- google/cloud/testing_util/capture_log_lines_backend.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3078)
> chore: fix copyright boilerplate

- ci/kokoro/install/Dockerfile.debian-buster
- google/cloud/storage/tests/CMakeLists.txt
- google/cloud/storage/tests/object_file_multi_threaded_test.cc
- google/cloud/storage/tests/run_integration_tests_production.sh
- google/cloud/storage/tests/run_integration_tests_testbench.sh
- google/cloud/storage/tests/storage_client_integration_tests.bzl
I wrote this test to reproduce #3074. I believe this is a libcurl bug, but the test and the Dockerfile to build with Debian 10 are useful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3079)
> feat: a new test for multithreaded downloads

- super/ExternalProjectHelper.cmake
- super/external/c-ares.cmake
- super/external/crc32c.cmake
- super/external/curl.cmake
- super/external/googleapis.cmake
- super/external/googletest.cmake
- super/external/grpc.cmake
- super/external/protobuf.cmake
- super/external/zlib.cmake
Now that the external projects are only used in super builds we can
simplify them some more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3081)
> cleanup: simplify external projects some more

- google/cloud/storage/client.h
This fixes #2966
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3161)
> docs:Link HMAC service account key documentation.

- google/cloud/storage/tests/object_integration_test.cc
It only runs on Linux because there is no portable way to list open
files.
This fixes #2953.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3169)
> test: add an integration test for FD leaks.

- google/cloud/README.md
- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3177)
> update release notes [skip ci]

- ci/kokoro/docker/build-in-docker-cmake.sh
Fixes #2163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3187)
> bug: fix flaky builds due to ccache initialization

- doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3192)
> doc: add links to generated documentation

- ci/kokoro/docker/publish-refdocs.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3195)
> docs: add a kokoro build config for doxygen docs

- doc/setup-cmake-environment.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3209)
> Fix typo in file path

- doc/setup-cmake-environment.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3216)
> doc: fix cut&paste error in CMake instructions

- INSTALL.md
Evidently we (meaning I) made multiple changes to the installation
requirements and neglected to update the INSTALL.md file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3218)
> chore: update the INSTALL.md file

- INSTALL.md
- bazel/google_cloud_cpp_deps.bzl
- ci/kokoro/docker/Dockerfile.fedora-install
- ci/kokoro/docker/Dockerfile.ubuntu-install
- ci/kokoro/install/Dockerfile.centos
- ci/kokoro/install/Dockerfile.debian
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.ubuntu
- ci/kokoro/install/Dockerfile.ubuntu-trusty
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/CONTROL
- ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/portfile.cmake
- super/external/google-cloud-cpp-common.cmake
This is required for #3016.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3219)
> Bump google-cloud-cpp-common to 0.15.

- INSTALL.md
- bazel/google_cloud_cpp_deps.bzl
- ci/kokoro/docker/Dockerfile.fedora-install
- ci/kokoro/docker/Dockerfile.ubuntu-install
- ci/kokoro/install/Dockerfile.centos
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.debian
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-trusty
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/portfile.cmake
- super/external/google-cloud-cpp-common.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3231)
> chore: bump google-cloud-cpp-common to v0.16.0

- README.md
- ci/kokoro/readme/Dockerfile.centos-7
- ci/kokoro/readme/Dockerfile.centos-8
- ci/kokoro/readme/Dockerfile.debian-buster
- ci/kokoro/readme/Dockerfile.debian-stretch
- ci/kokoro/readme/Dockerfile.fedora
- ci/kokoro/readme/Dockerfile.opensuse-leap
- ci/kokoro/readme/Dockerfile.opensuse-tumbleweed
- ci/kokoro/readme/Dockerfile.ubuntu-bionic
- ci/kokoro/readme/Dockerfile.ubuntu-trusty
- ci/kokoro/readme/build.sh
- ci/kokoro/readme/common.cfg
- ci/test-readme/generate-readme.sh
All the files in `ci/kokoro/readme/` are automatically generated.
Part of the work for #3228
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3241)
> ci: automatically generate ci/kokoro/readme

- google/cloud/storage/client.cc
- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/internal/tuple_filter.h
- google/cloud/storage/object_test.cc
- google/cloud/storage/tests/object_integration_test.cc
This fixes #3016.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3239)
> feat: implement `ComposeMany`

- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3251)
> chore: update README files

- ci/kokoro/install/Dockerfile.debian-buster
Part of the work for #3258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3259)
> ci: fix install build for Debian-10 (Buster)

- ci/benchmarks/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3272)
> ci: fix Dockerfile for benchmark images

- google/cloud/storage/examples/storage_service_account_samples.cc
We had an existing sample, so I just reused it. Note that this uses the implicit
project, there is a separate sample using an explicit project id.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3278)
> doc: add storage_get_service_account tag

- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3281)
> chore: add release notes

- google/cloud/storage/internal/object_streambuf.cc
- google/cloud/storage/internal/object_streambuf_test.cc
Fix #3280 by putting the upload stream in a bad state when there is an unexpected jump in the next expected byte from GCS.  Also prevents corruption of uploads if not all of the bytes written in Flush get committed to GCS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3283)
> fix: add logic to ObjectWriteStreambuf for handling jumps in upload ranges to fix #3280

- google/cloud/bigtable/filters.h
- google/cloud/bigtable/filters_test.cc
- google/cloud/bigtable/tests/filters_integration_test.cc
Fixes #3292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3294)
> feat: implement bigtable::Filter::InterleaveFromRange

- google/cloud/storage/internal/bucket_requests.h
- google/cloud/storage/testbench/gcs_bucket.py
- google/cloud/storage/tests/bucket_integration_test.cc
- google/cloud/storage/tests/run_integration_tests_production.sh
- google/cloud/storage/tests/run_integration_tests_testbench.sh
- google/cloud/storage/well_known_parameters.h
This fixes #3203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3298)
> feat: support optionsRequestedPolicyVersion query parameter in GetBucketIamPolicy

- cmake/FindProtobufWithTargets.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3299)
> Fix an error in FindProtobufWithTargets.cmake

- doc/setup-development-environment.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3295)
> chore: update windows development instructions

- google/cloud/bigtable/README.md
- google/cloud/storage/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3306)
> chore: update readmes for release

- .bazelrc
- bazel/google_cloud_cpp_deps.bzl
- super/external/grpc.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3305)
> chore: upgrade grpc to v1.26.0

- .bazelrc
- bazel/googleapis.BUILD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3311)
> chore: remove -fno-sanitize=vptr; add grpc++ to proto deps

- doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3312)
> chore: update release instructions

- google/cloud/storage/doc/parallel-uploads-design.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3321)
> docs: document parallel uploads design

- google/cloud/storage/benchmarks/storage_parallel_uploads_benchmark.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3339)
> test: allow specifying dir in parallel upload BM

- doc/cpp-style-guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3360)
> doc: fix enum style; we follow GSG

- INSTALL.md
- README.md
- WORKSPACE
- bazel/google_cloud_cpp_deps.bzl
- ci/benchmarks/Dockerfile
- ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
- ci/kokoro/docker/Dockerfile.ubuntu-install
- ci/kokoro/docker/build.sh
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/kokoro/windows/bazel/build.bat
- ci/kokoro/windows/install-dependencies.ps1
- ci/test-install/WORKSPACE
- super/external/protobuf.cmake
This is needed to compile with the latest and greatest googleapis protos
on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3364)
> ci: upgrade to protobuf v3.11.3

- google/cloud/storage/parallel_upload.cc
- google/cloud/storage/parallel_upload.h
- google/cloud/storage/parallel_uploads_test.cc
This will be needed for resumable parallel uploads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3382)
> feat: implement ParallelUploadPersistentState

- google/cloud/bigtable/CHANGELOG.md
- google/cloud/storage/CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3385)
> chore: update release notes

- google/cloud/storage/parallel_upload.h
Before this change, `ParallelUploadFileShard` used to hold a
`NonResumableParallelUploadState`. This PR makes it hold
`ParallelUploadStateImpl`, which will be shared between both resumable
and non-resumable versions allowing to avoid code duplication.
In order to make review easier, the change is split into two commits - one simply moving existing code and the other slightly modifying it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3383)
> refactor: generalize ParallelUploadFileShard

- google/cloud/storage/benchmarks/CMakeLists.txt
- google/cloud/storage/benchmarks/benchmark_utils.cc
- google/cloud/storage/benchmarks/benchmark_utils.h
- google/cloud/storage/benchmarks/bounded_queue.h
- google/cloud/storage/benchmarks/storage_benchmarks.bzl
- google/cloud/storage/benchmarks/storage_shard_throughput_benchmark.cc
- google/cloud/storage/benchmarks/storage_throughput_benchmark.cc
- google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
Fixes #3400 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3406)
> refactor: helper to delete all objects in a bucket

- ci/kokoro/docker/build.sh
SC2145: Argument mixes string and array. Use * or separate argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3408)
> fix: quash a shellcheck warning

- doc/setup-development-environment.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3410)
> doc: recommend MSVC 2019 for Windows development

- google/cloud/storage/client.cc
- google/cloud/storage/internal/signed_url_requests.cc
- google/cloud/storage/internal/signed_url_requests.h
- google/cloud/storage/internal/signed_url_requests_test.cc
- google/cloud/storage/tests/UrlSignerV4TestData.json
- google/cloud/storage/tests/signed_url_conformance_test.cc
This PR is towards #3329.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3411)
> feat: v4 signed urls formatting fixes

- ci/install-cloud-sdk.sh
- ci/kokoro/ubuntu/build.sh
- doc/setup-development-environment.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3416)
> chore: update Cloud SDK version

- google/cloud/storage/tests/signed_url_conformance_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3418)
> refactor: make V4 signed URLs tests fine grained

- google/cloud/bigtable/client_options_test.cc
- google/cloud/storage/internal/compute_engine_util_test.cc
- google/cloud/storage/internal/curl_client_test.cc
- google/cloud/storage/oauth2/google_application_default_credentials_file_test.cc
- google/cloud/storage/oauth2/google_credentials_test.cc
- google/cloud/storage/storage_client_options_test.cc
- google/cloud/storage/tests/object_media_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3424)
> chore: migrate to `testing_util::ScopedEnvironment`

- ci/test-install/bigtable/bigtable_install_test.cc
Fixes #3361.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3425)
> fix: delete the table created in bigtable_install_test

- ci/kokoro/docker/Dockerfile.fedora
- ci/kokoro/docker/Dockerfile.fedora-install
- ci/kokoro/docker/Dockerfile.ubuntu
- ci/kokoro/docker/Dockerfile.ubuntu-install
Fixes #3421 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3430)
> fix: workaround pip installation problems

- google/cloud/storage/client_sign_policy_document_test.cc
- google/cloud/storage/client_sign_url_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3434)
> cleanup: remove remnant (unused) environment_variable_restore.h includes

- google/cloud/storage/testbench/testbench.py
Fixes: #3438
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3439)
> fix(3438): add /download/storage/v1 handler

- google/cloud/storage/parallel_upload.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3448)
> doc: add doxygen comments for ParallelUploadFile

- google/cloud/storage/internal/signed_url_requests.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3451)
> fix: use east const

- ci/benchmarks/Dockerfile
- ci/kokoro/docker/Dockerfile.fedora-install
- ci/kokoro/docker/Dockerfile.ubuntu-install
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3454)
> ci: use cpp-cmakefiles-v0.5.0 in CI builds

- google/cloud/storage/client.cc
- google/cloud/storage/internal/signed_url_requests.cc
- google/cloud/storage/internal/signed_url_requests.h
- google/cloud/storage/internal/signed_url_requests_test.cc
- google/cloud/storage/signed_url_options.h
- google/cloud/storage/tests/signed_url_conformance_test.cc
This fixes #3327.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3460)
> feat: implement virtual hostname V4 signatures

- INSTALL.md
- bazel/google_cloud_cpp_deps.bzl
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- super/external/googleapis.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3462)
> chore: update cpp-cmakefile version

- ci/kokoro/docker/build-in-docker-bazel.sh
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
This is a change equivalent to:
googleapis/google-cloud-cpp-spanner#1360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3466)
> testing: add `RUNS_PER_TEST` environment variable

- google/cloud/storage/internal/signed_url_requests.cc
- google/cloud/storage/internal/signed_url_requests.h
- google/cloud/storage/internal/signed_url_requests_test.cc
- google/cloud/storage/signed_url_options.h
- google/cloud/storage/tests/signed_url_conformance_test.cc
This fixes #6874.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3463)
> feat: allow domain named buckets in signed URLs v4

- ci/kokoro/docker/build-in-docker-bazel.sh
- ci/kokoro/docker/build.sh
- ci/kokoro/docker/integration-nightly.cfg
- ci/kokoro/docker/integration-presubmit.cfg
- ci/kokoro/docker/integration.cfg
This build with eventually replace the builds in ci/kokoro/ubuntu, and
will bring this repository inline with the other repositories.
Part of the work for #3473
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3477)
> ci: add integration build to ci/kokoro/docker

- ci/kokoro/docker/build-in-docker-bazel.sh
Part of the work for #3473
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3478)
> ci: reduce noise in the integration tests

- ci/kokoro/docker/build.sh
- google/cloud/storage/internal/curl_download_request.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3485)
> bug: check curl connection before unpausing

- google/cloud/bigtable/examples/bigtable_grpc_credentials.cc
- google/cloud/bigtable/examples/run_examples_utils.sh
Part of the work for #3489
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3495)
> cleanup: refactor samples to C++ driver

- ci/kokoro/docker/download-cache.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3503)
> cleanup: fix shellcheck warning about egrep

- ci/kokoro/docker/build-in-docker-cmake.sh
The first message was happening *after* the check-style step, which
gave the impression that the build was frozen for several seconds.
I fixed that and took the opportunity to fix all the other messages
to have the same format (start with a date, progress messages in
yellow, errors in red, success in green).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3510)
> ci: improve messages for CMake builds

- ci/kokoro/docker/build-in-docker-cmake.sh
We still need to workaround #441
Part of the work for #3489 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3507)
> ci: retry bigtable integration tests

- ci/kokoro/docker/build-in-docker-cmake.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3514)
> ci: stop on first successful integration test

- ci/kokoro/windows/build-bazel.ps1
Makes the build faster, from about 30m to below 15m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3515)
> ci: use Bazel cache for Windows builds

- ci/kokoro/macos/build-bazel.sh
- ci/kokoro/macos/build.sh
- ci/kokoro/macos/download-cache.sh
- ci/kokoro/macos/upload-cache.sh
This fixes #3519
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3605)
> ci: enable caching for macOS+Bazel build

- ci/kokoro/docker/build.sh
Part of the work for googleapis/google-cloud-cpp-common#239
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3608)
> ci: use UTC timestamps for Docker builds

- ci/kokoro/docker/Dockerfile.centos
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
- google/cloud/storage/parallel_upload.h
Part of the work for #3577 #3578 #3579 and #3580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3609)
> ci: configure builds GCC and Clang versions

- google/cloud/bigtable/examples/bigtable_examples_common.cc
- google/cloud/bigtable/examples/bigtable_examples_common.h
- google/cloud/bigtable/examples/bigtable_examples_common_test.cc
This is a followup to the post-merge comments in #3617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3629)
> cleanup: simplify tests for bigtable::examples::Example

- INSTALL.md
- bazel/google_cloud_cpp_deps.bzl
- ci/kokoro/docker/Dockerfile.fedora-install
- ci/kokoro/docker/Dockerfile.ubuntu-install
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/CONTROL
- ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/portfile.cmake
- super/external/google-cloud-cpp-common.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3633)
> chore: upgrade g-c-cpp-common to v0.25.0

- ci/kokoro/docker/Dockerfile.ubuntu-install
Used my fork to debug the build and forgot to revert the change
when sending the original PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3634)
> ci: fix reference to coryan's fork

- google/cloud/storage/tests/signed_url_conformance_test.cc
- google/cloud/storage/tests/v4_signatures.json
Updated to 24a5e2373d1240ff3538f9999888053ba8b6a539.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3631)
> chore: update signed URL conformance tests

- google/cloud/bigtable/CHANGELOG.md
- google/cloud/storage/CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3636)
> chore: update CHANGELOGS for release

- google/cloud/storage/well_known_parameters.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3641)
> fix: add a missing const

- ci/kokoro/docker/build-in-docker-bazel.sh
- google/cloud/bigtable/examples/BUILD
- google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
- google/cloud/storage/examples/BUILD
- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_bucket_acl_samples.cc
Part of the work for #3524 and #3523.  I found a number of silly mistakes that was rendering these programs not runnable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3640)
> refactor: no scripts for storage_bucket_acl_samples

- google/cloud/bigtable/examples/BUILD
- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/bigtable_autorun_examples.bzl
- google/cloud/storage/examples/BUILD
- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/storage_autorun_examples.bzl
- google/cloud/storage/examples/storage_examples.bzl
This will make the work on #3524 and #3523 easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3643)
> refactor: simplify examples maintenance

- google/cloud/storage/client.h
- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_autorun_examples.bzl
- google/cloud/storage/examples/storage_bucket_acl_samples.cc
- google/cloud/storage/examples/storage_examples_common.cc
- google/cloud/storage/examples/storage_examples_common.h
- google/cloud/storage/examples/storage_examples_common_test.cc
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/examples/storage_signed_url_v2_samples.cc
- google/cloud/storage/examples/storage_signed_url_v4_samples.cc
Part of the work for #3524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3646)
> refactor: no scripts for signed URL examples

- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/bigtable_autorun_examples.bzl
- google/cloud/bigtable/examples/bigtable_examples.bzl
- google/cloud/bigtable/examples/bigtable_hello_table_admin.cc
- google/cloud/bigtable/examples/run_admin_examples_production.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
Run this program using CMake and/or Bazel, no scripts necessary.
Fixes #3681 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3691)
> refactor: no scripts for bigtable_hello_table_admin

- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_autorun_examples.bzl
- google/cloud/storage/examples/storage_bucket_acl_samples.cc
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/examples/storage_examples_common.cc
- google/cloud/storage/examples/storage_examples_common.h
- google/cloud/storage/examples/storage_examples_common_test.cc
- google/cloud/storage/examples/storage_website_samples.cc
Use C++ code to drive the static website configuration examples.
Fixes #3671
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3692)
> refactor: static website config examples

- google/cloud/storage/policy_document.h
- google/cloud/storage/policy_document_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3699)
> feat: default timepoint in PolicyDocumentV4

- google/cloud/storage/examples/storage_policy_doc_samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3718)
> fix: incorrect name for signature field

- ci/etc/integration-tests-config.ps1
- ci/kokoro/windows/build-quickstart-bazel.ps1
- ci/kokoro/windows/build.ps1
- ci/kokoro/windows/common.cfg
Part of the work for #3534
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3723)
> ci: test quickstart instructions for Windows+Bazel

- google/cloud/storage/examples/storage_bucket_cors_samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3725)
> feat(storage): new sample to remove CORS configuration

- README.md
- ci/etc/kokoro/install/run-installed-programs.sh
- ci/kokoro/docker/build-in-docker-bazel-dependency.sh
- ci/kokoro/windows/build-quickstart-bazel.ps1
- google/cloud/storage/README.md
- google/cloud/storage/quickstart/quickstart.cc
Fixes an issue brought up in https://github.com/googleapis/google-cloud-cpp/pull/3724
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3726)
> fix: remove unused project_id arg

- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_autorun_examples.bzl
- google/cloud/storage/examples/storage_examples.bzl
- google/cloud/storage/examples/storage_notification_samples.cc
Fixes #3669 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3745)
> refactor: run storage notification examples without scripts

- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_autorun_examples.bzl
- google/cloud/storage/examples/storage_default_object_acl_samples.cc
- google/cloud/storage/examples/storage_examples.bzl
Fixes #3655
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3749)
> refactor: run storage default object examples without scripts

- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/bigtable_autorun_examples.bzl
- google/cloud/bigtable/examples/bigtable_examples.bzl
- google/cloud/bigtable/examples/run_admin_examples_production.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
- google/cloud/bigtable/examples/table_admin_async_snippets.cc
Fixes #3678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3759)
> refactor: run bigtable_table_admin_async_snippets without scripts

- google/cloud/storage/examples/storage_bucket_acl_samples.cc
Fixes #3757
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3758)
> cleanup: use service account in storage_bucket_acl_samples

- release/release.sh
Addresses two post-merge comments from @devbww
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3760)
> fix: use printf %q for quoting

- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_autorun_examples.bzl
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/examples/storage_object_versioning_samples.cc
Fixes #3665
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3761)
> refactor: run storage object versioning examples without scripts

- ci/kokoro/docker/build-in-docker-bazel.sh
Fixes #3746
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3753)
> ci: better cleanup for HMAC test service accounts

- google/cloud/storage/examples/storage_default_object_acl_samples.cc
Fixes #3763
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3767)
> cleanup: use the service account instead of "allAuthenticatedUsers"

- ci/etc/kokoro/install/run-installed-programs.sh
- ci/kokoro/docker/build-in-docker-bazel.sh
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
- ci/kokoro/docker/coverage-presubmit.cfg
- ci/kokoro/docker/coverage.cfg
- ci/kokoro/docker/integration-nightly.cfg
- ci/kokoro/docker/integration-presubmit.cfg
- ci/kokoro/docker/integration.cfg
- ci/kokoro/install/common.cfg
- ci/kokoro/macos/build.sh
- ci/kokoro/macos/common.cfg
- ci/kokoro/windows/build-quickstart-bazel.ps1
- ci/kokoro/windows/build-quickstart-cmake.ps1
- ci/kokoro/windows/common.cfg
Use a new account to run the integration tests and examples, with more
restricted privileges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3771)
> cleanup: new account to run integration tests

- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_autorun_examples.bzl
- google/cloud/storage/examples/storage_object_hold_samples.cc
- google/cloud/storage/examples/storage_object_samples.cc
Fixes #3663 and fixes #3664 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3772)
> refactor: run storage object hold examples without scripts

- bazel/googleapis.BUILD
Part of https://github.com/googleapis/google-cloud-cpp/issues/3560
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3775)
> feat: add the protos needed for bigquery

- ci/kokoro/docker/build-in-docker-bazel.sh
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/download-cache.sh
- ci/kokoro/docker/upload-cache.sh
- ci/kokoro/gcloud-functions.sh
- ci/kokoro/macos/download-cache.sh
- ci/kokoro/macos/upload-cache.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3773)
> ci: refactor functions to call gcloud

- google/cloud/storage/client.h
- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_autorun_examples.bzl
- google/cloud/storage/examples/storage_object_file_transfer_samples.cc
- google/cloud/storage/examples/storage_object_samples.cc
- google/cloud/storage/parallel_upload.h
Fixes #3657 and fixes #3658
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3778)
> refactor: run storage upload/download file examples without scripts

- ci/kokoro/docker/download-cache.sh
- ci/kokoro/docker/upload-cache.sh
- ci/kokoro/macos/download-cache.sh
- ci/kokoro/macos/upload-cache.sh
- release/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3785)
> cleanup: fix shellcheck warnings

- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/bigtable_autorun_examples.bzl
- google/cloud/bigtable/examples/bigtable_examples.bzl
- google/cloud/bigtable/examples/bigtable_hello_world.cc
- google/cloud/bigtable/examples/run_admin_examples_production.sh
- google/cloud/bigtable/examples/run_examples_utils.sh
Fixes #3682
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3784)
> refactor: run bigtable_hello_world without scripts

- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_client_mock_samples.cc
Fixes #3673 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3783)
> refactor: run storage_client_mock_samples without scripts

- ci/benchmarks/Dockerfile
- ci/kokoro/docker/Dockerfile.fedora-install
- ci/kokoro/docker/Dockerfile.ubuntu-install
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- doc/packaging.md
- super/external/googleapis.cmake
Related to #3788
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3789)
> chore: update to cpp-cmakefiles 0.8.0

- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_autorun_examples.bzl
- google/cloud/storage/examples/storage_examples.bzl
- google/cloud/storage/examples/storage_object_acl_samples.cc
Fixes #3668
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3777)
> refactor: run storage object ACL examples without scripts

- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/storage_autorun_examples.bzl
- google/cloud/storage/examples/storage_quickstart.cc
This example is used in the cloud.google.com website, I should not have
moved it around.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3792)
> feat: restore storage_quickstart example

- ci/etc/quickstart-config.sh
- ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
- ci/kokoro/macos/build-quickstart-bazel.sh
- ci/kokoro/macos/build-quickstart-cmake.sh
- ci/kokoro/macos/build.sh
- ci/kokoro/macos/upload-cache.sh
Part of the work for #3730 and #3731 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3793)
> ci: build scripts for quickstart on macOS

- google/cloud/storage/examples/storage_object_acl_samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3804)
> cleanup: remove top-level `gcs` namespace alias

- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_autorun_examples.bzl
- google/cloud/storage/examples/storage_bucket_samples.cc
- google/cloud/storage/examples/storage_examples.bzl
Fixes #3649
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3811)
> refactor: run storage bucket examples without scripts

- google/cloud/storage/client.h
- google/cloud/storage/examples/run_examples_utils.sh
- google/cloud/storage/examples/storage_object_rewrite_samples.cc
- google/cloud/storage/examples/storage_object_samples.cc
Fixes #3660
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3813)
> refactor: run storage rename object example without scripts

- .bazelrc
- bazel/ubsan_suppressions.txt
- google/cloud/storage/client.cc
- google/cloud/storage/client_sign_policy_document_test.cc
- google/cloud/storage/internal/policy_document_request.cc
- google/cloud/storage/internal/policy_document_request.h
- google/cloud/storage/internal/policy_document_request_test.cc
- google/cloud/storage/tests/signed_url_conformance_test.cc
This fixes #3326 and #3635.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3687)
> feat: implement POST policy escaping

- ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
- ci/kokoro/docker/build.sh
- ci/kokoro/docker/upload-cache.sh
Part of the work for #3734
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3830)
> ci: new quickstart build for Linux+CMake+vcpkg

- bazel/googleapis.BUILD
Part of https://github.com/googleapis/google-cloud-cpp/issues/3838
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3840)
> chore: added overlay dep that -common will need

- bazel/googleapis.BUILD
- google/cloud/bigquery/BUILD
- google/cloud/bigtable/BUILD
- google/cloud/bigtable/examples/BUILD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3842)
> refactor: remove unneeded targets from overlay BUILD

- google/cloud/storage/tests/object_file_multi_threaded_test.cc
In several places we computed random data from multiple threads using a
shared PRNG, which is inherently racy. Ironically, then we proceeded to
not use the data. Just removing the code makes some races go away.
Part of the work for #3832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3849)
> fix: remove unused racy code in a test

- google/cloud/storage/tests/object_insert_integration_test.cc
I think the regular expressions did not work with MSVC. I chose not to
investigate and just use a simpler predicate.
Part of the work for #3540 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3863)
> fix: object_insert_integration_test fails with MSVC

- ci/kokoro/macos/build-cmake.sh
- ci/kokoro/macos/common.cfg
Part of the work for #3540 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3864)
> ci: enable integration tests for macOS+CMake

- ci/kokoro/macos/build-bazel.sh
Part of the work for #3540
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3866)
> ci: enable integration tests for macOS+Bazel

- ci/kokoro/windows/build-cmake.ps1
Part of the work for #3540
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3874)
> ci: enable integration tests for Windows+CMake

- ci/etc/kokoro/install/project-config.sh
- ci/generate-markdown/generate-packaging.sh
- ci/kokoro/install/Dockerfile.ubuntu-focal
- doc/packaging.md
A new LTS release of Ubuntu (20.04 - Focal Fossa) has become available.
These last for 5 years and it would be nice to start testing on it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3893)
> ci: configure a kokoro/install build for Ubuntu:20.04

- ci/kokoro/docker/Dockerfile.fedora-install
- ci/kokoro/docker/Dockerfile.ubuntu-install
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-focal
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- doc/packaging.md
- super/external/googleapis.cmake
This also fixes #3892 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3914)
> chore: upgrade to googleapis v0.9.0

- .gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3949)
> chore: ignore compile_commands.json in git

- ci/kokoro/windows/build-cmake-dependencies.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3955)
> ci: fix windows + vcpkg cache update

- google/cloud/completion_queue_test.cc
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/3952
Fixes a flake by using `future::wait()` rather than wait_for(), and
increasing a relative timer that looked like a potential future flake
(pun accidental).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3957)
> fix: windows+bazel flake

- google/cloud/storage/client.cc
- google/cloud/storage/examples/storage_policy_doc_samples.cc
- google/cloud/storage/internal/policy_document_request.cc
- google/cloud/storage/internal/policy_document_request.h
- google/cloud/storage/internal/policy_document_request_test.cc
- google/cloud/storage/policy_document.h
- google/cloud/storage/policy_document_test.cc
- google/cloud/storage/tests/signed_url_conformance_test.cc
This fixes #3836
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3961)
> feat: prepare form fields in signed V4 policies

- ci/kokoro/docker/publish-refdocs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3965)
> ci: fix publish-refdocs for common libraries

- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/bigtable_examples.bzl
- google/cloud/bigtable/examples/table_admin_async_snippets.cc
- google/cloud/bigtable/examples/table_admin_iam_policy_snippets.cc
- google/cloud/bigtable/examples/table_admin_snippets.cc
- google/cloud/bigtable/table_admin.h
- google/cloud/bigtable/tests/CMakeLists.txt
- google/cloud/bigtable/tests/admin_async_future_integration_test.cc
- google/cloud/bigtable/tests/admin_iam_policy_integration_test.cc
- google/cloud/bigtable/tests/admin_integration_test.cc
- google/cloud/bigtable/tests/bigtable_client_integration_tests.bzl
run integration tests and examples against production for table level IAM Policy.
This closes #3755
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3964)
> refactor: run integration tests and examples against production for table level IAM Policy

- .clang-tidy
- google/cloud/bigtable/testing/table_integration_test.cc
- google/cloud/internal/build_info.cc.in
- google/cloud/storage/internal/hash_validator_impl.cc
- google/cloud/storage/internal/object_requests.cc
- google/cloud/storage/internal/resumable_upload_session.cc
- google/cloud/storage/oauth2/google_credentials.cc
Justification is included in the changed file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3970)
> chore: disable modernize-avoid-c-arrays

- google/cloud/storage/testbench/gcs_bucket.py
- google/cloud/storage/testbench/gcs_object.py
Address inconsistency raised in: #3447. This will help use the testbench with languages like Golang.
Fixes #3447 
cc: @tritone 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3972)
> fix: storage testbench to use str instead int

- doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3986)
> doc: update the instructions to cut a release

- doc/cutting-a-release.md
- google/cloud/bigtable/quickstart/WORKSPACE
- google/cloud/storage/quickstart/WORKSPACE
Also update the documentation to mention we need to do this from now on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3989)
> chore: update version for */quickstart/WORKSPACE

- ci/kokoro/docker/Dockerfile.fedora-install
- ci/kokoro/windows/build-cmake-dependencies.ps1
- super/CMakeLists.txt
- super/external/benchmark.cmake
Part of https://github.com/googleapis/google-cloud-cpp/issues/3561
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4005)
> chore: add benchmark dep needed by spanner

- cmake/GoogleCloudCppCommon.cmake
This PR copies the `google_cloud_cpp_install_headers` cmake function
from the -spanner repo. This version knows how to install headers
associated with interface libraries, in addition to regular libraries.
Spanner needs this support.
Part of https://github.com/googleapis/google-cloud-cpp/issues/3561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4008)
> feat: enable install of interface libraries

- ci/kokoro/docker/build-in-docker-bazel.sh
Fixes #3790
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4009)
> ci: avoid flakiness in HMAC integration tests

- README.md
- ci/generate-markdown/generate-readme.sh
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/4020
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4021)
> fix: remove incorrect note about Spanner

- google/cloud/spanner/client.h
- google/cloud/spanner/query_options.h
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/4037
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4046)
> doc: link to official QueryOptions docs

- ci/etc/kokoro/install/project-config.sh
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-focal
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/quickstart/Makefile
Fixes: #4015
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4051)
> feat: add spanner/quickstart/Makefile

- google/cloud/storage/parallel_upload.cc
Fixes #4056 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4059)
> fix: C2593: 'operator =' is ambiguous

- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-focal
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/kokoro/install/build.sh
This should have been part of PR #4081, but I forgot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4082)
> cleanup: remove WARNING about auto gen files

- google/cloud/bigtable/doc/bigtable-samples-data-client.dox
- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/bigtable_examples.bzl
- google/cloud/bigtable/examples/bigtable_examples_common.cc
- google/cloud/bigtable/examples/bigtable_examples_common.h
- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/read_snippets.cc
- google/cloud/bigtable/table.h
These tests follow the Java counterpart:
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/bigtable/snippets/src/test/java/com/example/bigtable/ReadsTest.java
Fixes #3499 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4054)
> test: add more bigtable read samples

- google/cloud/bigtable/examples/CMakeLists.txt
- google/cloud/bigtable/examples/bigtable_grpc_credentials.cc
- google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
- google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
- google/cloud/bigtable/examples/data_async_snippets.cc
- google/cloud/bigtable/examples/data_snippets.cc
- google/cloud/bigtable/examples/instance_admin_async_snippets.cc
- google/cloud/bigtable/examples/read_snippets.cc
- google/cloud/bigtable/examples/table_admin_async_snippets.cc
- google/cloud/bigtable/examples/table_admin_iam_policy_snippets.cc
- google/cloud/bigtable/examples/table_admin_snippets.cc
part of #3958
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4088)
> cleanup: enable clang-tidy for `bigtable/examples`

- bazel/googleapis.BUILD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4092)
> fix: drop unused dep; fixes comment

- google/cloud/bigtable/mutations.cc
- google/cloud/bigtable/mutations.h
- google/cloud/bigtable/mutations_test.cc
This fixes #3689.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4086)
> feat: overload SetCell() for bigtable::Cell

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4135)
> cleanup: remove stale comment

- ci/kokoro/docker/build-in-docker-cmake.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4136)
> cleanup: use xargs --verbose to print command

- ci/kokoro/docker/build-in-docker-cmake.sh
- google/cloud/storage/CMakeLists.txt
- google/cloud/storage/examples/CMakeLists.txt
- google/cloud/storage/examples/storage_grpc_samples.cc
- google/cloud/storage/tests/CMakeLists.txt
Part of the work for #4143 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4145)
> feat: enable GCS+gRPC on clang-tidy build

- ci/kokoro/docker/build-in-docker-cmake.sh
- google/cloud/storage/tests/grpc_integration_test.cc
Part of the work for #4143, incidentally this runs the first integration tests.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4149)
> feat: enable GCS+gRPC plugin on coverage build

- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4218)
> feat: new build with GCS+gRPC plugin disabled

- google/cloud/storage/internal/grpc_client.cc
- google/cloud/storage/internal/grpc_client.h
- google/cloud/storage/internal/grpc_client_test.cc
Fixes #4192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4242)
> feat: implement To/FromProto for CustomerEncryption

- google/cloud/storage/CMakeLists.txt
- google/cloud/storage/internal/grpc_client_failures_test.cc
- google/cloud/storage/storage_client_grpc_unit_tests.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4232)
> feat: test GrpcClient error reporting

- google/cloud/CMakeLists.txt
- google/cloud/bigtable/CMakeLists.txt
- google/cloud/config-version.cmake.in
- google/cloud/firestore/CMakeLists.txt
- google/cloud/spanner/CMakeLists.txt
- google/cloud/storage/CMakeLists.txt
- google/cloud/testing_util/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4244)
> cleanup: remove redundant GOOGLE_CLOUD_CPP_CONFIG* variables

- bazel/google_cloud_cpp_deps.bzl
- ci/kokoro/docker/build.sh
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-focal
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- doc/packaging.md
- super/external/grpc.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4261)
> cleanup: update to grpc v1.29.1

- google/cloud/storage/internal/grpc_client.cc
- google/cloud/storage/internal/grpc_client.h
- google/cloud/storage/internal/grpc_client_bucket_metadata_test.cc
- google/cloud/storage/internal/grpc_client_bucket_request_test.cc
- google/cloud/storage/internal/grpc_client_test.cc
Convert all fields except `lifecycle_policy`
Part of the work for #4173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4269)
> feat: improve To/FromProto for BucketMetadata

- google/cloud/bigtable/cell.h
- google/cloud/bigtable/mutations.cc
- google/cloud/bigtable/mutations.h
- google/cloud/bigtable/mutations_test.cc
This fixes #4109.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4241)
> feat: avoid copies in `SetCell(Cell)`

- google/cloud/storage/internal/grpc_client.cc
- google/cloud/storage/internal/grpc_client.h
- google/cloud/storage/internal/grpc_client_bucket_metadata_test.cc
- google/cloud/storage/lifecycle_rule.h
Fixes #4165 and fixes #4173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4270)
> feat: implement To/FromProto for LifecycleRule

- google/cloud/storage/benchmarks/BUILD
- google/cloud/storage/benchmarks/CMakeLists.txt
- google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4277)
> feat: support XML vs. JSON in throughput_vs_cpu_benchmark

- google/cloud/bigtable/examples/data_snippets.cc
fixes #4119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4281)
> fix: flaky examples on macos builds

- ci/kokoro/docker/upload-coverage.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4293)
> feat: time codecov upload

- google/cloud/storage/benchmarks/storage_throughput_vs_cpu_plots.py
Some improvements on how the plots look, and generate one more useful
plot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4294)
> feat(storage/benchmarks): more and better plots

- google/cloud/storage/benchmarks/README.md
- google/cloud/storage/benchmarks/storage_throughput_vs_cpu_plots.py
I used these in #4298
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4301)
> doc(storage/benchmarks): print result summaries

- google/cloud/testing_util/assert_ok.cc
- google/cloud/testing_util/assert_ok.h
Fixes #4142.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4302)
> cleanup: Fix namespace in testing_util/assert_ok

- super/external/grpc.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4308)
> fix: missing dependency for gRPC in CMake superbuild

- ci/kokoro/docker/build-in-docker-bazel.sh
- ci/kokoro/docker/build.sh
Fixes: #4306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4313)
> fix: re-enable spanner backup tests w/ increased timeout

- google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
Fixes #4290
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4314)
> feat(storage/benchmarks): measure ObjectInsert()

- google/cloud/bigtable/examples/data_filter_snippets.cc
This Pull Request includes example of composing conditions. 
This also closes #3500
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4315)
> feat: more bigtable data filter samples

- CHANGELOG.md
Preview rendered file: https://github.com/devjgm/google-cloud-cpp/blob/release-notes/CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4318)
> feat: updated CHANGELOG for 2020-06 release

- google/cloud/BUILD
- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
- google/cloud/internal/slow_iota_test.cc
In this PR we write a simple test for a model of `source<T,E>`.
This is not the class or test we would expose to our customers,
it is just a kernel to start growing tests and helper functions around.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4323)
> feat: prototype source<T, E>

- ci/kokoro/windows/build-bazel.ps1
- ci/kokoro/windows/build-quickstart-bazel.ps1
This is an attempt to fix the flakes in #4045
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4355)
> fix: don't preserve symlinks in 7z archive

- google/cloud/storage/benchmarks/BUILD
- google/cloud/storage/benchmarks/CMakeLists.txt
- google/cloud/storage/benchmarks/storage_benchmark_programs.bzl
- google/cloud/storage/benchmarks/throughput_experiment_test.cc
Add an integration test to run each experiment. Mostly because I am
annoyed about code that is not tested, but also because the (planned)
experiments for raw libcurl and raw grpc tests will need some kind of
testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4360)
> feat(storage/benchmark): experiment integration test

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/storage/client.cc
- google/cloud/storage/client_write_object_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4370)
> cleanup: minor issue that clang-format misses

- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_common.bzl
- google/cloud/google_cloud_cpp_common_unit_tests.bzl
- google/cloud/internal/source_transforms.h
- google/cloud/internal/source_transforms_test.cc
Fixes #4340
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4366)
> feat(source<T>): add TransformedSource

- google/cloud/spanner/database_admin_client_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4373)
> fix(spanner): use correct name for test
