doc/adr/2022-01-21-only-public-types-in-public-APIs.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8042)
=> doc(ADR): only public types in public APIs

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
Fixes #4198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8048)
=> feat(GCS+gRPC): implement GetObjectMetadata

google/cloud/pubsub/integration_tests/schema_admin_integration_test.cc, google/cloud/pubsub/integration_tests/subscriber_integration_test.cc, google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc, google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc, google/cloud/spanner/integration_tests/client_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8058)
=> test(spanner): use MakeInsecureCredentials() in UnifiedCredentials test

generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc
Motivated by a new service with a proto containing a "namespace"
field. The C++ proto compiler adds a trailing underscore to such
fields and their associated accessors, so we should do the same.
And we should also do it in the parameters to "method_signature"
overloads, and in generated @param annotations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8063)
=> feat(generator): handle proto fields named with C++ keywords

google/cloud/testing_util/validate_metadata.cc
Some RPCs do not have the API annotations needed to validate the
`x-goog-request-params` header.  In fact, some of these RPCs may
not have a `x-goog-request-params` header set at all, and we should
not try to validate them.
Part of the work for #8074
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8076)
=> test(common): support validation resource headers

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc
Fixes #4197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8056)
=> feat(GCS+gRPC): implement ListObjects()

generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8087)
=> impl(generator): skip method signatures that contain deprecated fields

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, external/googleapis/protodeps/bigtable.deps, generator/generator_config.textproto, google/cloud/automl/auto_ml_client.h, google/cloud/automl/internal/auto_ml_stub.h, google/cloud/automl/prediction_client.h, google/cloud/gkehub/gke_hub_client.h, google/cloud/spanner/admin/database_admin_client.h
Notably includes the Spanner `DatabaseDialect` and `TypeAnnotationCode`
fields for supporting both Google SQL and PostgreSQL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8093)
=> chore(deps): update googleapis

generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/test.proto, generator/internal/client_generator.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8091)
=> fix(generator): incorrect methods comments when skippking deprecated methods

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc
Fixes #7750
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8092)
=> feat(GCS+gRPC): implement DeleteObject

ci/cloudbuild/builds/bazel-latest.sh, ci/cloudbuild/triggers/bazel-latest-ci.yaml, ci/cloudbuild/triggers/bazel-latest-pr.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8099)
=> ci: add bazel-latest build

google/cloud/storage/client.cc, google/cloud/storage/client.h, google/cloud/storage/internal/object_requests.h, google/cloud/storage/upload_options.h
Fixes #4514
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8096)
=> feat(storage): per-upload buffer size configuration

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc
Fixes #4193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8100)
=> feat(GCS+gRPC): implement RewriteObject()

generator/generator_config.textproto, google/cloud/storage/CMakeLists.txt, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser.h, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/storage_client_grpc_unit_tests.bzl, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
Fixes #7752
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8103)
=> feat(GCS+gRPC): implement GetBucketMetadata()

CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8114)
=> cleanup: better error messages for invalid features

google/cloud/storage/tests/create_client_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8113)
=> cleanup(storage): remove unused includes in test

doc/contributor/howto-guide-adding-generated-libraries.md
When I follow these instructions, I skip the mkdir and everything seems to work just fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8119)
=> doc: remove unneeded mkdir

ci/etc/oldest-deps/vcpkg.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8123)
=> chore: update gtest version in cmake-oldest-deps

google/cloud/internal/rest_response.cc, google/cloud/internal/rest_response.h, google/cloud/internal/rest_response_test.cc, google/cloud/testing_util/CMakeLists.txt, google/cloud/testing_util/google_cloud_cpp_testing_rest.bzl, google/cloud/testing_util/mock_rest_response.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8112)
=> impl(rest): add RestResponse class

bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/builds/lib/integration.sh, cmake/GoogleapisConfig.cmake, google/cloud/recommender/recommender_client.h, google/cloud/storage/internal/grpc_object_metadata_parser.cc, google/cloud/storage/internal/grpc_object_metadata_parser.h, google/cloud/storage/internal/grpc_object_metadata_parser_test.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8156)
=> chore(deps): update googleapis circa 2022-01-28

google/cloud/storage/internal/grpc_client_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8159)
=> test(GCS+gRPC): adjust test for new protos

google/cloud/asset/asset_client.cc, google/cloud/asset/asset_connection.cc, google/cloud/asset/asset_connection.h, google/cloud/asset/internal/asset_connection_impl.cc, google/cloud/asset/internal/asset_connection_impl.h, google/cloud/asset/mocks/mock_asset_connection.h, google/cloud/memcache/cloud_memcache_client.cc, google/cloud/memcache/cloud_memcache_connection.cc, google/cloud/memcache/cloud_memcache_connection.h, google/cloud/memcache/internal/cloud_memcache_connection_impl.cc, google/cloud/memcache/internal/cloud_memcache_connection_impl.h, google/cloud/memcache/mocks/mock_cloud_memcache_connection.h, google/cloud/redis/cloud_redis_client.cc, google/cloud/redis/cloud_redis_connection.cc, google/cloud/redis/cloud_redis_connection.h, google/cloud/redis/internal/cloud_redis_connection_impl.cc, google/cloud/redis/internal/cloud_redis_connection_impl.h, google/cloud/redis/mocks/mock_cloud_redis_connection.h
Regenerate a few libraries merged after #8158 got started.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8162)
=> chore: update generated libraries

google/cloud/spanner/client.h, google/cloud/spanner/internal/connection_impl.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8166)
=> impl(spanner): follow the Options rules of thumb by merging defaults

google/cloud/oslogin/README.md, google/cloud/oslogin/doc/main.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8191)
=> docs: fix oslogin links

google/cloud/internal/curl_impl.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8163)
=> impl(rest): correct blank line header check

google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/object_requests_test.cc
Part of the work for #4196
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8193)
=> fix(storage): missing options in UpdateObject()

ci/cloudbuild/builds/cmake-install.sh, external/googleapis/CMakeLists.txt, external/googleapis/protodeps/common.deps, external/googleapis/protolists/common.list, external/googleapis/update_libraries.sh
Part of the work for #8183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8192)
=> feat(googleapis): add google/cloud/common protos

google/cloud/internal/rest_request.cc, google/cloud/internal/rest_response.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8196)
=> fix(rest): add missing include for std::tolower

google/cloud/assuredworkloads/BUILD.bazel, google/cloud/assuredworkloads/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8199)
=> fix(assuredworkloads): disable on Windows

google/cloud/BUILD.bazel, google/cloud/internal/rest_request.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8200)
=> fix(rest): compile with MSVC 2017

ci/kokoro/windows/build-32.bat, ci/kokoro/windows/build.bat
credit to @devbww for diagnosing the problem and @coryan for writing the code to copy-paste. (assuming this fix works)
Hopefully this breaks our windows builds...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8197)
=> ci: fix kokoro windows builds?

doc/contributor/howto-guide-adding-generated-libraries.md, external/googleapis/update_libraries.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8214)
=> feat(generator): speed up new library generation

generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/test.proto, generator/internal/descriptor_utils.cc
fixes #8105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8215)
=> impl(generator): allow service proto definitions without leading comments

ci/cloudbuild/builds/lib/integration.sh
Part of the work for #4196
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8211)
=> chore(deps): update storage testbench

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc
Fixes #4194
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8209)
=> feat(GCS+gRPC): implement `ComposeObject()`

BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8225)
=> cleanup: simplify Bazel targets for new libraries

google/cloud/testing_util/validate_metadata.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8226)
=> test(common): speed up context tests on Windows

google/cloud/logging/README.md, google/cloud/logging/quickstart/quickstart.cc, google/cloud/pubsublite/README.md, google/cloud/pubsublite/quickstart/quickstart.cc, google/cloud/secretmanager/README.md, google/cloud/secretmanager/quickstart/quickstart.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8228)
=> cleanup: fix some nits in quickstarts

CHANGELOG.md, generator/integration_tests/golden/BUILD.bazel, generator/integration_tests/golden/CMakeLists.txt, generator/integration_tests/golden/golden_kitchen_sink_connection.h, generator/integration_tests/golden/google_cloud_cpp_generator_golden_files.bzl, generator/integration_tests/golden/internal/golden_kitchen_sink_connection_impl.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_connection_impl.h, generator/integration_tests/golden/internal/streaming.cc, generator/internal/connection_generator.cc, generator/internal/connection_impl_generator.cc, google/cloud/bigquery/CMakeLists.txt, google/cloud/bigquery/bigquery_read_connection.cc, google/cloud/bigquery/bigquery_read_connection.h, google/cloud/bigquery/google_cloud_cpp_bigquery.bzl, google/cloud/bigquery/internal/bigquery_read_connection_impl.cc, google/cloud/bigquery/internal/bigquery_read_connection_impl.h, google/cloud/bigquery/internal/streaming.cc, google/cloud/osconfig/agent_endpoint_connection.h, google/cloud/osconfig/internal/agent_endpoint_connection_impl.cc, google/cloud/osconfig/internal/agent_endpoint_connection_impl.h, google/cloud/osconfig/internal/streaming.cc
fixes: #8139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8218)
=> refactor: in generated libs move streaming update function internal

google/cloud/secretmanager/quickstart/BUILD.bazel, google/cloud/tasks/quickstart/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8232)
=> cleanup: avoid the experimental target of a GA'd library

google/cloud/gkehub/README.md, google/cloud/gkehub/quickstart/quickstart.cc, google/cloud/kms/README.md, google/cloud/kms/quickstart/quickstart.cc, google/cloud/logging/README.md, google/cloud/logging/quickstart/quickstart.cc, google/cloud/memcache/README.md, google/cloud/memcache/quickstart/quickstart.cc, google/cloud/redis/README.md, google/cloud/redis/quickstart/quickstart.cc
Part of the work for #7936 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8249)
=> fix: typos and errors in quickstart programs

google/cloud/cloudbuild/CMakeLists.txt, google/cloud/cloudbuild/README.md, google/cloud/cloudbuild/quickstart/quickstart.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8260)
=> fix(cloudbuild): quickstart works and tested by CI

ci/cloudbuild/builds/cmake-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8265)
=> ci: reduce logging in cmake-install build

doc/contributor/howto-guide-setup-development-workstation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8266)
=> doc: show how to create compile_commands.json w/ cmake

.editorconfig, ci/cloudbuild/build.sh, ci/cloudbuild/builds/checkers.sh, ci/cloudbuild/builds/lib/bazel.sh, ci/cloudbuild/cache.sh, ci/cloudbuild/trigger.sh, ci/etc/quickstart-config.sh, ci/lib/io.sh, release/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8270)
=> chore: shfmt follows google style

google/cloud/workflows/CMakeLists.txt, google/cloud/workflows/README.md, google/cloud/workflows/quickstart/quickstart.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8274)
=> fix(workflows): correct quickstart and enable in CI

google/cloud/appengine/CMakeLists.txt
Part of the work for #7936 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8275)
=> test(appengine): enable quickstart in CI

ci/kokoro/macos/builds/cmake-vcpkg.sh, ci/kokoro/macos/builds/quickstart-cmake.sh
Fixes #8273
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8277)
=> ci: deflake macOS+vcpkg builds

google/cloud/dataproc/internal/autoscaling_policy_metadata_decorator.cc, google/cloud/dataproc/internal/autoscaling_policy_option_defaults.cc, google/cloud/dataproc/internal/batch_controller_metadata_decorator.cc, google/cloud/dataproc/internal/batch_controller_option_defaults.cc, google/cloud/dataproc/internal/cluster_controller_metadata_decorator.cc, google/cloud/dataproc/internal/cluster_controller_option_defaults.cc, google/cloud/dataproc/internal/job_controller_metadata_decorator.cc, google/cloud/dataproc/internal/job_controller_option_defaults.cc, google/cloud/dataproc/internal/workflow_template_metadata_decorator.cc, google/cloud/dataproc/internal/workflow_template_option_defaults.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8282)
=> cleanup: regenerate dataproc

google/cloud/spanner/samples/samples.cc
Return a `google::cloud::Status` from some `Commit()` functors to use
the transaction retry loop.  I also used `std::move()` consistently to
return a `foo.status()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8279)
=> test(spanner): deflake samples

ci/cloudbuild/builds/bazel-oldest.sh, ci/cloudbuild/triggers/bazel-oldest-ci.yaml, ci/cloudbuild/triggers/bazel-oldest-pr.yaml
Part of the work for #8259
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8281)
=> ci: new build for oldest Bazel version

ci/cloudbuild/triggers/bazel-oldest-ci.yaml, ci/cloudbuild/triggers/bazel-oldest-pr.yaml
Ooops.  I created the triggers with the right names, this is just fixing our metadata. Part of the work for #8259 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8292)
=> ci: fix name for new triggers

.github/renovate.json
Fixes #8297, part of the work for #8259
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8298)
=> ci: automatically update Bazel version, take 2

ci/cloudbuild/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8295)
=> cleanup: cut more output from interactive builds

ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh, google/cloud/accessapproval/CMakeLists.txt, google/cloud/automl/CMakeLists.txt, google/cloud/dlp/CMakeLists.txt, google/cloud/language/CMakeLists.txt, google/cloud/orgpolicy/CMakeLists.txt, google/cloud/retail/CMakeLists.txt, google/cloud/retail/README.md, google/cloud/retail/quickstart/quickstart.cc, google/cloud/texttospeech/CMakeLists.txt, google/cloud/translate/CMakeLists.txt, google/cloud/videointelligence/CMakeLists.txt, google/cloud/vision/CMakeLists.txt, google/cloud/webrisk/CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8299)
=> ci: enable more quickstart programs

ci/kokoro/macos/build.sh
We were not cleaning up the artifacts directory on errors. Kokoro copies
this directory very slowly, and this was making our failures slower than
they needed to be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8308)
=> ci: speedup macos build shutdown

.github/renovate.json
I forgot about the Kokoro builds in my last change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8311)
=> ci: automatically update Bazel version, part 2

.github/renovate.json
This is the "how do regular expressions work?" edition.
Part of the work for #8259
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8315)
=> ci: automatically update Bazel, part 3

google/cloud/spanner/internal/defaults.cc, google/cloud/spanner/internal/defaults_test.cc
Add support to override the project used for billing and accounting
purposes.
Part of the work for #8284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8316)
=> feat(spanner): support x-goog-user-project

ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh, google/cloud/gameservices/CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8322)
=> test(gameservices): enable quickstart in CI

google/cloud/iot/CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8334)
=> test(iot): enable quickstart in CI

google/cloud/talent/CMakeLists.txt, google/cloud/talent/README.md, google/cloud/talent/quickstart/quickstart.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8335)
=> test(talent): enable quickstart in CI

generator/generator_config.textproto, google/cloud/apigeeconnect/internal/connection_option_defaults.cc, google/cloud/automl/internal/prediction_option_defaults.cc, google/cloud/bigquery/internal/connection_option_defaults.cc, google/cloud/retail/internal/prediction_option_defaults.cc
Fixes #8304 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8319)
=> cleanup: rename conflicting endpoints

ci/cloudbuild/builds/integration-production.sh, ci/cloudbuild/triggers/integration-production-ci.yaml, ci/cloudbuild/triggers/integration-production-pr.yaml
Part of the work for #6221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8323)
=> ci: add GCB build testing against prod

ci/kokoro/macos/builds/bazel.sh, ci/kokoro/macos/builds/cmake-vcpkg.sh, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-cmake.ps1, ci/kokoro/windows/lib/integration.ps1
Part of the work for #6221 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8344)
=> ci: run minimal quickstart programs on Kokoro

google/cloud/bigtable/table_admin.h, google/cloud/bigtable/table_admin_test.cc
Part of the work for #7530
This is the analog of #8086, but for `TableAdmin` instead of `InstanceAdmin`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8351)
=> impl(bigtable): common policies in TableAdmin

ci/kokoro/windows/build-cmake.ps1
I tested locally, should be good to go.  Tag #6221 for future reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8352)
=> ci: fix Windows+CMake builds

ci/cloudbuild/build.sh, ci/cloudbuild/builds/clang-tidy.sh, ci/cloudbuild/builds/lib/cmake.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8350)
=> ci: no cache stats in interactive builds

generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc, google/cloud/bigtable/async_row_reader_test.cc, google/cloud/bigtable/mutation_batcher_test.cc, google/cloud/bigtable/row_reader_test.cc, google/cloud/bigtable/table_admin_legacy_test.cc, google/cloud/bigtable/table_apply_test.cc, google/cloud/bigtable/table_check_and_mutate_row_test.cc, google/cloud/bigtable/table_readmodifywriterow_test.cc, google/cloud/bigtable/table_readrow_test.cc, google/cloud/bigtable/testing/mock_async_failing_rpc_factory.h, google/cloud/bigtable/testing/mock_response_reader.h, google/cloud/internal/minimal_iam_credentials_stub_test.cc, google/cloud/pubsub/internal/publisher_metadata_test.cc, google/cloud/pubsub/internal/schema_metadata_test.cc, google/cloud/pubsub/internal/subscriber_metadata_test.cc, google/cloud/pubsub/publisher_connection_test.cc, google/cloud/pubsub/schema_admin_connection_test.cc, google/cloud/pubsub/subscriber_connection_test.cc, google/cloud/pubsub/subscription_admin_connection_test.cc, google/cloud/pubsub/topic_admin_connection_test.cc, google/cloud/spanner/internal/database_admin_metadata_test.cc, google/cloud/spanner/internal/instance_admin_metadata_test.cc, google/cloud/spanner/internal/metadata_spanner_stub_test.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_configure_client_context_test.cc, google/cloud/storage/internal/storage_stub_factory_test.cc, google/cloud/testing_util/validate_metadata.cc, google/cloud/testing_util/validate_metadata.h
This is needed to complete the next import into Google's code
repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8348)
=> test: use fixture for gRPC metadata tests

doc/contributor/howto-guide-adding-generated-libraries.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8359)
=> doc: update new library how-to guide

google/cloud/bigtable/table_admin_test.cc
`TableAdmin` has a few public structs. They are really simple, but we should still test them.
* [`CreateBackupParams`](https://github.com/googleapis/google-cloud-cpp/blob/522f5f9deaed7c2049896c1ff3724d0475e5ad07/google/cloud/bigtable/table_admin.h#L375-L392)
* [`UpdateBackupParams`](https://github.com/googleapis/google-cloud-cpp/blob/522f5f9deaed7c2049896c1ff3724d0475e5ad07/google/cloud/bigtable/table_admin.h#L458-L472)
* [`ListBackupParams`](https://github.com/googleapis/google-cloud-cpp/blob/522f5f9deaed7c2049896c1ff3724d0475e5ad07/google/cloud/bigtable/table_admin.h#L543)
* [`RestoreTableParams`](https://github.com/googleapis/google-cloud-cpp/blob/522f5f9deaed7c2049896c1ff3724d0475e5ad07/google/cloud/bigtable/table_admin.h#L679-L694)
--- …
=> test(bigtable): TableAdmin params structs

generator/generator_config.textproto, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser.h, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc
Fixes #7754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8372)
=> feat(GCS+gRPC): implement `CreateBucket()`

generator/generator_config.textproto, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser.h, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc
Fixes #7755
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8375)
=> feat(GCS+gRPC): implement `DeleteBucket()`

google/cloud/securitycenter/CMakeLists.txt, google/cloud/securitycenter/README.md, google/cloud/securitycenter/quickstart/quickstart.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8382)
=> test(securitycenter): enable quickstart in CI

google/cloud/servicecontrol/CMakeLists.txt
Part of the work for #7936 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8381)
=> feat(servicecontrol): enable quickstart in CI

google/cloud/assuredworkloads/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8384)
=> feat(assuredworkloads): enable quickstart in CI

google/cloud/debugger/CMakeLists.txt, google/cloud/debugger/README.md, google/cloud/debugger/quickstart/quickstart.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8386)
=> test(debugger): enable quickstart in CI

google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.h, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc
Motivated by #4162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8390)
=> fix(GCS+gRPC): ignored fields in BucketMetadata parsing

google/cloud/internal/rest_client.cc, google/cloud/internal/rest_client_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8397)
=> impl(rest): add content-length header to requests with payloads

google/cloud/internal/rest_client.cc, google/cloud/internal/rest_client_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8399)
=> impl(rest): only populate userIp when requested via options

google/cloud/bigtable/internal/prefix_range_end.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8405)
=> cleanup(bigtable): add missing includes

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_rest_internal.bzl, google/cloud/google_cloud_cpp_rest_internal_unit_tests.bzl, google/cloud/internal/oauth2_impersonate_service_account_credentials.cc, google/cloud/internal/unified_rest_credentials.cc, google/cloud/internal/unified_rest_credentials.h, google/cloud/internal/unified_rest_credentials_test.cc
Integration tests are in progress to increase test coverage.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400)
=> impl(oauth2): add GUAC to OAuth2 credential mapping

google/cloud/options.cc, google/cloud/options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8407)
=> cleanup(common): better names for MergeOptions parameters

generator/generator_config.textproto, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser.h, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc
Fixes #4162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8394)
=> feat(GCS+gRPC): implement `PatchBucket()`

generator/generator_config.textproto, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser.h, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc
Fixes #7753
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8415)
=> feat(GCS+grpc): implement `ListBuckets()`

generator/generator_config.textproto, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser.h, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc
Fixes #4161
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8420)
=> feat(GCS+gRPC): implement `GetNativeBucketIamPolicy()`

generator/generator_config.textproto, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser.h, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc
Fixes #4158
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8428)
=> feat(GCS+gRPC): implement `LockBucketRetentionPolicy()`

generator/generator_config.textproto, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser.h, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc
Fixes #4159
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8427)
=> feat(GCS+gRPC): implement `TestBucketIamPermissions()`

google/cloud/internal/rest_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8433)
=> impl(rest): omit content-length header when zero

google/cloud/bigtable/doc/bigtable-hello-instance-admin.dox, google/cloud/bigtable/doc/bigtable-hello-table-admin.dox, google/cloud/bigtable/doc/bigtable-hello-world.dox, google/cloud/bigtable/doc/bigtable-samples-grpc-credentials.dox, google/cloud/bigtable/instance_admin.h
Fixes #7528
I took a final pass at this. I am marking the issue fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8436)
=> docs(bigtable): cleanup admin documentation

google/cloud/bigtable/async_row_reader.h
This fixes the import.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8437)
=> fix(bigtable): cast to std::string which works with string and Cord

generator/generator_config.textproto, google/cloud/storage/internal/bucket_requests.cc, google/cloud/storage/internal/bucket_requests.h, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser.h, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc
Fixes #4160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8431)
=> feat(GCS+gRPC): implement `SetBucketIamPolicy()`

google/cloud/internal/http_payload.cc, google/cloud/internal/oauth2_authorized_user_credentials.h, google/cloud/internal/oauth2_compute_engine_credentials.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8442)
=> chore: cleanup formatting and documentation

google/cloud/internal/background_threads_impl.cc
Don't return from the `AutomaticallyCreatedBackgroundThreads` ctor until we
know that each thread functor has been invoked.
Some users hold their client objects, which own `BackgroundThreads` objects,
in such a way that the client is not destroyed during process shutdown, and
therefore that its background threads are not joined.  This means that it
is possible for a `std::thread` to be running but still within the standard
library (i.e., not yet in the user functor) while global objects are being
destroyed.
In the case at hand, the standard library was in the process of setting up
thread-specific data via `pthread_setspecific()`, when its key appears to
have disappeared from underneath it, resulting in MemorySanitizer errors.
This probably isn't the only shutdown race waiting to bite us, …
=> fix: wait until AutomaticallyCreatedBackgroundThreads start

google/cloud/pubsub/internal/defaults.cc
Use `g::c::internal::PopulateCommonOptions()` and
`g::c::internal::PopulateGrpcOptions()` to initialize the Pub/Sub
default options.
Part of the work for #3317, it also helps with #8284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8454)
=> refactor(pubsub): use common option initializers

google/cloud/internal/rest_request.cc, google/cloud/internal/rest_request.h, google/cloud/internal/rest_request_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8461)
=> impl(rest): add AppendPath methods

google/cloud/internal/rest_options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8468)
=> doc(storage): UserIp option is deprecated

google/cloud/storage/grpc_plugin.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8490)
=> doc(GCS+gRPC): update GrpcPluginOption description

BUILD.bazel, CHANGELOG.md, README.md, google/cloud/pubsublite/CMakeLists.txt, google/cloud/pubsublite/README.md, google/cloud/pubsublite/doc/main.dox, google/cloud/pubsublite/quickstart/BUILD.bazel
Part of the work for #8495
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8497)
=> fix(pubsublite)!: revert GA declaration

release/changes.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8499)
=> chore: add "impl" to the list of uninteresting changes

doc/contributor/howto-guide-declare-a-library-ga.md
Restructured the document to make steps more obvious. Add commands to
execute the steps as little shell scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8494)
=> doc: improvements to "How-To declare GA"

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8500)
=> doc: update CHANGELOG for v1.38.0 release

google/cloud/storage/benchmarks/aggregate_download_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_download_throughput_options_test.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_options_test.cc, google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/benchmarks/benchmark_utils.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8503)
=> cleanup(GCS+gRPC): remove unused enum values

google/cloud/pubsublite/internal/futures.h, google/cloud/pubsublite/internal/resumable_async_streaming_read_write_rpc.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8505)
=> cleanup(pubsublite): add RAII async root wrapper

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc
The `ReadRequest` captured within `PartialResultSetReaderFactory`
needs to be valid after `ConnectionImpl::ReadImpl()` returns because
`PartialResultSetResume::Read()` will use the factory/request, along
with an updated `resume_token`, to create a new reader when the
previous reader finishes with a retry-able status.  So, the request
needs to be captured "by value".
However, `ConnectionImpl::ReadImpl()` also needs to be able to
update the transaction field within that `ReadRequest` (with the
result of an implicit `BeginTransaction()`) should the original
request fail or otherwise not yield metadata.  So, we also need to
hold a reference to that captured value.
To satisfy both requirements, heap allocate the `ReadRequest` and
share its ownership between the factory and `ReadImpl()`.
To …
=> fix(spanner): capture the ReadRequest by value in the reader factory

google/cloud/spanner/internal/partial_result_set_source.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8526)
=> impl(spanner): add a TODO concerning the resume_token protocol

google/cloud/pubsublite/CMakeLists.txt, google/cloud/pubsublite/google_cloud_cpp_pubsublite.bzl, google/cloud/pubsublite/internal/resumable_async_streaming_read_write_rpc.h, google/cloud/pubsublite/internal/resumable_async_streaming_read_write_rpc_test.cc, google/cloud/pubsublite/internal/service.h, google/cloud/pubsublite/internal/service_composite.h, google/cloud/pubsublite/internal/service_composite_test.cc, google/cloud/pubsublite/pubsublite_testing.bzl, google/cloud/pubsublite/pubsublite_unit_tests.bzl, google/cloud/pubsublite/testing/mock_service.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8529)
=> feat(pubsublite): service composite implementation

ci/kokoro/macos/builds/cmake-vcpkg.sh
Fixes: #8362
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8540)
=> ci: retry brew installs

generator/BUILD.bazel, generator/integration_tests/BUILD.bazel, generator/integration_tests/golden/BUILD.bazel
Related to: #3701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8548)
=> chore: limit generator bazel visibility

ci/generate-markdown/generate-packaging.sh, doc/packaging.md
Fixes: #6697
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8546)
=> doc: install instructions for macOS

google/cloud/testing_util/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8556)
=> chore!: remove deprecated bazel config_settings

ci/cloudbuild/builds/clang-tidy.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8563)
=> ci: only "Highlight generated code differences" on non-manual builds

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8565)
=> test(storage): control gRPC channel count in benchmark

generator/integration_tests/backup.proto, generator/integration_tests/common.proto, generator/integration_tests/golden/golden_thing_admin_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8576)
=> cleanup: remove unused imports

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8574)
=> feat(spanner): integration tests and sample for CopyBackup()

ci/verify_current_targets/BUILD.bazel, ci/verify_deprecated_targets/BUILD.bazel
Related to: #3701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8577)
=> ci: change the ci/verify* BUILD files to private visibility

google/cloud/storage/internal/retry_resumable_upload_session_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8587)
=> cleanup(storage): remove unnecessary test fixture

ci/verify_deprecated_targets/BUILD.bazel
Part of #3701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8600)
=> ci: test all deprecated bazel targets

google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc
The recent spate of `CreateBackup()` failures highlighted a few places
where we subsequently dereferenced a non-OK `StatusOr`.  Fix those by
either asserting the operation was OK (when the rest of the test case
is then useless), or guarding the dereference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8604)
=> ci(spanner): eliminate some run-on crashes after expectation failures

ci/cloudbuild/builds/lib/cmake.sh, ci/cloudbuild/dockerfiles/fedora-35-cxx20.Dockerfile, ci/cloudbuild/triggers/cxx20-ci.yaml, ci/cloudbuild/triggers/cxx20-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8599)
=> ci: move cxx20 build to Fedora:35

ci/cloudbuild/builds/lib/integration.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8618)
=> ci: pin Werkzeug to a version compatible with httpbin

google/cloud/BUILD.bazel, google/cloud/capture_build_info.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8631)
=> cleanup: better name for rule attributes

ci/cloudbuild/dockerfiles/checkers.Dockerfile
The previous version no longer installs correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8635)
=> chore: update Python formatter (psf/black)

google/cloud/iam/integration_tests/iam_integration_test.cc
fixes #7357
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8636)
=> cleanup(iam): add retry loop to reduce integration test flakiness

generator/generator_config.textproto, google/cloud/pubsublite/admin_client.cc, google/cloud/pubsublite/admin_client.h, google/cloud/pubsublite/admin_connection.cc, google/cloud/pubsublite/admin_connection.h, google/cloud/pubsublite/internal/admin_auth_decorator.cc, google/cloud/pubsublite/internal/admin_auth_decorator.h, google/cloud/pubsublite/internal/admin_connection_impl.cc, google/cloud/pubsublite/internal/admin_connection_impl.h, google/cloud/pubsublite/internal/admin_logging_decorator.cc, google/cloud/pubsublite/internal/admin_logging_decorator.h, google/cloud/pubsublite/internal/admin_metadata_decorator.cc, google/cloud/pubsublite/internal/admin_metadata_decorator.h, google/cloud/pubsublite/internal/admin_stub.cc, google/cloud/pubsublite/internal/admin_stub.h, google/cloud/pubsublite/mocks/mock_admin_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8640)
=> feat(pubsublite): add async version of `GetTopicPartitions()`

google/cloud/pubsub/internal/create_channel.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8626)
=> fix(pubsub): increase grpc.max_metadata_size limit

ci/cloudbuild/dockerfiles/checkers.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8645)
=> chore: update shfmt version

ci/cloudbuild/dockerfiles/debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/fedora-34.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35-cxx11.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, doc/packaging.md
This reverts commit 17023f220015483ddd8358fc0d760d3d49bd2ec9.  See #8668 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8669)
=> Revert "chore(deps): protocolbuffers/protobuf to v3.20.0"

ci/cloudbuild/builds/checkers.sh, ci/cloudbuild/dockerfiles/checkers.Dockerfile, ci/generate-markdown/update-reference-index.sh, doc/reference/index.html
This page will be automatically maintained by the `checkers` build, and
include links to the reference docs for each GA library.
Part of the work for #8682
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8683)
=> doc: create a landing page for reference docs

google/cloud/pubsub/publisher.h
Thanks to @bjackman for letting us know about the lack of documentation.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8703)
=> doc(pubsub): document publish return value

CHANGELOG.md, bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35-cxx11.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, doc/packaging.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8727)
=> chore(deps): update to grpc-1.45.2

CHANGELOG.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8735)
=> doc: announce C++11 changes

google/cloud/storage/internal/logging_client.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8741)
=> impl(storage): logging for resumable uploads

google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client_test.cc
Implement the easy functions (`CreateResumableUpload()` and
`QueryResumableUpload()`) related to resumable uploads in `RetryClient`.
Used the opportunity to clean up the unit test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8743)
=> impl(storage): start on retry for resumable uploads

google/cloud/spanner/mutations_test.cc
Add a test case for Mutation marshalling of the Spanner wrapper
types, Bytes, Date, Json, Numeric, and Timestamp, which all end
up as string values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8751)
=> test(spanner): add a MutationsTest for the Spanner types

google/cloud/pubsublite/internal/resumable_async_streaming_read_write_rpc.h, google/cloud/pubsublite/internal/resumable_async_streaming_read_write_rpc_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8760)
=> fix(pubsublite): async ordering fixes on resumable stream and lifetime of underlying stream

google/cloud/storage/internal/object_requests.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8765)
=> fix(storage): build on MSVC+x86

google/cloud/storage/internal/object_requests.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8769)
=> cleanup(storage): post merge comments

doc/contributor/howto-guide-adding-generated-libraries.md, generator/internal/scaffold_generator.cc
This was too easy to forget, and the effort is reduced to one copy/paste.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8767)
=> cleanup: copy-paste scaffolding env var command

google/cloud/spanner/samples/samples.cc
Re-order a few Spanner samples so that some upcoming additions will
slot in more sensibly.  Also adjust a few more names to align with
the conventions.  All of this is a functional no-op.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8774)
=> cleanup(spanner): re-order some samples for clarity

google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
Some renaming and other no-op changes that will make upcoming
merges cleaner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8775)
=> cleanup(spanner): cleanup instance-admin integration tests

google/cloud/logging/quickstart/BUILD.bazel, google/cloud/osconfig/quickstart/BUILD.bazel, google/cloud/speech/quickstart/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8781)
=> cleanup: heed the "this library is now GA" bazel warnings

google/cloud/pubsublite/internal/multipartition_publisher.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8791)
=> cleanup(pubsublite): explicitly use std

google/cloud/storage/tests/object_basic_crud_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8814)
=> test(storage): verify defaults for customTime attribute

external/googleapis/protodeps/storagetransfer.deps
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8817)
=> chore(deps): run external/googleapis/update_libraries.sh

google/cloud/storage/options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8825)
=> doc: fix typo, change "optional" to "optimal"

google/cloud/storage/examples/storage_client_initialization_samples.cc
Also some light formatting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8826)
=> cleanup(storage): fix sample name

google/cloud/bigtable/testing/mock_bigtable_stub.h
Part of the work for #8798
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8836)
=> impl(bigtable): mocks for streaming read rpcs

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8844)
=> doc: update CHANGELOG for v1.40.0

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8845)
=> doc: minor edits to the CHANGELOG

google/cloud/storage/tests/curl_download_request_integration_test.cc, google/cloud/storage/tests/curl_request_integration_test.cc
Make the tests for `HttpVersion` with download requests useful (it was
not setting the option).  Make both the test for `CurlRequest` and
`CurlDownloadRequest` more strict when HTTP/2 is enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8861)
=> test(storage): correct testing for `HttpVersion` option

google/cloud/bigtable/internal/data_connection.cc, google/cloud/bigtable/internal/data_connection.h, google/cloud/bigtable/internal/defaults.cc, google/cloud/bigtable/internal/defaults_test.cc, google/cloud/bigtable/options.h
Part of the work for #8798
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8867)
=> impl(bigtable): add data options

google/cloud/storage/tests/object_read_range_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8874)
=> test(storage): improve integration tests for `ReadRange()`

google/cloud/storage/tests/object_read_range_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8877)
=> test(storage): compile with MSVC+x86

google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/mutations_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8881)
=> test(spanner): additional tests for spanner::PgNumeric

google/cloud/storage/testing/storage_integration_test.cc, google/cloud/storage/testing/storage_integration_test.h, google/cloud/storage/tests/object_media_integration_test.cc
The `x-retry-test-id` is a more powerful and cleaner mechanism to
simulate failure scenarios in the storage testbench. This PR introduces
some helper functions to create test ids, and uses the function in one
test.
Motivated by #8286 and part of the work for #8886
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8888)
=> test(storage): start migration to `x-retry-test-id`

google/cloud/internal/openssl_util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8890)
=> chore: add include file

google/cloud/storage/tests/decompressive_transcoding_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8895)
=> cleanup(storage): remove some testbench workarounds

ci/cloudbuild/builds/lib/integration.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8899)
=> chore: update storage-testbench to v0.20.0

google/cloud/pubsub/samples/CMakeLists.txt
Motivated by #7197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8901)
=> cleanup(pubsub): simplify CMake file for samples

google/cloud/pubsub/samples/pubsub_samples_common.cc, google/cloud/pubsub/samples/pubsub_samples_common.h, google/cloud/pubsub/samples/samples.cc
Part of the work for #7197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8910)
=> refactor(pubsub): move helper functions to examples library

doc/adr/2022-05-06-customers-must-type-experimental-to-access-experimental-features.md
Fixes #5862
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8898)
=> doc: an ADR about experimental features

google/cloud/examples/gcs2cbt.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8913)
=> cleanup: use preferred cbt API in gcs2cbt

google/cloud/pubsub/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8918)
=> cleanup(pubsub): fix some nits

google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh, google/cloud/pubsub/google_cloud_cpp_pubsub.bzl, google/cloud/pubsub/options.cc, google/cloud/pubsub/options.h, google/cloud/pubsub/options_test.cc, google/cloud/pubsub/pubsub_client_unit_tests.bzl, google/cloud/pubsub/samples/BUILD.bazel, google/cloud/pubsub/samples/CMakeLists.txt, google/cloud/pubsub/samples/iam_samples.cc, google/cloud/pubsub/samples/pubsub_client_integration_samples.bzl
Fixes #7197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8917)
=> doc(pubsub): implement IAM examples

google/cloud/storage/internal/curl_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8925)
=> cleanup(storage): remove unused types

google/cloud/internal/curl_rest_client.cc, google/cloud/storage/internal/rest_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8927)
=> refactor(storage): refactor bucket methods to use rest library

generator/generator_config.textproto, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.h, google/cloud/storage/internal/grpc_hmac_key_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/storage_client_grpc_unit_tests.bzl, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/grpc_hmac_key_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
Fixes #4208
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8931)
=> feat(GCS+gRPC): implement `GetHmacKey()`

google/cloud/async_streaming_read_rpc.h, google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/async_streaming_read_rpc.h, google/cloud/internal/async_streaming_read_rpc_impl.h, google/cloud/internal/async_streaming_read_rpc_impl_test.cc
Part of the work for #8937 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8935)
=> impl(common): abstractions for asynchronous streaming read RPCs

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.h, google/cloud/storage/internal/grpc_hmac_key_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_hmac_key_integration_test.cc
Fixes #4209
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8939)
=> feat(GCS+gRPC): implement `DeleteHmacKey()`

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.h, google/cloud/storage/internal/grpc_hmac_key_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_hmac_key_integration_test.cc
Fixes #4207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8943)
=> feat(GCS+gRPC): implement `UpdateHmacKey`

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.h, google/cloud/storage/internal/grpc_hmac_key_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_hmac_key_integration_test.cc
Fixes #4210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8945)
=> feat(GCS+gRPC): implement `CreateHmacKey()`

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.h, google/cloud/storage/internal/grpc_hmac_key_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_hmac_key_integration_test.cc
Fixes #4211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8949)
=> feat(GCS+gRPC): implement `ListHmacKeys()`

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc, google/cloud/spanner/integration_tests/data_types_integration_test.cc, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/database_integration_test.cc
Fixes #5024.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8953)
=> cleanup(spanner): the spanner emulator now supports NUMERIC

generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc, generator/internal/metadata_decorator_generator.cc
My stub factory tests are failing without this
<hr />
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8962)
=> fix(generator): async streaming read MD respects routing header

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc
Fixes #4177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8960)
=> feat(GCS+gRPC): implement `GetBucketAcl()`

google/cloud/bigtable/admin/integration_tests/table_admin_integration_test.cc, google/cloud/bigtable/benchmarks/benchmark.cc, google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, google/cloud/bigtable/examples/bigtable_hello_app_profile.cc, google/cloud/bigtable/examples/bigtable_hello_table_admin.cc, google/cloud/bigtable/examples/bigtable_hello_world.cc, google/cloud/bigtable/examples/bigtable_table_admin_backup_snippets.cc, google/cloud/bigtable/examples/data_async_snippets.cc, google/cloud/bigtable/examples/data_filter_snippets.cc, google/cloud/bigtable/examples/data_snippets.cc, google/cloud/bigtable/examples/read_snippets.cc, google/cloud/bigtable/examples/table_admin_iam_policy_snippets.cc, google/cloud/bigtable/examples/table_admin_snippets.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8969)
=> cleanup(bigtable): better example code for GC rules

google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/internal/oauth2_service_account_credentials_test.cc, google/cloud/storage/oauth2/service_account_credentials.cc, google/cloud/storage/oauth2/service_account_credentials_test.cc
Fixes #8974
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8975)
=> fix: format multiple scopes correctly in service account assertions

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc
Fixes #4178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8978)
=> feat(GCS+gRPC): implement `DeleteBucketAcl()`

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc
Fixes #4176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8986)
=> feat(GCS+gRPC): implement `UpdateBucketAcl()`

doc/contributor/howto-guide-adding-generated-libraries.md
update how we add experimental targets.
pressure the developer into testing their quickstart.
commit the CHANGELOG changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8982)
=> doc: touch up howto add library

google/cloud/storage/bucket_access_control.h, google/cloud/storage/internal/grpc_bucket_access_control_parser.cc, google/cloud/storage/internal/grpc_bucket_access_control_parser.h, google/cloud/storage/internal/grpc_bucket_access_control_parser_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc
Fixes #4175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8989)
=> feat(GCS+gRPC): implement `PatchBucketAcl()`

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, google/cloud/asset/asset_client.cc, google/cloud/asset/asset_client.h, google/cloud/asset/asset_connection.cc, google/cloud/asset/asset_connection.h, google/cloud/asset/asset_connection_idempotency_policy.cc, google/cloud/asset/asset_connection_idempotency_policy.h, google/cloud/asset/internal/asset_auth_decorator.cc, google/cloud/asset/internal/asset_auth_decorator.h, google/cloud/asset/internal/asset_connection_impl.cc, google/cloud/asset/internal/asset_connection_impl.h, google/cloud/asset/internal/asset_logging_decorator.cc, google/cloud/asset/internal/asset_logging_decorator.h, google/cloud/asset/internal/asset_metadata_decorator.cc, google/cloud/asset/internal/asset_metadata_decorator.h, google/cloud/asset/internal/asset_stub.cc, google/cloud/asset/internal/asset_stub.h, google/cloud/asset/mocks/mock_asset_connection.h, google/cloud/bigtable/admin/bigtable_instance_admin_client.h, google/cloud/bigtable/admin/bigtable_table_admin_client.h
I am creating a "How-to Guide" for this chore, I figured I would send the PR since I did all the work already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9007)
=> chore: update googleapis SHA circa 2022-05-18

README.md, doc/contributor/README.md
Make it easier to preserve links as the code is imported into google.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9006)
=> cleanup: more import nits

doc/contributor/howto-guide-update-googleapis-sha.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9008)
=> doc: describe how to update the googleapis SHA

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc
When using DirectPath it makes little or no sense to use more than one
gRPC channel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9025)
=> feat(GCS+gRPC): adjust default channel count for DirectPath

ci/cloudbuild/builds/lib/integration.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9036)
=> chore: update storage testbench to v0.21.0

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/grpc_object_acl_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
Introducing a new integration test in this PR to host all the
`*ObjectAcl()` integration tests.
Fixes #4205
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9037)
=> feat(GCS+gRPC): implement `ListObjectAcl()`

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/grpc_object_acl_integration_test.cc
Fixes #4204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9043)
=> feat(GCS+gRPC): implement `CreateObjectAcl()`

google/cloud/spanner/client_test.cc
After #9032, setting the `EndpointOption` only has an effect when there is
no prevailing `${endpoint_env}`, which there might be if we are also running
integration tests against an alternate service.
So, remove `${endpoint_env}` (`GOOGLE_CLOUD_CPP_SPANNER_DEFAULT_ENDPOINT`
for Spanner), and `${emulator_env}` for good measure (`SPANNER_EMULATOR_HOST`),
from the environment of the relevant unit test for `MakeConnection()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9044)
=> test(spanner): check EndpointOption setting in a compatible environment

google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9045)
=> test(GCS+gRPC): simplify testing with newer testbench

google/cloud/future_coroutines_test.cc, google/cloud/internal/future_coroutines.h
And this is why we try to test every function in template classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9046)
=> fix(common): compilation error with coroutines and futures

google/cloud/storage/tests/object_insert_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9041)
=> chore(storage): add more userIp tests

google/cloud/storage/internal/grpc_client_test.cc
On Windows the default credentials are fairly slow, and we do not need
them for this unit test.
Previously:
```
//google/cloud/storage:internal_grpc_client_test                         PASSED in 234.3s
```
Now:
```
//google/cloud/storage:internal_grpc_client_test                         PASSED in 64.2s
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9050)
=> test(GCS+gRPC): speed up `GrpcClient` test

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/grpc_object_acl_integration_test.cc
Fixes #4202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9048)
=> feat(GCS+gRPC): implement `GetObjectAcl()`

google/cloud/bigtable/row_reader.cc, google/cloud/bigtable/row_reader.h, google/cloud/bigtable/row_reader_test.cc
Part of the work for #8804
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9053)
=> impl(bigtable): RowReader forwards CurrentOptions

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, google/cloud/accessapproval/access_approval_client.cc, google/cloud/accessapproval/access_approval_client.h, google/cloud/accessapproval/access_approval_connection.cc, google/cloud/accessapproval/access_approval_connection.h, google/cloud/accessapproval/access_approval_connection_idempotency_policy.cc, google/cloud/accessapproval/access_approval_connection_idempotency_policy.h, google/cloud/accessapproval/internal/access_approval_auth_decorator.cc, google/cloud/accessapproval/internal/access_approval_auth_decorator.h, google/cloud/accessapproval/internal/access_approval_connection_impl.cc, google/cloud/accessapproval/internal/access_approval_connection_impl.h, google/cloud/accessapproval/internal/access_approval_logging_decorator.cc, google/cloud/accessapproval/internal/access_approval_logging_decorator.h, google/cloud/accessapproval/internal/access_approval_metadata_decorator.cc, google/cloud/accessapproval/internal/access_approval_metadata_decorator.h, google/cloud/accessapproval/internal/access_approval_stub.cc, google/cloud/accessapproval/internal/access_approval_stub.h, google/cloud/accessapproval/mocks/mock_access_approval_connection.h, google/cloud/bigtable/admin/bigtable_instance_admin_client.h, google/cloud/bigtable/admin/bigtable_table_admin_client.h, google/cloud/iam/iam_credentials_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9066)
=> chore: update googleapis SHA circa 2022-05-25

generator/generator_config.textproto, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h
Part of the work for #7300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9071)
=> impl(GCS+gRPC): generate `AsyncReadObject()` function

google/cloud/spanner/samples/samples.cc
When selecting an `InstanceConfig` to use in the samples that create
a new `Instance`, we have some special filtering to avoid locations
where we run integration tests.  This filtering is specific to the
production Spanner service, and so should not be applied when using
an alternative like the staging service.
This allows the `spanner_create_database_with_encryption_key` sample
to run on the staging service, as its encryption key is tied to a
location whose `InstanceConfig` was previously discarded by the filter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9075)
=> test(spanner): limit special instance-config filtering to prod

cmake/GoogleCloudCppCommon.cmake
Fixes #9057
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9095)
=> doc: doxygen for `admin_mocks`

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, external/googleapis/protolists/securitycenter.list, google/cloud/securitycenter/security_center_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9116)
=> chore: update googleapis SHA circa 2022-05-31

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9122)
=> chore: update changelog for v1.41.0 release

google/cloud/internal/curl_http_payload.cc, google/cloud/internal/curl_http_payload.h, google/cloud/internal/curl_impl.h, google/cloud/internal/http_payload.h, google/cloud/testing_util/mock_http_payload.h
Necessary for refactoring GCS to use rest library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9118)
=> feat(rest): add HasUnreadData method

google/cloud/internal/curl_impl.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9126)
=> fix(rest): userIp population and multi removal

google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake, google/cloud/storage/internal/async_connection.h, google/cloud/storage/internal/async_connection_impl.cc, google/cloud/storage/internal/async_connection_impl.h, google/cloud/storage/internal/async_connection_impl_test.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl
Part of the work for #568
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9120)
=> impl(GCS+gRPC): add `*Connection` class for async client

google/cloud/storage/internal/rest_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9132)
=> refactor(storage): most of the object methods to use rest library

google/cloud/storage/client.h
Fixes #9141 and other things that are not reported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9146)
=> doc(storage): missing options for several functions

ci/cloudbuild/builds/coverage.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9147)
=> ci: coverage build includes `storage::internal::RestClient`

google/cloud/storage/internal/rest_client.cc, google/cloud/storage/internal/rest_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9145)
=> refactor(storage): insert object using rest library

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, google/cloud/retail/completion_client.h, google/cloud/retail/prediction_client.h, google/cloud/retail/product_client.h, google/cloud/retail/search_client.h, google/cloud/retail/user_event_client.h
Mostly to pickup `google::spanner::v1::Session::creator_role`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9154)
=> chore: update googleapis SHA circa 2022-06-02

google/cloud/internal/curl_impl.cc
fixes #7955
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9151)
=> impl(rest): support multi span post

google/cloud/storage/async_client.cc, google/cloud/storage/async_client.h, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/async_client_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
Fixes #9128 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9142)
=> feat(GCS+gRPC): first function for async client

google/cloud/spanner/value_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9159)
=> test(spanner): be more lenient with NaN output formatting

google/cloud/storage/internal/rest_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9158)
=> refactor(storage): use multiple spans for insert object

google/cloud/storage/internal/rest_client.cc
And move some helper functions to an anonymous namespace for internal linkage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9160)
=> refactor(storage): copy object to use rest library

doc/contributor/howto-guide-declare-a-library-ga.md, release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9153)
=> cleanup: do a pass on contributor docs

google/cloud/bigtable/table.cc, google/cloud/bigtable/table_test.cc
Fixes #8802 
I will turn on the integration tests for this client call in a subsequent PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9163)
=> impl(bigtable): `Table::BulkApply()`  with Connection

google/cloud/internal/oauth2_service_account_credentials.h, google/cloud/status.h, google/cloud/storage/oauth2/service_account_credentials.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9170)
=> chore: add some missing block-comment leaders

google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/async_streaming_write_rpc_auth.h, google/cloud/internal/async_streaming_write_rpc_auth_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9178)
=> impl(common): the Auth decorator for streaming write RPCs

google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/async_streaming_write_rpc_logging.h, google/cloud/internal/async_streaming_write_rpc_logging_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9185)
=> impl(common): the Logging decorator for streaming write RPCs

generator/generator_config.textproto, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9194)
=> impl(GCS+gRPC): generate asynchronous WriteObject in stubs

google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_options.h, google/cloud/internal/curl_rest_client.cc, google/cloud/storage/client.cc, google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/rest_client.cc, google/cloud/storage/internal/rest_client.h, google/cloud/storage/options.h, google/cloud/storage/tests/object_media_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197)
=> refactor(storage): read object to use rest library

google/cloud/bigtable/internal/async_bulk_apply.cc, google/cloud/bigtable/internal/async_row_reader.h, google/cloud/bigtable/internal/async_row_sampler.cc, google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/legacy_async_row_sampler.cc, google/cloud/bigtable/row_reader.cc, google/cloud/bigtable/table.cc, google/cloud/internal/async_read_write_stream_logging.h, google/cloud/internal/async_streaming_read_rpc_logging.h, google/cloud/internal/minimal_iam_credentials_stub.cc, google/cloud/pubsub/internal/publisher_auth.cc, google/cloud/pubsub/internal/subscriber_auth.cc, google/cloud/pubsub/internal/subscriber_logging.cc, google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/internal/spanner_auth.cc, google/cloud/storage/client.h
Fixes #9223
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9226)
=> cleanup: less copies before pass by value to lambda

google/cloud/internal/async_streaming_read_rpc_impl_test.cc, google/cloud/internal/async_streaming_write_rpc_impl_test.cc, google/cloud/storage/object_rewriter.cc, google/cloud/storage/object_rewriter.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9228)
=> cleanup: avoid some more copying of OptionsSpan

google/cloud/options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9231)
=> impl(common): make OptionsSpan uncopyable and unmovable

google/cloud/bigtable/internal/async_row_sampler_test.cc
As @scotthart pointed out, this test breaks inside google3 because of some Cord / string shenanigans. This is the same idea as #9234, but applied to the test function instead of the class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9235)
=> cleanup(bigtable): fix test for google3

google/cloud/options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9243)
=> impl(common): also make OptionsSpan unallocatable

google/cloud/storage/internal/rest_client.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9241)
=> impl(storage): use `CurrentOptions()` in `RestClient`

google/cloud/storage/client_write_object_test.cc
The unit tests did not exercise the retry path as well as they could.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9261)
=> test(storage): improve unit tests for `Client::WriteObject()`

google/cloud/storage/README.md
Fix typo in readme file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9264)
=> doc: broken link in GCS README file

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/tests/data_async_future_integration_test.cc
Fixes #9175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9267)
=> impl(bigtable): modern `Table::AsyncBulkApply()`

google/cloud/internal/rest_response.h, google/cloud/storage/client.cc, google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/rest_client.cc, google/cloud/storage/internal/rest_request_builder.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9274)
=> refactor(storage): resumable uploads to use Rest library

google/cloud/storage/internal/rest_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9275)
=> refactor(storage): acl methods to use rest library

google/cloud/storage/internal/rest_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9276)
=> refactor(storage): hmac and notification methods to use rest library

google/cloud/storage/internal/async_accumulate_read_object_test.cc, google/cloud/storage/internal/grpc_object_read_source_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9286)
=> cleanup(GCS+gRPC): duplicate mocks for `AsyncReadObject()` result

google/cloud/contactcenterinsights/README.md, google/cloud/datacatalog/README.md, google/cloud/dataplex/README.md, google/cloud/dataproc/README.md, google/cloud/dialogflow_cx/README.md, google/cloud/dialogflow_es/README.md, google/cloud/language/README.md, google/cloud/managedidentities/README.md, google/cloud/profiler/README.md, google/cloud/pubsublite/README.md, google/cloud/resourcesettings/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9295)
=> cleanup: remove "experimental" warnings on GA libraries

google/cloud/pubsublite/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9298)
=> doc: revert pubsublite README changes

doc/contributor/howto-guide-declare-a-library-ga.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9299)
=> doc: update guide to declare libraries GA

ci/kokoro/macos/builds/quickstart-cmake.sh
vcpkg can use GCS to keep its binary cache (i.e. pre-built binaries of
each package).  This cache uploads each package as it is built, which
is nice when doing a large rebuild, as the results are immediately
saved.  This is a content-based cache, and it includes the signature of
the compiler and other elements in the toolchain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9300)
=> ci(kokoro/macOS): use GCS for vcpkg binary cache

ci/install-cloud-sdk.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9311)
=> chore(deps): update gcloud to 390.0.0

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9315)
=> doc: update CHANGELOG.md pre v1.42.0

google/cloud/bigtable/table.h, google/cloud/bigtable/table_test.cc
This corrects a regression from #9272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9317)
=> cleanup(bigtable): `AsyncReadRows` accepts move-only types again

google/cloud/pubsub/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9322)
=> doc(pubsub): use the right region tags

google/cloud/spanner/samples/samples.cc
Drop some special cases that are no longer needed for recent releases
of the Spanner emulator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9321)
=> test(spanner): remove some emulator conditionals

google/cloud/spanner/integration_tests/client_integration_test.cc
The emulator will support this soon enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9341)
=> test(spanner): relax database dialect emulator expectations

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source.h, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9357)
=> impl(pubsub): handle streaming pull subscription properties

google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
Instead of relying on "long enough" timeouts use a mock completion
queue to control exactly when the timer expire (never in these tests).
Part of the work for #9327, and yes, this is the second deflake, the first one was a temporary fix to unblock other development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9369)
=> deflake(pubsub): mock completion queue to avoid unwanted timers

google/cloud/bigtable/table.h
A simple refactor motivated by #8860 
Instead of storing a `project_id`, `instance_id`, and `table_id`, we just store a `TableResource`.
Note that this accessor exists: https://github.com/googleapis/google-cloud-cpp/blob/87b0591a1f9dc32080c577953ac6ee34bacb9717/google/cloud/bigtable/table.h#L367
So we either have to store the full table name as a member in `Table` or in `TableResource`. I figured it was better to make the extra copy in `Table` instead of having `TableResource::FullName` return a `st::string const&`. Our code inside of `Table` is a little uglier this way, but that's ok.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9399)
=> refactor(bigtable): `Table` stores `TableResource`

google/cloud/internal/rest_response.cc, google/cloud/internal/rest_response.h, google/cloud/storage/internal/http_response.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9419)
=> cleanup: refactor HTTP code to StatusCode mapping

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, external/googleapis/protolists/securitycenter.list, google/cloud/container/cluster_manager_client.cc, google/cloud/container/cluster_manager_client.h, google/cloud/container/cluster_manager_connection.cc, google/cloud/container/cluster_manager_connection.h, google/cloud/container/cluster_manager_connection_idempotency_policy.cc, google/cloud/container/cluster_manager_connection_idempotency_policy.h, google/cloud/container/internal/cluster_manager_auth_decorator.cc, google/cloud/container/internal/cluster_manager_auth_decorator.h, google/cloud/container/internal/cluster_manager_connection_impl.cc, google/cloud/container/internal/cluster_manager_connection_impl.h, google/cloud/container/internal/cluster_manager_logging_decorator.cc, google/cloud/container/internal/cluster_manager_logging_decorator.h, google/cloud/container/internal/cluster_manager_metadata_decorator.cc, google/cloud/container/internal/cluster_manager_metadata_decorator.h, google/cloud/container/internal/cluster_manager_stub.cc, google/cloud/container/internal/cluster_manager_stub.h, google/cloud/container/mocks/mock_cluster_manager_connection.h, google/cloud/dialogflow_es/answer_records_client.h, google/cloud/dialogflow_es/conversation_profiles_client.h, google/cloud/securitycenter/security_center_client.h, google/cloud/spanner/admin/instance_admin_client.h, google/cloud/trace/trace_client.h
Mostly to pick up `google.spanner.admin.instance.v1.Instance.create_time`
and `.update_time`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9421)
=> chore(deps): update googleapis protos circa 2022-07-04

google/cloud/bigtable/table_test.cc, google/cloud/pubsublite/internal/default_publish_message_transformer.h, google/cloud/pubsublite/internal/service.h, google/cloud/spanner/samples/postgresql_samples.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9424)
=> cleanup: reformat some "const west" declarations

google/cloud/storage/internal/lifecycle_rule_parser.cc
ETOOMANYPRS. The changes to upgrade `clang-tidy` ran separately from the
changes to reduce complexity in storage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9429)
=> cleanup(storage): fix `clang-tidy` build

google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_client.cc
This time, I used clang-tidy to find functions with high cognitive
complexity in the gRPC plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9432)
=> cleanup(storage): more cognitive complexity reduction

google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc, google/cloud/storage/benchmarks/throughput_options.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9433)
=> cleanup(storage): final cognitive complexity reduction

ARCHITECTURE.md, CHANGELOG.md, google/cloud/bigtable/doc/bigtable-mocking.dox, google/cloud/bigtable/doc/migrating-from-dataclient.dox, google/cloud/bigtable/examples/howto_mock_data_api.cc, google/cloud/spanner/doc/spanner-mocking.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9430)
=> chore: modernize bigtable changelog update

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9439)
=> chore: update changelog for v2.0.0 release

google/cloud/pubsub/internal/defaults.cc, google/cloud/pubsub/internal/defaults_test.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/options.h
Fixes #9327
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9438)
=> feat(pubsub): add new option for exactly-once delivery

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/grpc_default_object_acl_integration_test.cc
Fixes #4183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9458)
=> feat(GCS+gRPC): implement `GetDefaultObjectAcl()`

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/grpc_default_object_acl_integration_test.cc
Fixes #4185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9465)
=> feat(GCS+gRPC): implement `CreateDefaultObjectAcl()`

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/grpc_default_object_acl_integration_test.cc
Fixes #4184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9473)
=> feat(GCS+gRPC): implement `DeleteDefaultObjectAcl()`

google/cloud/storage/internal/grpc_bucket_access_control_parser.cc, google/cloud/storage/internal/grpc_bucket_access_control_parser_test.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc, google/cloud/storage/internal/grpc_hmac_key_metadata_parser.cc, google/cloud/storage/internal/grpc_hmac_key_metadata_parser_test.cc, google/cloud/storage/internal/grpc_object_access_control_parser.cc, google/cloud/storage/internal/grpc_object_access_control_parser_test.cc, google/cloud/storage/internal/grpc_object_metadata_parser.cc, google/cloud/storage/internal/grpc_object_metadata_parser_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9472)
=> feat(GCS+gRPC): use ETag proto fields

ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9515)
=> ci: move `msan` build to Fedora:36

bazel/google_cloud_cpp_deps.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9517)
=> chore(deps): fix google/benchmark SHA256 again

generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/internal/client_generator.cc, generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils.h, google/cloud/bigquery/bigquery_write_client.h, google/cloud/dialogflow_cx/sessions_client.h, google/cloud/dialogflow_es/sessions_client.h, google/cloud/logging/logging_service_v2_client.h, google/cloud/speech/speech_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9510)
=> cleanup: document bidirectional streams

google/cloud/bigtable/README.md, google/cloud/bigtable/quickstart/quickstart.cc
Fixes #9309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9513)
=> cleanup(bigtable): use `DataConnection` in quickstart

google/cloud/storage/doc/storage-main.dox
This creates a little sidebar with the TOC:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9520)
=> doc(storage): add table of contents to landing page

google/cloud/internal/curl_rest_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9527)
=> fix(storage): remove UB in `MakePooledRestClient()`

ci/cloudbuild/triggers/coverage-ci.yaml, ci/cloudbuild/triggers/coverage-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9528)
=> ci: move coverage build to Fedora:36

google/cloud/internal/curl_rest_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9539)
=> fix(storage): remove UB in `MakePooledRestClient()` (#9527)

ci/kokoro/windows/bazel-debug-2022-presubmit.cfg, ci/kokoro/windows/bazel-debug-2022.cfg, ci/kokoro/windows/bazel-release-2022-presubmit.cfg, ci/kokoro/windows/bazel-release-2022.cfg, ci/kokoro/windows/build-32.bat, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-quickstart-bazel.ps1, ci/kokoro/windows/build.bat, ci/kokoro/windows/build.ps1
Prepare the scripts to build with MSVC 2022. Create the configuration files for
Kokoro.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9542)
=> ci: configure MSVC 2022 builds

google/cloud/internal/curl_impl.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9543)
=> impl(rest): improve write performance

ci/cloudbuild/builds/lib/integration.sh
Part of the work for #5910
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9547)
=> chore(deps): update storage testbench to v0.27.0

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9548)
=> test(spanner): use Options in the retry/backoff-policy sample

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/admin/integration_tests/backup_integration_test.cc
Fixes #8573.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9549)
=> test(spanner): RestoreDatabase() now sets database_dialect

CHANGELOG.md, release/changes.sh
Relative links respect the current branch or tag, and they are easier to
write too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9553)
=> cleanup: use relative links in CHANGELOG

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9570)
=> test(storage): control gRPC background thread count

google/cloud/internal/curl_handle_factory.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9586)
=> fix(rest): build failure with MSVC+x86

google/cloud/storage/benchmarks/throughput_experiment.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9594)
=> cleanup(storage): fix windows release build

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9597)
=> test(storage): benchmark option to disable retry loop

google/cloud/internal/oauth2_google_credentials_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9599)
=> cleanup: remove unused test code

google/cloud/internal/oauth2_google_credentials.cc
The helper functions had parameters that were effectively constant. And
we already have an `google::cloud::Options` parameter that we could
use for any configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9600)
=> cleanup: simplify `GoogleDefaultCredentials()` implementation

google/cloud/internal/unified_rest_credentials_integration_test.cc
Change the test to always issue a request that should succeed, even for
insecure credentials. Always wrap the tests with retry loops, as these
are integration tests hitting production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9612)
=> test(rest): verify the success path for insecure credentials

google/cloud/storage/internal/complex_option.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9615)
=> impl(storage): make complex options `value_or()` const

release/README.md, release/changes.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9611)
=> doc: update CHANGELOG generation

google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/internal/oauth2_service_account_credentials.h, google/cloud/internal/oauth2_service_account_credentials_test.cc, google/cloud/internal/unified_rest_credentials_integration_test.cc
Unless explicitly disabled, use self-signed JWTs for service accounts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9621)
=> impl(rest): prefer self-signed JWTs for service accounts

google/cloud/dialogflow_cx/README.md, google/cloud/dialogflow_cx/quickstart/quickstart.cc, google/cloud/dialogflow_es/README.md, google/cloud/dialogflow_es/quickstart/quickstart.cc, google/cloud/documentai/README.md, google/cloud/documentai/quickstart/quickstart.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9628)
=> cleanup: leave bread crumbs for quickstart changes after #9625

google/cloud/internal/curl_impl.cc
GCC on Ubuntu 22.04 gives me a warning:
```
google/cloud/internal/curl_impl.cc: In member function
'google::cloud::v2_2_0::StatusOr<int>
google::cloud::rest_internal::v2_2_0::CurlImpl::PerformWork()':
google/cloud/internal/curl_impl.cc:559:24: warning:
'multi_remove_result' may be used uninitialized in this function
[-Wmaybe-uninitialized]
559 |         return AsStatus(multi_remove_result, __func__);
|                ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I am not sure why we don't get an error in our CI builds. It does seem
to me that the compiler is right, so I just fixed the code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9630)
=> cleanup: fix warning about uninitialized variable

google/cloud/iam/integration_tests/iam_integration_test.cc
fixes #6475 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9634)
=> cleanup(iam): add retry loops to mitigate integration test flakes

google/cloud/storage/internal/storage_stub_factory.cc
Part of work for #8878
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9635)
=> impl(GCS+gRPC): isolate channels via local subchannel pools

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_notification_request_parser.cc, google/cloud/storage/internal/grpc_notification_request_parser.h, google/cloud/storage/internal/grpc_notification_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_notification_integration_test.cc
Fixes #4190
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9641)
=> feat(GCS+gRPC): implement `GetNotification()`

google/cloud/storage/benchmarks/aggregate_upload_throughput_benchmark.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9645)
=> test(storage): fix gRPC support in upload benchmark

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_notification_request_parser.cc, google/cloud/storage/internal/grpc_notification_request_parser.h, google/cloud/storage/internal/grpc_notification_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_notification_integration_test.cc
Fixes #4188
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9644)
=> feat(GCS+gRPC): implement `DeleteNotification()`

google/cloud/storage/internal/notification_requests.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9642)
=> doc(storage): fix comments for Notification requests

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_notification_request_parser.cc, google/cloud/storage/internal/grpc_notification_request_parser.h, google/cloud/storage/internal/grpc_notification_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_notification_integration_test.cc
Fixes #4191
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9646)
=> feat(GCS+gRPC): implement `ListNotifications()`

google/cloud/bigtable/instance_admin_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9660)
=> cleanup(bigtable): call things options instead of policies

ci/kokoro/macos/builds/cmake-vcpkg.sh, ci/kokoro/macos/builds/quickstart-cmake.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9668)
=> ci(macOS): prefer tmpfs directory for vcpkg installation

google/cloud/storage/internal/async_connection_impl.cc, google/cloud/storage/internal/async_connection_impl.h
Part of the work for #9168
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9674)
=> refactor(storage): async connection assumes call options

google/cloud/storage/benchmarks/aggregate_download_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_download_throughput_options_test.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_options_test.cc, google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9679)
=> test(storage): connection pool size option for benchmarks

google/cloud/internal/curl_rest_client.cc, google/cloud/storage/internal/rest_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9681)
=> impl(storage): always set content-length and fix LockRetentionPolicy parameters

google/cloud/pubsublite/integration_tests/publisher_integration_test.cc
In #9678, I forgot to set `topic_name_` upon initialization, so we were not deleting the topic in the test's destructor. Oops, my bad.
https://github.com/googleapis/google-cloud-cpp/blob/ad5acebb8a413baeafbb2fb9857fc2086215795e/google/cloud/pubsublite/integration_tests/publisher_integration_test.cc#L85
I noticed that most leaked topics were getting deleted, though. Turns out we will make a request like `projects/cloud-cpp-testing-resources/locations/...`, but receive a response like: `projects/123456789/locations/....`. So the string comparison to check whether a topic was stale was always coming up true. Fix this by only comparing the topic id.
- - - …
=> cleanup(pubsublite): fix integration test resource cleanup

CHANGELOG.md, ci/cloudbuild/builds/coverage.sh, google/cloud/storage/client_options.cc, google/cloud/storage/client_options_test.cc, google/cloud/storage/client_test.cc, google/cloud/storage/grpc_plugin_test.cc
Part of the work for #9659
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9680)
=> impl(storage): make RestClient http transport the default

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, google/cloud/asset/asset_client.cc, google/cloud/asset/asset_client.h, google/cloud/asset/asset_connection.cc, google/cloud/asset/asset_connection.h, google/cloud/asset/asset_connection_idempotency_policy.cc, google/cloud/asset/asset_connection_idempotency_policy.h, google/cloud/asset/internal/asset_auth_decorator.cc, google/cloud/asset/internal/asset_auth_decorator.h, google/cloud/asset/internal/asset_connection_impl.cc, google/cloud/asset/internal/asset_connection_impl.h, google/cloud/asset/internal/asset_logging_decorator.cc, google/cloud/asset/internal/asset_logging_decorator.h, google/cloud/asset/internal/asset_metadata_decorator.cc, google/cloud/asset/internal/asset_metadata_decorator.h, google/cloud/asset/internal/asset_stub.cc, google/cloud/asset/internal/asset_stub.h, google/cloud/asset/mocks/mock_asset_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9696)
=> chore: update googleapis SHA circa 2022-08-17

ci/cloudbuild/builds/checkers.sh, ci/cloudbuild/builds/generate-libraries.sh
I think this makes the work to generate new libraries easier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9697)
=> ci: refactor main.dox updates

ci/cloudbuild/builds/checkers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9701)
=> ci: fix output of checkers build

google/cloud/storage/oauth2/compute_engine_credentials.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9707)
=> impl(oauth2): refactor ComputeEngineCredentials transport

google/cloud/storage/oauth2/google_application_default_credentials_file.cc, google/cloud/storage/oauth2/google_application_default_credentials_file.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9708)
=> impl(oauth2): refactor application credentials file

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9711)
=> cleanup: delete end-of-line whitespace

.github/ISSUE_TEMPLATE/internal-cleanup.md, ci/cloudbuild/dockerfiles/demo-alpine-stable.Dockerfile, ci/generate-markdown/generate-packaging.sh, doc/packaging.md
1. Add some text to the body of the "internal-cleanup" issue template.
2. Wrap some "demo-alpine-stable" recipes with bash code highlighting.
Also adjust some nearby text that I happened to notice.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9713)
=> doc: tweak some markdown structure prior to auto formatting

google/cloud/storage/oauth2/google_application_default_credentials_file.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9716)
=> impl(oauth2): finish refactoring credentials file

google/cloud/internal/oauth2_refreshing_credentials_wrapper.h, google/cloud/storage/oauth2/refreshing_credentials_wrapper.cc, google/cloud/storage/oauth2/refreshing_credentials_wrapper.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9717)
=> impl(oauth2): refactor RefreshingCredentialsWrapper

google/cloud/baremetalsolution/quickstart/BUILD.bazel, google/cloud/beyondcorp/quickstart/BUILD.bazel, google/cloud/optimization/quickstart/BUILD.bazel, google/cloud/run/quickstart/BUILD.bazel, google/cloud/video/quickstart/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9720)
=> cleanup: remove use of deprecated targets for GAd libraries

CHANGELOG.md, README.md, ci/generate-markdown/generate-packaging.sh, ci/generate-markdown/update-library-readme.sh, doc/contributor/howto-guide-setup-cmake-environment.md, google/cloud/bigtable/README.md, google/cloud/spanner/benchmarks/README.md, google/cloud/storage/quickstart/README.md
Also adjust some additional formatting to match `mdformat` conventions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9725)
=> doc: fix some broken links exposed by the use of mdformat

release/changes.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9726)
=> doc: generate CHANGELOG messages with mdformat-compatible lists

google/cloud/storage/internal/async_accumulate_read_object.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9731)
=> impl(GCS+gRPC): prepare code for import into google

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, google/cloud/accessapproval/access_approval_client.h
Primarily to pick up `google.spanner.v1.TypeAnnotationCode.PG_JSONB`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9737)
=> chore: update googleapis SHA circa 2022-08-26

google/cloud/storage/oauth2/service_account_credentials.cc, google/cloud/storage/oauth2/service_account_credentials.h, google/cloud/storage/oauth2/service_account_credentials_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9736)
=> impl(oauth2): refactor ServiceAccountCredentials

ci/cloudbuild/builds/lib/integration.sh, google/cloud/storage/internal/unified_rest_credentials.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9743)
=> impl(oauth2): switch default OAuth2 credentials transport to REST

google/cloud/storage/internal/grpc_client.cc
The client library only needs to send the upload id on the first
`Write()` call of the `WriteObject()` streaming RPC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9745)
=> impl(GCS+gRPC): avoid redundant upload ids

google/cloud/storage/internal/grpc_client_failures_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9749)
=> test(GCS+gRPC): cleanup test as all functions are implemented

google/cloud/bigquery/integration_tests/bigquery_read_integration_test.cc
fixes #9728
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9752)
=> cleanup(flake): add retry loop to mitigate flakiness

google/cloud/storage/tests/object_file_multi_threaded_test.cc
Fixes #9762
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9764)
=> cleanup(storage): deflake integration test

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9763)
=> doc: update CHANGELOG for v2.2.0 release

google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
… check
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9767)
=> test(spanner): remove unneeded check

generator/generator_config.textproto, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9775)
=> impl(GCS+gRPC): enable AsyncStartResumableWrite

google/cloud/storage/async_client.h, google/cloud/storage/internal/async_connection.h, google/cloud/storage/internal/async_connection_impl.cc, google/cloud/storage/internal/async_connection_impl.h
Motivated by #9134
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9776)
=> cleanup(GCS+gRPC): reduce copies in `AsyncClient`

google/cloud/storage/tests/object_read_range_integration_test.cc
Fixes #9058
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9779)
=> cleanup(GCS+gRPC): remove workaround in test

google/cloud/storage/async_client.h, google/cloud/storage/internal/async_connection.h, google/cloud/storage/internal/async_connection_impl.cc, google/cloud/storage/internal/async_connection_impl.h, google/cloud/storage/tests/async_client_integration_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9777)
=> impl(GCS+gRPC): add `AsyncClient::StartResumableUpload()`

generator/generator_config.textproto, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9783)
=> impl(GCS+gRPC): enable `AsyncQueryResumableWrite()`

google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9785)
=> fix(GCS+gRPC): support resets in `BucketPatchBuilder`

google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9787)
=> fix(GCS+gRPC): support resets in `ObjectPatchBuilder`

README.md
Fixes #6685
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9816)
=> doc: add note about minimum Bazel

google/cloud/videointelligence/CMakeLists.txt
Motivated by #9814
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9822)
=> ci: disable flaky `videointelligence` quickstart

google/cloud/storage/testing/random_names.cc
Fixes #9106
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9821)
=> test(storage): deflake very rare errors

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, external/googleapis/protolists/bigquery.list, external/googleapis/protolists/websecurityscanner.list, google/cloud/bigquery/bigquery_write_client.h, google/cloud/dlp/dlp_client.h, google/cloud/storagetransfer/internal/storage_transfer_auth_decorator.cc, google/cloud/storagetransfer/internal/storage_transfer_auth_decorator.h, google/cloud/storagetransfer/internal/storage_transfer_connection_impl.cc, google/cloud/storagetransfer/internal/storage_transfer_connection_impl.h, google/cloud/storagetransfer/internal/storage_transfer_logging_decorator.cc, google/cloud/storagetransfer/internal/storage_transfer_logging_decorator.h, google/cloud/storagetransfer/internal/storage_transfer_metadata_decorator.cc, google/cloud/storagetransfer/internal/storage_transfer_metadata_decorator.h, google/cloud/storagetransfer/internal/storage_transfer_stub.cc, google/cloud/storagetransfer/internal/storage_transfer_stub.h, google/cloud/storagetransfer/mocks/mock_storage_transfer_connection.h, google/cloud/storagetransfer/storage_transfer_client.cc, google/cloud/storagetransfer/storage_transfer_client.h, google/cloud/storagetransfer/storage_transfer_connection.cc, google/cloud/storagetransfer/storage_transfer_connection.h, google/cloud/storagetransfer/storage_transfer_connection_idempotency_policy.cc, google/cloud/storagetransfer/storage_transfer_connection_idempotency_policy.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9826)
=> chore: update googleapis SHA circa 2022-09-12

.github/renovate.json
AFAIK, we cannot validate these before merging them.
Fixes #8297
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9846)
=> chore: fix typo in renovate configuration

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9861)
=> doc: update CHANGELOG for v2.2.1

CHANGELOG.md, bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35-cxx11.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, doc/packaging.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9863)
=> chore(deps): update protobuf to v21.6

ci/kokoro/windows/build-32.bat, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-quickstart-bazel.ps1, ci/kokoro/windows/build.bat
Part of the work for #9591 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9871)
=> ci: prepare for windows moves

ci/check-include-guards.gawk, generator/generator_config.textproto, google/cloud/spanner/doc/spanner-mocking.dox, google/cloud/storage/doc/storage-main.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9877)
=> cleanup: squash some multi-blank-line separators

ci/kokoro/lib/vcpkg.sh
Fixes #9879
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9880)
=> ci: cleanup vcpkg cache path

ci/kokoro/windows/build-32.bat, ci/kokoro/windows/build-cmake-dependencies.ps1, ci/kokoro/windows/build-cmake.ps1, ci/kokoro/windows/build-quickstart-cmake.ps1, ci/kokoro/windows/build.bat, ci/kokoro/windows/build.ps1, ci/kokoro/windows/lib/vcpkg-cache.ps1
Part of the work for #9591
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9878)
=> ci: use GCS cache for vcpkg on Kokoro+Windows

google/cloud/internal/type_list.h, google/cloud/storage/parallel_upload.h
fixes #8630
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9885)
=> impl(storage): static_assert to check Options for ParallelUploadFile

ci/cloudbuild/builds/gcs-grpc.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9888)
=> ci: disable production GCS+gRPC metadata integration tests

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9894)
=> doc: remove obsolete note about change in language standard

ci/kokoro/windows/builds/bazel.ps1, ci/kokoro/windows/builds/quickstart-bazel.ps1, ci/kokoro/windows/lib/bazel.ps1
Part of the work for #9891
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9901)
=> ci: restore some windows + quickstart builds

google/cloud/internal/async_connection_ready.cc, google/cloud/internal/async_connection_ready.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_stub_factory.cc, google/cloud/storage/internal/storage_stub_factory.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9905)
=> impl(GCS+gRPC): automatically refresh gRPC channels

ci/kokoro/windows/lib/bazel.ps1
Fixes #9531
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9924)
=> ci: enable MSVC 2017 + Release build

google/cloud/spanner/internal/status_utils_test.cc
Also test that a `Status` with a session `ResourceInfo` payload, but without "Session not found" in its message, is identified by `IsSessionNotFound()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9939)
=> test(spanner): additional test for IsSessionNotFound

ci/kokoro/windows/builds/quickstart-bazel.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9940)
=> ci: improve Bazel filter for Windows quickstart

ci/kokoro/windows/builds/quickstart-cmake.ps1
Fixes #9915
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9944)
=> ci: fewer workarounds on Windows+CMake quickstarts

google/cloud/storage/internal/grpc_service_account_parser.cc, google/cloud/storage/internal/service_account_parser.cc, google/cloud/storage/service_account.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9945)
=> cleanup(storage): easier mocking for `ServiceAccount`

google/cloud/storage/internal/lifecycle_rule_parser.cc, google/cloud/storage/lifecycle_rule.h
It is good for humans to have many friends. Classes should have as few as possible.
Motivated by #8929, but not needed to complete that work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9946)
=> cleanup(storage): remove unneeded `friend`

google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_name.cc, google/cloud/storage/internal/grpc_bucket_name.h, google/cloud/storage/internal/grpc_bucket_name_test.cc, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_notification_metadata_parser.cc, google/cloud/storage/internal/grpc_notification_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9960)
=> cleanup(GCS+gRPC): bucket name helpers to `storage_internal`

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9963)
=> chore: update changelog for v2.3.0

google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/error_parsing_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
Part of the work for #9947 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9968)
=> test(storage): verify error info is parsed correctly

google/cloud/storage/internal/retry_client.cc
Motivated by #9947
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9970)
=> refactor(storage): use retry loop helpers

google/cloud/bigtable/internal/defaults.cc
I want to add an if statement that puts us over the cognitive complexity limit.... so do a minor refactor first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9977)
=> refactor(bigtable): further reduce cognitive complexity

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h
Some small amount of refactoring. I think it will make my next changes easier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9983)
=> refactor(GCS+gRPC): move common code to helpers

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h
Part of the work for #9900
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9984)
=> impl(GCS+gRPC): avoid translating from proto

google/cloud/storage/internal/grpc_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9987)
=> cleanup(GCS+gRPC): remove unused function

ci/cloudbuild/builds/lib/integration.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9989)
=> chore(deps): update storage-testbench

.typos.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10002)
=> chore: add resourcemanager to typos

google/cloud/grpc_options.h
Fixes #8906
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10000)
=> doc: document when GrpcNumChannelsOption applies

google/cloud/storage/bucket_cors_entry_test.cc, google/cloud/storage/bucket_iam_configuration_test.cc, google/cloud/storage/google_cloud_cpp_storage.cmake, google/cloud/storage/storage_client_unit_tests.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10005)
=> test(storage): minor coverage improvements

google/cloud/storage/testing/storage_integration_test.cc, google/cloud/storage/tests/object_file_integration_test.cc, google/cloud/storage/tests/object_file_multi_threaded_test.cc
Avoid writing to the working directory, even in integration tests. This will let us run the integration tests in more restrictive CI systems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10014)
=> test(storage): use `::testing::TempDir()` for test files

google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc, google/cloud/storage/tests/grpc_default_object_acl_integration_test.cc, google/cloud/storage/tests/grpc_hmac_key_integration_test.cc, google/cloud/storage/tests/grpc_integration_test.cc, google/cloud/storage/tests/grpc_notification_integration_test.cc, google/cloud/storage/tests/grpc_object_acl_integration_test.cc, google/cloud/storage/tests/grpc_object_media_integration_test.cc, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc, google/cloud/storage/tests/grpc_service_account_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10013)
=> test(GCS+gRPC): simplify integration test

google/cloud/container/README.md, google/cloud/container/quickstart/quickstart.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10027)
=> cleanup(container): optimization nit in quickstart

BUILD.bazel, google/cloud/baremetalsolution/config.cmake.in, google/cloud/baremetalsolution/quickstart/CMakeLists.txt, google/cloud/beyondcorp/config.cmake.in, google/cloud/beyondcorp/quickstart/CMakeLists.txt, google/cloud/optimization/config.cmake.in, google/cloud/optimization/quickstart/CMakeLists.txt, google/cloud/osconfig/config.cmake.in, google/cloud/osconfig/quickstart/CMakeLists.txt, google/cloud/run/config.cmake.in, google/cloud/run/quickstart/CMakeLists.txt, google/cloud/video/config.cmake.in, google/cloud/video/quickstart/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10042)
=> cleanup: finish GA transition for several libraries

ci/cloudbuild/notifiers/logs/function/generate_svg_badge.cc, google/cloud/internal/binary_data_as_debug_string.cc, google/cloud/internal/curl_wrappers.cc, google/cloud/internal/rest_context.cc, google/cloud/pubsublite/endpoint.cc, google/cloud/spanner/numeric.cc, google/cloud/storage/internal/generate_message_boundary_test.cc, google/cloud/storage/internal/signed_url_requests.cc, google/cloud/testing_util/command_line_parsing.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10041)
=> cleanup: `<cctype>` functions and `unsigned char`

google/cloud/batch/quickstart/BUILD.bazel
See #10044.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10056)
=> cleanup(batch): the Cloud Batch service is now GA

ci/kokoro/windows/builds/quickstart-bazel.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10068)
=> ci(batch): temporarily suppress building the batch quickstart on Windows

google/cloud/bigtable/mutation_batcher.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10087)
=> cleanup(bigtable): simplify with lambda

google/cloud/bigtable/mutation_batcher_test.cc
Simplify the `MutationBatcher` test by using a `Table` constructed with `DataConnection` instead of `DataClient`. (The `MutationBatcher` accepts a `Table`. It does not care what the substrate is. The different substrates are tested elsewhere. We should use the better one here.)
I tried to make the diff as inoffensive as possible. For the reviewer:
* `ResultPiece` had three parts to it: successes, transient failures, permanent failures. That is reduced to just: failures.
* I found the curly braces hard to parse, so I made the `Exchange`s explicit.
* The last test was removed because the callback now runs synchronously in all of the tests.
* I wish we could remove [this hook](https://github.com/googleapis/google-cloud-cpp/blob/536bbc7ff1ec23b07d24c239c14096be1a0acf57/google/cloud/bigtable/mu …
=> cleanup(bigtable): use `DataConnection` for mocking

generator/generator_config.textproto, google/cloud/pubsub/internal/subscriber_auth_decorator.cc, google/cloud/pubsub/internal/subscriber_auth_decorator.h, google/cloud/pubsub/internal/subscriber_logging_decorator.cc, google/cloud/pubsub/internal/subscriber_logging_decorator.h, google/cloud/pubsub/internal/subscriber_metadata_decorator.cc, google/cloud/pubsub/internal/subscriber_metadata_decorator.h, google/cloud/pubsub/internal/subscriber_round_robin_decorator.cc, google/cloud/pubsub/internal/subscriber_round_robin_decorator.h, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h, google/cloud/pubsub/testing/mock_subscriber_stub.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10092)
=> impl(pubsub): generate code for `Pull()` RPC

google/cloud/iam/integration_tests/iam_integration_test.cc
fixes #9904 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10091)
=> chore(iam): add retry to flaky integration test

generator/integration_tests/golden/internal/golden_kitchen_sink_round_robin_decorator.cc, generator/integration_tests/golden/internal/golden_thing_admin_round_robin_decorator.cc, generator/internal/round_robin_decorator_generator.cc, google/cloud/pubsub/internal/publisher_round_robin_decorator.cc, google/cloud/pubsub/internal/subscriber_round_robin_decorator.cc
Thanks to @devbww for the suggestion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10093)
=> feat(generator): optimize round-robin decorators

google/cloud/doc/guac.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10111)
=> doc(common): several fixes from a post-merge review

google/cloud/iam/doc/main.dox
Part of the work for #10114 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10116)
=> refactor(iam): normalize Doxygen landing page

bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cxx14.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, doc/packaging.md
Reverts googleapis/google-cloud-cpp#10112
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10119)
=> Revert "chore(deps): update grpc to v1.50.1"

examples/grpc_credential_types.cc
Switch from `ListInstances()` to `ListInstanceConfigs()` so that we might observe the effect in the "cloud_apis" data collection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10120)
=> chore: change Spanner instance admin call used by example

ci/cloudbuild/builds/checkers.sh, ci/generate-markdown/update-library-landing-dox.sh
I am planning to add more update steps to the `main.dox` files, it was getting too messy as inline code.
Part of the work for #10114 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10113)
=> ci: refactor main.dox updater to a script

google/cloud/mocks/mock_stream_range.h, google/cloud/stream_range.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10122)
=> doc: mocks library / StreamRange

ci/cloudbuild/builds/checkers.sh, google/cloud/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10123)
=> ci: fix CMakeLists.txt formatting

ci/cloudbuild/build.sh, ci/cloudbuild/builds/generate-libraries.sh, ci/cloudbuild/cloudbuild.yaml
Quality of life improvement for doing generator development.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10150)
=> chore(generator): add env var to reduce scope of generate-libraries build

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10158)
=> chore: update changelog for v2.4.0

ci/generate-markdown/generate-readme.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10159)
=> doc: add internal to generate README filter

generator/internal/predicate_utils_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10164)
=> impl(generator): simplify test name

generator/generator_config.proto, generator/standalone_main.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10166)
=> impl(generator): add rest transport option

generator/internal/descriptor_utils_test.cc
Motivated by #10169 
This will be useful to check that we do not include repeated message signatures. Verify that a method key is not present in the `VarsDictionary`. Start with the two deprecated functions in the unit test.
https://github.com/googleapis/google-cloud-cpp/blob/f3d08b736565af0d5bef916c8134b52c77a579a4/generator/internal/descriptor_utils_test.cc#L455-L463
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10178)
=> test(generator): check for absence of method var keys

ci/cloudbuild/builds/coverage.sh
Part of the work for #6952
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10188)
=> ci: deflake (probably) the coverage builds

generator/internal/descriptor_utils_test.cc
Mostly reverts #10178.
At the time, I didn't notice there was a dedicated test for the absence of deprecated method signature keys.
Keep the gMock-isms (`Contains`,`Pair`) from the earlier PR, though.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10185)
=> cleanup: simplify method vars test

generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10213)
=> cleanup(generator): fix some nits in the generator output

ci/kokoro/windows/builds/quickstart-cmake.ps1
Fixes #9914
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10227)
=> ci: enable more libraries in Windows+CMake+Quickstart build

generator/integration_tests/tests/mock_golden_kitchen_sink_rest_stub.h, generator/integration_tests/tests/mock_golden_thing_admin_rest_stub.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10232)
=> impl(generator): add mock rest stubs

google/cloud/rest_options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10243)
=> impl(rest): make Option names consistent

ci/kokoro/windows/lib/bazel.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10248)
=> ci: move Windows+Bazel root to tmpfs volume

google/cloud/doc/options.dox, google/cloud/rest_options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10249)
=> doc(rest): add rest-options group

ci/kokoro/windows/builds/quickstart-bazel.ps1, ci/kokoro/windows/builds/quickstart-cmake.ps1
Fixes #10067.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10257)
=> cleanup(batch): remove suppression of quickstart on Windows

doc/adr/2022-11-16-option-precedence-hierarchy.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10262)
=> doc(adr): add ADR regarding Option reconciliation

google/cloud/pubsublite/internal/futures.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10276)
=> cleanup(pubsublite): internal typo

cmake/GoogleCloudCppCommon.cmake
The effect of this PR is to generate docs for `speech_v2::*` + `vmwareengine_v1::*` types.
See: [speech.pdf](https://github.com/googleapis/google-cloud-cpp/files/10048140/speech.pdf)
<hr />
We achieve this by telling doxygen to look recursively through the libraries (i.e. things that are not `google/cloud`). For `google/cloud`, we manually list the subdirectories doxygen should consider.
This reverts some of #7596, but keeps the important simplification that we don't enumerate the 90 libraries patterns to exclude from the `google/cloud` documentation include path.
<hr />
**Alternatives Considered:**
(I considered turning off recursion for all handwritten libraries. But I think it is cleaner to just exclude patterns like `*/testing/*`. We would have a problem if `googleapis` puts something …
=> cleanup: doxygen is recursive in libraries (again)

google/cloud/internal/make_status.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10286)
=> impl(common): modifiers for `ErrorInfoBuilder` lvalues

generator/integration_tests/golden/internal/golden_kitchen_sink_rest_stub.cc, generator/integration_tests/golden/internal/golden_thing_admin_rest_stub.cc, generator/internal/stub_rest_generator.cc
fixes #10214
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10273)
=> impl(generator): refactor generated rest stub to use EndpointOption

ci/cloudbuild/dockerfiles/fedora-36-cmake.Dockerfile
Part of the work for #10283
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10292)
=> ci: install otel in cmake fedora builds

WORKSPACE.bazel, bazel/google_cloud_cpp_deps.bzl
Part of the work for #10283
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10294)
=> impl(otel): bazel loads OpenTelemetry

.github/renovate.json
Part of the work for #10283
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10306)
=> chore: group some deps in renovate bot configuration

.github/renovate.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10311)
=> cleanup: address post-merge comments

CMakeLists.txt
lets us build with just `-DGOOGLE_CLOUD_CPP_ENABLE="generator"`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10335)
=> cleanup(generator): generator needs rest library

ci/kokoro/windows/builds/quickstart-bazel.ps1
Part of the work for #10208
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10351)
=> ci: enable `beyondcorp` quickstart on Windows

generator/integration_tests/tests/golden_kitchen_sink_rest_stub_test.cc, generator/integration_tests/tests/golden_thing_admin_rest_stub_test.cc, google/cloud/internal/curl_http_payload_test.cc, google/cloud/internal/external_account_token_source_url_test.cc, google/cloud/internal/oauth2_authorized_user_credentials_test.cc, google/cloud/internal/oauth2_compute_engine_credentials_test.cc, google/cloud/internal/oauth2_external_account_credentials_test.cc, google/cloud/internal/oauth2_minimal_iam_credentials_rest_test.cc, google/cloud/internal/oauth2_service_account_credentials_test.cc, google/cloud/internal/rest_response_test.cc, google/cloud/internal/rest_stub_helpers_test.cc, google/cloud/storage/internal/rest_object_read_source_test.cc, google/cloud/testing_util/mock_http_payload.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10343)
=> refactor: use helper to mock `oauth2_internal::HttpPayload`

ci/cloudbuild/builds/check-api.sh
This will unblock future googleapis SHA updates.
Here is an example of a failed `check-api` build:
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/b815c373-d930-44db-bc1d-fe5443e66735;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/10358/6c38859de975e74e9a540fca8a3706d699d2339e/fedora-36-cmake-check-api/log-b815c373-d930-44db-bc1d-fe5443e66735.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10359)
=> ci: check-api skips gRPC stubs

google/cloud/speech/BUILD.bazel
See #10338
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10371)
=> cleanup(speech): conform to new BUILD convention

ci/cloudbuild/builds/gcs-grpc.sh
Related to #10379
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10380)
=> ci: disable GCS+gRPC tests against production

google/cloud/storage/internal/unified_rest_credentials.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10384)
=> cleanup(storage): remove unused code

google/cloud/internal/unified_rest_credentials.cc, google/cloud/storage/internal/unified_rest_credentials.cc
These changes will be more useful with the addition of external accounts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10390)
=> cleanup: simplify some credentials mapping

CHANGELOG.md, google/cloud/iam/CMakeLists.txt
Also fixed a typo in the CMake file comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10401)
=> doc(iam): mention IAM v2 in the CHANGELOG

ci/cloudbuild/builds/gcs-grpc.sh
Fixes #10379
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10402)
=> ci: restore GCS+gRPC integration tests

google/cloud/pubsub/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10403)
=> doc(pubsub): add region tags for `Pull()` example

google/cloud/pubsub/samples/samples.cc
I used the wrong tag in the previous PR
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10405)
=> doc(pubsub): wrong region tag

ci/cloudbuild/dockerfiles/fedora-36-cxx14.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cxx20.Dockerfile
This should have been done as part of #10283
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10414)
=> ci(otel): test with min/max C++ standard

google/cloud/internal/compute_engine_util.cc, google/cloud/internal/compute_engine_util.h, google/cloud/internal/oauth2_compute_engine_credentials.cc, google/cloud/internal/oauth2_compute_engine_credentials.h, google/cloud/internal/oauth2_compute_engine_credentials_test.cc, google/cloud/internal/oauth2_google_credentials.cc, google/cloud/storage/oauth2/compute_engine_credentials.cc, google/cloud/storage/oauth2/compute_engine_credentials.h
Part of the work for #10419
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10423)
=> impl(oauth2): client factory for `ComputeEngineCredentials`

google/cloud/internal/oauth2_authorized_user_credentials.cc, google/cloud/internal/oauth2_authorized_user_credentials.h, google/cloud/internal/oauth2_authorized_user_credentials_test.cc, google/cloud/internal/oauth2_google_credentials.cc, google/cloud/storage/oauth2/authorized_user_credentials.cc, google/cloud/storage/oauth2/authorized_user_credentials.h
Part of the work for #10419
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10422)
=> impl(oauth2): client factory in `AuthorizedUserCredentials`

ci/etc/oldest-deps/vcpkg.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10424)
=> chore: update googletest in `cmake-oldest-deps` builds

google/cloud/internal/external_account_token_source_url.cc, google/cloud/internal/oauth2_external_account_credentials.cc, google/cloud/internal/oauth2_external_account_credentials_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10429)
=> impl(oauth2): propagate `Options` in external accounts

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/integration_tests/client_integration_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/database_integration_test.cc
Simply mark the emulator conditionals with a bread crumb.
Closes #5048, closes #5479, and closes #7144.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10446)
=> cleanup(spanner): do not track missing emulator features individually

google/cloud/internal/oauth2_external_account_credentials.cc, google/cloud/internal/oauth2_external_account_credentials_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10459)
=> impl(oauth2): support AWS external accounts

google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h, google/cloud/internal/curl_impl_test.cc
Eliminate "shift down" logic in the spill buffer and WriteVector.  While this probably doesn't make a measurable difference ...
```
//google/cloud:internal_curl_rest_client_integration_test
old over 100 runs: max = 5.0s, min = 2.6s, avg = 4.6s, dev = 0.3s
new over 100 runs: max = 5.0s, min = 2.3s, avg = 4.6s, dev = 0.4s
```
..., removing redundant copying is always a good thing.  Fixes #7958.
Move the spill buffer code into its own class so that it might be tested individually.
Initialize `download_stall_minimum_rate_` (from its option) instead of overwriting `transfer_stall_minimum_rate_`.
Do not store an entire `Options` object when we only need the value of the `CurlFollowLocationOption`.
Close #8059 by commenting on how the libcurl API does not support data buffers owned by the …
=> impl(rest): make the CurlImpl spill buffer circular

google/cloud/speech/CMakeLists.txt, google/cloud/texttospeech/CMakeLists.txt, google/cloud/trace/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10486)
=> fix: remove duplicate protos

google/cloud/spanner/bytes.h, google/cloud/spanner/json.h, google/cloud/spanner/numeric.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10502)
=> doc(spanner): fix Doxygen group names

google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc, google/cloud/bigtable/benchmarks/benchmark.h, google/cloud/bigtable/benchmarks/constants.h, google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc, google/cloud/bigtable/column_family.h, google/cloud/bigtable/data_client.h, google/cloud/bigtable/filters.h, google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/instance_config.h, google/cloud/bigtable/instance_resource.h, google/cloud/bigtable/instance_update_config.h, google/cloud/bigtable/internal/common_client.h, google/cloud/bigtable/internal/google_bytes_traits.h, google/cloud/bigtable/mutations.h, google/cloud/bigtable/row_range.h, google/cloud/bigtable/table.h, google/cloud/bigtable/table_admin.h, google/cloud/bigtable/table_config.h, google/cloud/bigtable/table_resource.h, google/cloud/bigtable/testing/inprocess_data_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10505)
=> doc(bigtable): use real Doxygen groups

google/cloud/pubsub/message.h, google/cloud/pubsub/schema.h, google/cloud/pubsub/snapshot.h, google/cloud/pubsub/subscription.h, google/cloud/pubsub/subscription_builder.h, google/cloud/pubsub/topic.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10506)
=> doc(pubsub): use real Doxygen groups

google/cloud/storage/bucket_cors_entry.h, google/cloud/storage/bucket_custom_placement_config.h, google/cloud/storage/bucket_iam_configuration.h, google/cloud/storage/client_options.h, google/cloud/storage/idempotency_policy.h, google/cloud/storage/internal/access_control_common.h, google/cloud/storage/internal/hmac_key_requests.h, google/cloud/storage/internal/object_metadata_parser.h, google/cloud/storage/internal/patch_builder.h, google/cloud/storage/internal/raw_client.h, google/cloud/storage/notification_metadata.h, google/cloud/storage/object_read_stream.h, google/cloud/storage/object_write_stream.h, google/cloud/storage/policy_document.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10507)
=> doc(storage): use real Doxygen groups

.bazelignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10514)
=> chore: ignore more directories

google/cloud/google_cloud_cpp_common.bzl, google/cloud/google_cloud_cpp_common.cmake, google/cloud/google_cloud_cpp_common_unit_tests.bzl, google/cloud/internal/timer_queue.cc, google/cloud/internal/timer_queue.h, google/cloud/internal/timer_queue_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10499)
=> impl: add TimerQueue

google/cloud/internal/timer_queue_test.cc
Fixes #10524
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10525)
=> fix(common): deflake timer_queue_test

.cmake-format.py, cmake/GoogleCloudCppDoxygen.cmake
I think this will make additional changes to support XML output more readable. I am also planning to reduce the number of arguments passed via global variables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10527)
=> refactor: use CMake functions for Doxygen

ci/kokoro/windows/builds/quickstart-cmake.ps1, google/cloud/storage/doc/environment-variables.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10534)
=> cleanup: remove some trailing whitespace

google/cloud/pubsub/README.md, google/cloud/pubsub/doc/environment-variables.dox, google/cloud/pubsub/doc/error-handling.dox, google/cloud/pubsub/doc/pubsub-main.dox, google/cloud/pubsub/quickstart/quickstart.cc
Part of the work for #10157
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10536)
=> doc(pubsub): declutter landing pages

google/cloud/internal/timer_queue.cc, google/cloud/internal/timer_queue.h, google/cloud/internal/timer_queue_test.cc
Fixes #10522. Fixes #10512. Fixes #10521.  Probably introduces new bugs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10528)
=> impl(common): use leader/followers in `TimerQueue`

google/cloud/bigtable/examples/bigtable_grpc_credentials.cc, google/cloud/bigtable/examples/bigtable_hello_app_profile.cc, google/cloud/bigtable/examples/bigtable_hello_instance_admin.cc, google/cloud/bigtable/examples/bigtable_hello_table_admin.cc, google/cloud/bigtable/examples/bigtable_hello_world.cc, google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc, google/cloud/bigtable/examples/bigtable_table_admin_backup_snippets.cc, google/cloud/bigtable/examples/data_async_snippets.cc, google/cloud/bigtable/examples/data_filter_snippets.cc, google/cloud/bigtable/examples/data_snippets.cc, google/cloud/bigtable/examples/read_snippets.cc, google/cloud/bigtable/examples/table_admin_iam_policy_snippets.cc, google/cloud/bigtable/examples/table_admin_snippets.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10546)
=> cleanup(bigtable): examples throw full `Status`

examples/grpc_credential_types.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10548)
=> cleanup(common): examples throw full `Status`

google/cloud/pubsub/samples/iam_samples.cc, google/cloud/pubsub/samples/samples.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10551)
=> cleanup(pubsub): samples throw full `Status`

google/cloud/iam/samples/iam_credentials_samples.cc, google/cloud/iam/samples/iam_samples.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10550)
=> cleanup(iam): samples throw full `Status`

google/cloud/bigquery/samples/bigquery_read_samples.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10549)
=> cleanup(bigquery): samples throw full `Status`

google/cloud/spanner/README.md, google/cloud/spanner/doc/environment-variables.dox, google/cloud/spanner/doc/error-handler.dox, google/cloud/spanner/doc/spanner-main.dox, google/cloud/spanner/quickstart/quickstart.cc
Part of the work for #10157
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10552)
=> doc(spanner): declutter landing pages

google/cloud/internal/rest_completion_queue_impl.cc, google/cloud/internal/timer_queue.cc, google/cloud/internal/timer_queue.h, google/cloud/internal/timer_queue_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10544)
=> impl(common): TimerQueue supports per-timer cancellation

google/cloud/internal/rest_completion_queue_impl.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10556)
=> impl(common): lack of std::chrono::ceil workaround

google/cloud/google_cloud_cpp_rest_protobuf_internal.bzl, google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake, google/cloud/google_cloud_cpp_rest_protobuf_internal_unit_tests.bzl, google/cloud/internal/rest_background_threads_impl.cc, google/cloud/internal/rest_background_threads_impl.h, google/cloud/internal/rest_background_threads_impl_test.cc
REST version of background threads using a RestCompletionQueueImpl.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10565)
=> impl(rest): rest background threads

doc/contributor/howto-guide-forks-and-pull-requests.md, google/cloud/bigtable/benchmarks/scan_throughput_benchmark.cc, google/cloud/bigtable/internal/unary_client_utils.h, google/cloud/bigtable/tools/convert_acceptance_tests.py, google/cloud/internal/async_read_stream_impl.h, google/cloud/internal/curl_wrappers_locking_already_present_test.cc, google/cloud/internal/oauth2_google_credentials.h, google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/commit_options.h, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/query_options.h, google/cloud/spanner/row.h, google/cloud/storage/client.h, google/cloud/storage/oauth2/google_credentials.h, google/cloud/storage/oauth2/google_credentials_test.cc, google/cloud/storage/policy_document.h, google/cloud/storage/tests/bucket_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10569)
=> doc: cleanup 'the the' typos

google/cloud/internal/timer_queue.cc, google/cloud/internal/timer_queue.h, google/cloud/internal/timer_queue_test.cc
Part of the work for #10553
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10563)
=> impl(common): TimerQueue atomic callbacks

google/cloud/google_cloud_cpp_rest_protobuf_internal.bzl, google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake, google/cloud/google_cloud_cpp_rest_protobuf_internal_unit_tests.bzl, google/cloud/internal/async_rest_retry_loop.h, google/cloud/internal/async_rest_retry_loop_test.cc
Adds REST version of existing AsyncRetryLoop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10570)
=> impl(rest): add AsyncRestRetryLoop

google/cloud/google_cloud_cpp_rest_protobuf_internal.bzl, google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake, google/cloud/google_cloud_cpp_rest_protobuf_internal_unit_tests.bzl, google/cloud/internal/rest_retry_loop.h, google/cloud/internal/rest_retry_loop_test.cc
Adds REST version of existing `RetryLoop`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10574)
=> impl(rest): add RestRetryLoop

generator/internal/descriptor_utils.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10578)
=> impl(generator): leave a TODO about dealing with deprecated fields

google/cloud/BUILD.bazel, google/cloud/google_cloud_cpp_rest_protobuf_internal.bzl, google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake, google/cloud/google_cloud_cpp_rest_protobuf_internal_unit_tests.bzl, google/cloud/internal/async_rest_polling_loop.cc, google/cloud/internal/async_rest_polling_loop.h, google/cloud/internal/async_rest_polling_loop_test.cc
Add REST version of AsyncPollingLoop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10576)
=> impl(rest): add AsyncRestPollingLoop

google/cloud/google_cloud_cpp_rest_protobuf_internal.bzl, google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake, google/cloud/google_cloud_cpp_rest_protobuf_internal_unit_tests.bzl, google/cloud/internal/async_rest_long_running_operation.h, google/cloud/internal/async_rest_long_running_operation_test.cc
Adds LRO support for REST transport.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10588)
=> impl(rest): add AsyncRestLongRunningOperation

cmake/GoogleCloudCppFeatures.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10590)
=> fix: respect GOOGLE_CLOUD_CPP_<feature> flags

google/cloud/internal/rest_options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10594)
=> impl(rest): add internal LRO endpoint option

google/cloud/internal/rest_options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10596)
=> impl(rest): add LRO option to list

google/cloud/internal/oauth2_compute_engine_credentials.cc, google/cloud/storage/oauth2/compute_engine_credentials.cc, google/cloud/storage/oauth2/service_account_credentials.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10612)
=> cleanup: more uses of 'or'

google/cloud/google_cloud_cpp_common.cmake, google/cloud/google_cloud_cpp_grpc_utils.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10616)
=> fix(common): missing Abseil deps in pkgconfig

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_logging_decorator.h, generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_metadata_decorator.h, generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_stub.cc, generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_stub.h, generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_logging_decorator.cc, generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_logging_decorator.h, generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_metadata_decorator.cc, generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_metadata_decorator.h, generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_stub.cc, generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_stub.h, generator/integration_tests/tests/golden_thing_admin_rest_logging_decorator_test.cc, generator/integration_tests/tests/golden_thing_admin_rest_metadata_decorator_test.cc, generator/integration_tests/tests/golden_thing_admin_rest_stub_test.cc, generator/integration_tests/tests/mock_golden_thing_admin_rest_stub.h, generator/internal/logging_decorator_rest_generator.cc, generator/internal/metadata_decorator_rest_generator.cc, generator/internal/stub_rest_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10624)
=> impl(generator): add LRO support to rest stub and decorators

generator/internal/descriptor_utils.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10638)
=> feat(generator): workaround for pubsub/v1/schema.proto

google/cloud/internal/async_rest_long_running_operation.h, google/cloud/internal/async_rest_long_running_operation_test.cc, google/cloud/internal/async_rest_polling_loop.cc, google/cloud/internal/async_rest_polling_loop.h, google/cloud/internal/async_rest_polling_loop_test.cc, google/cloud/internal/async_rest_retry_loop.h, google/cloud/internal/async_rest_retry_loop_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10647)
=> impl(rest): change lro framework to use std::unique_ptr<RestContext>

generator/integration_tests/tests/golden_kitchen_sink_tracing_connection_test.cc, generator/integration_tests/tests/golden_thing_admin_tracing_connection_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10645)
=> cleanup(otel): slightly improve test readability

cmake/GoogleCloudCppDoxygen.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10653)
=> cleanup: reorder Doxygen variables

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_stub_factory.cc, generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_stub_factory.cc, generator/internal/stub_factory_rest_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10651)
=> impl(generator): add LRO endpoint option to rest stub factory

google/cloud/pubsub/internal/schema_tracing_connection.cc, google/cloud/pubsub/internal/schema_tracing_stub.cc, google/cloud/pubsub/internal/schema_tracing_stub.h
ETOOMANYPRs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10662)
=> chore: regenerate after merging

ci/install-cloud-sdk.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10659)
=> chore(deps): update gcloud to 415.0.0

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_stub_factory.cc, generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_stub_factory.cc, generator/internal/stub_factory_rest_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10661)
=> impl(generator): sanitize endpoint string in stub factory

ci/cloudbuild/builds/cxx14.sh, ci/cloudbuild/builds/cxx20.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10668)
=> ci: compile all libraries with C++{14,20}

generator/CMakeLists.txt, generator/google_cloud_cpp_generator.bzl, generator/internal/proto_definition_location.h, generator/internal/resolve_comment_references.cc, generator/internal/resolve_comment_references_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10674)
=> refactor(generator): split ProtoDefinitionLocation

google/cloud/storage/internal/xml_node.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10686)
=> cleanup(storage): an additional clarifying comment for XmlParser

ci/cloudbuild/dockerfiles/checkers.Dockerfile, google/cloud/internal/future_coroutines.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10690)
=> ci: update checkers to Fedora:37

.github/renovate.json, bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/centos-7.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cmake.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cxx14.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10692)
=> chore(deps): update googletest to v1.13.0

ci/cloudbuild/dockerfiles/checkers.Dockerfile, doc/contributor/howto-guide-setup-development-workstation.md
Also update the documentation to better match what we use in CI vs. what should be installed in your workstation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10697)
=> chore: update formatting tools

google/cloud/internal/rest_stub_helpers.cc, google/cloud/internal/rest_stub_helpers_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10700)
=> impl(rest): ignore unknown fields when parsing JSON to proto

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10702)
=> cleanup(spanner): display row count in ExecutePartitionedDml() samples

google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc, google/cloud/bigtable/data_connection.cc, google/cloud/bigtable/examples/data_snippets.cc, google/cloud/bigtable/internal/bulk_mutator.cc, google/cloud/bigtable/internal/connection_refresh_state.cc, google/cloud/bigtable/internal/legacy_async_row_reader_test.cc, google/cloud/bigtable/mutation_batcher.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10707)
=> cleanup(bigtable): prepare for clang-tidy 15

google/cloud/iam/samples/iam_samples.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10710)
=> cleanup(iam): prepare for clang-tidy 15

google/cloud/spanner/client.cc, google/cloud/spanner/integration_tests/client_integration_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10712)
=> cleanup(spanner): prepare for clang-tidy 15

google/cloud/storage/bucket_metadata_test.cc, google/cloud/storage/client.h, google/cloud/storage/internal/curl_download_request.h, google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/internal/policy_document_request.cc, google/cloud/storage/list_objects_and_prefixes_reader_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10713)
=> cleanup(storage): prepare for clang-tidy 15

generator/internal/descriptor_utils.cc, generator/internal/predicate_utils.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10709)
=> cleanup(generator): prepare for clang-tidy 15

google/cloud/pubsublite/internal/partition_publisher_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10711)
=> cleanup(pubsublite): prepare for clang-tidy 15

ci/cloudbuild/dockerfiles/fedora-37-cxx14.Dockerfile, ci/cloudbuild/triggers/cxx14-ci.yaml, ci/cloudbuild/triggers/cxx14-pr.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10716)
=> ci: move cxx14 build to Fedora:37

ci/cloudbuild/dockerfiles/fedora-37-cxx20.Dockerfile, ci/cloudbuild/triggers/cxx20-ci.yaml, ci/cloudbuild/triggers/cxx20-pr.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10717)
=> ci: switch cxx20 build to Fedora:37

bazel/google_cloud_cpp_deps.bzl
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10721)
=> chore(deps): update boringssl version

ci/cloudbuild/dockerfiles/fedora-37-bazel.Dockerfile, ci/cloudbuild/triggers/libcxx-ci.yaml, ci/cloudbuild/triggers/libcxx-pr.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10724)
=> ci: switch libcxx build to Fedora:37

ci/cloudbuild/build.sh, ci/cloudbuild/triggers/asan-ci.yaml, ci/cloudbuild/triggers/asan-pr.yaml, ci/cloudbuild/triggers/tsan-ci.yaml, ci/cloudbuild/triggers/tsan-pr.yaml, ci/cloudbuild/triggers/ubsan-ci.yaml, ci/cloudbuild/triggers/ubsan-pr.yaml, ci/cloudbuild/triggers/xsan-ci.yaml, ci/cloudbuild/triggers/xsan-pr.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10732)
=> ci: switch most sanitizer builds to Fedora:37

.bazelrc, ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10734)
=> ci: switch msan build to Fedora:37

ci/cloudbuild/builds/integration-daily.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10740)
=> ci: switch integration-daily build to Fedora:37

ci/kokoro/windows/builds/quickstart-bazel.ps1
Mitigates the problems from #10737
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10742)
=> ci: deflake build due to Bazel bug

ci/cloudbuild/triggers/check-api-ci.yaml, ci/cloudbuild/triggers/check-api-pr.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10743)
=> ci: switch check-api build to Fedora:37

google/cloud/bigtable/table_admin.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10747)
=> doc(bigtable): prepare for Fedora:37

generator/internal/descriptor_utils.cc, generator/internal/format_class_comments.cc, generator/internal/format_class_comments_test.cc, google/cloud/artifactregistry/artifact_registry_client.h, google/cloud/asset/asset_client.h, google/cloud/monitoring/group_client.h, google/cloud/resourcemanager/folders_client.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10749)
=> feat(generator): prepare comment output for Fedora:37

ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/generate-markdown/generate-packaging.sh, doc/packaging.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10753)
=> ci: switch `demo-fedora` build to Fedora:37

.clang-format, docfx/.clang-tidy, docfx/doxygen2markdown.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10773)
=> cleanup(docfx): fine tune linters

ci/cloudbuild/builds/m32.sh, ci/cloudbuild/dockerfiles/fedora-m32.Dockerfile, ci/cloudbuild/triggers/m32-ci.yaml, ci/cloudbuild/triggers/m32-pr.yaml, ci/etc/m32-toolchain.cmake
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10776)
=> ci: introduce a 32-bit build (m32)

ci/cloudbuild/builds/m32.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10786)
=> ci(m32): fail on build or unit test failures

ci/cloudbuild/builds/m32.sh, ci/cloudbuild/dockerfiles/fedora-m32.Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10790)
=> ci(m32): enable integration tests

ci/cloudbuild/builds/m32.sh
Fixes #10775
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10794)
=> ci: finalize m32 build

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc
`CreateBucket()` returns a confusing error code when the bucket already exists. In JSON we map 409 (aka kAborted) to kAlreadyExists.  gRPC returns kFailedPrecondition, which we now also map to kAlreadyExists.
Part of the work for #9800, also related to #10478
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10799)
=> impl(GCS+gRPC): map `CreateBucket()` error codes

google/cloud/storage/tests/bucket_integration_test.cc, google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc, google/cloud/storage/tests/grpc_default_object_acl_integration_test.cc, google/cloud/storage/tests/grpc_object_acl_integration_test.cc, google/cloud/storage/tests/object_integration_test.cc
Fixes #9800
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10801)
=> test(GCS+gRPC): restore `*Acl` integration tests

google/cloud/storage/internal/storage_round_robin.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10800)
=> impl(GCS+gRPC): reduce noise in logs

google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client_test.cc
The service-side problems are fixed.  Closes #9563
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10816)
=> cleanup(GCS+gRPC): remove workaround

cmake/GoogleCloudCppFeatures.cmake, google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/admin/integration_tests/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10823)
=> cleanup: simplify HTTP transcoding configuration

google/cloud/bigtable/filters.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10825)
=> cleanup(bigtable): typo

doc/compile-time-configuration.md, doc/packaging.md
Fixes #8572
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10822)
=> doc: describe compile-time options

doc/contributor/howto-guide-adding-generated-libraries.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10826)
=> doc: add note to generating libraries howto

generator/internal/scaffold_generator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10827)
=> generator: add cloud-docs dep in CMakeLists.txt

doc/contributor/howto-guide-setup-development-workstation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10833)
=> doc: update some developer instructions

ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/builds/lib/features.sh, ci/verify_current_targets/CMakeLists.txt, google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/config-rest.cmake.in
Fixes #10830 
Install `bigquery_rest` and test for it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10836)
=> impl(bigquery): install bigquery_rest

CHANGELOG.md
I should have done this in the last commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10842)
=> doc: update CHANGELOG for v1.42.2 release

google/cloud/bigtable/internal/default_row_reader.h, google/cloud/bigtable/table.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10848)
=> cleanup(bigtable): remove unused

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
Also document what we have not implemented.  I will fill these in as needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10855)
=> impl(docfx): continue implementing paragraphs

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10861)
=> impl(docfx): support `sect*` elements

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10880)
=> impl(docfx): add support for `ref` elements

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
This is enough to support the landing page for the common library. It is missing features, the plan of record is to add these as-needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10886)
=> impl(docfx): support Doxygen `@page` documents

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10890)
=> impl(docfx): support `programlisting` elements

google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/query_partition_test.cc, google/cloud/spanner/read_partition_test.cc, google/cloud/spanner/testing/matchers.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10909)
=> test(spanner): check route-to-leader in HasSessionAndTransaction

cmake/GoogleCloudCppFeatures.cmake, google/cloud/batch/config.cmake.in, libraries.bzl
In a follow up, I will GA `apikeys`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10914)
=> chore(batch): make full GA

doc/contributor/howto-guide-declare-a-library-ga.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10915)
=> doc: howto declare GA update

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10924)
=> impl(docfx): support `variablelist` elements

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10949)
=> impl(docfx): support `orderedlist` elements

ci/kokoro/windows/builds/quickstart-cmake.ps1
It seems that #9913 is fixed, enable the tests that used to fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10960)
=> ci: test more quickstarts on Windows

ci/kokoro/windows/builds/quickstart-cmake.ps1
Reverts some of the changes in #10819
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10962)
=> ci: remove unused CMake option

bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/fedora-37-cmake.Dockerfile, docfx/BUILD.bazel, docfx/CMakeLists.txt, vcpkg.json
I will need to generate YAML files. These look simple until you start reading about how to quote string literals.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10964)
=> impl(docfx): introduce yaml-cpp dependency

docfx/CMakeLists.txt, docfx/docfx.bzl, docfx/doxygen_pages.cc, docfx/doxygen_pages_test.cc, docfx/toc_entry.cc, docfx/toc_entry.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10968)
=> impl(docfx): extract table of contents for pages

docfx/doxygen2docfx.cc, docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc, docfx/doxygen_pages.cc, docfx/doxygen_pages.h, docfx/doxygen_pages_test.cc, docfx/parse_arguments.cc, docfx/parse_arguments.h, docfx/parse_arguments_test.cc, docfx/toc_entry.cc, docfx/toc_entry.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10969)
=> refactor(docfx): move to a namespace

docfx/doxygen2docfx.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10974)
=> impl(docfx): generate files for TOC and pages

bazel/google_cloud_cpp_deps.bzl, cmake/GoogleapisConfig.cmake, google/cloud/batch/v1/batch_client.h, google/cloud/certificatemanager/v1/certificate_manager_client.h, google/cloud/contactcenterinsights/v1/contact_center_insights_client.h, google/cloud/scheduler/v1/cloud_scheduler_client.h, google/cloud/video/transcoder/v1/transcoder_client.h
Pick up `spanner.v1.{ExecuteSql,Read}Request.data_boost_enabled`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10987)
=> chore: update googleapis SHA circa 2023-03-02

google/cloud/bigquery/BUILD.bazel, google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/bigquery_http_response.cc, google/cloud/bigquery/v2/minimal/internal/bigquery_http_response.h, google/cloud/bigquery/v2/minimal/internal/bigquery_http_response_test.cc, google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc, google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h, google/cloud/bigquery/v2/minimal/internal/common_v2_resources_test.cc, google/cloud/bigquery/v2/minimal/internal/job.h, google/cloud/bigquery/v2/minimal/internal/job_configuration.h, google/cloud/bigquery/v2/minimal/internal/job_response.cc, google/cloud/bigquery/v2/minimal/internal/job_response_test.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.h, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc, google/cloud/bigquery/v2/minimal/internal/job_retry_policy.h
Implementation of Custom job class, http response, rest response, and rest stub with unit tests. 
fyi: Not all fields are included  in the custom classes for the V2 job proto. I have included selected fields based on use cases. Some classes QueryParameterType and QueryParameterStructType and self referential and recursive mirroring the job proto messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10953)
=> impl(bigquery): V2 GetJob api - Implementation 

generator/BUILD.bazel, generator/CMakeLists.txt, generator/internal/discovery_to_proto.cc
Reads the discovery document from either a local file or http server. Integration tests will be added later to exercise this code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10999)
=> impl(generator): parse Discovery Document JSON

generator/CMakeLists.txt, generator/google_cloud_cpp_generator_unit_tests.bzl, generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc
Part of the work for #10980 
Perform some field checking of the Discovery JSON and add types defined as `schema` into a container of "Types".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11001)
=> impl(generator): extract schema from Discovery Doc

google/cloud/internal/grpc_opentelemetry.cc, google/cloud/internal/grpc_opentelemetry.h, google/cloud/internal/grpc_opentelemetry_test.cc, google/cloud/internal/opentelemetry.h, google/cloud/internal/opentelemetry_test.cc
Part of the work for #10618
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11005)
=> impl(otel): handle future<T>

generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11009)
=> impl(generator): handle empty id in discovery doc

google/cloud/storage/object_write_stream.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11015)
=> doc(storage): clarify `ObjectWriteStream` behavior

google/cloud/google_cloud_cpp_rest_internal.bzl, google/cloud/google_cloud_cpp_rest_internal.cmake, google/cloud/google_cloud_cpp_rest_internal_unit_tests.bzl, google/cloud/google_cloud_cpp_rest_protobuf_internal.bzl, google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake, google/cloud/google_cloud_cpp_rest_protobuf_internal_unit_tests.bzl
This reorg will improve efficiency and productivity, increase innovation and creativity, and better align our code with our values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11020)
=> cleanup: move RestRetryLoop into rest_internal

generator/internal/codegen_utils.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11024)
=> cleanup(generator): simplify discovery doc comment logic

google/cloud/bigquery/BUILD.bazel, google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/job_connection.cc, google/cloud/bigquery/v2/minimal/internal/job_connection.h, google/cloud/bigquery/v2/minimal/internal/job_connection_test.cc, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.cc, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.h, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy_test.cc, google/cloud/bigquery/v2/minimal/internal/job_logging.cc, google/cloud/bigquery/v2/minimal/internal/job_logging.h, google/cloud/bigquery/v2/minimal/internal/job_metadata.cc, google/cloud/bigquery/v2/minimal/internal/job_metadata.h, google/cloud/bigquery/v2/minimal/internal/job_options.cc, google/cloud/bigquery/v2/minimal/internal/job_options.h, google/cloud/bigquery/v2/minimal/internal/job_options_test.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.h, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.h, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_factory.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc, google/cloud/bigquery/v2/minimal/internal/job_retry_policy.h
All the files modified are connected to each other and are referenced which is why I didn't want to split them up.
Connection tests are currently stubbed out. Connection tests implementation with detailed mocks will be added in the subsequent PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11016)
=> impl(bigquery): Remaining implementation files for GetJob api.

google/cloud/internal/future_impl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11032)
=> cleanup: `#include <atomic>`

google/cloud/bigquery/v2/minimal/internal/job_request.cc, google/cloud/bigquery/v2/minimal/internal/job_request_test.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_factory.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc
Changes to address github issue: https://github.com/googleapis/google-cloud-cpp/issues/11026
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11038)
=> impl(bigquery): set all default options in a single place

generator/generator_config.textproto, google/cloud/iam/admin/v1/iam_connection_idempotency_policy.cc, google/cloud/iam/credentials/v1/iam_credentials_connection_idempotency_policy.cc
This should also help reduce flakes in our tests/samples.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11045)
=> fix(iam): override idempotency on idempotent POST methods

generator/generator_config.textproto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11047)
=> fix(iam): remove redundant idempotency override

google/cloud/spanner/integration_tests/client_integration_test.cc
The groundwork for adding PostgreSQL versions of some Spanner client integration tests.  Firstly just "DatabaseDialect", but more will come as time goes by.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11058)
=> test(spanner): postgresql client integration tests

google/cloud/storage/tests/grpc_integration_test.cc, google/cloud/storage/tests/grpc_object_media_integration_test.cc, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc
Motivated by #11060 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11059)
=> cleanup(storage): remove unused `#includes`

generator/integration_tests/tests/golden_thing_admin_tracing_connection_test.cc
Verify behavior of these tracing connection calls.
I considered updating unimplemented unit tests to expect that there are no spans created. (So that when I do implement tracing for that method, things will fail until I update the unit tests). But I don't think it is worth doing. The remaining methods (streams, OCC loop) have one unit test per client method. It will stand out if no unit tests are updated in those PRs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11067)
=> test(otel): missing unit tests

google/cloud/bigquery/v2/minimal/internal/job_request.cc, google/cloud/bigquery/v2/minimal/internal/job_request.h, google/cloud/bigquery/v2/minimal/internal/job_request_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063)
=> impl(bigquery): ListJobs api - request object implementation and unit tests

google/cloud/bigquery/v2/minimal/internal/job.h, google/cloud/bigquery/v2/minimal/internal/job_response.cc, google/cloud/bigquery/v2/minimal/internal/job_response.h, google/cloud/bigquery/v2/minimal/internal/job_response_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11068)
=> impl(bigquery): ListJobs api - Response object parsing, implementation and unit tests

google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.cc, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy.h, google/cloud/bigquery/v2/minimal/internal/job_idempotency_policy_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11080)
=> impl(bigquery): ListJobs api - Add support for ListJobs in Idempotency policy

google/cloud/internal/async_read_write_stream_impl_test.cc, google/cloud/internal/async_streaming_write_rpc_impl_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11092)
=> cleanup: use std::make_unique

ci/cloudbuild/dockerfiles/fedora-37-cmake.Dockerfile
Motivated by #10895
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11096)
=> ci: update yaml-cpp

docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11100)
=> impl(docfx): generate YAML for `typedef`

google/cloud/bigquery/v2/minimal/internal/job_logging.cc, google/cloud/bigquery/v2/minimal/internal/job_logging.h, google/cloud/bigquery/v2/minimal/internal/job_metadata.cc, google/cloud/bigquery/v2/minimal/internal/job_metadata.h, google/cloud/bigquery/v2/minimal/internal/job_request.cc, google/cloud/bigquery/v2/minimal/internal/job_request.h, google/cloud/bigquery/v2/minimal/internal/job_request_test.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_stub.h, google/cloud/bigquery/v2/minimal/internal/job_rest_stub_test.cc, google/cloud/bigquery/v2/minimal/testing/mock_job_rest_stub.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11081)
=> impl(bigquery): ListJobs api - Added ListJobs() support to BigQueryRestStub

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_tracing_stub.cc, generator/integration_tests/tests/golden_kitchen_sink_tracing_stub_test.cc, generator/internal/tracing_stub_generator.cc, google/cloud/bigquery/storage/v1/internal/bigquery_read_tracing_stub.cc, google/cloud/bigtable/internal/bigtable_tracing_stub.cc, google/cloud/osconfig/agentendpoint/v1/internal/agent_endpoint_tracing_stub.cc, google/cloud/storage/internal/storage_tracing_stub.cc
Part of the work for #10620
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11104)
=> impl(otel): tracing for streaming reads in stubs

generator/internal/discovery_type_vertex.cc, generator/internal/discovery_type_vertex.h, generator/internal/discovery_type_vertex_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11097)
=> impl(generator): add helper functions for formatting protobuf messages

docfx/doxygen2syntax.cc, docfx/doxygen2syntax.h, docfx/doxygen2syntax_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11124)
=> impl(docfx): generate `syntax` element for functions

generator/internal/discovery_type_vertex.cc, generator/internal/discovery_type_vertex.h, generator/internal/discovery_type_vertex_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11119)
=> impl(generator): format discovery JSON to protobuf message

docfx/doxygen2syntax.cc, docfx/doxygen2syntax.h, docfx/doxygen2syntax_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11132)
=> impl(docfx): generate `syntax` element for classes

docfx/doxygen2syntax.cc, docfx/doxygen2syntax.h, docfx/doxygen2syntax_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11137)
=> impl(docfx): generate `syntax` element for namespaces

ci/cloudbuild/notifiers/alerts/deploy.sh, ci/cloudbuild/notifiers/alerts/function/function.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11146)
=> ci: only notify friends for 'friends' builds

doc/compile-time-configuration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11151)
=> doc: fix typo

docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11150)
=> impl(docfx): generate YAML for <sectiondef> and children

docfx/doxygen2syntax.cc, docfx/doxygen2syntax.h, docfx/doxygen2syntax_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11153)
=> impl(docfx): generate `syntax` element for variables

generator/CMakeLists.txt, generator/google_cloud_cpp_generator_unit_tests.bzl, generator/internal/discovery_resource.cc, generator/internal/discovery_resource.h, generator/internal/discovery_resource_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11139)
=> impl(generator): add helper functions for formatting resource proto defintions

docfx/doxygen2yaml.cc, docfx/doxygen2yaml_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11160)
=> impl(docfx): weave `syntax` in existing YAML

release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11164)
=> doc: increase verbosity on version bump instructions

generator/internal/discovery_resource.cc, generator/internal/discovery_resource.h, generator/internal/discovery_resource_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11154)
=> impl(generator): format resource JSON as proto service

docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11159)
=> impl(docfx): generate YAML for namespaces

docfx/doxygen2markdown.cc, docfx/doxygen2markdown_test.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11162)
=> impl(docfx): generate YAML for functions

docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11176)
=> impl(docfx): generate YAML for classes

docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11178)
=> impl(docfx): generate YAML for variables

docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11179)
=> impl(docfx): generate YAML for structs

google/cloud/bigquery/BUILD.bazel, google/cloud/bigquery/v2/minimal/internal/job_client.cc, google/cloud/bigquery/v2/minimal/internal/job_client.h, google/cloud/bigquery/v2/minimal/internal/job_client_test.cc, google/cloud/bigquery/v2/minimal/internal/job_connection.cc, google/cloud/bigquery/v2/minimal/internal/job_connection.h, google/cloud/bigquery/v2/minimal/internal/job_connection_test.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.cc, google/cloud/bigquery/v2/minimal/internal/job_rest_connection_impl.h, google/cloud/bigquery/v2/minimal/mocks/mock_job_connection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11133)
=> impl(bigquery): Adding ListJobs api support to job Connection classes

google/cloud/videointelligence/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11203)
=> ci: disable videointelligence quickstart

google/cloud/spanner/samples/samples.cc
Part of the work for #11201
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11204)
=> ci(spanner): disable data boost samples

ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/builds/lib/features.sh, ci/verify_current_targets/CMakeLists.txt, google/cloud/opentelemetry/CMakeLists.txt, google/cloud/opentelemetry/config.cmake.in
Part of the work for #11156
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11206)
=> impl(otel): install opentelemetry_sdk

docfx/doxygen2syntax.cc, docfx/doxygen2syntax.h, docfx/doxygen2syntax_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11212)
=> impl(docfx): generate syntax for friend declarations

docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11214)
=> impl(docfx): generate YAML for friend declarations

docfx/doxygen2yaml.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11215)
=> impl(docfx): document compound recursion

docfx/README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11217)
=> doc(docfx): list steps for end-to-end testing

google/cloud/bigquery/v2/minimal/internal/bigquery_http_response.cc, google/cloud/bigquery/v2/minimal/internal/bigquery_http_response_test.cc, google/cloud/bigquery/v2/minimal/internal/job_response.cc, google/cloud/bigquery/v2/minimal/internal/job_response_test.cc, google/cloud/internal/debug_string.cc, google/cloud/internal/debug_string.h, google/cloud/internal/debug_string_test.cc
- `absl::optional<T>`
- `std::vector<T>`
- `std::multimap<std::string, std::string>`
Use these to complete `DebugString()` support for `BigQueryHttpResponse` and `ListJobsResponse`, and prepare for `optional` use in `ListJobsRequest`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11228)
=> impl(common): enhance DebugFormatter support

CHANGELOG.md, README.md, ci/cloudbuild/builds/bazel-oldest.sh, google/cloud/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11231)
=> cleanup: minimum Bazel version is 5.4

docfx/doxygen2yaml.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11234)
=> impl(docfx): do not recurse Mock classes

doc/ctype-cord-workarounds.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11239)
=> doc: address comments on ctype-cord-workarounds

google/cloud/storage/internal/grpc_ctype_cord_workaround.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11242)
=> cleanup(GCS+gRPC): remove unused include

google/cloud/storage/internal/grpc_split_write_object_data.cc, google/cloud/storage/internal/grpc_split_write_object_data.h
The `absl::Cord(absl::string_view)` constructor splits the input data into small chunks of 4KiB each. That puts pressure on the allocator, as we often use this with 32MiB buffers. Esun had two really good suggestions:
- Use `absl::MakeCordFromExternal()` to avoid the pressure on the allocator.
- Only create a Cord when needed in `Next()`, to reduce the overall memory usage.
That made `Next()` the only function that needed specialization, so do that.
Thanks to @veblush for the original patch and the effort to test this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11240)
=> impl(GCS+gRPC): reduce allocations in absl::Cord

generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11237)
=> impl(generator): minor cleanup

google/cloud/google_cloud_cpp_rest_internal.bzl, google/cloud/google_cloud_cpp_rest_internal.cmake, google/cloud/google_cloud_cpp_rest_internal_unit_tests.bzl, google/cloud/internal/rest_opentelemetry.cc, google/cloud/internal/tracing_http_payload.cc, google/cloud/internal/tracing_http_payload.h, google/cloud/internal/tracing_http_payload_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11227)
=> impl(otel): tracing for `rest_internal::HttpPayload`

generator/internal/discovery_file.cc
Implement the suggestions from https://github.com/googleapis/google-cloud-cpp/pull/11195#pullrequestreview-1378064211
In my opinion, the code is simpler now. Arguably, I spend too much time on such things, which might explain why I am perpetually behind on my projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11241)
=> refactor: newline management in DiscoveryFile

google/cloud/storage/internal/grpc_split_write_object_data.cc, google/cloud/storage/internal/grpc_split_write_object_data.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11248)
=> impl(GCS+gRPC): optimize SplitObjectWriteData

generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11277)
=> feat(generator): add SynthesizeRequestType

generator/generator_test.cc, generator/internal/predicate_utils_test.cc, generator/internal/service_code_generator_test.cc, generator/testing/fake_source_tree.cc, generator/testing/fake_source_tree.h, google/cloud/internal/rest_stub_helpers.cc
Some changes needed because Protobuf v22.x is a major release for C++, with breaking changes.
Fixes #11276
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11278)
=> chore(deps): prepare for Protobuf v22.x

generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11282)
=> feat(generator): add ProcessMethodsRequestsAndResponses

google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11289)
=> fix: correct rest_protobuf_internal cmake install directives

google/cloud/spanner/samples/samples.cc
The problem with the DataBoost samples was that there is no capacity in the region used by our Spanner instances labelled as "samples:yes".
So, lets re-enable them, but with a specific allowance for seeing a `kPermissionDenied` status code.  Then, they will automatically start working when capacity is allocated, and after which we can remove the workaround.
Use `//!` to keep the workaround out of the published snippets.
Related to #11201.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11293)
=> ci(spanner): re-enable DataBoost samples but with workaround

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/dataset.cc, google/cloud/bigquery/v2/minimal/internal/dataset.h, google/cloud/bigquery/v2/minimal/internal/dataset_test.cc
This PR contains the custom classes and json parsing for  the Dataset resource.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11261)
=> impl(bigquery): Dataset api - Custom classes and unit tests for V2 Dataset resource

docfx/doxygen2markdown.cc, docfx/doxygen2markdown.h, docfx/doxygen2markdown_test.cc
Fixes #11245
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11310)
=> impl(docfx): support `<table>` elements

CMakeLists.txt, ci/cloudbuild/builds/checkers.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11316)
=> cleanup: format top-level CMake file too

google/cloud/mocks/mock_stream_range.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11323)
=> cleanup: docs nit in `mocks::MakeStreamRange`

docfx/CMakeLists.txt, docfx/docfx.bzl, docfx/doxygen2docfx.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc, docfx/public_docs.cc, docfx/public_docs.h, docfx/public_docs_test.cc, docfx/unit_tests.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11325)
=> refactor(docfx): split `IncludeInPublicDocuments()`

docfx/doxygen_pages.cc, docfx/doxygen_pages_test.cc, docfx/public_docs.cc, docfx/public_docs_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11326)
=> impl(docfx): exclude 'Deprecated List' page

docfx/doxygen2docfx.cc, docfx/doxygen2toc.cc, docfx/doxygen2toc_test.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml.h, docfx/doxygen2yaml_test.cc, docfx/doxygen_pages.cc, docfx/doxygen_pages.h, docfx/doxygen_pages_test.cc, docfx/public_docs.cc, docfx/public_docs.h, docfx/public_docs_test.cc, docfx/yaml_context.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11330)
=> impl(docfx): only 'cloud' documents google::cloud

CHANGELOG.md
Maybe I should have done this in the previous PR, but I needed the PR id.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11334)
=> chore: update CHANGELOG.md for v2.9.1

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/dataset_rest_stub.cc, google/cloud/bigquery/v2/minimal/internal/dataset_rest_stub.h, google/cloud/bigquery/v2/minimal/internal/dataset_rest_stub_factory.cc, google/cloud/bigquery/v2/minimal/internal/dataset_rest_stub_factory.h, google/cloud/bigquery/v2/minimal/internal/dataset_rest_stub_test.cc, google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324)
=> impl(bigquery): Rest stubs for dataset apis

docfx/CMakeLists.txt, docfx/docfx.bzl, docfx/doxygen2children.cc, docfx/doxygen2children.h, docfx/doxygen2children_test.cc, docfx/unit_tests.bzl
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11338)
=> impl(docfx): helper function to compute children

docfx/CMakeLists.txt, docfx/docfx.bzl, docfx/doxygen2references.cc, docfx/doxygen2references.h, docfx/doxygen2references_test.cc, docfx/unit_tests.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11340)
=> impl(docfx): helpers for `reference` section

google/cloud/internal/rest_opentelemetry.cc, google/cloud/internal/rest_opentelemetry.h, google/cloud/internal/rest_opentelemetry_test.cc
Part of the work for #11264
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11341)
=> impl(otel): implement TextMapCarrier for HTTP

generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto.h, generator/internal/discovery_to_proto_test.cc
Passing multiple strings combined with the number of arguments was starting to get unreadable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11342)
=> refactor(generator): aggregate doc properties to pass to functions

google/cloud/storage/internal/grpc_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11354)
=> impl(GCS+gRPC): fix comment post-merge

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_testing.bzl, google/cloud/bigquery/v2/minimal/internal/job_logging_test.cc, google/cloud/bigquery/v2/minimal/testing/mock_log_backend.h
Renamed MockJobLoggingBackend class to MockLoggingBackend since this class will be used in multiple logging decorators.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11362)
=> impl(bigquery): Refactor rename MockJobLoggingBackend

google/cloud/storage/internal/storage_stub_factory.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11369)
=> impl(GCS+gRPC): use OTel tracing decorator

docfx/doxygen2markdown.cc, docfx/doxygen2markdown_test.cc, docfx/generate_metadata.cc, docfx/generate_metadata_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11374)
=> impl(docfx): support cross-references to common

docfx/doxygen2syntax.cc, docfx/doxygen2syntax_test.cc, docfx/doxygen2yaml_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11379)
=> impl(docfx): use correct field for return type

generator/internal/discovery_file.cc, generator/internal/discovery_file.h, generator/internal/discovery_file_test.cc, generator/internal/discovery_type_vertex.h
fixes #11353
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11378)
=> impl(generator): add package name support for DiscoveryFile

docfx/doxygen2markdown.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11382)
=> impl(docfx): split `summary` from longer description

docfx/doxygen2yaml.cc, docfx/doxygen2yaml_test.cc, docfx/testing/inputs.cc, docfx/testing/inputs.h
A bit embarrassing, apologies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11388)
=> fix(docfx): remove mock description from non-mocks

generator/internal/discovery_resource.cc, generator/internal/discovery_resource.h, generator/internal/discovery_resource_test.cc, generator/internal/discovery_to_proto.cc, generator/internal/discovery_to_proto_test.cc
In order for protoc to generate code, some files need to always be imported, others conditionally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11398)
=> impl(generator): add appropriate proto imports

generator/internal/descriptor_utils.cc, google/cloud/bigtable/admin/bigtable_instance_admin_client.h, google/cloud/bigtable/admin/bigtable_table_admin_client.h
More details at:
https://www.doxygen.nl/manual/markdown.html#mddox_code_spans
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11400)
=> feat(generator): workaround Doxygen limitations on code spans

google/cloud/bigtable/table.h
More details at:
https://www.doxygen.nl/manual/markdown.html#mddox_code_spans
Part of the work for https://github.com/googleapis/google-cloud-cpp/issues/11309
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11401)
=> doc(bigtable): workaround Doxygen limitations on code spans

docfx/doxygen2markdown.cc, docfx/doxygen2markdown_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11403)
=> impl(docfx): support <linebreak> elements

docfx/doxygen2markdown.cc, docfx/doxygen2markdown_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11402)
=> impl(docfx): ignore <zwj> elements

google/cloud/storage/examples/storage_client_per_operation_samples.cc
The samples showing how to override the retry policies now use values that are more realistic, and more tolerant of transient failures in the CI builds.
Part of the work for #10413
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11411)
=> test(storage): more tolerant policies in samples

ci/cloudbuild/cache.sh, ci/install-cloud-sdk.sh, ci/kokoro/lib/cache.sh, google/cloud/pubsub/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11409)
=> chore: update the Google Cloud CLI

generator/internal/descriptor_utils.cc, google/cloud/dialogflow_es/agents_client.h
I fooled myself into believing that only bigtable had these problems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11406)
=> feat(generator): more Doxygen workarounds

google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client_test.cc
Part of the work for #7170
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11407)
=> impl(storage): add backoff spans

google/cloud/sql/CMakeLists.txt, google/cloud/sql/integration_tests/BUILD.bazel, google/cloud/sql/integration_tests/CMakeLists.txt, google/cloud/sql/integration_tests/sql_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11383)
=> impl(sql): add first integration test

google/cloud/storage/client.cc
Part of the work for #7170
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11417)
=> impl(storage): add Tracing client if enabled

docfx/doxygen2markdown.cc, docfx/doxygen2markdown_test.cc
Part of the work for #11428 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11429)
=> impl(docfx): cleanup zwj sequences

ci/cloudbuild/builds/lib/integration.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11434)
=> impl(spanner): enable REST instance admin test against emulator

generator/integration_tests/golden/v1/internal/golden_kitchen_sink_tracing_stub.cc, generator/integration_tests/tests/golden_kitchen_sink_tracing_stub_test.cc, generator/internal/tracing_stub_generator.cc, google/cloud/storage/internal/storage_tracing_stub.cc
Part of the work for #10620 
Note that there is no associated Connection level change, because all streaming writes are handwritten at that layer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11444)
=> impl(otel): traced streaming writes in stubs

docfx/doxygen_groups.cc, docfx/doxygen_groups_test.cc
Fixes #11449
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11450)
=> impl(docfx): fix titles for groups

docfx/doxygen2yaml.cc, docfx/doxygen2yaml_test.cc
TIL: we can classify functions as operators or constructors
https://github.com/googleapis/doc-pipeline/blob/89a368af73590e34f052072adbf46676acc9c626/third_party/docfx/templates/devsite/UniversalReference.common.js#L377
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11454)
=> impl(docfx): better classification for functions

google/cloud/spanner/testing/pick_instance_config.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11461)
=> test(spanner): avoid `europe-west9`

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/table.cc, google/cloud/bigquery/v2/minimal/internal/table.h, google/cloud/bigquery/v2/minimal/internal/table_constraints.h, google/cloud/bigquery/v2/minimal/internal/table_partition.h, google/cloud/bigquery/v2/minimal/internal/table_schema.cc, google/cloud/bigquery/v2/minimal/internal/table_schema.h, google/cloud/bigquery/v2/minimal/internal/table_test.cc, google/cloud/bigquery/v2/minimal/internal/table_view.cc, google/cloud/bigquery/v2/minimal/internal/table_view.h
This PR contains custom classes for the Bigquery v2 Table resource. Json parsing and unit tests are included.
Since the pattern was the same as following in JOb and Dataset resource I included all related files int the same PR.
Thanks in advance for the review!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11438)
=> impl(bigquery): Custom classes for Table resource

CHANGELOG.md, google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/storage/tests/curl_request_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11480)
=> fix(rest): missing user-agent separator

docfx/doxygen2syntax.cc, docfx/function_classifiers.cc, docfx/function_classifiers.h, docfx/function_classifiers_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11487)
=> impl(docfx): more helpers to classify functions

release/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11492)
=> docs: improve patch release how-to

doc/adr/2023-05-03-patch-releases-are-ABI-compatible.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11491)
=> docs: stronger guarantees for patch releases

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/table_request.cc, google/cloud/bigquery/v2/minimal/internal/table_request.h, google/cloud/bigquery/v2/minimal/internal/table_request_test.cc, google/cloud/bigquery/v2/minimal/internal/table_view.cc, google/cloud/bigquery/v2/minimal/internal/table_view.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11490)
=> impl(bigquery): Table request classes with unit tests

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_testing.bzl, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/dataset_response_test.cc, google/cloud/bigquery/v2/minimal/internal/table_response.cc, google/cloud/bigquery/v2/minimal/internal/table_response.h, google/cloud/bigquery/v2/minimal/internal/table_response_test.cc, google/cloud/bigquery/v2/minimal/internal/table_test.cc, google/cloud/bigquery/v2/minimal/testing/table_test_utils.cc, google/cloud/bigquery/v2/minimal/testing/table_test_utils.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11500)
=> impl(bigquery): Table response classes with unit tests

ci/cloudbuild/builds/lib/integration.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11505)
=> ci(storage): upgrade to storage-testbench v0.36.0

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/dataset_request.cc, google/cloud/bigquery/v2/minimal/internal/job_request.cc, google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.cc, google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h, google/cloud/bigquery/v2/minimal/internal/rest_stub_utils_test.cc, google/cloud/bigquery/v2/minimal/internal/table_request.cc
Refactored the common rest endpoint methods used by table, dataset and job resource.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11504)
=> impl(bigquery): refactor/cleanup of endpoint methods

google/cloud/bigtable/row_reader.cc, google/cloud/bigtable/row_reader.h, google/cloud/bigtable/row_reader_test.cc
Part of the work for #11508
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11509)
=> impl(bigtable): call context for RowReader

ci/cloudbuild/builds/lib/integration.sh, google/cloud/sql/integration_tests/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11511)
=> impl(sql): enable integration tests

google/cloud/bigtable/internal/bigtable_stub_factory.cc, google/cloud/bigtable/internal/bigtable_stub_factory_test.cc
Part of the work for #11508
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11510)
=> impl(bigtable): include tracing stub

WORKSPACE.bazel, bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/centos-7.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cmake.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cxx14.Dockerfile, ci/cloudbuild/dockerfiles/fedora-37-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11514)
=> chore(deps): update benchmark to v1.8.0

google/cloud/bigquery/v2/minimal/internal/dataset_rest_stub_factory.cc
Added the creating of Dataset logging client to the Stub factory
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11526)
=> impl(bigquery): Dataset StubFactory changes

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_testing.bzl, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/table_response_test.cc, google/cloud/bigquery/v2/minimal/internal/table_rest_stub.cc, google/cloud/bigquery/v2/minimal/internal/table_rest_stub.h, google/cloud/bigquery/v2/minimal/internal/table_rest_stub_factory.cc, google/cloud/bigquery/v2/minimal/internal/table_rest_stub_factory.h, google/cloud/bigquery/v2/minimal/internal/table_rest_stub_test.cc, google/cloud/bigquery/v2/minimal/testing/mock_table_rest_stub.h, google/cloud/bigquery/v2/minimal/testing/table_test_utils.cc, google/cloud/bigquery/v2/minimal/testing/table_test_utils.h
Rest stub, stub factory implementation and unit tests for Table resource
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11525)
=> impl(bigquery): Table stub and stub factory classes

google/cloud/bigtable/internal/data_tracing_connection.cc, google/cloud/bigtable/internal/data_tracing_connection_test.cc
Part of the work for #11508
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11540)
=> impl(bigtable): tracing for ReadRows

google/cloud/bigquery/bigquery_rest.cmake, google/cloud/bigquery/bigquery_rest_unit_tests.bzl, google/cloud/bigquery/google_cloud_cpp_bigquery_rest.bzl, google/cloud/bigquery/v2/minimal/internal/common_options.h, google/cloud/bigquery/v2/minimal/internal/job_options.cc, google/cloud/bigquery/v2/minimal/internal/table_idempotency_policy.cc, google/cloud/bigquery/v2/minimal/internal/table_idempotency_policy.h, google/cloud/bigquery/v2/minimal/internal/table_idempotency_policy_test.cc, google/cloud/bigquery/v2/minimal/internal/table_options.cc, google/cloud/bigquery/v2/minimal/internal/table_options.h, google/cloud/bigquery/v2/minimal/internal/table_options_test.cc, google/cloud/bigquery/v2/minimal/internal/table_retry_policy.h
Ah...sorry, Creating this pull request again since I deleted this branch by mistake.
Carlos, can you reapprove please? I'll see if I can merge it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11544)
=> impl(bigquery): Table options and policies

google/cloud/bigtable/internal/async_bulk_apply_test.cc, google/cloud/bigtable/testing/mock_policies.h, google/cloud/internal/grpc_request_metadata.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11552)
=> cleanup: use gRPC include paths that are more amenable to rewriting

google/cloud/opentelemetry/trace_exporter.cc, google/cloud/opentelemetry/trace_exporter_test.cc
Part of the work for #11156
By design the exporter cannot block execution. Provide some visibility into its failures by logging them at the WARNING level.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11553)
=> impl(otel): trace exporter logs on failure

google/cloud/bigtable/internal/data_tracing_connection.cc, google/cloud/bigtable/internal/data_tracing_connection_test.cc
Part of the work for #11508 
Arguably we are not adding any value by adding an attribute for `row_found`. (applications and other libraries have visibility into that already). But whatever. These things are easy to remove.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11554)
=> impl(bigtable): tracing for single row reads

google/cloud/bigtable/internal/data_tracing_connection.cc, google/cloud/bigtable/internal/data_tracing_connection_test.cc
Part of the work for #11508 
I considered adding span events for each read, but decided against it because:
- there will probably be too many events to be useful.
- the row keys might be too long for Cloud Trace anyway
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11558)
=> impl(bigtable): tracing for AsyncReadRows

google/cloud/bigtable/data_connection.cc, google/cloud/bigtable/data_connection_test.cc
Fixes #11508
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11559)
=> impl(bigtable): include DataTracingConnection

google/cloud/bigquery/v2/minimal/internal/table_rest_stub_factory.cc
Added logging and metadata client creation to Table Stub Factory. Fixes #[11527](https://github.com/googleapis/google-cloud-cpp/issues/11527)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11567)
=> impl(bigquery): Table Stub Factory changes

google/cloud/beyondcorp/appconnections/v1/.repo-metadata.json, google/cloud/beyondcorp/appconnectors/v1/.repo-metadata.json, google/cloud/beyondcorp/appgateways/v1/.repo-metadata.json, google/cloud/beyondcorp/clientconnectorservices/v1/.repo-metadata.json, google/cloud/beyondcorp/clientgateways/v1/.repo-metadata.json
Part of the work #11519 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11570)
=> chore(beyondcord): backfill `.repo-metadata.json`

google/cloud/bigquery/analyticshub/v1/.repo-metadata.json, google/cloud/bigquery/connection/v1/.repo-metadata.json, google/cloud/bigquery/datapolicies/v1/.repo-metadata.json, google/cloud/bigquery/datatransfer/v1/.repo-metadata.json, google/cloud/bigquery/migration/v2/.repo-metadata.json, google/cloud/bigquery/reservation/v1/.repo-metadata.json, google/cloud/bigquery/storage/v1/.repo-metadata.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11571)
=> chore(bigquery): backfill `.repo-metadata.json` files

google/cloud/accessapproval/v1/.repo-metadata.json, google/cloud/accesscontextmanager/v1/.repo-metadata.json, google/cloud/advisorynotifications/v1/.repo-metadata.json, google/cloud/alloydb/v1/.repo-metadata.json, google/cloud/apigateway/v1/.repo-metadata.json, google/cloud/apigeeconnect/v1/.repo-metadata.json, google/cloud/apikeys/v2/.repo-metadata.json, google/cloud/appengine/v1/.repo-metadata.json, google/cloud/artifactregistry/v1/.repo-metadata.json, google/cloud/asset/v1/.repo-metadata.json, google/cloud/assuredworkloads/v1/.repo-metadata.json, google/cloud/automl/v1/.repo-metadata.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11575)
=> chore(a*): backfill `.repo-metadata.json` files

google/cloud/webrisk/v1/.repo-metadata.json, google/cloud/websecurityscanner/v1/.repo-metadata.json, google/cloud/workflows/executions/v1/.repo-metadata.json, google/cloud/workflows/v1/.repo-metadata.json, google/cloud/workstations/v1/.repo-metadata.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11574)
=> chore(w*): backfill `.repo-metadata.json` files

generator/internal/scaffold_generator.cc, google/cloud/advisorynotifications/v1/.repo-metadata.json, google/cloud/alloydb/v1/.repo-metadata.json, google/cloud/beyondcorp/appconnections/v1/.repo-metadata.json, google/cloud/beyondcorp/appconnectors/v1/.repo-metadata.json, google/cloud/beyondcorp/appgateways/v1/.repo-metadata.json, google/cloud/beyondcorp/clientconnectorservices/v1/.repo-metadata.json, google/cloud/beyondcorp/clientgateways/v1/.repo-metadata.json, google/cloud/bigquery/analyticshub/v1/.repo-metadata.json, google/cloud/bigquery/connection/v1/.repo-metadata.json, google/cloud/bigquery/datapolicies/v1/.repo-metadata.json, google/cloud/bigquery/datatransfer/v1/.repo-metadata.json, google/cloud/bigquery/migration/v2/.repo-metadata.json, google/cloud/bigquery/reservation/v1/.repo-metadata.json, google/cloud/bigquery/storage/v1/.repo-metadata.json, google/cloud/bigtable/.repo-metadata.json, google/cloud/confidentialcomputing/v1/.repo-metadata.json, google/cloud/datacatalog/v1/.repo-metadata.json, google/cloud/kms/inventory/v1/.repo-metadata.json, google/cloud/pubsub/.repo-metadata.json, google/cloud/spanner/.repo-metadata.json, google/cloud/storage/.repo-metadata.json, google/cloud/storageinsights/v1/.repo-metadata.json, google/cloud/support/v2/.repo-metadata.json, google/cloud/workstations/v1/.repo-metadata.json
I misread the PRD (or the follow up PRD) for these fields.
Part of the work for #11519, fixes #11580
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11581)
=> fix(generator): bad `.repo-metadata.json` fields

ci/cloudbuild/builds/publish-docs.sh
Part of the work for #11430
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11582)
=> ci: upload more library documentation

google/cloud/bigtable/internal/async_bulk_apply.cc, google/cloud/bigtable/internal/async_bulk_apply.h, google/cloud/bigtable/internal/async_bulk_apply_test.cc
Part of the work for #11585
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11590)
=> impl(bigtable): AsyncBulkApply traced backoffs

docfx/doxygen2toc.cc, docfx/doxygen2toc_test.cc, docfx/doxygen2yaml.cc, docfx/doxygen2yaml_test.cc
Fixes #11588 
Fixes #11587 
Fixes #11586 
Fixes #11583
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11592)
=> impl(docfx): use `NodeName()` in contents and ToC

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11578)
=> doc: guarantees for env vars and telemetry data

google/cloud/baremetalsolution/v2/.repo-metadata.json, google/cloud/batch/v1/.repo-metadata.json, google/cloud/billing/budgets/v1/.repo-metadata.json, google/cloud/billing/v1/.repo-metadata.json, google/cloud/binaryauthorization/v1/.repo-metadata.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11595)
=> chore(b*): backfill `.repo-metadata.json` files

google/cloud/certificatemanager/v1/.repo-metadata.json, google/cloud/channel/v1/.repo-metadata.json, google/cloud/cloudbuild/v1/.repo-metadata.json, google/cloud/cloudbuild/v2/.repo-metadata.json, google/cloud/composer/v1/.repo-metadata.json, google/cloud/connectors/v1/.repo-metadata.json, google/cloud/contactcenterinsights/v1/.repo-metadata.json, google/cloud/container/v1/.repo-metadata.json, google/cloud/containeranalysis/v1/.repo-metadata.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11596)
=> chore(c*): backfill `.repo-metadata.json` files

google/cloud/talent/v4/.repo-metadata.json, google/cloud/tasks/v2/.repo-metadata.json, google/cloud/texttospeech/v1/.repo-metadata.json, google/cloud/tpu/v1/.repo-metadata.json, google/cloud/tpu/v2/.repo-metadata.json, google/cloud/trace/v1/.repo-metadata.json, google/cloud/trace/v2/.repo-metadata.json, google/cloud/translate/v3/.repo-metadata.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11597)
=> chore(t*): backfill `.repo-metadata.json` files

google/cloud/bigtable/internal/async_row_reader.cc, google/cloud/bigtable/internal/async_row_reader.h, google/cloud/bigtable/internal/async_row_reader_test.cc
Fixes #11585
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11599)
=> impl(bigtable): AsyncReadRows traced backoffs

README.md, google/cloud/trace/CMakeLists.txt, google/cloud/trace/README.md, google/cloud/trace/doc/main.dox, google/cloud/trace/doc/options.dox, google/cloud/trace/quickstart/CMakeLists.txt, google/cloud/trace/quickstart/Makefile, google/cloud/trace/quickstart/README.md, google/cloud/trace/quickstart/WORKSPACE.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11598)
=> doc(trace): Cloud Trace, not Stackdriver Trace

docfx/public_docs.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11611)
=> impl(docfx): skip absl:: symbols

google/cloud/datacatalog/lineage/v1/.repo-metadata.json, google/cloud/datamigration/v1/.repo-metadata.json, google/cloud/dataplex/v1/.repo-metadata.json, google/cloud/dataproc/v1/.repo-metadata.json, google/cloud/datastream/v1/.repo-metadata.json, google/cloud/debugger/v2/.repo-metadata.json, google/cloud/deploy/v1/.repo-metadata.json, google/cloud/dialogflow_cx/.repo-metadata.json, google/cloud/dialogflow_es/.repo-metadata.json, google/cloud/dlp/v2/.repo-metadata.json, google/cloud/documentai/v1/.repo-metadata.json
Part of the work for #11519 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11600)
=> chore(d*): backfill `.repo-metadata.json` files

google/cloud/policytroubleshooter/v1/.repo-metadata.json, google/cloud/privateca/v1/.repo-metadata.json, google/cloud/profiler/v2/.repo-metadata.json, google/cloud/pubsublite/.repo-metadata.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11608)
=> chore(p*): backfill `.repo-metadata.json` files

google/cloud/scheduler/v1/.repo-metadata.json, google/cloud/secretmanager/v1/.repo-metadata.json, google/cloud/securitycenter/v1/.repo-metadata.json, google/cloud/servicecontrol/v1/.repo-metadata.json, google/cloud/servicecontrol/v2/.repo-metadata.json, google/cloud/servicedirectory/v1/.repo-metadata.json, google/cloud/servicemanagement/v1/.repo-metadata.json, google/cloud/serviceusage/v1/.repo-metadata.json, google/cloud/shell/v1/.repo-metadata.json, google/cloud/speech/v1/.repo-metadata.json, google/cloud/speech/v2/.repo-metadata.json, google/cloud/sql/v1/.repo-metadata.json, google/cloud/storagetransfer/v1/.repo-metadata.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11601)
=> chore(s*): backfill `.repo-metadata.json` files

google/cloud/recommender/v1/.repo-metadata.json, google/cloud/redis/v1/.repo-metadata.json, google/cloud/resourcemanager/v3/.repo-metadata.json, google/cloud/resourcesettings/v1/.repo-metadata.json, google/cloud/retail/v2/.repo-metadata.json, google/cloud/run/v2/.repo-metadata.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11606)
=> chore(r*): backfill `.repo-metadata.json` files
