googleapis/google-cloud-cpp

google/cloud/storage/CMakeLists.txt, google/cloud/storage/bucket_metadata.h, google/cloud/storage/google_cloud_cpp_storage.bzl, google/cloud/storage/internal/bucket_acl_requests.cc, google/cloud/storage/internal/bucket_acl_requests.h, google/cloud/storage/internal/bucket_requests.cc, google/cloud/storage/internal/bucket_requests.h, google/cloud/storage/internal/default_object_acl_requests.cc, google/cloud/storage/internal/default_object_acl_requests.h, google/cloud/storage/internal/object_acl_requests.cc, google/cloud/storage/internal/object_acl_requests.h, google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/patch_builder.cc, google/cloud/storage/internal/patch_builder.h, google/cloud/storage/internal/patch_builder_details.h, google/cloud/storage/internal/patch_builder_test.cc, google/cloud/storage/object_metadata.h
So far we have been using strings to represent "patch" requests. For
JSON this works, just store the string representation of a JSON patch.
For gRPC this will not work anymore, we need the actual patch to compute
the corresponding gRPC request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8122)
=> impl(storage): make patch objects accessible

CHANGELOG.md
Related to: https://github.com/googleapis/google-cloud-cpp/pull/8095
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8131)
=> doc: add notice about Bazel version to CHANGELOG

google/cloud/storage/client.h, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/object_requests_test.cc, google/cloud/storage/tests/object_basic_crud_integration_test.cc
After all these years, we were missing some options for
`storage::Client::PatchObject()`.  They were in the documentation, but
trying to use them would have resulted in a compilation error.
Part of the work for #4195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8137)
=> fix(storage): add missing options for PatchObject()

google/cloud/storage/internal/grpc_client.cc
I do not know of a good way to write unit tests or integration tests to
verify the timeout and other attributes are set in each gRPC call. But
while I think about that, might as well fix the places where I missed
them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8143)
=> fix(GCS+gRPC): missing `grpc::ClientContext` set up

ci/kokoro/macos/common.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8150)
=> ci: increase default timeout for macOS builds

google/cloud/storage/CMakeLists.txt, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl
Add unit tests to verify the context, or at least the system parameters,
are set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8151)
=> test(GCS+gRPC): verify context setup in GrpcClient

google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h
The intent of handling a response by first writing all bytes to the spill buffer was to enable the status code and headers to be interrogated via the `RestResponse` class, without having to read all the bytes in the response body. The initial implementation was based on the model that libcurl would write all of CURLOPT_BUFFERSIZE bytes at once into the spill buffer. This was incorrect and in order to handle multiple writes to the spill buffer new monitoring of when the status line and headers were received was added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8157)
=> fix(rest): initial partial read could overflow spill buffer

generator/generator_config.textproto, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc
Fixes #4195.  Note that gRPC combines the `PatchObject()` and `UpdateObject()` RPCs into a single RPC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8142)
=> feat(GCS+gRPC): implement `PatchObject()`

cmake/CompileProtos.cmake
Update the helper functions in CMake to support `INTERFACE` proto
libraries. `INTERFACE` libraries have no filesystem artifacts, there is
no `-l...` option required for them.  They are useful when you want to
create a new name for a CMake target without breaking compatibility, or
when you want to group multiple targets.  They are also useful for
header-only libraries, but that is not the case here.
I am planning to use this feature for Cloud Trace, Cloud Monitoring, and
Text-to-Speech.  All of these have proto libraries in
`external/googleapis`, I can create new libraries for these protos in
`google/cloud/${service}`, but I do not want to introduce potential ODR
violations.
--- …
=> impl(cmake): support interface proto libraries

google/cloud/texttospeech/CMakeLists.txt
We had two libraries that compiled the same proto files.  That was a
recipe to create ODR violations.  With this PR one of the libraries
depends on the other, avoiding the duplicates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8169)
=> fix(texttospeech): remove duplicate protos

generator/integration_tests/golden/internal/golden_kitchen_sink_connection_impl.cc, generator/integration_tests/golden/streaming.cc, generator/internal/connection_impl_generator.cc, google/cloud/logging/CMakeLists.txt, google/cloud/logging/README.md, google/cloud/logging/google_cloud_cpp_logging.bzl, google/cloud/logging/internal/logging_service_v2_connection_impl.cc, google/cloud/logging/internal/streaming.cc
This changes the generator to **not** emit the body of the bidirectional streaming RPC.  There are very few services that need these RPCs, many are hand-crafted in full, many need a very unique implementation for this function, some do not need a retry / resume loop at all.
We will be implementing these functions by hand, in a `internal/streaming.cc` file (or similar).  In this PR only the golden files and `google/cloud/logging` are affected.  I am not implementing interesting versions of the function body, that will come in separate PRs.
Part of the work for #7795.  I added some TODO entries to prevent accidentally declaring GA for the logging library.
--- …
=> feat(generator): always hand-craft bidir streaming body

google/cloud/storage/client.h, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/object_requests_test.cc
Add missing option (and tests) for `storage::Client::CopyObject()`.
Part of the work for #4199
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8171)
=> fix(storage): missing option for CopyObject()

google/cloud/storage/client.h, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/object_requests_test.cc
I missed `DestinationKmsKeyName` as an option for
`storage::Client::CopyObject()`.  I checked twice for any other missing
options, but then again, I thought I had checked twice already.
Part of the work for #4199 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8188)
=> fix(storage): missing kms key option in CopyObject()

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc
Fixes #4199 . Note that no new `*Stub` operations are needed because there is no `CopyObject()` in gRPC, we need to emulate the existing call using `RewriteObject()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8190)
=> feat(GCS+gRPC): implement CopyObject()

google/cloud/bigtable/metadata_update_policy_test.cc, google/cloud/bigtable/table.h, google/cloud/bigtable/table_test.cc
Related to #5934
We have customers that use our `Table` clients to interact with tables spread across various instances and projects. Because the project and instance ids are stored in the `DataClient`, the customer is forced to create multiple connections, which is redundant and slow. While this issue will be addressed as part of the effort to modernize the Data API, that will take time. This PR doesn't hurt, and it adds value now.
This PR stores the project and instance ids in the `Table`. Customers can now produce a copy of a `Table` with a modified resource name, without needing to make a new connection to the service.
```cc
// Old code
auto t1 = Table(MakeDataClient("project-1", "instance-A"), "table-X");
auto t2 = Table(MakeDataClient("project-2", "instance-B"), "table-Y"); // …
```
=> feat(bigtable): cheap Table creation with different resource name

CHANGELOG.md
I thought the list looked better with things like "Cloud Vision" listed under "C" instead of "V".
Names are in accordance with:
https://cloud.google.com/guides/style/branding-list
The following names  were not obvious. I used my best judgment.
* Anthos GKE API
* Compute Engine OS Config
* Compute Engine OS Login
* Retail
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8189)
=> docs: introduce new libraries

google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/instance_admin_test.cc, google/cloud/bigtable/table_admin.h, google/cloud/bigtable/table_admin_test.cc
Same thing as #8172, but with the Admin clients.
`InstanceAdmin` has been converted. If you use the `Connection` classes with it, you don't need this function. I still think its fine to add the function now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8194)
=> feat(bigtable): cheap Admin creation with different resource names

ci/kokoro/windows/build-bazel.ps1
Remove some code to troubleshoot full disk problems. These problems have
been resolved for a while, and the checks are very slow on my
workstation. If the problems ever come back, we can add these back. Note
that the somewhat faster checks in `ci/kokoro/windows/build.ps1` are
still there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8202)
=> ci: speedup local Windows builds

generator/integration_tests/golden/golden_thing_admin_client.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_client_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_client_test.cc, generator/internal/client_generator.cc, google/cloud/bigtable/admin/bigtable_instance_admin_client.cc, google/cloud/bigtable/admin/bigtable_table_admin_client.cc, google/cloud/billing/cloud_billing_client.cc, google/cloud/containeranalysis/container_analysis_client.cc, google/cloud/iam/iam_client.cc, google/cloud/iot/device_manager_client.cc, google/cloud/resourcemanager/folders_client.cc, google/cloud/securitycenter/security_center_client.cc, google/cloud/spanner/admin/database_admin_client.cc, google/cloud/spanner/admin/instance_admin_client.cc, google/cloud/tasks/cloud_tasks_client.cc
Fix `Options` handling in the generated OCC-loop `SetIamPolicy()`
overloads.  We were failing to pass the operation options through
to the sub-`GetIamPolicy()`/`SetIamPolicy()` calls.  Continuing to
call back into the client layer from the OCC loop is suboptimal
however, as we would need to make a copy of the `Options` only to
create new `OptionsSpan`s with the same values.  So, call through
to the connection layer directly, avoiding the need to deal with
`Options` at all.
Then add tests, for each variety of generated RPC, to check that
options are correctly propagated and overridden through connection,
client, and operation layers.
--- …
=> fix(generator): fix options handling in SetIamPolicy() OCC loop

google/cloud/BUILD.bazel, google/cloud/bigtable/benchmarks/BUILD.bazel, google/cloud/storage/BUILD.bazel, google/cloud/storage/benchmarks/BUILD.bazel, google/cloud/storage/tests/BUILD.bazel, google/cloud/testing_util/BUILD.bazel
The former is the preferred way to specify platforms. Note that in the
testing_util case, I dropped the support for freebsd and openbsd. I'm
not sure why those cases were there or if we need them. We don't seem to
have those cases elsewhere. I can add them back if they are needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8207)
=> cleanup: prefer @platforms rather than @bazel_tools

CHANGELOG.md
I added entries for `Cloud Tasks` and `Secret Manager`, as they are now GA. (even though their content is identical to `Bigquery`, `IAM`). This will not scale when we declare the new libraries GA.
This PR does not show up in the CHANGELOG. Should it?
* feat(pubsublite): add TopicStats service ([#7966](https://github.com/googleapis/google-cloud-cpp/pull/7966))
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8208)
=> doc: update CHANGELOG for v1.36.0 release

google/cloud/iam/samples/iam_samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8204)
=> docs(iam): added comments on private_key_data

ci/cloudbuild/builds/lib/integration.sh
Yes, two of these in one day.  I should have just skipped the update to v0.13.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8223)
=> chore(deps): update storage testbench to v0.14.0

generator/internal/scaffold_generator.cc
Obviously this is not ideal, but it is better than waiting for renovate bot after each new library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8224)
=> chore(generator): update generated workspace file

google/cloud/storage/internal/grpc_client_test.cc
This seems to do the trick on Windows.  My previous change made faster on Linux, but seems to have little or no effect on the Windows builds.  I claim a :monkey:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8230)
=> test(GCS+gRPC): speed up grpc_client_test, take 2

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/connection.cc, google/cloud/spanner/connection.h, google/cloud/spanner/google_cloud_cpp_spanner.bzl
We think pure virtual functions are a recipe to break backwards
compatibility as we add member functions, so, in order to make such
future additions consistent, we now give the existing functions
default implementations that all fail with `kUnimplemented`.
Fixes #5336.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8237)
=> cleanup(spanner): make the spanner::Connection interface non-pure

ci/cloudbuild/build.sh
I tested locally, when the `docker build` step fails we get the full output. If it succeeds we get only the SHA of the created image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8238)
=> ci: hide docker output for manual builds

ci/cloudbuild/builds/check-api.sh, ci/cloudbuild/builds/cmake-install.sh, ci/cloudbuild/builds/demo-install.sh, ci/cloudbuild/builds/install-gcs-grpc.sh, ci/cloudbuild/builds/shared.sh, doc/packaging.md
With all the new libraries this steps eats too many lines in my
terminal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8241)
=> ci: quiet the cmake install steps

ci/cloudbuild/builds/shared.sh, cmake/quickstart-runner.cmake, doc/contributor/howto-guide-adding-generated-libraries.md, generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator_test.cc, google/cloud/filestore/CMakeLists.txt
This PR introduces scripts to run the quickstart programs in all
generated libraries. It also changes the scaffold to generate these new
fragments in the generated `CMakeLists.txt` and `BUILD.bazel` files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8221)
=> ci: bootstrap quickstart runners

ci/kokoro/macos/builds/bazel.sh, ci/kokoro/macos/builds/quickstart-bazel.sh, ci/kokoro/windows/build-bazel.ps1, ci/kokoro/windows/build-quickstart-bazel.ps1
I am hoping this will reduce the impact of #3645
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8242)
=> ci: reduce Bazel's remote cache timeout

google/cloud/storage/oauth2/credential_constants.h
In the client library, OAuth tokens are currently cached until they have 500s of time remaining. However, as per [public documentation](https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances), "The metadata server caches access tokens until they have 5 minutes of remaining time..."
This leaves a 200s-window in which RefreshingCredentialsWrapper objects can repeatedly attempt to refresh credentials from the metadata server, but receive the same token each time. 
This pull request corrects the value of slack from 500s to 300s to prevent this from happening.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8255)
=> fix(oauth2): use correct expiration slack value

bazel/google_cloud_cpp_deps.bzl, google/cloud/asset/BUILD.bazel, google/cloud/assuredworkloads/BUILD.bazel, google/cloud/channel/BUILD.bazel
Perhaps misleadingly, the list of constraints provided to
`target_compatible_with` form a conjunction: all these constraints must
be satisfied for the rule to be compatible:
> A list of constraint_values that **must** be present
https://docs.bazel.build/versions/main/be/common-definitions.html#common.target_compatible_with
What wanted to do in all cases was to exclude one platform, and
fortunately Bazel provides `@platforms//:incompatible` for that purpose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8257)
=> fix: correct uses of `target_compatible_with`

google/cloud/composer/CMakeLists.txt, google/cloud/composer/README.md, google/cloud/composer/quickstart/quickstart.cc, google/cloud/contactcenterinsights/CMakeLists.txt, google/cloud/gkehub/CMakeLists.txt, google/cloud/gkehub/README.md, google/cloud/gkehub/quickstart/quickstart.cc, google/cloud/ids/CMakeLists.txt, google/cloud/ids/README.md, google/cloud/ids/quickstart/quickstart.cc, google/cloud/kms/CMakeLists.txt, google/cloud/logging/CMakeLists.txt, google/cloud/memcache/CMakeLists.txt, google/cloud/redis/CMakeLists.txt, google/cloud/scheduler/CMakeLists.txt, google/cloud/scheduler/README.md, google/cloud/scheduler/quickstart/quickstart.cc, google/cloud/tpu/CMakeLists.txt, google/cloud/tpu/README.md, google/cloud/tpu/quickstart/quickstart.cc, google/cloud/vmmigration/CMakeLists.txt, google/cloud/vmmigration/README.md, google/cloud/vmmigration/quickstart/quickstart.cc
Another pass cleaning up quickstart programs and adding them to the CI
builds.
I know I am not being very systematic on these, maybe I should be sending one PR per quickstart or something.  But I think speed is more important than carefully curated code archaeological records in this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8254)
=> fix: make quickstarts run and add to CI

ci/lib/run_gcs_httpbin_emulator_utils.sh, google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh, google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
We use `curl` to create a couple of buckets in the storage testbench.
With this change the curl invocations are silent on success.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8262)
=> ci: silence storage testbench set up

.gitignore
This directory is created by clangd when indexing source code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8263)
=> chore: gitignore .cache dir

ci/cloudbuild/builds/lib/integration.sh, ci/cloudbuild/builds/publish-docs.sh
To continue the effort to eliminate uninteresting build output,
and particularly when it is highlighted somehow, quash the "You
are using pip version X; however, version Y is available" warning.
Also, we might as well skip installing the docuploader package
when we're going to skip uploading the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8261)
=> ci: pass the --disable-pip-version-check flag to "pip install"

ci/cloudbuild/builds/checkers.sh, ci/cloudbuild/dockerfiles/checkers.Dockerfile
This upgrades us to the newest version of typos-cli. The previous
version we were using (1.3.1) was also broken, but we didn't notice
because I think all of our `gcb-checkers` docker images had an old
version that worked. Aside: I think somehow the cached docker images
don't get invalidated properly.
Anyway, the string "ba" showed up as a typo (in the old and new
version). I changed it to "bx", which I think makes the word weird
enough that `typos` doesn't flag it as a typo. I also upgrade to a newer
version of typos to make sure all the docker images get rebuilt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8267)
=> chore: upgrade and fix typos-cli

google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h
Instead of trying detect by ourselves when the status and all headers have been received, rely on libcurl to signal that via the first call to WriteCallback. libcurl will invoke HeaderCallback up until that point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8268)
=> fix(rest): correct detection of all headers received

.clang-tidy
Newer versions of clang-tidy include the
`readability-identifier-length`, which complains if identifiers names
are too short. This is really annoying and it would warn us on things
like:
```cc
auto x = 123;
```
This needs to be disabled.
https://clang.llvm.org/extra/clang-tidy/checks/readability-identifier-length.html#:~:text=This%20check%20finds%20variables%20and,and%20for%20exception%20variable%20names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8269)
=> chore: allow short identifiers

ci/cloudbuild/builds/lib/integration.sh, ci/kokoro/macos/build.sh, ci/kokoro/macos/builds/cmake-vcpkg.sh, ci/kokoro/macos/builds/quickstart-bazel.sh, ci/kokoro/macos/builds/quickstart-cmake.sh
Turns out there are more steps in both the Bazel and CMake builds that
needed deflaking. Also preemptively improve retry loop in the general
integration test script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8287)
=> ci: deflake macOS Bazel builds

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc
The underlying RPC is already generated, so this did not need any
changes to the `*Stub` classes.
Fixes #4196
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8278)
=> feat(GCS+gRPC): implement `UpdateObject()`

google/cloud/bigtable/benchmarks/endurance_benchmark.cc, google/cloud/internal/curl_impl.cc, google/cloud/internal/non_constructible.h, google/cloud/internal/status_payload_keys.cc, google/cloud/internal/status_payload_keys.h, google/cloud/storage/internal/logging_resumable_upload_session_test.cc, google/cloud/storage/internal/retry_resumable_upload_session.cc
These were fixed using a new clang-format with
`--qualifier-alignment=right`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8289)
=> chore: fix west->east const

google/cloud/internal/rest_client.cc, google/cloud/internal/rest_client.h, google/cloud/internal/rest_client_integration_test.cc
This adds an overload to RestClient::Post that accepts a collection of key/value pairs representing form data. The values of each pair are x-www-form-urlencoded and the all pairs are assembled into a payload such `key1=value1&key2=value2&keyN=valueN`. This addition was the result of preserving the libcurl encapsulation in `CurlImpl` and `curl_easy_escape` requiring an easy handle as an argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8291)
=> impl(rest): add POST with form_data method

google/cloud/internal/async_long_running_operation_test.cc, google/cloud/internal/async_polling_loop.cc, google/cloud/internal/async_polling_loop_test.cc, google/cloud/internal/async_retry_loop.h, google/cloud/internal/async_retry_loop_test.cc, google/cloud/internal/pagination_range_test.cc, google/cloud/internal/retry_loop_test.cc, google/cloud/stream_range.h, google/cloud/stream_range_test.cc
Save the options in force during `StreamRange<T>` construction,
and then restore them over `internal::StreamReader<T>` callbacks.
This means that streaming/paginated operations will have the right
options installed during all their RPCs.
As well as adding tests to check this behavior for `StreamRange`
and `MakePaginationRange`, also add checks to verify the matching,
existing behavior for `RetryLoop`, `AsyncLongRunningOperation`,
and `AsyncPollingLoop`.
Fixes #8248.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8256)
=> fix: add Options save/restore to StreamRange<T>

google/cloud/asset/CMakeLists.txt, google/cloud/asset/README.md, google/cloud/asset/quickstart/quickstart.cc
Querying all the assets in our test project takes 2.5 minutes, and it
will only get slower. I made the quickstart a little more complicated,
but runs faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8318)
=> test(asset): enable quickstart in CI

google/cloud/pubsub/samples/samples.cc
Use the existing example, it does what we want it just needed the right
region tags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8326)
=> doc(pubsub): add region tag for subscription with filter

google/cloud/bigtable/admin_client.cc, google/cloud/bigtable/data_client.cc, google/cloud/bigtable/internal/defaults.cc, google/cloud/bigtable/internal/defaults_test.cc
Part of the work for #8284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8324)
=> feat(bigtable): support x-goog-user-project

google/cloud/bigtable/admin_client.cc, google/cloud/bigtable/admin_client.h, google/cloud/bigtable/table_admin.h, google/cloud/bigtable/table_admin_test.cc
Part of the work for #7530 
The analog of #8061, but for `TableAdmin`. The main differences are that:
1. `TableAdmin` requires a CQ, whereas `InstanceAdmin` did not.
2. In `InstanceAdmin`, I added a new public constructor that takes in a Connection class ([code](https://github.com/googleapis/google-cloud-cpp/blob/089d318a9d630ebab12d9736dadd59c5f99a1df0/google/cloud/bigtable/instance_admin.h#L130-L134)). I thought this was needed for cheap `InstanceAdmin` creation, with a different project id. Now we get cheap client creation via the `WithNewTarget()` methods. So making the new constructor public is unnecessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8 …
=> impl(bigtable): table admin connection logic

google/cloud/bigtable/instance_admin_test.cc, google/cloud/bigtable/internal/logging_admin_client.h, google/cloud/bigtable/table_admin_test.cc
`AdminClient` is in a transition state. The base class has these non pure virtual functions: https://github.com/googleapis/google-cloud-cpp/blob/6b6de2af1a62972a1e0144e2d4d7c2448d956294/google/cloud/bigtable/admin_client.h#L298-L305
I did not realize that the `AdminClient` in certain tests was a `LoggingAdminClient`, which called the non-pure base function and returned a `nullptr` for a connection. This escaped my tests which only checked that two connections were equal.
Soon, `LoggingAdminClient` will be deleted. But for now, I will have it return the `DefaultAdminClient`s CQ and Connection, so my tests will pass in this transition state.
--- …
=> cleanup(bigtable): silly test cleanup

ci/cloudbuild/builds/quickstart-production.sh, ci/cloudbuild/triggers/quickstart-production-ci.yaml, ci/cloudbuild/triggers/quickstart-production-pr.yaml, ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh, google/cloud/bigquery/CMakeLists.txt, google/cloud/bigtable/CMakeLists.txt, google/cloud/iam/CMakeLists.txt, google/cloud/iam/README.md, google/cloud/iam/quickstart/quickstart.cc, google/cloud/pubsub/CMakeLists.txt, google/cloud/spanner/CMakeLists.txt, google/cloud/storage/CMakeLists.txt
I was hijacking the `shared` build to run the quickstart programs. This
moves the running of those programs to their own build, and adds drivers
for any quickstarts that predate the effort to run generated
quickstarts. It seems simpler to have one mechanism to run all of them.
Part of the work for #6221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8342)
=> ci: run the quickstarts in their own build

ci/cloudbuild/build.sh
Since version 18, docker has an improved build engine called "buildkit",
that we can optionally enable by setting an environment variable.
AFAIKT, this new building engine is strictly better, and in particular
its output is much less verbose, but is still very informative about
what is happening and the progress being made. For example, the output
from a clean build of the `gcb-checkers` image is:
```
2022-02-11T15:31:02Z (+0s)
--------------------------------------------------
|   Building docker image: gcb-checkers:latest   |
--------------------------------------------------
2022-02-11T15:31:02Z (+0s): + docker build -t gcb-checkers:latest --build-arg=NCPU=96 -f ci/cloudbuild/dockerfiles/checkers.Dockerfile ci
[+] Building 214.5s (12/12) FINISHED
=> [internal] load build definition …
```
=> ci: use DOCKER_BUILDKIT

ci/cloudbuild/build.sh
Outputting the links to log files with a leading asterisk will make them
paste into GH issues as two bullets, which will be a bit nicer to read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8349)
=> chore: log links are bulleted lines

google/cloud/storage/examples/CMakeLists.txt
I have a different version of MSVC compared to the version used in CI.
The tests do not compile without `/bigobj`, and presumably this affects
customers too.  We probably should enable that option for all tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8357)
=> test(storage): workaround MSVC limits

CMakeLists.txt
We have not needed the `OPENSSL_ROOT_DIR` environment variable set for a
long time, since we stopped doing super builds of gRPC at least.
Turn the message to a `WARNING`, as ee do recommend setting the CMake
variable of the same name on Apple, because the default OpenSSL is not
functional.
Let CMake format the message because it does a better job: it uses the
terminal width to break lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8358)
=> doc: update stale warnings for macOS

ci/cloudbuild/builds/integration-production.sh
This will reduce the noise caused by some integration tests that are
flaking too much.
Workaround for #8128
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8363)
=> ci: cache test results in `integration-production`

google/cloud/spanner/internal/partial_result_set_source.cc, google/cloud/spanner/internal/partial_result_set_source.h, google/cloud/spanner/internal/partial_result_set_source_test.cc, google/cloud/spanner/results.h
Save the options in force during `PartialResultSetSource` construction,
and then restore them over `PartialResultSetReader` calls.  This means
that `NextRow()`, `Finish()` and `TryCancel()` will have the right
options installed during any RPCs they execute.
Tighten up the test by installing a non-matching `OptionsSpan` before
any `NextRow()` calls are made, and by expecting no `TryCancel()`s in
cases that complete their enumeration.
This is the Spanner equivalent of #8256.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8355)
=> fix(spanner): add Options save/restore to PartialResultSetSource

google/cloud/bigtable/admin_client.cc, google/cloud/bigtable/internal/admin_client_params.cc, google/cloud/bigtable/internal/admin_client_params.h, google/cloud/bigtable/internal/admin_client_params_test.cc
Simplify the logic a bit. It is an invariant of the struct that the `options` field will have the `GrpcCompletionQueueOption` set. (we test for this). So there is no need to have a separate `cq` field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8366)
=> cleanup(bigtable): simplify admin client params

google/cloud/oslogin/CMakeLists.txt, google/cloud/shell/CMakeLists.txt
I think the best we can do for these services is run them, and verify we
get some kind of error.
These services are intended for *users* to retrieve their preferences
from GCP.  They cannot be used from service accounts, and only the user
can access their preferences.  That all sounds fine. Our integration
tests authenticate with a service account (as they should), and thus
cannot retrieve their own preferences (they are not a user). Even if we
created a demo or fake user, the service accounts cannot access the
preferences for such users, and I do not think we would want to do that
anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-c …
=> test: enable oslogin and shell quickstarts in CI

google/cloud/accesscontextmanager/CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8373)
=> test(accesscontextmanager): enable quickstart in CI

ci/cloudbuild/builds/checkers.sh
In a preview branch we may have merged a `googleapis.patch` file
to support a new feature that uses unreleased protos.  This patch
file often has lines that contain a single space because there are
empty context lines in the diff.  We do not want to trim those
trailing spaces, so exclude `googleapis.patch` from the process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8374)
=> ci: exclude any googleapis.patch from whitespace fixing

google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/instance_admin_test.cc, google/cloud/bigtable/table_admin.h, google/cloud/bigtable/table_admin_legacy_test.cc, google/cloud/bigtable/table_admin_test.cc, google/cloud/spanner/query_partition.h, google/cloud/spanner/query_partition_test.cc, google/cloud/spanner/read_partition.h, google/cloud/spanner/read_partition_test.cc
I am not labeling this as a breaking change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8377)
=> cleanup: move friend tester classes into internal

google/cloud/bigtable/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/bigtable/instance_admin.cc, google/cloud/storage/client.h, google/cloud/storage/internal/logging_client.cc, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/list_objects_and_prefixes_reader_test.cc, google/cloud/storage/list_objects_reader_test.cc, google/cloud/storage/parallel_upload.h, google/cloud/storage/tests/object_write_streambuf_integration_test.cc
Note that `extra_state_arg` in `storage/parallel_upload.h` is an `absl::optional<>`, not a `StatusOr<>`. I am pretty sure we still want to change it though.
The one in `storage/client.h` I made look like all the other returns, e.g.: https://github.com/googleapis/google-cloud-cpp/blob/31819a04430bca3c0d782e09695787d832144983/google/cloud/storage/client.h#L1747
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8387)
=> cleanup: use operator* instead of value for OK StatusOr's

google/cloud/storage/bucket_metadata.cc, google/cloud/storage/bucket_metadata_test.cc
Patching and updating buckets was ignoring some lifecycle condition
fields.
Motivated by #4162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8389)
=> fix(storage): ignored fields in lifecycle patches

google/cloud/bigtable/examples/table_admin_snippets.cc
Fixes #7740 
Technically, this issue was closed by #8383, which resolved the lifetime issues by holding the background threads in `TableAdmin`, outside the `AsyncWaitForConsistencyImpl`. But we still needed to clean up the deflaking sleep in the test.
Also, simplify the printing of the output. It is now impossible to return an OK Status, that is `kInconsistent`. We [return a polling loop exhausted error](https://github.com/googleapis/google-cloud-cpp/blob/8cbde8d0217159156c20634c46f5ef8027f3dbfc/google/cloud/bigtable/internal/wait_for_consistency.cc#L104-L105) instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8393)
=> cleanup(bigtable): remove sleep from table_admin_snippets

CMakeLists.txt, cmake/GoogleCloudCppCommon.cmake, google/cloud/bigquery/CMakeLists.txt, google/cloud/bigtable/CMakeLists.txt, google/cloud/examples/CMakeLists.txt, google/cloud/iam/CMakeLists.txt, google/cloud/pubsub/CMakeLists.txt, google/cloud/spanner/CMakeLists.txt, google/cloud/storage/CMakeLists.txt
This will allow us to add examples to a generated library, without
having to modify the generated `CMakeLists.txt` file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8392)
=> refactor: include examples from top-level CMake

google/cloud/internal/curl_impl.cc, google/cloud/internal/rest_client.cc, google/cloud/internal/rest_client_test.cc
Some GCP services are very particular how the Host header is formatted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8391)
=> fix(rest): formating headers

google/cloud/future_generic.h, google/cloud/future_generic_test.cc, google/cloud/future_void.h, google/cloud/future_void_test.cc, google/cloud/internal/utility.h
When the value type of a future is convertible to the value type of another, this allows the futures to interconvert.
This is useful with, for example, make_ready_future, where one could return `make_ready_future(absl::nullopt)` for a return type of `future<absl::optional<Result>>`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8329)
=> feat(common): Add converting constructors for future

google/cloud/internal/resumable_streaming_read_rpc_test.cc, google/cloud/internal/streaming_read_rpc_test.cc, google/cloud/internal/streaming_write_rpc_test.cc, google/cloud/stream_range.h, google/cloud/stream_range_test.cc
Restore the creation-time `Options` in the `StreamRange<T>` destructor
while explicitly clearing the `reader_` functor.  If the reader has not
reached the end of the range, then deleting it may send a best-effort,
out-of-band cancel on the call, and we should restore the options when
re-entering the library.  Add a test for the destructor case.  This is
a followup to #8256.
Also take this opportunity to delete some unused type aliases I stumbled
upon during this work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8403)
=> fix: restore Options over deletion of StreamRange<T>::reader_

google/cloud/pubsub/schema_admin_client.cc, google/cloud/pubsub/schema_admin_client.h, google/cloud/pubsub/schema_admin_client_test.cc, google/cloud/pubsub/schema_admin_connection.cc, google/cloud/pubsub/schema_admin_connection.h
Part of the work #7689
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8406)
=> feat(pubsub): per-call options in SchemaAdminClient

google/cloud/pubsub/schema_admin_connection.cc, google/cloud/pubsub/schema_admin_connection.h
I removed the implementation by accident. It looked unused, and I
thought it was in the `pubsub_internal` namespace.  Good thing I caught
this before the release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8412)
=> fix(pubsub): restore MakeSchemaAdminConnection overload

google/cloud/completion_queue_test.cc
As the comment says the checks were not needed. They were probably overly optimistic and lead to flakes.
Fixes #5440 (again?)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8410)
=> test(common): deflake completion queue test

google/cloud/pubsub/topic_admin_client.cc, google/cloud/pubsub/topic_admin_client.h, google/cloud/pubsub/topic_admin_client_test.cc, google/cloud/pubsub/topic_admin_connection.cc, google/cloud/pubsub/topic_admin_connection.h
Part of the work for #7689
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8411)
=> feat(pubsub): per-call options in TopicAdminClient

CHANGELOG.md
Who reviewed #8418 ??? 🤦‍♂️
I think we should continue linking to our libraries instead of linking to the cloud service documentation.
I think because BigQuery is GA, anything we add to it is also GA. This means the new services. I think we should just list their addition under the BigQuery changes.
Also there is the question of `speech`. I removed it because I don't think that it belongs. The section says "we do not anticipate any API changes to these libraries before declaring them GA". I think our intention is to add more user friendly APIs before declaring `speech` GA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8422)
=> cleanup: touch up CHANGELOG

google/cloud/bigtable/async_row_reader.h, google/cloud/bigtable/async_row_reader_test.cc, google/cloud/bigtable/row_reader.cc, google/cloud/bigtable/row_reader_test.cc
Fixes #8321 
Thank you to @liujiongxin for the report and the fix!
The bigtable tests are old and use things like `FakeCompletionQueueImpl` instead of the newer `MockCompletionQueueImpl`. I am not going to modernize the tests right now.
Both tests borrow heavily from the basic retry tests (immediately above them) in the test fixtures. They just add one more `Read()` that returns an empty chunk with the `last_scanned_row_key` set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8423)
=> fix(bigtable): ReadRows retries from the `last_scanned_row_key`

google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_options.h, google/cloud/internal/oauth2_compute_engine_credentials.cc, google/cloud/internal/oauth2_compute_engine_credentials_test.cc, google/cloud/internal/oauth2_google_credentials_test.cc
Querying the gce metadata needs to be a GET instead of a POST and must be able to follow redirects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8421)
=> fix(oauth2): compute engine credential query

google/cloud/storage/bucket_metadata.h, google/cloud/storage/object_metadata.h
The documentation was not rendering correctly. It was reusing the
description from one function to many unrelated functions. In addition,
the groups were also rendering incorrectly.
After re-reading the Doxygen documentation it seems that
```cc
/// @name Group description
///@{
... grouped member functions
///@}
```
Is the "Right Thing":tm:
Fixes #8429.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8434)
=> doc(storage): improve `{Bucket,Object}Metadata` docs

google/cloud/bigtable/admin_client.cc, google/cloud/bigtable/admin_client.h, google/cloud/bigtable/table_admin.h
Part of the work for #8419 
This makes the intent of the API much clearer. The class is no longer meant to be extended. But any code using the factory functions will continue to work.
I removed pure virtual functions but I am not calling this a breaking change, because it has not been released yet. The `InstanceAdminClient` version of this is a different story.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8424)
=> refactor(bigtable): simplify AdminClient

google/cloud/storage/internal/access_control_common_parser.cc, google/cloud/storage/internal/access_control_common_parser_test.cc
We are working on google-cloud integration for our project [Apache Nifi Minifi CPP](https://github.com/apache/nifi-minifi-cpp)
And I found that the `projectTeam` is an optional field in the `ObjectMetadata` json, however it will crash if it is present but null.
This makes impossible to make integration tests using the [fake-gcs-server](https://github.com/fsouza/fake-gcs-server), because the response to a ResumableUploadRequest is something like this due to the datastructure in [google-cloud-go](https://github.com/googleapis/google-cloud-go/blob/main/storage/acl.go#L60)
```
{
"bucket":"my-bucket",
"name":"my-key",
"contentType":"",
"contentEncoding":"",
"acl":[
{
"entity":"projectOwner",
"entityId":"",
"role":"OWNER",
"domain":"",
"email":"",
"projectTeam":null
}
], …
```
=> fix(storage): json["projectTeam"] might be present but null

google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_result.cc, google/cloud/storage/benchmarks/throughput_result.h, google/cloud/storage/benchmarks/throughput_result_test.cc
For the most part this just creates a placeholder to report the transfer
size. While the transfer size and object size could be different in case
of (unrecoverable) errors during download, the real motivation is to
support partial downloads in a future PR.
Fixes #4349
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8447)
=> cleanup(storage): report transfer size in benchmark

CHANGELOG.md, google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/instance_admin_client.cc, google/cloud/bigtable/instance_admin_client.h
Fixes #8419
The `InstanceAdmin` equivalent of #8424. I also added a note in the changelog, because this is technically a break since the last release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8449)
=> refactor(bigtable)!: mark InstanceAdminClient as final

google/cloud/internal/oauth2_authorized_user_credentials.cc, google/cloud/internal/oauth2_compute_engine_credentials.cc, google/cloud/internal/oauth2_refreshing_credentials_wrapper.cc, google/cloud/internal/oauth2_refreshing_credentials_wrapper.h, google/cloud/internal/oauth2_refreshing_credentials_wrapper_test.cc, google/cloud/internal/oauth2_service_account_credentials.cc
fixes #8288
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8445)
=> refactor(oauth2): add current time injection point for testing

google/cloud/bigtable/internal/defaults.cc, google/cloud/bigtable/internal/defaults_test.cc
An unnecessary change. I just like it slightly better if we only default `UserProjectOption` for the Data API, and let the generated `Connection`s do the defaulting for the Admin APIs. I plan to do the same for the incoming `AuthorityOption`.
My thinking in general is that `bigtable::internal::DefaultOptions()` should only mimic the default configuration from the old `bigtable::ClientOptions`. Also I think that isolating these temporary defaults in `DefaultDataOptions` will make things easier to clean up when the Data API is modernized (some time this century).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8455)
=> refactor(bigtable): only default UserProjectOption for Data API

google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h, google/cloud/internal/curl_rest_client.cc, google/cloud/internal/curl_rest_client.h, google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/internal/oauth2_authorized_user_credentials.cc, google/cloud/internal/oauth2_compute_engine_credentials.cc, google/cloud/internal/oauth2_minimal_iam_credentials_rest.cc, google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/internal/rest_client.h, google/cloud/internal/unified_rest_credentials_integration_test.cc
1.
https://github.com/googleapis/google-cloud-cpp/blob/541eb09c32c91c09ea84a55fc0861e916ebec56a/google/cloud/internal/curl_impl.h#L40-L42
declares a static object (i.e., internal linkage) in a header. We
want to avoid that because it can lead to ODR issues. See
https://abseil.io/tips/140 for more details.
2.
https://github.com/googleapis/google-cloud-cpp/blob/541eb09c32c91c09ea84a55fc0861e916ebec56a/google/cloud/internal/rest_client.h#L38-L44
These factory functions should be named "Make..." not "Get...". For
functions that create things, we use the verb "Make", which follows
the standard's naming (e.g., make_pair).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-c …
=> cleanup: rest client style cleanups

google/cloud/pubsub/internal/default_batch_sink.cc, google/cloud/pubsub/internal/default_batch_sink.h, google/cloud/pubsub/internal/publisher_metadata.cc, google/cloud/pubsub/internal/publisher_metadata_test.cc, google/cloud/pubsub/internal/schema_metadata.cc, google/cloud/pubsub/internal/schema_metadata_test.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source.h, google/cloud/pubsub/internal/subscriber_metadata.cc, google/cloud/pubsub/internal/subscriber_metadata_test.cc
Change the metadata decorators to inject `x-goog-user-project` from the
current option span.
For the admin APIs, use the per-call options to configure a span in the
`*Client` class.  For `pubsub::Publisher` and `pubsub::Subscriber` it is
less clear which call "triggers" an RPC, and far less clear how to merge
options from multiple RPCs.  I have decided to use the per-connection
options in this case. We can always add more fine-grained options later,
but this takes care of the common case.
Part of the work for #8284 and will help with #3317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8456)
=> feat(pubsub): support x-goog-user-project

google/cloud/pubsub/internal/publisher_metadata.cc, google/cloud/pubsub/internal/subscriber_metadata.cc
By default use `pubsub.googleapis.com` as the `authority` in all
requests, regardless of the `EndpointOption` value.  This improves the
support for PSC and VPC-SC.
Part of the work for #3317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8460)
=> feat(pubsub): support `AuthorityOption`

google/cloud/bigtable/data_client.cc, google/cloud/bigtable/internal/defaults.cc, google/cloud/bigtable/internal/defaults_test.cc
The bigtable part of #3317 
Also, there was an oopsies for the `user_project_`. One reason we did not catch it is because there are no tests for `DataClient::ApplyOptions()`. I just fixed the bug, without adding any tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8458)
=> feat(bigtable): better support for PSC and VPC-SC

google/cloud/internal/rest_options.h, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_client_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc
If present, use the `AuthorityOption` to configure the `Host: ` header
or the `.set_authority()` attribute in `grpc::ClientContext`. By
default, configure `AuthorityOption` to be `storage.googleapis.com`,
applications can override this when initializing the `storage::Client`.
There is already an issue open to add per-call `Options` that would
provide more fine-grained control of this field.
Fixes #3317.  I am adding a node to #8164 because we will need to undo some of this work to support per-call options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8462)
=> feat(storage): support AuthorityOption

CHANGELOG.md, google/cloud/spanner/internal/connection_impl.cc
Allow the prevailing `Options` to override the connection options
for the retry/backoff policies and RPC tracing parameters, so that
any per-operation options are heeded.
This is the final step in fixing #7690, so announce that users
should now prefer to use `Options` on all Spanner client calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8466)
=> feat(spanner): use prevailing Options in ConnectionImpl

ci/cloudbuild/builds/check-api.sh
I meant to remove the `;` at the beginning of the enabled services list.
It is harmless, but untidy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8469)
=> ci: cleanup check-api GOOGLE_CLOUD_CPP_ENABLE value

CMakeLists.txt
Recent commits broke the possibility to use the project with CMake as an ExternalProject(FetchContent in my case).
In https://github.com/googleapis/google-cloud-cpp/commit/f4c898f47838dffade2f0cdf4a182e0347a34612 and https://github.com/googleapis/google-cloud-cpp/commit/14a0ad2bf1574a87277778b2b146a80672872ccb in the root CMakeLists.txt the folder structure is checked relative to CMAKE_SOURCE_DIR which works if the project is standalone, however if used as an external project CMAKE_SOURCE_DIR refers to the topmost project's source dir.
I suggest we change these to CMAKE_CURRENT_SOURCE_DIR since `add_subdirectory` already works relative to that.
--- …
=> fix: use CMAKE_CURRENT_SOURCE_DIR instead of CMAKE_SOURCE_DIR

google/cloud/CMakeLists.txt, google/cloud/google_cloud_cpp_common_benchmarks.bzl, google/cloud/options.h, google/cloud/options_benchmark.cc
With the growing ubiquity of `Options`, it seems like a good
idea to keep an eye on its performance.  To that end, add a
micro benchmark which can be expanded as we see fit.  For now,
simply benchmark `get<T>()` performance on both present and
default option types.
Time:
The original motivation for this PR was removing the function-
static synchronization from the "present" path, however the
benchmark indicates that this is only a slight win (<0.5%),
and it seems to cost us a similar amount in the "default"
path.  At least it makes those cases similar in performance,
which is a good thing given that it is unclear which is more
common.  (I guess it is also a good thing to confirm that
function-static synchronization is fast.)
Space:
Template the allocation of the default value for an …
=> impl: a benchmark and two small (non-)optimizations for Options

google/cloud/storage/grpc_plugin.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/storage_stub_factory.cc
With the new backend for Google Direct Access (aka Direct Path) it is
easier to configure gRPC.  I also made it possible to configure the
plugin using `google::cloud::Options`.  Some of these changes are not
backwards compatible, but this is an experimental component.
Motivated by #3398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8488)
=> cleanup(GCS+gRPC)!: simplify plugin configuration

google/cloud/container/CMakeLists.txt
Fixes #8491 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8492)
=> fix(container): missing CMake dependency

google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/benchmarks/benchmark_utils.h, google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_experiment.h, google/cloud/storage/benchmarks/throughput_experiment_test.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc, google/cloud/storage/benchmarks/throughput_result.cc, google/cloud/storage/benchmarks/throughput_result.h, google/cloud/storage/benchmarks/throughput_result_test.cc
Change the existing throughput_vs_cpu benchmark to compare gRPC and
gRPC+DirectPath side-by-side.  Add peer information when available.
This will need some more work, but it is a good change as-is.  Motivated by #3398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8489)
=> feat(GCS+gRPC): benchmark with Direct Path

google/cloud/pubsublite/internal/resumable_async_streaming_read_write_rpc.h, google/cloud/pubsublite/internal/resumable_async_streaming_read_write_rpc_test.cc
When `Shutdown` is called on the resumable stream, `Cancel` should be called on the underlying stream when it's in a valid state to cancel any outstanding operations that might not finish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8498)
=> fix(pubsublite): Cancel in Shutdown

google/cloud/pubsublite/internal/resumable_async_streaming_read_write_rpc.h, google/cloud/pubsublite/internal/resumable_async_streaming_read_write_rpc_test.cc
param should always be default constructed object anyway
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8506)
=> cleanup(pubsublite): remove param from Write

google/cloud/storage/benchmarks/throughput_experiment.cc
The download benchmarks were skipping the last successful `read()`.
Motivated by #3398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8512)
=> test(storage): correct download size in benchmark

google/cloud/storage/benchmarks/throughput_result.cc, google/cloud/storage/benchmarks/throughput_result_test.cc
Replace any commas, newlines, and carriage returns in message strings
with semicolons. This seems to work better with the Python parser for
CSV files than quoting the value.
Motivated by  #3398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8513)
=> test(storage): simplify benchmark output

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
Add command-line options to control the endpoints in the throughput
benchmarks. This is useful as the direct path endpoint name changes
depending on the gRPC version, and it helps troubleshooting too.
Also fixed a number of nits in the output.
Part of the work for #3398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8514)
=> test(storage): command-line options for benchmark endpoints

google/cloud/storage/client.cc, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client.h, google/cloud/storage/internal/retry_client_test.cc, google/cloud/storage/internal/retry_object_read_source_test.cc
Instances of this class must always be created in the heap and managed
via `std::shared_ptr<>`.  Use a factory function to create them.
Fixes #3026
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8518)
=> cleanup(storage): no public constructor for RetryClient

google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_result.cc, google/cloud/storage/benchmarks/throughput_result.h, google/cloud/storage/benchmarks/throughput_result_test.cc
Add a timestamp to each benchmark result. I will use this to plot the
performance over time.
Part of the work for #3398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8519)
=> test(GCS+gRPC): timestamp benchmark results

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc
I am starting to run benchmarks that take hours to complete.  Sometimes
it is desirable to capture partial results from these benchmarks to
debug the analysis scripts, or even run preliminary analysis. With this
change the throughput-vs-cpu benchmark streams its results as it runs,
instead of printing the results at the end of the test.
Motivated by #3398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8520)
=> test(storage): stream benchmark results

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/internal/logging_result_set_reader.cc, google/cloud/spanner/internal/logging_result_set_reader.h, google/cloud/spanner/internal/logging_result_set_reader_test.cc, google/cloud/spanner/internal/partial_result_set_reader.h, google/cloud/spanner/internal/partial_result_set_resume.cc, google/cloud/spanner/internal/partial_result_set_resume.h, google/cloud/spanner/internal/partial_result_set_resume_test.cc, google/cloud/spanner/internal/partial_result_set_source.cc, google/cloud/spanner/internal/partial_result_set_source_test.cc, google/cloud/spanner/testing/mock_partial_result_set_reader.h
Problems:
- A `google::spanner::v1::PartialResultSet` may not contain
a `resume_token` when it also does not complete a new row,
so `last_resume_token_` should not be updated in that case.
- When `PartialResultSetResume::Read()` uses its factory and
`last_resume_token_` to create a new `PartialResultSetReader`,
it should inform the `PartialResultSetSource` so that any
partly-constructed row can be discarded before processing
the resumed stream (which will resend that row).
That is, a "resume token" is really a row iterator, and a level
above row fragmentation and value chunking. So fix all of that.
Then expand the `ConnectionImplTest.ReadSuccess` test case to
exercise the new code paths.
--- …
=> fix(spanner): correct handling of PartialResultSet.resume_token

generator/internal/scaffold_generator.cc, google/cloud/accessapproval/doc/main.dox
the scaffold variables were unused. and `accessapproval` had some spanner specific documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8524)
=> cleanup: scaffold

google/cloud/bigtable/CMakeLists.txt
Part of the work for #8533
(the other parts are verifying the fix and releasing a new library version)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8534)
=> test(bigtable): add missing dep

google/cloud/storage/CMakeLists.txt
Fixes #8533
The storage part. Thanks to @tobim for identifying the fix in [this comment](https://github.com/googleapis/google-cloud-cpp/issues/8533#issuecomment-1065934624).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8535)
=> test(storage): add google_cloud_cpp_testing dep

CHANGELOG.md, CMakeLists.txt, ci/cloudbuild/builds/clang-tidy.sh, ci/cloudbuild/builds/lib/cmake.sh
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/6767
Rather than us explicitly setting (defaulting) `CMAKE_CXX_STANDARD=11`, we leave it unset and rely on the compiler's default C++ language standard. This will let customers more easily build w/ the "correct" standard for their platform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8537)
=> feat!: let CMAKE_CXX_STANDARD remain unset

generator/internal/descriptor_utils.cc
Fixes: #8244
I was not able to reproduce the warning on my M1 Mac, but I'm pretty sure this
change would be the fix for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8541)
=> fix: compiler warning from generator

ci/kokoro/macos/builds/cmake-vcpkg.sh
This makes it easier to build the code and run the tests on macos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8542)
=> ci: skip quickstarts on macos when no credentials

google/cloud/pubsub/ci/lib/pubsub_emulator.sh, google/cloud/spanner/ci/lib/spanner_emulator.sh
Loop 60 times (up from 12) while waiting to see the "listening on"
message from the pubsub emulator log.
For both pubsub and spanner emit the "Cannot determine port" error
message with a timestamp, so that it is easy to see just how long
we waited.
Finally, for spanner, dump the emulator log when we fail to find a
port, so that we might have some idea of what went wrong.
Fixes #8539.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8545)
=> ci: wait longer for the pubsub emulator to start listening

google/cloud/spanner/testing/random_backup_name.cc, google/cloud/spanner/testing/random_database_name.cc
PostgreSQL identifiers cannot contain hyphens, so, rather than making
things conditional on the database dialect, it's easier to simply refrain
from using hyphens in generated database/backup names altogether.
Temporarily we still match hyphens in RandomDatabasePrefixRegex() so
that CleanupStaleDatabases() will garbage collect both varieties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8547)
=> test(spanner): restrict generated database/backup names for compat

ci/cloudbuild/dockerfiles/checkers.Dockerfile
It appears that even the checkers build needs the patch command
when the com_google_googleapis `patch_tool = "patch"` is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8549)
=> ci: add patch to the checkers docker image

BUILD.bazel, ci/cloudbuild/builds/check-api.sh, ci/generate-markdown/generate-readme.sh
Since #3701 says we want users to only use top-level build targets like
`//:foo`, we need to expose the targets from our
`google/cloud/BUILD.bazel` file.
I'm happy to bikeshe the target names here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8552)
=> feat: expose build targets for common libraries

google/cloud/pubsub/ci/lib/pubsub_emulator.sh, google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh, google/cloud/spanner/ci/lib/spanner_emulator.sh, google/cloud/spanner/ci/run_integration_tests_emulator_bazel.sh
- Add a `-s` (`--no-messages`) flag to the quiet grep for the
"listening on" in emulator logfile, which will suppress any
`grep: emulator.log: No such file or directory` message
should we be looking before the logfile actually exists.
- Discard the `popd` output (`/workspace`) after starting the
emulator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8554)
=> ci: discard some uninteresting emulator-test output

ci/cloudbuild/cloudbuild.yaml
Related to #6438
This might (or might not) fix the rare kaniko flakes we see. But I
imagine it almost certainly cannot hurt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8558)
=> ci: enable retries for kaniko

google/cloud/BUILD.bazel, google/cloud/bigquery/integration_tests/BUILD.bazel, google/cloud/bigquery/samples/BUILD.bazel, google/cloud/bigtable/BUILD.bazel, google/cloud/bigtable/admin/integration_tests/BUILD.bazel, google/cloud/bigtable/benchmarks/BUILD.bazel, google/cloud/bigtable/examples/BUILD.bazel, google/cloud/bigtable/tests/BUILD.bazel, google/cloud/examples/BUILD.bazel, google/cloud/grpc_utils/BUILD.bazel, google/cloud/iam/samples/BUILD.bazel, google/cloud/logging/integration_tests/BUILD.bazel, google/cloud/pubsub/BUILD.bazel, google/cloud/pubsub/benchmarks/BUILD.bazel, google/cloud/pubsub/integration_tests/BUILD.bazel, google/cloud/pubsub/samples/BUILD.bazel, google/cloud/spanner/BUILD.bazel, google/cloud/spanner/admin/integration_tests/BUILD.bazel, google/cloud/spanner/benchmarks/BUILD.bazel, google/cloud/spanner/integration_tests/BUILD.bazel, google/cloud/spanner/samples/BUILD.bazel, google/cloud/storage/BUILD.bazel, google/cloud/storage/benchmarks/BUILD.bazel, google/cloud/storage/examples/BUILD.bazel, google/cloud/storage/tests/BUILD.bazel, google/cloud/testing_util/BUILD.bazel
Part of: #3701
We want users to only use targets in the top-level //BUILD.bazel file.
Very likely nobody is using these targets even right now. But a 90+ day
deprecation would be nice. We could extend this to a year if people feel
that's necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8550)
=> cleanup: mark google/cloud/ bazel targets as deprecated

ci/cloudbuild/builds/clang-tidy.sh
The `pubsublite` directory contains hand-crafted code and should be
checked with `clang-tidy`. Incidentally this regenerates all the `.bzl`
files, so we can check for differences as part of this build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8560)
=> ci: more hand-crafted code to clang-tidy build

google/cloud/BUILD.bazel, google/cloud/bigquery/integration_tests/BUILD.bazel, google/cloud/bigquery/samples/BUILD.bazel, google/cloud/bigtable/BUILD.bazel, google/cloud/bigtable/admin/integration_tests/BUILD.bazel, google/cloud/bigtable/benchmarks/BUILD.bazel, google/cloud/bigtable/examples/BUILD.bazel, google/cloud/bigtable/tests/BUILD.bazel, google/cloud/examples/BUILD.bazel, google/cloud/iam/samples/BUILD.bazel, google/cloud/logging/integration_tests/BUILD.bazel, google/cloud/pubsub/BUILD.bazel, google/cloud/pubsub/benchmarks/BUILD.bazel, google/cloud/pubsub/integration_tests/BUILD.bazel, google/cloud/pubsub/samples/BUILD.bazel, google/cloud/spanner/BUILD.bazel, google/cloud/spanner/admin/integration_tests/BUILD.bazel, google/cloud/spanner/benchmarks/BUILD.bazel, google/cloud/spanner/integration_tests/BUILD.bazel, google/cloud/spanner/samples/BUILD.bazel, google/cloud/storage/BUILD.bazel, google/cloud/storage/benchmarks/BUILD.bazel, google/cloud/storage/examples/BUILD.bazel, google/cloud/storage/tests/BUILD.bazel, google/cloud/testing_util/BUILD.bazel
Reverts googleapis/google-cloud-cpp#8550
Reverting because this causes too many deprecation warnings in our own builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8561)
=> Revert "cleanup: mark google/cloud/ bazel targets as deprecated"

google/cloud/storage/internal/object_write_streambuf.cc, google/cloud/storage/internal/object_write_streambuf_test.cc
Very rarely the retry policy is exhausted during an upload. If this
happens when the last request was a query to find the status of the
upload the `UploadChunk()` succeeds with a short write.
We need to determine if that is a good idea (it might be). In the
interim, we need to signal to the application that the stream is no
longer usable. They can use `.Suspend()` to reset the stream (maybe in
another process) if that can be useful.
Part of the work for #8559
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8562)
=> fix(storage): return an error on short writes

google/cloud/future_coroutines_test.cc, google/cloud/internal/future_coroutines.h, google/cloud/internal/port_platform.h
Applications can disable coroutine support by adding
`-DGOOGLE_CLOUD_CPP_HAVE_COROUTINES=0` to the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8571)
=> feat(common): make coroutine support optional

google/cloud/bigquery/integration_tests/BUILD.bazel, google/cloud/bigquery/quickstart/BUILD.bazel, google/cloud/bigquery/samples/BUILD.bazel, google/cloud/bigtable/admin/integration_tests/BUILD.bazel, google/cloud/bigtable/benchmarks/BUILD.bazel, google/cloud/bigtable/examples/BUILD.bazel, google/cloud/bigtable/quickstart/BUILD.bazel, google/cloud/bigtable/tests/BUILD.bazel, google/cloud/examples/BUILD.bazel, google/cloud/iam/quickstart/BUILD.bazel, google/cloud/iam/samples/BUILD.bazel, google/cloud/logging/integration_tests/BUILD.bazel, google/cloud/pubsub/benchmarks/BUILD.bazel, google/cloud/pubsub/integration_tests/BUILD.bazel, google/cloud/pubsub/quickstart/BUILD.bazel, google/cloud/pubsub/samples/BUILD.bazel, google/cloud/spanner/admin/integration_tests/BUILD.bazel, google/cloud/spanner/benchmarks/BUILD.bazel, google/cloud/spanner/integration_tests/BUILD.bazel, google/cloud/spanner/samples/BUILD.bazel, google/cloud/storage/benchmarks/BUILD.bazel, google/cloud/storage/examples/BUILD.bazel, google/cloud/storage/quickstart/BUILD.bazel, google/cloud/storage/tests/BUILD.bazel
Part of #3701 
These changes are only affecting whole BUILD files that are in a directory that is obviously not intended to be part of a user-facing API. These are (integration) tests, examples, samples, benchmarks, and quickstarts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8578)
=> cleanup!: change bazel visibility to private for {tests,quickstarts,examples,samples,benchmarks}

google/cloud/pubsub/BUILD.bazel, google/cloud/pubsub/benchmarks/BUILD.bazel, google/cloud/pubsub/integration_tests/BUILD.bazel, google/cloud/pubsub/samples/BUILD.bazel
Part of #3701
Marks all PubSub BUILD targets as private by default. cc_test targets
that were previously public are now private. The
`//google/cloud/pubsub:pubsub_client_testing` target was never
intended to be public and is now deprecated to be deleted in about a
year.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8582)
=> cleanup!: deprecate public pubsub bazel targets

google/cloud/storage/BUILD.bazel
Part of #3701
The target `//google/cloud/storage:google_cloud_cpp_storage_grpc` became
non-public, but it was experimental so it didn't need to be
deprecated.
All `cc_test` targets became private.
The `//google/cloud/storage:storage_client_testing` target remains
public.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8583)
=> cleanup!: change storage bazel visibility to private by default

google/cloud/bigtable/benchmarks/BUILD.bazel, google/cloud/pubsub/BUILD.bazel, google/cloud/pubsub/benchmarks/BUILD.bazel, google/cloud/spanner/BUILD.bazel, google/cloud/spanner/benchmarks/BUILD.bazel, google/cloud/storage/BUILD.bazel, google/cloud/storage/benchmarks/BUILD.bazel
With Bazel we need to treat benchmarks as binaries, otherwise
`bazel run` behaves poorly: it merges `stdout` and `stderr`, and
injects extra output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8579)
=> cleanup: use `cc_binary()` for benchmarks

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/integration_tests/client_integration_test.cc
Extend existing tests to also cover `database_dialect`by setting it
in the CreateDatabaseRequest, and expecting it in Database and Backup
responses.  Include allowances for these being invisible to the Spanner
emulator, and for pending bug #8573.
In particular, BackupIntegrationTest.BackupRestore leaves the dialect
unspecified in CreateDatabase() (but expects to see GOOGLE_STANDARD_SQL
in responses), while it is set explicitly to GOOGLE_STANDARD_SQL in
DatabaseAdminClientTest.VersionRetentionPeriodCreate, and to POSTGRESQL
in BackupExtraIntegrationTest.BackupRestoreWithCMEK.
DatabaseAdminClientTest.DatabasePostgreSQLBasics is a new test case
that also exercises the non-backup parts of an explicit POSTGRESQL
setting.
[Aside: These are only in the tests for the generated database admin …
=> feat(spanner): integration tests for Database.database_dialect

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc
Parsing from some protos related to resumable upload sessions was not
well tested.  With some refactoring it all looks good now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8588)
=> refactor(GCS+gRPC): parsing for `ResumableUploadResponse`

google/cloud/spanner/samples/samples.cc
The C++ Cloud Spanner client was the one that used the specified tag
for the CopyBackup() sample.  Someone else got it wrong originally it
seems, and then the remaining languages just copied that.
The easiest path forward was to change the specification, so this now
brings the C++ sample into line with the new reality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8615)
=> test(spanner): change CopyBackup() sample tag

ci/cloudbuild/builds/lib/integration.sh
While investigating the Werkzeug issue, I came across this tiny
inconsistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8619)
=> cleanup(ci): make the REST test banner the same for bazel/cmake

google/cloud/spanner/samples/CMakeLists.txt, google/cloud/spanner/samples/pg_samples.cc, google/cloud/spanner/samples/postgresql_samples.cc, google/cloud/spanner/samples/spanner_client_integration_samples.bzl
These samples are sufficiently different from the "Google Standard"
dialect ones that they deserve their own source file (not to mention
that `samples.cc` is becoming unmanageable).  If there ends up being
any significant commonality between the samples implementations, we
can factor it out later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8617)
=> feat(spanner): add initial PostgreSQL samples

BUILD.bazel, generator/BUILD.bazel, google/cloud/bigtable/BUILD.bazel, google/cloud/bigtable/benchmarks/BUILD.bazel, google/cloud/bigtable/examples/BUILD.bazel, google/cloud/pubsub/BUILD.bazel, google/cloud/pubsub/benchmarks/BUILD.bazel, google/cloud/pubsub/samples/BUILD.bazel, google/cloud/pubsublite/BUILD.bazel, google/cloud/spanner/BUILD.bazel, google/cloud/spanner/benchmarks/BUILD.bazel, google/cloud/storage/BUILD.bazel, google/cloud/storage/benchmarks/BUILD.bazel, google/cloud/storage/examples/BUILD.bazel, google/cloud/testing_util/BUILD.bazel
Use the bazel testonly attribute to ensure that test code does not
end up in the production libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8623)
=> test: add bazel testonly attributes to test libraries and byproducts

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_experiment.h
The benchmark was creating different clients per thread regardless of
the `--client-per-thread` option value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8624)
=> test(storage): fix client-per-thread implementation

ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh
- Bump the size of the "lastN" buffer from 100 to 256.  This
will help catch the entirety of long-running operations.
- Turn off "single line" mode.  I've found that the protobuf
tracing is significantly easier to read this way.  It is
certainly nicer when attaching a trace to a bug report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8634)
=> ci: tweak the integration-test logging configuration

.clang-tidy, ci/cloudbuild/dockerfiles/fedora-35.Dockerfile, ci/cloudbuild/triggers/clang-tidy-ci.yaml, ci/cloudbuild/triggers/clang-tidy-pr.yaml, google/cloud/bigtable/row_reader.cc
I disabled some noisy `clang-tidy` warnings, but otherwise the fixes
were fairly minimal.
Note that this PR, and the build after the merge, are still using Fedora:34, we need to update the GCB triggers to get the new version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8633)
=> ci: move clang-tidy build to Fedora:35

ci/cloudbuild/dockerfiles/checkers.Dockerfile, ci/cloudbuild/triggers/generate-libraries-ci.yaml, ci/cloudbuild/triggers/generate-libraries-pr.yaml
The checkers build and the generate-libraries build need to change
atomically. Both reformat all the C++ code, so we better use the same
version of `clang-format` in both builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8638)
=> ci: use checkers image for generate-libraries build

ci/cloudbuild/dockerfiles/checkers.Dockerfile
I also reordered the steps in `checkers.Dockerfile` to run the slowest
(`cargo install typos-cli`) first. Makes it less painful to upgrade
other things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8637)
=> chore: update buildifier to 5.0.1

bazel/configure_template.bzl, bazel/crc32c.BUILD, bazel/curl.BUILD
With this PR Windows builds should not require `bash(1)`. This PR
removes all references to `genrule()` on Windows (there is one left, but
only takes effect on Linux).
Part of the work for #8613
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8632)
=> cleanup: avoid genrule() on Windows

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc
Decrease the polling-time limit from 3 hours to 90 minutes.  The
test infrastructure has a 3h timeout itself, and if that hits first
then we won't see the RPC tracing needed to figure out what is going
wrong.  Successful runs indicate that the backup should only take
about 30-45m, so the 90m limit should still be sufficient to only
catch problematic cases.
Part of #8616 and #8628.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8639)
=> ci(spanner): decrease LRO polling-time limit for backup tests

ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile
Part of the work for #7555 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8646)
=> ci: move `msan` build to Fedora:35

ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8647)
=> ci: move `demo-fedora` build to Fedora:35

ci/cloudbuild/dockerfiles/fedora-35-cxx11.Dockerfile, ci/cloudbuild/triggers/cxx11-ci.yaml, ci/cloudbuild/triggers/cxx11-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8648)
=> ci: move `cxx11` build to Fedora:35

google/cloud/pubsublite/internal/partition_publisher.cc, google/cloud/pubsublite/internal/partition_publisher_test.cc
In the case that a `PartitionPublisher` is instantiated, but `Start` and `Shutdown` are not called on it, then the alarm that is created still must terminate. This PR adds a test for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8643)
=> cleanup(pubsublite): prevent alarm from executing when Start not called

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc
Tolerate (cleanup and skip) `CreateBackup()` integration tests that fail
with "terminated by polling policy" deadline-exceeded errors, until #8616
can be resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8644)
=> ci(spanner): temporarily tolerate another failure in CreateBackup()

ci/cloudbuild/builds/lib/integration.sh
The integration tests may need git to compare the generator golden
files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8651)
=> ci: set up git for integration tests

CHANGELOG.md, google/cloud/bigtable/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/bigtable/instance_admin.cc, google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/instance_admin_test.cc, google/cloud/bigtable/tests/instance_admin_integration_test.cc, google/cloud/bigtable/version.h
The bigtable part of #5929 
I think the storage part will require some minor test updates, so I am going to break the task up into three PRs.
1. Bigtable
2. Storage
3. Common
I will not remove the future breaking change note in the CHANGELOG until step 3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8652)
=> cleanup(bigtable)!: remove deprecated InstanceAdmin IAM functions

ci/cloudbuild/triggers/asan-ci.yaml, ci/cloudbuild/triggers/asan-pr.yaml, ci/cloudbuild/triggers/tsan-ci.yaml, ci/cloudbuild/triggers/tsan-pr.yaml, ci/cloudbuild/triggers/ubsan-ci.yaml, ci/cloudbuild/triggers/ubsan-pr.yaml, ci/cloudbuild/triggers/xsan-ci.yaml, ci/cloudbuild/triggers/xsan-pr.yaml
The builds are already moved, this just updates the trigger files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8653)
=> ci: update *san trigger files to use Fedora:35

ci/cloudbuild/triggers/shared-ci.yaml, ci/cloudbuild/triggers/shared-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8656)
=> ci: move `shared` build to Fedora:35

ci/cloudbuild/triggers/libcxx-ci.yaml, ci/cloudbuild/triggers/libcxx-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8659)
=> ci: move `libcxx` build to Fedora:35

ci/cloudbuild/triggers/noex-ci.yaml, ci/cloudbuild/triggers/noex-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8660)
=> ci: move `noex` build to Fedora:35

ci/cloudbuild/triggers/coverage-ci.yaml, ci/cloudbuild/triggers/coverage-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8663)
=> ci: move `coverage` build to Fedora:35

ci/cloudbuild/triggers/cmake-install-ci.yaml, ci/cloudbuild/triggers/cmake-install-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8670)
=> ci: move `cmake-install` build to Fedora:35

ci/cloudbuild/triggers/bazel-oldest-ci.yaml, ci/cloudbuild/triggers/bazel-oldest-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8671)
=> ci: move `bazel-oldest` build to Fedora:35

ci/cloudbuild/triggers/bazel-targets-ci.yaml, ci/cloudbuild/triggers/bazel-targets-pr.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8672)
=> ci: move `bazel-targets` build to Fedora:35

ci/cloudbuild/triggers/gcs-grpc-ci.yaml, ci/cloudbuild/triggers/gcs-grpc-pr.yaml, ci/cloudbuild/triggers/install-gcs-grpc-ci.yaml, ci/cloudbuild/triggers/install-gcs-grpc-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8673)
=> ci: move GCS+gRPC builds to Fedora:35

ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh, google/cloud/internal/async_polling_loop.cc, google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc
Reacting to a "terminated by polling policy" error is difficult at
best as the caller won't know the actual state of the operation, and
will have little they can do to regain state.  In the case at hand,
we stop waiting for the CreateBackup(), but it continues none the
less, and we no longer have a handle by which the operation can be
canceled.  Attempting to drop the database while a backup operation
is pending will fail, so don't even try.  Instead, we rely upon the
short expiration time of test backups, and the eventual cleanup of
test databases (2 days) to reclaim the lost resources.
In general, the client library probably shouldn't be synthesizing
a return status for an operation.  Rather, it should be accurately
reflecting the state of the service. Leave a comment to that effect, …
=> ci(spanner): tweak response to polling timeout in CreateBackup() test

ci/cloudbuild/triggers/integration-production-ci.yaml, ci/cloudbuild/triggers/integration-production-pr.yaml, ci/cloudbuild/triggers/quickstart-production-ci.yaml, ci/cloudbuild/triggers/quickstart-production-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8676)
=> ci: move builds using production to Fedora:35

ci/cloudbuild/triggers/publish-docs-ci.yaml, ci/cloudbuild/triggers/publish-docs-pr.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8677)
=> ci: move `publish-docs` build to Fedora:35

google/cloud/storage/examples/storage_bucket_samples.cc
Motivated by #8586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8595)
=> doc(storage): add custom-dual regions example

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8684)
=> chore: update CHANGELOG for 202204 release

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/samples/postgresql_samples.cc, google/cloud/spanner/testing/cleanup_stale_databases.cc, google/cloud/spanner/testing/random_database_name.cc, google/cloud/spanner/testing/random_database_name.h, google/cloud/spanner/testing/random_database_name_test.cc
Now that I have abandoned trying to parameterize tests/samples on
database dialect, it is straightforward to choose the right quoting
convention needed to include hyphens in database names in the CREATE
DDL statement.  So, resume using "db-YYYY-MM-DD-" prefixes for random
database names---they are easier to produce and read.  This reverts
most of #8547.
Also change `RandomDatabasePrefixRegex()` to return a regex that
indeed only matches the random-database prefix, and which therefore
should be passed to `std::regex_search()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8685)
=> test(spanner): revert to using hyphen separators in database names

google/cloud/spanner/integration_tests/data_types_integration_test.cc
Restore verification of the (newly-lowered) JSON nesting limit.
See #8327.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8689)
=> test(spanner): re-enable DataTypeIntegrationTest.JsonMaxNesting

google/cloud/storage/client.cc, google/cloud/storage/client_write_object_test.cc, google/cloud/storage/examples/storage_client_mock_samples.cc, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_client.h, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/internal/hybrid_client.h, google/cloud/storage/internal/logging_client.cc, google/cloud/storage/internal/logging_client.h, google/cloud/storage/internal/raw_client.h, google/cloud/storage/internal/resumable_upload_session.h, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client.h, google/cloud/storage/internal/retry_resumable_upload_session.cc, google/cloud/storage/internal/retry_resumable_upload_session.h, google/cloud/storage/internal/retry_resumable_upload_session_test.cc, google/cloud/storage/parallel_upload.cc, google/cloud/storage/parallel_uploads_test.cc, google/cloud/storage/testing/mock_client.h, google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc, google/cloud/storage/tests/object_write_streambuf_integration_test.cc
When creating new resumable upload sessions we need to return the
initial session state. Otherwise, any resumed sessions have an incorrect
value for the committed bytes and whether the upload is completed or
not.  In this change we just return the state, but do not use it.
Part of the work for #8621 and #8559
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8622)
=> fix(storage)!: return initial session state

generator/internal/descriptor_utils.cc
Motivated by #7990.  I tried all kinds of other workarounds before settling for this monstrosity.
I cannot figure out how to pass arbitrary strings, with spaces and newlines, as parameters to the generator, if somebody tells me how to do that, we can move these out of the code and into `generator_config.textproto`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8700)
=> feat(generator): workaround dialogflow + doxygen problems

google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/object_requests_test.cc, google/cloud/storage/internal/resumable_upload_session.cc
These will be used to move the resumable upload RPCs away from
`storage::internal::ResumableUploadSession` to `RawClient`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8709)
=> impl(storage): new resumable upload types

google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_client.h, google/cloud/storage/internal/curl_client_test.cc, google/cloud/storage/internal/curl_resumable_upload_session.cc, google/cloud/storage/internal/curl_resumable_upload_session_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session.cc, google/cloud/storage/internal/grpc_resumable_upload_session_test.cc, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/internal/hybrid_client.h, google/cloud/storage/internal/logging_client.cc, google/cloud/storage/internal/logging_client.h, google/cloud/storage/internal/raw_client.h, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client.h, google/cloud/storage/testing/mock_client.h
The plan is to remove the "sessions" used for resumable uploads. To that
end this PR introduces the new functions that implement resumable
uploads, albeit they are unused and unimplemented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8712)
=> cleanup(storage)!: scaffold session-less RU

ci/cloudbuild/cloudbuild.yaml
We use `kaniko:v1.6.y-debug` instead of `kaniko:v1.6.y` to workaround
problems I think do not exist in the v1.8.x series (and higher).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8711)
=> ci: use release version of Kaniko

google/cloud/connection_options_test.cc, google/cloud/future_generic_test.cc, google/cloud/future_generic_then_test.cc, google/cloud/future_void_test.cc, google/cloud/future_void_then_test.cc, google/cloud/internal/async_polling_loop.cc, google/cloud/internal/async_retry_loop.h, google/cloud/internal/async_retry_unary_rpc_test.cc, google/cloud/internal/base64_transforms.h, google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h, google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/internal/extract_long_running_result_test.cc, google/cloud/internal/future_impl_test.cc, google/cloud/internal/log_impl.h, google/cloud/internal/oauth2_authorized_user_credentials.cc, google/cloud/internal/oauth2_compute_engine_credentials.cc, google/cloud/internal/oauth2_google_credentials_test.cc, google/cloud/internal/oauth2_minimal_iam_credentials_rest_test.cc, google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/internal/oauth2_service_account_credentials_test.cc, google/cloud/internal/pagination_range.h, google/cloud/internal/random.cc, google/cloud/internal/retry_policy.h, google/cloud/log.h
I found these while trying to build with OpenSSL 3.0. Motivated by #8544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8715)
=> cleanup(common): fix clang-tidy 14 warnings

google/cloud/examples/grpc_credential_types.cc
I found these while trying to build with OpenSSL 3.0. Motivated by #8544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8718)
=> cleanup: miscellanous clang-tidy 14 fixes

generator/integration_tests/golden/tests/golden_kitchen_sink_client_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc, generator/internal/descriptor_utils.cc, generator/internal/predicate_utils.cc
I found these while trying to build with OpenSSL 3.0. Motivated by #8544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8717)
=> cleanup(generator): fix clang-tidy 14 warnings

google/cloud/pubsub/internal/subscription_session_test.cc
I found these while trying to build with OpenSSL 3.0. Motivated by https://github.com/googleapis/google-cloud-cpp/issues/8544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8719)
=> cleanup(pubsub): fix clang-tidy 14 warnings

google/cloud/pubsublite/message_metadata_test.cc, google/cloud/pubsublite/topic_test.cc
I found these while trying to build with OpenSSL 3.0. Motivated by https://github.com/googleapis/google-cloud-cpp/issues/8544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8720)
=> cleanup(pubsublite): fix clang-tidy 14 warnings

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc, google/cloud/spanner/internal/merge_chunk_test.cc
I found these while trying to build with OpenSSL 3.0. Motivated by https://github.com/googleapis/google-cloud-cpp/issues/8544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8721)
=> cleanup(spanner): fix clang-tidy 14 warnings

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/client.cc, google/cloud/storage/client.h, google/cloud/storage/internal/access_control_common_parser.cc, google/cloud/storage/internal/bucket_metadata_parser.cc, google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/internal/curl_request_builder.h, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/logging_client.cc, google/cloud/storage/internal/object_metadata_parser.cc, google/cloud/storage/internal/patch_builder.cc, google/cloud/storage/internal/patch_builder_test.cc, google/cloud/storage/internal/retry_client_test.cc, google/cloud/storage/internal/retry_object_read_source_test.cc, google/cloud/storage/internal/retry_resumable_upload_session_test.cc, google/cloud/storage/internal/storage_stub_factory_test.cc, google/cloud/storage/oauth2/authorized_user_credentials.cc, google/cloud/storage/oauth2/compute_engine_credentials.cc, google/cloud/storage/oauth2/service_account_credentials.cc, google/cloud/storage/object_read_stream.cc, google/cloud/storage/object_write_stream.cc, google/cloud/storage/parallel_upload.cc, google/cloud/storage/parallel_upload.h, google/cloud/storage/parallel_uploads_test.cc, google/cloud/storage/tests/error_injection_integration_test.cc, google/cloud/storage/tests/object_resumable_write_integration_test.cc
I found these while trying to build with OpenSSL 3.0. Motivated by https://github.com/googleapis/google-cloud-cpp/issues/8544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8722)
=> cleanup(storage): fix clang-tidy 14 warnings

google/cloud/pubsublite/internal/partition_publisher_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8710)
=> cleanup(pubsublite): wrap partition publisher test mocks with `StrictMock`

google/cloud/CMakeLists.txt, google/cloud/config-rest.cmake.in, google/cloud/internal/curl_handle.cc, google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h, google/cloud/internal/curl_wrappers.cc
As part of the REST refactor effort, the extern "C" symbols names in the REST library needed to be different than the existing names in GCS.
Also fixes some of the REST libraries cmake configuration to follow existing conventions.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8693)
=> chore(rest): correct cmake config and disambiguate C names

google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/integration_tests/backup_extra_integration_test.cc, google/cloud/spanner/integration_tests/backup_integration_test.cc
Revert #8605 given the indication that the "Read-only transaction
timestamp has exceeded the maximum timestamp staleness" failed
precondition from CreateBackup() has been avoided in the backend.
We'll close #8594 in a few days if things remain quiet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8737)
=> ci(spanner): revert the toleration of a CreateBackup() error

google/cloud/internal/openssl_util.cc
Add the OpenSSL errors if there are any failures. Also some (I think)
clean ups on the use of `std::unique_ptr<>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8738)
=> impl(rest): better errors in SignUsingSha256()

google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/internal/grpc_resumable_upload_session.cc, google/cloud/storage/internal/grpc_resumable_upload_session.h, google/cloud/storage/internal/object_requests.h
This moves the implementation of `UploadChunk()` from the resumable
upload sessions to the `*Client` classes. Part of the work to
remove the resumable upload sessions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8739)
=> refactor(storage): move `UploadChunk()` implementation

google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/testing/pick_instance_config.cc, google/cloud/spanner/testing/pick_instance_config.h
Change PickInstanceConfig() to take a predicate over InstanceConfig
values instead of a regex to match against InstanceConfig.name. This
provides a flexibility that will be needed for an upcoming feature
where we will need to select an instance config based upon more
complex conditions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8748)
=> test(spanner): a more flexible PickInstanceConfig()

google/cloud/storage/idempotency_policy_test.cc, google/cloud/storage/internal/curl_client_test.cc, google/cloud/storage/internal/curl_resumable_upload_session.cc, google/cloud/storage/internal/curl_resumable_upload_session_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_resumable_upload_session.cc, google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/object_requests_test.cc
This changes the `internal::UploadChunkRequest` class to support partial
writes. The class remains immutable, but now provides a function to
return a new `UploadChunkRequest` with the remaining data (but the
original options) after a partial write.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8747)
=> impl(storage): support for partial writes in `UploadChunkRequest`

generator/generator_config.textproto, google/cloud/dialogflow_cx/doc/main.dox, google/cloud/dialogflow_cx/internal/environments_option_defaults.cc, google/cloud/dialogflow_cx/internal/versions_option_defaults.cc, google/cloud/dialogflow_es/CMakeLists.txt, google/cloud/dialogflow_es/doc/main.dox, google/cloud/dialogflow_es/internal/environments_option_defaults.cc, google/cloud/dialogflow_es/internal/versions_option_defaults.cc
Document service environment endpoints in Dialogflow. (I think this is too easy to forget. I will edit the howto generate a library doc so that it doesn't happen again).
The two dialogflow editions have the same environment variables. I considered differentiating them, but decided not to. Two of the variables conflict with other libraries though. Those two were changed.
```sh
grep -rho "\"GOOGLE_CLOUD_CPP_.*_ENDPOINT\"" | sort | uniq -cd
2 "GOOGLE_CLOUD_CPP_AGENTS_ENDPOINT"
2 "GOOGLE_CLOUD_CPP_ENTITY_TYPES_ENDPOINT"
3 "GOOGLE_CLOUD_CPP_ENVIRONMENTS_ENDPOINT"
2 "GOOGLE_CLOUD_CPP_INTENTS_ENDPOINT"
2 "GOOGLE_CLOUD_CPP_SESSION_ENTITY_TYPES_ENDPOINT"
2 "GOOGLE_CLOUD_CPP_SESSIONS_ENDPOINT"
9 "GOOGLE_CLOUD_CPP_SPANNER_DEFAULT_ENDPOINT"
3 "GOOGLE_CLOUD_CPP_VERSIONS_ENDPOINT"
```
---
This change …
=> cleanup(dialogflow): endpoint env vars

google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/pick_instance_config.cc, google/cloud/spanner/testing/pick_instance_config.h
Use the new `spanner_testing::PickInstanceConfig()` predicate support
to replace the special `PickConfig()` function in the Spanner samples.
Simplify the `PickInstanceConfig()` implementation.  There is no need
to wrap the `ListInstanceConfigs()` in a lambda.
Plus some other miscellaneous cleanup:
- Tighten up the `PickInstanceConfig()` predicate in the integration
tests.
- Use `config_id` consistently to distinguish instance configs from
their ID.
- Adjust some sample banners to use the real sample tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8758)
=> cleanup(spanner): use the new PickInstanceConfig() API in samples

google/cloud/internal/async_polling_loop.cc
Pick up some less-polemic updates to `OnPoll()` from the closed #8695:
- Add clarifying comments when we satisfy the promise with an error.
- Don't even try to update `op_name_`; it must be set by the time we
reach `OnPoll()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8756)
=> impl(spanner): carry over some updates to AsyncPollingLoopImpl::OnPoll()

google/cloud/pubsub/publisher_connection.cc
This should increase throughput of messages without ordering keys which are sent when message ordering is enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8753)
=> impl(pubsub): Bypass SequentialBatchSink for empty ordering keys

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc
This continues moving the implementation of `ResumableUploadSession` in
terms of session-less "resumable uploads".  The expectation is that
a session-less implementation will be easier to reason about and have
fewer problems when resuming uploads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8764)
=> refactor(GCS+gRPC): write resumable session using RU

google/cloud/spanner/testing/random_instance_name.cc, google/cloud/spanner/testing/random_instance_name.h
This facilitates an upcoming change where we will need to generate
another form of instance ID, which has a different prefix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8771)
=> refactor(spanner): extract instance ID generation into helper func

google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client_test.cc
This implements the resumable uploads retry loop as part of the
`RetryClient`.  The retry loop for this function is different, as it
requires querying the state of the upload via an alternative function
on a transient failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8762)
=> impl(storage): implement `RetryClient::UploadChunk()`

google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/testing/cleanup_stale_instances.cc, google/cloud/spanner/testing/cleanup_stale_instances.h
Move the regex for random instance names, and the check that it indeed
matches, into `CleanupStaleInstances()` itself.
Also factor out the "cutoff date" logic into a helper function, in
preparation for an upcoming change where we will need to cleanup an
additional form of instance resource.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8772)
=> refactor(spanner): move random-instance regex into CleanupStaleInstances

google/cloud/pubsublite/internal/multipartition_publisher.cc, google/cloud/pubsublite/internal/multipartition_publisher.h, google/cloud/pubsublite/internal/multipartition_publisher_test.cc
in the following case:
thread 1: call `Publish` on `5` messages before publishers are instantiated
alarm thread: instantiate publishers and start loop of calling `PartitionPublisher::Publish` on above messages
alarm thread: call `PartitionPublisher::Publish` on first message
thread 1: call `Publish` on `6`th message which is `PartitionPublisher::Publish`ed due to publishers having been instantiated
alarm thread: `2`nd to `5`th messages are `PartitionPublisher::Publish`ed
this leads to incorrect ordering
This PR implements `MultipartitionPublisher::Publish` via an internal buffer to remove these types of race conditions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-clo …
=> fix(pubsublite): multipartition publisher ordering

CHANGELOG.md, google/cloud/storagetransfer/BUILD.bazel, google/cloud/storagetransfer/CMakeLists.txt
See https://github.com/googleapis/google-cloud-cpp/issues/8785 about a name clash on `UID_MAX` from `<sys/syslimits.h>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8789)
=> fix: temporarily disable google/cloud/storagetransfer on macOS

google/cloud/pubsublite/topic.h, google/cloud/pubsublite/topic_test.cc
this PR changes the `Topic` constructor arguments to be the same as they are in the Cloud Console
ex. `project_id`, `location_id`, `topic_id`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8790)
=> cleanup(pubsublite): change `Topic` var names

generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator.h, generator/internal/scaffold_generator_test.cc
Since #8696 we no longer need the `proto_files` and `proto_deps`
variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8801)
=> cleanup(generator): remove some dead code from the scaffold generator

google/cloud/spanner/value.cc, google/cloud/spanner/value_test.cc
Unlike IEEE 754, which defines that NaN is not equal to itself,
Spanner NaN values are considered equal (for easy sorting), so
spanner::Value should behave the same way for FLOAT64.
http://cloud/spanner/docs/reference/standard-sql/data-types#orderable_floating_points
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8805)
=> fix(spanner)!: FLOAT64 NaN values are considered equal

cmake/CompileProtos.cmake, google/cloud/accesscontextmanager/CMakeLists.txt, google/cloud/asset/CMakeLists.txt, google/cloud/binaryauthorization/CMakeLists.txt, google/cloud/containeranalysis/CMakeLists.txt, google/cloud/debugger/CMakeLists.txt, google/cloud/oslogin/CMakeLists.txt, google/cloud/recommender/CMakeLists.txt
This completes the work started in #8792 by udpating the remaining
`google/cloud/*/CMakeLists.txt` files.
In order to do so, we need to introduce a couple of special cases
(to omit some targets, and transform others) when processing the
`<library>.deps` files.
Also, `google/cloud/asset/CMakeLists.txt` has a special case to
deal with `google/cloud/orgpolicy/v1/orgpolicy.proto`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8809)
=> cleanup: use new CompileProtos support in remaining CMakeLists

google/cloud/google_cloud_cpp_common.bzl, google/cloud/google_cloud_cpp_common.cmake, google/cloud/internal/invoke_result.h, google/cloud/internal/type_traits.h
I am going to use this template by itself.  Seems better to use a
separate file, matching the name of the C++17 header that contains it.
Motivated by #8621
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8808)
=> refactor(common): split `internal::void_t`

google/cloud/storage/parallel_uploads_test.cc
This test will need a lot of changes to support session-less uploads. In
this iteration we just change the test, in a way that (hopefully) will
make the removal of sessions easier to grok.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8811)
=> test(storage): prepare for session-less uploads

google/cloud/storage/internal/curl_resumable_upload_session.cc, google/cloud/storage/internal/generic_request.h, google/cloud/storage/internal/grpc_resumable_upload_session.cc
In a few places we need to copy all the options from a request to
another request, sometimes with a different type for the destination
request.
Part of the changes for #8621
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8812)
=> refactor(storage): helper function to copy request options

google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsub/google_cloud_cpp_pubsub.bzl, google/cloud/pubsub/internal/containing_publisher_connection.h, google/cloud/pubsub/publisher_connection.cc
Migrated `ContainingPublisherConnection` in `pubsub` from a source file to an internal header so that we can use it in the Pub/Sub Lite factory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8818)
=> refactor(pubsub): containing publisher conn

google/cloud/internal/port_platform.h
Use `defined(__clang__)` and `defined(COMPILER_MSVC)` to detect
clang-cl.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8822)
=> impl: add simple exception-detection support for clang-cl

google/cloud/bigtable/client_options.h
The deprecation part of #7230 
I did not schedule its removal. At the moment, I don't have a compelling reason to do so. The class is not hurting anybody.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8824)
=> doc(bigtable): deprecate ClientOptions

CHANGELOG.md, google/cloud/bigtable/data_client.cc, google/cloud/bigtable/data_client.h, google/cloud/bigtable/data_client_test.cc, google/cloud/bigtable/internal/logging_data_client.h, google/cloud/bigtable/tests/data_integration_test.cc, google/cloud/bigtable/version.h
The deprecation part of #8800 
I added compiler warnings for `Channel()` and `reset()` to the base class, a la [this spanner warning](https://github.com/googleapis/google-cloud-cpp/blob/c3042b5b54f489341e2801f15b27fa3d70966625/google/cloud/spanner/version.h#L23).
We still call `BackgroundThreadsFactory()` in `Table`: https://github.com/googleapis/google-cloud-cpp/blob/c3042b5b54f489341e2801f15b27fa3d70966625/google/cloud/bigtable/table.h#L228
I am relying on documentation to communicate the future removal of `DataClient::BackgroundThreadsFactory()`. I could not figure out a way to add a compiler warning to this function that:
1. doesn't break customer code extending `DataClient`. (Note that such code might not exist)
2. doesn't yield a compiler warning for us
--- …
=> doc(bigtable): deprecate DataClient member fns

google/cloud/bigtable/data_client.cc, google/cloud/bigtable/data_client.h, google/cloud/bigtable/data_client_test.cc, google/cloud/bigtable/internal/logging_data_client.h, google/cloud/bigtable/testing/inprocess_data_client.h, google/cloud/bigtable/testing/mock_data_client.h, google/cloud/bigtable/tests/data_integration_test.cc
This reverts a lot of #8813
Thank you to @devbww for reminding me about `disable_deprecation_warnings.inc`
I included the deprecation warning for all classes that derive from `DataClient` (`internal::LoggingDataClient`, `testing::MockDataClient`, and `testing::InProcessDataClient`). I am not sure the `testing::*` classes will break our CI build. I am just being safe.
I might add a compiler warning for `DataClient::BackgroundThreadsFactory()` and disable it in `table.h` in a subsequent PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8827)
=> cleanup(bigtable): disable deprecation warnings properly (maybe)

google/cloud/bigtable/data_client.cc
I missed this one: https://source.cloud.google.com/results/invocations/35c67e54-4f87-42b8-b383-b5526f0af405/log
sorry for iterating in the CI build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8828)
=> cleanup(bigtable): disable deprecation warnings for DefaultDataClient

google/cloud/storage/benchmarks/storage_parallel_uploads_benchmark.cc, google/cloud/storage/client.cc, google/cloud/storage/client.h, google/cloud/storage/iam_policy.cc, google/cloud/storage/internal/tuple_filter_test.cc, google/cloud/storage/oauth2/service_account_credentials_test.cc, google/cloud/storage/parallel_upload.h, google/cloud/storage/well_known_headers.h
Fixed the root cause of a number of clang-tidy warnings and remove the
comments disabling them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8832)
=> cleanup(storage): fix clang-tidy warnings

ci/cloudbuild/builds/lib/integration.sh, ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh, google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request_test.cc, google/cloud/storage/internal/object_read_source.h, google/cloud/storage/internal/object_read_streambuf.cc, google/cloud/storage/internal/object_read_streambuf.h, google/cloud/storage/object_read_stream.h, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/decompressive_transcoding_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
GCS can decompress some objects during download.  For these objects the
returned checksum/hashes matches the compressed data, but the computed
checksums match the decompressed data.
Part of the work for #8286
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8830)
=> fix(storage): disable checksums for transcoded objects

google/cloud/storage/internal/storage_stub_factory.cc
We probably want to respect the common options that configure a gRPC channel in storage. https://github.com/googleapis/google-cloud-cpp/blob/c16f539c5794750ff067f3b5d83738c69d0a5317/google/cloud/grpc_options.cc#L37-L47
<hr />
I did not add any tests. I could have factored out the creation of the `grpc::ChannelArguments` for testing.... but I couldn't guarantee that function would be called.
An interesting way to test this would be to use a mock [grpc authentication strategy](https://github.com/googleapis/google-cloud-cpp/blob/f779bb99395bbdfe3aac51864ff2abf2a0b6dffc/google/cloud/internal/unified_grpc_credentials.h#L32-L42). We could have some:
```c++
namespace google::cloud::internal {
class MockGrpcAuthenticationStrategy : public GrpcAuthenticationStrategy {
MOCK_METHOD( ... );
};
struct …
```
=> feat(storage): configure gRPC channel w Options

google/cloud/bigtable/internal/common_client.h, google/cloud/bigtable/internal/connection_refresh_state.cc, google/cloud/bigtable/internal/connection_refresh_state.h, google/cloud/bigtable/internal/connection_refresh_state_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8837)
=> cleanup(bigtable): move refresh into `bigtable_internal`

google/cloud/storage/client.h, google/cloud/storage/examples/storage_object_samples.cc, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/tests/decompressive_transcoding_integration_test.cc, google/cloud/storage/well_known_headers.h
For objects stored in gzip format (and with contentEncoding == "gzip")
GCS over HTTP automatically decompresses the object during download.
Some applications may want to read the object in compressed format.
Support this use-case with a new option (`AcceptEncoding`) for
`Client::ReadObject()`, and a new helper function
(`AcceptEncodingGzip()`) that returns this option with the correct value.
Fixes #8305
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8834)
=> feat(storage): new option to disable decompressive transcoding

google/cloud/bigtable/internal/common_client.h, google/cloud/bigtable/internal/connection_refresh_state.cc, google/cloud/bigtable/internal/connection_refresh_state.h, google/cloud/bigtable/internal/connection_refresh_state_test.cc
This itty bitty refactor will make the channel creation by the stub factory read better (in my opinion)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8840)
=> refactor(bigtable): channel refresh

CMakeLists.txt
We cannot enable the storage library and disable the `rest-internal`
library, unfortunately the check was based on the wrong variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8850)
=> fix: correct check for storage vs. rest enabled

google/cloud/storage/tests/curl_request_integration_test.cc
I am planning to replace the implementation of `httpbin` in the
testbench, the new implementation has a less amusing payload for
`418 - I AM A TEAPOT` errors. The new expectation passes with both the
current and the upcoming `echo` service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8846)
=> test(storage): relax integration test checks

google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_handle.cc, google/cloud/storage/internal/curl_handle_factory.cc, google/cloud/storage/internal/curl_request.cc, google/cloud/storage/internal/curl_wrappers.cc, google/cloud/storage/internal/curl_wrappers.h
It seems that, despite all existing precautions, we are still getting
errors on `curl_setopt(..., CURLOPT_BUFFERSIZE, value)` because the
option cannot be set until some internal cleanup happens.  Since `value`
is always the same, we can set it when the handle is created, and avoid
the cleanup problems.
Part of the work for #7051
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8865)
=> fix(storage): set CURLOPT_BUFFERSIZE once per handle

google/cloud/internal/curl_handle.cc, google/cloud/internal/curl_handle_factory.cc, google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h, google/cloud/internal/curl_wrappers.cc, google/cloud/internal/curl_wrappers.h
It seems that, despite all existing precautions, we are still getting
errors on `curl_setopt(..., CURLOPT_BUFFERSIZE, value)` because the
option cannot be set until some internal cleanup happens.  Since `value`
is always the same, we can set it when the handle is created, and avoid
the cleanup problems.
Motivated by #7051
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8866)
=> fix(rest): set CURLOPT_BUFFERSIZE once per handle

google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request.h, google/cloud/storage/internal/curl_handle.cc, google/cloud/storage/internal/curl_handle.h, google/cloud/storage/internal/curl_handle_test.cc, google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/internal/curl_request_builder.h, google/cloud/storage/tests/curl_download_request_integration_test.cc
If `CurlHandle::SetOption()` fails, return a `Status` and remove the
handle from the connection pool.
Motivated by #7051
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8871)
=> fix(storage): use Status for `CurlHandle::SetOption()`

google/cloud/internal/curl_handle.cc, google/cloud/internal/curl_handle.h, google/cloud/internal/curl_handle_test.cc, google/cloud/internal/curl_impl.cc
If `curl_easy_setopt()` (via `CurlHandle::SetOption()`) fails return a
`Status` and remove the handle from the connection pool.
Motivated by #7051
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8869)
=> fix(rest): use Status for errors in `curl_easy_setopt()`

google/cloud/spanner/samples/postgresql_samples.cc, google/cloud/spanner/value.cc, google/cloud/spanner/value.h, google/cloud/spanner/value_test.cc
Add support for `spanner::PgNumeric` to build a `spanner::Value`
with `Type { .code=NUMERIC, .type_annotation=PG_NUMERIC }`.
`TypeCode::NUMERIC` now takes the `type_annotation` into account
for equality tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8872)
=> feat(spanner): spanner::Value support for spanner::PgNumeric

google/cloud/bigtable/internal/defaults.cc
It seems like we should preserve the policy defaults for the Data API, instead of using the generator's defaults. That way code that goes from: `Table table(MakeDataClient());` -> `Table table(MakeDataConnection())` acts sort of the same.
Note that bigtable's exponential backoff policy expects different input parameters than the common backoff policy: https://github.com/googleapis/google-cloud-cpp/blob/2618390d2ca7409f1408ed19633ade2c34a9661a/google/cloud/bigtable/rpc_backoff_policy.h#L94
<hr />
Now everything gets a constant https://github.com/googleapis/google-cloud-cpp/pull/8867#discussion_r864316634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8884)
=> cleanup(bigtable): preserve policy defaults

google/cloud/spanner/numeric.h
Restore a comment about building a PgNumeric from (case-insensitive)
"NaN", which was lost during the shuffle of implementation strategies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8891)
=> doc(spanner): add a comment about building a "NaN" PgNumeric

CHANGELOG.md, google/cloud/bigtable/row_reader.cc, google/cloud/bigtable/row_reader.h, google/cloud/bigtable/row_reader_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/version.h
The deprecation part of #8854
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8887)
=> doc(bigtable): deprecate RowReader public ctors

google/cloud/storage/internal/retry_object_read_source.cc, google/cloud/storage/internal/retry_object_read_source.h, google/cloud/storage/internal/retry_object_read_source_test.cc
GCS can automatically decompress objects compressed with `gzip`.
However, it does not support the `Read-Range` header for such downloads,
all such downloads start from the first byte.  To resume an interrupted
download that is being automatically "gunzipped" (aka a download under
"decompressive transcoding") we need to discard all data until the
last received offset from the first download.
Fixes #8286, a future PR will add an integration test, see #8893.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8894)
=> fix(storage): resume "gunzipped" downloads

google/cloud/storage/internal/object_write_streambuf_test.cc, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client_test.cc
In some very rare circumstances a resumable upload may report that all
bytes have been received (and thus there is no more need to send data),
but fail to send back the finalized object metadata. In those cases we
need to retry sending the message to finalize the object.
Fixes #8868 
/FYI: @Jseph
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8896)
=> fix(storage): handle full but not finalized uploads

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc, google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc, google/cloud/spanner/connection_options_test.cc, google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc
Prefer using `google::cloud::Options` instead.
Motivated by https://github.com/googleapis/google-cloud-cpp/pull/8900#pullrequestreview-965001024
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8903)
=> cleanup(spanner): stop using `ConnectionOptions`

google/cloud/storage/tests/decompressive_transcoding_integration_test.cc
Adds an integration test for "gunzipped" (aka decompressive transcoding)
downloads.
Fixes #8893
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8904)
=> test(storage): "gunzipped" downloads integration

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
Nothing important, I just noticed it was not called at all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8905)
=> cleanup(spanner): remove unused test function

google/cloud/connection_options.h, google/cloud/connection_options_test.cc
I deprecated each function in `google::cloud::ConnectionOptions` and
documented what is the alternative mechanism via
`google::cloud::Options`.  I did not deprecate the class itself because
it is used in backwards compatibility functions, for example,
`pubsub::Make*Connection`.  Marking the class deprecated stops our code
from compiling.
Part of the work for #7348
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8907)
=> doc(common): deprecate `ConnectionOptions` member functions

google/cloud/pubsub/publisher_connection.h, google/cloud/pubsub/schema_admin_connection.h, google/cloud/pubsub/subscriber_connection.h, google/cloud/pubsub/subscription_admin_connection.h, google/cloud/pubsub/topic_admin_connection.h
I did not set a date to retire these functions, because I do not think
we should retire them.  They are basically harmless.
Part of the work for #7348
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8900)
=> doc(pubsub): deprecate functions consuming `ConnectionOptions`

google/cloud/pubsub/subscriber_options.h, google/cloud/pubsub/subscriber_options_test.cc
As usual, we cannot mark the class itself as deprecated, because it is
used in functions needed for backwards compatibility (even though those
functions are deprecated too). What we can do is mark all member
functions, including constructors, as deprecated.  We also document the
class and all its member functions as deprecated too.
Fixes #7348 (for realsies)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8916)
=> doc(pubsub): deprecate `SubscriberOptions`

google/cloud/bigtable/admin_client.h, google/cloud/bigtable/admin_client_test.cc, google/cloud/bigtable/client_options.cc, google/cloud/bigtable/client_options.h, google/cloud/bigtable/client_options_test.cc, google/cloud/bigtable/data_client.h, google/cloud/bigtable/instance_admin_client.h, google/cloud/bigtable/instance_admin_client_test.cc
Part of the work for #7230
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8914)
=> doc(bigtable): compiler warnings for ClientOptions

google/cloud/testing_util/CMakeLists.txt, google/cloud/testing_util/google_cloud_cpp_testing_grpc.cmake, google/cloud/testing_util/google_cloud_cpp_testing_rest.cmake
A fairly uncommon configuration for us, but it seems fairly common for
GCS-only customers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8923)
=> fix(common): compile with storage and without gRPC

google/cloud/storage/client.h, google/cloud/storage/internal/hmac_key_requests.h
Fix all `HmacKey` requests to accept `UserProject`. Used the opportunity
to document the "common options", since I had to do that for these
requests anyway. And then fixed some rendering problems.
Motivated by #4208
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8928)
=> fix(storage): all `HmacKey` requests accept `UserProject`

google/cloud/spanner/client.cc, google/cloud/spanner/client_test.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/internal/transaction_impl.h, google/cloud/spanner/internal/transaction_impl_test.cc, google/cloud/spanner/testing/matchers.h, google/cloud/spanner/transaction_test.cc
Introduce `TransactionContext` to encapsulate the read-only callback
parameters to the transaction visitation functor.
When we added the first parameter, `seqno`, we said, "Great, a single
extra parameter."  When we added the second parameter, `tag`, we
said, "This might get out of hand, but there's no time to fix it now."
A third parameter is on the horizon, so let's take the opportunity to
add a "context" struct now to house all the additional transaction
data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8933)
=> refactor(spanner): use struct for transaction callback parameters

google/cloud/pubsub/subscriber_options.cc, google/cloud/pubsub/subscriber_options.h
In a previous PR I made the default constructor for `SubscriberOptions`
deprecated (this was intended) and `explicit` (this was not). This
restores the implicit default constructor for `SubscriberOptions`, so
expressions like `{}` will continue to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8936)
=> cleanup(pubsub): revert breaking change for `SubscriberOptions`

google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/async_streaming_read_rpc_logging.h, google/cloud/internal/async_streaming_read_rpc_logging_test.cc
Part of the work for #8937 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8947)
=> feat(common): `*Logging` decorator for asynchronous streaming read RPCs

google/cloud/bigtable/internal/legacy_row_reader_impl.cc, google/cloud/bigtable/internal/legacy_row_reader_impl.h, google/cloud/bigtable/internal/row_reader_impl.h, google/cloud/bigtable/internal/rowreaderiterator.cc, google/cloud/bigtable/row_reader_test.cc
refactor `RowReader` / `RowReaderIterator` to deal in `absl::variant<Status, Row>`s instead of `StatusOr<absl::optional<Row>>`s. This is more consistent with the interface `StreamRange` expects. In a subsequent PR I will probably implement RowReader in terms of a StreamRange (which will allow me to delete `bigtable/internal/rowreader_iterator.{h,cc}`)
| previous type: `StatusOr<absl::optional<Row>>` | new type: `absl::variant<Status, Row>` |
|-|-|
| has `Row` | has `Row`|
| bad Status | has bad Status |
| has `absl::nullopt` | has OK Status|
<hr />
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8948)
=> refactor(bigtable): use variant<status, T> not StatusOr<optional<T>>

google/cloud/internal/curl_rest_client.cc, google/cloud/internal/curl_rest_client.h, google/cloud/internal/curl_rest_client_test.cc
Simplify Host header population by using the AuthorityOption as an override. Otherwise, if the endpoint is a googleapis.com address, use it for the Host header. This adds the burden of correctly specifying the AuthorityOption to the library being built on top of the RestLibrary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8950)
=> refactor(rest): leverage AuthorityOption to override Host header

ci/cloudbuild/builds/generate-libraries.sh
If a new service is added to an existing proto file, the generator
creates new files. We want to detect these and add the new generated
files to the right library, or maybe omit the service if there are very
good reasons to do so.
Fixes #7584
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8952)
=> ci: detect when generator creates new files

generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.h, generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_stub.h, generator/integration_tests/golden/tests/golden_kitchen_sink_auth_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc, generator/integration_tests/golden_config.textproto, generator/internal/auth_decorator_generator.cc, generator/internal/client_generator.cc, generator/internal/connection_generator.cc, generator/internal/connection_impl_generator.cc, generator/internal/logging_decorator_generator.cc, generator/internal/metadata_decorator_generator.cc, generator/internal/service_code_generator.cc, generator/internal/service_code_generator.h, generator/internal/stub_generator.cc
The generator can add asynchronous streaming reads in the `*Stub`
classes and their decorators.  No code is generated for the
`*Connection` or `*Client` classes.  We still don't know what is the
right API at that layer, and the services that need this have
hand-crafted `*Connection` and `*Client` layers at the moment.
Fixes #8937
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8951)
=> feat(generate): async streaming reads for `*Stub`

google/cloud/bigtable/internal/row_reader_impl.h, google/cloud/bigtable/row_reader.cc, google/cloud/bigtable/row_reader.h, google/cloud/bigtable/row_reader_test.cc
Fixes #8892 
Let's just keep this simple. Adding a `StatusOnlyRowReader` will let me construct a default `RowReader`. It will also let me return an unimplemented `RowReader` (which I want for the default `DataConnection`). I will deal with mocking later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8958)
=> feat(bigtable): default construct a RowReader

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
This is one of the first member functions that does not map directly to
a RPC.  We need to simulate it using the `GetBucket()` RPC and filter
out the data we do not need.
Fixes #4180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8946)
=> feat(GCS+gRPC): implement `ListBucketAcl()`

ci/cloudbuild/builds/lib/integration.sh
Now that we no longer pin Werkzeug (#8875), we also no longer need
to uninstall the default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8959)
=> cleanup(storage): stop trying to uninstall Werkzeug

ci/cloudbuild/builds/generate-libraries.sh
Update the protobuf lists/deps during the `generate-libraries` build.
Any edits or new files this produces will be cause the build to fail
due to the subsequent git diff/status checks.  Part of #7372.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8961)
=> ci(generate-libraries): run update_libraries.sh

generator/generator_config.textproto, google/cloud/bigtable/internal/bigtable_auth_decorator.cc, google/cloud/bigtable/internal/bigtable_auth_decorator.h, google/cloud/bigtable/internal/bigtable_channel_refresh.cc, google/cloud/bigtable/internal/bigtable_channel_refresh.h, google/cloud/bigtable/internal/bigtable_logging_decorator.cc, google/cloud/bigtable/internal/bigtable_logging_decorator.h, google/cloud/bigtable/internal/bigtable_metadata_decorator.cc, google/cloud/bigtable/internal/bigtable_metadata_decorator.h, google/cloud/bigtable/internal/bigtable_round_robin.cc, google/cloud/bigtable/internal/bigtable_round_robin.h, google/cloud/bigtable/internal/bigtable_round_robin_test.cc, google/cloud/bigtable/internal/bigtable_stub.cc, google/cloud/bigtable/internal/bigtable_stub.h, google/cloud/bigtable/internal/bigtable_stub_factory_test.cc, google/cloud/bigtable/testing/mock_bigtable_stub.h
Part of the work for #8798 
I will need these things eventually. We might as well add them now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8964)
=> impl(bigtable): generate async streaming read rpcs in stubs

google/cloud/storage/internal/http_response.cc, google/cloud/storage/internal/http_response_test.cc
Maybe unsurprisingly, the error payloads are less structured that we
expected. This PR performs additional validation to avoid crashes while
trying to parse these payloads as a `ErrorInfo`.  If we could reliably
use exceptions I would just parse the code and handle any exception in
a single line of code, alas, we cannot.
Fixes #8965
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8968)
=> fix(storage): avoid crashes when parsing `ErrorInfo`

google/cloud/storage/internal/http_response_test.cc
Part of the work for #8965
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8970)
=> test(storage): more test cases for `ErrorInfo` parser

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/google_cloud_cpp_bigtable.bzl, google/cloud/bigtable/internal/data_connection.h, google/cloud/bigtable/mutation_branch.h, google/cloud/bigtable/options.h, google/cloud/bigtable/row_reader.h, google/cloud/bigtable/table.h
Move `MutationBranch` into its own file so I can include it from `DataConnection` and `Table`. I would rather do this than 1) add a public definition to a file in the `bigtable/internal/` directory 2) develop `DataConnection` in the `bigtable/` directory
Move the policy definitions out of `DataConnection`. (I am not sure why the generator defines things here...). If I don't do it, there would be a cyclic dependency: `data_connection.h` -> `row_reader.h` -> `data_client.h` -> `client_options.h` -> `options.h` -> `data_connection.h`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8967)
=> refactor(bigtable): move some definitions around

google/cloud/common_options.h, google/cloud/internal/curl_rest_client.h, google/cloud/internal/oauth2_minimal_iam_credentials_rest.cc, google/cloud/internal/oauth2_minimal_iam_credentials_rest.h, google/cloud/internal/rest_options.h
common_options.h already defines an `google::cloud::EndpointOption`, having an additional `google::cloud::rest_internal::RestEndpointOption` is unnecessary as the endpoint used to create the `RestClient` should be resolved by the library using the `RestClient`.
Additionally, add comments emphasizing the immutability of an endpoint in a `CurlRestClient` and add comments emphasizing the relationship between `EndpoinOption` and `AuthorityOption`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8977)
=> refactor(rest): remove RestEndpointOption from Rest library

generator/generator_config.textproto, google/cloud/monitoring/internal/metric_auth_decorator.cc, google/cloud/monitoring/internal/metric_auth_decorator.h, google/cloud/monitoring/internal/metric_connection_impl.cc, google/cloud/monitoring/internal/metric_connection_impl.h, google/cloud/monitoring/internal/metric_logging_decorator.cc, google/cloud/monitoring/internal/metric_logging_decorator.h, google/cloud/monitoring/internal/metric_metadata_decorator.cc, google/cloud/monitoring/internal/metric_metadata_decorator.h, google/cloud/monitoring/internal/metric_stub.cc, google/cloud/monitoring/internal/metric_stub.h, google/cloud/monitoring/metric_client.cc, google/cloud/monitoring/metric_client.h, google/cloud/monitoring/metric_connection.cc, google/cloud/monitoring/metric_connection.h, google/cloud/monitoring/mocks/mock_metric_connection.h
At least one team is interested in using the asynchronous version of
this RPC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8983)
=> feat(monitoring): generate async version of `CreateTimeSeries()`

google/cloud/storage/internal/grpc_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8987)
=> cleanup(GCS+gRPC): avoid excessive copies in `*BucketAcl()`

google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/retry_policy.h, google/cloud/spanner/retry_policy_test.cc
Fixes #7394 (well, this is all I am going to do on it unless it becomes a bigger problem)
Refactor spanner to point to the [common helper](https://github.com/googleapis/google-cloud-cpp/blob/0ff878ea71ccea66e1e2c7cf74e703683ec7ad94/google/cloud/internal/retry_policy.cc#L24-L30).
Note that we drop the "Connection closed with unknown cause" case. It was fixed 4 years ago. Googlers can see: https://b.corp.google.com/issues/27794742#comment14
We also drop the "HTTP/2 error code: INTERNAL_ERROR" case. It is covered by matching on "Received Rst Stream". Googlers can see: https://b.corp.google.com/issues/33017979 for an example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cl …
=> refactor(spanner): use common RST_STREAM status helper

google/cloud/storage/client_options.cc
For historical reasons, the storage library uses
`CLOUD_STORAGE_TRACING_COMPONENTS`.  It was filtering the components
provided in this environment variable, which made it impossible to
enable logging for GCS+gRPC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8994)
=> fix(GCS+gRPC): use all tracing components from environment variable

google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/tests/object_integration_test.cc
A few fields in the `WithObjectMetadata()` option were not used. Notably
`custom_time()` and `acl()`.  I changed the unit test to make it easier
to inspect that all fields are tested, the expectation is created via
`ExpectedFullObjectMetadata()`.  A few fields are complicated, because
they only setable in requests that create new objects.
To fix the problem I refactored the code to copy mutable fields from the
`storage::*Request` classes to the `google.storage.v2.Object` proto.
Fixes #8990
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8993)
=> fix(GCS+gRPC): unused mutable Object fields

doc/contributor/howto-guide-update-googleapis-sha.md, external/googleapis/renovate.sh
Add a script to update the googleapis Bazel/CMake dependencies, much
like the renovate-bot would do if it was enabled.  Update the how-to
doc to use the script.
Part of #7372.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9017)
=> refactor(common): encapsulate googleapis updates in a script

cmake/templates/config.pc.in
The definition of `exec_prefix` was wrong, but probably harmless, as we
also defined `libdir` incorrectly.  These are the correct definitions
according to:
https://people.freedesktop.org/~dbn/pkg-config-guide.html#concepts
If I read the documentation incorrectly: at least we just need to fix
one place.
Part of the work for #8992
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9019)
=> fix: use correct paths in `pkg-config` files

generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator.h, generator/internal/scaffold_generator_test.cc
I should have removed the code to generate these files when we stopped
using them.
Part of the work for #8992
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9020)
=> cleanup(generator): do not generate `config.pc.in` files

ci/cloudbuild/builds/cmake-single-feature.sh, cmake/AddPkgConfig.cmake, cmake/CompileProtos.cmake, cmake/GoogleCloudCppCommon.cmake, cmake/templates/config.pc.in, external/googleapis/CMakeLists.txt, google/cloud/storage/google_cloud_cpp_storage.cmake
Change the `config.pc.in` template to use our own variables
(`GOOGLE_CLOUD_CPP_PC_{LIB,INCLUDE}DIR`) for the `libdir=` and
`includedir=` values. A new helper CMake macro sets these variables to
`CMAKE_INSTALL_{LIB,INCLUDE}DIR` when these are absolute paths,
otherwise it adds the right prefix.
I changed `cmake-single-feature.sh` to test for this new behavior. Maybe
abusing the build.
Fixes #8992
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9022)
=> fix: support absolute paths for `CMAKE_INSTALL_*DIR`

google/cloud/storage/examples/storage_lifecycle_management_samples.cc, google/cloud/storage/lifecycle_rule.cc, google/cloud/storage/lifecycle_rule.h
A new helper function to avoid typos. Also add the snippet for this
feature.
Fixes #8690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9028)
=> feat(storage): helper functions for new lifecycle action

google/cloud/spanner/admin/integration_tests/backup_integration_test.cc, google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc
Setting of `database_dialect` in the `CreateDatabase()` result has
been fixed.  `RestoreDatabase()`, however, remains an issue.
Part of #8573.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9029)
=> test(spanner): remove database_dialect workaround for CreateDatabase

google/cloud/storage/bucket_metadata.cc, google/cloud/storage/bucket_metadata_test.cc, google/cloud/storage/internal/bucket_metadata_parser.cc, google/cloud/storage/internal/bucket_metadata_parser.h, google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/lifecycle_rule_parser.cc, google/cloud/storage/lifecycle_rule.cc, google/cloud/storage/lifecycle_rule.h, google/cloud/storage/lifecycle_rule_test.cc, google/cloud/storage/tests/bucket_integration_test.cc
GCS is adding additional Object Lifecycle Management rules. This PR
introduces support for the rules in REST and gRPC.
Part of the work for #8968
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9030)
=> feat(storage): implement suffix and prefix OLM rules

google/cloud/storage/tests/bucket_integration_test.cc
This test failed a couple of times for me, when running from my
workstation against production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9031)
=> cleanup(storage): deflake bucket IAM integration test

google/cloud/bigtable/internal/data_connection.cc, google/cloud/bigtable/internal/data_connection.h
Part of the work for #8798 
Add the DataConnection API as defined in this (internal) [document](https://docs.google.com/document/d/1NjGK7_1gfkxavxFxIHcKoDyxPWGITnYL5JBH18ZNG6A/edit?resourcekey=0-A9nSevk5ZyWVGzhxtXE93Q).
The one difference is that I forgot about resources (app profile id + table name) in the document. We do not want to store resources in the Connection. So the Table must pass the resource names with each request.
I tried my best to minimize the `NOLINT` eye sore. `NOLINTBEGIN`/`NOLINTEND` [is a thing](https://clang.llvm.org/extra/clang-tidy/), but not until clang-tidy 15.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9033)
=> impl(bigtable): add unimplemented Connection API

google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsub/ci/lib/pubsub_emulator.sh, google/cloud/pubsub/message.h, google/cloud/pubsub/mocks/mock_ack_handler.h, google/cloud/pubsub/quickstart/Makefile, google/cloud/pubsub/version.h
The name of the service is Cloud Pub/Sub, fixed it in a number of
places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9034)
=> doc(pubsub): fix typos Pub/Sub vs. Pubsub

CHANGELOG.md, generator/integration_tests/golden/tests/golden_kitchen_sink_option_defaults_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_option_defaults_test.cc, google/cloud/internal/populate_common_options.cc, google/cloud/internal/populate_common_options_test.cc, google/cloud/spanner/internal/defaults_test.cc
Make the preference order be (1) `${emulator_env}`, (2) `${endpoint_env}`,
(3) `EndpointOption`, and (4) default value.
The changes to the tests are good indications that the new ordering is more
logical.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9032)
=> fix(common)!: adjust env/option/default override order for endpoints

ci/cloudbuild/builds/cmake-install.sh, google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/google_cloud_cpp_bigtable_mocks.bzl, google/cloud/bigtable/mocks/mock_data_connection.h
Part of the work for #8798 
`bigtable_mocks` is a public namespace. So we develop in `bigtable_internal` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9035)
=> impl(bigtable): add mock data connection

google/cloud/internal/populate_common_options.cc, google/cloud/internal/populate_common_options.h
Follow the `PopulateCommonOptions()` specification and actually ignore
empty environment-variable names, rather than assuming that `${}` never
has a value (or that the `std::getenv()` implementation will never
return a value for an empty name).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9042)
=> impl(common): do not lookup empty environment-variable names

google/cloud/bigtable/mocks/mock_data_connection.h, google/cloud/bigtable/table.h, google/cloud/bigtable/table_test.cc
Part of the work for #8798 
I see that the test defines global `std::string`s. This is not the PR to deal with those.
Also, move `MockDataConnection` from `bigtable_internal` -> `bigtable_mocks::internal`. I think that is a better idea.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9059)
=> impl(bigtable): add Table ctor that accepts a DataConnection

ci/cloudbuild/builds/generate-libraries.sh, google/cloud/baremetalsolution/doc/main.dox
Teach the `generate-libraries` build how to update the generated endpoint
documentation.
Run it to update the `baremetalsolution` doc, which is the only one that
still has the required injection markers.  A followup PR will re-add these
markers to all the other `main.dox` files.
This, and the recent addition of `external/googleapis/update_libraries.sh`
to the `generate-libraries` build, means the the "How-to Guide" for adding
a generated library can be simplified, but that remains a TODO for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9056)
=> doc: update generated endpoint documentation during generate-libraries

ci/cloudbuild/builds/gcs-grpc.sh, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake, google/cloud/storage/grpc_plugin.cc, google/cloud/storage/grpc_plugin_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl, google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc, google/cloud/storage/tests/grpc_hmac_key_integration_test.cc, google/cloud/storage/tests/grpc_integration_test.cc, google/cloud/storage/tests/grpc_object_acl_integration_test.cc, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc, google/cloud/storage/tests/grpc_service_account_integration_test.cc, google/cloud/storage/tests/object_read_range_integration_test.cc, google/cloud/storage/tests/signed_url_integration_test.cc
The integration tests against production were disabled while the protos
stabilized. There are no anticipated breaking changes at this point.
We cannot pass the options created for a `GrpcClient` to a `CurlClient`.
The latter has a very subtle interpretation of `AuthorityOption` as it
supports two separate services: `iamcredentials.googleapis.com` is
used to sign blobs.
A number of tests remain disabled because they use metadata operations
in gRPC, which are not ready in production. Changed their TODO entries
to point to the right bug.
Fixes #7257
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9060)
=> ci: enable GCS+gRPC production integration tests

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/testing/mock_policies.h
Part of the work for #8799 , #8798 
This PR implements DataConnection::Apply(). It includes getters for call vs. connection options. The Table::Apply() piece will be addressed in a later PR, when I have set up the integration tests to exercise the new code path.
The old code path is [here](https://github.com/googleapis/google-cloud-cpp/blob/e6a8a6ffe1396cdd16ce4405d8578fbd9420d2cc/google/cloud/bigtable/table.cc#L72)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9070)
=> impl(bigtable): implement DataConnection::Apply()

ci/cloudbuild/builds/publish-docs.sh
The latest release of gcp-docuploader does not work (version mismatches
with Protobuf). This pins the script to use an unreleased version, that
is ugly, but works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9076)
=> ci: pin gcp-docuploader to a working version

generator/integration_tests/golden/golden_thing_admin_connection_idempotency_policy.cc, generator/internal/idempotency_policy_generator.cc, google/cloud/artifactregistry/artifact_registry_connection_idempotency_policy.cc, google/cloud/bigquery/connection_connection_idempotency_policy.cc, google/cloud/bigtable/admin/bigtable_instance_admin_connection_idempotency_policy.cc, google/cloud/bigtable/admin/bigtable_table_admin_connection_idempotency_policy.cc, google/cloud/billing/cloud_billing_connection_idempotency_policy.cc, google/cloud/containeranalysis/container_analysis_connection_idempotency_policy.cc, google/cloud/datacatalog/data_catalog_connection_idempotency_policy.cc, google/cloud/datacatalog/policy_tag_manager_connection_idempotency_policy.cc, google/cloud/functions/cloud_functions_connection_idempotency_policy.cc, google/cloud/iam/iam_connection_idempotency_policy.cc, google/cloud/iam/iam_policy_connection_idempotency_policy.cc, google/cloud/iap/identity_aware_proxy_admin_connection_idempotency_policy.cc, google/cloud/iot/device_manager_connection_idempotency_policy.cc, google/cloud/resourcemanager/folders_connection_idempotency_policy.cc, google/cloud/resourcemanager/organizations_connection_idempotency_policy.cc, google/cloud/resourcemanager/projects_connection_idempotency_policy.cc, google/cloud/secretmanager/secret_manager_connection_idempotency_policy.cc, google/cloud/securitycenter/security_center_connection_idempotency_policy.cc, google/cloud/servicedirectory/registration_connection_idempotency_policy.cc, google/cloud/spanner/admin/database_admin_connection_idempotency_policy.cc, google/cloud/spanner/admin/instance_admin_connection_idempotency_policy.cc, google/cloud/tasks/cloud_tasks_connection_idempotency_policy.cc
The `SetIamPolicy()` operations can be idempotent if the request has an
ETag value. The ETag value is a pre-condition, that changes when the
operation succeeds.  In other words, the operation can succeed at
most once: all such operations are idempotent.
Fixes #2595
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9078)
=> feat(generator): `SetIamPolicy()` can be idempotent

google/cloud/spanner/BUILD.bazel, google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/client_test.cc, google/cloud/spanner/google_cloud_cpp_spanner_mocks.bzl, google/cloud/spanner/internal/partial_result_set_source_test.cc, google/cloud/spanner/mocks/row.h, google/cloud/spanner/results_test.cc, google/cloud/spanner/row_benchmark.cc, google/cloud/spanner/row_test.cc, google/cloud/spanner/samples/mock_execute_query.cc
Begin a migration of test-only code out of `google_cloud_cpp_spanner` and
into `google_cloud_cpp_spanner_mocks`.  Followup work will deprecate
`spanner::MakeTestRow()`.  The implementation probably can't move until
the deprecation is complete because of the restrictions on test-only
dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9080)
=> test(spanner): expose spanner::MakeTestRow() as spanner_mocks::MakeRow()

ci/cloudbuild/builds/publish-docs.sh
Make multiple attempts to upload the documentation tarballs.  The
`docuploader` Python module does not do this automatically, and changing
it looks more complicated than I expected.
Fixes #9012
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9079)
=> ci: deflake `publish-docs` build

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_read_object_test.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/grpc_object_read_source.h, google/cloud/storage/internal/grpc_object_read_source_test.cc, google/cloud/storage/internal/storage_stub_factory_test.cc, google/cloud/storage/testing/mock_storage_stub.h
Previously we timed out a download if it failed to complete the download
in a given time. This requires setting excessive timeouts for
applications that download both small objects (which take milliseconds)
and large objects (which can take minutes).
Furthermore, some applications start a download and then consume the
data slowly.  The timeout values for such applications would need to be
too large too.
This PR uses the asynchronous API to download objects. This API allows
us to timeout a `Read()` call, and abort the download if it is not
making progress.
Fixes #7300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9072)
=> feat(GCS+gRPC): timeout downloads on lack of progress

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc, google/cloud/storage/tests/grpc_object_acl_integration_test.cc
Over JSON the semantics are "update-or-insert" for `*AccessControl`
operations, when we emulate these functions over gRPC we should
follow the same semantics.
Fixes #9055
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9077)
=> fix(GCS+gRPC): use "upsert" semantics for `*AccessControl`

google/cloud/bigtable/benchmarks/benchmark.cc, google/cloud/bigtable/benchmarks/embedded_server_test.cc, google/cloud/bigtable/client_options.h, google/cloud/bigtable/internal/defaults.cc, google/cloud/bigtable/internal/defaults_test.cc, google/cloud/bigtable/options.h
Fixes #9027 and does a tiny bit of the work for #9081 
This change:
1. Makes it possible to use `EndpointOption` with `DataClient`, `AdminClient`, and `InstanceAdminClient`
2. Recommends against using `DataEndpointOption`, `AdminEndpointOption`, and `InstanceAdminEndpointOption` to configure the above classes in documentation only.
Note that our `Default*Options()` functions expect `DefaultOptions()` to provide input via `*EndpointOption`. (for example [here](https://github.com/googleapis/google-cloud-cpp/blob/7b535eeb2db520e47988a02e6601199268a2fa08/google/cloud/bigtable/internal/defaults.cc#L199-L200)). I will clean this stuff up as part of #9081.
--- …
=> feat(bigtable): configure `*Client`s with `EndpointOption`

CHANGELOG.md, google/cloud/spanner/mocks/row.h, google/cloud/spanner/row.h, google/cloud/spanner/version.h
See #9086 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9087)
=> test(spanner): start deprecation period for spanner::MakeTestRow()

ci/cloudbuild/builds/coverage.sh
The bash-based code coverage uploader is deprecated, and the new thing
is v0.2.x... sigh.  In any case, it makes little sense to stay on the
deprecated version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9088)
=> ci: update code coverage uploader

google/cloud/bigtable/table.cc, google/cloud/bigtable/table_bulk_apply_test.cc
Fixes #9089 ... although this should be tested properly.
We now check the loop condition before sleeping instead of after.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9091)
=> fix(bigtable): remove unnecessary sleeps from BulkApply

google/cloud/storage/internal/grpc_object_read_source.cc
A `google::cloud::internal::AsyncStreamingReadRpc<T>` object must not
be deleted until the `Finish()` operation completes.  This is a
requirement imposed by `grpc::ClientAsyncReaderInterface<>`.
I obviously forgot about this requirement in the implementation of
progress-based timeouts.
Fixes #9094
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9096)
=> fix(GCS+gRPC): streaming RPC lifetime was too short

.github/renovate.json, bazel/google_cloud_cpp_deps.bzl, ci/cloudbuild/dockerfiles/debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35-cxx11.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile, ci/generate-markdown/generate-packaging.sh, doc/packaging.md, generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/internal/descriptor_utils.cc
Starting with this release Protobuf (the package) is vX.y (e.g. v21.1),
while the C++ components are v3.21.1.  The major number for C++ could
increase with a new release for protobuf, without affecting the major
number for other languages.
In this PR I:
- Change the Docker images and Bazel WORKSPACE files to download the
newer proto
- Changed the `renovate.json` configuration to use the new version
numbers (I hope)
- Updated the documentation w.r.t. the minimum required version for
the micro generator, it no longer can use older versions.
- Fixed some formatting problems in packaging.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9092)
=> chore(deps): update protobuf to v3.21.1

ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile, doc/packaging.md
Our packaging instructions used `-H.` to set the source directory for
the CMake configuration step.  `-H` is an undocumented option, starting
with CMake 3.13 we can use `-S .`.
Likewise, our packaging instructions included `-DCMAKE_CXX_STANDARD=11`
for Abseil. This is not needed because the compilers we support all
default to C++14 or higher.
Finally, in some distros we compiled all libraries except gRPC as shared
libraries.  That seems unnecessarily inconsistent and confusing.
Fixes #9085
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9099)
=> cleanup: modernize packaging instructions

cmake/EnableWerror.cmake
As long as CMake >= 3.8, this will automatically require C++ >= 11 to
compile the library and their dependencies.  This is only relevant with
Apple Clang, the last compiler we support that defaults to C++98 (and
apparently will always default to C++98).  All other compilers we
support default to C++14 or higher.
While this only works for CMake >= 3.8, I expect this is almost always
the case on macOS.  In other words, this can fail to automate things in
theory, but should work well in practice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9104)
=> feat: if available use compile features to request C++ >= 11

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
This is intended for troubleshooting, adding a timeout is unlikely to
produce better performance (except maybe by cutting tail latencies).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9109)
=> test(storage): support transfer timeouts in benchmark

google/cloud/bigtable/testing/table_integration_test.cc, google/cloud/bigtable/testing/table_integration_test.h, google/cloud/bigtable/tests/data_integration_test.cc
Fixes #8798 
Introduce the mechanism to test both the `DataClient` and `DataConnection` implementations of `Table` in integration tests.
Most tests use multiple client calls, but `TableReadRowsWrongTable` only calls `ReadRows()`. So we can convert that one to use value parameters. As more client calls are implemented, we will convert more tests to `TEST_P`s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9110)
=> test(bigtable): exercise DataConnection in integration tests

generator/generator_config.textproto, google/cloud/storage/internal/storage_auth_decorator.cc, google/cloud/storage/internal/storage_auth_decorator.h, google/cloud/storage/internal/storage_logging_decorator.cc, google/cloud/storage/internal/storage_logging_decorator.h, google/cloud/storage/internal/storage_metadata_decorator.cc, google/cloud/storage/internal/storage_metadata_decorator.h, google/cloud/storage/internal/storage_round_robin.cc, google/cloud/storage/internal/storage_round_robin.h, google/cloud/storage/internal/storage_round_robin_test.cc, google/cloud/storage/internal/storage_stub.cc, google/cloud/storage/internal/storage_stub.h, google/cloud/storage/testing/mock_storage_stub.h
This is the start of implementing Async operations for GCS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9115)
=> impl(storage): add `AsyncDeleteObject()` to stubs

ci/cloudbuild/build.sh
`ci/cloudbuild/build.sh --docker --trigger=xxx --verbose` failed
to actually be verbose in the local build within the docker image
because the `--env=VERBOSE_FLAG=${VERBOSE_FLAG:-}` setting was
ignored in the `ci/cloudbuild/build.sh --local` reinvocation.
So, make the `VERBOSE_FLAG` initialization heed an existing value
in the environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9119)
=> ci: allow --verbose flag to affect output of docker build

google/cloud/internal/getenv.cc
The use `_dupenv_s()` is a MSVC requirements, it is not needed for GCC
under Windows. Note that we do not plan to test systematically with this
compiler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9140)
=> fix(common): compile with GCC (MinGW-w64) under Windows

google/cloud/storage/google_cloud_cpp_storage.cmake
I think we may need to reimplement these functions to convert from
UTF-8 to UTF-16 (or is it UTF-32?).  For now, just disable the
deprecation warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9143)
=> fix(storage): disable MSVC C++17 deprecation warnings

google/cloud/internal/getenv.cc
* consistently use `#if defined(_MSC_VER)` over `#ifdef _MSC_VER`
* `s/_MSVC_VER)/_MSC_VER/`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9149)
=> cleanup(common): nit-pick cleanup to #9140

google/cloud/dataplex/quickstart/BUILD.bazel, google/cloud/dataplex/quickstart/CMakeLists.txt, google/cloud/dialogflow_cx/quickstart/BUILD.bazel, google/cloud/dialogflow_cx/quickstart/CMakeLists.txt, google/cloud/dialogflow_es/quickstart/BUILD.bazel, google/cloud/dialogflow_es/quickstart/CMakeLists.txt
I forgot these in #9137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9148)
=> cleanup: some quickstarts reference GA targets

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/bigtable_client_unit_tests.bzl, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/legacy_table_test.cc, google/cloud/bigtable/table_test.cc
I am going to hurt myself on these eventually....
Drop test fixtures from `internal_data_connection_impl.cc`. Also do some light editing like `connection`->`conn` and adding an argument to the mutation factory functions.
Also split `table_test.cc` into tests that use the DataConnection and those that use the DataClient in a fixture. A lot of the DataClient tests should be salvaged, but I don't want to deal with them right now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9152)
=> refactor(bigtable): remove/isolate some test fixtures

google/cloud/internal/curl_impl.cc, google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/tests/object_read_headers_integration_test.cc
The `storage::ObjectReadStream` class exposes debugging information via
the `std::multimap<std::string, std::string> headers()` function. Note
that this is a **multi** map because headers can be duplicated in some
cases.  At some point I made a mistake and returned an extra
`:curl-peer` header in each `ObjectReadSource::Read()` call.
If the application is downloading a very large object (say 100GiB) and
the application processes the data in small chunks (say a few KiB) then
millions of calls to `ObjectReadSource::Read()` would take place.
Consequently, the multimap contained millions of duplicate entries.
Previously this went unnoticed because (1) the multimap is released
when the download completes, and (2) our benchmarks and tests tend to
perform larger reads (say a few MiB) from …
=> fix(storage): do not duplicate debugging headers

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc
Part of the work for #8802 
Here is the Table implementation of this retry loop: https://github.com/googleapis/google-cloud-cpp/blob/2a00f3d17425a15987674ba79548680be4330bed/google/cloud/bigtable/table.cc#L153-L180
The tests are mostly from: [table_bulk_apply_test.cc](https://github.com/googleapis/google-cloud-cpp/blob/2a00f3d17425a15987674ba79548680be4330bed/google/cloud/bigtable/table_bulk_apply_test.cc), but hopefully they are a bit clearer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9155)
=> impl(bigtable): implement DataConnection::BulkApply()

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h
Define member functions in the same order as they appear in `data_connection.{h,cc}`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9167)
=> refactor(bigtable): reorder code; waste builds

google/cloud/internal/pagination_range.h, google/cloud/internal/pagination_range_test.cc
We used to write code like this:
```cc
template <typename U>
static auto constexpr E(U& u) {
return std::move(*u.mutable_next_page_token());
}
template <typename U>
static auto constexpr E(U& u) {
return std::move(u.next_page_token);
}
```
The idea is that only one of these overloads would be available because
of SFINAE.  Some versions of GCC complain that this is ambiguous.
Fixes #9111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9144)
=> fix(common): workaround GCC "ambiguous" overload errors

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/table.cc
Part of the work for #8799 (implementing `Table::(Async)ReadModifyWriteRow()`)
I want to use this function in the `DataConnection`, so let's move it now to keep PRs small-ish. Also add a unit test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9177)
=> refactor(bigtable): move transform; add unit test

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/tests/data_integration_test.cc
Fixes #8804 
The implementation is a direct copy from `table.cc`: https://github.com/googleapis/google-cloud-cpp/blob/be0097b0adea5fd1a911e47e105ee84021042bcb/google/cloud/bigtable/table.cc#L222-L239
(We copy the code instead of factoring it out, because eventually there will only be one version of the code).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9176)
=> impl(bigtable): implement modern Table::ReadRow()

google/cloud/bigtable/internal/data_connection.cc, google/cloud/bigtable/internal/data_connection.h, google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/mocks/mock_data_connection.h, google/cloud/bigtable/table.cc, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/tests/data_integration_test.cc
Part of the work for #8799
Note that I made an oopsies in the Connection's API. Good thing I am developing in `internal`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9181)
=> impl(bigtable): modern `Table::ReadModifyWriteRow()`

google/cloud/internal/async_read_write_stream_logging.h, google/cloud/internal/async_streaming_read_rpc_logging.h, google/cloud/internal/log_wrapper.h, google/cloud/internal/log_wrapper_test.cc, google/cloud/internal/minimal_iam_credentials_stub.cc, google/cloud/internal/streaming_write_rpc_logging.h, google/cloud/pubsub/internal/subscriber_logging.cc, google/cloud/spanner/internal/logging_result_set_reader.cc
Followup to #9169 to add error payloads to remaining `Status` logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9186)
=> feat(common): include status error payloads in the RPC log

google/cloud/storage/internal/generic_request.h, google/cloud/storage/internal/generic_request_test.cc
With this change, the `storage::Client` class could accept
`google::cloud::Options` parameters in the parameter packs, and they
will be ignored by the `*Request::set_multiple_options()` calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9191)
=> impl(storage): ignore `google::cloud::Options` in `*Request`

google/cloud/storage/internal/generic_request.h
Addresses a question in https://github.com/googleapis/google-cloud-cpp/pull/9191#pullrequestreview-998755291 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9196)
=> fix(storage): missing `set_multiple_options()` overload

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/tests/data_integration_test.cc
Part of the work for #8799 ; and this completes the `data_integration_test.cc` part of #9164 
The implementation code comes from:
https://github.com/googleapis/google-cloud-cpp/blob/f779bb99395bbdfe3aac51864ff2abf2a0b6dffc/google/cloud/bigtable/table.cc#L231-L244
https://github.com/googleapis/google-cloud-cpp/blob/f779bb99395bbdfe3aac51864ff2abf2a0b6dffc/google/cloud/bigtable/table.cc#L253-L254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9190)
=> impl(bigtable): modern `Table::CheckAndMutateRow()`

google/cloud/storage/google_cloud_cpp_storage.bzl, google/cloud/storage/google_cloud_cpp_storage.cmake, google/cloud/storage/internal/make_options_span.h, google/cloud/storage/internal/make_options_span_test.cc, google/cloud/storage/storage_client_unit_tests.bzl
To add per-operation options we need some helpers to create a span from
the parameter pack received by each operation.  With these helpers we
will be able to more easily add spans. For example:
```cc
class Client {
public:
...
template <typename... RequestOptions>
StatusOr<ObjectMetadata> GetObjectMetadata(
std::string const& bucket_name, std::string const& object_name,
RequestOptions&&... options) {
auto const span = internal::MakeOptionSpan(
options(), std::forward<RequestOptions>(options)...);
...
..
}
};
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9195)
=> impl(storage): helpers to create `OptionSpan`

google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_client.h, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/internal/hybrid_client.h, google/cloud/storage/internal/logging_client.cc, google/cloud/storage/internal/logging_client.h, google/cloud/storage/internal/raw_client.h, google/cloud/storage/internal/rest_client.cc, google/cloud/storage/internal/rest_client.h, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client.h, google/cloud/storage/testing/mock_client.h
To support per-operation options we need to get the
`google::cloud::Options` of a `RawClient`.  This is analogous to the
`options()` accessor in the `*Connection` classes for other libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9192)
=> impl(storage): `internal::RawClient` gains `options()`

google/cloud/storage/client.h, google/cloud/storage/client_service_account_test.cc, google/cloud/storage/internal/hmac_key_requests.h, google/cloud/storage/internal/make_options_span.h, google/cloud/storage/testing/client_unit_test.cc
This introduces support for per-operation `google::cloud::Options`,
starting with the operations related to service accounts.
This change also introduced some changes to the test fixtures that I
expect will be used in all tests.
Also fixed an unrelated typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9199)
=> feat(storage): per-operation options / service accounts

google/cloud/storage/client.h, google/cloud/storage/client_bucket_acl_test.cc
`BucketAccessControl` resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9202)
=> feat(storage): per-operation options / BucketAccessControl

google/cloud/internal/log_wrapper.h, google/cloud/internal/streaming_read_rpc_logging.h, google/cloud/internal/streaming_write_rpc_logging.h
Our logging convention is "func() << request" and "func() >> response".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9213)
=> cleanup(common): correct the direction on some request/response logging

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/bigtable_client_unit_tests.bzl, google/cloud/bigtable/google_cloud_cpp_bigtable.bzl, google/cloud/bigtable/internal/async_streaming_read.h, google/cloud/bigtable/internal/async_streaming_read_test.cc
Fixes #9172 
In future PRs, calls to `CompletionQueue::MakeStreamingReadRpc`:
https://github.com/dbolduc/google-cloud-cpp/blob/1c5231c7020b3b875c2b1ee7556b012fe65a4c26/google/cloud/bigtable/internal/async_row_sampler.cc#L69-L82
will become:
https://github.com/dbolduc/google-cloud-cpp/blob/dad6578857859f6b35dfbb9777eb15bd9cd350e6/google/cloud/bigtable/internal/darren_sampler.cc#L60-L66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9215)
=> impl(bigtable): add async streaming read helper

google/cloud/storage/client.h, google/cloud/storage/client_notifications_test.cc
`Notification` resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9205)
=> feat(storage): per-operation options / Notification

google/cloud/storage/client.h, google/cloud/storage/client_object_acl_test.cc
`ObjectAccessControl` resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9206)
=> feat(storage): per-operation options / ObjectAccessControl

google/cloud/storage/client.h, google/cloud/storage/client_object_copy_test.cc, google/cloud/storage/object_rewriter.cc, google/cloud/storage/object_rewriter.h
copying existing objects into new objects, that is, `CopyObject()`, the
`RewriteObject()` overloads, and `ComposeObject()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9207)
=> feat(storage): per-operation options / Object "copy"

google/cloud/storage/bucket_test.cc, google/cloud/storage/client.h
`Bucket` resources.
Part of the changes for #7691
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9209)
=> feat(storage): per-operation options / Bucket

google/cloud/storage/google_cloud_cpp_storage_grpc.cmake, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_client_upload_chunk_test.cc, google/cloud/storage/internal/storage_stub_factory_test.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl, google/cloud/storage/testing/mock_storage_stub.h
Predicting the total time (and therefore an appropriate timeout) for an
upload is difficult, as it depends on the size of the upload.  Instead,
we expect the upload to make progress, and timeout if they stall.
Fixes #9150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9198)
=> feat(GCS+gRPC): timeout uploads when stalled

google/cloud/storage/internal/bucket_acl_requests.cc, google/cloud/storage/internal/bucket_acl_requests.h, google/cloud/storage/internal/bucket_requests.cc, google/cloud/storage/internal/bucket_requests.h, google/cloud/storage/internal/default_object_acl_requests.cc, google/cloud/storage/internal/default_object_acl_requests.h, google/cloud/storage/internal/hmac_key_requests.cc, google/cloud/storage/internal/hmac_key_requests.h, google/cloud/storage/internal/notification_requests.cc, google/cloud/storage/internal/notification_requests.h, google/cloud/storage/internal/object_acl_requests.cc, google/cloud/storage/internal/object_acl_requests.h, google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/sign_blob_requests.cc, google/cloud/storage/internal/sign_blob_requests.h
Currently, some request types have `FromHttpResponse` methods that accept a `std::string const&` and other request types have `FromHttpResponse` methods that accept a `HttpResponse const&`. This makes it difficult to call them generically. This PR adds `HttpResponse const&` overloads to request types so that we can call `T::FromHttpResponse(HttpResponse const&)` on all request types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9227)
=> impl(storage): add HttpResponse overloads to be leveraged by rest refactor

google/cloud/storage/client.cc, google/cloud/storage/client_test.cc, google/cloud/storage/client_write_object_test.cc, google/cloud/storage/internal/object_write_streambuf_test.cc, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client.h, google/cloud/storage/internal/retry_client_test.cc, google/cloud/storage/internal/retry_object_read_source_test.cc, google/cloud/storage/object_test.cc, google/cloud/storage/testing/client_unit_test.cc, google/cloud/storage/testing/mock_client.h
The most interesting options in this case are the `RetryPolicyOption`
and `BackoffPolicyOption`.
Because now the policies are obtained from the `CurrentOptions()` and
these are initialized from `mock->options()`, the mocks need to return
sensible values for the options.
Some tests need to set the OptionsSpan, or the unit under test will not
work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9230)
=> impl(storage): use `CurrentOptions()` for `RetryClient`

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/tests/data_async_future_integration_test.cc
Part of the work for #8799 
Scroll up in the files to see the `ReadModifyWriteRow()` implementations. These changes are almost identical, but made to be async.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9237)
=> impl(bigtable): modern `Table::AsyncReadModifyWriteRow()`

google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h, google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/internal/rest_options.h
Need to support GCS using 308 for upload resume, but in a generic fashion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9236)
=> impl(rest): add support for treating specified error codes as non-failures

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_insert_object_media_test.cc, google/cloud/storage/internal/grpc_client_read_object_test.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_client_upload_chunk_test.cc, google/cloud/storage/internal/grpc_object_read_source.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9239)
=> feat(GCS+gRPC): use per-operation options

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/tests/data_async_future_integration_test.cc
Fixes #8799 
Again, this is basically a copy/paste of the synchronous implementation/tests directly above the new code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9242)
=> impl(bigtable): modern `Table::AsyncCheckAndMutateRow()`

google/cloud/internal/oauth2_compute_engine_credentials.cc, google/cloud/internal/oauth2_compute_engine_credentials.h, google/cloud/internal/oauth2_compute_engine_credentials_test.cc, google/cloud/storage/oauth2/compute_engine_credentials.cc, google/cloud/storage/oauth2/compute_engine_credentials_test.cc
We parse (but largely ignore) some metadata information about the GCE
service account. This parsing was very strict, rejecting the data if
fields were missing.  We now accept missing fields, and field them
with blank data (or empty lists).  We also accept the responses from
Cloud Shell, where the `scopes` field is a newline separated string,
instead of an array of strings.  This may be a bug in Cloud Shell, but
it makes the library unusable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9251)
=> fix: relax parsing for GCE informational fields

google/cloud/storage/client.h, google/cloud/storage/examples/CMakeLists.txt, google/cloud/storage/examples/storage_client_per_operation_samples.cc, google/cloud/storage/examples/storage_examples.bzl
Fixes #7691
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9247)
=> doc(storage): document per-operation options

google/cloud/internal/oauth2_google_credentials.cc, google/cloud/internal/oauth2_google_credentials.h, google/cloud/internal/oauth2_google_credentials_test.cc, google/cloud/storage/oauth2/google_credentials.cc, google/cloud/storage/oauth2/google_credentials_test.cc
Getting the authorization token from the GCE credentials can fail
when the credentials are created.  The metadata service may be
experiencing some kind of transient failure.  It is better to return the
credentials, and let the retry loops handle the problem.  If the failure
is not transient, the retry loop will handle that too.
Fixes #9249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9252)
=> fix: handle transient failures in the GCE credentials

google/cloud/storage/client.h
There are several deprecated functions in `storage::Client`. For
historical reasons they were at the beginning of the class. That is
prime real estate that we should use for the recommended functions, not
for deprecated stuff.
Fixes #9212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9254)
=> cleanup(storage): move deprecated functions down

google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h, google/cloud/internal/curl_impl_test.cc
Rest library needs to support requests specifying the full url in its path member, particularly in the case of GCS resumable uploads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9240)
=> impl(rest): handle full url specification in request path

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/tests/table_sample_rows_integration_test.cc
Fixes #8803 and finishes the sample fixture of #9164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9246)
=> impl(bigtable): modern `Table::SampleRows()`

ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh
GCS can log at the gRPC `*Stub` level, which can be useful in detailed
troubleshooting.  This change adds these logs to the integration tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9257)
=> ci(GCS+gRPC): also log the gRPC calls

google/cloud/storage/client.cc, google/cloud/storage/client_test.cc, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client.h, google/cloud/storage/testing/client_unit_test.cc, google/cloud/storage/testing/mock_client.h
This deprecated constructor
https://github.com/googleapis/google-cloud-cpp/blob/2c83a865b680bb7c498b00770c3bbf5cfb0480a4/google/cloud/storage/client.h#L3236-L3244
... consolidates the retry/backoff/idempotency policies as options
https://github.com/googleapis/google-cloud-cpp/blob/2c83a865b680bb7c498b00770c3bbf5cfb0480a4/google/cloud/storage/client_options.h#L51-L55
... but when the options get to the `RetryClient`, only the logging configuration is used.
https://github.com/googleapis/google-cloud-cpp/blob/2c83a865b680bb7c498b00770c3bbf5cfb0480a4/google/cloud/storage/client.cc#L45-L58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9255)
=> fix(storage): respect policies in deprecated constructor

google/cloud/options.cc
I think it is common to call `MergeOptions()` with an empty set of
`preferred` options (all calls to `Make*Connection()` work like this).
Therefore, at the cost of a small `if()` we can change the function in
this case from `O(n)` to `O(1)`.  Seems worthwhile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9258)
=> impl(common): micro-optimization on `internal::MergeOptions`

google/cloud/storage/testing/storage_integration_test.cc
Some uploads are timing out, and the timeout is about as long as the
retry policy.  Extend the retry policy to avoid spurious flakes.
Part of the work for #9256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9259)
=> ci(GCS+gRPC): deflake integration tests

google/cloud/storage/internal/hybrid_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9260)
=> cleanup(GCS+gRPC): remove spurious `std::move()`

google/cloud/storage/client.h
We have direct access to the `google::cloud::Options` used to initialize
a `RawClient`, we do not need to use the (deprecated) `ClientOptions`
created from it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9262)
=> cleanup(storage): avoid using deprecated `storage::ClientOptions`

google/cloud/bigtable/README.md
I grepped for `"}/)"` and found this one too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9265)
=> doc: broken link in Bigtable README

google/cloud/pubsub/internal/default_batch_sink.cc, google/cloud/pubsub/internal/default_batch_sink_test.cc, google/cloud/pubsub/internal/defaults.cc, google/cloud/pubsub/internal/defaults_test.cc, google/cloud/pubsub/options.h, google/cloud/pubsub/samples/samples.cc
New options to compress published messages before they are put on the
wire.  This can reduce bandwidth usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9270)
=> feat(pubsub): implement per-batch compression

google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client_test.cc
This is new behavior (or will be new behavior once it is rolled out) in
the GCS+gRPC implementation.  Trying to perform two concurrent uploads
will fail with `kAborted`.
Fixes #9182
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9263)
=> feat(GCS+gRPC): retry resumable uploads on `kAborted`

google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake, google/cloud/storage/internal/async_accumulate_read_object.cc, google/cloud/storage/internal/async_accumulate_read_object.h, google/cloud/storage/internal/async_accumulate_read_object_test.cc, google/cloud/storage/storage_client_grpc_unit_tests.bzl
The asynchronous version of `ReadObject()` will return all the bytes. We
need a function to asynchronously accumulate all the values from a
single `AsyncReadObject()` call to the `StorageStub`. This function does
to retry or resume the download, that will come later. In case you are
wonder, we will require applications to only make "ranged reads", where
the number of bytes downloaded is controlled by the application.
Part of the work for #9133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9277)
=> impl(GCS+gRPC): async accumulator for `ReadObject()`

google/cloud/spanner/samples/samples.cc
Apply a workaround to the samples, similar to that in the integration
tests, for the #8616 CreateBackup() timeout issue.  If we see the exact
error, we abandon the test but return a "success" status.
This does hide the problem from our view, but there is nothing the
client library can really do about it.  At least we can still see the
RPC trace should we look at the logs.
We're awaiting guidance on exactly how we should exercise operations
that may take hours to complete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9279)
=> test(spanner): workaround for CreateBackup() timeout in samples

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/data_client.h, google/cloud/bigtable/google_cloud_cpp_bigtable.bzl, google/cloud/bigtable/internal/async_row_reader.cc, google/cloud/bigtable/internal/async_row_reader.h, google/cloud/bigtable/table.h
Part of the work for #9174 
Our virtual connection base class cannot have templates. So we need to convert the arguments passed into `Table::AsyncReadRows(...)`.
I could use some help on whether the arguments to the `std::function` should be `const&` qualified or not:
```c++
// e.g. :
using RowFunctor = std::function<future<bool>(bigtable::Row const&)>;
using FinishFunctor = std::function<void(Status const&)>;
```
For the record, we `std::move` the row into the RowFunctor: https://github.com/dbolduc/google-cloud-cpp/blob/eba7d22730fd530caff55cb7469e54376b99e446/google/cloud/bigtable/internal/async_row_reader.cc#L106
but we do not `std::move` the status into the FinishFunctor:
https://github.com/dbolduc/google-cloud-cpp/blob/eba7d22730fd530caff55cb7469e54376b99e446/google/cloud/bigtable/int …
=> refactor(bigtable): untemplate `AsyncRowReader`

google/cloud/storage/internal/async_accumulate_read_object.cc, google/cloud/storage/internal/async_accumulate_read_object.h, google/cloud/storage/internal/async_accumulate_read_object_test.cc
More code in the `.h` file than strictly needed, and the API was not any
better.
I should have noticed this when I was writing the code. It become more obvious as I write another function that uses this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9288)
=> cleanup(GCS+gRPC): hide implementation details in .cc file

google/cloud/google_cloud_cpp_rest_internal.bzl, google/cloud/google_cloud_cpp_rest_internal.cmake, google/cloud/google_cloud_cpp_rest_internal_unit_tests.bzl, google/cloud/internal/curl_rest_response.cc, google/cloud/internal/rest_parse_json_error.cc, google/cloud/internal/rest_parse_json_error.h, google/cloud/internal/rest_parse_json_error_test.cc, google/cloud/storage/internal/http_response.cc, google/cloud/storage/internal/http_response_test.cc
We had two versions of the `ErrorInfo` parser from JSON payloads.  The
version in `storage/` was more robust when the payload was malformed.
The version in `cloud/internal/` preserved the HTTP status code (a good
idea in general).
This change consolidates the two implementations to the `rest_internal`
library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9293)
=> refactor(common): consolidate `ErrorInfo` parsing

google/cloud/storage/internal/async_accumulate_read_object.cc
I tried to cheat for the timers and avoid a callback, but it produces
deadlocks if the completion queue has a single thread.
Part of the work for #9133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9291)
=> fix(GCS+gRPC): all `co_await` should be callbacks

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/table.h, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/tests/data_async_future_integration_test.cc
Part of the work for #9174 
The only remaining client call is `Table::AsyncReadRow` (singular).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9294)
=> impl(bigtable): modern `Table::AsyncReadRows()`

google/cloud/storage/internal/async_accumulate_read_object.cc, google/cloud/storage/internal/async_accumulate_read_object.h, google/cloud/storage/internal/async_accumulate_read_object_test.cc
This is another building block for `AsyncClient::ReadObject()`. On
failures, it retries the `AsyncReadObject()` request skipping any bytes
already received. The retry loop stops on the first streaming RPC that
completes successfully, or when the retry policy is exhausted.
Part of the work for #9133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9296)
=> impl(GCS+gRPC): `AsyncReadObject` accumulator with retries

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/tests/data_async_future_integration_test.cc
Fixes #9174 , Fixes #9164 
The implementation code is copied from: https://github.com/googleapis/google-cloud-cpp/blob/aa2c0873870fdef2349c03baefdde10be6c4fa39/google/cloud/bigtable/table.cc#L437-L486
I know we do not like the copying, but this is the last of it.
The test cases are exactly the same as the synchronous version, `ReadRow()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9297)
=> impl(bigtable): modern `Table::AsyncReadRow()`

ci/verify_current_targets/CMakeLists.txt, google/cloud/bigquery/quickstart/CMakeLists.txt, google/cloud/bigtable/quickstart/CMakeLists.txt, google/cloud/iam/quickstart/CMakeLists.txt, google/cloud/pubsub/quickstart/CMakeLists.txt, google/cloud/spanner/quickstart/CMakeLists.txt, google/cloud/storage/quickstart/CMakeLists.txt
The generated quickstarts never set CMAKE_CXX_STANDARD, but we used to
set this in older code.  We also do not compile any "C" code so the
CMake projects do not need to waste time looking for a "C" compiler.
Also cleaned up one of the CI support files, which had a similar
set of problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9303)
=> cleanup: no CMAKE_CXX_STANDARD in quickstarts

google/cloud/storage/async_object_responses.h, google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake, google/cloud/storage/internal/async_accumulate_read_object.cc, google/cloud/storage/internal/async_accumulate_read_object.h, google/cloud/storage/internal/async_accumulate_read_object_test.cc
In the `storage` library we do not expose protos directly to the
application developer. This change introduces a function to convert the
protos accumulated by `AsyncAccumulateReadObjectFull()` into types that
are consistent with the public APIs.
Part for the work for #9133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9302)
=> impl(GCS+gRPC): convert `AsyncReadObject()` results

google/cloud/storage/async_client.h, google/cloud/storage/internal/async_connection.h, google/cloud/storage/internal/async_connection_impl.cc, google/cloud/storage/internal/async_connection_impl.h, google/cloud/storage/tests/async_client_integration_test.cc
Implement a function to asynchronously read a portion of the object
contents.  The callers must set the size of this portion, which gives
them control over how much memory this call uses. Use this new function
from one of the integration tests.
Fixes #9133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9305)
=> impl(GCS+gRPC): add `AsyncReadObjectRange`

google/cloud/bigtable/table.cc, google/cloud/bigtable/table.h, google/cloud/bigtable/table_test.cc
Part of the work for #7688
I do not think it makes sense to add Options to the constructors that accept a `DataClient`, because no options will apply to the calls.
The constructor is lacking documentation. I will add it later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9307)
=> impl(bigtable): `Table` accepts `Options`

ci/kokoro/lib/vcpkg.sh, ci/kokoro/macos/builds/cmake-vcpkg.sh, ci/kokoro/macos/builds/quickstart-cmake.sh
I searched for places where there is an explicit or implicit download,
and wrap them with a retry loop. This motivated me to refactor the
code to install vcpkg.
Incidentally, my previous changes to use GCS for the vcpkg cache may
have increased flakiness: instead of one download for the vcpkg binary
caches it performs N (currently 14). This is fixed in this change too.
Part of the work for #8723
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9306)
=> ci: deflake macOS builds with CMake

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/bigtable_client_unit_tests.bzl, google/cloud/bigtable/examples/table_admin_snippets.cc, google/cloud/bigtable/google_cloud_cpp_bigtable.bzl, google/cloud/bigtable/table_admin.cc, google/cloud/bigtable/wait_for_consistency.cc, google/cloud/bigtable/wait_for_consistency.h, google/cloud/bigtable/wait_for_consistency_test.cc
Fixes #7732 
This PR makes our internal helper to poll for consistency public. We change the type from a `Connection` to a `Client`, because it is a better API. We update our sample code to use the new shiny.
I considered putting this in `bigtable/admin/`, but decided against mixing the generated code. I could be convinced to change it and update the `.codecov.yml` to not ignore the entire `bigtable/admin/` directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9310)
=> feat(bigtable): add `AsyncWaitForConsistency()` helper for Table Admin

CMakeLists.txt
The CMake project was defined as using both "C++" (aka `CXX`) and "C",
but only C++ is used. Removed the search for the "C" compiler, as we
will not use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9324)
=> cleanup: no need to search for the "C" compiler

google/cloud/pubsub/snapshot_builder.h, google/cloud/pubsub/subscription_builder.cc, google/cloud/pubsub/subscription_builder.h, google/cloud/pubsub/subscription_builder_test.cc, google/cloud/pubsub/topic_builder.h
We provide a few helpers to build the protos. While this may not be a
good idea in the long run, it is the current plan, so we need these
updates from time to time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9326)
=> feat(pubsub): update subscription builders

ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile, ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile, ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile, ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile, ci/cloudbuild/dockerfiles/demo-ubuntu-jammy.Dockerfile, ci/generate-markdown/generate-packaging.sh, doc/packaging.md
Our instructions did not highlight why we recommend the magic `sed`
command to tweak Abseil. The command is easy to miss, and deserves a
larger warning. On macOS with homebrew this is even more tricky, as
homebrew does not patch Abseil's headers.
I changed the recommended command to reflect the default C++ version for
each platform.
I also updated the instructions around enabling additional libraries
with CMake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9334)
=> doc: improve documentation around Abseil's ABI pinning

ci/cloudbuild/builds/cxx14.sh, ci/cloudbuild/dockerfiles/fedora-36-cxx14.Dockerfile, ci/cloudbuild/triggers/cxx14-ci.yaml, ci/cloudbuild/triggers/cxx14-pr.yaml
Before we can stop testing with C++11 we need to start testing with
C++14.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9337)
=> ci: add new build to test with C++14

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_result.cc, google/cloud/storage/benchmarks/throughput_result.h, google/cloud/storage/benchmarks/throughput_result_test.cc
Sometimes we need to pair the upload and download lines. This adds
enough information (object name, generations) to the log lines to do
so.
It also flushes the default `google::cloud::LogSink` if an error is
detected.  That can produce better logs to troubleshoot problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9344)
=> test(storage): log more details on success

cmake/FindCurlWithTargets.cmake
We need to define CURL_STATICLIB when we use static Curl on Windows.
If we don't define CURL_STATICLIB for static Curl on Windows,
google-cloud-cpp refers wrong symbols.
For example, https://github.com/apache/arrow/pull/13404 encountered
this problem:
https://github.com/apache/arrow/runs/7004628336?check_suite_focus=true#step:11:751
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe:
../windows/arrow-8.0.0.9000/lib/i386/libarrow_bundled_dependencies.a(curl_wrappers.cc.obj):(.text+0x2):
undefined reference to `_imp__curl_global_cleanup'
libarrow_bundled_dependencies.a includes libgoogle_cloud_cpp*.a and
curl_wrappers.cc.obj in the above log is a file in google-cloud-cpp.
I confirmed that this change solves this problem in …
=> fix: add missing -DCURLSTATICLIB for system static Curl on Windows

ci/cloudbuild/dockerfiles/demo-alpine-stable.Dockerfile, ci/cloudbuild/triggers/demo-alpine-stable-ci.yaml, ci/cloudbuild/triggers/demo-alpine-stable-pr.yaml, ci/generate-markdown/generate-packaging.sh, doc/packaging.md, google/cloud/bigquery/quickstart/Makefile, google/cloud/bigtable/quickstart/Makefile, google/cloud/iam/quickstart/Makefile, google/cloud/pubsub/quickstart/Makefile, google/cloud/spanner/quickstart/Makefile, google/cloud/storage/quickstart/Makefile
This is our first build using `musl`.  Fortunately, Alpine stays fairly
up-to-date with all our dependencies, so we can just use the packages.
I had to fix the `*/quickstart/Makefile` files because the default on
this platform is C++17, and our makefiles were unnecessarily hard-coding
C++11.
Part of the work for #510 (I need to manually add the triggers once this is merged)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9347)
=> ci: create new build for Alpine:3.16 (aka Stable)

google/cloud/internal/log_wrapper.cc, google/cloud/internal/log_wrapper.h, google/cloud/internal/log_wrapper_test.cc
Add `DebugString(std::string, TracingOptions const&)` for adding a plain
string to the RPC log, but with the `truncate_string_field_longer_than`
behavior of `google::protobuf::TextFormat::Printer`.
This will be used in an upcoming change that will log a `resume_token`
from the Spanner streaming read/query protocol, and which is extremely
long.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9351)
=> feat(common): truncation support for plain strings in the RPC log

google/cloud/google_cloud_cpp_grpc_utils.bzl, google/cloud/google_cloud_cpp_grpc_utils.cmake, google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl, google/cloud/internal/routing_matcher.h, google/cloud/internal/routing_matcher_test.cc
Part of the work for #9121
For context, this is how the `RoutingMatcher` class will be used:
https://github.com/dbolduc/google-cloud-cpp/blob/b173e447940dc3d6ae71d00f9b570e6c5262058d/generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc#L113-L158
And if you were curious, this branch has the full implementation:
https://github.com/googleapis/google-cloud-cpp/compare/main...dbolduc:wip-routing-parameters?expand=1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9353)
=> impl(common): add explicit routing matcher

.github/renovate.json
Protobuf no longer uses something that Renovate can handle by default.
As usual, one cannot test these changes so we will have to see if they work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9365)
=> chore(renovate): configure protobuf versioning

google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
The unit test depends on not having time-triggered `Write()` calls. I
cannot figure out a way to disable them, but increasing the timeout
makes them less likely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9366)
=> deflake(pubsub): make time-triggered `Write()` events less likely

generator/internal/descriptor_utils.cc, generator/internal/descriptor_utils.h, generator/internal/descriptor_utils_test.cc
Part of the work for #9121 
Our metadata generator will interact with the `ExplicitRoutingInfo` data struct in order to generate the code. We use this intermediate object instead of generating code directly from the `google.api.RoutingRule` because the translation is complex enough to warrant unit testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9360)
=> impl(generator): process the `RoutingRule` proto

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/internal/logging_result_set_reader.cc, google/cloud/spanner/internal/logging_result_set_reader.h, google/cloud/spanner/internal/logging_result_set_reader_test.cc, google/cloud/spanner/internal/partial_result_set_reader.h, google/cloud/spanner/internal/partial_result_set_resume.cc, google/cloud/spanner/internal/partial_result_set_resume.h, google/cloud/spanner/internal/partial_result_set_resume_test.cc, google/cloud/spanner/internal/partial_result_set_source.cc, google/cloud/spanner/internal/partial_result_set_source.h, google/cloud/spanner/internal/partial_result_set_source_test.cc, google/cloud/spanner/options.h, google/cloud/spanner/testing/mock_partial_result_set_reader.h
The service only adds a `resume_token` when the `PartialResultSet` ends
with a completed row (except when the `PartialResultSet` also completes
the stream, in which case the `resume_token` remains empty). Therefore,
`resume_token` and `chunked_value` are mutually exclusive.
This means the library has to buffer rows completed within a non-token
`PartialResultSet` if it is to maintain resumability. This mainly affects
the algorithm and data used by `PartialResultSetSource::ReadFromStream()`.
For example, the storage of the token moves from `PartialResultSetResume`
to `PartialResultSetSource`, and the latter gains a `deque` of complete,
but undeliverable rows.
Introduce the `StreamingResumabilityBufferSizeOption` to control the size
of the buffer. If this size is exceeded, complete rows will …
=> impl(spanner): fix the handling of PartialResultSet.resume_token

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_experiment.h, google/cloud/storage/benchmarks/throughput_experiment_test.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc, google/cloud/storage/benchmarks/throughput_result.cc, google/cloud/storage/benchmarks/throughput_result.h, google/cloud/storage/benchmarks/throughput_result_test.cc
Rename the options controlling the read and write buffer sizes to match
what they do. Remove the parameters related to the library
buffer sizes. We bypass these buffers, so they have no effect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9370)
=> test(storage): cleanup benchmark options

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
Sometimes we only want to get a few samples per second or per minute.
For example, if we are running the benchmark for multiple days getting
hundreds of samples per second can be overwhelming. With this change the
user can control the maximum sampling rate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9364)
=> test(storage): control benchmark pacing

google/cloud/internal/log_wrapper.cc
Add a cast to the `int64_t`-to-`size_t` conversion from #9351.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9371)
=> impl: fix build for Windows+x86

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/bigtable_client_unit_tests.bzl, google/cloud/bigtable/google_cloud_cpp_bigtable.bzl, google/cloud/bigtable/table_resource.cc, google/cloud/bigtable/table_resource.h, google/cloud/bigtable/table_resource_test.cc
Fixes #9348 
Plagiarized from [spanner/database.h](https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/spanner/database.h)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9377)
=> feat(bigtable): table resource name as a class

google/cloud/testing_util/validate_metadata.cc, google/cloud/testing_util/validate_metadata.h
Part of the work for #9373 
First we refactor this class to make it easier to work with.
`IsContextMDValid` returns a `Status`. Instead of reporting errors by returning a `Status` (and leaving the method early), we use `EXPECT_CALL`'s and continue checking the expectations. (I will send a PR after this one to change the function to be a `void`, and update our tests accordingly).
We also prepare ourselves a place to add logic relating to `google.api.RoutingRule`s.
This is a test helper class. It has no associated tests to verify its behavior so.....
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9376)
=> refactor(testing_util): `ValidateMetadataFixture` sets gmock expectations

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source.h, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
So far we have been using the `StreamingPull()` RPC to receive data and
to refresh the message leases. To implement exactly-once delivery we
need to retry the message lease refreshes, and it is better to do this
using a separate unary RPC because (1) it is easier to implement,
(2) it is more consistent with other libraries, and (3) the preferred
approach by the Pub/Sub service folks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9379)
=> impl(pubsub): use unary RPCs to refresh leases

google/cloud/bigtable/options.h, google/cloud/bigtable/table.h, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/testing/table_integration_test.cc, google/cloud/bigtable/tests/data_integration_test.cc, google/cloud/bigtable/tests/table_sample_rows_integration_test.cc
Part of the work for #9349 
For now, if the `AppProfileIdOption` is supplied to the `Table` constructor, we copy the value into `Table::app_profile_id_`, and pass that along to the Connection when a call is made.
In a follow up PR, I will modify the Connection API to drop the `app_profile_id` argument from its calls, and instead look for the value in `CurrentOptions()`. I think I will drop `Table::app_profile_id_` in that PR as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9382)
=> feat(bigtable): add `AppProfileIdOption`

generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc, generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc, google/cloud/bigtable/internal/bigtable_stub_factory_test.cc, google/cloud/bigtable/internal/legacy_async_row_reader_test.cc, google/cloud/bigtable/internal/legacy_row_reader_test.cc, google/cloud/bigtable/mutation_batcher_test.cc, google/cloud/bigtable/table_apply_test.cc, google/cloud/bigtable/table_check_and_mutate_row_test.cc, google/cloud/bigtable/table_readmodifywriterow_test.cc, google/cloud/bigtable/table_readrow_test.cc, google/cloud/bigtable/testing/mock_async_failing_rpc_factory.h, google/cloud/bigtable/testing/mock_response_reader.h, google/cloud/internal/minimal_iam_credentials_stub_test.cc, google/cloud/pubsub/internal/publisher_metadata_test.cc, google/cloud/pubsub/internal/schema_metadata_test.cc, google/cloud/pubsub/internal/subscriber_metadata_test.cc, google/cloud/pubsub/publisher_connection_test.cc, google/cloud/pubsub/schema_admin_connection_test.cc, google/cloud/pubsub/subscriber_connection_test.cc, google/cloud/pubsub/subscription_admin_connection_test.cc, google/cloud/pubsub/topic_admin_connection_test.cc, google/cloud/spanner/internal/database_admin_metadata_test.cc, google/cloud/spanner/internal/instance_admin_metadata_test.cc, google/cloud/spanner/internal/metadata_spanner_stub_test.cc, google/cloud/storage/internal/storage_stub_factory_test.cc, google/cloud/testing_util/validate_metadata.cc, google/cloud/testing_util/validate_metadata.h
Part of the work for #9373 
**REVIEWER**: the actual refactor is in the second commit, which is mostly moving things from the source to the header. The first commit contains updates to all the tests.
For my next trick, I am adding a templated `Request` parameter to `IsContextMDValid`, and dropping the return value. Explicit routing looks into the contents of a request so we will need this information.
The case of streaming writes is weird because there is no request when we add metadata to the `grpc::ClientContext`. So we just send empty requests in our tests. Note that `BigQueryWriteClient::AppendRows` would not pass this test. (This has been true forever. I opened #9381 to address it).
Also, make the error message for the metadata matcher more informative (like it used to be).
```
Value …
```
=> refactor(testing_util): prepare metadata validation to handle explicit routing

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_experiment.h, google/cloud/storage/benchmarks/throughput_experiment_test.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc, google/cloud/storage/benchmarks/throughput_result.cc, google/cloud/storage/benchmarks/throughput_result.h, google/cloud/storage/benchmarks/throughput_result_test.cc
A lot of analytical workloads use "ranged" reads, i.e., they read a
portion of a larger object. There seems to be performance advantages
when reading up to 2MiB. Likewise, there are measurable performance
differences when the offset is on a 2MiB boundary and/or the read
size is on a 2 MiB boundary.
We would like to measure these effects, and therefore we need new
parameters for the benchmark.
By now, we have 4 of these "quantized" size ranges, I did some
refactoring to avoid code duplication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9378)
=> test(storage): benchmark supports ranged reads

google/cloud/bigtable/internal/legacy_row_reader_test.cc, google/cloud/testing_util/BUILD.bazel, google/cloud/testing_util/google_cloud_cpp_testing_grpc.cmake, google/cloud/testing_util/validate_metadata.cc
Fixes #9373
Note that any test in Bigtable (the only service with explicit routing for which we have a library) which sets an app profile id will now fail the context metadata check. There is apparently exactly one such test, so we implement a temporary workaround.
My plan is to add more such tests by also setting the app profile id in the `bigtable_stub_factory_test.cc`.
But this will have to wait until after the generator has explicit routing support.
https://github.com/googleapis/google-cloud-cpp/blob/91aae8c5bbd5182534ba716a07a3d5a1a3bdade0/google/cloud/bigtable/internal/bigtable_stub_factory_test.cc#L117-L119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp …
=> test: validate explicit routing

google/cloud/bigtable/data_connection.cc, google/cloud/bigtable/data_connection.h, google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/mocks/mock_data_connection.h, google/cloud/bigtable/table.cc, google/cloud/bigtable/table.h, google/cloud/bigtable/table_test.cc
Fixes #9349 
This tedious PR does two things:
1. stores the app profile in `Table::options_` instead of `Table::app_profile_id_`. (Note that `options_` is already passed in an `OptionsSpan` for each RPC). Legacy uses of `app_profile_id_` become `app_profile_id()`.
2. drops `std::string const& app_profile_id` from the Connection methods. We set up`OptionsSpan`s in the Connection unit tests so we can verify that all RPCs set a request's `app_profile_id` field.
While this is a breaking change at HEAD, the methods are less than 2 weeks old and have not been included in a release yet. The upside of this change is that the method signature of the Connection is closer to that of the Table. And it's nice to have one less field to type.
My apologies for not validating the Table API surface before …
=> fix(bigtable)!: pass app profile id to connection as options

generator/integration_tests/BUILD.bazel, generator/integration_tests/CMakeLists.txt, generator/integration_tests/golden/golden_kitchen_sink_client.cc, generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/golden_kitchen_sink_connection.cc, generator/integration_tests/golden/golden_kitchen_sink_connection.h, generator/integration_tests/golden/golden_kitchen_sink_connection_idempotency_policy.cc, generator/integration_tests/golden/golden_kitchen_sink_connection_idempotency_policy.h, generator/integration_tests/golden/golden_thing_admin_client.h, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_connection_impl.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_connection_impl.h, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.h, generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.cc, generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_connection.h, generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_stub.h, generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc, generator/integration_tests/test.proto, generator/internal/metadata_decorator_generator.cc, google/cloud/bigtable/internal/bigtable_metadata_decorator.cc
Fixes #9121 
The first and last commits are interesting. The middle two are not.
We do not pass our variables through `service_method_vars`. It is easier to work with the data directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9368)
=> feat(generator): support explicit routing headers

google/cloud/bigtable/table_resource.cc, google/cloud/bigtable/table_resource.h, google/cloud/bigtable/table_resource_test.cc
I am sorry, but writing code like `TableResource(InstanceResource(Project("p"), "i"), "t)"` is just too painful for me. I am sure it would be painful for our customers too.
So add a constructor that accepts strings. `TableResource("p", "i", "t")`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9397)
=> cleanup(bigtable): ergonomic string ctor for TableResource

google/cloud/pubsub/subscriber.h
We used to consume any object that could be converted to a
`std::function<>` of the right type. Consuming the `std::function<>`
will allow us to overload on the function type. We expect applications
using exactly-once delivery will consume a different `AckHandler` which
includes error messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9395)
=> cleanup(pubsub): subscriber consumes `std::function<>`

.github/renovate.json
Apparently renovate bot cannot handle Abseil's versions with the default
configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9401)
=> chore(renovate): configure Abseil versioning

google/cloud/bigtable/options.h, google/cloud/bigtable/table.h, google/cloud/bigtable/table_test.cc, google/cloud/bigtable/testing/table_integration_test.cc, google/cloud/bigtable/tests/data_integration_test.cc, google/cloud/bigtable/tests/table_sample_rows_integration_test.cc
Fixes #8860
Technically this fixes #6465 which fixes #1161. Although we should probably update our [credentials sample](https://github.com/googleapis/google-cloud-cpp/blob/c8a4920f64e5fdafb180d9ae1e30bcf4f7bbb3ff/google/cloud/bigtable/examples/bigtable_grpc_credentials.cc). (I think of that task as #7434).
Release the `Table` constructor that accepts a `DataConnection`. Yay, we are close to having a good mocking story. and a good credentials story. (I say close because there is still the pesky legacy API which does not have these things and lives alongside the "new shinny").
For now I just list the relevant options in the constructor's documentation. I would like to link to examples of how the `Options` are used. But the examples must exist first. (#9309 tracks this work).
I would also …
=> feat(bigtable): modern `Table` constructor

generator/internal/predicate_utils.h, generator/internal/service_code_generator.cc, google/cloud/pubsub/internal/exactly_once_policies.cc
At least one of these was breaking a downstream consumer of the
repo, where incidental inclusions don't happen in the same way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9406)
=> cleanup: include algorithm for std::any_of

google/cloud/pubsub/ack_handler.h, google/cloud/pubsub/internal/exactly_once_ack_handler.h
From:  https://github.com/googleapis/google-cloud-cpp/pull/9394#pullrequestreview-1025466119 
That motivated some other small changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9404)
=> doc(pubsub): improve documentation for `*AckHandler`

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
This finally uses the lease extensions on a subscription with
exactly-once delivery enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9396)
=> impl(pubsub): exactly-once delivery retries lease extensions

google/cloud/bigtable/admin/integration_tests/table_admin_integration_test.cc, google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc, google/cloud/bigtable/benchmarks/benchmark.cc, google/cloud/bigtable/benchmarks/benchmark.h, google/cloud/bigtable/benchmarks/embedded_server_test.cc, google/cloud/bigtable/benchmarks/endurance_benchmark.cc, google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc, google/cloud/bigtable/benchmarks/scan_throughput_benchmark.cc, google/cloud/bigtable/tests/admin_integration_test.cc
Part of the work for #9309 
I took the opportunity to simplify `benchmark.h` by returning a `Table` instead of a `DataClient` to be made into a `Table`.
Everything else should be straight forward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9409)
=> cleanup(bigtable): prefer DataConnection API in benchmarks, tests

google/cloud/pubsub/snapshot_builder.h, google/cloud/pubsub/subscription_builder.h, google/cloud/pubsub/topic_builder.h
This makes it easier to do any downstream mapping of names
in environments with non-standard protobuf namespaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9407)
=> cleanup(pubsub): use fully-qualified google::protobuf types

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_options.cc
The benchmark would perform a range read with 50% probability, but some
ranged reads were "full" as the range was larger than the object. I
found it hard to reason about this, so now only the range size controls
whether the read is full or not.
I also rediscovered a quirk of the JSON API, that it is better avoided:
reading the last 0 bytes actually returns all the bytes. Maybe we should
fix this in the client library itself, for now just avoid running into
it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9400)
=> test(storage): more tweaks to ranged reads

generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc, generator/integration_tests/test.proto, generator/internal/descriptor_utils.cc, google/cloud/testing_util/validate_metadata.cc
Handle fields that look like `field.sub_field`. I re-read the explicit routing parameters spec and they allow for these nested fields.
We copy the implementation from the `HttpRule`: https://github.com/googleapis/google-cloud-cpp/blob/d67dce6e8a69a78f4f47045172b6145875dee348/generator/internal/descriptor_utils.cc#L255-L264
In order to test this, `IsContextMDValid` needs to learn how to generically access this field name. (It did not need to before because the `HttpRule` only checks that a routing key exists and matches some known pattern. It does not set its expectations by looking at the request's contents like the `RoutingRule` does.)
I added a new test for the nested case. And updated all explicit routing tests to both use `IsContextMDValid` and to verify the expected headers manually. …
=> fix(generator): handle explicit routing params for nested fields

ci/cloudbuild/triggers/gcc-7.3-ci.yaml, ci/cloudbuild/triggers/gcc-7.3-pr.yaml
TIL: trigger names cannot contain periods. I think keeping the file names as they are is less confusing w.r.t. the build name, and the version of GCC and so on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9412)
=> ci: fix gcc-7.3 trigger names

google/cloud/pubsub/internal/exactly_once_policies.cc, google/cloud/pubsub/internal/extend_leases_with_retry.cc
Some downstream users enable this clang-tidy, so we might as well take
its advice.
https://clang.llvm.org/extra/clang-tidy/checks/abseil/string-find-startswith.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9416)
=> cleanup: heed abseil-string-find-startswith clang-tidy

google/cloud/bigtable/doc/bigtable-main.dox, google/cloud/bigtable/doc/bigtable-mocking.dox, google/cloud/bigtable/examples/CMakeLists.txt, google/cloud/bigtable/examples/bigtable_examples_unit_tests.bzl, google/cloud/bigtable/examples/howto_mock_data_api.cc, google/cloud/bigtable/mocks/mock_data_connection.h
Fixes #9308 
Add a dedicated document that walks through how to mock `Table::ReadRows`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9415)
=> doc(bigtable): how to mock the Data API

google/cloud/bigtable/internal/legacy_row_reader_test.cc, google/cloud/bigtable/metadata_update_policy.cc, google/cloud/bigtable/metadata_update_policy.h, google/cloud/bigtable/metadata_update_policy_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/table.h
Fixes #9123 
Add a method that lets us configure `MetadataUpdatePolicy` that takes in a `table_name` and an `app_profile_id`. (Essentially hardcoding what the generator does). We piggyback off an existing constructor, because I did not feel like dealing with private friends. (Obviously, I was not going to grow the API and add a public constructor).
Inside `Table`, our app profile id is stored in `Table::options_`. We make sure that `metadata_update_policy_` is defined after `options_` so we can use the `app_profile_id()` accessor in our constructors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9414)
=> feat(bigtable): dynamic routing of Data API requests

google/cloud/pubsub/internal/subscription_concurrency_control.cc, google/cloud/pubsub/internal/subscription_concurrency_control.h, google/cloud/pubsub/internal/subscription_concurrency_control_test.cc, google/cloud/pubsub/internal/subscription_session.cc, google/cloud/pubsub/internal/subscription_session.h, google/cloud/pubsub/internal/subscription_session_test.cc, google/cloud/pubsub/subscriber_connection.cc
While the implementation always uses `ExactlyOnceAckHandler`, the
application will receive the `*AckHandler` type that it requests. For
applications continuing to use `pubsub::AckHandler` the implementation
is wrapped, and any errors are logged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9413)
=> impl(pubsub): use `ExactlyOnceAckHandler`

google/cloud/google_cloud_cpp_rest_internal.bzl, google/cloud/google_cloud_cpp_rest_internal.cmake, google/cloud/google_cloud_cpp_rest_internal_unit_tests.bzl, google/cloud/internal/curl_rest_response.cc, google/cloud/internal/rest_response.cc, google/cloud/internal/rest_response_test.cc
The `AsStatus()` functions were declared in `rest_response.h`, but
defined in `curl_rest_response.cc`.  That seems unnecessarily confusing.
The test were also in an mismatched file.
I also refactored a function that `clang-tidy` claims has high
complexity to make it less so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9418)
=> cleanup(rest): move code to matching `.cc` file

ci/cloudbuild/dockerfiles/fedora-36.Dockerfile, ci/cloudbuild/triggers/clang-tidy-ci.yaml, ci/cloudbuild/triggers/clang-tidy-pr.yaml, generator/integration_tests/golden/tests/golden_kitchen_sink_auth_decorator_test.cc, generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc, google/cloud/storage/tests/decompressive_transcoding_integration_test.cc
Fedora:36 is out, it ships with clang-tidy 14.0.0, which includes a
number of useful checks regarding Abseil.  It also seems to be better
and detecting unused `using` declarations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9423)
=> ci: move `clang-tidy` build to Fedora:36

ci/cloudbuild/build.sh
When building with `--cloud=...` we need to export the
`VERBOSE_FLAG` environment variable. In most command-line builds this
is exported via the `docker run --env=...` commands, so it was hard to
detect. To make it easier to detect such problems, I reordered the
`export` commands to match the `docker run` order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9422)
=> ci: missing export in build.sh

google/cloud/storage/bucket_metadata.cc, google/cloud/storage/internal/lifecycle_rule_parser.cc, google/cloud/storage/internal/retry_client.cc, google/cloud/storage/lifecycle_rule.cc
I ran `clang-tidy` with the `readability-function-cognitive-complexity`
warning enabled. It found some functions that were too complex for their
own good, this cleans up all such functions in the storage library.
There are more such functions to clean up in the gRPC plugin, and I
have not even started on tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9420)
=> cleanup(storage): reduce maximum function cognitive complexity

google/cloud/spanner/instance_admin_connection_test.cc
There are no defined samples nor suggested extra tests for the new
Spanner Instance fields, so let's at least verify that they can be
parsed from a text proto we use in a `GetInstance()` mock.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9427)
=> test(spanner): populate Instance create_time and update_time fields

.clang-format, ci/cloudbuild/dockerfiles/checkers.Dockerfile
This includes `clang-format` 14. I enabled the "east const" formatting,
probably the most interesting rule with this new version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9428)
=> ci: move `checkers` build to Fedora:36

.clang-tidy, google/cloud/storage/.clang-tidy
Enable the clang-tidy `readability-function-cognitive-complexity` check
(as an error) for `google/cloud/storage/`.  I think we should turn this
on everywhere, but needed to start somewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9435)
=> cleanup(storage): enforce cognitive complexity limits

google/cloud/pubsub/.clang-tidy, google/cloud/pubsub/benchmarks/endurance.cc
One function was a little over the limit, fix it and enable the
`readability-function-cognitive-complexity`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9445)
=> cleanup(pubsub): enable clang-tidy's cognitive complexity

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
Need more options to make the benchmark usable in the pre-production
environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9451)
=> test(storage): options for pre-prod testing

google/cloud/bigtable/doc/bigtable-samples-grpc-credentials.dox, google/cloud/bigtable/examples/bigtable_hello_instance_admin.cc
The argument to `ListInstances(std::string parent)` is a project name. I must have been thinking of the `ListClusters` API when I made these changes. Ugh.
Noticed while working on #4122. The emulator is cool with the bad resource name, but the production service rightfully yells at us.
Also, stop using an `internal` symbol in our public example code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9461)
=> doc(bigtable): fix uses of `ListInstances` in docs

doc/contributor/howto-guide-adding-generated-libraries.md
This step is now done by `generate-libraries-pr`. https://github.com/googleapis/google-cloud-cpp/blob/4be7b7e1564aecfba447446dc64ab577ae4a6b0f/ci/cloudbuild/builds/generate-libraries.sh#L52-L80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9462)
=> cleanup(docs): skip manual document endpoint step

google/cloud/internal/log_wrapper.cc
- Expand google.protobuf.Any payloads rather than printing their
serialized content.
- Print fields in the order defined in source code instead of by
the field number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9477)
=> feat(common): make the RPC log even more readable

google/cloud/spanner/testing/cleanup_stale_databases.cc, google/cloud/spanner/testing/cleanup_stale_databases.h, google/cloud/spanner/testing/database_integration_test.cc
The word is that server-side logs are kept for 7 days while a database
exists, so let's keep abandoned test databases around for at least that
long.
The immediate goal is to help in the debugging of #4758.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9479)
=> test(spanner): extend abandoned-database retention period to 7 days

google/cloud/storage/bucket_metadata.cc, google/cloud/storage/bucket_metadata.h, google/cloud/storage/bucket_metadata_test.cc, google/cloud/storage/examples/storage_bucket_samples.cc, google/cloud/storage/internal/bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.h, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc
Fixes #9135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9481)
=> feat(storage): support Bucket custom placement config

.github/renovate.json, ci/cloudbuild/build.sh, ci/cloudbuild/dockerfiles/checkers.Dockerfile, ci/cloudbuild/dockerfiles/debian-github.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35-cxx20.Dockerfile, ci/cloudbuild/dockerfiles/fedora-35.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36-cxx14.Dockerfile, ci/cloudbuild/dockerfiles/fedora-36.Dockerfile, ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-bionic.Dockerfile, ci/cloudbuild/dockerfiles/ubuntu-focal.Dockerfile, ci/install-cloud-sdk.sh
Make it easier to run some builds on ARM64 machines. The Dockerfiles
download a few pre-built binaries, and those need to be platform
specific.
There is no Spanner emulator for ARM64, in this change we just don't
install it. Some builds do not need it, but I did not take any action
(such as disabling the integration tests) beyond that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9488)
=> ci: make it easier to run on ARM64 machines

google/cloud/google_cloud_cpp_common.bzl, google/cloud/google_cloud_cpp_common.cmake, google/cloud/internal/auth_header_error.cc, google/cloud/internal/auth_header_error.h, google/cloud/internal/oauth2_authorized_user_credentials.cc, google/cloud/internal/oauth2_compute_engine_credentials.cc, google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/rest_client.cc, google/cloud/storage/oauth2/authorized_user_credentials.cc, google/cloud/storage/oauth2/compute_engine_credentials.cc, google/cloud/storage/oauth2/service_account_credentials.cc
When we fail to generate an access token the errors can be very
confusing.  See for example this discussion:
https://issues.apache.org/jira/browse/ARROW-17069
This change is an attempt at making these errors less confusing. They
could be made event better if we had a specific webpage describing
client library authentication and troubleshooting, but we do not have
such a page at the moment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9485)
=> feat: improve error messages for access token errors

ci/cloudbuild/cache.sh, ci/cloudbuild/cloudbuild.yaml, ci/kokoro/lib/cache.sh
The (new, but well regarded) `gcloud alpha storage` commands have a
reputation of being faster than `gsutil` without requiring a lot of
tuning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9493)
=> ci: speed up cache uploads and downloads

google/cloud/pubsub/samples/samples.cc, google/cloud/pubsub/subscription_admin_client.h
Note that this was not added to the auto samples run. The reason is that it requires a BigQuery table to exist or to be created. It looks like there isn't library support for creating tables in C++. If there is a way to do it and it is preferred that this sample be added to the auto-run samples, I can do that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9500)
=> doc(pubsub): create BigQuery subscription sample

bazel/google_cloud_cpp_deps.bzl
I think this indicates the release tag got moved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9507)
=> chore(deps): fix google/benchmark SHA256

BUILD.bazel, ci/verify_current_targets/CMakeLists.txt, google/cloud/dataplex/config.cmake.in, google/cloud/dialogflow_cx/config.cmake.in, google/cloud/dialogflow_es/config.cmake.in, google/cloud/logging/config.cmake.in, google/cloud/logging/quickstart/CMakeLists.txt, google/cloud/speech/config.cmake.in, google/cloud/speech/quickstart/CMakeLists.txt
Remove experimental aliases. Use `logging` instead of `experimental-logging` in our CI.
Note that we do not move `osconfig`. (If I understand things correctly) we never moved the CMake targets into the transition state. We only define `google-cloud-cpp::experimental-osconfig`. https://github.com/googleapis/google-cloud-cpp/blob/021fceb482a2dc5782c4c1568dc0b303fcd77199/google/cloud/osconfig/CMakeLists.txt#L67-L76
I think we should keep our bazel and cmake targets in sync. I will send a follow up PR to move the osconfig cmake targets into a transition state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9504)
=> chore: move libraries from transition to full GA

ci/cloudbuild/dockerfiles/fedora-36-cxx20.Dockerfile, ci/cloudbuild/triggers/cxx20-ci.yaml, ci/cloudbuild/triggers/cxx20-pr.yaml
I had to work around some kind of problem a build failure with
`google/benchmark`.
Part of the work for #8922 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9506)
=> ci: update C++20 build to Fedora:36

google/cloud/storage/internal/invocation_id_generator.cc
TIL: it is undefined behavior to use `std::uniform_int_distribution<>`
with `char`, `unsigned char`, and its aliases. And some platforms
enforce this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9509)
=> fix(storage): no char for `std::uniform_int_distribution`

ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile, ci/generate-markdown/generate-packaging.sh, doc/packaging.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9516)
=> ci: move `demo-fedora` build to Fedora:36

BUILD.bazel, google/cloud/osconfig/CMakeLists.txt, google/cloud/osconfig/README.md, google/cloud/osconfig/config.cmake.in, google/cloud/osconfig/doc/main.dox
the bazel build was moved to a transition state, but the cmake build was not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9511)
=> chore: declare `osconfig` GA

google/cloud/bigtable/internal/legacy_bulk_mutator_test.cc, google/cloud/bigtable/internal/legacy_row_reader_test.cc, google/cloud/testing_util/validate_metadata.cc, google/cloud/testing_util/validate_metadata.h
The main change is to check for (unordered) equality of the routing header against our expectations. Previously, we were checking that the actual header is a superset of the expected headers.
We skip validation of the routing header for any client-side streams.
We do some light refactoring/renaming of method names vs method descriptors.
Then we update two bigtable tests to set realistic resource values, so the metadata is extracted properly. (Our tests were setting the table name to `""`, which is not something the library will ever do.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9475)
=> test: stricter routing metadata validation

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
When I changed the lease extensions to use unary RPCs (as opposed to
inline messages in the streaming pull), I neglected to include the
subscription name with the request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9523)
=> fix(pubsub): missing subscription name in lease extensions

generator/internal/metadata_decorator_generator.cc
The generator cannot create code to capture the routing instructions on
asynchronous streaming writes.  The generated functions do not have a
request to extract the routing instructions from.  Just inject the
basic metadata, the caller is responsible for adding the routing
instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9524)
=> fix(generator): streaming writes with routing instructions

CHANGELOG.md, google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
When I changed the lease extensions to use unary RPCs (as opposed to
inline messages in the streaming pull), I neglected to include the
subscription name with the request.
Fixes #9529
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9533)
=> fix(pubsub): missing subscription name in lease extensions (#9523)

google/cloud/spanner/client_test.cc, google/cloud/spanner/integration_tests/client_integration_test.cc
`ClientTest.MakeConnectionOptionalArguments` is really an integration
test in unit-test clothing.  Indeed, in the near future just creating
a database connection will start the process of filling the session
pool.  So, move it from `client_test.cc` to `client_integration_test.cc`.
Also, the purpose of the test is to ensure that the previous overloads
with `ConnectionOptions` and `SessionPoolOptions` are still available,
and not to verify any particular behavior.  So, simplify accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9545)
=> test(spanner): MakeConnection() test will require a service

google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/internal/defaults.cc, google/cloud/spanner/internal/defaults_test.cc, google/cloud/spanner/internal/session_pool_test.cc, google/cloud/spanner/session_pool_options_test.cc
Set the default value for `spanner::SessionPoolMinSessionsOption` to
`(25 * num_channels)`.  This means we will start the session-allocation
process at connection-creation time rather than waiting for the first
request.
The actual change is simple.  Most of the PR deals with:
- Reordering `BatchCreateSessions()` expectations to before connection
creation.
- Expecting additional `BatchCreateSessions()` calls when the first one
fails.
Fixes #4483.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9546)
=> feat(spanner): default SessionPoolMinSessionsOption to a non-zero value

google/cloud/storage/benchmarks/throughput_experiment.cc
Adds an upload ID to the "notes" section of operation logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9551)
=> test(storage): log upload ID in throughput_experiment

CHANGELOG.md, google/cloud/debugger/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9552)
=> doc(debugger): announce deprecation

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/grpc_object_media_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
This is a small function, so I added the request parser, unit tests, and
integration tests in a single PR.
Fixes #5910
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9550)
=> feat(GCS+gRPC): implement `DeleteResumableUpload()`

generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_stub.h, google/cloud/internal/streaming_write_rpc.h, google/cloud/internal/streaming_write_rpc_impl.h, google/cloud/internal/streaming_write_rpc_logging.h, google/cloud/internal/streaming_write_rpc_logging_test.cc
I will (eventually) need this for GCS+gRPC, so we can troubleshoot
uploads, and we can better evaluate the performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9557)
=> impl: support request metadata for streaming write RPCs

google/cloud/storage/internal/retry_client.cc, google/cloud/storage/internal/retry_client_test.cc
The service is (we think incorrectly) returning `kAlreadyExists` for
some uploads. We need a workaround to unblock some testing. The GCS
team is working on a fix in parallel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9564)
=> feat(GCS+gRPC): treat some `kAlreadyExists` errors as transient

google/cloud/bigtable/CMakeLists.txt
The library is no longer header-only, it needs to become a real library.
Part of the work for #5782
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9568)
=> fix(bigtable): the mocks library is no longer header-only

google/cloud/storage/internal/async_accumulate_read_object_test.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_read_object_test.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/grpc_object_read_source.h, google/cloud/storage/internal/grpc_object_read_source_test.cc, google/cloud/storage/internal/storage_stub_factory_test.cc, google/cloud/storage/testing/mock_storage_stub.h
This changes the implementation of `ReadObject()` to use the blocking
API and a watchdog timer to implement stall timeouts. If the timer
expires before the `Read()` operation completes a background thread
cancels the RPC.  If the operation completes, we cancel the timer.
Part of the work for #9558 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9554)
=> fix(GCS+gRPC): more efficient `ReadObject()` stall timeouts

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_insert_object_media_test.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_client_upload_chunk_test.cc, google/cloud/storage/internal/storage_stub_factory_test.cc, google/cloud/storage/testing/mock_storage_stub.h
This changes the implementation of `InsertObject()` to use the blocking
API and a watchdog timer to implement stall timeouts. If the timer
expires before the `Write()` operation completes a background thread
cancels the RPC.  If the operation completes, we cancel the timer.
Part of the work for #9558
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9573)
=> feat(GCS+gRPC): more efficient `InsertObject()` stall timeouts

google/cloud/internal/curl_handle.cc, google/cloud/internal/curl_handle.h, google/cloud/internal/curl_handle_factory.cc, google/cloud/internal/curl_handle_factory.h, google/cloud/internal/curl_handle_factory_benchmark.cc, google/cloud/internal/curl_impl.cc, google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_handle.cc, google/cloud/storage/internal/curl_handle.h
When a CURL* handle has an error we don't want to return it to the pool.
The error probably indicates a bad server (in the load balancer) or a
bad connection, and it is time to set up a new connection. Previously,
we just discarded the handle, how let the factory do so. In a future
PR we will use this to update counters in the factory, and adjust how
aggressively the pool releases its handles.
Part of the work for #9469
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9575)
=> impl(rest): always discard handles via HandleFactory

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_upload_chunk_test.cc
This changes the implementation of `WriteObject()` to use the blocking
API and a watchdog timer to implement stall timeouts. If the timer
expires before the `Write()` operation completes a background thread
cancels the RPC.  If the operation completes, we cancel the timer.
Fixes #9558
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9576)
=> feat(GCS+gRPC): more efficient `WriteObject()` stall timeouts

google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/benchmarks/benchmark_utils.h
The computers do not care, but it was hard to inspect the output with
the very long names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9579)
=> test(storage): use shorter random object names

google/cloud/storage/examples/storage_client_mock_samples.cc, google/cloud/storage/internal/curl_request.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc, google/cloud/storage/internal/object_requests.cc, google/cloud/storage/internal/object_requests.h, google/cloud/storage/internal/object_requests_test.cc, google/cloud/storage/internal/object_write_streambuf.cc, google/cloud/storage/internal/object_write_streambuf.h, google/cloud/storage/internal/retry_client_test.cc, google/cloud/storage/object_write_stream.cc
Make it easier to troubleshoot problems with resumable uploads (aka
`Client::WriteObject()`) by capturing the headers of the last request.
We do not want to capture the headers for all the requests because there
can be an unbounded number of requests, and therefore all the headers
can consume arbitrary amounts of memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9580)
=> feat(storage): add debugging headers to `ObjectWriteStream`

google/cloud/bigtable/data_connection.h
Fixes #1553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9583)
=> doc(bigtable): document connection pooling model

google/cloud/internal/curl_handle_factory.cc, google/cloud/internal/curl_handle_factory.h, google/cloud/internal/curl_handle_factory_benchmark.cc
Before this change, the pool would always remove half the handles to
make room for additional handles returning to the pool. We want to
remove fewer handles when there are few excess handles, and remove
more handles (but not all handles) when there are more excess handles.
Fixes #9469 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9582)
=> impl(rest): tune HandleFactory cleanup

generator/integration_tests/golden/golden_thing_admin_client.cc, generator/internal/client_generator.cc, google/cloud/bigtable/admin/bigtable_instance_admin_client.cc, google/cloud/bigtable/admin/bigtable_table_admin_client.cc, google/cloud/billing/cloud_billing_client.cc, google/cloud/containeranalysis/container_analysis_client.cc, google/cloud/datacatalog/data_catalog_client.cc, google/cloud/iam/iam_client.cc, google/cloud/iot/device_manager_client.cc, google/cloud/resourcemanager/folders_client.cc, google/cloud/securitycenter/security_center_client.cc, google/cloud/spanner/admin/database_admin_client.cc, google/cloud/spanner/admin/instance_admin_client.cc, google/cloud/tasks/cloud_tasks_client.cc
In the OCC-loop overload of SetIamPolicy(), do not loop on kAborted
when there is no BackoffPolicyOption.  This will not affect production
code as there is a default BackoffPolicyOption in that case.  However,
a mock connection in a test may not have one, but we undoubtedly never
want to loop in that circumstance anyway unless the test has expressly
set a policy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9585)
=> impl(generator): do not OCC loop when there is no backoff policy

google/cloud/spanner/client.h, google/cloud/spanner/internal/connection_impl.cc
Follow the lead of the generator, and only apply the Spanner default
options in one place: `spanner::MakeConnection()`.
None of the `Client` tests are sensitive to the options returned by
the mock connection, and the `ConnectionImpl` tests already add the
`spanner_internal::DefaultOptions()` themselves.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9588)
=> impl(spanner): only apply default options in one place

google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
Sometimes we just want to benchmark `WriteObject()` or `InsertObject()`,
but the benchmark was always testing with both.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9589)
=> test(storage): add options to select upload function

google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_result.cc, google/cloud/storage/benchmarks/throughput_result.h, google/cloud/storage/benchmarks/throughput_result_test.cc
Use specific fields for the bucket name, object name, object generation,
and (when applicable) the upload id. For REST uploads, cleanup the
upload id: we used to print the full URL. Create a field to include the
number of retries, but that is not filled yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9592)
=> test(storage): cleanup benchmark output

ci/kokoro/windows/cmake-release-x86-presubmit.cfg
This creates the configuration files, but they need to be enabled
internally too.
Part of the work for #9587
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9595)
=> ci: presubmit configs for Windows and CMake

google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h, google/cloud/internal/rest_options.h, google/cloud/storage/client_options.cc, google/cloud/storage/client_options_test.cc, google/cloud/storage/internal/curl_download_request.cc, google/cloud/storage/internal/curl_download_request.h, google/cloud/storage/internal/curl_request.cc, google/cloud/storage/internal/curl_request.h, google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/internal/curl_request_builder.h, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/options.h
Some applications need more progress than just "at least 1 byte per
second for K seconds".  These new options allow them to require "at
least N bytes per second for K seconds".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9593)
=> feat(storage): experimental options to tune stall timeouts

google/cloud/storage/internal/group_options.h, google/cloud/storage/internal/group_options_test.cc
Do not use `static`, these are global functions. And declare all
overloads before they are used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9596)
=> cleanup(storage): correctly declare `GroupOptions()` overloads

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9598)
=> test(storage): benchmark options to tune stall timeouts

google/cloud/internal/oauth2_service_account_credentials_test.cc
I want to make changes to `ServiceAccountCredentials`, and having
hard-coded magic strings makes it harder than it should be. Took the
opportunity to remove unused code from the test, and that make the
test fixture unjustified.
Part of the work #7674
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9601)
=> cleanup: remove magic test strings for `ServiceAccountCredentials`

google/cloud/credentials.h
I think the previous description assumed the reader already knew what
service accounts are and why you would use them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9602)
=> doc: a gentler introduction to IAM and service accounts

google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/internal/oauth2_service_account_credentials.h, google/cloud/internal/oauth2_service_account_credentials_test.cc
Also cleaned up some complicated implementation using `MergeOptions()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9613)
=> cleanup(rest): remove constant parameters

google/cloud/internal/unified_rest_credentials_integration_test.cc
The storage service has some particular requirements w.r.t. self-signed
JWTs for service account credentials.  We need to support self-signed
JWTs for a number of reasons. Adding a test before I change the service
account credentials implementation will avoid regressions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9610)
=> test(rest): use storage service in integration test

google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/internal/oauth2_service_account_credentials.h, google/cloud/internal/oauth2_service_account_credentials_test.cc, google/cloud/internal/unified_rest_credentials_integration_test.cc
Service Accounts can create self-signed JWTs. These JWTs serve as access
tokens, to GCP, but do not require an RPC to create them. They are,
therefore, more efficient to create, more reliable, and work with the
token endpoint (https://oauth2.googleapis.com/token) is blocked by a
firewall or hidden by something like VPC-SC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9616)
=> impl(rest): helper functions to create self-signed JWTs

google/cloud/internal/curl_rest_client.cc, google/cloud/internal/curl_rest_client.h
fixes #9607
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9620)
=> fix(rest): cache credentials

google/cloud/google_cloud_cpp_common.bzl, google/cloud/google_cloud_cpp_common.cmake, google/cloud/google_cloud_cpp_common_unit_tests.bzl, google/cloud/internal/group_options.h, google/cloud/internal/group_options_test.cc, google/cloud/storage/async_client.h, google/cloud/storage/client.h, google/cloud/storage/google_cloud_cpp_storage.bzl, google/cloud/storage/google_cloud_cpp_storage.cmake, google/cloud/storage/storage_client_unit_tests.bzl
Part of the work for #7688 
The following client functions exist in bigtable:
`Table::(Async)ReadModifyWriteRow(..., Args&&... rules);`
I will need to accept `Options` passed into the parameter pack. `storage::internal::GroupOptions` is the solution to this problem. So move it out of storage and into common.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9618)
=> refactor: move `GroupOptions` into common

google/cloud/options.cc, google/cloud/options.h, google/cloud/options_test.cc
Part of the work for #7688 
Add an internal helper to see if Options are empty or not.
There are two code paths in the `bigtable::Table` client. One that uses `client_` and one that uses `connection_`. Per operation options only apply to the path that uses the `connection_`. I do not want to check if `opts.has<T>` for each `T` option. So, we just check to see if the options are empty.
The code in bigtable will look vaguely like this:
```cc
Status Table::Foo(Options opts) {
if (!connection_ && !google::cloud::internal::IsEmpty(opts)) {
return Status(StatusCode::kFailedPrecondition,
"Per-operation options only apply to `Table`s constructed "
"with a `DataConnection`.");
}
// etc...
}
```
--- …
=> impl: check if options are empty

google/cloud/storage/benchmarks/aggregate_upload_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_options.h, google/cloud/storage/benchmarks/aggregate_upload_throughput_options_test.cc
I want to use the `aggregate_upload_throughput` benchmark to compare
gRPC vs. DirectPath vs. REST with different timeout parameters and
other options. It seemed simpler to add a `google::cloud::Options` to
the benchmark configuration, that will require fewer changes in the
future, and simplifies (I think) the client initialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9622)
=> test(storage): improvements in upload benchmark

google/cloud/bigtable/data_connection.cc, google/cloud/bigtable/data_connection.h, google/cloud/bigtable/legacy_table_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/table.h, google/cloud/bigtable/table_test.cc
Most of the work for #7688 
This PR handles all calls except for `Table::(Async)ReadModifyWriteRow(...)`, which are a little bit more involved.
If `Options` are supplied to a `Table` implemented by `DataClient`, we will immediately return a `kInvalidArgument` error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9623)
=> feat(bigtable): per-operation Options (pt. 1)

google/cloud/bigtable/legacy_table_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/table.h, google/cloud/bigtable/table_test.cc
Fixes #7688  
Accept `Options` in the `(Async)ReadModifyWriteRow(..., Args&& rules_and_options)` parameter packs. (I dare you to improve on the name: `rules_and_options`).
We extract the options using `GroupOptions(...)`. And ignore `Options` when we are adding rules to the `request` proto.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9627)
=> feat(bigtable): per-operation Options (pt. 2)

google/cloud/storage/oauth2/service_account_credentials.cc, google/cloud/storage/oauth2/service_account_credentials.h, google/cloud/storage/oauth2/service_account_credentials_test.cc
Change the default implementation of SA (Service Account) credentials to
use self-signed JWTs by default.  Applications can disable this
by setting the `GOOGLE_CLOUD_CPP_EXPERIMENTAL_DISABLE_SELF_SIGNED_JWT`
environment variable (to any value).
Fixes #7674
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9629)
=> feat(storage): SA credentials default to self-signed JWTs

google/cloud/bigtable/column_family.h, google/cloud/bigtable/column_family_test.cc, google/cloud/bigtable/filters.h, google/cloud/bigtable/filters_test.cc, google/cloud/bigtable/mutations.h, google/cloud/bigtable/mutations_test.cc, google/cloud/bigtable/read_modify_write_rule.h, google/cloud/bigtable/read_modify_write_rule_test.cc, google/cloud/bigtable/row_set.h, google/cloud/bigtable/row_set_test.cc, google/cloud/bigtable/table_admin.h, google/cloud/bigtable/table_admin_test.cc
Part of the work for #2310 
The types are:
* `ColumnFamilyModification`
* `FailedMutation`
* `Filter`
* `GcRule`
* `ReadModifyWriteRule`
* `RowSet`
* `SingleRowMutation`
* `TableAdmin`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9647)
=> feat(bigtable): define equality operator for some classes

google/cloud/bigtable/data_connection.cc, google/cloud/bigtable/data_connection.h, google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/table.h
Follow the lead of the generator and:
1. Remove `bigtable_internal::MakeDataConnection(...)` (which I wasn't even using).
2. Default the `Options` exactly once - in `bigtable::MakeDataConnection(...)`. Adjust tests accordingly.
I also modified a unit test to check that `Options` are defaulted by `MakeDataConnection`. Ideally we wouldn't construct a `DataConnection` in the test, we would just verify that defauted options are passed to it... but that is ok. If we didn't have this test and we forgot to default the options [here](https://github.com/googleapis/google-cloud-cpp/blob/e14aed697ecc8924d4d2fafeea45fefd152065eb/google/cloud/bigtable/data_connection.cc#L145), we would only learn about it from an integration test segfaulting.
- - - …
=> cleanup(bigtable): default options like the generator does

google/cloud/spanner/create_instance_request_builder.h, google/cloud/spanner/create_instance_request_builder_test.cc, google/cloud/spanner/update_instance_request_builder.h, google/cloud/spanner/update_instance_request_builder_test.cc
Part of the work for #2310 
The classes are:
* `spanner::CreateInstanceRequestBuilder`
* `spanner::UpdateInstanceRequestBuilder`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9648)
=> feat(spanner): equality for copyable classes

google/cloud/storage/iam_policy.cc, google/cloud/storage/iam_policy.h, google/cloud/storage/internal/patch_builder.cc, google/cloud/storage/internal/patch_builder.h, google/cloud/storage/internal/patch_builder_test.cc, google/cloud/storage/storage_iam_policy_test.cc
Part of the work for #2310
The types are:
* `storage::NativeExpression`
* `storage::NativeIamBinding`
* `storage::NativeIamPolicy`
And I was too lazy to do this internal type in a separate PR:
* `storage::internal::PatchBuilder`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9649)
=> feat(storage): equality for Native IAM types

google/cloud/storage/google_cloud_cpp_storage.bzl, google/cloud/storage/google_cloud_cpp_storage.cmake, google/cloud/storage/internal/generic_request.h, google/cloud/storage/user_ip_option.h
The `storage::UserIp` class, while not recommended, is part of the
public API and, to be discoverable, needs to be in the same directory
as all public APIs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9652)
=> refactor(impl): move `UserIp` out of `internal/`

google/cloud/bigtable/instance_admin.cc, google/cloud/bigtable/instance_admin.h, google/cloud/bigtable/instance_admin_test.cc
Part of the work for #9168 
With this change, we copy options from the connection to the legacy client upon construction. These options make it into an `OptionSpan` for each legacy client call.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9653)
=> refactor(bigtable): `InstanceAdmin` receives Connection `Options`

google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_download_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_download_throughput_options.h, google/cloud/storage/benchmarks/aggregate_download_throughput_options_test.cc
Use `google::cloud::Options` directly. Simplifies the initialization and
the parsing code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9651)
=> test(storage): cleanup options for aggregate download benchmark

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h, google/cloud/spanner/internal/connection_impl_test.cc
Part of the work for #9168 
`ConnectionImpl` can assume the relevant options are always present in `CurrentOptions()`. The unit test for this class will always supply a retry/backoff policy for the operation.
Simplify the unit tests to only make one type of connection. Some call options set a limited error count retry policy; others use the default limited time retry policy. All operations use the custom backoff policy. This speeds up the test from ~5s to ~2.5s on my cloudtop.
**Warning:** @devbww this PR changes the logic around checking for `rpc-streams` logging. I don't think we should add the connection's set of tracing components to the operation's set of tracing components, because that is not the typical behavior of merging options.
- - - …
=> refactor(spanner): assume call options

google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_benchmark.cc, google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/benchmarks/benchmark_utils.h, google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
This completes the changes to store the client configuration in
`Options`.  The benchmark specific options are still in a struct, which
maybe I want to change in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9658)
=> test(storage): use Options to store client configuration

google/cloud/bigtable/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/bigtable/tests/instance_admin_integration_test.cc
Fixes #9650 
We clean up instances with this regex in our ci builds
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9661)
=> ci(bigtable): ensure stale instances are cleaned up

google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl.h, google/cloud/bigtable/internal/data_connection_impl_test.cc
Part of the work for #9168 
Basically #9655 but in bigtable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9663)
=> cleanup(bigtable): assume call options

ci/retry-command.sh
macOS does not support a `s` suffix for `sleep(1)`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9667)
=> ci: fix `retry-command.sh` for macOS

google/cloud/bigtable/table_admin.cc, google/cloud/bigtable/table_admin.h, google/cloud/bigtable/table_admin_test.cc
Part of the work for #9168. This PR unblocks the generator refactor.
Same story as #9653 - merge in options coming from the connection and put them in an `OptionsSpan` for each client call.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9656)
=> refactor(bigtable): `TableAdmin` receives Connection `Options`

google/cloud/spanner/testing/random_database_name.cc
It has been over four months since we settled on using only dash
separators in the prefixes of random database names (db-YYYY-MM-DD-),
so we can now remove the allowance for matching underscores as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9670)
=> test(spanner): revert matching of interim database prefixes

ci/kokoro/macos/build.sh
The cache download is failing with:
```
Copying gs://cloud-cpp-kokoro-results/build-cache/google-cloud-cpp/main/cache-macos-cmake-vcpkg.tar.gz to file://cmake-out/download/cache-macos-cmake-vcpkg.tar.gz
ERROR: This download was skipped since the google-crc32c
binary is not installed, and Python hash computation will likely
throttle performance. You can change this by installing the binary
by running "/Users/kbuilder/.pyenv/versions/3.10.3/bin/python3 -m pip install google-crc32c --target /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/third_party" or
modifying the "storage/check_hashes" config setting.
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-clou …
=> ci(macOS): install missing components

google/cloud/storage/benchmarks/throughput_experiment.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9677)
=> impl(storage): make both Xml and XmlV2 set Fields option in benchmarks

google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/integration_tests/session_pool_integration_test.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/internal/session_pool.cc, google/cloud/spanner/internal/session_pool.h, google/cloud/spanner/internal/session_pool_test.cc, google/cloud/spanner/options.h, google/cloud/spanner/samples/samples.cc
Introduce `spanner::SessionCreatorRoleOption`, which can be passed to
`spanner::MakeConnection()` to set the `session_template.creator_role`
used when creating sessions for the connection.
Add integration test for creating and listing roles.
Add samples:
- spanner_add_and_drop_database_roles
- spanner_read_data_with_database_role
- spanner_list_database_roles
- spanner_enable_fine_grained_access
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9669)
=> feat(spanner): fine-grained access control

google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_benchmark.cc, google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/benchmarks/benchmark_utils.h, google/cloud/storage/benchmarks/throughput_result.cc
Add some timestamps which are handy when trying to correlate with
external graphs or other logs.  Refactored some code to print
timestamps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9684)
=> test(storage): add details to aggregate benchmarks

google/cloud/pubsublite/integration_tests/publisher_integration_test.cc
Do a pass on this integration test.
* Use `SetUp` and `TearDown` instead of `::testing::Test`'s ctor and dtor.
* Assert before using the values in `absl::optional<T>` or `StatusOr<T>`.
* Make calls using clients instead of connections (this unblocks my other PR)
I am confused what is under test though... I think it is `pubsublite::MakePublisherConnection(...)` ? If I understood, I would probably rename the test cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9678)
=> cleanup(pubsublite): nicer integration test

ci/cloudbuild/builds/lib/integration.sh
Currently, the integration test only runs on `integration-production-pr`. Let's run it on some other linux bazel builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9686)
=> ci(pubsublite): run integration test in more builds

google/cloud/storage/google_cloud_cpp_storage_grpc.bzl, google/cloud/storage/google_cloud_cpp_storage_grpc.cmake, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc, google/cloud/storage/internal/grpc_configure_client_context.cc, google/cloud/storage/internal/grpc_configure_client_context.h, google/cloud/storage/internal/grpc_configure_client_context_test.cc
Fixes b/238793833
Routing rules are here: https://github.com/googleapis/googleapis/blob/b7cb84f5d42e6dba0fdcc2d8689313f6a8c9d7b9/google/storage/v2/storage.proto#L340-L349
I did the logic by hand, instead of using what the generator might produce. I did this because the two fields are a `oneof` that our code is already split on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9694)
=> feat(GCS+gRPC): routing headers for WriteObject

google/cloud/bigtable/internal/readrowsparser.cc
The proto says: "Labels are only set on the first CellChunk per cell.". So we can include it in the if statement.
https://github.com/googleapis/googleapis/blob/e6e875a456c046e94eeb5a76211daa046a8e72c9/google/bigtable/v2/bigtable.proto#L268-L271
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9687)
=> cleanup(bigtable): reclaim vertical space

google/cloud/bigtable/internal/async_row_sampler.cc, google/cloud/bigtable/internal/async_row_sampler.h, google/cloud/bigtable/internal/async_row_sampler_test.cc
Part of the work for #9692 
`AsyncRowSampler` continues the `CurrentOptions` on retries.
I am sure this will call `ConfigureContext()` with the right options. I am less sure that this is the "right" way to continue the `Options`. It seems like any `.then()` in this or `PerformAsyncStreamingRead<>` *could* continue the `Options`. I don't think it is necessary though. I think we only need the `Options` for when we are creating the `internal::AsyncStreamingReadRpc<>` and configuring the context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9693)
=> impl(bigtable): AsyncRowSampler continues CurrentOptions

google/cloud/bigtable/internal/async_bulk_apply.cc, google/cloud/bigtable/internal/async_bulk_apply.h, google/cloud/bigtable/internal/async_bulk_apply_test.cc, google/cloud/bigtable/internal/async_row_reader.cc, google/cloud/bigtable/internal/async_row_reader.h, google/cloud/bigtable/internal/async_row_reader_test.cc, google/cloud/bigtable/internal/async_row_sampler_test.cc
Fixes #9692 
The same as #9693, but for `AsyncBulkApplier` and `AsyncRowReader`.
Also, verify that the `GrpcSetupOption` is invoked twice in these tests, as this is the behavior we really care about.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9700)
=> impl(bigtable): `AsyncBulkApplier`, `AsyncRowReader` continue `CurrentOptions()`

google/cloud/bigtable/internal/bulk_mutator.cc, google/cloud/bigtable/internal/bulk_mutator.h, google/cloud/bigtable/internal/bulk_mutator_test.cc
Part of the work for #7479 
In order to report the proper errors for bulk mutations that end on OK streams, the `BulkMutator` needs to keep track of the last known status for a mutation it may or may not retry. There is always one copy translating from `grpc::Status` -> `google::cloud::Status`. `std::move()` the `Status` from then on.
In the case where a mutation fails in a stream that also fails, I return the mutation error. My guess is that it will be more informative. But we accept either in the unit test.
Note that we retry all OK streams at the moment. This will be fixed in either 1, 2, or 4 follow up PRs. (I haven't decided)
- - - …
=> impl(bigtable): `BulkMutator` keeps pending mutations' last status

google/cloud/bigtable/internal/async_bulk_apply.cc, google/cloud/bigtable/internal/async_bulk_apply_test.cc, google/cloud/bigtable/internal/data_connection_impl.cc, google/cloud/bigtable/internal/data_connection_impl_test.cc, google/cloud/bigtable/internal/legacy_async_bulk_apply.cc, google/cloud/bigtable/internal/legacy_async_bulk_apply_test.cc, google/cloud/bigtable/table.cc, google/cloud/bigtable/table.h, google/cloud/bigtable/table_bulk_apply_test.cc
Fixes #7479 
Streams with an OK status, but failing mutations count towards the retry policy. 
While the 4 tests don't look like each other, they are consistent with the other tests in their fixtures, namely the `TooManyFailures` or `*Exhausted` tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9706)
=> fix(bigtable): Use retry policy on streams with failing mutations

ci/cloudbuild/builds/lib/integration.sh, google/cloud/internal/oauth2_google_credentials.cc, google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/internal/oauth2_service_account_credentials.h, google/cloud/storage/internal/unified_rest_credentials.cc, google/cloud/storage/oauth2/service_account_credentials.cc
In order to migrate to the Rest library, we need to create `storage::oauth2::Credentials` from `oauth2_internal::Credentials`. The difficulty comes from the inability to overload `AuthorizationHeader` between the two types because only the return type is different, thus the wrapper and visitor pattern to map between the two.
Additionally, while we intend to phase out P12 support, we need to add support for it back in to `oauth2_internal` until we formally remove P12 support. Without P12 support, the mapping between the two types is incomplete.
Part of the work for #9689
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9709)
=> impl(oauth2): refactor Credentials for Rest transport with P12 support

generator/generator_config.textproto, google/cloud/dataproc/README.md, google/cloud/dataproc/autoscaling_policy_connection.cc, google/cloud/dataproc/autoscaling_policy_connection.h, google/cloud/dataproc/batch_controller_connection.cc, google/cloud/dataproc/batch_controller_connection.h, google/cloud/dataproc/cluster_controller_connection.cc, google/cloud/dataproc/cluster_controller_connection.h, google/cloud/dataproc/doc/main.dox, google/cloud/dataproc/internal/autoscaling_policy_option_defaults.cc, google/cloud/dataproc/internal/autoscaling_policy_option_defaults.h, google/cloud/dataproc/internal/batch_controller_option_defaults.cc, google/cloud/dataproc/internal/batch_controller_option_defaults.h, google/cloud/dataproc/internal/cluster_controller_option_defaults.cc, google/cloud/dataproc/internal/cluster_controller_option_defaults.h, google/cloud/dataproc/internal/job_controller_option_defaults.cc, google/cloud/dataproc/internal/job_controller_option_defaults.h, google/cloud/dataproc/internal/workflow_template_option_defaults.cc, google/cloud/dataproc/internal/workflow_template_option_defaults.h, google/cloud/dataproc/job_controller_connection.cc, google/cloud/dataproc/job_controller_connection.h, google/cloud/dataproc/quickstart/quickstart.cc, google/cloud/dataproc/workflow_template_connection.cc, google/cloud/dataproc/workflow_template_connection.h
There will now be an additional `Make<Service>Connection()` overload
that takes a `location` parameter, which is used to build the default
`EndpointOption` value (see #9625).
Update the quickstart to use the new `MakeClusterControllerConnection()`
overload.
Fixes #8239.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9722)
=> feat(dataproc): mark the dataproc services as location dependent

google/cloud/internal/oauth2_credentials.cc, google/cloud/internal/oauth2_credentials.h, google/cloud/internal/oauth2_service_account_credentials.cc, google/cloud/internal/oauth2_service_account_credentials.h
This is necessary in order to be consistent with the current `storage::oauth2::SignBlob` functionality.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9724)
=> impl(oauth2): allow for optional signing account in SignBlob

google/cloud/spanner/integration_tests/data_types_integration_test.cc
Reduce the "spanner_json_max_nesting_level" from 90 to 80, now that
the service is crashing on nesting depths somewhere in [82..90].
It appears that 80 will be the new documented limit.
And that means we temporarily expect `kAlreadyExists` when trying to
re-add a value with a nesting depth of 81.
See #7212, #8327, and #8689 for previous action in this area.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9727)
=> test(spanner): cater to the service vagaries on nested JSON

google/cloud/bigtable/internal/bigtable_channel_refresh_test.cc, google/cloud/bigtable/internal/bigtable_stub_factory.cc, google/cloud/bigtable/internal/common_client.h, google/cloud/bigtable/internal/connection_refresh_state.cc, google/cloud/bigtable/internal/connection_refresh_state.h, google/cloud/bigtable/internal/connection_refresh_state_test.cc
Fixes #9712 
This is mostly a refactor. Update the channel refresh API to accept a `shared_ptr<internal::CompletionQueueImpl>` instead of a `shared_ptr<CompletionQueue>`.
Now, we will not back out of the channel refresh loop too early, because the background threads hold onto the CQ object for the lifetime of the stub.
Add a regression test for this behavior that fails at HEAD.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9718)
=> fix(bigtable): `DataConnection` refreshes channels

ci/cloudbuild/builds/checkers.sh
Mention the `.mdformat.toml` file in the "checkers" build script.
We need the configuration file to stop `mdformat` from searching
up outside the source tree, so we might as well use it to set
the configuration, instead of using command-line options.  This
breadcrumb will reinforce that convention.
Also add some hyphenation to a nearby message while I'm here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9733)
=> doc: leave a reference to the mdformat configuration file

google/cloud/pubsublite/internal/resumable_async_streaming_read_write_rpc.h, google/cloud/storage/internal/rest_client.cc
The right incantation to move a `Status` from a `StatusOr<>` is
`std::move(x).status()`, not `std::move(x.status())`. Hopefully my
search-fu was good enough to find all of them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9734)
=> cleanup: avoid copying `Status` from `StatusOr<>`

google/cloud/storage/doc/storage-main.dox, google/cloud/storage/quickstart/README.md
Change https://cloud.google.com/storage/docs/quickstarts to https://cloud.google.com/storage/docs/introduction#quickstarts as per https://critique.corp.google.com/cl/470022707
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9738)
=> doc(storage): update broken docs link

google/cloud/storage/benchmarks/CMakeLists.txt
I am going to make more changes to this file, the extra nesting was
annoying.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9741)
=> cleanup(storage): unnest benchmark CMake file

google/cloud/storage/internal/retry_client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9744)
=> feat(storage): improve error messages on stalled uploads

google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_benchmark.cc, google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/benchmarks/benchmark_utils.h, google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_experiment.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc, google/cloud/storage/benchmarks/throughput_result.cc, google/cloud/storage/benchmarks/throughput_result.h, google/cloud/storage/benchmarks/throughput_result_test.cc
Now all benchmarks support `--labels`, which makes it easier to
concatenate and then analyze the results from multiple tests. The test
also capture GCE metadata by default, this is useful for analysis too.
I also changed the output from different benchmarks to start with the
timestamp of each experiment and then the labels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9748)
=> test(storage): more consistent benchmark output and options

google/cloud/storage/grpc_plugin_test.cc, google/cloud/storage/internal/hybrid_client.cc, google/cloud/storage/internal/hybrid_client.h, google/cloud/storage/internal/rest_client.cc, google/cloud/storage/internal/rest_client.h
Remove uses of `CurlClient`. One lingering in the implementation of
`RestClient` itself.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9759)
=> cleanup(storage): remove some uses of `CurlClient`

google/cloud/internal/curl_handle.cc, google/cloud/internal/curl_wrappers.cc, google/cloud/internal/curl_wrappers.h, google/cloud/internal/curl_wrappers_test.cc, google/cloud/storage/internal/curl_handle.cc
Shorten some excessively long messages, simplify the output format, and
truncate bearer tokens in the logs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9758)
=> refactor: make HTTP logs safer and more readable

google/cloud/storage/internal/policy_document_request.cc
Thanks to @brianpl for this patch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9768)
=> fix(storage): no workaround needed with libc++ and MSVC

google/cloud/spanner/admin/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/integration_tests/client_integration_test.cc, google/cloud/spanner/integration_tests/data_types_integration_test.cc, google/cloud/spanner/testing/database_integration_test.cc, google/cloud/spanner/testing/database_integration_test.h
Add a `PgDatabaseIntegrationTest` test fixture that creates the
database using `DatabaseDialect::POSTGRESQL` and with PostgreSQL-
specific column types.  This enables the testing of types with
PG type annotation codes, like `spanner::PgNumeric`, from
`spanner/integration_tests:data_types_integration_test`.  Then,
add "WriteRead" and "WriteReadArray" tests for `PgNumeric` that
were previously missing.
Also move some (negative) checks for JSON index/key and PG NUMERIC
key support to the data-types integration test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9769)
=> test(spanner): create a PostgreSQL version of DatabaseIntegrationTest

google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser_test.cc
Applications can use `UploadContentLength` to set the full object size for both gRPC-based uploads.  The same option has the same effect with REST.
Fixes #5032
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9778)
=> impl(GCS+gRPC): support `UploadContentLength` option

google/cloud/dialogflow_cx/README.md, google/cloud/dialogflow_cx/quickstart/quickstart.cc, google/cloud/dialogflow_es/README.md, google/cloud/dialogflow_es/quickstart/quickstart.cc, google/cloud/documentai/README.md, google/cloud/documentai/quickstart/quickstart.cc
Make use of new generator support for services with location-dependent default endpoints (see #9625).
Fixes #9626.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9780)
=> cleanup: update the quickstarts for location-dependent services

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client_test.cc
The implementation of `GrpcClient::*Acl` needs to perform `GetBucketMetadata()` or `GetObjectMetadata()` requests to access the ACLs.  These requests must use the "full" projection, as the service does not return the ACLs for the default projection.  I also need to fix the testbench to work as the service does.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9786)
=> fix(GCS+gRPC): use full projection in `GrpcClient::*Acl()`

google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc
The format of the `google.storage.v2.Bucket.Logging.log_bucket` field was undefined until recently. The decision is to use "proto" format, this implements that decision.
Motivated by #5673
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9789)
=> impl(GCS+gRPC): handle bucket names in logging field

google/cloud/storage/examples/storage_bucket_samples.cc, google/cloud/storage/examples/storage_examples_common.cc, google/cloud/storage/examples/storage_examples_common.h, google/cloud/storage/examples/storage_examples_common_test.cc
Motivated by #5673
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9797)
=> refactor(storage): examples bucket prefix defined in a function

google/cloud/storage/tests/bucket_integration_test.cc, google/cloud/storage/tests/grpc_hmac_key_integration_test.cc, google/cloud/storage/tests/grpc_notification_integration_test.cc, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc, google/cloud/storage/tests/object_integration_test.cc, google/cloud/storage/tests/object_resumable_write_integration_test.cc
When possible, remove or at least simplify the workarounds for production.  In some cases the test needs to be disabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9799)
=> cleanup(GCS+gRPC): simplify workarounds for production

google/cloud/internal/curl_wrappers.cc, google/cloud/internal/curl_wrappers.h, google/cloud/internal/curl_wrappers_test.cc
By default, initialize libcurl with locking and signal handlers that work for most applications. In particular, leaving the default handler for `SIGPIPE` usually results in the application crashes when a socket is closed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9798)
=> fix(common): better defaults for curl initialization

google/cloud/storage/tests/bucket_integration_test.cc, google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc, google/cloud/storage/tests/grpc_default_object_acl_integration_test.cc, google/cloud/storage/tests/grpc_notification_integration_test.cc, google/cloud/storage/tests/grpc_object_acl_integration_test.cc, google/cloud/storage/tests/grpc_object_media_integration_test.cc, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc, google/cloud/storage/tests/grpc_service_account_integration_test.cc, google/cloud/storage/tests/object_basic_crud_integration_test.cc, google/cloud/storage/tests/object_integration_test.cc, google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc
A few tests needed some tweaks to work in production (the testbench is more forgiving).  I also switched from a generic bug to track the disabled tests to specific bugs that describe (or link) the underlying problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9807)
=> test(GCS+gRPC): prepare integration tests for production

google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/benchmarks/throughput_options_test.cc
I confused myself on how to interpret the default read and offset ranges. The intent was to *not* set a `ReadRange()` option if the command line arguments were not set. The effect was to set an empty `ReadRange()` value, which produced an unexpected `Range:` header. Fortunately, the value of the header had no effect, but really confused me.
With this change the optional parameters are represented by `absl::optional` values. Which makes it easier to treat them correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9808)
=> test(storage): fix handling of optional ranges

ci/cloudbuild/builds/gcs-grpc.sh, ci/etc/integration-tests-config.ps1, ci/etc/integration-tests-config.sh, google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/benchmarks/throughput_options.h, google/cloud/storage/examples/storage_examples_common.cc, google/cloud/storage/testing/storage_integration_test.cc, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc
There are several tests still disabled, but we have specific bugs to track them. Most of them are just waiting for changes to roll out in production.
Fixes #5673.  Or at least, the remaining work is all tracked my smaller bugs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9809)
=> ci: enable (most) GCS+gRPC integration tests

google/cloud/storage/benchmarks/aggregate_download_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_download_throughput_options_test.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_options.cc, google/cloud/storage/benchmarks/aggregate_upload_throughput_options_test.cc, google/cloud/storage/benchmarks/benchmark_utils.cc, google/cloud/storage/benchmarks/throughput_options.cc, google/cloud/storage/benchmarks/throughput_options_test.cc, google/cloud/storage/client_options.cc, google/cloud/storage/client_options_test.cc, google/cloud/storage/internal/curl_request_builder.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/options.h
These options have proven useful. Time to move them out of `storage_experimental`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9813)
=> feat(storage): release `*StallMinimumThroughputOption`

bazel/google_cloud_cpp_deps.bzl, external/googleapis/CMakeLists.txt, external/googleapis/renovate.sh
Use GCS as a backup source for the tarball. I changed the script that updates the googleapis SHA to populate this backup at the same time.
Fixes #8102
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9819)
=> ci: deflake googleapis downloads from GitHub

README.md
Update the support policy and breaking change policy to point to the Google Open Source docs.
Part of me thinks we should not be in the business of writing down the minimum versions of these things. But then the other part of me thinks that the information that customers want to know should be available without clicking links (and searchable too).
Maybe we should add `` tags and have a script that copies the table from the `oss-policies-info` repo and writes it into our README....
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9815)
=> docs: update support policy

doc/contributor/howto-guide-adding-generated-libraries.md, doc/contributor/howto-guide-declare-a-library-ga.md, generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator.h, generator/internal/scaffold_generator_test.cc, generator/standalone_main.cc
The generator can now generate GA or experimental scaffolding. GA is the default.
Update the generation instructions accordingly.
Make the GA/experimental + semver notes in the README and doxygen conform.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9824)
=> impl(generator): GA or experimental scaffolding

google/cloud/internal/oauth2_service_account_credentials_test.cc
One of the tests did not initialize the `FakeClock` and thus could fail if the previous test left it in an unexpected state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9828)
=> test(common): do not depend on test run order

ci/kokoro/windows/bazel-debug-2019-presubmit.cfg, ci/kokoro/windows/bazel-debug-2019.cfg, ci/kokoro/windows/bazel-release-2019-presubmit.cfg, ci/kokoro/windows/bazel-release-2019.cfg
This change just creates placeholder Kokoro configuration files. In a separate change I will remove the `bazel*.cfg` files without an explicit MSVC version. Then I will switch the default to 2022.
Part of the work for #9591
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9829)
=> ci: placeholders to change default MSVC version

google/cloud/storage/internal/storage_stub_factory.cc
Follow a number of recommendations from the gRPC team.  They all make sense to me. Turning off `GRPC_DNS_ENABLE_SRV_QUERIES` is useful in that it disables code that we do not use, and thus avoids any potential bugs.
The `KEEPALIVE` settings are less obvious.  They should help gRPC detect broken connections sooner than it would otherwise.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9832)
=> impl(GCS+gRPC): tweak gRPC channel configuration

google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_object_metadata_parser.cc, google/cloud/storage/internal/grpc_owner_parser.cc, google/cloud/storage/internal/grpc_owner_parser.h, google/cloud/storage/internal/grpc_owner_parser_test.cc
The struct was just serving as a namespace. This also starts the move of the GCS+gRPC implementation details to the `storage_internal` namespace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9837)
=> cleanup(GCS+gRPC): remove `struct GrpcOwnerParser`

.github/renovate.json
We have very specific versions in our pip requirement files. There are lots of them, and several of them receive too many updates. Reducing update frequency to weekly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9844)
=> chore: renovate is too noisy for pip

ci/kokoro/windows/bazel-debug-2019-presubmit.cfg, ci/kokoro/windows/bazel-debug-2019.cfg, ci/kokoro/windows/bazel-release-2019-presubmit.cfg, ci/kokoro/windows/bazel-release-2019.cfg
This change just creates placeholder Kokoro configuration files. In a separate change I will remove the `bazel*.cfg` files without an explicit MSVC version. Then I will switch the default to 2022.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9850)
=> ci: placeholders to change default MSVC version (#9829)

google/cloud/terminate_handler.h, google/cloud/terminate_handler_test.cc
Restore the original `TerminateHandler` at the end of each test so that
`TerminateHandler.UnsetTerminates` does not need to be run first.
Part of #9831.
And while we're here, avoid a namespace-scope `std::string`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9858)
=> test: make the TerminateHandler tests order independent

.bazelrc, ci/lib/init.sh
Run tests in a random order to help expose undesirable interdependencies.
Fixes #9831.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9865)
=> test: enable googletest shuffling

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_notification_metadata_parser.cc, google/cloud/storage/internal/grpc_notification_metadata_parser.h, google/cloud/storage/internal/grpc_notification_metadata_parser_test.cc, google/cloud/storage/internal/grpc_notification_request_parser.cc, google/cloud/storage/internal/grpc_notification_request_parser.h, google/cloud/storage/internal/grpc_notification_request_parser_test.cc
Part of the work for #8929.
But mostly a small PR to make sure my Kokoro configuration changes did not break anything.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9867)
=> refactor(GCS+gRPC): `Notification` helpers to `storage_internal`

ci/cloudbuild/convert-to-branch-triggers.sh, release/README.md
To support the LTS branch and to create patch releases, we need GCB triggers for that specific branch. This adds a script to create such triggers.
Update the notes on how to create patch releases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9866)
=> ci: new script to create branch triggers

google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/cleanup_stale_instances.cc, google/cloud/spanner/testing/cleanup_stale_instances.h, google/cloud/spanner/testing/pick_instance_config.cc, google/cloud/spanner/testing/pick_instance_config.h, google/cloud/spanner/testing/random_instance_name.cc, google/cloud/spanner/testing/random_instance_name.h
Tests and samples for user-managed instance configurations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9872)
=> feat(spanner): add support for CMMR phase 2

google/cloud/spanner/testing/cleanup_stale_instances.cc
These have never caught any problems, and, even if they did, the remedy would probably just be to remove the stales objects anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9875)
=> test(spanner): remove "too many stale" checks

ci/kokoro/windows/build-32.bat, ci/kokoro/windows/build.bat, ci/kokoro/windows/triplets/x64-windows-static.cmake, ci/kokoro/windows/triplets/x64-windows.cmake, ci/kokoro/windows/triplets/x86-windows-static.cmake, ci/kokoro/windows/triplets/x86-windows.cmake
`vcpkg` uses its own algorithm to find MSVC. The documented way to change this algorithm is to create a custom triplet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9881)
=> ci: use custom vcpkg triplets for Windows+CMake

ci/cloudbuild/builds/coverage.sh
Change all the codecov flags to their long versions for improved readability.  Add "--verbose" for additional logging.  Remove "-q", which doesn't exist (as far as I can tell from the project repo, it never did).
Fixes #9250.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9883)
=> cleanup: update coverage uploader to v0.3.1

google/cloud/storage/bucket_metadata.cc, google/cloud/storage/bucket_metadata.h, google/cloud/storage/internal/bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.cc
Populating all the fields for `BucketMetadata` was somewhat difficult. The class tried to prevent applications from setting fields that only the server would set.  I thought about adding a `BucketMetadataBuilder`, but that would duplicate a lot of code without preventing anything. In addition, all the other libraries use protos that allow any field to be set, and that does not seemt to create a lot of trouble or confusion.
I also stopped using the "composition-by-private-inheritance" base because it does not save enough code.  I expect this class will go away once I make similar changes to `ObjectMetadata`.
Part of the work for #8929, I also think it will help with #7142
- - - …
=> feat(storage): easier mocks with `BucketMetadata`

google/cloud/spanner/README.md, google/cloud/spanner/quickstart/quickstart.cc, google/cloud/spanner/samples/postgresql_samples.cc, google/cloud/spanner/samples/samples.cc
Throw `google::cloud::Status` values directly in samples, instead of wrapping only their messages in a `std::runtime_error`.  And then tweak to avoid `misc-throw-by-value-catch-by-reference` clang-tidy warnings.
In the quickstart we don't really need the complications of `throw` and `catch` at all.
Part of #9016.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9892)
=> cleanup(spanner): throw full Status values

google/cloud/storage/parallel_upload.h
Before we check whether `ParallelUploadFileSupportedOptions` contains a given type, we should remove any reference and top-level cv qualifiers. For example, `ParallelUploadFile()` supports `UserIp const&` just like it does `UserIp`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9893)
=> fix(storage): decay type before testing supported-options membership

google/cloud/storage/bucket_metadata.h, google/cloud/storage/google_cloud_cpp_storage.bzl, google/cloud/storage/google_cloud_cpp_storage.cmake, google/cloud/storage/internal/access_control_common.h, google/cloud/storage/internal/bucket_metadata_parser.cc, google/cloud/storage/internal/common_metadata.h, google/cloud/storage/internal/common_metadata_parser.h, google/cloud/storage/internal/grpc_object_metadata_parser.cc, google/cloud/storage/internal/grpc_owner_parser.h, google/cloud/storage/internal/lifecycle_rule_parser.cc, google/cloud/storage/internal/object_access_control_parser.cc, google/cloud/storage/internal/object_metadata_parser.cc, google/cloud/storage/object_access_control.h, google/cloud/storage/object_metadata.cc, google/cloud/storage/object_metadata.h, google/cloud/storage/object_metadata_test.cc, google/cloud/storage/owner.h
Recapitulates the changes to make `BucketMetadata` easier to mock. This change adds modifiers for all the fields in `ObjectMetadata` and removes the need for `internal::CommonMetadata<>`.
Since `internal::CommonMetadata<>` is not needed, I deprecated the class, removed all references to the class or its header file, and refactor any useful code out of its header file.
This is part of the work for #7142 and for #8929
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9899)
=> feat(storage): easier mocks with `ObjectMetadata`

google/cloud/internal/attributes.h
we require C++14, so simplify the deprecated macro
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9902)
=> cleanup: use [[deprecated]]

google/cloud/storage/google_cloud_cpp_storage.bzl, google/cloud/storage/google_cloud_cpp_storage.cmake, google/cloud/storage/internal/access_control_common.h, google/cloud/storage/project_team.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9906)
=> refactor(storage): move `ProjectTeam` to a public header

ci/kokoro/windows/common.cfg
Only the builds testing specific versions of MSVC need to use MSVC 2019, or earlier.
Part of the work for #9591 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9908)
=> ci: use MSVC 2022 by default

google/cloud/storage/bucket_access_control.cc, google/cloud/storage/bucket_access_control.h, google/cloud/storage/internal/access_control_common.h, google/cloud/storage/internal/access_control_common_parser.cc, google/cloud/storage/internal/access_control_common_parser.h, google/cloud/storage/internal/access_control_common_parser_test.cc, google/cloud/storage/internal/access_control_common_test.cc, google/cloud/storage/internal/bucket_access_control_parser.cc, google/cloud/storage/internal/common_metadata.h, google/cloud/storage/internal/grpc_bucket_access_control_parser.cc, google/cloud/storage/internal/grpc_object_access_control_parser.cc, google/cloud/storage/internal/object_access_control_parser.cc, google/cloud/storage/internal/object_acl_requests.cc, google/cloud/storage/object_access_control.cc, google/cloud/storage/object_access_control.h, google/cloud/storage/project_team.h
Add modifiers for all the attributes in `ObjectAccessControl` and `BucketAccessControl`. That makes it easier to mock the class.
I deprecated `internal::AccessControlCommon` as this class is no longer used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9910)
=> feat(storage): easier mocks for `*AccessControl`

bazel/google_cloud_cpp_deps.bzl
Use `Label()` to avoid referencing the name of the repository (`@com_github_googleapis_google_cloud_cpp`) in the definition of the workspace macro.  With this change, downstream dependencies can use whatever name they want for our repository.  Currently, they have to use `@com_github_googleapis_google_cloud_cpp`.  Once we create a release, we can use this to shorten our repository name and compile more code on Windows.
Part of the work for #9340.  Tested locally with:
```
env -C google/cloud/kms/quickstart/ bazel build :quickstart
```
and
```
env -C google/cloud/kms/quickstart/ bazel build --override_repository=com_github_googleapis_google_cloud_cpp=$PWD :quickstart
```
Candidly, I copied this from the [tensorstore](https://github.com/google/tensorstore/blob/master/third_party/com_github_n …
=> feat: Bazel downstream dependencies can pick repository name

google/cloud/storage/tests/thread_integration_test.cc
Lower the number of objects created/deleted in the test, which brings down the average runtime from about to 12.5m to 10m, and that reduces the possibility of exceeding the "long" timeout of 15m.
"Fixes" #9909.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9918)
=> test(storage): reduce runtime of ThreadIntegrationTest.Unshared

ci/kokoro/windows/builds/quickstart-bazel.ps1, ci/kokoro/windows/builds/quickstart-cmake.ps1, ci/kokoro/windows/lib/bazel.ps1, ci/kokoro/windows/lib/vcpkg.ps1
For CMake: compile as many as are available with the `vcpkg` version used in the builds.
For Bazel: compile as many as are available with the `google-cloud-cpp` release used in the quickstart `WORKSPACE.bazel` files.
In both cases I created a hard-coded list of libraries that do not compile on Windows.  I could not figure out how to query the libraries that fail to compile on Windows from Bazel or CMake.
Fixes #9891 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9920)
=> ci: compile all quickstarts on Windows

google/cloud/storage/grpc_plugin_test.cc
Avoid depending on the production service and/or credentials.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9928)
=> test(GCS+gRPC): avoid global resources in unit test

google/cloud/internal/async_connection_ready.cc, google/cloud/internal/async_connection_ready.h, google/cloud/internal/async_connection_ready_test.cc
The helpers to wait for a `grpc::Channel` to be ready sometimes failed because the channel was already connected. This was harmless, as this was mostly used to continuously poll the connections.
The tests could flake under load.  Put some code to prevent this, and increase the timeouts to make it even less likely.
Fixes #9922
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9927)
=> fix: spurious timeouts waiting for connection

ci/kokoro/windows/builds/quickstart-bazel.ps1
The intention was to discover the quickstarts available using the `google-cloud-cpp` version in the `**/quickstart/WORKSPACE.bazel` files.  To do so, we should run the bazel query in a `**/quickstart` directory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9931)
=> ci: fix directory to discover quickstarts

google/cloud/spanner/integration_tests/data_types_integration_test.cc
Remove the test that verified the Spanner service supports its advertised maximum level of JSON nesting.  The client doesn't do anything but pass the JSON string through, so any testing here belongs solely in the realm of the service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9933)
=> test(spanner): remove DataTypeIntegrationTest.JsonMaxNesting

google/cloud/storage/bucket_access_control.h, google/cloud/storage/bucket_metadata.h, google/cloud/storage/google_cloud_cpp_storage.bzl, google/cloud/storage/google_cloud_cpp_storage.cmake, google/cloud/storage/internal/grpc_bucket_access_control_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_object_access_control_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/patch_builder.h, google/cloud/storage/internal/patch_builder_details.cc, google/cloud/storage/internal/patch_builder_details.h, google/cloud/storage/object_access_control.h, google/cloud/storage/object_metadata.h
Use a single `friend` struct that needs to be forward declared.
The Google Style Guide frowns upon `struct` types with only static
functions. I think it is justified in this case because (a) it
simplifies all the `friend` declaratios, (b) it avoids exposing the
`nlohmann` stuff in our public headers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9932)
=> cleanup(storage): minimize friends for `*PatchBuilder`

google/cloud/storage/internal/grpc_bucket_access_control_parser.cc, google/cloud/storage/internal/grpc_bucket_access_control_parser.h, google/cloud/storage/internal/grpc_bucket_access_control_parser_test.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_client.cc
Move the helper functions out of an empty struct and into the `storage_internal` namespace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9937)
=> cleanup(GCS+gRPC): BucketAccessControl helpers

google/cloud/storage/internal/access_control_common.h, google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_access_control_parser.cc, google/cloud/storage/internal/grpc_object_access_control_parser.h, google/cloud/storage/internal/grpc_object_access_control_parser_test.cc, google/cloud/storage/internal/grpc_object_metadata_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.cc
Move the functions to a namespace and remove the
`GrpcObjectAccessControlParser` struct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9938)
=> cleanup(GCS+gRPC): `ObjectAccessControl` helpers

google/cloud/storage/internal/async_accumulate_read_object.cc, google/cloud/storage/internal/common_metadata.h, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_metadata_parser.cc, google/cloud/storage/internal/grpc_object_metadata_parser.h, google/cloud/storage/internal/grpc_object_metadata_parser_test.cc, google/cloud/storage/internal/grpc_object_read_source.cc, google/cloud/storage/internal/grpc_object_read_source_test.cc, google/cloud/storage/internal/grpc_object_request_parser.cc
Remove the `GrpcObjectMetadataParser` struct, move its functions (they were all static) to the `storage_internal` namespace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9941)
=> cleanup(GCS+gRPC): move `ObjectMetadata` helpers

google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.h, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/lifecycle_rule.h
Remove the `GrpcBucketMetadataParser` struct, move its functions (they were all static) to the `storage_internal` namespace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9942)
=> cleanup(GCS+gRPC): move `BucketMetadata` helpers

google/cloud/storage/internal/async_connection_impl.cc, google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_object_request_parser.cc, google/cloud/storage/internal/grpc_object_request_parser.h, google/cloud/storage/internal/grpc_object_request_parser_test.cc
Remove the `GrpcObjectRequestsParser` struct, and move its functions (they were all static) to the `storage_internal` namespace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9943)
=> cleanup(GCS+gRPC): move Object request helpers

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_service_account_parser.cc, google/cloud/storage/internal/grpc_service_account_parser.h, google/cloud/storage/internal/grpc_service_account_parser_test.cc
Remove the `GrpcServiceAccountParser` struct, and move all its functions (they were all `static`) to the `storage_internal` namespace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9950)
=> cleanup(GCS+gRPC): move `ServiceAccount` helpers to namespace

google/cloud/storage/hmac_key_metadata.h, google/cloud/storage/internal/grpc_hmac_key_metadata_parser.cc, google/cloud/storage/internal/hmac_key_metadata_parser.cc
Add modifiers to make mocking easier. Remove unneeded `friend` declarations after this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9949)
=> feat(storage): easier mocks for `HmacKeyMetadata`

google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser.h, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/storage/internal/grpc_client.cc
Remove the `GrpcBucketRequestParser` struct, which only had static member functions. Move the functions to the `storage_internal` namespace.
Part of the changes for #8929
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9951)
=> cleanup(GCS+gRPC): move `Bucket` request helpers to namespace

google/cloud/spanner/internal/session_pool.cc, google/cloud/spanner/internal/session_pool.h, google/cloud/spanner/internal/session_pool_test.cc
When the "SELECT 1" session-refresh query fails with "Session not found", remove the bad session from the pool, if possible.  Previously we did nothing because (1) it shouldn't happen, and (2) we have other mechanisms in place to deal with bad sessions (which must remain).  But it is better dealt with directly if we can.
Fixes #4026.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9954)
=> fix(spanner): remove session from pool upon "not found" refresh failure

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_hmac_key_metadata_parser.cc, google/cloud/storage/internal/grpc_hmac_key_metadata_parser.h, google/cloud/storage/internal/grpc_hmac_key_metadata_parser_test.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.cc
Remove the `HmacKeyMetadataParser` struct, which only had static member functions. Move the functions to the `storage_internal` namespace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9955)
=> cleanup(GCS+gRPC): move `HmacKeyMetadata` helpers to namespace

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.cc, google/cloud/storage/internal/grpc_hmac_key_request_parser.h, google/cloud/storage/internal/grpc_hmac_key_request_parser_test.cc
Remove the `GrpcHmacKeyRequestParser` struct, which only had static member functions. Move the functions to the `storage_internal` namespace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9959)
=> cleanup(GCS+gRPC): move `HmacKey` request helpers to namespace

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_sign_blob_request_parser.cc, google/cloud/storage/internal/grpc_sign_blob_request_parser.h, google/cloud/storage/internal/grpc_sign_blob_request_parser_test.cc
Despite the branch name, this is only part of the work for #8929
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9962)
=> cleanup(GCS+gRPC): move `SignBlob` request helpers

google/cloud/internal/retry_loop_helpers.cc, google/cloud/internal/retry_loop_helpers.h, google/cloud/internal/retry_loop_helpers_test.cc
Motivated by #9947
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9971)
=> fix(common): preserve `ErrorInfo` on retry errors

google/cloud/storage/tests/error_parsing_integration_test.cc
Motivated by #9947
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9974)
=> test(storage): check for useful `ErrorInfo`

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_client.h, google/cloud/storage/internal/grpc_client_test.cc
An upcoming change to the GCS protos will allow us to improve the implementation of `*AccessControl` updates.  Some entities go by two different ids.  The upcoming protos will include both ids. We can then implement more accurate Get -> Modify -> Update loops for these resources.
Part of the work for #9900
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9979)
=> impl(GCS+gRPC): use protos for *AccessControl updates

google/cloud/bigtable/internal/defaults.cc, google/cloud/bigtable/internal/defaults_test.cc
Fixes #4382 and basically undoes #6175
I set up a VM with the magic subnet. If I set the endpoint as such and make some request, I see that my gRPC peer is `2001:4860:8040:...etc....`.
Note that `google-c2p:///bigtable.googleapis.com` requires the project to be allow-listed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9978)
=> feat(bigtable): support `GOOGLE_CLOUD_ENABLE_DIRECT_PATH`

google/cloud/pubsub/internal/batching_publisher_connection.cc, google/cloud/pubsub/internal/batching_publisher_connection.h, google/cloud/pubsub/internal/batching_publisher_connection_test.cc
Cancel the timer (if any) before shutting down.  This can be a problem for applications that have very long batches (say multiple seconds or minutes).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9991)
=> fix(pubsub): faster shutdowns for `Publisher`

CMakeLists.txt, cmake/GoogleapisConfig.cmake, doc/contributor/howto-guide-update-googleapis-sha.md, external/googleapis/CMakeLists.txt, external/googleapis/renovate.sh
Still provide a mechanism to override the URL. This is useful when building in environments disconnected from the Internet, or when creating packages, where downloading is frowned upon.
Fixes #9993
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9994)
=> fix: download googleapis if SHA changes

google/cloud/pubsub/internal/batching_publisher_connection.cc
Fixes #9995  Tested with:
```
CXX=clang++ CC=clang bazel test --test_filter=BatchingPublisherConnectionTest.BatchTorture --config=tsan --runs_per_test=10000 //google/cloud/pubsub:internal_batching_publisher_connection_test
INFO: Analyzed target //google/cloud/pubsub:internal_batching_publisher_connection_test (0 packages loaded, 137 targets configured).
INFO: Found 1 test target...
Target //google/cloud/pubsub:internal_batching_publisher_connection_test up-to-date:
/usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/f1b649d8eddab70da217bfe95503f270/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/pubsub/internal_batching_publisher_connection_test
INFO: Elapsed time: 290.361s, Critical Path: 10.31s
INFO: 10001 processes: 1 internal, 10000 …
```
=> fix(pubsub): race condition capturing batching timer

google/cloud/storage/internal/curl_client.cc, google/cloud/storage/internal/curl_client.h, google/cloud/storage/internal/generate_message_boundary.cc, google/cloud/storage/internal/generate_message_boundary_benchmark.cc, google/cloud/storage/internal/rest_client.cc, google/cloud/storage/internal/rest_client.h, google/cloud/storage/options.h
With this change the client library will optimistically use a randomly generated string as a message boundary, but will not validate if the string appears in the payload.
The new behavior makes sense as (1) it saves about 2ms of client CPU time for 128MiB uploads, (2) if there is a collision this will be detected by the service via the upload checksums, and (3) the probability of a collision is small.
The current implementation has a population of more than $10^{100}$ strings to pick from. The probability of finding this string in a EB of data is less than $1 / 10^{95}$.  You could upload a EB of data per second for a billion years and still not find a collision.
- - - …
=> feat(storage): faster `InsertObject()` uploads

google/cloud/storage/bucket_autoclass.cc, google/cloud/storage/bucket_autoclass.h, google/cloud/storage/bucket_metadata.cc, google/cloud/storage/bucket_metadata.h, google/cloud/storage/bucket_metadata_test.cc, google/cloud/storage/examples/CMakeLists.txt, google/cloud/storage/examples/storage_bucket_autoclass_samples.cc, google/cloud/storage/examples/storage_examples.bzl, google/cloud/storage/google_cloud_cpp_storage.bzl, google/cloud/storage/google_cloud_cpp_storage.cmake, google/cloud/storage/internal/bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.cc, google/cloud/storage/internal/grpc_bucket_metadata_parser.h, google/cloud/storage/internal/grpc_bucket_metadata_parser_test.cc, google/cloud/storage/internal/grpc_bucket_request_parser.cc, google/cloud/storage/internal/grpc_bucket_request_parser_test.cc, google/cloud/testing_util/example_driver.cc
This implements support for REST and gRPC, as well as the unit tests and the samples.
Fixes #9751
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10003)
=> feat(storage): support `Autoclass` feature

google/cloud/storage/internal/grpc_client.cc, google/cloud/storage/internal/grpc_configure_client_context.cc, google/cloud/storage/internal/grpc_configure_client_context.h, google/cloud/storage/internal/grpc_configure_client_context_test.cc
Move more helper functions to the `storage_internal` namespace.
Part of the work for #8929 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10009)
=> cleanup(GCS+gRPC): move to `storage_internal`

google/cloud/completion_queue_benchmark.cc, google/cloud/options_benchmark.cc, google/cloud/spanner/bytes_benchmark.cc, google/cloud/spanner/internal/merge_chunk_benchmark.cc, google/cloud/spanner/numeric_benchmark.cc, google/cloud/spanner/row_benchmark.cc, google/cloud/storage/internal/generate_message_boundary_benchmark.cc
There are `T const&` and `T&` overloads of `benchmark::DoNotOptimize()`. It seems the `T const&` does not work with some compilers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10018)
=> cleanup: use recommended `benchmark::DoNotOptimize` overload

google/cloud/storage/tests/create_client_integration_test.cc
Even though `create_client_integration_test.cc` is an integration test, there is no reason to use the default credentials with the emulator. The default credentials typically try to use the GCE metadata service, which may not exist in some CI environments. Or may take a long time to fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10019)
=> test(storage): make one test more hermetic

google/cloud/storage/google_cloud_cpp_storage_grpc.cmake
They were sorted already, so this is probably redundant. At least, it makes the CMake file consistent with other similar files and minimizes confusion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10025)
=> cleanup(GCS+gRPC): keep library sources sorted

google/cloud/storage/tests/grpc_bucket_acl_integration_test.cc, google/cloud/storage/tests/grpc_bucket_metadata_integration_test.cc, google/cloud/storage/tests/grpc_default_object_acl_integration_test.cc, google/cloud/storage/tests/grpc_hmac_key_integration_test.cc, google/cloud/storage/tests/grpc_integration_test.cc, google/cloud/storage/tests/grpc_notification_integration_test.cc, google/cloud/storage/tests/grpc_object_acl_integration_test.cc, google/cloud/storage/tests/grpc_object_media_integration_test.cc, google/cloud/storage/tests/grpc_object_metadata_integration_test.cc, google/cloud/storage/tests/grpc_service_account_integration_test.cc
The integration tests do not need to be in the `storage::internal` namespace.
Fixes #8929
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10026)
=> cleanup(GCS+gRPC): move out of `storage::internal`

google/cloud/spanner/testing/random_backup_name.cc, google/cloud/spanner/testing/random_database_name.cc, google/cloud/spanner/testing/random_instance_name.cc
While it is allowable to use hyphens and/or underscores in the suffixes we generate for random database, backup, and instance{,config} names, they just make the prefixes less discernible at a glance.  So, omit them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10020)
=> test(spanner): only use alpha-numerics in random name suffixes

google/cloud/spanner/numeric.cc
`clang-tidy` says that `std::string(ptr, 0)` is bug prone. Same thing for `std::string_view` and `absl::string_view`.  We could silence the warning with `NOLINT`, but I think a default constructor captures the intent better.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10029)
=> cleanup(spanner): fix future clang-tidy warnings

google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source.h, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
Pub/Sub sets a quota of 512KB for `ModifyAckDeadlineRequest` messages. Theoretically we could have gone over that limit, for example, if the application had thousands of messages in memory, and we needed to extend their leases.  With this change such requests will be broken into multiple RPCs.
It also sets a quota for `AcknowledgeRequest` messages, but always send a single `ack_id` in this case, there is no chance to go over the limit.
Fixes #9471
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10032)
=> fix(pubsub): limit `ModifyAckDeadlineRequest` size

google/cloud/spanner/admin/integration_tests/instance_admin_integration_test.cc
Temporarily refrain from creating an Instance that uses the custom InstanceConfig until we can figure out why the DeleteInstanceConfig() call is now failing with "Cannot remove <name> since it is used by 1 instance(s)."
"Fixes" #10006.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10033)
=> test(spanner): refrain from creating an instance using the custom config

google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsub/google_cloud_cpp_pubsub.bzl, google/cloud/pubsub/mocks/mock_subscriber_connection.h, google/cloud/pubsub/subscriber.cc, google/cloud/pubsub/subscriber.h, google/cloud/pubsub/subscriber_connection.cc, google/cloud/pubsub/subscriber_connection.h, google/cloud/pubsub/subscriber_connection_test.cc, google/cloud/pubsub/subscriber_test.cc
Part of the work for #7689
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10043)
=> feat(pubsub): implement per-call options for `Subscriber`

google/cloud/pubsub/internal/publisher_auth.cc, google/cloud/pubsub/internal/publisher_auth.h, google/cloud/pubsub/internal/publisher_auth_test.cc, google/cloud/pubsub/internal/publisher_logging.cc, google/cloud/pubsub/internal/publisher_logging.h, google/cloud/pubsub/internal/publisher_logging_test.cc, google/cloud/pubsub/internal/publisher_metadata.cc, google/cloud/pubsub/internal/publisher_metadata.h, google/cloud/pubsub/internal/publisher_metadata_test.cc, google/cloud/pubsub/internal/publisher_round_robin.cc, google/cloud/pubsub/internal/publisher_round_robin.h, google/cloud/pubsub/internal/publisher_round_robin_test.cc, google/cloud/pubsub/internal/publisher_stub.cc, google/cloud/pubsub/internal/publisher_stub.h, google/cloud/pubsub/testing/mock_publisher_stub.h
This is the blocking version of `AsyncPublish()`, I will use it to implement a simpler API for applications that do not need high-performance publishers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10047)
=> impl(pubsub): add `Publish()` to stub and decorators

google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_impl.h, google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/internal/rest_options.h, google/cloud/internal/rest_response.cc, google/cloud/storage/client_options.cc, google/cloud/storage/client_options_test.cc, google/cloud/storage/internal/rest_client.cc, google/cloud/storage/tests/object_resumable_write_integration_test.cc
We need the full payload when returning completing a `HttpRequest` with a non-OK status code. The payload may contain a full ErrorInfo, and we want the application to have access to those.
`rest_internal::CurlImpl` was converting the HTTP status code unless it was in a list of values ignored. Then `storage::RestClient` used a per-method predicate to convert some values to errors.  It seems simpler to *never* convert an HTTP status code to a `Status` in the `CurlImpl` layer. After all, an HTTP request that completes with a status code was able to send and receive the call.
Fixes #9947 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10051)
=> fix(rest): return complete payloads for errors

google/cloud/internal/curl_http_payload.cc, google/cloud/internal/curl_http_payload.h, google/cloud/internal/curl_impl.cc, google/cloud/internal/curl_rest_client_integration_test.cc, google/cloud/storage/tests/CMakeLists.txt, google/cloud/storage/tests/object_read_large_integration_test.cc, google/cloud/storage/tests/storage_client_integration_tests.bzl
We were injecting a `:curl-peer` pseudo-header (usually used for troubleshooting) for each `Read()` call.  The existing tests did not catch this because this headers were never exposed to the application layer either.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10054)
=> fix(rest): too many debug headers

google/cloud/pubsub/internal/publisher_stub.cc, google/cloud/pubsub/internal/publisher_stub.h, google/cloud/pubsub/internal/schema_stub.cc, google/cloud/pubsub/internal/schema_stub.h, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h
The generator puts these classes in the headers (for good reasons), I want to do the same to make the switch to fully generated files easier to grok.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10061)
=> refactor(pubsub): move `Default*Stub` to headers

google/cloud/pubsub/internal/schema_auth_decorator.cc, google/cloud/pubsub/internal/schema_auth_decorator.h, google/cloud/pubsub/internal/schema_auth_test.cc, google/cloud/pubsub/internal/schema_logging_decorator.cc, google/cloud/pubsub/internal/schema_logging_decorator.h, google/cloud/pubsub/internal/schema_logging_test.cc, google/cloud/pubsub/internal/schema_metadata_decorator.cc, google/cloud/pubsub/internal/schema_metadata_decorator.h, google/cloud/pubsub/internal/schema_metadata_test.cc, google/cloud/pubsub/internal/schema_stub.cc, google/cloud/pubsub/internal/schema_stub.h, google/cloud/pubsub/internal/schema_stub_factory.cc, google/cloud/pubsub/internal/schema_stub_factory.h, google/cloud/pubsub/schema_admin_connection.cc, google/cloud/pubsub/schema_admin_connection.h, google/cloud/pubsub/schema_admin_connection_test.cc, google/cloud/pubsub/testing/mock_schema_stub.h
Use the name that the generator will use: `SchemaServiceStub`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10064)
=> refactor(pubsub): rename `SchemaStub`

google/cloud/pubsub/internal/publisher_auth_decorator.cc, google/cloud/pubsub/internal/publisher_auth_decorator.h, google/cloud/pubsub/internal/publisher_logging_decorator.cc, google/cloud/pubsub/internal/publisher_logging_decorator.h, google/cloud/pubsub/internal/publisher_metadata_decorator.cc, google/cloud/pubsub/internal/publisher_metadata_decorator.h, google/cloud/pubsub/internal/publisher_stub.cc, google/cloud/pubsub/internal/publisher_stub.h, google/cloud/pubsub/internal/subscriber_auth_decorator.cc, google/cloud/pubsub/internal/subscriber_auth_decorator.h, google/cloud/pubsub/internal/subscriber_logging_decorator.cc, google/cloud/pubsub/internal/subscriber_logging_decorator.h, google/cloud/pubsub/internal/subscriber_metadata_decorator.cc, google/cloud/pubsub/internal/subscriber_metadata_decorator.h, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h
This is a large, but trivial change. It reorders the `*Stub` member function declaration and definitions to match the order used by the generator.
Part of the work for #7187.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10066)
=> refactor(pubsub): reorder `*Stub` functions

google/cloud/pubsub/internal/publisher_logging_decorator.cc, google/cloud/pubsub/internal/schema_logging_decorator.cc, google/cloud/pubsub/internal/subscriber_logging_decorator.cc
This is to match what the generator does.
Part of the changes for #7187
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10069)
=> refactor(pubsub): fully qualify `LogWrapper()` calls

google/cloud/pubsub/internal/publisher_stub.cc, google/cloud/pubsub/internal/publisher_stub.h, google/cloud/pubsub/internal/schema_stub.cc, google/cloud/pubsub/internal/schema_stub.h, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h
Use the same names the generator does.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10070)
=> cleanup(pubsub): match generated function parameters names

google/cloud/pubsub/internal/subscriber_logging_decorator.cc, google/cloud/pubsub/internal/subscriber_logging_decorator.h
Use the same wrapper as the generator does.
Part of the work for #7187.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10071)
=> cleanup(pubsub): remove ad-hoc wrapper for streaming RPC

google/cloud/pubsub/integration_tests/subscriber_integration_test.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source.cc, google/cloud/pubsub/internal/streaming_subscription_batch_source.h, google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc, google/cloud/pubsub/internal/subscriber_auth_decorator.cc, google/cloud/pubsub/internal/subscriber_auth_decorator.h, google/cloud/pubsub/internal/subscriber_auth_test.cc, google/cloud/pubsub/internal/subscriber_logging_decorator.cc, google/cloud/pubsub/internal/subscriber_logging_decorator.h, google/cloud/pubsub/internal/subscriber_logging_test.cc, google/cloud/pubsub/internal/subscriber_metadata_decorator.cc, google/cloud/pubsub/internal/subscriber_metadata_decorator.h, google/cloud/pubsub/internal/subscriber_metadata_test.cc, google/cloud/pubsub/internal/subscriber_round_robin.cc, google/cloud/pubsub/internal/subscriber_round_robin.h, google/cloud/pubsub/internal/subscriber_round_robin_test.cc, google/cloud/pubsub/internal/subscriber_stub.cc, google/cloud/pubsub/internal/subscriber_stub.h, google/cloud/pubsub/internal/subscription_session_test.cc, google/cloud/pubsub/subscriber_connection_test.cc, google/cloud/pubsub/testing/fake_streaming_pull.cc, google/cloud/pubsub/testing/fake_streaming_pull.h, google/cloud/pubsub/testing/mock_subscriber_stub.h
Use the generator signature for `StreamingPull`, the only bidir streaming RPC in this service. The affected function is in `pubsub_internal`, so the change is non-breaking, but it does require changing a large number of tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10072)
=> cleanup(pubsub): signature for bidir streaming RPC

google/cloud/pubsub/internal/publisher_logging_decorator.cc, google/cloud/pubsub/internal/publisher_logging_decorator.h, google/cloud/pubsub/internal/publisher_logging_test.cc, google/cloud/pubsub/internal/publisher_stub_factory.cc, google/cloud/pubsub/internal/schema_logging_decorator.cc, google/cloud/pubsub/internal/schema_logging_decorator.h, google/cloud/pubsub/internal/schema_logging_test.cc, google/cloud/pubsub/internal/subscriber_logging_decorator.cc, google/cloud/pubsub/internal/subscriber_logging_decorator.h, google/cloud/pubsub/internal/subscriber_logging_test.cc, google/cloud/pubsub/schema_admin_connection.cc, google/cloud/pubsub/subscriber_connection.cc, google/cloud/pubsub/subscription_admin_connection.cc
Change the constructors for logging decorators to match the generated code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10073)
=> cleanup(pubsub): logging decorator constructors

ci/cloudbuild/builds/checkers.sh, ci/cloudbuild/builds/generate-libraries.sh
When possible, use `git ls-files` to filter files by extension or name. It should be possible to use `--exclude` to exclude files, but I left that for another day.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10084)
=> cleanup: use `git ls-files` to filter files

generator/integration_tests/golden/golden_kitchen_sink_client.cc, generator/integration_tests/golden/golden_kitchen_sink_client.h, generator/integration_tests/golden/golden_kitchen_sink_connection.cc, generator/integration_tests/golden/golden_kitchen_sink_connection.h, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_connection_impl.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_connection_impl.h, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.h, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.cc, generator/integration_tests/golden/internal/golden_kitchen_sink_stub.h, generator/integration_tests/golden/internal/streaming.cc, generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_connection.h, generator/integration_tests/golden_config.textproto, generator/integration_tests/test.proto, generator/integration_tests/tests/golden_kitchen_sink_auth_decorator_test.cc, generator/integration_tests/tests/golden_kitchen_sink_client_test.cc, generator/integration_tests/tests/golden_kitchen_sink_connection_test.cc, generator/integration_tests/tests/golden_kitchen_sink_logging_decorator_test.cc, generator/integration_tests/tests/golden_kitchen_sink_metadata_decorator_test.cc, generator/integration_tests/tests/golden_kitchen_sink_stub_test.cc, generator/integration_tests/tests/mock_golden_kitchen_sink_stub.h
The test RPCs had names inspired by their source service.  I found this
confusing when trying to determine if a new RPC for "streaming reads"
was needed, or what the right RPC for a "streaming read-write" test
would be.  This PR changes their names to `StreamingRead()`,
`StreamingWrite()`, and `StreamginReadWrite()`.  It also changes the
request and response messages to be shared across RPCs, and they are
simply named `Request` and `Response`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10086)
=> cleanup(generator): improve testing RPC names

google/cloud/spanner/integration_tests/data_types_integration_test.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/json.h, google/cloud/spanner/samples/postgresql_samples.cc, google/cloud/spanner/testing/database_integration_test.cc, google/cloud/spanner/value.cc, google/cloud/spanner/value.h, google/cloud/spanner/value_test.cc
Introduce `google::cloud::spanner::JsonB` for PostgreSQL databases. The interface is the same as `Json` (just a strongly-typed string), but `JsonB` values are stored in the database in a decomposed, binary format, which affects performance: `JsonB` is slower to input, but faster to process as it avoids reparsing.
Note: Support for arrays of `JSONB` will come later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10098)
=> feat(spanner): support for the PG.JSONB data type

google/cloud/internal/async_retry_loop.h, google/cloud/internal/async_retry_loop_test.cc
Capture the current options in creation of the class. (I will consider accepting `Options` in the constructor instead, but I would rather get the fix out first). I will need to do the same thing for the async polling loop. There may be others...
In practice this change only affects `bigtable`, which uses `GrpcSetupOption` to preserve legacy behavior of `bigtable::RPC*Policy::Setup(grpc::ClientContext&)`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10100)
=> fix: configure context in async retries

google/cloud/spanner/integration_tests/data_types_integration_test.cc
It looks like different versions/configs of the backend respond in slightly different ways, so loosen the #10095 workaround expectation. In particular, this accounts for the current state of the staging service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10099)
=> test(spanner): loosen message expectation on column not found

google/cloud/spanner/results.cc, google/cloud/spanner/results.h, google/cloud/spanner/results_test.cc
Soon it will be possible for `Client::ExecuteQuery()` to execute a DML statement (within a read/write transaction) that both modifies and returns data.  So, if the result source behind the `RowStream` can produce `ResultSetStats`, we can return the number of rows that were modified.  Otherwise, for a normal query, return zero.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10102)
=> feat(spanner): add support for RowStream::RowsModified()

google/cloud/spanner/samples/postgresql_samples.cc, google/cloud/spanner/samples/samples.cc
Update some `spanner::SqlStatement` formatting to be consistent between samples.  Also fix the `stream-of` sample to output all the data it queries, with the correct labels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10105)
=> cleanup(spanner): make SQL formatting more consistent

google/cloud/storage/doc/storage-main.dox
This satisfies the most common requests for additional examples.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10107)
=> doc(storage): common initialization examples

ci/cloudbuild/builds/cmake-install.sh, ci/verify_current_targets/CMakeLists.txt, cmake/AddPkgConfig.cmake, google/cloud/pubsub/CMakeLists.txt, google/cloud/pubsub/config-mocks.cmake.in, google/cloud/pubsub/mocks-config.cmake.in
Part of the work for #5782
* Move `google-cloud-cpp::pubsub_mocks` out of `pubsub-targets` and into `pubsub_mocks-targets`.
* **Is this a breaking change?**
* Add a google_cloud_cpp_pubsub_mocks pkg
I have no idea if this works. Or how to test it.
But I can (from the `demo-fedora-pr` docker shell)
```sh
docker:demo-fedora$ ls /h/google-cloud-cpp-installed/lib64/cmake/google_cloud_cpp_pubsub_mocks/
google_cloud_cpp_pubsub_mocks-config-version.cmake  pubsub_mocks-targets.cmake
google_cloud_cpp_pubsub_mocks-config.cmake
```
```sh
docker:demo-fedora$ PKG_CONFIG_PATH="/h/google-cloud-cpp-installed/lib64/pkgconfig:${PKG_CONFIG_PATH:-}"
docker:demo-fedora$ pkg-config --validate google_cloud_cpp_pubsub_mocks
```
of course, `GTest` is not installed on that image, so I don't know what is being …
=> feat(pubsub): install pubsub_mocks pkg

google/cloud/credentials.h, google/cloud/doc/common-main.dox, google/cloud/doc/guac.dox
I created a page for all the authentication components. I also moved some general overview stuff out of the `Credentials` class into the components overview.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10110)
=> doc(common): make authentication docs easier to find

CMakeLists.txt
This will make it easier to add generated files in said directories and then add build scripts for them later.
Part of the work for #10114
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10117)
=> ci: skip sample directories without a CMake file

google/cloud/pubsub/samples/mock_subscriber.cc, google/cloud/pubsub/samples/samples.cc
Allow for `pubsub::Message::data()` to return a type that isn't exactly `std::string`, but is explicitly convertible to it.
Also tweak the bracketing for a `#include`.
Both of these make it easier for a downstream user of the code to adapt it to a different environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10135)
=> impl(pubsub): use the pubsub::PubsubMessageDataType type alias

google/cloud/baremetalsolution/doc/main.dox, google/cloud/beyondcorp/doc/main.dox, google/cloud/optimization/doc/main.dox, google/cloud/run/doc/main.dox, google/cloud/video/doc/main.dox
Doxygen interprets `**` at the beginning of the line as part of a Doxygen comment block.  In these cases we wanted to interpret this as a `**not**`, i.e., bold the word. There may be better solutions, but this is a quick fix to get the formatting right.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10137)
=> doc: workaround Doxygen formatting quirk

google/cloud/pubsub/doc/pubsub-main.dox, google/cloud/pubsub/samples/CMakeLists.txt, google/cloud/pubsub/samples/client_samples.cc, google/cloud/pubsub/samples/pubsub_client_integration_samples.bzl
For each `*Client` class add an examples showing how to override the default endpoint and authentication credentials. Reference these examples from the landing page, as this is one of the most common questions for the client libraries.
Fixes #10133 and fixes #10132
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10136)
=> doc(pubsub): samples for endpoint and auth

google/cloud/google_cloud_cpp_rest_internal.cmake, google/cloud/google_cloud_cpp_rest_protobuf_internal.cmake, google/cloud/storage/google_cloud_cpp_storage.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10148)
=> refactor: make rest internal lib punctuation consistent with other libs

google/cloud/bigtable/CMakeLists.txt, google/cloud/bigtable/doc/bigtable-main.dox, google/cloud/bigtable/examples/CMakeLists.txt, google/cloud/bigtable/examples/bigtable_examples.bzl, google/cloud/bigtable/examples/client_samples.cc
Add examples showing how to override the default endpoint and default authentication.
Fixes #10143 and fixes #10144
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10149)
=> doc(bigtable): add `*Client` samples

google/cloud/bigquery/samples/BUILD.bazel, google/cloud/bigquery/samples/CMakeLists.txt, google/cloud/bigtable/examples/BUILD.bazel, google/cloud/iam/samples/BUILD.bazel, google/cloud/iam/samples/CMakeLists.txt, google/cloud/pubsub/samples/BUILD.bazel, google/cloud/pubsub/samples/CMakeLists.txt, google/cloud/spanner/samples/BUILD.bazel, google/cloud/spanner/samples/CMakeLists.txt, google/cloud/storage/examples/BUILD.bazel
Samples that have their own `main()`, and don't use gtest anyway, should not link with `@com_google_googletest//:gtest_main`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10156)
=> cleanup: eliminate ODR violations in samples

generator/internal/predicate_utils.cc, generator/internal/predicate_utils.h, generator/internal/predicate_utils_test.cc
Necessary to determine if an rpc can be used with REST transport.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10160)
=> impl(generator): add predicate for http annotation

google/cloud/spanner/samples/client_samples.cc
Do not demand that `${GOOGLE_CLOUD_CPP_TEST_SERVICE_ACCOUNT_KEYFILE}` is set when we're running the Spanner client samples against the emulator, as it's value is not used in that case.  This allows the test to be used by the emulator dev team without unnecessary extra requirements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10163)
=> test(spanner): relax environment requirement under emulator

ci/cloudbuild/builds/cmake-install.sh, ci/etc/expected_install_directories, ci/etc/full_feature_list, generator/internal/scaffold_generator.cc, generator/internal/scaffold_generator.h, generator/internal/scaffold_generator_test.cc, generator/standalone_main.cc
I would rather assume that the `product_path` matches `google/cloud/service($|/**)` than assume that it matches `**/service`
(I am sure my regex syntax is wrong, but you get the point)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10171)
=> cleanup(generator): better library name parsing for nested services
